ampproject/amphtml

spec/amp-cache-guidelines.md
=> Cache guidelines include subdomain recommendation

extensions/amp-compare-slider/0.1/amp-compare-slider.js, extensions/amp-position-observer/0.1/amp-position-observer.js
=> Use AMP.extension for declarations

extensions/amp-ad/amp-ad.md
Fixes https://github.com/ampproject/docs/issues/667
cc: @ithinkihaveacat
=> Clarify wording for data-loading-strategy #667

3p/iframe-messaging-client.js, ads/inabox/inabox-messaging-host.js, ads/inabox/position-observer.js, extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js, extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js, src/3p-frame-messaging.js, src/inabox/inabox-viewport.js, src/service/viewport-impl.js, test/functional/3p/test-iframe-messaging-client.js, test/functional/inabox/test-inabox-messaging-host.js, test/functional/inabox/test-inabox-viewport.js, test/functional/test-viewport.js
Implement the 'request-position' API for inabox in AMP or non AMP host. And the logic to protect host from multiple requests within same animation frame. 
under 'inabox-position-api' experiment flag
=> Inabox request position api

extensions/amp-web-push/amp-web-push.md
Improve formatting, wording, and consistency.
=> Improve amp-web-push docs

extensions/amp-bind/0.1/bind-validator.js, extensions/amp-bind/amp-bind.md, validator/validator-main.protoascii
=> Add support for [hidden] to bind and validator

extensions/amp-analytics/amp-analytics.md, extensions/amp-analytics/amp-video-analytics.md
Formal markdown docs for video analytics.
Related to #9902, should be the very last task for it.
=> Formally document video analytics

extensions/amp-timeago/validator-amp-timeago.protoascii
Per conversation on #11123, removing cdata validation.
Will wait for @aghassemi approval before merging.
=> Remove cdata validation from amp-timeago

build-system/app.js, build-system/tasks/presubmit-checks.js, examples/pwa/pwa-ampdoc-shell.html, examples/pwa/pwa.js, src/amp-shadow.js, src/service/ampdoc-impl.js, src/service/extensions-impl.js, test/functional/test-ampdoc.js, test/functional/test-extensions.js
Change proposal to AMP Shadow, so the PWA can benefit from AMP runtime
=> Allows the PWA main document itself to be adopted as an AMP document

spec/amp-actions-and-events.md
Follow-up for #10914.
/to @ericlindley-g
=> Update docs for AMP.setState chaining

src/service/platform-impl.js, test/functional/test-platform.js
Fix https://github.com/ampproject/amphtml/issues/10415
=> Show amp app banner in opera

extensions/amp-ad-network-adsense-impl/0.1/test/test-adsense-a4a-config.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
It's a forbidden API.
/cc @ampproject/a4a.
=> Stop using Object.entries

extensions/amp-viewer-integration/0.1/test/test-touch-handler.js, extensions/amp-viewer-integration/0.1/touch-handler.js, test/_init_tests.js
=> Use a passive event handlers for touch events in viewer messaging when possible.

ads/google/test/test-adsense.js
Address missing unit test coverage for ads/google/adsense.js
=> Add AdSense Delayed Fetch Unit Test Coverage

third_party/caja/README.amp, third_party/caja/html-sanitizer.js
See https://github.com/google/caja/pull/2026
=> Patch from Caja on regex capitalization

validator/CHANGELOG.md
=> Update changelog with validator release

extensions/amp-form/amp-form.md, spec/amp-actions-and-events.md
Follow-up to #10242.
/to @ericlindley-g (while @bpaduch is out)
=> Document valid/invalid form events

.travis.yml
Temporarily fixes #11203, until the root causes are investigated
=> Use older trusty image on Travis due to broken build

extensions/amp-lightbox-viewer/0.1/amp-lightbox-viewer.js
Fix https://github.com/ampproject/amphtml/issues/10391
=> Fix lightbox caption and topbar to be in sync when toggling

extensions/amp-access/0.1/amp-login-done.html, extensions/amp-access/0.1/amp-login-done.js
=> Login done: ensure that AMP services are not invoked

build-system/pr-check.js, build-system/tasks/visual-diff.rb
Follow up to #11196
Context: https://github.com/ampproject/amphtml/pull/11196#discussion_r137643997
=> Verify visual tests after running unit tests

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Related to #7618. Follow-up to #11127.
=> Ramp new signature verifier experiment to 1%

build-system/global-configs/prod-config.json
- No side effects on sidebar from the 1%
=> Launch toolbar to 100%

extensions/amp-lightbox-viewer/0.1/amp-lightbox-viewer.css, extensions/amp-lightbox-viewer/0.1/amp-lightbox-viewer.js
Fix https://github.com/ampproject/amphtml/issues/11103
=> Lightbox: improve ux and add paddingTop to description box

test/manual/amp-animation/scrollbound-inabox.non.amp.html
=> Add scrollbound animation example (inabox non AMP)

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js
=> Allow Fast Fetch from non-HTTPS pages

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Starting 1% experiment from https://github.com/ampproject/amphtml/pull/11063
=> Start 1% experiment for canonical FF support for doubleclick

examples/amp-position-observer.amp.html, extensions/amp-position-observer/amp-position-observer.md
Docs update related to launch: https://github.com/ampproject/amphtml/pull/11259
=> Docs updates for amp-position-observer launch

src/shadow-embed.js
=> childElementsByTag wasn't returning the style tags

extensions/amp-bind/amp-bind.md, spec/amp-actions-and-events.md
Partial for #9128.
/to @ericlindley-g
=> Document AMP.pushState()

build-system/tasks/validator.js
=> Print Jasmine logs during validator tests

extensions/amp-analytics/amp-analytics.md, extensions/amp-analytics/amp-components-analytics.md
Moved from internal doc to GitHub. 
cc @lannka
=> Readme for components to implement analytics

tools/errortracker/errortracker.go
Fixes https://github.com/ampproject/amphtml/pull/11307/files#r139273031
=> Move forwarding below client/log creation

extensions/amp-audio/0.1/test/validator-amp-audio.html, extensions/amp-video/0.1/amp-video.js, extensions/amp-video/0.1/test/test-amp-video.js, extensions/amp-video/amp-video.md, extensions/amp-video/validator-amp-video.protoascii
Closes https://github.com/ampproject/amphtml/issues/11328 
/cc @jessanastasio
=> Propagate controlsList from amp-video to video

extensions/amp-auto-ads/0.1/amp-auto-ads.js, extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
/to @lannka 
/cc @tlong2 
Fixes https://github.com/ampproject/amphtml/issues/11044.
=> Make amp-auto-ads wait for viewer visible

src/service/fixed-layer.js, test/functional/test-fixed-layer.js
Fixes https://github.com/ampproject/amphtml/issues/11340.
=> Detect fixed top-autos with important styles

build-system/pr-check.js, build-system/tasks/lint.js
Finishes what #11341 set out to do
=> Run build system linter only for PRs

spec/amp-css-classes.md, spec/amp-html-format.md
Fixes https://github.com/ampproject/docs/issues/2
=> Add doc on amp-mode classes

extensions/amp-a4a/0.1/amp-a4a.js
Update safeframe version to 1-0-10
=> AMP Ad Fast Fetch: update safeframe version

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Remove client-side experiment from build configs.
=> AdSense Fast Fetch Delay Request experiment cleanup

.gitignore, .travis.yml, build-system/check-package-manager.js, build-system/exec.js, build-system/pr-check.js, contributing/getting-started-e2e.md, contributing/getting-started-quick.md, package.json
=> Enforce the use of yarn for package management

gulpfile.js
=> Fix login-done JS location

extensions/amp-vk/0.1/amp-vk.js
Addressing @jridgewell's comments on #11299
=> amp-vk: assert enum 

ads/google/a4a/performance.js
=> Fix feature-detection bug with performance.now in A4A

examples/visual-tests/pinterest.amp/pinterest.amp.html, test/visual-diff/visual-tests.json
This PR demonstrates the addition of a new visual test.
#10155
=> Add a visual diff test for amp-pinterest

examples/visual-tests/article.amp/article.amp.html, test/visual-diff/visual-tests.json
This should make the visual test for this file less flaky
=> Add wait code for amp.article.html

validator/CHANGELOG.md
=> Updated changelog with recent validator release

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Please cherry pick to production
=> Ramp canonical ff experiment down to 0

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Will hopefully give us a better picture of the metrics.
Related to #7618. Follow-up to #11228.
=> Ramp Fast Fetch crypto verifier experiment to 10%

build-system/amp4test.js, test/integration/test-user-error-reporting.js
=> Unskip user error reporting integration test 

extensions/amp-access/0.1/test/test-amp-access.js, test/functional/test-custom-element.js
=> Enable tests for Chai4

src/url.js, test/functional/test-url.js
Check for 'null' in getWinOrigin
=> Check for 'null' in getWinOrigin

SUPPORT.md
- Needed to change level of indents for 2nd UL so it appears correctly when imported into ampproject.org
- Improved some wording
- Added statement on using SO for implementation questions
=> Amend formatting and wording so it can be rendered in ampproject.org

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
=> Turn Experiment fraction back to 0.01 for Canonical FF experiments for DoubleClick

test/visual-diff/visual-tests.json
=> Skip AMP article visual test

examples/bind/forms.amp.html, src/service/standard-actions-impl.js, test/functional/test-standard-actions.js
=> Fix AMP.setState chaining

test/integration/test-user-error-reporting.js
=> Skip flaky test on safari

spec/amp-shadow-doc.md
=> SD polyfill docs

src/service/performance-impl.js
Chrome's implementation does not yet support reporting on past values.
See
https://bugs.chromium.org/p/chromium/issues/detail?id=725567
The good news is that it appears as if we have only reported on fast loads so far :)
=> Explicitly report past Performance Timineline values.

src/utils/array.js
This changes filterSplice from an O(n^2) alg into an O(n) alg by
mutating updating elements lazily during traversal.
=> Make filterSplice into a O(n) algorithm

extensions/amp-animation/0.1/amp-animation.js
Fixes #11522 
/to @aghassemi @dvoytenko
=> Use ampdoc API to check the tree position of the amp-animation element

examples/amp-list.amp.html, extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/test-amp-list.js, extensions/amp-list/amp-list.md, validator/CHANGELOG.md
=> amp-list: single-result -> single-item to match validation rules

extensions/amp-story/0.1/progress-bar.js, extensions/amp-story/0.1/system-layer.js, extensions/amp-story/0.1/test/test-system-layer.js
From https://github.com/newmuis/amphtml-story/pull/21, https://github.com/newmuis/amphtml-story/pull/26, https://github.com/newmuis/amphtml-story/pull/188
/cc @newmuis
=> Implement system layer components for amp-story

extensions/amp-auto-ads/0.1/test/test-placement.js
fixes https://github.com/ampproject/amphtml/issues/11399
=> Fixing disabled test in extensions/amp-auto-ads/0.1/test/test-placement.js

extensions/amp-analytics/integrating-analytics.md
Per https://github.com/ampproject/docs/issues/713, we want to ensure that when new analytics vendor configurations are added that they also update the corresponding documentation for Analytics Vendors.
=> Update instructions to add vendor to vendor list

build-system/tasks/karma.conf.js, build-system/tasks/runtime-test.js
https://saucelabs.com/blog/need-to-test-your-app-on-ios-11
=> Run integration tests on Sauce Labs iOS 11

build-system/server.js, build-system/tasks/serve.js, package.json, yarn.lock
=> Add --cache option to send caching headers for local resources.

extensions/amp-analytics/0.1/vendors.js
Closes https://github.com/ampproject/amphtml/issues/11406
=> change transport types for top100-analytics

build-system/shorten-license.js, build-system/tasks/compile.js, package.json, yarn.lock
closes https://github.com/ampproject/amphtml/issues/11585
/cc @erwinmombay
=> shorten license text in minified files

spec/amp-html-format.md
"filter" is not blacklisted; updated documentation per https://github.com/ampproject/amphtml/issues/11611#issuecomment-335309380
=> Remove "filter" as blacklisted item

ads/google/a4a/google-data-reporter.js, build-system/dep-check-config.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
Phase 1 PR. Next phase will add additional variables for Make Body Visible, First Contentful Paint, and First Viewport Ready. But those are not existing amp-analytics variables currently.
=> Implements new CSI ping for firstVisibleTime

extensions/amp-social-share/0.1/amp-social-share.css
Closes https://github.com/ampproject/amphtml/issues/11651
=> amp-social-share: Update twitter to match the brand

examples/bind/basic.amp.html, extensions/amp-bind/0.1/bind-validator.js, extensions/amp-bind/0.1/test/test-bind-validator.js, validator/validator-main.protoascii
=> amp-bind: Support ARIA attributes

spec/amp-actions-and-events.md
=> Fix docs for event.valueAsNumber

contributing/building-an-amp-extension.md
Please pick a meaningful title for your pull request using sentence case.
Do not overuse punctuation in the title like `(chore):`. If it is helpful feel free to start with a project name, though, like `ProjectX: Implement some feature`.
Enter a succinct description of what is achieved by the PR. Ideally describe why the change is being made.
Bullet points like
really help with making this more readable.
Fixes/Closes/Related-to #1 (enter issue number, except in rare cases where none exists).
=> Minor sentence fixes

extensions/amp-story/0.1/analytics.js, extensions/amp-story/0.1/test/test-analytics.js
=> Rename amp-story analytics vars

extensions/amp-story/0.1/amp-story-desktop.css, extensions/amp-story/0.1/amp-story.css, extensions/amp-story/0.1/amp-story.js, extensions/amp-story/0.1/background.js, extensions/amp-story/0.1/bookend.js, extensions/amp-story/0.1/share.js, extensions/amp-story/0.1/system-layer.js, extensions/amp-story/0.1/test/test-system-layer.js
Still remaining: bottom bar, final logo display (pending the microdata/ld+json discussions?)
/to @newmuis @alanorozco
=> Initial amphtml pass at amp-story desktop view

extensions/amp-story/0.1/amp-story-desktop.css
=> Add tweaks after UX review

examples/analytics-vendors.amp.html, extensions/amp-analytics/0.1/test/vendor-requests.json, extensions/amp-analytics/0.1/vendors.js
- Add mediarithmics integration in vendor.js of amp-analytics
- Add mediarithmics in amp-analytics examples page
Fixes/Closes/Related-to #11262
=> mediarithmics amp-analytics tag integration

build-system/tasks/presubmit-checks.js, src/impression.js, src/service/viewer-impl.js, test/functional/test-impression.js, test/functional/test-viewer.js
=> Request replaceUrl from viewer

extensions/amp-analytics/amp-video-analytics.md
=> Fix incorrect trigger names in video analytics docs

extensions/amp-analytics/0.1/amp-analytics.js
=> Analytics: Differentiates between element unlayout and page unlayout

extensions/amp-ad-network-adsense-impl/0.1/adsense-a4a-config.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-adsense-a4a-config.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/doubleclick-a4a-config.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-a4a-config.js
Removes AdSense/Doubleclick Fast Fetch holdbacks as well AdSense Delayed request holdback.
=> Remove AdSense/Doubleclick Fast Fetch and AdSense FF Delayed Request holdbacks

extensions/amp-carousel/0.1/base-carousel.js
closes https://github.com/ampproject/amphtml/issues/11709
=> amp-carousel: fix aria labels

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Start at 1%, see https://github.com/ampproject/amphtml/pull/11704
=> Add experiment fraction for unconditioned canonical

examples/brid-player.amp.html, extensions/amp-brid-player/0.1/amp-brid-player.js, extensions/amp-brid-player/0.1/test/validator-amp-brid-player.html, extensions/amp-brid-player/0.1/test/validator-amp-brid-player.out, extensions/amp-brid-player/amp-brid-player.md, extensions/amp-brid-player/validator-amp-brid-player.protoascii
Continuing from #11680 
Outstream unit implementation for amp-brid- player extension.
@aghassemi
=> Outstream unit implementation for amp-brid- player extension

ads/google/a4a/utils.js
Increase length for truncation from 4k to 16k
=> Increase length of google ad urls to 16k

extensions/amp-ad-network-adsense-impl/0.1/adsense-shared-state.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Includes prev_slotnames parameter on AdSense Fast Fetch requests similar to prev_frmts
=> AdSense Fast Fetch include prev_slotnames parameter

extensions/amp-form/0.1/form-validators.js
=> Fix amp-selector error when used with custom validation

extensions/amp-video/0.1/amp-video.js, extensions/amp-video/0.1/test/test-amp-video.js, extensions/amp-video/amp-video.md, extensions/amp-video/validator-amp-video.protoascii
/cc @newmuis might be useful for STAMP.
=> amp-video: propagate disableremoteplayback

extensions/amp-iframe/validator-amp-iframe.protoascii, extensions/amp-story/0.1/test/validator-amp-story-video-error.html, extensions/amp-story/0.1/test/validator-amp-story-video-error.out, extensions/amp-video/validator-amp-video.protoascii, validator/validator-main.protoascii
Fixes #11541 
- amp-iframe allow="geolocation"
- update amp-story rules
=> Validator roll up

build-system/app.js, examples/csp.amp.html
Keep csp consistent on github.
=> Make CSP consistent

build-system/tasks/prepend-global/index.js, build-system/tasks/runtime-test.js, gulpfile.js
Follow up to #11588
Fixes #11763
/to @aghassemi @erwinmombay
=> Use local prod / canary config during gulp build / dist / test

extensions/amp-position-observer/0.1/amp-position-observer.js, test/integration/test-position-observer.js, test/manual/amp-animation/embeds/scrollbound/clock.a4a.html, test/manual/amp-animation/scrollbound-embeds.amp.html, tools/experiments/experiments.js
partial for https://github.com/ampproject/amphtml/issues/10875 `x-config.json` changes needs to wait until this is in prod.
=> amp-position-observer: remove experiment tag

build-system/tasks/visual-diff.rb
Based on my IDE suggestions :)
=> Rubify visual-diff.rb based on the Google style guide

src/service/resources-impl.js, test/functional/test-resources.js
=> Make sure viewport resize triggers documentHeight message

build-system/app.js, examples/csp.amp.html
Issue #11376, allow material design icons cdn.
Validator changes will be in a separate future PR.
=> Add material design icons cdn

src/runtime.js, test/functional/test-runtime.js
=> Enable amp-keyframes in PWA

validator/CHANGELOG.md
=> Validator release

spec/amp-managing-user-state.md
As I was reading this doc, I had a hard time with the table (didn't even know there was a third column), so rearranged and reformatted the content to make the table easier to read.
cc: @rudygalfi
=> Improve table layout for readability

ads/revjet.md, examples/ads.amp.html
=> Add missing quotes

ads/outbrain.md
Update Outbrain amp-embed documentation
- Remove testMode parameter from outbrain.md
=> Update Outbrain amp-embed documentation

gulpfile.js
Follow up to #11588 and #11768 
Fixes #11763
=> Print instructions to switch / remove configs during build / dist

extensions/amp-animation/0.1/amp-animation.js, extensions/amp-animation/0.1/test/test-amp-animation.js, extensions/amp-animation/amp-animation.md, tools/experiments/experiments.js
=> Retire amp-animation experiment from code

spec/amp-html-format.md, validator/validator-main.protoascii
=> Keyframes documentation

extensions/amp-a4a/amp-a4a-format.md, extensions/amp-position-observer/validator-amp-position-observer.protoascii, validator/engine/validator_test.js
/to @honeybadgerdontcare 
/cc @ampproject/a4a
=> whitelist amp-position-observer for A4A

extensions/amp-access-laterpay/0.1/laterpay-impl.js, extensions/amp-access-laterpay/0.1/test/test-amp-access-laterpay.js, extensions/amp-access-laterpay/amp-access-laterpay.md
This pull request adds support for using LaterPay with our US region servers, and to eventually add support for more regions in the future.
=> Support for US LaterPay region

extensions/amp-ad/amp-ad.md
Updating the presence of amp-ima-video
=> Update video ad serving documentation

extensions/amp-apester-media/0.1/amp-apester-media.js
Closes https://github.com/ampproject/amphtml/issues/11338
=> amp-apester: null check

validator/validator-main.protoascii
=> Validator: allow "fr" attribute for radialGradient SVG tag 

extensions/amp-story/0.1/amp-story.js, extensions/amp-story/0.1/test/test-amp-story.js
Fixes #11641
- Adds overflow hidden for html and body
=> Prevent overscroll for amp-story

css/amp.css, src/friendly-iframe-embed.js, test/functional/test-friendly-iframe-embed.js
Apply the same style to FIE as of inabox.
=> Apply correct style to embed doc html

src/intersection-observer-polyfill.js, test/functional/test-intersection-observer-polyfill.js
=> InOb should accept threshold with single number

spec/amp-actions-and-events.md
In my opinion it looks slightly better, though still not perfect.
=> Improve readability

src/error.js, test/functional/test-error.js
=> POST error messages to reporting server

extensions/amp-dynamic-css-classes/amp-dynamic-css-classes.md
Add reference to ABE's example for this component.
=> Add ABE example to doc

spec/amp-actions-and-events.md
Cleaned up the formatting of the doc so that when I have the ampproject site import it, it renders correctly.
=> Doc cleanup so can be imported to ampproject site

validator/nodejs/index.js
Support experimental html formats for developers producing their own validator builds.
=> Support experimental html formats in npm validator.

extensions/amp-story/0.1/amp-story.js, tools/experiments/experiments.js
Fixes #11974.
/to @alanorozco @prateekbh
=> amp-story: Flag auto fullscreen

src/service/cid-impl.js, test/functional/test-cid.js
Attempt to fix #11888 and #11628 
This is my best guess...
=> Wait for viewer visible before sending cid request

extensions/amp-story/amp-story.md
Fixes #12003.
Quick fix. Follow-up PR for social share/more details upcoming.
=> Documentation fix for bookend spec

extensions/amp-story/0.1/amp-story.js, extensions/amp-story/0.1/test/test-amp-story.js
Adds event listeners for next previous buttons on desktop and test for it. 
=> Fixes next/previous buttons on desktop

extensions/amp-ad-network-doubleclick-impl/doubleclick-rtc.md
Add Real Time Config documentation for doubleclick fast fetch
=> Add RTC Documentation for Doubleclick

extensions/amp-story/0.1/amp-story-desktop.css
Fixes the border-radius for desktop mode on STAMP
=> rounded progress bars

extensions/amp-story/0.1/amp-story-desktop.css
=> Enforces inactive pages offscreen

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Add fraction for https://github.com/ampproject/amphtml/pull/12037 
Also fix fraction for https://github.com/ampproject/amphtml/pull/11883
=> Add fraction for canonical holdback, fix fractions for identity exp

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/requests.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js, extensions/amp-analytics/0.1/test/test-requests.js, extensions/amp-analytics/0.1/test/test-variables.js, extensions/amp-analytics/0.1/variables.js, test/manual/analytics-batching.amp.html
First step for #11241 
Each request becomes an instance from a pure string, I refactored a bit to move requestHandler to its own class. 
cc @pomeroyr @avimehta
=> Analytics requests-v2 to support basic batching features

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Check:  https://travis-ci.org/ampproject/amphtml/jobs/302151724
follow up to #12057
=> Fix red master

src/service/cid-impl.js
=> Trace request cid fail doc not visible error

extensions/amp-youtube/0.1/amp-youtube.js
Closes https://github.com/ampproject/amphtml/issues/12063
=> amp-youtube: fix a race where unlayout is called before load finishes

extensions/amp-story/0.1/amp-story.css, extensions/amp-story/0.1/amp-story.js, extensions/amp-story/0.1/bookend.js, extensions/amp-story/0.1/system-layer.js, extensions/amp-story/0.1/test/test-system-layer.js, src/transition.js
=> Bookend interaction changes

validator/validator-main.protoascii
closes https://github.com/ampproject/amphtml/issues/12096
=> validator: add aria-current

ads/adfox.js, ads/yandex.js, ads/yandex.md
- Added new callback `onRender`
- Changed `onError` logic
=> Added onRender and improve onError callbacks in Yandex and Adfox ads

extensions/amp-story/0.1/amp-story-hint.css, extensions/amp-story/0.1/amp-story-hint.js
Some minor fixes in education system animation as discussed with Hong.
=> Minor animation fixes

extensions/amp-story/0.1/amp-story.css, extensions/amp-story/0.1/bookend.js
Presentation was previously broken (i.e., icon not being displayed, image pushing other elements down).
=> Presentation fix for replay button when story has image

extensions/amp-story/0.1/amp-story.css
- Centered experiment alert text
=> Nit styling fix for amp-story experimental

extensions/amp-story/0.1/amp-story.css
Rendering strategy changed on #12021, which means margins need to change.
=> Fix bottom margin for bookend article set

package.json, yarn.lock
Tested locally, and this works on mac os and linux.
Partial fix for #12181 
Partial fix for #12157
=> Update version of eslint

extensions/amp-story/0.1/amp-story-desktop.css, extensions/amp-story/0.1/amp-story.css
Specifically:
- Full size rendering with margins.
- Share widget hidden.
- Multi-column.
=> Basic styling of bookend for desktop

extensions/amp-analytics/0.1/test/test-visibility-model.js, extensions/amp-analytics/0.1/visibility-manager.js, extensions/amp-analytics/0.1/visibility-model.js, test/manual/amp-analytics-visible-reset.amp.html
For #11987 
update doc in separate PR.
=> Analytics enable reset visible event

extensions/amp-analytics/amp-video-analytics.md
There was missing missing character (,) which causes JSON error in sending analytics.
Please pick a meaningful title for your pull request using sentence case.
Do not overuse punctuation in the title like `(chore):`. If it is helpful feel free to start with a project name, though, like `ProjectX: Implement some feature`.
Enter a succinct description of what is achieved by the PR. Ideally describe why the change is being made.
Bullet points like
really help with making this more readable.
Fixes/Closes/Related-to #1 (enter issue number, except in rare cases where none exists).
=> updated description file for Amp Video Analytics

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js
Create iframe within amp-ads for inabox
- create iframe within the amp-ads if inabox
- add tests
=> Create iframe within amp-ads for inabox

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js
=> Pass reference to window in amp-analytics `inabox` check

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/iframe-transport.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js, extensions/amp-analytics/0.1/test/test-iframe-transport.js
Add preconnectCallback to preload iframe-transport-client-lib.js for amp-analytics
=> Preload iframe-transport-client-lib.js for amp-analytics

extensions/amp-analytics/0.1/test/test-visibility-model.js, extensions/amp-analytics/0.1/visibility-model.js, test/manual/amp-analytics-visible-repeat.amp.html
Renames "reset" to "repeat".
Subsequent work in a separate PR will tweak the logic of repeat.
=> InOb Repeat

validator/CHANGELOG.md
Also adding some newlines to make things easier to read.
=> Add release notes for this validator release and previous.

extensions/amp-lightbox-viewer/0.1/amp-lightbox-viewer.js, src/image-viewer.js
Adds swipe up to close. This should be the final PR necessary to functionally complete https://github.com/ampproject/amphtml/issues/9977. 
Tested on desktop / android chrome.
=> Lightbox 2.0: swipe to close

test/manual/amp-lightbox-viewer-demo.amp.html
Pretty blog-style demo for Lightbox UX Review (https://github.com/ampproject/amphtml/issues/12288).
=> Lightbox 2.0: prettified demo

test/functional/test-amp-img.js, test/functional/test-url-replacements.js
/to @aghassemi 
/cc @choumx @lannka
=> Skip flaky tests to unblock PRs. Unskip issue #12336

src/form-data-wrapper.js, src/service/xhr-impl.js
=> Fix regression caused by #12084

extensions/amp-story/amp-story.md
Just spotted a typo and propose a quick edit.
=> Fix typo in amp-story.md

extensions/amp-ad-network-doubleclick-impl/doubleclick-rtc.md
Added new option for Doubleclick RTC, see https://github.com/ampproject/amphtml/pull/12281
Updated the Doubleclick RTC docs to reflect this.
=> Update doubleclick RTC doc to reflect new option

spec/amp-var-substitutions.md
Closes https://github.com/ampproject/amphtml/issues/12319
=> variable-substitution: TIMESTAMP, seconds -> milliseconds

extensions/amp-analytics/0.1/requests.js, extensions/amp-analytics/0.1/test/test-requests.js
=> Fix a double encoding issue in extraUrlParams.

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/test/test-visibility-manager.js, extensions/amp-analytics/0.1/test/test-visibility-model.js, extensions/amp-analytics/0.1/visibility-manager.js, extensions/amp-analytics/0.1/visibility-model.js, test/manual/amp-analytics-visible-repeat.amp.html
See discussion comments at the bottom of #11987
=> Make repeat be boolean-only, not boolean or int

ads/gumgum.js
Adding placement attribute, 'pl, to our slot placement element - to be sent to ad server for amp.
=> Adding placement attribute to our slot placement element

src/service/viewer-impl.js, test/functional/test-viewer.js
=> Revert temporary fix for the TrustedViewer issue caused by missing appropriate handshake

extensions/amp-bind/0.1/bind-impl.js, extensions/amp-bind/0.1/test/integration/test-bind-impl.js, src/json.js
=> Fix AMP.pushState() bug for nested objects

extensions/amp-story/0.1/amp-story-desktop.css
Makes it look a little better.
=> Center blurred background

ads/_config.js, ads/mediavine.js, ads/mediavine.md, examples/ads.amp.html
- Updates url to point to newer Mediavine assets
=> Update Mediavine script url

extensions/amp-story/0.1/amp-story-page.js, extensions/amp-story/0.1/amp-story.css, extensions/amp-story/0.1/amp-story.js, extensions/amp-story/0.1/bookend.js
1. Changes styling: typography sizes, colors, dimensions.
2. Blurs active page when visible.
3. Pauses/restarts page on show/hide bookend.
4. Fixes a bug in which authors could accidentally override text-align.
5. Removes close button. Bookend closes when tapping outside usable area.
6. Removes `:after` multi-column workaround (not required with max-width breakpoints).
7. Fixes replay.
=> Bookend UI changes

extensions/amp-iframe/amp-iframe.md
Fixes a dead link to intersection observer doc
=> fix dead IntersectionObserver  link in amp-iframe.md

spec/amp-cors-requests.md
Improve CORS guide with Example walkthrough section + Testing section.
Fixes: https://github.com/ampproject/amphtml/issues/12089
=> Add example & testing sections to CORS guide

extensions/amp-animation/0.1/amp-animation.js, extensions/amp-animation/0.1/web-animation-service.js, extensions/amp-animation/0.1/web-animations-polyfill.js
Fixes animations not running on Safari.
=> Ensure WebAnimation polyfill is installed for amp-story

extensions/amp-story/0.1/amp-story.css
Fixes bug causing that in some cases, pages will fly-in from the bottom or diagonally.
=> Fix page transition on desktop

extensions/amp-story/0.1/amp-story-hint.css, extensions/amp-story/0.1/amp-story-hint.js, extensions/amp-story/0.1/test/test-amp-story-hint.js
- Simplifies hide/show/timeout lifecycle.
- Some code style changes/refactor.
=> Simplify AmpStoryHint (fixes repaint issue)

extensions/amp-analytics/amp-analytics.md, extensions/amp-analytics/integrating-analytics.md, extensions/amp-analytics/why-not-iframe.md
=> Iframe transport documentation

SUPPORT.md
Added link and info to AMP's status page: https://status.ampproject.org/
=> Added info & link to status page

extensions/amp-ad/validator-amp-ad.protoascii, validator/testdata/feature_tests/ads.html
Whitelist rtc-config parameter for amp-ad introduced in #11607
=> Validator: rtc-config parameter for amp-ad

examples/bind/macros.amp.html, extensions/amp-bind/0.1/amp-bind-macro.js, extensions/amp-bind/0.1/bind-evaluator.js, extensions/amp-bind/0.1/bind-expression.js, extensions/amp-bind/0.1/bind-impl.js, extensions/amp-bind/0.1/bind-macro.js, extensions/amp-bind/0.1/test/test-bind-evaluator.js, extensions/amp-bind/0.1/test/test-bind-expression.js
- Fix cycle/recursions in amp-bind-macro w/ tests
- Add macros.amp.html test page
- Other minor fixes
/to @jridgewell @josh313
=> amp-bind-macro: Fix recursion bug and style fixes

src/service/cid-impl.js
=> Print expected errors when deprecated Viewer CID API is being used.

validator/gulpjs/README.md, validator/gulpjs/package.json
=> bump gulp-amphtml-validator version to 1.0.2

validator/validator-main.protoascii
=> Allow crossorigin on link tags

extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
=> Fix and unskip amp-sidebar tests

extensions/amp-story/0.1/amp-story-desktop.css, extensions/amp-story/0.1/amp-story.js
- Hides bookend background.
- Hides pages/system layer and darkens background when bookend is active.
=> Enter bookend transition for desktop

extensions/amp-image-lightbox/0.1/amp-image-lightbox.js, extensions/amp-image-lightbox/0.1/test/test-amp-image-lightbox.js
=> Return amp-image-lightbox focus to source element after close

test/functional/test-resources.js
master is red due to a failure to use a `sinon` sandbox. https://travis-ci.org/ampproject/amphtml/jobs/319396580
This PR fixes that.
=> Fix unit test failure on master by using a sinon sandbox

extensions/amp-story/0.1/amp-story.css
1. Style for big screens
2. Fix animation.
=> Update toast styling

extensions/amp-story/0.1/bookend.js
=> Use correct JSON-LD field for story title

extensions/amp-story/0.1/animation.js, extensions/amp-story/0.1/utils.js
=> Calculates animation rectangles without applying scaling transformation

ads/README.md
small typo in the email address
=> update README.md typo

src/service/layers-impl.js
Fixes https://github.com/ampproject/amphtml/issues/12553
=> Layers: Implement Disposable interface

extensions/amp-ad-exit/amp-ad-exit.md
=> Fix commas

css/amp.css, extensions/amp-carousel/0.1/base-carousel.js, testing/test-helper.js
Fixes #7975
It's a lightweight solution that fixes the bug. If we'd like more rigorous control over the positioning of the elements we can accomplish that in a follow up PR.
/to @aghassemi 
/cc @cathyxz @calebcordry
=> Use simple a11y class and offset.

extensions/amp-a4a/0.1/callout-vendors.js
Adding media.net as vendor for amp rtc
=> Register medianet as a vendor for AMP RTC

extensions/amp-analytics/0.1/visibility-model.js
Change `dev().warn()` to `dev().error()` to verify the fix.
=> Track analytics visibility model error

CONTRIBUTING.md
Changes documentation to reflect new Status Update label.  These issues are no longer weekly.
=> Changes documentation to reflect new Status Update label

build-system/tasks/process-github-issues.js
Changes the "Weekly Status" label to "Status Update" (since they are no longer weekly).
=> Change the "Weekly Status" label to "Status Update" (since they are no longer weekly)

src/service/cid-api.js, src/service/cid-impl.js, src/service/viewer-cid-api.js, test/functional/test-cid-api.js, test/functional/test-cid.js, test/functional/test-viewer-cid-api.js
=> Add canonicalOrigin support to the CID API.

extensions/amp-date-picker/0.1/dates-list.js, extensions/amp-date-picker/0.1/react-utils.js, extensions/amp-date-picker/0.1/test/test-dates-list.js
First round of tests for the date picker.
=> Add tests for dates-list.js

validator/engine/validator.js
Click [here](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4ffa41ed08b90f7efe/files/validator/engine/validator.js?sort=name&dir=ASC&mode=heatmap&excluded=false#L4405) for the alerts
Introduced [here](https://lgtm.com/projects/g/ampproject/amphtml/rev/a31fac1dacb64e0805dbafc8d46185586bea4892)
Partial fix for #12597
=> Fix LGTM alerts in validator.js

validator/engine/htmlparser.js
=> Fix lgtm errors in htmlparser.js

src/service/layers-impl.js, src/service/resource.js, src/service/url-replacements-impl.js, src/service/vsync-impl.js
Fixes the following LGTM errors:
- [src/service/layers-impl.js#L305](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4ffa41ed08b90f7efe/files/src/service/layers-impl.js?sort=name&dir=ASC&mode=heatmap&excluded=false#L305)
- [src/service/resource.js#L686](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4ffa41ed08b90f7efe/files/src/service/resource.js?sort=name&dir=ASC&mode=heatmap&excluded=false#L686)
- [src/service/resource.js#L478](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4ffa41ed08b90f7efe/files/src/service/resource.js?sort=name&dir=ASC&mode=heatmap&excluded=false#L478)
- [src/service/url-replacements-impl.js#L248](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4 …
=> Fix LGTM errors in src/service/

src/service/cid-impl.js, test/functional/test-cid.js
Verified #11888 has been fixed. 
Clean up and closes #11888
=> Clean up error tracker for document not visible

src/error.js
Fixes the following LGTM error:
- [src/error.js#L420](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4ffa41ed08b90f7efe/files/src/error.js?sort=name&dir=ASC&mode=heatmap&excluded=false#L420)
Partial fix for #12597
=> Fix LGTM errors in error.js

3p/3p.js, 3p/environment.js, src/3p-frame.js
Fixes the following LGTM errors:
- [src/3p-frame.js#L302](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4ffa41ed08b90f7efe/files/src/3p-frame.js?sort=name&dir=ASC&mode=heatmap&excluded=false#L302)
- [3p/3p.js#L152](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4ffa41ed08b90f7efe/files/3p/3p.js?sort=name&dir=ASC&mode=heatmap&excluded=false#L152)
Suppresses this LGTM error:
- [3p/environment.js#L196](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4ffa41ed08b90f7efe/files/3p/environment.js?sort=name&dir=ASC&mode=heatmap&excluded=false#L196)
Partial fix for #12597
=> Fix LGTM errors in 3p code

examples/ads.amp.html, examples/forms.amp.html, examples/gfycat.amp.html, examples/ima-video.amp.html
Fixes the following LGTM errors:
- [examples/gfycat.amp.html#L28](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4ffa41ed08b90f7efe/files/examples/gfycat.amp.html#L28)
- [examples/ima-video.amp.html#L31](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4ffa41ed08b90f7efe/files/examples/ima-video.amp.html?sort=name&dir=ASC&mode=heatmap&excluded=false#L31)
- [examples/forms.amp.html#L259](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4ffa41ed08b90f7efe/files/examples/forms.amp.html?sort=name&dir=ASC&mode=heatmap&excluded=false#L259)
- [examples/forms.amp.html#L323](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/a4d5dedaa4349a630d64ac4ffa41ed08b90f7efe/files/examples/forms.amp.html?sort=name&d …
=> Fix LGTM errors in examples/

extensions/amp-carousel/0.1/slidescroll.js
(Did a bit of code quality work on the method.)
=> Trigger slidechange event from dynamic calls

extensions/amp-story/0.1/share.js
=> Load amp-social-share when system share is supported

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js
=> Only preload iframe transport client lib if needed

extensions/amp-analytics/0.1/amp-analytics.js
=> Remove ampcors check when fetching analytics remote config

extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-rtc.js
Incorrectly was using data-json instead of json.
=> Fix macros for RTC Doubleclick

extensions/amp-story/0.1/amp-story-hint.css
This fixes the poorly positioned animating circles on some education layers
=> fix animating circle fixed position

src/service/cid-api.js
=> Print CID API error response to browser console.

spec/amp-html-format.md
Typekit now supports CSS Loading 🙌 
- Add example of how to use Typekit
Related to https://github.com/ampproject/amphtml/issues/2820
=> Add instructions for using Typekit

extensions/amp-a4a/amp-a4a-format.md
https://github.com/ampproject/amphtml/issues/7846#issuecomment-332569254
Please pick a meaningful title for your pull request using sentence case.
Do not overuse punctuation in the title like `(chore):`. If it is helpful feel free to start with a project name, though, like `ProjectX: Implement some feature`.
Enter a succinct description of what is achieved by the PR. Ideally describe why the change is being made.
Bullet points like
really help with making this more readable.
Fixes/Closes/Related-to #1 (enter issue number, except in rare cases where none exists).
=> Update the a4a spec to require amp-animation based on https://github.com/ampproject/amphtml/issues/7846#issuecomment-332569254

extensions/amp-lightbox-viewer/0.1/amp-lightbox-viewer.css
Closes https://github.com/ampproject/amphtml/issues/12581
Use media queries and css grid layout to make the gallery responsive. 
iPad
iPhone 4
Desktop
=> Add media queries with css grid layout to ensure responsive gallery

extensions/amp-analytics/amp-analytics.md
The feature has been out for a while. Add documentation.
=> Documentation to analytics basic batching support

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/batching-plugins.js, extensions/amp-analytics/0.1/requests.js, extensions/amp-analytics/0.1/test/test-requests.js, test/manual/analytics-batching.amp.html
=> Analytics: add batching plugin support

extensions/amp-ad/validator-amp-ad.protoascii, extensions/amp-anim/validator-amp-anim.protoascii, extensions/amp-carousel/validator-amp-carousel.protoascii, extensions/amp-fit-text/validator-amp-fit-text.protoascii, extensions/amp-iframe/validator-amp-iframe.protoascii, extensions/amp-story/0.1/test/validator-amp-story-video-error.out, extensions/amp-twitter/validator-amp-twitter.protoascii, validator/build.py, validator/engine/validator.js, validator/engine/validator_test.js, validator/testdata/feature_tests/amp_layouts.html, validator/testdata/feature_tests/amp_layouts.out, validator/testdata/feature_tests/noscript.out, validator/validator-main.protoascii, validator/validator.proto
Release Notes:
- Prefer sets of errors based on specificity over volume.
- INTRINSIC layout.
- HtmlFormat.Code enum.
=> Sync GitHub 20180122

build-system/dep-check-config.js, examples/wistiaplayer.amp.html, extensions/amp-wistia-player/0.1/amp-wistia-player.js, extensions/amp-wistia-player/0.1/test/test-amp-wistia-player.js, extensions/amp-wistia-player/amp-wistia-player.md, extensions/amp-wistia-player/validator-amp-wistia-player.protoascii, gulpfile.js
=> Add amp-wistia-player in order to load Wistia videos

extensions/amp-sticky-ad/1.0/amp-sticky-ad.js, extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
delay adding to fix layer by after dom mutation. 
Fix the error `Error: Tried to add display:none element to FixedLayer AMP-STICKY-AD`
=> Delay adding sticky-ad to fix layer

extensions/amp-lightbox-viewer/0.1/amp-lightbox-viewer.js
Addresses https://github.com/ampproject/amphtml/issues/12932.
=> Tweak animations not to show carousel too early

css/amp.css
=> Only show initial load screen for embedded AMP case

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
/cc @jasti 
Launching the experiment even before #13010 makes it to prod.
=> launch amp-ima-video through a flag flip

extensions/amp-analytics/0.1/amp-analytics.js
temporary fix to #13005 
Revert #12787 to patch the fix to prod. The real fix should be #13009
=> Revert 12787

extensions/amp-story/amp-story.md
This amp-story example fragment no longer validates. Make some minimal changes so that it does.
/cc @newmuis
=> Make amp-story example validate

extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/test-amp-list.js
Fixes #13007.
- Verified this fixes the bug on https://amp-live-list-form.glitch.me/amp-list-src.html
=> Fix amp-list fails to fetch when hidden

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/requests.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js, extensions/amp-analytics/0.1/test/test-requests.js
A prerequisites to support `batchInterval` : )
The promise is not used anywhere except in tests.
=> Analytics: refactor remove unused promise

test/functional/test-url-replacements.js
Fixes test flake introduced by https://github.com/ampproject/amphtml/pull/12914.
=> Fix test flake in test-url-replacements

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
=> Launch "ampcontext" API migration to 10%

extensions/amp-lightbox-viewer/0.1/amp-lightbox-viewer.css
Update lightbox icons per latest designs.
=> Update lightbox icons

extensions/amp-bind/0.1/bind-validator.js, extensions/amp-bind/0.1/test/test-bind-validator.js, extensions/amp-selector/0.1/test/validator-amp-selector.html, extensions/amp-selector/0.1/test/validator-amp-selector.out, extensions/amp-selector/validator-amp-selector.protoascii
Fixes #13020.
/to @alabiaga /cc @honeybadgerdontcare FYI validator change.
=> Allow binding to amp-selector[disabled]

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-signature-verifier.js, extensions/amp-access/0.1/jwt.js, extensions/amp-ad-network-adzerk-impl/0.1/amp-ad-network-adzerk-impl.js, extensions/amp-ad-network-adzerk-impl/0.1/test/test-amp-ad-network-adzerk-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js, extensions/amp-iframe/0.1/amp-iframe.js, src/service/crypto-impl.js, src/service/xhr-impl.js, src/utils/bytes.js, test/functional/utils/test-base64.js, test/functional/utils/test-bytes.js
Fixes/Closes/Related-to #12870
=> deprecate utf8Encode and utf8Decode async calls and rename methods

extensions/amp-position-observer/0.1/amp-position-observer.js
Fixes https://github.com/ampproject/amphtml/issues/12799
=> scrollbound animations: fix jumps caused by mobile browsers' addressbar changing the viewport height

test/manual/article-with-lightbox-2.0-gallery.amp.html
Tiny fixes to the lightbox demo article itself.
=> Remove broken image and reassign image to own gallery

css/amp.css, extensions/amp-story/0.1/amp-story.css
=> Remove white loading screen and AMP default loading dots

validator/CHANGELOG.md
Includes latest release details.
=> Update CHANGELOG with validator release details

test/manual/amp-animation/scrollbound-embeds.amp.html
=> Add note to scrollbound animation test page

extensions/amp-lightbox-viewer/0.1/amp-lightbox-viewer.css
Incorporating feedback from today's UX session. 
- Reorder buttons (the close button is on the wrong side). 
- Adjust gradients downward to 0.3 max for buttons and 0.5 max for text description. 
- Use a media query for adapting to larger button icons and margins when we switch to desktop mode at 1024 px.
=> Lightbox UX polish round 2

extensions/amp-image-viewer/0.1/amp-image-viewer.js
A port of https://github.com/ampproject/amphtml/pull/12636. Closes #12580.
=> Adjust max scale to fit screen

extensions/amp-a4a/0.1/amp-ad-templates.js, extensions/amp-ad-network-adzerk-impl/0.1/data/0
=> AdZerk local demo: use template on AMP cache

extensions/amp-story/0.1/utils.js
=> Prevent NaN when calculating unscaled client rect

extensions/amp-bind/amp-bind.md
=> Minor fixes to amp-bind-macro docs

extensions/amp-story/0.1/amp-story.css, extensions/amp-story/0.1/amp-story.js, extensions/amp-story/0.1/bookend.js
Bonus: Using `amp-img`.
Fixes #12918
=> Hide brokend bookend images

extensions/amp-ad/0.1/amp-ad.js, extensions/amp-ad/0.1/test/test-amp-ad-custom.js, tools/experiments/experiments.js
=> Remove ad-type-custom feature flag.

extensions/amp-ad/0.1/amp-ad-custom.js, test/manual/amp-ad.custom.amp.html
=> <amp-ad type=custom>: allow defining template via the "template" attribute

extensions/amp-user-notification/amp-user-notification.md
Code block was not terminated.
=> Fix amp-user-notification docs issue

extensions/amp-mathml/amp-mathml.md
=> Minor fixes

extensions/amp-ima-video/amp-ima-video.md
=> Minor wording update

extensions/amp-riddle-quiz/amp-riddle-quiz.md
Fixed script link + improved wording (as it'll be imported into ampproject.org)
=> Correcting & Improving doc

gulpfile.js
Documentation that's visible during use is best documentation.
Follow up to #13203
=> Document usage of --noextensions and --extensions

extensions/amp-youtube/0.1/amp-youtube.js
Detected with [black magic](https://github.com/ampproject/amphtml/pull/13223).
=> Display youtube placeholder in mutate phase

examples/amp-story/bookend.html, examples/amp-story/bookend.json, extensions/amp-story/0.1/amp-story.css
We will now scale instead of stretch.
Fixes #13115.
=> Fix bookend image aspect scaling

extensions/amp-story/amp-story-analytics.md
=> Adding amp-story-analytics

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js
=> Fix bug: #HandleRequestForEvent_ return with user error

extensions/amp-carousel/0.1/amp-carousel.css, extensions/amp-carousel/0.1/slidescroll.js
Partially fixes - https://github.com/ampproject/amphtml/issues/11537
=> Fix for broken snapping on IOS for slides

test/manual/article-with-lightbox-2.0-gallery.amp.html
=> Hand icon for all lightboxed images

extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Not all images have an exit transition.
=> Lightbox: only apply ghost to images going through transitions

caches.json
=> Add cloudflare to caches.json

extensions/amp-list/0.1/amp-list.js
/to @danielrozenberg @alabiaga
=> Change [state] usage from warning to error

package.json, yarn.lock
Reverts ampproject/amphtml#13333
=> Revert "Update browserify to the latest version 🚀"

package.json, yarn.lock
Reverts ampproject/amphtml#13347 since it turned out to be unrelated to  the `master` redness being discussed in #13351
=> Revert "Revert "Update browserify to the latest version 🚀""

extensions/amp-story/0.1/amp-story.css
Bug introduced by https://github.com/ampproject/amphtml/commit/2469a858d3d1e398b5a64fc5acf7a585f069c4f0
Fixes #13334
=> Fixing pointer-events on system layer buttons.

ads/google/doubleclick.md
Link no longer goes anywhere, remove.
=> Delete dead link

extensions/amp-story/amp-story-auto-ads.md
=> Update amp-story-auto-ads spec

extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
=> amp-lightbox-gallery: rescan when needed to support amp-list and friends

test/visual-diff/visual-tests.json
Fixes #10377
Fixes #11496
Partial fix for #13351
=> 🏗️✅ Re-enable old visual diff tests now that we're using chrome

extensions/amp-story/0.1/test/test-amp-story.js
📖
- Changes comments to point at an issue.
=> Fixes comments to point at a GH issue.

extensions/amp-a4a/amp-a4a-format.md, extensions/amp-mustache/validator-amp-mustache.protoascii, validator/engine/validator_test.js, validator/testdata/amp4ads_feature_tests/extensions.out
=> Allow amp-mustache in a4a

extensions/amp-story/amp-story.md
=> Add whitelist signup docs to amp-story.md

build-system/conformance-config.textproto, build-system/tasks/presubmit-checks.js
=> :recycle: :building_construction: Move cookie/getCookie/setCookie restrictions to conformance-config.textproto

extensions/amp-story/amp-story.md
Added links to resources on AMP By Example and other docs.
cc: @sebastianbenz
=> Add links to other story resources

css/amp.css, extensions/amp-subscriptions/0.1/amp-subscriptions.css, extensions/amp-subscriptions/0.1/amp-subscriptions.js, extensions/amp-subscriptions/0.1/renderer.js, extensions/amp-subscriptions/0.1/test/test-renderer.js
The intent with the `Render` class is to eventually provide the method `render(state|entitlements|???)`. This method will be called once entitlements have been resolved and it will translate the state/entitlements and call `setGrantState_`, `setLoginState_`, etc internally.
=> Subscriptions renderer

extensions/amp-byside-content/amp-byside-content.md, extensions/amp-facebook-page/amp-facebook-page.md, extensions/amp-fx-collection/amp-fx-collection.md
Clean up docs for new components so they are consistent and render correctly in ampproject.org.
=> Clean up docs for new components

extensions/amp-image-viewer/0.1/amp-image-viewer.js
Closes https://github.com/ampproject/amphtml/issues/13532.
=> <amp-image-viewer> move mutation out of measure into mutate

extensions/amp-reach-player/0.1/amp-reach-player.js
Fixes https://github.com/ampproject/amphtml/issues/13539
=> amp-reach-player: Allow fullscreen

test/integration/test-video-players-helper.js, test/integration/test-video-players.js
Fixes #10283, #10974 (hopefully)
Related-to #13566
Will keep an eye on master to make sure unskipping these doesn't flake.
/to @aghassemi 
/cc @rsimha
=> Skip 3q video tests due to service instability. Unskip integration tests

css/amp.css, examples/amp-story-auto-ads.amp.html, extensions/amp-story/0.1/amp-story-auto-ads.js, extensions/amp-story/0.1/amp-story-page.js, extensions/amp-story/0.1/amp-story.js, extensions/amp-story/notes.md
This is a continuation of the implementation of `story-auto-ads`. It now will show/hide ads in the right places. Still much more to come.
to/ @newmuis @alanorozco 
I am trying to keep everything seperate, but I made a few minor changes to `amp-story.js` & one in `amp-story-page.js`. Please let me know if there is anything that may be problematic, or if you can think of a better way.
=> ✨ amp-story-auto-ads showing in the right places

extensions/amp-bind/0.1/bind-evaluator.js, extensions/amp-bind/0.1/bind-impl.js
=> Report errors from BindEvaluator.addMacros()

extensions/amp-carousel/0.1/slidescroll.js, test/manual/amp-slidescroll.amp.html, tools/experiments/experiments.js
Partial for https://github.com/ampproject/amphtml/issues/8195
=> amp-carousel: First phase of cleaning up snap experiment

examples/amp-story-auto-ads-payload.json, examples/amp-story-auto-ads.amp.html, extensions/amp-story/0.1/amp-story-auto-ads.js
`auto-story-ads` will now read publisher defined config and render using a custom ad template.
=> ✨Use template ads for `auto-story-ads`

extensions/amp-access/0.1/amp-access-source.js, extensions/amp-access/0.1/amp-access.js
This bug was introduced in #12353. Now, when a given source
completes authorization, the callback will both broadcast
reauthorize and queue up a rerender of root.
=> 🐛Fix failure to reauthorize on login in amp-access

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/real-time-config-manager.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-a4a/0.1/test/test-real-time-config-manager.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
See most recent requests https://github.com/ampproject/amphtml/issues/12374
Adding CANONICAL_URL and TIMEOUT
=> Add two new custom macros for RTC

extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css, extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js, test/manual/amp-lightbox-gallery-launch.amp.html
This PR separates out manual launch tests by category and adds new tests for ads
=> Refactor lightbox launch tests

extensions/amp-playbuzz/0.1/amp-playbuzz.css
1. Style-fix: "Show More" button will be returned to the bottom
2. Style-fix: button cursor will be pointer
#13661
=> fix(overflow): "Show More" button position should be in the bottom

validator/webui/@polymer/webui-mainpage/webui-mainpage.html, validator/webui/@polymer/webui-urlform/webui-urlform.html
Update the validator webui to include AMP4EMAIL as an option.
=> Add AMP4EMAIL

ads/taboola.js
Updated copyright info from 2015 to 2018.
=> Updated copyright for taboola.js

validator/testdata/feature_tests/regexps.html, validator/testdata/feature_tests/regexps.out, validator/validator-main.protoascii
Add the new Font Awesome CDN urls to the allowed fonts source list, add test cases to match.
Fixes #13770 
Fixed #13685
=> :bug: Add new Font Awseome URL format, fixes #13770 and #13685 

build-system/app.js, examples/csp.amp.html
Corresponds to #13773 for #13770 and #13685.
=> csp update for use.fontawesome.com

contributing/web-standards-related-to-amp.md
=> Tracking web standards and web features proposals related to AMP.

extensions/amp-story/amp-story-ads.md
=> Adding Experimental note

extensions/amp-story/amp-story-ads.md, extensions/amp-story/amp-story-auto-ads.md
Title. View diff without whitespace to see actual changes :)
=> Correct typos in story ads docs

extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/test-amp-list.js
Fixes https://github.com/ampproject/amphtml/pull/13707#discussion_r171431437.
=> amp-list: Schedule pass if queue is non-empty

extensions/amp-ad/amp-ad.md, spec/amp-html-format.md
Related to https://github.com/ampproject/docs/issues/872
=> fix links to avoid 404s

builtins/amp-img.js, extensions/amp-anim/0.1/amp-anim.js, extensions/amp-bind/0.1/bind-validator.js, extensions/amp-bind/0.1/test/test-bind-validator.js, extensions/amp-image-lightbox/0.1/amp-image-lightbox.js, extensions/amp-image-lightbox/0.1/test/test-amp-image-lightbox.js, extensions/amp-image-viewer/0.1/amp-image-viewer.js, src/sanitizer.js, src/srcset.js, test/functional/test-sanitizer.js, test/functional/test-srcset.js
Shaves a half kb off compiled size, and makes simplifies some of the algorithms.
=> 🚀♻️ Refactor Srcset

extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
Fixed incorrect quote character which was probably inserted because of a copy/paste.
=> Fixed incorrect quotation character.

extensions/amp-analytics/0.1/vendors.js
Thank you for merging previous PR #13097.
But unfortunately I found a wrong value in the `CLIENT_ID`.
Could you merge this patch?
Thanks,
=> Fix treasuredata's cid-scope-cookie-fallback-name

examples/sticky.ads.amp.html, extensions/amp-sticky-ad/1.0/amp-sticky-ad.js, extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
Do not display sticky ad before user notification dismissal
=> Fix sticky-ad added to fixed layer too early

extensions/amp-story/0.1/amp-story-auto-ads.js
Throw error if given CTA url is not the right protocol.
=> 🐛 Sanitize CTA Urls

extensions/amp-access/amp-access.md, extensions/amp-ad/amp-ad.md, extensions/amp-bind/amp-bind.md, extensions/amp-call-tracking/amp-call-tracking.md, extensions/amp-form/amp-form.md, extensions/amp-iframe/amp-iframe.md, extensions/amp-list/amp-list.md, extensions/amp-user-notification/amp-user-notification.md
Cleaned up links to posted to docs hosted on ampproject.org.
=> Clean up links in docs

extensions/amp-ad/0.1/amp-ad-ui.js
=> Fix amp-embed

validator/README.md
Adding recently verified validation build instructions for Mac freshly run off of @nainar 's computer. Let me know / feel free to edit if any of this looks sketch.
=> Add validator instructions for mac

validator/validator-main.protoascii
=> Allow referrerpolicy on anchor tags in AMP docs

extensions/amp-lightbox-gallery/0.1/test/validator-amp-lightbox-gallery.html, extensions/amp-lightbox-gallery/0.1/test/validator-amp-lightbox-gallery.out, extensions/amp-lightbox-gallery/validator-amp-lightbox-gallery.protoascii, extensions/amp-mustache/validator-amp-mustache.protoascii, extensions/amp-story-auto-ads/0.1/test/validator-amp-story-auto-ads.html, extensions/amp-story-auto-ads/0.1/test/validator-amp-story-auto-ads.out, extensions/amp-story-auto-ads/validator-amp-story-auto-ads.protoascii, extensions/amp-story/validator-amp-story.protoascii, extensions/amp-youtube/validator-amp-youtube.protoascii, validator/README.md, validator/engine/validator_test.js, validator/testdata/feature_tests/forms.out, validator/validator-main.protoascii
- Revision bumps
- amp-story-auto-ads
=> Validator Roll-up

examples/amp-story/animations-presets.html, extensions/amp-story/0.1/animation-presets-utils.js, extensions/amp-story/0.1/animation-presets.js, src/style.js
Refactors animation preset by adding a set of common util functions for animations.
This in preparation of new animation presets that will be added for #12173.
/cc @newmuis
=> Refactors animation presets ♻️

ads/custom.md
=> Docs: data-url needs to be accessible cross-origin

src/sanitizer.js, test/functional/test-sanitizer.js
Closes https://github.com/ampproject/amphtml/issues/13893
=> sanitizer: allow aria- and role

extensions/amp-access/amp-access.md
Adds documentation corresponding to functionality added in #12353
=> 📖Add documentation for multiple access sources

extensions/amp-a4a/0.1/amp-a4a.js
To match current version served by GPT.
=> Update safeframe version to 1-0-17

spec/amp-html-layout.md
Fixes https://github.com/ampproject/amphtml/issues/12487
cc: @jridgewell
=> Add note about no intrinsic size for responsive elements

build-system/tasks/presubmit-checks.js, extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-a4a/0.1/test/utils.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js, extensions/amp-ad/0.1/amp-ad-3p-impl.js, extensions/amp-ad/0.1/amp-ad-custom.js, extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js, extensions/amp-ad/0.1/test/test-amp-ad-custom.js, extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js, extensions/amp-bind/0.1/amp-bind-macro.js, extensions/amp-bind/0.1/amp-state.js, extensions/amp-iframe/0.1/amp-iframe.js, extensions/amp-iframe/0.1/test/test-amp-iframe.js, extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js, src/base-element.js, src/custom-element.js, src/element-stub.js, src/service/resource.js, src/service/resources-impl.js, test/functional/test-amp-img.js, test/functional/test-base-element.js, test/functional/test-resource.js, test/functional/test-resources.js
=> ♻️ Rename (get|update)Priority to (get|update)LayoutPriority

ads/medianet.js, ads/medianet.md
Remove doubleclick.js dependency from medianet.js
=> Support for standalone Media.net amp tag

spec/amp-html-layout.md
Fixes https://github.com/ampproject/amphtml/issues/13506
=> Add info for fill layout - parent needs position

build-system/app.js, examples/live-list-update-reverse.amp.html, extensions/amp-live-list/0.1/amp-live-list.js, extensions/amp-live-list/0.1/test/test-amp-live-list.js, tools/experiments/experiments.js
still bikeshedding new property name
=> Add a way to insert new items at the bottom of the component

extensions/amp-ad-network-doubleclick-impl/0.1/doubleclick-a4a-config.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-a4a-config.js
Ignore useSameDomainRenderingUntilDeprecated
=> Add experiment to ignore USDRUD for doubleclick.

extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
Turning off expand by push or expand by overlay was broken.
=> Fix SF config.

extensions/amp-beopinion/0.1/test/validator-amp-beopinion.html, extensions/amp-beopinion/0.1/test/validator-amp-beopinion.out, extensions/amp-beopinion/validator-amp-beopinion.protoascii, extensions/amp-subscriptions/0.1/test/validator-amp-subscriptions.html, extensions/amp-subscriptions/0.1/test/validator-amp-subscriptions.out, extensions/amp-subscriptions/validator-amp-subscriptions.protoascii, validator/validator-main.protoascii
Add revision bumps and amp-subscriptions validation
=> Validator update

src/url.js, test/functional/test-url.js
=> Allow /ad/ as cache URL prefix.

examples/scroll.amp.html, extensions/amp-access-scroll/0.1/scroll-impl.js
- Put back missing return of authorization value
- Do not add Scroll iframe element in stories
=> 🐛Fix two bugs in amp-access-scroll

src/service/url-replacements-impl.js, test/functional/test-url-replacements.js
=> ♻️URL Relpacements: Simplify DocInfo Values

extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-video/0.1/test/test-amp-video.js, src/preconnect.js, test/functional/test-preconnect.js
Due to short preconnect timeout this seems better; and it allows us to preconnect to pub controlled origins.
=> 🚀Delay preconnects until doc is visible.

extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css, extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js, test/manual/amp-lightbox-gallery-launch.amp.html
Addresses https://github.com/ampproject/amphtml/issues/11215.
=> Fix description animations

extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Closes https://github.com/ampproject/amphtml/issues/13974
=> Don't create thumbnails for <amp-ad> in <amp-lightbox-gallery>

ads/_config.js, ads/imonomy.js
Fixed problems after release of first version:
- problem with access to top window context for getting page url.
- other small adjustments in imonomy.js file.
- disable imonomy external prefetch request.
- imonomy.js refactoring
#13998
=> imonomy network fix tracking

src/inabox/inabox-viewport.js, src/service/resource.js, src/service/viewport/viewport-binding-def.js, src/service/viewport/viewport-binding-ios-embed-wrapper.js, src/service/viewport/viewport-binding-natural.js, src/service/viewport/viewport-impl.js, test/functional/test-resource.js
=> :bug: Fix fix-positioned elements in inabox

examples/bodymovin-animation.amp.html
Fixes a mistake in the import in the examples file.
=> <amp-bodymovin-animation> Fix imports in example

extensions/amp-ad/amp-ad.md
=> Add note indicating ad collapses when outside of current viewport

ads/_integration-guide.md
Just cleaning up language, wording, and fixing 404 link.
=> Fix wording and link

extensions/amp-story/0.1/amp-story-ads.css
=> 🐛 Change story-ad text to bold

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
See https://github.com/ampproject/amphtml/pull/14094
=> Turn off delayed fetch deprecation until March 29

extensions/amp-list/amp-list.md
Follow up to https://github.com/ampproject/amphtml/pull/13782
=> amp-list: document new reset-on-refresh attribute

extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Pause lightbox children on close so that videos in lightbox stop playing after lightbox closes.
=> Pause lightbox children on close

extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
Follow up to https://github.com/ampproject/amphtml/pull/14126. The visibility hidden / visible is already set in the animations. This is a follow up to make sure that it is accurate in the show/hide classes.
=> Add visibility toggle

extensions/amp-list/0.1/amp-list.js
=> Remove amp-list debug statement

extensions/amp-story/0.1/amp-story-store-service.js, extensions/amp-story/0.1/amp-story.js, extensions/amp-story/0.1/test/test-amp-story-store-service.js
Last PR before we can start rendering UI elements into a shadow DOM.
=> Adding the desktop state to the store.

extensions/amp-story/0.1/amp-story.js
=> Fix assumption that stories have more than 1 page

build-system/config.js, build-system/conformance-config.textproto, build-system/tasks/presubmit-checks.js, examples/article-access-iframe.amp.html, examples/article-access-iframe.provider.html, extensions/amp-access/0.1/amp-access-iframe.js, extensions/amp-access/0.1/amp-access-source.js, extensions/amp-access/0.1/iframe-api/README.md, extensions/amp-access/0.1/iframe-api/access-controller.js, extensions/amp-access/0.1/iframe-api/amp-iframe-api-export.js, extensions/amp-access/0.1/iframe-api/iframe-api.js, extensions/amp-access/0.1/iframe-api/messenger.js, extensions/amp-access/0.1/test/test-amp-access-iframe.js, extensions/amp-access/0.1/test/test-amp-access-source.js, extensions/amp-access/0.1/test/test-iframe-api.js, extensions/amp-access/0.1/test/test-iframe-messenger.js, gulpfile.js, tools/experiments/experiments.js
Blocked by #14187
Partial for #13287
=> Access iframe messaging and handshake implementation

extensions/amp-story/0.1/amp-story.js
=> 🐛Enable the amp-story experiment for file:// URLs.

.gitignore
=> 🏗Add chromedriver.log to .gitignore

README.md
Updates the README so the "front page" of the AMP Project on GitHub provides links for contributors AND people using AMP.
=> Updates README to add some clarity for contributors and users

extensions/amp-access/0.1/iframe-api/README.md
=> minor update to access iframe doc

spec/amp-html-layout.md
:book: Add `intrinsic` layout to the summary of layout requirements
=> Add intrinsic to summary of layout requirements

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
See https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.2
=> SwG release 0.1.22.2

extensions/amp-story/0.1/amp-story-bookend.css
Updating the bookend in/out animation easing curves to match the [Material Design guidelines](https://material.io/guidelines/motion/movement.html#movement-movement-in-out-of-screen-bounds).
=> Mobile bookend animation easing curves.

extensions/amp-story/amp-story.md
Adds to amp-story readme the new preset animations introduced in #13910
=> 📖 Adds documentation of new animations

examples/article-access-iframe.amp.html, examples/article-access-iframe.provider.html, extensions/amp-access/0.1/amp-access-iframe.js, extensions/amp-access/0.1/iframe-api/README.md, extensions/amp-access/0.1/iframe-api/access-controller.js, extensions/amp-access/0.1/iframe-api/iframe-api.js, extensions/amp-access/0.1/test/test-amp-access-iframe.js
Partial for #13287.
/cc @rudygalfi
=> Access iframe: resolve config vars, define authorization better, docs

extensions/amp-story/0.1/amp-story-bookend.css, extensions/amp-story/0.1/amp-story.js
Switching from a slide in animation to a fade in animation for the desktop bookend.
=> Bookend desktop animation

extensions/amp-story/0.1/amp-story-system-layer.css, extensions/amp-story/0.1/amp-story-system-layer.js
Removing the ``ui-left`` and ``ui-right`` duplicated buttons by using the ``flex-direction: row-reverse`` property.
=> Using the same ui-buttons on both mobile and web versions.

extensions/amp-story/0.1/amp-story.js
Fixes #13621
/cc @matthewgcallahan
=> Only do CSS.supports detection on browsers that support it

spec/amp-html-format.md
Fixes https://github.com/ampproject/docs/issues/899
=> Minor doc fix to escape dots

spec/amp-var-substitutions.md
=> 📖 Documents HTML Attribute, implemented in #13712

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-ad/0.1/amp-ad-3p-impl.js, extensions/amp-ad/0.1/amp-ad-custom.js, extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js, extensions/amp-ad/0.1/test/test-amp-ad-custom.js, extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js, extensions/amp-bind/0.1/amp-bind-macro.js, extensions/amp-bind/0.1/amp-state.js, extensions/amp-iframe/0.1/amp-iframe.js, extensions/amp-iframe/0.1/test/test-amp-iframe.js, extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js, src/base-element.js, src/layout.js, test/functional/test-amp-img.js, test/functional/test-base-element.js, test/functional/test-resource.js, test/functional/test-resources.js
Oh right I had this PR ready to go for a month now and just forgot about it :P
Fixes #13555
=> ♻️ Replace the magic numbers for priority layout values with an enum

extensions/amp-story/0.1/amp-story-auto-ads.js, extensions/amp-story/amp-story-ads.md
=> Add install now CTA button type

extensions/amp-date-picker/amp-date-picker.md
Clean up and improvements for amp-date-picker ref doc.
=> Doc fixup for amp-date-picker

extensions/amp-story/0.1/amp-story-bookend.js, extensions/amp-story/0.1/amp-story-system-layer.js, extensions/amp-story/0.1/utils.js
Moving the logic to create a shadow root and append the element + style into a util function.
=> Util function for stories shadow DOM.

extensions/amp-story/amp-story-ads.md
=> Update doc mention about using deep links

extensions/amp-story/0.1/amp-story-bookend.css
=> Set amp-story bookend opacity to 70%

extensions/amp-story/0.1/_locales/en.js
=> Explicitly call out tap action in hint strings

extensions/amp-a4a/0.1/test/test-callout-vendors.js
Add test that verifies RTC vendor urls all use HTTPS
=> RTC ensure vendor urls are HTTPS

extensions/amp-selector/amp-selector.md
=> 📖Add the select event to the amp-selector docs

spec/amp-actions-and-events.md
Added some `tr` tags for bodymovin actions table
=> 📖Add rows for different bodymovin actions and descriptions

test/functional/test-error.js, test/functional/test-url.js
=> Skip flaky tests

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
See https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.3
=> SwG release 0.1.22.3

build-system/tasks/karma.conf.js, build-system/tasks/runtime-test.js
=> 🏗 Fix sauce platform list

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js, extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js, extensions/amp-subscriptions/0.1/amp-subscriptions.js, extensions/amp-subscriptions/0.1/doc-impl.js, extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js, extensions/amp-subscriptions/0.1/test/test-doc-impl.js
=> Support multi-doc for subscriptions

extensions/amp-subscriptions/amp-subscriptions.md
=> Subscriptions: microdata configuration docs

extensions/amp-subscriptions/0.1/amp-subscriptions.js, extensions/amp-subscriptions/0.1/entitlement.js, extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js, extensions/amp-subscriptions/0.1/test/test-entitlement.js
- sends actual raw data in raw field
=> Subscriptions: raw bug fix

build-system/dep-check-config.js, extensions/amp-story/0.1/amp-story-page.js
=> 🐛 Install Video Service at story page level when delegating autoplay

3p/integration.js, ads/_config.js, ads/kuadio.js, ads/kuadio.md, examples/ads.amp.html, extensions/amp-ad/amp-ad.md
We added our ad network "kuadio".
* Add network logic
* Add samples and doc
* Update configuration files
Could you review our commits?
Best regards.
=> Add kuadio ad network 

spec/amp-html-format.md
=> update docs to reflect updates in now supported css properties

extensions/amp-bodymovin-animation/amp-bodymovin-animation.md
Added link to new ABE example.
cc: @sebastianbenz
=> Add ABE example link for amp-bodymovin-animation

extensions/amp-subscriptions/amp-subscriptions.md
=> Subscriptions: more documentation on emulating viewer behavior

extensions/amp-date-picker/validator-amp-date-picker.protoascii, validator/validator-main.protoascii, validator/validator_gen_js.py
- validator amp-date-picker update no relative urls.
- Remove foreignobject support from SVG.
- Fix typo "text-combine-upright"
=> Sync to Github

extensions/amp-story/0.1/amp-story-hint.js, extensions/amp-story/0.1/amp-story-share-menu.css, extensions/amp-story/0.1/amp-story-share-menu.js, extensions/amp-story/0.1/amp-story-store-service.js, extensions/amp-story/0.1/amp-story-system-layer.css, extensions/amp-story/0.1/amp-story-system-layer.js, extensions/amp-story/0.1/amp-story.js, extensions/amp-story/0.1/test/test-amp-story-share-menu.js, extensions/amp-story/0.1/test/test-system-layer.js, gulpfile.js
- New sharing menu component reusing the ScrollableSharingWidget component
- New sharing icon in the system layer, with a different SVG for Android and iOS (defaults to Android), hidden on desktop
Partial for #12186.
=> Story share menu.

package.json, yarn.lock
See https://github.com/google/web-activities/releases/tag/1.8
=> Upgrade Web Activities to 1.8

build-system/dep-check-config.js, build-system/tasks/presubmit-checks.js, extensions/amp-document-recommendations/0.1/amp-document-recommendations.js
- Tracks the position of each block of recommendations in the viewport with PositionObserver
- Updates document title/URL when recommendation leaves the viewport in either direction
=> ✨ amp-document-recommendations: Use PositionObserver to detect when active document changes

extensions/amp-consent/0.1/amp-consent.js, extensions/amp-consent/0.1/test/test-amp-consent.js, src/service/notification-ui-manager.js, test/functional/test-notification-ui-manager.js, test/manual/amp-consent.html
#14433 merged. Test added. PTAL
=> amp-consent postPromptUI

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.4
=> Upgrade SwG to 0.1.22.4

validator/testdata/feature_tests/amp_geo.out, validator/validator-main.protoascii
Just revision bumping here and an empty line in a test file.
=> Upstream more validator changes

ads/google/a4a/docs/Network-Impl-Guide.md
Improve the documentation in terms of: grammar, formatting, spelling, layout, and consistency.  Actual technical content was unaltered.
=> doc cleanup for fast fetch guide

examples/carousel.amp.html, extensions/amp-carousel/0.1/scrollable-carousel.js, extensions/amp-carousel/0.1/slidescroll.js
Closes https://github.com/ampproject/amphtml/issues/13011. 
My only question here is does it make sense to scroll so that the target slide is in the center of the carousel or the left? The way I interpreted the aesthetic of the scrollable-carousel, was that the target slide was the left-most slide. But maybe I'm misinterpreting how people use them.
=> Add goToSlide to scrollable-slides

extensions/amp-document-recommendations/0.1/amp-document-recommendations.js
- `amp-document-recommendations-click` on a recommendation click
- `amp-document-recommendations-scroll` when scrolling the page down into a document
- `amp-document-recommendations-scroll-back` when scrolling back up the page into a previous document
- Tracks from/to URLs for both
=> ✨ amp-document-recommendations: Trigger analytics events when setting active document

spec/amp-actions-and-events.md
Updated documentation that was impacted by #12814
=> amp-carousel: Update amp-actions-and-events.md

examples/article-access-iframe.provider.html, extensions/amp-access/0.1/amp-access-iframe.js, extensions/amp-access/0.1/iframe-api/README.md, extensions/amp-access/0.1/iframe-api/access-controller.js, extensions/amp-access/0.1/test/test-amp-access-iframe.js, extensions/amp-access/0.1/test/test-iframe-api.js
=> Access iframe: get rid of data subfield; update examples

ads/README.md
=> Missed closing brace

extensions/amp-bind/0.1/test/integration/test-bind-impl.js
These tests are failing repeatedly on Travis. See https://travis-ci.org/ampproject/amphtml/jobs/365658076#L721-L733
=> ✅ Skip flaky Bind tests

extensions/amp-analytics/0.1/test/test-visibility-manager.js
Corrects a comment I made in #14561
=> Corrects comment text

extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
We decided in UX review that we want to get rid of the top bar while description overflow is on
=> Toggle top bar on description overflow

test/_init_tests.js
=> 🏗 Prevent unnecessary use of allowConsoleError

validator/validator-main.protoascii
=> allow webcal uri scheme

extensions/amp-document-recommendations/0.1/amp-document-recommendations.css, extensions/amp-document-recommendations/0.1/amp-document-recommendations.js
Uses a style attached in the shadow DOM to hide position fixed elements of nested pages.
Option of changing between positioned fixed elements of active page was considered, but decided against while only documents from one source are used.
@peterjosling
=> ✨Document-level infinite-scroll (#12945): Hide position fixed elements of nested pages.

extensions/amp-mustache/0.1/test/test-amp-mustache.js
Followup to #14432
Note that I split some of the tests into multiple, smaller tests
=> ✅ Wrap tests in test-amp-mustache.js that expect a console error with `allowConsoleError`

extensions/amp-geo/amp-geo.md, spec/amp-var-substitutions.md
=> 📖 amp-geo documentation

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.5
=> Upgrade SwG to 0.1.22.5

extensions/amp-subscriptions/0.1/entitlement.js, extensions/amp-subscriptions/0.1/test/test-viewer-platform.js, extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
- recognizes metering response from Viewer
=> Subscriptions: metering fix

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.6
=> Upgrade SwG to 0.1.22.6

examples/amp-consent.amp.html, extensions/amp-consent/0.1/amp-consent.js, extensions/amp-consent/0.1/test/test-amp-consent.js
To fix the prerender privacy leak.
=> Bug fix: amp-consent wait for document visible before sending request

examples/article-fade-in.amp.html, extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js, extensions/amp-fx-collection/0.1/providers/fx-provider.js, extensions/amp-fx-collection/amp-fx-collection.md
This will allow for better sharing of attributes across all presets.
=> Rename `data-margin` to `data-margin-start` for amp-fx

ads/_integration-guide.md
=> Fix SSP lingo

examples/article-access-laterpay.amp.html, extensions/amp-access-laterpay/0.1/laterpay-impl.js, extensions/amp-access-laterpay/0.2/amp-access-laterpay.css, extensions/amp-access-laterpay/0.2/amp-access-laterpay.js, extensions/amp-access-laterpay/0.2/laterpay-impl.js, extensions/amp-access-laterpay/0.2/test/test-amp-access-laterpay.js, extensions/amp-access-laterpay/0.2/test/validator-amp-access-laterpay.html, extensions/amp-access-laterpay/0.2/test/validator-amp-access-laterpay.out, extensions/amp-access-laterpay/amp-access-laterpay.md, extensions/amp-access-laterpay/validator-amp-access-laterpay.protoascii, gulpfile.js
This updates amp-access-laterpay to use the new LaterPay Connector 2.0 API, including the new data format.
This branch is based off the branch from #14437
Relates to #11733
=> ✨ Update amp-access-laterpay for the new LaterPay API

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Turn "amp-consent" experiment on. Need this in before prod release.
=> Turn on amp-consent

extensions/amp-consent/amp-consent.md
=> 📖amp-consent documentation

spec/amp-cache-guidelines.md
See #14692 for more info.
/cc @dknecht
=> 📖 AMP caches need to dynamically generate amp-geo.js

extensions/amp-consent/amp-consent.md
=> Fix code so renders correctly ampproject.org

extensions/amp-a4a/rtc-documentation.md
Comments break the JSON if you copy/paste it
=> Remove comments in JSON example

extensions/amp-geo/amp-geo.md
=> 📖 more doc fixes to amp-geo for readability and phrasing

extensions/amp-a4a/0.1/amp-a4a.js
To match current GPT safeframe version
=> Fast Fetch update safeframe version

extensions/amp-consent/0.1/amp-consent.js, extensions/amp-consent/0.1/test/test-amp-consent.js, test/manual/amp-consent-geo.html
Add "promptIfUnknownForGeoGroup" to config. 
And use <amp-geo> provided isoCountryGroup if "checkConsentHref" is not defined. 
cc @rudygalfi @jasti
=> amp-consent: integrate with amp-geo outcome

build-system/tasks/visual-diff.rb
This will prevent Travis timeouts like this: https://travis-ci.org/ampproject/amphtml/jobs/368724822#L2469
=> 🏗 🐛 Print messages to keep Travis alive while waiting for Percy status

ads/dable.js, examples/ads.amp.html
Support case that page has no item id.
=> Add Dable ad functionality

extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
=> Fix and unskip test

.eslintrc, .travis.yml, build-system/eslint-rules/vsync.js, src/.eslintrc, src/custom-element.js, test/functional/test-custom-element.js, test/integration/test-amp-img.js
PR 1 for Remove direct VSync access.
Part of #12748.
=> Layers: Remove VSync from CustomElement

3p/ampcontext.js
=> Cleanup AmpContext's annotation

test/integration/test-video-players-helper.js
These fail on `master`: https://travis-ci.org/ampproject/amphtml/jobs/370349732#L668-L696
=> ✅ Skip failing video tests

test/integration/test-video-players.js
=> Skip amp-brid-player tests.

spec/amp-managing-user-state.md
Cosmetic changes done so that when I have doc imported into ampproject.org (in "Analytics" docs section), it will render nicely and be valid AMP.
=> Cosmetic changes for doc to render on ampproject.org

extensions/amp-story/1.0/variable-service.js
Seems like a leftover from 97f6f61b89.
Part of #14761.
=> 🚮 Cleanup AmpStoryVariableService private field

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js, test/manual/amp-story-doubleclick.amp.html
Example story using double-click config to ensure everything is going well 😁
=> [amp-story] manual test for dfp

src/animation.js
=> ♻️ Cleanup AnimationPlayer's private state

extensions/amp-story/0.1/amp-story-share-menu.js, extensions/amp-story/0.1/amp-story-system-layer.js, extensions/amp-story/0.1/amp-story.js, extensions/amp-story/0.1/analytics.js, extensions/amp-story/0.1/animation.js, extensions/amp-story/0.1/development-ui.js, extensions/amp-story/0.1/page-scaling.js, extensions/amp-story/0.1/variable-service.js, extensions/amp-story/1.0/amp-story-share-menu.js, extensions/amp-story/1.0/amp-story-system-layer.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/analytics.js, extensions/amp-story/1.0/animation.js, extensions/amp-story/1.0/development-ui.js, extensions/amp-story/1.0/page-scaling.js
Remove unused properties in the amp-story extension.
Fixes #14883
=> Remove unused properties in the amp-story extension.

src/sanitizer.js
fix annotation from a previous PR #14447
=> fix annotation

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js, extensions/amp-subscriptions/0.1/amp-subscriptions.js, extensions/amp-subscriptions/0.1/local-subscription-platform.js, extensions/amp-subscriptions/0.1/platform-store.js, extensions/amp-subscriptions/0.1/service-adapter.js, extensions/amp-subscriptions/0.1/subscription-platform.js, extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js, extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js, extensions/amp-subscriptions/0.1/test/test-platform-store.js, extensions/amp-subscriptions/0.1/test/test-service-adapter.js, extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
- Add action delegation via attribute
=> Subscriptions: Action delegation

src/focus-history.js, src/gesture-recognizers.js, src/inabox/inabox-viewport.js, src/input.js, src/motion.js, src/service/action-impl.js, src/service/document-state.js, src/service/standard-actions-impl.js, src/service/variable-source.js, src/service/video-manager-impl.js, src/service/viewer-cid-api.js, src/srcset.js
=> 🚮 Cleanup a few unused privates in src

3p/integration.js, test/integration/test-amp-ad-3p.js, tools/experiments/experiments.js
=> Remove legacy code before ampcontext.

extensions/amp-story/1.0/_locales/en.js, extensions/amp-story/1.0/localization.js
Adds strings for the domain dialog to be added in #14923
=> 🌐 Add strings for domain dialog

extensions/amp-subscriptions/0.1/amp-subscriptions.js, extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
- Skip entire platform and unblock document for `alwaysGrant`
=> Subscriptions: Skip platform for alwaysGrant

extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
This provides the AMP tooling for a $sf.ext.geom().pos position tracking API.
=> Send required data into GPT safeframe for position tracking API

package.json, yarn.lock
=> Update preact to the latest version 🚀

extensions/amp-bodymovin-animation/0.1/amp-bodymovin-animation.js
=> Remove unused variable from amp-bodymovin-animation.js

extensions/amp-instagram/0.1/amp-instagram.js
=> Remove unused variable from <amp-instagram>

gulpfile.js
Fixes bundle size increase caused by https://github.com/ampproject/amphtml/pull/14922#issuecomment-385541703
=> ✅ Increase expected minified bundle size

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
Version: 0.1.22.10
Previous release: 0.1.22.9
Update Save Subscription Request to include authCode or token (#348)
=> SWG Release 0.1.22.10

package.json, yarn.lock
=> Update autoprefixer to the latest version 🚀

extensions/amp-video/0.1/test/validator-amp-video.html, extensions/amp-video/0.1/test/validator-amp-video.out, extensions/amp-video/validator-amp-video.protoascii
Adding only for `amp-video` as audit for support in other players is pending.
=> ✅ Add validation for rotate-to-fullscreen in amp-video

extensions/amp-gfycat/0.1/amp-gfycat.js
Because nobody deserves something as bad as fullscreen gifs.
=> 🚮 Remove fullscreen from amp-gfycat

3p/ampcontext.js, ads/_ping_.js, build-system/app.js, extensions/amp-ad/0.1/amp-ad-3p-impl.js, extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js, extensions/amp-consent/0.1/amp-consent.js, extensions/amp-consent/0.1/consent-policy-manager.js, extensions/amp-consent/0.1/consent-state-manager.js, extensions/amp-consent/0.1/test/test-consent-policy-manager.js, src/consent-state.js
=> Pass along sharedData from consent response to 3p ad iframes

ads/README.md
=> 📖 Document amp-consent related ampcontext APIs.

examples/amp-subscriptions.amp.html, extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js, extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js, extensions/amp-subscriptions/0.1/amp-subscriptions.js, extensions/amp-subscriptions/0.1/local-subscription-platform-renderer.js, extensions/amp-subscriptions/0.1/local-subscription-platform.js, extensions/amp-subscriptions/0.1/platform-store.js, extensions/amp-subscriptions/0.1/service-adapter.js, extensions/amp-subscriptions/0.1/subscription-platform.js, extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js, extensions/amp-subscriptions/0.1/test/test-local-subscription-rendering.js, extensions/amp-subscriptions/0.1/test/test-platform-store.js, extensions/amp-subscriptions/0.1/test/test-service-adapter.js, extensions/amp-subscriptions/0.1/viewer-subscription-platform.js, extensions/amp-subscriptions/amp-subscriptions.md
- Delegated UI decoration to another platform
=> Subscriptions: UI Decoration delegation

src/service/action-impl.js
Saw a null reference error
checked blame
it was me 😭
=> 🐛Prevent null reference error

extensions/amp-access-scroll/0.1/amp-access-scroll.css
Fixes an issue where mismatch between placeholder and current UI causes jitter.
=> 🐛Update Scroll amp-access extension placeholder CSS to match current UI

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.11
=> SwG release 0.1.22.11

src/friendly-iframe-embed.js
They juste needed the `@restricted` annotation.
Part of #14761.
=> Update FIE's unused privates

extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js, extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js
Redoing #13409, which was rolled back in #14293
Fixes #12473
=> Remove timer-based delay in <amp-install-serviceworker>

ads/google/imaVideo.js, extensions/amp-ima-video/0.1/amp-ima-video.js, extensions/amp-ima-video/0.1/test/test-amp-ima-video.js, extensions/amp-ima-video/consent-blocking.md
Adds amp-consent blocking to amp-ima-video. Usage is outlined in consent-blocking.md.
=> ✨ amp-ima-video: Add consent blocking.

src/utils/video.js
=> amp-video: Make sure rejected autoplay detection promises are caught

extensions/amp-story/1.0/amp-story-consent.css, extensions/amp-story/1.0/amp-story-consent.js, extensions/amp-story/1.0/amp-story.css, test/functional/test-action.js
=> Migrate amp-story-consent away from position: fixed.

extensions/amp-story/1.0/amp-story-consent.js, extensions/amp-story/1.0/test/test-amp-story-consent.js, test/functional/test-action.js
AMP Story consent i18n.
Partial for #14538
=> AMP Story consent i18n.

src/service/resources-impl.js
=> ✨ Add dirtyElement method to Resources

src/batched-json.js, src/service/url-replacements-impl.js, test/functional/test-batched-json.js, test/functional/test-url-replacements.js
Fixes #12498.
Context: https://github.com/ampproject/amphtml/issues/12498#issuecomment-385969938
=> Make dynamic CORS fail without opt-in

tools/experiments/experiments.js
We'll leave this as a manual opt-in for now. See https://github.com/ampproject/amphtml/issues/15158 for details.
=> Add Layers experiment

extensions/amp-story/0.1/test/validator-amp-story-cta-layer-error.out, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/validator-amp-story-consent.html, extensions/amp-story/1.0/test/validator-amp-story-consent.out, extensions/amp-story/validator-amp-story.protoascii
Updates the validation rules to allow the ``amp-story-consent`` component.
Partial for #14538
=> Story consent component validator.

extensions/amp-story/0.1/amp-story-consent.css, extensions/amp-story/0.1/amp-story-consent.js, extensions/amp-story/0.1/amp-story.css, extensions/amp-story/0.1/amp-story.js, extensions/amp-story/0.1/test/test-amp-story-consent.js, extensions/amp-story/0.1/test/validator-amp-story-consent.html, extensions/amp-story/0.1/test/validator-amp-story-consent.out, gulpfile.js
Copy the ``amp-story-consent`` component from 1.0 to 0.1.
Partial for #14538
=> Copy the amp-story-consent component from 1.0 to 0.1.

extensions/amp-bind/0.1/bind-impl.js
Partial for #11434.
Context: https://github.com/ampproject/amphtml/issues/11434#issuecomment-387747773
=> amp-bind: Measure impact of reducing binding limit

build-system/tasks/bundle-size.js
Fixes https://travis-ci.org/ampproject/amphtml/jobs/377004285
=> bump bundle size

extensions/amp-a4a/amp-a4a-format.md
=> Add amp-bind to list of amp4ads documentation of allowed extensions

ads/README.md
=> 📖 Update ads doc for the context.getConsentState API.

build-system/tasks/bundle-size.js, src/dom.js, src/impression.js, src/motion.js, src/service.js, src/service/ampdoc-impl.js, src/service/extensions-impl.js, src/service/history-impl.js, src/service/resource.js, src/service/template-impl.js, src/service/viewer-impl.js, src/service/vsync-impl.js, src/utils/signals.js
The `Deferred` class creates a `{ promise, resolve, reject }` struct, removing all these resolvers to extract the `resolve` and `reject` params.
=> ♻️ Use Deferred class in src

extensions/amp-ad/amp-ad.md
Doc update to add RTC support for Fast Fetch
=> Doc update to add RTC support for Fast Fetch

extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
Enable using the back button to exit out of lightbox per https://github.com/ampproject/amphtml/issues/15198.
=> Add history to lightbox-gallery

.travis.yml
=> 🏗 Make Travis email notifications less spammy

.travis.yml
=> 🏗 Notify when tests on `master` go from failing -> passing

extensions/amp-audio/0.1/amp-audio.js, extensions/amp-audio/0.1/test/test-amp-audio.js
As per suggestions made by @alanorozco  in #15207
=> Clean up code for actions in <amp-audio>

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
See https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.12
=> SwG release 0.1.22.12

ads/24smi.js, ads/_a4a-config.js, ads/adfox.js, ads/adgeneration.js, ads/adhese.js, ads/adocean.js
This PR fixes the JSDoc errors mentioned in https://github.com/ampproject/amphtml/issues/15255#issuecomment-388910649
Partial fix for #15255
=> 📖 Fix incorrect JSDoc annotations in `ads/`

extensions/amp-geo/amp-geo.md
...I was wondering why our sample didn't work.
//cc @jpettitt @kul3r4
=> Fix amp-geo docs: s/AMPBind/AmpBind

extensions/amp-next-page/0.1/test/test-amp-next-page.js
Per https://github.com/ampproject/amphtml/pull/15213#pullrequestreview-120079340 this is flaky.
@peterjosling another one to enable later. Root cause might be same as https://github.com/ampproject/amphtml/pull/15259.
=> Skip analytics test in test-amp-next-page.js

spec/amp-cors-requests.md
=> Fix for #15250 CORS sample code

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Also alphabetize existing doc opt-ins.
=> Allow document opt-in for `inline-styles`

extensions/amp-video-service/0.1/amp-video-service.js, src/service/video-manager-impl.js, src/service/video-service-interface.js, src/service/video-service-sync-impl.js, src/service/video/docking.js, src/services.js, src/video-interface.js
Orthogonal changes related to new lint rules.
=> ♻️ Coalesce Type

extensions/amp-form/0.1/test/test-amp-form.js
This PR fixes blocking test failures for #15132
=> ✅Fix unhandled errors in form tests. Unbreak tests.

test/integration/test-amp-ad-custom.js
Master has been red for a couple of hours with this flake. https://travis-ci.org/ampproject/amphtml/jobs/379414735
Unskip issue #15329
=> Skip flaky test

extensions/amp-access/0.1/test/test-amp-access-iframe.js
master is red after #15292. fix the test
=> Fix test failure on master

build-system/tasks/lint.js, contributing/DEVELOPING.md
=> 🏗 Add `--local-changes` flag to `gulp lint`

extensions/amp-next-page/0.1/next-page-service.js, extensions/amp-next-page/0.1/test/test-amp-next-page.js
I *think* this completely de-flakes it (but I can't really check well on Travis).
Fixes #15234
=> ✅ amp-next-page: Fix and re-enable flaky tests

extensions/amp-consent/amp-consent.md
=> 📖 Fix syntax errors in amp-consent docs

extensions/amp-analytics/amp-analytics.md
- Fix json in documentation example
=> :book: Make json in the example valid

ads/giraff.js, ads/giraff.md
- Added widgetId optional parameter
=> ✨amp-ads: Added widgetId optional parameter for Giraff network

examples/visual-tests/amp-lightbox-gallery.html, test/visual-diff/visual-tests
This pretty much does nothing other than verify that lightbox doesn't kill normal UI. More logic pending interaction support from visual diff infrastructure.
=> Add visual test for lightbox gallery

extensions/amp-story/1.0/amp-story-bookend.css
=> 🐛 Apply font family to all elements inside the bookend

validator/README.md
Partially fixes https://github.com/ampproject/amphtml/issues/8022
still need windows installation
=> add osx installation of deps

examples/amp-story/bookendv1.json, extensions/amp-story/1.0/amp-story-share.js, extensions/amp-story/1.0/test/test-amp-story-bookend.js
=> 🐛 Fixes custom sharing parameters for amp-story bookend config v1.0

src/service/video/docking.js, test/functional/test-video-docking.js
Fixes #15403, #15402
(Also fixes an infinite timeout 😰)
=> 🐛Fix docking positioning bugs

examples/visual-tests/video/rotate-to-fullscreen.html, test/visual-diff/visual-tests
Simple check to ensure that the video is laid out normally with the attribute on.
=> ✅ Add visual test for rotate-to-fullscreen

build-system/tasks/lint.js
With #15444, we started linting the `.js` files in `validator/`. Since the directory still contains a handful of unfixed warnings, this PR exempts strict linting for the `validator/` directory. 
Follow up to #15444
=> 🏗 Exempt validator changes from strict linting

src/service/cid-impl.js
Just need an `@restricted` annotation
Part of #14761.
=> 🚮 Update CID's unused privates

extensions/amp-story/1.0/amp-story-bookend.css, extensions/amp-story/1.0/bookend/components/article.js, extensions/amp-story/1.0/bookend/components/cta-link.js, extensions/amp-story/1.0/bookend/components/heading.js, extensions/amp-story/1.0/bookend/components/landscape.js, extensions/amp-story/1.0/bookend/components/portrait.js, extensions/amp-story/1.0/bookend/components/text-box.js, extensions/amp-story/1.0/test/test-amp-story-bookend.js
♻️
* Adds common css class for bookend components to remove duplicate code.
* Cleans up strings in asserts.
* MIsc readability fixes.
=> ♻️ cleanups to amp-story bookend components

extensions/amp-bind/0.1/bind-impl.js
Context: https://github.com/ampproject/amphtml/pull/15408#discussion_r189420744
I thought the Promise constructor caused a lint error but I guess not.
=> Fix bind-impl.js nits

build-system/global-configs/prod-config.json
Master issue: https://github.com/ampproject/amphtml/issues/11575
This was already upped to 100% of canary last release.
=> Ramp up native srcset experiment to 10%

ads/google/imaVideo.js, extensions/amp-ima-video/0.1/amp-ima-video.js, extensions/amp-ima-video/validator-amp-ima-video.protoascii, src/service/video-manager-impl.js
Closes #10597.
\+ Drive-by cleanup
=> ✨ Support fullscreen API in <amp-ima-video>

extensions/amp-next-page/validator-amp-next-page.protoascii
Thanks to @bpaduch for finding the bug.
=> 🐛  amp-next-page: adding common attrs for script tag to validation rules

extensions/amp-story/0.1/test/validator-amp-story-consent.html, extensions/amp-story/0.1/test/validator-amp-story-consent.out, extensions/amp-story/1.0/test/validator-amp-story-consent.html, extensions/amp-story/1.0/test/validator-amp-story-consent.out, extensions/amp-story/validator-amp-story.protoascii
Validator update after moving the amp-story-consent JSON configuration.
Context: https://github.com/ampproject/amphtml/pull/15366/files/f48b29ca4203dd4cfce001b9555128d307551c7b#r189401119
Linked to #15473
=> Validator update after moving the amp-story-consent JSON configuration.

extensions/amp-geo/amp-geo.md
Adding a note to clarify that ISO country !== TLD in all cases - highlight GB/UK example
Related #15390
=> 📖🌐 Add note about uk/gb confusion

extensions/amp-consent/amp-consent.md
Adding FAQs for amp-consent and GDPR.
cc: @rudygalfi
=> Add FAQs about GDPR + amp-consent

examples/date-picker.amp.html
@cathyxz Thanks for reminding me of the `scrollable` attribute : P
=> 🐛 The fullscreen lightbox date-picker needs the scrollable attribute

contributing/getting-started-quick.md
- Changes references to git rebase to git merge
=> Update getting-started-quick.md to use merge instead of rebase

contributing/getting-started-e2e.md
-Changes the Getting Started End to End to use git merge rather than git rebase
=> 📖 Update getting-started-e2e.md to use merge instead of rebase

build-system/tasks/validator.js
=> validator: make gulp validator --update_tests work

src/service/video-manager-impl.js, src/service/video-service-interface.js, test/functional/test-video-rotate-to-fullscreen.js, test/integration/test-video-manager.js
=> 🐛 All actions should reflect that user interacted with video

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Partial for #15123.
If all's quiet after a week of 10% prod, let's go 100%.
=> ✨ Enable 'svg-in-mustache' in canary and 10% in prod

build-system/git.js
See https://github.com/ampproject/amphtml/pull/15503#discussion_r190072706 for context
Closes #15503
=> 🐛 Fix `git diff` commands used to determine changed files

CONTRIBUTING.md
Fix broken anchor/bookmark link.
=> Nit: fix bookmark link

3p/facebook.js, examples/facebook.amp.html
Without this PR the `data-order-by` attribute being set on `<amp-facebook-comments>` does nothing.
=> Propagate `data-order-by` attribute in `<amp-facebook-comments>`

extensions/amp-analytics/0.1/activity-impl.js, test/functional/test-activity.js
=> 🐛 Fix incrementalEngagedTime bug.

extensions/amp-consent/amp-consent.md
=> Added amp-ima-video doc link

extensions/amp-a4a/0.1/amp-a4a.js
=> 🐛: Release resource before detach when refresh ad slot 

ads/_config.js
* Enable `consentHandlingOverride` for Mediavine
=> Enable `consentHandlingOverride` for Mediavine

build-system/copy-abe-visual-test-pages.sh, build-system/enable-git-pre-push.sh
Address the problem in https://github.com/ampproject/amphtml/pull/15507#issuecomment-391470855
Follow up to #15507
=> 🐛 Don't use `realpath` in shell scripts

extensions/amp-next-page/0.1/test/validator-amp-next-page.html, extensions/amp-next-page/0.1/test/validator-amp-next-page.out
/cc @emarchiori email thread reminded me that neither did I :)
=> amp-next-page: validation tests

build-system/default-pre-push, build-system/tasks/bundle-size.js
=> 🐛 Clean up `pre-push` messages

src/service/cid-impl.js, src/service/viewer-cid-api.js
=> Fix lint JsDoc for *-cid-*.js

ads/_config.js, ads/yieldmo.js, examples/ads-legacy.amp.html, examples/ads.amp.html
Updating the Yieldmo adapter to use different js files. 
Also updating the Yieldmo samples with working test ads.
=> 🚀 Update the Yieldmo adapter to use the correct js files

extensions/amp-story/0.1/amp-story.css, extensions/amp-story/0.1/amp-story.js, extensions/amp-story/1.0/amp-story.css, extensions/amp-story/1.0/amp-story.js
Fixes #11857.
Fixes #13652.
Partial for #15562.
=> 🐛 Conditionally hide audio icon and show equalizer icon for stories

3p/github.js, 3p/iframe-transport-client.js, 3p/mathml.js, 3p/twitter.js
=> Fix lint JsDoc for 3p/*.js

examples/amp-story/bookendv1.html, extensions/amp-story/1.0/test/validator-amp-story-bookend-error.html, extensions/amp-story/1.0/test/validator-amp-story-bookend-error.out, extensions/amp-story/1.0/test/validator-amp-story-bookend.html, extensions/amp-story/1.0/test/validator-amp-story-bookend.out, extensions/amp-story/validator-amp-story.protoascii
Fixes #15589
Accepts layout attribute for amp-story-bookend tag.
=> 🐛 Accept layout attribute in amp-story-bookend tag

validator/build.py, validator/webui/build.py
- Remove unused yarn_version
- Use implicit string concatenation
=> build.py lint cleanups:

validator/engine/validator_test.js, validator/light/validator-light_test.js
Fix issue with validator tests where dotfiles in testdir will cause the test harness to fail.
=> Fix issue with validator tests regarding dotfiles

extensions/amp-geo/amp-geo.md
:book:  Made doc consistent with others - removed availability row + added row for ABE example link
=> Add ABE example link

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Forked from #15613.
/to @alabiaga
=> Allow doc-opt-in for 'disable-faster-amp-list'

extensions/amp-selector/amp-selector.md
Improve doc by adding link to ABE example.
=> Add link to ABE example

build-system/tasks/presubmit-checks.js, extensions/amp-a4a/0.1/amp-ad-template-helper.js, src/runtime.js, src/service/extensions-impl.js, src/service/url-impl.js, src/services.js, src/url.js, src/utils/lru-cache.js, test/functional/utils/test-lru-cache.js
Adds a `AmpDoc` service for parsing URLs.
Part of https://github.com/ampproject/amphtml/issues/14753
/cc @jpettitt
=> ✨ URL parsing service

extensions/amp-analytics/0.1/events.js, extensions/amp-analytics/0.1/iframe-transport-message-queue.js, extensions/amp-analytics/0.1/iframe-transport.js, extensions/amp-analytics/0.1/instrumentation.js
=> Fix lint JsDoc for amp-analytics/*.js

extensions/amp-analytics/0.1/vendors.js
This PR fixes analytics endpoint creation for the byside vendor
=> 🐛 Fix analytics byside vendor endpoint creation

extensions/amp-viewer-integration/CAPABILITIES.md
Most of these don't seem to be documented anywhere, let alone all in one place.
Descriptions are fairly basic for now (as I'm not entirely clear on what all of them do).
=> 📖 Add table with all valid viewer capabilities

extensions/amp-story/1.0/test/validator-amp-story-bookend-layout-error.html, extensions/amp-story/1.0/test/validator-amp-story-bookend-layout-error.out
=> Adds test to amp-story-bookend layout attribute

examples/visual-tests/amp-list/amp-list.amp.html, src/sanitizer.js, test/functional/test-sanitizer.js
And add a visual regression test.
=> Fix missing attrs with `svg-in-mustache`

ads/inabox/inabox-host.js, test/functional/inabox/test-inabox-host.js
=> Validate inabox pending messages, and print more specific errors.

package.json, yarn.lock
Upgrade web-activities to v1.11.0
=> WA upgrade to 1.11.0

extensions/amp-social-share/0.1/amp-social-share.js
Size of `amp-social-share.js` before gzip:
before: `15505`
after: `14277`
delta: `-7.9%`
=> ♻️ Remove src/url requirement from amp-social-share

extensions/amp-iframe/amp-iframe.md, spec/amp-actions-and-events.md
=> Remove two-way iframe messaging docs

build-system/default-pre-push, build-system/tasks/runtime-test.js
=> 🐛 Fix pre-push messages

extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js, extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js
Size before gzip:
Before: `8355`
After: `6367`
Delta: `-23.7%`
=> ♻️ Remove src/url requirement from amp-install-serviceworker

extensions/amp-analytics/0.1/test/test-amp-analytics.js, extensions/amp-analytics/0.1/test/test-iframe-transport-message-queue.js, extensions/amp-analytics/0.1/test/test-iframe-transport.js
=> Fix test-amp-analytics.js

build-system/eslint-rules/no-style-property-setting.js, test/fixtures/actions.html, test/integration/test-actions.js, testing/iframe.js
Fixes #15702.
Verified that this would've caught #15684.
/to @alabiaga /cc @aghassemi @jpettitt
=> Add integration tests for actions

ads/medyanet.js, ads/medyanet.md, examples/ads.amp.html
Added new custom ad-tag data parameter: Domain
=> Medyanet Ad Network Update for Domain Data 

build-system/tasks/bundle-size.js, src/service/url-expander/expander.js, src/service/url-replacements-impl.js, test/functional/url-expander/test-expander.js
Introduce option for synchronous url resolution with v2 expander.
There is a temporary build size increase, so that we can delete code once this is fully implemented.
=> Resolve url macros synchronously

build-system/global-configs/prod-config.json
This should go out with next week's release. Original issue: https://github.com/ampproject/amphtml/issues/11575.
=> Ramp up native srcset experiment to 70%

extensions/amp-install-serviceworker/amp-install-serviceworker.md
=> Disambiguate amp-install-sw docs

build-system/pr-check.js, build-system/tasks/karma.conf.js, build-system/tasks/runtime-test.js
=> Attempt to enable Safari 11.0 on SL

build-system/tasks/bundle-size.js
=> Fix master from bundle size after #15784

spec/amp-html-components.md
This change reflects the changed built-in components.
=> 📖 amp-html-components.md: Fix broken links

extensions/amp-next-page/0.1/amp-next-page.js, extensions/amp-next-page/0.1/config.js, extensions/amp-next-page/0.1/next-page-service.js, extensions/amp-next-page/0.1/test/test-amp-next-page.js, extensions/amp-next-page/0.1/test/test-config.js
`src/url` has been deprecated in favor of `Url` service.
/cc @peterjosling
=> ♻️ Remove src/url requirements from amp-next-page

extensions/amp-carousel/0.1/slidescroll.js, test/manual/amp-lightbox-carousel.amp.html
Closes https://github.com/ampproject/amphtml/issues/15772.
=> Fix carousel scroll on unlayout race condition trying to access non-existant slide

extensions/amp-story/0.1/amp-story.css, extensions/amp-story/1.0/amp-story.css
=> 🐛 Prevent setting min/max width/height on standalone amp-story elements

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
Version: 0.1.22.12
Previous release: 0.1.22.13
358: WA Upgrade to 1.11.0
357: SaveSubscription API to now accept a callback to retrieve the SaveSubscriptionRequest
356: Button Export
=> SwG release 0.1.22.13

extensions/amp-app-banner/0.1/amp-app-banner.js, extensions/amp-app-banner/0.1/test/test-amp-app-banner.js
Size before gzip:
before: `10649`
after: `9310`
delta: `-12.5%`
=> ♻️ Remove src/url requirement from amp-app-banner

build-system/amp.extern.js, extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/real-time-config-manager.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-a4a/0.1/test/test-real-time-config-manager.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Was a bit of a mess, maybe we can make it a little less of a mess. This is just a starting refactor to move it to a class, helps make things a little less crazy. still more work to do
=> Refactor Real Time Config code 

extensions/amp-story/0.1/amp-story-bookend.js, extensions/amp-story/0.1/amp-story-share.js, extensions/amp-story/0.1/related-articles.js
Since in some cases publishers might update their JSON config to use the 1.0 spec, they might not yet have the markup ready to comply with the amp-story 1.0 spec. We want to support this case to enable an easier transition.
=> ♻️ adds support for bookend config v1.0 in amp story v0.1.

extensions/amp-story/1.0/amp-story-bookend.css, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/bookend/amp-story-bookend.js, extensions/amp-story/1.0/bookend/bookend-component.js, extensions/amp-story/1.0/bookend/components/article.js, extensions/amp-story/1.0/bookend/components/bookend-component-interface.js, extensions/amp-story/1.0/bookend/components/cta-link.js, extensions/amp-story/1.0/bookend/components/heading.js, extensions/amp-story/1.0/bookend/components/landscape.js, extensions/amp-story/1.0/bookend/components/portrait.js, extensions/amp-story/1.0/bookend/components/text-box.js, extensions/amp-story/1.0/test/test-amp-story-bookend.js
=> ✨Adds AMP-to-AMP linking support in amp-story bookend components

extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
Simple update to documentation here to reflect the fact that fluid feature has launched and is no longer considered in beta.
@glevitzky @keithwrightbos @jasti FYI.
=> 📖Update doc to reflect Fluid status beta->launched

extensions/amp-story/1.0/_locales/ar.js, extensions/amp-story/1.0/_locales/de.js, extensions/amp-story/1.0/_locales/default.js, extensions/amp-story/1.0/_locales/en-GB.js, extensions/amp-story/1.0/_locales/es-419.js, extensions/amp-story/1.0/_locales/es.js, extensions/amp-story/1.0/_locales/fr-CA.js, extensions/amp-story/1.0/_locales/fr.js, extensions/amp-story/1.0/_locales/hi.js, extensions/amp-story/1.0/_locales/id.js, extensions/amp-story/1.0/_locales/it.js, extensions/amp-story/1.0/_locales/ja.js, extensions/amp-story/1.0/_locales/ko.js, extensions/amp-story/1.0/_locales/nl.js, extensions/amp-story/1.0/_locales/no.js, extensions/amp-story/1.0/_locales/pt-BR.js, extensions/amp-story/1.0/_locales/pt.js, extensions/amp-story/1.0/_locales/ru.js, extensions/amp-story/1.0/_locales/tr.js, extensions/amp-story/1.0/_locales/vi.js, extensions/amp-story/1.0/_locales/zh-TW.js, extensions/amp-story/1.0/_locales/zh.js
Adds translations for five new strings:
- `AMP_STORY_CONSENT_ACCEPT_BUTTON_LABEL`
- `AMP_STORY_CONSENT_DECLINE_BUTTON_LABEL`
- `AMP_STORY_CONSENT_DISMISS_DIALOG_BUTTON_LABEL`
- `AMP_STORY_DOMAIN_DIALOG_HEADING_LABEL`
- `AMP_STORY_DOMAIN_DIALOG_HEADING_LINK`
=> 🌐 Add translations for new batch of strings

test/functional/test-integration.js
=> Fix test-integration.js

extensions/amp-story/1.0/amp-story-info-dialog.css, extensions/amp-story/1.0/amp-story-info-dialog.js, extensions/amp-story/1.0/amp-story-store-service.js, extensions/amp-story/1.0/amp-story-system-layer.css, extensions/amp-story/1.0/amp-story-system-layer.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story-info-dialog.js, extensions/amp-story/1.0/test/test-amp-story-share-menu.js, extensions/amp-story/1.0/test/test-amp-story-store-service.js, extensions/amp-story/1.0/test/test-amp-story.js, gulpfile.js
This ports the info dialog that was added to amp-story 0.1 in #15130 to amp-story 1.0.
=> ♻️ Port amp-story info dialog to 1.0

3p/integration.js, ads/_config.js, ads/epeex.js, ads/epeex.md, examples/ads.amp.html, extensions/amp-ad/amp-ad.md, package.json
Add network logic
Add samples and doc
Update configuration files
Could you please review our commits?
Thanks
=> ✨Add New Ads Network - Epeex

extensions/amp-ad-network-doubleclick-impl/safeframe.md
Include description of resize and pos
=> Update sf docs

extensions/amp-call-tracking/amp-call-tracking.md, extensions/amp-facebook-comments/amp-facebook-comments.md, extensions/amp-facebook-like/amp-facebook-like.md, extensions/amp-facebook-page/amp-facebook-page.md, extensions/amp-google-vrview-image/amp-google-vrview-image.md, extensions/amp-reddit/amp-reddit.md, extensions/amp-timeago/amp-timeago.md
Improve docs by adding links to existing ABE demos.
cc: @sebastianbenz
=> Docs - add links to ABE demos

extensions/amp-story/1.0/bookend/components/article.js
From [this](https://user-images.githubusercontent.com/1492044/41115728-602d04c8-6a56-11e8-9ff8-fe7f6742a889.png).
=> Fixing the bookend article layout.

ads/_config.js, ads/ezoic.md
Adding consentHandlingOverride flag so Ezoic amp-ad can handle consent itself.
=> Add consentHandlingOverride flag to ezoic ampad

extensions/amp-position-observer/0.1/amp-position-observer.js, extensions/amp-position-observer/0.1/test/test-amp-position-observer.js, extensions/amp-position-observer/0.1/test/validator-amp-position-observer.html, extensions/amp-position-observer/0.1/test/validator-amp-position-observer.out, extensions/amp-position-observer/amp-position-observer.md, extensions/amp-position-observer/validator-amp-position-observer.protoascii
Fixes #11047.
TODO: Add tests.
=> Add ability to not trigger amp-position-observer after first iteration

extensions/amp-a4a/0.1/callout-vendors.js
Error ping url for Medianet Amp RTC vendor
=> Specify error reporting url for media.net RTC

build-system/tasks/bundle-size.js, src/service/url-expander/expander.js, src/service/url-replacements-impl.js, src/service/variable-source.js, test/functional/test-navigation.js, test/functional/url-expander/test-expander.js
Now supporting `opt_whiteList` && `opt_collectVars`.
=> ♻️Introduce more functionality to new expander.

.eslintrc, build-system/tasks/dep-check.js, src/error.js
=> Update eslint jsdoc preference

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
=> ♻️ amp-carousel: obsolete flag clean up

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js
=> Fix more test-amp-analytics.js failures due to expected console errors.

extensions/amp-bind/0.1/bind-impl.js
Fixes #15980. Partial for #15519.
Quick fix to allow up to 2000 bindings *after* user gestures. Would like to get this into canary cut today.
=> Increment binding limit by 500 on user gesture (up to 2000)

examples/amp-story/bookendv1.json, examples/amp-story/json/bookend.json, extensions/amp-story/1.0/amp-story-share.js, extensions/amp-story/1.0/bookend/amp-story-bookend.js, extensions/amp-story/1.0/bookend/bookend-component.js, extensions/amp-story/1.0/test/test-amp-story-bookend.js
=> Changes amp-story-bookend config to use camelcase

examples/bind/svgimage.amp.html, extensions/amp-bind/0.1/bind-validator.js, extensions/amp-bind/0.1/test/test-bind-validator.js
=> Add support for binding to svg image

extensions/amp-analytics/0.1/test/test-variables.js, test/functional/test-runtime.js
More console.error expectations!
=> ✅ Add `allowConsoleError`s in test-variables.js and test-runtime.js

build-system/tasks/bundle-size.js, src/service/video/autoplay.js, test/functional/test-video-autoplay.js
Related to #15750.
This matches the logic in production [as seen here](https://github.com/ampproject/amphtml/blob/2c64e317b30bd75b168ac4181683ccead3f47de2/src/service/video-manager-impl.js#L249).
=> 🐛 Honor visibility event to trigger autoplay

build-system/enable-git-pre-push.sh
Missed another incorrect message.
Follow up to #15711
Fixes #15709
=> 🐛 Fix git pre-push message

extensions/amp-bind/0.1/bind-expression.js
Should've been part of #14634.
=> Remove last amp-bind null warning

src/service/ampdoc-impl.js
=> 🐛 Only try to return an ampdoc shell if the ampdoc-shell experiment is on

test/size.txt
=> submit latest size for reference

extensions/amp-fx-collection/0.1/amp-fx-collection.js, extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js, extensions/amp-fx-collection/0.1/test/test-amp-fx-collection.js, tools/experiments/experiments.js
Fixes #14068. 
Waiting on final UX approval of ABE before launching.
=> Launch amp-fx='fly-in-*'

build-system/global-configs/prod-config.json
Part of https://github.com/ampproject/amphtml/issues/11575.
=> Ramp up native srcset experiment to 100%

extensions/amp-pan-zoom/0.1/amp-pan-zoom.js, extensions/amp-pan-zoom/0.1/test/integration/test-amp-pan-zoom.js, extensions/amp-pan-zoom/0.1/test/validator-amp-pan-zoom.html, extensions/amp-pan-zoom/0.1/test/validator-amp-pan-zoom.out, extensions/amp-pan-zoom/amp-pan-zoom.md, extensions/amp-pan-zoom/validator-amp-pan-zoom.protoascii, test/manual/amp-pan-zoom.amp.html
Adds API, Layout, Documentation, and Validation. Details at go/amp-pan-zoom.
=> Add default configurations and validation to amp-pan-zoom 

extensions/amp-3d-gltf/0.1/test/test-amp-3d-gltf.js
https://github.com/ampproject/amphtml/issues/16080
=> Skip flaky 3d-gltf test

extensions/amp-story/0.1/amp-story.css, extensions/amp-story/1.0/amp-story.css
=> 🖍 Update equalizer icon styles for amp-story

build-system/tasks/update-packages.js
/cc @aghassemi @nainar 
Closes #15260
=> Make sure all RAF are executed against the same window

extensions/amp-3d-gltf/0.1/test/test-amp-3d-gltf.js
Skipping flaky test that failed master builds:
https://travis-ci.org/ampproject/amphtml/jobs/393828581
https://travis-ci.org/ampproject/amphtml/jobs/393728819
=> Skip flaky test that timed out on master in test-amp-3g-ltgf

build-system/tasks/runtime-test.js, builtins/amp-img.js, test/functional/test-amp-img.js, test/integration/test-amp-img.js
Fixes https://github.com/ampproject/amphtml/issues/15769
=> Fix regex match -> exec bug in amp-img

ads/google/a4a/google-data-reporter.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js, extensions/amp-ad/0.1/amp-ad-3p-impl.js, validator/engine/validator_test.js
Fixes https://github.com/ampproject/amphtml/issues/16043
=> Amp-a4a move lifecycle report init to buildCallback

src/service/video-manager-impl.js, src/service/video/autoplay.js, test/functional/test-video-autoplay.js
Also removed a Vsync cycle since no measurements are made.
Closes #16108.
=> 📐 Reduce autoplay visibility ratio to 50%

examples/scroll.amp.html, extensions/amp-access-scroll/0.1/scroll-impl.js
Send additional URL information to Scroll's access, analytics, and iframe requests to support functionality and debugging.
=> Update various URL parameters for amp-access-scroll

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, build-system/tasks/bundle-size.js
Sets experiments added in #16136 to 0.01 in canary & production.
=> Add experiment fractions defined in #16136

extensions/amp-a4a/0.1/real-time-config-manager.js, extensions/amp-a4a/0.1/test/test-real-time-config-manager.js, src/consent-state.js
The current predicate is brittle and doesn't handle new states well.
=> Make consent state predicate handle new states

extensions/amp-sidebar/0.1/test/integration/test-amp-sidebar.js, test/functional/test-resources.js, test/integration/test-video-players-helper.js
Skip resource tests for Safari per https://github.com/ampproject/amphtml/issues/16156. 
Skip sidebar tests for Chrome per https://github.com/ampproject/amphtml/issues/16157
Skip amp-video tests per https://github.com/ampproject/amphtml/issues/16154
=> Skip all flaky tests on master today

examples/date-picker.amp.html, extensions/amp-date-picker/0.1/amp-date-picker.js, extensions/amp-date-picker/0.1/test/integration/test-integration-amp-date-picker-actions.js, extensions/amp-date-picker/amp-date-picker.md
amp-bind hooks coming soon, but this is more important for launch.
=> ✨✅ Add today actions and integration test them

test/visual-diff/visual-tests
=> Mark 4 more visual diff tests as flaky

extensions/amp-accordion/0.1/test/integration/test-amp-accordion.js, extensions/amp-accordion/validator-amp-accordion.protoascii, test/manual/amp-accordion-integration.amp.html, test/manual/amp-accordion.amp.html
Fixes https://github.com/ampproject/amphtml/issues/16143
Allow media attribute on amp-accordion.
=> Add media attribute to amp-accordion's validation

extensions/amp-form/0.1/amp-form.js, extensions/amp-form/amp-form.md
=> Update amp-form docs

extensions/amp-addthis/0.1/addthis-utils/monitors/active-tools-monitor.js, extensions/amp-addthis/0.1/addthis-utils/monitors/click-monitor.js, extensions/amp-addthis/0.1/addthis-utils/monitors/dwell-monitor.js, extensions/amp-addthis/0.1/addthis-utils/monitors/scroll-monitor.js, extensions/amp-addthis/0.1/addthis-utils/rot13.js, extensions/amp-fx-collection/0.1/providers/amp-fx-presets-utils.js, extensions/amp-fx-collection/0.1/providers/fx-provider.js, extensions/amp-viewer-integration/0.1/examples/amp-viewer-host.js, extensions/amp-viewer-integration/0.1/messaging/messaging.js
Adds jsDocs based on the function names
=> fixing types

src/service/navigation.js
Just needs a rubber stamp.
Re: https://github.com/ampproject/amphtml/pull/15731#discussion_r192501467. Missed that comment before merging it.
=> Add comment explaining test code conditional

src/service/video-manager-impl.js
=> 🐛 Fix selector to hide equalizer icon on interaction

build-system/tasks/presubmit-checks.js, examples/amp-consent.amp.html, extensions/amp-consent/0.1/amp-consent.js, extensions/amp-consent/0.1/consent-state-manager.js, extensions/amp-consent/0.1/test/test-consent-state-manager.js
=> ✨amp-consent: request on consent state change

test/manual/amp-pan-zoom.amp.html
Add the setting of the variable `scale` for each sample, otherwise it's confusing to understand what's going on.
@cathyxz PTAL
=> fix amp-pan-zoom sample

build-system/tasks/visual-diff.rb
Temporary mitigation for #16133 and #16228
=> 🏗✅ Don't run ABE visual tests for PR builds until flakes are disabled

test/functional/test-cid.js, test/functional/test-crypto.js
Partial fix for #14406
Partial fix for #16076
=> ✅ 🐛 Expect more errors in unit tests

examples/article-with-docked-video.html, src/service/video/docking.js, test/functional/test-video-docking.js
Fixes #15812
Also triggers `dock` and `undock`.
Minimizes only when the slot is positioned at the top. Logic to minimize to bottom coming up in a follow-up PR.
=> ✨ Minimize to slot element

spec/amp-cors-requests.md
Added "noshowtoc" so I can use the actual toc sidebar in the ampproject.org
=> Minor style added for ampproject rendering

extensions/amp-consent/0.1/amp-consent.js, extensions/amp-consent/0.1/test/test-amp-consent.js
=> Remove EXTERNAL_CONSENT_FLOW flag

extensions/amp-image-viewer/0.1/amp-image-viewer.js
Follow up refactor to https://github.com/ampproject/amphtml/issues/14936.
=> Get rid of isRelayoutNeeded and refactor to onMeasureChanged

extensions/amp-story/0.1/amp-story.js
- Same fix as  PR 15543, but applied to version 1.0
- Addresses issue #15404
=> Shows hint overlay on up swipe like version 1.0

extensions/amp-date-picker/0.1/test/integration/test-integration-amp-date-picker-actions.js, testing/iframe.js
Reverts ampproject/amphtml#16194
=> Revert "Fix flakes by swapping setInterval with setTimeout"

extensions/amp-date-picker/0.1/amp-date-picker.js, extensions/amp-date-picker/0.1/test/integration/test-integration-amp-date-picker-actions.js, extensions/amp-date-picker/0.1/test/test-amp-date-picker.js, extensions/amp-date-picker/amp-date-picker.md, tools/experiments/experiments.js
Closes #12267.
🚀Launching `amp-date-picker`!!
=> 🚮 Remove amp-date-picker experiment

build-system/tasks/karma.conf.js
Based on the documentation at https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-Timeouts
Fixes #16135 
Fixes #14848
=> 🏗 🐛 Adjust Sauce Labs timeouts to prevent disconnections

LICENSE
An accidental find/replace across the entire project seems to have caused a few mistakes in the LICENSE file.
Recommendation: Create a test that verifies the content of the LICENSE isn't changed by a commit (in a future PR).
=> 📖  Fix broken find/replace across project

extensions/amp-story/0.1/localization.js, extensions/amp-story/0.1/test/test-localization.js, extensions/amp-story/1.0/localization.js, extensions/amp-story/1.0/test/test-localization.js
=> 🐛 Default to English if the language is unspecified in amp-story 0.1

package.json, yarn.lock
See https://github.com/google/web-activities/releases/tag/1.13
=> Web Activities 1.13

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
See https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.14
=> SwG release 0.1.22.14
