ampproject/amphtml

- package.json
Addresses https://github.com/ampproject/amphtml/pull/16336#issuecomment-400182633
Follow up to #16336
> More Greenkeeper cleanup

- extensions/amp-subscriptions/0.1/amp-subscriptions.css
- extensions/amp-subscriptions/0.1/test/test-dialog.js
- extensions/amp-subscriptions/0.1/test/test-renderer.js
> 🐛 fix nested html issue.

- build-system/global-configs/prod-config.json
> 📈Increase percentage in new macro experiment

- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors.js
Update eulerian analytics:
* page tracking enhancements
* context flag added
> Update eulerian analytics

- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-rtc.js
Fixes https://github.com/ampproject/amphtml/issues/16407
> Fix verifyStillCurrent usage and add extra protection

- examples/date-picker.amp.html
- extensions/amp-date-picker/0.1/amp-date-picker.css
- extensions/amp-date-picker/0.1/amp-date-picker.js
- extensions/amp-date-picker/amp-date-picker.md
Since the preact/react-dates height bug has not yet been resolved, add a warning to inform users of the bug and how to prevent it from occurring.
/to @alanorozco @aghassemi 
/fyi @kristoferbaxter
> 🐛🖍Add a warning for non-default day-size values due to #13897

- README.md
Adds a banner to README for the AMP Contributor Summit.
> Add a banner to README for the AMP Contributor Summit

- extensions/amp-geo/0.1/test/test-amp-geo.js
> ✅Make amp-geo coverage 100%

- contributing/DEVELOPING.md
- test/functional/test-iframe-helper.js
- test/functional/test-iframe-stub.js
This PR unskips some tests and fixes the path of the code coverage report in the dev docs.
Soon, there should be a comment on this PR with details of the delta in code coverage.
> ✅ Unskip some tests and see the effect on coverage

- extensions/amp-geo/amp-geo.md
> 🐛 📖 clarify localdev doc

- examples/amp-story/access.html
- extensions/amp-story/1.0/amp-story-access.css
- extensions/amp-story/1.0/amp-story-access.js
- extensions/amp-story/1.0/amp-story-store-service.js
- extensions/amp-story/1.0/amp-story.css
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/test/test-amp-story-access.js
- extensions/amp-story/1.0/test/test-amp-story.js
- `amp-story-access` component
- `ACCESS_STATE` new story state
- `examples/amp-story/access.html` example
Part of #12180
> amp-story-access component drawer.

- extensions/amp-analytics/integrating-analytics.md
I found a lot of PRs fail to change the test file because we didn't document the requirement. We still want the test for every vendor right?
> 📖 Improve analytics integration PR instructions.

- build-system/pr-check.js
> Run integration tests on sauce labs in non coverage mode

- extensions/amp-experiment/0.1/amp-experiment.js
- extensions/amp-experiment/0.1/test/test-amp-experiment.js
- src/service/url-replacements-impl.js
> 🐛 Fix a race condition that may have caused experiment variants to not be available

- extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
PRs that alter code in the dependency graph of this file are unable to be submitted due to problems in this test file.
Related to #16545
> 🐛Skip broken tests

- spec/amp-html-format.md
This is a continuation of https://github.com/ampproject/docs/pull/1019#issuecomment-402299570, as inline styles are now allowed.
> 📖 Fix spec to reflect that inline styles are now allowed

- extensions/amp-apester-media/0.1/utils.js
- Feature: adapt Apester media's content to the user’s platform
> ✨Apester Media (extension): Added Platform Detection

- 3p/integration.js
- ads/_config.js
- ads/aja.js
- ads/aja.md
- examples/ads.amp.html
- extensions/amp-ad/amp-ad.md
Add support for new `AJA` network.
> #AJA re-PR

- build-system/global-configs/prod-config.json
> 📈Bump url-replacement-v2 experiment

- build-system/pr-check.js
Run unit and integration tests on Travis' Chrome until Sauce labs issues are ironed out.
Related to #16633
> 🔥🏗 Temporarily disable testing on Sauce Labs

- extensions/amp-subscriptions/0.1/amp-subscriptions.js
- extensions/amp-subscriptions/0.1/analytics.js
- extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
- extensions/amp-subscriptions/amp-subscriptions.md
- adds `subscriptions-access-granted`.
- adds `subscriptions-access-denied`.
> Subscriptions: adding new events

- src/mode.js
- src/validator-integration.js
- test/functional/test-validator-integration.js
> Add query param to bypass validation in dev mode.

- build-system/tasks/visual-diff.js
- test/visual-diff/visual-tests
Fixed #16133
I'll keep rerunning the integration tests and add mark flaky tests on this branch until I'm confident there are no more
> 🏗 Reenable ABE visual diffs

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
> Safari fix for Toast animation

- build-system/pr-check.js
- build-system/tasks/visual-diff.js
To fix the issue mentioned in https://github.com/ampproject/amphtml/pull/16390#issuecomment-401254376
> 🏗 `:%s/--verify/--verify_status/` in `gulp visual-diff`

- build-system/pr-check.js
> 🏗 Re-enable visual diff tests when running all commands in PR check

- build-system/pr-check.js
Fixes #16694.
/to @rsimha /cc @erwinmombay
> Disable bundle-size on non-master pushes

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
> SwG release 0.1.22.21

- extensions/amp-consent/amp-consent.md
Merge when 1530320824316 hit prod
> 📖External consent flow doc

- extensions/amp-sidebar/0.1/amp-sidebar.css
- extensions/amp-sidebar/amp-sidebar.md
Original PR by @ericlindley-g  see #16635. That PR was not merging to master but to a feature branch.
Not totally sure, but I think this is all that needs to happen to remove the 80vw restriction. (one of last two parts of https://github.com/ampproject/amphtml/issues/10587)
Closes #10587
> ✨amp-sidebar: Remove 80vw restriction for amp-sidebar

- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-list/0.1/amp-list.js
- src/log.js
TIL `dev().fine` is pruned in prod builds.
> Use dev().info for prod logging

- css/video-autoplay.css
- src/service/video-manager-impl.js
- src/service/video-service-sync-impl.js
> 🐛Show equalizer icon in 3p players without `controls`

- test/visual-diff/visual-tests
> ✅ Mark the <amp-jwplayer> visual diff test as flaky

- ads/mediavine.md
- Detail about user consent ad personalization
> 📖 Update Mediavine docs

- builtins/amp-pixel.js
- examples/analytics.amp.html
- extensions/amp-analytics/0.1/transport.js
- extensions/amp-analytics/amp-analytics.md
- src/pixel.js
- test/integration/test-amp-analytics.js
> Support referrerPolicy:no-referrer in amp-analytics

- gulpfile.js
With #16452, we started building two versions of the runtime: one with polyfills and one without. However, in minified mode, the PR ended up writing both the polyfill and non-polyfill version of `amp.js` to the same destination file in parallel. This race resulted in the error...
```
"Error: Found 2 AMP_CONFIG(s) before write. Aborting!"
```
This PR introduces the following fixes:
1. Writes the non-polyfill version of `amp.js` to a new file called `amp-esm.js`
2. In local development mode, makes sure the AMP config is correctly written to both the polyfill and non-polyfill versions (of minified and non-minfied builds)
3. Updates the build progress output to print out the destination filename (instead of the source filename) during a compilation / minification step
Follow up to #16452 …
> 🏗🐛 Build the polyfill and non-polyfill versions of the runtime into separate files

- extensions/amp-date-countdown/amp-date-countdown.md
> 📖 Update amp-date-countdown samples

- package.json
- yarn.lock
> 🚮 Remove `greenkeeper-lockfile`

- extensions/amp-lightbox-gallery/0.1/test/integration/test-amp-lightbox-gallery.js
> Skip amp-lightbox-gallery integration tests

- css/amp.css
- examples/everything.iframed.html
- examples/viewport.html
- src/service/viewport/viewport-binding-ios-embed-sd.js
- src/service/viewport/viewport-impl.js
- test/functional/test-viewport-binding.js
- test/functional/test-viewport.js
- tools/experiments/experiments.js
> Shadow root viewport binding for iOS

- build-system/runner/src/org/ampproject/AmpCommandLineRunner.java
- build-system/tasks/bundle-size.js
This reverts commit 457bf03b57f1ac38caf276b45fa30f34e8e5e245.
> Revert "fix flags passed into the custom runner (#16793)"

- examples/amp-story/doubleclick.html
- extensions/amp-story/1.0/amp-story-page.js
- src/friendly-iframe-embed.js
Also moved example from `test/manual` to `examples/`.
> ♻️Use built-in FIE checker

- build-system/base.js
- build-system/config.js
- build-system/get-dep-graph.js
- build-system/tasks/presubmit-checks.js
- build-system/tasks/update-packages.js
- src/polyfills.js
- src/service/extensions-impl.js
- test/manual/amp-single-pass-compilation.html
- testing/describes.js
- testing/iframe.js
Reverts ampproject/amphtml#16846
Broke running tests.
> Revert "Code-cleanup of splittable fork."

- build-system/amp.extern.js
- build-system/tasks/bundle-size.js
- src/runtime.js
- test/functional/test-runtime.js
extensions need to able to declare and lazy load intermediate module as dependencies
> add a way to load dependencies lazily through configuration

- extensions/amp-ad-network-doubleclick-impl/single-page-ad.md
Pointing to DoubleClick help center document for trafficking details.
> Updating with DoubleClick documentation

- extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
> 🚀sticky-ad measure background color before mutate

- extensions/amp-analytics/amp-analytics.md
> 📖: Update maxTimerLength doc

- extensions/amp-analytics/0.1/test/test-requests.js
> Fix test-requests.js error

- extensions/amp-a4a/0.1/amp-ad-type-defs.js
- extensions/amp-ad-network-adzerk-impl/0.1/amp-ad-network-adzerk-impl.js
> Fix a4a temps

- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
- src/custom-element.js
> amp-list: Reset when refreshing with local data

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/bookend/amp-story-bookend.js
- extensions/amp-story/1.0/events.js
- extensions/amp-story/1.0/pagination-buttons.js
- extensions/amp-story/1.0/test/test-amp-story.js
- This combines the dispatch() and dispatchCustom() calls in events.js in order to fix an issue in Internet Explorer
- Addresses issue #11520
> Combines dispatch utility events in amp-story

- build-system/tasks/visual-diff.js
> 🏗 Print progress ●'s for `gulp visual-diff` on Travis

- extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
- extensions/amp-ad/0.1/amp-ad-custom.js
- extensions/amp-analytics/0.1/activity-impl.js
- extensions/amp-analytics/0.1/events.js
- extensions/amp-analytics/0.1/instrumentation.js
- extensions/amp-analytics/0.1/test/test-vendors.js
- extensions/amp-bind/0.1/bind-validator.js
> ♻️ Replace direct `hasOwnProperty` with `src/utils/object.js#hasOwn` [extensions/amp-[a-b]*]

- 3p/3p.js
- 3p/embedly.js
- ads/adincube.js
- ads/adplugg.js
- ads/connatix.js
- ads/google/adsense.js
- ads/imonomy.js
- ads/ix.js
- ads/kiosked.js
- ads/medianet.js
- ads/sekindo.js
- ads/spotx.js
- ads/uas.js
> ♻️ Replace direct `hasOwnProperty` with `src/utils/object.js#hasOwn` [3p/ & ads/]

- src/experiments.js
- src/service/url-expander/expander.js
- src/service/url-replacements-impl.js
- test/functional/test-ads-config.js
> ♻️ Replace direct `hasOwnProperty` with `src/utils/object.js#hasOwn` [src/ and test/]

- .lgtm.yml
> 🏗 Exempt docs, tests, and third party code from LGTM analysis

- test/functional/test-cid.js
> Fix all silently passing tests in test-cid.js.

- ads/appnexus.js
render ads that are available but not rendered when the slot is above the fold and then scrolled into view
https://github.com/ampproject/amphtml/pull/14038/commits/8bbef696fa1e5dab078f12e1ee98a089b1b2ad14
render ads above the fold when scrolled to view
https://github.com/ampproject/amphtml/pull/14038/commits/197b1aa12559b819cd2c122749e35e46d1bdafb4
handle nobid, use promise-like pattern
https://github.com/ampproject/amphtml/pull/14038/commits/c336f63d51a6f7d153e855196d2190418d57605e
fix lint errors
https://github.com/ampproject/amphtml/pull/14038/commits/29d29d73333a8730d7197e6b04e36d05687943fb
remove whitespace
https://github.com/ampproject/amphtml/pull/14038/commits/65e2304c034c0b8dfd99af653302f717baceafcb
doc apntag.showTag
https://github.com/ampproject/amphtml/pull/14038/commits/a153ed …
> update referring to changeRequests from pull14038 containing:

- extensions/amp-fx-collection/0.1/test/validator-amp-fx-collection.html
- extensions/amp-fx-collection/0.1/test/validator-amp-fx-collection.out
- validator/validator-main.protoascii
> Remove restricted presets on "amp-fx" attribute

- spec/amp-cors-requests.md
Fixes #13708 
- Applied feedback per request in #13708.  
- Also rearranged and rewrote language to be more about "what should be done" vs "what we have".
> 📖 Update CORS guide per feedback

- spec/amp-var-substitutions.md
> 📖 totalTime doc improvement

- examples/amp-story/bookendv1.json
- extensions/amp-story/1.0/bookend/components/article.js
- extensions/amp-story/1.0/bookend/components/bookend-component-interface.js
- extensions/amp-story/1.0/bookend/components/landscape.js
- extensions/amp-story/1.0/bookend/components/portrait.js
> 🐛Display origin urls in bookend components for amp-story v1.0

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
> Remove amp-animations experiment from configs

- tools/experiments/experiments.js
> Cleanup animation experiment

- extensions/amp-pan-zoom/0.1/amp-pan-zoom.css
- extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
Closes https://github.com/ampproject/amphtml/issues/16926. 
/cc  @kul3r4
> Allow developers to set alignment by getting rid of inline styles for top and left

- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-a4a/0.1/callout-vendors.js
- extensions/amp-a4a/0.1/real-time-config-manager.js
- extensions/amp-a4a/0.1/test/fetch-mock.js
these type errors only show up on newer closure compiler versions
> fix a few a4a type mismatches

- build-system/tasks/runtime-test.js
Follow up to #16970
Follow up to #16878
Fixes #16851
> 🏗 Don't exit the Karma process during watch

- extensions/amp-access/0.1/amp-access.js
- extensions/amp-access/0.1/test/validator-amp-access-missing-extension.html
- extensions/amp-access/0.1/test/validator-amp-access-missing-extension.out
- extensions/amp-access/0.1/test/validator-amp-access.html
- extensions/amp-access/0.1/test/validator-amp-access.out
- extensions/amp-access/amp-access.md
- extensions/amp-access/validator-amp-access.protoascii
- extensions/amp-analytics/validator-amp-analytics.protoascii
> Remove analytics as a requirement for amp-access

- build-system/tasks/lint.js
> Print a list of files that were fixed after `gulp lint`

- build-system/amp4test.js
- build-system/pr-check.js
- build-system/tasks/runtime-test.js
- extensions/amp-sidebar/0.1/test/integration/test-amp-sidebar.js
- src/service/extension-location.js
- test/integration/test-errors.js
- test/integration/test-video-players-helper.js
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
> Fixing tests with single pass compilation and turn them on on travis.

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
Should shut off till fix for av is out
> Temporarily ramp down canonical adsense ff experiments

- extensions/amp-consent/0.1/amp-consent.js
- extensions/amp-consent/0.1/test/test-amp-consent.js
> 🐛: amp-consent stop collecting non dev error

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
> SwG release 0.1.22.22

- css/video-docking.css
- src/service/video/docking.js
> 🖍 Position dismiss button at corner, invert mute/unmute icons

- build-system/global-configs/prod-config.json
- build-system/tasks/bundle-size.js
No issues have been identified in canary.
> Turn on "font-display-swap" experiment in prod.

- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
> ✨Add more options for amp story ads CTA

- extensions/amp-consent/amp-consent.md
Documentation for #15290 
To document the list of pre-defined consent policy we introduced.
> 📖 Predefined consent policy documentation

- extensions/amp-consent/amp-consent.md
Merge when 1530320824316 hit prod
> 📖 on consent update request documentation 

- contributing/component-validator-rules.md
Some of these fields have changed names recently, updating documentation.
> Update validator rule examples

- extensions/amp-story/amp-story.md
> 📖 Adds docs for AMP-to-AMP linking in amp-story-bookend

- package.json
- yarn.lock
> 🏗🐛 Move puppeteer and @percy/puppeteer to devDependencies

- build-system/amp4test.js
Looks like the `req.query.css` variable was rendered into the html template string as `undefined`. This resolves that.
> 🐛Fix <style amp-custom>undefined</style>

- extensions/amp-addthis/amp-addthis.md
- Prefix the title with an emoji to identify what is being done. (Copy-paste from the list below.)
🔥 P0 fix (`:fire:`)  
✅ Tests …
> correct the usage example of amp-addthis extension

- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
- test/manual/amp-lightbox-gallery.amp.html
Closes https://github.com/ampproject/amphtml/issues/16608. 
Details in issue ^^.
> Fix lightbox gallery doesn't work in SSR bug

- test/visual-diff/visual-tests
> ✅ Mark amp-kaltura-player and amp-brightcove visual diff tests as flaky

- examples/date-picker.amp.html
- extensions/amp-date-picker/0.1/amp-date-picker.js
- extensions/amp-date-picker/0.1/test/integration/test-integration-amp-date-picker-actions.js
Addresses overlay opening behavior mentioned in #16716
> 🐛Prevent overlay flash on clear

- extensions/amp-pan-zoom/validator-amp-pan-zoom.protoascii
/to @cathyxz @honeybadgerdontcare
> Add amp-pan-zoom to experimental validator format

- extensions/amp-mustache/0.1/test/validator-amp-mustache-version.out
- extensions/amp-mustache/validator-amp-mustache.protoascii
https://github.com/ampproject/amphtml/issues/17138#issuecomment-408462207
/to @alin04 /cc @honeybadgerdontcare
> amp-mustache: Un-deprecate 0.1

- extensions/amp-story/1.0/test/test-amp-story.js
Stub replaceState only once in `test-amp-story`.
> ♻️ Stub replaceState only once.

- src/purifier.js
> Whitelist amp-fit-text attributes on amp-list

- test/visual-diff/visual-tests
> ✅ Disable amp-story visual diff tests, as they are flaky

- extensions/amp-auto-ads/0.1/ad-strategy.js
- extensions/amp-auto-ads/0.1/placement.js
> amp-auto-ads: report debugging info in log level "info".

- extensions/amp-addthis/amp-addthis.md
- Prefix the title with an emoji to identify what is being done. (Copy-paste from the list below.)
🔥 P0 fix (`:fire:`)  
✅ Tests …
> 📖 <amp-addthis> Correct readme for data-* usage

- src/purifier.js
- test/functional/test-purifier.js
- test/functional/test-sanitizer.js
Fixes #17181.
@cvializ I think those are all the special amp-form attributes, anything I missed?
> Support submitting, verify-error in amp-mustache-0.2

- test/visual-diff/visual-tests
Thanks @gmajoulet for noticing!
> ✅ Mark the `<amp-o2-player>` visual diff test as flaky

- extensions/amp-auto-ads/0.1/placement.js
- extensions/amp-auto-ads/0.1/test/test-placement.js
> 🐛amp-auto-ads: wait customElement to be ready before calling attemptChangeSize

- extensions/amp-date-picker/0.1/test/integration/test-integration-amp-date-picker-actions.js
Master was turning red
https://travis-ci.org/ampproject/amphtml/jobs/409996261
https://travis-ci.org/ampproject/amphtml/jobs/410039876
> ✅🐛Skip flaky amp-date-picker AMP action integration tests

- examples/date-picker.amp.html
- extensions/amp-date-picker/0.1/amp-date-picker.js
- extensions/amp-date-picker/amp-date-picker.md
- extensions/amp-date-picker/validator-amp-date-picker.protoascii
Fixes https://github.com/ampproject/amphtml/issues/17082
/to @aghassemi 
/cc @ericlindley-g @mdiblasio
> ✨Enable the minimum-nights attribute

- spec/amp-versioning-policy.md
Linking not in markdown format.
> 📖Fix #announcements link

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
Latest Subscribe with Google release.
> swg release 0.1.22.23

- spec/amp-html-components.md
- spec/amp-html-format.md
This contributes to[ /doc issue 1027](https://github.com/ampproject/docs/issues/1027)
> 📖 Updated information on inline styling allowed in AMP

- extensions/amp-mustache/0.1/test/validator-amp-mustache-version.out
- extensions/amp-mustache/validator-amp-mustache.protoascii
Reverts ampproject/amphtml#17154
> Revert "amp-mustache: Un-deprecate 0.1"

- build-system/internal-version.js
- build-system/tasks/compile.js
- gulpfile.js
> 🚮 Remove the internalRuntimeToken

- extensions/amp-geo/amp-geo.md
Added validation section, which is a standard part of component docs.
fyi: @CrystalFaith
> 📖Added validation section

- extensions/amp-instagram/amp-instagram.md
> 📖 Fix typo in amp-instagram docs

- extensions/amp-analytics/0.1/crc32.js
- extensions/amp-analytics/0.1/test/test-crc32.js
Adds a standard (?) CRC32 implementation. Includes some test cases that should be easily copy & paste-able for analytics vendors.
> ✓ CRC32 Implementation

- build-system/tasks/compile.js
https://github.com/ampproject/amphtml/pull/17251/files#r207411908
> Missed one gulp replace

- extensions/amp-story/1.0/amp-story.css
Fixing the RTL CSS selectors for the loading spinner and equalizer.
Sorry I missed it during the code review. :(
Fixes #17276
> Fixing the RTL CSS selectors for the loading spinner and equalizer.

- build-system/global-configs/canary-config.json
> Enable CSS scroll snap experiment on carousels

- extensions/amp-analytics/0.1/variables.js
- src/utils/base64.js
- test/functional/utils/test-base64.js
Also use it for the `$BASE64` Macro.
cc/ @zikas
> ♻️Single method for unicode base64Url(str)

- build-system/global-configs/prod-config.json
> Url Replacement Experiment Bump

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
> Remove 3p-use-ampcontext flag.

- extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
- src/service/resource.js
- test/functional/test-resource.js
This is the real fix for #17223.
Reverts #17225.
Fixes #17228.
Fixes #17280.
> 🐛✨First onMeasureChanged even if unchanged after build

- examples/google-document-embed.amp.html
- extensions/amp-bind/0.1/bind-validator.js
- extensions/amp-google-document-embed/0.1/amp-google-document-embed.js
- extensions/amp-google-document-embed/0.1/test/validator-amp-google-document-embed.html
- extensions/amp-google-document-embed/0.1/test/validator-amp-google-document-embed.out
- extensions/amp-google-document-embed/validator-amp-google-document-embed.protoascii
Last feature before launch of `amp-google-document-embed` (#16907)
> ✨Enable amp-bind for amp-google-document-embed source attr

- extensions/amp-list/amp-list.md
> Document new amp-list attributes

- extensions/amp-carousel/0.1/slidescroll.js
Addresses: #16508 
Decided on this curve after discussion with @spacedino.
> Change animation curve in amp-carousel

- extensions/amp-live-list/amp-live-list.md
Contributes to [issue #787](https://github.com/ampproject/docs/issues/787)
> 📖 Updated wording to clarify user interaction and DOM updates in amp-live-list

- CONTRIBUTING.md
New contributors may be confused by our use of emojis in pull request. This provides a quick key. 
Resolves [issue  #16902](https://github.com/ampproject/amphtml/issues/16902).
> 📖 Added pull request emoji key for new contributors

- examples/auto-ads.amp.html
- extensions/amp-auto-ads/0.1/ad-network-config.js
- extensions/amp-auto-ads/0.1/ad-strategy.js
- extensions/amp-auto-ads/0.1/amp-auto-ads.js
- extensions/amp-auto-ads/0.1/placement.js
- extensions/amp-auto-ads/0.1/test/test-ad-network-config.js
- extensions/amp-auto-ads/0.1/test/test-ad-strategy.js
- extensions/amp-auto-ads/0.1/test/test-placement.js
- src/layout-rect.js
- test/functional/test-layout-rect.js
- tools/experiments/experiments.js
Only use full-width responsive for auto ads in AMP.
> Enforce full-width responsive for all auto ads.

- extensions/amp-story/1.0/test/test-amp-story.js
Fixes all the `Cannot read property '__AMP_TOP' of null` errors in our `test-amp-story` file.
If a test doesn't call `layoutCallback`, the following lines 
````
element = win.document.createElement('amp-story');
win.document.body.appendChild(element);
````
in the `beforeEach` of the next test will fail because `element.ownerDocument.defaultView` will be undefined.
> Fix amp-story tests.

- extensions/amp-image-slider/0.1/amp-image-slider.js
> ✨amp-image-slider add ARIA

- extensions/amp-google-document-embed/0.1/amp-google-document-embed.js
- extensions/amp-google-document-embed/0.1/test/test-amp-google-document-embed.js
- extensions/amp-google-document-embed/amp-google-document-embed.md
- tools/experiments/experiments.js
Remove the experiment and update the docs to link to the ABE for `amp-google-document-embed`
/to @cathyxz @aghassemi 
/cc @jaygray0919
> ✨ Launch amp-google-document-embed

- extensions/amp-image-slider/amp-image-slider.md
Stumbled on this doc and performed some doc cleanup for consistency and clarity.  When this component is ready to use, further cleanup will be required to clarify the navigation language and flesh out the rest of the doc (e.g., validation, overview, etc.)
fyi: @CrystalFaith
> Doc cleanup of amp-image-slider

- extensions/amp-3d-gltf/amp-3d-gltf.md
> Added link to ABE example

- extensions/amp-bind/0.1/bind-validator.js
- extensions/amp-bind/0.1/test/test-bind-validator.js
- extensions/amp-bind/amp-bind.md
- extensions/amp-lightbox/0.1/amp-lightbox.js
- extensions/amp-lightbox/validator-amp-lightbox.protoascii
Fixes #17334.
Open to suggestions for the binding name. Tested manually, will add unit tests soon.
/to @aghassemi
> amp-lightbox: Add [open] binding

- ads/_config.js
- ads/teads.md
Adding consentHandlingOverride flag to Teads
> add consentHandlingOverride flag for Teads

- extensions/amp-image-slider/validator-amp-image-slider.protoascii
- validator/testdata/feature_tests/amp-image-slider.html
- validator/testdata/feature_tests/amp-image-slider.out
> ✨amp-image-slider P0 validator rules

- extensions/amp-image-slider/0.1/amp-image-slider.js
> 🐛 amp-image-slider add Edge non-standard keycode

- builtins/amp-pixel.md
- extensions/amp-analytics/amp-analytics.md
Added info about stripping out usqp parameter for custom analytics requests.
Fixes #12621
> 📖 Added info on usqp parameter

- CONTRIBUTING.md
- contributing/building-an-amp-extension.md
Improvements to Building an AMP Extension doc (aesthetic mostly):
- Added TOC 
- Provided visual layout of directory structure
- Improved information for writing component doc
> 📖 Improve layout and info for building extension doc

- extensions/amp-story/1.0/amp-story-bookend.css
> 🐛 fix margin for cta links in bookend

- validator/validator-main.protoascii
> Allow style attribute on SVG tag

- extensions/amp-carousel/0.1/slidescroll.js
See here for reason: https://github.com/ampproject/amphtml/pull/17431/files#r209392880.
Must merge this in before: https://github.com/ampproject/amphtml/pull/17438
> Redisable CSS Scrol Snap for iOS 10.3

- extensions/amp-image-slider/0.1/amp-image-slider.css
> 🐛 amp-image-slider hide/show hint easing/timing update

- build-system/global-configs/canary-config.json
Turning this on since we have merged fix #17366 into the 1% canary and landed #17367
> Turn on CSS Scroll Snap experiment again.

- build-system/tasks/firebase.js
- build-system/tasks/presubmit-checks.js
- Copy over dist.3p directory
- Change the thirdPartyUrl to just be on the same origin as the page so that it works
> 🏗Make 3p frames work with firebase task.

- build-system/global-configs/canary-config.json
> Enable 'faster-bind-scan' in canary

- extensions/amp-twitter/0.1/amp-twitter.css
- extensions/amp-twitter/0.1/amp-twitter.js
- Move some stuff that should be in measure/mutate into the proper
phase.
- Add a static and fade out version of the loader.
- Make sure fade out placeholder does not move/resize when the size of `<amp-twitter>` changes.
For #17171
> ✨Add two variations for the Twitter loading state.

- extensions/amp-ad/amp-ad.md
Fix the documentation to reflect the correct order.
> Ad doc fix

- extensions/amp-bind/0.1/bind-impl.js
- src/json.js
- test/functional/test-json.js
> amp-bind: Check equality to depth of 10

- src/host-services.js
- src/inabox/host-services.js
The API consists of 3 services:
- visibility
- fullscreen
- exit
Those services are being used by extensions needed to function in inabox env.
Those services are to be implemented by separate inabox extensions, like `amp-mraid.js` or `amp-safeframe.js`.
For #16557
> Introduce Host API  for inabox.

- extensions/amp-video/0.1/amp-video.js
- src/base-element.js
Fixes #15965.
/to @aghassemi /cc @sparhami
> Move video prerender-able check to firstAttachedCallback

- spec/amp-var-substitutions.md
> Update URL substitution doc to indicate URL host cannot be substituted

- extensions/amp-mustache/amp-mustache.md
/to @CrystalFaith /cc @jpettitt
> amp-mustache: Better version notes and quote-escaping tips

- spec/amp-email-format.md
/to @jasti @CrystalFaith /cc @raywainman
> AMP4EMAIL: Recommend text/html MIME part last

- build-system/check-package-manager.js
When an AMP package update is necessary during the normal development workflow, a `yarn` install is automatically done as part of `gulp update-packages`. Prior to the install, we check to make sure the versions of `node` and `yarn` are up to date, and print warnings if any of them are outdated, or if a global `gulp` is detected. However, it often happens that the warning messages scroll by quickly, and go unnoticed. This recently resulted in the AMP toolchain bug #17513 going undetected.
This PR inserts a pause if an outdated toolchain is detected. It isn't mandatory to fix immediately, and developers may press any key to continue with the install.
```
$ yarn
yarn install v1.3.2
$ node build-system/check-package-manager.js
WARNING: Detected node version v8.9.4. Recommended (latest LTS) …
```
> 🏗 Pause `yarn` install when an outdated toolchain is detected

- validator/testdata/amp4email_feature_tests/amp_form.html
- validator/testdata/amp4email_feature_tests/amp_form.out
This was a merge error in PR #17521.
🐛✅🚮
> Delete old amp4email test per cl/208519413.

- extensions/amp-mustache/amp-mustache.md
Fixes: https://github.com/ampproject/docs/issues/1106
> 🔥  Correct syntax to fix docs build

- contributing/buildcop.md
Publishes docs describing the buildcop role and tasks.
/cc @erwinmombay
> Publish buildcop docs

- contributing/DEVELOPING.md
Adds a link to the buildcop & release documentation to DEVELOPING.md.
> Adds link to buildcop & release docs to DEVELOPING.md

- examples/amp-story/access.html
- extensions/amp-story/1.0/amp-story-access.css
- extensions/amp-story/1.0/amp-story-access.js
- extensions/amp-story/1.0/amp-story-store-service.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/test/test-amp-story.js
- Implementing the access navigation flow
- Better desktop animation
- Tests
Part of #12180
> amp-story-access blocking paywalls.

- extensions/amp-story/1.0/amp-story-consent.css
Update amp-story-consent max-height on desktop.
> Update amp-story-consent max-height on desktop.

- extensions/amp-story/OWNERS
> 🏗 Update amp-story OWNERS

- build-system/global-configs/prod-config.json
Launching the experiment in prod after three weeks of canary (#17060).
Part of #17017
> Launch the amp-story-navigation-performance experiment in prod.

- GOVERNANCE.md
> 📖 Barb moved on

- extensions/amp-story/1.0/amp-story-access.js
Allow users to dismiss the amp-story-access component so they can browse the pages they have access to again.
Related to #12180
> Allow users to dismiss the amp-story-access component.

- spec/amp-cache-modifications.md
Do not remove json+ld from AMP Caches.
> Update amp cache best practices

- extensions/amp-date-countdown/0.1/test/validator-amp-date-countdown.html
- extensions/amp-date-countdown/0.1/test/validator-amp-date-countdown.out
- extensions/amp-date-countdown/validator-amp-date-countdown.protoascii
Handling comment on https://github.com/ampproject/amphtml/pull/16648#pullrequestreview-147366162 and adding tests.
> ♻️ amp-date-countdown: Updated validator rule and tests

- build-system/global-configs/canary-config.json
> Enable no-initial-intersection on canary.

- extensions/amp-story/1.0/amp-story-consent.js
- extensions/amp-story/1.0/test/test-amp-story-consent.js
Assert that the publisher logo src is a URL in amp-story-consent.
> Assert that the publisher logo src is a URL in amp-story-consent.

- extensions/amp-story/1.0/amp-story-access.css
- extensions/amp-story/1.0/amp-story-bookend.css
- extensions/amp-story/1.0/amp-story-consent.css
- extensions/amp-story/1.0/amp-story.css
Using `text-align: start;` over `left` in `amp-story`.
> Using text-align: start; over left in amp-story.

- extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
- test/manual/amp-pan-zoom-initial.amp.html
- test/manual/amp-pan-zoom-positioning.amp.html
- test/manual/amp-pan-zoom.amp.html
Closes https://github.com/ampproject/amphtml/issues/17417. 
This probably needs multiple device testing.
> Update zoom / pan bounds based on offset from center

- extensions/amp-twitter/0.1/test/validator-amp-twitter.out
- extensions/amp-twitter/validator-amp-twitter.protoascii
- validator/validator-main.protoascii
- cl/209662636 Revision bump for #17455
- cl/209666395 Sort attribute names, amp-twitter
> Validator rollout

- extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
> Update broken sticky ad link

- extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
> Update broken sticky ads link

- src/purifier.js
- test/functional/test-purifier.js
> amp-mustache-0.2: Fix unwhitelisting of default attributes bug

- extensions/amp-analytics/amp-analytics.md
- extensions/amp-analytics/integrating-analytics.md
> Update doc for iframe transport

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
> Change AMP Auto Ads responsive experiment to 0.1% 

- src/service/navigation.js
- src/utils/priority-queue.js
- test/functional/test-navigation.js
- test/functional/utils/test-priority-queue.js
> Allow same priority when registering anchor mutators.

- examples/image-slider.amp.html
- extensions/amp-image-slider/0.1/amp-image-slider.js
- extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
- extensions/amp-image-slider/amp-image-slider.md
- extensions/amp-image-slider/validator-amp-image-slider.protoascii
- test/manual/amp-image-slider.amp.html
- validator/testdata/feature_tests/amp-image-slider.html
- validator/testdata/feature_tests/amp-image-slider.out
> ✨📖✅ [amp-image-slider] Expose P2 features

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
This will allow us to experiment with the different loading states.
> Allow twitter placeholder flags to be set via url.

- src/service/document-info-impl.js
- src/service/url-replacements-impl.js
- test/functional/test-document-info.js
- test/functional/test-url-replacements.js
To fix #17671 
cc @brandondiamond
> Fix sourceUrl when there's no replaceParams

- build-system/global-configs/canary-config.json
> ✨ Enable Layers in Canary

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
Had to separate this out due to pr rules.
> 👨🏻‍🔬Allow doc opt-in of linker experiment

- examples/image-slider.amp.html
- extensions/amp-image-slider/0.1/amp-image-slider.js
- extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
- extensions/amp-image-slider/0.1/test/test-amp-image-slider.js
> ✨ [amp-image-slider] Remove user experiment asserts

- examples/amp-story/access.html
- extensions/amp-story/1.0/amp-story-desktop.css
[Screenshot](https://user-images.githubusercontent.com/1492044/44657688-ab2b5880-a9cb-11e8-96e8-6ff1f03720b6.png)
Part of #12180
> Blur next desktop page if protected behind a paywall.

- build-system/global-configs/prod-config.json
> Enable no-initial-intersection flag in prod.

- build-system/tasks/bundle-size.js
- src/service.js
- src/service/extensions-impl.js
- src/service/timer-impl.js
- test/functional/test-activity.js
- test/functional/test-cid.js
- test/functional/test-extensions.js
- test/functional/test-focus-history.js
- test/functional/test-history.js
- test/functional/test-input.js
- test/functional/test-timer.js
- test/functional/test-viewer.js
- test/functional/test-viewport.js
- test/functional/test-vsync.js
- testing/describes.js
- testing/fake-dom.js
- testing/iframe.js
> Make timer service embeddable

- extensions/amp-analytics/0.1/test/test-variables.js
- extensions/amp-analytics/0.1/variables.js
Async expandTemplate is unnecessary.
> Refactor variables.js

- extensions/amp-story/1.0/amp-story-access.css
Fixing `pointer-events` on `amp-story-access` to allow scroll.
Related to #12180
> Fixing pointer-events on story access to allow scroll.

- build-system/tasks/presubmit-checks.js
- src/amp-shadow.js
- src/amp.js
- src/chunk.js
- src/error.js
- src/inabox/amp-inabox-lite.js
- src/inabox/amp-inabox.js
- src/style-installer.js
- test/functional/test-style-installer.js
Create separate function to be called by error case. Remove `opt_waitForServices`  from the original function. 
Manually tested that this does in fact solve the tasty bug. 
Closes #16334
> ♻️Refactor makeBodyVisible

- contributing/building-an-amp-extension.md
> 📖 Improve building an extension docs

- extensions/amp-mustache/amp-mustache.md
Context: 
https://github.com/ampproject/amphtml/issues/11205#issuecomment-327942911
`b/113342222`
/to @jridgewell @CrystalFaith
> Add 'Pitfalls' section to amp-mustache docs

- extensions/amp-story/1.0/amp-story-access.css
Notification paywall desktop design reviews.
[Screenshot](https://user-images.githubusercontent.com/1492044/44810831-fc407580-aba0-11e8-9fae-e404c45cb60a.png)
Related to #12180
> Notification paywall desktop design reviews.

- extensions/amp-story/1.0/amp-story-access.css
- extensions/amp-story/1.0/amp-story-consent.css
- extensions/amp-story/1.0/amp-story-info-dialog.css
- extensions/amp-story/1.0/amp-story-share-menu.css
- extensions/amp-story/1.0/amp-story.css
As seen with Hong, this PR makes the background overlays darker.
> Darken opacity background overlays.

- extensions/amp-story/1.0/amp-story-system-layer.css
- Force the text to `#fff`
- Adding a shadow under the text for better accessibility
- Vertical alignment for the text
> Audio help text style improvements.

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
> SwG release 0.1.22.25

- examples/amp-story/access.html
- extensions/amp-story/1.0/test/validator-amp-story-access.html
- extensions/amp-story/1.0/test/validator-amp-story-access.out
- extensions/amp-story/1.0/test/validator-amp-story-cta-layer-error.out
- extensions/amp-story/validator-amp-story.protoascii
Updates the validation rules to allow the `amp-story-access` component.
Partial for #12180
> Story access component validator.

- 3p/integration.js
- ads/_config.js
- ads/runative.js
- ads/runative.md
- examples/ads.amp.html
- extensions/amp-ad/amp-ad.md
Implement native ad of "runative" ads network
> ✨ Implementation of runative ad

- extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
- extensions/amp-pan-zoom/0.1/test/test-amp-pan-zoom.js
- test/manual/amp-pan-zoom-initial.amp.html
- test/manual/amp-pan-zoom.amp.html
Fixes https://github.com/ampproject/amphtml/issues/17617.
> Fix pinch zoom to corner bug

- extensions/amp-addthis/0.1/addthis-utils/lojson.js
- extensions/amp-addthis/0.1/amp-addthis.js
this reads were breaking in single pass
> fix typedef so that JsonObject prop reads are detected by type checker

- extensions/amp-consent/0.1/test/test-amp-consent.js
Introduce helper function to make tests cleaner
> ✅♻️ : Make amp-consent test cleaner

- css/video-autoplay.css
- extensions/amp-addthis/0.1/addthis-utils/pixel.js
- extensions/amp-analytics/0.1/iframe-transport.js
- extensions/amp-analytics/0.1/transport.js
- extensions/amp-form/0.1/amp-form.css
- extensions/amp-form/0.1/test/test-validation-bubble.js
- extensions/amp-form/0.1/validation-bubble.js
- extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js
- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
- extensions/amp-next-page/0.1/next-page-service.js
- extensions/amp-social-share/0.1/amp-social-share.js
- extensions/amp-story/0.1/amp-story-share-menu.js
- extensions/amp-story/0.1/amp-story.js
- extensions/amp-story/1.0/amp-story-share-menu.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-web-push/0.1/iframehost.js
- src/layout.js
- src/service/fixed-layer.js
- src/service/video-manager-impl.js
These are the easy ones to fix.
Part of #17475.
> ♻️ Use toggle instead of setStyle

- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
Was working on tests for #17000 and noticed several things that should be fixed. 
/to @alabiaga
> Clean up amp-list SSR code and rework unit tests.

- src/custom-element.js
- src/service/layers-impl.js
Fixes https://github.com/ampproject/amphtml/issues/17837.
> Layers: Remove element when it detaches

- extensions/amp-analytics/0.1/amp-analytics.js
- extensions/amp-analytics/0.1/test/test-transport.js
- extensions/amp-analytics/0.1/transport.js
This is a preparation PR before we can introduce more stuff to transport layer.
Related to #15729
> Make Transport a real class

- extensions/amp-consent/0.1/amp-consent.js
- extensions/amp-consent/0.1/test/test-amp-consent.js
- src/json.js
- test/functional/test-json.js
Introduce the `getSingleChildJsonConfig` helper method for components to read their json config with shared code.
> getSingleChildJsonConfig helper method

- build-system/tasks/changelog.js
> fix help info

- contributing/building-an-amp-extension.md
address @cathyxz last comment in #17731
> add snippet about cleaning up experiment

- extensions/amp-image-slider/amp-image-slider.md
- tools/experiments/experiments.js
> 📖🚮[amp-image-slider] Remove remaining experimental marks

- extensions/amp-story/1.0/amp-story-share.js
- extensions/amp-story/1.0/toast.js
> 🐛 Appends toasts to the story instead of the body

- extensions/amp-analytics/0.1/linker-manager.js
- extensions/amp-analytics/0.1/test/test-linker-manager.js
Double negatives are hard to comprehend.
> 🐛Linker `proxyOrigin` should default to true

- build-system/tasks/bundle-size.js
- extensions/amp-animation/0.1/amp-animation.js
- extensions/amp-video/0.1/amp-video.js
- src/layout.js
- src/service/fixed-layer.js
- src/service/viewport/viewport-binding-ios-embed-sd.js
- src/shadow-embed.js
- src/style.js
> Allow setting the initial display style of an element

- build-system/tasks/bundle-size.js
- extensions/amp-consent/0.1/amp-consent.css
- extensions/amp-consent/0.1/amp-consent.js
- extensions/amp-consent/0.1/test/test-amp-consent.js
> ♻️Move amp-consent to toggle compatible implementation

- extensions/amp-analytics/0.1/linker.js
- extensions/amp-analytics/0.1/test/test-linker-manager.js
- extensions/amp-analytics/0.1/test/test-linker.js
> Update linker format.

- src/service/viewport/viewport-binding-ios-embed-sd.js
- test/functional/test-viewport-binding.js
> iOS Embed SD viewport: prevent webkit-overflow-scrolling paint bug

- extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
- extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-input.js
relates to #17867
relates to #2273
This is a follow up PR to a PR comment on the layoutCallback() possibly being called multiple times. Therefore, Added a gaurd boolean to prevent multiple registration/unregistration.
> ✨ Fixed amp-recaptcha-input Registration layoutCallback() Race Condition

- extensions/amp-analytics/0.1/linker-manager.js
- extensions/amp-analytics/0.1/test/test-linker-manager.js
Closes #17954
/cc @calebcordry
> Support default linker config.

- extensions/amp-consent/0.1/amp-consent.js
- extensions/amp-consent/0.1/test/test-amp-consent.js
- test/manual/amp-consent-cmp.html
create iframe w/ promptUISrc
TODO in following PR: apply placeholder and hide iframe before iframe ready.
> ✨ AMP consent v2: support promptUISrc

- extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
- extensions/amp-pan-zoom/0.1/amp-pan-zoom.css
- extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
- extensions/amp-pan-zoom/0.1/test/test-amp-pan-zoom.js
- testing/test-helper.js
Closes https://github.com/ampproject/amphtml/issues/17845
TODO:
> Add desktop panning with mouse events

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
Clean up the experiment related configs.
> Remove amp-img-native-srcset related configs.

- tools/experiments/experiments.js
> Remove amp-img-native-srcset from experiments.

- src/3p-frame.js
- test/integration/test-3p-frame.js
- tools/experiments/experiments.js
…if required sandbox flags are supported (which they are widely).
Implements #14240
> Apply a sandbox to all 3p ad iframes

- extensions/amp-analytics/0.1/vendors.js
#16763 accidentally removed it
> Add krux config back

- extensions/amp-story/1.0/amp-story.js
> 🐛Stops incorrect titles appearing with mouse hover on story bookend

- extensions/amp-analytics/0.1/linker-manager.js
- extensions/amp-analytics/0.1/test/test-linker-manager.js
- test/functional/test-platform.js
It works on desktop Safari 12
Still looking for a real iOS12 device to test out.
> Only auto enable linker on Safari 12+

- build-system/conformance-config.textproto
- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-list/0.1/amp-list.js
- extensions/amp-story/0.1/amp-story.js
- extensions/amp-story/1.0/amp-story.js
- src/history.js
- src/service/history-impl.js
- src/service/viewer-impl.js
Fixes https://github.com/ampproject/amphtml/issues/18008.
>  Guard access to History.p.state

- extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
Attempt to fix the flaky test. The original test didn't handle the timer stub correctly somehow.
> Attempt to fix 3p-ad-impl flaky test

- build-system/pr-check.js
This PR makes it so that when *only* unit test files are changed, we run just those tests that were modified instead of running all ~8000 unit tests. This should make Travis builds faster and more reliable without losing any test coverage.
Fixes #15813
> 🏗🐛 When a PR only changes unit test files, run just those tests that were changed

- extensions/amp-brid-player/OWNERS.yaml
per https://github.com/ampproject/amphtml/pull/18021#issuecomment-421410798 @pedjoni8 is the new owner.
> amp-brid-player: update owner

- extensions/amp-story/0.1/test/test-amp-story-system-layer.js
> ✅ Skip flaky amp-story test

- extensions/amp-story/1.0/amp-story-system-layer.css
> 🐛Ensures white colored text for audio messages

- extensions/amp-story/1.0/amp-story-desktop.css
> 🖍 Fade between amp story backgrounds on desktop page switch

- extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.27
> SwG release 0.1.22.27

- build-system/global-configs/canary-config.json
> Re-enable Layers in Canary

- build-system/tasks/bundle-size.js
Master is red: https://travis-ci.org/ampproject/amphtml/jobs/429835146#L603
> 🏗 Bump bundle size

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
> Set 1% experiment for Doubleclick Idle Fix

- validator/testdata/feature_tests/regexps.html
- validator/testdata/feature_tests/regexps.out
- validator/validator-main.protoascii
Resolves the recent comments in #15100.
> Update the stylesheet URL regular expression to support old fontawesome

- extensions/amp-consent/0.1/amp-consent.js
- extensions/amp-consent/0.1/consent-ui.js
- extensions/amp-consent/0.1/test/test-amp-consent.js
- extensions/amp-consent/0.1/test/test-consent-ui.js
Create the consentUI class where the placeholder logic will be added to later. 
PTAL. Thanks!
> ♻️ ConsentUI class

- ads/_config.js
- ads/teads.js
Update of  Teads Ads CDN entry point and prefetch config to reflect infrastructure migration
> ♻️Updated Teads Ads CDN entry point and prefetch config

- ads/nativo.md
Simple change on the example HTML, and messaging on how to contact Nativo.
> :book: Nativo: Updated example HTML and config messaging.

- examples/bind/carousels.amp.html
- extensions/amp-selector/0.1/amp-selector.js
- extensions/amp-selector/0.1/test/test-amp-selector.js
Context: `b/115690618#comment5`
> amp-selector: Support [disabled] binding

- extensions/amp-consent/0.1/amp-consent.js
Fix #18261 
Fortunately the fallback behavior is correct...
> 🐛Use hasOwn to avoid false value

- extensions/amp-analytics/0.1/analytics-root.js
- extensions/amp-analytics/0.1/config.js
- extensions/amp-analytics/0.1/events.js
- extensions/amp-analytics/0.1/iframe-transport-message-queue.js
- extensions/amp-analytics/0.1/iframe-transport.js
- extensions/amp-analytics/0.1/requests.js
- extensions/amp-analytics/0.1/test/test-config.js
- extensions/amp-analytics/0.1/transport.js
- extensions/amp-analytics/0.1/variables.js
- extensions/amp-analytics/0.1/visibility-manager.js
> Unify all TAG string format in amp-analytics extension.

- test/integration/test-video-players.js
> ⏪Unskip amp-brid-player tests

- contributing/getting-started-e2e.md
> Improve testing section in "getting-started-e2e.md"

- extensions/amp-youtube/0.1/test/test-amp-youtube.js
Related issues: #18085
I fixed spelling.
> fix spelling favour into favor

- extensions/amp-access-scroll/0.1/scroll-impl.js
amp-access-scroll coordinates with the Scroll App on Safari browsers when unable to authorize normally
> ✨Implement Scroll App connect flow for Safari

- examples/visual-tests/amp-by-example/samples_templates/product_page/source/index.html
Closes https://github.com/ampproject/amphtml/issues/18104. Changes `colour` to `color`
@nainar please review
> ♻️Fix spelling issue in product page source

- spec/amp-var-substitutions.md
Change "whitelisted" to "white listed"
Closes #18096
> closes Issue #18096

- extensions/amp-instagram/amp-instagram.md
Correct spelling in amp-instagram.md from 'attept' to 'attempt'. Closes Issue #18094.
> 📖amp-instagram.md: Spelling Correction from attept to attempt (ACS Codelab 13)

- examples/visual-tests/amp-by-example/components/amp-accordion/embed/index.html
Prefer American spelling: behaviour -> behavior. Closes #18105. 🎊
/cc @cathyxz
> 📖Spelling tweaks for consistency

- spec/amp-html-format.md
- Changed all instances of whitelist[ed] to white list[ed] 
- closes #18325
> 🐛ACS-15: Changed all instances of whitelist[ed] to white list[ed]

- examples/visual-tests/amp-by-example/components/amp-accordion/source/index.html
- Change 'behaviour' to 'behavior'.
- Closes #18107
> ♻️ change 'behaviour' to 'behavior' #18107

- test/integration/test-video-players.js
Reverts ampproject/amphtml#17628 which was just merged by is causing flakes 
Closes #18328
> Revert "⏪Unskip amp-brid-player tests"

- extensions/amp-date-picker/0.1/test/validator-amp-date-picker.html
- extensions/amp-date-picker/0.1/test/validator-amp-date-picker.out
- extensions/amp-date-picker/validator-amp-date-picker.protoascii
Fixes https://github.com/ampproject/amphtml/issues/16904
> 🐛Add missing date, start-date, end-date attrs to amp-date-picker

- src/video-interface.js
This PR is for [issue 18075 [ACS - Beginner codelab only - 18]](https://github.com/ampproject/amphtml/issues/18075)
♻️Resolve spelling inconsistency from `behaviour` to `behavior` , @nainar please review!
> ♻️Resolve spelling inconsistency from behaviour to behavior

- extensions/amp-timeago/OWNERS.yaml
> Add OWNERS.yaml file for amp-timeago

- extensions/amp-bind/0.1/bind-expr-impl.js
Change the UK spelling of "behaviour" to US spelling of "behavior"
Closes issue https://github.com/ampproject/amphtml/issues/18079
> ACS: 18079 - Spelling inconsistencies

- examples/visual-tests/amp-by-example/visual_effects/basics_of_scrollbound_effects/embed/index.html
- examples/visual-tests/amp-by-example/visual_effects/basics_of_scrollbound_effects/index.html
- examples/visual-tests/amp-by-example/visual_effects/basics_of_scrollbound_effects/source/index.html
- extensions/amp-image-slider/amp-image-slider.md
- test/visual-diff/visual-tests
> :book: Fix typo for overlayed to overlaid (#18086)

- extensions/amp-story/1.0/_locales/fr.js
Update amp-story french translations.
> Update amp-story french translations.

- extensions/amp-story/1.0/amp-story-system-layer.css
Fixes https://github.com/ampproject/amphtml/issues/17376
@Enriqe
> GFI: 17376 - amp-story share pill not hidden with embedMode=2

- contributing/getting-started-quick.md
Add a command to retrieve the upstream/master ref to a fork.
This closes Issue 18322
> 🐛Add command to fetch the upstream ref

- ads/appnexus.md
Added a new example to AppNexus AST Example page that contains keywords.
> 📖 Add AST AMP Example with Keywords

- extensions/amp-date-picker/0.1/amp-date-picker.js
This feature was documented but something happened to the implementation along the way. 
Fixes https://github.com/ampproject/amphtml/issues/17951
> 🐛 Fix missing assignment to highlighted and blocked

- src/service/video-manager-impl.js
Rectify spelling inconsistency in video-manager-impl.js
Closes  #18077
> 📖Change the UK spelling of "Behaviour" to US spelling of "Behavior"

- src/utils/math.js
Rectify spelling inconsistency in math.js
This closes Issue 18076
> 🐛 Change spelling 'behaviour' to 'behavior'

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/media-pool.js
- Partially addresses #17985 ("Video should not be paused and rewinded during the animation, but after, so the animation doesn't look too "jumpy")
> ✨Smoothen transition between videos in stories

- extensions/amp-date-picker/0.1/test/test-amp-date-picker.js
> ✅ Test date picker highlighted and blocked src attributes

- testing/describes.js
> Remove setting of global sandbox in describes

- extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
Update loadPromise to this.baseInstance_.loadPromise in the amp iframe handler.  Closes Issue #5294.
> 🐛Update loadPromise to this.baseInstance_.loadPromise

- build-system/conformance-config.textproto
- test/functional/test-layout.js
> Test nodisplay SSR

- extensions/amp-analytics/0.1/amp-analytics.js
- extensions/amp-analytics/0.1/test/test-amp-analytics.js
> 🐛✨ Analytics: Support boolean enabled value 

- src/service/variable-source.js
- test/functional/test-variable-source.js
Removed due to suggestion in #18271 that caching is dangerous, and should be avoided.
> ♻️Remove caching of GlobalVariableSource Expr

- extensions/amp-analytics/0.1/amp-analytics.js
- extensions/amp-analytics/0.1/cookie-writer.js
- extensions/amp-analytics/0.1/linker-reader.js
- extensions/amp-analytics/0.1/linker.js
- extensions/amp-analytics/0.1/test/test-cookie-writer.js
- extensions/amp-analytics/0.1/test/test-linker-reader.js
- extensions/amp-analytics/0.1/test/test-linker.js
- src/url.js
- src/utils/base64.js
- test/functional/test-url.js
- test/functional/utils/test-base64.js
- test/manual/amp-analytics-cookie-writer.html
> ✨Analytics: LINKER_PARAM binding

- extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js
- extensions/amp-nexxtv-player/0.1/test/test-amp-nexxtv-player.js
The structure of video urls for our player has changed a little bit.
old:
https://embed.nexx.cloud/761/71QQG852413DU7J
new: 
https://embed.nexx.cloud/761/video/71QQG852413DU7J
> ♻️ nexxtv-player minor change in building video source

- extensions/amp-subscriptions/0.1/platform-store.js
Fix misspelled @const annotation.
Fix typos and grammar in comments.
✨ New …
> Fix typos in comments

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
- Added startTimeMs attribute for latency measurement (#422)
- Login Flow doc - Fix function name (#421)
- Adding IsReadyToPay bit to the XHR response (#419)
- adding optional IsReadyToPay field in entitlements (#410)
- Fix link flow doc (#413)
- Fix deferred account creation doc (#409)
- Upgrade Web Activities to 1.14 (#412)
- Refactor pay-flow to establish PayClient interface for ease of migration (#408)
- A simple experiment system (#407)
- Revert "Disable pay prefetch" (#405)
- Disable pay prefetch (#404)
- Rename uuid.swg.js to uuid-swg.js (#403)
- Initial commit of uuid utils (#402)
> SwG release 0.1.22.28

- extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
- extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
- extensions/amp-subscriptions/0.1/platform-store.js
- extensions/amp-subscriptions/0.1/score-factors.js
- extensions/amp-subscriptions/0.1/test/test-platform-store.js
- extensions/amp-subscriptions/amp-subscriptions.md
> Separate login logic from subscribe and change default of supportsViewer to 0

- build-system/tasks/compile.js
Fixes master breakage (#18552) due to dumb mistake in a code readability change.
> Fix bug in regex matching in compile.js

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
See #18597 removing code portions
> remove doubleclickIdleExp experiment

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
> SwG release 0.1.22.29

- contributing/getting-started-e2e.md
Related to #15119.
Adds specifying java version in env variables of bash profile.
> 📖 Specifies adding env variable for java version

- ads/connatix.md
> added quotes to documentation

- extensions/amp-pinterest/amp-pinterest.md
Fixes issue [#1082](https://github.com/ampproject/docs/issues/1082)
> updated pinterest Pin It language to Save

- validator/validator-main.protoascii
Validator change.
Resolves #18546
> Add the BiP Messenger scheme to anchor href attributes.

- build-system/tasks/bundle-size.js
@erwinmombay Could we force merge this one to unblock patching canary. Thanks
> Increase bundle size for patch canary

- extensions/amp-selector/amp-selector.md
Closes issue[ #1200](https://github.com/ampproject/docs/issues/1200)
> Added documentation on keyboard-select-mode

- extensions/amp-list/amp-list.md
Part 2 of 2 to resolve issue [#18619](https://github.com/ampproject/amphtml/issues/18619)
[Part 1](https://github.com/ampproject/docs/pull/1231)
> added sample of styling for content fetched in amp-list

- extensions/amp-brightcove/0.1/amp-brightcove.js
- extensions/amp-brightcove/0.1/test/test-amp-brightcove.js
- improve tests for amp-brightcove
- refactoring to align with tests
- changed log strings to literals for #18636
> ✅amp-brightcove: Extend test coverage

- src/form.js
- test/functional/test-form.js
Fixes https://github.com/ampproject/amphtml/issues/18744
> 🐛Do not submit value for empty multiselect

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
A couple of pages used in manual testing (contain cidapi meta tag && amp-form) 
https://www.dailystar.co.uk/tv/big-brother/734609/Big-Brother-2018-housemate-Isabella-Hussain-new-Isaac-evicted/amp
https://www.eventbrite.co.uk/e/free-travel-from-south-shields-to-the-peoples-vote-march-tickets-51073377848/amp
> 👨🏻‍🔬Turn on linker-form experiment

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
Launch the `amp-story-hold-to-pause` experiment in Canary.
#18714
> Launch the amp-story-hold-to-pause experiment in Canary.

- extensions/amp-analytics/linker-id-receiving.md
Corrects a typo in extensions/amp-analytics/linker-id-receiving.md
> 📖 Fixes typo in extensions/amp-analytics/linker-id-receiving.md

- contributing/TESTING.md
Specially the `firebase init` phase.
> Add more detailed instructions for gulp firebase

- build-system/tasks/presubmit-checks.js
- src/service/storage-impl.js
As discussed in #17742, this is pre work to support storing consent string.
> Allow storing non boolean value to localStorage

- build-system/app-index/template.html
> 🏗 Set `target=_blank` on header links

- extensions/amp-3d-gltf/amp-3d-gltf.md
> 📖 amp-3d-gltf: Document CORS requirements.

- build-system/app-video-testbench.js
Except `amp-video-iframe`, which is being added on #18802.
> ✨ Support all players in video testbench

- build-system/global-configs/canary-config.json
https://www.youtube.com/watch?v=YzSJBowPECY
> Disable Layers in canary

- extensions/amp-date-picker/amp-date-picker.md
Fixes #18371 
Documents and provides examples and a generator for RFC 5545 RRULE dates.
/to @CrystalFaith for review
> 📖Provide an explanation and examples of ISO 8601 and RFC 5545

- extensions/amp-bind/0.1/amp-state.js
- extensions/amp-bind/0.1/test/test-amp-state.js
> Support "refresh" action on amp-state

- extensions/amp-script/0.1/amp-script.js
- extensions/amp-script/0.1/test/validator-amp-script.html
- extensions/amp-script/0.1/test/validator-amp-script.out
- extensions/amp-script/OWNERS.yaml
- extensions/amp-script/validator-amp-script.protoascii
- tools/experiments/experiments.js
/to @kristoferbaxter @honeybadgerdontcare
> amp-script: Validation and experiment

- extensions/amp-consent/0.1/consent-ui.js
There might be a race condition in the way `amp-consent` shows the consent UI:
1. `amp-consent` hides its children
2. `<amp-element layout="nodisplay">` gets built, and runtime hides it because of the `layout="nodisplay"` attribute
3. `amp-consent` shows `amp-element`
Sometimes `amp-consent` resolves before `amp-element layout="nodisplay"` is built. It results in 2 happening AFTER 3, hiding the consent UI.
It does repro fairly often on [this amp-story](https://animalsake.com/raising-goats#amp-geo=FR) (~1 in 15 times).
I deployed minified before/after the fix versions on Firebase, but I can't get any of them to fail :(
- [Before](https://stamp-consent-nodisplay-before.firebaseapp.com/examples/amp-story/goats.html)
- [After](https://stamp-consent-nodisplay-after.firebaseapp.com/examples/amp- …
> Fixing race condition sometimes hiding the consent UI.

- validator/gulpjs/owers.yaml
sebastianbenz doesn't owe us anything.
> 🚮 Remove owers.yaml.

- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors/dynatrace.js
Updated the URL parameter from referer to url
Fix for https://github.com/ampproject/amphtml/issues/18739
> 🐛 Adapt dynatrace vendor parameter in amp-analytics to the new URL format #18739

- build-system/app.js
- extensions/amp-form/0.1/amp-form.js
- extensions/amp-form/0.1/test/test-amp-form.js
- src/form-data-wrapper.js
- test/functional/test-form-data-wrapper.js
- test/functional/test-xhr-fetch-polyfill.js
- test/functional/test-xhr.js
Fixes #18022
/to @nainar @aghassemi
> 🐛Remove empty file objects from native form data.

- extensions/amp-access/amp-access.md
- extensions/amp-subscriptions/amp-subscriptions.md
> 📖  Fix minor typo in amp-subscriptions and amp-access doc

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
https://github.com/ampproject/amphtml/issues/17475
> Enable hidden-mutation-observer experiment

- extensions/amp-inputmask/0.1/amp-inputmask.js
> 🐛Fix copypaste reference error

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.34
> SwG release 0.1.22.34

- src/service/fixed-layer.js
- test/functional/test-fixed-layer.js
- testing/fake-dom.js
- tools/experiments/experiments.js
Now when an element is toggled (hidden or un-hidden), the `FixedLayer` will run an update.
Fixes #17475
Fixes #16554
Fixes #16933
Depends on #18788
> ✨ Update FixedLayer on Element Hidden Toggle

- examples/amp-story/access.html
Fix amp-story/access.html example since the [amp-by-example API changed](https://github.com/ampproject/amp-by-example/commit/a35abe9c37021dc74e8f6d819bb969668a053d7a#diff-04921688a13ecee77e98c890b29d505eL36).
> Fix amp-story/access.html example.

- gulpfile.js
commented out some code to fix master. cause lint issues to break master =/
> Fix lint issue

- gulpfile.js
temporary fix for https://github.com/ampproject/amphtml/issues/18934
> remove appending of local amp_config to esm since we stopped generating it

- build-system/conformance-config.textproto
- extensions/amp-date-picker/0.1/amp-date-picker.js
> 🐛Fix Element.prototype.closest call breaking IE

- examples/analytics-vendors.amp.html
- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors/upscore.js
Add upScore as an analytics vendor to amp-analytics
Intent To Implement: #18626
> ✨Adding upScore as an analytics vendor to amp-analytics

- build-system/amp4test.js
- test/integration/test-amp-pixel.js
- testing/describes.js
Adds tests for amp-pixel to expand macros.
> ✅Introduce more amp-pixel integration tests

- extensions/amp-consent/0.1/consent-policy-manager.js
> Stop reporting expected error

- examples/anim-worklet.amp.html
- extensions/amp-animation/0.1/web-animations.js
- src/service/viewport/viewport-impl.js
- third_party/closure-compiler/externs/web_animations.js
- tools/experiments/experiments.js
Things to still be done:
- Only use AnimationWorklet when animation is tied to `amp-position-observer`
> Add WorkletAnimation to amp-animation.js

- validator/testdata/feature_tests/leaks.out
- validator/testdata/feature_tests/noscript.html
- validator/testdata/feature_tests/noscript.out
- validator/validator-main.protoascii
Resolves the noscript parts of #18965
> Add support for <noscript><picture><source>.

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/page-advancement.js
Allow resuming a TimeAdvancement after being paused.
Fixes #18990
> Allow resuming a TimeAdvancement after being paused.

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
> Update experiment for scroll-height-bounce to be "on" in canary and "off" in prod

- examples/article-with-docked-video.html
- src/service/video/docking.js
Also updated example to:
1. match ABE
2. be updated for the separate actions triggered.
> ✨ Trigger docking actions from slot or video

- extensions/amp-bind/amp-bind.md
related: https://github.com/ampproject/amphtml/pull/18836
> update docs for amp-state refresh support

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.35
> SwG release 0.1.22.35

- package.json
Fixes Travis PR builds breaking due to Node LTS version moving from 8 to 10
Sample build https://travis-ci.org/ampproject/amphtml/builds/448458060?utm_source=github_status&utm_medium=notification
> 🏗 Update package.json node version. Fixes PR builds.

- ads/google/a4a/test/test-utils.js
- ads/google/a4a/utils.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
This parameter reports when the AMP document started load as an epoch timestamp on Google AMP ad tags.
> ✨ Add domLoadingTime to ad requests

- build-system/dep-check-config.js
- extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js
- extensions/amp-analytics/0.1/test/test-amp-analytics.js
- extensions/amp-analytics/0.1/test/test-variables.js
- extensions/amp-analytics/0.1/variables.js
- src/service/url-expander/expander.js
- src/service/url-replacements-impl.js
- src/service/variable-source.js
- tools/experiments/experiments.js
> 🗑Remove old url replacement code

- src/service/navigation.js
- src/service/viewport/viewport-impl.js
Fix element focus issue for IE
Fixes #18671
> [#18671], Fix a11y issue for IE platform

- build-system/amp.extern.js
- build-system/compile-wrappers.js
- build-system/single-pass.js
- bundles.config.js
- examples/date-picker.amp.html
- extensions/amp-date-picker/0.1/amp-date-picker.js
- extensions/amp-date-picker/0.1/date-picker-common.js
- extensions/amp-date-picker/0.1/date-range-picker.js
- extensions/amp-date-picker/0.1/dates-list.js
- extensions/amp-date-picker/0.1/defaultPhrases.js
- extensions/amp-date-picker/0.1/single-date-picker.js
- extensions/amp-viz-vega/0.1/amp-viz-vega.js
this fixes amp-viz-vega and amp-date-picker which rely on 3p code
> add a way to post process append 3p files to our js binaries

- src/service/video/docking.js
> Fix docking overlay/shadow not being sized

- src/service/navigation.js
> 📖  Update code documentation for IE11 A11Y fix

- src/service/fixed-layer.js
Writing it down since I keep forgetting what these criteria are and why they exist.
> Better fixed-layer transferability comment

- 3p/3d-gltf/viewer.js
- ads/ads.extern.js
- examples/amp-3d-gltf.amp.html
- extensions/amp-3d-gltf/0.1/amp-3d-gltf.js
- extensions/amp-3d-gltf/amp-3d-gltf.md
pr for https://github.com/ampproject/amphtml/issues/18276
> ✨ amp-3d-gltf: Add action to rotate model

- build-system/global-configs/prod-config.json
Launch story hold to pause experiment after a successful user testing session.
Closes #18714
> Launch story hold to pause experiment.

- extensions/amp-animation/0.1/amp-animation.js
- extensions/amp-animation/0.1/web-animations.js
- extensions/amp-position-observer/0.1/amp-position-observer.js
- src/service/action-impl.js
This also passes along the values for the `intersection-ratio`s however, those aren't used. Can split that up into a separate PR if needed.
> [ANIMATION WORKLET] Calculate viewport-margins for scroll linked animation

- build-system/amp4test.js
- build-system/tasks/presubmit-checks.js
- test/integration/test-amp-analytics.js
PR #19118 introduced a bug in request-bank related test.  Only URL params were used as key.
> Fix amp4test request-bank

- extensions/amp-form/0.1/amp-form.js
Fixes the lint message raised by https://github.com/ampproject/amphtml/pull/18636 for `amp-form`
> ♻️Remove non-string log messages

- ads/zen.js
Add internal param to config of renderWidget function that needs to some zen-plathform features
> ♻️ Add internal param to embed-zen config

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
To fix P0 #19136
Please lmk if this is not the change that's needed to disable the experiment that's causing the bug
> 🏗Fix p0 caused by hidden-mutation-observer experiment

- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors/gemius.js
amp-analytics dnt variable for Gemius
> amp-analytics: Gemius dnt param

- examples/analytics-reportWhen.amp.html
reportWhen, with documentation and unit tests, was added in #18847. This PR additionally adds an example.
> Add example for reportWhen usage

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
> swg 0.1.22.37 release

- extensions/amp-animation/0.1/web-animations.js
Next step:
Turn on tests for all of WorkletAnimationRunner.
> [ANIMATION WORKLET ] Support `intersection-ratios` 

- extensions/amp-date-picker/0.1/amp-date-picker.js
@cvializ do you mind testing a before and after for this functionality in single pass (I dont know how to test it).
> ensure that startDate and endDate are preserved keys. these come from react

- validator/validator-main.protoascii
> allow attribution and sizes on img within noscript

- extensions/amp-analytics/0.1/linker-manager.js
- extensions/amp-analytics/0.1/test/test-linker-manager.js
Also refactor the tests a bit so that multiple handlers can be registered.
> 🐛Don't auto opt in linker twice

- src/service/fixed-layer.js
- test/functional/test-fixed-layer.js
> Sync fixed-layer attributes with body

- ads/google/csa.md
Removing beta language since this functionality is used broadly and not subject to whitelisting.
> Update csa.md to remove beta language

- extensions/amp-script/0.1/test/validator-amp-script.out
- extensions/amp-script/validator-amp-script.protoascii
> Invalidate amp-script

- extensions/amp-script/amp-script.md
/to @kristoferbaxter @cramforce /cc @CrystalFaith
> amp-script: First-pass documentation

- validator/nodejs/package.json
- validator/package.json
- validator/webui/package.json
Addresses https://github.com/ampproject/amphtml/pull/19159#issuecomment-437989479
Follow up to #19159
> 🏗 Update allowed nodejs versions for validator

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
See https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.38
> SwG Release 0.1.22.38

- extensions/amp-mowplayer/OWNERS.yaml
We probably want to add a linter for the owners files. that all of them are yaml lists
> add missing `-`

- extensions/amp-story/1.0/amp-story-tooltip.js
- extensions/amp-story/1.0/test/test-amp-story-tooltip.js
Part of #19181
Visual diff tests and validation will come in follow-ups.
> Adds unit tests for tooltip ✅

- extensions/amp-story/1.0/page-advancement.js
> Don't display tooltip when target is under cta layer 🐛

- src/service/fixed-layer.js
Re: https://github.com/ampproject/amphtml/pull/19169#pullrequestreview-173075093
> Add comments to fixed-layer synchronization

- build-system/conformance-config.textproto
- build-system/tasks/presubmit-checks.js
- extensions/amp-access-laterpay/0.1/laterpay-impl.js
- extensions/amp-access-laterpay/0.2/laterpay-impl.js
- extensions/amp-carousel/0.1/slidescroll.js
- extensions/amp-form/0.1/amp-form.js
- src/custom-element.js
- src/dom.js
This is the first step to supporting the Custom Element spec's sync behavior in our polyfill.
> Ban DOM v4 methods

- build-system/pr-check.js
- contributing/TESTING.md
- gulpfile.js
Fixed #17108 which was accidentally reopened with #18158
> 🏗 Add `--fortesting` to `gulp build` step in `pr-check.js`

- ads/adgeneration.js
- ads/adgeneration.md
- fix asynchronous XHR enable by default.
and some refactoring.
- CLA name: adg-dev
- Corporation Name: Supership Inc.
> 🐛fix amp-ad support for Ad Generation

- extensions/amp-video/0.1/amp-video.js
> 🐛 Mute/unmute only if not managed by MediaPool

- build-system/amp4test.js
- build-system/tasks/runtime-test.js
This PR addresses https://github.com/ampproject/amphtml/pull/19123#pullrequestreview-172162150 and silences the verbose logs printed by the fake XHR server during automated tests.
> 🏗 Silence fake XHR server logs during automated tests

- examples/amp-orientation-observer-amp-3d-gltf.amp.html
- extensions/amp-orientation-observer/0.1/amp-orientation-observer.js
> Add minimum ratio for <amp-orientation-observer> to reduce 'jerkiness'

- test/integration/test-video-players.js
> Skip amp-video-iframe integration tests

- build-system/amp.extern.js
- src/error.js
- src/mode-object.js
- src/mode.js
- test/functional/test-error.js
this allows me to group the single pass experiment easier for errors
> pass single pass type to query params if it exists

- examples/visual-tests/amp-story/amp-story-tooltip-desktop.js
- examples/visual-tests/amp-story/amp-story-tooltip.html
- examples/visual-tests/amp-story/amp-story-tooltip.js
- extensions/amp-story/1.0/amp-story-tooltip.css
- test/visual-diff/visual-tests
> ✅ Add visual and interactive test for amp-story-tooltip

- extensions/amp-analytics/0.1/events.js
To fix https://github.com/ampproject/amphtml/pull/18847#issuecomment-438700815
> 🐛Analytics: Allow repeat hidden triggers

- extensions/amp-bind/0.1/bind-evaluator.js
- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-bind/0.1/bind-validator.js
- extensions/amp-bind/0.1/test/test-bind-validator.js
- src/web-worker/web-worker.js
- test/fixtures/bind-amp4email.html
- test/integration/test-amp-bind.js
> Disallow URL attribute bindings in amp4email

- build-system/check-package-manager.js
> 🏗 Fixed misleading 'yarn' error about 'gulp' on first install

- extensions/amp-analytics/0.1/linker-manager.js
- extensions/amp-analytics/0.1/test/test-linker-manager.js
- tools/experiments/experiments.js
This has been at 1 since #18017
> 🚮Remove linker meta tag experiment

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
Final code deletion in #18968.
> 🗑Clean up url-replacement-v2 config

- src/intersection-observer-polyfill.js
- test/functional/test-intersection-observer-polyfill.js
closes #19252
Did exactly what the title says, and added tests to make sure this stays fixed 😄 
@zhouyx Not entirely sure how you manually tested this, would be awesome to know your steps so I can also manually make sure this fix works 😄
> 🐛Disconnected Intersection Observer Polyfill in Intersection Observer Api Destroy()

- 3p/viqeoplayer.js
Added parameters for internal statistics player viqeo
> ♻️ Added parameters for internal statistics player viqeo

- package.json
- yarn.lock
this fixes issue related to see dominictarr/event-stream#116
> update nodemon. 

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg-button.css
- third_party/subscriptions-project/swg.js
swg release [0.1.22.39](https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.39)
> swg release 0.1.22.39

- examples/article-access.amp.html
- extensions/amp-access/0.1/amp-access.js
- extensions/amp-access/0.1/test/test-amp-access.js
> ✨ add refresh action to amp-access

- extensions/amp-story/1.0/amp-story-system-layer.css
Fix desktop sharing pill styles.
[Screenshot](https://user-images.githubusercontent.com/1492044/49174117-81a80300-f313-11e8-8ce7-f1306a3bb329.png)
Fixes #19498
> Fix desktop sharing pill styles.

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
> Clean up 'faster-bind-scan' experiment

- extensions/amp-form/0.1/test/test-amp-form.js
- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
> Set amp source origin in requests for amp-list enabled for SSR

- extensions/amp-experiment/0.1/amp-experiment.js
- extensions/amp-experiment/0.1/test/test-amp-experiment.js
- access body through ampdoc
fixes https://github.com/ampproject/amphtml/issues/19434
> Fix: Amp experiment variable access in shadow-v0.js

- extensions/amp-video/OWNERS.yaml
@wassgha @erwinmombay @alanorozco  Since PRs will get auto assigned soon, let's go with this for now.
> Update amp-video owners

- validator/README.md
Added a link to VSCode extension for AMP HTML validator
> Add link to VSCode extension for AMP HTML validator

- spec/amp-actions-and-events.md
Adds refresh action documentation for amp-state, related to #18836 
@alabiaga @choumx
> Add refresh action documentation for amp-state

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
To be submitted once #19332 hits prod.
#18714 #18715
> Cleanup the amp-story-hold-to-pause experiments files.

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
> Turn on flag sandbox-ads

- build-system/tasks/bundle-size.js
> 🏗 bundle-size requests to GitHub App should accept any 2xx status code

- ads/videonow.js
> -- videonow ad's urls fixed

- extensions/amp-bind/0.1/bind-expression.js
> Remove Object.values polyfill in bind-expression.js

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
See https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.40
> SwG release 0.1.22.40

- extensions/amp-addthis/0.1/test/test-amp-addthis.js
fixes some unit tests that were previously failing
> amp-addthis extension unit test fix

- gulpfile.js
- generate module compatible script only for esm runs
> build module safe scripts only when building --esm

- extensions/amp-a4a/0.1/test/test-a4a-var-source.js
- src/service/url-replacements-impl.js
- src/services.js
Partial for #16322. Follow-up to #19496.
> Disallow ampdoc in Services.bindForDocOrNull()

- extensions/amp-subscriptions/0.1/test/test-dialog.js
filed https://github.com/ampproject/amphtml/issues/19625
> temporarily skip flakey amp-subscriptions test

- examples/analytics-vendors.amp.html
- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors.js
- extensions/amp-analytics/0.1/vendors/permutive.js
> Add new amp-analytics vendor: Permutive

- extensions/amp-analytics/linker-id-receiving.md
Its a tricky sentence, and hopefully with this minor tweak its easier to read.
>  Tweaking doc of `cookies` object

- .eslintrc
- build-system/eslint-rules/no-non-string-log-args.js
Need to change `assert` methods to be variadic before turning this on
> turn off fixer for now

- build-system/tasks/runtime-test.js
> Remove Mobile Safari 11 from tests

- extensions/amp-video/0.1/test/test-amp-video.js
Related to #19664 
To unblock #19613
https://travis-ci.org/ampproject/amphtml/jobs/463581530
> Skip amp video tests that are failing when running alone

- extensions/amp-analytics/0.1/test/test-linker-manager.js
Timing gap between new tests added in #19520 and refactoring in #19560.
/to @calebcordry
> Fix test-linker-manager.js

- extensions/amp-story/1.0/test/test-amp-story-system-layer.js
Register localization service in system layer tests
> [amp-story] Register localization service in system layer tests

- src/service/url-replacements-impl.js
- test/functional/test-url-replacements.js
> ♻️Don't encode expandStringSync

- test/integration/test-amp-analytics.js
> Add integration test for CLIENT_ID in amp-analytics

- extensions/amp-story/1.0/amp-story-store-service.js
- extensions/amp-story/1.0/amp-story.js
> [amp-story] Add totalPages to AmpStoryStoreService

- css/amp.css
- examples/analytics-iframe-transport-remote-frame.html
- extensions/amp-analytics/0.1/amp-analytics.css
- extensions/amp-analytics/0.1/amp-analytics.js
- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
- test/manual/amp-analytics-in-fie.amp.html
Closes #19678 to @jridgewell @lannka 
cc @keithwrightbos 
cc @calebcordry on amp-story-auto-ads change.
> 🐛Allow amp-analytics to layout correctly in FIE

- test/functional/test-custom-element.js
Causes master to be red: e.g., https://travis-ci.org/ampproject/amphtml/jobs/465536458#L1431
> ✅ Disable flaky CustomElement test

- bundles.config.js
- examples/amp-date-display.amp.html
- extensions/amp-date-display/0.1/amp-date-display.js
- extensions/amp-date-display/0.1/test/test-amp-date-display.js
- extensions/amp-date-display/0.1/test/validator-amp-date-display.html
- extensions/amp-date-display/0.1/test/validator-amp-date-display.out
- extensions/amp-date-display/OWNERS.yaml
- extensions/amp-date-display/amp-date-display.md
- extensions/amp-date-display/validator-amp-date-display.protoascii
- tools/experiments/experiments.js
- validator/engine/validator.js
Fixes #10837.
@aghassemi This is @robinpokorny's branch for amp-date-display. Last update from Robin was that it was just pending documentation. 
Any chance we can get an owner from UI team to help clean up and shepherd this in?
> [WIP] amp-date-display

- test/functional/test-custom-element.js
Related to #19750, adds to #19752
> Disable two flaky CustomElement tests

- ads/zen.md
- Edit documentation for embed-zen, make width - optional parameter
> 📖 Edit embed-zen documentation

- extensions/amp-subscriptions-google/OWNERS.yaml
- extensions/amp-subscriptions/OWNERS.yaml
Updating owners files to current team to allow merges.
> Add SwG team to amp-subscriptions and amp-subscriptions-google owners

- src/service/fixed-layer.js
- test/functional/test-fixed-layer.js
> 🐛 Fix FixedLayer attribute sync for amp-bind

- test/functional/test-fixed-layer.js
Re: https://github.com/ampproject/amphtml/pull/19805#discussion_r240821426
> ✅ Add more tests to fixed-layer attr sync

- build-system/single-pass.js
- extensions/amp-addthis/0.1/addthis-utils/lojson.js
- extensions/amp-addthis/0.1/amp-addthis.js
- extensions/amp-addthis/0.1/config-manager.js
- extensions/amp-addthis/0.1/post-message-dispatcher.js
closes https://github.com/ampproject/amphtml/issues/19633
> Fix amp-addthis single pass bugs

- extensions/amp-accordion/0.1/test/integration/test-amp-accordion.js
- extensions/amp-form/0.1/test/integration/test-integration-form.js
- extensions/amp-fx-collection/0.1/test/integration/test-amp-fx-fade-in-scroll.js
- test/integration/test-amp-carousel.js
- test/integration/test-errors.js
- test/integration/test-toggle-display.js
- test/integration/test-user-error-reporting.js
- test/integration/test-visibility-states.js
> Add TODOs for skipped tests

- extensions/amp-list/0.1/amp-list.js
1. Fix bug where existing items are getting appended again on every load. 
2. Fix bug where load-end element and load-failed element doesn't disappear after bind.
> [amp-list-load-more] Fix bug where existing items are getting appended again

- build-system/tasks/runtime-test.js
- extensions/amp-form/0.1/test/integration/test-integration-form-verifiers.js
- extensions/amp-form/0.1/test/integration/test-integration-form.js
- extensions/amp-inputmask/0.1/test/integration/test-integration-amp-inputmask.js
- test/fixtures/bind-form.html
- test/functional/test-xhr.js
Also restore the batch size of 4 because reducing it didn't seem to change anything in the amount of flakes
Discussion leading to this resolution in issue #19788
SauceLabs supported ports for the proxy server: https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy+FAQS#SauceConnectProxyFAQS-CanIAccessApplicationsonlocalhost%3F
> Replace test server port from 31862 to 8081 for better proxy support in SauceLabs

- extensions/amp-consent/0.1/consent-ui.js
- extensions/amp-consent/0.1/test/test-consent-ui.js
This is to fix #19599.
Did more investigation. I'll share in the other thread.
> 🐛Update fixed layer after toggle display

- examples/date-picker.amp.html
- extensions/amp-date-picker/0.1/amp-date-picker.js
- extensions/amp-date-picker/0.1/date-range-picker.js
- extensions/amp-date-picker/0.1/test/integration/test-integration-maximum-nights.js
- extensions/amp-date-picker/0.1/test/validator-amp-date-picker.html
- extensions/amp-date-picker/0.1/test/validator-amp-date-picker.out
- extensions/amp-date-picker/0.1/wrappers/maximum-nights.js
- extensions/amp-date-picker/amp-date-picker.md
- extensions/amp-date-picker/validator-amp-date-picker.protoascii
Fixes #19702.
Feature is implemented as a wrapper React component to implement modularly. The wrapper folder doesn't contain the other wrapper classes yet, like `withFocusedTrueHack` but this will be done in a future refactor to simplify the other classes.
> ✨maximum-nights attribute on amp-date-picker

- extensions/amp-social-share/validator-amp-social-share.protoascii
- validator/validator-main.protoascii
> add fb-me and wh protocols for anchor and social-share

- build-system/pr-check.js
Fixes #19875
Would have caught a bundle-size increase in PR #19812
> Mark `babel-plugins` files as affecting the runtime in the `gulp pr-check` task

- extensions/amp-access-poool/0.1/amp-access-poool.js
- extensions/amp-access-poool/0.1/test/test-amp-access-poool.js
- extensions/amp-access-poool/validator-amp-access-poool.protoascii
> Fix copyright date on amp-access-poool files

- extensions/amp-analytics/0.1/transport-serializer.js
- src/service/url-replacements-impl.js
- test/functional/test-url-replacements.js
- test/integration/test-amp-ad-fake.js
- test/integration/test-amp-analytics.js
- test/integration/test-amp-pixel.js
- test/integration/test-user-error-reporting.js
> ✅Enable skipped singlepass tests

- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
- extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
For details see #19736
Closes #19736
> 🐛amp-story-auto-ads: stringify objects in config

- test/integration/test-amp-inabox.js
... with a TODO to unskip it on Safari.
> add test for inabox BTF

- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
> Refactor lightbox gallery to use htmlFor

- extensions/amp-ad-exit/0.1/amp-ad-exit.js
- extensions/amp-ad-exit/0.1/config.js
found some bugs in single pass for amp-ad-exit where we are dot access on a objects coming from a script configuration.
> fix amp-ad-exit in singlepass

- src/impression.js
Follow up to #19958 
Let me know if this is less confusing.
> Update code comment

- build-system/runner/src/org/ampproject/AmpPass.java
This should not be needed for single pass.
> Add special case to inline new assert function.

- test/integration/test-amp-ad-3p.js
also unmuted an assertion that seems to be working again.
tested locally with complied code.
Closes #16825
> Increase timeout to fix flakiness of attemptChangeSize request

- test/visual-diff/visual-tests
Fixes https://travis-ci.org/ampproject/amphtml/jobs/471068548#L654
> 🐛 Remove duplicate visual test

- src/custom-element.js
> Remove unused load-end event

- build-system/runner/src/org/ampproject/AmpPass.java
This reverts commit 370b6e3a504537b5e5db4b5881dd095d282de2c4.
> Revert "Remove the whole statement when stripping asserts/logs when possible. (#20033)"

- extensions/amp-video-iframe/0.1/amp-video-iframe.js
- extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
- tools/experiments/experiments.js
Partial for #19563
**Not to be merged until Jan 1st.**
> 🚮Remove `amp-video-iframe` experiment guard

- extensions/amp-story/1.0/amp-story-system-layer.css
Being able to click through the system layer when it's hidden.
> Click through the system layer when hidden.

- extensions/amp-story/1.0/amp-story.js
Alternative implementation to #20040
> 🐛 Prevent context menu in stories

- examples/analytics-vendors.amp.html
- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors.js
- extensions/amp-analytics/0.1/vendors/upscore.js
Hi @torch2424, 
How are you? Some time has passed since we last talked, and I hope that you are doing well.
A few days ago, we tested the UpScore AMP analytics with one of our clients and noticed that we have a small issue. So after an investigation and debugging I noticed that I completely missed out one part of AMP integration, and forgot to add the UPSCORE_CONFIG inside vendors.js file. 
I would really appreciate if we could resolve this as soon as possible.
I wish Merry Christmas and Happy and Prosperous New Year, to you and whole Google AMP team. 
Sandi 
Last UpScore pull request#18734
> 🐛: Adding UpScore to Vendor.js

- build-system/tasks/presubmit-checks.js
> Update presubmit check to require copyright for 2019

- tools/experiments/experiments.js
> 🚮Cleanup `amp-story-scaling` experiment

- examples/analytics-vendors.amp.html
Follow up to https://github.com/ampproject/amphtml/pull/20069#issuecomment-450946833
cc @lannka
> Minor fix to analytics vendor example page

- extensions/amp-analytics/amp-video-analytics.md
- extensions/amp-brightcove/0.1/amp-brightcove.js
- Implements currentTime, duration, playedRangesJson, and playedTotal in amp-brightcove
- Fixes #19817
> ✨amp-brightcove: extend analytics support

- build-system/tasks/changelog.js
Fixes https://github.com/ampproject/amphtml/issues/20027
using the github API to determine the last branch can sometimes cause bugs like when the last tag is in draft mode or if production patches is the last branch on github
> Fix changelog baseline

- contributing/component-validator-rules.md
- extensions/amp-recaptcha-input/0.1/test/validator-amp-recaptcha-input.html
- extensions/amp-recaptcha-input/0.1/test/validator-amp-recaptcha-input.out
- extensions/amp-recaptcha-input/validator-amp-recaptcha-input.protoascii
- validator/README.md
- validator/build.py
relates to #18829
relates to #2273
This adds validation tests for the new `amp-recaptcha-input`. With some help from @Gregable to get this working / validating correctly.
Also, updated documentation from the learnings @Gregable and I had from getting this going.
> ✨/ ♻️amp-recaptcha-input: Added Validation tests / Updated Validation Documentation

- examples/amp-consent.amp.html
- extensions/amp-consent/0.1/amp-consent.js
- extensions/amp-consent/0.1/consent-config.js
- extensions/amp-consent/0.1/consent-policy-manager.js
- extensions/amp-consent/0.1/consent-state-manager.js
- extensions/amp-consent/0.1/test/test-amp-consent.js
- extensions/amp-consent/0.1/test/test-consent-config.js
- extensions/amp-consent/0.1/test/test-consent-policy-manager.js
- extensions/amp-consent/0.1/test/test-consent-state-manager.js
Follow up of #20089 
Remove multiple consent instance from all services.
> Remove multi consent prompt support

- extensions/amp-recaptcha-input/0.1/test/validator-amp-recaptcha-input.html
- extensions/amp-recaptcha-input/0.1/test/validator-amp-recaptcha-input.out
continuation of #20143
Happy new year! 🎉
Simply fixes the copyright year from some bad copypasta.
> 🐛amp-recaptcha-input: Fixed Copyright year on Validator HTML Test

- extensions/amp-a4a/0.1/callout-vendors.js
Add Navegg into a4a vendors list.
> ✨ Add Navegg as A4A vendor

- ads/adgeneration.js
use writeScript instead of loadScript
CLA name: adg-dev
Corporation Name: Supership Inc.
> ♻️use writeScript instead of loadScript

- build-system/amp.extern.js
- extensions/amp-ad/0.1/amp-ad-3p-impl.js
- src/iframe-attributes.js
As agreed with @erwinmombay. We decided to complete the extern list for 3p ad, even though we are using JsonObject.
> Extern list for 3p ad context attributes

- extensions/amp-story/1.0/_locales/nl.js
Proposed improvement of Dutch translations
✨ New feature (`:sparkles:`) …
> 🌐 suggested i18n update for nl.js

- extensions/amp-story/1.0/_locales/zh.js
Localization for simplified Chinese is not accurate or even wrong~
> 🐛AMP STORY : Fixed localization for simplified Chinese

- ads/README.md
Follow up to #20185 where I missed 1 replacement. Thanks @rsimha!
> Rename test/functional dir to test/unit in ads/README.md

- extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
- extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
- extensions/amp-subscriptions/0.1/actions.js
- extensions/amp-subscriptions/0.1/amp-subscriptions.js
- extensions/amp-subscriptions/0.1/analytics.js
- extensions/amp-subscriptions/0.1/local-subscription-platform.js
- extensions/amp-subscriptions/0.1/service-adapter.js
- extensions/amp-subscriptions/0.1/test/test-actions.js
- extensions/amp-subscriptions/0.1/test/test-analytics.js
- extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
- extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
- extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
> Subscriptions: add additional events for SwG

- extensions/amp-story/1.0/amp-story.css
> Prevent contextmenu on iOS.

- build-system/tasks/compile.js
- extensions/amp-experiment/0.1/amp-experiment.js
- extensions/amp-experiment/0.1/test/test-amp-experiment.js
- extensions/amp-experiment/0.1/variant.js
- src/error.js
- src/service/url-replacements-impl.js
- src/services.js
- test/unit/test-url-replacements.js
> Fix amp-experiment instantiation for shadow mode

- extensions/amp-story/1.0/amp-story-system-layer.css
- extensions/amp-story/1.0/amp-story-system-layer.js
Increase the height of the fullbleed desktop progress bar.
> Increase the height of the fullbleed desktop progress bar.

- validator/webui/@polymer/webui-mainpage/webui-mainpage.html
- validator/webui/@polymer/webui-urlform/webui-urlform.html
Surfaces a new drop down called "Actions" to validate AMP actions documents.
> Add Actions to Validator WebUI

- extensions/amp-story/1.0/amp-story.css
- extensions/amp-story/1.0/amp-story.js
> 🖍 Add sidebar transitions/ styling

- extensions/amp-story/1.0/amp-story-page-attachment.js
- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/utils.js
Reopen the page attachment if a user clicks on a link that's in it, and comes back.
#20209
> Reopen page attachment from browser history.

- extensions/amp-image-viewer/0.1/amp-image-viewer.js
Closes https://github.com/ampproject/amphtml/issues/20241.
> Fix [amp-lightbox-gallery] panning results in carousel swipe

- extensions/amp-list/0.1/test/validator-amp-list.html
- extensions/amp-list/0.1/test/validator-amp-list.out
- extensions/amp-list/validator-amp-list.protoascii
Part of #10230, blocks #20314.
> Add validation for [is-layout-container]

- extensions/amp-video-iframe/amp-video-iframe.md
> 📖 Add copyright header

- extensions/amp-video-docking/0.1/amp-video-docking.js
- extensions/amp-video-docking/0.1/controls.js
> 🐛 Reapply docking target on resize if changed

- examples/amp-consent.amp.html
- src/consent.js
- src/custom-element.js
- test/manual/amp-consent-cmp.html
- test/unit/test-consent.js
- test/unit/test-custom-element.js
Partial for #20253 
I'll make the validator change in a separate PR.
> ✨Consent: Allow using metaTag to block AMP components by tagName

- extensions/amp-consent/0.1/test/validator-amp-consent-invalid-no-meta.html
- extensions/amp-consent/0.1/test/validator-amp-consent-invalid-no-meta.out
- extensions/amp-consent/0.1/test/validator-amp-consent-multi.html
- extensions/amp-consent/0.1/test/validator-amp-consent-multi.out
- extensions/amp-consent/0.1/test/validator-amp-consent-type.html
- extensions/amp-consent/0.1/test/validator-amp-consent-type.out
- extensions/amp-consent/validator-amp-consent.protoascii
- validator/validator-main.protoascii
Second part of #20253, follow up to  #20284
> amp-consent-v2-validator change

- extensions/amp-story/1.0/test/test-amp-story-embedded-component.js
#19213 #16522
Renaming test filename and symbols for embedded components. (No new code).
> Rename embedded component tests ♻️

- CONTRIBUTING.md
update broken contribute code/feature and ongoing participation bookmarks.
> update broken bookmarks in contribution doc

- extensions/amp-story/1.0/amp-story-page-attachment.js
Close the story page attachment on browser back.
#20209
> Close the story page attachment on browser back.

- extensions/amp-bind/amp-bind.md
> 🐛 amp-bind: close amp-bind-macro tag in example

- examples/visual-tests/amp-story/amp-story-page-attachment-desktop.js
- examples/visual-tests/amp-story/amp-story-page-attachment.html
- examples/visual-tests/amp-story/amp-story-page-attachment.js
- test/visual-diff/visual-tests
Story page attachment visual tests.
#20209
> Story page attachment visual tests.

- src/purifier.js
> amp-mustache: Don't log user error for binding attributes

- extensions/amp-carousel/0.2/carousel.js
- extensions/amp-carousel/0.2/dimensions.js
- test/manual/amp-carousel-0-2/basic.amp.html
- Add logic for setting the CSS snap properties.
- Add logic for advance/prev/next.
- Add logic for scrolling the current element into view.
- Add a basic manual test.
> Add additional carousel v2 logic.

- extensions/amp-consent/0.1/amp-consent.js
- extensions/amp-consent/0.1/test/test-amp-consent.js
- extensions/amp-geo/0.1/amp-geo-in-group.js
- extensions/amp-geo/0.1/amp-geo.js
- extensions/amp-geo/0.1/test/test-amp-geo.js
- extensions/amp-user-notification/0.1/amp-user-notification.js
- extensions/amp-user-notification/0.1/test/test-amp-user-notification.js
> 🐛Move GEO_IN_GROUP types to pure file

- src/polyfills.js
- src/service/extensions-impl.js
Until we're ready to begin the canary experiment, allow it to be stripped from the production builds.
> 🚮 DCE custom-elements-v1

- build-system/global-configs/prod-config.json
> Launch amp-list-viewport-resize to 50%

- examples/masking.amp.html
Implements what will probably be one of the most common use-cases for inputmasking.
> ✨Add phone dropdown example

- extensions/amp-carousel/0.2/carousel.js
- extensions/amp-carousel/0.2/dimensions.js
- extensions/amp-carousel/0.2/responsive-attributes.js
- extensions/amp-carousel/0.2/test-e2e/test-carousel.js
- extensions/amp-carousel/0.2/test/test-responsive-attributes.js
- Update the current index on scroll
- Move slides around on scroll
- Implement scroll position restoration (when resetting the reference
point or when rotating)
- Have responsive attributes logic ignore attributes that have no configuration option (e.g. style)
- Make media query attribute parsing logic more robust
> Additional logic for carousel v2.

- extensions/amp-analytics/amp-analytics.md
Part of #20280
Documentation for the basic functionality as well as the new `varGroups` feature 🎉
> 📖Documentation for configRewriter

- extensions/amp-date-display/amp-date-display.md
Also opened https://github.com/ampproject/amp-by-example/pull/1808
> Document the attributes and values of amp-date-display

- contributing/TESTING.md
> remove old sauce lab credit snippet

- build-system/tasks/e2e/selenium-webdriver-controller.js
- extensions/amp-carousel/0.2/carousel.js
- extensions/amp-carousel/0.2/test-e2e/helpers.js
- extensions/amp-carousel/0.2/test-e2e/test-carousel.js
- extensions/amp-carousel/0.2/test-e2e/test-max-swipe.js
- extensions/amp-carousel/0.2/test-e2e/test-mixed-lengths.js
- extensions/amp-carousel/0.2/test-e2e/test-responsive.js
- test/manual/amp-carousel-0-2/max-swipe-one-no-loop.amp.html
- test/manual/amp-carousel-0-2/max-swipe-one.amp.html
- test/manual/amp-carousel-0-2/mixed-lengths-no-snap.amp.html
- test/manual/amp-carousel-0-2/mixed-lengths.amp.html
- test/manual/amp-carousel-0-2/responsive.amp.html
- Add scrollBy method for functional tests.
- Add tests for mixed-length carousels.
- Add tests for responsive attributes.
- Add tests for side-slide-count attribute.
* Fix regression causing too much scroll width.
> ✅Add carousel v2 tests.

- ads/adyoulike.md
> 🐛📖  Fix  Adyoulike typo on readme

- build-system/sauce_connect/start_sauce_connect.sh
We've had trouble with Sauce Labs of late. This PR prints the current service status before connecting, so we have a better idea of why failures occur.
Documentation:
Status URL: [link](https://wiki.saucelabs.com/display/DOCS/Platform+Information+Methods#PlatformInformationMethods-GetSauceLabsStatus)
REST API: [link](https://wiki.saucelabs.com/display/DOCS/Accessing+the+API)
Fixes #20488
Partial fix for #20492
> 🏗 Fetch and print sauce labs status before connecting

- extensions/amp-date-display/0.1/amp-date-display.js
- extensions/amp-date-display/amp-date-display.md
- tools/experiments/experiments.js
> 🚮 Remove amp-date-display experiment

- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
> 🐛 Hide gallery button when displaying single-item gallery

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
The checks were removed in #18606.
> Clean up inabox-rov experiment.

- extensions/amp-story/1.0/amp-story.js
Pause the story when the landscape overlay warning is displayed.
> Pause the story when the landscape overlay warning is displayed.

- ads/kuadio.js
- ads/kuadio.md
> ✨ Improve kuadio ad network optional params data-ref

- ads/zucks.js
- ads/zucks.md
- examples/ads.amp.html
We currently support another new type of ad and would like to integrate with amp-ad.
This is a non breaking changes since the previous api won't change.
> ✨ Support new ad type for Zucks ad network

- extensions/amp-story/amp-story.md
> 📖 Add documentation for localizing AMP stories

- build-system/global-configs/prod-config.json
> launch amp-list-viewport-resize to 75% in prod

- build-system/pr-check.js
saucelabs status incident here https://status.saucelabs.com/incidents/tsvpd1kmd98p
> temporarily disable saucelabs because of flakiness

- extensions/amp-video-docking/0.1/amp-video-docking.css
- extensions/amp-video-docking/0.1/amp-video-docking.js
> 🐛Reparent placeholder to account for incorrect positioning

- examples/form-proxy-template-to-viewer-host.amp.html
- extensions/amp-form/0.1/amp-form.js
- extensions/amp-form/0.1/test/test-amp-form.js
- src/ssr-template-helper.js
> Fix amp-form server side rendering

- extensions/amp-consent/0.1/consent-ui.js
- test/manual/diy-consent.html
closes #20548
As per @zhouyx 's suggestion: "I've verified moving toggle() around is indeed the cause here. The toggle(iframe, true) was moved after scheduleLayout(iframe). In this case runtime won't layout the iframe because it has display:none."
This moves the toggle to the correct place.
Also thank you to @patrick-mcdougle for identifying this!
> 🐛Moved toggle order for Consent Iframe

- extensions/amp-inputmask/0.1/inputmask-payment-card-alias.js
Fixes the issues raised during the bug bash.
> 🐛Prevent letters in credit cards. Allow editing beginning.

- extensions/amp-bind/0.1/bind-validator.js
- extensions/amp-form/0.1/form-validators.js
- extensions/amp-form/0.1/test/test-form-validators.js
- extensions/amp-form/amp-form.md
- validator/validator-main.protoascii
Fixes #8247. 
~Will add tests and validator rules if you're cool with this rough approach.~ Done.
> Support pattern validation on textarea

- extensions/amp-subscriptions/0.1/dialog.js
- extensions/amp-subscriptions/0.1/test/test-dialog.js
> Force the subscriptions dialog into the fixed layer to avoid collisions with border

- third_party/inputmask/inputmask.date.extensions.js
- third_party/inputmask/patches/0012-toggle-edited-date-mask.patch
/cc @andrewwatterson This will unbreak the existing weirdness in the date mask. If we decide on a better UX when we meet we can replace this with that.
> 🐛Remove mask behavior if user deletes from middle of date

- examples/visual-tests/amp-selector.amp.html
- examples/visual-tests/amp-selector.js
- test/visual-diff/visual-tests
> ✅ Add visual diff tests for `<amp-selector>`

- examples/visual-tests/amp-accordion/amp-accordion.html
- examples/visual-tests/amp-accordion/amp-accordion.js
- test/visual-diff/visual-tests
> Add first amp-accordion visual tests

- extensions/amp-inputmask/0.1/text-mask.js
Hidden inputs created for inputmasks with the `mask-output` attribute would misbehave when combined with amp-list and disabled inputs.
> 🐛Fix mask-output when combined with amp-list

- build-system/global-configs/prod-config.json
> launch amp-list-viewport-resize to all

- extensions/amp-inputmask/0.1/amp-inputmask.js
- extensions/amp-inputmask/0.1/test/integration/test-integration-amp-inputmask-date.js
- extensions/amp-inputmask/0.1/test/integration/test-integration-amp-inputmask.js
- extensions/amp-inputmask/README.md
- tools/experiments/experiments.js
> ✨Launch amp-inputmask

- spec/auto-lightbox.md
Google internal related: go/amp-auto-lightbox
Reflects status of working code after #20751, #20761
> 📖 Document auto-lightbox treatment

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
🚀🔬🤓
For more details on this particular feature, please read the spec:
<https://github.com/ampproject/amphtml/blob/master/spec/auto-lightbox.md>
> 🐦 Activate `amp-auto-lightbox` in canary

- contributing/CODE_OWNERSHIP.md
- contributing/DEVELOPING.md
This PR outlines the code ownership model for `ampproject/amphtml` and describes its implementation at a high level. Source code for the solution can be found at https://github.com/google/github-owners-bot (under development).
> 📖 Add documentation for new code ownership model

- extensions/amp-access-laterpay/amp-access-laterpay.md
We've had some feedback from customers that some of these points, while being documented elsewhere, aren't always obvious to them specially when they're new to both AMP and our product. As such these improvements will hopefully help with reducing confusion and getting them started more easily.
- Add some more info on how this integration relates to other LaterPay
integrations and AMP Access
- Add info on how to configure and setup analytics
- Add info on how to setup this integration to work alongside AMP Access
and a publisher's existing paywall
> 📖 Documentation improvements for amp-access-laterpay

- test/integration/test-amp-skimlinks.js
> Skip integration test in firefox

- extensions/amp-story/1.0/_locales/es-419.js
- extensions/amp-story/1.0/_locales/es.js
> 🐛🌐 amp-story: Added missing localization strings in es and es-419

- ads/unruly.md
- examples/ads.amp.html
- update unruly.md and ads.amp.html with new responsive layout
> 📖 Documentation(unruly): update README and test page with correct integration instructions

- extensions/amp-geo/0.1/amp-geo.js
- extensions/amp-subscriptions/0.1/amp-subscriptions.css
paywall dialog was on top of link complete dialog.
> 🐛 Fix subscriptions dialog stacking order.

- extensions/amp-story-auto-ads/amp-story-auto-ads.md
> 📖amp story ads RTC & Targeting docs

- src/dom.js
https://jsbench.github.io/#e00c46505b5b875d2dcd5894d6e46adc
Thanks for caching the original bug!
> Optimize scopeSelector

- extensions/amp-video-iframe/0.1/amp-video-iframe.js
- extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
Docs say we do it, but we don't, so let's do it!
Also cleaned up some tests to be clearer and to use `async/await`.
> ✨ Set amp=1 fragment in amp-video-iframe src

- src/video-iframe-integration.js
- Prefix all frame-level errors with `<amp-video-iframe>` to let authors know source of integration mistakes.
- Fail to `adopt` window twice, notify that script tag should only be included once.
- Display valid listener types when trying to `listenTo('invalidFramework')`.
- Don't let author `listenTo` twice.
> 🛑 <amp-video-iframe> integration safeguards

- extensions/amp-analytics/amp-analytics.md
- src/error.js
- tools/experiments/experiments.js
> Clean up 'user-error-reporting'

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
> AdSense Fast Fetch 1% experiment delay requested based on fixed viewport offset

- ads/google/a4a/shared/content-recommendation.js
- ads/google/a4a/shared/test/test-content-recommendation.js
- ads/google/test/test-utils.js
- ads/google/utils.js
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
- extensions/amp-ad/0.1/amp-ad-3p-impl.js
- extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
The commit introduces core-shared.js file which supposed to be shared between AMP and internal Google adsbygoogle.js codebase. The file has minimal dependencies on environment to make keeping them in sync easier.
In particular this commit adds support for publisher settings as described in https://support.google.com/adsense/answer/7533385
Tested:
unit tests
manually on fast fetch and delayed fetch
> ✨ Improve Google matched content logic to reflect adsbygoogle.js.

- extensions/amp-story/1.0/_locales/default.js
- extensions/amp-story/1.0/_locales/en.js
- extensions/amp-story/1.0/amp-story-store-service.js
- extensions/amp-story/1.0/amp-story-viewport-warning-layer.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/localization.js
- extensions/amp-story/1.0/test/test-amp-story-store-service.js
- Displaying specific messages to users so they know if they have to resize their browser's height, width, or both
- Different refactoring / code health things
Closes #19950, #19670
> Displaying more specific messages when users have to resize their window.

- build-system/dep-check-config.js
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
See #20833.  Modify to respect tighter viewport constraint set by data-loading-strategy attribute when set.
> AdSense Fast Fetch delay 3 viewport experiment - respect loading strategy

- extensions/amp-a4a/0.1/test/test-template-renderer.js
- src/layout.js
- test/unit/test-layout.js
> 🐛Do not perform static layout for cloned nodes with static layout.

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
##Previous release: 0.1.22.43
##Changes for this release:
- Do not expose port out of ActivityIframeView (#509)
- WA 1.22.0 release (#511)
> SwG Release 0.1.22.44

- extensions/amp-video-docking/amp-video-docking.md
- Document target types and events.
- Clarify a few things.
> 📖 video-docking: Target types and events

- validator/engine/validator.js
> Use const in validator code

- build-system/tasks/visual-diff/helpers.js
- build-system/tasks/visual-diff/index.js
- examples/visual-tests/amp-accordion/amp-accordion.js
- examples/visual-tests/amp-date-picker/amp-date-picker.js
- examples/visual-tests/amp-list/amp-list.amp.js
- examples/visual-tests/amp-selector.js
- examples/visual-tests/amp-sidebar/amp-sidebar.js
- examples/visual-tests/amp-story/amp-story-page-attachment-desktop.js
- examples/visual-tests/amp-story/amp-story-page-attachment.js
- examples/visual-tests/amp-story/amp-story-pagination-buttons.js
- examples/visual-tests/amp-story/amp-story-sidebar.js
- examples/visual-tests/amp-story/amp-story-tooltip-desktop.js
- examples/visual-tests/amp-story/amp-story-tooltip.js
- examples/visual-tests/font.amp.404/font.amp.js
- test/visual-diff/visual-tests
> Split visual diff helper functions to simplify the API for test writers

- build-system/pr-check/build.js
- build-system/pr-check/checks.js
- build-system/pr-check/dist-tests.js
- build-system/pr-check/local-tests.js
- build-system/pr-check/remote-tests.js
- build-system/pr-check/validator-tests.js
- build-system/pr-check/visual-diff-tests.js
To avoid errors on Travis push builds seen here
https://travis-ci.org/ampproject/amphtml/jobs/493957831#L669
> 🏗 Print git change summary only for non-push builds

- extensions/amp-ad-exit/0.1/amp-ad-exit.js
- extensions/amp-mraid/0.1/amp-mraid.js
- src/inabox/host-services.js
- src/service.js
- test/unit/test-service.js
@jeffkaufman please take a look at the change in mraid.js. I guess I'm now confused about the fallback-on attribute. what did we need that?
@choumx please take a look at the change I made to the `service.js`
> Reject host service on failures.

- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
> 🐛 Fix optional check

- extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
> 🐛 Wait for element to be upgraded before mutate

- extensions/amp-dailymotion/0.1/test/validator-amp-dailymotion.html
- extensions/amp-dailymotion/0.1/test/validator-amp-dailymotion.out
- extensions/amp-dailymotion/amp-dailymotion.md
- extensions/amp-dailymotion/validator-amp-dailymotion.protoascii
- extensions/amp-video-docking/0.1/test/validator-amp-video-docking-amp-dailymotion.html
- extensions/amp-video-docking/0.1/test/validator-amp-video-docking-amp-dailymotion.out
- extensions/amp-video-docking/amp-video-docking.md
- spec/amp-video-interface.md
Component has great `VideoInterface` support, so `dock` can be supported without any kinks!
> ✨Support <amp-dailymotion dock>

- extensions/amp-addthis/amp-addthis.md
> 📖 amp-add-this: fix video in documentation

- examples/article-with-docked-video.html
- ½ cup unsalted butter, melted
- ⅓ cup granulated sugar
- ½ cup light brown sugar, packed
- 1 large egg
- 1 teaspoon vanilla extract
- ½ teaspoon baking soda
- ½ teaspoon salt
- 1 ½ cups all-purpose flour
- 1 ½ cups chocolate chips
1. Place melted butter in the bowl of a stand mixer fitted with the paddle attachment. Add granulated and brown sugars and mix on low speed until the mixture is smooth. Mix in egg and vanilla extract and mix on medium speed until combined.
2. Mix in baking soda and salt, then slowly mix in flour and mix just until the batter is smooth. Slowly mix in chocolate chips.
3. Line a cookie sheet with parchment paper. Scoop 2 tablespoon balls of dough onto the cookie sheet. Cover with plastic wrap and chill for at least 2 hours.
4. Preheat oven to 350°F. Line a second …
> 🍪 Chocolate chip cookie recipe

- extensions/amp-analytics/0.1/linker-manager.js
Has been at 1 for a long time. 
TODO: remove from config after this hits prod.
> 🧪Remove linker-form experiment

- package.json
- yarn.lock
> 🐛Update @ampproject/animations

- extensions/amp-addthis/0.1/test/validator-amp-addthis.html
- extensions/amp-addthis/0.1/test/validator-amp-addthis.out
- extensions/amp-addthis/validator-amp-addthis.protoascii
🐛 fix required attributes
we used to only have one set of required attributes now we have mild complexity in our logic
> fix required attributes

- examples/amp-consent.amp.html
- extensions/amp-analytics/0.1/requests.js
- extensions/amp-analytics/0.1/test/test-requests.js
- extensions/amp-analytics/0.1/variables.js
- extensions/amp-analytics/0.1/vendors.js
- src/consent.js
> Add CONSENT_STATE macro support for amp-analytics

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
> Update SwG version to 0.1.22.45

- extensions/amp-bind/0.1/test/integration/test-bind-impl.js
- package.json
- yarn.lock
This fixes the test errors seen in https://github.com/ampproject/amphtml/pull/21072#pullrequestreview-207767673
Closes #21072
> 🏗🐛 Upgrade `lolex` to 3.1.0 and fix bug in test usage

- extensions/amp-analytics/0.1/variables.js
As agreed in #20995 rename variables
> Rename CONSENT_STATE variables

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
> Enable 'fixed-elements-in-lightbox' in canary/prod

- examples/amp-script/empty.js
- examples/amp-script/hello-world.amp.html
- extensions/amp-script/0.1/amp-script.js
- package.json
- yarn.lock
See https://github.com/ampproject/worker-dom/releases/tag/v0.2.18
> Upgrade Worker-DOM to 0.2.18 to fix multi-root isolation

- ads/custom.md
`"amp-analyics"` -> `"amp-analytics"`
> 📖 Fix typo in custom.md.

- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
> 🐛Guard against errors in lightbox transition animation.

- extensions/amp-viewer-integration/TICKEVENTS.md
- src/service/performance-impl.js
- test/unit/test-performance.js
See https://github.com/GoogleChromeLabs/first-input-delay
Fixes #21121
> ✨ Introduce `fid-polyfill` tickevent.

- contributing/design-reviews.md
This adds instructions for automatically joining design review video conferences (by joining a Google Group) and does some other minor cleanup.
> Add instructions for being able to automatically join design reviews (and other cleanup)

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
> Allow doc opt-in for inabox-viewport-friendly.

- renovate.json
https://renovatebot.com/docs/configuration-options/#commitmessageprefix
> 🏗 Add a prefix to incoming Renovate PR titles

- contributing/TESTING.md
- Add additional instructions about project creation during the `firebase init` step as well as general tips for using Firebase.
> 📖 Update firebase init documentation

- src/service/resources-impl.js
I pushed the Element into `dirtySet`, not the `ChangeHeightRequest`.
> 🐛 Fix layers dirtying after resize

- build-system/tasks/extension-generator/index.js
To match the format introduced in #20684.
> 🏗 Reflect new extension docs format in generator

- extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
> 🐛 Fix race condition for `signals`

- extensions/amp-story/amp-story.md
AMP Story page attachments documentation.
Feel free to rephrase anything that sounds weird or is not aligned with the rest of our docs, or suggest parts I forgot to mention :)
> AMP Story page attachments documentation.

- .travis.yml
- build-system/pr-check/utils.js
Follow up to https://github.com/ampproject/amphtml/pull/21205#discussion_r261788671
Also ensures authentication using the GCP service account works, and public access to the storage bucket is removed.
> 🏗 Install openssl on Travis VMs

- extensions/amp-iframe/0.1/amp-iframe.js
- extensions/amp-iframe/0.1/test/test-amp-iframe.js
- extensions/amp-ima-video/0.1/amp-ima-video.js
- extensions/amp-youtube/0.1/amp-youtube.js
- src/iframe-video.js
> 🐛Video: temp workaround for Chrome 72-74 breakage

- ads/_config.js
- ads/gumgum.js
Update g2 dependencies to use js.gumgum.com
> ADJS-443 update refs to js.gumgum

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
Per  https://github.com/ampproject/amphtml/issues/17053.
> Add amp-img-auto-sizes to doc-level-optin

- build-system/amp.extern.js
> 🐛 Move Signals to AmpElement

- src/service/performance-impl.js
- test/unit/test-performance.js
https://github.com/ampproject/amphtml/pull/21060#issuecomment-470652789
Also clean up the test code.
/cc @ericandrewlewis
> Performance service can't get other services too early

- extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js
Mea culpa. Fixes #21332 introduced by #20905.
Will introduce unit tests in a later PR so this won't happen again.
> 🐛 Fix bad translate from refactor

- extensions/amp-base-carousel/0.1/array-util.js
- extensions/amp-base-carousel/0.1/carousel.js
Some cleanup in #21321 removed some needed functionality,
The e2e tests did fail as a result, but I didn't run them manually and they don't run on submit yet.
/cc @cvializ
> amp-base-carousel: fix the result of some cleanup.

- extensions/amp-story/1.0/amp-story.css
With #20981, the `font-size` seems fairly small.  This increases it by 25%.
> 🖍 Increase base font-size of amp-story

- extensions/amp-story/amp-story.md
Closes #20260
It'd be good to update the [ABE docs for visual effects in stories](https://ampbyexample.com/stories/visual_effects/ken_burns/) too, but we can leave that for later. This will be good enough for publishers to use.
> 📖  Add docs for new parameters in zoom/pan animations

- build-system/tasks/e2e/README.md
- build-system/tasks/e2e/describes-e2e.js
- contributing/TESTING.md
/to @cathyxz @sparhami 
/cc @estherkim 
/cc @CrystalOnScript not sure if you'd want to review this but in case
> 📖Document common questions about writing E2E tests

- extensions/amp-base-carousel/0.1/test-e2e/test-arrows-non-looping.js
- extensions/amp-base-carousel/0.1/test-e2e/test-arrows.js
- extensions/amp-base-carousel/0.1/test-e2e/test-mixed-lengths-no-snap.js
Fixes https://github.com/ampproject/amphtml/issues/21243
> Split up test-arrows and test-mixed-lengths

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
Launches https://github.com/ampproject/amphtml/issues/14060. 
/cc @nainar
> Launch amp-list-load-more to 100% of canary and production

- extensions/amp-story/1.0/test/validator-amp-story-amp-twitter-error.html
- extensions/amp-story/1.0/test/validator-amp-story-amp-twitter-error.out
- extensions/amp-story/1.0/test/validator-amp-story-amp-twitter.html
- extensions/amp-story/1.0/test/validator-amp-story-amp-twitter.out
- extensions/amp-story/validator-amp-story.protoascii
> Enable validation for amp-twitter

- extensions/amp-story/1.0/pagination-buttons.css
Updating the fullbleed desktop navigation icons, as described in the attached issue.
Fixes #21302
> Updating the fullbleed desktop navigation icons.

- extensions/amp-story/1.0/amp-story-share-menu.css
- extensions/amp-story/1.0/amp-story-share.css
Story share menu margins and background color.
Closes #21365
> Story share menu margins and background color.

- build-system/global-configs/prod-config.json
> ⬆️ ramp up `amp-auto-lightbox` to 50%

- extensions/amp-fx-collection/0.1/providers/amp-fx-presets-utils.js
- extensions/amp-fx-collection/0.1/providers/fx-provider.js
- extensions/amp-fx-collection/0.1/scroll-toggle.js
- src/custom-element.js
- src/layout.js
- src/preconnect.js
- src/service/fixed-layer.js
- src/service/jank-meter.js
- src/service/standard-actions-impl.js
- src/service/url-replacements-impl.js
- src/service/viewport/viewport-binding-ios-embed-sd.js
- src/service/viewport/viewport-impl.js
- test/unit/test-layout.js
- test/unit/test-viewport.js
Reverts #21083 (and #21343, which fixed a bug in #21083).
> ⏪ Revert Support amp-fx=float-in-* in viewer

- extensions/amp-sidebar/amp-sidebar.md
Fix typo in the sidebar documentation.
> Fix typo in the sidebar documentation.

- extensions/amp-a4a/0.1/a4a-variable-source.js
- extensions/amp-a4a/0.1/test/test-a4a-var-source.js
- extensions/amp-analytics/0.1/vendors.js
> Remove adNavTiming, adNavType, and adRedirectCount

- src/service/performance-impl.js
- test/unit/test-performance.js
> 🐛✅Fix tickevent tests for Safari

- ads/google/a4a/test/test-utils.js
- ads/google/a4a/utils.js
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Setup experiment 'amp-ad-ff-adx-ady' used in AdSense/Doubleclick experiment setting adx/ady to 1 instead of 0.
> AdSense/Doubleclick Fast Fetch adxy experiment

- extensions/amp-carousel/0.1/scrollable-carousel.js
- extensions/amp-image-slider/0.1/amp-image-slider.js
These extensions added layers support with the understanding that layers redoes the prioritization of elements. Now that we've experiment guarded the prioritization code, we need to guard here too.
> ♻️ Disable layers prioritization code in extensions

- package.json
- yarn.lock
See https://github.com/ampproject/worker-dom/releases/tag/v0.3.0
> WorkerDOM: upgrade to 0.3.0

- extensions/amp-story/validator-amp-story.protoascii
Stories `animate-in-timing-function` parameter validation rules.
It can be used like this:
```
<p animate-in="fly-in-right" animate-in-duration="600" animate-in-timing-function="linear">
...
</p>
```
> Stories animate-in-timing-function parameter validation.

- ads/caprofitx.js
- ads/caprofitx.md
- examples/ads.amp.html
Add a new ad serving method by `'mediaid'` with rich features.
Changes:
- Remove data validation at caprofitx.js (we will validate on our side)
- Update CA ProFit-X's document and examples
> ✨ Add CA ProFit-X's new ad serving method

- extensions/amp-story/1.0/test/validator-amp-story-amp-twitter.html
- extensions/amp-story/1.0/test/validator-amp-story-amp-twitter.out
- extensions/amp-story/validator-amp-story.protoascii
#19213 #16522
Support new `interactive` attribute added in #21402 for dead embeds.
> ✨ Validation for new interactive attribute

- examples/visual-tests/amp-story/amp-story-tooltip-desktop.js
- examples/visual-tests/amp-story/amp-story-tooltip.html
- examples/visual-tests/amp-story/amp-story-tooltip.js
- extensions/amp-story/1.0/amp-story-embedded-component.js
Read #21402 for more context
#19213 #16522
> ✅ Add visual diff tests for dead embeds

- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/integration/test-amp-list.js
- extensions/amp-list/amp-list.md
- test/manual/amp-list/infinite-scroll-fail.amp.html
Partial for #18875. Will remove experiment config 2 release cycles from this PR.
> 🚮Cleanup amp-list-resizable-children experiment

- build-system/routes/list.js
- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list-load-more.js
- test/manual/amp-list/infinite-scroll-1.amp.html
- testing/test-helper.js
Fixes https://github.com/ampproject/amphtml/issues/21455. This was a previously solved problem, but regressed. Added a regression test for future proofing this.
> Fix duplicate items in load-more when scrolling fast

- extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
Buttons doc: document lang option (#526)
Add productType parameter to offers and contributions flow (#525)
Contributions API updates and documentation (#523)
Button title text changes for i18n (#524)
button-api: fix Spanish button titles (#522)
> swg-release 0.1.22.47

- examples/autocomplete.amp.html
- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Support submit-on-enter attribute on amp-autocomplete.
> ✨Support submit-on-enter attribute on amp-autocomplete.

- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
> 🐛Fix lightbox shim appearing on top of the captions.

- extensions/amp-story/1.0/test/validator-amp-story-amp-instagram-error.html
- extensions/amp-story/1.0/test/validator-amp-story-amp-instagram-error.out
- extensions/amp-story/1.0/test/validator-amp-story-amp-instagram.html
- extensions/amp-story/1.0/test/validator-amp-story-amp-instagram.out
- extensions/amp-story/1.0/test/validator-amp-story-amp-twitter-error.html
- extensions/amp-story/1.0/test/validator-amp-story-amp-twitter-error.out
- extensions/amp-story/1.0/test/validator-amp-story-amp-twitter.html
- extensions/amp-story/1.0/test/validator-amp-story-amp-twitter.out
- extensions/amp-story/validator-amp-story.protoascii
> ✨ Validation for amp-instagram in amp-story

- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors/gtag.js
> ✨ Add a marker to floodlight request to indicate dynamic tags.

- test/integration/test-amp-ad-fake.js
- test/integration/test-amp-inabox.js
- test/unit/test-resources.js
e.g.,
test-amp-ad-fake.js: https://travis-ci.org/ampproject/amphtml/jobs/509933790#L1519-L1524
test-resources.js: https://travis-ci.org/ampproject/amphtml/jobs/509628807#L1545-L1547
> ✔️ Disable two flaky tests

- spec/amp-cache-transform.md
Also, propose future work of integration with HTTP Variants.
> 📖 Document q-values / media type params alternative.

- examples/linkers.html
- extensions/amp-analytics/0.1/cookie-writer.js
- extensions/amp-analytics/0.1/linker-manager.js
- extensions/amp-analytics/0.1/linker-reader.js
- extensions/amp-analytics/0.1/test/test-cookie-writer.js
- extensions/amp-analytics/0.1/test/test-linker-manager.js
- extensions/amp-analytics/0.1/test/test-linker-reader.js
- extensions/amp-analytics/0.1/test/test-requests.js
- extensions/amp-analytics/0.1/test/test-resource-timing.js
- extensions/amp-analytics/0.1/test/test-variables.js
- extensions/amp-analytics/0.1/variables.js
Closes #20864
Also related to b/122839876
> ✨Allow LINKER_PARAM macro use more broadly

- build-system/global-configs/prod-config.json
> ⬆️ramp up auto-lightbox to 100% for April 2nd prod.

- build-system/dep-check-config.js
- bundles.config.js
- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-attribution.css
- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
And don't position it in the center if in `supports-landscape` mode.
Closes #21424
> 🐛Move `ad` badge to shadow DOM

- extensions/amp-live-list/0.1/live-list-manager.js
- extensions/amp-live-list/0.1/test/test-live-list-manager.js
- src/service/url-impl.js
> ✨Allow amp-live-list to fetch from CDN if transformed

- extensions/amp-subscriptions/amp-subscriptions.md
Describe intended use of data property and usage limitations.
> amp-subscriptions doc: update entitlement response guidance

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
Changes in this version
Propensity API (#514)
> SwG Release 0.1.22.48

- spec/amp-email-format.md
To be in sync with https://github.com/ampproject/docs/blob/future/pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-email-format.md
> 📖 Update AMP for Email spec

- extensions/amp-story/1.0/amp-story-system-layer.css
Fixing the story audio UX font size.
Fixes #21605
> Fixing the story audio UX font size.

- examples/analytics-vendors.amp.html
- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors.js
- extensions/amp-analytics/0.1/vendors/kenshoo.js
✨  Add [Kenshoo](https://kenshoo.com/) as an amp-analytics vendor.
> ✨ Add Kenshoo to AMP analytics vendors

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
Experiment should run on 5% on each branch.
> ✨ Ramp up auto ads responsive to 10%

- build-system/tasks/e2e/README.md
- build-system/tasks/e2e/index.js
- contributing/TESTING.md
> 🏗 Add watch mode to `gulp e2e`

- extensions/amp-carousel/amp-carousel.md
Stray `</p>` seems to be causing trouble on amp.dev.
> 📖 Fix layout issue in amp-carousel

- build-system/app.js
- examples/autocomplete.amp.html
- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
- extensions/amp-autocomplete/amp-autocomplete.md
Demo available at https://amp-autocomplete.firebaseapp.com
- Implement `none` filter on amp-autocomplete
- Add and test method `truncateToMaxEntries_`
- Add an endpoint in `app.js` that takes a query parameter and returns a JSON
- Add example usage of `filter="none"` in `autocomplete.amp.html`
- Update documentation
> ✨ Implement `none` filter on amp-autocomplete.

- build-system/global-configs/prod-config.json
50% launch for #19513, targeting canary release on April 2. 
/cc @nainar
> Launch auto-sizes to 50% of production

- extensions/amp-story/1.0/amp-story-share.css
- extensions/amp-story/1.0/amp-story-share.js
Branching sharing option alignment.
Fixes #21642
> Branching sharing option alignment.

- build-system/tasks/runtime-test/helpers.js
Fixes bug pointed out by @rsimha here - https://github.com/ampproject/amphtml/pull/20117#discussion_r270273034, in the refactoring of `runtime-test.js`
> 🏗 Fix test local changes bug

- spec/amp-var-substitutions.md
A tiny word fix from height -> width here: https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#screen-width
> 📖 Small word fix for amp-var-substitutions.md

- extensions/amp-iframe/amp-iframe.md
Fixes https://github.com/ampproject/docs/issues/1576
> 📖 Update Google Maps API Key

- examples/analytics-scrollDepth.amp.html
- extensions/amp-analytics/0.1/test/test-events.js
- extensions/amp-analytics/0.1/test/test-visibility-manager.js
- extensions/amp-analytics/0.1/test/test-visibility-model.js
- extensions/amp-analytics/0.1/visibility-manager.js
- extensions/amp-analytics/0.1/visibility-model.js
- spec/amp-var-substitutions.md
- src/layout-rect.js
Add initialScrollDepth, maxScrollDepth to visibility tracker
> Add isd, msd to visibility tracker

- SUPPORT.md
> 📖 Update links to amp.dev

- .github/ISSUE_TEMPLATE/intent-to-implement--i2i-.md
This adds a suggestion to the I2I template to sign the CLA as soon as possible.
/cc @torch2424
> Adds a suggestion to I2I template to sign CLA as soon as possible

- test/visual-diff/visual-tests
Tests are failing yet again...
Tracking for embedded component: #21665
Tracking for landscape template: #21749
> Disable flaky visual diff tests
