ampproject/amphtml

- src/service/resources-impl.js
This is a partial revert of #21128, since it may have caused a ads
metrics regression. I'm still confident that calling `dirtyElement` is
the correct behavior, but let's see...
> 🐛 Experiment guard dirtyElement call in collapseElement

- 3p/integration.js
- ads/_config.js
- ads/aja.js
- ads/aja.md
- examples/ads.amp.html
Adds support for CAaja ads network.
Hello.
We are A.J.A., a subsidiary of CyberAgent which provides ad-network service in Japan. (https://www.cyberagent.co.jp/) CA
(https://aja-kk.co.jp/) AJA
We'd like to add support to amp-ad.
Thanks.
previous↓
#21067
> ✨🐛RE_3:Add support for CAaja ads network

- build-system/tasks/e2e/expect.js
This allows E2E tests to wait for `ControllerPromises` to resolve `true`, `false`, or `ok` from a `FunctionalTestController`
/cc @dvoytenko
> ✅ Add support for Chai true, false and ok expectations

- extensions/amp-brid-player/0.1/test/validator-amp-brid-player.html
- extensions/amp-brid-player/0.1/test/validator-amp-brid-player.out
- extensions/amp-brid-player/amp-brid-player.md
- extensions/amp-brid-player/validator-amp-brid-player.protoascii
Added support for tags in dynamic playlists, and updated documentation for new attribute (https://github.com/ampproject/amphtml/pull/19190)
> Dynamic playlist tag support (amp-brid-player)

- extensions/amp-a4a/0.1/amp-ad-utils.js
- extensions/amp-a4a/0.1/test/test-amp-ad-utils.js
- extensions/amp-a4a/0.1/test/testdata/valid_css_at_rules_amp.reserialized.js
Normally, ad responses contain the offsets that point to the beginning and end of <script> tags included in the tag of creatives so that they can be excised, and if these offsets are missing the creative will not gain preferential rendering. This change will compute the offsets on the client, permitting the <script> tags to be excised even if the offsets are not included in the ad response.
Fixes #21381
> Scrub <script> tags from <head> of ad responses if offsets are missing 

- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list-load-more.js
- test/manual/amp-list/infinite-scroll-1.amp.html
This fixes a race condition where `attemptToFit_` is called before `loadMoreSrc` is initialized. 
The bug: 
`attemptToFit` is sometimes called before `loadMoreSrc` is initialized (i.e. when the placeholder element is larger than `<amp-list>` and needs to be resized, or if a viewport resize is triggered before layout callback completes). This is slightly more severe on higher latency networks due to the need to wait for load and installation of the origin experiments extension.
> [amp-list] Fix race condition on access to this.loadMoreService_ 

- build-system/tasks/visual-diff/index.js
Help gather more info for #21056 
Currently only some `Error` objects include the test name in their title, which makes it harder to find which tests cause the crash when the `Error` is thrown from Puppeteer, instead of from our own custom functions in `helper.js`
> 🏗 Add test name to error messages in visual-diff

- extensions/amp-image-viewer/0.1/amp-image-viewer.js
Add a tap listener to propagate clicks within the image viewer. Previously, clicks would only be propagated while zoomed in. Additionally, doubling tapping while zoomed in would cause the controls toggle twice (i.e. if they were visible, they would hide, then reshow; if they were hidden, they would show then hide again). Now, tapping will always propagate the click as long as it is not a double tap gesture.
Fixes #21431
/cc @cathyxz
> 🐛Make click event available to ancestors of image viewer.

- examples/visual-tests/amp-story/amp-story-sidebar.html
- examples/visual-tests/amp-story/amp-story-sidebar.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/test/test-amp-story.js
Resolves #21050
When sidebar for stories closes via an amp action, the story opacity mask should also close. 
Because the opacity mask was created for the use of sidebar specifically in stories, closing/opening the story mask is not bound to the sidebar's closing/opening. We solve this issue by directly toggling the mask when the sidebar's state is changed.
> 🐛Close opacity layer when sidebar for stories closed via action

- extensions/amp-story/1.0/amp-story-embedded-component.js
- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/page-advancement.js
- extensions/amp-story/1.0/test/test-amp-story-page.js
Dead embeds will behave like regular embeds but won't be interactive (i.e. they won't trigger the tooltip). 
This PR makes it so that publishers will have to explicitly opt-in to the interactive mode. They will be able to do this using the `interactive="true"` attribute on the embed.
Follow ups will be sent for validation / visual tests.
> ✨ Support dead embeds

- extensions/amp-story/1.0/animation-presets.js
- extensions/amp-story/1.0/animation.js
Updating the default stories animations curves and duration so they respect the material guidelines.
Animations are actually still slower than what's recommended but I don't want to introduce too big of a change.
Publishers could already override the animation duration, but this PR also introduces a way to provide their own timing function:
```
<p animate-in="fly-in-right" animate-in-duration="600" animate-in-timing-function="linear">
...
</p>
```
> Stories default animations curves and duration.

- extensions/amp-fx-collection/0.1/providers/amp-fx-presets.js
Apparently `calc(0 - -10vh)` is an invalid value but `calc(0px - -10px)` isn't. 😑
Partial for #21430.
> 🐛 Fix bad calc()

- css/amp.css
- extensions/amp-story/1.0/amp-story.css
Stories assets preloading is broken in a way that if you have a 10 pages story with an image on each page, these 10 images will get loaded right away.
This PR positions the `amp-story-page` elements far away from the viewport, until the story runtime starts adding `[active]` or `[distance]` attribute and controls when elements should be built and loaded by the AMP runtime.
If the AMP runtime is loaded before the AMP Story runtime, it would start building and loading `amp-img` and `amp-video` elements. To avoid these race conditions, the CSS fix is added to both `amp.css` and `amp-story.css`.
The behavior is the following: it hides all `amp-story-pages` except for the first page, until an `[active]` or `[distance]` attribute is added once the `amp-story.buildCallback/layoutCallback` are …
> 🚀 Story assets preloading improvements.

- examples/autocomplete.amp.html
- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
- extensions/amp-autocomplete/amp-autocomplete.md
Key decisions made to support rich content have been documented in the [Supporting plain and rich content](https://docs.google.com/document/d/1OOPnKgShbh7BN2D24u7bxa57z2spAiBA8n9o0L5V3qA/edit#heading=h.kd3r11jhzfrz) section of the amp-autocomplete design doc.
- Use template service to find and render templates.
- Create attribute "filter-value" (different name?) to know which property to filter off of when data is an array of JsonObject instead of an array of strings. Limitation: Can only filter off of one property.
- Require template to have "value" attribute that is the text that is inserted in the input field when the item is selected.
- Replaces isItemElement() with getItemElement() since not all elements that can be selected in a template item have the 'i-amphtml-autocomplete-item' …
> ✨Support rich content on amp-autocomplete. 

- src/dom.js
- test/unit/test-dom.js
This should be impossible, but sometimes the document is ready but the
body is not yet parsed. So, ensure the document has a body before
resolving `waitForBody`.
Fixes #21423.
> 🐛 Ensure body is available

- ads/purch.js
- ads/purch.md
Added support for "config" parameter in purch amp-ad adapter.
Tag format data-config='{"targeting":{"key1":"value1", "key2":"value2"}}'
This change is trivial, totally isolated to the purch amp-ad adapter and is totally backward compatible.
> ✨Added support for "config" parameter in purch amp-ad adapter.

- extensions/amp-autocomplete/0.1/amp-autocomplete.css
- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
This change is to replace the lastElementChild way of keeping track of the partial user input.
- Refactor amp-autocomplete (and accompanying tests) to save the partial user input locally
> ♻️Refactor amp-autocomplete to save the partial user input locally

- extensions/amp-image-viewer/0.1/amp-image-viewer.js
Instead of looking for the layout class or attribute, check for the
`<img>` element instead. This is a safer check as we can be sure that
the `<amp-img>` has completed its `layoutCallback`.
Fixes #21481
> 🐛Change check to see if amp-img has completed layout.

- build-system/global-configs/prod-config.json
Master issue: https://github.com/ampproject/amphtml/issues/19513. 
Relatedly, we tried out this feature in https://github.com/ampproject/amphtml/issues/17053, and found https://github.com/ampproject/amphtml/issues/21371. It is surfaced due to the change in this experiment but is fundamentally an issue with `layout=INTRINSIC`.  Since workarounds exist, we should be able to launch auto-sizes in parallel. However, if anything here is blocking and needs to be fixed prior to launching this to 10%, please kindly let me know. =) 
/fyi @westonruter
> Launch amp-img-auto-sizes to 10% of production

- extensions/amp-smartlinks/0.1/linkmate.js
- extensions/amp-smartlinks/0.1/test/test-linkmate.js
Follow up to https://github.com/ampproject/amphtml/pull/20967:
- Bug in `mapLinks_` function in `linkmate.js` was only mapping one set of links to the API response. Update that function to accurately map anchor values on the page to values in the API response.
- The `linkSelector` and `linkAttribute` config options weren't working properly because we weren't using `getAttribute`. Start doing that!
> 🐛amp-smartlinks fix bug in mapLinks_ function and attribute behavior

- extensions/amp-form/0.1/test/test-amp-form.js
- src/form-data-wrapper.js
- src/form.js
- test/unit/test-form-data-wrapper.js
- test/unit/test-form.js
Resolves #21498
GET form submits and POST form submits in browsers without `FormData.prototype.entries` support followed a code path that used `getFormAsObject` which was addressed by #18785
This PR adds the button used to submit the form to the `NativeFormDataWrapper` to add the value to `FormData` for all submit code paths. Includes regression tests.
/to @cathyxz @alanorozco 
/cc @aghassemi
> 🐛Include the submit button clicked in POST responses

- build-system/tasks/runtime-test/index.js
Fixes bug when running integration tests on local IE browser, e.g. `gulp test --integration --nobuild --ie`
Bug is that IE fails to launch. Uses `IE_no_addons` custom launcher as default, which disables IE extensions as instructed here:
https://github.com/karma-runner/karma-ie-launcher#running-ie-in-no-add-ons-mode
>  🏗 Fix launching IE when running integration tests locally

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
This is low risk experiment that fades a blurry-image placeholder into the real image when the real image loads.
> 🖍 Enable blurry-image placeholder transition experiment

- extensions/amp-access/0.1/amp-access.js
- extensions/amp-form/0.1/amp-form.js
- extensions/amp-viewer-assistance/0.1/amp-viewer-assistance.js
- src/service/action-impl.js
- test/unit/test-action.js
Prerequisite for #21322.
For action handlers of non-AMP elements, remove the `ActionTrust` check from registration time and allow the handler itself to do the check instead.
This is a simple solution to support both HIGH and LOW trust actions in a single handler.
/to @alabiaga
> Delegate trust check to action handler

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/test/test-amp-story-page.js
Introduces new selector so that `mediapool` can control audio/video elements that are inside a FIE (for ads).
I want to make sure that this new querySelector does not control anything we don't want. Specifically if a page attachment might ever have a FIE with media elements.
> 🐛Find media inside FIE

- extensions/amp-date-picker/0.1/amp-date-picker.js
- third_party/moment/moment.extern.js
> 🐛Fix bind data when start and end are the same

- extensions/amp-access-scroll/0.1/amp-access-scroll.css
- extensions/amp-access-scroll/0.1/scroll-impl.js
This PR updates the styling of the placeholder rendered by the amp-access-scroll extension to match the content loaded in later (similar to #14993 )
cc @kushal
> 🐛Update Scroll amp-access extension placeholder CSS to match current UI

- spec/amp-cache-transform.md
`>` at the beginning of the line was creating a blockquote, even though
it was inside a backtick quote.
> 📖 Fix markdown formatting error

- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
- extensions/amp-autocomplete/amp-autocomplete.md
- Expose the `select` event on amp-autocomplete.
- Add documentation to the `md` file.
- Add a unit test for the new `fireSelectEvent_` method.
> ✨Expose the `select` event on amp-autocomplete.

- examples/visual-tests/amp-sidebar/amp-sidebar-toolbar-ol.amp.html
- examples/visual-tests/amp-sidebar/amp-sidebar-toolbar-ul.amp.html
- examples/visual-tests/amp-sidebar/amp-sidebar-toolbar.js
- extensions/amp-sidebar/0.1/amp-sidebar.css
- extensions/amp-sidebar/0.1/test/validator-amp-sidebar-autoscroll-valid.html
- extensions/amp-sidebar/0.1/test/validator-amp-sidebar-autoscroll-valid.out
- extensions/amp-sidebar/0.1/test/validator-amp-sidebar.html
- extensions/amp-sidebar/0.1/test/validator-amp-sidebar.out
- extensions/amp-sidebar/amp-sidebar.md
- extensions/amp-sidebar/validator-amp-sidebar.protoascii
- test/visual-diff/visual-tests
Resolves #20312 
- Validate `ol` as a child of `amp-sidebar > nav`.
- Add additional examples in validator tests
> 🐛Accept "ol" as a child of amp-sidebar > nav

- extensions/amp-consent/0.1/amp-consent.css
- extensions/amp-consent/0.1/consent-ui.js
- extensions/amp-consent/0.1/test/test-consent-ui.js
- test/manual/diy-consent.html
closes #21324
This allows for setting an initial height between `10vh` and `60vh` on iframe ready. As well as optionally removing the border radius and box shadow on the consent iframe container 😄
> ✨amp-consent: consent-ui Allow Passing Initial styles on ready

- extensions/amp-story/0.1/test/validator-amp-story-animations-error.out
- extensions/amp-story/0.1/test/validator-amp-story-animations.out
- extensions/amp-story/0.1/test/validator-amp-story-consent-geo.out
- extensions/amp-story/0.1/test/validator-amp-story-consent.out
- extensions/amp-story/0.1/test/validator-amp-story-cta-layer-error.out
- extensions/amp-story/0.1/test/validator-amp-story-cta-layer.out
- extensions/amp-story/0.1/test/validator-amp-story-deprecated.out
- extensions/amp-story/0.1/test/validator-amp-story-reference-point.out
- extensions/amp-story/0.1/test/validator-amp-story-video-error.out
- extensions/amp-story/0.1/test/validator-amp-story.out
- extensions/amp-story/0.1/test/validator-empty-story.out
- extensions/amp-story/1.0/test/validator-amp-story-deprecated.out
- extensions/amp-story/validator-amp-story.protoascii
This has been documented as deprecated in the spec, blog post, email, and Slack channels. The validator has been triggering deprecation warnings based on the APIs used, but not based on the version of the script; this PR adds that change.
See #21251 for the intent to implement.
> 🚮 Mark version 0.1 of amp-story as deprecated

- extensions/amp-image-viewer/0.1/amp-image-viewer.js
This reverts commit a62890252b6c2875cd5f9bff755f4f9a5c744869.
This breaks re-opening the lightbox gallery after closing it on Safari.
/cc @jridgewell @aghassemi
> Revert "🐛Change check to see if amp-img has completed layout. (#21483)"

- extensions/amp-position-observer/amp-position-observer.md
This PR addresses the missing documentation for the valid use of the 'once' attribute for 'amp-position-observer'.
When using this boolean attribute, the value must be unassigned, an empty string or set to 'once' in order to pass the AMP validator.
> 📖 Clarify documentation for 'once' attribute

- extensions/amp-image-viewer/0.1/amp-image-viewer.js
Change the check to see if we already have an img to be more robust by checking
if we already extracted the `img` from the `amp-img`, which only happens after
the `amp-img` has laid out once.
A variation of this was first attempted in #21483, which was reverted.
Fixes #21481 
/cc @jridgewell It turns out because we are doing weird stuff, we cannot rely on the `LOAD_END` signal from the `amp-img`. It is a bit weird that we didn't encounter the issue on Chrome. This seems to stem from the image viewer getting the unlayout callback on Safari and not on Chrome. This results in Chrome never hitting this code path. Not sure why it isn't happening on Chrome, maybe Safari behaves differently due to fixed layer?
> 🐛Fix incorrectly sized image viewer images.

- extensions/amp-story/1.0/media-pool.js
- extensions/amp-story/1.0/test/test-media-pool.js
This PR allows MediaPool to play any number of media elements (fixes #13476), by fixing a bug with the `replaced-media` property in MediaPool.  Copying from the bug:
> This affects both audio and video.  If `n` is the size of the MediaPool for the specified media type, then the you will encounter an error once you navigate to the page containing the `2n+1`th media element of that type.
> 
> This is because we delay clear the associated `replaced-media` after the promise from the `SwapOutOfDomTask` resolves:
> 
> https://github.com/ampproject/amphtml/blob/969a0a0ea9d093010f03980cbf61a898970b248a/extensions/amp-story/1.0/media-pool.js#L570-L574
> 
> The `SwapOutOfDomTask` is executed in a microtask.  However, when this media element is being swapped back into the DOM, there is synchronous …
> 🐛 Fix replaced-media pointer in MediaPool

- extensions/amp-story/1.0/media-pool.js
This PR adds clearer IDs to pool media:
- Placeholder elements (those specified by the publisher) will get IDs in the form of `i-amphtml-placeholder-media-0` through `i-amphtml-placeholder-media-n` when registered in the media pool
- Pool elements (those created in MediaPool's internal implementation) will get IDs in the form of `i-amphtml-pool-media-0` through `i-amphtml-pool-media-n` when created
This PR also does a proper check for whether an element originated from the media pool; originally we just checked to see if it was in the `allocated` array, but this switches to check the `i-amphtml-pool-media` class name, since we could accidentally put a placeholder video in the `allocated` array.
> ♻️ Update media pool with clearer IDs and proper pool membership check

- extensions/amp-access/0.1/amp-access.js
Fixes #21623
This will prevent document authors from erroneously specifying amp-access configs in non-script tags, which would cause the cache to remove the `amp-access` extension.
> 🐛Make non-script amp-access configs a runtime error

- .travis.yml
Reverting #20749 which had unintended side-effects (e.g., #21636 is a PR that created both a pr build and a push build on Travis)
> 🏗 Remove `^revert-.*$` branch names from push-build config on Travis

- contributing/contributing-code.md
This documents the TSC's definition of code review approval/merging roles as described in ampproject/meta-tsc#3.
Since this seemed (a) specific to amphtml and (b) not really about governance I removed the earlier versions of these roles from ampproject/meta/GOVERNANCE.md and added these definitions in the code contribution docs for amphtml.
(Other repos that want to follow the same process can link to this definition.  Repos that want to use a different process can define them in their CONTRIBUTING.md)
/cc @ampproject/tsc @erwinmombay @rsimha @tobie
> Defines code review & approval roles

- extensions/amp-a4a/amp-a4a-format.md
Will be properly retired as part of https://github.com/ampproject/amphtml/issues/21340 but removing documentation so it doesn't cause further developer confusion.
CC @ampproject/a4a
> 🚮Deleting amp-youtube from the a4a-spec

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/media-pool.js
- extensions/amp-story/1.0/media-tasks.js
- extensions/amp-story/1.0/test/test-media-tasks.js
Using an `amp-audio` element on the first page of a story has two issues:
- Playing the audio will fail since there was no user intent, and trigger the "Play this video" UI message that's supposed to be for videos only -> we stop triggering this message, and rely on the story unmute button to play the audio
- Unmuting the story will unmute the audio, but not play it -> play the audio if it wasn't playing when it's unmuted
Fixes #21604
> Fix amp-audio on the first page of a story.

- extensions/amp-story/1.0/amp-story-render-service.js
- extensions/amp-story/1.0/amp-story.js
- src/render-delaying-services.js
Followup to #21193.  This fixes the previously-broken definition for amp-story, so that it may block on it's `layoutCallback` before rendering.
Fixes #21349
> 🐛 Block initial amp-story render on amp-story layout

- examples/experiment-1.0.amp.html
- extensions/amp-experiment/1.0/amp-experiment.js
- extensions/amp-experiment/1.0/test/test-amp-experiment.js
- extensions/amp-experiment/1.0/test/test-variant.js
- extensions/amp-experiment/1.0/variant.js
relates to #21484
This starts the config parser for the 1.0 format (see #20225). Most importantly here, this preserves the analytics, but also passes an object down to `applyMutations_()` which can then use a mutation service to start ingestion of mutations (later PR).
**First image had some testing code to show things work**
> ✨Started a config parser for the amp-experiment 1.0 format

- src/service/performance-impl.js
Removing the prerender check for the 'visible' performance mark and instead waiting on this.viewer_.whenFirstVisible() in all cases
When measuring the performance of a page using amp signed exchange (SXG) we don't want to wait on the hasBeenVisible since there is no prerender. 
See this document for more details: https://docs.google.com/document/d/1DcnglmBUuZ6pLp_Y3cn0c9StJOIfUAricQtdj--Fbm4/edit?ts=5c8a697e#
> ✨ Removing prerender check to include SXG performance marks

- build-system/tasks/karma.conf.js
- package.json
- yarn.lock
Based on previous TravisCI test results, I've researched the issue of why Sauce Labs test runs are not working properly and timing out improperly. It looks like [this issue](https://github.com/karma-runner/karma-sauce-launcher/issues/159) in the karma-sauce-launcher project is at play here. Based on the thread there, I've downgraded the version of karma-sauce-launcher in this PR to `1.2.0` to see if this resolves the issue. 
In the meantime, I've also opened a [pull request](https://github.com/karma-runner/karma-sauce-launcher/pull/161) in the karma-sauce-launcher project to try to resolve this issue. It appears functionality to keep Sauce Labs sessions alive that was present in v1.x versions of the karma-sauce-launcher have been lost in v2.x and I'm trying to reintroduce them.
> 🏗 Workaround attempt for Sauce Labs timeout issues  

- extensions/amp-story/1.0/amp-story-store-service.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/test/test-amp-story.js
Adds a `[orientation=landscape|portrait]` attributes on the `<amp-story>` element, meant to make CSS styling across experiences and orientations easier for publishers.
This orientation attribute describes how the story is displayed, and not the viewport, like would a CSS media query. Eg: for the desktop three panels UI, the orientation will be `portrait`, when the viewport is actually `landscape`.
Part of #21661
> Add orientation and device attributes on the amp-story element.

- .github/ISSUE_TEMPLATE/cherry_pick_template.md
Suggested guidelines:
- The mini-PM should be written soon after the cherry-pick is deployed.
- A mini-PM is required for production cherry-picks, but optional for RC-only cherry-picks.
- If required, the mini-PM must be written and its action items completed before the cherry-pick issue can be closed.
/to @mrjoro
> Add mini-postmortem to cherry-pick template

- test/visual-diff/visual-tests
Disable embedded component desktop visual diff tests.
Tracked in #21665
> Disable embedded component desktop visual diff tests.

- extensions/amp-analytics/0.1/amp-analytics.js
- extensions/amp-analytics/0.1/config.js
- extensions/amp-analytics/0.1/test/test-amp-analytics.js
- extensions/amp-analytics/0.1/vendors/googleanalytics.js
Modifies the vendor configuration for optout. Vendors currently configure optout by adding the following:
```
'optout': 'function.name'
```
This updates it so that a vendor can specify a function name or an element in the DOM that will cause analytics to be opted out.
```
'optout': {
'function': 'function.name',
'id': 'elementId'
}
```
Based on the conversation in the issue, we're leaving backwards compatibility for now, until GTM is able to deploy a change to use the updated optout format. Because of this, there is duplicate code so that it will be an easy to remove the backwards compatibility once the GTM changes roll out.
> ✨ Add additional analytics opt out mechanism. (#21163)

- extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js
- extensions/amp-recaptcha-input/0.1/test/test-amp-recaptcha-input.js
closes #2273 
This removes the experiment for `amp-recaptcha-input`. Thus launching this feature, and making this available to the public! 😄 
This should be **approved before April 8th, 2019**, and **merged on April 8th, 2019**. In order to line up with a certain date 👀 
Also, this should have a paired documentation update to inform users the feature is no longer experimental 😄 After this goes live in PROD (to avoid confusion).
> ✨amp-recaptcha-input: Removed experiment from amp-recaptcha-input

- build-system/dep-check-config.js
- extensions/amp-experiment/1.0/amp-experiment.js
- extensions/amp-experiment/1.0/test/test-amp-experiment.js
Ironic title 😂 
This creates the experiment check for `amp-experiment-v1` with support for origin trial checking (as I trust we will be going down that path, cc @jeffjose ).
**Before Enabling Experiment**
**After Enabling Experiment**
> ✨amp-experiment-v1: Created experiment for amp-experiment-v1

- extensions/amp-viewer-assistance/0.1/amp-viewer-assistance.js
- extensions/amp-viewer-assistance/0.1/test/test-amp-viewer-assistance.js
- extensions/amp-viewer-assistance/amp-viewer-assistance.md
In response to [this discussion comment](https://github.com/ampproject/amphtml/pull/21512/files/bc39a41be26b7510b29a037419f7800a878ed97f#r268412642), I created a whitelist for valid action statuses that can be passed via `amp-viewer-assistance` and `updateActionState`.
/cc @choumx
> ✨ Create whitelist for amp-viewer-assistance.updateActionState actionStatus

- extensions/amp-base-carousel/0.1/carousel.css
This will result in much more predictable carousel swiping behavior for browsers that support the property.
> Use `scroll-snap-stop` for amp-base-carousel

- validator/engine/validator_test.js
Extension spec tests were accidentally gated under a check for custom attrs, and so weren't running.  Reenable them, after tweaking them so they're no longer broken.
> ✅validator tests: enable extension spec testing

- examples/visual-tests/amp-story/amp-story-tooltip-desktop.js
- test/visual-diff/visual-tests
Closes #21665
Ran tests repeatedly (20+ times/variation) and 800ms seemed to be the sweet spot.
> ✅  Re-enable embedded component desktop tests

- extensions/amp-story/amp-story.md
Fixes ampproject/docs#1724: the amp-story documentation is currently not available when filtering for format stories.
/cc @sebastianbenz, @CrystalOnScript
> 🐛 Update frontmatter for amp-story documentation.

- build-system/tasks/serve.js
Turns out this is already handled by `nodemon`, we simply need to add the devdash module path to watch and reload server.
> 🚀  Watch devdash modules for server reload

- build-system/amp.extern.js
- extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
- test/integration/test-amp-recaptcha-input.js
closes #21009 
relates to #20541
Simple fix, added data to the externs as mentioned by @erwinmombay 😄 
Also, this bumps the amp-mustache version, to then get the test fully working.
> 🐛 amp-recaptcha-input: Fixed single pass tests

- examples/experiment-1.0.amp.html
- extensions/amp-experiment/1.0/amp-experiment.js
- extensions/amp-experiment/1.0/mutation-parser.js
- extensions/amp-experiment/1.0/test/test-amp-experiment.js
- extensions/amp-experiment/1.0/test/test-mutation-parser.js
[Example Config in docs.snippets.json](https://glitch.com/edit/#!/amp-optimize-playground).
This starts the "Mutation Record" parser for `amp-experiment`. This only does the base "Mutation Record", Parsing specific mutations and returning functions to apply these mutations will come in later PRs. Thus, there is specific code that is there to outline how mutations will operate, and meant to demonstrate the API. This will be removed as it is not completed to keep PRs small(er).
**This original PR still requires tests. Let me know when the API looks good and should have tests written.**
cc @calebcordry 
**Note, this simple returns the mutation records in the console. This code was removed, and was meant for testing purposes.**
> ✨amp-experiment: Mutation Parser for 1.0 format

- contributing/TESTING.md
When Percy flakes it's not obvious how to rerun it, since you can't do that from within Percy.  Added docs on how to handle it.
> 📖Document how to rerun Percy on a PR

- examples/experiment-1.0.amp.html
- extensions/amp-experiment/1.0/mutation-parser.js
- extensions/amp-experiment/1.0/test/test-mutation-parser.js
This implements some base functionality for amp-experiment for an upcoming initial demo. This includes support for some of the `attributes` type mutations (style with `color` and `background-color`, src, and href), as well as `characterData` mutations 😄
> ✨amp-experiment: Base functionality for Demo

- contributing/contributing-code.md
Adds a bullet point to sign the CLA at the start of both the "minor change" and "significant change" section to encourage kicking off the CLA acceptance process as early as possible.
/cc @torch2424
> Emphasize signing CLA as soon as possible in contribution docs

- src/url.js
Issue: #20543 
This change adds 127.0.0.1 to the exceptions for secure urls.
> 🐛 Implemented secure url exception for http://127.0.0.1

- src/service/resources-impl.js
When the Layers experiment was enabled, dirtying the element would invalidate Layer's cached measurements. But I forgot to invalidate Resource's measurement state, which controls signals to the AMP elements (like, `onLayoutMeasure` and `onMeasureChanged`).
This has a particularly bad affect on A4A ads, since they initiate ads requests during `onLayoutMeasure`!
> 🐛 Layers: Bust Resource's measurements when dirtying

- examples/amp-script/hello-world.js
- extensions/amp-script/0.1/amp-script.js
- package.json
- yarn.lock
See:
* https://github.com/ampproject/worker-dom/releases/tag/v0.4.0
* https://github.com/ampproject/worker-dom/releases/tag/v0.5.0
* https://github.com/ampproject/worker-dom/releases/tag/v0.6.0
> WorkerDOM: upgrade to 0.6.0

- extensions/amp-experiment/1.0/mutation-parser.js
- extensions/amp-experiment/1.0/test/validator-amp-experiment.html
- extensions/amp-experiment/1.0/test/validator-amp-experiment.out
- extensions/amp-experiment/validator-amp-experiment.protoascii
relates to #21734
This updates the validator to accept the 1.0 version of amp-experiment. As well as adresses a [regex comment on the previous amp-experiment mad by @honeybadgerdontcare ](https://github.com/ampproject/amphtml/pull/21734#discussion_r272765479), that we agreed to implement offline.
> ✨amp-experiment: 1.0 Validation, and Regex Updates

- extensions/amp-web-push/0.1/amp-web-push-config.js
- extensions/amp-web-push/0.1/test/test-web-push-config.js
- extensions/amp-web-push/0.1/test/test-web-push-service.js
- extensions/amp-web-push/0.1/web-push-service.js
- extensions/amp-web-push/amp-web-push.md
Fixes #19023 
Allows **amp-web-push** to:
- Declare Service Workers in subdirectories.
- Declare custom scopes for Service Workers.
**Instructions to test locally:**
The component requires absolute urls on HTTPS to work. The following steps will allow to test the component locally (a proper test on a public URL is still required after going live).
1. Bypass requirements for public and HTTPS urls, by commenting from [this line](https://github.com/ampproject/amphtml/blob/7b16d1cc109eb77a8e0477dd8eff9501fae638b2/extensions/amp-web-push/0.1/amp-web-push-config.js#L85) to [this line](https://github.com/ampproject/amphtml/blob/7b16d1cc109eb77a8e0477dd8eff9501fae638b2/extensions/amp-web-push/0.1/amp-web-push-config.js#L115) of amp-web-push-config.js.
2. Make sure to compile first with ``gulp …
> ✨ Allowing custom scope for SW in <amp-web-push>

- build-system/tasks/runtime-test/index.js
Follow up to #20574 where Chrome and Edge were disabled on integration tests.
> 🏗 Reenable Edge and Chrome on Remote Tests (Sauce Labs) job

- extensions/amp-video/0.1/test/test-amp-video.js
Skips a failing test on AMP Video, that somehow doesn't fail the test suite, but aborts the file tests execution. This allows the following tests to actually run.
Also removes a console warning on the following test.
See #21767
cc @rsimha
> Skip AMP Video failing HTTP test.

- builtins/amp-img.js
- extensions/amp-anim/0.1/amp-anim.js
- extensions/amp-anim/0.1/test/test-amp-anim.js
- extensions/amp-anim/0.1/test/validator-amp-anim.html
- extensions/amp-anim/0.1/test/validator-amp-anim.out
- extensions/amp-anim/validator-amp-anim.protoascii
- extensions/amp-video/0.1/amp-video.js
- extensions/amp-video/0.1/test/test-amp-video.js
- extensions/amp-video/0.1/test/validator-amp-video.html
- extensions/amp-video/0.1/test/validator-amp-video.out
- extensions/amp-video/validator-amp-video.protoascii
- src/style.js
- test/unit/test-amp-img.js
- validator/validator-main.protoascii
This PR introduces a helper that retrieves the `object-fit` and `object-position` attributes of the element (ie: `<amp-img>`), and if they exist, sets inline styles on the childElement (ie: `<img>`). These inline styles are not marked as `!important`, so they can still be overridden by AMP extensions CSS if needed.
It gives better control to publishers over how their assets are displayed, by making it easier to select what part of the image should always be visible, or how the image should fit its container.
This helper is used for `amp-img`, `amp-video`, and `amp-anim`.
These styles are added right before the child element is appended to the DOM, so assets are rendered with the expected positions.
Since publishers have to explicitly write these attributes, this is not a breaking change. …
> object-fit and object-position attributes for amp-img, amp-video, and amp-anim.

- .eslintignore
- .eslintrc
- build-system/eslint-rules/await-expect.js
This PR should prevent test writers from forgetting to `await` their `expect`s accidentally and having tests succeed when they shouldn't.
This PR also prevents the generated code in the `firebase` directory from getting linted and making the `gulp lint` task take longer
> 🏗 Add lint rule to enforce that e2e test `expects` are `await`ed

- build-system/global-configs/prod-config.json
This PR should merge **after** canary cut on April 9, 2019 and **before** canary cut on April 16, 2019.
> Launch amp-img-auto-sizes to 100% of production

- test/integration/test-amp-inabox.js
- test/integration/test-amp-recaptcha-input.js
We recently re-enabled testing on Edge. This PR skips a few tests that don't work on the browser.
Logs: https://travis-ci.org/ampproject/amphtml/jobs/518345369#L1599-L1654
Follow up to https://github.com/ampproject/amphtml/pull/21796#issuecomment-481860023
> ✅ Skip some tests that fail on Edge now that we're running tests on the browser

- extensions/amp-script/0.1/test/integration/test-amp-script.js
We recently enabled testing on a few Windows browsers (Edge, Firefox, and Chrome). This PR disables some newly found `amp-script` integration test failures on Windows.
**Edge:** https://travis-ci.org/ampproject/amphtml/jobs/518429019#L2287-L2360
**Firefox:** https://travis-ci.org/ampproject/amphtml/jobs/518429019#L2369-L2457
**Chrome:** https://travis-ci.org/ampproject/amphtml/jobs/518429019#L2460-L2527
Follow up to https://github.com/ampproject/amphtml/pull/21796#issuecomment-481860023
> ✅ Skip `amp-script` tests on Windows (Edge, Firefox, and Chrome)

- test/integration/test-amp-inabox.js
#21812 skipped some `inabox` tests on Edge, now that we've enabled testing on a few new browsers. It turns out the failures are widespread across all Windows browsers (Edge, Firefox, and Chrome).
**Logs:** https://travis-ci.org/ampproject/amphtml/jobs/518516284#L1574-L1595
This PR skips the tests on Windows. They still continue to be run on Linux and Mac OS.
Follow up to #21812
> ✅ Skip `inabox` tests on Windows, not just Edge

- build-system/tasks/e2e/describes-e2e.js
- build-system/tasks/e2e/index.js
The PR is an attempt to fix the inconsistent number of E2E tests being run on Travis.
It's possible that test files are being cached. Mocha will skip test files that are in the node require cache, so this ensures that the cache is cleared.
~~This also attempts to fix this error - `NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.` by spinning up a WebDriver instance only once per describes(), instead of for each it().~~ Never mind about this, because some tests assume that a fresh page is spun up for each it()
> 🏗 Clear node require cache when running E2E tests

- build-system/tasks/karma.conf.js
We frequently see disconnect failures [of this sort](https://travis-ci.org/ampproject/amphtml/jobs/518812129#L2245-L2250) on Sauce Labs, even when tests pass:
```
Safari 12.0.0 (Mac OS X 10.13.6) ERROR
Disconnected, because no message in 240000 ms.
[15:51:38] Safari 12.0.0 (Mac OS X 10.13.6): Executed 38 of 517 (Skipped 62) SUCCESS
11 04 2019 15:51:38.676:ERROR [reporter.sauce]: ✖ Test Disconnected
```
Our tests take ~9 minutes for normal execution. This PR increases the values of `browserDisconnectTimeout` and `browserNoActivityTimeout` to 10 minutes each so that test runs don't fail if the browser doesn't communicate for that period (Safari in particular is known to stay silent while running tests). Once keepalives are implemented in `karma-sauce-launcher`, we can reduce these timeouts …
> 🏗 Change disconnect / no activity timeouts for Sauce Labs

- 3p/integration.js
- ads/google/a4a/utils.js
- build-system/dep-check-config.js
- build-system/shorten-license.js
- extensions/amp-analytics/0.1/iframe-transport.js
- extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
- src/3p-frame.js
- src/amp-shadow.js
- src/amp.js
- src/iframe-attributes.js
- src/inabox/amp-inabox-lite.js
- src/inabox/amp-inabox.js
- src/internal-version.js
- src/mode.js
- src/runtime.js
- src/service/url-replacements-impl.js
Through a lot of trial and error, I've identified the two areas where our sourcemaps were getting screwed up. Embarrassingly, it's the same two areas from #17251.
It turns out, combining two different modifications into a single sourcemap isn't trivial. So, I'm falling back on more of a hack:
When we shorten the license comments, I'm ensuring that the shortened license has the same number of lines as the original. We waste a couple of bytes, but now there's no issue with lines coming after being mapped to the incorrect line number.
Additionally, I've extracted the `$internalRuntimeVersion$` magic string into a single location. That means only 1 line will have incorrect source mappings (which will only affect the columns). That line happens very early in the file, with other things that …
> 🐛 Fix Source maps

- extensions/amp-list/0.1/test/integration/test-amp-list.js
Sets internal timeouts to make it obvious which poll is failing. Related to https://github.com/ampproject/amphtml/issues/21821.
> Update flaky integration test on amp-list

- ads/google/a4a/traffic-experiments.js
- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-a4a/0.1/test/test-amp-a4a.js
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
To isolate single pass and its controls performance characteristics, we need to send the experiment ids to be able to filter them.
> add single pass experiment IDs when needed.

- build-system/default-pre-push
- build-system/pr-check.js
- build-system/pr-check/local-tests.js
Fixed that issue noticed by Raghu in https://github.com/ampproject/amphtml/pull/21407#pullrequestreview-223524623
> Add explicity `--unit` to automated tests that run on `--local-changes`

- extensions/amp-bind/0.1/amp-state.js
- extensions/amp-list/0.1/amp-list.js
- extensions/amp-viewer-assistance/0.1/amp-viewer-assistance.js
- extensions/amp-viewer-assistance/0.1/test/test-amp-viewer-assistance.js
- extensions/amp-viewer-assistance/amp-viewer-assistance.md
With the introduction of #21512, `<amp-list>` now supports the `fetch-error` event. This change allows `amp-viewer-assistance` to report a failed XHR using the `fetch-error` event.
/cc @choumx
> ✨ Add support for "error" param for amp-viewer-assistance.updateActionState

- extensions/amp-list/amp-list.md
Updating documentation to reflect https://github.com/ampproject/amphtml/issues/14060.
> Update docs for amp-list to indicate that load-more is out of experimental

- build-system/single-pass.js
- build-system/tasks/compile.js
- package.json
- yarn.lock
This PR replaces `gulp-closure-compiler` (which has not received an update in 3 years) with the native `gulp` plugin that is part of `google-closure-compiler`. With this, we can do custom text replacements on `gulp.src` and pass them directly to closure compiler without having to copy the intermediate output to a temp directory.
Addresses https://github.com/ampproject/amphtml/issues/21828#issuecomment-483487677.
Partial fix for #21828
Follow up to #21830
Follow up to #16799
Fixes #21839
> 🏗 Replace `gulp-closure-compiler` with `google-closure-compiler`

- tools/experiments/experiments.js
Remove resizable children experiment from `experiment.js`. Do not merge before https://github.com/ampproject/amphtml/pull/21843.
> Remove resizable children experiment

- build-system/pr-check/checks.js
- build-system/tasks/runtime-test/index.js
- build-system/tasks/runtime-test/status-report.js
Add an early indicator for which test types are expected to run vs. which ones are skipped in the PR.
This PR also fixes the missing `skipped` status for `--local-changes`, which can be determined _after_ the `gulp test --unit --local-changes` command is executed (whether other test types get skipped is determined before executing their equivalent `gulp test` command)
> 🏗 Report queued/skipped tests to the test status app

- build-system/tasks/visual-diff/index.js
In debugging of #21056.
Note that this PR also removes a superfluous navigation to `about:blank` before the actual page navigation, since each page uses a separate, newly created tab. The explicit navigation to `about:blank` is holdout from older code, when we were reusing tabs. This change _might_ have the accidental side effect of fixing the above issue (although I doubt it)
> Add error logging for page navigation errors in visual diff tests

- extensions/amp-a4a/0.1/test/test-refresh.js
- extensions/amp-story/1.0/amp-story.js
- src/inabox/amp-inabox-lite.js
- src/intersection-observer-polyfill.js
- src/runtime.js
- src/service/fixed-layer.js
- src/service/hidden-observer-impl.js
- src/services.js
- test/unit/test-fixed-layer.js
- test/unit/test-hidden-observer.js
- test/unit/test-intersection-observer-polyfill.js
Creates a shared `hidden` attribute `MutationObserver`, so that we don't have extensions creating redundant MOs.
Fixes https://github.com/ampproject/amphtml/issues/19054
> ✨ Create a hidden attribute mutation observer service

- src/purifier.js
- src/sanitation.js
No longer needed now that we set `ALLOW_UNKNOWN_PROTOCOLS`.
/to @delima02
> DOMPurify: Remove special-case for "on" attribute

- spec/amp-cors-requests.md
> cors docs: caches.json is now the canonical source of cache info

- extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
- extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
Don't auto lightbox elements with subscriptions-action attribute and their descendants
> 🐛  don't auto lightbox elements with subscriptions-action attribute

- extensions/amp-geo/0.1/amp-geo.js
`String.p.trim` is now optimized away by closure compiler, so we need to switch to something that can't be optimized. This regex works well enough.
Our possible cases are:
1. `'{{AMP_ISO_COUNTRY_HOTPATCH}}'` (CDN fails to hotpatch)
- `match` will equal `['', undefined]`
2. `'jp                          '` (CDN hotpatches, appends spaces to preserve sourcemaps)
- `match` will equal `['jp                          ', 'jp']`
3. `'                            '` (CDN can't determine country code)
- `match` will equal `['                            ', undefined]`
4. `'jp'` (CDN hotpatches, but doesn't preserve sourcemaps)
- `match` will equal `['jp', 'jp']`
Fixes #21915
> 🐛 Update amp-geo country code hotpatch detection

- build-system/runner/src/org/ampproject/AmpCommandLineRunner.java
- build-system/runner/src/org/ampproject/AmpPass.java
- build-system/runner/test/org/ampproject/AmpPassTest.java
- build-system/runner/test/org/ampproject/AmpPassTestEnvTest.java
- build-system/single-pass.js
- build-system/tasks/compile.js
- src/internal-version.js
This implements a compile time constant replacement for the AMP Version magic string. This also fixes the last remaining issue with sourcemaps, caused by the old string replace not keeping the same number of chars in the replacement.
```js
// input
import {version} from './internal-version';
console.log(version());
// output
console.log("1904010000000");
```
> 🐛 Replace internal version with compile time constant

- extensions/amp-auto-ads/0.1/anchor-ad-strategy.js
Under amp-auto-ads extension, the service to fetch amp-sticky ad ext does not have the correct version passed (its default is 0.1), resulting in a 404. Passing 1.0 resolves it.
> small fix for amp auto anchor ads

- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
- extensions/amp-autocomplete/amp-autocomplete.md
This PR fixes a submit-on-enter bug wherein `submit-on-enter="false"` fails to prevent form submission when `Enter` is pressed while suggestions are displaying. The updated behavior is as follows: `submit-on-enter="true"` does not disrupt any consequences of pressing `Enter` in the containing input field of an `amp-autocomplete`. `submit-on-enter="false"` will prevent default behavior only if suggestions are displayed. This is because the default consequences of pressing `Enter` should only be disrupted when there is a new interaction pattern for it, such as selecting an item from a list of suggestions, which is not possible when no suggestions are displayed.
- Fixes the aforementioned bug
- Updates tests and documentation to reflect changes
- Fixes related logic with setting and …
> 🐛amp-autocomplete: Fix submit-on-enter bug

- extensions/amp-video-docking/amp-video-docking.md
Simply corrects the amp-video-iframe link at `amp-video-docking.md`.
> 📖 amp-video-docking: Correct the URL of amp-video-iframe

- build-system/tasks/compile.js
- gulpfile.js
The default `gulp dist` doesn't include source code content in sourcemaps. This is useful while debugging, and can be enabled by passing [`--source_map_include_content=true`](https://github.com/google/closure-compiler/wiki/Flags-and-Options#reports) to closure compiler.
This PR adds a flag for `gulp dist` called `--full_sourcemaps`, which internally sets the closure compiler flag.
Addresses https://github.com/ampproject/amphtml/pull/21832#pullrequestreview-228148815
> 🏗✨ Add `--full_sourcemaps`, a `gulp dist` flag to include source code in sourcemaps

- README.md
Updates links to point to amp.dev instead of ampproject.org.
/cc @ampproject/wg-outreach
> Changes README references from ampproject.org to amp.dev

- .travis.yml
@cathyxz's comment in the chat made me realize that it isn't entirely clear to everyone that these two stages are non-blocking, so adding this to their name.
Before this PR:
After this PR:
> 🏗 Add the text `[non-blocking]` to the Remote and e2e Travis stages

- extensions/amp-mraid/0.1/amp-mraid.js
Currently, if we serve amp-mraid to a non-inabox environment it will bail out immediately.  Unfortunately, amp-analytics etc will be stuck waiting for amp-mraid to finish loading.  We should treat this like any other environment mismatch, and fall back if configured to.
> 🐛amp-mraid: handle non-inabox better

- examples/mraid/inabox-mraid.html
- extensions/amp-mraid/0.1/amp-mraid.js
Initially the design for amp-mraid was that there were multiple situations in which it would need to decide whether to fall back to standard web apis, and we wanted to allow the author to choose how amp-mraid should handle that situation.  It's now clear that this was too complicated, and the only decision amp-mraid needs the author to make is how it should handle the case where it doesn't look like its running in a mobile app.
Additionally, when a creative author decides to include mraid support in a creative they're generally going to want the fallback behavior.  They don't know what environment they will be serving into, and want reasonable behavior everywhere.  Make fallback the default.  Ad networks that know at serving time that they're serving to mobile apps can use no-fallback to …
> ✨ mraid: change default for fallback, and simplify configuration

- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list-load-more.js
- extensions/amp-list/0.1/test/test-amp-list.js
Follow up to https://github.com/ampproject/amphtml/issues/14060. Basically adding origin trials resulted in a bunch of ugly promises to wait for the extension script to install. Now that `load-more` is launched, this PR removes said promises and makes the code path here easier to read.
> Remove references to amp-list-load-more experiment now that the feature has launched

- contributing/contributing-code.md
This updates the docs on contributing to:
- Replace the generic "reviewer" term for the person who helps a person navigate the process with "guide" now that we have an official Reviewer role.
- Simplifies the section for small changes by incorporating specifics on finding the Reviewer/Owner into it (rather than pointing to a different section of the doc).
/cc @ampproject/wg-outreach
> Updates contributing docs to simplify small change section and change "reviewer" to "guide"

- extensions/amp-story/1.0/amp-story-desktop-panels.css
- extensions/amp-story/1.0/amp-story-media-query-service.js
- extensions/amp-story/1.0/amp-story.css
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/test/test-amp-story-media-query-service.js
- src/services.js
Publishers can provide `<media-query>` elements that accept two options: `media` and `className`.
The media query will match against the `amp-story-page` element, and not the viewport, solving media queries for stories.
When the `media` is matched, the `className` will be added as a class on the `amp-story` element, allowing publishers to write custom CSS.
Example:
```
<style amp-custom>
.foo p {
/* Only triggered when the specified media query matches. */
}
.bar p {
/* Only triggered when the specified media query matches. */
}
</style>
<amp-story class="foo? bar?">
<media-query media="(orientation: portrait)" class-name="foo"></media-query>
<media-query media="(max-width: 600px)" class-name="bar"></media-query>
<amp-story-page>
...
</amp-story-page>
</amp-story>
```
> Stories media queries service.

- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Expand the `token-prefix` filter to match on a wider range of user input types on amp-autocomplete.
- Tokenizes inputs on special character separators in addition to `' '` (space) and ignores `'.'` (dot)
- Adds unit tests for helper functions `tokenPrefixMatch_`, `tokenizeString_`, and `mapFromTokensArray_`
- Makes the following trade off: Calls `tokenizeString_` on the same input one time for every item it is matched against (rather than once total) to prioritize readability in the implementation of `filterData_`. A refactor would be good to minimize this computational cost in the future, but I'd recommend waiting until other filters (fuzzy and custom) are implemented to get a feel for the most useful and readable way to refactor.
> 🐛 Expand token-prefix meaning on amp-autocomplete

- extensions/amp-iframe/0.1/test/test-amp-iframe.js
Fixes https://github.com/ampproject/amphtml/issues/21960 
We were sending resize message too early causing a race (e.g. if parent was not yet listening for it). Moving it to an async callback will eliminate the sync race.
> ✅ amp-iframe: fix test flake

- spec/amp-html-format.md
Sample Document of AMP HTML Format has a warning of a script using amphtml-validator.
It uses amp-ad in AMP-HTML, but it does not load amp-ad script.
before
```
➜  amp-test amphtml-validator index.html
index.html: PASS
index.html:108:6 The tag 'amp-ad extension .js script' is missing or incorrect, but required by 'amp-ad'. This will soon be an error. (see https://www.ampproject.org/docs/reference/components/amp-ad)
```
after
```
➜  amp-test amphtml-validator index.html
index.html: PASS
```
> 📖 Update Sample document of AMP HTML Format needs amp-ad script

- extensions/amp-script/0.1/test/integration/test-amp-script.js
These tests have been failing consistently on Sauce labs. It looks like they never did work on Safari.
The last four runs from today all show the exact same failures, all on Safari:
https://travis-ci.org/ampproject/amphtml/jobs/524563240#L2047
https://travis-ci.org/ampproject/amphtml/jobs/524545924#L2047
https://travis-ci.org/ampproject/amphtml/jobs/524545470#L2047
https://travis-ci.org/ampproject/amphtml/jobs/524525824#L2047
This is part of an effort to make Sauce labs runs green, and eventually block PRs when they fail.
> ✅ Make Sauce labs integration tests green

- extensions/amp-base-carousel/0.1/amp-base-carousel.css
- extensions/amp-base-carousel/0.1/amp-base-carousel.js
- extensions/amp-base-carousel/0.1/auto-advance.js
- extensions/amp-base-carousel/0.1/carousel-accessibility.js
- extensions/amp-base-carousel/0.1/carousel.js
- src/dom.js
- test/unit/test-dom.js
- Add z-index so buttons are clickable by VoiceOver when 'hidden'
- Use `disabled` attribute for next/prev button when at the start/end for accessibility
- Pause auto advance when `pauseCallback` is called
- Pause auto advance when the carousel gains focus
- Add/remove aria-hidden on slides as the index changes
- Treat carousels with multiple items visible at once as a list
> ♿amp-base-carousel a11y fixes

- build-system/tasks/e2e/describes-e2e.js
- extensions/amp-base-carousel/0.1/test-e2e/test-arrows-non-looping.js
- extensions/amp-base-carousel/0.1/test-e2e/test-arrows.js
- extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
- extensions/amp-base-carousel/0.1/test-e2e/test-grouping.js
- extensions/amp-base-carousel/0.1/test-e2e/test-initial-slide.js
- extensions/amp-base-carousel/0.1/test-e2e/test-mixed-lengths-no-snap.js
- extensions/amp-base-carousel/0.1/test-e2e/test-mixed-lengths.js
- extensions/amp-base-carousel/0.1/test-e2e/test-non-looping.js
- extensions/amp-base-carousel/0.1/test-e2e/test-responsive.js
- extensions/amp-base-carousel/0.1/test-e2e/test-vertical.js
Skips flaky amp-base-carousel e2e tests and un-nests `test-grouping.js` to prevent cascading test failures.
Also creates an `ItConfig` to allow you to skip a single test like 
``` 
it().configure().skipShadowDemo().run('should...', ...)
```
cc\ @sparhami @cvializ
> ✅ Skip flaky amp-base-carousel e2e tests

- .travis.yml
The `Remote (Sauce Labs) tests` job on Travis has been non-blocking due to rampant disconnection errors and test failures.
- In #21822, we increased the disconnection timeout to give all browsers enough time to complete testing. With this, we're no longer seeing disconnect errors. 
- Context: `karma-sauce-launcher` lacks a heartbeat to keep test sessions alive (https://github.com/karma-runner/karma-sauce-launcher/pull/161)
- In #21983, we skipped the remaining integration tests that never did work on Safari.
With this, it's time to surface genuine test failures by making the job blocking. Here are the last few runs (all green):
- https://travis-ci.org/ampproject/amphtml/jobs/524602477#L1581-L1584
- https://travis-ci.org/ampproject/amphtml/jobs/524616811#L1931-L1934
- …
> 🏗 Make remote (sauce labs) tests blocking on Travis now that they're green

- examples/visual-tests/amp-story/amp-story-page-attachment-desktop.js
- examples/visual-tests/amp-story/amp-story-page-attachment.js
- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/amp-story.css
- extensions/amp-story/1.0/test/test-amp-story-page.js
Ability for publishers to control the default "Swipe up" text that appears on story pages when an `amp-story-page-attachment` is provided.
Publishers can specify a new `data-cta-label` attribute on the `amp-story-page-attachment` element.
```
<amp-story-page-attachment layout="nodisplay" data-cta-label="More cute cats">
/* AMPHTML content */
</amp-story-page-attachment>
```
https://github.com/ampproject/amphtml/issues/21920
> Custom CTA label for story page attachments.

- src/service/fixed-layer.js
- src/service/hidden-observer-impl.js
Hidden observer fails to init in PWAs because `document` is assumed
instead of allowing for the possibility of `document` or `shadowRoot`. Add
fallbacks for `shadowRoot`.
Fixes #21975
Fixes #21113.
> 🐛 fixed-layer: Fix hidden observer init in PWA

- build-system/tasks/visual-diff/index.js
Will restore it once I figure out a more permanent fix. Technically this just reduces the number of parallel running pages from 10 to 1 😅
I re-ran the visual diff test stage 7 times and it passed every time. This increases the running time from ~1.5 to ~5 minutes, so still within reason
> 🏗 Remove parallelization from visual diff to avoid flakiness

- extensions/amp-story/1.0/amp-story-share.js
The "Get link" sharing button in the bookend is currently broken in all stories ([example](https://www.washingtonpost.com/graphics/2019/world/amp-stories/sri-lanka-mourning/)).
`this.root.querySelector('#page-share')` is only available if the `amp-story-branching` experiment is enabled.
> Fix the copy to clipboard sharing option on Stories.

- extensions/amp-web-push/0.1/test/validator-amp-web-push.html
- extensions/amp-web-push/0.1/test/validator-amp-web-push.out
- extensions/amp-web-push/validator-amp-web-push.protoascii
Adding validation for `service-worker-scope` attribute in `amp-web-push` component (complementing change made in #21702).
The rule created in validator-amp-web-push.protoascii defines the attribute as:
- Optional: By not adding a "mandatory" attribute in the declaration.
- Of type URL, HTTPS and relative: This comes from [SW Spec](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register#Parameters): 
"**scope**: A USVString representing a URL that defines a service worker's registration scope; that is, what range of URLs a service worker can control. This is usually a relative URL. It is relative to the base URL of the application."
Tests have been added to show the different use cases: 
- Using the component without service-worker-scope.
- Using the component with …
> ✅ Allowing service-worker-scope attribute in amp-web-push for AMP validator

- CONTRIBUTING.md
CONTRIBUTING.md is our top-level file for how people can get involved in AMP (contributing code/features but also filing issues, proposing FRs, etc.).  This adds a pointer to the working groups, and updates the "Status Update" link to the current WG Status Update issues.
> Adds a reference to Working Groups in CONTRIBUTING.md

- test/unit/test-3p-environment.js
`gulp test --unit --nobuild --headless --files=test/unit/test-3p-environment.js` fails when it runs in isolation or with `--local-changes`, but passes when it runs without flags.
It is blocking some PRs like #21972
lolex's target is the window of an iframe that gets destroyed in the global afterEach cleanup. Somehow, calling `uninstall` removes the timer methods entirely instead of restoring the original ones, and the tests fail because `setTimeout` doesn't exist.
Even though I don't fully understand the bug, not calling `uninstall` should be fine since `testWin` is re-created for each test.
> Fix 3p environment tests.

- build-system/global-configs/canary-config.json
This moves `a4aProfilingRate` to 1% in canary (to match its 1% in RC), and moves `ampdoc-closest` to 1% in canary (to match its 1% in RC).
> Match RC and Canary experiment percentages

- build-system/pr-check/utils.js
Without setting the storage project id, it's possible to attempt to upload the build artifact to another project, which results in failed PRs. Example - https://travis-ci.org/ampproject/amphtml/jobs/520320458#L928
This hard sets the storage project id.
> 🏗 Ensure build artifact gets uploaded to the right location

- examples/visual-tests/amp-autocomplete/amp-autocomplete-data.json
- examples/visual-tests/amp-autocomplete/amp-autocomplete.amp.html
- examples/visual-tests/amp-autocomplete/amp-autocomplete.js
- test/visual-diff/visual-tests
Add visual test for amp-autocomplete rendering and displaying items on focus for plain-text inline data.
> ✅ Add visual test for amp-autocomplete

- test/integration/test-amp-inabox.js
As noted in #21311 these tests are unreliable. This is most likely due to the various workarounds so the inabox creatives can work properly in an iframed host page smaller than the viewport size. The best solution going forward is probably to port them to being e2e tests.
Also coalesced the various comments across the file into one at the top.
> Skip the inabox BTF tests.

- .gitignore
- build-system/compile/compile.js
- build-system/compile/single-pass.js
- package.json
- yarn.lock
Running `gulp dist --single_pass` generates a `.js` and a `.map` file each for ~150 extensions. The build steps in `singlePassCompile` as written today do 2 extra file reads and file writes for each of the 300 `.js` / `.map` files.
This PR consolidates all the compilation steps into a series of `gulp` stream operations with one final file write at the end, and eliminates ~1200 unnecessary file reads / writes. 
Follow up to #21953
> 🏗♻️ Consolidate single pass compilation steps, eliminate ~1200 file reads / writes

- src/service/layers-impl.js
Part of the layers algorithm is to traverse out of FIE frames to the
parent AMP doc. To do this, when we hit the document node, we test to
see if we can access the document's window's `frameElement`. However,
if the parent window is cross-origin, this will cause an error.
We actually guard against this error, so there is no real issue. But these
accesses are still logged in dev tools, which gets really annoying. This
is a nice-to-have change so that we only attempt getting the
`frameElement` once, and cache the result.
> Layers: guard against repeated cross-origin accesses

- extensions/amp-date-picker/amp-date-picker.md
I was checking the date picker documentation recently for how it describes the `select` event, and I noticed it did not describe the `select` event. This PR implements the missing documentation.
> 📖Add missing documentation for date picker change event

- build-system/pr-check/e2e-tests.js
Uses the same logic that creates a build artifact in the build job when running the e2e test job.
Fixes #21880
> 🏗 Run E2E test job in PRs only when you have a build artifact

- src/web-worker/web-worker.js
If a bind evaluator already exists for a given scope, allow it to be
re-constructed.
Fixes #17532
> 🐛 web-worker: Do not fail on bind re-init

- examples/autocomplete.amp.html
- extensions/amp-autocomplete/0.1/amp-autocomplete.css
- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
- Re-renders results on down arrow key if none are showing.
- Re-renders results to an active item on blur so that if the element gain focus again, it will display updated suggestions.
- Points the results upwards or downwards based on input position in the viewport.
- Makes sure the active item is always visible in the results and is scrolled to within its container element if necessary.
> 🐛 Fix amp-autocomplete bugs related to results display and interaction

- build-system/compile/compile.js
- build-system/compile/shorten-license.js
- build-system/compile/single-pass.js
This PR addresses https://github.com/ampproject/amphtml/issues/22076#issuecomment-488104236 and https://github.com/ampproject/amphtml/pull/21818#pullrequestreview-225709634 without breaking #11589 or #21818. It eliminates the hack mentioned in https://github.com/ampproject/amphtml/pull/21818#issue-269468229. I verified this with @jridgewell's [sourcemaps tool](https://justin.ridgewell.name/source-map-visualization/#custom-choose).
With this, we see licences like this in `v0.js`...
```js
/*
Copyright (C) 2014-2016 by Andrea Giammarchi - @WebReflection
Use of this source code is governed by a MIT-style
license that can be found in the LICENSE file or at
https://opensource.org/licenses/MIT.
*/
/*
Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
Use of this source code is …
```
> 🏗🚮 Remove blank lines from copyright licenses in `v0.js` without breaking sourcemaps

- extensions/amp-audio/0.1/amp-audio.js
- extensions/amp-audio/0.1/test/test-amp-audio.js
- extensions/amp-video/0.1/amp-video.js
- src/event-helper.js
This PR ensures that `amp-video` and `amp-audio` `layoutCallback`s complete and don't remain pending.
- Changing `loadstart` to `loadedmetadata` to resolve the `loadPromise`
`amp-video` and `amp-audio` rely on `loadPromise` to complete their `layoutCallback`. This PR improves the `isLoaded` helper so it correctly detects that the HTMLMediaElement already triggered the event `loadPromise` would be waiting for.
Without this, `amp-video` and `amp-audio` `layoutCallback` could potentially never resolve in specific contexts, like when handled by the amp-story media pool.
The code used to listen to the `loadstart` event, but there is no way to synchronously check if this event already fired. We switch to listening to the `loadedmetadata` event that can be checked synchronously with `readyState …
> Better support for HTMLMediaElement in the loadPromise helper.

- extensions/amp-base-carousel/0.1/test-e2e/test-arrows-non-looping.js
- extensions/amp-base-carousel/0.1/test-e2e/test-non-looping.js
- test/manual/amp-base-carousel/non-looping.amp.html
This test checks the opacity values of the next and previous carousel arrows when you are at the beginning of the carousel, in the middle, and at the end. Currently the test fails because it looks for `prevArrowSlot` and `nextArrowSlot` opacity values which doesn't always exist. 
This PR changes the test to look at the button elements instead. It also clicks instead of scrolls to get to the end of the carousel because `controller.scrollBy()` doesn't seem to work locally.
(incremental fix for #21986)
> ✅ Fix carousel arrows non looping e2e test

- build-system/pr-check/local-tests.js
- build-system/tasks/e2e/selenium-webdriver-controller.js
- extensions/amp-base-carousel/0.1/test-e2e/test-arrows-non-looping.js
- extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
- extensions/amp-base-carousel/0.1/test-e2e/test-grouping.js
- Implements `element.scrollTo()` for selenium webdriver controller.
- Replaces `driver.scrollBy` with `driver.scrollTo` in some but not all E2E tests. (Note that they have different starting positions when setting top or left offsets, so `driver.scrollBy(el, width*(slidecount-1))` becomes `driver.scrollTo(el, width*(slidecount-2))`
- Unskips a carousel grouping test, checks off some TODOs
(follow up to #22081)
(incremental fix for #21986)
> 🏗 Use scrollTo instead of scrollBy in some E2E tests

- build-system/compile/single-pass.js
- build-system/runner/src/org/ampproject/AmpCommandLineRunner.java
to try and remove as much custom settings in the java code, set `rename_prefix_namespace` through the config flag instead.
> use the `rename_prefix_namespace` flag instead of setting it in java

- examples/autocomplete.amp.html
- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
- extensions/amp-autocomplete/amp-autocomplete.md
- src/utils/key-codes.js
- Update the `select` event on `amp-autocomplete` to contain the selected value in the `event.value` property.
- Fire the `select` event on `Tab` with the active highlighted item if there is one
- Add an example that listens to the `select` event
- Add the `Tab` key in common `key-codes.js`
> Update the select event on amp-autocomplete

- build-system/tasks/validator.js
#22125 upgraded `gulp` to v4 and updated all tasks to the new API. It resulted an error in the validator checks because the functions are not `async`, so the `gulp` task wouldn't exit cleanly.
See https://travis-ci.org/ampproject/amphtml/jobs/527924651#L315
This PR makes both functions in `build-system/tasks/validator.js` async.
> 🏗🐛 Make `validator` functions `async` so that their `gulp` tasks complete

- build-system/tasks/runtime-test/helpers.js
- build-system/tasks/runtime-test/index.js
- https://github.com/karma-runner/karma-sauce-launcher/issues/117 sometimes causes the `Cannot find module '../build/safe-execute'` error during Karma test runs
- The bug was fixed via the workaround in #13328
- `karma-sauce-launcher` was upgraded to a version that didn't depend on `wd`
- The workaround was reverted in #19889
- `karma-sauce-launcher` was rolled back to the old version in #21578 because it caused disconnection errors on Sauce labs 
This PR reinstates the workaround from #13328 until such time that we need it.
> 🏗🐛 Fix flaky Karma startup by refreshing the `wd` cache (again)

- build-system/tasks/css.js
- build-system/tasks/dist.js
- build-system/tasks/extension-helpers.js
- build-system/tasks/firebase.js
- build-system/tasks/helpers.js
- build-system/tasks/prepend-global/index.js
- build-system/tasks/runtime-test/index.js
- Consolidates all the `Recompiled CSS in ...` messages during `gulp {css|build|dist}` into one message (there were too many that appeared all at once)
- Removes the `Transformed` messages during `gulp build` (they merely indicated the start of a `babelify` call, and were redundant)
- Fixes some duplicate / incorrect writes of `AMP_CONFIG` to various runtime targets (see https://github.com/ampproject/amphtml/commit/2f87ad2b63b8891ad904c8dcd14371ff7ffb8717#r33407812 and https://github.com/ampproject/amphtml/commit/5fd7c8a3632391356ad1c1b2afbd2b652fc28d5c#r33407960)
- Makes `gulp` tasks that depend on `gulp {css|build|dist}` wait for them to finish before starting (before this, tasks like `gulp test` wouldn't fully wait for the pre-requisite task to complete) …
> 🏗🚮🐛 Assorted `gulp` compilation fixes

- build-system/tasks/visual-diff/helpers.js
- build-system/tasks/visual-diff/index.js
- build-system/tasks/visual-diff/snippets/snapshot-error.html
Progress on #21056
Stability changes:
* Parallelize visibility helper methods using Promises
* Replace page navigation retry mechanism with a more robust check for event-based responses
* Increase page navigation timeout from 7 to 30 seconds (last increase was in #seconds
* Preallocate tabs instead of opening and closing one tab per test
* Increase number of parallel tabs from 1 to 5 (was 10 before #21991)
Developer experience changes:
* Print HTML of document to the snapshot error page
* e.g., https://percy.io/ampproject/amphtml/builds/1801799/view/117271471/375?mode=diff&browser=firefox&snapshot=117271471
* Record and print `console.METHOD(...)` calls inside the page when test fails
* e.g., https://travis-ci.org/ampproject/amphtml/jobs/526199016#L1563-L1584
Minor changes:
* Do not bring …
> 🏗 Stability and developer-experience changes for visual diffs testing platform

- extensions/amp-story/1.0/amp-story-page-attachment-header.css
- extensions/amp-story/1.0/amp-story-page-attachment.js
Ability for publishers to provide an optional title to the page attachment.
Publishers can specify a new `data-title` attribute on the `amp-story-page-attachment` element.
```
<amp-story-page-attachment layout="nodisplay" data-title="More cute cats">
/* AMPHTML content */
</amp-story-page-attachment>
```
https://github.com/ampproject/amphtml/issues/21921
> Optional story page attachment title.

- examples/autocomplete.amp.html
- extensions/amp-autocomplete/0.1/amp-autocomplete.css
- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
- extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
- extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
The ability to `disable` an item on `amp-autocomplete` means to be able to suggest it among the list of results but not allow a user to keyboard navigate to it or select it from the list. This is to suggest that the item is not currently available for whatever reason. 
This change recognizes the `data-disabled` attribute on amp-autocomplete. This is only supported through Json datatypes and templating.
- Implement this in a way that accounts for item selection and `activeItem` highlighting through keyboard navigation.
- Add an example of using this feature
- Add validator and unit tests for this feature
- Modify relevant CSS selectors
> ✨ Support ability to 'disable' an item on amp-autocomplete.

- extensions/amp-script/0.1/amp-script.js
- extensions/amp-script/0.1/test/unit/test-amp-script.js
- src/purifier.js
- test/unit/test-purifier.js
Fixes two small bugs in #21782:
1. `getAllowedTags()` doesn't contain AMP tags, so we need to manually add support
2. Allow tag-agnostic whitelisted attributes (`WHITELISTED_ATTRS`)
Also added a couple TODOs since there's more I'd like to do to make these code paths cleaner and more readable.
/to @jridgewell /cc @kristoferbaxter
> amp-script: Allow attribute mutations on built-ins

- .travis.yml
Reverts ampproject/amphtml#21992
Reason for revert: `🏗 Stability and developer-experience changes for visual diffs testing platform` #21980
Addresses #21056
> Revert "✅ Make visual tests non-blocking"

- build-system/tasks/extension-generator/index.js
Changes the generated spec_url to be amp.dev instead of ampproject.org
> update extension generator to amp.dev

- build-system/global-configs/prod-config.json
relates to #22059
Follow up to #22084 . This allows doc level opt in to the new experiment for removing `height: auto !important` for amp4ads.
cc @jeffkaufman @keithwrightbos We'd want to roll out this experiment at 0% and slowly roll out to 100%. 😄 Ensuring their is no drop in revenue, or anything like that.
> 🐛 amp inabox: Added the inabox `height: auto !important` experiment to the prod config

- extensions/amp-story/amp-story.md
The term "experimental" might refer to an AMP experiment that must be toggled on via https://cdn.ampproject.org/experiments.html ([example](https://twitter.com/benmorss/status/1120474249981059073)). As of 1.0, this is not needed for `<amp-story>`.
/cc @newmuis @morsssss
> Docs: remove "experimental" (overloaded term)

- examples/masking-trim.amp.html
- extensions/amp-inputmask/0.1/inputmask-custom-alias.js
- extensions/amp-inputmask/0.1/mask-impl.js
- extensions/amp-inputmask/0.1/test/test-inputmask-custom-alias.js
- extensions/amp-inputmask/0.1/test/test-mask-impl.js
- extensions/amp-inputmask/0.1/test/validator-amp-inputmask.html
- extensions/amp-inputmask/0.1/test/validator-amp-inputmask.out
- extensions/amp-inputmask/amp-inputmask.md
- extensions/amp-inputmask/validator-amp-inputmask.protoascii
Fixes #21706 (the original document will need to add `mask-trim-zeros="0"`)
✅Adds unit tests, since the integration tests ended up being flaky 
📖Renamed `README.md` to fit the convention for the other components
A small refactor to improve unit-testability.
> ✨Add support for mask-trim-zeros attribute on amp-inputmask.

- css/amp.css
- examples/autocomplete.amp.html
- examples/visual-tests/amp-autocomplete/amp-autocomplete.amp.html
- examples/visual-tests/amp-autocomplete/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- Set `dir="auto"` attributes on amp-autocomplete input and generated item elements.
- Add example usage
- Add visual test for rtl dataset
> 🌐 Support RTL inputs and datasets on amp-autocomplete

- build-system/tasks/helpers.js
- build-system/typescript.js
The file `build-system/tasks/helpers.js` contains lots of helper code used in `gulp {build|dist}`.
This PR splits `compileJs` (~200 lines) into `compileUnminifiedJs`, `compileMinifiedJs`, `compileTs`, `handleBundleError`, `finishBundle`, and `maybeEnableLocalTesting`.
Partially addresses https://github.com/ampproject/amphtml/pull/22109#discussion_r280509902
Follow up to #22109
Follow up to #13792
> 🏗♻️Refactor `compileJs` into smaller functions

- build-system/tasks/karma.conf.js
During CI builds, we run [~15000](https://travis-ci.org/ampproject/amphtml/builds/530045204) tests on Travis.
- [~9500](https://travis-ci.org/ampproject/amphtml/jobs/530045211#L1566) unit tests (local)
- [~3700](https://travis-ci.org/ampproject/amphtml/jobs/530045212#L1929) unit tests (sauce labs)
- [~350](https://travis-ci.org/ampproject/amphtml/jobs/530045211#L1540) integration tests (local)
- [~270](https://travis-ci.org/ampproject/amphtml/jobs/530045209#L1947) integration tests (local, single pass)
- [~600](https://travis-ci.org/ampproject/amphtml/jobs/530045212#L1968) integration tests (sauce labs)
- [~350](https://travis-ci.org/ampproject/amphtml/jobs/530045212#L1988) integration tests (sauce labs, beta browsers)
Often times, a single-digit number of tests will fail due to timing …
> 🏗 Retry tests before failing them on Travis

- css/Z_INDEX.md
- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.css
- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
- extensions/amp-lightbox-gallery/0.1/lightbox-caption.css
- extensions/amp-lightbox-gallery/0.1/lightbox-caption.js
- test/manual/amp-lightbox-gallery-launch-captions.amp.html
- Refactor lightbox captions into a separate file.
- Fix downwards movement at the start of the captions expanding by
having consistent padding both before and after the expansion.
- Allow opening lightbox with the captions already expanded via an
action.
- Apply captions fading mask when switching slides, which is less
jarring when the new slide's captions are overflowing.
- Keep the close and gallery view buttons visible when the caption is
expanded. This is important when opening when captions already expanded.
* Added a fade out effect to the top of the text, so it does not clash
with the buttons.
- Change the caption fade out mask to use `mask-image` instead of a
gradient. This works well when the captions are overlaying the image
(e.g. if you enter pan-zoom mode or the image is in …
> ✨🖍🐛 Lightbox captions changes.

- build-system/compile/closure-compile.js
- build-system/runner/src/org/ampproject/AmpCodingConvention.java
- build-system/runner/src/org/ampproject/AmpCommandLineRunner.java
- build-system/runner/src/org/ampproject/AmpPass.java
Today, `gulp dist --single_pass` makes one large closure invocation (among others) to compile `v0.js` + `extensions/`. This internally uses `runner.jar`, which happens to disable all custom passes for the singe pass invocation.
This PR switches the single pass invocation to use `compiler.jar`, and removes all single pass specific code from `runner.jar`.
Addresses https://github.com/ampproject/amphtml/pull/21953#issuecomment-487422465
Requires #22064
Requires #22216 
Potentially unblocks #22040
> 🏗🚮 Use `compiler.jar` instead of `runner.jar` for single pass, remove unnecessary code

- extensions/amp-viewer-integration/integrating-viewer-with-amp-doc-guide.md
- validator/chromeextension/popup-validator.html
- validator/engine/validator.js
- validator/webui/README.md
- validator/webui/index.html
- validator/webui/serve-standalone.go
- validator/webui/serve.go
Update validation links for the Validator Web UI from validator.ampproject.org to validator.amp.dev now that validator.amp.dev is live.
> validator.amp.dev is live, update links

- build-system/runner/src/org/ampproject/AmpPass.java
- build-system/runner/test/org/ampproject/AmpPassTest.java
In #22216, `version()` from `src/internal_version.js` was renamed to `internalRuntimeVersion()`. This PR makes up for that change in AmpPass.java.
Addresses https://github.com/ampproject/amphtml/pull/22216#issuecomment-491106311 and fixes [this](https://travis-ci.org/ampproject/amphtml/jobs/530499265#L1945-L1958) test failure
Follow up to #22216
> 🏗🐛 Rename `version` to `internalRuntimeVersion` in AmpPass.java

- build-system/tasks/e2e/describes-e2e.js
- Fix all existing `beforeEach` errors by increasing its timeout to 30s. Keep test timeout at 20s.
- Remove multiple fixture support when there's just one.
- Await `setup()` and `teardown()`, which are async.
- Clean up TODOs.
> 🏗 Clean up describes-e2e

- build-system/config.js
- build-system/tasks/runtime-test/index.js
- test/integration/test-configuration.js
1. Clean up integration test run on IE
- Skip `integration/test-configuration.js` on IE because it fails
- Remove `unit/test-error.js` from integration test run
Now there are zero tests that have opted into IE.
2. Make IE tests blocking
- Move browser from beta/non-blocking batch to stable/blocking, for a total of 5 stable browsers
- Because batch size is set to 4, move IE to the end of the list so it runs in its own batch (just for in case)
cc/ @lannka @torch2424
> 🏗 Re add IE11 to our CI in blocking mode

- extensions/amp-autocomplete/0.1/test-e2e/test-amp-autocomplete.js
Update expected e2e test outcome based on a feature change to "re-renders results to an active item on blur so that if the element gain focus again, it will display updated suggestions" in #22054
> 🐛✅Update failing autocomplete e2e test

- extensions/amp-live-list/0.1/amp-live-list.js
- extensions/amp-live-list/0.1/live-list-manager.js
- extensions/amp-live-list/0.1/test/test-amp-live-list.js
- extensions/amp-live-list/0.1/test/test-live-list-manager.js
Resolves #21718
Problem: If we dynamically append an amp-live-list in the client at runtime, there will not be a corresponding amp-live-list in the server document. Even though the custom container that we specified in the amp-live-list is indeed in both documents.
Proposed solution: Create a relationship between the dynamically added amp-live-list, and the custom slot (could be the element that built the live-list).
Then the manager will be able to query for that element on the server document., and it would compare these two elements by following the same logic amp-live-list currently uses.
Changelog:
* Introduce new attributes to configure amp-live-list:
` disable-scrolling`, `disable-pagination`.
* Introduce new `AMP_LIVE_LIST_CUSTOM_SLOT_ID` property, which if present, specifies a …
> ✨ Support dynamically added lists and add configuration options

- build-system/compile/compile.js
- build-system/tasks/build.js
- build-system/tasks/check-types.js
- build-system/tasks/dist.js
- build-system/tasks/helpers.js
Today, there is one giant function called `compile()` in `build-system/tasks/helpers.js` that compiles the various AMP build targets in minified and unminified modes. 
- Removes the obsolete `checkTypes` option (added in #3539, made obsolete by #4931)
- Removes the obsolete `preventRemoveAndMakeDir` option (added in #2880, but never used as `false`)
- Reorganizes `compile()` into `compileAllMinifiedTargets()` and `compileAllUnminifiedTargets()`
- Applies a strict order to the compilation of `v0.js` and `v0-esm.js`, thereby fixing the race in #18934
Follow up to #3539 and #4931
Follow up to #2880
Fixes #18934
> 🏗♻️🚮🐛 Refactor `compile()` in `build-system/tasks/helpers.js`

- build-system/tasks/dist.js
- build-system/tasks/helpers.js
- build-system/tasks/prepend-global/index.js
- Writes `AMP_CONFIG` to each AMP target immediately after compilation
- Separates the minified, unminified, and single pass code paths for config writes
- Fixes incorrect / missing items in the list of targets 
Addresses https://github.com/ampproject/amphtml/pull/22147#pullrequestreview-234090110
Follow up to #22147
> 🏗♻️ Refactor post-compilation config writes

- src/get-bounding-client-rect.js
Re: https://github.com/ampproject/amphtml/pull/21855
> 🐛 Store the native getBoundingClientRect before patching

- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js
The presence of `position: absolute` on the slot element interferes with our ability to correctly measure the size of fluid creatives. Ad slots with fluid creatives resize themselves by taking up the maximum width available and setting their height to match the height of the creative's body element. This height is different if `position: absolute` is present (due to the element being removed from the normal document flow). So in the current way we measure and resize:
1) Add `i-amphtml-layout-awaiting-size` to slot element, which adds `position: absolute`
2) Measure height H from creative's body element
3) Set slot height to H
4) Remove `i-amphtml-layout-awaiting-size` from slot element, which removes `position: absolute`
H may be too large for the available width, since the element is …
> Remove position: absolute when measuring fluid creative height.

- css/amp.css
relates to #22084
closes #22034
Per request from @jasti and @lannka Adding this to our current height experiment for inabox.
cc @jeffkaufman @keithwrightbos We'd want to roll out this experiment at 0% and roll out to 100%. 😄
> 🐛 amp inabox: Removed margin: auto !important for the amp4ads use case

- extensions/amp-form/0.1/amp-form.js
Update the action invocation on submit error event data not to be the error object as in the context of AMP.setState action, the postMessage will not be successful as error objects are non cloneable.
b131633888
> amp form submit-error action fix

- .github/ISSUE_TEMPLATE/cherry_pick_template.md
- .github/ISSUE_TEMPLATE/intent-to-deprecate--i2d-.md
- .github/ISSUE_TEMPLATE/intent-to-remove--i2r-.md
Adds new Intent-to-Deprecate and Intent-to-Remove issue templates as part of the updated removal process being updated in #22114.
These templates are inspired by the [Chromium feature removal process/templates](https://www.chromium.org/blink/removing-features).
/cc @ampproject/tsc @honeybadgerdontcare @twifkak @ithinkihaveacat
> Add Intent-to-Deprecate and Intent-to-Remove templates

- spec/amp-email-format.md
The links in the AMP4Email spec are outdated due to changes in the URL scheme of amp.dev.
/cc @fstanis, @pbakaus
> 📖 Fix broken links in AMP4Email spec.

- extensions/amp-auto-ads/0.1/ad-tracker.js
- extensions/amp-auto-ads/0.1/anchor-ad-strategy.js
`getElementsByTagName` (and several other methods) do not exist on `ShadowRoot`s, even though the externs claim they do. Will fix that separately.
See https://github.com/ampproject/amphtml/issues/17614#issuecomment-492346630
For #17614
> 🐛Fix usage of `getElementsByTagName` on ShadowRoot.

- extensions/amp-form/0.1/amp-form.js
- extensions/amp-form/0.1/test/test-amp-form.js
- Reduces number of type casts (a source of bugs e.g. #22221)
- Fixes code dupe across `handlePresubmitFailure_`, `handleXhrSubmitFailure_` and `handleSsrTemplateFailure_`
- Other minor clean up
/to @cvializ
> amp-form: Reduce typecasts, clean up

- src/preconnect.js
- test/unit/test-preconnect.js
Changed the endpoint to use `robots.txt` (and a more descriptive query string), as the current implementation causes some undesirable side-effects (404s in server logs, performance issues, user confusion, etc). 
Fixes #21088.
> 🏗 Altered Safari Preconnect Polyfill Endpoint

- build-system/pr-check/local-tests.js
With #15461 and #15585, we started running `gulp test --unit --local-changes` on Travis before running all unit tests. This helps us fail early when a PR breaks unit tests. However, in the case of large refactors, it results in wasted time by rerunning a large number of tests twice.
In this PR, we skip directly to running all unit tests when a PR is flagged as a large refactor (# files changed >= 50).
This addresses the "future work" suggestion at https://github.com/ampproject/amphtml/pull/15585#pullrequestreview-123414218 (it only took a year!)
Follow up to #15461
Follow up to #15585
> 🏗 Don't run unit tests on local changes for large refactors

- extensions/amp-connatix-player/amp-connatix-player.md
There was a leftover comment (auto generated) that wasn't removed which causes the page to render the licence agreement.
Also fixed the category attribute
> 📖 Connatix Player extension: fix broken documentation page

- examples/a4a-consent.amp.html
- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-a4a/0.1/real-time-config-manager.js
- extensions/amp-a4a/0.1/test/test-amp-a4a.js
closes #22197
This creates a `CONSENT_STRING` macro to be sent through a4a RTC 😄 
`a4a-consent.amp.html`
> ✨amp-consent: Allowed passing the consent string through a macro

- build-system/pr-check/local-tests.js
- build-system/tasks/runtime-test/helpers.js
- build-system/tasks/runtime-test/index.js
In #22320, we skipped running unit tests on local changes for large refactors. However, this leaves the Github status in an incomplete state.
This PR moves the logic to `build-system/tasks/runtime-test/helpers.js`, so we can mark the status as skipped if needed.
Follow up to #22320
> 🏗🐛 Mark `--local-changes` test status as skipped for large refactors

- extensions/amp-next-page/0.1/next-page-service.js
Fixes #20638.
- Move fetch rejection handler up to the fetch promise, and use `user().error` instead of `dev().error`.
- Remove extraneous `Promise` between `createHTMLDocument` and attachment.
Tip: View diff with whitespace ignored (`?w=1`).
/to @peterjosling @sparhami
> amp-next-page: Fetch failure should be a user error

- extensions/amp-story/1.0/amp-story-desktop-panels.css
- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/amp-story.css
- extensions/amp-story/1.0/page-advancement.js
- extensions/amp-story/1.0/test/test-amp-story-page.js
- extensions/amp-story/1.0/utils.js
As we introduce new `orientation` attributes, and element based CSS Media Queries, we want publishers to be able to specify different assets (images, videos) depending on the viewport size or orientation.
This PR ensures that videos are played/paused accordingly as they get hidden/displayed.
The feature is actually pretty complex but fits in not so many lines of code. I tried to keep the code behavior as similar as possible, and only add some code that reacts to visibility changes.
Feel free to ask all the questions you have, and suggest more code comments to explain how things work!
Changelog:
- `.i-amphtml-story-grid-template-fill` can now potentially have multiple children, as publishers should be able to provide different version of the same asset
- …
> Handling video visibility updates.

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
This is a follow up PR to #22306. 
I can't have them removed in same PR because there's a presubmit check for that. 
However it is fine this time because we've removed the check for 'amp-consent' experiment in production code long time ago.
> Remove 'amp-consent' experiment flag pr2

- extensions/amp-lightbox/amp-lightbox.md
`<amp-lightbox>` is already supported in the validator and spec:
https://github.com/ampproject/amphtml/blob/1e66423afab615a0df5d36ad43757bd29379a554/extensions/amp-lightbox/validator-amp-lightbox.protoascii#L30-L32
This is to fix the amp.dev page which currently 404s: https://amp.dev/documentation/components/amp-lightbox?format=email
> 📖 Add email to amp-lightbox supported formats

- spec/amp-versioning-policy.md
This updates the deprecation and removal process.  Includes new Intent-to-Deprecate and Intent-to-Remove inspired by the [Chromium feature removal process/templates](https://www.chromium.org/blink/removing-features).
This change also:
- adds the additional requirement to announce deprecations and breaking changes on Slack
- adds privacy fixes as a reason we may launch breaking changes
Partial fix for https://github.com/ampproject/meta/issues/18.
/cc @ampproject/tsc @ampproject/wg-runtime @ampproject/wg-infra @ampproject/wg-caching
> Update feature deprecation/removal process

- extensions/amp-story/amp-story.md
Documentation for story page attachments CTA label and title.
To be merged once both https://github.com/ampproject/amphtml/pull/21985 and https://github.com/ampproject/amphtml/pull/21988 are deployed to production.
Closes https://github.com/ampproject/amphtml/issues/21921, #21920
> Documentation for story page attachments CTA label and title.

- extensions/amp-story/1.0/amp-story.css
Twitter embed applies a `width: 100%` on responsive layouts for the iframe, but the tweet itself only has a `max-width` of `500px`. This yields to some blank space being clickable which might be confusing to users.
Before:
After:
> 🐛 Add max width to amp-twitter

- css/amp.css
- src/service/resource.js
- src/service/resources-impl.js
- test/unit/test-resources.js
- tools/experiments/experiments.js
Alternative implementation to https://github.com/ampproject/amphtml/pull/21555, suggested by @dvoytenko 
AMP prerendering builds 20 elements, so that the content above the fold is already loaded and rendered when a user opens an AMP document.
This PR forces the build for elements beyond this limit of 20, if they are in the defined viewport area that is used to layout the elements during prerendering.
Fixes #21432
> Force build additional components during prerendering if needed.

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/live-story-manager.js
- extensions/amp-story/1.0/test/test-live-story-manager.js
Master issue #21714
Closes #21719
Introduces LiveStoryManager, which will be in charge of all live story-specific logic.
In particular, it:
* Builds an `amp-live-list` component with the story-specific configuration and appends it to the DOM.
* Listens to `AmpLiveList#Update` action and appends a new page to the DOM (if any).
More follow up PRs will be sent:
* handle the progress bar with the new updates
* show a button that when clicked will take a user to the new page
* tests for LiveStoryManager
> ✨ Introduce LiveStoryManager

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/page-advancement.js
Adds some safeguards for the use of embedded components:
* If user clicks towards the vertical edges of the screen, no tooltip will be shown.
> 🐛 Add safe zone in screen edges to prevent blocking navigation

- contributing/getting-started-quick.md
Partial fix for https://github.com/ampproject/meta/issues/18.
- Removes references to "core committers"
- Points to documentation on finding reviewers for a PR.
> Removes references to core committers and help find reviewers

- build-system/tasks/pr-check.js
When a local PR check (`gulp pr-check`) fails, it prints a cryptic failure message at the end.
Changes in this PR:
- Return a proper exit status and print a message when a check fails
- Run yarn and build target checks first
- Print total running time
Split off from #22348
Addresses https://github.com/ampproject/amphtml/pull/22348#issuecomment-493554080
> 🏗🐛 Fixes for `gulp pr-check`

- src/dom.js
- test/unit/test-dom.js
- test/unit/test-element-service.js
> Ensure that the waitForBody yields at the earliest possible time when body is opened

- extensions/amp-access/amp-access.md
- extensions/amp-subscriptions/amp-subscriptions.md
Fixes the typos pointed out in PR #19148.
/cc @dcmoore-gd @ampproject/wg-access-subscriptions
> Fixes typo in amp-access and amp-subscriptions docs

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
Launch the `amp-force-prerender-visible-elements` experiment for canary and 1% of prod traffic.
#21791
> Launch the force prerender experiment for canary and 1% of prod traffic.

- build-system/pr-check/checks.js
- build-system/tasks/ava.js
- build-system/tasks/babel-plugin-tests.js
- build-system/tasks/pr-check.js
- gulpfile.js
- package.json
- yarn.lock
- Creates a new `gulp babel-plugin-tests` task for the `jest`-based tests for AMP's custom babel plugins
- Moves test config for these tests from `package.json` to the task 
- Moves test config for `ava`-based tests into the already present `gulp ava` task
- Removes the `files` config setting for `ava()` since `gulp.src` already picks the correct set of files
- Removes outdated / defunct `npm` test scripts from `package.json`
Split off from #22348
Addresses https://github.com/ampproject/amphtml/pull/22348#issuecomment-493554080
> 🏗♻️ Move test configuration out of `package json`

- extensions/amp-analytics/0.1/iframe-transport-vendors.js
- extensions/amp-analytics/0.1/vendors.js
Adding a separate JSON Object (IFRAME_TRANSPORTS_CANARY) in iframe-transport-vendors.js to represent sources to be loaded into iframe when using iframe transport in Canary. 
Adding conditional logic in vendors.js to use IFRAME_TRANSPORTS_CANARY when in Canary and IFRAME_TRANSPORTS, otherwise.
This will help vendors test changes in Canary without altering the source in live traffic.
> Add separate iframe transport URLs for Canary

- build-system/pr-check/build-targets.js
- build-system/pr-check/build.js
- build-system/pr-check/checks.js
- build-system/pr-check/dist-bundle-size.js
- build-system/pr-check/e2e-tests.js
- build-system/pr-check/local-tests.js
- build-system/pr-check/remote-tests.js
- build-system/pr-check/single-pass-tests.js
- build-system/pr-check/validator-tests.js
- build-system/pr-check/visual-diff-tests.js
- build-system/tasks/pr-check.js
- build-system/tasks/runtime-test/status-report.js
- Simplifies the process by which build targets are determined
- Rolls `BUILD_SYSTEM` into `RUNTIME` (the runtime must be built and tested for all build system changes)
- Re-evaluates the checks / tests that must be run for each target (the [original logic](https://github.com/ampproject/amphtml/pull/5157/files) is outdated)
- Determines build targets only during PR builds (push builds do everything, irrespective of targets)
- Verifies build targets for all jobs in the `build` stage (to detect races where they're [valid](https://travis-ci.org/ampproject/amphtml/jobs/533964805#L314) for some jobs in a PR and [invalid](https://travis-ci.org/ampproject/amphtml/jobs/533964804#L307) for others) (reported by @gmajoulet)
Follow up to #22319
Follow up to #20921 …
> 🏗 Update the build target logic used during PR checks

- extensions/amp-lightbox-gallery/amp-lightbox-gallery.md
Due to https://github.com/ampproject/docs/issues/2089, the redirect was broken, Changing link to point directly to the main site.
> 📖amp-lightbox-gallery: update the broken example link

- build-system/git.js
- build-system/pr-check/utils.js
There's a bug in the logic used to determine the PR branch creation point on Travis. It works for branches with a single merge point with `master`, but it breaks down when a branch has been merged multiple times.
This PR fixes the logic by listing all the common ancestors of the PR branch and `master` using [`git rev-list --boundary`](https://git-scm.com/docs/git-rev-list#Documentation/git-rev-list.txt---boundary), and picking the most recent one.
For example, the PR branch in [this](https://travis-ci.org/ampproject/amphtml/jobs/533426874#L426) Travis job was forked at `57dcee4eb` after which two merge commits were done. The current logic is returning an incorrect branch point way back in the past. The new logic returns the correct branch point.
Follow up to #19954
> 🏗🐛 Fix logic used to determine the branch creation point on Travis

- extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
- extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js
- src/common-signals.js
- src/friendly-iframe-embed.js
I found the common signals to be a bit confusing. Added some comments to the file and also reorder the signals based on trigger time. 
Ads support a renderStart API which listens to 'render-start' msg from iframe. This could help AMP runtime to display an ad at a more accurate time. The `RENDER_START` signal is different. It is a signal that's used to tell AMP runtime and other components the ad is now visible. 
In the PR, I separate the concept between 'render-start' msg and RENDER_START signal. Should make the code easier to understand. And the PR fixes the issue where RENDER_START signal is not triggered at iframe on load event.
> Differentiate 'render-start' msg and RENDER_START signal

- extensions/amp-script/0.1/amp-script.js
Removes `AMP-Access-Control-Allow-Source-Origin` header requirement for author code loaded within `amp-script`.
Addresses: #22170
> 🐛 `amp-script` Remove AMP cors requirement for author code

- extensions/amp-story/amp-story.md
In https://www.ampproject.org/docs/reference/components/amp-story#publisher-logo-src-guidelines it says "The logo should be at least 96x96 pixels." but the doc mentions a logo which is 36x36.
> Updates size of publisher logo according to guidance

- extensions/amp-analytics/0.1/amp-analytics.js
- extensions/amp-analytics/0.1/variables.js
Introduced _another_ bug in #22300. When loading new amp docs into shadow shell shell service registration is asynchronous, but I was trying to retrieve the service synchronously. This changes amp-analytics to wait for a promise of this service.
All other analytics files can continue to use the sync method as their creating analytics element will have waited for promise to resolve.
> 🐛Fix variable service race.

- build-system/pr-check/build.js
- build-system/pr-check/dist-bundle-size.js
- build-system/pr-check/visual-diff-tests.js
- build-system/tasks/visual-diff/index.js
This PR makes the visual tests use minified builds when run locally and on Travis.
TODO: Resolve conflicts with #22397 before merging this.
Fixes #22391
> 🏗 Use minified build for visual diff tests

- extensions/amp-analytics/0.1/cookie-writer.js
- extensions/amp-analytics/0.1/test/test-cookie-writer.js
Closes #22328 
We discussed more on this topic. Given that we only write cookie on pub origin, it makes sense for publisher to write any cookie value. 
Few concerns: 
1. No whitelist or blacklist is applied. Basically one can choose to write any user information they can get to the cookie. 
2. The feature can be misused. One can write unnecessary information or static string to the cookie. 
Note these can be achieved on non AMP pages already. 
to @jeffjose want to get your idea on this as well.
> allow cookie writer macros

- extensions/amp-analytics/0.1/vendors/gtag.js
Gtag needs to know if navigation happened from amp CDN. Existing signal for this is presence of document referrer and absence of external referrer.
> ✨ Add referrer presence signals to the config rewriter varGroups.

- spec/amp-cache-guidelines.md
Update the section "Adding a new cache to the AMP ecosystem" to mention `caches.json`.
This removes the suggestion to "publicly announce" the cache (somewhat unnecessary; `caches.json` can be used for this) and also the small list of "example caches" (likewise).
> "AMP Cache Guidelines" update

- .travis.yml
Text coloring is broken on Travis push builds because of how secret environment variables are processed. 
This PR implements the workaround in https://github.com/travis-ci/travis-ci/issues/7967#issuecomment-424521694 to restore text coloring.
Fixes #10117
> 🏗 Restore text coloring in Travis logs

- extensions/amp-story/1.0/amp-story.js
The new story render service waits for the signal `CommonSignals.LOAD_END` from the `<amp-story>` component. This signal will trigger when `amp-story.layoutCallback()` resolves. Until then, the story will be hidden.
However, `amp-story.layoutCallback()` will wait for all the pages to build, which might not happen in prerendering because of the 20 elements limit.
This PR introduces a change that, during prerendering, resolves `amp-story.layoutCallback()` once the first `amp-story-page` builds so the story render service can display it.
> Fix story render service during prerendering.

- validator/validator-main.protoascii
Certain experiments are will be enabled by default (eg, the new blurry image placeholders). This provides a way for publishers to opt-out of the experiment.
We considered whether to reuse the `amp-experiments-opt-in` meta tag, but we found opting-out using an opt-in was confusing. This provides a more natural way.
> ✨ Add new <meta name="amp-experiments-opt-out">

- ads/beaverads.js
- contributing/component-validator-rules.md
closes #22373 
I noticed we need to run `gulp validator --update_tests` to update our `.out` files for tests when building #22176 . Thus, I mentioned it in the docs 😄
> ♻️Added comment on generating `.out` files for validator

- extensions/amp-experiment/1.0/test/test-variant.js
- extensions/amp-experiment/1.0/variant.js
relates to #21705
This allows variants to have zero mutations. We are allowing this, as often times people like to use a "control variant". This should differ from the base page, because often times users are charged by the analytics pings, thus this allows users to not get ALL the information of the base page, and just a fraction of it.
> ✨amp-experiment 1.0: Removed the "No mutations" limitation

- .gitignore
- ads/beaverads.js
- build-system/amp-cors.js
- build-system/app.js
- build-system/routes/user-location.js
- bundles.config.js
- examples/amp-user-location.amp.html
- extensions/amp-analytics/0.1/vendors.js
- extensions/amp-user-location/0.1/amp-user-location.js
- extensions/amp-user-location/0.1/position-error.js
- extensions/amp-user-location/0.1/test/test-amp-user-location.js
- extensions/amp-user-location/0.1/test/test-user-location-service.js
- extensions/amp-user-location/0.1/test/validator-amp-user-location.html
- extensions/amp-user-location/0.1/test/validator-amp-user-location.out
- extensions/amp-user-location/0.1/user-location-service.js
- extensions/amp-user-location/0.1/user-location.js
- extensions/amp-user-location/amp-user-location.md
- extensions/amp-user-location/validator-amp-user-location.protoascii
- spec/amp-var-substitutions.md
- src/mode.js
- src/service/url-replacements-impl.js
- src/services.js
- test/unit/test-url-replacements.js
- tools/experiments/experiments.js
Implements #8929.
Geolocation access is mediated by the `UserLocationService` which handles the interactions with the Geolocation API and maintains the state to be requested and accessed by both the `amp-user-location` AMP component and the `url-replacements` service.
Tests (>90% coverage) and documentation are part of this PR. Initially this feature is behind an experiment while we evaluate and test the component.
/to @alanorozco @sparhami 
/cc @jeffjose
> Implementation for amp-user-location component

- extensions/amp-carousel/0.1/base-carousel.js
- extensions/amp-carousel/0.1/scrollable-carousel.js
- extensions/amp-carousel/0.1/test/test-scrollable-carousel.js
- extensions/amp-carousel/0.1/test/test-slidescroll.js
Fixes https://github.com/ampproject/amphtml/issues/21071
In scrollable carousel, the next/previous buttons add no functionality for screen readers as scrollable carousel is just a horizontally scrollable div which ATs navigate just like any other content.
To avoid confusion, we therefore set the role to presentation for the controls in this case.
> 🐛 amp-carousel: hide next/prev in type=carousel for screen readers

- build-system/tasks/runtime-test/index.js
Karma tests on occasionally return a failure with zero tests. Currently, it's not clear why this happened. (Disconnection? Error?)
This PR logs the `browser.lastResult` JSON object returned by Karma to aid in debugging.
Related to #16851
Follow up to #16878
> 🏗 Log Karma results when zero tests are detected

- .eslintrc
- build-system/amp.extern.js
- build-system/compile/compile.js
- build-system/config.js
- build-system/runner/src/org/ampproject/AmpCodingConvention.java
- build-system/runner/src/org/ampproject/AmpCommandLineRunner.java
- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
- extensions/amp-subscriptions/0.1/local-subscription-platform-base.js
- src/element-service.js
- src/layout.js
- src/log.js
- src/polyfills/promise.js
- src/service/action-impl.js
- src/service/hidden-observer-impl.js
- src/service/navigation.js
- src/service/standard-actions-impl.js
- src/service/timer-impl.js
- src/service/url-impl.js
- src/url.js
- test/integration/test-amp-ad-fake.js
- third_party/closure-compiler/POM-file-changes.patch
- third_party/closure-compiler/README.amp
This PR upgrades the version of closure compiler used to minify the AMP runtime to [`v20190513`](https://github.com/google/closure-compiler/wiki/Releases#may-13-2019-v20190513).
- Updated `compiler.jar` with a custom built version based on `v20190513`
- Reverts two breaking changes in closure compiler code ([one](https://github.com/google/closure-compiler/commit/0393c80ca01b6b861376dad7f91043a38bb37dc0), [two](https://github.com/google/closure-compiler/commit/acea045bcc566c8d1ba74bc8f63fbb1568a18c2b)) (required until https://github.com/google/closure-compiler/issues/3041 is fixed)
- Updated `compiler-and-tests.jar` with a custom built version based on `v20190513`
- Follows the steps outlined [here](https://github.com/ampproject/amphtml/pull/18552#issue-220501644)
- Updated …
> 🏗✨ Upgrade closure compiler to v20190513

- .github/ISSUE_TEMPLATE/cherry_pick_template.md
- contributing/release-schedule.md
Updates who can approve cherry picks based on TSC guidance in #22089.
Fixes #22089 (and partial fix for https://github.com/ampproject/meta/issues/18).
/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers
> Update docs/template for new cherry pick approvers

- build-system/server-a4a-template.html
Also change amp-ad layout to fixed size to match the description.
> Remove the confusing "force3p" string in a4a envelope.

- src/service.js
- src/service/timer-impl.js
Are they intentionally imported?
timer-impl.js is only compiled in main binary, so removing the import should be a no-op.
polyfill in service.js gets browserified in every extension, while closure compiler is smart enough to strip them off from each extension.
> Remove duplicated polyfill import.

- build-system/tasks/css.js
- src/service/video/install-autoplay-styles.js
They're duplicates of /build/css/*, which caused naming conflict for js imports.
> Clean up: remove copies of CSS files under /build/. 

- extensions/amp-access-scroll/0.1/scroll-impl.js
Updates the URL for the Scroll activation button iframe - this better aligns with our URL architecture moving forward.
> ♻️Use connect URL for activate iframe in amp-access-scroll

- build-system/check-package-manager.js
- build-system/exec.js
This PR detects if there's a possibly incorrect version of `gulp` somewhere in the user's `$PATH`, and prints a warning before carrying on.
The `gulp` checks in `check-package-manager.js`:
- ...  are only triggered during `yarn` (which is run much less frequently), and don't slow down actual invocations of `gulp`
- ... do not prevent the `yarn` command from running even if they find problems
> 🏗 Add a check for the default `gulp` executable path

- build-system/check-package-manager.js
This is part of the effort to make sure an incorrect version of `gulp` isn't being used by default.
Follow up to #22459
> 🏗 Allow `gulp` to run from `amphtml/node_modules`

- build-system/tasks/presubmit-checks.js
- src/service/template-impl.js
- src/services.js
Partial for #22414. Next is to start migrating extension code to use the async API.
/to @calebcordry /cc @jridgewell
> Ban getServiceForDoc() in extensions/* paths.

- examples/autocomplete.amp.html
- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
- extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
- extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
This change is because input tags without `type` [default to `type=text`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Form_%3Cinput%3E_types).
- Still enforces `type="text|search"` if `type` is present on the `input` tag.
- Confirms that this is not a breaking change to any functionality (by removing `type` attributes from some `input` tags in the example and validator html files
- Updates validator and tests
> Allow input tags in amp-autocomplete to have no "type" attribute.

- .eslintrc
This PR unblocks #22489, which upgrades `eslint-plugin-jsdoc` to v7.
A similar change will have to be made in `ampproject/amp-github-apps` before https://github.com/ampproject/amp-github-apps/pull/133 can be merged.
For context, see https://github.com/ampproject/amphtml/pull/22421#issuecomment-494963105
> 🏗 Enable `noDefaults: true` for `jsdoc/check-types`

- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
- test/manual/amp-lightbox-gallery.amp.html
The heavy lifting is already done in the animations library, the only thing left wiring it up on the AMP side. This will allow animations like on this demo page: https://sparhami.github.io/animations/docs/demo/zoom-crop/, where the container (in this case, `<amp-img>` can be used to crop the image to an interesting part.
> ✨Support lightbox gallery crop animation.

- extensions/amp-story/1.0/amp-story.css
- test/visual-diff/visual-tests
Updating the story sidebar animations.
Sepand fixed the `amp-sidebar` animations (:1st_place_medal:) in this awesome PR https://github.com/ampproject/amphtml/pull/22324
This PR reflects the changes in `amp-story`.
Note: using the `[side]` attribute on `amp-sidebar` is disallowed by the validator within `amp-story`.
> Updating the story amp-sidebar animations.

- extensions/amp-list/0.1/amp-list.js
Mustache templates rendering as empty strings is a totally valid case. 
However, an empty string is falsy, and would fail the current assertion. 
/review @alabiaga 
/cc @GoTcWang
> 🐛 FIX: Allow empty string as rendered template

- extensions/amp-story/1.0/amp-story-page-attachment-header.css
- extensions/amp-story/1.0/amp-story-page-attachment.css
- extensions/amp-story/1.0/amp-story-page-attachment.js
Creates a dark mode for the `amp-story-page-attachment` component.
```
<amp-story-page-attachment layout="nodisplay" data-dark-mode>
...
</amp-story-page-attachment>
```
Masterbug #20209
Feature #22204
> Story page attachment dark mode.

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/test/test-amp-story-page.js
- extensions/amp-story/1.0/test/test-amp-story.js
Related to #21714
Moves `waitForMediaLayout` to `AmpStoryPage#layoutCallback` and replaces `AmpStoryPage#whenLoaded` with `CommonSignals.LOAD_END`.
`markPageAsLoaded_` is running in AmpStoryPage's constructor and it's causing errors when trying to append a new page with the LiveListManager. This is because `markPageAsLoaded` uses `resources`, but `resources` is not present for elements that haven't been attached to the DOM yet.
In the case of LiveListManager, the page is first initialized by calling `importNode`, and then it's appended to the DOM at a later time.
We can use this opportunity to get rid of the custom `whenLoaded` event in AmpStoryPage, and to use the standard `whenSignals(CommonSignals.LOAD_END)`.
> 🐛 Page layout improvements

- extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
- extensions/amp-subscriptions/0.1/amp-subscriptions.js
- extensions/amp-subscriptions/0.1/local-subscription-platform-base.js
- extensions/amp-subscriptions/0.1/platform-store.js
- extensions/amp-subscriptions/0.1/subscription-platform.js
- extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
- extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
- extensions/amp-subscriptions/0.1/test/test-platform-store.js
- extensions/amp-subscriptions/0.1/viewer-subscription-platform.js
This PR allows the `amp-subscriptions` pingback to return all entitlements (as opposed to just the one that granted access).
Changes:
1. Expose the `getAllPlatformsEntitlements` method in `platform-store.js`
2. Add a `pingbackReturnsAllEntitlements` method to `SubscriptionPlatform`
3. Modify `amp-subscriptions` to return all entitlements if `pingbackAllEntitlements` is true in the local platform config
4. Tests for the above
5. Add stub `pingbackReturnsAllEntitlements` to `amp-subscriptions-google`
> ✨ Support multi entitlement pingback in amp-subscriptions

- examples/autocomplete.amp.html
- extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
- Replace invalid form attributes with an endpoint that both works and validates
- Allow relative URLs in the `src` attribute on `amp-autocomplete`
> ✅ Make sure amp-autocomplete example validates

- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors/permutive.js
This PR makes two minor improvements to Permutive's amp-analytics configuration:
- Bug fix: use `timer` trigger for tracking page engagement
- Adds additional request type for _custom_ events
> 🐛Improvements to Permutive amp-analytics config

- css/ampdoc.css
- src/service/fixed-layer.js
- tools/experiments/experiments.js
amp-sidebar is invisible when opened. Affects iOS in "email" and "actions" specs.
The is due to the non-traditional CSS boilerplate which causes the fixed layer to be hidden: 
```html
<style amp4email-boilerplate>body{visibility:hidden}</style>
```
Tthe regression happened in https://github.com/ampproject/amphtml/pull/20954/files#diff-a244d3899d7cb3930087a9d566a46af9R963, which stopped overriding the "visibility" style on the fixed layer. 
Use higher-specificity CSS to override the boilerplate rule and make sure the transfer layer is visible when intended:
```css
#i-amphtml-wrapper + body {
visibility: visible;
}
```
This PR also cleans up the `fixed-elements-in-lightbox` experiment code guards.
`b/133327438`
> Fix invisible amp-sidebar in AMP4EMAIL

- src/form.js
- test/unit/test-form.js
The `isDisabled` helper will be used to determine if an element should
skip the dirtiness check.
This is a part of #22534.
/cc @cvializ @GoTcWang
> ♻️✅ Export `isDisabled` helper

- build-system/pr-check/local-tests.js
Since code coverage is measured only for the runtime, it makes sense to upload coverage reports only for runtime changes.
This prevents cases where partial coverage reports are are uploaded. For example, if a PR runs only integration tests, but not unit tests.
Follow up to #22515
> 🏗  Upload codecov reports only for runtime changes

- extensions/amp-sidebar/0.1/amp-sidebar.css
- Remove `!important` from translate rules, since they are not
overridden by animation properties in Firefox.
Fixes #22553
> Fix sidebar opening for Firefox.

- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
Fixes #22552 by partially reverting #22227.
Allows `amp-list` that's mutated by `[src]` with local data but have zero size (width or height == 0) to render.
> Revert deferral of [src] local data render until layout

- extensions/amp-story/1.0/amp-story-store-service.js
- extensions/amp-story/1.0/amp-story-system-layer.css
- extensions/amp-story/1.0/amp-story-system-layer.js
- extensions/amp-story/1.0/live-story-manager.js
Closes #21721
Master issue: #21714
When button is clicked, user is taken to the latest page in the story.
> ✨Adds button when new update is available

- extensions/amp-story/0.1/amp-story-render-service.js
- extensions/amp-story/0.1/amp-story.js
Copy/pasting PRs #21382 + #22344 + #22346 from v1.0 to v0.1
> Story render service for amp-story 0.1.

- .eslintrc
- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
- src/service/action-impl.js
- src/service/hidden-observer-impl.js
- src/service/navigation.js
- src/service/standard-actions-impl.js
- src/service/timer-impl.js
- src/service/url-impl.js
- test/integration/test-amp-ad-fake.js
See #22572. Seems like it's now failing due to a regression (function being stripped from compiled code).
> Fix friendly embedding on amp-ad, and reenable test-amp-ad-fake.js

- test/fixtures/images-ie.html
- test/fixtures/images.html
- test/integration/test-amp-img.js
- testing/describes.js
- Fixes bug where Mocha was skipping an `amp-img` integration test that opted into IE 11 due to an overridden test config
- Fixes test itself that timed out by adding a poll and using an html test fixture that uses minified build
> ✅ Fix amp-img integration test on IE 11

- extensions/amp-story/1.0/amp-story-access.css
- extensions/amp-story/1.0/amp-story.css
- extensions/amp-story/1.0/amp-story.js
We internally use `--i-amphtml-story-vw`, `--i-amphtml-story-vh`, `--i-amphtml-story-vmin`, and `--i-amphtml-story-vmax` to represent the size of the story page, rather than the viewport.  Publishers have requested this as well, so this PR renames it to be public (and perhaps make more sense externally).
> 🖍 Make story page viewport units public, for usage in publisher styles

- extensions/amp-story/amp-story.md
Documentation for story page attachments dark mode.
To be merged once #22505 hits production.
Masterbug #20209
Fixes #22204
> Documentation for story page attachments dark mode.

- 3p/nameframe.max.html
- 3p/remote.html
- validator/chromeextension/content_script.js
- validator/engine/validator-in-browser.js
In #22488, we fixed all the  security, correctness, and maintainability issues in our code detected via static analysis from LGTM.com.
This PR suppresses the remaining [issues](https://lgtm.com/projects/g/ampproject/amphtml/alerts/?mode=tree) that are expected and can't be fixed.
**Files:**
- [3p/nameframe.max.html](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/7eaee60d39c77ab949affe0cca4ab838af597148/files/3p/nameframe.max.html?sort=name&dir=ASC&mode=heatmap#x78f351d75e4e421a:1)
- [3p/remote.html](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/7eaee60d39c77ab949affe0cca4ab838af597148/files/3p/remote.html?sort=name&dir=ASC&mode=heatmap#xc096312c4d8092a5:1)
- [validator/chromeextension/content_script.js](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/7eaee60d39c7 …
> 🐛 Suppress expected LGTM alerts that can't be fixed

- 3p/environment.js
- build-system/compile/compile.js
In #5114, type checking was disabled for `3p/environment.js` due to warnings that couldn't be suppressed. See https://github.com/ampproject/amphtml/pull/5114#discussion_r79574510 and https://github.com/ampproject/amphtml/pull/5114#discussion_r79609847.
https://github.com/ampproject/amphtml/blob/855c753e38f026bc03430628b805944979e5e18c/build-system/tasks/compile.js#L334-L335
This PR enables type checking for the file, and suppresses / fixes the three warnings / errors that were returned by `gulp check-types`.
```
3p/environment.js:197: WARNING - Suspicious code. This code lacks side-effects. Is there a bug?
return (0, win.eval /*NOT OK but whatcha gonna do.*/).call(win, fn); // lgtm [js/useless-expression]
^
3p/environment.js:272: WARNING - @suppress annotation not allowed here. See …
```
> 🐛 Enable type checking for `3p/environment.js`

- extensions/amp-animation/0.1/parsers/css-expr-impl.js
-Changed the spelling of the word "behaviour" to the English spelling "behavior"
-Closes issue #18080
> 🐛 Fixed spelling inconsistency in extensions/amp-animation/0.1/css-expr-impl.js

- build-system/tasks/extension-helpers.js
The extension `amp-sticky-ad-0.1` is in a special category of aliased bundles, where the old source code has been deleted, and we just copy the code from the current `1.0` version into the `0.1` alias. While doing so, we were neglecting to copy the sourcemap file.
This PR fixes the bug by copying the sourcemap file in addition to the JS and CSS files.
Fixes #17518
> 🐛 Copy sourcemap file for aliased bundles

- .codecov.yml
We recently started showing project level and patch level code coverage for `amphtml` PRs as separate statuses for unit and integration tests .
This PR consolidates the project and patch level coverage numbers into one status each (thereby giving PR authors a choice in whether to test their code with unit tests or integration tests)
**Future work:**
- Set minimum code coverage thresholds. For example:
- No PR may reduce the project level coverage by more than 10% (in practice, this is hard to do, since you'd either have to add ~5000 lines of code with zero test coverage, or delete a whole lot of tests)
- Every PR must make sure that at least 50% of the lines of code added / changed by the PR are covered by at least one unit or integration test (the goal is to cause project level code …
> 🏗 Consolidate AMP's code coverage PR statuses

- .codecov.yml
We recently enabled PR statuses from `codecov` in order to improve AMP's code coverage. It appears the settings in `.codecov.yaml` are not taking effect.
**PR comments:**
- Comments are supposed to be disabled. Yet they're being posted. For example: https://github.com/ampproject/amphtml/pull/22494#issuecomment-497895188
https://github.com/ampproject/amphtml/blob/9c4ec350f095981c343c2f2197490e1dd260fd20/.codecov.yml#L3-L4
**PR statuses:**
- The failure threshold is supposed to be 100% (so all PRs pass). Yet, PRs are failing when coverage reduces by even a fraction of a percent. For example: https://github.com/ampproject/amphtml/pull/22494#event-2382422032
https://github.com/ampproject/amphtml/blob/9c4ec350f095981c343c2f2197490e1dd260fd20/.codecov.yml#L6-L16
This PR rewrites the …
> 🐛 Fix `.codecov.yaml`

- build-system/tasks/helpers.js
- package.json
- yarn.lock
- Cleans up the code used to compile unminified JS
- Simplifies the handling of `--watch` (Future cleanup: Simplify the two-step build added in #923)
- Fixes build timing by starting measurement when bundling actually begins (https://github.com/ampproject/amphtml/pull/10290#pullrequestreview-48511479)
- Stops using `lazypipe` (added in #702, but slows down the build now that we have ~150 targets)
- Stops modifying `_init_tests.js` during `watch` to trigger tests (added in #1667, no longer necessary)
- Speeds up unminified builds by ~15%
Running time for `gulp build` on Travis: [5m 35s](https://travis-ci.org/ampproject/amphtml/jobs/540428748#L319) → [4m 42s](https://travis-ci.org/ampproject/amphtml/jobs/540467882#L350)
Follow up to #702, #923, #1667, #10290, and …
> 🏗♻️ Refactor and speed up unminified builds

- extensions/amp-call-tracking/0.1/amp-call-tracking.js
- extensions/amp-call-tracking/0.1/test/test-amp-call-tracking.js
closes #20551
This makes the phone number optional, and simply warns if there is no response from the call-tacking API. Allowing the phone number link still work 😄
> 🐛amp-call-tracking: Made the 'phoneNumber' field optional

- extensions/amp-story/1.0/amp-story-page-attachment-header.css
- extensions/amp-story/1.0/amp-story-page-attachment.css
- extensions/amp-story/1.0/amp-story-page-attachment.js
- extensions/amp-story/amp-story.md
Addressing https://github.com/ampproject/amphtml/pull/22506#issuecomment-497786504
- Removing the documentation until this rolls out to production
- New opt in for the dark theme:
```
<amp-story-page-attachment theme="dark">
```
cc @abouraya FYI
> Replacing story attachment data-dark-mode with theme.

- extensions/amp-story/1.0/test/validator-amp-story-page-attachment-error.html
- extensions/amp-story/1.0/test/validator-amp-story-page-attachment-error.out
- extensions/amp-story/1.0/test/validator-amp-story-page-attachment.html
- extensions/amp-story/1.0/test/validator-amp-story-page-attachment.out
- extensions/amp-story/validator-amp-story.protoascii
Allowing a `theme` attribute on `amp-story-page-attachment`.
To be merged after #22642
> Attachment theme validation.

- build-system/tasks/build.js
- build-system/tasks/css.js
- build-system/tasks/dist.js
- build-system/tasks/extension-helpers.js
- build-system/tasks/helpers.js
- gulpfile.js
- Moves `buildExperiments()` from `build-system/tasks/helpers.js` to `build-system/tasks/dist.js` (should've been done in #22109)
- Removes unused `watch` logic from `buildExperiments` and cleans up unused `gulp` task (copy-pasted in #923)
- Removes unused `watch` logic from `buildLoginDoneVersion` and cleans up unused `gulp` task  (copy-pasted in #1330)
- Simplifies the `watch` logic for extensions by using a separate watcher to rebuild an extension when any file in its directory is modified (see #47, #12900, #12911, and #22635)
- Removes the obsolete `bundleOnlyIfListedInFiles` option used to selectively build extensions (added in #3091) now that we have `--extensions` and `--extensions_from` (added in #13203, #13249, and #17129)
Follow up to #47, #923, …
> 🏗♻️ Refactor / clean up the `watch` logic used for extensions

- extensions/amp-form/0.1/amp-form.js
- extensions/amp-form/0.1/form-dirtiness.js
- extensions/amp-form/0.1/test/test-form-dirtiness.js
This currently supports detecting the dirtiness of text-typed `<input>`
and `<textarea>`. This does not take the submitted value into account
yet.
This is part of #22534.
> ✨ FEATURE: AMP form dirtiness indicator class

- extensions/amp-analytics/0.1/test/test-variables.js
- src/service/url-expander/expander.js
The expander works by walking the input string. When it sees a macro it pushes the promise of a value (async) or the immediate resulting value (sync) into an array, that will be joined at the end of string or the next `)`. 
For example in a async call:
`'abcMACROdef' => ['abc', Promise, 'def'] `
This can become a problem in nested context because this array is what is passed to the function that resolves the function through `function.apply`. 
`'OUTER(INNER)' => OUTER.apply([INNER]) // good`
`'OUTER(foo, INNER)' => OUTER.apply(['foo', INNER]) // good`  
`'OUTER(fooINNER, bar)' => OUTER.apply(['foo', INNER, 'bar']) // bad - three args passed to OUTER instead of two`
This fix changes this to use an array of arrays, where we can keep track of each argument in its own array, and therefore …
> 🐛Fix broken args in expander.

- src/cookies.js
- test/unit/test-cookies.js
- testing/fake-dom.js
Introduce the `getHighestAvailableDomain` function so it can be reused by linker manager.
New behavior:
1. Expect option.domain to be explicitly specified if we want to write to proxyOrigin
2. option.domain value overrides the `highestAvailableDomain=true`. 
Rewrite test-cookies.js. 
Hope to keep the PR size small. I'll submit the linker manager change in a seperate PR.
> getHighestAvailableDomain helper method

- .travis.yml
- validator/README.md
- validator/build.py
- validator/validator_gen_js.py
This makes it easier to consume by scripts to e.g. pull the list of all tags allowed by a specific format or generate autocomplete definitions for playground.amp.dev.
> ✨ Adds generator for JSON version of the validator spec

- build-system/tasks/e2e/describes-e2e.js
- build-system/tasks/e2e/index.js
This allows a user of the command to filter only suites that have a
matching enumerated browser.
This Fixes https://github.com/ampproject/amphtml/issues/22432
> add browsers option to e2e task

- build-system/babel-plugins/babel-plugin-transform-amp-extension-call/test/fixtures/transform-call/transform-simple-body/input.js
- build-system/babel-plugins/babel-plugin-transform-amp-extension-call/test/fixtures/transform-call/transform-simple-body/output.js
- extensions/amp-mustache/0.1/amp-mustache.js
- extensions/amp-mustache/0.2/amp-mustache.js
- src/service/template-impl.js
Unregistering the template causes some visual diff tests to fail (#22047) and we traced the issue here. When this special-cased code was removed the visual diff test started working.
It's possible that our recent work on the testing infrastructure made this special-casing unnecessary, but I would appreciate if you can shed some light on why this was added in the first place
> ✅ Remove special casing for tests from amp-mustache extension registration

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/amp-story-store-service.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/events.js
- extensions/amp-story/1.0/test/test-amp-story.js
The Story runtime decides to either show the bookend, or send a message to the viewer depending the the `#cap=swipe` attribute.
When displayed in the context of a viewer that has multiple documents, the story runtime doesn't show the bookend but asks the viewer to navigate to the next story.
This PR enables messaging to tap to a next or previous story and browse a feed of stories from a viewer.
- Renames `SHOW_NO_PREVIOUS_PAGE_HELP` event into `NO_PREVIOUS_PAGE`
- Introduces a new `NO_NEXT_PAGE` event. We should eventually move away from these events but it'd be a pretty large refactoring, and we were happy with their performance last time we checked.
- Sends a message to the viewer when tapping back on the first page, or next on the last page, if in a viewer with multiple stories
- …
> Viewer messaging to select the next/previous document.

- extensions/amp-autocomplete/amp-autocomplete.md
- extensions/amp-base-carousel/amp-base-carousel.md
- extensions/amp-google-vrview-image/amp-google-vrview-image.md
- extensions/amp-next-page/amp-next-page.md
- extensions/amp-pan-zoom/amp-pan-zoom.md
- extensions/amp-script/amp-script.md
- extensions/amp-truncate-text/amp-truncate-text.md
- extensions/amp-user-location/amp-user-location.md
- extensions/amp-viz-vega/amp-viz-vega.md
The [experiments page](https://amp.dev/documentation/guides-and-tutorials/learn/experimental) on amp.dev now dynamically lists experimental components if they have a frontmatter key of `experimental` or `origin_trial`.
This adds `experimental` to: `amp-autocomplete`, `amp-base-carousel`, `amp-google-vrview-image`, `amp-next-page`, `amp-pan-zoom`, `amp-script`, `amp-truncate-text`, `amp-user-location` and `amp-viz-vega`.
/cc @CrystalOnScript @sebastianbenz
> 📖 Add frontmatter key to experimental components

- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/sra-utils.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
For doubleclick SRA requests, combine key/values shared by all slots in the request into single parameter (csp) instead of duplicating causing url length increase.
> amp-ad doubleclick SRA - combine common key/values into single parameter

- extensions/amp-form/0.1/form-dirtiness.js
- extensions/amp-form/0.1/test/test-form-dirtiness.js
This is used for the `amp-form-dirty` check. A form field is not dirty
when the value matches its submitted value.
> ✨ FEATURE: record form field's submitted value

- build-system/tasks/e2e/expect.js
This adds the rest of the Chai methods and properties to be compatible with the AMP E2E retryable promises for expect calls.
/cc @alanorozco
> ✅ Add remaining chai properties and refactor

- extensions/amp-analytics/0.1/linker-manager.js
- extensions/amp-analytics/0.1/test/test-linker-manager.js
Order:
1. respect `destinationDomains`
2. if `destinationDomains` can't be found. etld+1 can be found: Decorate all subdomain + friendly domain to canonical url
3. if `destinationDomains` can't be found. etld+1 can't be found (proxy origin w/o meta tag): Decorate all friendly domains (canonical + source)
> Linker: change default behavior to decorate all subdomains (if can be found)

- extensions/amp-accordion/0.1/amp-accordion.js
- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- Add aria attributes to autocomplete to identify the `aria-activedescendent` for reading and indexing selected values properly.
- Change `aria-autocomplete` from `list` to `both` to suggest that there are both list items provided and that the selected value is updated inline in the input field.
- Follow up with some related comments with `amp-accordian` suggested in #18534
> Make sure SR reads index of list options in amp-autocomplete

- extensions/amp-brightcove/0.1/amp-brightcove.js
- extensions/amp-brightcove/0.1/test/test-amp-brightcove.js
Redispatches the loadedmetadata event. This is needed for percentage analytics.
> 🐛amp-brightcove: Redispatch loadedmetadata event

- build-system/tasks/css.js
- src/service/video/install-autoplay-styles.js
A change introduced in PR #22377 was causing errors when I ran `gulp` since it attempts to parse a CSS file as JS. The code no longer produces the error when the `.css.js` file is used instead.
> Use css.js for autoplay styles

- extensions/amp-consent/0.1/consent-ui.js
Making sure the consent UI AMP element is upgraded before calling `whenBuilt`.
This PR is actually a follow up on #18841, that waits for the consent UI to be built before showing it. Sometimes, the code would run even before the component is upgraded to an AMP custom element. The `whenBuilt` method would not exist, resulting in `this.h.whenBuilt is not a function` errors.
> Making sure the consent UI AMP element is upgraded before calling whenBuilt.

- extensions/amp-script/amp-script.md
This PR is dependent on me landing a definition of OT in amp.dev.
Will add a link to the OT definition and edit this PR then.
> Add OT link in amp-script documentation

- ads/zucks.js
- examples/ads.amp.html
- Fix a bug from our pull request (https://github.com/ampproject/amphtml/pull/20206)
- Start using loadScript for tag that supports async load
> 🐛Fix zucks ad return timing

- extensions/amp-sidebar/0.1/amp-sidebar.js
`HTMLElement.focus()` causes undesirable scrolling on UIWebView. There also doesn't seem to be a good way to target UIWebView specifically via user agent.
Tested on iPhone 7, Safari 12.1.3 and this doesn't appear to have any impact on a11y (VoiceOver focus).
`b/133327438`
> Fix amp-sidebar scrolling on open/close in UIWebView

- examples/autocomplete.amp.html
- examples/visual-tests/amp-autocomplete/amp-autocomplete.amp.html
- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
- extensions/amp-autocomplete/amp-autocomplete.md
- tools/experiments/experiments.js
Resolves #21021
- Remove experiment tags from `amp-autocomplete` component, tests, and examples
- Update availability and associated documentation
- Removes `amp-autocomplete` from `experiments.js`
> Cleanup `amp-autocomplete` experiment.

- extensions/amp-story/1.0/amp-story.js
This PR sets the viewport size styles during prerender, to avoid a font size jump when the document goes from `PRERENDER` to `VISIBLE` (more info and screenshots in the issue).
Fixes #22752
> Update story viewport size styles in prerender.

- build-system/tasks/report-test-status.js
This PR is a nit, because this:
Looks better than this:
(especially because we still have the `single-pass` line, not `single_pass` 😬)
> Rename reported test status from `local_changes` to `local-changes`

- extensions/amp-form/0.1/amp-form.js
- extensions/amp-form/0.1/test/test-amp-form.js
A new `amp-form-dirty` class will be applied to AMP form's `<form>`
element, when any of its containing form controls is dirty.
A form control is dirty, when its value:
- does not match its default value, and
- does not match its last submitted value, and
- is not empty.
> ✨ Integrate `amp-form-dirty` into AMP form

- build-system/tasks/a4a.js
- build-system/tasks/integration.js
- build-system/tasks/runtime-test/helpers.js
- build-system/tasks/runtime-test/runtime-test-base.js
- build-system/tasks/unit.js
- gulpfile.js
Changes in this PR
- Creates `gulp a4a`
- Moves shared code into new `RuntimeTestRunner` and `RuntimeTestConfig` classes that unit, integration, and a4a tests use
Next steps
1. Documentation
2. Delete `runtime-test/index.js` and announce changes to team
related to masterbug #22507
> 🏗 Create gulp a4a and refactor unit/integration/a4a

- ads/README.md
- build-system/tasks/pr-check.js
- contributing/TESTING.md
- contributing/buildcop.md
- contributing/building-an-amp-extension.md
- contributing/getting-started-e2e.md
- contributing/getting-started-quick.md
- contributing/good-first-issues-template.md
Switches out `gulp test` with `gulp unit` or `gulp integration` in documentation + minor clean ups.
related to masterbug #22507
> 📖 Update testing documentation

- extensions/amp-consent/0.1/consent-ui.js
This PR adds the `allow-popups` rule to the consent prompt ui iframe.
This implements the feature requested in #22759
There doesn't appear to be any tests or an example related to this change that needed updating, correct me if I'm wrong.
/cc @zhouyx  @torch2424
> ✨ Adding 'allow-popups' to the consent prompt UI iframe

- src/service/viewport/viewport-binding-def.js
- src/service/viewport/viewport-binding-ios-embed-sd.js
- src/service/viewport/viewport-binding-ios-embed-wrapper.js
- src/service/viewport/viewport-binding-natural.js
- tools/experiments/experiments.js
`getContentHeight()` is incorrect for some pages on iOS since the margin-bottom of the last child is not included in `getBoundingClientRect().height`. To fix this, calculate and add it manually.
Gated under `bottom-margin-in-content-height` experiment. Will enable it in a separate PR.
`b/134179389`
> Include child margin-bottom in content height

- extensions/amp-analytics/0.1/linker-manager.js
- extensions/amp-analytics/0.1/test/test-linker-manager.js
Fixes a regression introduced in https://github.com/ampproject/amphtml/pull/22361
We should not overwrite href if linker param is not added.
Fixes b/134696625
> Linker: fix handling of fragments

- extensions/amp-experiment/0.1/amp-experiment.js
- extensions/amp-experiment/1.0/amp-experiment.js
- extensions/amp-story/1.0/amp-story-share.js
- src/log.js
previously we always had to cast the return type to the assert functions/methods to get the correct return type (because it would always return a union type of `type|null`. adding the `@template R` annotation here fixes the type narrowing problem since it reduces the type to just the passed in type.
> fix type narrowing problem so that we can remove casts

- extensions/amp-story/1.0/_locales/default.js
- extensions/amp-story/1.0/_locales/en.js
- extensions/amp-story/1.0/amp-story-system-layer.css
- extensions/amp-story/1.0/amp-story-system-layer.js
- src/localized-strings.js
Follow up for #22519
Partial for #21714
Shows a label when a live story is updated with new pages and the user is on the last page.
Preview:
EDIT: updated UX
> ✨ Show label when live story is updated and user is on last page.

- build-system/tasks/runtime-test/index.js
To let developers know to use new tasks, print out a warning for several days before we delete this task.
related to masterbug #22507
> 🏗 Print warning that `gulp test` will be deprecated soon

- extensions/amp-bind/amp-bind.md
Add a table entry to indicate that `aria-` attributes can be updated using `<amp-bind>`.
> Update amp-bind docs for aria attributes.

- build-system/tasks/a4a.js
- build-system/tasks/integration.js
- build-system/tasks/runtime-test/helpers-unit.js
- build-system/tasks/runtime-test/helpers.js
- build-system/tasks/runtime-test/runtime-test-base.js
- build-system/tasks/unit.js
Gulp test refactor clean up
- moves config methods outside class
- fixes bug for `gulp unit --local_changes` that logged things twice
- updates Travis reporter for `gulp unit --local_changes` that printed test names instead of dots
- fills out gulp task information for `unit`, `integration`, and `a4a`
Follow up to https://github.com/ampproject/amphtml/pull/22717
> 🏗 Gulp test refactor clean up

- extensions/amp-analytics/0.1/variables.js
- src/service/url-replacements-impl.js
- src/service/variable-source.js
This is to follow up #22423 
After the fix in #22508. All macro input arguments are guaranteed to be string. Removed unnecessary string check.
> Remove unnecessary type cast in macro resolvers

- src/service/performance-impl.js
- test/unit/test-performance.js
This metric is now sent when the viewer visibility state changes to inactive, rather than just on document end of lifecycle.
Fixes #22781
> :bug: Send layout jank metrics more proactively.

- examples/viewer.html
- examples/xhr-intercept.html
- src/utils/xhr-utils.js
- test/unit/test-xhr.js
follow up to addressing https://github.com/ampproject/amphtml/pull/22600#discussion_r291307673
-allow xhr interceptor in local dev mode and not in validation development mode.
-add viewer xhrInterceptor example.
> Allow XHR interceptor in local development mode

- extensions/amp-viewer-integration/0.1/highlight-handler.js
- extensions/amp-viewer-integration/0.1/test/test-highlight-handler.js
Based on the discussion with UI designers, we decided to change the background color of highlighted texts into yellow to keep consistency with Chrome:
https://docs.google.com/document/d/1OzfBkwXkeALVHtcqrK7Wj_GN3Jk_rlhdOAElPH_jabI/edit#heading=h.6m0mi6jwv4v0
> Change the background color of highlighted texts from orange to yellow.

- extensions/amp-date-picker/0.1/amp-date-picker.js
- extensions/amp-date-picker/0.1/test/test-amp-date-picker.js
Fixes #22688
Instead of assigning `readonly` at load-time, assign it just before the mobile device focuses on the input element. This prevents the keyboard from appearing and allows validation to continue as normal.
> 🐛Fix form-validators with date picker on touch devices

- extensions/amp-story/1.0/amp-story.css
To be prerendered, an element has to either:
- Be in the first 20 elements discovered
- Be positioned in a predefined layout area AND have a non zero height (!!!!)
`amp-story` is `height: 100%;` which means the height has to be propagated from its ancestors chain. The chain starts as soon as `amp-story.buildCallback()` sets a class on `<html>`. When the document is visible, `amp-story` will build even if it has no height. However, during prerendering, we need to make sure it has a height of at least 1px in order to build.
There's already a `min-height: 1px;` rule in `ampdoc.css`, but apparently if the `amp-story.css` loads before the runtime tries to build `<amp-story>`, it would be overriden by the expected styles we want when the document is visible.
This fix should be a safe …
> Story min-height fallback during prerendering.

- extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
- src/custom-element.js
- src/inabox/inabox-viewport.js
- src/service/layers-impl.js
- src/service/resource.js
- test/unit/inabox/test-inabox-viewport.js
By forcing remeasure during resource measure, we were invalidating both the element and it's entire parent layer. This had the effect of remeasuring every element on the page when the parent layer is the root scroller.
`Resources` calls this measurement during it's initial page rendering (in a loop on every `Resource`). That gets us n<sup>2</sup> calls to `getBoundingClientRect()` and `clientWidth`/`clientHeight`, which slowed everything down.
Thankfully, there was only one caller that actually needed a forced remeasurement.
> 🚀 Layers: Fix quadratic remeasurements during initial page load

- examples/visual-tests/amp-story/amp-story-live-story.html
- extensions/amp-live-list/0.1/live-list-manager.js
- extensions/amp-live-list/0.1/test/test-live-list-manager.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/live-story-manager.js
- extensions/amp-story/1.0/test/test-live-story-manager.js
In an effort to make the "live story" functionality as easy to use for publishers as possible, we are removing the need to include a value in the `dynamic-live-list` attribute. 
Previously this value was used so that, when updating the live list with the server updates, the code reading the document from the server knew how to find the amp-live-list element. Since this value was present in both client and server documents, it gave us the information we needed to find the updates in the server document.
With this PR we follow a different approach -- from using something _we have_ to something _we know_. It uses a reserved hash (id + 'dynamic-list') to make the match and find the live list in the DOM. This way, when looking at the server document, we know how to find this element without …
> Remove dynamic-live-list attribute

- contributing/DEVELOPING.md
- contributing/buildcop.md
We currently tell people to let the buildcop know when there is an issue with the tests, but don't have a way of contacting the buildcop.
Instead, let's point people to the #contributing channel on Slack, where the buildcop should be (and if not, someone who is in the channel would be able to let the buildcop know).
This change also more explicitly tells the buildcop to pay attention to the #contributing channel on Slack.
/cc @ampproject/wg-infra
> Point people to Slack instead of buildcop when there's a test breakage

- extensions/amp-anim/0.1/amp-anim.js
- extensions/amp-anim/0.1/test/test-amp-anim.js
Pass opt_removeMissingAttrs to remove the srcset attribute if it is not specified on the amp-anim element. This clears the placeholder value set in `unlayoutCallback`.
Fixes #22864
> 🐛Remove srcset on relayout if needed

- extensions/amp-base-carousel/0.1/amp-base-carousel.css
- extensions/amp-base-carousel/0.1/amp-base-carousel.js
- extensions/amp-base-carousel/0.1/auto-advance.js
- extensions/amp-base-carousel/0.1/carousel.js
- Only go to the next item when the carousel arrow itself is clicked
rather than the element that contains the arrow (which is full height).
- Disable looping when there are less than 3x slides compared to the
visible count, since the UI does not behave  correctly. The threshold for this
can be reduced, but requires more work.
- Add an `allowWrap` option to `advance`. This is used to prevent the
next/prev arrows from looping (when looping is disabled) if they are quickly
clicked before they are disabled. Autoadvance is still allowed to wrap
when looping is disabled.
- Use the `scrollend` event, when available, to immediately restore the
scrolling reference point. This ne feature allows us to determine when
scrolling ends directly instead of waiting for a gap after a scroll
event.
* We …
> 🐛Various fixes for amp-base-carousel.

- examples/analytics-vendors.amp.html
- extensions/amp-analytics/0.1/test/test-vendors.js
- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors.js
- extensions/amp-analytics/0.1/vendors/webengage.js
Resolves #22124 . Adds WebEngage as an amp-analytics vendor option.
@lannka
> ✨ Add WebEngage as an analytics vendor

- src/inabox/amp-inabox.js
- src/service/core-services.js
This will reduce amp4ads-v0.js size from 285K to 275k by excluding all the unused iOS viewport bindings code from inabox runtime.
for #22867
> Inabox: remove unnecessary dependencies on various viewport bindings

- examples/article-with-lightbox-2.0-gallery.amp.html
- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
- Copy over all `data-` attributes when carousel slides are wrapped for
pan-zoom within `<amp-lightbox-gallery>`.
- Fixes/improvements for `article-with-lightbox-2.0-gallery` example:
* Fix incorrect analytics config for carousel slide changes, was using the wrong event name so analytics was not firing.
* Add from/to slide as url params.
* Add URL param for the slide changes in the lightbox as an example of
how to distinguish the two sources of slide changes.
* Add data-slide-id for some of the slides in the second carousel as
an example.
Fixes #22883
> 🐛Fix `data-slide-id` not being preserved when lightboxing a carousel.

- build-system/amp4test.js
- src/inabox/amp-inabox.js
- test/integration/test-amp-inabox.js
`maybeTrackImpression` was introduced for Ads landing page (ALP), which does not apply to AMPHTML ads.
This will reduce amp4ads-v0.js size from 275K to 273K.
for #22867
> Inabox: remove unnecessary dependency on maybeTrackImpression

- src/service/viewport/viewport-binding-def.js
- test/unit/test-viewport.js
- Ignore children that don't affect height of the document.
- Add tests now that this is a substantial piece of code. :)
`b/133327438#comment27`
> marginBottomOfLastChild should only check position=static|relative

- extensions/amp-live-list/0.1/live-list-manager.js
- extensions/amp-live-list/0.1/test/test-live-list-manager.js
Support a `live-story-disabled` attribute in the `live-list-manager.js` so that when a live story is disabled we stop polling for new updates.
Partial for #21714 #22841
> Add live-story-disabled attribute to support disabled live stories

- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-bind/0.1/test/integration/test-bind-impl.js
- src/amp-events.js
This introduces a new `AmpEvents.VALUE_CHANGE` event. It is dispatched
when `amp-bind` mutates form input values, specifically:
`<input [value]>`, `<textarea [text]>`, `<input [checked]>`, and
`<option [selected]>`.
A custom event is chosen over a mutation observer, because binding
`[text]` on `textarea` does not change the DOM (and it's expected), thus
a mutation observer won't pick up the change. The same applies to
`input` elements, when we eventually have two separate bindings for
`[value]` and `[defaultValue]`.
/cc @GoTcWang @choumx thanks!
> Dispatch VALUE_CHANGE on `amp-bind` value changes

- src/custom-element.js
This should break an infinite loop when an element has to wait for layout (eg, owned by another element) but is in viewport. Showing the loading indicator causes a mutate, which has to be measured, which causes another mutate (because the `toggleLoading` happens as a step in `onLayoutMeasure`).
Fixes #22525.
> 🐛 Do not toggle loading to same state

- extensions/amp-date-picker/0.1/amp-date-picker.js
- extensions/amp-date-picker/0.1/test/test-amp-date-picker-bind.js
- extensions/amp-date-picker/0.1/test/test-amp-date-picker-state.js
- extensions/amp-date-picker/0.1/test/test-amp-date-picker.js
- extensions/amp-date-picker/0.1/test/test-wrapper-maximum-nights.js
- extensions/amp-date-picker/0.1/wrappers/maximum-nights.js
With this PR, every file in `amp-date-picker` should have test coverage above 80%. Some of these tests are also regression tests for previous bugs.
> Improve all adp modules coverage to above 80%

- build-system/eslint-rules/no-export-side-effect.js
- Allows ExportSpecifier
Example:
```js
export {x, y};
```
> ♻️ ESLint Rules: Allow ExportSpecifier

- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-attribution.css
- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
- extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
Moves the ad badge container to the same shadow root as the ad badge.
Changes logic to to propagate all meaningful attributes to the shadow root (using js), instead of relying on not-well-supported  `:host-context` CSS selector. 
Closes #22592
> 🐛Fix `Ad` badge in non-chrome browsers.

- .eslintrc
- ads/inabox/position-observer.js
- extensions/amp-a4a/0.1/real-time-config-manager.js
- extensions/amp-a4a/0.1/refresh-manager.js
- extensions/amp-a4a/0.1/signature-verifier.js
- extensions/amp-access/0.1/amp-access-other.js
- extensions/amp-access/0.1/amp-access-server.js
- extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
- extensions/amp-analytics/0.1/analytics-root.js
- extensions/amp-animation/0.1/amp-animation.js
- extensions/amp-animation/0.1/parsers/css-expr-ast.js
- extensions/amp-base-carousel/0.1/amp-base-carousel.js
- extensions/amp-base-carousel/0.1/carousel-accessibility.js
- extensions/amp-base-carousel/0.1/carousel.js
- extensions/amp-bind/0.1/amp-bind-macro.js
- extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js
- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
- extensions/amp-lightbox-gallery/0.1/lightbox-caption.js
- extensions/amp-lightbox-gallery/0.1/lightbox-controls.js
- extensions/amp-live-list/0.1/poller.js
- extensions/amp-position-observer/0.1/amp-position-observer.js
- extensions/amp-story/1.0/amp-story-system-layer.js
- extensions/amp-story/1.0/page-advancement.js
- extensions/amp-story/1.0/story-analytics.js
- src/service/storage-impl.js
- src/service/viewport/viewport-binding-ios-embed-wrapper.js
- src/service/vsync-impl.js
#15075 added a new lint rule called `amphtml-internal/unused-private-field` to ensure that all private class fields are correctly annotated. Since then, the rule has sat around for a while in warning mode and then gotten turned off.
This PR re-enables the rule and updates annotations that aren't supposed to be `@private`.
**Note:** Most of the annotations I've changed are obviously supposed to be `@protected`, `@restricted`, or `@visibleForTesting`. However, a small handful of fields are either not being used anywhere, or are being exposed to external code in some way. In the interest of not touching code, I've gone ahead and marked them `@protected`.
> 🐛 Turn on the `amphtml-internal/unused-private-field` rule, fix errors

- src/service/fixed-layer.js
- test/unit/test-fixed-layer.js
This prevents double-offsetting of elements that are nested inside another fixed/sticky-positioned element.
Fixes #22860
Fixes #22881
> 🐛 FixedLayer: Do not track children of already tracked elements

- extensions/amp-story/1.0/navigation-state.js
- extensions/amp-story/1.0/story-analytics.js
- extensions/amp-story/1.0/test/test-analytics.js
> 📈 Add last-page-visible trigger

- extensions/amp-form/0.1/form-dirtiness.js
- extensions/amp-form/0.1/test/test-form-dirtiness.js
`AmpEvents.FORM_VALUE_CHANGE` is dispatched when `amp-bind` changes a
form value (e.g. input field, dropdown menu selection, etc).
This updates `FormDirtiness` to listen to `amp-bind` changes, and
recalculate the overall dirtiness accordingly.
> Update form dirtiness on FORM_VALUE_CHANGE event

- extensions/amp-base-carousel/0.1/carousel.css
- extensions/amp-carousel/0.1/amp-carousel.css
Fixes the clipping in Firefox for `<amp-carousel>` and `<amp-base-carousel>`. This was already fixed for Safari/Chrome (#20513).
There does not appear to be a solution for Edge/IE.
Fixes #18352
> 🐛Fix bottom of slides being clipped.

- extensions/amp-subscriptions/0.1/amp-subscriptions.js
- extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Adds `cap=paywall` to viewer - allows a viewer to suppress on page paywall and provide its own it it's also handling auth.
> ✨ Allow viewer to override paywall as well as auth

- build-system/compile/compile.js
- build-system/conformance-config.textproto
- extensions/amp-auto-ads/0.1/anchor-ad-strategy.js
- extensions/amp-date-picker/0.1/dates-list.js
- extensions/amp-experiment/1.0/attribute-allow-list/allowed-attribute-mutation-entry.js
- extensions/amp-geo/0.1/amp-geo.js
- extensions/amp-story/1.0/page-advancement.js
Re: https://github.com/ampproject/amphtml/issues/22822#issuecomment-503332800
Fixes #22822
> 🐛 Report conformance config violations as errors

- .travis.yml
Removes `$HOME/.cache/pip` from the cache because it changes every build, which means uploading new files for every Travis job. `pip` should already be supported on Xenial VMs but if not, we should install it in a `before_install` script instead of keeping in the cache.
Removes `stop_sauce_connect.sh` because it's a duplicate.
Also removes `sauce_connect` from the cache - unclear what that is?
Adds `ps -ef` as `after_script`s on the remote test and e2e jobs, because they have a tendency to hang and I'd like to see what processes are still running after the tests are complete.
> 🏗 Clean up build cache on Travis

- build-system/default-pre-push
- build-system/tasks/lint.js
- build-system/tasks/pr-check.js
- contributing/TESTING.md
- contributing/getting-started-e2e.md
The convention for multi-word `gulp` flag names is to use an underscore instead of a dash.
This PR changes the `gulp lint` flag from `--local-changes` to `--local_changes`, and makes it consistent with the flag used for `gulp unit`. It also prints a warning when the old flag is used.
> 🏗 Change `gulp lint` flag from `--local-changes` to `--local_changes`

- build-system/tasks/karma.conf.js
- build-system/tasks/runtime-test/runtime-test-base.js
#22927 added a global transform for packages listed in `dependencies` in `package.json`. However, it missed the code paths for code coverage and local test runs.
This PR fixes both issues.
Follow up to #22927
Closes #22949
> 🐛Fix global transform configs for `babelify`

- extensions/amp-youtube/0.1/amp-youtube.js
- extensions/amp-youtube/0.1/test/test-amp-youtube.js
- extensions/amp-youtube/0.1/test/validator-amp-youtube.html
- extensions/amp-youtube/0.1/test/validator-amp-youtube.out
- extensions/amp-youtube/amp-youtube.md
- extensions/amp-youtube/validator-amp-youtube.protoascii
See discussion in #22855 for context
Closes #22855 
- Handles looping internally through javascript instead of the Youtube player for standalone videos (fixes both transition issues during looping as well as removes the need to add `data-param-playlist` whenever `data-param-loop` is specified), and delegates looping to the Youtube player for playlists
- `data-param-loop` is no longer supported on `amp-youtube` and is replaced by the `loop` parameter
Screencast demonstrating the issue (credits @westonruter ) https://youtu.be/8PZGJf3dtwM
> 🐛Smoother amp-youtube video looping

- 3p/integration.js
- ads/1wo.js
- ads/1wo.md
- ads/_config.js
- examples/ads.amp.html
- extensions/amp-ad/amp-ad.md
Implemented 1WorldOnline ad integration
> ✨ Ads: 1WorldOnline ad integration

- build-system/tasks/e2e/controller-promise.js
- build-system/tasks/e2e/expect.js
- build-system/tasks/e2e/functional-test-controller.js
- build-system/tasks/e2e/puppeteer-controller.js
- build-system/tasks/e2e/selenium-webdriver-controller.js
- test/unit/test-controller-promise.js
It feels meta, but the `ControllerPromise` class seems complex enough that it needs its own tests.
These can also help serve as documentation for how the `expect.js` wrapper in Chai is implemented to make everything a little clearer because there is a lot of indirection.
> ✅ Add tests and comments for ControllerPromise. Refactor

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/amp-story-store-service.js
- extensions/amp-story/1.0/amp-story-vertical.css
- extensions/amp-story/1.0/amp-story.css
- extensions/amp-story/1.0/amp-story.js
- Rendering page attachments at the bottom of the document in vertical rendering
- Rename `UIType.SCROLL` into `UIType.VERTICAL`
- Preventing from switching from `UIType.VERTICAL` to any other `UIType`. All the other UITypes can be switched from one to the other, but allowing to do so with this mode would introduce a lot of unnecessary complexity. This PR adds an error message if someone tries to do so, so we don't end up in a broken state.
> Rendering page attachments at the bottom of the document in vertical rendering.

- extensions/amp-user-location/amp-user-location.md
Change markdown \` \`  to \<code>\</code> on tables to prevent strange accents.
related to #22970
> 🐛[amp-user-location] fix accents appearing when converting md

- extensions/amp-analytics/amp-analytics.md
It's supposed to have the same level as other siblings like "Access triggers" above, nested under "Triggers".
> Fix headings for "Video analytics triggers"

- examples/visual-tests/amp-story/amp-story-vertical-rendering.html
- extensions/amp-story/1.0/amp-story-vertical.css
- extensions/amp-story/1.0/amp-story.js
Show the story bookend in vertical rendering.
> Show the story bookend in vertical rendering.

- extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
- extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
- extensions/amp-subscriptions/0.1/actions.js
- extensions/amp-subscriptions/0.1/analytics.js
- extensions/amp-subscriptions/0.1/local-subscription-platform-base.js
- extensions/amp-subscriptions/0.1/test/test-actions.js
- extensions/amp-subscriptions/0.1/test/test-analytics.js
- extensions/amp-subscriptions/0.1/test/test-local-subscription-rendering.js
- extensions/amp-subscriptions/0.1/test/test-local-subscriptions-iframe-platform.js
- extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
- extensions/amp-subscriptions/0.1/test/test-renderer.js
- extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
This replaces the use of strings with enums for action commands and logging within amp-subscriptions and amp-subscriptions-google.  It is required for a future project which will enhance event management within the subscriptions frameworks.
> ♻️ Create enums for Actions and ActionResults

- src/dom.js
- src/friendly-iframe-embed.js
- src/service/ampdoc-impl.js
- src/service/extensions-impl.js
- src/shadow-embed.js
- test/_init_tests.js
- test/unit/test-ampdoc.js
- test/unit/test-dom.js
- test/unit/test-friendly-iframe-embed.js
- test/unit/test-runtime.js
- test/unit/test-shadow-embed.js
- tools/experiments/experiments.js
> Create skeleton and navigation for FIE ampdocs

- build-system/compile/compile.js
- build-system/compile/single-pass.js
- build-system/tasks/dist.js
This prints the minified closure builds without whitespace, making debugging issues with compiled code less of a nuisance.
> 🏗 Add pretty_print option to compiled output

- build-system/amp.extern.js
- examples/bind/list.amp.html
- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-bind/0.1/test/integration/test-bind-impl.js
- extensions/amp-date-picker/0.1/amp-date-picker.js
- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
Fixes #22341, partial for #21901.
- Bug: Fix race condition between `amp-list[binding=refresh]` and amp-bind's initial DOM scan.
- Optimization: Skip `Bind.rescan` in amp-list if new children have no binding marker attributes (`[i-amphtml-binding]`).
- Optimization: Significantly speed up initial render for amp-list[binding=always] by changing `Bind.rescan` to only wait for a small part of Bind's initialization.
- Bug: Refactor `Bind.rescan` to fix/support amp-date-picker's usage.
> Fix race and speed up amp-list/amp-bind interaction

- build-system/eslint-rules/await-expect.js
- build-system/tasks/e2e/expect.js
- test/e2e/test-expect.js
This PR tests and establishes that `ControllerPromise`s work with the overwritten Chai methods in `expect.js` in positive and negative cases, in combination with the value being immediately and eventually correct.
This also adds support for failing a test if a `ControllerPromise` is passed to a Chai method that doesn't make sense, like `throw`.
While testing I found that the fix in #22811 was causing an error that got swallowed and prevented the rest of the overwrites from getting added. The full fix for the error #22811 tried to solve was to make the method in `overwriteAlwaysUseSuper` not `async`. In debugging I found a misbehavior where a try/catch generated by the async/await transform was eating the error that the overwritten expect needed.
> ✅ Add tests for the expect wrapper

- extensions/amp-truncate-text/amp-truncate-text.md
- extensions/amp-viewer-assistance/amp-viewer-assistance.md
This is to prevent these two from being visible on amp.dev under the wrong categories.
> 📖 Update formats for amp-truncate-text and amp-viewer-assistance

- extensions/amp-truncate-text/0.1/amp-truncate-text-shadow.css
- extensions/amp-truncate-text/0.1/amp-truncate-text.css
- extensions/amp-truncate-text/0.1/amp-truncate-text.js
- extensions/amp-truncate-text/0.1/test/test-amp-truncate-text.js
- extensions/amp-truncate-text/0.1/test/validator-amp-truncate-text.html
- extensions/amp-truncate-text/0.1/test/validator-amp-truncate-text.out
- extensions/amp-truncate-text/0.1/truncate-text.js
- extensions/amp-truncate-text/amp-truncate-text.md
- test/manual/amp-truncate-text/always-show-expand.amp.html
- test/manual/amp-truncate-text/even-more.amp.html
- test/manual/amp-truncate-text/expand-collapse.amp.html
- test/manual/amp-truncate-text/full-width-button.amp.html
- test/manual/amp-truncate-text/inline-block-compact.amp.html
- test/manual/amp-truncate-text/inline-block-large.amp.html
- test/manual/amp-truncate-text/inline-button.amp.html
- test/manual/amp-truncate-text/link-before-truncation.amp.html
- test/manual/amp-truncate-text/link-truncated.amp.html
- test/manual/amp-truncate-text/persistent-and-collapsed.amp.html
- test/manual/amp-truncate-text/persistent.amp.html
- test/manual/amp-truncate-text/right-aligned-compact.amp.html
- test/manual/amp-truncate-text/right-aligned-large.amp.html
- Rename "expand" slot into "collapsed", since it may be used to do something
other than expand.
- Rename "collapse" slot into "expanded", since it may be used to do something
other than collapse.
- Support custom tap actions as well as anchor tags, which will override
the default expand/collapse behavior of the "collapsed" and "expanded"
slots.
- Add a "persistent" slot that is always present. This is useful when
you have something like a short description (which may be truncated,
depending on available space), but you want to link to another page
regardless of truncation.
> amp-truncate-text: support custom actions.

- .travis.yml
- build-system/exec.js
Also temporarily removes e2e node_modules in Travis cache.
Closes https://github.com/ampproject/amphtml/issues/23004
> 🐛 Update execOrDie to handle a null status

- src/runtime.js
- test/unit/test-runtime.js
fixes #22587
- need to add more tests
> Exposing meta tags from attachShadowDoc

- renovate.json
This PR prevents potentially risky auto-updates to packages that are shipped with the runtime.
> 🏗 Disable `renovate` for all dependencies in package.json

- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Allow width expansion to occur if the returned width is larger than the initial width.
Previously, for multi-size, we disallowed this behavior. However, as we introduce parent/full-width flexible ads, this behavior must be allowed.
Originally from PR #22593. That PR was abandoned due to git accidentally pulling in a bunch of unrelated changes.
> Allow width expansion for parent/full-width creatives

- src/service/layers-impl.js
- test/unit/test-layers.js
This is attempt 2 to fix the quadratic remeasurements described in #22809.
This changes the layers code so that child layouts are remeasured as needed, not eagerly when the parent layer is remeasured. Still, causing any mutation inside a layer causes all layouts inside that layer to be invalidated. But since we no longer need to remeasure everything in that layer to get the measurements of a single layout, this leads to significantly less remeasures overall.
> 🚀 Layers: Lazily remeasure child layouts

- build-system/tasks/runtime-test/runtime-test-base.js
#22931 added `build-system/tasks/e2e/controller-promise.js`, which is being [included](https://codecov.io/gh/ampproject/amphtml/tree/e6d62f2f3b41635c0aaa559b526ee01a41dc373a) in code coverage reports.
This PR removes `build-system/` from code coverage.
> 🏗 Exempt `build-system/` from code coverage

- build-system/tasks/presubmit-checks.js
Related to #22888  . 
For #22867
>  Add amp4ads documentations to storage/cid service presubmit rules.

- src/font-stylesheet-timeout.js
- test/unit/test-font-stylesheet-timeout.js
Fixes #22984. Chromium based browsers are changing the loading semantics of resources for media queries they know will never be supported. As a result, the font loading semantics of AMP are likely to break.
This PR moves AMP font loading timeout to use `print` instead of `not-blocking`.
> 🚀Move `non-blocking` font media to `print`

- build-system/tasks/extension-helpers.js
- build-system/tasks/helpers.js
This PR cleans up the old logic used to determine when to stop compilation and when to continue it during `watch` by adding a new field to `options` called `continueOnError`. This was necessary because extensions use an additional `watch` mechanism since they need to respond to changes to `.js` and `.css` files.
Addresses https://github.com/ampproject/amphtml/pull/13312#issuecomment-501037941
Follow up to #13312
Follow up to #22659
> 🏗🐛 Don't cancel `watch` if an edit causes a compilation error (redux)

- tools/experiments/experiments.js
Fixes #18737. Removing since #17589 was never shipped.
> Remove "fie-metadata-extension" experiment

- extensions/amp-analytics/0.1/analytics-root.js
This line is throwing some superfluous errors when we're testing AMP on mobile apps. I'm assuming it's not actually needed.
> Remove debugging fetch from amp-analytics.

- extensions/amp-access/0.1/amp-access.js
- extensions/amp-subscriptions/0.1/amp-subscriptions.js
- src/inabox/amp-inabox.js
- src/inabox/inabox-cid.js
- src/service/cid-impl.js
- src/service/core-services.js
- src/service/url-replacements-impl.js
- src/services.js
- test/unit/test-url-replacements.js
> Provide dummy impl for CID service in inabox.

- src/inabox/amp-inabox.js
- src/service/core-services.js
This reduces the size of amp4ads-v0.js from 273.5KB to 271KB
for #22867
> Inabox: remove unnecessary dependency on storage services.

- examples/experiment-1.0.amp.html
- extensions/amp-experiment/1.0/attribute-allow-list/allowed-attribute-mutation-entry.js
- extensions/amp-experiment/1.0/attribute-allow-list/attribute-allow-list.js
- extensions/amp-experiment/1.0/test/test-mutation-parser.js
- validator/validator-main.protoascii
relates to #21705
Pretty small change, but allows any class to be applied as an attribute mutation 😄
> ✨amp-experiment 1.0: Allowed all class changes

- extensions/amp-form/0.1/form-dirtiness.js
- extensions/amp-form/0.1/test/test-form-dirtiness.js
This includes:
- text fields
- textareas
- radio buttons
- checkboxes
- dropdown menus
> Support all native HTML inputs for dirtiness check

- src/service/resources-impl.js
Cleanup for the `amp-force-prerender-visible-elements` after it has been launched.
Part of https://github.com/ampproject/amphtml/issues/21791
> Cleanup amp-force-prerender-visible-elements experiment code.

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
- tools/experiments/experiments.js
The experiment was removed in https://github.com/ampproject/amphtml/commit/8a022533e1e3d2ce70609cb9058845e707751456#diff-b8f9686fbe618a8a1767815ebf2ae443
> Remove amp-apester-media exp flag

- extensions/amp-twitter/0.1/amp-twitter.js
The logic for sizing the placeholder, when a user placeholder is not present is no longer needed.
Fixes #22990
> 🐛Remove logic for old amp-twitter default loader

- extensions/amp-sidebar/0.1/amp-sidebar.js
- extensions/amp-sidebar/0.1/test-e2e/test-amp-sidebar.js
- test/fixtures/e2e/amp-sidebar/amp-sidebar.html
Closes #6757 
In ShadowDOM the sidebar mask was getting appended to the outer doc, not the body of the shadow document, so its styles and behavior weren't getting applied. This uses the ampdoc API method to get a reference to the correct body and fixes the bug.
> Add e2e tests for amp-sidebar. Fix bug in ShadowDOM.

- 3p/recaptcha.js
relates to #22279
This fixes the error handler throwing an error when the err that is returned by the reCAPTCHA script is null.
EDIT: Confirmed with team directly, error can be null
**If I put the test code:**
**It shows the error can be null:**
**Just proof the script is loaded correctly:**
> 🐛amp-recaptcha-input: Added support for error returning null

- examples/visual-tests/amp-story/amp-story-vertical-rendering.html
- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/animation.js
Any story content supposed to animate in when a page becomes active is hidden by default, and ignored by some search engine indexing tools.
This PR plays all the animations with no duration on render, and shows the pages in their active state.
If this PR works, the visual diff test should be a no-op. :))
Fixes #23070
> Play and finish all animations in story vertical rendering mode. 

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
- examples/date-picker.amp.html
- examples/travel-lb.amp.html
- examples/travel.amp.html
Cleans up the flag and some leftover doc-level optins from examples
> 🚮 Cleanup amp-date-picker feature flag

- extensions/amp-story/1.0/amp-story.js
This PR builds the story system layer in prerender mode. It used to wait for all the `amp-story-page` components to be built, even though we only need their `id` attribute.
> Build the story system layer during prerender.

- build-system/tasks/dist.js
Addresses https://github.com/ampproject/amphtml/issues/22637#issuecomment-505197725
Fixes #22637
> 🐛 Fix base path for `buildWebPushPublisherFile`

- examples/amp-story/bookend.html
- examples/amp-story/live-story.html
- extensions/amp-story/1.0/amp-story-store-service.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/live-story-manager.js
- extensions/amp-story/1.0/pagination-buttons.js
- extensions/amp-story/1.0/progress-bar.js
- extensions/amp-story/1.0/test/test-live-story-manager.js
Part of  #21714
* Installs amp-live-list extension automatically.
* Updates pagination buttons in 3-panels view. Closes #22770.
* Updates distance attributes on new pages.
* Supports adding a new page in the middle of a story & updates progress bar accordingly.
* Stops trying to append the new pages on the LiveStoryManger and leaves that to the amp-live-list.
* Adds an example live story.
> 💅 Live story polishes

- .travis.yml
Fixes this error seen on Travis visual diff jobs, similar to the e2e chromedriver error from earlier.
```
Error: Cannot find module 'puppeteer'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:690:17)
at require (internal/modules/cjs/helpers.js:25:18)
at installPercy_ (/home/travis/build/ampproject/amphtml/build-system/tasks/visual-diff/index.js:856:15)
at visualDiff (/home/travis/build/ampproject/amphtml/build-system/tasks/visual-diff/index.js:767:3)
at taskWrapper (/home/travis/build/ampproject/amphtml/node_modules/undertaker/lib/set-task.js:13:15)
at bound (domain.js:402:14)
at runBound (domain.js:415:12)
at asyncRunner …
```
> 🚮 Stop caching visual diff node_modules on Travis

- build-system/tasks/jsify-css.js
`autoprefixer` [added a warning](https://travis-ci.org/ampproject/amphtml/jobs/551960000#L323) for a potentially breaking change in its new version by renaming the `browsers` field. See #22652 and https://github.com/postcss/autoprefixer/issues/1226.
```
Replace Autoprefixer browsers option to Browserslist config.
Use browserslist key in package.json or .browserslistrc file.
Using browsers option cause some error. Browserslist config 
can be used for Babel, Autoprefixer, postcss-normalize and other tools.
If you really need to use option, rename it to overrideBrowserslist.
Learn more at:
https://github.com/browserslist/browserslist#readme
https://twitter.com/browserslist
```
This PR renames `browsers` to `overrideBrowserslist` as recommended in the warning.
> 🏗🐛 Silence `autoprefixer` deprecation warning by renaming `browsers` to `overrideBrowserslist`

- build-system/compile/compile.js
- build-system/tasks/jsify-css.js
- extensions/amp-date-picker/0.1/dates-list.js
- extensions/amp-date-picker/0.1/test/test-dates-list.js
In #22946, we switched `rrule` from a copy in `third_party` to an installed module. However, we neglected to add an entry for the module in the directories included in the runtime.
This PR fixes things so that the `rrule` code is included in `dist/v0/amp-date-picker-0.1.js`.
~It will likely have to be cherry-picked to canary before next week's prod push.~ **Edit:** None of the currently released versions are affected by this issue. This fix will make it into the next canary and prod releases.
> 🐛 Make sure `rrule` code is included in `amp-date-picker`

- extensions/amp-story/1.0/test/validator-amp-story-templates.html
- extensions/amp-story/1.0/test/validator-amp-story-templates.out
- extensions/amp-story/validator-amp-story.protoascii
Allowing the `position` attribute on `amp-story-grid-layer` so publishers can use [this feature](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story-templates.css#L17-L37).
> Allowing the position attribute on amp-story-grid-layer.

- extensions/amp-analytics/amp-analytics.md
Add documentation for the `requestOrigin` field in `amp-analyitcs` config. Implemented here https://github.com/ampproject/amphtml/pull/22454
cc @zhouyx
> 📖  Documentation for requestOrigin

- build-system/compile/single-pass.js
They're all incorrect due to non-sourcemap-aware transformations we do on them.
> 🏗 Remove all single-pass sourcemaps

- extensions/amp-subscriptions/0.1/local-subscription-platform-remote.js
- extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
Fixes a bug where we were not correctly serializing multiple entitlements if `pingbackAllEntitlements` is set
> correctly pingback multiple entitlements

- extensions/amp-twitter/0.1/test/validator-amp-twitter.html
- extensions/amp-twitter/0.1/test/validator-amp-twitter.out
- extensions/amp-twitter/validator-amp-twitter.protoascii
- test/manual/amp-twitter.amp.html
Closes https://github.com/ampproject/amphtml/issues/20340. 
The attributes `theme` and `link-color` are applicable to Tweets, Moments and Timelines. Since we already validate that one of `data-momentid`, `data-timeline-source-type`, or `data-tweetid` must be present, there is no need to additionally validate these since we pass on all `data-` attributes.
> Update amp-twitter validation for moments and timelines

- validator/testdata/amp4ads_feature_tests/amp_story_ad.html
- validator/testdata/amp4ads_feature_tests/amp_story_ad.out
- validator/testdata/amp4ads_feature_tests/amp_story_ad_errors.html
- validator/testdata/amp4ads_feature_tests/amp_story_ad_errors.out
- validator/validator-main.protoascii
Introducing a new meta tag that advertisers can use to pass information to the amp runtime. These new meta tags will be read by the a4a transformer, and their data will be added to the created `<script type="application/json" amp-ad-metadata>` object.
format:
`<meta name="amp-vars-id" content="123">`
> New validation rule for A4A meta tags.

- extensions/amp-image-lightbox/validator-amp-image-lightbox.protoascii
- extensions/amp-lightbox/validator-amp-lightbox.protoascii
Deprecate amp-lightbox and amp-image-lighbox in the AMP4EMAIL spec.
https://github.com/ampproject/amphtml/issues/23170
@choumx @fstanis
> 🐛 AMP4Email: Deprecate amp-lightbox and amp-image-lightbox

- src/utils/xhr-utils.js
- test/unit/utils/test-xhr-utils.js
- Adds descriptively named variables for readability.
- Fixes issue where test variables were leaking across tests.
- Fixes issue with `hasCapability` stub (used in several tests) returning `false` by default. So other means of preventing interception weren't being tested in isolation.
- Fixes issues with `'initialized to bypass'` test. An extra line (`ampDocSingle = null`) at the top of the test was causing `getViewerInterceptResponse` to no-op, before checking for the bypass flag and dev environment (which wasn't being mocked).
- Adds new `'proxy URL'` test.
- Adds new `'viewer can not intercept'` test.
- Updates tests to use async/await for readability.
- Updated a few beginnings of test titles from `'should be no-op...'` to `'should not intercept...'`. This helps clarify which tests …
> ♻️🐛 Refactors `getViewerInterceptResponse` and improves tests

- extensions/amp-story/1.0/pagination-buttons.js
`CURRENT_PAGE_INDEX` is 0 when loading a story on the first page, triggering a console error on every non mobile story load.
> Fix devAssert(0) console error.

- ads/revcontent.js
- ads/revcontent.md
For certain implementations writeScript is not a good option. loadScript will allow the recontent amp script to be added after the page is rendered. This should probably be the default but to maintain backward compatibility it will be enabled by passing the loadscript data attribute
> revcontent amp-ad loadscript option

- extensions/amp-analytics/0.1/linker-manager.js
This is to follow up #22815
As agreed offline, I am duplicating the binding declaration to support `COOKIE` in Linker. Once we pass element to variable service, or FIE has its own instance of ampdoc service. This can be removed.
> COOKIE macro support in linker

- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/test/test-amp-story.js
Considering the following example:
```
<style amp-custom>
foo {
transform: translate3d(-100vw, 0, 0);
}
</style>
```
The expected rewritten CSS should be `translate3d(calc(-100 * var(--story-page-vh)), 0, 0)`, but was `translate3d(-calc(100 * var(--story-page-vh)), 0, 0)`, which is invalid.
> Rewrite negative responsive units.

- ads/google/adsense.md
Update adsense example AMPHTML doc to make example snippet responsive and update supported tags.
Responsive is the preferred format for using the AdSense tag.
> Update adsense example AMPHTML doc to make example snippet responsive and update supported tags

- extensions/amp-story/1.0/amp-story-vertical.css
- extensions/amp-story/1.0/amp-story.js
Vertical rendering mode triggers all publishers custom CSS animations with no delay.
Context: some publishers might rely on the `[active]` attribute to trigger their CSS animations.
This PR adds an `[active]` attribute to all pages, and sets both the transition delay and duration to 0s, so pages are displayed in their final state.
Fixes #23070
> Vertical rendering mode triggers all publishers custom CSS animations with no delay.

- extensions/amp-analytics/0.1/test/test-variables.js
- extensions/amp-analytics/0.1/variables.js
Add a $MATCH macro. https://github.com/ampproject/amphtml/issues/23017
`$MATCH(str, regex, opt_index)`
Applies the [match function
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) to the given `str` with the given `regex`.
Returns the matching group declared by `opt_index`, where `opt_index=0` indicates the full match. Defaults to 0. If there is no match for the given index, empty string is returned
E.g.
`$MATCH(test.123, test\.(\d+), 0)`     ->     `test.123`
`$MATCH(test.123, test\.(\d+), 1)`     ->     `123`
`$MATCH(test.test, test\.(\d+), 1)`     ->     ``
cc @zhouyx @zikas
> ✨ Add MATCH macro

- build-system/tasks/ava.js
Fixes [this](https://travis-ci.org/ampproject/amphtml/jobs/556521119#L347) async completion bug introduced by #23188. Unfortunately, PR job didn't test it because the `ava` tests are run only when the tests or code are changed.
> 🐛 Fix async completion bug in `gulp ava`

- build-system/amp.extern.js
- build-system/compile/compile.js
When `gulp check-types` detects a real error, it's accompanied by hundreds of warnings due to known issues in the code. This PR fixes / silences those warnings so that only the errors that need to be acted on are displayed on the screen.
> 🏗 Silence / fix known warnings that appear when `gulp check-types` detects an error

- extensions/amp-story/1.0/amp-story-desktop-panels.css
The GPU memory used by our desktop three panels experience was so high that on some computers, the hardware-accelerated video decoding was stuttering, resulting on videos not playing.
(Hardware accelerated video decoding uses GPU, not CPU, which is why videos were playing smoothly when we were disabling it).
This fix gets all videos to play as smooth as expected in this desktop three panels layout, but as a nice side effect gets the overall experience much much faster.
Removing this `box-shadow` has no visible effect, since we removed the background images.
One line fix but really interesting performance improvements:
| Device  | Max GPU memory / Min FPS before | Max GPU memory / Min FPS after | Improvement |
| :-------------: | :-------------: | :-------------: | :-------------: |
| Dell …
> Story desktop GPU memory optimization so videos play smoothly.

- build-system/amp.extern.js
- build-system/tasks/presubmit-checks.js
- src/utils/xhr-utils.js
- test/unit/utils/test-xhr-utils.js
Adds prerenderSafe param to FetchInitDef. This param marks a request as safe to send before the viewer is visible.
Fixes #23101.
> 🚀 FetchInitDef prerenderSafe param

- build-system/compile/compile.js
- build-system/pr-check/single-pass-tests.js
This PR stops using `--pseudo_names` for `gulp dist` on Travis. It also increases the parallelism for single pass compile when the flag isn't being used.
Closes #23238
> 🏗 Increase parallelism for single pass unless `--pseudo_names` is used

- src/form-data-wrapper.js
- test/unit/test-form-data-wrapper.js
Fixes #23270
It looks like we check for this in `getFormAsObject` but neglected to in `NativeFormDataWrapper#maybeIncludeSubmitButton`. Added a regression test.
> Do not add nameless submit buttons to form data

- README.md
This adds a promo for the AMP Contributor Summit 2019 to our main repo's README.md.
/cc @ampproject/wg-outreach
> Add a promo to README for AMPCS2019

- builtins/amp-img.md
- extensions/amp-accordion/amp-accordion.md
- extensions/amp-ad/amp-ad.md
- extensions/amp-carousel/amp-carousel.md
- extensions/amp-fit-text/amp-fit-text.md
- extensions/amp-form/amp-form.md
- extensions/amp-list/amp-list.md
- extensions/amp-twitter/amp-twitter.md
- extensions/amp-video/amp-video.md
Ampbyexample code and preview iframes are replaced with inline example code
Resolves https://github.com/ampproject/docs/issues/2053
For the documentation directly in the 'docs' project this was already done.
An example how this looks like can be seen here:
https://amp-dev-staging.appspot.com/documentation/guides-and-tutorials/develop/media_iframes_3p/?format=websites
> 📖 Convert ampbyexample iframes to inline preview

- .yarnrc
This PR makes it so that `yarn add` installs an exact version to `package.json` by default
See https://yarnpkg.com/lang/en/docs/yarnrc/#toc-cli-arguments
> 🏗 Force exact versions during `yarn add`

- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list-load-more.js
- test/manual/amp-list/infinite-scroll-1.amp.html
The measurement from `positionRect.bottom` is actually (a call to `getClientBoundingRect`) measuring distance from viewport top already, not distance from the beginning of the page. There is no need to subtract the scrollTop distance in this case.
> Fix 3 viewports down bug

- extensions/amp-pinterest/0.1/pin-widget.js
- test/manual/amp-pinterest.amp.html
Closes https://github.com/ampproject/amphtml/issues/19281. 
The more severe problem here is the untabbable and unclickable `Save` button that's a `<span>` in `pin-widget.js`. Addressed that by adding a `tabindex`, `aria-label`, and a `onKeyDown` handler that triggers the click handler if `SPACE` or `ENTER` while selected. 
Ran lighthouse a few times and added aria labels and such--we should probably do this more systematically with our components.
> Fix a11y on amp-pinterest

- build-system/tasks/bundle-size.js
> Replace deprecated method call `.createFile` with `.createOrUpdateFile` in bundle-size.js

- extensions/amp-accordion/0.1/amp-accordion.js
Fixes #23254 
IE11 and Edge emit a syntax error when `attributesFilter` is used without `attributes: true` in the observe configuration object.
For example: https://stackoverflow.com/questions/50593385/mutationobserver-syntax-error-on-ie-11
> Fix IE11 syntax error with attributeFilter without attributes

- build-system/git.js
- build-system/pr-check/checks.js
- build-system/tasks/check-exact-versions.js
- build-system/tasks/pr-check.js
- build-system/tasks/presubmit-checks.js
- gulpfile.js
- package.json
- renovate.json
- yarn.lock
It often happens that someone adds a new package to `package.json` with a non-exact version number. This plays badly with Renovate, which relies on the presence of exact version numbers, and results in avoidable review comments or follow up fixes.
- Adds a new check called `gulp check-exact-versions` that makes sure all `package.json` files in the repo contain exact versions
- Adds a new helper function called `gitDiffFileMaster` to `git.js` (+ clean up)
- Updates `build-system/pr-check/checks.js` to run this task during PR checks on Travis
- Updates `build-system/tasks/pr-check.js` to run this task during local PR checks
- Updates `renovate.json` with the full list of `package.json` files in the repo that can receive regular version upgrades
> 🏗 Enforce exact versions in `package.json` files

- extensions/amp-story/1.0/animation.js
This PR introduces a number of fixes for animation bugs that we've had for a while related to hold-to-pause.
1: Console errors were showing up due to animations that hadn't started yet. This was due to the fact that we weren't checking if the animation was still waiting for another animation or had a delay.
2: When an animation with a delay was paused, it ignored the pausing and continued to animate. Fixes #23224
3: When an animation with a delay hadn't started yet, and the user navigated to another page and then came back, the delay wasn't being restarted, so it would appear right away on page landing.
To address these, I separated the `getStartWaitPromise_ ` and a new `getDelayWaitPromise_` that is only in charge of the delay. Each delay will get a `delayId_` and a `delayStartTime_`. …
> 🐛 Animation improvements

- build-system/tasks/dist.js
- build-system/tasks/e2e/index.js
- build-system/tasks/helpers.js
- build-system/tasks/integration.js
- build-system/tasks/presubmit-checks.js
- build-system/tasks/runtime-test/helpers.js
- build-system/tasks/runtime-test/runtime-test-base.js
- build-system/tasks/visual-diff/index.js
- contributing/TESTING.md
This PR enables the running of the `e2e`, `integration`, and `visual-diff` tests against the `canary` config.
**To run against the `prod` config (default):**
```
gulp e2e [...]
gulp integration [...]
gulp visual-diff [...]
```
**To run against the `canary` config:**
```
gulp e2e --config canary [...]
gulp integration --config canary [...]
gulp visual-diff --config canary [...]
```
**To run against whichever config type was previously built:**
```
gulp e2e --nobuild [...]
gulp integration --nobuild [...]
gulp visual-diff --nobuild [...]
```
> 🏗 Enable `e2e`, `integration`, and `visual-diff` tests to be run using the `canary` AMP config

- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-bind/0.1/test/integration/test-bind-impl.js
> amp-bind: Don't get stuck on sibling-less amp-list

- extensions/amp-story/1.0/bookend/amp-story-bookend.js
- src/service/navigation.js
- test/unit/test-navigation.js
fixes #23260
When clicking a link from the bookend, the URL wasn't being decorated with the `_gl` parameter because the bookend is inside a shadow DOM. 
This is because whenever the `handle_` method in `navigation.js` received the event, the `target` would correspond to the entire shadow DOM root, instead of the actual clicked target.
This PR allows custom AMP targets to be forwarded on the event by using a custom property, then `navigation.js` can check if this property exists, and use that instead of the default `target` that comes in the event.
> Pass correct event target from the bookend to the AMP linker

- src/service.js
- src/service/navigation.js
- test/unit/test-document-info.js
- test/unit/test-document-submit.js
- test/unit/test-element-service.js
- test/unit/test-friendly-iframe-embed.js
- test/unit/test-intersection-observer-polyfill.js
- test/unit/test-navigation.js
- test/unit/test-resource.js
- test/unit/test-standard-actions.js
- test/unit/test-template.js
- test/unit/test-url-replacements.js
- test/unit/test-viewer.js
> Fix tests for ampdoc-fie mode

- build-system/compile/compile.js
- build-system/performance-observer.extern.js
- extensions/amp-viewer-integration/TICKEVENTS.md
- src/service/performance-impl.js
- test/unit/test-performance.js
Fixes #23154
This introduces a bit of duplication with existing code for layout jank support. I've suggested we remove layout jank support in ~a month, see #23198.
> ✨ Introduce new tick event `cls` (Cumulative Layout Shift).

- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors/comscore.js
- Adding the consentState Macro into Comscore's UDM Tag as 'cs_amp_consent' 
- Comscore Jira ticket: [TAG-4790]
- Note: Cannot find Comscore's CLA agreement. Sent two emails to cla-submissions@google.com and have not received a response. Please advise
> ✨Add Consent State Macro into Comscore's Vendor Script

- build-system/runner/test/org/ampproject/AmpPassTest.java
- build-system/runner/test/org/ampproject/AmpPassTestEnvTest.java
Addresses https://github.com/ampproject/amphtml/pull/22839#pullrequestreview-262728210
Fixes these errors:
```
compile-tests:
[mkdir] Created dir: /usr/local/google/home/rsimha/src/amphtml/build-system/runner/build/test
[javac] Compiling 3 source files to /usr/local/google/home/rsimha/src/amphtml/build-system/runner/build/test
[javac] Compiling 2 source files to /usr/local/google/home/rsimha/src/amphtml/build-system/runner/build/test
[javac] /usr/local/google/home/rsimha/src/amphtml/build-system/runner/test/org/ampproject/AmpPassTest.java:37: error: constructor AmpPass in class AmpPass cannot be applied to given types;
[javac]     return new AmpPass(compiler, /* isProd */ true, suffixTypes, assignmentReplacements,
[javac]            ^
[javac]   required: …
```
> 🏗🐛 Fix broken `runner.jar` tests by removing unused code

- build-system/tasks/e2e/describes-e2e.js
- build-system/tasks/e2e/puppeteer-controller.js
- build-system/tasks/e2e/selenium-webdriver-controller.js
- extensions/amp-autocomplete/0.1/test-e2e/test-amp-autocomplete.js
- extensions/amp-base-carousel/0.1/test-e2e/test-arrows.js
- extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
- extensions/amp-base-carousel/0.1/test-e2e/test-non-looping.js
- extensions/amp-base-carousel/0.1/test-e2e/test-responsive.js
- extensions/amp-base-carousel/0.1/test-e2e/test-vertical.js
It's not perfect and not as highly prioritized, but it should still be maintained unless we decided to delete the code from the repo. This PR is a pre-requisite for the request interception feature.
Main changes
- Changed `SeleniumTestController#scroll` to be `scrollTo` to match the `FunctionalTestController` API
- Only run the Chrome browser tests for Puppeteer runs.
- Fix `ControllerPromise` `waitFunction` in `PuppeteerController` for falsy expected values.
5 tests are still not passing with Puppeteer: 3 amp carousel, one amp-form, one amp-script. But this is better than before. I'd like to merge this PR before fixing to move incrementally.
> ✅ Improve Puppeteer support.

- extensions/amp-story/1.0/amp-story-viewport-warning-layer.css
Fix rotation overlay font size that was made really small as a side effect of the responsive font sizing. The font size was ~9px.
> Fix rotation overlay font size.

- .eslintrc
- build-system/eslint-rules/private-prop-names.js
- build-system/runner/src/org/ampproject/AmpCodingConvention.java
- extensions/amp-analytics/0.1/amp-analytics.js
- extensions/amp-analytics/0.1/analytics-root.js
- extensions/amp-analytics/0.1/config.js
- src/cookies.js
- src/service/custom-element-registry.js
- src/service/fixed-layer.js
- src/service/vsync-impl.js
- src/style-installer.js
`AmpCodingConvention.java` checks function names for the `NoInline` suffix to prevent them from being inlined by closure compiler.
- Some function names in our codebase end with `NoInline_`, which doesn't match the suffix because of the underscore
- The suffix check is no longer required because closure compiler supports the `@noinline` annotation that has the same result (See https://github.com/google/closure-compiler/issues/2751 and https://github.com/google/closure-compiler/commit/9cc62fae5f473f226bb93f15a31eb8c7ff274e03)
This PR removes all custom suffix code and replaces it with `@noinline` annotations.
Partial fix for #17120 and #22452
> 🏗 Replace `NoInline` suffix check in `runner.jar` with the `@noinline` closure annotation

- build-system/runner/src/org/ampproject/AmpCodingConvention.java
- build-system/tasks/css.js
#10121 added a hack to `AmpCodingConvention.java` to prevent the inlining of CSS. This is no longer required because closure supports the `@noinline` annotation. (See https://github.com/google/closure-compiler/issues/2751 and https://github.com/google/closure-compiler/commit/5698304a8e8832805a67a720396540d53cb4a88b)
This PR replaces the hack with a `@noinline` annotation wherever `cssText` is defined.
Follow up to #23363
Partial fix for #17120 and #22452
> 🏗  Replace hack to prevent inlining of cssText with a `@noinline` annotation

- build-system/compile/compile.js
This is a workaround for https://github.com/google/closure-compiler-npm/issues/9
Related to #23238
Follow up to #23282
> 🏗 Reduce closure concurrency during slower compilation operations

- extensions/amp-story/1.0/amp-story-system-layer.css
Fixes #21898
Having this `-webkit-mask-image` property was causing glitches in Firefox mobile. 
Not sure why we had it in the first place but I tested it on both an Android with Firefox and on iOS with Chrome/Safari and it seems to work fine without it.
Demo: https://stamp-animation.firebaseapp.com
> 🐛 Firefox mobile progress bar glitch fix

- build-system/runner/src/org/ampproject/AmpCommandLineRunner.java
- build-system/runner/src/org/ampproject/AmpPass.java
- build-system/runner/test/org/ampproject/AmpPassTest.java
- build-system/runner/test/org/ampproject/AmpPassTestEnvTest.java
In #22839, several `babel` transformations were added to the multi pass build as a pre-requisite step to running closure compiler. With this, we no longer need most of the custom passes in `AmpPass.java`.
This PR cleans up all unnecessary code in `runner.jar`.
**Coming up:** Fix the removal of `assert` functions via `babel`, and remove `AmpPass.java` altogether.
Follow up to #22839 
Partial fix for #17120 and #22452
> 🏗🚮 Clean up custom code in `runner.jar` that has been replaced by babel transforms

- build-system/pr-check/utils.js
- build-system/tasks/pr-deploy-bot-utils.js
Adds HTML files from `examples` and `test/manual` to the dist package that Travis uploads
Replaces the URLs with the minified versions that live in the same dir (not cdn)
This is so that the pr-deploy-bot can grab all the stuff necessary to create a test site for a PR branch when you ask it to.
> 🏗 [pr-deploy-bot] Add html files to dist package that Travis uploads 

- extensions/amp-script/0.1/amp-script.js
- src/purifier.js
- test/unit/test-purifier.js
Partial for #23156.
- Allow removal of attributes early since `DOMPurify.isValidAttribute` expects non-null values.
- Add warning for sanitized form elements without `[sandbox=allow-forms]`.
- Remove special-case for `WHITELISTED_ATTRS` in `validateAttributeChange()` since I didn't realize those are already covered by the DOMPurify config.
> amp-script: Allow removal of attributes

- ads/google/a4a/utils.js
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Send experiment ID to Doubleclick/Adsense to validate FIE CSS reduction changes for https://github.com/ampproject/amphtml/issues/22418
See https://github.com/ampproject/amphtml/pull/22631/files for changes validated.
> 🖍 AMP FIE CSS cleanup Doubleclick/Adsense experiment

- build-system/tasks/presubmit-checks.js
- extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
- extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Updates SWG to use the new `prerenderSafe` param when fetching entitlements. This will allow the entitlements fetch to be sent before the view is active, but only for viewers on Google domains.
Fixes #23102.
> ✨ Updates SWG to use prerenderSafe fetch param

- ads/inabox/inabox-messaging-host.js
- ads/inabox/position-observer.js
- build-system/amp.extern.js
- src/inabox/inabox-viewport.js
- test/unit/inabox/test-position-observer.js
1. If `window.frameElement` is not available (e.g. because the ad IS the top window) use `getScrollingElement()`. This is mostly relevant for mobile apps.
2. Both the host script and the amp4ads runtime within friendly iframes will now share one position observer (sitting at the host window) instead of using a separate one for each. This prevents multiple scroll listeners, which can reduce performance.
3. Fix single pass build, which was actually broken before because of minification - the position observer would send back the minified `data` object while the inabox runtime would still try to read the unminified name (`data['viewportRect']`). The object will now be unminified in all cases.
> Various optimizations to AMP inabox friendly iframe position observer.

- build-system/tasks/e2e/index.js
- build-system/tasks/e2e/package.json
- build-system/tasks/visual-diff/package.json
There's a security vulnerability in one of our test deps that uses an outdated dependency version. It turns out this is because Renovate is configured to upgrade `devDependencies`, but leave `dependencies` alone (#23008). 
This PR moves all of the E2E and visual diff packages to `devDependencies` to enable automatic upgrades. It also adds some logging to the E2E tests (I found this useful while testing these changes.)
Soon, we should see version upgrade PRs for the packages used by our tests.
> 🏗 Enable package updates for E2E and visual diff tests

- extensions/amp-ad/0.1/amp-ad-custom.js
- extensions/amp-ad/0.1/test/validator-amp-ad.html
- extensions/amp-ad/0.1/test/validator-amp-ad.out
- extensions/amp-ad/validator-amp-ad.protoascii
Fixes https://github.com/ampproject/amphtml/issues/21314
> 🐛 Enforce amp-ad type=custom has an HTTPS data-url

- extensions/amp-addthis/0.1/addthis-utils/pixel.js
It appears (from our error logs) that the JSON requests occasionally return invalid JSON. Maybe something to do with ad blocking?
Fixes https://github.com/ampproject/amphtml/issues/19253.
/cc @taojing10 @dmvjs @pjcunnin @matthinegardner
> 🐛 Catch invalid json responses in amp-addthis

- src/service/url-expander/expander.js
- src/string.js
And introduce new trimStart helper in its place.
Closes #23432
> 🐛Remove string.trimStart() from expander

- src/service/layers-impl.js
This handles cleanup of layouts that have been removed from the DOM tree but are still stuck in the Layers tree. Custom elements didn't really have a problem, since they would eventually invoke `detachedCallback` which would notify layers. But native elements (which can also be added to the layers tree) don't have a similar callback without using a `MutationObserver`.
I chose to avoid a MO here because it would just be calling the `throttledCleanup` itself. Instead, we attempt cleanup whenever someone interacts with Layers. Because we're throttling, it shouldn't hurt performance that much.
Fixes https://github.com/ampproject/amphtml/issues/23433.
> 🐛 Cleanup detached layers periodically

- test/integration/test-amp-pixel.js
Related to #23439 
Adds a test that will hit the `trimStart` codepath.
> 🧪Add integration test for nested macro with leading space.

- .eslintrc
- build-system/eslint-rules/no-duplicate-name-typedef.js
- extensions/amp-access-laterpay/0.1/laterpay-impl.js
- extensions/amp-access-laterpay/0.2/laterpay-impl.js
- extensions/amp-story/0.1/logging.js
- extensions/amp-story/0.1/media-pool.js
- extensions/amp-story/0.1/pagination-buttons.js
- extensions/amp-story/1.0/logging.js
- extensions/amp-story/1.0/media-pool.js
- extensions/amp-story/1.0/pagination-buttons.js
Since we plan on hosting typedefs to externs, Duplicate names should be prevented to avoid collision and replacement complexity.
The hoisting of typedefs is part of the single pass effort, it will prevent us from obfuscating fields that were cast from JsonObject types. We will eventually unhoist the typefs at some point when we are confident will all the typing.
> Add no-duplicate-name-typedefs eslint rule

- build-system/build.conf.js
- build-system/global-configs/README.md
- build-system/global-configs/experiments-config.json
- build-system/tasks/presubmit-checks.js
Add an expiration time (Unix timestamp in milliseconds) to experiments tracked in `experiments-config.json`. Build will throw an error if expiration timestamp is missing, or if expiration time has passed.
cc @zhouyx for review :)
> ✨ Add expiration time to experiments

- test/unit/test-form.js
This change migrates the test to use the preferred `createElement` and
`setAttribute` to set up test elements.
Test elements for `isFieldDefault` were originally created with
`insertAdjacentHTML` to ensure their `defaultValue`(*) properties are
generated correctly. It turns out `setAttribute` actually modifies the
element's HTML definition, and thus could update the `defaultValue`
property.
\* The `defaultValue` property returns "the default value as originally
specified in the HTML that created this object."
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#Properties
Follow-up for https://github.com/ampproject/amphtml/pull/22541#discussion_r291228753, related to #22534.
/cc @GoTcWang, @cvializ thanks!
> ✅ TEST: createElement instead of insertAdjacentHTML

- build-system/tasks/runtime-test/runtime-test-base.js
- extensions/amp-analytics/0.1/vendors.js
Update to https://github.com/ampproject/amphtml/pull/23388
The control flow for the `--coverage` flag overwrites existing babel plugins, specifically the `minify-replace` plugin that is used to define experiment constants. This caused `--coverage` tests to fail.
This PR changes the `coverage` flow so that it doesn't overwrite existing babel plugins.
> 🐛 Don't overwrite existing babel plugins in unit test --coverage flag

- extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
- extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
- src/auto-lightbox.js
- src/format.js
- src/purifier.js
- src/sanitation.js
`amp-lightbox-gallery` is not allowed on `amp4email`, which makes the loading of this extension unnecessary and could lead to bugs.
b/136742391 for internal tracking.
> 🗑 Disable auto-lightbox on formats other than `amp/⚡`

- build-system/pr-check/dist-bundle-size.js
- build-system/pr-check/utils.js
- build-system/tasks/pr-deploy-bot-utils.js
This is so that the pr-deploy bot doesn't let someone deploy a PR branch before the bits are ready.
> 🏗 [pr-deploy-bot] Send http post to amp-pr-deploy-bot when dist finishes on Travis

- extensions/amp-subscriptions-google/OWNERS.yaml
This PR just adds me to the OWNERS file for the SwG extension
> 🏗 Adds me to OWNERS file for `amp-subscriptions-google`

- build-system/pr-check/build.js
- build-system/pr-check/checks.js
- build-system/pr-check/dist-bundle-size.js
- build-system/pr-check/utils.js
- build-system/pr-check/validator-tests.js
- build-system/tasks/pr-check.js
There have been a few instances in the past where a PR branch wasn't properly forked from `master`, and resulted in inconsistent test failures during PR checks on Travis. For example:
**Branches that weren't forked:**
- https://travis-ci.org/ampproject/amphtml/jobs/553527341#L345
- https://travis-ci.org/ampproject/amphtml/jobs/562725155#L344
**Inconsistent test failures:**
- https://travis-ci.org/ampproject/amphtml/jobs/562725156#L344
This PR adds a mechanism to detect and report cases like this instead of silently continuing the PR build.
> 🏗 Add a check to make sure the PR branch was properly forked from `master`

- extensions/amp-iframe/0.1/amp-iframe.js
- extensions/amp-iframe/0.1/test/test-amp-iframe.js
- extensions/amp-iframe/0.1/test/validator-amp-iframe.html
- extensions/amp-iframe/0.1/test/validator-amp-iframe.out
- extensions/amp-iframe/validator-amp-iframe.protoascii
Closes #23478 
- Propagates the `tabindex` attribute to the internal iframe on `amp-iframe`
- Adds tests and validator changes
> 🐛 Propagate `tabindex` on amp-iframe

- build-system/compile/single-pass.js
- build-system/tasks/build.js
- build-system/tasks/dist.js
- build-system/tasks/helpers.js
- build-system/tasks/presubmit-checks.js
This PR adds informative progress indicators for `build` and `dist` on Travis. The goal is to understand why the running time of `gulp dist` on Travis has started fluctuating so much of late. See https://github.com/ampproject/amphtml/issues/23484#issue-471860642.
Partial fix for #23484
> 🏗 Add progress indicators for `build` and `dist` on Travis

- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/test/test-variable-service.js
- extensions/amp-story/1.0/variable-service.js
When an ad is displayed, the progress variable is set to 1 because the ad is at the end of the DOM tree, after the amp-story-pages. And since `progress = pageIndex / totalPages`, the variable is set to 1, even if the ad is shown in the middle of the story.
This PR makes it so that the progress is unchanged whenever an ad is shown.
Also in this PR:
* Consolidate `onMutedStateChange` & `onAdvancementModeStateChange` methods from variable-service
> 🐛 Don't update progress variable when ad is shown

- build-system/app.js
- examples/bfcache/analytics-report-when.html
- examples/bfcache/no-unload.html
- extensions/amp-analytics/0.1/events.js
- extensions/amp-analytics/0.1/test/test-events.js
This is part of the stateful AMP effort. The first step is to get out of the browser's way when it caches documents in the back/forward cache. amp-analytics was adding an `unload` listener if the document includes a visibility spec with `"reportWhen": "documentExit"`, but if `pagehide` is supported then `unload` is not needed.  `unload` listeners cause browsers to not cache pages in the bfcache on navigation.
Related to #23527 
/to @cathyxz @sparhami 
/cc @nainar
> Add bfcache test examples and remove unload listener unless pagehide is unsupported

- build-system/build.conf.js
https://github.com/ampproject/amphtml/pull/22146 refactored `build.conf.js` and accidentally removed the `minify-replace` plugin. This PR adds it back.
> 🐛 Regression: add back babel replace plugin

- extensions/amp-iframe/validator-amp-iframe.protoascii
The C++ textproto parser check-fails on this line (introduced in #23482); this 
change fixes that. OTOH, `gulp validator` seems to be happy both before and
after this change, so I think it's safe.
> Double-escape regex backslash for C++ textproto.

- ads/google/a4a/utils.js
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- src/friendly-iframe-embed.js
- src/service/extensions-impl.js
Rather than using the experiment as gate, this PR changes to use the experiment branch to match what ads uses to send the experiment IDs to the server.
> Use experiment branch to gate fie-css-cleanup

- build-system/tasks/visual-diff/index.js
- test/visual-diff/visual-tests
A4A has a few visual tests where content is shown in an iframe, which is not visible by default since the content is not in the parent DOM when uploaded. As a workaround, we pull the iframe DOM out to the parent DOM (see examples/visual-tests/amp-ad/amp-ad.js) in order to make iframe entirely visible.
In these scenarios, we do not need base cases executed, and this PR proposes to add a flag not to run them.
> Allow not running visual-diff base test

- extensions/amp-consent/0.1/amp-consent.css
- test/manual/diy-consent.html
closes #22945 
Today I learned, iOS does not like fixed containers with a scrollable iframe. [Example 1](https://davidwalsh.name/scroll-iframes-ios), [Example 2](https://github.com/ampproject/amphtml/issues/7400). This, this adds the necessary overflow to allow the parent div to be scrollable 😄 
**Note:** This requires the CMP to declare a height on their `html` element in the inner Iframe. I couldn't get it working another way 😢 
<details><summary>Click Me</summary>
</details>
<details><summary>Click Me</summary>
</details>
<details><summary>Click Me</summary>
</details>
<details><summary>Click Me</summary>
</details>
<details><summary>Click Me</summary>
</details>
> amp-consent CMP: Fixed CMP frame not being scrollable on iOS

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
With this change, 5% of DoubleClick ad slot requests will contain the flexible ad request params ('msz' and 'psz'), enabling flexible creatives on those slots.
> Ramp FlexAdSlot params to 5%.

- validator/build.py
- validator/package.json
- validator/yarn.lock
Closure compiler binary path changes, so this involves a small build.py
change as well.
> Update closure and jasmine dependencies for AMPHTML validator.

- src/experiments.js
This expected error report is not really actionable by us so we can avoid reporting it (or forwarding it to the viewer) and simply warn.
> Failing to retrieve experiments should be a warning

- extensions/amp-selector/0.1/amp-selector.js
- extensions/amp-selector/0.1/test/test-amp-selector.js
- Have an `<amp-selector>` component inside a form
- Change the value of the `<amp-selector>` by using the `selectUp` or `selectDown` actions.
- _Result_: the `<amp-selector>`'s value is not submitted.
The inner `<input>` components are not being recreated when using the `selectUp` or `selectDown` actions.
Added missing calls to `setInputs_()`.
Bonus: added missing call to `fireSelectEvent_()`.
/cc @nainar and @cvializ since you created & reviewed #13439
> 🐛 Fix amp-selector in form not submitted when using selectUp/selectDown actions

- src/mode.js
- test/unit/test-mode.js
Add support for all AMP HTML (amp, amp4ads, actions, amp4email) formats during in browser development mode. The corresponding validator engine changes to support this will roll up. If this or the validator changes are not synced via the same release it is fine as the default behavior is to validate against the `AMP` format.
> In browser validation support for other AMP HTML formats

- extensions/amp-link-rewriter/0.1/scope.js
Classic forEach on a `NodeList` error. We could save ourselves a lot of trouble if we added a conformance check for this.
> 🐛 Fix forEach is not a function error

- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
Related to #21234
`getA4AMetaTags` returns a `NodeList` and not an array, and calling `forEach` on it breaks in IE11.
https://github.com/ampproject/amphtml/blob/1d5d13943b0fdf941b6dc63c0941cf7953810589/extensions/amp-story-auto-ads/0.1/utils.js#L44-L51
> 🐛 Fix forEach on NodeList

- extensions/amp-story-auto-ads/0.1/utils.js
Addresses https://github.com/ampproject/amphtml/pull/23577#pullrequestreview-268064478
See https://travis-ci.org/ampproject/amphtml/jobs/565201762#L383
```js
...Type checking failed:
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js:986: ERROR - [JSC_TYPE_MISMATCH] actual parameter 1 of iterateCursor$$module$src$dom does not match formal parameter
found   : *
required: IArrayLike<?>
iterateCursor(tags, tag => {
^^^^
```
> 🐛 Fix merge conflict between #23577 and #23559

- extensions/amp-analytics/0.1/amp-analytics.js
- extensions/amp-analytics/0.1/config.js
- extensions/amp-analytics/0.1/cookie-writer.js
- extensions/amp-analytics/0.1/linker-manager.js
- extensions/amp-analytics/0.1/requests.js
- extensions/amp-analytics/0.1/test/test-linker-manager.js
- extensions/amp-analytics/0.1/test/test-variables.js
- extensions/amp-analytics/0.1/variables.js
Removes some code duplication and a race? where different macros would be available depending on when getMacros would be called (this may still exist for resource timing which was not moved).
@zhouyx please let me know if there is anything I am missing in this PR. Seems like there is already pretty good test coverage.
> ♻️Move element dependent macros to `getMacros`

- extensions/amp-form/0.1/form-validators.js
- extensions/amp-form/0.1/test/test-form-validators.js
Closes #12717 
- Assigns a unique ID to validation messages when necessary (needed for an a11y attr)
- Sets the `aria-describedby` attribute on the invalid form element to its corresponding validation message
- Adds tests for the changes
@jamesshannon This should do what was described in the issue but I am not sure if it fixes the issue and actually "reads validation messages politely" so it would be great to test with Voice Over and let me know if this is the desired behavior.
> ♿ Read validation messages politely

- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/flexible-ad-slot-utils.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-flexible-ad-slot-utils.js
Flexible ad slots enable slots to expand beyond their initially set width. When this occurs, it may be required to center the creative. This helps maintain a symmetric look, and prevents the creative from exiting the viewport.
> Ensure that expanded slots are correctly centered.

- build-system/tasks/dep-check.js
The `gulp dep-check` task has a few problems when it detects a dependency error:
- It repeatedly prints all dependency rules for every error, which makes the output extremely verbose and unreadable
- It does not suggest a fix for valid dependencies
- It doesn't cleanly exit and causes `gulp` to [complain](https://travis-ci.org/ampproject/amphtml/jobs/565138133#L664) about async completion
This PR fixes all the above problems.
**Before:**
**After:**
> 🏗 Synchronize `gulp dep-check` and make error output more readable

- extensions/amp-facebook/facebook-loader.js
Facebook logo changed recently to a circular version with a new shade of blue (see www.facebookbrand.com ) - this updates the SVG used in the new AMP loaders to reflect those changes.
> 🖍 Update new loader with current Facebook logo.

- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-script/0.1/amp-script.js
- src/purifier.js
- src/sanitation.js
- src/sanitizer.js
- test/unit/test-purifier.js
- test/unit/test-sanitizer.js
Enforce the AMP component whitelist at runtime as well.
> Sanitize non-whitelisted AMP elements in AMP4EMAIL

- .travis.yml
Set back to blocking once Chrome / ChromeDriver versioning issue is fixed.
> 🏗 Set Travis e2e job as non blocking

- extensions/amp-carousel/0.1/scrollable-carousel.js
- extensions/amp-carousel/0.1/slidescroll.js
- extensions/amp-carousel/0.1/test/test-scrollable-carousel.js
- extensions/amp-carousel/0.1/test/test-slidescroll.js
- extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
- extensions/amp-lightbox/0.1/amp-lightbox.js
- extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
- extensions/amp-story/1.0/amp-story-page-attachment.js
- src/base-element.js
- src/service/owners-impl.js
- src/service/resources-impl.js
This PR moves updateInViewport to owners-impl.
1. Some unit tests have been disabled for other reasons so the fix cannot be validated.
2. There are references to methods in resources-impl from building-an-amp-extension.md. I think it would be better to update it once we finish rather than piece-by-piece.
> Move updateInViewport to from resource to owners service impl

- build-system/global-configs/experiments-config.json
- build-system/tasks/extension-helpers.js
- Add `gulp generate-vendor-configs` to experiments command so that vendor JSONs are generated during the experiment build
- Enable `--compile_vendor_configs` by default, so no need to add this flag anymore
> ✨ Update analytics vendor split experiments config

- ads/_config.js
This PR is intended for delete in the ad server list.
As we have finished providing the functions,
by delete ad.omks.valuecommerce.com in preconnect array.
Corporation name: ValueCommerce Co., Ltd.
> delete ad server in the preconnect list

- .travis.yml
- build-system/tasks/e2e/describes-e2e.js
- build-system/tasks/e2e/yarn.lock
Fixes bug where the browser was not running in headless mode even though you passed in the `--headless` flag.
This should fix the 2 failing e2e tests, so we should reenable the e2e job as blocking on Travis.
> 🏗 Fix e2e headless mode and make e2e job blocking again

- .eslintrc
- build-system/eslint-rules/no-unload-listener.js
- extensions/amp-analytics/0.1/events.js
- extensions/amp-viewer-integration/0.1/amp-viewer-integration.js
- src/service/performance-impl.js
Related to #23527 
This PR will trigger a linter warning if an `unload` listener is added. This will help prevent bfcache from becoming broken unintentionally.
> 🏗 Add lint rule for unload listener

- build-system/tasks/extension-helpers.js
Found the issue while debugging with a component that has sub folders. This would significantly ease my local development experience. 
This now includes all test folders, but I think that's fine because I don't expect files in test folders to be changed during manual testing. Thanks.
> 🐛Gulp watch: watch all sub folders

- extensions/amp-story/1.0/amp-story-system-layer.js
- extensions/amp-story/1.0/test/test-amp-story-system-layer.js
This ensures that STAMPs, even if embedded, always have a discoverable link to themselves.
> Turn the share button into a self-link for each STAMP

- test/unit/test-viewport.js
- testing/describes.js
Also introduced a helper method to automatically restore properties in `afterEach`: `sandbox.defineProperty(...)` 
closes #23689
> Fix a test isolation problem caused by the use of Object.defineProperty w/o restore.

- extensions/amp-sidebar/0.1/amp-sidebar.js
- extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
- src/modal.js
- Keep track of the opened state as a variable and not an attribute, so
it is updated immediately. This makes sure multiple open/close calls in
a row do not cause issues for the modal or history stacks.
Fixes #23572
>  🐛 Fix race condition when opening/closing sidebar.

- css/ampdoc.css
- extensions/amp-instagram/0.1/amp-instagram.js
- extensions/amp-instagram/0.1/test/test-amp-instagram.js
- test/integration/test-released.js
- Switches embed version from 9 to 12
- Updates top padding to new value (`54px`) and makes this actually work
- Switches image to load with intrinsic size and hidden overflow because that just works much better in practice.
> Update amp-instagram to new embed version and remove certain classes of jank

- extensions/amp-social-share/0.1/amp-social-share-config.js
- extensions/amp-social-share/0.1/amp-social-share.js
- extensions/amp-social-share/0.1/test/test-amp-social-share.js
- extensions/amp-social-share/amp-social-share.md
- Introduces the concept of an obsolete share button
- Renders those as `display:none`
- Marks gplus (RIP) as obsolete.
Fixes #21743
> Mark gplus share button as obsolete and don't render it.

- build-system/config.js
- extensions/amp-script/0.1/test/unit/test-amp-script.js
> 🐛 Fix unit test paths

- build-system/git.js
- build-system/pr-check/utils.js
AMP Travis builds use `origin/master` as the baseline while determining the list of files changed by a PR. This used to work back when our build matrix had a single stage, but it occasionally breaks when new commits have been merged to `master` while a multi-stage build is in progress.
After reaching out to Travis support, the recommended approach to determining the latest commit merged to `master` that is included in a Travis build is to run the following command, which returns the common ancestor of `origin/master` and the `HEAD` commit of the PR branch. See [this](https://travis-ci.community/t/origin-master-moving-forward-between-build-stages/4189/6) post.
```
git merge-base origin/master HEAD
```
This PR implements the recommended approach. For the most part, it is a no-op and causes …
> 🐛 Do not use `origin/master` during Travis builds

- examples/pwa/pwa.js
`appendChild(scriptElement)` no longer throws when the script failed to load, causing non-minimized pwa example to fail. This PR fixes that issue.
> Fix PWA example script

- extensions/amp-story/1.0/amp-story-info-dialog.css
> 🖍 Make both bottom corners of info dialog rounded

- extensions/amp-analytics/amp-video-analytics.md
- src/service/video-manager-impl.js
- src/video-interface.js
- test/manual/amp-ima-video.html
> Introduce video-ad-start/end event

- extensions/amp-story/1.0/_locales/en.js
- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/amp-story.css
- src/localized-strings.js
Optimizing the "play video" button displayed when a video fails to play:
- If the video errors, display an error message instead of the "play video" button
- Display the "play video" button when autoplay was not allowed
[Demo here](https://video-autoplay-6cd5a.firebaseapp.com/examples/s20/body-painting/index.html): enable "Battery saving mode", go on page 2, reload the story, and wait for the auto advance - you should see the "Play video" button.
Fixes #22473, #22820
> Story video failure play vs error message.

- src/amp.js
- src/chunk.js
- src/inabox/amp-inabox.js
- test/unit/test-chunk.js
This change got much bigger than planned. On top of a functional change there is one major refactoring: We now never schedule another execution until after the current one is done. This ensures that we don't over-schedule which effectively voids the point of multiple scheduling strategies. In a way this is a risky change, because previously we always ensured that we'd schedule an execution if we added a task. Now this relies on the state machine being correct.
Unskips the tests for long tasks.
Functional change: Avoids scheduling macro-tasks if the body is still hidden, because we want to get out of this state ASAP. Improves FCP with the experiment on by about 20%.
Related to #23618
> Overhaul Chunks implementation and avoid macro tasks before body is visible.

- extensions/amp-bind/0.1/bind-evaluator.js
- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-bind/0.1/test/integration/test-bind-impl.js
- extensions/amp-bind/0.1/test/test-bind-evaluator.js
- extensions/amp-bind/0.1/test/test-bind-expression.js
> amp-bind: Don't validate non-primitive expression results

- build-system/tasks/dev-dashboard-tests.js
- package.json
- yarn.lock
- Synchronizes `gulp` task exit to prevent the `Did you forget to signal async completion?` error
- Makes Travis logging silent when tests pass and concise when they fail
**Before (tests fail):**
```
[20:46:20] Using gulpfile ~/src/amphtml/gulpfile.js
[20:46:20] Starting 'dev-dashboard-tests'...
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․!․․․․․․․․․․․․․․․․․․
47 passing (473ms)
1 failing
1) devdash
Test helpers
parseHtmlChunk
returns firstElementChild:
AssertionError: expected 2 to equal 3
+ expected - actual
-2
+3
at Context.it (build-system/app-index/test/test-self.js:38:22)
at process.topLevelDomainCallback (domain.js:126:23)
[20:44:23] The following tasks did not complete: dev-dashboard-tests
[20:44:23] Did you forget to signal async completion?
```
**Before (tests pass):**
``` …
```
> 🏗 Synchronize exit and fix logging on Travis for dev dashboard tests

- build-system/compile/single-pass.js
- build-system/tasks/dep-check.js
- build-system/tasks/helpers.js
- build-system/tasks/karma.conf.js
This PR enables the `fast: true` option for `browserify`.
**Reference:** The "Advanced Options" section at https://github.com/browserify/browserify#usage
> 🏗 Speed up `browserify` while building the runtime and running tests

- extensions/amp-sidebar/amp-sidebar.md
- extensions/amp-sidebar/validator-amp-sidebar.protoascii
Closes #21895
Removes requirement for `amp-sidebar` to be a direct descendant of `body`.
> Relaxes requirement that amp-sidebar be a direct child of body

- test/unit/test-cid.js
Now that `getEntropy` will be a public method that will be exported, we can't reply on increasing the calling time to generate the random value. Set a seed instead. 
To unblock #23451
> ♻️ Cid-impl test improvement

- build-system/tasks/dist.js
- tools/experiments/experiments.html
This PR adds a version section to the AMP experiments page. From here on, http://cdn.ampproject.org/experiments.html will show the current version, with a link to the GitHub release for that version.
Fixes #23544
> 🏗✨ Add a `Version` section to the experiments page that links to the GitHub release

- extensions/amp-story/1.0/amp-story.css
From @hongwei1990:
> breakpoint 1: 320≤  viewport width < 1024，menu width = 75% of the viewport. Max width = 360pt
> breakpoint 2: viewport width ≥ 1024，menu width = 25% of the viewport. Max width = 600pt
Here we use `[desktop]` for the 1024px breakpoint.
The `width` CSS property is not specified so publishers can use it to specify it to anything in between the set `min-width` and `max-width`. It will default to the `min-width`.
> Updating default story sidebar width.

- 3p/integration.js
- test/unit/3p/test-3p-frame.js
Remove the duplicative tests, and move the tests into unit folder.
> ✅Repurpose test-3p-frame.js as a unit test

- builtins/amp-img.js
- extensions/amp-bind/amp-bind.md
- test/unit/test-amp-img.js
Fixes #10207. 
- Mutating [src] is a no-op if [srcset] already exists, so remove the latter.
- Originally fixed in #11493 but regressed as part of the "native srcset" feature in #16404.
/to @cathyxz
> amp-img: Remove [srcset] when [src] is mutated

- extensions/amp-selector/0.1/amp-selector.js
- extensions/amp-selector/0.1/test/test-amp-selector.js
> 🐛Do not select hidden elements in amp-selector

- build-system/tasks/visual-diff/yarn.lock
The visual tests use v0.4.0 of `@percy/puppeteer`, which has dependencies with known security vulnerabilities. 
https://github.com/ampproject/amphtml/blob/cfc17637d064b5d747d9c810f0a39de8f6c9b98c/build-system/tasks/visual-diff/package.json#L6-L9
v1.0.0 of `@percy/puppeteer` fixes these vulnerabilities, but we can't upgrade because of breaking  API changes. See #23462.
Until then, this PR manually upgrades the offending dependencies to safe versions. (Future task: Upgrade to v1.0.0 of `@percy/puppeteer`.)
> 🏗🐛Manually update `build-system/tasks/visual-diff/yarn.lock` to address security vulnerabilities

- build-system/eslint-rules/no-duplicate-name-typedef.js
#23472 added the `no-duplicate-name-typedef` rule, which keeps track of typedefs in a global map during `gulp lint`. The rule breaks eslint IDE plugins that do on-the-fly linting because the global map isn't cleared between runs.
For example, closing and reopening `tools/experiments/experiments.js` in VS code results in this bogus error:
This PR disables the rule unless `gulp lint` is being run.
Follow up to #23472
> 🏗🐛 Disable `no-duplicate-name-typedef` rule during on-the-fly IDE linting

- build-system/build.conf.js
- build-system/dep-check-config.js
- examples/lots-of-images.amp.html
- src/base-element.js
- src/custom-element.js
- src/friendly-iframe-embed.js
- src/polyfills.js
- src/polyfills/domtokenlist.js
- src/service.js
- src/service/ampdoc-impl.js
- test/unit/test-polyfill-domtokenlist-toggle.js
- Removes unnecessary `hasAttributes` call from `propagateAttributes`
- Bundles several `classList.add` operations into one.
- Add special case for AMP Doc retrieval that is faster if no shadow doc was ever added which is common.
- Makes hot `getTopWindow` function faster by ensuring the property that is rarely defined is at least known.
> Various micro optimizations of the component boot flow.

- extensions/amp-bind/0.1/bind-evaluator.js
- extensions/amp-bind/0.1/bind-expression.js
- extensions/amp-bind/0.1/bind-macro.js
- extensions/amp-bind/0.1/test/test-bind-evaluator.js
- extensions/amp-bind/amp-bind.md
Fixes #20167.
Useful for referencing amp-state with non-alphanumeric in `id`, e.g.
```html
<amp-state id="x-1">...</amp-state>
<p [text]="global['x-1']"></p>
```
Also some unrelated documentation tweaks in amp-bind.md.
> amp-bind: Add "global" reference

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
This serves loaders to all of canary and 1% of prod traffic. The next steps will be a 10%, 50% and then 100% roll out if everything looks good.
> Set the new loaders experiment to 1% of traffic.

- extensions/amp-story/1.0/amp-story-bookend.css
- extensions/amp-story/1.0/amp-story-draggable-drawer-header.css
- extensions/amp-story/1.0/amp-story-draggable-drawer.css
- extensions/amp-story/1.0/amp-story-draggable-drawer.js
- extensions/amp-story/1.0/amp-story-page-attachment.js
- extensions/amp-story/1.0/amp-story-system-layer.css
- extensions/amp-story/1.0/amp-story-vertical.css
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/bookend/amp-story-bookend.js
- extensions/amp-story/1.0/test/test-amp-story-bookend.js
- extensions/amp-story/1.0/test/test-amp-story.js
Re-using the new `draggable-drawer` abstract class extracted from page attachments to enable swiping down to close the bookend.
Animations + scrolling logic is now handled by the `draggable-drawer` and removed from the bookend implementation.
- Mobile: swipe down interactions + small handle on top of the bookend
- Desktop: no-op
[Demo here](http://draggable-bookend.firebaseapp.com/examples/s20/body-painting/index.html)
Part 2/2
Fixes #13833
> Swipe down to close the bookend.

- build-system/compile/compile.js
This PR disables closure compiler parallelism during local development in order to prevent this error:
```js
[14:10:14] 'dist' errored after 1.83 min
[14:10:14] Error in plugin 'gulp-google-closure-compiler'
Error parsing json encoded files
```
**Note:** The error stems from Nailgun (see #21939), which significantly speeds up `gulp dist` by allowing for the reuse of a single closure compiler java process across multiple compilation invocations. Reducing parallelism to 1 will still retain the benefit of not having to restart the JVM multiple times, while avoiding the race that causes the `Error parsing json encoded files` error.
Fixes #23793
Fixes #23238
> 🐛 Disable closure compiler parallelism during local development

- build-system/build.conf.js
- build-system/global-configs/experiments-config.json
Current experimentA config is now "expired".
> Move expiration date back to 2020

- ads/nativeroll.js
- examples/ads.amp.html
@lannka 
@zhouyx
Help with merge this plz.
> fixed nativeroll's player collapse & resize bug

- build-system/compile/closure-compile.js
- build-system/tasks/check-types.js
- build-system/tasks/dist.js
- build-system/tasks/nailgun.js
There appear to be some development environments for which using nailgun to invoke closure compiler causes compilation to fail. This PR provides developers with a way to opt out of nailgun by using the `--disable_nailgun` flag with `gulp dist` or `gulp check-types`.
Mitigates #23801
> 🏗 Add a way to opt out of Nailgun during `dist` and `check-types`

- extensions/amp-analytics/0.1/transport.js
Duplicates #22325
Fix link to the amp-iframe origin policy.
Without the fix - https://i.imgur.com/Wv7IqgR.png
> 🐛 Fix link to the amp-iframe origin policy

- extensions/amp-mustache/amp-mustache.md
The amp-mustache documentation contains unnecessary code block quotes that normally will be rendered, but should not.
As seen on github the quotes after the `{{#section}}` block are shown:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-mustache/amp-mustache.md#syntax
On amp.dev the quotes are currently not shown, but this will change as we are about to change the preprocessing of the imported markdown files from amphtml.
So please apply this PR to remove the unnecessary quotes.
> 📖Fix invalid and unnecessary code block quotes in docs

- build-system/compile/compile.js
- build-system/conformance-config.textproto
- extensions/amp-date-picker/0.1/date-picker-common.js
- extensions/amp-date-picker/0.1/react-utils.js
- extensions/amp-date-picker/0.1/single-date-picker.js
- extensions/amp-date-picker/0.1/wrappers/maximum-nights.js
Fixes #23429
It turns out the solution was to make Closure Compiler stop checking the `extends` and to use ES5 class syntax with manual prototype chaining. Not ideal, but at least it's an established pattern that works.
> Fix amp-date-picker closure compiler warnings

- extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
- extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
- extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
> ✨Do not require amp-autocomplete to be a child of a form

- extensions/amp-story/1.0/amp-story.css
Really couldn't find a responsive font-size that works across all experiences (desktop - tablet - mobile), so I just increased the size to match the other UI we have (especially the sound UI messages).
If we want to customize the font size further, I think we should have different media query breakpoints, and target each experience differently: desktop three panels vs full bleed are different, tablet vs mobile are different, etc.
Fixes #22804
> Increase play & error message font size.

- extensions/amp-carousel/0.2/amp-carousel.js
- extensions/amp-carousel/validator-amp-carousel.protoascii
- Support initial (non-bound) value for `slide` (for #11734)
- Fix `toggleAutoplay` when no argument is specified
- Stop propagation on touchmove like carousel 0.1 so it does not cause a viewer swipe
> 🐛✨`<amp-carousel>` 0.2 minor fixes

- examples/amp-imgur.amp.html
- extensions/amp-imgur/0.1/amp-imgur.js
- extensions/amp-imgur/0.1/test/test-amp-imgur.js
- extensions/amp-imgur/OWNERS.yaml
Closes #23816
- Fixes an issue that caused slashes in `amp-imgur` IDs to be URIEncoded
- Added a test and an example to take into account the `a/` ID format
- Added myself as an owner since `techhtml` hasn't contributed in a while
- Clean up and renaming for some variables copied from `amp-instagram`
> 🐛Fixes `amp-imgur` issue with new id format

- build-system/tasks/karma.conf.js
Due to the addition of more tests and a larger number of babel transforms, the Karma-based tests on Sauce Labs have started taking longer than 10 minutes to run, resulting in the "no activity after 10 minutes" error due to the absence of keepalives in `karma-sauce-launcher`.
This PR increases the timeout to 15 minutes to give tests more time to execute.
> 🏗Increase Karma timeout for Sauce Labs tests

- extensions/amp-next-page/amp-next-page.md
Building amp.dev is currently [blocked](https://travis-ci.org/ampproject/amp.dev/jobs/569698147#L1329) by a syntax error in the `amp-next-page` docs which is fixed by this PR.
> 📖 Add missing quote to opening tip tag

- src/custom-element.js
- test/unit/test-custom-element.js
Handles resize events by setting intrinsic layout's img src to ''. This
does not include validator updates to support the intrinsic sizer.
Fixes #17686
> ✨Make "layout=intrinsic" compatible with SSR

- validator/validator-main.protoascii
These attributes help to get some of the nice features of AMP (layout
stability, async loading) when scripts are not enabled for browsers that support them.
We might consider allowing `<img intrinsicsize="blah x blah" loading="lazy">`
as an alternative to `<amp-img>` in the future if polyfilling the attributes is
feasible.
Closes #22802
> Support some new img attributes for those within noscript.

- extensions/amp-analytics/0.1/linker-manager.js
- extensions/amp-analytics/0.1/test/test-linker-manager.js
- test/manual/amp-analytics/analytics-linker.html
Closes #22787
#23792 introduced the generic fix. Where no anchor mutator will be applied with same href. 
Revert the previous fix from #22753. 
Also I couldn't find a linker example page. Added one for future use.
> Revert the analytics linker hack to check href

- extensions/amp-story/amp-story.md
- Fixes #23645 by deleting the section on posters.  This section was largely duplicative of the documentation of the `poster-portrait-src`, `poster-landscape-src`, and `poster-square-src` attributes.
- Fixes #23646 by moving the overview section to the top.
- Fixes #23643 and fixes #23649 by updating the deletion date for 0.1, as well as calling out the fact that 0.1 is invalid AMP and will be deleted in the Version Notes table.
- Fixes #23639 by deleting the "new bookend capabilities" section, as this information is duplicative of what's already present in the bookend documentation.
- Fixes #23647 by removing all instances of "new" referring to a feature being new (i.e. keeping instances of "new" that refer to other things, like live-story documentation on adding new pages to a story …
> 📖 Clean up outdated documentation in amp-story.md

- src/chunk.js
- test/unit/test-chunk.js
- Schedules task after, not just before making body visible. Bug introduxed in #23750
- Measures total time spend in task including immediate micro tasks invoked from it.
- Does not schedule a tasks if last invocation was a while ago, but the queue unwound in between.
Related to #23618
> Correctness fixes for chunk queue

- build-system/check-package-manager.js
New laptops that don't have the recommended python version for AMP development (v2.7) can return mysterious errors. See https://github.com/ampproject/amphtml/issues/23801#issue-478170003
This PR prints a warning when a python version other than v2.7 is detected.
Addresses https://github.com/ampproject/amphtml/issues/23801#issuecomment-519743182
> 🏗 Add check for python v2.7

- extensions/amp-story/1.0/amp-story-hint.css
Closes #18664
* For the first page hint, the gradient's direction was going the opposite way.
* For the "tap instead of swiping" hint, the dashed border was on the wrong side due to the svg not working correctly.
> Fix first page hint layer for RTL

- src/custom-element.js
- test/unit/test-custom-element.js
This was a mishandling while doing the refactoring. This PR fixes https://github.com/ampproject/amphtml/issues/23858 
Also needed to be cherry picked to canary. Prod is not affected.
> Fix the regression caused by resources->owners refactoring

- extensions/amp-story/1.0/amp-story-bookend.css
- extensions/amp-story/1.0/amp-story-consent.css
- extensions/amp-story/1.0/amp-story-draggable-drawer-header.css
- extensions/amp-story/1.0/amp-story-info-dialog.css
- extensions/amp-story/1.0/amp-story-shadow-reset.css
- extensions/amp-story/1.0/amp-story-share-menu.css
- extensions/amp-story/1.0/amp-story-viewport-warning-layer.css
Here's what we learned today: https://developers.google.com/web/fundamentals/web-components/shadowdom#reset
So here's a reset for our shadow trees that inherited from other properties :)
I tested most properties that can be inherited and it turns out you were able to do pretty fun stuff to mess up with our UI, despite the shadow DOM:
Fixes #23663
> CSS reset for shadow trees.

- extensions/amp-story/1.0/test/validator-amp-story-video-controls.html
- extensions/amp-story/1.0/test/validator-amp-story-video-controls.out
- extensions/amp-video/validator-amp-video.protoascii
Allow regular AMPHTML validation rules on `amp-video` within `amp-story-page-attachments`.
> Allow regular AMPHTML validation rules on amp-video within page-attachments.

- src/service/cache-cid-api.js
- src/service/viewer-impl.js
Fixes #20120. 
There are two sources of timeout in that bug: cache-cid-api.js and history-impl.js. This PR makes the former an expected dev error. 
I think the latter is due to viewer messaging init timeout but I'm not 100% sure, so changed the message for that `timeoutPromise` to see what happens.
> Make cache cid timeout an expected error

- extensions/amp-date-display/0.1/test/validator-amp-date-display.html
- extensions/amp-date-display/0.1/test/validator-amp-date-display.out
- extensions/amp-date-display/validator-amp-date-display.protoascii
Closes https://github.com/ampproject/amphtml/issues/23731. 
Context: `amp-date-display` makes use of `<template>`s. It should therefore allow the `template` attribute to reference templates without causing template nesting when used inside of `<amp-list>`.
> Update amp-date-display validation to allow template attribute

- build-system/dep-check-config.js
- extensions/amp-facebook-comments/0.1/amp-facebook-comments.js
- extensions/amp-facebook-page/0.1/amp-facebook-page.js
- extensions/amp-facebook/0.1/amp-facebook.js
- extensions/amp-facebook/0.1/facebook-loader.js
This PR moves `facebook-loader.js` into its component directory to fix these (currently silenced) type checking errors, which stem from the fact that extension code is expected to live in a directory of the format `amp-foo/0.x/`. See https://github.com/ampproject/amphtml/pull/23084#discussion_r299597394 for more details.
```js
Type checking failed:
extensions/amp-facebook-comments/0.1/amp-facebook-comments.js:17: ERROR - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "../../amp-facebook/facebook-loader"
import {createLoaderLogo} from '../../amp-facebook/facebook-loader';
^
extensions/amp-facebook-page/0.1/amp-facebook-page.js:17: ERROR - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "../../amp-facebook/facebook-loader"
import {createLoaderLogo} from …
```
> 🐛 Move `facebook-loader.js` into its component directory

- src/service/platform-impl.js
Fixes #23882
Uses the win object when calling `matchMedia().matches` to make sure the right context is being passed.
> Fix illegal invocation

- extensions/amp-action-macro/amp-action-macro.md
The Link to the `amp-action-macro` examples was wrong. This PR fixes it..
> 📖 Fix link to amp-action-macro example

- src/service/standard-actions-impl.js
- test/unit/test-standard-actions.js
Fixes #22435
Add a check in the `handleToggleClass` method to prevent toggling when class name is internal to amp (prefixed by 'i-amphtml-', '-amp-', or 'amp-').
> 🐛 Add check to disable toggling for amp internal classes

- build-system/compile/compile.js
- build-system/compile/single-pass.js
#23759 upgraded closure compiler to v20190729. With this, it's time to clean up a few flags:
- `--only_closure_dependencies` has been [deprecated](https://github.com/google/closure-compiler/blob/maven-v20190729/src/com/google/javascript/jscomp/CommandLineRunner.java#L610-L616) in favor of `--dependency_mode=PRUNE`
- `--module` has been [replaced](https://github.com/google/closure-compiler/blob/maven-v20190729/src/com/google/javascript/jscomp/CommandLineRunner.java#L274-L286) by `--chunk`
- `--module_wrapper` has been [replaced](https://github.com/google/closure-compiler/blob/maven-v20190729/src/com/google/javascript/jscomp/CommandLineRunner.java#L365-L375) by `--chunk_wrapper`
- `--module_output_path_prefix` has been [replaced](https://github.com/google/closure-compiler/blob/maven-v2019072 …
> 🏗 Clean up deprecated closure compiler flags

- extensions/amp-gfycat/amp-gfycat.md
Rawgit (https://rawgit.com) is [shutting down](https://twitter.com/rawgit/status/1049360165030567937). This PR replaces the one use of rawgit in the repo with an equivalent service called githack (https://raw.githack.com).
**New url:** https://raw.githack.com/ampproject/amphtml/master/examples/gfycat.amp.html
> 🐛 Remove uses of rawgit

- build-system/amp.extern.js
- src/custom-element.js
Enables stronger type checking in custom-element.js by removing `@suppress` and `@this` annotations. I think these were originally needed on an older version of Closure compiler.
Fixed a few type errors that this caught and verified that this would've caught #23858.
/to @lannka @powerivq
> Remove @suppress in custom-element.js

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
- src/inabox/amp-inabox.js
- tools/experiments/experiments.js
Reverts ampproject/amphtml#23819
lightbox ads is broken. See #23946 as a fix. But obviously we are lacking e2e/visual tests for this. Let's unlaunch first.
> Revert "Fully launch inabox-css-cleanup"

- css/ampdoc.css
- css/ampshared.css
This broke light box ads.
Problem get surfaced after the inabox-css-cleanup launch. (#23819  Not in canary yet. It's in the recent cut https://github.com/ampproject/amphtml/releases/tag/untagged-3e6b3211ec8f7e5ab371)
> [hidden] should be in shared CSS

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
Reverts ampproject/amphtml#23780
This has a race condition where the default placeholder may not be removed with amp-img and potentially other components.
Fixes #23964
> Revert "Set the new loaders experiment to 1% of traffic."

- examples/amphtml-ads/lightbox-ad.a4a.html
It's obsolete: https://github.com/ampproject/amphtml/issues/8334
> Remove amp-ad-banner in lightbox ad example

- extensions/amp-selector/0.1/amp-selector.js
- extensions/amp-selector/0.1/test-e2e/test-amp-selector-tabs.js
- test/fixtures/e2e/amp-selector/amp-selector-tabs.html
Closes #23820 , Related to https://github.com/ampproject/amphtml/pull/23688#pullrequestreview-270935715 in #23688
- Adds e2e tests that would've caught the issue of children not rendering correctly when toggling with `amp-selector`
> ✅ Adds e2e tests for amp-selector

- testing/fake-dom.js
Currently, fake-dom overrides `document.hidden`, but not `document.visibilityState`. Since the `document.visibilityState` comes from the `DOMImplementation`, they often get out-of-sync in tests which creates test uncertainty.
> Testing: synchronize hidden and visibilityState in fake-dom

- build-system/tasks/vendor-configs.js
Add the test vendor JSON `_fake_.json` into the final build because some integration tests rely on this. Specifically `test/integration/test-amp-analytics.js`
cc @zhouyx for review :)
> ⏪  Add test vendor json to compilation

- extensions/amp-lightbox/0.1/test-e2e/test-amp-lightbox.js
Seems we already have the tests. Just need to enable them.
/cc @zombifier
> Enable e2e tests for amp-lightbox for AMPHTML ads.

- 3p/integration.js
- ads/_config.js
- ads/yahoonativeads.js
- ads/yahoonativeads.md
- examples/ads.amp.html
- extensions/amp-ad/amp-ad.md
Adds support to render Yahoo Native Ad units using the `amp-embed` tag. 
Sample Rendering
> ✨adds support for amp-embed type=yahoonativeads

- extensions/amp-story/1.0/amp-story-shadow-reset.css
- extensions/amp-story/1.0/amp-story.css
The bug this PR is fixing:
The `amp-consent` prompt on `amp-story` does not get hidden when you accept or reject the consent prompt, even though `amp-consent` did not change any of their code.
What actually happens:
CSS `visibility`, unlike `display`, is inherited.
If you add `display: none;` to an element, adding `display: block;` to one of its descendants will have no effect. But the equivalent with visibility will show the descendant.
Because inheritable CSS properties "pierce" the Shadow DOM, `visibility: hidden;` was applied to the consent UI, and sending #23876 broke this behavior.
> Make stories shadow trees inherit from the visibility property.

- build-system/pr-check/utils.js
- build-system/tasks/pr-deploy-bot-utils.js
Fixes `pr deploy bot` bug where urls in html files were being replaced with `/dist/v0.js` instead of `https://storage.googleapis.com/amp-test-website-1/amp_dist_<travisbuildnumber>/dist/v0.js`
> 🏗 [pr deploy] Replace url in html files with storage api host name

- extensions/amp-loader/0.1/amp-loader.css
- extensions/amp-loader/0.1/amp-loader.js
- src/loader.js
Instead, create the background as part of the as a part of the loader
element itself. This makes sure the background is removed when the
loader is removed.
This avoids an issue where the placeholder appears on top of an
`<amp-img>` if the image finishes downloading before the loaders code
runs.
Closes #23964
> 🐛Change loader code to no longer add a default placeholder.

- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-bind/0.1/test/integration/test-bind-impl.js
Fixes #17969.
- Use a queue to store history replace/push. 
- Debounce queue flushes on replace but immediately flush on push.
- Collapse consecutive queued replaces.
> amp-bind: Rate-limit history operations

- build-system/dep-check-config.js
- build-system/sources.js
- Add a comment to dep-check-config to indicate you need to update
sources.js
Fixes #23966
> Include amp-base-carousel in amp-carousel's build.

- build-system/pr-check/build-targets.js
As requested by @Gregable, since running all the runtime tests for validator-only changes is unnecessary, and makes the validator workflow slower than necessary.
> 🏗 Don't run all the runtime tests for validator-only changes

- extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
Releases the latest version of SwG to AMP. See the following for the associated release: https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.63
/cc @jpettitt 
------------------------------------------
SwG Release 0.1.22.63
Version 0.1.22.63
Previous release: 0.1.22.61
Add images to offers-flow.md (#628)
switch propensity to using passed in fetcher for AMP compatibility (#626)
Update yarn version and remove ~ from versions to make the build more stable (#625)
SwG Button Impression Logging (#624)
Log SwG button clicks with EventManager (#622)
Use Runtime's EventManager instead of AnalyticsService (#595)
Share hostname in query parameters to Propensity Server (#608)
Make Logger Available in Runtime (#614)
Create Logger (#613)
Fixes JSError tests for FF (#620)
Fixed failed …
> SwG release 0.1.22.63

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
Roll forwards of loaders experiment ramp up. The loaders should render correctly when the image is cached and the extension loads slowly now that #23964 is fixed.
Reverts ampproject/amphtml#23963
> Revert "Revert "Set the new loaders experiment to 1% of traffic.""

- package.json
`terser` is only used by the build system, and should live in `devDependencies`
https://github.com/ampproject/amphtml/blob/36b7f5c7180fa18534e6c64a9642c3e950791a3d/build-system/compile/single-pass.js#L37
Addresses https://github.com/ampproject/amphtml/pull/23050#discussion_r314793001
> 🐛 Move `terser` from `dependencies` to `devDependencies`

- build-system/tasks/pr-deploy-bot-utils.js
Calling `travisBuildNumber()` in the global scope results in an error while running any `gulp` task locally.
```
ERROR: This is not a Travis build. Cannot get process.env.TRAVIS_BUILD_NUMBER.
```
This PR moves the call to local scope.
Addresses https://github.com/ampproject/amphtml/pull/23976/files#r314841349
> 🏗🐛 Don't call `travisBuildNumber()` in the global scope

- examples/amp-story/analytics.html
- examples/analytics.amp.html
- extensions/amp-analytics/0.1/analytics-root.js
- extensions/amp-analytics/0.1/events.js
- extensions/amp-analytics/0.1/test/test-events.js
- extensions/amp-story/1.0/amp-story-page-attachment.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/story-analytics.js
- extensions/amp-story/1.0/test/test-analytics.js
- src/analytics.js
Fixes #24017
We just noticed some early analytic events (e.g. story-page-visible on the first page) aren't being logged correctly since the amp-analytics service isn't ready to listen for these events yet. This has been happening since #23030 was pushed since it stopped buffering early events.
This reverts commit 1a3eb267ffe210579e35f47af4346af795576adf. #23030
> 🔥 Revert "📈 Initial StorySpec Implementation (#23030)"

- src/service/document-info-impl.js
Fixes #23988.
Bug introduced in: https://github.com/ampproject/amphtml/pull/23451/files#r314530969
Affects browsers that don't implement `WebCrypto` or `Crypto.getRandomValues`: https://caniuse.com/#search=getRandomValues
> Make DocInfo.pageViewId64 async

- build-system/routes/a4a-envelopes.js
- build-system/server-a4a-template.html
- build-system/server-inabox-template.html
- build-system/tasks/e2e/describes-e2e.js
- extensions/amp-lightbox/0.1/test-e2e/test-amp-lightbox.js
- extensions/amp-position-observer/0.1/test-e2e/test-amp-position-observer.js
- test/fixtures/e2e/amp-position-observer/scrollbound-animation.html
The issue turned out to be the a4a template has hardcoded AMP scripts in `<head>`, which does not respect local dev server's `SERVE_MODE`.
> Fix and enable e2e tests for AMPHTML ads FIE rendering mode

- ads/google/a4a/utils.js
For AdSense/Doubleclick fast fetch, reduce max URL length (after which it will be truncated with &trunc=1 appended) from 16k to 15k to allow for length of headers in the ad request.
> AdSense/Doubleclick Fast Fetch 15k URL length

- testing/test-helper.js
When tearing down `RequestBank` and fetch fails, the error gets swallowed.
before fix
```
✗ TypeError: Cannot read property 'text' of undefined
at testing/test-helper.js:201:29
``` 
after fix
```
✗ Error: XHR Failed fetching (http://localhost:9876/...): Failed to fetch​​​
at createErrorVargs (src/log.js:688:13)
at Log.createExpectedError (src/log.js:344:36)
at src/service/xhr-impl.js:109:22
```
> Throw useful error if RequestBank teardown fails

- README.md
Applications are closed for the AMP Contributor Summit 2019, so we'll stop pointing people to it.  (We'll contact registered attendees through other means directly when needed.)
/cc @ampproject/wg-outreach
> Removes the AMP Contributor Summit 2019 banner now that applications are closed

- extensions/amp-form/0.1/form-dirtiness.js
- extensions/amp-form/0.1/test/test-form-dirtiness.js
New forms are usually clean. However, if `amp-bind` mutates a form field
before the `amp-form` is initialized, the `amp-form` will miss the
`FORM_VALUE_CHANGE` event dispatched.
cc/ @GoTcWang @choumx Thanks!
> 🐛 FIX: check all fields' dirtiness on AMP form init

- examples/visual-tests/amphtml-ads/resource/image.html
- examples/visual-tests/amphtml-ads/resource/text.html
This has been passing in the past. Unsure about the reason but now it is breaking.
> Amphtml ads visual tests should use relative path against root

- build-system/tasks/presubmit-checks.js
- extensions/amp-a4a/0.1/test/test-amp-a4a.js
- extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
- extensions/amp-analytics/0.1/test/test-visibility-manager.js
- extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js
- extensions/amp-skimlinks/0.1/test/test-amp-skimlinks.js
- extensions/amp-smartlinks/0.1/test/test-amp-smartlinks.js
- src/preconnect.js
- src/runtime.js
- src/service/ampdoc-impl.js
- src/service/document-state.js
- src/service/viewer-impl.js
- src/utils/document-visibility.js
- test/integration/test-visibility-states.js
- test/unit/3p/test-3p-frame.js
- test/unit/test-ampdoc.js
- test/unit/test-chunk.js
- test/unit/test-document-state.js
- test/unit/test-performance.js
- test/unit/test-preconnect.js
- test/unit/test-viewer.js
- test/unit/utils/test-document-visibility.js
Blocked by #23871.
Partial for #22734, #22733.
Step 1: support visiblityState and family APIs in AmpDoc.
Step 2: remove visibilityState from Viewer.
> Support visibility API in the ampdoc

- src/amp.js
- src/preconnect.js
- test/unit/test-preconnect.js
Ensures quicker onward journeys by preconnecting to the source URL and canonical URL of a document upon page load.
Fixes #24043
> Automatically preconnect to source origins on page loads.

- examples/experiment-1.0.amp.html
- extensions/amp-experiment/1.0/apply-experiment.js
- extensions/amp-experiment/1.0/mutation/attribute-mutation-default-class.js
- extensions/amp-experiment/1.0/mutation/attribute-mutation-default-style.js
- extensions/amp-experiment/1.0/mutation/attribute-mutation-default-url.js
- extensions/amp-experiment/1.0/mutation/character-data-mutation.js
- extensions/amp-experiment/1.0/mutation/mutation.js
- extensions/amp-experiment/1.0/test/test-attribute-mutation.js
This PR fixes how the style attribute should be set. So now it doesn't override the existing value. 
We also allow setting multiple style pairs now. 
Rename `validate` to `parseAndValidate` as well.
> <amp-experiment> style mutation fix and improvment

- .eslintrc
- build-system/compile/single-pass.js
- build-system/eslint-rules/split-single-pass-comment.js
- build-system/runner/src/org/ampproject/AmpCommandLineRunner.java
Supersedes https://github.com/ampproject/amphtml/pull/24027.
This allows Closure to inline known-constant properties into any accesses, which allows it to DCE if-statement branches that are known to never run.
> 🏗🚮 Enable property inlining

- extensions/amp-video-iframe/0.1/amp-video-iframe.js
Closes #23989
Need help creating a test for this (if needed), I tried stubbing the iframe's `postMessage` call but sinon is unable to stub it because the test video iframe is served from `http://iframe.localhost:9876/` which is apparently not the same origin as `localhost:9876` so sinon can't access the `contentWindow`.
> 🐛Fixes race condition in `amp-video-iframe`

- extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/media-performance-metrics-service.js
- extensions/amp-story/1.0/test/test-amp-story-cta-layer.js
- extensions/amp-story/1.0/test/test-amp-story-page.js
- extensions/amp-story/1.0/test/test-amp-story.js
- extensions/amp-story/1.0/test/test-full-bleed-animations.js
- extensions/amp-story/1.0/test/test-live-story-manager.js
- extensions/amp-story/1.0/test/test-media-performance-metrics-service.js
- src/services.js
Introducing a new media performance metrics service, that records media performance metrics and forwards these to the viewer through the existing performance service.
Here are the metrics:
- Definition: time taken to start video playback after the play() call is made
- Label: smjl
- Value: time in milliseconds
- Definition: milliseconds (for consistency) of video watched by the client. Buffering, paused, and other waiting states do not count.
- Label: smwt
- Value: time in milliseconds (for consistency)
- Definition: triggered when an error stops playback entirely where playback cannot resume. Value gives information to understand what caused the error.
- Label: smerr
- Value: Integer [1, 4] corresponding to MediaError.code as defined by the spec
- Definition: sum of the duration of …
> Story media performance metrics.

- 3p/integration.js
- extensions/amp-a4a/0.1/test/test-amp-a4a.js
- extensions/amp-a4a/0.1/test/test-amp-ad-template-helper.js
- extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
- extensions/amp-ad-network-adzerk-impl/0.1/test/test-amp-ad-network-adzerk-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-rtc.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
- extensions/amp-analytics/0.1/test/test-amp-analytics.js
- extensions/amp-analytics/0.1/test/test-analytics-root.js
- extensions/amp-analytics/0.1/test/test-cookie-writer.js
- extensions/amp-analytics/0.1/test/test-transport.js
- extensions/amp-analytics/0.1/test/test-variables.js
- extensions/amp-analytics/0.1/test/test-visibility-manager.js
- extensions/amp-bind/0.1/test/integration/test-bind-impl.js
- extensions/amp-geo/0.1/test/test-amp-geo.js
- extensions/amp-lightbox-gallery/0.1/test/integration/test-amp-lightbox-gallery.js
- src/mode.js
- test/_init_tests.js
- test/manual/loaders-new.amp.html
- test/unit/3p/test-3p-frame.js
- test/unit/test-base-element.js
- test/unit/test-error.js
- test/unit/test-extension-location.js
- test/unit/test-log.js
- test/unit/test-mode.js
- test/unit/test-runtime.js
- test/unit/utils/test-xhr-utils.js
> Rename AMP_MODE to __AMP_MODE

- extensions/amp-story/1.0/amp-story-desktop-panels.css
Some CSS transforms like a `translate` using % based value, or `scale`, can end up displaying blurry half pixel borders (see attached issue).
There are many hacks available to work around it, like `backface-visibility` for `translate` properties, or using JavaScript to compute a rounded number of pixels. However, the only one I found that works with both `scale` and `translate` is this `perspective` property.
It doesn't seem to affect GPU memory usage and fixes the issue across browsers.
Fixes #16626
> Fixes half pixel borders on story desktop.

- build-system/app.js
- build-system/shadow-viewer.js
This cherry-picks/rebases commits from https://github.com/ampproject/amphtml/pull/23213.
This PR improves the ability for `gulp serve` to be used with a host other than `localhost:8000`. It uses schemeless URLs for the AMP proxy viewer and AMP shadow viewer so that the HTTPS protocol will be used (and successfully loaded) when `gulp serve` is invoked with `--https` or when SSL termination happens higher in the network stack.
See companion pull request for the Local AMP Chrome extension: #24029.
> 🏗 Improve serving from non-localhost host

- testing/local-amp-chrome-extension/background.js
- testing/local-amp-chrome-extension/manifest.json
- testing/local-amp-chrome-extension/popup.html
- testing/local-amp-chrome-extension/popup.js
This is split off from #23213. 
When calling `gulp serve` you can specify a host to use that is different from the default `localhost:8000` (default arguments `--host=localhost` and `--port=8000`).  However, the Local AMP browser extension does not support anything but the default. This PR updates the extension popup to include a URL input field for the actual base URL to be supplied (e.g. `https://amphtml.lndo.site/`).
Importantly, this allows for the extension to be successfully used on HTTPS sites. Previously, I would get insecure mixed content warnings on HTTPS sites since the script URLs would be loaded from `http://localhost:8000`.
> 🏗 Update Local AMP extension to allow custom base URLs

- extensions/amp-bind/0.1/bind-validator.js
- extensions/amp-bind/amp-bind.md
- extensions/amp-twitter/0.1/amp-twitter.js
- extensions/amp-twitter/0.1/test/test-amp-twitter.js
Resolves #17953 
Allow mutation of `data-tweetid` in amp-twitter via amp-bind so that displayed tweet can be changed dynamically.
/to @cathyxz
> ✨ Make tweet id a bindable attribute

- build-system/tasks/visual-diff/index.js
I am unsure of any history why we block data URLs in the visual test, but this seems unnecessary since there are a few SVGs, small images embedded in the HTML and they are deterministic. This PR removes this restriction.
This PR is expected to change various existing snapshots from visual diff.
> ✅ Unblock data url for visual diff test

- build-system/dep-check-config.js
- build-system/sources.js
- examples/amp-story/ads/app-install.html
- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
- extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
- extensions/amp-story-auto-ads/0.1/utils.js
Temporary fix to allow reading of `amp-ad-exit` so that we can support ad networks that only include click tracking urls inside of `amp-ad-exit` config.
This should be deleted once these networks have first class support.
> ✨Story Ads: read amp-ad-exit 

- extensions/amp-experiment/1.0/mutation/attribute-mutation-default-style.js
- extensions/amp-experiment/1.0/test/test-attribute-mutation.js
Add the following list of style property support
Support all values:
`color`
`background-color`
`font-size`
`background-image`
`border-width`
`border-style`
`border-color`
Support a list of values
`visibility`: `hidden`
`display`: `none`
`position`: `static`/`relative`/`absolute`/`initial`/`inherit`
Support mutation for NON AMP elements only
`width` and `height` (all values)
> <amp-experiment> 1.0 add style mutation support

- .lando.yml
- build-system/tasks/generate-runner.js
In `generateRunner()` it currently is detecting for an error for running `ant` by checking for the response `stderr`. This turns out to not always work. When Java is not installed, then the only `stdout` is populated. The proper way to detect for an error is to check the exit code. This PR does that, as well as add a link to where instructions can be found to install Java as required.
> 🏗 Fix detection for failure to generateRunner

- examples/visual-tests/amphtml-ads/amp-inabox-static.html
- examples/visual-tests/amphtml-ads/resource/amp-ads-fallback.html
Part of https://github.com/ampproject/amphtml/issues/23864
Realizing from https://github.com/ampproject/amphtml/issues/23858 that we do not cover fallback in the visual test, this PR adds a test case to cover fallbacks for inabox.
> Add visual test for AMPHTML ads fallback

- build-system/global-configs/prod-config.json
Loaders is at 1% in the current RC (and 100% of canary traffic) and will go to 1% of prod traffic in the next push. This change ramps up to 10% for the next RC/prod cycle.
/cc @nainar
> Ramp loaders up to 10% of prod traffic.

- src/service/performance-impl.js
- test/unit/test-performance.js
Closes #24071
Part of #23634 
/cc @ericandrewlewis for context
> 🚮 Removes `beforeunload` event use in performance impl

- extensions/amp-sidebar/0.1/amp-sidebar.css
- extensions/amp-story/1.0/amp-story.css
Use rgba `background-color` to set the opacity of masks in `amp-sidebar` and `amp-story` so that swipe-to-dismiss can animate mask independent of max opacity.
@sparhami @cathyxz @gmajoulet
> 🖍 Change mask styling for amp-sidebar and amp-story

- extensions/amp-story/1.0/bookend/amp-story-bookend.js
- extensions/amp-story/1.0/test/test-amp-story-bookend.js
[This story](https://feature.undp.org/sahel/) uses the bookend to configure the share providers, but [has no bookend components](https://feature.undp.org/sahel/bookend.json).
The issue is that on desktop, we still show an empty bookend: [screenshot](https://user-images.githubusercontent.com/1492044/63449372-012fb200-c40e-11e9-9e6b-1c2e63a04aba.png)
We have some code to not show the bookend if it has no components ([here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story.js#L2312)), but the issue is that we have some other bookend code that automatically prepends a "heading" component if there wasn't one already ([here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/bookend/bookend-component.js#L108)). `components.length` …
> Don't show an empty desktop bookend when there are no components.

- src/gesture.js
- test/unit/test-gesture.js
Add `shouldStopPropagation` parameter to `Gestures.get()`, default false. This will help with handling sidebar swipe-to-dismiss inside `amp-viewer`.
@sparhami
> Add stop propagation parameter in gestures

- src/service/performance-impl.js
- test/unit/test-performance.js
Add a story experiment ID to the performance service so we can slice the performance metrics for AMP Story.
The only difference from the previous implementation is that the call to "messaging ready signal" is now queued so we don't have to delay it while we wait to know if the document is a story, but that is a no-op.
> Add a "story" experiment ID to the performance service.

- build-system/tasks/runtime-test/helpers.js
Karma tests are run in batches on Sauce Labs browsers. If a batch stalls for some reason, it's hard to tell which browsers were in that batch, and which browser stalled.
This PR prints a message for each `browser_start` event to help figure out which browsers are currently running tests.
> 🏗 Print a message before a Karma browser starts running tests

- extensions/amp-script/0.1/test/integration/test-amp-script.js
- test/integration/test-visibility-states.js
More information can be found at #24124
> Skip failing integration tests

- examples/amphtml-ads/scrollbound-animation-ad.a4a.html
- src/inabox/inabox-viewport.js
/cc @lannka 
The bug broke some components like `amp-position-observer`.
I missed this change during #23201, which resolved some single pass issues.
Also removed the space filling div in the inabox example because I think it's meant to be loaded in the inabox envelope.
The e2e tests are not run with single pass right? Otherwise this would probably have been caught. Whether it's worth doing so though is up to you and the AMP folks.
> Fix getRootClientRectAsync not working in cross domain inabox when compiled in single-pass mode

- build-system/tasks/build.js
- build-system/tasks/extension-helpers.js
Today, the default `gulp` task builds the core runtime and all extensions before starting up its webserver. As the number of extensions has increased, the wait for server startup has become several minutes long.
This PR reorganizes the default `gulp` task as follows:
1. Build the core runtime and other default targets
2. Launch the webserver
3. Build extensions
With this PR, the wait for webserver startup goes down from a few minutes to ~30 seconds. The `--watch` and `--extensions` mechanisms remain unchanged.
> 🏗 Reorganize default `gulp` task to build extensions after launching server

- build-system/tasks/presubmit-checks.js
- extensions/amp-a4a/0.1/test/test-a4a-var-source.js
- extensions/amp-viewer-integration/0.1/test/integration/test-amp-webview-viewer-integration.js
- src/chunk.js
- src/service/performance-impl.js
- src/service/resources-impl.js
- test/unit/test-chunk.js
- test/unit/test-document-info.js
- test/unit/test-performance.js
- test/unit/test-resources.js
- test/unit/test-url-replacements.js
This change allows AMP to make the body visible before the resource pipeline initializes. This results in a significant improvement in FCP. The change is, however, effectively a no-op when `macro-after-long-task` is off, because without the resource init continues to execute within the same macro as the rest of AMP's initialization.
This change may
- Regress other perf metrics, because certain JS execution and hence network requests are now delayed by a paint
- Should not improve FCP on pages that have their boilerplate removed
- May regress FID because the user may be enticed to click earlier when init code is still running.
- There is a change in how `first-viewport-ready` is calculated. Previously the code relied on resource discovery running early, now it always waits until the …
> [Rollforward] Relatively drastically improve FCP for docs with a hidden body.

- extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
- extensions/amp-script/0.1/test/integration/test-amp-script.js
- test/_init_tests.js
- test/integration/test-amp-carousel.js
- test/integration/test-errors.js
- test/integration/test-user-error-reporting.js
- test/integration/test-video-players-helper.js
- test/integration/test-visibility-states.js
`skipWindows()` was used to skip flaky tests, but introduced a side effect where tests were being skipped for all browsers (excluding those opted into Safari) in Sauce Labs. This is because we run integration tests for Chrome, Firefox, Edge and IE on Windows.
Skipping tests should be allowed at the browser level, not OS.
related to #24124
> ✅ Remove skipWindows() as a test config

- extensions/amp-access-scroll/0.1/amp-access-scroll.css
- extensions/amp-access-scroll/0.1/read-depth-tracker.js
- extensions/amp-access-scroll/0.1/scroll-audio.js
- extensions/amp-access-scroll/0.1/scroll-bar.js
- extensions/amp-access-scroll/0.1/scroll-component.js
- extensions/amp-access-scroll/0.1/scroll-impl.js
- extensions/amp-access-scroll/0.1/scroll-relay.js
- extensions/amp-access-scroll/OWNERS.yaml
This PR brings support for the article audio feature from desktop Scroll to the amp-access-scroll extension, plus some refactoring within the extension for cleanup and maintainability. 
- Adds audio player iframe when user taps audio icon in scrollbar:
- Audio iframe is lazily created after user interaction
- Relay class uses postMessage to synchronize playing / paused state between Scroll bar and audio iframe. Messages are filtered down by origin and are only passed between frames created by this extension.
- Refactors Scroll bar iframe to use component pattern
cc @kushal @dbow
> ✨ Add audio support to amp-access-scroll extension

- build-system/tasks/extension-helpers.js
- build-system/tasks/vendor-configs.js
- Eliminates the race between `compileVendorConfigs` and `buildExtensionJs()` for `amp-analytics`. Now, the two are done one after the other, making the build logs easier to read.
- Prints the `Compiled all analytics vendor configs into dist/v0/analytics-vendors/` message only when at least one vendor config was actually generated
- Consolidates the `vendorConfigs` task by removing the call to `printNobuildHelp()` (unnecessary copy-paste)
> 🏗🐛 Assorted fixes to vendor config generation

- extensions/amp-accordion/0.1/amp-accordion.js
Closes #24118 
Fix bug introduced in #23720, resolve issue #24118
> 🐛 Set a destination scope to hasAction method to prevent checking tap presence on parents elements on amp-accordion

- extensions/amp-story/1.0/media-performance-metrics-service.js
- extensions/amp-story/1.0/test/test-media-performance-metrics-service.js
Updating the media rebuffer rate metric from float to integer, as the current CSI pipeline doesn't support floats.
> Media rebuffer rate metric as integer and not float.

- extensions/amp-viewer-integration/0.1/amp-viewer-integration.js
- Made sure that the last usage of an `unload`/`beforeunload` event does not interfere with the BFCache (only installed on documents that are running inside a viewer)
> Explains allowed usage of an unload listener inside amp-viewer-integration

- 3p/integration.js
- ads/_config.js
- ads/readmo.js
- ads/readmo.md
- examples/ads.amp.html
- extensions/amp-ad/amp-ad.md
Adds support for Verizon Media ReadMo modules (content circulation units) using the `amp-embed` tag. 
----
Sample Rendering
**Mobile**
**Stream**
**Recommendation blocks**
> ✨add support for amp-embed type=readmo

- .gitignore
- extensions/amp-experiment/1.0/mutation/attribute-mutation-default-url.js
- extensions/amp-experiment/1.0/test/test-attribute-mutation.js
- test/manual/amp-experiment-1.0.html
To fix the race condition (it happens most of the time), where the `src` attribute is changed after AMP element's `buildCallback`
> <amp-experiment> 1.0 Support mutating src attribute

- extensions/amp-story/1.0/amp-story-draggable-drawer.css
Fix bookend momentum scrolling on iOS.
I deleted it from the bookend code [here](https://github.com/ampproject/amphtml/pull/23761/files#diff-67e8c7c25bbfaceb818b48a574a0edbaL41) and forgot to add it to the draggable drawer code.
> Fix bookend momentum scrolling on iOS.

- build-system/server.js
- build-system/tasks/build.js
- build-system/tasks/extension-helpers.js
- build-system/tasks/serve.js
**Background:** Until recently, the default `gulp` task would build the core runtime and all extensions before starting up its webserver. With #24138, the flow was reorganized to:
1. Build the core runtime and other default targets
2. Launch the webserver
3. Build extensions
**PR highlights:** A new flag `--lazy_build_extensions` is introduced for the default `gulp` task. It further reorganizes the flow as follows:
1. Build the core runtime and other default targets (unchanged)
2. Launch the webserver (unchanged)
3. The first time an extension is requested from the server, lazily build it (with watch enabled) and serve a fresh version
- After this, the normal `watch` mechanism applies, and the extension gets rebuilt on edit 
- Subsequent requests for the extension will instantly serve it …
> 🏗 Lazily build extensions during the default `gulp` task

- build-system/global-configs/canary-config.json
- extensions/amp-lightbox-gallery/0.1/utils.js
- extensions/amp-sidebar/0.1/amp-sidebar.css
- extensions/amp-sidebar/0.1/amp-sidebar.js
- extensions/amp-sidebar/0.1/swipe-to-dismiss.js
- extensions/amp-sidebar/0.1/utils.js
- src/string.js
- test/unit/test-string.js
Resolves #23927 
Add the ability to dismiss `amp-sidebar` on swipe, with closing animation and mask opacity transition.
Demo: [https://amp-sidebar-swipe.firebaseapp.com/](https://amp-sidebar-swipe.firebaseapp.com/examples/playground.amp.html)
Following sidebar implementations in apps such as Gmail, Spotify and Discord, the dismiss threshold is currently set at 1/2 sidebar width, meaning the sidebar would bounce back if the swipe distance at the point of release is less than half of sidebar width (unless sufficient velocity is applied).
/to @sparhami @cathyxz for review; can also discuss potentials for refactoring and e2e tests.
@andrewwatterson @nainar Some parameters that could be tweaked:
- Speed at which sidebar closes after release
- Speed at which sidebar bounces back after release
- …
> ✨ Enable swipe-to-dismiss for amp sidebar with gestures

- build-system/tasks/css.js
- build-system/tasks/dist.js
- build-system/tasks/extension-helpers.js
This PR picks up where #24137 left off. 
- Always include `amp-loader` and `amp-auto-lightbox` in the list of extensions to be built
- Refactor `getExtensionsToBuild()` and `buildExtensions()`
- Remove the defunct `options.CompileAll`
- Use `options.compileOnlyCss` to determine if `buildExtensions()` should build just CSS (for all extensions)
- Minor clean up
Addresses https://github.com/ampproject/amphtml/pull/24137#pullrequestreview-279234713
Closes #24137
> 🏗 Always build amp-loader and amp-auto-lightbox (adapted from #24137)

- testing/local-amp-chrome-extension/popup.html
I noticed when trying the Local AMP Chrome extension today, that clicking on the toggle had no effect at all. I'm not sure why, but it seems a change in Chrome broke the toggle. When digging into the code, I'm not sure why the toggle worked in the first place. The toggle `div` was not seemingly connected to the checkbox. So this PR turns the `div` into a `label` with an explicit relationship so that clicks on the label will cause the `checked` state to toggle.
This PR also cleans up the formatting of the HTML a bit.
> 🏗 Fix Local AMP Serving CDN toggle in Chrome extension

- build-system/compile/log-messages.js
- build-system/compile/single-pass.js
- build-system/lazy-build.js
- build-system/server.js
- build-system/tasks/build.js
- build-system/tasks/dist.js
- build-system/tasks/extension-helpers.js
- build-system/tasks/helpers.js
- build-system/tasks/serve.js
- bundles.config.js
#24152 added a way to lazily build extensions during the default `gulp` task. This PR goes a step further, and lazily builds all JS (except for the core runtime `amp.js`, which is eagerly built).
**Usage:**
```
gulp --lazy_build
```
- Removed all hardcoded `compileJs` calls in `build-system/tasks/helpers.js`
- Added several js target definitions to `bundles.config.js`
- Refactored JS building into a new function called `doBuildJs()`
- Added a new server module `build-system/lazy-build.js` to build JS and extensions
- Refactored `performBuild()` in `build-system/tasks/build.js`
- Refactored `dist()` in `build-system/tasks/dist.js`
- Assorted documentation / logging / clean up
**Coming up:**
- Refactor `serve.js` and `server.js` to eliminate the separate binary problem …
> 🏗 Lazily build JS during default `gulp` task

- build-system/compile/log-messages.js
- build-system/pr-check/build-targets.js
The tests for AMP's custom babel plugins are [broken](https://travis-ci.org/ampproject/amphtml/jobs/576577805#L360) on `master` because of code that was imported by `log-messages.js`
PR highlights:
- Remove `require` statement that leads to the babel transformation of more code than intended
- Make sure babel plugin tests are run for changes to any files that affect the plugins
> 🏗🐛 Remove imports from `log-messages.js` that break custom babel plugin tests

- .travis.yml
Keep local Safari e2e support but move back to Xenial on Travis to prevent queued jobs.
> Move e2e job back to Xenial

- build-system/lazy-build.js
- build-system/tasks/helpers.js
Today, if a test webpage requests a JS file more than once during `gulp --lazy_build`, concurrent builds are triggered for the same file, leading to a race.
This PR eliminates the race as follows:
- Changes the function signature of `doBuildJs()` to match that of `doBuildExtension()`
- Refactors repeated code in `lazyBuildExtensions()` and `lazyBuildJs()` into a helper function `lazyBuild()` that calls the correct build function if necessary
- Adds a mechanism to `lazyBuild()` to keep track of and wait for pending builds before serving 
This implements the "luxury" version of lazy building mentioned in https://github.com/ampproject/amphtml/pull/24138#pullrequestreview-278442430
Addresses https://github.com/ampproject/amphtml/issues/24141#issuecomment-524878844
Partial fix for #24141 …
> 🏗 Wait on pending builds during `gulp --lazy_build`

- css/ampdoc.css
- src/service/viewport/viewport-binding-natural.js
- test/unit/test-viewport-binding.js
Partial for #23379.
Fix for b/140131460.
> Stop iOS 13 from elastically horizontally scrolling documents

- build-system/tasks/dist.js
- build-system/tasks/extension-helpers.js
- bundles.config.js
This PR changes the way extension aliasing is done, and paves the way for lazy building of aliased extensions.
- Deleted `declareExtensionVersionAlias()`, `copyAliasExtensions()`, and `verifyExtensionAliasBundles()`
- Changed format of `extensionAliasBundles` to include just the current version and the aliased (deprecated) version
- Other options are inferred from the current version
- Moved extension aliasing to happen just after the building of CSS / JS (so it can happen during lazy builds)
- Assorted clean up, use of `async` / `await`
**Coming up:** Modify the path switching code in `app.js` to handle the case where an aliased extension is requested
Partial fix for #24141 and #24226
> 🏗 Improve extension aliasing and allow lazy building of aliased extensions

- build-system/compile/single-pass.js
#24258 changed the way aliased extensions are copied, and moved the copy step into the extension building step in order to support lazy building of extensions one at a time. As a result, aliased extensions are no longer copied during single pass compilation.
This PR adds an additional step to single pass compilation to copy all aliased extensions.
Follow up to #24258
> 🏗 Copy aliased extensions after single pass compilation

- build-system/sources.js
amp-story-auto-ads is importing a function from amp-ad-exit to validate config. In PR #24044 I added this specific file, but should have been a glob. 
This showed up as `FilterType$$module$extensions$amp_ad_exit$0_1$filters$filter is not defined` in canary
Side note: this worked when testing with `gulp dist --fortesting && gulp serve --compiled` not sure why it wasn't broken. @erwinmombay Do you know of a better way I can test?
> 🐛Story Ads: fix dependency

- src/service/localization.js
- test/unit/test-localization.js
Stories (and story ads) are registering many string bundles in the following way https://github.com/ampproject/amphtml/blob/8f2e2f849fbdd933a3718e8f74d5b8830cbc7c28/extensions/amp-story/1.0/amp-story.js#L359-L381
The variants that have uppercase letters are not correctly being retrieved. This is because in `registerLocalizedStringBundle ` the registration is keyed on the uppercase version 
```js
this.localizedStringBundles_ = { 'en-GB' : { ...some bundle...} }
```
But in `getLanguageCodesFromString` when we generate potential keys we are lowercasing them https://github.com/ampproject/amphtml/blob/8f2e2f849fbdd933a3718e8f74d5b8830cbc7c28/src/service/localization.js#L76-L79
Therefore it tries to find `this.localizedStringBundles_['en-gb']` which does not exist :(
This PR changes the logic …
> 🐛Fix localization for locales containing uppercase chars.

- README.md
Currently, the badge links to the list of all releases; this PR makes it link to the latest release.
Closes #24294 .
> 📖 Make releases badge point to latest release

- builtins/amp-img.js
- test/unit/test-amp-img.js
I think the previous case could have produced double downloading.
> Synchronously set sizes during initial image element creation.

- examples/amp-story/ads/app-install.html
This config more closely matches output from partner ad networks and should be used in e2e/ manual testing.
> 🐛Story Ads: update amp-ad-exit config

- build-system/tasks/karma.conf.js
Attempt to fix_ https://github.com/ampproject/amphtml/issues/24286 by setting karma's `browserNoActivityTimeout` to 30s.
Right now `browserNoActivityTimeout` is set to 15 min. Which means if a browser stopped sending messaged to karma, karma would wait 15 minutes before disconnecting itself and retrying.
Travis VMs will time out after 10 minutes so we're not actually letting karma disconnect and reconnect.
Also `browserDisconnectTimeout` is set to 15 min but I'm not sure this is the issue.
> 🏗 Fix karma sauce timeouts on Travis

- build-system/lazy-build.js
- build-system/server.js
- build-system/tasks/build.js
- build-system/tasks/compile-jison.js
- build-system/tasks/dist.js
- build-system/tasks/extension-helpers.js
- build-system/tasks/helpers.js
- build-system/tasks/serve.js
When `gulp --lazy_build` is run, all extensions are lazily built by default. This can pose a problem when a test page requests several extensions, causing the page to timeout while the extensions are being lazily built.
This PR mitigates the problem by letting developers pre-build some extensions and lazy-build the rest.
- Added support for the use of `--extensions` and / or `--extensions_from` with `gulp --lazy_build`
- Cleaned up logging for `compileJison()` and `bootstrapThirdPartyFrames()` (logs are now less chatty)
- Removed `compileCoreRuntime()` (addresses https://github.com/ampproject/amphtml/pull/24244#discussion_r318384400)
**Usage:**
```js
// Lazy build all JS and extensions
gulp --lazy_build
//  Eagerly build amp-foo and amp-bar, lazily build the rest
gulp …
```
> 🏗 Add support for pre-building some extensions during `gulp --lazy_build`

- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/service/load-more-service.js
- test/manual/amp-list/infinite-scroll-1.amp.html
- test/manual/amp-list/load-more-refresh.amp.html
Closes #24034. 
The reset-on-refresh feature basically nukes the existing contents of `amp-list` and shows the placeholder while loading. If load-more is applied, the relevant elements like load-more-loading, load-more-ended, load-more-button, and load-more-failed should all be hidden during the refresh.
> fix compatibility of load-more with reset-on-refresh

- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-bind/0.1/test/integration/test-bind-impl.js
Reverts ampproject/amphtml#23938.
Rate-limiting should happen at the `History` service level to avoid breaking history change ordering between extensions e.g. when `amp-lightbox.open` is chained after a `AMP.setState` action. 
May be related to an AoG bug. Rolling back first and will roll forward with the correct fix soon.
> Revert "amp-bind: Rate-limit history operations"

- build-system/dep-check-config.js
- build-system/sources.js
- Add facebook loader as a source since it is needed by
amp-facebook-page and amp-facebook-comments.
- Remove duplicate dep-check-config entry.
Fixes #24253
> 🐛Fix facebook loader for comments, page.

- extensions/amp-analytics/0.1/events.js
- extensions/amp-video-iframe/0.1/amp-video-iframe.js
- extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
- src/service/video-manager-impl.js
- src/video-interface.js
- test/manual/amp-video.amp.html
Borked this feature during review for #18869, as custom event names were introduced per request.
Fixes by introducing an intermediate signal rather than overriding the event dispatched.
`VideoEventTracker` for analytics only knows how to listen to a finite set of signals, so it's simpler to "redefine" the event type for user configuration on the analytics end.
Fixes #22665
> 🐛 Fix regression for analytics with custom event name

- extensions/amp-bind/0.1/amp-state.js
- src/service/history-impl.js
- test/unit/test-history.js
Also includes minor fix for runtime error due to `amp-state[src]` mutations with non-primitives.
> History: Defend against bad "historyPopped" data

- extensions/amp-story/amp-story-analytics.md
This doc shows up as the first result on SERP for [amp story analytics]. Adding a link to the user-friendly blogpost.
> Add a link to analytics blogpost on amp.dev

- extensions/amp-nexxtv-player/0.1/test/test-amp-nexxtv-player.js
These seem to be failing locally and on Travis, blocking the build from being green.
It doesn't seem like there are any recent AMP changes that might cause this to start failing. This is most likely the iframe itself failing to load, causing layout not to complete and thus the test to timeout.
Failures:
https://travis-ci.org/ampproject/amphtml/jobs/580426924
https://travis-ci.org/ampproject/amphtml/jobs/580436568
> Skip failing tests.

- extensions/amp-base-carousel/0.1/child-layout-manager.js
- extensions/amp-base-carousel/0.1/test/test-child-layout-manager.js
- extensions/amp-carousel/0.2/amp-carousel.js
On iOS (but not desktop Safari), the carousel slides will sometimes flicker if we attempt to do layout while the user is scrolling the carousel, which can be distracting. To avoid this, wait until scrolling has stopped before requesting layout.
- Change logic to avoid layout of children until scrolling stops for iOS
* This may result in the user hitting blank slides if scrolling quickly more
often, but avoids a distracting flicker in the general case
* Note: there may still be a flicker if the user starts scrolling again before one of the nearby finishes layout
- Avoid trashing at the threshold for layout/unlayout in Safari by giving the
unlayout an extra buffer area
> 🐛Avoid carousel flickering on iOS.

- extensions/amp-autocomplete/amp-autocomplete.md
This PR adds the missing link to the `amp-autocomplete`.
> 📖 Add link to amp-autocomplete example
