ampproject/amphtml

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Remove scroll-height-bounce and scroll-height-minheight from config

---

css/amp.css
src/service/viewport/viewport-binding-ios-embed-sd.js
src/service/viewport/viewport-binding-ios-embed-wrapper.js
test/unit/test-viewport-binding.js
tools/experiments/experiments.js

Remove scroll-height-bounce and scroll-height-minheight experiments

---

extensions/amp-list/0.1/test-e2e/test-load-more-auto.js
extensions/amp-list/0.1/test-e2e/test-load-more-manual.js

Skip amp-list e2e tests that fail - https://travis-ci.org/ampproject/amphtml/jobs/518330506#L1826-L1919
cc/ @cathyxz

✅ Skip amp-list e2e tests for now

---

extensions/amp-link-rewriter/0.1/test/validator-amp-link-rewriter-exclude.html
extensions/amp-link-rewriter/0.1/test/validator-amp-link-rewriter-exclude.out
extensions/amp-link-rewriter/validator-amp-link-rewriter.protoascii
extensions/amp-skimlinks/validator-amp-skimlinks.protoascii
extensions/amp-smartlinks/validator-amp-smartlinks.protoascii

Right now we have 3 extensions that are rewriting anchor href attribute. To avoid conflict we propose exclusion rules.
/cc: @torch2424

✨Avoid rewriting href with multiple extensions

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

Revert third_party/subscriptions-project/ files for Closure upgrade

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Partial for https://github.com/ampproject/amphtml/issues/18875, related: https://github.com/ampproject/amphtml/pull/21877.

Cleanup amp-list-resizable-children experiment

---

extensions/amp-form/amp-form.md

Update doc as suggested in:
https://github.com/ampproject/amphtml/issues/11691

Update amp-form.md for user-invalid polyfill on fieldset

---

build-system/tasks/compile.js

In #21900, we switched from using `gulp-closure-compiler` to `google-closure-compiler` to minify the runtime. The former prints a long error message that includes the `java` invocation line, while the latter takes a `logger` object as part of `pluginOptions`, to which it writes error messages.
This PR updates the error logging in `compile.js` to be compatible with the new plugin.
Follow up to #21900

🏗🐛 Fix closure compiler error logging

---

build-system/tasks/visual-diff/index.js

Followup fix for comment https://github.com/ampproject/amphtml/pull/21852#pullrequestreview-227563859

🏗 Fold visual diff test errors and warning on Travis

---

build-system/tasks/visual-diff/index.js
build-system/tasks/visual-diff/snippets/snapshot-error.html

🏗 Create a snapshot with the error message for failing visual diff tests

---

extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js
extensions/amp-iframe/0.1/test/test-amp-iframe.js

Unbreak the build by skipping two consistently flaking tests
Related #21960 #21961 
/to @rsimha 
/cc @jpettitt  @aghassemi @lannka

✅ Skip flaky tests

---

extensions/amp-video/0.1/test/test-amp-video.js

Re-enable amp-video HTTP test.

---

build-system/tasks/e2e/package.json
build-system/tasks/e2e/yarn.lock
renovate.json

The previous version of ChromeDriver did not work after updating to Chrome 74.
/to @rsimha 
/cc @caroqliu @estherkim

🐛Use current ChromeDriver version

---

examples/analytics-vendors.amp.html
extensions/amp-analytics/0.1/test/vendor-requests.json
extensions/amp-analytics/0.1/vendors.js
extensions/amp-analytics/0.1/vendors/vponanalytics.js

✨  Add Vpon Analytics to AMP analytics vendors

✨ Add Vpon Analytics to AMP analytics vendors #21769

---

.travis.yml

They've been very flaky of late. @danielrozenberg is working on a fix for #21056. Meanwhile let's make them non-blocking.

✅ Make visual tests non-blocking

---

extensions/amp-subscriptions/0.1/local-subscription-platform.js
extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js

fixes #22022 
correctly return entitlement from local service, add test for same.

Issue 22022 fix

---

extensions/amp-image-slider/validator-amp-image-slider.protoascii
extensions/amp-video-iframe/validator-amp-video-iframe.protoascii
validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.html
validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.out
validator/validator-main.protoascii

- cl/245480181 Revision bump for #21526
- cl/245331243 Allow i-amphtml-sizer as child of amp-video-iframe.
- cl/245095560 Allow i-amphtml-sizer as child of amp-image-slider.
- cl/244691564 Revision bump for #21552
- cl/243147325 Revision bump for #21770

Validator 20190426

---

extensions/amp-image-lightbox/0.1/test/integration/test-amp-image-lightbox.js
extensions/amp-sidebar/0.1/test/integration/test-amp-sidebar.js

Closes #21997
Closes #21999
Skipping to unblock, I think writing these in the new E2E framework would be better than trying to painfully debug here.

✅ amp-sidebar and amp-image-lightbox tests in FF

---

extensions/amp-list/0.1/test-e2e/test-load-more-auto.js
extensions/amp-list/0.1/test-e2e/test-load-more-manual.js
extensions/amp-list/0.1/test/integration/test-amp-list.js
extensions/amp-list/0.1/test/test-amp-list-container.js
extensions/amp-list/0.1/test/test-amp-list-load-more.js
test/manual/amp-list/load-more-manual.amp.html

Remove flaky integration tests in favor of unit tests. Write additional tests for amp-list-load-more. 
Closes #21993

Update amp-list tests

---

build-system/dep-check-config.js
examples/amp-script/hello-world.amp.html
extensions/amp-script/0.1/amp-script.js

/to @dvoytenko /cc @kristoferbaxter

amp-script: Add origin experiment check

---

ads/google/imaVideo.js
build-system/dep-check-config.js

Fixes https://github.com/ampproject/amphtml/issues/21987

🐛 amp-ima-video: Fix wrong null check

---

extensions/amp-facebook-comments/amp-facebook-comments.md

Closes https://github.com/ampproject/amphtml/issues/22062

📖 amp-facebook-comments: Document enforced max `numposts`

---

test/visual-diff/visual-tests

Disable pagination buttons visual diff tests.

Disable pagination buttons visual diff tests.

---

extensions/amp-script/0.1/amp-script.js
extensions/amp-script/0.1/test/unit/test-amp-script.js
src/purifier.js
test/unit/test-purifier.js

/to @dvoytenko /cc @kristoferbaxter

amp-script: Validate tag for attribute/property mutations

---

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js

Adding the crypto functionality into amp-subscriptions-google

✨ Implement crypto functionality in amp-subscriptions-google

---

extensions/amp-analytics/linker-id-forwarding.md

📖Add documentation for linker wildcard matching.

---

package.json
yarn.lock

Reverts ampproject/amphtml#21894
Reason for revert: https://travis-ci.org/ampproject/amphtml/jobs/526704640

Revert "📦 Update dependency google-closure-compiler to v20190415"

---

extensions/amp-form/0.1/amp-form-textarea.js
extensions/amp-form/0.1/test/test-amp-form-textarea.js
test/manual/amp-form-textarea-table.amp.html

I also noticed an empty test, so I filled it out and refactored its implementation method to be more testable.

🐛 Fix autoexpand text areas with relative widths

---

extensions/amp-bind/0.1/bind-expression.js
extensions/amp-bind/0.1/test/test-bind-expression.js

Fixes #21971.
- Added Math's sqrt method as sqrt()
- Added Math's log method as log()

Math Functions: Sqrt and Log function added ✨

---

build-system/git.js
build-system/internal-version.js
build-system/tasks/helpers.js

Add --custom_version_mark to build jobs to set a custom last digit to the RTV number

---

extensions/amp-analytics/0.1/amp-analytics.js
extensions/amp-analytics/0.1/config.js
extensions/amp-analytics/0.1/cookie-writer.js
extensions/amp-analytics/0.1/linker-manager.js
extensions/amp-analytics/0.1/requests.js
extensions/amp-analytics/0.1/resource-timing.js
extensions/amp-analytics/0.1/test/test-amp-analytics.js
extensions/amp-analytics/0.1/test/test-cookie-writer.js
extensions/amp-analytics/0.1/test/test-linker-manager.js
extensions/amp-analytics/0.1/test/test-requests.js
extensions/amp-analytics/0.1/test/test-resource-timing.js
extensions/amp-analytics/0.1/test/test-variables.js
extensions/amp-analytics/0.1/variables.js

h/t to @torch2424 from whom I copypasta'd a lot of this code :)

♻️Move VariableService to doc level

---

build-system/babel-plugins/babel-plugin-transform-amp-extension-call/index.js
build-system/babel-plugins/babel-plugin-transform-amp-extension-call/test/fixtures/transform-call/transform-simple-body/input.js
build-system/babel-plugins/babel-plugin-transform-amp-extension-call/test/fixtures/transform-call/transform-simple-body/options.json
build-system/babel-plugins/babel-plugin-transform-amp-extension-call/test/fixtures/transform-call/transform-simple-body/output.js
build-system/babel-plugins/babel-plugin-transform-amp-extension-call/test/index.js
build-system/build.conf.js
build-system/runner/src/org/ampproject/AmpCommandLineRunner.java
build-system/runner/src/org/ampproject/AmpPass.java

replace the `inlineAmpExtensionCall` found in https://github.com/ampproject/amphtml/blob/master/build-system/runner/src/org/ampproject/AmpPass.java#L155

add plugin transformer to AMP.extension call for singlepass

---

test/visual-diff/visual-tests

e.g., flaky in https://percy.io/ampproject/amphtml/builds/1828636

Disable flaky visual diff test "amp-accordion: page loads"

---

test/integration/test-amp-skimlinks.js

The skipped tests timeout 100% of the time when run locally. They also
timeout on Travis.
Fixes #22154
/cc @slocka

✅ Skip timing out tests.

---

_config.yml
ads/_config.js
ads/aja.js
ads/aja.md
examples/ads.amp.html
extensions/amp-ad/amp-ad.md

```Can not ad transition because of "absolute" of <div id = "C">.```
Suggested revision above

🖍🚀🐛support for CAaja ads network

---

test/integration/test-amp-skimlinks.js

✅ Skip all amp-skimlinks integration tests.

---

extensions/amp-lightbox/0.1/amp-lightbox.js

Fixes https://github.com/ampproject/amphtml/issues/21984 
Similar approach as `amp-sidebar` here.

🍎 🐛 amp-lightbox: prevent iOS scroll freeze in both directions.

---

extensions/amp-script/0.1/amp-script.js

/to @dvoytenko /cc @kristoferbaxter

amp-script: Share size limit across elements

---

build-system/shadow-viewer.js

Fixes html is not a function error.

🐞Fix dev server shadow mode.

---

test/integration/test-amp-ad-fake.js

it's starting to flake, so skip it and keep Travis green.

Skip flaky A4A test

---

spec/amp-actions-and-events.md

toggleAutoplay is an action, not an event

---

extensions/amp-bind/0.1/bind-impl.js
extensions/amp-bind/0.1/bind-validator.js
extensions/amp-bind/0.1/test/integration/test-bind-impl.js
extensions/amp-bind/0.1/test/validator-amp-bind.html
extensions/amp-bind/0.1/test/validator-amp-bind.out
extensions/amp-bind/amp-bind.md
validator/validator-main.protoascii

amp-bind: Update textarea initial value via [defaultText]

---

extensions/amp-analytics/0.1/amp-analytics.js
extensions/amp-analytics/0.1/config.js
extensions/amp-analytics/0.1/cookie-writer.js
extensions/amp-analytics/0.1/linker-manager.js
extensions/amp-analytics/0.1/requests.js
extensions/amp-analytics/0.1/resource-timing.js
extensions/amp-analytics/0.1/test/test-amp-analytics.js
extensions/amp-analytics/0.1/test/test-cookie-writer.js
extensions/amp-analytics/0.1/test/test-linker-manager.js
extensions/amp-analytics/0.1/test/test-requests.js
extensions/amp-analytics/0.1/test/test-resource-timing.js
extensions/amp-analytics/0.1/test/test-variables.js
extensions/amp-analytics/0.1/variables.js

Reverts ampproject/amphtml#22137
For more detail see #22217
Cherry pick request coming.

Revert "♻️Move VariableService to doc level"

---

build-system/app-test.js
build-system/tasks/e2e/functional-test-controller.js
build-system/tasks/e2e/puppeteer-controller.js
build-system/tasks/e2e/selenium-webdriver-controller.js
extensions/amp-date-picker/0.1/amp-date-picker.js
extensions/amp-date-picker/0.1/date-picker-common.js
extensions/amp-date-picker/0.1/dates-list.js
extensions/amp-date-picker/0.1/test-e2e/test-blocked-dates.js
extensions/amp-date-picker/amp-date-picker.md
test/fixtures/e2e/amp-date-picker/blocked-dates.html

Implements #17950 
/to @cathyxz @sparhami 
/cc @estherkim

✨Add allow-blocked-end-date flag and e2e test

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

Previous release: 0.1.22.49
Changes in this release:
Propensity API update and experiment changes (535)
Update code owners to add more reviewers for files (538)
Create code owners (536)
Note - issue numbers are for the swg-js project

SwG Release 0.1.22.50

---

src/service/viewport/viewport-binding-ios-embed-sd.js
src/service/viewport/viewport-binding-ios-embed-wrapper.js
src/service/viewport/viewport-impl.js
test/unit/test-viewport-binding.js
test/unit/test-viewport.js
tools/experiments/experiments.js

Experiment to disable transfer layer in 12.2 and above

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Config for ios-fixed-no-transfer experiment

---

3p/integration.js
ads/google/a4a/utils.js
build-system/babel-plugins/babel-plugin-transform-version-call/index.js
build-system/babel-plugins/babel-plugin-transform-version-call/test/fixtures/transform/transform-internal-runtime-version-call/input.js
build-system/babel-plugins/babel-plugin-transform-version-call/test/fixtures/transform/transform-internal-runtime-version-call/options.json
build-system/babel-plugins/babel-plugin-transform-version-call/test/fixtures/transform/transform-internal-runtime-version-call/output.js
build-system/babel-plugins/babel-plugin-transform-version-call/test/index.js
build-system/babel-plugins/babel-plugin-transform-version/index.js
build-system/build.conf.js
build-system/runner/src/org/ampproject/AmpPass.java
extensions/amp-analytics/0.1/iframe-transport.js
extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
src/3p-frame.js
src/amp-shadow.js
src/amp.js
src/iframe-attributes.js
src/inabox/amp-inabox-lite.js
src/inabox/amp-inabox.js
src/internal-version.js
src/mode.js
src/runtime.js
src/service/url-replacements-impl.js

for some reason these calls aren't dce'd into the string literal

repace version() calls with the version string literal

---

ads/_config.js
ads/pubmine.js
examples/ads.amp.html

At the moment each pubmine slot sends an ad request. This PR contains changes allowing sending one ad request for multiple slots.

🚀 Use a multislot request for pubmine ads

---

src/inabox/inabox-viewport.js
src/service/viewport/viewport-binding-def.js
src/service/viewport/viewport-binding-ios-embed-sd.js
src/service/viewport/viewport-binding-ios-embed-wrapper.js
src/service/viewport/viewport-binding-natural.js
src/service/viewport/viewport-impl.js
test/unit/test-viewport-binding.js
test/unit/test-viewport.js

Override global scrollTo in iOS embed cases

---

extensions/amp-analytics/0.1/cookie-writer.js
extensions/amp-analytics/0.1/test/test-cookie-writer.js
testing/fake-dom.js

Rewrote some of the tests to cover the cookie domain and expiration.
Closes #21377

Write cookies to eTLD+1

---

build-system/amp4test.js
build-system/app.js
build-system/shadow-viewer.js
test/integration/test-amp-analytics.js
testing/describes.js

Introduces new `amp4test/compose-shadow` endpoint that takes a docUrl and wraps it in shadow viewer. 
Also adds a basic analytics test.

✨Add shadow integration test for amp analytics

---

3p/integration.js
ads/_config.js
ads/opinary.js
ads/opinary.md
examples/ads.amp.html
extensions/amp-ad/amp-ad.md

amp-embed support for [Opinary](https://www.opinary.com)

amp-embed support for opinary

---

extensions/amp-ad-custom/0.1/test/validator-amp-ad-custom.html
extensions/amp-ad-custom/0.1/test/validator-amp-ad-custom.out
extensions/amp-ad-custom/validator-amp-ad-custom.protoascii

Add validation rules for <amp-ad-custom>

---

extensions/amp-recaptcha-input/amp-recaptcha-input.md

🐛amp-recaptcha-input: Removed the experimental blurb in the recaptcha reference docs

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-button.css
third_party/subscriptions-project/swg.js

SwG release 0.1.22.51
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.51

SwG release 0.1.22.51

---

extensions/amp-web-push/0.1/amp-web-push.service-worker.js

Fix typo for web push service worker messenger command

🐛 Web push: service worker messenger command typo

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Remove doc opt-in for 'ampdoc-shell' experiment

---

extensions/amp-consent/integrating-consent.md

Follow up to the discussion here https://github.com/ampproject/amphtml/pull/22257#issuecomment-492020391

Rename consentState to consentStateValue

---

build-system/tasks/e2e/amp-driver.js
examples/viewer.html

This allows us to pass different viewer capabilities in the hashparam so we can test against various sets of caps.
/to @choumx 
/cc @caroqliu

🏗Enable passing viewer caps as hashparam

---

extensions/amp-analytics/amp-analytics.md

📖 AMP analytics docs: Correct format support (-email, +stories)

---

contributing/contributing-code.md
spec/amp-versioning-policy.md

- Points to the breaking changes policy and new deprecation process (I2D/I2R) from the deprecation doc
- FIxes a minor typo in deprecation docs

Points to deprecation process from contribution doc & fixes typo

---

spec/amp-html-components.md

- Points to the common CLA documentation.
- Points to the current process for making significant changes.
Partial fix for https://github.com/ampproject/meta/issues/18.

Updates the components doc for current processes

---

build-system/tasks/e2e/describes-e2e.js
build-system/tasks/e2e/selenium-webdriver-controller.js

Fixes #22271
Thanks @cvializ for your help :blush:

🏗 Appropriately handle async E2E test error

---

extensions/amp-analytics/0.1/linker-manager.js
extensions/amp-analytics/0.1/test/test-linker-manager.js
src/service/navigation.js
test/manual/amp-linker-simple.amp.html

Enable linker for AMP.navigateTo

---

extensions/amp-analytics/0.1/amp-analytics.js
extensions/amp-analytics/0.1/config.js
extensions/amp-analytics/0.1/cookie-writer.js
extensions/amp-analytics/0.1/linker-manager.js
extensions/amp-analytics/0.1/requests.js
extensions/amp-analytics/0.1/resource-timing.js
extensions/amp-analytics/0.1/test/test-amp-analytics.js
extensions/amp-analytics/0.1/test/test-cookie-writer.js
extensions/amp-analytics/0.1/test/test-linker-manager.js
extensions/amp-analytics/0.1/test/test-requests.js
extensions/amp-analytics/0.1/test/test-resource-timing.js
extensions/amp-analytics/0.1/test/test-variables.js
extensions/amp-analytics/0.1/variables.js

Reimplementing this refactor after adding shadow integration test. 
Closes #22217

♻️Move VariableService to doc level #2

---

build-system/tasks/karma.conf.js
build-system/tasks/runtime-test/index.js

Fixes https://github.com/ampproject/amphtml/issues/22385

🐛 Don't overwrite browserify transform config

---

extensions/amp-autocomplete/amp-autocomplete.md
extensions/amp-form/amp-form.md
extensions/amp-gist/amp-gist.md
extensions/amp-inputmask/amp-inputmask.md
extensions/amp-link-rewriter/amp-link-rewriter.md
extensions/amp-mraid/amp-mraid.md
extensions/amp-smartlinks/amp-smartlinks.md

Fixes ampproject/docs#2113, ampproject/docs#2110.

📖 Fix formatting issues in extension docs and add missing front-matter

---

build-system/tasks/e2e/index.js
extensions/amp-base-carousel/0.1/test-e2e/test-autoadvance.js
extensions/amp-base-carousel/0.1/test-e2e/test-grouping.js
extensions/amp-base-carousel/0.1/test-e2e/test-mixed-lengths.js
extensions/amp-base-carousel/0.1/test-e2e/test-non-looping.js
extensions/amp-form/0.1/test-e2e/test-ssr.js
extensions/amp-list/0.1/test-e2e/test-ssr.js

- Skips failing E2E tests
- If test fails, reattempt test for up to 2 times
cc/ @sparhami for some of the skipped tests

🏗 Skip failing e2e tests and set retry to 2

---

ads/beaverads.js

This broke master due to checks being run before prettier change.
cc/ @rsimha

Reformat beaverads contribution

---

extensions/amp-date-picker/0.1/amp-date-picker.js

- Fix for the issue: https://github.com/ampproject/amphtml/issues/21886

fix wrong data event Select amp-date-picker range

---

ads/google/a4a/test/test-utils.js
build-system/tasks/runtime-test/index.js
test/unit/test-amp-context.js
test/unit/test-ampdoc.js
test/unit/test-document-info.js
test/unit/test-font-stylesheet-timeout.js
test/unit/test-friendly-iframe-embed.js
test/unit/test-iframe-helper.js
test/unit/test-iframe-stub.js
test/unit/test-performance.js
test/unit/test-preconnect.js
test/unit/test-purifier.js
test/unit/test-runtime.js
test/unit/test-shadow-embed.js
test/unit/test-url-replacements.js
test/unit/test-url-rewrite.js
test/unit/test-url.js
test/unit/test-viewport-binding.js

This PR runs a large number of core runtime unit tests on Firefox (in addition to Safari, where they're already enabled).
Follow up to #11827
Fixes #6039

🏗 Run unit tests on Firefox

---

extensions/amp-story/1.0/amp-story-store-service.js
extensions/amp-story/1.0/amp-story-system-layer.js
extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/live-story-manager.js
extensions/amp-story/1.0/progress-bar.js
extensions/amp-story/1.0/test/test-amp-story.js
extensions/amp-story/1.0/test/test-full-bleed-animations.js

Master issue #21714
Closes #21722

✨ Update progress bar when new page is appended by the LiveStoryManager

---

extensions/amp-story/amp-story.md

Add `animate-in-timing-function` attribute to the amp-story documentation.

Add animate-in-timing-function attribute to the amp-story documentation.

---

extensions/amp-analytics/0.1/test/test-variables.js
extensions/amp-analytics/0.1/variables.js

Casting all input to string until design for all macros is finalized.
Related to #22423

🐛Fix $SUBSTR macro

---

validator/validator-main.protoascii

Reverts ampproject/amphtml#22417
Per https://github.com/ampproject/amphtml/issues/21931#issuecomment-494873147, we've decided not to offer a page level opt-out.

Revert "✨ Add new <meta name="amp-experiments-opt-out">"

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

Testing the changes related to JsDoc.

SwG release 0.1.22.51.1

---

ads/pubmine.js
test/unit/ads/test-pubmine.js

🔥  Fix pubmine ads

---

build-system/app-index/settings.js
build-system/tasks/build.js
build-system/tasks/check-types.js
build-system/tasks/dist.js
build-system/tasks/e2e/index.js
build-system/tasks/firebase.js
build-system/tasks/runtime-test/index.js
build-system/tasks/visual-diff/index.js

Addresses https://github.com/ampproject/amphtml/pull/22380#issuecomment-495018233
Follow up to #22380

🏗🐛 Don't run `clean` during `build`, `check-types`, or `dist`

---

build-system/tasks/e2e/describes-e2e.js
build-system/tasks/e2e/functional-test-controller.js
build-system/tasks/e2e/index.js
build-system/tasks/e2e/package.json
build-system/tasks/e2e/yarn.lock
extensions/amp-base-carousel/0.1/test-e2e/test-arrows.js
package.json
yarn.lock

this adds a `describe` block before environment variants for browser type.
also adds firefox webdriver

add firefox option for e2e tests

---

extensions/amp-ad-network-doubleclick-impl/multi-size.md

As titled, minor fix in `extensions/amp-ad-network-doubleclick-impl/multi-size.md`

📖 Fix up sample HTML syntax in doc

---

build-system/runner/README.md
build-system/runner/src/org/ampproject/AmpCodingConvention.java
build-system/tasks/css.js

Fix hardcoded CSS filename in closure compiler code.

---

.travis.yml

🏗 Turn E2E tests into BLOCKING MODE in our CI build

---

spec/amp-html-format.md

Picture is disallowed in AMP. Updated documentation to reflect this. Partially resolves issue #22430

📖Added picture to table 

---

extensions/amp-lightbox-gallery/0.1/lightbox-controls.css

- All icons changes should be pixel perfect replacements of the previous ones.
- Recreated prev, next, close, and gallery buttons from scratch
- Cleaned up slides button svg

🚀Optimize svgs used in lightbox gallery.

---

3p/embedly.js
3p/github.js
3p/nameframe.max.html
build-system/tasks/presubmit-checks.js
extensions/amp-vimeo/0.1/amp-vimeo.js
src/3p-frame.js
validator/build.py
validator/engine/json-testutil.js
validator/engine/validator-in-browser.js
validator/webui/build.py

This PR fixes a few of the security, correctness, and maintainability [issues](https://lgtm.com/projects/g/ampproject/amphtml/alerts/?mode=tree) in our code detected via static analysis from LGTM.com.
**Fixed:**
- [3p/embedly.js](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/62a6f805a2d91db98d7bd8751b61b9171d0a8cc5/files/3p/embedly.js?sort=name&dir=ASC&mode=heatmap#x4eccbef23f39f97c:1)
- [3p/github.js](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/62a6f805a2d91db98d7bd8751b61b9171d0a8cc5/files/3p/github.js#x9c3fcb1368a63323:1)
- [3p/nameframe.max.html](https://lgtm.com/projects/g/ampproject/amphtml/snapshot/62a6f805a2d91db98d7bd8751b61b9171d0a8cc5/files/3p/nameframe.max.html#x8c1e62f82fa99681:1)
- [extensions/amp-vimeo/0.1/amp-vimeo.js](https://lgtm.com/projects/g/amppr …

🐛 Fix LGTM alerts in AMP codebase

---

examples/amp-ad-template.amp.html
extensions/amp-a4a/0.1/friendly-frame-util.js

applyFillContent on amp-ad-custom

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

SwG release 0.1.22.53
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.53
Fixes #22558

SwG 0.1.22.53

---

build-system/tasks/report-test-status.js
build-system/tasks/runtime-test/index.js

Wrapping up a dangling TODO from PR #21863

🏗 Report test status for integration tests on stable browsers on SauceLabs

---

src/form.js
test/unit/test-form.js

This will be used as part of an form field's dirtiness check.
This is part of #22534.
/cc @cvializ @GoTcWang

Add `isFieldEmpty` helper

---

extensions/amp-story/1.0/amp-story-page-attachment.js

Page attachment components now own their AMP components descendants lifecycle callbacks.
This fixes at least two bugs:
- Videos weren't always paused when a user closed the attachment
- Some components weren't laid out when the scroll height was too big (runtime doesn't understand scrollboxes)
Fixes #22322, #21897

Handling the lifecycle of AMP components within an attachment.

---

build-system/tasks/codecov-upload.js
build-system/travis.js

Fixes [this](https://travis-ci.org/ampproject/amphtml/jobs/540185768#L1608-L1609) error seen in push builds:
Follow up to #22515 and #22549

🏗 Fix code coverage logging on Travis

---

extensions/amp-story/1.0/amp-story-store-service.js
extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/pagination-buttons.js

♻️ Replace usage of pagesCount with page_ids.length

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Ramp up the amp-force-prerender-visible-elements experiment from 1% to 10%
#21791

Ramp up the force prerender experiment from 1% to 10%.

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Turn on 'inabox-remove-height-auto'

---

extensions/amp-story/amp-story.md

Adds references for `amp-twitter` plus guidance on how to use the `interactive` attribute.
#19213 #16522

📖  Add references to amp-twitter

---

src/service/viewport/viewport-impl.js
test/unit/test-viewport.js

Override global scrollY/pageYOffset in iOS embed cases

---

build-system/pr-check/build.js
build-system/pr-check/dist-bundle-size.js
extensions/amp-analytics/0.1/test/test-cookie-writer.js

Test added in #22483.
This appears to be a fix, but I am unsure if it is the correct fix. It is odd that it passed on PR, but now seems to be broken locally and on travis. 
to/ @jonathantyng-amp @zhouyx 
Closes #22694

🐛Fix broken cookie writer test

---

extensions/amp-story/1.0/amp-story-page-attachment.js
extensions/amp-story/1.0/story-analytics.js

Analytics trigger when opening/closing the story page attachment.

Analytics trigger when opening/closing the story page attachment.

---

examples/cmp-vendors.amp.html
extensions/amp-consent/amp-consent.md
extensions/amp-consent/cmps/didomi.md

Add Didomi documentation and example to AMP related to this comment: 
https://github.com/ampproject/amphtml/pull/22518

📖amp-consent: Add Didomi CMP documentation + example (rebase)

---

build-system/tasks/css.js

Add explanatory comment

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Launch the `amp-force-prerender-visible-elements` experiment.
cc @choumx 
Closes #21791

Launch the force prerender experiment.

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Enable "margin-bottom-in-content-height" in canary/prod

---

contributing/TESTING.md

📖 Fix table in testing documentation

---

extensions/amp-story/amp-story.md

To be merged once #22642 is available in production.

Documenting amp-story-page-attachment theme.

---

extensions/amp-story/amp-story-analytics.md

To be merged when #22710 is available in production.

Documentation for the story page attachment analytics triggers.

---

extensions/amp-story/1.0/amp-story-page.js

The JSDoc string for amp-story-page was copied and pasted from amp-story and therefore incorrect.
/cc @newmuis

Updates the JSDoc for amp-story-page overview

---

extensions/amp-auto-ads/0.1/anchor-ad-strategy.js
extensions/amp-auto-ads/0.1/opt-in-status.js
extensions/amp-auto-ads/0.1/test/test-anchor-ad-strategy.js

Add a new data attribute on amp-ad element which will tell whether publisher enabled anchor ad or not.

🐛 Add a new data attribute on the created amp-ad element

---

src/cookies.js

Use endsWith Helper

---

src/inabox/amp-inabox.js
src/service/extensions-impl.js
tools/experiments/experiments.js

for #22418
config change is in separate PR: #22632

Introduce experiments for ad CSS clean ups.

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Ads CSS experiments config change

---

extensions/amp-story/amp-story.md

Update image src in story documentation.

Update image src in story documentation.

---

extensions/amp-analytics/0.1/linker-manager.js
extensions/amp-analytics/0.1/test/test-linker-manager.js

Follow up to #22753
Previous PR merged to make canary cut. Fixing nits here.

⛏Linker fragment nits

---

src/service/video-manager-impl.js
test/unit/test-video-analytics-percentage-tracker.js

Fixes #22701
@alanorozco do you think this will work or are there any concerns with this approach?

🐛 Fix percentage-played when loadedmetadata fires before listener is added

---

extensions/amp-user-location/validator-amp-user-location.protoascii

Addresses https://github.com/ampproject/amphtml/pull/22773#discussion_r293000401 review feedback

🐛 do not allow relative URL with https

---

extensions/amp-form/0.1/form-validators.js

🐛 Handle case where textarea has required attr

---

extensions/amp-video-iframe/amp-video-iframe.md

# Description
Fixes some typos in the amp-video-iframe documentation.

📖Typos in amp-video-iframe.md

---

extensions/amp-date-picker/0.1/amp-date-picker.js
extensions/amp-date-picker/0.1/dates-list.js
extensions/amp-date-picker/0.1/test/test-amp-date-picker-state.js
extensions/amp-date-picker/0.1/test/test-dates-list.js

Improve coverage on amp-date-picker.
I found and fixed a contract bug in dates-list 😅

✅ Improve amp-date-picker coverage with state machine and dates-list

---

extensions/amp-story/1.0/amp-story-page.js
extensions/amp-story/1.0/amp-story-scroll.css
extensions/amp-story/1.0/amp-story-store-service.js
extensions/amp-story/1.0/amp-story.css
extensions/amp-story/1.0/amp-story.js

Renders the story in a vertical scrollable format to hopefully make it easier to understand by search engine crawlers.

Story vertical scrolling rendering.

---

extensions/amp-apester-media/0.1/amp-apester-media.js

Closes https://github.com/ampproject/amphtml/issues/19254

♻️ amp-apester-media: reduce some error noise.

---

extensions/amp-story/1.0/test/validator-amp-story-live-story-error.html
extensions/amp-story/1.0/test/validator-amp-story-live-story-error.out
extensions/amp-story/1.0/test/validator-amp-story-live-story.html
extensions/amp-story/1.0/test/validator-amp-story-live-story.out
extensions/amp-story/validator-amp-story.protoascii

Validation for live story functionality.
Partial for #21714

✨ Live story validation

---

src/service/url-expander/expander.js
test/integration/test-amp-analytics.js

The expander is broken with singlepass.

Fix analytics expander in singlepass

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

Releases the latest version of SwG to AMP.  Primarily, this allows SwG event management development to begin within AMP.

SwG Release 0.1.22.56

---

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js

🐛 Check if there's an embedded iframe before using it

---

LICENSE

Update LICENSE to be an exact copy of https://www.apache.org/licenses/LICENSE-2.0.txt
Line 189 should have template text, not a Google copyright notice.

Update LICENSE to be an exact copy of Apache license.

---

examples/visual-tests/amp-story/amp-story-vertical-rendering.html
test/visual-diff/visual-tests

Story vertical rendering visual diff tests.

Story vertical rendering visual diff tests.

---

build-system/conformance-config.textproto

Re: https://github.com/ampproject/amphtml/pull/22946#discussion_r296255096

🏗 Add a Node.p.after exception for dates-list

---

ads/outbrain.md

- Changed configuration attribute names
- Fixed typo
- Added another example
/cc @zhouyx

📖 Updated Outbrain amp-embed documentation

---

ads/custom.md
ads/google/a4a/docs/Network-Impl-Guide.md
extensions/amp-form/amp-form.md
spec/amp-cors-requests.md

Closes #22136.
Followup on #22630.
DO NOT SUBMIT until #22630 is in PROD+1

Update AMP CORS docs with removed AMP-Access-Control-Allow-Source-Origin requirement

---

extensions/amp-accordion/amp-accordion.md

📖 Fix amp accordion docs

---

build-system/amp.extern.js
build-system/conformance-config.textproto
extensions/amp-date-picker/0.1/dates-list.js

Addresses https://github.com/ampproject/amphtml/pull/22946#issuecomment-505167101

🐛 Add type info for `RRule`, remove conformance config exceptions

---

build-system/eslint-rules/no-import.js
test/e2e/test-controller-promise.js

♻️ Move ControllerPromise test to test/e2e

---

build-system/tasks/dep-check.js
build-system/tasks/helpers.js
build-system/tasks/karma.conf.js
build-system/tasks/runtime-test/runtime-test-base.js

Addresses pending item in https://github.com/ampproject/amphtml/pull/22951#pullrequestreview-252573822

🏗 Consolidate `babel` global transform config

---

extensions/amp-base-carousel/amp-base-carousel.md

- Fix code syntax in table.
- Fix documentation for horizontal, the correct default value is `true`.

📖  Update amp-base-carousel.md

---

extensions/amp-lightbox/0.1/test-e2e/test-amp-lightbox.js
test/fixtures/e2e/amp-lightbox/amp-lightbox.html

✅ Add e2e test for amp-lightbox basic behavior

---

extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js

Setting value of the 'aanf' url parameter with the actual value of the data attribute of the ad element.

🐛 Set value of url parameter for fast fetch

---

src/service/variable-source.js
test/integration/test-amp-analytics.js
test/unit/test-url-replacements.js
test/unit/test-variable-source.js

The PR caused side effect on some reporting due to the new "nextTick" behavior in navTiming macro.
/cc @jeffkaufman

Revert #22812

---

extensions/amp-addthis/amp-addthis.md

Fixes ampproject/docs#2168
edit the teaser text to "Displays AddThis’ customizable social share buttons."

📖 Edit teaser text for amp-addthis component

---

extensions/amp-consent/integrating-consent.md

The feature is no longer protected under experiment flag : )

Update consent integration doc 

---

extensions/amp-analytics/0.1/amp-analytics.js
src/service/ampdoc-impl.js
test/unit/test-ampdoc.js
test/unit/test-document-info.js
test/unit/test-element-service.js
test/unit/test-fixed-layer.js
test/unit/test-intersection-observer-polyfill.js
test/unit/test-url-replacements.js

Cleanup ampdoc-closest experiment

---

extensions/amp-auto-ads/amp-auto-ads.md

Correcting the PlacementType and attributes Enum in amp-auto-ads.md file.

🐛 Correcting the Enum fields in amp-auto-ads.md file

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json
src/font-stylesheet-timeout.js
test/unit/test-font-stylesheet-timeout.js
tools/experiments/experiments.js

🚮 Cleanup font-display-swap experiment

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json
examples/live-list-update-reverse.amp.html
extensions/amp-live-list/0.1/amp-live-list.js
extensions/amp-live-list/0.1/test/test-amp-live-list.js
tools/experiments/experiments.js

🚮 Cleanup amp-live-list-sorting experiment

---

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js

Related to #23102.
Revert this PR once #23101 has been fixed.

Disable prerendering mode for SwG

---

extensions/amp-access/0.1/test/test-login-dialog.js
extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js
extensions/amp-install-serviceworker/0.1/test/test-amp-install-serviceworker.js
extensions/amp-lightbox/0.1/amp-lightbox.js
src/document-fetcher.js
src/error.js
src/runtime.js
src/service/ampdoc-impl.js
src/service/vsync-impl.js
src/service/xhr-impl.js
test/_init_tests.js
test/integration/test-video-manager.js
test/unit/test-activity.js
test/unit/test-ampdoc.js
test/unit/test-cid.js
test/unit/test-error.js
test/unit/test-extensions.js
test/unit/test-fixed-layer.js
test/unit/test-layers.js
test/unit/test-runtime.js
test/unit/test-url-replacements.js
test/unit/test-viewer.js
test/unit/test-viewport-binding.js
test/unit/test-viewport.js
test/unit/test-vsync.js
test/unit/test-xhr-document-fetcher.js
test/unit/test-xhr.js
testing/iframe.js

Require node to be always passed when resolving ampdoc

---

extensions/amp-a4a/0.1/amp-ad-network-base.js

Fixes #23094.
Tested on publisher's test page and verified the solution works.

Ensure template ads do not send out multiple requests when layout changes

---

src/service.js
test/unit/test-service.js

Minor clean up, no callers today.

Remove fallbackToTopWin option for FIE service getter

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

SwG release 0.1.22.59
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.59

SwG 0.1.22.59

---

src/service/video-manager-impl.js
test/integration/test-video-manager.js

Fix video autoplay ad start/end masks

---

extensions/amp-truncate-text/amp-truncate-text.md

- Change backticks to code tag within a table
- Fix old slot names

📖 Update amp-truncate-text documentation

---

examples/amp-subscriptions-smartbox.amp.html
extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js

Adds `subscriptions-message-text-color` attribute, which allows users to define a custom color for the message text shown below the SmartButton.

✨ SWG: Adds attribute for SmartButton's message text color

---

spec/auto-lightbox.md

📖 Remove experimental note about auto-lightbox

---

test/unit/test-amp-img.js

Remove launched auto-sizes experiment from tests

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Partial for https://github.com/ampproject/amphtml/issues/20517.

Remove launched auto-sizes experiments from configs

---

tools/experiments/experiments.js

Remove the auto-sizes experiment entirely

---

package.json
src/purifier.js
src/sanitation.js
yarn.lock

Upgrade dompurify to 1.0.11 and remove hack

---

src/service.js
test/unit/test-service.js

To address https://github.com/ampproject/amphtml/pull/23153#discussion_r301761759

Only install FIE services on ampdoc in the ampdoc-fie mode

---

3p/integration.js
ads/_config.js
ads/dynad.js
ads/dynad.md
examples/ads.amp.html
extensions/amp-ad/amp-ad.md

Provides support for amp-ad type=dynad
DynAd is an ad network used by https://afiliados.uol.com.br/
close #22968

✨ amp-ad type=dynad

---

build-system/compile/compile.js

🏗  Separate closure warning levels for compile vs. type check

---

src/service/resources-impl.js
test/integration/test-visibility-states.js

Change unselectText() to private method.

---

src/service/resources-impl.js
test/unit/test-resource.js

Change resources-impl/rebuildDomWhenReady() to private method.

---

extensions/amp-form/0.1/form-dirtiness.js
extensions/amp-form/0.1/test/test-form-dirtiness.js
src/amp-events.js

Dispatch a custom event when form dirtiness changes

---

extensions/amp-viewer-integration/amp-doc-viewer-api.md
extensions/amp-viewer-integration/integrating-viewer-with-amp-doc-guide.md

link to Viewer API and messages details in the viewer integration doc

Viewer API doc link

---

src/base-element.js
src/service/resources-impl.js

Remove unused method getMaxDpr().

---

src/base-element.js
src/service/resources-impl.js

Remove getDpr() from resources-impl.js

---

README.md

- Reorder and group badges by function
- add logos to badges
- standardize badge style to flat-square
- add hover/title text to badges
- add Project Metrics badges (see https://github.com/ampproject/amp-github-apps/pull/238)

📖 Update README badges and add badges for project metrics

---

extensions/amp-youtube/0.1/amp-youtube.js
src/custom-element.js
test/unit/test-custom-element.js

Add deprecation error when amp-youtube is used in AMPHTML ads.

---

src/service/resources-impl.js

Remove isRuntimeOn() from resources-impl.js

---

extensions/amp-a4a/0.1/callout-vendors.js
extensions/amp-a4a/rtc-documentation.md
extensions/amp-a4a/rtc-publisher-implementation-guide.md

- Adds Kargo to the list of RTC Vendors available
- also adds Kargo to list of supported vendors in RTC documentation

✨ Adding Kargo RTC Vendor

---

extensions/amp-story/amp-story-analytics.md

To be merged when #22929 hits production.
#22901

📖 Adds docs for last page visible

---

contributing/ORIGIN_TRIALS.md

We didn't have a permanent link to our OT process so adding it.
Needs review by TSC
@ampproject/tsc 
FYI: @kristoferbaxter @jeffjose @torch2424 @choumx

Create ORIGIN_TRIALS.md to document Trials process

---

extensions/amp-date-picker/0.1/test/validator-amp-date-picker.html
extensions/amp-date-picker/0.1/test/validator-amp-date-picker.out
extensions/amp-date-picker/validator-amp-date-picker.protoascii

Fixes missed validation rule from https://github.com/ampproject/amphtml/pull/22029#issuecomment-511777132

🐛 Add validation for allow-blocked-end-date

---

extensions/amp-story/1.0/amp-story.css

Story attachment spec update to be consistent with ads CTAs.

Story attachment spec update to be consistent with ads CTAs.

---

examples/article-access-poool.amp.html
extensions/amp-access-poool/amp-access-poool.md

- Updates (a lot of) phrasing in `amp-access-poool` documentation
- Cleans `amp-access-poool` example code
This PR replaces #21347 after what seems to be a rebase screw-up.
/cc @jpettitt

📖 amp-access-poool: Update documentation & example

---

extensions/amp-subscriptions-google/amp-subscriptions-google.md

Adds code highlighting for SwG's documentation

📖 SwG: Add code highlighting

---

contributing/design-reviews.md

Added some more details on areas of discussion that might come up in a Design Review. Specially as it pertains to different Working Groups.

Update to reflect potential areas to think about in Design Reviews

---

examples/analytics-vendors.amp.html
extensions/amp-analytics/0.1/test/vendor-requests.json
extensions/amp-analytics/0.1/vendors/webengage.js

Added region support in the WebEngage Analytics for the localization of the data storage.
PR Reference: #22554 
I2I Reference: #22124
@zhouyx  @torch2424 @lannka

✨Added region support in webengage analytics.

---

src/service/viewport/viewport-impl.js
test/unit/test-viewport.js
tools/experiments/experiments.js

Experiment to support natural viewport binding on iOS

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Configure ios-scrollable-iframe experiment

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json
tools/experiments/experiments.js

To be merged once #23066 has been in production for two release cycles.
Part of https://github.com/ampproject/amphtml/issues/21791
Closes https://github.com/ampproject/amphtml/issues/21792

Cleanup amp-force-prerender-visible-elements configuration files.

---

spec/email/amp-email-css.md

-   Adds `@pointer`
-   Clarifies on at-rules
-   Clarifies on custom fonts
-   Clarifies on external stylesheets

📖 Update AMP for Email CSS docs

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json
src/service/viewport/viewport-binding-def.js
test/unit/test-viewport.js
tools/experiments/experiments.js

Clean up "margin-bottom-in-content-height" experiment

---

examples/amp-story/analytics.html
examples/analytics.amp.html
extensions/amp-analytics/0.1/analytics-root.js
extensions/amp-analytics/0.1/events.js
extensions/amp-analytics/0.1/test/test-events.js
extensions/amp-story/1.0/amp-story-page-attachment.js
extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/story-analytics.js
extensions/amp-story/1.0/test/test-analytics.js
src/analytics.js

📈 Initial StorySpec Implementation

---

src/service/resources-impl.js

Fixes https://github.com/ampproject/amphtml/issues/20935

🐛 Mark collapse attempt denied as an expected error

---

extensions/amp-ooyala-player/0.1/amp-ooyala-player.js

Fixes https://github.com/ampproject/amphtml/issues/22826

🐛 Fix ooyala when event data is null

---

ads/revcontent.js
ads/revcontent.md

This PR adds support for a new ad code that Revcontent would like to start using within our AMP widgets.

✨ RevContent new ad code support

---

ads/opinary.js

This PR inserts a new div with a unique ID, along with our tool, at each AMP integration. 
We ran into the problem where we could not easily isolate which integrated polls were coming from AMP articles. With this little fix we will be able to easily locate these polls as this will allow us to set a flag in our event system that the poll was seen/ voted on/ interacted with within an AMP article.

✨ opinary amp detection

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

SwG 0.1.22.61 release

---

extensions/amp-access/0.1/amp-access.js
extensions/amp-animation/0.1/web-animations.js
extensions/amp-auto-ads/0.1/placement.js
extensions/amp-bind/0.1/bind-impl.js
extensions/amp-form/0.1/amp-form.js
extensions/amp-form/0.1/form-validators.js
extensions/amp-fx-collection/0.1/providers/fx-provider.js
extensions/amp-next-page/0.1/next-page-service.js
extensions/amp-story/0.1/amp-story-info-dialog.js
extensions/amp-story/1.0/amp-story-embedded-component.js
extensions/amp-story/1.0/amp-story-info-dialog.js
extensions/amp-story/1.0/amp-story-page.js
extensions/amp-story/1.0/page-advancement.js
extensions/amp-subscriptions/0.1/renderer.js
src/custom-element.js
src/friendly-iframe-embed.js
src/service/performance-impl.js
src/service/resource.js
src/service/resources-impl.js
src/service/standard-actions-impl.js
src/services.js

Extract ResourcesDef, MutatorsDef, OwnersDef interfaces

---

build-system/app.js

version=2 is already removed in #23051

Remove version from inabox envelope URL.

---

build-system/pr-check/build.js
build-system/pr-check/checks.js
build-system/pr-check/dist-bundle-size.js
build-system/pr-check/utils.js
build-system/pr-check/validator-tests.js
build-system/tasks/pr-check.js

Addresses https://github.com/ampproject/amphtml/pull/23495#issuecomment-514756840
Follow up to #23495

🏗 Change the PR branch check to a warning and clarify message

---

src/service/variable-source.js
test/integration/test-amp-analytics.js
test/unit/test-url-replacements.js

Follow up to #23069 and #22812
Wait for loadEndEvent to resolve after load event has completed.

Fix race condition when resolving performanceTiming.loadEventEnd [Attempt 2]

---

build-system/global-configs/canary-config.json

Start FIE CSS experiment in Canary.

Set fie-css-cleanup to 1% in canary

---

test/integration/test-amphtml-ads.js

we might be able to bring back our BTF tests after recent test isolation clean ups. 
especially we already had a success of #23500
for #21311

Am I lucky today?

---

src/inabox/inabox-services.js

polyfill is already installed in 
https://github.com/ampproject/amphtml/blob/f535df85e56a37266012fbe9ad559f0c1ec787c5/src/inabox/amp-inabox.js#L21

Remove a duplicated polyfill import for inabox.

---

build-system/tasks/lint.js

This PR uses (and prints) relative paths instead of absolute paths during `gulp lint`. It makes the output of `gulp lint` more readable, and makes it much easier to copy-paste filenames from the error / warning results in order to edit code, run tests, etc.

🏗 Use relative paths during lint checks

---

.github/ISSUE_TEMPLATE.md

Added a few tips and resources to make it easier for people to submit isolated repros on bug reports.

Update issues template with tips for debugging endpoints

---

build-system/compile/compile.js
build-system/compile/log-messages.js
build-system/compile/single-pass.js
build-system/tasks/build.js
build-system/tasks/dist.js
build-system/tasks/helpers.js

Also does some cleanup, particularly in a large promise chain that can be simplified with `async/await`.

🏗 Always format extracted messages on dist

---

extensions/amp-analytics/0.1/events.js
extensions/amp-analytics/0.1/instrumentation.js
extensions/amp-analytics/0.1/requests.js
extensions/amp-analytics/0.1/test/test-analytics-group.js
extensions/amp-analytics/0.1/test/test-analytics-root.js
extensions/amp-analytics/0.1/test/test-events.js
extensions/amp-analytics/0.1/test/test-instrumentation.js
extensions/amp-analytics/0.1/test/test-visibility-manager.js

save some bytes and have easier code search!

♻️ Analytics event type

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json
src/inabox/amp-inabox.js
tools/experiments/experiments.js

Issue https://github.com/ampproject/amphtml/issues/23573
Disable load chunking for inabox.

Experiment to disable load chunking for inabox runtime

---

build-system/build.conf.js

- removes unwanted array includes polyfill from module compatible scripts

Removing array includes from module compatible scripts

---

build-system/tasks/presubmit-checks.js
spec/amp-localstorage.md

There were several discussions on this topic, hope this clarifies our policy on future localStorage usage. Let me know if this is a good place to add the doc. 
cc @cramforce @mrjoro

localStorage usage Guideline

---

build-system/tasks/vendor-configs.js

Don't compile test vendor JSONs, specifically `_fake_.json`
cc @zhouyx for review :)

✨ Dont compile test vendor JSONs

---

extensions/amp-carousel/0.1/scrollable-carousel.js
extensions/amp-carousel/0.1/slidescroll.js
extensions/amp-carousel/0.1/test/test-scrollable-carousel.js
extensions/amp-carousel/0.1/test/test-slidescroll.js
extensions/amp-consent/0.1/consent-ui.js
extensions/amp-consent/0.1/test/test-consent-ui.js
extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
extensions/amp-fx-flying-carpet/0.1/test/test-amp-fx-flying-carpet.js
extensions/amp-image-slider/0.1/amp-image-slider.js
extensions/amp-image-viewer/0.1/amp-image-viewer.js
extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
extensions/amp-lightbox/0.1/amp-lightbox.js
extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
extensions/amp-pan-zoom/0.1/test/test-amp-pan-zoom.js
extensions/amp-sidebar/0.1/amp-sidebar.js
extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
extensions/amp-story/0.1/test/test-amp-story.js
extensions/amp-story/1.0/amp-story-embedded-component.js
extensions/amp-story/1.0/amp-story-page-attachment.js
src/base-element.js
src/custom-element.js
src/service/owners-impl.js
src/service/resources-impl.js
test/unit/test-custom-element.js

This PR moves all schedule* methods from resources to owners.

More refactoring of resources-impl to owners-impl

---

contributing/building-an-amp-extension.md
extensions/amp-carousel/0.1/scrollable-carousel.js
extensions/amp-carousel/0.1/slidescroll.js
extensions/amp-consent/0.1/amp-consent.js
extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
extensions/amp-image-slider/0.1/amp-image-slider.js
extensions/amp-image-viewer/0.1/amp-image-viewer.js
extensions/amp-lightbox/0.1/amp-lightbox.js
extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
extensions/amp-story/1.0/amp-story-page-attachment.js
src/base-element.js
src/service/owners-impl.js
src/service/resources-impl.js

Moving implementation to owners-impl is intended to be done on  a separate PR.

Sever remaining owners service method from resources

---

build-system/app-utils.js

I believe it is no longer in use.

Remove reference to inabox lite

---

build-system/pr-check/checks.js

Synchronize calls to reportAllExpectedTests()

---

test/unit/test-xhr.js

Skip flaky xhr test

---

extensions/amp-access/0.1/test/test-amp-access-iframe.js
extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-rtc.js
extensions/amp-form/0.1/test/test-amp-form-textarea.js
extensions/amp-form/0.1/test/test-form-validators.js
extensions/amp-form/0.1/test/test-form-verifiers.js
extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
extensions/amp-web-push/0.1/test/test-web-push-permission-dialog.js
extensions/amp-web-push/0.1/test/test-web-push-service.js
extensions/amp-youtube/0.1/test/test-amp-youtube.js
test/unit/inabox/test-inabox-messaging-host.js
test/unit/test-chunk.js
test/unit/test-custom-element.js
test/unit/test-font-stylesheet-timeout.js
test/unit/test-form.js
test/unit/test-resource.js
test/unit/test-runtime.js
test/unit/test-viewport.js
testing/describes.js

Change all usages of Object.defineProperty to sandbox.defineProperty in tests

---

test/unit/test-dom.js
testing/describes.js

Introduce sandbox.deleteProperty

---

test/unit/test-friendly-iframe-embed.js

No longer an issue. Re-enable test.

Re-enable skipped test in test-friendly-iframe-embed

---

src/service/navigation.js
src/service/url-impl.js
test/unit/test-navigation.js
testing/fake-dom.js

Fixes https://github.com/ampproject/amphtml/issues/22376.

🐛 Use source relative URLs in navigateTo

---

extensions/amp-story/0.1/amp-story-base-layer.js

Re-words the description to remove double usage of the word "from".

📖 Updates AmpStoryBaseLayer description

---

build-system/compile/single-pass.js

🐛 Clean up `$weak$` files after single pass compilation

---

extensions/amp-bind/0.1/amp-state.js
extensions/amp-bind/0.1/bind-impl.js

Don't ignore falsy values in amp-state

---

build-system/tasks/lint.js

🏗🚮 Delete deprecation warning for `gulp lint --local-changes`

---

src/service/video-manager-impl.js

🚀 Clean up video manager listeners on dispose

---

build-system/tasks/bundle-size.js
package.json
yarn.lock

Progress on #21275 (see issue for work plan)
Fixes #23711

🏗 Report brotli bundle-size

---

extensions/amp-accordion/0.1/amp-accordion.js

Closes https://github.com/ampproject/amphtml/issues/22381.

Add user warning to prevent tap actions registered on amp-accordion headers

---

extensions/amp-story/1.0/test/validator-amp-story-video-controls.html
extensions/amp-story/1.0/test/validator-amp-story-video-controls.out
extensions/amp-story/1.0/test/validator-amp-story-video-error.html
extensions/amp-story/1.0/test/validator-amp-story-video-error.out
extensions/amp-video/validator-amp-video.protoascii

Disallow controls attribute on amp story video elements.
Warning: technically a breaking change

Disallow controls attribute on amp story video elements.

---

extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md

These two features are no longer in Beta, they have been Launched

updated beta to launched

---

extensions/amp-analytics/linker-id-forwarding.md

Duplicate of #21470, original contributor @kotlowskip was having CLA issues.
Fixes bad JSON example.

Fix linker-forwarding examples.

---

spec/amp-html-format.md

Fixes issue [#2274](https://github.com/ampproject/docs/issues/2274).

fixed links

---

extensions/amp-script/amp-script.md

Link to supported values for layout

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json
src/inabox/amp-inabox.js
tools/experiments/experiments.js

Fully launch inabox-css-cleanup

---

extensions/amp-access/amp-access.md

The link takes to you ampbyexample.com. This is happening with most of the components, not only with this one.
- Improve …

📖 Link to example page is broken

---

build-system/tasks/report-test-status.js
build-system/travis.js

Partial fix for https://github.com/ampproject/amp-github-apps/issues/85

🏗 Send the Travis job URL to the test status bot

---

extensions/amp-bind/0.1/test/validator-amp-bind.html
extensions/amp-bind/0.1/test/validator-amp-bind.out
validator/testdata/amp4email_feature_tests/amp_form.out
validator/validator-main.protoascii

Allow input[type] binding in AMP format

---

extensions/amp-analytics/0.1/test/vendor-requests.json
extensions/amp-analytics/0.1/vendors/gemius.js

- Add additional parameters for Gemius amp-analytics

Add additional parameters for Gemius amp-analytics

---

src/service/navigation.js

Fixes #20998 
I'll clean up the analytics linker code in following PR.

🐛 Do not apply anchor mutator for internal navigation

---

spec/amp-var-substitutions.md

Closes #19320 
I also created a new section that documents all variables from other AMP components. PTAL Thank you

Add VARIANT doc to the variables list

---

test/integration/test-amp-ad-fake.js

for #23755
it's a dup of test-amphtml-ads.js

Remove duplicated test in test-amp-ad-fake.js

---

build-system/tasks/bundle-size.js

Step 2.i. of the proposed shift in #21275
Step 2.ii. will come in ~1 month

🏗 Report brotli bundle-size on pull requests

---

examples/visual-tests/amp-story/amp-story-tooltip.html
extensions/amp-story/1.0/amp-story-embedded-component.js

Fixes https://github.com/ampproject/amphtml/issues/19428

[amp-story] Hides tool tip next arrow overlay when you're on the last page

---

src/sanitation.js
test/unit/test-purifier.js

Allow [itemprop] in amp-mustache-0.2

---

bundles.config.js
examples/standalone.amp.html
extensions/amp-standalone/0.1/amp-standalone.js
extensions/amp-standalone/0.1/test/test-amp-standalone.js
extensions/amp-standalone/README.md
src/amp.js
src/service/platform-impl.js
src/services.js
src/standalone.js
test/unit/test-platform.js

Fixes https://github.com/ampproject/amphtml/issues/3835
Fixes https://github.com/ampproject/amphtml/issues/3861
This PR approached the problem by adding a dedicated extension for this use case to avoid increasing bundle size for code that will run in only a few use-cases.
/to @sparhami 
/to @sebastianbenz

Fix navigation in PWAs / webpages saved to homescreen

---

ads/navegg.md

📖Update navegg.md

---

src/clipboard.js

Fixes https://github.com/ampproject/amphtml/issues/17023

[amp-story] Fix copy-link-to-clipboard bug in Firefox

---

spec/amp-html-layout.md

This PR replaces the [original one](https://github.com/ampproject/amphtml/pull/20650) as the link was failing and I couldn't update the other.

📖 Add tip to AMPHTML layout page that leads to a quick demonstration (and remove unneeded TOC)

---

extensions/amp-sidebar/0.1/amp-sidebar.js

🐛Fixes iOS Safari status bar compensation height

---

extensions/amp-script/0.1/test-e2e/test-amp-script.js
extensions/amp-script/0.1/test/integration/test-amp-script.js
extensions/amp-script/amp-script.md
tools/experiments/experiments.js

amp-script: Clean up experiment code and docs

---

src/service/resource.js
test/unit/test-resource.js

Fixes https://github.com/ampproject/amphtml/issues/20049.

🐛 Always remeasure after build

---

examples/amp-script/vue-todomvc.amp.html

Add `sandbox="allow-forms"` to `<amp-script>`. The working demo is [here](https://repl.it/repls/BuoyantBarrenThing).

amp-script: Update Vue.js TodoMVC example

---

build-system/eslint-rules/unused-private-field.js

Fixes https://github.com/ampproject/amphtml/issues/17803

🐛 Support destructuring in private props linter

---

extensions/amp-ad/0.1/amp-ad-ui.js
src/base-element.js
src/service/resources-impl.js
test/unit/test-resources.js

Partial for #23926.
Closes #23619.

Resize events: report false positives for user activation

---

extensions/amp-experiment/0.1/variant.js
extensions/amp-experiment/1.0/amp-experiment.js
extensions/amp-experiment/1.0/test/test-amp-experiment.js
extensions/amp-experiment/1.0/variant.js
extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
extensions/amp-viewer-integration/0.1/messaging/messaging.js
src/impression.js
src/runtime.js
src/service/ampdoc-impl.js
src/service/core-services.js
src/service/viewer-impl.js
test/unit/test-ampdoc.js
test/unit/test-runtime.js
test/unit/test-viewer.js
testing/describes.js

Move parameters to ampdoc from viewer

---

examples/visual-tests/amphtml-ads/amp-inabox-static.html

To be consistent with other iframes

Add common iframe attributes to inabox visual test template.

---

test/unit/test-action.js
test/unit/test-cid.js
test/unit/test-history.js
test/unit/test-storage.js
test/unit/test-vsync.js

Minor cleanup: switch some tests to describes

---

extensions/amp-story/1.0/test/test-amp-story.js

```
DESCRIBE => AmpDocService
DESCRIBE => amp-story
DESCRIBE =>  
DESCRIBE => amp-story branching
IT => "after each" hook for "should navigate to the correct previous page after navigating away"
✗ Error: Blocked a frame with origin "http://localhost:9876" from accessing a cross-origin frame.
at experimentToggles (home/travis/build/ampproject/amphtml/src/experiments.js:127:10)
at isExperimentOn (home/travis/build/ampproject/amphtml/src/experiments.js:73:19)
at toggleExperiment (home/travis/build/ampproject/amphtml/src/experiments.js:95:23)
at Context.<anonymous> (home/travis/build/ampproject/amphtml/extensions/amp-story/1.0/test/test-amp-story.js:1583:9)
HeadlessChrome 76.0.3809 (Linux 0.0.0) AmpDocService amp-story   amp-story branching "after each" hook for "should navigate to the …
```

Remove flaky amp-story branching test

---

src/service/performance-impl.js
test/unit/test-performance.js

As we agreed offline, we will be collecting the document ready signal to study the delay of DOM Content Loaded.

Collect document ready signal

---

src/service/variable-source.js
test/manual/amp-analytics/analytics-nav-timing.html

Closes #23534 
cc @jonkeller @jeffkaufman

Resolve navTiming variable earlier if possible

---

extensions/amp-mustache/0.1/amp-mustache.js
extensions/amp-mustache/0.2/amp-mustache.js

Follow-up to #23877.
/to @lannka

Remove @suppress from amp-mustache

---

examples/amp-viewer-gpay-button.amp.html
examples/amp-viewer-gpay-inline.amp.html
extensions/amp-viewer-gpay-button/0.1/amp-viewer-gpay-button.js
extensions/amp-viewer-gpay-button/0.1/test/test-amp-viewer-gpay-button.js
extensions/amp-viewer-gpay-button/0.1/test/validator-amp-viewer-gpay-button.html
extensions/amp-viewer-gpay-button/0.1/test/validator-amp-viewer-gpay-button.out
extensions/amp-viewer-gpay-button/amp-viewer-gpay-button.md
extensions/amp-viewer-gpay-button/validator-amp-viewer-gpay-button.protoascii
extensions/amp-viewer-gpay-inline/0.1/amp-viewer-gpay-inline.js
extensions/amp-viewer-gpay-inline/0.1/test/test-amp-viewer-gpay-inline.js
extensions/amp-viewer-gpay-inline/0.1/test/validator-amp-viewer-gpay-inline.html
extensions/amp-viewer-gpay-inline/0.1/test/validator-amp-viewer-gpay-inline.out
extensions/amp-viewer-gpay-inline/amp-viewer-gpay-inline.md
extensions/amp-viewer-gpay-inline/validator-amp-viewer-gpay-inline.protoascii

Creates the skeleton code for the payment widgets with updated names
After code implementation and service files are added, legacy payment extensions will be removed

Extension skeleton code for payment widgets

---

build-system/tasks/e2e/amp-driver.js

This helped me to debug an e2e failure on Travis.

Print DOM snapshot while e2e tests timed out.

---

extensions/amp-viewer-integration/0.1/test/test-variable-service.js
extensions/amp-viewer-integration/0.1/variable-service.js
src/service/url-replacements-impl.js
test/unit/test-url-replacements.js

🐛 Move FRAGMENT_PARAM out of amp-viewer-integration

---

ads/directadvert.js
ads/directadvert.md

Added: 
- serverName
- canonicalUrl
- referrer

✨amp-ads: Added optional params for Directadvert network

---

src/custom-element.js
src/element-service.js
src/service/custom-element-registry.js
test/unit/test-custom-element-registry.js
test/unit/test-custom-element.js
test/unit/test-extensions.js
test/unit/test-friendly-iframe-embed.js
test/unit/test-runtime.js

Rename ampExtendedElements to __AMP_EXTENDED_ELEMENTS

---

extensions/amp-sidebar/amp-sidebar.md

Updating Story amp-sidebar width documentation.

Updating Story amp-sidebar width documentation.

---

build-system/check-package-manager.js

We use `check-package-manager.js` to run several checks on the AMP toolchain (`node`, `yarn`, `gulp`,  `python`) during development.
A couple of the checks for `gulp-cli` assume that the tool was installed using `yarn global add`, as our dev docs currently [recommend](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md#one-time-setup):
- The `gulp` executable path is valid
- The `gulp-cli` command line tool is installed
The resulting warnings can be annoying to those who are using alternatives like [npx](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b), [Lando](https://docs.lando.dev/guides/lando-info.html#using-javascript-nodejs), or [Volta](https://www.notionjs.com/).
- Changes the …

🏗 Fixes to `check-package-manager.js`

---

extensions/amp-a4a/0.1/callout-vendors.js

🐛 Update callout-vendors.js for Navegg

---

extensions/amp-story/1.0/amp-story-draggable-drawer-header.css

Attachment close button icon no-repeat.
Fixes #22982

Story attachment close button icon no-repeat.

---

extensions/amp-a4a/0.1/callout-vendors.js

Mapped the CONSENT_STATE & CONSENT_STRING macros into the Criteo callout URL.

✨ Added support of consent macros in Criteo callout url

---

extensions/amp-analytics/0.1/vendors/googleanalytics.js
extensions/amp-analytics/0.1/vendors/gtag.js

As agreed, here's the default config that need publisher to opt-in to use
@jeffjose please help to test the config with your story example. Thanks.

Add story default config

---

extensions/amp-consent/0.1/consent-ui.js

🐛 <amp-consent> Hide placeholder when the iframe is removed

---

build-system/tasks/presubmit-checks.js
extensions/amp-a4a/0.1/test/test-a4a-var-source.js
extensions/amp-viewer-integration/0.1/test/integration/test-amp-webview-viewer-integration.js
src/chunk.js
src/service/performance-impl.js
src/service/resources-impl.js
test/unit/test-chunk.js
test/unit/test-document-info.js
test/unit/test-performance.js
test/unit/test-resources.js
test/unit/test-url-replacements.js

Reverts ampproject/amphtml#23778
This PR broke unit tests on master: https://travis-ci.org/ampproject/amphtml/builds/575034978
PR check from yesterday was green: https://travis-ci.org/ampproject/amphtml/builds/574516335

Revert "Relatively drastically improve FCP for docs with a hidden body."

---

build-system/dep-check-config.js
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/story-ad-localization.js
extensions/amp-story-auto-ads/0.1/test/test-story-ad-localization.js

Part 2 of continuing effort to move to smaller classes and have better testing.
Moves localization related logic to its own class.
Part of #23710

♻️Story ads: move localization

---

extensions/amp-viewer-integration/0.1/test/test-touch-handler.js
extensions/amp-viewer-integration/0.1/touch-handler.js

Viewer touch handler: only try to cancel events when cancelable

---

extensions/amp-access/0.1/test/test-jwt.js
src/3p-frame.js
src/experiments.js
src/log.js
test/unit/test-experiments.js

Prefix remaining window globals in src/

---

build-system/amp.extern.js
extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
extensions/amp-ad/0.1/amp-ad-3p-impl.js
extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js
src/iframe-helper.js
test/unit/test-iframe-helper.js
tools/experiments/experiments.js

Partial for #24110.
Related to #24113.

Implement iframe pausing for 3p ads

---

extensions/amp-subscriptions/amp-subscriptions.md

amp-subscriptions document `pingbackAllEntitlements` flag

📖 amp-subscriptions document pingbackAllEntitlements flag

---

build-system/amp.extern.js
build-system/eslint-rules/window-property-name.js
extensions/amp-auto-ads/0.1/test/test-ad-strategy.js
extensions/amp-auto-ads/0.1/test/test-placement.js
src/3p-frame.js
src/custom-element.js
src/error.js

Partial for #24051.
- Check `builtins/` folder and MAKE_NAMING_CONSISTENT.

♻️ Clean up window global prefixing

---

extensions/amp-a4a/0.1/callout-vendors.js

Request URL was wrong, causing a CORS error.

🐛Navegg: Adjusted Endpoint Req

---

examples/amphtml-ads/scrollbound-animation-ad.a4a.html

revert some unwanted changes 
Now I think we might need a test for those example files to make sure they are all valid AMP :-)

fix scrollbound animation ad example.

---

build-system/tasks/extension-helpers.js

Addresses https://github.com/ampproject/amphtml/pull/24193#issuecomment-524964978
Follow up to #24193

🏗 Allow the simultaneous use of `--extensions` and `--extensions_from`

---

build-system/global-configs/experiments-config.json
src/inabox/inabox-services.js
src/inabox/inabox-viewport.js

for #22867
This generate a amp4ads-v0.js with size of 232KB

Create RTV experiment for INABOX_LITE

---

extensions/amp-story/1.0/amp-story-draggable-drawer-header.css
extensions/amp-story/1.0/amp-story-page-attachment.js

Fix story attachment dark theme.

Fix story attachment dark theme.

---

src/service/performance-impl.js
test/unit/test-performance.js

Follow changes in the Event Timing API in Chrome 77.

---

extensions/amp-story/1.0/amp-story-system-layer.css
extensions/amp-story/1.0/progress-bar.js

Increase margin in progress bar segments & decrease debounce rate
temp demo: https://stamp-animation.firebaseapp.com/examples/amp-story/progressbar-overflow.html
/cc @hongwei1990

🖍Progressbar overflow tweaks

---

extensions/amp-carousel/amp-carousel.md

AMP for Email doesn't currently support amp-carousel 0.2.

📖 Update amp-carousel 0.2 doc formats

---

extensions/amp-carousel/0.1/amp-carousel.md
extensions/amp-carousel/amp-carousel.md

Document that amp-carousel autoplay stops on interaction

---

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js

Changes amp-subscriptions-google to return non-granting entitlements if that's all it can find.
Precedence is now
1. granting entitlement
1. first non-granting entitlement
1. null if no entitlements
This allows pingback on non-granting entitlements (eg registration)

Fix return of non-granting entitlements

---

build-system/dep-check-config.js
examples/amp-story/ad-development.html
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/test/story-mock.js
extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
src/utils/array.js

Introduces new `development` mode for amp-story-auto-ads if you include a `development` attribute on the tag.
```html
<amp-story-auto-ads id="i-amphtml-demo-1" development>
...
</amp-story-auto-ads>
```
Really helpful for iterative ad development, and will be used in story preview tool.

🎇Story Ads: Development mode

---

builtins/amp-img.js
test/unit/test-amp-img.js

Reverts ampproject/amphtml#23880

Revert "🐛Prevent automatic sizing for amp-imgs with intrinsic layout"

---

ads/readmo.js
ads/readmo.md
examples/ads.amp.html

This PR introduces
- A new optional param for customizing the unit title
- Tweaks to `observeIntersection` for better measurement 
- Copy changes to the documentation
@calebcordry

🔥🐛update readmo script and example [amp-embed type=readmo]

---

src/base-element.js
src/custom-element.js

It's only set on the custom element, never on the BaseElement.

♻️ Move layoutScheduleTime to CustomElement class

---

extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js

🐛 Experiment for fixing height inconsistency between 3p and a4a paths for AdSense ads

---

extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-auto-ads/0.1/amp-auto-ads.js
extensions/amp-auto-ads/0.1/placement.js
extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
extensions/amp-auto-ads/0.1/test/test-placement.js

See https://github.com/ampproject/amphtml/issues/24168.

🐛Set up experiment for delegating responsive sizing from amp-auto-ads to network specific amp-ad implementation

---

extensions/amp-list/amp-list.md

Wording was confusing - clarified it a bit.

clarified AMP applies CSS to overflow attribute

---

examples/visual-tests/amp-story/amp-story-consent.js
test/visual-diff/visual-tests

Adding accept/reject story consent interactive tests.

Story consent interactive tests.

---

examples/amp-story/analytics.html
examples/amp-story/bookendv1.json
extensions/amp-story/1.0/bookend/amp-story-bookend.js
extensions/amp-story/1.0/bookend/bookend-component.js
extensions/amp-story/1.0/bookend/components/article.js
extensions/amp-story/1.0/bookend/components/bookend-component-interface.js
extensions/amp-story/1.0/bookend/components/cta-link.js
extensions/amp-story/1.0/bookend/components/heading.js
extensions/amp-story/1.0/bookend/components/landscape.js
extensions/amp-story/1.0/bookend/components/portrait.js
extensions/amp-story/1.0/bookend/components/text-box.js
extensions/amp-story/1.0/story-analytics.js
extensions/amp-story/1.0/test/test-amp-story-bookend.js
extensions/amp-story/1.0/variable-service.js

Closes #23893
Adds a new analytics event trigger `story-bookend-click` and variables: 
* `storyBookendComponentPosition`
* `storyBookendComponentType`
* `storyBookendTargetHref`

📈 Add custom analytics event for bookend clicks

---

ads/readmo.js
ads/readmo.md
examples/ads.amp.html

Need to make `url` a required field for ReadMo modules. I've updated the docs and example. @calebcordry

🐛🔥📖make url required; update docs

---

src/inabox/inabox-services.js

Enable RTV experiment for inabox-resources-lite

---

extensions/amp-nexxtv-player/0.1/test/test-amp-nexxtv-player.js

- fixed errors in travis build issue mentioned here #24351 
- removed tests which are already covered by validation test
- added test for responsive layout
- added test for unlayoutCallback

🐛 ✅ 🚮fixed build errors in amp-nexxtv-player and added additional test

---

extensions/amp-list/amp-list.md

- Clarified overflow section
- Added styling to example
- resolves issue [#24374](https://github.com/ampproject/amphtml/issues/24374)

📖added information on overflow behavior 

---

extensions/amp-story/1.0/amp-story-page.js

TLDR:
https://github.com/ampproject/amphtml/pull/23794 introduced better error handling for story videos. This new code will display the error message without trying to play the video if it has no sources.
Calling `preloadMedia_` before `playMedia_` ensures sources are set by the media pool, and avoids the early return.
More context:
This isn't the usual code path (and I didn't know this one existed tbh), and only happens when the `amp-video` has no height (`resource.isDisplayed()` returns false) when we first try to play it. In this case, we don't set the video sources to make sure nothing loads, which saves users data. A few frames later the video is detected as visible, and we try to play it. This PR ensures that, in this very case, the sources are added back before trying to play it. …

Ensures story video has sources before playing to avoid early error.

---

validator/validator-main.protoascii

- cl/268074143 Revision bump for #22903

cl/268074143 Revision bump for #22903

---

extensions/amp-carousel/amp-carousel.md

Fix typo, change `The is` to `This is`

📖 Fix typo

---

build-system/tasks/bundle-size.js

This should help debug cases like https://github.com/ampproject/amphtml/pull/24418#issuecomment-529676896

🏗 Add a `--on_local_build` mode for `gulp bundle-size`

---

build-system/tasks/bundle-size.js
package.json
yarn.lock

Preconditions before merging:
Post-actions:

🏗 Use the bundle-size app to store new sizes

---

third_party/subscriptions-project/OWNERS.yaml

Add OWNERS.yaml for subscriptions project

---

src/log.js

🐛 Message extraction: Fallback on unserialize objects

---

build-system/server/app.js
package.json
yarn.lock

Reverts ampproject/amphtml#24527
https://github.com/ampproject/amphtml/issues/24558

Revert "Soft DNS rewrite for various dev envelops"

---

examples/amp-script/example.amp.html
extensions/amp-script/0.1/amp-script.js
extensions/amp-script/0.1/test/unit/test-amp-script.js
package.json
yarn.lock

Fixes #22410.
Also upgrade worker-dom to `0.19.0`. Documentation to follow.

amp-script: Support setState/getState in worker

---

test/integration/test-amphtml-ads.js

Skip flaky "more real ads" test in test-amphtml-ads.js

---

extensions/amp-script/OWNERS.yaml

Update amp-script owners

---

builtins/amp-img.md
extensions/amp-anim/amp-anim.md

Fully resolves issue [#1951](https://github.com/ampproject/amp.dev/issues/1951)

📖added src info for emails

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

✨ SwG release 0.1.22.69
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.69

✨ SwG release 0.1.22.69

---

src/inabox/inabox-resources.js
src/ini-load.js
src/service/resources-impl.js
src/service/resources-interface.js
test/integration/test-amphtml-ads.js

Fix INABOX_LITE resources ready-scan signal.

---

extensions/amp-analytics/0.1/test/test-visibility-manager.js
src/service/vsync-impl.js
test/unit/test-vsync.js

Remove globalDocumentState from vsync

---

test/integration/test-amphtml-ads.js

Flaking by timing out on Firefox (#24657)

✅ Skip BTF integration tests

---

extensions/amp-story/OWNERS.yaml

> Prefixing a user or team with # will @ mention that owner in a comment on any PR which touches those files/directories

Updating the amp-story owners file.

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

✨ SwG release 0.1.22.70
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.70

✨ SwG release 0.1.22.70

---

ads/ix.md

Corrected a few typos in the file
🐛 Bug fix …

📖 Updated IX.md: Corrected a few typos

---

extensions/amp-analytics/OWNERS.yaml

Update OWNERS to contain analytics working group instead of individuals.

📖 Update owners

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

✨ SWG release 0.1.22.72
- clean up gulp assets 
- Fixes a flaky dialog test 
- Update owner for api directory, so all changes to api code needs owner's approval. 
- Remove unused minimatch to solve the security alert 
- Replace gulp plugin gulp-util b/c it is deprecated 
- Remove deprecated messaging APIs

✨ SWG release 0.1.22.72

---

ads/blade.js

- fix bladeOnLoad callback function
- fix bladeConfig

🐛 amp-ad type blade - fix bladeOnLoad callback

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json
examples/amphtml-ads/many-ads.host.html
src/inabox/amp-inabox.js
tools/experiments/experiments.js

Remove code for inabox chunking experiments

---

extensions/amp-consent/OWNERS.yaml
extensions/amp-instagram/OWNERS.yaml
extensions/amp-subscriptions-google/OWNERS.yaml
extensions/amp-subscriptions/OWNERS.yaml

Cleanup old owners assignments.

Cleanup stale owners file entries

---

package.json

i probably forgot to add -D when installing

babel-preset-modules should be a devDependency

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

See https://github.com/ampproject/amphtml/pull/24409.

Ramp up inconsistent responsive height selection fix experiment to 5%.

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

See https://github.com/ampproject/amphtml/issues/24168.

Ramp up experiment for using responsive amp-ad in amp-auto-ads to 5%.

---

build-system/OWNERS.yaml
build-system/global-configs/OWNERS.yaml

Make wg-approvers owner of experiments

---

examples/OWNERS.yaml
test/OWNERS.yaml

copy-pasted the list from https://github.com/orgs/ampproject/teams/working-groups/teams

⚡️Add all WGs as owners for common folders

---

build-system/eslint-rules/window-property-name.js

Addresses https://github.com/ampproject/amphtml/pull/24062#pullrequestreview-297137725

🏗🐛 Resolve paths in `window-property-name` custom `eslint` rule

---

extensions/amp-fx-flying-carpet/OWNERS.yaml
extensions/amp-viqeo-player/OWNERS.yaml

Fixes an accidental commit on #24828

🐛Fixes accidental ownership swap

---

src/service/viewer-impl.js

Ref: b/113673017
Fixes https://github.com/ampproject/amphtml/issues/24914

Restore visibility methods as restricted in the viewer for viewer-integration fixes

---

build-system/global-configs/experiments-config.json

Extend experiments A and B by 1 month

---

build-system/tasks/bundle-size.js

Related to https://github.com/ampproject/amp-github-apps/issues/271

🏗 Remove unnecessary .json from bundle-size /store URL

---

build-system/tasks/e2e/package.json
build-system/tasks/e2e/yarn.lock

Revert "📦 Update dependency selenium-webdriver to v4.0.0-alpha.5"

---

test/fixtures/e2e/amphtml-ads/amp-ad-exit.amp.html

Remove extra css for amp-ad-exit e2e test

---

ads/inabox/inabox-host.js

Better inabox console message when message.source is null

---

extensions/amp-animation/0.1/test-e2e/test-amp-animation.js
test/e2e/test-adchoices.js
test/fixtures/e2e/amp-animation/simple.html
test/fixtures/e2e/amphtml-ads/text.html

Similar purpose: We want to use e2e to ensure amp-animation does not broke horribly within amp4ads (inabox)

Amp animation e2e test

---

extensions/amp-analytics/OWNERS

Follow up to #23958. @avimehta this should prevent automatic PR review requests. We can always ping you for help manually : ) Thanks

Update amp-analytics owner file

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.75
- 🐛 Disables fixed layer (#687)

SwG Release 0.1.22.75

---

extensions/amp-animation/0.1/test-e2e/test-amp-animation.js

It is flaky in shadow environment. Disable for now to debug.

Disable amp-animation for shadow for flakiness

---

extensions/amp-subscriptions-google/0.1/test-e2e/test-amp-subscriptions-google.js

See https://travis-ci.org/ampproject/amphtml/jobs/598248437#L2053-L2063
This has consistently be failing in the last 10 or so test builds.
/to @chenshay

Skip flaky subscriptions e2e test

---

OWNERS

Also adds @mrjoro as an owner of markdown and OWNERS files

🏗 Update all markdown files to be owned by wg-outreach

---

extensions/amp-ad-custom/amp-ad-custom.md

s/adexample.com/adnetwork.com/

Fixing typo

---

extensions/amp-subscriptions-google/OWNERS

🏗 Makes Yuan an owner of SwG extension

---

spec/email/OWNERS

Add wg-amp4email as OWNERS for spec/email

---

ads/insticator.md

📖 Minor updates to the insticator.md read me file:
- updated component required parameters description
- added Insticator embed description
cc @calebcordry 
cc @triso07

Updates to the .md read me file for <amp-embed type="insticator">

---

extensions/amp-ad-custom/amp-ad-custom.md

Formatting a code-block

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Ramp up the `sidebar-swipe-to-dismiss` experiment to 100% of prod.

Ramp up experiment for sidebar swipe-to-dismiss

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.78

---

.github/ISSUE_TEMPLATE/intent-to-implement--i2i-.md

Fixes Issue #24083 - Incorrect links on 'intent-to-implement--i2i-.md'.
(Second PR ever, please provide feedback as needed)

Issue 24083 - Fixing CONTRIBUTING.md on I2I 

---

extensions/amp-story-auto-ads/0.1/_locales/en-GB.js
extensions/amp-story-auto-ads/0.1/_locales/en.js

Somewhere along the line I think we lost the 'now' part.
@newmuis is there something I should do here for the other translations?

Fix shop now CTA 

---

extensions/amp-script/amp-script.md

amp.dev has same issue.
https://amp.dev/documentation/components/amp-script/?format=websites

<amp-script /> document's example typo

---

extensions/amp-form/0.1/amp-form.js
extensions/amp-form/0.1/test/test-amp-form.js
extensions/amp-list/0.1/amp-list.js
extensions/amp-list/0.1/test/test-amp-list-load-more.js
extensions/amp-list/0.1/test/test-amp-list.js
src/ssr-template-helper.js
test/unit/test-ssr-template-helper.js

Previous naming was confusing and potentially misleading.

♻️📖Rename methods in SsrTemplateHelper

---

build-system/compile/bundles.config.js
build-system/compile/check-for-unknown-deps.js
build-system/compile/compile.js
build-system/compile/single-pass.js
test/unit/test-fixed-layer.js

Fixes #24283.
Blocked by:
- ~https://github.com/ampproject/amphtml/issues/24297~
- ~https://github.com/ampproject/amphtml/issues/24281~
- ~https://github.com/ampproject/amphtml/issues/24253~

🏗 Check for unknown dependencies during after compilation

---

extensions/amp-viewer-integration/CAPABILITIES.md
extensions/amp-viewer-integration/amp-doc-viewer-api.md
src/service/viewport/viewport-impl.js
test/unit/test-viewport.js

Switch iOS iframe scrolling mode configuration to capabilities

---

build-system/tasks/bundle-size.js

Related to https://github.com/ampproject/amp-github-apps/issues/271

🏗 Remove unnecessary .json from bundle-size /report URL

---

validator/nodejs/package.json

Release amphtml-validator with node 8 support
Related to #25161 and #25278 
@rsimha 
/cc @ampproject/wg-caching

amphtml-validator v1.0.29 with node 8 support

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.79

---

extensions/amp-access-scroll/0.1/scroll-bar.js

Update source url for Scroll scrollbar iframe to new endpoint

🐛 Update Scroll UI to reference new url

---

extensions/amp-live-list/amp-live-list.md

As several partners have hit an issue with this, I felt like we should document the issue until it is fixed.

📖add warning about slow updates with amp-live-list

---

OWNERS

🏗 Remove `@rcebulko` as owner of all OWNERS files

---

extensions/amp-recaptcha-input/amp-recaptcha-input.md

`media` is for things like video players.

📖 Change amp-recaptcha-input category to dynamic-content

---

extensions/amp-auto-ads/0.1/amp-auto-ads.js
extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js

Fixing the issue which puts 'no-fill' attribute on the base attributes.

🐛 Fix no filling all amp adsense ads.

---

extensions/amp-viewer-integration/OWNERS

Add wg-viewers to owners for amp-viewer-integration

---

extensions/amp-viewer-integration/0.1/messaging/messaging.js

Add missing type annotation

---

extensions/amp-analytics/0.1/test/test-visibility-manager.js
extensions/amp-analytics/0.1/visibility-manager.js

Follow up on #25007 and #25321.

Fix visibility manager resolution in shadow doc mode

---

test/integration/test-amphtml-ads.js

Addresses https://github.com/ampproject/amphtml/issues/24657#issuecomment-548888417
Unblocks `master`
```
DESCRIBE => AMPHTML ad on AMP Page
DESCRIBE => BTF
DESCRIBE =>  
IT => should layout amp-img, amp-pixel, amp-analytics
✗ expected 1572626029399 to be below 1572626029144
Error
at AssertionError (node_modules/chai/chai.js:9449:7)
at Assertion.prototype.assert (node_modules/chai/chai.js:239:7)
at assertBelow (node_modules/chai/chai.js:1755:7)
at methodWrapper (node_modules/chai/chai.js:7824:5)
at Anonymous function (/home/travis/build/ampproject/amphtml/test/integration/test-amphtml-ads.js:407:5 <- /tmp/0bbb856b10c1c898095f46b6d3d3453d.browserify.js:102328:5)
at run (/home/travis/build/ampproject/amphtml/node_modules/core-js/modules/es6.promise.js:75:13 <- …
```

✅ Skip flaky BTF integration test

---

extensions/amp-link-rewriter/0.1/amp-link-rewriter.js

Remove access of ampdoc in AmpLinkRewriter's constructor.

---

validator/chromeextension/content_script.js

chromeextension: Fix regex test for amphtml

---

extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js

I think we're receiving badly ordered gestures, which is causing #22533.
Now, if we receive a subsequent gesture without first receiving the `first` gesture, we'll early exit. That should solve the bug. I'm also adding error reporting, so we can track down exactly how this is happening.

🐛 Attempt to fix LightboxGallery issue

---

src/inabox/inabox-resources.js
src/input.js
src/service/resources-impl.js
test/unit/test-input.js

inabox-lite: setup input mode classes.

---

extensions/amp-video-iframe/amp-video-iframe.md

Video.js integration takes a `<video>` element, Jwplayer integration takes a `jwplayer` instance object.

📖 Clarify readymade amp-video-iframe integration APIs

---

build-system/test-configs/dep-check-config.js
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/story-ad-page.js
extensions/amp-story-auto-ads/0.1/test/story-mock.js
extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js
extensions/amp-story/1.0/utils.js

Mostly moving code from one file to another, exposes a few new public methods to get page state, and a lot of new tests.
Sorry for the large PR, but not really a lot of new code (other than test).
Part of #23710

♻️Story Ads: move page related logic to its own class

---

validator/nodejs/README.md

Update version notes for recent releases.

Update version notes

---

tools/experiments/OWNERS

Fix typo in filename for OWNERS file

---

build-system/global-configs/canary-config.json

Re: https://github.com/ampproject/amphtml/issues/25203
Re: https://github.com/ampproject/amphtml/issues/24929

Enable layoutbox invalidate onscroll experiment in Canary

---

src/cookies.js
test/unit/test-cookies.js
tools/experiments/experiments.js

Fixes https://github.com/ampproject/amphtml/issues/25280
cc @choumx @jridgewell

Force cookies with SameSite=None to also include Secure

---

validator/package.json

www.ampproject.org redirects to amp.dev, updating description

Update url to amp.dev

---

extensions/amp-mowplayer/0.1/amp-mowplayer.js
extensions/amp-mowplayer/0.1/test/test-amp-mowplayer.js
extensions/amp-mowplayer/0.1/test/validator-amp-mowplayer.html
extensions/amp-mowplayer/0.1/test/validator-amp-mowplayer.out

Closes #24903 , replaces #25484

🐛 Update mowplayer version for `amp-mowplayer`

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Merge after https://github.com/ampproject/amphtml/pull/25210 (validator changes) lands in production.

Launch amp-mega-menu to 100% of canary and production

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Retire ios-scrollable-iframe experiment from launch configs

---

test/unit/test-amp-img.js
test/unit/test-resources.js

Closes https://github.com/ampproject/amphtml/issues/24512.

Add tests clarifying the behavior of layout intrinsic for amp-img

---

extensions/amp-viewer-integration/0.1/messaging/README.md

Neglected to do this in #24797

Update amp-viewer-messaging README

---

extensions/amp-auto-ads/0.1/amp-auto-ads.js
extensions/amp-auto-ads/0.1/placement.js
extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
extensions/amp-auto-ads/0.1/test/test-placement.js

See https://github.com/ampproject/amphtml/issues/24168.

✨ Launch the 'use responsive ads for responsive sizing in auto ads' experiment to a 5% holdback

---

ads/ix.md

Updated to include Multi-size Ad examples and parameters

📖 Updated to include Multi-size Ad examples

---

src/polyfills/custom-elements.js

Closure compiler was eliminating the `opt_ctor.call(instance)` line as useless. This had no real effect on us, because we're transpiling our code.
But, in a world where we shipped native `class` code to browsers, this would have resulted in us wrapping the `HTMLElement` class unnecessarily. Not the full polyfill, but the minimal polyfill.
Fixing this will allow us to eventually use no polyfill when we ship native classes.

🐛 Fix transpiled detection in CEv1 polyfill

---

extensions/amp-autocomplete/0.1/amp-autocomplete.js
extensions/amp-bind/0.1/amp-state.js
extensions/amp-list/0.1/amp-list.js
extensions/amp-next-page/0.1/amp-next-page.js
extensions/amp-user-location/0.1/config-loader.js
src/batched-json.js
test/unit/test-batched-json.js

As suggested by @jridgewell  in a [comment](https://github.com/ampproject/amphtml/pull/25489#discussion_r343897806).

♻️ Refactor `batchFetchJsonFor` by combining all options into an options bag. 

---

extensions/amp-bind/0.1/bind-impl.js

Send 'bindReady' even in dev mode

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

- Update dependency rollup to v1.26.5 (#785)
- Updated package prettier. (#784)
- Update dependency rollup to v1.26.4 (#783)
- Clean up gulpfile and gulp tasks. (#782)
- Stop starting server so soon (#780)
- Added links to badges on readme. (#779)
- ♻ Adds extra default value for param (#776)
- Update dependency @babel/core to v7.7.2 (#778)
- Update dependency glob to v7.1.6 (#775)
- First e2e test (#777)
- ♻️ Removes `opt_` prefixes from param names - also updates code style a bit (#774)
- Update dependency fetch-mock to v7.7.3 (#773)
- Update dependency @babel/core to v7.7.0 (#772)
- Log Account Linking (#760)
- Update proto (#770)

SwG release 0.1.22.83

---

package.json
src/sanitation.js
src/url-rewrite.js
test/unit/test-purifier.js
test/unit/test-sanitizer.js
yarn.lock

Also update protocol sanitization re: `b/143784753`

Upgrade DOMPurify to 2.0.7

---

examples/amp-story/amp-story-branching.html
examples/amp-story/branching.html
extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/test/test-amp-story.js

This PR enables support for navigating to arbitrary pages inside a story using a fragment params.

✨ Enable navigating pages through fragment params

---

extensions/amp-list/0.1/amp-list.js

To unblock master: https://travis-ci.org/ampproject/amphtml/jobs/611243724#L332-L334

Prettifier fix

---

extensions/amp-story/1.0/amp-story-page.js

Switching browser tab should not rewind story videos.

Switching browser tab should not rewind story videos.

---

extensions/amp-story/1.0/amp-story.css

Closes #25538
Demo:
https://media.giphy.com/media/lPcjzAgKILkXIgdnJc/giphy.gif
@hongwei1990

🖍 Add shadow to loading spinner

---

extensions/amp-story/1.0/bookend/components/article.js
extensions/amp-story/1.0/bookend/components/landscape.js
extensions/amp-story/1.0/bookend/components/portrait.js
extensions/amp-story/1.0/test/test-amp-story-bookend.js
extensions/amp-story/1.0/utils.js

🐛 Rewrite urls for thumbnail images in bookend

---

extensions/amp-script/amp-script.md

/to @CrystalOnScript @jridgewell

amp-script: Improve "state passing" and "AMP elements" docs

---

extensions/amp-access/OWNERS

Update OWNERS for amp-access

---

extensions/amp-a4a/0.1/test/test-amp-a4a.js

✅ Skip ads `cross-domain rendering` test

---

extensions/amp-story/1.0/amp-story-embedded-component.js
extensions/amp-story/1.0/story-analytics.js
extensions/amp-story/1.0/test/test-amp-story-embedded-component.js
test/integration/test-amp-story-analytics.js

Closes #25645
Also adds tests related to the recently landed PR #25547

📈✨ Add data-vars support and tests for amp-story-analytics

---

contributing/TESTING.md

📖Update `gulp visual-diff` instructions in TESTING.md

---

extensions/amp-access-laterpay/0.2/OWNERS

Create owners for amp-access-laterpay

---

examples/amp-consent/amp-consent-iframe.amp.html
examples/amp-consent/amp-consent.amp.html
examples/amp-consent/cmp-vendors.amp.html
examples/amphtml-ads/consent.a4a.html
extensions/amp-consent/integrating-consent.md

Move them to a dedicated folder.

Move amp-consent examples

---

extensions/amp-story/amp-story-analytics.md

📖 Add documentation for bookend click analytics

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Experiment added in https://github.com/ampproject/amphtml/pull/25557/files.

🏗Set amp-auto-ad-no-op experiment traffic fraction to 5%.

---

extensions/amp-story/amp-story.md

The following PR follows what was written by @bramanudom in #21614 but cuts down to the current capabilities introduced by #25502.
#20083

📖 Documentation for branching

---

third_party/subscriptions-project/aes_gcm.js

- Copies AES-GCM encryption function from subscriptions-project/encryption to amp third party.

✨Copy AES-GCM encryption function to AMP.

---

build-system/tasks/e2e/amp-driver.js
build-system/tasks/presubmit-checks.js
extensions/amp-video/0.1/test-e2e/test-amp-video.js
test/fixtures/e2e/amp-video/autoplay.html

We want to cover e2e tests on some critical cases for amp4ads

Add e2e tests for amp-video

---

build-system/tasks/extension-generator/extension-doc.template.md

...rather than fixed `amp-component-name`

📖 Use ${name} for inserting selected extension name

---

build-system/server/app.js
examples/amp-consent/geooverride-consent.amp.html
examples/amp-consent/geooverride-iframe.amp.html
examples/amp-consent/geooverride.amp.html
examples/amp-consent/prompt.html

Add an example of using  geoOverride on amp-consent

---

src/service/platform-impl.js

Partial for https://github.com/ampproject/amphtml/issues/23582.

♻️ Type-fixing: registering a service should return undefined.

---

spec/amp-actions-and-events.md

added action for amp-lightbox-gallery

---

extensions/amp-auto-ads/0.1/amp-auto-ads.js
extensions/amp-auto-ads/0.1/placement.js
extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
extensions/amp-auto-ads/0.1/test/test-placement.js

We've gathered enough holdback data now.
This closes the following issues:
* https://github.com/ampproject/amphtml/issues/24168
* https://github.com/ampproject/amphtml/issues/24169

🚮 Clean up use-responsive-ads-for-responsive-sizing-in-auto-ads holdback experiment

---

examples/amp-consent/geooverride-iframe.amp.html
examples/amp-consent/geooverride.amp.html
examples/amp-consent/prompt.html

Some examples for the publishers and CMP.

amp-consent geo examples iframe auto accept

---

src/service/extension-location.js
test/unit/test-extension-location.js

Fixes https://github.com/ampproject/amphtml/pull/25763#discussion_r352911596.

Fix extension URL parsing for optional ".max"

---

extensions/amp-story/1.0/amp-story-embedded-component.js
extensions/amp-story/1.0/test/test-amp-story.js

🐛 Pressing esc or back key to close expanded component

---

examples/amp-story/amp-story-branching.html
examples/amp-story/analytics.html
examples/visual-tests/amp-story/info-dialog.html
extensions/amp-story/1.0/amp-story-info-dialog.js
extensions/amp-story/1.0/amp-story-page-attachment.js
extensions/amp-story/1.0/amp-story-share-menu.js
extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/bookend/amp-story-bookend.js
extensions/amp-story/1.0/story-analytics.js

Closes #25744
Adds `story-open` and `story-close` analytics trigger support for:
* amp-story-bookend
* amp-story-page-attachment
* amp-social-share
* amp-story-info-dialog
* amp-sidebar

📈 ✨ Add analytics for openable and closeable things

---

build-system/server/app-video-testbench.js
build-system/server/app.js

Fixes server [errors](https://travis-ci.org/ampproject/amphtml/jobs/620910057#L539) on `master` during experiment A/B/C tests.
Follow up to #25822

🐛Correctly handle file read errors in gulp test server

---

spec/amp-3p-video.md
src/video-interface.js

- Includes guide for explaining when and how to build vendor-specific players.
- Updates some `VideoInterface` method descriptions.

📖 3p video player guide and explainer

---

examples/amp-story/ampconf.html
examples/amp-story/rtl.html

it shild bi `Helvetica Neue` nit `hilvitici 9`

🐛 fix incirrict fint fimily

---

.github/PULL_REQUEST_TEMPLATE.md

📖 Update PR template with link to contribution process

---

build-system/test-configs/dep-check-config.js
extensions/amp-live-list/0.1/live-list-manager.js

Reverts ampproject/amphtml#25295

Revert "Introduce AMP Live List Cache Busting"

---

extensions/amp-list/amp-list.md

Partially addresses https://github.com/ampproject/amphtml/issues/25593
cc @caroqliu / @choumx

📖amp-list: documentation for using the new strip-prefix attribute

---

examples/analytics-notification.amp.html

In the analytics notification example, there are two examples. The current example gives a CORS issue on local repositories. As it calls some fake endpoints which may be only be whitelisted for some URLs. So, I think it is best to change it with the second example which works everywhere. I had a discussion on this with @micajuine-ho on issue no #24905. You can also check that out.

🐛 Changes analytics notification example in amp.dev because the current example gives error when run locally 

---

examples/amp-consent/amp-consent-geo.html
examples/amp-consent/amp-consent-server.html
extensions/amp-consent/0.1/consent-info.js
extensions/amp-consent/0.1/consent-state-manager.js
extensions/amp-consent/0.1/test/test-consent-info.js
extensions/amp-consent/0.1/test/test-consent-state-manager.js

amp-consent: support unknown state from response 

---

examples/analytics-notification.amp.html

Solves #24905
I added description on the analytics-notification page earlier in the example it was a blank page so it was a little difficult to understand. So now with the description regarding the functionality and the error in the console, it is more descriptive about what that example does.

📖 Added description and css for it in analytics-notification to solve #24905

---

3p/OWNERS

Some parts of components outside of the scope of ads and analytics live in 3p and there will likely be more in the future.

📖 Add wg-ui-and-a11y to 3p OWNERS set

---

examples/visual-tests/amp-video-docking/amp-video-docking.js

✅ Visual test docking controls activated by tap

---

src/service/video-manager-impl.js
test/unit/test-video-analytics-percentage-tracker.js

🐛Protect against video freezing in stories

---

extensions/amp-list/0.1/amp-list.js
extensions/amp-list/0.1/test/validator-amp-list.html
extensions/amp-list/0.1/test/validator-amp-list.out
extensions/amp-list/amp-list.md
extensions/amp-list/validator-amp-list.protoascii
src/batched-json.js

**summary**
Rename the `strip-prefix` attribute to the more specific `xssi-prefix` as suggested by @lannka.

♻️ Refactor: Rename strip-prefix to xssi-prefix

---

src/service/extensions-impl.js
src/validator-integration.js

Addressing post-submission comments by @choumx  on https://github.com/ampproject/amphtml/pull/25784

propagate nonce: update to only document.head

---

examples/amp-story/quiz.html
examples/visual-tests/amp-story/amp-story-quiz-sizing-positioning.html
extensions/amp-story/1.0/amp-story-page-attachment.js
extensions/amp-story/1.0/amp-story-quiz.css
extensions/amp-story/1.0/amp-story-quiz.js
extensions/amp-story/1.0/amp-story-user-overridable.css
extensions/amp-story/1.0/amp-story.css
extensions/amp-story/1.0/page-advancement.js
test/visual-diff/visual-tests

Add constraints to the quiz element, which can be added to further interactive elements down the road. Specifically, enforced the automatic sizing, and disabled interactivity outside the interaction safety area (e.g. the edges of the screen and the bottom when CTA or Page Attachment is present)
Adds work related to tracking issue #25615

✨Add sizing and positioning constraints to quiz element

---

examples/jwplayer.amp.html
extensions/amp-jwplayer/0.1/amp-jwplayer.js
extensions/amp-jwplayer/0.1/test/test-amp-jwplayer.js
extensions/amp-jwplayer/0.1/test/validator-amp-jwplayer.html
extensions/amp-jwplayer/0.1/test/validator-amp-jwplayer.out
extensions/amp-jwplayer/amp-jwplayer.md

**Description**
- This PR is required to accurately reflect JW Player AMP component usage.

⏪📖 JW Player: Update documentation and remove configuration options

---

extensions/amp-form/0.1/amp-form.js
extensions/amp-form/0.1/test/test-amp-form.js
extensions/amp-form/amp-form.md

Addresses `b/143896641`
cc @choumx / @jridgewell

xssi-prefix support to amp-form

---

spec/amp-html-format.md

Resolves [issue #25933](https://github.com/ampproject/amphtml/issues/25933)

ID disallowed names 

---

spec/amp-3p-video.md

📖Fix component link s/youtube/story/

---

examples/analytics-vendors.amp.html
extensions/amp-analytics/0.1/test/vendor-requests.json
extensions/amp-analytics/0.1/vendors.js
extensions/amp-analytics/0.1/vendors/memo.js

fixes #25979
This is a repeat of a previous submission, but we had problems with the CLA agreements and how they linked to git accounts. I believe this is fixed now.
/cc @zhouyx @jeffjose

✨ Implementing analytics vendor support for Memo (memo.co)

---

ads/capirs.js

🚮 Remove unnecessary lpdid  script loading

---

extensions/amp-viewer-integration/TICKEVENTS.md
src/service/performance-impl.js
test/unit/test-performance.js

Introduce Largest Contentful Paint tick event

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

Reduce redirect delay (#894)
Update dependency postcss to v7.0.25 (#893)
Update link for badges. (#892)

SwG Release 0.1.22.87

---

build-system/compile/bundles.config.js
build-system/test-configs/dep-check-config.js
extensions/amp-base-carousel/0.1/amp-base-carousel.js
extensions/amp-base-carousel/0.1/carousel.css
extensions/amp-base-carousel/0.1/carousel.js
extensions/amp-inline-gallery/0.1/amp-inline-gallery-thumbnails.css
extensions/amp-inline-gallery/0.1/amp-inline-gallery-thumbnails.js
extensions/amp-inline-gallery/0.1/amp-inline-gallery.js
test/manual/amp-inline-gallery/pagination-and-thumbnails.amp.html

This creates a thumbnail for each slide in the carousel and hooks up event listeners to them to change the slide in the carousel. No syncing of state is done for the thumbnails since we have not gotten that UX to feel good yet.
Live demo at https://amp-polish.firebaseapp.com/manual/amp-inline-gallery/pagination-and-thumbnails.amp.html

✨Add inline-gallery thumbnails element.

---

build-system/compile/build.conf.js

Allow setting RTV experiment flag to custom value

---

build-system/tasks/extension-helpers.js

Generate analytics vendor configs in singlepass

---

validator/engine/validator.js

Fixes #25990 
- cl/286269591 AMP respect different varieties of lightning bolt.

cl/286269591 AMP respect different varieties of lightning bolt.

---

examples/visual-tests/amphtml-ads/amp-fie-static.html
test/visual-diff/visual-tests

Add FIE visual tests for amp-ad

---

extensions/amp-carousel/0.1/amp-carousel.css
extensions/amp-carousel/0.1/base-carousel.js
extensions/amp-carousel/0.1/test-e2e/test-hidden-controls.js
test/manual/amp-carousel/0.1/hidden-controls.amp.html

♿Replace `i-amphtml-screen-reader` usage on amp-carousel 0.1

---

examples/visual-tests/amp-autocomplete/amp-autocomplete.amp.html
extensions/amp-autocomplete/0.1/amp-autocomplete.js
extensions/amp-autocomplete/0.1/autocomplete-binding-inline.js
extensions/amp-autocomplete/0.1/test-e2e/test-amp-autocomplete-inline.js
extensions/amp-autocomplete/0.1/test-e2e/test-amp-autocomplete.js
extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-bindings.js
extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
extensions/amp-autocomplete/amp-autocomplete.md

🚮Remove amp-autocomplete `inline` and `query` experiments

---

extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
extensions/amp-subscriptions/0.1/viewer-subscription-platform.js

Correctly handle the case where the viewer returns a non-granting entitlement and metering.

🐛 Metering viewer fix

---

extensions/amp-script/0.1/amp-script.js
extensions/amp-script/0.1/test/integration/test-amp-script.js
extensions/amp-script/amp-script.md

Fixes #26047. Also fixes and unskips integration tests.

amp-script: Remove height constraint for mutation

---

extensions/amp-position-observer/0.1/amp-position-observer.js

Fixes https://github.com/ampproject/amphtml/issues/25998 @lannka 
More test coverage TBD

Fix: amp-position-observer fails to detect movement in friendly iframe

---

build-system/global-configs/prod-config.json

We have turned it on for Canary for a few months. This PR would turn it on for prod.

Turn on fie-css-cleanup for prod

---

extensions/amp-subscriptions/validator-amp-subscriptions.protoascii
validator/engine/validator_test.js
validator/validator-main.protoascii

- cl/286594572 amp-subscriptions
- cl/286916651 Revision bump for #26138

Validator rollup 20191223

---

extensions/amp-consent/amp-consent.md

Discussed #26081 offline and agreed to make spec clearer on this topic

Amp-consent value opt-in/opt-out clarification

---

extensions/amp-form/0.1/amp-form.js
extensions/amp-form/0.1/test/test-amp-form.js

🐛amp-form: Parse JSON string in SSR response['body']

---

src/service/url-replacements-impl.js

Variant error message

---

build-system/tasks/presubmit-checks.js

Blocks https://github.com/ampproject/amphtml/pull/26129

Allow 2020 in copyright declaration

---

build-system/externs/amp.extern.js
extensions/amp-bind/0.1/amp-state.js
extensions/amp-bind/0.1/bind-impl.js
extensions/amp-bind/0.1/test/integration/test-bind-impl.js
extensions/amp-bind/0.1/test/test-amp-state.js
extensions/amp-script/0.1/amp-script.js
extensions/amp-script/0.1/test/unit/test-amp-script.js

Small improvement leading up to https://github.com/ampproject/amphtml/pull/26046

♻️ Refactor bind.setState and bind.apply to take in an options bag.

---

src/OWNERS
src/service/OWNERS

Add wg-analytics to cid service owners

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

- Update dependency sinon to v8.0.4 (#942)
- Update dependency gulp-load-plugins to v2.0.2 (#941)
- Update dependency mocha to v7 (#939)
- ✅ Adds tests for polyfills to bring their coverage to 100% (#938)
- Update dependency rollup to v1.28.0 (#940)
- ✅ Updates API messages and brings coverage to 100% (#936)
- update proto (#935)
- Update dependency postcss to v7.0.26 (#934)
- ✅ Adds test to `JsError` class and brings coverage to 100% (#931)
- ✅ Refactors `i18n` utility and brings coverage to 100% (#932)
- ✅ E2E login: Wait for password element to go away (#930)
- Update dependency sinon to v8.0.2 (#933)
- ✅ Skips E2E login step if possible (#929)
- ✅ Refactors types utility and brings coverage to 100% (#928)
- ✅ Refactors dom utility and brings coverage to 100% (#926)
- ✅ Replaces …

SwG release 0.1.22.88

---

tools/experiments/experiments.html
tools/experiments/experiments.js

I'm open to suggestions on phrasing 🙃
Tag-along changes: comment nit in experiments.js

📖 Add note in experiments page about blocking third-party cookies

---

examples/amp-consent/amp-consent-client.html
examples/amp-consent/amp-consent-geo.html
examples/amp-consent/amp-consent-server.html
examples/amp-story-auto-ads.amp.html
test/manual/amp-analytics-cookie-writer.html
test/manual/amp-analytics/analytics-fcp.html
test/manual/amp-analytics/analytics-nav-timing.html
test/manual/amp-consent/legacy_config_support/amp-consent.amp.html
test/manual/amp-ima-video.html
test/manual/analytics-batching.amp.html

Fix analytics examples 

---

extensions/amp-position-observer/0.1/amp-position-observer.js

Add issue number to amp fie experiment cleanup comment

---

extensions/amp-script/0.1/amp-script.js
extensions/amp-script/0.1/test/unit/test-amp-script.js

Addresses https://github.com/ampproject/amphtml/issues/25476.
cc @jridgewell  / @choumx

♻️ amp-script: remove support for deprecated development mode opt-in flag

---

extensions/amp-nested-menu/0.1/amp-nested-menu.js
extensions/amp-nested-menu/0.1/test/test-amp-nested-menu.js
extensions/amp-nested-menu/amp-nested-menu.md

Closes #25368 and #24665 
- Adds support for the keyboard keys "HOME" (selects the first item in the list) and "END" (selects the last item in the list 
- Adds related tests

✨Add HOME and END key support on `amp-nested-menu`

---

examples/amp-consent/cmp-vendors.amp.html
extensions/amp-consent/0.1/cmps.js
extensions/amp-consent/amp-consent.md
extensions/amp-consent/cmps/marfeel.md

- Add Marfeel to CMPs list with its proper parameters.
- Added documentation:
- Instructions
- Example
- Example on cmp-vendors page.
I2i opened issue can be found [here](https://github.com/ampproject/amphtml/issues/26181).
/cc @ampproject/wg-monetization

✨AMP-Consent: Add Marfeel to CMPs list

---

build-system/tasks/presubmit-checks.js
extensions/amp-form/amp-form.md

Added CONSENT_* macros to vendor callout for GDPR and CCPA support.

Callout vendor update: added consent macros to indexexchange url

---

src/service/OWNERS

Add wg-analytics to url-replacement owners

---

contributing/contributing-code.md

Copy edit thread for contributing code docs. Includes all suggestions from https://github.com/ampproject/amphtml/pull/26085

📖 Update contributing-code with copy edits

---

ads/inabox/position-observer.js

🐛 Don't assume window is always available for inabox. It can be already destroyed

---

extensions/amp-analytics/amp-video-analytics.md

For #24542
Added documentation for how to capture click events on a video for analytics requests.

📖 Video click analytics event

---

src/OWNERS

https://github.com/ampproject/amphtml/pull/26276#issuecomment-573162486
/cc @jridgewell

Update OWNERS to make wg-stories owner of amp-story-embed

---

extensions/amp-action-macro/0.1/amp-action-macro.js

amp-action macro layout error

---

ads/readmo.js
ads/readmo.md
examples/ads.amp.html

This PR performs some code cleanup and resolves a critical internal bug.
- removes `onViewChange` hook 
- Use `global` instead of `window`
- Update demo documentation/example

🔥🐛[readmo-amp] code cleanup and bug fix

---

src/service/url-replacements-impl.js

In regards to #26210, track usage before we move to amp-analytics/remove.

Expected error to track AMP_STATE usage

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

- Update babel monorepo to v7.8.3 (#950)
- Remove unused PayClientBindingSwg (#905)
- Update dependency @babel/preset-env to v7.8.2 (#949)
- Update babel monorepo to v7.8.0 (#948)
- Respect event manager ready promise (#947)
- Update dependency karma-firefox-launcher to v1.3.0 (#943)
- Update dependency rollup to v1.29.0 (#944)
- SwG early logging (#937)

SwG release 0.1.22.89

---

build-system/tasks/extension-generator/extension-doc.template.md

Makes more sense to have examples under Usager

quick format change

---

extensions/amp-timeago/amp-timeago.md

Resolved issue [#2346](https://github.com/ampproject/amp.dev/issues/2346)

clarified text node behavior

---

extensions/amp-script/amp-script.md
extensions/amp-script/validator-amp-script.protoascii

/cc @ampproject/wg-ui-and-a11y @ampproject/wg-caching

✨ Add support for `"intrisic"` layout for `<amp-script>`

---

.github/ISSUE_TEMPLATE/intent-to-implement--i2i-.md
.github/ISSUE_TEMPLATE/intent-to-ship--i2s-.md

See here for context: https://docs.google.com/document/d/1bF5tHbm-ObyjKLfoiIEAI5V-YvMsA3Bchsux5u4cKZM/edit#

Update I2I & I2S to reflect new Open Source process

---

extensions/amp-story/1.0/amp-story-page.js

Render video alt and title attributes in vertical rendering mode.

Render video alt and title attributes in vertical rendering mode.

---

package.json
yarn.lock

Upgrade WorkerDOM to latest version.

Upgrade WorkerDOM to latest version

---

src/service/url-expander/OWNERS

Ad wg-analytics as owner of url-expander

---

build-system/externs/amp.extern.js
extensions/amp-bind/0.1/bind-impl.js
extensions/amp-script/0.1/amp-script.js
extensions/amp-script/0.1/test/unit/test-amp-script.js

Address the addendum: https://github.com/ampproject/amphtml/issues/24862#issuecomment-554040403

amp-script: high trust addendum

---

extensions/amp-mustache/0.2/test/validator-amp-mustache-json.html
extensions/amp-mustache/0.2/test/validator-amp-mustache-json.out
extensions/amp-mustache/0.2/test/validator-json-not-in-template.html
extensions/amp-mustache/0.2/test/validator-json-not-in-template.out
extensions/amp-subscriptions/validator-amp-subscriptions.protoascii
validator/engine/validator.js
validator/validator-main.protoascii

- cl/290331009 Revision bump for #26369
- cl/290296806 n/a
- cl/289965888 github commit msg missing or malformed
- cl/289922243 Revision bump for #'26283

Validator rollup (more from last update)

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

Fixes broken SwG Release 0.1.22.90 (in "Safer labels").
- Safer labels (#963)
- Set Canonical URL in Analytics Service (#962)
- Update dependency rollup to v1.29.1 (#961)

SwG Release 0.1.22.91

---

contributing/getting-started-e2e.md
contributing/getting-started-quick.md

Clarifies the ambiguities that recently blocked @Enriqe from adding a dependency.

📖 Clarify process for adding dependencies

---

extensions/amp-story/1.0/test/integration/test-amp-story-affiliate-link.js

This reverts commit b7188b9266094a8b58a8eb2c759bf59e82b11dc2.

Revert "Skip amp story affiliate link test (#26386)"

---

.eslintignore
.eslintrc
ads/ads.extern.js
build-system/externs/amp.extern.js
build-system/externs/dompurify.extern.js
third_party/moment/moment.extern.js

**summary**
Extern javascript files should ideally be prettified as well. Currently I'm investigating the best way to go about this.
As brought up here: https://github.com/ampproject/amphtml/pull/26202#issuecomment-571290162
**interesting notes:**
- There was a duplicate typedef (`GetCidDef`). I deleted one of them and pointed the locations where it was used to the other definition.
- We unfortunately cannot say "remove all rules" and so I've one by one disabled the ones that failed.

♻️ Lint: include externs

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Fixes https://github.com/ampproject/amphtml/issues/24929

✨ Launch layoutbox-invalidate-on-scroll

---

extensions/amp-story/1.0/test/test-full-bleed-animations.js
extensions/amp-story/1.0/test/test-live-story-manager.js

These tests are blocking https://github.com/ampproject/amphtml/pull/26449 from being merged, cf https://travis-ci.org/ampproject/amphtml/jobs/641134620
I believe they have been failing for a long time but somehow that PR triggered them. cc @ampproject/wg-infra

Fix Story tests.

---

examples/fluid.amp.html
extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js

Ensure that fluid slots hidden by media queries do not issue ad requests.

---

extensions/amp-list/0.1/test/test-amp-list.js

Seems to also be broken on master, but CI does not pick up on it. Still investigating now to figure out how this happened.
cc @jridgewell

🐛 amp-list: fix broken test re. missing layout

---

extensions/amp-consent/amp-consent.md

🐛Fix dead link in amp-consent.md

---

src/service/resources-impl.js

Should help debug: https://github.com/ampproject/amphtml/issues/18207

🕵️ Improve logging to debug missing Resource issue.

---

build-system/compile/bundles.config.js
build-system/tasks/helpers.js
build-system/tasks/presubmit-checks.js
examples/amp-story/player.html
src/OWNERS
src/amp-story-player-manager.js
src/amp-story-player.js
test/unit/test-amp-story-player.js

♻️ Rename amp-story-embed to amp-story-player

---

extensions/amp-story-auto-ads/0.1/story-ad-button-text-fitter.js

https://github.com/ampproject/amphtml/pull/25296
FYI there should be no behavioral change.

 ♻️Resource=>Mutator refactor for story auto ads

---

.github/ISSUE_TEMPLATE/cherry_pick_template.md

This is in addition to the fixes in #26542.

🏗 Fix another cherry-pick link

---

ads/temedya.md

TE Medya native widget readme file.

📖temedya.md file

---

src/OWNERS

Set owners for js in src/ for wg-ads and wg-analytics

---

extensions/amp-access-poool/0.1/poool-impl.js

https://github.com/ampproject/amphtml/pull/25296
There should be no behavioral change.
Needing to re-merge after reverting the relevant PR.

♻️Resource=>Mutator refactor for access-poool

---

validator/nodejs/index.js

There is a terrible practice to extend String because this generate issues in other libraries and code.
The library colors is extending the String object and this lead to other code issues, so is better use the safe version proposed in:
https://github.com/Marak/colors.js#usage

🐛Prevent extend String object by the "colors" library.

---

src/service/batched-xhr-impl.js
test/unit/test-batched-xhr.js

Fixes https://github.com/ampproject/amphtml/issues/17810

🐛 batched-xhr-impl: use absolute url as key for batchFetch

---

extensions/amp-story/amp-story.md

Fix typos, broken links and update which posters are required for AMP Stories.

🐛 Fix typos for amp-story.md

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

- Update dependency chromedriver to v79.0.3 (#982)
- Update dependency codecov to v3.6.4 (#981)
- Update dependency rollup to v1.31.0 (#977)
- Update dependency codecov to v3.6.3 (#978)
- Update dependency karma-browserify to v7 (#975)
- Update babel monorepo to v7.8.4 (#976)
- Update dependency chromedriver to v79.0.2 (#974)
- Update dependency rollup to v1.30.1 (#973)
- Update dependency mocha to v7.0.1 (#972)
- ✅ Refactors `logger-test` (#971)
- ✅ Migrates tests to use for/of (#970)
- Update dependency codecov to v3.6.2 (#968)
- Add a test to prevent an issue from reoccurring (#964)
- ✔️ Refactors 'client-event-manager' tests and brings coverage to 100% (#967)
- Update dependency sinon to v8.1.1 (#965)

🏗 SwG Release 0.1.22.92

---

extensions/amp-apester-media/0.1/monetization/companion/display.js
extensions/amp-apester-media/0.1/monetization/companion/video.js
extensions/amp-apester-media/0.1/test/test-amp-apester-monetization.js

https://github.com/ampproject/amphtml/pull/25296

♻️ Resource=>Mutator refactor for apester-media

---

src/service/performance-impl.js

♻️ performance-impl: delete unused code

---

extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js

e.g. https://travis-ci.org/ampproject/amphtml/jobs/647176100?utm_medium=notification&utm_source=github_status
/cc @ampproject/wg-ads

Skip ads test breaking master

---

extensions/amp-timeago/amp-timeago.md

Updated headings and moved content block out of example. oops

quick fix and update to amp-timeago

---

extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js

https://github.com/ampproject/amphtml/issues/26651#event-3018634061

✅ Set amp-ad unit test to use unreachable domain

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.93

SwG Release 0.1.22.93

---

extensions/amp-consent/amp-consent.md

related to https://github.com/ampproject/amphtml/pull/26539#issuecomment-584371298

🐛📖 Fix amp-consent.md url

---

build-system/tasks/extension-helpers.js

The extension watcher used by `gulp [watch|build]` looks for changes in an extension directory and rebuilds the extension if any file changes. This works well for extensions contained in a single directory. However, ad network extensions all use `extensions/amp-a4a/` as their base class, and this directory isn't rebuilt by the watcher.
This PR modifies the extension watching mechanism to also watch for changes in `extensions/amp-a4a/` when an ad network extension is being watched.
**To test this:**
1. Launch the dev server by running `gulp`
2. Load some ad network extensions by navigating to http://localhost:8000/examples/a4a.amp.html 
3. Wait for all extensions on that page to be built
4. Modify `extensions/amp-a4a/0.1/amp-a4a.js`
You should see all the ad network extensions that were …

🏗 Watch and rebuild `amp-a4a` when an ad network extension is being watched

---

extensions/amp-truncate-text/0.1/amp-truncate-text.js
extensions/amp-truncate-text/0.1/test/test-amp-truncate-text.js

🚀 Remove amp-truncate-text experiment check

---

extensions/amp-ima-video/0.1/amp-ima-video.js

Closes #23365
Need to have pauseCallback() implemented, so that we can pause resources (amp-ima-video) when they are not visible anymore
https://github.com/ampproject/amphtml/blob/ec0adfc967f2656c08499efeebdf97013d2b5b58/src/service/resource.js#L981-L986

Added pauseCallback in amp-ima-video

---

extensions/amp-analytics/integrating-analytics.md

migrate from .js file to .json file
cc @lannka

Update Analytics integration doc

---

extensions/amp-story/amp-story-page-attachment.md

Fix amp validation error in amp-story-page-attachment.md
Fixes: ampproject/amp.dev#3439

🐛 Fix validation error

---

extensions/amp-story/1.0/amp-story.css

Context and explanation at #26718

Fix amp-video layoutCallback on first story page.

---

examples/autocomplete.amp.html
extensions/amp-autocomplete/0.1/amp-autocomplete.js
extensions/amp-autocomplete/0.1/autocomplete-binding-def.js
extensions/amp-autocomplete/0.1/autocomplete-binding-inline.js
extensions/amp-autocomplete/0.1/autocomplete-binding-single.js
extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-bindings.js
extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js

Remove amp-autocomplete form ancestor requirement

---

examples/amp-consent/cmp-vendors.amp.html
extensions/amp-consent/0.1/cmps.js
extensions/amp-consent/amp-consent.md
extensions/amp-consent/cmps/ogury.md

📖 amp-consent: Add Ogury CMP doc + example

---

build-system/tasks/visual-diff/index.js
package.json
yarn.lock

Race conditions are fun
/cc @westonruter whose PR stumbled on this bug

🏗🐛 Wait for Percy agent to start before performing visual diff tests

---

validator/gulpjs/README.md

Per npm release as a result of #26775

update gulpjs README.md version notes

---

build-system/tasks/karma.conf.js

trying to update Sauce timeouts

---

build-system/global-configs/canary-config.json

Turn on restrict fullscreen flag canary

---

spec/amp-html-format.md

resolves issue [24757](https://github.com/ampproject/amphtml/issues/24757)

application/json is ab allowed type for <script>

---

build-system/compile/compile.js

this currently breaks sourcemaps in esm build

Do not append `sourceMappingURL` to map files

---

css/amp-story-player-iframe.css
examples/amp-story/player.html
src/amp-story-player.js
test/unit/test-amp-story-player.js

✨[amp-story-player] Adds tap-to-next/previous story

---

extensions/amp-script/amp-script.md

Addresses ampproject/amppackager#395.

📖 Clarify SXG duration minimum

---

build-system/global-configs/prod-config.json

For #26432
Expect in stable March 3

Amp consent restrict fullscreen prod flag

---

extensions/amp-story/amp-story-player.md
spec/amp-story-player.md

Adds initial documentation for the new `amp-story-player`.
I2I #24539
Tracker #26308

📖 [amp-story-player] Initial docs

---

test/unit/test-viewer.js

Make test aware of some console errors when expected.

viewer: Minor test improvements

---

extensions/amp-video-iframe/amp-video-iframe.md
spec/amp-3p-video.md

📖Callout for amp-video-iframe samples

---

test/unit/test-cookies.js

```
ERROR: 'Should never attempt to set cookie on proxy origin: c&1'
The test "test-cookies   write cookie to right domain on proxy" resulted in a call to console.error. (See above line.)
ERROR: 'Should never attempt to set cookie on proxy origin: c&1'
The test "test-cookies   write cookie to right domain on proxy" resulted in a …
```

cookie: Minor test improvement

---

validator/validator-main.protoascii

See agreement across WG here: https://docs.google.com/document/d/1lsG9svgClzfknEwWD8mMc7kf91N8RJhGrssNPc0lO9E/edit#bookmark=id.17gxd3ks8hmv

Increase AMP4Email CSS Limit

---

examples/brid-player.amp.html
extensions/amp-brid-player/0.1/amp-brid-player.js
extensions/amp-brid-player/0.1/test/validator-amp-brid-player.html
extensions/amp-brid-player/0.1/test/validator-amp-brid-player.out
extensions/amp-brid-player/amp-brid-player.md
extensions/amp-brid-player/validator-amp-brid-player.protoascii

Adding dock support for Brid player

---

extensions/amp-access-scroll/amp-access-scroll.md

Adds documentation file for the Scroll extension.
Fixes #26664

📖Add documentation for amp-access-scroll

---

spec/amp-story-player.md

🐛 Fix img url

---

build-system/test-configs/dep-check-config.js

followup to https://github.com/ampproject/amphtml/pull/26981

dep-check: USE CAPS FOR IMPORTANCE

---

build-system/compile/bundles.config.js
extensions/amp-next-page/1.0/amp-next-page.js
extensions/amp-next-page/1.0/test/test-amp-next-page.js
extensions/amp-next-page/amp-next-page.md
test/manual/amp-next-page/1.0/amp-next-page.amp.html
test/manual/amp-next-page/1.0/amp-next-page.element-visibility.html
test/manual/amp-next-page/1.0/amp-next-page.script-templated-separator.amp.html
tools/experiments/experiments-config.js

Closes #25634 
Closes #14876
Closes #19823 
Closes #15807 
Closes  #18735
Closes #20400
Closes #25630
Closes #15818
Closes #25553

Launch `amp-next-page` v2 & clean up experiment

---

extensions/amp-iframe/0.1/amp-iframe.js
extensions/amp-iframe/0.1/test/test-amp-iframe.js

🐛 only log first error for ignored embed-size in amp-iframe

---

build-system/tasks/extension-generator/extension-doc.template.md

Partially resolves [#3623](https://github.com/ampproject/amp.dev/issues/3623)

specified use of markdown in teaser

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

- Adds logging when transaction ID changes
- Adds old_transaction_id to analytics proto
- sendBeacon now uses request body

✨ SwG version 0.1.22.95

---

examples/carousel-v1.amp.html
extensions/amp-carousel/0.1/base-slides.js
extensions/amp-carousel/0.1/slidescroll.js
extensions/amp-carousel/0.1/test/test-slidescroll.js

Fire low trust events when relevant in amp-carousel v1

---

extensions/amp-mustache/amp-mustache.md

For context see here: https://docs.google.com/document/d/1lsG9svgClzfknEwWD8mMc7kf91N8RJhGrssNPc0lO9E/edit#bookmark=id.1xum78ltl3cu

Update link to Mustache spec and not JS implementation

---

extensions/amp-mustache/amp-mustache.md

See #26950 for background.
/to @nainar 
/to @kristoferbaxter 
/to @choumx

📖Fix one more referecnes to Mustache.js

---

extensions/amp-access-scroll/0.1/scroll-protocol.js

This was supposed to be bundled in #27047
cc @dvoytenko @dbow @kushal

✨amp-access-scroll Bump protocol version

---

examples/analytics-vendors.amp.html
extensions/amp-analytics/0.1/test/vendor-requests.json
extensions/amp-analytics/0.1/vendors/adobeanalytics.json

We'd like to take advantage of the linker in Adobe Analytics. Additionally we made some small updates outlined below:
* Changed the internal Adobe Analytics type from 0 => 2
* removed the request type priority from AdobeAnalytics
* added .python_version to .gitignore
* updated tests for AdobeAnalytics to reflect changes
Fixes #26289

✨AmpAnalytics: Add linker to ADOBEANALYTICS_CONFIG (#26289)

---

extensions/amp-timeago/0.2/timeago.js

We changed the global type def from `Preact` to `PreactDef`.

🐛 Fix Timeago Preact Type

---

babel.config.js
build-system/babel-plugins/babel-plugin-transform-fix-leading-comments/test/fixtures/transform/basic/input.js
build-system/babel-plugins/babel-plugin-transform-fix-leading-comments/test/fixtures/transform/basic/output.js
build-system/babel-plugins/babel-plugin-transform-fix-leading-comments/test/index.js
build-system/compile/build.conf.js
build-system/compile/compile.js
build-system/eslint-rules/preact.js

https://github.com/ampproject/amphtml/pull/26903

Fixes various review comments on JSX PR

---

extensions/amp-ad-exit/amp-ad-exit.md

📖Update amp-ad-exit docs

---

extensions/amp-story-auto-ads/amp-story-auto-ads.md
extensions/amp-story/amp-story.md

Fixes: ampproject/amp.dev#3620

🐛 Fix format for story-components

---

extensions/amp-a4a/0.1/callout-vendors.js

It's a small macro update on the RTC endpoint.
- placement_id macro added
- tag_id macro reverted to default
Hi @lannka, could you please take a look and merge it anytime soon? Thank you!

✨The Ozone Project: Update RTC endpoint macro in callout-vendors.js

---

build-system/compile/bundles.config.js
extensions/amp-story-education/0.1/amp-story-education.css
extensions/amp-story-education/0.1/amp-story-education.js
extensions/amp-story-education/0.1/test/test-amp-story-education.js
extensions/amp-story-education/OWNERS
extensions/amp-story-education/validator-amp-story-education.protoascii

Creating the `amp-story-education` extension.
#27097

amp-story-education extension boilerplate.

---

extensions/amp-story/1.0/test/validator-amp-story-bookend-inline.html
extensions/amp-story/1.0/test/validator-amp-story-bookend-inline.out
extensions/amp-story/validator-amp-story.protoascii

🐛Allow nonce in inline bookend 

---

builtins/amp-img.js

split from https://github.com/ampproject/amphtml/pull/27037

♻️ alphabetize propagated attrs in amp-img

---

extensions/amp-bind/amp-bind.md

Fixes #27086 (mismatched `[/filter]` with [filter ...]`)

Fix filters in amp-bind reference

---

extensions/amp-ad/amp-ad.md

Correcting 'availbel' to available

📖 Fix typo in amp-ad.md

---

extensions/amp-bind/amp-bind.md

The commit broke the amp.dev build due to unclosed filter.

Revert "Fix filters in amp-bind reference (#27143)"

---

ads/OWNERS

While I'm in the ads working group, as someone primarily working on AdManager I think it doesn't make sense for me to be handling reviews to ads code in general.

 🏗 ads owners: don't send reviews to jeffkaufman

---

src/amp-story-player.js

Limits capabilities in iframe as stated in: 
https://github.com/ampproject/amphtml/blob/e44a2c10d579723a8413fd55ba7a0d865629710b/src/3p-frame.js#L400-L404
Closes #27178
Tracker #26308

✨[amp-story-player] Sandbox iframes

---

build-system/tasks/check-links.js

This breaks due to reassigning `const`, introduced in #26739

🐛 [check-links] Don't reassign const

---

ads/readmo.js
ads/readmo.md

This PR makes use of the provided `json` attribute for `amp-ad` and `amp-embed` components  to support additional readmo configs.

♻️readmo: add support for custom configs via json attribute

---

ads/ssp.js
ads/ssp.md
examples/ads.amp.html
test/unit/ads/test-ssp.js

Hi,
please review my PR for:
- ✨ Edited amp-ad of type `ssp`
- ✨ Added support for multiple ads on page with same type
- ✅ Tests are also implemented
Thank you

Add support for multirequest Ads in Sklik SSP amp-ad

---

extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js

Tried for a while, to repro without much luck. Either way adding the check seems safe and in line with many of the other methods in the class.
Closes #15764

🐛Fix missing iframe error in safeframe

---

src/service/viewer-impl.js

First step for #27167.
/to @samouri

Add expected error for prerenderSize deprecation

---

extensions/amp-subscriptions/0.1/amp-subscriptions.js
extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js

🐛 Always unlock pages that have unlocked config

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Introduced in #17672. Safe to remove now.

Remove unused experiment config

---

extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
extensions/amp-subscriptions/0.1/viewer-subscription-platform.js

This PR updates the viewer platform to throw an error if one is included in the entitlements object
A few tests were updated to check for eventual rejections as well instead of using try/catch

✨ amp-subscriptions: In viewer platform, throw error if one is included with entitlements object

---

extensions/amp-inline-gallery/amp-inline-gallery.md

Fixes https://github.com/ampproject/amp.dev/issues/3691

📖 Add missing amp-lightbox-gallery import

---

build-system/tasks/performance/index.js
build-system/tasks/performance/load-config.js
build-system/tasks/performance/package.json
build-system/tasks/performance/print-report.js
build-system/tasks/performance/run-tests.js
build-system/tasks/performance/test-suite.js
build-system/tasks/performance/yarn.lock

Updates to `gulp performance`:
- Adds flags for threshold and url.
- Adds a test framework. Runs test for every metric on every URL, using the threshold flag.

🏗 Add test runner to gulp performance

---

extensions/amp-subscriptions/0.1/amp-subscriptions.js
extensions/amp-subscriptions/0.1/entitlement.js
extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js

Fixes https://github.com/ampproject/amphtml/issues/27299

🐛 amp-subscriptions: Resolves authdata on unlocked pages

---

extensions/amp-sidebar/0.1/amp-sidebar.js
extensions/amp-sidebar/0.1/toolbar.js
extensions/amp-sidebar/0.2/amp-sidebar.js
extensions/amp-sidebar/0.2/toolbar.js

Fixes #27301. Saw this as an unlinked error while on release duty.
/to @caroqliu

amp-sidebar: Fix async throw in toolbar

---

babel.config.js

Disable loose mode in classes, this will allow using newer es6 features like CEv1.

Add class plugin with loose:false

---

ads/relap.js

🐛 Fix Relap widget URL

---

build-system/tasks/create-golden-css/css/main.css
css/ampdoc.css
extensions/amp-iframe/0.1/test/test-amp-iframe.js
extensions/amp-sidebar/0.1/test/integration/test-amp-sidebar.js
extensions/amp-sidebar/0.2/test/integration/test-amp-sidebar.js
src/service/viewport/viewport-binding-natural.js
test/unit/test-viewport-binding.js

Disable x-scrolling on iOS when iframed

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

Version: 0.1.22.97
-----------------
Previous release: 0.1.22.96
Update dependency prettier to v2 (#1027)
Update dependency morgan to v1.10.0 (#1026)
Update babel monorepo to v7.9.0 (#1025)
Update dependency fs-extra to v9 (#1024)
Mark "no config could be discovered" as a user error (#1023)
Update dependency mocha to v7.1.1 (#1022)
Update dependency rollup to v2.1.0 (#1021)
Update dependency karma-sauce-launcher to v4 (#1020)

SwG release 0.1.22.97

---

extensions/amp-social-share/0.2/social-share.css.js
extensions/amp-social-share/0.2/social-share.js
third_party/optimized-svg-icons/social-share-svgs.js

[PR Deploy Bot Demo](https://storage.googleapis.com/amp-test-website-1/amp_dist_72025/examples/social-share.amp.html)

[amp-social-share v2] Remove SOCIAL_SHARE_ prefixes from assets

---

src/preact/base-element.js

[Related comment](https://github.com/ampproject/amphtml/pull/26543#discussion_r395912806)

Simplify mutateProps in PreactBaseElement

---

extensions/amp-story/1.0/page-advancement.js

Fix progress bar synchronization with amp-audio.
Basically using the same implementation details as for videos:
https://github.com/ampproject/amphtml/blob/bb80410e51edb592e7ab2e6b9b220d06a2e25301/extensions/amp-story/1.0/page-advancement.js#L977-L995
Partial for #27291

Fix progress bar synchronization with amp-audio.

---

extensions/amp-story/1.0/amp-story-page.js
extensions/amp-story/1.0/amp-story-store-service.js
extensions/amp-story/1.0/embed-mode.js
extensions/amp-story/1.0/test/test-amp-story-page.js
extensions/amp-story/1.0/test/test-full-bleed-animations.js
extensions/amp-story/1.0/test/test-live-story-manager.js
extensions/amp-story/1.0/utils.js

Adds optional flag for experiment.
[Demo using param](https://stamp-demo.firebaseapp.com/examples/amp-story/ampconf-preview.html#embedMode=3)

Experimental flag for preview

---

build-system/compile/build.conf.js
src/css.js

🚀 Use native CSS.escape in ESM build

---

extensions/amp-next-page/1.0/service.js

Fixed error handling for amp-next-page remote url fetching

---

3p/recaptcha.js
test/unit/3p/test-recaptcha.js

```
ERROR: 'The test "3p recaptcha.js should require a window.name" contains an "allowConsoleError" block that didn't result in a call to console.error.'
```

3p-recaptcha: Minor test improvement

---

extensions/amp-mustache/0.2/amp-mustache.js

Addresses https://github.com/ampproject/amphtml/issues/25596.

amp-mustache: emit a developer error for faulty mustache templates

---

test/visual-diff/visual-tests

And reassign all TODOs with issue number and working-groups.
Related to #27181

❄️ Disabled multiple flaky visual diff tests

---

extensions/amp-consent/0.1/amp-consent.css
extensions/amp-story/0.1/amp-story.css
extensions/amp-story/1.0/amp-story.css

Since this component is always filled asynchronously, not forcing it `fixed` causes content shift.

🐛 Make amp-consent position: fixed !important

---

src/error.js

Separate module and nomodule build errors

make the module build report as esm

---

extensions/amp-analytics/0.1/test/vendor-requests.json
extensions/amp-analytics/0.1/vendors/webengage.json

This PR adds more params in the requests being sent by WebEngage vendor in amp-analytics component.

♻️More attributes added in webengage amp-analytics vendor config

---

extensions/amp-next-page/amp-next-page.md

Fixes https://github.com/ampproject/amp.dev/issues/3773.
/cc @CrystalOnScript

📝 Fence literal mention of amp-next-page

---

extensions/amp-story-education/0.1/amp-story-education.js
extensions/amp-story-education/0.1/test/test-amp-story-education.js
extensions/amp-story/1.0/_locales/default.js
extensions/amp-story/1.0/_locales/en.js
src/localized-strings.js

Only show the swipe education if the swipe capability is present.
Closes #27097

Only show the swipe education if the swipe capability is present.

---

extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/page-advancement.js
extensions/amp-story/1.0/test/test-amp-story.js

Expose the `advancementMode` with the `selectDocument` messaging.

Expose the advancementMode with the selectDocument messaging.

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

Previous release: 0.1.22.97
Update dependency rollup to v2.3.0 (#1030)
Update dependency autoprefixer to v9.7.5 (#1029)
Update dependency prettier to v2.0.2 (#1028)

SwG release 0.1.22.98

---

extensions/amp-story/1.0/amp-story-draggable-drawer-header.css

Dark more drawer header color update.
cc @hongwei1990

Dark more drawer header color update.

---

extensions/amp-list/0.1/amp-list.js
extensions/amp-mustache/0.2/amp-mustache.js

Addresses https://github.com/ampproject/amphtml/issues/25596#issuecomment-604585579
**image**
cc @morsssss

amp-list: user().fine debug info for template rendering

---

validator/validator-main.protoascii

- cl/303432005 Revision bump for #27174

cl/303432005 Revision bump for #27174

---

extensions/amp-ad/amp-ad.md

This blocks the build since the build check fails.

📖 Remove reference to diaonomi

---

ads/rakutenunifiedads.md

Update document for amp_ad rakutenunifiedads

Update document for amp_ad rakutenunifiedads

---

extensions/amp-timeago/amp-timeago.md

amp-timeago: Fix weird HTML formatting in doc

---

src/dom.js

Noticed a typo was preventing fullscreen in a few edge cases, hope this helps!

[dom.js] Fix fullscreen util issue 🐛

---

README.md

This adds a link to the AMP DevX survey to the amphtml README.

Adds a link to the AMP DevX survey to the amphtml README

---

extensions/amp-social-share/0.1/amp-social-share.js

[amp-social-share]: Allow component to prerender

---

build-system/tasks/performance/stats.js

Account for 1 run when taking the trimmed mean of a performance test result. Thanks @micajuine-ho  for pointing it out :)

🏗Performance test bug fix

---

extensions/amp-story/amp-story-grid-layer.md

Resolves [issue 3782](https://github.com/ampproject/amp.dev/issues/3782)

removed amp-analytics from valid child list of amp-story-grid-layer

---

extensions/amp-subscriptions/0.1/amp-subscriptions.js
extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js

🐛 amp-subscriptions: Allow platforms to register but don't fetch entitlements on free pages

---

build-system/compile/sources.js
build-system/tasks/presubmit-checks.js
package.json
src/amp-story-player-impl.js
yarn.lock

Partial for #27588
Adds `toolbox-cache-url` as a node module and imports it in the player as a dependency.

🏗 [amp-story-player] Adds toolbox-cache-url as a dependency

---

tools/experiments/experiments.js

🏗 Add opt-in option to nightly release channel

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

Previous release: 0.1.22.98
Update dependency autoprefixer to v9.7.6 (#1047)
Change to self[] access in crypto.js (#1046)
Update dependency prettier to v2.0.4 (#1044)
Update dependency gulp-load-plugins to v2.0.3 (#1045)
Changes googleTransactionID, under experiment, to contain swg (#1037)
Update dependency prettier to v2.0.3 (#1043)
Update dependency rollup to v2.3.3 (#1042)
Update dependency chromedriver to v80.0.2 (#1041)
Update random.js for ie11 compatibility (#1040)
Removes third_party/encryption/aes_gcm.js and directory (#1039)
Update dependency rollup to v2.3.2 (#1036)
Update dependency gulp-git to v2.10.1 (#1035)
Update dependency karma-sauce-launcher to v4.1.2 (#1033)
Update dependency rollup to v2.3.1 (#1034)
Update dependency browserify to v16.5.1 (#1031)
Update dependency …

swg release 100
