ampproject/amphtml

extensions/amp-autocomplete/amp-autocomplete.md
The documentation for `amp-autocomplete` was missing a code block around a `<amp-autocomplete>` Tag, causing that sentence to be cut off.
=> 📖 Fix rendering of amp-autocomplete docs

extensions/amp-list/amp-list.md
This PR clarifies the autoexpansion of the overflow element in `amp-list`.
I used the following code to figure out the behavior:
```html
<!doctype html>
<html ⚡>
<head>
<meta charset="utf-8">
<title>amp-list - Example 2</title>
<script async src="https://cdn.ampproject.org/v0.js"></script>
<script custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js" async></script>
<script custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js" async></script>
<link rel="canonical" href="https://preview.amp.dev/documentation/components/amp-list.example.2.html">
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal …
```
=> 📖 Clarify autoexpansion of amp-lists overflow element

ads/yahoonativeads.js, ads/yahoonativeads.md, examples/ads.amp.html
Updating the current `yahoonativeads` ad integration
- Switch to new production `native.js`
- Update props, readme, and example
=> 🔥🐛update yahoonativeads script and example [amp-embed type=yahoonativeads]

build-system/global-configs/experiments-config.json
`environment` is used to determine whether to enable this experiment branch for inabox and/or web during promotion.
@danielrozenberg I believe the names need to be lowercase. Am I wrong?
=> Add environment variable to RTV experiment

build-system/tasks/karma.conf.js
Recently, there have been a spate of Travis timeouts due to tests taking too long on Sauce labs. This is correlated to the fact that we've recently started running more tests on Chrome, and they sometimes take > 5 mins total.
For example, here's info from the Sauce Labs failure corresponding to [this](https://travis-ci.org/ampproject/amphtml/jobs/581290688) build:
This PR increases the `idleTimeout` value to 10 mins, to allow tests to run for that long before timing out.
Possible fix for #24286
=> 🏗 Increase duration for which Sauce VMs are allowed to run tests

build-system/amp.extern.js, build-system/server/amp4test.js, build-system/server/app-index/index.js, build-system/server/app-utils.js, build-system/server/app-video-testbench.js, build-system/server/app.js, build-system/server/routes/a4a-envelopes.js, build-system/tasks/lint.js, build-system/tasks/runtime-test/runtime-test-base.js, build-system/tasks/serve.js, build-system/tasks/visual-diff/index.js
With #24325, `gulp serve` was re-implemented as an in-process server. As a result, the following instances of cross-process message passing via `process.env` in `build-system/` can be removed:
- `process.env.LOCAL_PR_CHECK` (not used anywhere)
- `process.env.WEBSERVER_QUIET` (replaced by `webserver_debug`)
- `process.env.SERVE_MODE` (replaced by `getServeMode()`)
Follow up to #24325
Related to #24141
=> 🏗 Remove unnecessary `process.env` references in `build-system/`

validator/webui/@polymer/webui-mainpage/webui-mainpage.html
The AMP documents shown at https://validator.ampproject.org/ are not actually as minimally valid as they can be: the XML self-closing slash should be removed.
```diff
- <link rel="canonical" href="self.html" />
+ <link rel="canonical" href="self.html">
```
The `meta`  tags lack the self-closing slashes and there's no treason for the `link` tags to have them. This is HTML not XHTML.
=> 🚮 Remove XML self-closing slash from rel=canonical link tags in validator example pages

examples/visual-tests/amp-story/amp-story-consent.html, examples/visual-tests/amp-story/amp-story-consent.rtl.html, test/visual-diff/visual-tests
Re-enable `amp-story-consent` percy tests.
Let's see how that goes. I've done some testing and see no no reason why this one would flake.
Fixes #23987
=> Re-enable amp-story-consent percy tests.

build-system/tasks/dist.js
At the end of the dist task, generate a complete listing of files
included in the distribution.
Fixes #24302
=> 🏗 build: Include file listing with dist

src/runtime.js, src/service/extensions-impl.js
Because `amp-mustache` is registered as `<script custom-template="amp-mustache">`, we failed to find the currently-loaded-but-incorrect-version script in `maybeLoadCorrectVersion`. Now, we defer that responsibility to the extension loader service.
=> 🐛 Ensure amp-mustache is version locked to v0.js

build-system/global-configs/README.md, build-system/global-configs/experiments-config.json
As we agreed added two types of experiment environment. Or maybe `type` is a better name?
@estherkim I don't know if it matters. But do you think we should run integration test for experiment that's only built for inabox?  
Thanks.
=> Add environment type to experiment config

examples/cmp-vendors.amp.html, extensions/amp-consent/0.1/cmps.js, extensions/amp-consent/amp-consent.md, extensions/amp-consent/cmps/sourcepoint.md
* Add SourcePoint to the CMPs list
* Add the required documentation
* Example 
* Instructions 
* Front page 
@zhouyx not sure if I'd have to tag you here since this is a PR related to `<amp-consent>` sorry if that's unnecessary.
=> amp-consent :sparkles: :book: Add SourcePoint to CMPs list

build-system/global-configs/experiments-config.json
Fixes master.
```
/home/travis/build/ampproject/amphtml/build-system/build.conf.js:94
throw new Error(
^
Error: experimentA has expired on Sun, 08 Sep 2019 00:00:00 GMT. Please remove from experiments-config.json and cleanup relevant code.
```
https://travis-ci.org/ampproject/amphtml/jobs/582527777
This was last broken a month ago in #23809. @zhouyx Are these expiry dates arbitrary? If so, we should pick a further date that doesn't break next month.
=> Move ANALYTICS_VENDOR_SPLIT expiry back one month

build-system/global-configs/experiments-config.json
I did not notice the existing key when I added the lowercase `environment`s.
cc @zhouyx
=> Remove conflicting experiments-config

build-system/server/lazy-build.js, build-system/tasks/build.js, build-system/tasks/extension-helpers.js, build-system/tasks/serve.js, contributing/getting-started-e2e.md
- Makes lazy building the default behavior of `gulp`
- Adds the `--eager_build` flag which eagerly builds all JS files and extensions after server startup
- Cleans up code that passed `argv` to `preBuildSomeExtensions()` (unnecessary after #24325)
- Moves the `if (lazyBuild)` blocks in `performBuild()` to `defaultTask()`
- Updates `parseExtensionFlags()` to distinguish between lazy and eager building
- Removes the outdated `--extensions=minimal_set` in favor of the always up to date `--extensions_from=examples/article.amp.html`
- Updates developer docs to describe the new behavior of `gulp`
**Usage:**
```js
// Lazily build all JS and extensions
gulp
//  Eagerly build amp-foo and amp-bar, lazily build the rest
gulp --extensions=amp-foo,amp-bar
//  Eagerly build …
```
=> 🏗 Lazy build by default during `gulp` and replace `--lazy_build` with `--eager_build`

test/integration/test-amphtml-ads.js
Build cop skips flaky tests. :) Filed #24421 for follow-up.
/to @jridgewell /cc @lannka
=> Skip flaky a4a integration test

test/integration/test-amp-ad-3p.js
Looks like `Referer` is no longer available in Chrome 77 (went to stable today).
```
DESCRIBE => amp-ad 3P
IT => create an iframe with APIs
✗ AssertionError: expected '' to include 'http://localhost:9876'
at http://localhost:9876/home/travis/build/ampproject/amphtml/test/integration/test-amp-ad-3p.js:124:39
[19:13:05] HeadlessChrome 77.0.3865 (Linux 0.0.0): Executed 262 of 440 (Skipped 178) 1 FAILED
```
https://travis-ci.org/ampproject/amphtml/jobs/583312743
/to @lannka
=> Fix test-amp-ad-3p.js in Chrome 77

extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js, test/unit/test-url-replacements.js
In Chrome 77 `Document.referrer` is now empty string in test iframes.
Fixes 4 broken tests on master: https://travis-ci.org/ampproject/amphtml/jobs/583391139
And wow our "unit tests" are something else. :)
=> Fix Document.referrer tests in Chrome 77

extensions/amp-subscriptions/0.1/dialog.js, extensions/amp-subscriptions/0.1/doc-impl.js, extensions/amp-subscriptions/0.1/test/test-dialog.js, src/service/fixed-layer.js, third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
SwG Release 0.1.22.67
Version: 0.1.22.67
Previous release: 0.1.22.65
include addToFixedLayer() in Doc for AMP compatibility (#652)
fix missing assert include and bad type (#653)
Tie UUID to time (#651)
Generate a better UUID (#648)
Analytics config (#649)
=> SwG Release 0.1.22.67

build-system/tasks/bundle-size.js
Attempt to fix the issue raised in https://github.com/ampproject/amphtml/pull/24418#issuecomment-529698706 based on suggestion in https://github.com/ampproject/amphtml/pull/24418#issuecomment-530151391
=> 🏗 Normalize RTV number before determining Brotli compressed size

extensions/amp-list/0.1/test/validator-amp-list.html, extensions/amp-list/0.1/test/validator-amp-list.out, extensions/amp-list/validator-amp-list.protoascii
Follow-up to #23470. Public documentation coming soon.
/to @honeybadgerdontcare /cc @cathyxz
=> Make amp-list[diffable] valid

extensions/amp-loader/0.1/amp-loader.css, extensions/amp-loader/0.1/spinner.js
The new Chrome layout engine has a bug with SVGs and position: absolute.
Since this has already launched, workaround the issue using a wrapping
element.
See: https://bugs.chromium.org/p/chromium/issues/detail?id=1002748
Note: Chrome 77 is launching today, unclear if this meets the cherry-pick criteria, but we may want to consider unlaunching the loaders or cherry-picking this.
Fixes #24393
/cc @nainar
=> 🐛Work around a Chrome layout bug introduced in Chrome 77.

src/service/standard-actions-impl.js, test/unit/test-standard-actions.js
Fixes #24457 
toggleClass action should be applicable to all classes (including `amp-*` and `-amp-*`) except those with `i-amphtml-` prefixes.
@cathyxz @choumx
=> 🐛 exclude amp- prefixes from reserved class

extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/test-amp-list.js
amp-list with placeholder already does this. I just forgot to add it.
/to @cathyxz
=> 🐛 amp-list[diffable]: Fit to initial content on layout

extensions/amp-animation/0.1/runners/native-web-animation-runner.js
Closes #24455
Dirty fix for a bug on Safari and Edge that prevents animations from resuming when switching tabs caused by a bug in the playState of animations (set to `pending` until the next call as opposed to `paused` or `running`).
=> 🐛Fixes bug with Safari/Edge animations not resuming

src/polyfills/custom-elements.js
There was a bug where cloning in/out of a `<template>` would upgrade the custom element nodes even if the tree belonged to the template's document (which is distinct from the page's document).
Fixes https://github.com/ampproject/amphtml/issues/24462
=> 🐛 CEv1: Only upgrade nodes if ownerDocument matches registry doc

build-system/global-configs/canary-config.json
Temporary fix for https://github.com/ampproject/amphtml/issues/24470.
=> Turn custom-elements-v1 experiment off in canary

OWNERS.yaml, css/OWNERS.yaml, test/OWNERS.yaml
Some existing OWNERS files have errors. This PR:
- removes empty OWNERS.yaml files
- removes unnecessary `@` prefix before teams/usernames
- fixes protoascii glob pattern in root owners file
=> 🐛 Fix existing syntax errors in OWNERS.yaml files

extensions/amp-a4a/0.1/real-time-config-manager.js
When someone supplies a timeout we check whether that's >= than the default timeout, and if so warn and fall back to the default.  This means that if you set tie timeout to the default you'll get an inappropriate warning.  Change to only warning when it's > than the default.
The only behavior change here is that we're no longer emitting a warning.
Fixes #24163.
=>  🐛Remove erroneous timeout warning

extensions/OWNERS.yaml, extensions/amp-3q-player/OWNERS.yaml, extensions/amp-brid-player/OWNERS.yaml, extensions/amp-delight-player/OWNERS.yaml, extensions/amp-kaltura-player/OWNERS.yaml, extensions/amp-nexxtv-player/OWNERS.yaml, extensions/amp-o2-player/OWNERS.yaml, extensions/amp-ooyala-player/OWNERS.yaml, extensions/amp-reach-player/OWNERS.yaml, extensions/amp-springboard-player/OWNERS.yaml, extensions/amp-wistia-player/OWNERS.yaml
All extensions ending in `-player` by convention are video players and are owned by @alanorozco and @wassgha . This PR:
- Adds `alanorozco` and `wassgha` as owners for all files `extensions/**/*-player.(js|md)`
- Removes duplicate ownership declarations in individual extension OWNERS files for @alanorozco (who owns all `*-player.(js|md)`) and @aghassemi (who is an owner of the full `extensions` directory
- Deletes empty OWNERS files
=> 🏗 Update ownership rules for extensions/**/*-player.js

OWNERS.yaml, validator/OWNERS.yaml
This PR:
- adds @ampproject/wg-caching as an owner of the `validator` directory
- removes the individual owners from the list (as they are all team members)
- adds @ampproject/wg-caching as an owner of all `validator-*.protoascii` files
@honeybadgerdontcare I noticed there are also files of the form `validator-*.html` and `validator-*.out`; are these also under your purview?
=> 🏗 Update ownership rules for validator files

src/polyfills.js
There is an init order conflict between experiment framework and logging infra. Disable the call for quick cherry-pick before we do a better fix.
This is a partial rollback of #24215
Fixes #24499
=> Temporary fix: Disable custom element experiment check because it happens too early

.travis.yml
All jobs on push builds share the same cache. However, the visual diff and e2e jobs require extra npm packages, which aren't always present in the cache. This results in an error where the only fix is to manually delete the cache and restart the job.
This creates separate caches for the visual diff and e2e jobs.
=> 🏗 Prevent corrupt Travis caches

build-system/server/app.js, package.json, yarn.lock
We have been depending on https://github.com/ampproject/amphtml/blob/master/.travis.yml#L34 to override DNS for *.localhost on Travis, but it does not exist on local dev environment. I find this evil-dns module that would inject into DNS module and overwrite DNS for the current nodejs instance only, so we do not have to depend on travis /etc/hosts.
=> Soft DNS rewrite for various dev envelops

build-system/dep-check-config.js, extensions/amp-base-carousel/0.1/amp-base-carousel.js, extensions/amp-base-carousel/0.1/carousel-accessibility.js, extensions/amp-base-carousel/0.1/carousel-events.js, extensions/amp-base-carousel/0.1/carousel.js, extensions/amp-base-carousel/0.1/child-layout-manager.js, extensions/amp-base-carousel/0.1/test/test-child-layout-manager.js, extensions/amp-carousel/0.2/amp-carousel.js, extensions/amp-carousel/0.2/test/test-type-slides.js
- Make this more robust to when IntersectionObserver fires. While this
is not a problem for amp-carousel, it is a problem for amp-stream-gallery,
causing it to sometimes not detect slides to layout on the initial render.
- Explicitly turn on/off queuing of changes during scroll rather than turning
it off all the time and trying to catch the next IntersectionObserver
changes after layout.
- Rename the internal carousel events to use a namespace, to avoid clashing
with DOM events in the future.
=> Change how carousel queuing of layout visibility works for iOS.

src/log.js
The `toString()` method won't be able to serialize `null` or `undefined`, but `String()` will.
=> 🐛 Logging message toString() blunder fix

build-system/global-configs/canary-config.json, build-system/global-configs/experiments-config.json, src/friendly-iframe-embed.js, src/polyfills.js, tools/experiments/experiments.js
This sidesteps https://github.com/ampproject/amphtml/issues/24499 by using an RTV experiment instead of a local experiment.
Also, it'll show the performance benefits, since we'll be able to DCE the old polyfill code. 😃
=> ♻️ Redefine custom-elements-v1 as an RTV experiment

examples/amp-story/embed.html, src/amp-story-embed.js
Basing this on a tag name will help to unify the AMP and non-AMP APIs, but keeping the implementation will avoid having to include the custom element polyfill.
WDYT?
=> Use tagname for creating story embeds

.gitignore, build-system/sauce_connect/start_sauce_connect.sh, contributing/TESTING.md
**Start proxy:**
```sh
export SAUCE_USERNAME=<username>
export SAUCE_ACCESS_KEY=<access key>
./build-system/sauce_connect/start_sauce_connect.sh
```
**Stop proxy:**
```sh
./build-system/sauce_connect/stop_sauce_connect.sh
```
=> 🏗✨ Add Mac OS support for the Sauce Labs Proxy launcher script

build-system/server/app.js
Previously the protocol-relative URLs could get confused if the doc has a base URL.
=> Make JS URLs more robust in local testing

build-system/tasks/dist.js, build-system/tasks/helpers.js
This PR reorganizes `dist()` to eliminate unnecessary parallelism, while maintaining the advantage of building runtime JS files and extensions respectively in parallel.
Implements the idea in https://github.com/ampproject/amphtml/issues/24487#issuecomment-532411620
Potential fix for #24487
=> 🏗 Reorganize `dist()`

extensions/amp-facebook/amp-facebook.md
This updates the `amp-facebook` docs to use amp.dev's new inline examples and while doing so is part of the fixes for ampproject/amp.dev#2914.
That's how this will render on amp.dev:
=> 📖 Use inline examples for amp-facebook docs

extensions/amp-script/amp-script.md
Fixes #24378.
I kept some of the runtime errors under an "Errors" section. I think it's useful for developers who might copy/paste and CTRL+F for console errors they see during development.
/to @CrystalOnScript
=> Better amp-script docs

build-system/pr-check/remote-tests.js, build-system/tasks/karma.conf.js, build-system/tasks/runtime-test/helpers.js, build-system/tasks/runtime-test/runtime-test-base.js
Runs integration tests in 2 different commands:
`gulp integration --nobuild --compiled --saucelabs --stable`
`gulp integration --nobuild --compiled --saucelabs --beta`
Does not run tests in batches. `--stable` and `--beta` only applies for sauce labs tests.
Behavior for `gulp integration --nobuild --compiled --saucelabs` remains the same.
Rename private methods from `method()` to `method_()`.
Possible fix for https://github.com/ampproject/amphtml/issues/24575
=> 🏗 Run Travis integration tests on Sauce Labs with 2 different commands

extensions/amp-analytics/0.1/analytics-root.js, extensions/amp-analytics/0.1/events.js, extensions/amp-analytics/0.1/instrumentation.js, extensions/amp-analytics/0.1/test/test-events.js, test/integration/test-amp-story-analytics.js
Partial rollforward of #23030
* Configurable options (StorySpec) e.g. `repeat: false` option. This will come in a follow up
* Integration tests
* New tracker `AmpStoryEventTracker` which inherits from `CustomEventTracker`. This will make it possible for us to build story-specific features in analytics (e.g. `storySpec`).
=> 📈 AmpStoryEventTracker & Integration tests

OWNERS.yaml
Most of the files in the repo root directory have to do with packages, infrastructure, or documentation. This PR adds owners for each category. 
- Packages: @ampproject/wg-infra, @ampproject/wg-runtime, @ampproject/wg-performance
- Infrastructure (all dot-files plus a few more): @ampproject/wg-infra 
- Documentation: @ampproject/wg-outreach 
Let me know if you think these aren't the right sets of owners.
=> 🏗 Specify owners for files in the repo's root directory

build-system/tasks/e2e/functional-test-controller.js, build-system/tasks/e2e/selenium-webdriver-controller.js, extensions/amp-ad-exit/0.1/test-e2e/test-amp-ad-exit.js, test/fixtures/e2e/amphtml-ads/amp-ad-exit.amp.html
There is no convenient way to intercept beacon calls right now, so I'll defer that part. This PR adds a few e2e tests for amp4ads amp-ad-exit.
I added two new interfaces into `functional-test-controller.js`.
=> Add e2e test for amp-ad-exit

test/_init_tests.js, test/integration/test-amp-story-analytics.js
They are flaking on master
https://travis-ci.org/ampproject/amphtml/jobs/587116429
```
IT => should send analytics event when navigating
✗ AssertionError: expected 'page-1' to equal 'page-2'
at _callee2$ (home/travis/build/ampproject/amphtml/test/integration/test-amp-story-analytics.js:143:35)
at tryCatch (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:65:40)
at Generator.invoke [as _invoke] (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:303:22)
at Generator.prototype.<computed> [as next] (home/travis/build/ampproject/amphtml/node_modules/regenerator-runtime/runtime.js:117:21)
at asyncGeneratorStep (/tmp/637d6ae55d488af8c723bc9ffe1cea60.browserify.js:99961:103)
at _next …
```
=> Skip flaky story analytics integration tests

build-system/pr-check/remote-tests.js, build-system/tasks/report-test-status.js, build-system/tasks/runtime-test/helpers.js
- Separate duplicate `integration/saucelabs` test status into `integration/saucelabs-stable` and `integration/saucelabs-beta`
- Split up execution into stable and beta for push builds too
- Report results / totals / errors for beta runs
- Set an "error" status when zero tests are detected, but don't exit (allows recovery in cases like [this](https://travis-ci.org/ampproject/amphtml/jobs/586766065#L2161-L2166))
- Fix logging
**Fixes [this](https://github.com/ampproject/amphtml/pull/24619/checks?check_run_id=227541301) error:**
Follow up to #24613
=> 🏗 Follow up changes to integration tests on sauce labs

build-system/tasks/nailgun.js
It's possible that the operation to stop the nailgun server after `gulp dist` occasionally causes Travis builds to stall. Since this is a non-essential cleanup step, it makes sense to make the operation time-bound and non-blocking.
This PR implements the idea in https://github.com/ampproject/amphtml/issues/24487#issuecomment-533321019 and gives the process 5 seconds to execute before printing a warning and continuing.
**Reference:** See the `timeout` option of [`child_process.spawnSync()`](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options)
Potential fix for #24487
=> 🏗 Make `nailgun` server stoppage a time-bound operation and log errors if any

build-system/server/routes/a4a-envelopes.js
Gracefully handle failure from envelop request promise. Currently it just silently crashes the server.
=> Handling a4a envelop crash

package.json, yarn.lock
Upgrade past 2.0.1 for this:
> Fixed a bypass affecting latest Chrome, caused by a newly discovered Chrome mXSS vulnerability
Not sure why renovate-bot didn't generate the PRs for 2.x.x. 
https://github.com/cure53/DOMPurify/releases
=> Upgrade DOMPurify to 2.0.2

OWNERS.yaml, extensions/OWNERS.yaml
Upgrades to the owners bot parser include support for brace-set expansion, ie `*.{js,css}`. This PR updates currently-duplicated rules to use this syntax.
=> 🏗 Updates existing OWNERS.yaml files with brace-set and modifier syntax1

extensions/amp-autocomplete/0.1/amp-autocomplete.js, extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js, extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Resolves #23772 
Currently amp-autocomplete will fetch remote data source on layout. This change:
- delays this initial fetch until the user first interacts with the input field contained in the component
- does not impact behavior for data provided inline
=> 🐛 amp-autocomplete: Fetch remote data after first user interaction

build-system/tasks/e2e/describes-e2e.js
Sometimes in Travis, chromedriver fails to start up.
```
1) amp-bind with <amp-video>
chrome
AMPHTML ads inabox environment 
"before each" hook for "should NOT change src when new value uses an invalid protocol":
WebDriverError: unknown error: Chrome failed to start: exited abnormally
(chrome not reachable)
(The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
So I added a retry mechanism. Note that this is different than `this.retries()` in mocha, because mocha retries only work for tests themselves, not hooks.
=> 🏗 Allow retries for e2e test setup and set retries to 1

extensions/amp-autocomplete/amp-autocomplete.md
Resolves #24684 
The `<` and `>` tags around `<amp-autocomplete>` in the documentation render the component on its documentation page instead of displays it as the desired text literal. This causes the section to end mid-sentence on the [amp.dev](https://amp.dev/documentation/components/amp-autocomplete/#attributes):
=> 📖 Update amp-autocomplete documentation

src/inabox/inabox-viewport.js
Tested locally. The bug should be caught by integration tests on Safari 11 (to be enabled #24666)
=> Fix inabox viewport

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js
In #24044 I introduced some code that would allow the outlink url to come from amp-ad-exit. This allows some partner teams to use this option while waiting on full story ad integration. 
Because the outlink can now be in the amp ad exit we should no longer throw when no `cta-url` meta tag is present.
This should probably be reinstated as part of work in #24080
=> 🐛Story Ads: Don't require outlink meta tag

src/cookies.js, tools/experiments/experiments.html, tools/experiments/experiments.js
With Chrome 78 (beta) and Chrome 80 (stable), cookies will be set with `SameSite=Lax` by default. This prevents the canary/rc cookie from being sent when the page is not on the cdn.ampproject.org domain when requesting v0.js.
Fixes #24643
/cc @jridgewell
=> Use SameSite=None for canary cookie.

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, css/ampshared.css, extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-ad/0.1/amp-ad-3p-impl.js, extensions/amp-ad/0.1/amp-ad-custom.js, extensions/amp-ad/0.1/amp-ad-ui.js, src/custom-element.js, src/loader.js, test/manual/loaders.amp.html, test/unit/test-custom-element.js, tools/experiments/experiments.js
- Remove the legacy loaders code and CSS.
- Remove experiment checks and flags.
- Reword references to the "new" loader.
Closes #21485
=> 🚮Cleanup for the new loaders.

extensions/amp-a4a/0.1/callout-vendors.js
Adds the gdpr_consent and account parameters to Rubicon and AppNexus Prebid Server RTC vendor entries
=> ✨Callout vendor update: adding gdpr_consent and account to Prebid Server urls

extensions/amp-base-carousel/0.1/carousel.js, extensions/amp-carousel/0.2/amp-carousel.js, extensions/amp-carousel/0.2/test/test-type-slides.js
- Change the carousel implementation to stop notifying when the internal index did not actually change. Note that the initial change is from `NaN` to an actual index, so that will still notify.
- Change the carousel 0.2 code to only fire the slideChange event/action after the first one (from the initial render).
Closes #24706
Fixes #24701
=> Do not trigger slideChange on the initial render.

build-system/server/amp-cors.js, build-system/server/app.js, spec/amp-cors-requests.md
I cannot figure out what purpose the `__amp_source_origin` serves now. I believe I left it behind in the last PR (#22648) due to oversight.
Let me know if you'd like to add a "__amp_source_origin is deprecated" section.
Closes #22136.
Followup on #22648.
=> Remove __amp_source_origin from the documentation

extensions/amp-story/1.0/test/test-amp-story-bookend.js, extensions/amp-story/1.0/test/test-amp-story-consent.js, extensions/amp-story/1.0/test/test-amp-story-cta-layer.js, extensions/amp-story/1.0/test/test-amp-story-embedded-component.js, extensions/amp-story/1.0/test/test-amp-story-info-dialog.js, extensions/amp-story/1.0/test/test-amp-story-media-query-service.js, extensions/amp-story/1.0/test/test-amp-story-page.js, extensions/amp-story/1.0/test/test-amp-story-request-service.js, extensions/amp-story/1.0/test/test-amp-story.js, extensions/amp-story/1.0/test/test-live-story-manager.js, extensions/amp-story/1.0/test/test-media-tasks.js
Got an improvement idea while working on https://github.com/ampproject/amphtml/pull/24719 (cf comment inline in that PR code) that would need this, and I got carried away...
=> Refactoring stories tests to use async/await.

extensions/amp-story-auto-ads/amp-story-auto-ads.md
Fixes a teeny tiny typo in the documentation for `amp-story-ads` that I just stumbled upon.
=> 🐛📖 Fix  typo in amp-story-ads docs

extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story.js
Deduplicates `amp-story-page` ids and triggers a user error, so the story doesn't fail on load.
Having duplicated IDs completely fails navigation or the progress bar.
```
<amp-story-page id="cover">
<amp-story-page id="cover">
```
becomes
```
<amp-story-page id="cover">
<amp-story-page id="cover__1">
```
=> Deduplicates amp-story-page ids.

ads/ix.md
=> 📖Updated rtc-config specification details in IX.md

ads/google/a4a/test/test-utils.js, ads/google/a4a/utils.js
I named the param same as the experiment prefix. 
One thing I found is that the param is only used for A4A, not related to inabox. So I left the `experimentX-control` alone. 
We should also document all the new AMP_CONFIG.type somewhere. 
to @erwinmombay @jeffkaufman
=> Pass experiment channel via the AmpRuntimeTypeParam

extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story.js
Store story page IDs from the buildCallback.
Also, updating the tests so the story is created with its pages already in the DOM.
Our previous implementation wasn't optimal: creating and attaching the story from `beforeEach` would trigger `buildCallback` before we append the pages.
In practice, that means that the timeline was
- `buildCallback` -> append `amp-story-page`s -> `layoutCallback`
and is now
- append `amp-story-page`s -> `buildCallback` -> `layoutCallback`
=> Store story page IDs from the buildCallback.

build-system/tasks/presubmit-checks.js, extensions/amp-experiment/0.1/amp-experiment.js, extensions/amp-experiment/1.0/amp-experiment.js, src/base-element.js, src/custom-element.js, src/service/resource.js, src/service/resources-impl.js, test/unit/test-resources.js
As we agreed offline, this PR 
1. Allow `<amp-experiment>` component to prerender
2. Introduce restricted `isBuildRenderBlocking()` method to bypass the 20 maximum build count
=> Allow amp-experiment to prerender and bypass maximum build limit

3p/beopinion.js
=> 🐛 Fix BeOp's style issue with flex

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
=> ♻️Refactor amp-ad-network-adsense-impl to move logic related to rive to a separate helper class

extensions/amp-twitter/0.1/OWNERS.yaml
This PR is part of a general owners cleanup effort.
PR #24743 added `ampproject/wg-ui-and-a11y` as an owner of `extensions/amp-twitter`. Since `nainar` is a member of that team, the rule in `extensions/amp-twitter/0.1/OWNERS.yaml`, which just has `nainar`, would unnecessarily assign `nainar` higher relevance. This PR removes the unneeded OWNERS.yaml file.
=> 🏗 Remove nainar as explicit owner (present in team)

extensions/amp-carousel/0.1/slidescroll.js, test/manual/amp-carousel/0.1/slides.amp.html, test/manual/amp-carousel/0.2/slides.amp.html
One effect of these changes is that on slow swipes, the carousel
takes longer to switch over to the snapped slide, since the scroll
momentum needs to stop before the snap instead of snapping shortly after
the touch is released.
- Change how the snapping/scroll end is handled with respect to touch
events and scroll.
- As long as the user is touching, do not snap the position.
- Do not snap after swipe is released like before, wait for scrolling
to stop.
- Increase the timeout after the last scroll event to be more robust.
Fixes #24541
=> 🐛Fix non-carousel scrolling on iOS 13 reverting to first slide.

src/polyfills/custom-elements.js
We're getting an error from `setPrototypeOf` somehow not being a method on `Object`.
=> 🐛 Use __proto__ instead of setPrototypeOf

extensions/amp-bind/0.1/bind-expression.js, extensions/amp-bind/0.1/test/test-bind-expression.js, extensions/amp-bind/amp-bind.md
Fixes https://github.com/ampproject/amphtml/issues/23133
Testing done:
- `yarn run gulp unit --files=extensions/amp-bind/0.1/test/test-bind-expression.js`
~Note: I haven't marked this PR as "ready" yet as I am still in the process of reading through the contributor guides.~
=> ✨Whitelists Math.pow for amp-bind

examples/amp-orientation-observer-3d-parallax.amp.html, examples/amp-orientation-observer-amp-3d-gltf.amp.html, examples/amp-orientation-observer-panorama.amp.html, examples/amp-orientation-observer-scroll.amp.html, examples/amp-orientation-observer.amp.html, extensions/amp-orientation-observer/0.1/amp-orientation-observer.js, extensions/amp-orientation-observer/0.1/test/test-amp-orientation-observer.js, extensions/amp-orientation-observer/0.1/test/validator-amp-orientation-observer.html, extensions/amp-orientation-observer/0.1/test/validator-amp-orientation-observer.out, extensions/amp-orientation-observer/amp-orientation-observer.md, extensions/amp-orientation-observer/validator-amp-orientation-observer.protoascii, src/utils/math.js, test/unit/utils/test-math.js
Closes #19326 , Closes #24400 
- Adds a configurable smoothing of the `alpha`/`beta`/`gamma` values (the configurable value is the subset size used to generate the moving average)
- Dynamically reads the rest values of `alpha`/`beta`/`gamma` instead of defaulting to `0`
- Clamps the values to the provided ranges
- Adds the required validator tests
=> ✨Adds smoothing to amp-orientation-observer

extensions/amp-carousel/0.1/amp-carousel.md, extensions/amp-carousel/amp-carousel.md
- Change example for customizing arrows to have encoded characters, add note about the fact that they must be encoded.
* Unlike AMP's CSS source, which is run through SVGO, developers may copy our example and try to use it directly, which does not work without encoding characters.
- Remove link to 0.1 documentation, it is now built-into the docs site.
Closes #24654
Closes #24419
=> 📖 Update for amp-carousel documentation

extensions/amp-auto-lightbox/OWNERS.yaml
This PR is part of a general owners cleanup effort.
PR #24743 added `ampproject/wg-ui-and-a11y` as an owner of `extensions/amp-auto-lightbox`, which previously just had `alanorozco`. Since he's a member of that team already, the rule is unnecessary, so this PR cleans that up.
=> 🏗 Remove alanorozo as explicit owner (present in team)

extensions/amp-story/1.0/progress-bar.js
Corrects spelling in the definition and usages of the `assertValidSegmentId_` method name (was previously `assertVaildSegmentId_`).
Resolves #24715
=> 🐛 Fix typo in assertValidSegmentId_ method name

extensions/amp-story/1.0/test/test-amp-story.js
Removes error message in `amp-story consent` test by adding a `nodisplay` layout attribute.
Resolves #24762
=> 🐛Add layout attribute to amp-story-consent test element

build-system/tasks/runtime-test/runtime-test-base.js, test/integration/test-amphtml-ads.js, testing/describes.js
Original PR is #24666. Adds test coverage to Safari 11 to test the IntersectionObserver polyfill, and fix a race condition in the test itself that would cause it to fail otherwise.
=> Enable Saucelabs tests on Safari 11 and fix Inabox tests

extensions/amp-a4a/0.1/callout-vendors.js
- added CONSENT_STRING macro to aps prebid url for GDPR support
#addowners
=> ✨Callout vendor update: added consent_string macros to aps prebid url

extensions/amp-bind/0.1/bind-impl.js
Causes surprising `amp-list` re-render on some complex pages e.g. `b/141334021`.
=> amp-bind: Increase equality check depth to 20

extensions/amp-list/validator-amp-list.protoascii
Meant to do this in #24467 but forgot. :p
/to @honeybadgerdontcare
=> Enable amp-list[diffable] in other AMP specs

build-system/tasks/integration.js
We need to run `gulp build` if we want to use unminimized bundle (amp.js vs v0.js). This PR fixes the problem that `gulp integration` by default does not build the right bundle it requires.
=> gulp integration build command consistency

build-system/tasks/presubmit-checks.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js, spec/amp-localstorage.md
See https://github.com/ampproject/amphtml/issues/23568.
=> ✨ Implement ad size optimization for AdSense.

src/element-service.js, src/runtime.js, src/service/extensions-impl.js, test/unit/test-custom-element-registry.js, test/unit/test-extensions.js, test/unit/test-runtime.js
Fixes runtime error on pages that use `amp-viewer-integration` with a mismatched RTV vs. v0.js.
```
extensions-impl.js:265 Uncaught (in promise) TypeError: Cannot read property 'removeAttribute' of null
at gn.f.reloadExtension (extensions-impl.js:265)
at sn (runtime.js:880)
at pn (runtime.js:207)
at un (runtime.js:324)
at wj.kd (amp.js:118)
at vj (chunk.js:192)
at rj.Se (chunk.js:420)
at chunk.js:471
```
`b/141559641`
=> Fix reloadExtension for amp-viewer-integration

extensions/amp-story/1.0/toast.js
Adds the `alert` role to toasts so screen readers assertively announce the content when the toast is displayed.
Resolves #24805
=> ♿Add alert role to toast for screen reader support

examples/amp-story/ads/app-install.html, extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/test-e2e/test-amp-story-auto-ads.js, test/fixtures/e2e/amp-story-auto-ads/dv3-request.html, test/fixtures/e2e/amp-story-auto-ads/dv3-transformed-creative.html
Some ad network partners will transform a creative after upload, including moving content that was previously in the `<body>` into a separate `<div>`.
This is a temporary solution until we have full ad network support or finalize a proper API, see #24829
Also introduces an e2e test with a transformed dv3 creative and removes some dv3 specific html from the base e2e test.
=> Story Ads: propagate visible attr to transformed body.

ads/nativeroll.js
Adding new callback onDestroy in our player and call 'noContentAvailable' on it
=> ✨ noContent on destroy Nativeroll player

ads/lentainform.js
Lentainform widget wouldn't work if first or second char of `data.publisher` is not alphanumeric.
=> 🐛Fix subdomain handling in lentainform widgets

extensions/amp-ooyala-player/0.1/amp-ooyala-player.js, extensions/amp-ooyala-player/0.1/test/test-amp-ooyala.js, extensions/amp-ooyala-player/0.1/test/validator-amp-ooyala.html, extensions/amp-ooyala-player/0.1/test/validator-amp-ooyala.out
The Ooyala player iframe version currently used is at https://player.ooyala.com/static/v4/sandbox/amp_iframe/skin-plugin/amp_iframe.html which is using the player version 4.10.6
Our current production version is at v4.32.8. This update will solve some customer issues with analytics and provide them with a more recent and stable player.
=> 🐛Update Ooyala player version from Sandbox to Prod

extensions/amp-script/amp-script.md
Add "Advanced usages" section that explains how to use `AMP.setState` and `AMP.getState` in amp-script.
=> Document setState/getState in amp-script

extensions/amp-story/1.0/amp-story-system-layer.js
Adds the `alert` role to sound announcements (e.g. "Sound on", "Sound off", or "This page has no sound") to assertively announce the content to screen readers.
Resolves #24807
=> ♿Add alert role to sound announcements for screen reader support

examples/amp-orientation-observer-3d-parallax.amp.html
Instead of the existing fake parallax (which acts only on a single axis) this example uses two parents, one for each axis, giving a more realistic parallax effect.
=> 🐛Adds true parallax to the `amp-orientation-observer` example

extensions/amp-story/1.0/_locales/README.md
Fixes the link to `LocalizedStringId` in the _locales/ README.
[Broken Link](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/localization.js#L32)
[Fixed Link](https://github.com/ampproject/amphtml/blob/master/src/localized-strings.js#L31)
=> 📖Fix broken link to LocalizedStringId in _locales/ README

extensions/amp-analytics/OWNERS.yaml
In a recent PR, the `wg-analytics` team was supposed to be added as an owner of `extensions/wg-analytics`, but it was not prefixed with the `ampproject/` organization so it could not be recognized as a team. This PR corrects that team specification.
=> Correct wg-analytics reference in owners file

build-system/compile/compile.js, build-system/compile/single-pass.js, build-system/tasks/extension-helpers.js, build-system/tasks/helpers.js
Still trying to figure out why `gulp dist` occasionally stalls on Travis. Tried a few things listed in #24487.
**Next steps in this PR:**
- Reduce parallelism for multi-pass `gulp dist` to 1 (doesn't make a substantial difference to running time)
- Add logging + timing for `buildExtensions()` and `compileAllJs()` (so we know when all promises have resolved)
- Fix bug in timing each minification step (we were counting queued time instead of running time, and weren't including the minutes value for longer tasks)
See https://github.com/ampproject/amphtml/issues/24487#issuecomment-533691728
Potential fix for #24487
=> 🏗 Reduce `gulp dist` parallelism on Travis, add some logging

build-system/tasks/bundle-size.js
Fixes #21275
Step 3.i. in https://github.com/ampproject/amphtml/issues/21275#issuecomment-518403361
=> 🏗 Stop reporting gzipped compressed size in the bundle-size task

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
See https://github.com/ampproject/amphtml/issues/23568.
=> Ramp up experiment for AdSense ad size optimization to 1% of AMP traffic

examples/OWNERS.yaml, test/OWNERS.yaml
YAML treats `*` as a special character, so it requires quotes to parse properly.
=> Fix wildcard owners in `test` and `examples`

build-system/tasks/bundle-size.js
Reverts ampproject/amphtml#24418
Reason:
```
dist-bundle-size.js: Running gulp bundle-size --on_push_build...
514[22:55:01] Using gulpfile ~/build/ampproject/amphtml/gulpfile.js
515[22:55:01] Starting 'bundle-size'...
516[22:55:02] Bundle size (brotli) is 71.78KB
517[22:55:02] Could not store the bundle size
518[22:55:02] Error: 400 Bad Request: POST request to /store must have numeric fields "gzippedBundleSize" and "brotliBundleSize"
519[22:55:02] Finished 'bundle-size' after 640 ms
```
=> Revert "🏗 Stop reporting gzipped compressed size in the bundle-size task"

extensions/amp-apester-media/OWNERS.yaml, extensions/amp-brid-player/OWNERS.yaml, extensions/amp-brightcove/OWNERS.yaml, extensions/amp-connatix-player/OWNERS.yaml, extensions/amp-date-display/OWNERS.yaml, extensions/amp-delight-player/OWNERS.yaml, extensions/amp-drilldown/OWNERS.yaml, extensions/amp-fx-flying-carpet/OWNERS.yaml, extensions/amp-gfycat/OWNERS.yaml, extensions/amp-google-vrview-image/OWNERS.yaml, extensions/amp-kaltura-player/OWNERS.yaml, extensions/amp-mowplayer/OWNERS.yaml, extensions/amp-nexxtv-player/OWNERS.yaml, extensions/amp-o2-player/OWNERS.yaml, extensions/amp-ooyala-player/OWNERS.yaml, extensions/amp-playbuzz/OWNERS.yaml, extensions/amp-powr-player/OWNERS.yaml, extensions/amp-reach-player/OWNERS.yaml, extensions/amp-recaptcha-input/OWNERS.yaml, extensions/amp-reddit/OWNERS.yaml, extensions/amp-springboard-player/OWNERS.yaml, extensions/amp-user-notification/OWNERS.yaml, extensions/amp-viqeo-player/OWNERS.yaml, extensions/amp-wistia-player/OWNERS.yaml
- Adds an OWNERS file to `amp-connatix-player`, `amp-delight-player`, `amp-drilldown` and `amp-wistia-player`
- Adds `wg-ui-and-a11y` as owner to multiple UI-related components that have a single owner
=> ♻️`wg-ui-and-a11y` to own externally contributed UI related components

yarn.lock
It's possible that the current `yarn` lockfile is missing some integrity checks, resulting in the error described in https://github.com/yarnpkg/yarn/issues/7584.
This PR deletes `yarn.lock` and regenerates it by re-installing all packages by running `yarn`.
=> 🏗 Regenerate `yarn.lock`

extensions/amp-youtube/validator-amp-youtube.protoascii, validator/engine/validator_test.js, validator/testdata/amp4ads_feature_tests/extensions.html, validator/testdata/amp4ads_feature_tests/extensions.out
I2I sent in March, deprecation notice sent in July
https://github.com/ampproject/amphtml/issues/21340
=> Disallow amp-youtube in amp4ads

build-system/tasks/bundle-size.js
Bundle-size bot has been fixed to not expect the `gzippedBundleSize` field
=> Revert "Revert "Stop reporting gzipped compressed size in the bundle-size task (#24418)" (#24882)"

extensions/amp-story/1.0/amp-story-draggable-drawer-header.css
Expanded the tap target size for the page attachment close button by switching the margin into padding and setting the background-origin to `content-box` to keep the X image in the center.
Resolves #24808
=> ♿Expand tap target size for page attachment close button

.github/PULL_REQUEST_TEMPLATE.md
The PR template instructs developers to include emoji in their PR descriptions. Copying the emoji works, but copying the emoji code does not.
This PR removes the emoji code from the template so people don't copy it by mistake.
=> 📖 Remove confusing emoji codes from PR template

extensions/amp-orientation-observer/0.1/amp-orientation-observer.js
Refactors repetitive methods and fixes a minor bug
=> ♻️Minor refactor for `amp-orientation-observer`

extensions/amp-ad/0.1/amp-ad-ui.js, src/service/resources-impl.js, test/unit/test-resources.js
Closes #23926, #24446.
The final measurements show that user activation reduces false negatives by ~5%. It has virtually no impact on false positives which appear to be very low at this time.
=> Remove resize logs and enable activation for resize decisions

extensions/amp-accordion/validator-amp-accordion.protoascii, extensions/amp-anim/validator-amp-anim.protoascii, extensions/amp-bind/validator-amp-bind.protoascii, extensions/amp-carousel/validator-amp-carousel.protoascii, extensions/amp-fit-text/validator-amp-fit-text.protoascii, extensions/amp-form/validator-amp-form.protoascii, extensions/amp-list/validator-amp-list.protoascii, extensions/amp-mustache/validator-amp-mustache.protoascii, extensions/amp-selector/validator-amp-selector.protoascii, extensions/amp-sidebar/validator-amp-sidebar.protoascii, extensions/amp-timeago/validator-amp-timeago.protoascii, validator/engine/validator_test.js, validator/testdata/amp4email_feature_tests/no_latest_extensions.html, validator/testdata/amp4email_feature_tests/no_latest_extensions.out
Fixes #24618.
/to @honeybadgerdontcare
=> AMP4Email: Disallow "latest" extension scripts

build-system/tasks/lint.js
This PR makes it so that `gulp lint`, `gulp lint --local_changes`, and `gulp lint --files=<glob>` are all capable of linting `OWNERS` files.
**Example usage:**
```
$ gulp lint --files=build-system/**/OWNERS
[16:47:00] Using gulpfile ~/src/amphtml/gulpfile.js
[16:47:00] Starting 'lint'...
[16:47:00] All packages in node_modules are up to date.
[16:47:00] INFO: Running lint on the following files:
[16:47:00] build-system/global-configs/OWNERS
[16:47:00] build-system/OWNERS
[16:47:01] SUCCESS: No linter warnings or errors.
[16:47:01] Finished 'lint' after 816 ms
```
```
$ gulp lint --local_changes
[16:47:45] Using gulpfile ~/src/amphtml/gulpfile.js
[16:47:45] Starting 'lint'...
[16:47:45] All packages in node_modules are up to date.
[16:47:45] INFO: Running lint on the following files: …
```
=> 🏗 Lint `OWNERS` files with `gulp lint`

build-system/tasks/lint.js
Addresses https://github.com/ampproject/amphtml/pull/24943#pullrequestreview-298421382
Follow up to #24943
=> 🏗 Use `config.lintGlobs` instead of a hard-coded list of globs

extensions/amp-subscriptions/0.1/crypto-handler.js, extensions/amp-subscriptions/0.1/test/test-crypto-handler.js
Changes the attribute name in SwG encrypted scripts from "encrypted" to "ciphertext" to avoid attribute duplication between the script tag and the surrounding section tag.
=> 🏗 Change Attribute Name in SwG Encrypted Scripts

build-system/babel-plugins/OWNERS, build-system/common/OWNERS, build-system/compile/OWNERS, build-system/eslint-rules/OWNERS, build-system/externs/OWNERS, build-system/pr-check/OWNERS, build-system/runner/OWNERS, build-system/sauce_connect/OWNERS, build-system/server/OWNERS, build-system/server/app-index/OWNERS, build-system/tasks/OWNERS, build-system/tasks/e2e/OWNERS, build-system/tasks/runtime-test/OWNERS, build-system/tasks/visual-diff/OWNERS, build-system/test-configs/OWNERS
This PR adds `OWNERS` files across `build-system/`.
/cc @ampproject/wg-infra @ampproject/wg-runtime @ampproject/wg-performance since there's some common code that everyone must be able to edit.
=> 🏗 Add `OWNERS` files for all `build-system/` sub-directories

build-system/tasks/bundle-size.js
Related to: https://github.com/ampproject/amp-github-apps/issues/271
=> 🏗 Switch bundle-size store function to the JSON API endpoint

build-system/tasks/runtime-test/helpers.js
Closes #24957:
Karma was reporting an error when zero tests were detected. Since this is a recoverable state, we are now merely logging the error.
=> ⏪Remove Error Reporting From karmaBrowserComplete_ When Zero Tests Found

build-system/tasks/build.js, build-system/tasks/serve.js
It has been a month since the default `gulp` behavior was changed to lazy build JS files and extensions (#24386). This PR removes the stopgap `--eager_build` flag that was added at the time.
Fixes #24423
=> 🏗 Remove `--eager_build` flag from `gulp`

extensions/amp-story/amp-story.md
- Changes the format of the amp-story attributes section to a table
- Updates the internal anchors referring to the attributes
=> 📖 Formats amp-story attributes section as a table.

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
- 🏗 Adds hash param for testing optimized Boq JS.
- Update payjs to be consist with the origin master.
- 🐜 Fixes an iOS issue where Dialog iframe wasn't being removed.
=> ✨ SWG release 0.1.22.74

.github/OWNERS, .github/PULL_REQUEST_TEMPLATE.md
This PR hides the PR template boilerplate even if it is inadvertently included in a PR description. Note that the instructions will still be visible when developers are writing their PR descriptions, because the github editor displays raw markup.
@mrjoro @CrystalOnScript WDYT?
**For example:**
=> 📖 Make PR template text invisible even when it is inadvertently included in a PR description

.eslintignore, .prettierrc, OWNERS, css/OWNERS, examples/OWNERS, extensions/OWNERS, tools/OWNERS, validator/OWNERS
- Remove default settings and unnecessary trailing comma from `.prettierrc`
- Don't ignore `OWNERS` files in `.eslintignore`
- Auto-fix a few `OWNERS` files (to be consistent with others)
- Don't auto-request reviews from contributors who no longer work on AMP full-time
=> 🏗 A few minor `OWNERS` fixes

extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/amp-story-store-service.js, extensions/amp-story/1.0/amp-story.js
Fixing a few things about the story navigation path.
The `updateNavigationPath` method used to decide of the target page: you'd call `switchTo` with a page ID, but it would be overridden in some cases. This was causing different bugs with progress bar and history, as the `targetPage` was overridden but not the `targetPageId`.
Instead, the navigation path is now stored and globally accessible. Pages, when getting the previous page id, look up in the navigation path. This way `switchTo` actually navigates to the page you passed as a parameter, making its behavior easier to predict and removing the previously mentioned bugs.
`updateNavigationPath` no longer decides of the target page, but only updates the store + history.
=> Story branching navigation path fixes.

extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/page-advancement.js
@jackbsteinberg investigated on the `page-advancement.js` code and found different architecture mistakes we made over the several refactoring.
`amp-story` can only get a `manual-advancement`, and `amp-story-page` cannot
`amp-story-page` can only get either a `TimeBased` or `MediaBased` advancement
When we used to listen for click events at the page level, we could have both a Manual + xBased advancement, but that is no longer possible. Each element can only get one type of advancement, making the `MultipleAdvancement` level of abstraction no longer needed.
This should be a no-op as no code path has been leading to `MultipleAdvancement` for a few months.
While a deeper refactoring would be super desirable, it'd require a ton more work (advancement callbacks emitting browser events back and …
=> Remove story multiple advancement config.

extensions/amp-story/1.0/amp-story-share.css, extensions/amp-story/1.0/amp-story-share.js
Removing this checkbox for desktop/mobile parity, as native sharing where we don't control the shared URL (unless we hack the `location.href`?) is now supported on both iOS and Android.
I'm open to discussing keeping it, but this would require UX work to get the wording + design right.
=> Remove the branching share page checkbox.

.eslintignore, .eslintrc, .prettierrc, build-system/tasks/lint.js, build-system/test-configs/config.js
#24938, #24943, and #24946 made it so that the formatting of `OWNERS` files was checked using `eslint` (in particular, `eslint-plugin-prettier`).
It turns out that `eslint` doesn't really work well for json5 code. For example, [this](https://github.com/ampproject/amphtml/pull/24988/files) simple change [broke](https://travis-ci.org/ampproject/amphtml/jobs/595662724#L384) the `babel-eslint` parser.
This PR rolls back the parts of #24938, #24943, and #24946 that had to do with linting `OWNERS` files, while leaving in place other improvements that were introduced (like [de-duplication](https://github.com/ampproject/amphtml/pull/24943#discussion_r332244710) of code).
With this, `OWNERS` files will no longer be checked by `eslint` or `prettier`. In future, a new workflow will be introduced to …
=> 🏗 Don't use `eslint` to check `OWNERS` files

OWNERS
Defines the reviewer team for the repository. Will cause the owners bot to enforce that every PR must have approval from at least one member of the `ampproject/reviewers-amphtml` team.
Closes https://github.com/ampproject/amp-github-apps/issues/522
=> Add reviewers team to root OWNERS file

extensions/amp-bind/0.1/bind-expression.js, extensions/amp-bind/0.1/test/test-bind-expression.js, extensions/amp-bind/amp-bind.md
Resolves #24659
Only string attributes are supported (Regex not supported)
=> ✨amp-bind: Allow String.replace()

extensions/amp-story/1.0/media-pool.js, extensions/amp-story/1.0/media-tasks.js, extensions/amp-story/1.0/sources.js, extensions/amp-story/1.0/test/test-media-tasks.js
Cached videos don't fallback to the origin video when configured as attributes of `<amp-video>`.
The media pool will remove the `src` attribute before the `amp-video.layoutCallback` runs, preventing it from propagating the cached src as a source of the new `<video>` element.
Solution is to transform the `src` attribute as a `HTMLSourceElement`, that will later be picked up by `amp-video.layoutCallback`.
This fixes stories like [this one](https://interactive-aljazeera-com.cdn.ampproject.org/v/s/interactive.aljazeera.com/aje/2018/nepal-great-plunder/index.html?amp_js_v=0.1&usqp=mq331AQCKAE%3D) (see page 2).
=> Media Pool: generate HTMLSourceElement from the src attribute.

extensions/amp-carousel/0.2/amp-carousel.js
Prior to this change, the carousel arrows would never hide for
amp-carousel 0.2, regardless of the `controls` attribute.
Fixes #25004
=> 🐛Hide type="carousel" arrows after swiping to a new slide.

.lando.yml
This is a follow-up on #23213 which adds a Lando environment for AMP core development. When attempting to [build the validator](https://github.com/ampproject/amphtml/tree/master/validator#usage), I found that the required dependencies were missing. This PR adds them.
=> 🏗 Lando: Install dependencies needed for building validator

src/config.js
Gmail mobile clients use *.gmail.com as the base URL for the WebView
that embeds the AMP HTML iframe.
/to @choumx
=> 🐛Consider *.gmail.com trusted viewer domains

build-system/tasks/bundle-size.js
Releated to https://github.com/ampproject/amp-github-apps/issues/271
=> 🏗 Report and store the bundle size of alternate runtime and extension files

extensions/amp-analytics/0.1/test/vendor-requests.json, extensions/amp-analytics/0.1/vendors/infonline.js
- Add new request type ```event``` to allow event based analytics requests
- Add ```type``` to query parameters for pageview and event requests to allow a different processing
Resolves #23276
=> ✨ Update INFOnline analytics vendor configuration

css/ampdoc.css
Added a rule to ignore amp-active divs on amp-stories to prevent the outdated loader from displaying.
Resolves #24609
=> 🐛Add CSS rule to hide amp-loaders from stories

extensions/amp-sidebar/0.1/amp-sidebar.js, extensions/amp-sidebar/0.1/test/test-amp-sidebar.js, extensions/amp-sidebar/1.0/amp-sidebar.js, extensions/amp-sidebar/1.0/test/test-amp-sidebar.js, src/service/ampdoc-impl.js, test/unit/test-ampdoc.js
This fixes a bug where the compiled (renamed) property for `ampDoc_`
could conflict with a form field name. Rather than blacklist `form`,
whitelist `amp-` elements in case anything else has this behavior (like
`window` and Element `id`s).
Fixes #24995
=> 🐛Restrict checking cached ampDoc reference to AMP elements.

extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/page-advancement.js
Fixes a bug where the progress bar would work improperly with a mismatch between the id supplied in `auto-advance-after` and the id of the media elements. Additionally, refactors the check for advancement types for updating the progress on non-auto-advanced pages.
Resolves #24940
=> 🐛Fix progress bar bug with more comprehensive advancement checks

spec/amp-var-substitutions.md
&lt;amp-pixel&gt; was missing &gt; on its opening tag.
=> 📖Fix typo in AMP Variable Substitutions documentation

build-system/common/utils.js, build-system/tasks/bundle-size.js, build-system/tasks/check-owners.js, build-system/tasks/dev-dashboard-tests.js, build-system/tasks/dist.js, build-system/tasks/lint.js, build-system/tasks/prettify.js, build-system/tasks/runtime-test/helpers-unit.js, build-system/tasks/serve.js, build-system/tasks/vendor-configs.js, package.json, yarn.lock
This PR replaces `globs-to-files` with `globby` across `build-system/` (and removes the now unnecessary step of converting the resulting filenames to relative paths).
- **[`globs-to-files`](https://www.npmjs.com/package/globs-to-files):**
- ~1000 weekly downloads
- Hasn't been updated in 4 years
- Cannot handle negative glob patterns
- **[`globby`](https://www.npmjs.com/package/globby):**
- ~16 million weekly downloads
- Actively maintained
- Significantly faster than other packages
- Can handle negative glob patterns
Addresses https://github.com/ampproject/amphtml/pull/25093#discussion_r336072228
=> 🏗 Replace `globs-to-files` with `globby`

extensions/amp-subscriptions-google/0.1/test-e2e/test-amp-subscriptions-google.js
This PR deflakes the SwG E2E test by waiting for the SwG button to render before triggering a click.
=> ✅ Deflakes SwG E2E Test

tools/OWNERS
Fixes some incorrect working group team names introduced in #24971 (see https://github.com/ampproject/amphtml/pull/24971#issuecomment-542864217)
=> 🏗 Fix team names in OWNERS of `tools`

src/service/extension-location.js, test/unit/test-extension-location.js
we no longer deploy single pass extensions inside an "sp" directory under the "rtv" directory. This was previously needed as the single pass deployment did not have unique versions and were tied to the currently deployed "stable" AMP version.
Now single pass experiment js binaries have a unique version were the prefix is in the 4x range and the `--custom_version_mark` flag (`gulp dist` option) is used to have a unique ID across the single pass arms (control/singlepass/esm)
=> remove sp path from extension location

src/OWNERS, src/service/OWNERS, src/service/video/OWNERS
Realized that video service files are really touched when creating 3p player contributions, so they can be set to the broader `ampproject/wg-ui-and-a11y` group (rather than the specific set from #24908).
Added missing ownership for other video/media related files in `src`.
=> OWNERS set for video files in src

ads/google/ima-player-data.js, extensions/amp-ima-video/0.1/amp-ima-video.js, src/service/video-manager-impl.js
Fixes the race condition that causes the ima-video player to freeze with slow network connection. Also added event trigger to calculate percentage played.
Closes #23356
=> 🐛Fixes ima-video race condition and percentage played 

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
🏗 Adds eslintrc file for build-system directory (#691)
🚮 Removes messageDeprecated fn from tests (#690)
🚮 Removes extra onMessageDeprecated mocks from tests (#688)
🚮 Removes onMessage code from AnalyticsService (#24906
=> SwG release 0.1.22.76

.github/OWNERS, .gitignore, .prettierrc, .vscode/OWNERS, .vscode/settings.json, build-system/common/utils.js, build-system/tasks/prettify.js, build-system/test-configs/config.js, contributing/getting-started-e2e.md
We now run two checks on Travis to ensure code correctness / style / formatting:
- `gulp lint` uses `eslint` to check JS files
- `gulp prettify` uses `prettier` to check non-JS files
Travis builds often fail due to errors from these checks, which can be annoying and waste VM resources.
- Add VS Code support for auto-formatting JS and non-JS files on save using `amphtml`'s preferred rules
- Add a project specific `.vscode/settings.json` settings file
- Document the preferred workflow to enable auto-fix-on-save behavior
- Include files in dot directories during `lint` / `prettify`
**For example, syntax highlighting + auto-correction for an `OWNERS` file:**
=> 🏗 Add VS Code auto-formatting support for JS and non-JS files

examples/visual-tests/amp-story/amp-story-sidebar.html, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story.js
Updating Pet's work from #20944
cc @bramanudom 
#20083
=> Story branching support for sidebar links.

build-system/tasks/e2e/index.js
Watch mode wasn't working because the node require cache wasn't properly being cleared, blocking Mocha from knowing which tests to rerun.
Now you can run `gulp e2e --nobuild --watch --files="foo.js"` like before.
=> 🏗 Fix watch mode on e2e tests

extensions/amp-story/1.0/amp-story-page.js
fixes #25118
When we updated the `getPreviousPageId()` method to extract the previous page id from the navigation path, we forgot to consider the case when the `AmpStoryPage` calling it is not necessarily the last page. e.g. 
https://github.com/ampproject/amphtml/blob/b6c4242ace9a3d32f82550a378593527c849a460/extensions/amp-story/1.0/amp-story.js#L1538-L1547
Since the navigation path hasn't changed between the two calls of `getPreviousPageId()`, `targetPage.getPreviousPageId()` and `minusOnePage.getPreviousPageId()` return the same id.
This PR ensures that we extract the previous page id given the current page id.
=> 🐛 fix getPreviousPageId

extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
It does not seem like this error should be causing any problems (since the error will just occur in the touch handler for the carousel, which has been nulled out due to the lightbox closing), but adding a check here to avoid logging errors.
I have not been able to reproduce the original error message through testing, but it seems like this change should avoid it.
Closes #22533
=> Avoid swipe to dismiss errors being logged.

build-system/tasks/prettify.js, package.json, yarn.lock
- No longer invokes `node_modules/.bin/prettier` once per file
- Uses the `gulp-prettier` package to stream all files
- Continues to print all formatting errors after execution
**Time to check / fix ~300 files:**
- Before: [~1m 30s](https://travis-ci.org/ampproject/amphtml/jobs/599798058#L334-L338)
- After: [~5s](https://travis-ci.org/ampproject/amphtml/jobs/599835404#L386-L390)
=> 🏗🚀 Significantly speed up `gulp prettify`

test/fixtures/e2e/amp-subscriptions-google/swg.amp.html
The test fixture had `<header>` instead of `<head>` this meant that the code designed to prevent extension race conditions was failing because the scripts were not found in `<head>` resulting in a hard to track test flake.
=> 🐛✅  <header> -> <head> to fix test flake

build-system/tasks/firebase.js, build-system/tasks/helpers.js, contributing/TESTING.md
Added a `fortesting` option to `gulp firebase` to enable testing ads on custom domains. 
The following are outdated descriptions of this PR. 
~~This PR does the following:~~
~~1. Re-adds `integration.js` and `f.js` to the list of files that we prepend `AMP_CONFIG` to.~~
~~2. Adds code in `firebase.js` to add `firebase` to the list of allowed 3rd party urls and 3rd party frame regexes so that ads can work on firebase.~~
Filed: 
- #25104 to @estherkim for fixing ads testing in PR deploy bot
- #25108 to @lannka for integration.js refactoring and any work to make sure that deployed demos still work with ads.
~~I wanted to make testing `amp-ad` work for firebase deployments. They're currently failing here: 
https://github.com/ampproject/amphtml/blob/3e6457ff825a90e76f14869197525298b67856df/3p/i …
=> allow firebase for 3p frames

build-system/tasks/prettify.js
=> 🏗 Fix `gulp prettify` when there's nothing to check

contributing/OWNERS
This gives more people who have some familiarity with our contributor documentation OWNERS powers.
This still makes me the default assignee for when people don't know who should review their PR.
/cc @cathyxz @ampproject/wg-infra @ampproject/wg-outreach
=> Adds some more people to collaboration OWNERS 

validator/nodejs/package.json
@rsimha 
In #15602 `check_package_manager.js` was added to [validator/nodejs/packages.json](https://github.com/ampproject/amphtml/blob/master/validator/nodejs/package.json). When publishing the npm module (`npm publish --access public`) we ran into an issue that this file wasn't included and it couldn't be installed (see below for error). Removing the script allowed us to publish. However I'm unsure if that is the final outcome desired given the PR that introduced it. @rsimha do you know if this file is necessary or only useful for `yarn` incantations and not `npm`?
```
user@honeybadgerdontcare:~/github/amphtml/validator$ npm install amphtml-validator@1.0.24
> amphtml-validator@1.0.24 preinstall /github/amphtml/validator/node_modules/amphtml-validator
> node …
```
=> remove preinstall script for node.js

build-system/compile/compile.js, build-system/compile/shorten-license.js, build-system/compile/sources.js, build-system/global-configs/experiments-config.json, build-system/tasks/presubmit-checks.js, build-system/tasks/update-packages.js, package.json, src/friendly-iframe-embed.js, src/polyfills.js, src/polyfills/custom-elements.js, src/service/custom-element-registry.js, test/unit/test-custom-element-registry.js, yarn.lock
There don't seem to be any errors. Let's launch!
Note, we're still always polyfilling. But this gets us one step closer to using native Custom Elements v1 when supported (either via ES6 classes, or a minimal wrapper polyfill instead of a full polyfill).
=> ✨ Launch Custom Elements v1 Polyfill

build-system/server/lazy-build.js, build-system/tasks/extension-helpers.js, build-system/tasks/helpers.js, build-system/tasks/serve.js
The default `gulp` task pre-builds the core runtime, and lazy builds all other JS files and extensions. This results in 404 errors for files that are sometimes loaded by the core runtime without a separate server request (#25024, #24226).
- Pre-builds `ww.js` during default `gulp` startup
- Pre-builds `amp-loader` and `amp-auto-lightbox` during default `gulp` startup
- Waits for pre-build tasks to complete before ending default `gulp` task
- Fixes logging to indicate which extensions are being pre-built
- Server startup still happens before pre-build tasks are executed
Fixes #25024
Fixes #24226
=> 🏗 Pre-build JS files and extensions loaded by core runtime during `gulp` startup

extensions/amp-sidebar/0.1/amp-sidebar.js, extensions/amp-sidebar/0.1/test/test-amp-sidebar.js, extensions/amp-sidebar/1.0/amp-sidebar.js, extensions/amp-sidebar/1.0/test/test-amp-sidebar.js
Partial for #24894. 
Ensure that the same trust level open/close/toggle action is called with is passed to the resulting open/close event to prevent trust escalation. Similar to #24425.
/to @leafsy /cc @sparhami
=> amp-sidebar: Propagate trust from action->event

extensions/amp-accordion/0.1/amp-accordion.js, extensions/amp-accordion/0.1/test/test-amp-accordion.js
Partial for #24894.
Ensure that the same trust level expand/collapse/toggle action is called with is passed to the resulting expand/collapse event to prevent trust escalation. Similar to #24425.
/to @cathyxz
=> amp-accordion: Propagate trust from action->event

src/service/navigation.js, test/unit/test-navigation.js
Mostly readability improvements, plus an important fix to make #19037 actually work.
=> Navigation: Fix IE a11y patch & clean up

validator/nodejs/package.json
Removed references to deleted amp.validator.categorizeError.
=> Publish amphtml-validator version 1.0.27

extensions/amp-ad-custom/amp-ad-custom.md
✨ Updated amp-smartlinks extension to pass link_source to Narrativ's Linkmate API endpoint
=> ✨amp-smartlinks: Adding new field to payload for API Endpoint

.gitignore, build-system/common/exec.js, build-system/tasks/visual-diff/helpers.js, build-system/tasks/visual-diff/index.js, build-system/tasks/visual-diff/package.json, build-system/tasks/visual-diff/percy-assets-loader.js, build-system/tasks/visual-diff/yarn.lock
Reverts ampproject/amphtml#25176
`gulp visual-diff --nobuild --empty` throws an error. Example here: https://travis-ci.org/ampproject/amphtml/jobs/601550094#L351-L361
=> Revert "🏗 Update @percy/percy-puppeteer to v1.x"

validator/nodejs/package.json
This is so we can release the node dependency change in 7316d7c3.
I'll save downstream changes to dependents for subsequent PRs.
=> Bump validator npm to 1.0.28.

.github/ISSUE_TEMPLATE/intent-to-implement--i2i-.md
Launch tracker can be found here: bit.ly/amp-launch-tracker
Open question:
Should this be linked to in the I2S as well (I think so)?
=> Update I2I to include Launch tracker

build-system/tasks/check-links.js
This might not be necessary if the ignore-by-backtick strategy works.
@rsimha Unsure how it would work with actual link syntax:
```md
[${name} rules](https://github.com/ampproject/amphtml/blob/master/extensions/${name}/validator-${name}.protoascii) 
```
Also some modernizing and cleanup.
(Offshoot of #25164)
=> 🏗 Ignore markdown templates in link checker by convention

ads/google/OWNERS, extensions/amp-a4a/OWNERS, extensions/amp-ad-network-adsense-impl/OWNERS, extensions/amp-ad-network-adzerk-impl/OWNERS, extensions/amp-ad-network-doubleclick-impl/OWNERS, extensions/amp-ad-network-fake-impl/OWNERS, extensions/amp-ad-network-gmossp-impl/OWNERS, extensions/amp-ad-network-triplelift-impl/OWNERS
During consolidation of GitHub teams (https://github.com/ampproject/meta/issues/43), `ampproject/a4a` was removed even though it is still listed in many OWNERS files. This PR updates references to the team, replacing them with `ampproject/wg-ads` or removing them where redundant.
=> 🐛 Replace all OWNERS file references to a4a team with wg-ads

build-system/tasks/check-links.js
Otherwise deleted or ignored files get printed out as successful. Oops.
=> 🏗 Preemptively skip empty link check results

extensions/amp-lightbox/0.1/amp-lightbox.js
Partial for #24894.
Ensure that the same trust level open/close/toggle action is called with is passed to the resulting open/close event to prevent trust escalation. Similar to #24425.
/to @alanorozco
=> amp-lightbox: Propagate trust from action->event

extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, src/ampdoc-fie.js, src/friendly-iframe-embed.js, src/service.js, src/service/ampdoc-impl.js, test/unit/test-ampdoc.js, test/unit/test-friendly-iframe-embed.js, test/unit/test-service.js
=> Redefine ampdoc-fie experiment as a branched experiment

build-system/common/utils.js, build-system/pr-check/checks.js, build-system/tasks/check-links.js, build-system/tasks/pr-check.js, build-system/tasks/prettify.js, build-system/test-configs/config.js, contributing/TESTING.md
This PR builds on #25226 and refactors / significantly speeds up `gulp check-links`
- Moves common functionality like `getFilesToCheck()` into `build-system/common/utils.js`
- Introduces the `--files` and `--local_changes` flags (`--files` now supports lists of globs)
- Makes it an error to run `gulp check-links` on *all* files in the repo (there are multiple thousands of links, so we only run the link checker on files changed by a PR)
- Uses the `ignorePatterns` option of [`markdown-link-check`](https://www.npmjs.com/package/markdown-link-check#markdownlinkcheckmarkdown-opts-callback) and deletes `filterAllowedLinks()` (addresses https://github.com/ampproject/amphtml/pull/25226#discussion_r338314998)
- Caches `gitDiffAddedNameOnlyMaster()` in `filesIntroducedByPr` …
=> 🏗🚀 Refactor and significantly speed up `gulp check-links`

extensions/amp-selector/0.1/amp-selector.js, extensions/amp-selector/0.1/test/test-amp-selector.js
Fixes #24425 and closes #24443.
Note: do not submit until deprecation notice period is over in mid-October.
/to @sparhami
=> amp-selector: "select" event should have variable trust

extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
If the returned creative has a size that matches one that was requested, we don't need to adjust the slot in any way.
=> Carve out flex slot expansion for multi-size responses.

src/polyfills/custom-elements.js
When we transpile `super` in Custom Element subclasses, we change it to `superClass.call(this)` (where `superClass` is `HTMLElementPolyfill`). That `.call` value is inherited from `Function.prototype`. 
But, IE11's native `HTMLElement` hierarchy doesn't extend from `Function`!  And because `HTMLElementPolyfill` extends from `HTMLElement`, it doesn't have a `.call`! So we need to manually install it.
=> 🐛 Fix Custom Element instance creation in IE11

extensions/amp-fit-text/validator-amp-fit-text.protoascii, validator/testdata/amp4email_feature_tests/no_latest_extensions.out
Follow up to #24854 
Restrict `amp-fit-text` AMP4EMAIL tagspec to only `html_format: AMP4EMAIL`.
=> Update amp-fit-text AMP4EMAIL tagspec

build-system/compile/check-for-unknown-deps.js
Addresses https://github.com/ampproject/amphtml/pull/24284#discussion_r338828208
**Before:**
**After:**
=> 🏗 Improve error logging in `build-system/compile/check-for-unknown-deps.js`

extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
If a parent container of the ad slot uses `text-align: center`, then there's no reason to apply flexible ad slot centering logic. This change will ensure we exit early, but still apply the z-index change.
=> Ensure that flexible ad centering isn't applied to slots centered via text-align.

src/service/extensions-impl.js, test/unit/test-extensions.js
add `crossorigin=anonymous` to auto inserted script so that error information from those extensions can be reported. 
related to #7353
=> Add crossorigin=anonymous to inserted script

extensions/amp-form/0.1/amp-form.js
SSR responses get passed fully to the `submit-success` and `submit-error` events on amp-form. These often include extra fields such as the HTML to render in the template. This change only exposes to the events the expected values of the amp-form response, such as data inserted into the form fields or relevant errors. b/138778080 cc/ @GoTcWang
=> 🐛Expose amp-form response from SSR in `submit-success` and `submit-error` events.

extensions/amp-ad/amp-ad.md
Update `amp-ad / amp-embed` doc file to add Insticator to the list of supported embed types.
@CrystalOnScript 
cc @triso07
=> 📖 Add Insticator to the list of supported embed types.

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, extensions/amp-list/0.1/test-e2e/test-load-more-auto.js, extensions/amp-list/0.1/test-e2e/test-load-more-manual.js, test/manual/amp-list/infinite-scroll-2.amp.html, test/manual/amp-list/infinite-scroll-fail.amp.html, tools/experiments/experiments-config.js
Cleans up unused experiments `amp-list-load-more` and `amp-list-viewport-resize`. Both experiments have been launched and are no longer referenced in our codebase.
=> Remove unused experiments from config and experiments

validator/nodejs/package.json
This PR makes it so that `amphtml-validator` can be used with `node` v8. This will need to be followed up with a new `1.0.29` release. 
Partial mitigation for #25209
Related to https://github.com/ampproject/amphtml/pull/25161#discussion_r337182956
/cc @ampproject/wg-caching
=> 🏗 Allow `amphtml-validator` to be used with `node` v8

extensions/amp-social-share/0.1/amp-social-share.js, extensions/amp-social-share/0.1/test/test-amp-social-share.js
Closes #25039 
Fixes the email and sms social sharing buttons on Chrome iOS to have the same behavior as iOS Safari.
=> 🐛Fixed social sharing buttons on iOS Webkit

ads/mgid.js
Mgid widget wouldn't work if first or second char of data.publisher is not alphanumeric.
=> 🐛Fix subdomain handling in mgid widgets

extensions/amp-nested-menu/0.1/amp-nested-menu.css, extensions/amp-nested-menu/0.1/amp-nested-menu.js, extensions/amp-nested-menu/0.1/test/test-amp-nested-menu.js, test/manual/amp-sidebar/amp-nested-menu.amp.html
Resolves: #25157 
Resolves: #24665 
Implement the following changes to `<amp-nested-menu>`:
- Add an optional "side" attribute that determines which side submenus should open from ("right" by default, "left" for RTL documents)
- Support all arrow keys:
- Left arrow (or right if side=left) to go back to parent menu;
- Right arrow (or left if side=right) to open submenu if submenu open button has focus;
- Up/Down arrow to move focus within menu (only works for `<li>` in the same list);
- Add a public `reset()` method that sidebar can call to reset menus on close;
- Change event listeners to use event delegation;
- Add tests for the new functionalities.
Demo: https://amp-nested-menu.firebaseapp.com/
=> Update <amp-nested-menu> event listeners and improve RTL + arrow key support

build-system/externs/amp.extern.js, build-system/test-configs/conformance-config.textproto, extensions/amp-viewer-integration/0.1/examples/amp-viewer-host.js, extensions/amp-viewer-integration/0.1/messaging/messaging.d.ts, extensions/amp-viewer-integration/0.1/messaging/messaging.js, extensions/amp-viewer-integration/0.1/messaging/package.json, extensions/amp-viewer-integration/0.1/test/integration/test-amp-viewer-integration.js, extensions/amp-viewer-integration/0.1/test/integration/test-messaging-handshake.js, test/fixtures/served/ampdoc-with-messaging.html
*   Removes dependencies on `getData` and `parseJson` to make it easier to publish on NPM.
*   Adds support for opaque origins (`postMessage` must use `*` as `targetOrigin` when origin is `"null"`).
*   Adds `initMessaging` helper function ([most of this logic is from here](https://github.com/ampproject/amp-viewer/blob/cbf0ae384cbd1b31a4b953ddaecbf1eaf3b9ce61/mobile-web/src/viewer-messaging.js#L100-L119)).
*   Changes uses of `==` to `===`.
I'll make a second PR to update version in package.json and publish when this is merged.
=> Add handshake logic and opaque origin support to amp-viewer-messaging

validator/testdata/amp4ads_feature_tests/crossorigin_anonymous_script.html, validator/testdata/amp4ads_feature_tests/crossorigin_anonymous_script.out, validator/testdata/feature_tests/crossorigin_anonymous_script.html, validator/testdata/feature_tests/crossorigin_anonymous_script.out, validator/validator-main.protoascii
This is a necessary step in order to fix error reporting for errors generated by crossorigin scripts. Making the script `anonymous` signals to the browser that there is no User PII in the script, and will allow the errors to be generated will full stack trace and error message.
Fixes https://github.com/ampproject/amphtml/issues/24731
=> ✨ Allow crossorigin=anonymous on Scripts

src/polyfills/custom-elements.js
When we've already initialized the the custom element registry, it used to drop the list of shadow roots. When a new CE was defined, we would then only query the host `document` (since we dropped all the shadow roots from the array). Obviously, that query selector won't find CEs inside the shadow tree.
So, we need to keep the list of shadow roots, that way we can query inside them when defining new custom elements.
Note, this will mean leaking every shadow permanently. Even if the shadow's host is removed from the document, we'll still have to keep its reference. We could setup a long running interval to find disconnected trees, but it wouldn't be able to tell the difference between a temporarily disconnected shadow and a destroyed shadow.
Fixes …
=> 🐛 Upgrade shadow root contents when defining new CEs

src/sanitation.js
This is for consistency with amp-list and amp-form: we don't allow
XHR-firing components to be nested under another XHR-firing template.
/to @choumx
=> Ban amp-state in Mustache template output

ads/google/a4a/test/test-utils.js, ads/google/a4a/utils.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, src/custom-element.js
Using globals can be risky and may break assumptions in shadow mode. 
Fixes #25007
=> 🐛A4A: Change a few window refs to ampdoc

extensions/amp-analytics/amp-analytics.md, extensions/amp-analytics/linker-id-forwarding.md
Matt introduced some unfriendly documentation changes in PR #25071 by
denoting some fields as JSON that are not real JSON. Viewing the
markdown makes these fields stand out more than they should. Revert
non-JSON fields to javascript linguist hint for the sake of readability.
=> 📖Cleanup scary red text in analytics docs

build-system/common/utils.js, build-system/pr-check/checks.js, build-system/tasks/check-links.js, build-system/tasks/check-owners.js
The owners syntax check API returns a response `{requestErrors, fileErrors, rules}`. This PR makes the `gulp check-owners` task call that API for each file in `--files` or `--local_changes`, and fails if there are any file errors.
I wasn't certain on where the API URI should live, so I made it a constant for now. Also not familiar with the conventions around logging, so I pattern-matched a bit, but feel free to suggest changes.
Do I need to adjust `checks.js` or something else to actually pass the `--local_changes` flag? 
Closes #24295
Closes https://github.com/ampproject/amp-github-apps/issues/281
=> [owners] Add OWNERS syntax check to Travis gulp task 

src/polyfills/custom-elements.js
It also directly calls into the globally installed error reporting function.
Re: https://github.com/ampproject/amphtml/pull/25289
It seems HTML spec is unlikely to change: https://github.com/whatwg/html/issues/5051
=> 🐛 Change to using setTimeout to avoid muted unhandledrejections

extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/test-amp-list.js
`amp-list` XHR failure currently results in a confusing SSR failure--the error is passed back and read as a response, leading to [an error](https://github.com/ampproject/amphtml/blob/master/extensions/amp-list/0.1/amp-list.js#L620-L624) downstream in the promise chain.
This change adds an explicit check for `response['init']['status']` of non-2xx to reject and render the fallback, as well as adds to the test cases regarding handling SSR response. b/135069789
=> Catch XHR errors in SSR response in amp-list.

extensions/amp-youtube/0.1/amp-youtube.js
https://github.com/ampproject/amphtml/issues/21340
Make sure all validation changes on https://github.com/ampproject/amphtml/pull/24864 are deployed on ampproject.org before merging this.
=> Remove amp-youtube a4a deprecation notice

build-system/eslint-rules/no-duplicate-name-typedef.js
When linting, we sometimes reprocess the same file multiple times. That will obviously trigger the duplicate typedef error.
Now, when we enter a file, we delete all typedef names that it registered.
=> 🏗 Fix duplicate typedefs when linting

src/inabox/inabox-resources.js
`scheduleLayoutOrPreload` is called in `owners-impl`. we should always try to layout remaining elements in this case.
This should fix the percy failure: https://percy.io/ampproject/amphtml/builds/3000829
=> Fix a bug that amp-carousel is not laying out children elements for inabox-lite.

build-system/compile/compile.js
Travis recently upgraded us to premium VMs on a trial basis. This PR experiments with increased concurrency for multi-pass `gulp dist` on Travis. Let's see what performance increase we get as a result of this.
=> 🏗🚀 Enable concurrency for multi-pass `gulp dist` on Travis

test/unit/test-resource.js
Fixes #25411
- Replaced all `amp-ad` elements by `amp-fake-element` in the test. Because using `amp-ad` element was causing unnecessary dependencies on other tests, which failed 60+ tests silently.
- Skipped 2 tests that were likely silently failing before.
=> Fix test-resource.js. It is failing when ran alone.

extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story.js
`pauseCallback` and `resumeCallback` don't really work the way Stories expect them to. They will get triggered as the viewer `visibilityState` changes, but not when the browser tab visibility changes.
However, Stories should be paused both on `visibilityState` and browser tab changes.
`amp-story-page.resume/pauseCallback` were triggered by the AMP runtime on `visibilityState` change, which wasn't expected by our code, causing various bugs as the one reported. We've never noticed the issue because the code happened to fail in an OK way, and we don't play so much with viewers locally.
The proposed fix is to rely on `ampdoc.onVisibilityChanged()` that is triggered in both cases (viewer + browser tab), and to stop using `pause/resumeCallback()`, as discussed with @jridgewell. …
=> Override pause/resumeCallback for Stories needs.

extensions/amp-carousel/0.1/scrollable-carousel.js, extensions/amp-carousel/0.1/slidescroll.js
Left and Right arrow keys in `amp-carousel` 0.1 currently interact with the component and the surrounding email client in the context of an AMP Email. These events should be consumed by the component. Though this change is motivated by an email use case, it is also useful generally.
b/129001654 cc/ @zhangsu
=> 🐛Escape left and right arrow keys in amp-carousel 0.1

extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/media-performance-metrics-service.js, extensions/amp-story/1.0/test/test-amp-story-page.js, extensions/amp-story/1.0/test/test-media-performance-metrics-service.js
When autoplay is blocked by the browser, don't flush the video performance metrics.
Instead, wait until the user clicks on the "play" button to start measuring, bless, and play the videos.
We could check if the autoplay is supported before even trying to measure the video performance, but this operation is rather slow as under the hood it creates a video and tries to play it. So instead we optimize for the case where everything plays as expected, and perform the expensive check only upon error.
Fixes #25147
=> Don't send video error metrics if autoplay was denied 

validator/package.json, validator/yarn.lock
Validator tests use `jasmine@3.5.0`, which depends on packages with security vulnerabilities. This PR manually overrides them until such time that `jasmine` pushes an update.
Travis tests will tell us if these updates actually work.
/cc @mrjoro @ampproject/wg-caching
=> 🏗 Manually upgrade transitive validator dependencies with security vulnerabilities

src/service/extensions-impl.js, test/unit/test-extensions.js
Fixes #25436.
Additionally fixes a race condition on the wait->reload sequence. Rare, but manifests itself exactly the same way as described in the #25436.
=> Narrow down script matching to avoid incorrect prefix matches

src/service/extensions-impl.js
Followup on #14998 that introduced extension loading timeout.
Partial for #25415.
=> Increase extension timeout to collect the failure data

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js, extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Update extension to use new setOnPaymentResponse callback instead of setOnSubscribeResponse.
=> Update Swg Amp extension to use new callbacks

src/video-interface.js
Ensures video element is upgraded to customElement before using signals. Tested locally.
Details in the issue.
Fixes #25386
=> Ensure video element is upgraded to customElement before using signals.

extensions/amp-form/0.1/amp-form.js
Reverts ampproject/amphtml#25242
=> Revert "🐛Expose amp-form response from SSR in `submit-success` and `submit-error` events."

src/custom-element.js, test/unit/test-custom-element.js
The loading container is created during `updateLayoutBox` (directly after a measure). It uses `mutateElement` to do it, which invalidates the layoutBox. When Resources detects that the layout box is invalid, it remeasures it, and calls `updateLayoutBox`.
Guess what happens?
We call `mutateElement` again. We invalidate the layout box. Resources measures, calls `updateLayoutBox`. On and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on …
=> 🚀 Break infinite loop with loading container

src/service/resources-impl.js
The quick checks here are meant to skip the more expensive remeasure checks. If any elements scroll, then there's the possibility for there to be new remeasure work. So we must do the full check after nested scrollers scroll.
Fixes https://github.com/ampproject/amphtml/issues/24929#issuecomment-550164064
=> 🐛 Check if any remeasures are necessary when nested scrollers scroll

extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Make tests that need a real ampdoc to use the appropriate configuration in the describes declaration.
=> Fixes ampdoc related test failures.

extensions/amp-video/0.1/amp-video.js, extensions/amp-video/0.1/test/test-amp-video.js
`amp-video` used to load the poster image in prerender (#1657 + #1718).
When introducing prerendering for cached videos (#12193 + #17493), we broke the case for prerendering the poster when the video is not cached.
If the video has cached sources OR a poster image, it should allow prerendering.
It is safe to prerender a video with a poster image but no cached source, as the `amp-video.layoutCallback` will only propagate the cached source until the viewer is visible ([source](https://github.com/ampproject/amphtml/blob/master/extensions/amp-video/0.1/amp-video.js#L310-L326)).
Fixes #25446
=> Prerender amp-video poster image.

examples/fluid.amp.html, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js
Currently, fluid impressions are only fired if the creative expands fully. This seems overly restrictive, as in some cases the creative may load within the viewport with a non-zero size. In these cases, it makes sense to fire a delayed impression ping as well.
=> Fire fluid delayed impression ping if creative has non-zero size.

extensions/amp-base-carousel/0.1/amp-base-carousel.js, extensions/amp-base-carousel/0.1/carousel-events.js, extensions/amp-base-carousel/0.1/carousel.js, extensions/amp-base-carousel/0.1/dimensions.js, extensions/amp-carousel/0.2/amp-carousel.js
The changes are in preparation for amp-inline-gallery, and move some of the code to more closely match #24388.
- Refactor amp-base-carousel to more closely match amp-stream-gallery's
code patterns.
- Track the current offset in the slide as a percentage rather than a
pixel offset, which will restore scroll position more accurately when
resizing.
- Fire events notifying what the current slide is and how much progress
been made for the gallery (e.g. to show indicator dots).
- Use intersection observer for visibility tracking of child slides for
amp-base-carousel.
- Fix a couple of edge cases (`<=` vs `<`).
=> 🐛♻️Refactor, changes to amp-base-carousel for amp-inline-gallery.

extensions/amp-subscriptions/0.1/crypto-handler.js, extensions/amp-subscriptions/0.1/test/test-crypto-handler.js
- Uses AES-GCM instead of AES-CTR in decryption for swg-crypto
- Updates encrypted text in tests to use AES-GCM
=> 🏗 Use AES-GCM instead of AES-CTR in SwG Decryption

build-system/compile/build.conf.js
If any experiment is expired, an error is thrown from the config. It breaks the master build and all experiment tests are not run.
This removes the expiration date check from the config. `experiment-tests.js` does this check already, and any expired experiment is skipped.
=> 🏗 Don't throw an error from the experiments config if an experiment is expired

builtins/amp-img.js, test/unit/test-amp-img.js
It appears `unlayoutCallback` can be called anytime after `build`. I had expected that it could only be called after `layoutCallback` completed.
Thankfully, it doesn't cause any real issues, but it's getting a lot of error reports.
Fixes #25511
=> 🐛 Only unlayout img if img exists

src/batched-json.js
If the pub's endpoints return non-json responses, that's not our problem.
Fixes https://github.com/ampproject/amphtml/issues/20690
=> ♻️ Tag batched JSON fetch failures as user errors

extensions/amp-next-page/0.1/next-page-service.js, extensions/amp-next-page/0.1/test/test-amp-next-page.js, src/runtime.js
Closes #25069 , Partial for #15807 & #14059 
- Patches `amp-next-page v0.1` (the change will land in `v0.2`) to allow it to override document visibility for the added shadow docs, fixing interactions with `amp-pixel` and possibly `amp-analytics` (previously all added "next" documents would be given the "visible" state even during pre-rendering which would immediately trigger an `amp-pixel` hit before the user reaches the next page).
- Adds partial testing (most tests will come after `e2e` testing is implemented, see #24610 )
- Cleans up tests
- Adds a new type `ShadowDoc` which defines the Shadow document object (already generated by the AMP runtime but typed as `Object`)
Previous to this change, shadow docs appended by `amp-next-page` would follow their parent's visibility state which in …
=> ✨Manual management of `amp-next-page` document visibility

examples/sidebar-nested-menu.html, extensions/amp-nested-menu/0.1/amp-nested-menu.css, extensions/amp-nested-menu/0.1/test/validator-amp-nested-menu-error.html, extensions/amp-nested-menu/0.1/test/validator-amp-nested-menu-error.out, extensions/amp-nested-menu/0.1/test/validator-amp-nested-menu.html, extensions/amp-nested-menu/0.1/test/validator-amp-nested-menu.out, extensions/amp-nested-menu/amp-nested-menu.md, extensions/amp-nested-menu/validator-amp-nested-menu.protoascii
I2I: #25049 
Add validation and test files for the `<amp-nested-menu>` extension.
The following items are enforced via validation:
- Nested menu must be inside `<amp-sidebar>`.
- Support only `layout=fill`.
- Whitelist the components below inside mega menu:
- `<amp-list>`
- `<amp-accordion>`
- `<amp-img>`
- Each element inside the component may have at most one of the following attributes:
- `amp-nested-submenu`: can be applied to `div`'s only, and cannot be the descendant of `<amp-accordion>`
- `amp-nested-submenu-open`: can be applied to `div`, `span`, `button` or heading tags
- `amp-nested-submenu-close`: same as above
/cc @nainar we decided to not support ads for now since [according to documentation](https://amp.dev/documentation/components/amp-sidebar/#behavior) it's not among the …
=> Add validation and documentation for <amp-nested-menu>

extensions/amp-yotpo/0.1/amp-yotpo.js
corresponding to issue  #20559: Child iframe removed in unlayoutCallback but never restored. b/123308595
added layoutCallback to load child iframe
=> fix(amp-yotpo):restore child iframe in layoutCallback

extensions/amp-form/0.1/test/test-amp-form.js
Replace `stub.returns(Promise.resolve(x))` with `stub.resolves(x)`. Same goes for `Promise.reject`.
=> ♻️Clean up amp-form test stubs handling Promises

extensions/amp-a4a/0.1/callout-vendors.js, extensions/amp-a4a/rtc-documentation.md, extensions/amp-a4a/rtc-publisher-implementation-guide.md
This pull request adds Automatad to rtc callout vendors list
=> Add Automatad to RTC Callout Vendors

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js, extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Pass through all AMP experiments to SwG, so we don't need individual
logic per experiment flag.  Enable 'gpay-native' experiment to 100%. It
will take effect as the 'gpay' experiment is ramped up.
This does mean that AMP and SwG share experiment namespaces now.
=> 🐛 Pass through applicable AMP experiments to SwG

extensions/amp-base-carousel/0.1/carousel.js, extensions/amp-base-carousel/0.1/test/test-carousel.js
- Change the `isAtEnd` method to work correctly when the carousel's
width is not a whole number.
Fixes #25510
=> 🐛Fix next carousel arrow showing up at the end.

extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/test-amp-list-load-more.js, extensions/amp-list/0.1/test/test-amp-list.js, test/manual/amp-list/infinite-scroll-fail.amp.html
Should fix https://github.com/ampproject/amphtml/issues/20690#issuecomment-473480167.
Context: the code relating to the load-more-failed element logic was originally pretty hacky. I hacked some code onto the `fetchList` function, but needed to know in `loadMoreCallback` if the fetch failed so we could `catch` the error and show the `load-more-failed` element. I think we can just make this code cleaner by providing a separate fetch-and-render function with a different codepath for the load-more case. I wonder if there's actually any benefit from throwing that error, or can we just do without it since we address both cases by triggering a `fetch-error` action already and showing a fallback / load-more-failed-and-retry element. 
Note: see inline conversation regarding the `throw error` …
=> ♻️Refactor error handling for amp-list load-more as not to throw needless errors

contributing/design-reviews.md
The #design-reviews Slack channel is rarely used.  To avoid confusion I've archived this channel, and we'll point people to the #contributing channel instead.
=> Change to #contributing Slack channel for design reviews

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Only merge this after https://github.com/ampproject/amphtml/pull/25339 has reached production (ETA 1-2 weeks from now). You can double check this by copying valid examples from the above PR into https://validator.ampproject.org/ and verifying that it validates.
=> Launch amp-nested-menu to 100% of production and canary

extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js, extensions/amp-fx-flying-carpet/0.1/test/test-amp-fx-flying-carpet.js
It seems like at some point, `onMeasureChanged` used to be called prior to the first layout, but that no longer appears to be the case, causing the container width to not be set until the first resize.
- Remove usage of `onMeasureChanged`, instead use `layoutCallback` with `isRelayoutNeeded` to keep the logic consistent.
- Make the `layoutCallback` set the container width, which will happen on the first layout as well as any subsequent resize.
Fixes #25393
=> 🐛Fix initial sizing of the flying carpet area.

extensions/amp-sidebar/0.1/amp-sidebar.js, extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
Demo here: https://amp-sidebar-no-anim.firebaseapp.com
Alternative solution to the sidebar iOS UI glitch: #25251
=> Disable sidebar close animation on iOS back

ads/_a4a-config.js, build-system/compile/bundles.config.js, build-system/test-configs/dep-check-config.js, examples/a4a.amp.html, extensions/amp-ad-network-mytarget-impl/0.1/amp-ad-network-mytarget-impl.js, extensions/amp-ad-network-mytarget-impl/0.1/mytarget-a4a-config.js, extensions/amp-ad-network-mytarget-impl/0.1/test/test-amp-ad-network-mytarget-impl.js, extensions/amp-ad-network-mytarget-impl/OWNERS, extensions/amp-ad-network-mytarget-impl/amp-ad-network-mytarget-impl-internal.md
myTarget is going to implement Fast-Fetch and A4A.
In the first iteration myTarget adapter supports fast-fetch, but we don't verify and sign creatives yet - so we assign rendering method to crossorigin iframe ('nameframe').
Signed creatives are in development.
Current adapter workflow:
Ad request returns the JSON for the selected slot;
JSON is parsed to get the ad markup;
Ad markup is rendered via crossdomain frame ('nameframe' method).
Example tag is presented in a4a.amp.html
`<amp-ad width="300" height="250" type="mytarget" data-use-a4a="true" data-ad-slot="197378"> <div placeholder></div> <div fallback></div> </amp-ad>`
Please, check the implementation. Thank you in advance.
=> [amp-ad] Add a4a (fast fetch) support to myTarget amp-ads

src/runtime.js
closeShadowRoot_ was recently updated to return a promise that resolves
on a race between visibility state change completion or 15ms timeout.
The timeout is pretty easy to hit. Remove the sense that a regression
occurred when this feature was introduced due to the new console
warning. Matters have only improved for those taking advantage of the
shadow closure promise. Log at the info level instead of warn.
=> Reduce severity of shadow close timeout log

extensions/amp-form/0.1/test/test-amp-form.js
As written, the test would never fail. The test is setup to pass when the SUT fails and fail when the SUT passes.  The problem is that as written, the test won't fail even if the SUT passes.
=> 🐛 amp-form test: fix test logic bug that would make it always pass

examples/amp-story/analytics.html, extensions/amp-analytics/0.1/events.js, extensions/amp-analytics/0.1/test/test-events.js, extensions/amp-story/1.0/amp-story-affiliate-link.js, extensions/amp-story/1.0/amp-story-embedded-component.js, extensions/amp-story/1.0/page-advancement.js, extensions/amp-story/1.0/story-analytics.js, extensions/amp-story/1.0/test/test-analytics.js
Closes #25545
Adds `story-focus` trigger to track whenever an element that opens a tooltip is clicked and `story-click-through` whenever a tooltip is clicked.
It also adds support for using `tagName` to target specific elements that can trigger the tooltip.
If the overall implementation / idea looks good I will write the corresponding tests.
=> ✨📈  Add analytics trigger for elements that show a tooltip

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css, extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/story-ad-button-text-fitter.js, extensions/amp-story-auto-ads/0.1/story-ad-page.js, extensions/amp-story-auto-ads/0.1/test-e2e/test-amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js
Previously we only allowed CTA text from predefined choices, this allows ads to have custom text.
The new behavior is that the button will grow horizontally to fit the new variable text length. If the text is too long to fit within the design spec, the ad will be discarded.
=> ✨Allow custom text in ASAA CTA

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
- Update dependency rollup to v1.27.2 (#799)
- ✅ Moves two `expect` calls outside callbacks (#794)
- Update babelify and get rid of custom-babel-helpers (#795)
- Always log page load event (#796)
- Allow adding defaultArguments to ActivityPort calls (#790)
- Add e2e tests to travis and set travis jobs in sequential stages. (#792)
- Updates a few tests to use async/await (#791)
- Handle passed null promise (#767)
- Update dependency rollup to v1.27.0 (#788)
- Add a helper.js and some other cleanups. (#787)
- Move gulp build task to gulpfile and clean up gulp test task. (#786)
=> SwG release 0.1.22.84

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-attribution.css, test/fixtures/e2e/amp-story-auto-ads/basic.html
If a publisher writes a CSS rule like `amp-story { text-align: center }` this rule will affect the placement of the attribution icon, even though the icon element is in shadow DOM :(
This fix explicitly sets the `left` position so that pubs can't break the positioning in this way.
=> 🐛Fix attribution icon being centered incorrectly

extensions/amp-image-viewer/0.1/amp-image-viewer.css, extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js, extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js, test/manual/amp-base-carousel/basic.amp.html, test/manual/amp-base-carousel/fixed-children.amp.html, test/manual/amp-base-carousel/mixed-lengths-no-snap.amp.html, test/manual/amp-base-carousel/mixed-lengths.amp.html, test/manual/amp-base-carousel/vertical.amp.html
- Fix amp-image-viewer never loading if the amp-image is a `layout="flex-item"` or
otherwise does not define a size. This is more important for `amp-base-carousel`, where you can give the slides `layout="flex-item"`, but could occur in other cases as well.
- Add lightbox attribute to a few of base carousel's manual tests.
=> 🐛Support amp-lightbox-gallery with amp-base-carousel

build-system/server/app-utils.js, build-system/tasks/build.js, build-system/tasks/e2e/index.js, build-system/tasks/serve.js, build-system/tasks/visual-diff/index.js, package.json, yarn.lock
In order to support lazy-building, the `gulp serve` task was recently re-written to be an in-process server (instead of a `nodemon` child process). See #24325. This PR modifies the `visual-diff` and `e2e` tasks to use this new server startup mode.
- Rewrites `launchWebServer_()` in `visual-diff` and `e2e` to directly call `startServer()`
- Refactors `gulp serve` code to support non-default startup modes like `--compiled` or `--rtv <15 digits>`, and prevent lazy building during tests
- Fixes a bug in the `--rtv` case, where the mode was being set to `rtv` instead of the actual 15 digits
Fixes #25613
=> 🏗 Use in-process `gulp` server during `visual-diff` and `e2e`

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
Based on viewport size etc sometimes ads will serve with a fractional border visible around the top and left side of the iframe holding a creative.
This is caused by the iframe not taking the full viewport and the background of the story itself peeking through. For normal ads we have some logic that tries to center the creative  in `amp-ad.css`
https://github.com/ampproject/amphtml/blob/3c20f74235c3d175316e6b98c588d9a79b725245/extensions/amp-ad/0.1/amp-ad.css#L53-L58
This logic sometimes causes the result to be fractional pixels which manifests the bug. This change overwrites this logic for story ads and always moves them to the top left.
Side note: I couldn't figure out how to write a test for this, as something like `getBoundingClientRect()` will actually report `top: 0, left: 0` even …
=> 🐛Fix weird border on some story ads

build-system/tasks/extension-generator/extension-doc.template.md
This PR updates the template used to create reference documentation for new amp components.
=> 📖 updated extension generator markdown template

examples/amp-form-initialization-test.html, extensions/amp-form/0.1/amp-form.js, extensions/amp-form/0.1/test/test-amp-form.js, extensions/amp-form/amp-form.md
Introduce amp-form attribute `data-initialize-from-url` and form field
attribute `data-allow-initialization` to selectively populate form
fields from URL query parameter values on page load.
Fixes #24533
Fixes #24876
=> ✨amp-form: Initialize form from URL

build-system/tasks/bundle-size/APPROVERS.json, build-system/tasks/bundle-size/README.md, build-system/tasks/bundle-size/index.js
wip - not yet being used because the bundle-size app needs to be updated to use it
=> 🏗 Add APPROVERS.json to enable blocking bundle-size checks for extensions

extensions/amp-story/1.0/test/test-amp-story-embedded-component.js
Fixes a merge conflict between #25649 and #25587.
=> 🐛Use `env.sandbox` in `test-amp-story-embedded-component.js`

extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
- Moves `expect` calls to top level to prevent silently failing tests
- Fixes a test (`should fallback if viewer provides auth but fails`) where the last `expect` wasn't being checked
=> ✅ Moves `expect` calls to top level in test-amp-subscriptions.js

extensions/amp-carousel/0.1/amp-carousel.md
Adds "Supported Layouts for Slides" section to `amp-carousel 0.1` documentation to include information about best practices for sizing `amp-carouse[type=slides]` and its nested elements.
b/143604287 cc/ @GoTcWang
=> 📖Update amp-carousel 0.1 documentation for `type="slides"`

extensions/amp-access-poool/OWNERS
=> Create OWNERS for amp-access-poool

extensions/amp-iframe/0.1/test/test-amp-iframe.js, src/service/resource.js
Related to #9177, #22533, #23935.
=> Deflake FIE and amp-iframe tests executed on the running runtime

3p/3p.js, test/unit/test-3p.js
Ads use `validateData` to ensure required attributes exist. In #24850 we recommended creating an ad with `0` height and requesting resize. This did not work as expected. While debugging I discovered `validateData` will reject attributes with zero values even though they should be valid.
This is because it calls `userAssert` which checks for falsey values here https://github.com/ampproject/amphtml/blob/5f7a03d369d3cc76c5c0efb6647e94269b6225d1/src/log.js#L404
This changes the check to  `val != null`.
=> 🐛Allow zero vals for in validateData

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
In both instances, we want 100% native buy flow.
=> 🐛Turn SwG gpay 100% in canary and 10% in prod.

src/service/extension-location.js, src/service/extensions-impl.js, test/unit/test-extension-location.js, test/unit/test-extensions.js
=> Fix reloading for 'latest' extension versions

extensions/amp-story/1.0/amp-story-embedded-component.js, extensions/amp-story/1.0/amp-story.css
Closes #24298
Closes #21724
Since the final height of the tweet is unknown when loading it initially, we should only resize the element's width in preparation for the "expanded" animation. Then, when animating into the "expanded" view, we read the actual height of the element in order to scale it appropriately.
(notice cut-off tweets)
(notice I'm able to click sides of tweet without blocking navigation)
=> 🐛 Improvements for embedded tweets

extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/validator-amp-list.html, extensions/amp-list/0.1/test/validator-amp-list.out, extensions/amp-list/validator-amp-list.protoascii, src/batched-json.js, src/service/xhr-impl.js, test/unit/test-batched-json.js, test/unit/test-xhr.js
Partially fixes https://github.com/ampproject/amphtml/issues/17691, https://github.com/ampproject/amphtml/issues/22689, and b/143896641
**summary**
Creates a new helper within the `xhr` service called `xssiJson`. It is meant to be logically equivalent to a standard [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response)'s json() function, except this one also optionally takes in a prefix to strip.
This PR also adds support to this feature via a `strip-prefix` attribute _just_ to the `amp-list` component. After this is submitted we can discuss which other components should also have this option.
=> AMP Runtime: add support to strip xssi prevention prefixes before converting fetch responses to json

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
See https://github.com/ampproject/amphtml/pull/25172
=> Launch layoutbox-invalidate-on-scroll to 0.5% of prod

spec/amp-cors-requests.md
This document currently breaks the amp.dev build process.
@CrystalOnScript @sebastianbenz
=> 📝 Fix missing quotation mark in AMP CORS guide

extensions/amp-iframe/amp-iframe.md
`allow-popups-to-escape-sandbox` has been implemented in all major browsers:
Chrome, Firefox and Safari:
https://www.chromestatus.com/feature/5708368589094912
Opera:
https://dev.opera.com/blog/opera-33/
Edge:
https://caniuse.com/#search=allow-popups-to-escape-sandbox
/to @choumx
=> Correct sandbox attribute browser support

src/polyfills/custom-elements.js
This adds IE10 support to the Custom Elements v1 polyfill. IE10 doesn't support `Object.setPrototypeOf`, so we must fake it by recursively copying over all properties from the prototype to the base object.
=> 🐛 CEv1: Support IE10

build-system/tasks/presubmit-checks.js, extensions/amp-form/0.1/test/test-amp-form.js, src/ssr-template-helper.js, test/unit/test-ssr-template-helper.js
**summary**
Viewers should be trusted if attempting to use SSR. This is a take two at https://github.com/ampproject/amphtml/pull/25520, but with a much simpler approach. Instead of turning ssr service's `isSupported` function to return a promise, we can defer the trusted viewer check to render time and throw if untrusted (rather than falling back to csr).
This behavior is okay because the developer has already explicitly opted in to ssr via an ampdoc attribute.
/to @choumx, @jridgewell
=> Viewer must be trusted for ssr templates to be supported

src/service/resources-impl.js
I cannot figure out what is happening to causes `Array.prototype.splice` to be undefined. So, let's avoid `splice` entirely. Upside it this will avoid an array allocation in the resources pass, which is usually a hotpath.
Fixes https://github.com/ampproject/amphtml/issues/25766.
=> 🐛 Remove splice Infinity

examples/analytics-vendors.amp.html, extensions/amp-analytics/0.1/test/vendor-requests.json, extensions/amp-analytics/0.1/vendors.js, extensions/amp-analytics/0.1/vendors/deepbi.js
Follow up of https://github.com/ampproject/amphtml/pull/25128
(fixing CLA - "cannot verify e-mail" issue)
Intent-to-implement ticket: #25070
@micajuine-ho @zhouyx - Thank you for your input. I hope this time it will get smoother :)
=> Adding Deep.BI analytics to AMP

src/video-iframe-integration.js, test/unit/test-video-iframe-integration.js
Fixes #25774.
Host-level component already sets an allow-list:
https://github.com/ampproject/amphtml/blob/083122d905d8b3a8ed53e88ca1ecdac2f5531ed7/extensions/amp-video-iframe/0.1/amp-video-iframe.js#L61-L69
https://github.com/ampproject/amphtml/blob/083122d905d8b3a8ed53e88ca1ecdac2f5531ed7/extensions/amp-video-iframe/0.1/amp-video-iframe.js#L318-L321
Frame-level integration allow-list is redundant (and currently inconsistent, causing #25774)
=> 🐛Remove `postEvent` allowlist from video iframe integration

src/polyfills/custom-elements.js, test/unit/test-polyfill-custom-elements.js
This does two things:
- Removes unnecessary local variables for global functions (mainly `Object`, since reusing the module's global won't pollute anything)
- Tests and fixes `copyProperties` in creating prototype chains in IE10
Re: https://github.com/ampproject/amphtml/pull/25801
=> 🐛 CEv1: copy properties from prototype chain in IE10

extensions/amp-video-docking/0.1/amp-video-docking.css, extensions/amp-video-docking/0.1/amp-video-docking.js, extensions/amp-video-docking/0.1/controls.js, extensions/amp-video-docking/0.1/events.js, extensions/amp-video-docking/0.1/test/test-amp-video-docking.js, extensions/amp-video-docking/amp-video-docking.md
Fixes #21783
Changes docked video's controls set to a single button to scroll back to the video's inline box while an ad is playing (area would otherwise be too small to interact with the ad).
Additionally:
- fixes #24408, a controls flickering bug when docked area changes
- updates tests from non-standard generator syntax to `async/await`
=> ✨🐛 Scroll return button on docked video ad

build-system/compile/single-pass.js, build-system/server/app-index/index.js, build-system/server/app-index/test/test-self.js, build-system/server/app-index/util/listing.js, build-system/server/app-video-testbench.js, build-system/server/app.js, build-system/server/recaptcha-router.js, build-system/server/routes/a4a-envelopes.js, build-system/tasks/bundle-size/index.js, build-system/tasks/changelog.js, build-system/tasks/check-owners.js, build-system/tasks/csvify-size/index.js, build-system/tasks/dep-check.js, build-system/tasks/e2e/puppeteer-controller.js, build-system/tasks/e2e/selenium-webdriver-controller.js, build-system/tasks/prepend-global/index.js, build-system/tasks/process-3p-github-pr.js, build-system/tasks/process-github-issues.js, build-system/tasks/release-tagging.js, build-system/tasks/todos.js, package.json, yarn.lock
Several of AMP's `gulp` tasks use the `bluebird` package for promise functionality because they were written at a time when `node` did not natively support promises.
- Replaces `Promise` from `bluebird` with node's native `Promise`
- Replaces `Promise.all` from `bluebird` with node's native `Promise.all`
- Replaces `promisify` from `bluebird` with node's native [`util.promisify`](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original)
- Replaces `promisifyAll` from `bluebird` with native promise APIs of [`fs`](https://nodejs.org/api/fs.html#fs_fs_promises_api) and [`fs-extra`](https://www.npmjs.com/package/fs-extra#sync-vs-async-vs-asyncawait)
- Completely removes `bluebird` from `package.json`
- `util.promisify` …
=> 🏗🚮 Replace `bluebird` promises with node's native promises

build-system/externs/amp.multipass.extern.js, builtins/amp-img.js, extensions/amp-carousel/0.1/scrollable-carousel.js, extensions/amp-carousel/0.1/slidescroll.js, extensions/amp-carousel/0.1/test/test-slidescroll.js, extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js, extensions/amp-fx-flying-carpet/0.1/test/test-amp-fx-flying-carpet.js, extensions/amp-vk/0.1/test/test-amp-vk.js, src/base-element.js, src/custom-element.js, src/service/resources-impl.js, test/unit/test-amp-img.js, test/unit/test-custom-element.js, test/unit/test-resources.js
Fixes #24249. 
- Original error from: https://github.com/ampproject/amphtml/pull/23031#discussion_r352895947.
Partial for #25824. 
- custom-element.js already has a `layoutWidth_` with apparently the same semantics.
=> Fix error, remove BaseElement.layoutWidth_

src/service/position-observer/position-observer-worker.js
- Tightens type checking on the `relativePos` field of the position observer's `PositionInViewport` type
=> Correct type for position observer `relativePos`

build-system/tasks/e2e/describes-e2e.js, build-system/tasks/e2e/request-bank.js, extensions/amp-ad-exit/0.1/test-e2e/test-amp-ad-exit.js, test/fixtures/e2e/amphtml-ads/amp-ad-exit.amp.html, testing/request-bank.js
Port the existing RequestBank to be usable on nodejs because of lack of xhr support in the current implementation. Am looking at using this for unit/integration in a separate PR.
=> Add request assertion to amp-ad-exit e2e test

extensions/amp-carousel/0.2/amp-carousel.js
- Use center alignment for slides in carousel 0.2, avoiding an issue
with fractional scroll positions not being tracked. While fractional
scroll is being fixed in Chrome, it may take longer to land in Safari.
Fixes #25775
=> 🐛Avoid fractional scroll position impacting current index.

extensions/amp-carousel/0.2/amp-carousel.js
Check if the value is not `undefined` like carousel 0.1, so that `0` works. 
Fixes #25723
=> 🐛Fix amp-carousel 0.2 bound slide change to slide zero.

builtins/amp-img.js, builtins/amp-img.md, src/base-element.js, test/unit/test-amp-img.js, test/unit/test-base-element.js
- Copy data attrs from amp-img to inner img (fixes #24787)
- Minor performance optimization to related `propagateAttributes` method (don't call .length on every loop iteration)
=> ✨ Copy data attrs from amp-img to inner img (fixes #24787)

extensions/amp-story/1.0/amp-story.js
During prerendering, we only build/layout the first story page. `this.initializePages_()` will stay pending until all pages are built, preventing a lot of code (access, branching, bookend, ...) from being executing until the story `visibilityState` gets to `visible`.
But when the story only has one page, this one being built, `this.initializePages_()` will resolve and run a lot of code consuming precious CPU cycles too soon, as well as messing up the UI (the only page is hidden).
This is a no-op in all stories but the single page ones.
Fixes https://github.com/ampproject/amphtml/issues/25872
=> Fix single page story prerendering.

extensions/amp-carousel/0.1/scrollable-carousel.js, extensions/amp-carousel/0.1/slidescroll.js
Having a focusable carousel container makes it possible to escape Arrow keys. This is a follow up change to #25405. cc/ @zhangsu
=> 🐛Make amp-carousel 0.1 focusable

3p/beopinion.js
It would appear that the confusion would come from the inverted
parameters:
- `requestResize` has (width, height)
- `onResizeDenied` callback has (height, width)
Attaching requestResize to onResizeDenied would invert the height &
width, and given it reads the width from the #c container, mistaking
them results in the resized container to be `InitialHeight x RequestedHeight`.
Took the occasion to only register `onResizeDenied` once instead of
multiple times.
Closes #25687
=> 🐛 Possible fix for resizing amp-ad beop

validator/engine/validator.js
In the validator engine, one of the comments is misleading, as it implies the wrong criteria to check.
The original comment `RESPONSIVE only allows heights attribute.` makes me think the limitation is on the attributes that responsive allows for, like not allowing for a width to be set on responsive.
However, looking at the code, it becomes apparent that the limitation is that the height attribute should not be present for any of the other layouts, only for responsive. So it doesn't limit what attributes the responsive layout can have, it limits what layout the height attribute can be applied to.
Therefore I suggest changing the comment to `Height attribute is only allowed for RESPONSIVE layout.`
=> 📖 Adapt misleading comment in validateLayout()

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/iframe-transport.js, extensions/amp-analytics/0.1/test/test-iframe-transport.js, extensions/amp-analytics/0.1/test/test-transport.js, extensions/amp-analytics/0.1/transport.js
Removed unnecessary preconnect as we are loading the iframe immediately.
This is a follow up of https://github.com/ampproject/amphtml/pull/25917/files#r354994477
=> Inject transport iframe to top window

extensions/amp-consent/0.1/consent-config.js, extensions/amp-consent/0.1/test/test-consent-config.js
One single instanceId to store consent info is allowed. Fix the issue the value NOT be overridden based on geo location. I'll make a change to the doc in a following PR.
=> amp-consent geoOverride: should NOT override instanceId

extensions/amp-script/amp-script.md
SUMMARY CHANGE
User-gestures, height rules from `< 300px` to `≤ 300px` to reflect that 300px is included.
=> 📖 Update rule for mutation / user-gesture

examples/visual-tests/amp-video-docking/amp-video-docking.js, examples/visual-tests/amp-video-docking/video-iframe-inner.html
1. Wait for controls to be visible on `hover`.
2. Give scrolling transition leeway (certain small vertical deltas were caused from near-done transitions).
3. Wait for scrollback controls by classname instead of trying to match the internal video iframe ad timeout.
4. Increase internal video ad timeout for leeway in tests occurring before it.
=> ✅ Unflake video docking visual tests

ads/google/a4a/test/test-utils.js, ads/google/a4a/utils.js, test/unit/test-error.js, test/unit/test-experiments.js
Recent updates in release scripts as a part of https://github.com/ampproject/amphtml/issues/25560 changed the release name in `AMP_CONFIG.type` from `canary` to `experimental`. There is one location in `amphtml` which uses this release name to determine the binary type RTV prefix code, which was not updated.
This PR updates two tests which referenced `canary` (one of which, `utils-test.js`, failed with this update). It then updates the `utils.js` code in A4A which references the old release name.
=> 🐛 Fix binary type map in a4a

extensions/amp-video-iframe/amp-video-iframe.md
A common problem is that new custom players are submitted when they're not required, as amp-video-iframe would be enough.
This clarifies how video vendors can take advantage of amp-video-iframe to let AMP authors embed video provided via their service.
=> 📖 Specify how amp-video-iframe can be used by video vendors 

src/service/extensions-impl.js, src/validator-integration.js, test/unit/test-validator-integration.js
**summary**
Any `nonce` attribute on script tags should be propagated to dynamically injected script tags.
Fixes https://github.com/ampproject/amphtml/issues/25701.
=> 🐛 Propagate nonce to generated script tags.

extensions/amp-video-docking/0.1/amp-video-docking.css, extensions/amp-video-docking/0.1/amp-video-docking.js, extensions/amp-video-docking/0.1/test/test-amp-video-docking.js
- RTL controls are incorrectly aligned and ordered.
- Cheaper and simpler to use `getPageLayoutBox` for slot element.
=> 🐛♻️ Docking: pageLayoutBox and position RTL controls

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, src/service/navigation.js, tools/experiments/experiments-config.js
Fixes #25180. Context: #25179.
View diff with whitespace ignored for easier reading.
=> Clean up 'remove-viewer-query-params-on-navigate' experiment

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
- ♻ Registers `src/proto/api_messages_test.js` as a test (#866)
- ✅ Improves test coverage (#865)
- Update dependency rollup to v1.27.9 (#863)
- Add subscribe button to amp article page (#861)
- Remove fancy-log and traivs requires in preinstall script. (#859)
- 🚮 Removes extra files (#860)
- Further work to propogate one-time status with sku (#855)
- Update dependency postcss to v7.0.24 (#858)
- Update babel monorepo to v7.7.5 (#857)
- Add sorting imports to "gulp lint" (#856)
- Run e2e tests against local server (#850)
- ✨ Updates API messages (#854)
- Remove experiment flag for Contributions (#852)
- Update dependency gulp-rename to v2 (#851)
- Update dependency gulp-git to v2.10.0 (#849)
- Update dependency rollup to v1.27.8 (#848)
- Update dependency rollup to v1.27.7 (#847)
- Update …
=> Swg release 0.1.22.85

extensions/amp-next-page/0.1/next-page-service.js
Closes #25812
- Switch to using a separate element for measuring position updates instead of relying on the separator (which can be customized to be `display: none` in which case the position observer no longer can observe it).
=> 🐛 amp-next-page fix interaction with styles

extensions/amp-autocomplete/0.1/amp-autocomplete.js, extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js, extensions/amp-form/0.1/amp-form.js, extensions/amp-form/0.1/test/test-amp-form.js, extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/test-amp-list.js, src/ssr-template-helper.js, test/unit/test-ssr-template-helper.js
This change is to better signal the intent of the variable. It is meant to signify that SSR should be used as opposed to just that it is "supported" (possible to use).
=> ♻️ Refactor template helper: Rename isSupported() to isEnabled()

build-system/tasks/e2e/amp-driver.js
Use case is for testing urls with amp-geo signifier (#amp-geo=de)
=> 🐛 Append url parameters correct in viewer-demo 

extensions/amp-next-page/amp-next-page.md
Documents two triggers that already exist on the host page using `amp-next-page`
=> 📖Documents existing analytics triggers on `amp-next-page`

extensions/amp-script/0.1/amp-script.js, extensions/amp-script/0.1/test/unit/test-amp-script.js, extensions/amp-script/amp-script.md, test/unit/test-validator-integration.js
**summary**
Addresses https://github.com/ampproject/amphtml/issues/24862
With this change, we allow all `AMP.setState` calls triggered within an amp-script to cause bind reevaluations as long as there was a recent (5s) user interaction.
**open question**
1. Is 5 seconds too long of a user interaction window? If so, how short should it be?
cc @choumx / @jridgewell
=> Treat amp-script AMP.setState as high trust

build-system/babel-plugins/babel-plugin-transform-simple-object-destructure/index.js, build-system/babel-plugins/babel-plugin-transform-simple-object-destructure/test/fixtures/transform/computed-keys/input.js, build-system/babel-plugins/babel-plugin-transform-simple-object-destructure/test/fixtures/transform/computed-keys/options.json, build-system/babel-plugins/babel-plugin-transform-simple-object-destructure/test/fixtures/transform/computed-keys/output.js, build-system/babel-plugins/babel-plugin-transform-simple-object-destructure/test/fixtures/transform/non-identifier-keys/input.js, build-system/babel-plugins/babel-plugin-transform-simple-object-destructure/test/fixtures/transform/non-identifier-keys/options.json, build-system/babel-plugins/babel-plugin-transform-simple-object-destructure/test/fixtures/transform/non-identifier-keys/output.js, test/unit/test-validator-integration.js
We need to use computed keys when the key is a quoted key or a numeric key. Also adds tests for computed keys.
Necessary for #25969.
=> 🐛 Fix simple-object-destructure transform for check-types

extensions/amp-base-carousel/0.1/amp-base-carousel.css, extensions/amp-base-carousel/0.1/test-e2e/test-hidden-controls.js, test/manual/amp-base-carousel/hidden-controls.amp.html
The selector was giving the `pointer-events: none` to the parent of the button, which was set to `pointer-events: all` a few rules above.
- Added a e2e test to make sure the button is not clickable.
- Tested on VoiceOver and Talkback to make sure the accessibility still works as expected.
=> 🐛Fix next/prev arrows being clickable with hidden controls for amp-base-carousel

validator/engine/validator.js, validator/testdata/transformed_feature_tests/server_side_rendering.html, validator/testdata/transformed_feature_tests/server_side_rendering.out, validator/testdata/transformed_feature_tests/transformed_but_not_identified_transformed.out, validator/validator-main.protoascii
Intrinsic layout SSR adds the following sizer element:
```html
<amp-img height="100" width="300" layout="intrinsic" class="i-amphtml-layout-intrinsic i-amphtml-layout-size-defined" i-amphtml-layout="intrinsic">
<i-amphtml-sizer class="i-amphtml-sizer">
</i-amphtml-sizer>
</amp-img>
```
This commit extends the `i-amphtml-sizer` validation rules to
alternatively support the intrinsic sizer element. The SVG sizer image
is validated via a regex checking if the `src` value is an SVG.
=> ✨ Validator support for transformed intrinsic layout

src/log.js, src/service/viewer-impl.js
Fixes #25923 
Another approach I've been thinking of is to introduce an `opt_errorType` param to the `#reportError()` method. But that doesn't apply to the uncaught error that we ret hrow. 
The code looks like
```
return Services.timerFor(this.win)
.timeoutPromise(20000, messagingPromise, 'initMessagingChannel')
.catch(reason => {
const error = getChannelError(
/** @type {!Error|string|undefined} */ (reason)
);
reportError(error);
throw error;
});
```
Do you know why we want to re-throw the error after calling `reportError()` (From my test, either one should get the error sent to endpoint)
=> Report dev error at viewer channel timeout

build-system/tasks/changelog.js
This PR fixes the following error in `gulp changelog`.
```
lastTag.trim is not a function
```
The error appears because `exec` returns an object containing two fields: `stdout` and `stderr`. The error can be traced back to the migration from `bluebird` promises to `util.promisify` done in #25822.
=> 🐛 Fix `gulp changelog`

test/unit/test-performance.js
- Provide a navigator on the fakeWin object which is needed when
creating the Performance service.
=> 🐛Fix test failure

ads/zucks.js
We din't load our ad inside the container #c so our ad din't show up.
=> 🐛 load script inside #c container for Zucks ad

src/service/performance-impl.js
Reverts #8142. 
Is this still useful? I find it confusing since "is canary" is already baked into our RTV scheme. Removing this would also simplify our latency dashboards.
/to @lannka @dvoytenko
=> Remove 'canary' perf experiment

extensions/amp-story/1.0/amp-story-quiz.js
Fixes small gcc type error:
```
extensions/amp-story/1.0/amp-story-quiz.js:121: WARNING - [JSC_MISSING_RETURN_STATEMENT] Missing return statement. Function expected to return boolean.
const gridLayer = closest(dev().assertElement(this.element), el => {
```
=> ♻️ amp-story-quiz: fix small gcc type warning

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
amp story auto ads should bail out early if there aren't enough pages in the story to ever be placed.
Partial fix for #22001
=> 🐛Don't request story ad in short stories.

extensions/amp-auto-ads/0.1/amp-auto-ads.js, extensions/amp-auto-ads/0.1/test/test-amp-auto-ads.js
When there is no config the server can send a noConfigReason which is displayed in the console. Currently this then prevents all the ad strategies from running, but some of the ad strategies may not require everything in the config. For example there may be no placements (and thus the server ads a noConfigReason explaining this), but it may still be worth running the anchor strategy, since this doesn't require placements.
=> Modifying AMP Auto Ads to run strategies even if noConfigReason present

build-system/tasks/build.js, build-system/tasks/helpers.js, package.json, yarn.lock
This PR adds coverage instrumentation to the unminified runtime served while running integration tests. It uses [`gulp-istanbul`](https://www.npmjs.com/package/gulp-istanbul) to do so, via an intermediate step during `gulp build --coverage`. We're still looking for a way to measure and report the coverage from within a browser during test execution.
Partial fix for #22682
=> 🏗 Add a `--coverage` flag to `gulp build` to instrument the unminified runtime

validator/java/pom.xml
This PR fixes the security warning introduced by #25579.
Resolves https://github.com/ampproject/amphtml/pull/25579#discussion_r354478921
/cc @GeorgeLuo
=> 🏗 Upgrade `com.puppycrawl.tools:checkstyle` to 8.18

validator/validator-main.protoascii
Fixes #26061
Allows `chrome://` protocol in `<a href>`.
=> Allow chrome protocol to A href

extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js, extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js, extensions/amp-auto-ads/0.1/adsense-network-config.js
🐛 Bug fix currently if amp-ad type=adsense element within amp-ad-sticky results in no fill on canonical AMP page, sticky element is improperly made visible.
Issue due to x-origin handler improperly calling renderStart based on load or timeout when expectation is the underlying adsense impl class is expected to trigger based on receiving fill postMessage.
=> Fix: amp-sticky-ad made visible for AdSense no fill case

build-system/tasks/e2e/package.json, build-system/tasks/e2e/yarn.lock
Update to the latest Selenium version so that we can take advantage of their new performance logging feature for e2e tests.
=> 🏗 Update Selenium version for e2e tests

extensions/amp-story/1.0/progress-bar.js
Not a big deal since people can't resize their phone, but when developers enable the responsive mode from the devtools the sidebar doesn't update correctly.
A better fix would be for the progress bar to be an AMP component, so we could listen for `onMeasureChanged` callbacks.
=> Change progress bar resize delay.

extensions/amp-story/1.0/amp-story-quiz.css, extensions/amp-story/1.0/amp-story-quiz.js
Adds animation to selecting an option from an `<amp-story-quiz>` element. The animation is available to view [here](https://codepen.io/jackbsteinberg/pen/BayKzrm).
Adds work related to #25615
=> 🖍Add animation to story quiz option selection

extensions/amp-form/amp-form.md
Fixes #22586
`amp-form` documentation currently states that `submit-success` and `submit-error` elements must be direct children of the form. In practice, `amp-form` respects these attributes if they are present on any descendent. This change updates the documentation to reflect this.
=> 📖amp-form renders response via templating provided in any descendent

extensions/amp-list/validator-amp-list.protoascii
This can already be achieved via the `changeToLayoutContainer` action, so it makes sense to whitelist the binding too.
=> Whitelist amp-list's [is-layout-container] in AMP for Email

extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/test-amp-list.js
**summary**
Addresses https://github.com/ampproject/amphtml/issues/25961
Adds a check that the `src` has not changed while the xhr was inflight. If the `src` has changed, then bail instead of scheduling a render.  I've added a test that previously would have resulted in two renders and now instead only has one.
cc @jridgewell  / @choumx
=> 🐛 Fix amp-list race condition

extensions/amp-analytics/0.1/activity-impl.js, test/unit/test-activity.js
- Add inactive events.
It stops calculate "${totalEngagedTime}" when mouse leave document.
=> ✨ Add inactive event types to amp-analytics

extensions/amp-nested-menu/0.1/amp-nested-menu.js, extensions/amp-nested-menu/0.1/test/test-amp-nested-menu.js, extensions/amp-sidebar/0.1/amp-sidebar.js, test/manual/amp-nested-menu/amp-nested-menu.amp.html, tools/experiments/experiments-config.js
Closes #25343. Merge this 2 release cycles AFTER https://github.com/ampproject/amphtml/pull/25516 has been launched to production and we have fixed an major outstanding bugs.
=> Cleanup the amp-nested-menu experiment

examples/forms.amp.html, extensions/amp-form/0.1/amp-form.js
Resolves #26004.
This change supports form submission via `Ctrl`/`Cmd` + `Enter` from within any nested `textarea`  element.
=> Support Ctrl + Enter to submit a form within a <textarea>

build-system/externs/amp.extern.js
**summary**
Just runs prettier on `amp.extern.js`.
Note: this removed/added some semicolons.
cc @choumx
=> ♻️ Run prettier on amp.extern.js

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/story-ad-page.js, extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
Fixes 2 bugs:
1. Should not request a new ad when visiting a previously seen ad (only when user sees a new ad)
2. Should not request an ad when there are not enough pages left in a story for it to be placed.
Closes #22001
=> 🐛Fix ad request logic in stories

extensions/amp-nested-menu/amp-nested-menu.md, extensions/amp-sidebar/0.1/amp-sidebar.md
Closes #26175, Partial for #26176 
- Adds an excerpt of the `amp-nested-menu` documentation to `amp-sidebar` 0.1
=> 📖 Document `amp-nested-menu` usage in `amp-sidebar`

src/service/cid-impl.js
Please see https://github.com/ampproject/amphtml/issues/25525#issuecomment-568125214 for context. 
Closes #25525 
@zikas Could you please confirm that this is the desired behavior. That the `CLIENT_ID(scope, opt_userNotificationId, opt_cookieName)` always return the value from `opt_cookieName` even if there's also value stored in `scope` (or if there's a new value generated for `scope`)? Thank you!
=> Always return cookie from origin if exist

examples/date-picker.amp.html, extensions/amp-date-picker/0.1/amp-date-picker.js, extensions/amp-date-picker/0.1/test/validator-amp-date-picker.html, extensions/amp-date-picker/0.1/test/validator-amp-date-picker.out, extensions/amp-date-picker/amp-date-picker.md, extensions/amp-date-picker/validator-amp-date-picker.protoascii
Implements `hideKeyboardShortcutsPanel` on amp-date-picker. Fixes #25608
/cc @caroqliu
=> ✨ amp-date-picker: allow to hide keyboard shortcuts panel #25608

examples/masking.amp.html, extensions/amp-inputmask/0.1/mask-impl.js, extensions/amp-inputmask/0.1/test/test-mask-impl.js
Fixes #24493
Calls `mask` on an `amp-inputmask` input when its value gets altered by `amp-state`.
=> 🐛Remask amp-inputmask elements on amp-state change

extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Fixes #24653.
We currently set a fixed z-index on flex ad slots upon expansion which is causing ads to hover over publisher content (usually navigation components which also use a z-index, but often a lower value), with no obvious added benefit. After this PR is merged, we will default to not setting a z-index for flex ad slots, but will maintain a temporary holdback experiment to ensure no other breakages occur and to allow for the easy reversal of this change.
This also removes an old holdback experiment for enabling flex ad slots, which is no longer of use.
=> Remove z-index on flex ad slots by default.

extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/amp-story.css
Respects `prefers-reduced-motion` for AMP story content animations.
This does not affect system components for now, but only animations provided by `animate-in` attributes, or custom publisher animations.
#24821
=> Respects prefers-reduced-motion for content animations.

.github/ISSUE_TEMPLATE/cherry_pick_template.md, .github/ISSUE_TEMPLATE/release-tracking-issue.md, .github/ISSUE_TEMPLATE/release_issue_template.md
Currently, we link to bit.ly/amp-cherry-picks for the cherry-pick documentation. https://github.com/ampproject/amp.dev/pull/3351 creates an AMP.dev shortlink (and updates the destination, since the documentation location changed). This PR updates the places in AMP HTML docs that reference the old link.
=> 📖 Update docs referencing bit.ly/amp-cherry-pick

build-system/tasks/presubmit-checks.js, build-system/test-configs/conformance-config.textproto, extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story-viewer-messaging-handler.js, extensions/amp-story/1.0/test/test-amp-story.js
Implement a Story <> Viewer messaging API allowing getting and setting states.
As suggested by @newmuis, there's an extra layer between the messaging and the internal store service, so we can still deprecate/refactor/rename the internal or external facing states independently.
This layer also provides extra state validation, to protect the store service from incorrect viewer messages.
=> Viewer get/setDocumentState messaging.

build-system/test-configs/dep-check-config.js, examples/amp-story/supports-landscape-ads.html, extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-attribution.css, extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css, extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/story-ad-page.js, extensions/amp-story-auto-ads/0.1/test-e2e/test-amp-story-auto-ads-fullbleed.js, extensions/amp-story-auto-ads/0.1/test-e2e/test-amp-story-auto-ads-utils.js, extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js, test/fixtures/e2e/amp-story-auto-ads/basic.html, test/fixtures/e2e/amp-story-auto-ads/fullbleed.html
Story ads so far have not been responsive. Introduces a new view for fullbleed stories on desktop where we render the ad in a mobile like size.
=> 🌉New "mobile" view for ads in fullbleed story

extensions/amp-next-page/0.2/service.js, extensions/amp-next-page/0.2/test/test-amp-next-page.js, extensions/amp-next-page/0.2/test/test-config.js, extensions/amp-next-page/0.2/utils.js
- Ports unit tests from `amp-next-page` v1 to v2 with a cleaner API
- Adds new unit tests, with more to come in following PRs
- Fixes bug in url rewriting
=> ✅ Implements unit test for `amp-next-page` v2

extensions/amp-a4a/0.1/callout-vendors.js, extensions/amp-a4a/rtc-documentation.md, extensions/amp-a4a/rtc-publisher-implementation-guide.md
This pull request adds flux adserver as a RTC callout vendors.
=> add flux as RTC callout vendors

extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side-expire-cache.js, extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side.js
Closes #26214
Was making 2 analytics request (1 for each page visit), but only withdrawing 1 from the request bank, leading to sometimes checking the right request.
Now withdraw both requests in the correct order.
=> Fix amp-consent flakey e2e

extensions/amp-story/1.0/amp-story-draggable-drawer.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story.js
When the viewer uses the `#cap=swipe` opt-in:
- Forwards vertical touch events, but still handling the page attachment case (there's no bookend in this mode, but they share the same code so it'd work properly too)
- Stops showing the navigation hint overlay UI as vertical events are for swiping to close / opening the page attachment, and horizontal events are for swiping between stories
More context and details #25697
Fixes #25697
=> Propagate vertical touch events in stories.

src/utils/story.js
Fixes bug that causes some documents to never send performance ticks e.g. the AMP4Email "Hello World" sample doc.
`b/147509020`
=> Fix edge case in isStoryDocument()

examples/amp-subscriptions.amp.html, extensions/amp-analytics/0.1/test/vendor-requests.json, extensions/amp-analytics/0.1/vendors/subscriptions-propensity.js, extensions/amp-analytics/0.1/vendors/subscriptions-propensity.json, extensions/amp-subscriptions/0.1/amp-subscriptions.js
Propensity has agreed to move the JSON object out of the shared parameter and into its own parameter.  This resolves an issue with double encoding.
=> 🐛 Change method of sending data to Propensity

extensions/amp-analytics/0.1/test/test-variables.js, extensions/amp-analytics/0.1/variables.js, src/OWNERS
=> 🐛Only expand strings in arrays

extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js, src/auto-lightbox.js
The `amp-auto-lightbox` script is loaded on all AMP Story documents, even in prerender mode.
This script is never used, removing it would save a bit over 3kb per story prerendered or loaded.
I added the `isStoryDocument` check in the `chunk()` statement as it uses some CPU cycles, but I'm open to alternative implementations. It delays the loading of the `amp-auto-lightbox` to after the `body` is fully parsed, which should be fine since AFAIK the lightbox can only be triggered by a user interaction.
=> Do not load amp-auto-lightbox on amp-story documents.

src/service/resources-impl.js, test/unit/test-mutator.js
Flexible ad slot expansion was [launched](https://github.com/ampproject/amphtml/pull/23931) earlier this year in August. The new behavior enables large creatives to be rendered within smaller ad slots, necessarily requiring the runtime to expand the slot element at render-time. As preparation for the launch, we made a slight [change](https://github.com/ampproject/amphtml/pull/23031) to AMP’s no-reflow policy, to allow in-viewport expansion if the following criteria hold:
- Width-only expansion,
- Element has no siblings,
- Parent element is an AMP element,
- Parent element's width is >= the new element width
These conditions, however, are too restrictive to allow in-viewport expansion in many cases, resulting in cropped ad slots that load within the viewport. This PR will modify the …
=> Modify restrictions for in-viewport expansion

extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/validator-amp-list.out, extensions/amp-list/validator-amp-list.protoascii
**summary**
Remove `[state]` attribute, which was deprecated back in Feb 2018 (https://github.com/ampproject/amphtml/pull/13237).
After checking our internal tool cookbook, this attr doesn't seem to be used in the wild.
=> ♻️ amp-list: remove support for deprecated state attribute

ads/google/a4a/line-delimited-response-handler.js, build-system/compile/compile.js, extensions/amp-analytics/0.1/instrumentation.js, extensions/amp-autocomplete/0.1/autocomplete-binding-inline.js, extensions/amp-autocomplete/0.1/autocomplete-binding-single.js, extensions/amp-fx-collection/0.1/fx-type.js, extensions/amp-lightbox-gallery/0.1/utils.js, extensions/amp-story/0.1/amp-story-share.js, extensions/amp-story/0.1/amp-story-store-service.js, extensions/amp-story/0.1/embed-mode.js, extensions/amp-story/1.0/amp-story-draggable-drawer.js, extensions/amp-story/1.0/amp-story-embedded-component.js, extensions/amp-story/1.0/amp-story-share.js, extensions/amp-story/1.0/amp-story-store-service.js, extensions/amp-story/1.0/embed-mode.js, extensions/amp-story/1.0/story-analytics.js, extensions/amp-video-docking/0.1/events.js, src/iframe-helper.js, src/log.js, src/service/origin-experiments-impl.js, src/service/owners-interface.js, src/service/resource.js, src/service/variable-source.js, src/url-rewrite.js, src/utils/xhr-utils.js, third_party/react-externs/externs.js
The `accessControls` closure compiler visibility check rule is currently ignored during `gulp check-types`. Turning on the rule results in about [350+ annotation errors](https://github.com/ampproject/amphtml/issues/26307#issuecomment-573214902).
This PR enables the rule and fixes all incorrect annotation errors. It took only ~25 annotation changes to fix all 350+ errors.
**Reference:** https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#visibility-checks
Fixes #26307
=> 🏗 🐛 Enable `accessControls` checks for JS code (and fix errors)

extensions/amp-mustache/0.1/test/test-amp-mustache.js, extensions/amp-mustache/0.2/test/test-amp-mustache.js, extensions/amp-mustache/amp-mustache.md, src/purifier/sanitation.js, test/unit/test-purifier.js
Since `<colgroup>` is allowed in triple mustache, `<col>` should also be. Related: b/141568361
=> Allowlist <col> tag for triple mustache 

extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js, extensions/amp-story/1.0/test/test-amp-story-viewer-messaging-handler.js
- Allows the `viewer-messaging-handler` API to retrieve data from the browser history, or the variable service
- Allows the `getDocumentState` viewer API to retrieve `PAGE_ATTACHMENT_STATE` and `STORY_PROGRESS`, as needed for various viewer use cases
#26020
=> Adding attachment state and story progress to getDocumentState API.

extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-auto-ads/0.1/adsense-network-config.js, extensions/amp-auto-ads/0.1/test/test-adsense-network-config.js
AdSense custom channels allow to track the performance of specific adunits and generate reports for each channel.
AMP currently only supports the data-ad-channel attribute, which allows to specify one or more custom channels for a specific amp-ad element.
Host channels are also available to AdSense Host account, these can be used to track the performance of ads across publishers.
https://developers.google.com/adsense/host/adunits#custom-channels
https://developers.google.com/adsense/host/faq/hostchannels
Currently AMP doesn't allow to specify an Host channel to `amp-ad` elements, this pull request adds support for the `data-ad-host-channel` attribute to both `amp-ad` and `amp-auto-ads` elements.
=> ✨ Add support for data-ad-host-channel to AdSense ads

build-system/tasks/presubmit-checks.js, examples/amp-story/quiz.html, extensions/amp-story/1.0/amp-story-quiz.js, extensions/amp-story/1.0/amp-story-request-service.js, extensions/amp-story/1.0/test/test-amp-story-quiz.js
Adds support for API calls in AMP Story Quizzes, to both retrieve and update the Reactions data. Currently the API calls must be supplied an endpoint, support for a default endpoint will come in a future PR.
=> ✨Add support for AMP Story Quiz Reaction API calls

.github/ISSUE_TEMPLATE/intent-to-implement--i2i-.md, .github/ISSUE_TEMPLATE/intent-to-ship--i2s-.md
This reverts commit d46416bb1c520bae1c9d09521d1e2e93cef51405.
Reverting because the original PR doesn't address the comment here: https://github.com/ampproject/amphtml/pull/25530#discussion_r366546137
=> Revert "Update I2I & I2S to reflect new Open Source process (#25530)"

package.json, validator/gulpjs/package.json, validator/nodejs/package.json, validator/package.json, validator/webui/package.json
The `engines` section of `package.json` has traditionally been used to enforce a known good range of versions of `node` for local development. This has worked well so far for developers who work on the `amphtml` repo, where we require an active LTS version of `node` (and recommend the _latest_ active LTS version of `node`).
However, we've had multiple instances in the past of the `engines` section of `package.json` coming in the way of developer workflows for external contributors who use sub-packages published from within the `amphtml` repo. See earlier relevant discussions in #19050, #19218, #25161, #25189, #25209, and #26408.
In addition, it has caused failures on Travis CI when `node` pushes out a new version, causing our `package.json` files to be outdated until they are manually …
=> 🏗 Remove the `engines` section from all `package.json` files in `amphtml`

validator/validator-main.protoascii
=> cl/290808403 Allow span[tooShort] in validation.

src/service/fixed-layer.js, test/unit/test-fixed-layer.js
When an AMP document is served canonically (like AMP.dev), the FixedLayer service is not needed.
This change disables the FixedLayer from performing its setup phase while we investigate a longer term fix. (#26397)
=> 🚀 Disable FixedLayer when page is served canonically

src/service/url-expander/expander.js, test/unit/url-expander/test-expander.js
Previously the parser ignoring feature only worked when an argument was completely wrapped in backticks eg ``FOO(abc, ` - `)``
This allows backticks to be used anywhere inside of a macro to give raw input. 
Follow up to #26247.
=> 🐛Expander: better support of backticks

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
Closes #26334 
In most browsers a css property set in keyframes will override a !important style. This does not happen in Firefox 😕.
=> 🐛Fix CTA not showing in Firefox

.vscode/settings.json
**Highlights:** Addresses this warning from VS Code's `eslint` plugin by migrating the deprecated setting to the new one.
**Reference:** `vscode-eslint` [release notes](https://github.com/microsoft/vscode-eslint/tree/release/2.0.4#release-notes).
=> 🏗 Migrate deprecated VSCode setting `eslint.autoFixOnSave` to `editor.codeActionsOnSave`

build-system/externs/amp.extern.js, src/amp.js, src/mode-object.js, src/mode.js
this will allow for us to identify if an AMP page has loaded the module or no module build.
module builds will be marked as `rtv-${version}-esm` while no module builds will be the usual `rtv-${version}`
=> add esm AMP_CONFIG field and esm performance identifier

.eslintignore, .eslintrc, ads/ads.extern.js, build-system/externs/amp.extern.js, build-system/externs/dompurify.extern.js, third_party/moment/moment.extern.js
Reverts ampproject/amphtml#26228
Revert reasons (https://github.com/ampproject/amphtml/pull/26228#issuecomment-577418939):
1. Initial merge was done via 8 commits instead of a squashed 1
2. There have been changes to the externs files that make them out of sync with the introduced lint rules (making master red)
=> Revert "♻️ Lint: include externs"

extensions/amp-a4a/0.1/callout-vendors.js, extensions/amp-a4a/rtc-documentation.md, extensions/amp-a4a/rtc-publisher-implementation-guide.md
This PR adds The Ozone Project RTC callout URL in callout-vendors.js.
_NOTE:
Our endpoint will be responding with content only to requests from the domains that are whitelisted in our prebid-server setup._
@mrjoro The Ozone Project agreed to the corporate CLA AFAIK but I am not sure what's the status of that at the moment.
@keithwrightbos Could you please review and let me know if anything else is required.
Thanks,
Greg
=> ✨ The Ozone Project: Add RTC endpoint to callout-vendors.js

extensions/amp-story/1.0/test/integration/test-amp-story-affiliate-link.js
Seems to be broken (or at least very flaky):
- https://travis-ci.org/ampproject/amphtml/jobs/640678925
- https://travis-ci.org/ampproject/amphtml/jobs/640676380
- https://travis-ci.org/ampproject/amphtml/jobs/640623255
This was skipped in https://github.com/ampproject/amphtml/pull/26386. That skip was reverted in https://github.com/ampproject/amphtml/pull/26395. I'm now un-reverting it.
=> ✅ Skip broken amp-story-affiliate link test

tools/experiments/experiments.html, tools/experiments/experiments.js
Fixes #25205
Tag-along change:
* Renamed dev/rc to experimental/beta (UI-facing change only, no backend change here)
=> 🏗 Add specific RTV opt-in to experiments.html

3p/integration.js, ads/_config.js, ads/byplay.js, ads/byplay.md, examples/ads.amp.html, extensions/amp-ad/amp-ad.md
We added "ByPlay" that the type of amp-ad.
Would you merge this commit?
We already signed a CLA.
Corporation Name: Tsumiki Inc.
=> Add amp-ad support for ByPlay

src/chunk.js, src/inabox/amp-inabox.js
=> Disable macro-after-long-task in inabox.

extensions/amp-consent/0.1/consent-ui.js, extensions/amp-consent/0.1/test/test-consent-ui.js, tools/experiments/experiments-config.js
Task 2 for #26432
If flag is on, don't focus on the CMP iframe when it loads, so that document.activeElement will not change.
=> amp-consent remove cmp iframe focus

.eslintignore, .eslintrc, ads/ads.extern.js, build-system/externs/amp.extern.js, build-system/externs/dompurify.extern.js, build-system/externs/preact.extern.js, third_party/moment/moment.extern.js
Reverts the revert (ampproject/amphtml#26445)
- also fixes the failing tests by running prettier on the newly added preact extern.
=> ♻️ Lint: include externs (round 2)

extensions/amp-script/0.1/amp-script.js, extensions/amp-script/0.1/test/unit/test-amp-script.js
Fixes https://github.com/ampproject/amphtml/issues/24265
=> ♻️ amp-script: emit warning if zero height and width.

extensions/amp-story/1.0/amp-story-desktop-panels.css, extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/amp-story.js
- Moves the code that sets the `--story-page--*` CSS variables to `amp-story-page`
- Leverages the `onMeasureChanged()` runtime method to know when the `amp-story-page` actually gets resized
- Only measures from the first story page, that always gets built because of the prerendering optimizations we have (even with branching)
- `onMeasureChanged()` is called after `buildCallback` but before `layoutCallback`, so the story can't be marked as rendered before the CSS variables are set, as it waits for the first page to be fully loaded. Also works perfectly with prerendering (no jump)
- Fixes a bug where the previous code would sometimes measure the page on viewport resize before the page is actually resized
- Provides a rounded value to use for the `translate` and remove the unwanted border …
=> Fix border around desktop amp-story-pages.

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js, extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
* Start sending the current AMP URL to SwG's analytics logs.  This replaces the canonical URL swg-js now automatically sets in the analytics logs.
=> ✨ Start logging AMP URL on SwG Pages

src/layout.js, test/unit/test-layout.js
=> More user friendly errors in layout.js

extensions/amp-story/1.0/amp-story-desktop-panels.css
TIL, Chrome can add this white border around elements if:
- You use a `scale()` on the element, that ends up in a non integer (float) width. This can be fixed with `perspective(1px);`. Done in this PR
- You use a `translateX()` on the element, which value is a non integer (float). This can be fixed by providing an integer value to `translateX()`. Done in #26449
#16626
=> Add perspective(1px) back to desktop amp-story-pages.

src/multidoc-manager.js
Closes #9871 by logging a warning when the URL arg to `attachShadowDoc` or `attachShadowDocAsStream` is not a string.
=> 🐛Log warning when missing URL while attaching shadow doc

extensions/amp-story/1.0/amp-story-desktop-panels.css
When loading a desktop panels story, the n+1 page isn't positioned until pretty late in the code execution, when we set positioning attributes. That n+1 page flies in the viewport once the position is set.
This PR positions the n+1 page until the final position attributes are set.
[Repro the animation issue](https://stamp-gmajoulet.firebaseapp.com/examples/s20/body-painting/index.html)
=> Position n+1 story desktop page before positioning attributes are set.

src/service/performance-impl.js, test/unit/test-performance.js
**summary**
Fixes: `b/137215986` by emitting `performance.timeOrigin` tick event when the messaging channel is ready.  Technically I could also have added this tick to the contructor since it would be queued until msr, but that would have required updating 23 tests.
=> performance: emit timeOrigin w/ polyfill

tools/experiments/experiments.js
Part of #25205
Tangentially related to #25560
=> ♻️ Change the opt-in cookie values to reflect upcoming CDN changes

build-system/tasks/dist.js
A (very) small part of #25989 . Currently, `files.txt` does not end in a newline. It should, which will allow the build script to append to it without having to worry about adding the newline itself.
=> 🏗 Add terminal newline to files.txt

examples/bind/basic.amp.html, extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/test-amp-list.js, tools/experiments/experiments-config.js
**Summary**
Implements https://github.com/ampproject/amphtml/issues/15647.
Allows an amp-list to initialize off of an SSRed amp-state. Initially I had been worried that this would delay the rendering of `amp-list` until `amp-bind` had finished initialization (ironically this could be slower than the client side fetch would have been). Turns out though, that `amp-state` parsing and `getState` are not blocked on amp-bind's `initializationPromise`, so all is well.
I've gated it on a feature flag, so nobody should be able to use it yet. In a followup PR I'll run performance measurements, create documentation and remove the flag.
cc @jridgewell / @choumx
=> ✨ [amp-list] Introduce "amp-state:" as a usable protocol for the src attribute.

extensions/amp-story/1.0/bookend/amp-story-bookend.js, extensions/amp-story/1.0/bookend/bookend-component.js, extensions/amp-story/1.0/bookend/components/article.js, extensions/amp-story/1.0/bookend/components/bookend-component-interface.js, extensions/amp-story/1.0/bookend/components/cta-link.js, extensions/amp-story/1.0/bookend/components/heading.js, extensions/amp-story/1.0/bookend/components/landscape.js, extensions/amp-story/1.0/bookend/components/portrait.js, extensions/amp-story/1.0/bookend/components/text-box.js, extensions/amp-story/1.0/test/test-amp-story-bookend.js, extensions/amp-story/1.0/utils.js
Closes #26316
Resolves relative URLs specified in the bookend configuration. See linked issue for more details.
* Note: I know we don't like to write code that is only used in tests but this was the best I could do given that Sinon doesn't like stubbing `document.location / window.location` and I've seen other tests do similar things.
=> 🐛 Rewrite relative urls in the bookend

test/unit/test-runtime.js, testing/fake-dom.js
While investigating test failures for #26447, I noticed that I would get a different number of tests each time when running `test-runtime` locally?!?
After investigation it appears many (all?) of the tests using `fakeWin` in this file would throw an error when the runtime eventually calls `getComputedStyle`. This PR adds this method to the fake win.
I think this was causing all sorts of weird behaviors, and likely that many tests were unintentionally being skipped due to the test runner borking. When I added the method it surfaced two obvious errors that must not have been run all this time :(
~~Also might be opening a can of worms here by exposing other uncaught errors in other test files that may be exposed after introduction of this method on `fakeWin`. Going to let travis run and see …
=> 🐛Add computed styles to fake win

build-system/compile/sources.js, build-system/tasks/presubmit-checks.js, examples/amp-story/embed.html, package.json, src/OWNERS, src/amp-story-embed-manager.js, src/amp-story-embed.js, test/unit/test-amp-story-embed.js, yarn.lock
Partial for #24539 
This PR adds:
* Messaging that is needed for communication between the viewer and the STAMPs.
* Adds an intersection observer that calls `layoutCallback()` with a fallback that uses a scroll listener.
Things I'm not sure about:
* Since I'm installing a new package (`@ampproject/viewer-messaging`), yarn.lock has been updated, but I don't know if that should be in my local gitignore or if it should actually be checked in.
Issue tracker #26308
=> ✨ [amp-story-embed] Adds messaging, implements build/layoutcallbacks

third_party/subscriptions-project/aes_gcm.js
Checks if browser is IE before accessing self.crypto as this is causing an issue with "crypto not found" on IE.
=> 🐛 Add check for isIE before accessing self.crypto

extensions/amp-a4a/amp-a4a-format.md
Resolves #25773: add amp-selector to the list of allowed extensions.
=> Update amp-a4a-format.md to include amp-selector.

src/inabox/inabox-viewport.js
The leak is caused by InaboxViewportImpl not disconnecting the binding on visibilityChange=hidden, so when the inabox iframe is cleared the reference to it remains in the top window. Readd code for handling the event, with a workaround for Safari not firing it on unload.
=> Fix memory leak in inabox-viewport-friendly introduced by inabox-lite.

extensions/amp-story/1.0/amp-story-page.js
Some publishers configure the page attachment with a single space character as the `data-cta-text`, eg: `data-cta-text=" "` which renders a completely empty "Swipe up" label.
See: https://aollco.com/collection/1708734
`trim()` removes all the empty characters (spaces) listed here http://emptycharacter.com/, very likely there are other ways to do it but this fixes the most obvious ones.
=> Trim page attachment cta text.

.github/ISSUE_TEMPLATE/cherry_pick_template.md
This PR updates the template. Labels have already been updated.
Partial fix for #25560
=> 🏗 Update Cherry-pick template with new release names

build-system/tasks/dist.js
seems we removed the flag recently. i'll follow this up by running integration tests against `--esm` in a follow up PR
=> pass in esm flag when transfering src to temp dir

test/unit/test-performance.js
**summary**
- Configured `lolex` to simulate `Date.now()` to begin at 100 instead of at 0. When it was 0, it became impossible to test the difference between relative and absolute time (value vs. delta)
- Rewrite a test that was checking for relative time to actually check for absolute time. This was either a bug in the test or is currently a bug in our code. @erwinmombay, can you help me figure out the intention of the test named: "should add default optional relative start time on the"
=> ♻️ test-performance.js: differentiate between relative and absolute time.

extensions/amp-story/1.0/amp-story-vertical.css
Otherwise the padding leads to the text going over the edge of the right side of the screen.
Fixes #26528
=> 🖍 Use auto instead of 100% as width of story description.

extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js, extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
=> 🐛 amp-auto-lightbox: Ignore unlaid out elements

extensions/amp-brid-player/0.1/amp-brid-player.js
This is a fix for current behavior where getCurrentTime() always returns 0, while getDuration() always returns 1.
=> Adding support for time/duration (amp-brid-player extension)

build-system/tasks/css.js, css/amp-story-player.css, examples/amp-story/player.html, src/amp-story-player.js
* Sets up basic css for the `amp-story-player` which will set a placeholder specified by the publisher (`--story-player-poster`).
* In the case no poster is specified, falls back to a spinner.
* Finally hides the above styles when the story is loaded.
Partial for #24539 #26308
=> 🖍 [amp-story-player] Adds css for pre-fetch experience

src/service/url-replacements-impl.js
#26210
Seems like there are is a good amount of uses of AMP_STATE. We should not move it out of url-replacements
=> Remove expected error

src/service/viewport/viewport-impl.js, test/unit/test-viewport.js
Fixes bug where scrollTop is not remeasured when a shadow doc becomes visible, preventing resource from loading until the user scolls (#11983)
=> 🐛Force scrollTop to be remeasured on shadow doc visibility change

src/service/performance-impl.js
- places all of `tick()`'s branched logic in a single place near the top, instead of being spread throughout.
- only sends `value` or `delta`, instead of both.
=> ♻️ peformance-impl: simplify tick()

contributing/getting-started-e2e.md
For newcomers, they likely want the JDK otherwise they cannot build the project.
=>  📖 Download the JDK not JRE

extensions/amp-story/1.0/amp-story-share-menu.css, extensions/amp-story/1.0/amp-story-share.css
Fixing the sharing layout to display labels that are up to 2 lines on mobile, desktop, and within the bookend.
Fixes #26602
=> Fix sharing layout when the label is two lines long.

build-system/tasks/css.js, css/OWNERS, css/amp-story-player-iframe.css, css/amp-story-player.css, src/amp-story-player.js
* Create a separate css file for iframe as suggested in https://github.com/ampproject/amphtml/pull/26557#discussion_r373217335 by @alanorozco
* Updates OWNERS so that we have write permissions for `amp-story-player-*.css` files.
Partial for #24539 #26308
=> 🖍 [amp-story-player] Extract iframe css to different file

examples/amp-story/quiz.html, extensions/amp-story/1.0/amp-story-quiz.css, extensions/amp-story/1.0/amp-story-quiz.js, extensions/amp-story/1.0/test/test-amp-story-quiz.js
Adds percentage display to <amp-story-quiz> component if data is available. These percentages are rounded to the nearest integer while preserving ties, general ordering, and summation to 100 (if possible).
Demo for percentage calculation can be found [here](https://codepen.io/jackbsteinberg/pen/YzPBzao)
Demo for percentage display can be found [here](https://codepen.io/jackbsteinberg/pen/vYEaoNj)
Adds work related to tracking issue #25615
=> ✨Add percentage display to <amp-story-quiz>

ads/_config.js, ads/yahoo.js
Minor change to the path for the script loaded by `yahoo` amp-ad plugin.
=> Updating path to Yahoo ad script 

test/unit/test-shadow-embed.js
I was debugging test failures in #26447 and found that if I ran `test-runtime.js` directly it would work, but if I ran `test-shadow-embed.js` with it, it would always fail :(
Turns out in some of our tests, we manually set the streaming supported flag through `setShadowDomStreamingSupportedForTesting`. This value gets cached here https://github.com/ampproject/amphtml/blob/eccff2da8522b573c7c0e7e369d1ec7c03e8b085/src/shadow-embed.js#L328-L331
These tests would reset this flag in a beforeEach block, but this would not clean up this state for the last test in the section, causing hard to track test failures.
Moves the resetting of this state to an afterEach block instead, which seems to solve the problem.
=> Fix shadow test state pollution

extensions/amp-iframe/0.1/amp-iframe.js, extensions/amp-iframe/0.1/test/test-amp-iframe.js, test/fixtures/served/iframe.html
Fixes #22714.
Pym.js supports the client window sending several types of messages, including:
* `height`
* `width`
* `parentPositionInfo`
* `navigateTo`
* `scrollToChildPos`
The only two messages that seem relevant in an AMP context are `width` and `height`, as they map to the [`embed-size` message](https://amp.dev/documentation/components/amp-iframe/?format=websites#iframe-resizing) that AMP is currently looking for.
[Demo video](https://youtu.be/sL7sdsBjNIQ) (YouTube): 
> [![Demo video](http://i.ytimg.com/vi/sL7sdsBjNIQ/maxresdefault.jpg)](https://youtu.be/sL7sdsBjNIQ)
The code can be tested using this Glitch: https://amp-iframe-pymjs-resizable.glitch.me/
=> ✨Add amp-iframe support for Pym.js width and height resize messages

extensions/amp-video-iframe/0.1/amp-video-iframe.js, extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js, extensions/amp-video-iframe/amp-video-iframe.md
Adds as query parameters for both `src` and `poster`.
=> ✨ Support data-param-* in amp-video-iframe

src/multidoc-manager.js, src/service/ampdoc-impl.js, test/unit/test-ampdoc.js, test/unit/test-runtime.js
- Add `getMetaByName` to `AmpDoc` to get the `content` value from a `<meta name=... content=...>` element. Override in `AmpShadowDoc` to perform the lookup in a name/content pair dictionary.
- Add `setMetaByName` to `AmpDoc` (only implemented in `AmpDocShadow`) to store meta name/content values in a variable. This enables retention of information stored in `<meta name=... content=...>` tags since it would be invalid HTML to copy them into the `ShadowRoot` where there is no `<head>` under which they could reside.
=> ampdoc: Add get/setMetaByName methods

extensions/amp-story/1.0/_locales/en.js, extensions/amp-story/1.0/amp-story-quiz.js, extensions/amp-story/1.0/test/test-amp-story-quiz.js, src/localized-strings.js
Adds i18n support for the answer choice options (e.g. A/B/C/D) in the <amp-story-quiz>.
Adds work related to tracking issue #25615
=> 🌐Add i18n for <amp-story-quiz> answer choice options

extensions/amp-subscriptions/0.1/local-subscription-platform-base.js, extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
To fix an issue with click handling in iOS 12 and lower (#25754), listen to both the root node and, if it's defined, its body property as well.
=> 🐛 amp-subscriptions: Fixes click event delegation for iOS 12 and lower

extensions/amp-story/1.0/page-advancement.js
Fix advancementMode variables for time based advancements. The advancement was set on `Advancement.start()` which is called when the page starts playing, rather than on `Advancement.onAdvance()`.
Fixes #26579
=> Fix advancementMode variables for time based advancements.

extensions/amp-story/1.0/media-pool.md
Don't know how this didn't get copied with everything else.....
Shows up as new, but it's just a word-for-word copy of https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/0.1/media-pool.md
=> 📖 Migrate mediapool overview doc to 1.0

test/unit/test-ampdoc.js
Restores tests that were skipped due to deprecated createShadowRoot API in Chrome 80
=> ✅ Fix shadow tests broken due to deprecated createShadowRoot API

spec/amp-html-format.md, validator/engine/validator_test.js, validator/java/src/main/proto/validator.proto, validator/validator-main.protoascii, validator/validator.pb.go, validator/validator.proto
Increase allowed css byte_limit in validation. This PR implements #26466
Please note: Haven't made changes in this section of the codebase before, a more thorough review is appreciated.
**Edit**: Incorrect # reference for implementation.
=> 🖍 Increase CSS byte limit from 50000 bytes to 75000 bytes

ads/google/a4a/shared/test/test-url-builder.js, extensions/amp-a4a/0.1/real-time-config-manager.js, extensions/amp-a4a/0.1/test/test-real-time-config-manager.js, extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js, extensions/amp-ad/0.1/test/test-amp-ad-custom.js, extensions/amp-ad/0.1/test/test-amp-ad.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js, extensions/amp-analytics/0.1/test/test-config-new.js, extensions/amp-analytics/0.1/test/test-config.js, extensions/amp-analytics/0.1/test/test-cookie-writer.js, extensions/amp-analytics/0.1/test/test-linker-manager.js, extensions/amp-analytics/0.1/test/test-requests.js
To avoid any inadvertently sending of a request to a real domain.
ICANN guarantees not to register `.test` domains so they can safely be used.
=> ✅Change domains on tests for ads/analytics

build-system/compile/compile.js, build-system/tasks/dist.js, build-system/tasks/extension-helpers.js, build-system/tasks/helpers.js, examples/everything.amp.esm.html, package.json, yarn.lock
when running `gulp dist --esm` we need to differentiate the modern js binaries from old generated binaries. We will suffix the file with `.mjs`. The output has not been changed
The solution in this pR is not optimal as it checks calls `maybeToEsmName` a few many times. This can be optimized by plumbing through the option throughout all the calls but that will take me a bit more time which I'll do in a follow up PR.
i'll also follow up with a PR to update a single example page with the mjs example. trying to do all of examples dynamically is more difficult since we only do string manipulation (we regex the url strings) while the mjs changes needs dom manipulation (needs to append multiple script tags and add attributes etc)
=> make extensions end in mjs file extension type

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, src/friendly-iframe-embed.js, tools/experiments/experiments-config.js
Remove experiment related code and release the feature.
closes #22418
=> Enable a4a friendly iframe css splitting for prod

extensions/amp-access-scroll/0.1/amp-access-scroll.css, extensions/amp-access-scroll/0.1/scroll-bar.js
Because of upcoming design enhancements to the bottom bar shown in the iframe with amp-access-scroll, it is necessary to remove the placeholder so that it does not conflict with the content that gets loaded subsequently in the iframe.
This PR removes the html and css associated with rendering the placeholder.
cc @kushal @dbow
=> 🖍 Remove placeholder on amp-access-scroll

extensions/amp-access/0.1/amp-access-server-jwt.js, extensions/amp-access/0.1/amp-access-server.js
Read `meta[name="i-amphtml-access-state"]` using method supported by
`AmpDocShadow` as well as other `AmpDoc` subtypes.
=> amp-access: Support i-amphtml-access-state lookup in AmpDocShadow

extensions/amp-inline-gallery/0.1/amp-inline-gallery.js, extensions/amp-inline-gallery/0.1/test/validator-amp-inline-gallery-pagination.html, extensions/amp-inline-gallery/0.1/test/validator-amp-inline-gallery-pagination.out, extensions/amp-inline-gallery/0.1/test/validator-amp-inline-gallery-thumbnails.html, extensions/amp-inline-gallery/0.1/test/validator-amp-inline-gallery-thumbnails.out, extensions/amp-inline-gallery/amp-inline-gallery.md, extensions/amp-inline-gallery/validator-amp-inline-gallery.protoascii
**Unchanged** clone of #26109, which had to be closed due to Github user email change/CLA issues.
- Add docs for amp-inline-gallery elements and linking to amp-base-carousel for its usage.
- Add validation rules for amp-inline-gallery elements.
- Fix selector for finding the amp-base-carousel, when it is a direct child of the amp-inline-gallery.
=> ✨amp-inline-gallery docs and validation rules

extensions/amp-analytics/0.1/linker-manager.js, src/service/cid-impl.js
- Read `meta[name="amp-google-client-id-api"]` using method supported by
`AmpDocShadow` as well as other `AmpDoc` subtypes.
- Tag `<body>` with `i-amphtml-linker-created` in `AmpDocShadow` since `<meta>`
element does not exist.
=> amp-analytics: Support amp-google-client-id-api lookup in AmpDocShadow

extensions/amp-consent/amp-consent.md
=> amp-consent uiConfig and captions documentation

extensions/amp-subscriptions/0.1/local-subscription-platform-base.js, extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
Stopping the propagation of `click` events broke the `amp-bind` extension. This PR uses a new method to ensure `click` events are only handled once by the `amp-subscriptions` extension. Basically, an additional property, specific to `amp-subscriptions`, is added to the event when it is first handled, and the handler bails if it is present on a subsequent call.
I plan to test this PR across a variety of devices/browsers using the PR deploy tool described here:
https://github.com/ampproject/amp-github-apps/blob/master/pr-deploy/README.md
=> 🐛 Subscriptions: Stops stopping propagation of click events

examples/amp-story/player.html, extensions/amp-story/1.0/amp-story.js, src/amp-story-player.js
=> ✨[amp-story-player] Install viewer integration script when inside the player

validator/chromeextension/bower.json, validator/chromeextension/popup-validator.html
A simple solution using CE v0 polyfill that fixes #26712 for Chrome 80+.
=> 🐛 Fix validator Chrome extension for Chrome 80+

build-system/externs/amp.extern.js, test/fixtures/served/shadow.html, test/integration/test-shadow-amp.js, testing/test-helper.js
Adds basic integration tests that show attaching a shadow AMP document and laying out an `<amp-img>` component. Closes #5580
=> ✅ Add integration for shadow AMP v0.js

extensions/amp-addthis/0.1/amp-addthis.js, extensions/amp-addthis/0.1/test/test-amp-addthis.js
Adds `?_amp_=VERSION` query param to force-bust old, broken versions of document when cached (origin has overly long cache age of 999 days, workaround for #24848)
@taojing10
@dmvjs
@pjcunnin
@matthinegardner
max-age should be changed on server :)
=> 🐛 Force bust cached document for amp-addthis

validator/chromeextension/manifest.json
Update AMP Validator Chrome Extenion's version number and remove unnecessary key file.
=> Bump version number, remove key

validator/validator-main.protoascii
When analyzing WordPress themes for compatibility, I came across links to RSS comments feed like:
```html
<a
href="https://example.com/foo/feed/" 
title="Comments RSS" 
rel="alternate"
type="application/rss+xml"
>Comments Feed</a>
```
This seems like it should be allowed.
Related: https://github.com/ampproject/amphtml/pull/26362
=> ✨ Allow a[type=application/rss+xml] in validator spec

validator/validator-main.protoascii
At one time, the HTML5 spec [included](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-time-element.html) a `pubdate` attribute on the `time` element. While ultimately the attribute was [removed](http://html5doctor.com/time-and-data-element/) from the spec, it gained usage in the WordPress world. Specifically, on WordPress.com there are 72 themes that use this attribute. On the WordPress.org theme directory there are at least 139 themes using `time[pubdate]`.
Even though this semantic attribute is obsolete, it seems justifiable to allow it.
=> ✨ Allow pubdate attribute on time element

validator/validator-main.protoascii
I came across a WordPress theme that was using the [`feed` URI scheme](https://en.wikipedia.org/wiki/Feed_URI_scheme). The WordPress AMP plugin removed the link because this protocol is not allowed. However, I believe it should be. Clicking such `feed` links on Mac OS results in the Apple News app being opened:
Example:
```html
<a href="feed:https://weston.ruter.net/feed/">RSS</a>
```
=> ✨ Add 'feed' to allowed protocols for links

.eslintrc, build-system/eslint-rules/no-arrow-on-register-functions.js, extensions/amp-geo/0.1/amp-geo.js, extensions/amp-next-page/0.1/amp-next-page.js, extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
in the module build this errors out because arrow functions are not `newable`
=> Do not allow arrow functions as the "factory" function for registerServiceDorDoc

validator/gulpjs/package.json, validator/gulpjs/test/validate.js
We should update the AMP validator dependency to 1.30.0 as well.
=> Update validator version & fix tests

extensions/amp-script/0.1/amp-script.js, extensions/amp-script/0.1/test/unit/test-amp-script.js
🐛 Bug fix: Enable `text/javascript` content type for scripts loaded via `amp-script`.
Addresses https://github.com/ampproject/amphtml/issues/26259.
=> Enable text/javascript header type.

extensions/amp-story/amp-story.md
Fixes #26783
The page https://amp.dev/documentation/components/amp-story/#amp-story-format causes an overflow on mobile devices, since the image https://github.com/ampproject/docs/raw/master/assets/img/docs/amp-story-tag-hierarchy.png is set to have a `fixed` layout, but is too wide for common mobile form factors.
🐛 Bug fix
📖 Documentation
=> Make image responsive

extensions/amp-autocomplete/0.1/amp-autocomplete.js, extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
Currently, if the `query` attribute is specified, existing query parameters in the
source url are replaced with the specified value.
For example, if the `src` is set to `https://example.com/?param=1` and the `query` attribute is set to `q`, then typing `abc` in the input field will attempt to load the suggestions from
```
https://example.com/?q=abc
```
instead of
```
https://example.com/?param=1&q=abc
```
This PR, if merged, will preserve any existing parameters and append the the query value instead of replacing it.
Fixes #26522
Ping: @caroqliu
=> 🐛amp-autocomplete: preserve existing query parameters. Fixes #26522

src/service/resources-interface.js
These new methods are only supposed to be used in the framework (vs extension), so it makes sense to make them visible only in package.
=> ♻️Move new methods in resources service to package visibility

builtins/amp-pixel.js, extensions/amp-analytics/0.1/transport.js, src/pixel.js
=> 🐛Check for window null before creating tracking pixel

examples/pwa-multidoc-loader.html
Provide a simple tool for developers to test their AMP documents...
1. in a PWA
2. in multidoc mode in a PWA
=> Add PWA multidoc loader to examples

ads/google/a4a/test/test-utils.js, build-system/server/amp4test.js, build-system/server/app.js, build-system/tasks/presubmit-checks.js, extensions/amp-ad-network-fake-impl/0.1/test/test-amp-ad-network-fake-impl.js, extensions/amp-ad-network-fake-impl/0.1/test/test-external-reorder-head-transformer.js, extensions/amp-analytics/0.1/test/test-iframe-transport-message-queue.js, extensions/amp-analytics/0.1/test/test-iframe-transport.js, extensions/amp-analytics/0.1/test/test-resource-timing.js, extensions/amp-analytics/0.1/test/test-transport.js, extensions/amp-analytics/0.1/test/test-variables.js, extensions/amp-analytics/0.1/test/test-visibility-manager.js, extensions/amp-consent/0.1/test/test-consent-config.js, test/unit/test-extension-analytics.js, test/unit/test-friendly-iframe-embed.js
To prevent requests from being sent.
=> ✅Another set of example.com change

build-system/server/app.js
Resolve error "TypeError: res is not a function"
=> build-system: Fix autocomplete error response

build-system/tasks/build.js, build-system/tasks/integration.js, build-system/tasks/process-3p-github-pr.js, gulpfile.js
Developers have frequently run into problems due to incorrect flag usage, where the recommended usage is not always obvious.
This PR checks for valid flag usage during the invocation of each `gulp` task, and prints a list of valid flags when invalid usage is detected.
=> 🏗 Ensure valid flag usage for `gulp` tasks

build-system/tasks/dist.js
Adds missing flags, since release automation runs `gulp dist --type canary --noconfig --esm`.
=> 🐛 Add gulp dist flags

extensions/amp-story-auto-ads/0.1/test-e2e/test-amp-story-auto-ads-fullbleed.js, extensions/amp-story-auto-ads/0.1/test-e2e/test-amp-story-auto-ads.js, extensions/amp-story/1.0/amp-story-page.js
Setting the CSS variables in the `html` tag `style` attribute is risky as anyone can override it. We changed the heuristics  in https://github.com/ampproject/amphtml/pull/26449 and now the variables get overwritten in some conditions, as the AMP runtime sets some styles on the `html` tag as well. It looks like a race condition though, but does happen enough to repro easily.
The fix consists in creating a `<style>` tag that's added to the `<head>` of the story document and can't be overwritten.
Fixes #26844
=> Fix story page sizing variables.

src/OWNERS, src/amp-story-player-iframe-pool.js, src/amp-story-player.js, test/unit/test-amp-story-player.js
=> ✨[amp-story-player] Adds navigation logic

examples/amp-story/ampconf.html, examples/visual-tests/amp-story/amp-story-bot-rendering.html, extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/amp-story-vertical.css, extensions/amp-story/1.0/semantic-render.js, extensions/amp-story/1.0/test/test-semantic-render.js
- Introduces a new file for "semantic rendering" to factor out the
related code into its own place.
- Render WebVTT and TTML based captions as paragraphs into the vertical document.
- Fixes a bug where text could still be white on white due to CSS inheritance.
- Updated visual tests with example for captions and video alt/title attribute.
=> ✨Render captions in the vertical render mode of stories

extensions/amp-bind/0.1/bind-impl.js, src/service/url-replacements-impl.js
- Allow returning null from `Bind.getStateValue()` so that values `null`
and `undefined` are not cast to strings "null" and "undefined"
- Set `AMP_STATE URL` replacement to substitute an empty string if
`Bind.getStateValue()` returns `null`
Fixes #26853
=> amp-bind: getStateValue: Return nullable string

test/integration/test-shadow-amp.js
This is the most common failure cause on `master` today.
```
DESCRIBE => AMP shadow v0
IT => "before each" hook for "should attach shadow AMP document"
✗ Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
IT => "before each" hook for "should attach shadow AMP document"
✗ Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
Safari 11.1.2 (Mac OS X 10.13.6): Executed 91 of 462 (1 FAILED) (skipped 371) (4 mins 10.788 secs / 1 min 37.474 secs)
Safari 12.1.1 (Mac OS X 10.13.6): Executed 91 of 462 (1 FAILED) (skipped 371) (4 mins 11.602 secs / 1 min 37.873 secs)
```
Related to #26863
=> ✅ Skip flaky shadow integration test on Safari

test/unit/test-ampdoc.js
- Arguments to describe() were incorrect.
- Expected result to explicit params tests was incorrect.
Fixes #26830
=> ampdoc: Fix params unit test

extensions/amp-story/1.0/amp-story-page.js
We found a bug in the AMP runtime that causes `onMeasuredChange` to sometimes not be called https://github.com/ampproject/amphtml/issues/26866
This PR is a followup fix for https://github.com/ampproject/amphtml/issues/26844, moving away from `onMeasuredChange` until it is fixed.
=> Replacing onMeasuredChange with onLayoutCallback.

test/integration/test-shadow-amp.js
This is the most common failure cause on `master` today.
```
DESCRIBE => AMP shadow v0
IT => "before each" hook for "should layout amp-img component in shadow AMP document"
✗ Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
Safari 11.1.2 (Mac OS X 10.13.6): Executed 91 of 462 (1 FAILED) (skipped 371) (3 mins 52.475 secs / 1 min 30.952 secs)
```
Related to #26863
=> ✅ Skip another flaky shadow integration test on Safari

extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js
Resolve the following unit test failure:
```
DESCRIBE => amp-sticky-ad 1.0 version
DESCRIBE =>  
DESCRIBE => with unvalid child 1.0
IT => should not build when child is not ad
✗ Error: Uncaught Error: The element did not specify a layout attribute. Check https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/control_layout and the respective element documentation for details.​​​ (/home/travis/build/ampproject/amphtml/src/log.js:436:7 <- /tmp/e37c3a9eb37e0c201b3e74053a0d4391.browserify.js:75967)
at Context.<anonymous> (home/travis/build/ampproject/amphtml/extensions/amp-sticky-ad/1.0/test/test-amp-sticky-ad.js:296:21)
```
=> amp-sticky-ad: Fix unit test

css/OWNERS, src/OWNERS
Including the curly braces for a single file pattern (not multiple options separated by a comma) was resulting in an incorrect expansion
=> 🐛 Update owners file to correct syntax

extensions/amp-access-scroll/0.1/amp-access-scroll.css, extensions/amp-access-scroll/0.1/amp-access-scroll.js, extensions/amp-access-scroll/0.1/read-depth-tracker.js, extensions/amp-access-scroll/0.1/scroll-bar.js, extensions/amp-access-scroll/0.1/scroll-component.js, extensions/amp-access-scroll/0.1/scroll-impl.js, extensions/amp-access-scroll/0.1/scroll-protocol.js, extensions/amp-access-scroll/0.1/scroll-relay.js, extensions/amp-access-scroll/0.1/scroll-sheet.js
This PR
- adds a protocol version query param to requests made from amp-access-scroll for compatibility
- adds a "holdback" flag and styles to prevent mismatched rendeirng with new layout
- renames ScrollAudio to ScrollSheet
- adds ability to dynamically size horizontal layout for ScrollComponents. Special care
was taken to ensure these properties cannot interrupt vertical browser layout;
only width, left, and right are allowed.
Dynamic sizing is necessary to pervent invisible iframes being drawn over usable
parts of the underlying page, which would cause UX and accessibility problems in
certain layout scenarios. Dynamic sizing solves this by shrinking the iframe to fit
the size neccessary to fit the rendered controls.
=> ✨ Update amp-access-scroll

src/service/action-impl.js, test/unit/test-action.js
New `getMetaByName` method supports retrieving meta content values in
shadow docs as well.
=> amp-action: Support whitelist lookup in AmpDocShadow

test/unit/test-dom.js
```
ERROR: '[DOM] Failed to open url on target:  _blank Error: intentional'
The test "DOM   openWindowDialog should retry on first exception" resulted in a call to console.error. (See above line.)
ERROR: 'The element did not specify a layout attribute. Check https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layo …
```
=> dom: Minor test improvements

test/unit/test-amp-pixel.js
```
ERROR: 'The <amp-pixel> src attribute must start with "https://" or "//". Invalid value: http://pubads.g.doubleclick.net/activity;dc_iu=1/abc;ord=2'
The test "amp-pixel   should disallow http URLs" resulted in a call to console.error. (See above line.)
ERROR: 'The <amp-pixel> src attribute must start with "https://" or "//". …
```
=> amp-pixel: Minor test improvements

test/unit/test-custom-element.js
```
ERROR: 'Error: upgrade failed'
The test "CustomElement   CustomElement Element - re-upgrade with a failed promised" resulted in a call to console.error. (See above line.)
ERROR: 'intentional [object HTMLElement]'
The test "CustomElement   CustomElement should anticipate build errors" resulted in a call to console.error. (See …
```
=> custom-element: Minor test improvements

build-system/tasks/karma.conf.js
When Karma runs our integration tests in a browser, it can take a while for results to be reported. This is increasingly relevant on slow browsers as the number of integration tests in our suite grows. Right now, the suite (including setup and teardown) does not always finish during this window, especially when there is a high Sauce load from many parallel Travis builds.
It impacts Chrome the most, since we execute many of our tests on Chrome (versus IE 11, which includes only a single integration test). 
This PR ups the activity timeout from 2 minutes to 5 minutes, which should resolve the majority of tests that currently fail due to message timeout errors.
=> 🏗 Increase karma browser activity timeout to 5min

extensions/amp-access/0.1/test/test-amp-access.js, src/service/performance-impl.js, test/unit/test-performance.js
Fixes https://github.com/ampproject/amphtml/issues/16042
TODO: figure out why it was reverted last time (https://github.com/ampproject/amphtml/pull/16227).
Answer: `performance.now()` is relative to `timeOrigin` whereas `Date.now()` is relative to epoch.
=> performance-impl: use performance.now() over Date.now()

test/unit/test-ad-cid.js
```
ERROR: '[AD-CID] Error: nope'
The test "ad-cid   should return undefined on failed CID" resulted in a call to console.error. (See above line.)
```
=> ad-cid: Minor test improvement

test/unit/test-cache-cid-api.js
```
ERROR: '[CacheCidApi] Error: fetchCidTimeout​​​'
The test "cacheCidApi   getScopedCid should fail if the request times out" resulted in a call to console.error. (See above line.)
```
=> cache-cid-api: Minor test improvement

test/unit/test-cid-api.js
```
ERROR: '[GoogleCidApi] '
The test "test-cid-api   should return null if API rejects" resulted in a call to console.error. (See above line.)
```
=> cid-api: Minor test improvement

test/unit/test-cid.js
```
ERROR: 'The test "cid   isScopeOptedIn should not work if vendor not whitelisted" contains an "allowConsoleError" block that didn't result in a call to console.error.'
```
=> cid: Minor test improvement

test/unit/test-extensions.js
```
ERROR: '[extensions] unknown extension for  e1'
The test "Extensions   registerExtension   should add element out of registration" resulted in a call to console.error. (See above line.)
ERROR: '[extensions] unknown extension for  '
The test "Extensions   registerExtension   should add element out of registration" resulted in …
```
=> extensions: Minor test improvements

test/unit/test-sanitizer.js
```
ERROR: 'The test "Caja-based should sanitize based on AMP doc format type should allow for input type file and password" contains an "allowConsoleError" block that didn't result in a call to console.error.'
ERROR: 'The test "Caja-based should sanitize based on AMP doc format type should only allow whitelisted AMP elements in AMP4EMAIL" contains an "allowConsoleError" block that didn't result in a call to console.error.'
```
=> sanitizer: Minor test improvements

test/unit/test-storage.js
```
ERROR: '[Storage] Failed to load store:  intentional'
The test "Storage   Storage should recover from binding failure" resulted in a call to console.error. (See above line.)
ERROR: '[Storage] Failed to load store:  InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly …
```
=> storage: Minor test improvements

test/unit/test-xhr-fetch-polyfill.js
```
ERROR: 'Only one of  GET, POST is currently allowed. Got PUT'
The test "fetch   fetch method should not allow PUT method" resulted in a call to console.error. (See above line.)
ERROR: 'Only one of  GET, POST is currently allowed. Got PATCH'
The test "fetch   fetch method should not allow PATCH method" resulted in a call to …
```
=> xhr-fetch-polyfill: Minor test improvements

test/unit/test-xhr.js
```
ERROR: 'Object expected:  '
The test "XHR interceptor should be rejected when response undefined" resulted in a call to console.error. (See above line.)
ERROR: 'Object expected:  '
The test "XHR interceptor should be rejected when response null" resulted in a call to console.error. (See above line.)
⤷ If the error is not …
```
=> xhr: Minor test improvements

test/unit/test-error.js
```
ERROR: 'Error: error'
The test "installErrorReporting   should report the normal promise rejection" resulted in a call to console.error. (See above line.)
ERROR: 'Error: rejected promise [object Object]'
The test "installErrorReporting   should allow null errors" resulted in a call to console.error. (See above line.)
⤷ If …
```
=> error: Minor test improvements

test/unit/test-service.js
```
ERROR: '[SERVICE] failed to dispose service b intentional'
The test "service ampdoc singletons should dispose disposable services" resulted in a call to console.error. (See above line.)
```
=> service: Minor test improvement

src/amp-events.js, src/custom-element.js, test/integration/test-amp-img.js, testing/iframe.js
The 'should respect media queries' amp-img integration test fails
intermittently due to a race between setting/getting class
`i-amphtml-hidden-by-media-query` when the window resizes. The race
results because `expect()` is performed immediately after an amp-img
`LOAD_START` event fires without waiting for the other amp-img to fire
its `UNLOAD` event. Remedy this by waiting for both amp-img layout changes
to fire before checking their final classes.
- Add `UNLOAD` event to custom-element test event dispatches
- Fix names of test events `LOAD_START`, `LOAD_END` so that they match the
corresponding signal names
=> integration: Improve amp-img test reliability

extensions/amp-video-docking/0.1/amp-video-docking.js, extensions/amp-video-docking/0.1/def.js, extensions/amp-video-docking/0.1/math.js, extensions/amp-video-docking/0.1/test/test-amp-video-docking.js, extensions/amp-video-docking/0.1/viewport-rect.js
- Simplifies types/style.
- Removes vertical axis edge logic (it was incomplete and not exposed to user.)
- Extracts utilities for conciseness (particularly in `math.js`).
- Consolidates element slot vs. dynamic corner behavior with a standard rectangle concept.
=> ♻️ Refactor docking to use rects for targets

build-system/tasks/karma.conf.js
Reverts ampproject/amphtml#26887
There's a bigger bug to be fixed; beta browser runs are not being batched. Rolling back until the underlying bug is found
=> Revert "🏗 Increase karma browser activity timeout to 5min"

extensions/amp-3q-player/0.1/amp-3q-player.js, extensions/amp-3q-player/0.1/test/test-amp-3q-player.js, extensions/amp-brightcove/0.1/amp-brightcove.js, extensions/amp-delight-player/0.1/amp-delight-player.js, extensions/amp-minute-media-player/0.1/amp-minute-media-player.js, extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js, extensions/amp-powr-player/0.1/amp-powr-player.js, extensions/amp-redbull-player/0.1/amp-redbull-player.js, extensions/amp-video-iframe/0.1/amp-video-iframe.js, extensions/amp-vimeo/0.1/amp-vimeo.js, extensions/amp-wistia-player/0.1/amp-wistia-player.js
`tryParseJson` was [modified to return `null`](https://github.com/ampproject/amphtml/blame/master/src/json.js#L131), this updates checks for all video players.
Fixes #26895
=> 🐛 Check for null on bad video message JSON parses

extensions/amp-analytics/0.1/vendors/webengage.js, extensions/amp-analytics/0.1/vendors/webengage.json
For vendor WebEngage Linker and Cookie configs have been added in order to make sure that the user journey across differently served AMP pages and Non-AMP is synced.
=> ♻️AMP Analytics: Linker and cookie configs added for WebEngage vendor

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js, extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Adds the sendBeacon method to AmpFetcher.  
This method is currently being used by an experiment (internal only).  The signature is required for the next SwG release.  There may be future adjustments to this code.
=> ✨ SwG - Add sendBeacon method to AmpFetcher

extensions/amp-form/amp-form.md
Small thing we missed in #26107
`amp-analytics` is not supported in emails. Also removed `verify-error` from *To render responses with templating:* since (1) it's never actually explained in the text that follows, (2) it's covered elsewhere in the doc.
=> Quick fix for amp-form reference for AMP for Email

extensions/amp-carousel/0.1/base-carousel.js
=> Make amp-carousel always show controls in emails

src/service/url-replacements-impl.js, src/service/variable-source.js, test/unit/test-url-replacements.js
- url: Read `meta[name="amp-link-variable-allowed-origin"]` using method
supported by `AmpDocShadow` as well as other `AmpDoc` subtypes.
- vars: Read `meta[name="amp-allowed-url-macros"]` using method
supported by `AmpDocShadow` as well as other `AmpDoc` subtypes.
=> variable substitutions: Support whitelist lookup in AmpDocShadow

build-system/tasks/validator.js
Fixes #26964
/cc @honeybadgerdontcare
=> Fixes `update_tests` flag on `gulp validator`

css/video-autoplay.css, extensions/amp-audio/0.1/amp-audio.js, extensions/amp-connatix-player/0.1/amp-connatix-player.js, extensions/amp-hulu/0.1/amp-hulu.js, extensions/amp-izlesene/0.1/amp-izlesene.js, extensions/amp-jwplayer/0.1/amp-jwplayer.js, extensions/amp-kaltura-player/0.1/amp-kaltura-player.js, extensions/amp-megaphone/0.1/amp-megaphone.js, extensions/amp-o2-player/0.1/amp-o2-player.js, extensions/amp-reach-player/0.1/amp-reach-player.js, extensions/amp-soundcloud/0.1/amp-soundcloud.js, extensions/amp-springboard-player/0.1/amp-springboard-player.js, src/service/video-manager-impl.js, src/video-interface.js, test/visual-diff/visual-tests
- `.i-amphtml-video-component` is gone, using existing `.i-amphtml-video-interface` instead.
- All media (audio/video) components are now `.i-amphtml-media-component`.
Note: video players that add `.i-amphtml-media-component` independently do NOT implement the `VideoInterface` and therefore do not subscribe to the manager.
=> ♻️ Consolidate players as .i-amphtml-media-component

extensions/amp-script/amp-script.md
Front-load the info about dependency on signed exchanges and/or AMP Packager.
Addresses ampproject/amppackager/#395. /cc @dritter
=> 📖 Clarify when max-age is required

build-system/eslint-rules/no-import.js
Caroline accidentally imported `from 'preact/src'`, and took a bit to figure out what was going wrong. This fix now forbids importing from the `preact/src` sub-paths.
=> 🏗️ Update no-import lint rule to forbid sub-paths

build-system/tasks/dep-check.js, build-system/test-configs/dep-check-config.js
**summary**
We have have a presubmit check called `check-deps` that ensures modules only depend on those that they should. While it does its job well, there is an issue facing it now where unused rule-exceptions are allowed to stay. This means that it is all too easy to have the file grow indefinitely.
This Pull Request adds in the a new type of error for allowlisted entries that are unused. It also removes all the currently unused rule-exceptions.
Interestingly enough, this check can help prevent us from making errors during refactors. Specifically I noticed that our `DOMPurify` code was refactored/moved around but the checks were never updated to the new filepaths.
**question**
~~Who should we bring in to verify that each of these removals from the dep config actually make sense and are …
=> Gulp Dep Check: fail on unused entries

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js, extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Redirects the new SwG "sendBeacon" command through AMP's native interface.
=> 🐛 SwG now uses AMP sendBeacon interface

test/unit/inabox/test-inabox-resources.js
```
ERROR: 'Missing resource prop on  [object HTMLDivElement]'
The test "inabox-resources   add & remove" resulted in a call to console.error. (See above line.)
```
=> inabox-resources: Minor test improvement

test/unit/test-viewport.js
```
ERROR: 'Expected service viewer to be registered'
The test "Viewport   top-level classes should not set singledoc class" resulted in a call to console.error. (See above line.)
```
=> viewport: Minor test improvement

test/unit/test-url-replacements.js
```
ERROR: 'The replacement url has invalid protocol:  javascript://example.com/?r=0.17944693054878424'
The test "UrlReplacements   UrlReplacements should reject javascript protocol" resulted in a call to console.error. (See above line.)
```
=> url-replacements: Minor test improvement

test/unit/test-url-replacements.js, test/unit/test-variable-source.js, test/unit/url-expander/test-expander.js
Cached meta tags feature requires stubbing `AmpDoc.getMeta` to ensure old
(or missing) meta tags are not reused in future tests.
=> 🐛 Fix unit tests broken by #26687

extensions/amp-video-iframe/amp-video-iframe.md, src/video-iframe-integration.js, test/unit/test-video-iframe-integration.js
`jwplayer()` will return the singleton instance, which makes sense as a default for a single iframed video.
Otherwise passed in explicitly like [here](https://glitch.com/edit/#!/amp-video-iframe-jwplayer?path=jwplayer.html).
=> ✨ amp-video-iframe integration: global jwplayer() singleton by default

spec/amp-actions-and-events.md, src/service/video-manager-impl.js
Maintains external sanity, e.g. we can say "to implement any playback actions on `amp-video-iframe` implement the method with its corresponding name".
=> ♻️ Alias video.fullscreen action for symmetry with interface names

test/unit/test-navigation.js
Errors are no longer thrown for:
- Multiple anchor mutators with equal priority
- Navigation to relative URLs
```
ERROR: 'The test "Navigation   non-embed   anchor mutators should throw error if priority is already in use" contains an "allowConsoleError" block that didn't result in a call to console.error.'
ERROR: 'The test "Navigation   non-embed   navigateTo should navigate relative to source url" contains an "allowConsoleError" block that didn't result in a call to console.error.'
```
=> navigation: Minor test improvements

examples/amp-story/quiz.html, extensions/amp-story/1.0/amp-story-quiz.css, extensions/amp-story/1.0/amp-story-quiz.js, extensions/amp-story/1.0/amp-story.css
Adds methods to customize the <amp-story-quiz> element via CSS custom properties for color customizations, or HTML attributes on the element for other customizations. 
Additionally adds support for leaving off the prompt of a quiz, in the case where a publisher wants to present only the quiz options.
* `theme`: controls the theme of the quiz - **`light`**, `dark`
* `chip-corner`: controls the sharpness of the corners on the option chip - **`round`**, `sharp`
* `chip-style`: controls the UI style of the option chips - **`outline`**, `shadow`
* `--accent-color`: controls the accent color of the quiz - default `#005AF0`
* `--prompt-text-color`: controls the color of the prompt text - default `#FFFFFF`
* `--option-text-color`: controls the color of the option text - default `#5F6368`
Adds …
=> ✨ Add customization options to <amp-story-quiz>

extensions/amp-analytics/0.1/test/test-events.js
Changing `function*` to `async` and removing unlisten
=> Improve visibility event tests

validator/testdata/transformed_feature_tests/server_side_rendering.html, validator/testdata/transformed_feature_tests/server_side_rendering.out, validator/validator-main.protoascii
Intrinsic layout validation originally required inline SVG attribute quotes to be escaped via `&quot;`. To reduce char count, this PR changes the behavior to expect single quotes instead. 
This is a breaking change, however, I don't think that this will be an issue as intrinsic layout SSR hasn't been implemented anywhere. If this is a concern, we could change the implementation to support both. 
//cc @jridgewell
=> ssr intrinsic layout: support svg using apostroph

extensions/amp-viewer-integration/0.1/amp-viewer-integration.js
By enabling the `touch` capability, viewers/players will be able to receive touch events from the AMP document even when they don't necessarily support `swiping`.
=> Adds new touch capability to viewer integration

extensions/amp-video-docking/0.1/controls.js, extensions/amp-viqeo-player/0.1/test/test-amp-viqeo-player.js, src/service/video-manager-impl.js, src/video-interface.js, test/integration/test-video-manager.js
Fixes #26980.
- Keeps `isRollingAd` state.
- Consolidates `getEntry(ForVideo|ForElement)_`.
- Rather than keep the manager as an intermediary for `VideoEntry` state, this exposes all state at once and proposes restructuring/moving public methods instead. Exposing all state at once prevents running a linear search thrice when showing controls.
=> 🐛 Maintain ad-rolling state, use to init dock controls

build-system/compile/compile.js, build-system/compile/single-pass.js, build-system/tasks/dist.js
single pass originally had its own `transformPathsToTempDir` which is very similar to `transferSrcsToTempDir` (pretty much a precursor). We need to unify usage so that the temp directory source is the same for single pass as well as the non single pass binaries ran during the single pass build
=> fix single-pass to use `transferSrcsToTempDir`

build-system/tasks/performance/measure-documents.js
**summary**
I recently started taking advantage of the new `gulp performance` task. During its execution, it always emits a message about calling `yarn install`, but then appears to hang until all the measurements are complete. For a single link with 100 runs, this meant 12m without a status update.
This PR adds progress notification to the task. Here is an example of the output:
=> gulp performance: emit status updates

ads/pubmine.js, ads/pubmine.md, test/unit/ads/test-pubmine.js
Updating our amp-ad implementation back-end to appropriately consume consent states passed by amp-consent. Not using `data-block-on-consent` assumes consent, but otherwise only `CONSENT_POLICY_STATE.SUFFICIENT` and `CONSENT_POLICY_STATE.UNKNOWN_NOT_REQUIRED` will pass consent.
=> ✨ Update Pubmine amp-ad to support amp-consent states

extensions/amp-web-push/amp-web-push.md
The `amp-web-push` validator spec component requires the layout of `nodisplay`:
https://github.com/ampproject/amphtml/blob/8dadf0336300daadf91304946d7959635635390e/extensions/amp-web-push/validator-amp-web-push.protoascii#L68-L70
The current example does not validate against this constraint:
This PR fixes the problem.
=> 📖 Fix validation errors in amp-web-push example

extensions/amp-access-scroll/0.1/scroll-bar.js, extensions/amp-access-scroll/0.1/scroll-impl.js
- Updates the "Activate" bar to use the same iframe URL as the normal Scroll user bar (we handle the difference on our end now)
- Sets up a Relay so the "Activate" bar can properly resize itself on demand
- Allows us to release the new Scroll UI begun [in 26810](https://github.com/ampproject/amphtml/pull/26810)
=> ✨amp-access-scroll: Update the activate bar to properly set up relay for resizing

extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js, extensions/amp-story/1.0/test/test-amp-story-viewer-messaging-handler.js
Providing a way to subscribe to document state updates, for viewers/players building features that need to be kept in sync with the story's states.
Feature context and implementation details: #26994
Fixes #26994
=> New onDocumentState viewer messaging.

src/event-helper-listen.js, src/gesture.js, test/unit/test-event-helper.js
This PR improves performance for touchstart / touchmove .
I would like to use passive option to improve scroll / touch event.
see passive listener details: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners
if this pr is applied, we could achieve 💯 on Best Practice pane in Lighthouse.
before: 
after:
solved: https://github.com/ampproject/amphtml/issues/25865
=> 🚀Use { passive: true } on gesture.js to improve touch event performance

extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
Remove Google SafeFrame origin check. Google is experimenting with loading SafeFrame from different domains, which would cause this check to fail. SafeFrame is designed to run arbitrary code so this check isn't helpful from a security perspective.
=> 🐛Remove Google Safeframe origin check

ads/revcontent.js, ads/revcontent.md
Revcontent has support for some verbose stats tracking called sub ids, but they were never implemented into our amp ad code as a supported attribute. This PR adds a parameter for them so that users can pass these along to our ad code and have them track as intended. While it's possible to pass these anyways, this parameter ensures that there are no console errors due to unknown attributes.
=> ✨ Add support for tracking sub ids for revcontent amp ads

extensions/amp-script/amp-script.md
Reflect changes made in https://github.com/ampproject/amphtml/pull/26465, allowing `Content-Type` of `text/javascript` for `amp-script`.
=> 📖 Allow `text/javascript` for amp-script

examples/amp-story/helloworld.html, extensions/amp-story/1.0/amp-story-grid-layer.js, extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/amp-story-store-service.js, extensions/amp-story/1.0/amp-story.css, extensions/amp-story/1.0/test/test-amp-story-grid-layer.js, extensions/amp-story/1.0/test/validator-amp-story-grid-layer-error.html, extensions/amp-story/1.0/test/validator-amp-story-grid-layer-error.out, extensions/amp-story/1.0/test/validator-amp-story-grid-layer.html, extensions/amp-story/1.0/test/validator-amp-story-grid-layer.out, extensions/amp-story/amp-story-grid-layer.md, extensions/amp-story/validator-amp-story.protoascii, src/style.js, test/unit/test-style.js
Fixes #27049
Blocked by: #27145
Let's discuss and if this works I will add the tests, validator rules, and documentation.
The most critical aspect here is `font-size`. Everything else could in theory be calculated via CSS, but font-size is the only outlier. The `font-size` has to be referenceable from the height, or in other words `font-size = X% of height`. So the only real choice here is `X`. I started with `100%`, but then I actually tried `10%` and I liked that a lot better. It's quite natural to use `em` units with that, as well as `%` values. Let me know what you think.
Another nuance: I used two private CSS vars and moved the actual CSS assignments to the private `i-amphtml-story-grid-template-aspect` class. I did this so that it's easy to override any of these values in the user …
=> Aspect ratio format for amp-story-grid-layer

extensions/amp-analytics/0.1/config.js
This should improve cacheablity.
=> 🚀 Disable ampCors for analytics vendors requests

build-system/common/utils.js, build-system/tasks/e2e/index.js, build-system/tasks/performance/index.js, build-system/tasks/visual-diff/index.js
There are now three copies of the code that installs packages on-demand within a `gulp` task subdirectory. This PR consolidates them into a single util function to be used by `gulp e2e|performance|visual-diff`.
**I swear, I tested all three:**
=> 🏗 Standardize on-demand package installation for `gulp` tasks

build-system/pr-check/dist-bundle-size.js, package.json, yarn.lock
Travis dist job is failing but there's no error message.
- Fixes the failure, which is an outdated dependency `caniuse-lite` which is used  by `@babel/preset-env`, `cssnano` and `autoprefixer`.
- Adds error logging to the dist job.
=> 🏗 Log dist error on Travis

extensions/amp-story/1.0/amp-story.js
In the player, stories following the first one that were loaded from origin and that did not explicitly imported the `viewer-integration.js` script were unplayable.
This was caused because we were installing the `viewer-integration.js` script in the `layoutCallback` of `AmpStory`. Since `layoutCallback` is not ran in `prerender` mode, these stories weren't installing the `viewer-integration.js` script. And by the time `layoutCallback` runs when displaying the next story, it is too late because the player's handshake has already timed out.
I didn't catch this before because I was testing with stories loaded from the cache, and since we inject the `viewer-integration.js` script in the cache, it seemed to work fine...
Fix following #26719
=> 🐛 [amp-story-player] Install viewer integration script on buildCallback

extensions/amp-script/0.1/amp-script.js, extensions/amp-script/0.1/test/unit/test-amp-script.js, extensions/amp-script/0.1/test/validator-amp-script.html, extensions/amp-script/0.1/test/validator-amp-script.out, extensions/amp-script/amp-script.md, extensions/amp-script/validator-amp-script.protoascii
- Relaxes requirement that `data-ampdevmode` must be on both root and the amp-script. Now, placing a `data-ampdevmode` on either will do.
- Removes a warning that `development` is outdated and `data-ampdevmode` should be used.
See https://github.com/ampproject/amphtml/issues/26341#issuecomment-594205335
Todo:
=> amp-script: decouple dev modes

extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js
`doubleclickImpl.iframe` is the field where the reference to the iframe is stored. There are four lines that set the incorrect field `doubleclickImpl.iframe_` (with an underscore). Removing these lines doesn't break the tests, so it seems like they aren't needed.
=> 🐛Delete setting of incorrect field "iframe_"

3p/OWNERS, ads/OWNERS, ads/google/OWNERS, extensions/amp-a4a/OWNERS, extensions/amp-ad-custom/OWNERS, extensions/amp-ad-exit/OWNERS, extensions/amp-ad-network-adsense-impl/OWNERS, extensions/amp-ad-network-adzerk-impl/OWNERS, extensions/amp-ad-network-doubleclick-impl/OWNERS, extensions/amp-ad-network-fake-impl/OWNERS, extensions/amp-ad/OWNERS, extensions/amp-beopinion/OWNERS, extensions/amp-consent/OWNERS, extensions/amp-mraid/OWNERS, src/OWNERS, src/inabox/OWNERS
Creating a separate  "GH team" for wg-ads PR reviews, that we can freely change according to members availability.
=> Change OWNER wg-ads to wg-ads-reviewers

build-system/pr-check/remote-tests.js, build-system/tasks/runtime-test/helpers.js
Comparing with https://github.com/ampproject/amphtml/pull/27016 to see batch size impact on Travis running time
=> 🏗️ enable 3-at-a-time batching for all sauce labs tests

extensions/amp-story-education/0.1/amp-story-education.css
- Show education fadeIn
- Tap to advance animation
- Swipe to skip animation: this one animates the `width` and `left` properties to work around the infamous `scaleX()` combined with a `border-radius` issue. It's far from ideal, but pretty hard to do different.
[Mobile only demo](https://stamp-education.firebaseapp.com/examples/s20/body-painting/index.html#cap=education)
cc @hongwei1990 if you want to review the animations!
#27097
=> Story navigation education animations.

src/pixel.js
Context: https://github.com/ampproject/amphtml/issues/23935#issuecomment-598350806
Addresses the [fourth](https://pantheon.corp.google.com/errors/CIzCt9nl8ZL4twE?time=P7D&project=amp-error-reporting) and soon-to-be* [third](https://pantheon.corp.google.com/errors/CIzCt9nl8ZL4twE?time=P7D&project=amp-error-reporting) most frequent unexpected error logged to AMP Error Reporting.
The soon-to-be part is because error volume has skyrocketed due to a very large news publisher updating their site in a way that triggers this race condition all the time. It's only been live for a day or so right now and only on Beta/Experimental, but based on that slice of traffic it's set to outpace almost all other reported errors.
I expect this to eliminate approximately 1 million error reports per week, based …
=> 🐛 Create image pixel in onload event handler of iframe

extensions/amp-video-iframe/0.1/amp-video-iframe.js
This PR addresses the [sixth](https://pantheon.corp.google.com/errors/CJCcoczlpdyaQQ?time=P1D&project=amp-error-reporting) and [seventh](https://pantheon.corp.google.com/errors/CLbMwZ_dlL396gE?time=P1D&project=amp-error-reporting) most frequent unexpected errors logged to AMP Error Reporting.
At issue here is the fact there is a private `readyDeferred_` property in this component which is initialized to `null` at runtime. During `layoutCallback` it's initialized to a new `Deferred`, and the deferred's promise is returned from `layoutCallback` where I'm guessing it's resolved by the runtime or something like that.
Problem is, there is code in `postMessage_` which tries to destructure `readyDeferred` into an object:
```
const {promise} = this.readyDeferred_;
if (!promise) {
return;
}
``` …
=> 🐛 Don't try to assign deferred before checking null

validator/build.py
This supports the option listed in
https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server,
and should be backwards-compatible with traditionally-installed Yarn,
per https://www.npmjs.com/package/npx.
=> 🏗 Run yarn via npx, in the `gulp validator` task.

extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Fixes #27125 
SafeFrame APIs are currently not rebuilt after refresh events, causing them to hold on to stale data (such as iframe and promise ID verification functions). In turn, this means calls to the API by post-initial creatives are effectively dropped.
=> Reconstruct safeframe API upon refreshing.

css/amp-story-player-iframe.css, src/amp-story-player.js, test/unit/test-amp-story-player.js
Adds swiping between stories.
[Demo (mobile only)](https://stamp-demo.firebaseapp.com/examples/amp-story/player.html)
Includes:
* New handlers for `touchstart`, `touchend`, `touchmove` events sent by the AMP doc.
* Tests (plus cleaning previous TODOs)
Does not include:
* RTL support (will come in a follow-up)
* Scroll issue #27184 (swiping on the player will cause a horizontal scroll in the parent page when it has an overflow).
* Main issue is that the touch event is "swallowed" by the iframe, and there's no way to `preventDefault` or `stopPropagation` on it. This can be verified in this [demo](https://codepen.io/wildlyinaccurate/pen/rzBaBE), notice how the touchEvents are logged outside the iframe but not when they're inside.
Closes #26698
Tracker #26308
=> ✨[amp-story-player] Adds swipe-to-next/previous story

.github/ISSUE_TEMPLATE/cherry_pick_template.md
Looked through some recent mini-PMs and found several that could use improvement. 
I think simplifying the template and adding better examples would like to make them more useful and less time consuming to write.
=> Make the mini-postmortem template more mini

extensions/amp-subscriptions-google/0.1/test-e2e/test-amp-subscriptions-google.js
This PR updates the SwG E2E test to check for newly rendering values
Looks like the Scenic SKUs got updated in Play Console, and if they were changed back there it could take 12+ hours to propagate
=> ✅ SwG: Updates E2E expectations to match new values

extensions/amp-date-display/0.2/amp-date-display.js, extensions/amp-timeago/0.2/amp-timeago.js, src/preact/base-element.js
Looks like the latest closure upgrade started DCE'ing our static prop assignments. This is the easiest fix to get them to persist.
=> 🐛 Use quoted properties to prevent Closure's DCE

build-system/test-configs/config.js
The HTML parser is written in C++ and many of these checks shouldn't apply to it.
=> Exclude /validator/htmlparser

spec/amp-html-layout.md, src/custom-element.js, test/unit/test-amp-img.js, test/unit/test-custom-element.js, validator/validator-main.protoascii
This allows specifying the `sizes` on elements without getting the sizing behavior of sizes in AMP (which adds a width based on which media query matches). Addresses #21736
See [discussion doc](https://docs.google.com/document/d/1qRF38BwZPfgIdNfZ8W1sf1lHyWYd2Y5ZFM4nPSMFt3Y/edit#) for more
=> Support `disable-inline-width` attribute when applying layout sizes

extensions/amp-access/0.1/amp-login-done-dialog.js, extensions/amp-access/0.1/test/test-amp-login-done-dialog.js
This PR updates `amp-access`'s login done dialog to keep trying to close its window for a minute.
Sometimes `window.close()` is ignored by the browser for a stretch of time. For instance, iOS ignores the method when there is a "Save Password" or "Update Password" prompt open. (https://github.com/ampproject/amphtml/issues/11369)
=> 🐛 amp-access: Keeps trying to close window for a minute

examples/amp-autocomplete-bind.html, examples/amp-autocomplete-testing.html, extensions/amp-autocomplete/0.1/amp-autocomplete.js, extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
- When selecting an autocomplete item, if `mutateElement()` is called
before the input element's value is changed, then input and change
events are fired in amp-script with the old input element's value.
Split up `selectItem_()` into two functions, one which sets input values
early and the other which fires events specific to amp-autocomplete at
the end.
- On item selection, fire amp-specific and native change events on the
the input to ensure the change is detected by `amp-bind` and user
scripts in `amp-script`.
Fixes #26273
=> amp-autocomplete: Revise order of selection events

package.json, yarn.lock
Reverts ampproject/amphtml#26439
`gulp-jest` was not updated to support new export pattern.
@ampproject/wg-infra Can we add testing or automation to ensure this doesn't happen again?
=> Revert "📦 Update dependency jest-cli to v25"

src/service/viewer-impl.js
Initializing the messaging channel to the viewer can time out for a handful of reasons. #23874 addressed one of those in `cid-impl.js`, marking the reported error as an expected/known failure case. This PR marks a similar viewer timeout error as expected, to improve classification in error reporting.  
Closes https://github.com/ampproject/amphtml/issues/20120
=> 🐛 Mark initMessagingChannel timeout as an expected error

build-system/tasks/presubmit-checks.js, extensions/amp-story-education/0.1/amp-story-education.js, extensions/amp-story-education/0.1/test/test-amp-story-education.js, extensions/amp-story/1.0/amp-story-store-service.js, extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js, extensions/amp-story/1.0/amp-story.js
Story education viewer messaging:
- Sends a message on build to display the tap + swipe navigation screen
- Only sends messages when the doc gets visible, to avoid receiving messages from multiple prerendered docs
- Stops propagation on touch events so they're not forwarded to the viewer, disabling the "swipe to next" feature (and the navigation hint overlay)
- Adds an `EDUCATION_STATE` in the store service and expose it to viewers, so they can block swiping interactions while it's on if they're using native gestures
#27097
=> Story education viewer messaging.

src/mode-object.js, src/mode.js, test/unit/3p/test-3p-frame.js
This makes it so we don't rely on the internal build system for the esm identification mechanism and solely rely on the external symbol replacement
=> use symbol replacement IS_ESM instead of relying on AMP_CONFIG.esm

src/service/storage-impl.js
When users disable storage, the Google AMP Viewer can throw an error when it receives a `saveStore` message. This PR catches that error and reports it as an expected error. This should silence ~185k errors/week from the unexpected error buckets.
Closes https://github.com/ampproject/amphtml/issues/25643
=> 🐛 Mark viewer storage failure as an expected error

tools/experiments/experiments.js
=> 🏗🚮 Remove deprecated AMP_CANARY cookie name from experiments.js

build-system/tasks/performance/print-report.js
Fix bug where experiment numbers were under PRODUCTION and control numbers were under BRANCH.
=> 🐛Swap columns on performance report

build-system/tasks/visual-diff/.percy.yaml, build-system/tasks/visual-diff/index.js, test/visual-diff/visual-tests
This PR:
* Adds a .percy.yaml file with default settings
* Sets the asset discovery timeout to 150 ms instead of the default 50 ms (recommended by Percy support in an attempt to resolve flakiness with missing images)
* [*Tag-along change*] removes the unused `asset_globs` field from the `visual_tests` file
Related to #27181
=> 🏗 add .percy.yaml config file for visual diff tests

extensions/amp-ima-video/0.1/amp-ima-video.js
Addresses the [third](https://pantheon.corp.google.com/errors/CNu81pXjoeLfVQ?time=P7D&project=amp-error-reporting) most frequently logged error in AMP Error Reporting.
Currently, when the amp-ima-video extension tries to send a command it:
1) Checks that the iframe's `contentWindow` is available
2) Waits for a promise to resolve indicating the player is ready
3) Tries to post a message to the iframe's `contentWindow`
If `unlayoutCallback` is called before the promise resolves, `contentWindow` won't be available, and we get this error. The solution is to instead validate the iframe is available after the promise resolves, right before trying to post a message to it.
I anticipate this will eliminate approximately 900k errors per week.
Closes …
=> 🐛 Validate presence of contentWindow after promise resolves

build-system/common/utils.js, build-system/tasks/e2e/index.js, build-system/tasks/visual-diff/index.js
Added `buildRuntime()` to `build-system/commons/utils`, which cleans and build the runtime using `--fortesting` flag and overwritten config. 
- Replaced in e2e and visual-diff
=> ♻️ Refactor dist --fortesting into commons/utils

extensions/amp-access/validator-amp-access.protoascii, extensions/amp-subscriptions/0.1/test/validator-amp-subscriptions-errors.out, extensions/amp-subscriptions/validator-amp-subscriptions.protoascii
Although the valdiator error is useful for pushing users to avoid errors, in practice amp-access and amp-subscriptions appear to coexist fine. This change is needed to allow publishers using amp-subscriptions to also use amp-access-scroll to let Scroll customers avoid ads.
=> 🐛Change validator to let amp-access and amp-subscriptions coexist

extensions/amp-video-docking/0.1/amp-video-docking.js
Addresses the [eigth](https://pantheon.corp.google.com/errors/CM2H9OvX1deHPQ?time=P7D&project=amp-error-reporting) most frequent unexpected error reported to AMP Error Reporting.
When the amp-video-docking component initializes, it tries to dock to either the left or right side of the screen, defaulting to right but using left if the `dir="rtl"` attribute is set on the document or body. The issue is that sometimes the component is initialized before the document is fully created, and so there is no documentElement and the call to `isRTL` fails. This PR gates the call to `isRTL` with an assertion that `document.body` exists, and if it doesn't defaults to docking to the right.Note that the initial docking is overridden when the user drags the dock.
I anticipate this PR will eliminate ~160k …
=> 🐛 Wait for document body to exist before testing rtl/ltr

build-system/common/git.js, build-system/pr-check/yarn-checks.js
During Travis runs, we check if `yarn.lock` was properly updated. This is currently done in `isYarnLockFileProperlyUpdated()` by searching for the string `"yarn.lock"` in the `git diff` output. The check can cause `gulp pr-check` to return a false negative during local development if an in-flight change happens to contain the string `yarn.lock` (rare, but can happen).
This PR makes the detection more explicit by examining the list of files modified to see if there are unexpected changes to `yarn.lock`.
=> 🏗 Make `yarn.lock` change detection more resilient

extensions/amp-bind/amp-bind.md
`<source>` and `<track>` are not allowed in emails.
/to @sebastianbenz 
/cc @choumx
=>  📖Remove irrelevant amp-bind doc for email

build-system/pr-check/build-targets.js
In order to optimize the use of Travis CPU time, AMP's PR checks use a [build target system](https://github.com/ampproject/amphtml/blob/master/build-system/pr-check/build-targets.js) to determine which tests to run. When packages are upgraded, the system currently neglects to run tests that may be affected, causing them to potentially [break on `master`](https://travis-ci.org/github/ampproject/amphtml/jobs/663242651#L367).
This PR makes it so that when a package upgrade is detected (e.g. a renovate PR), tests corresponding to all build targets are executed on Travis. Local `gulp pr-check` is left as is, because it's meant to be a quick verification and not a comprehensive run of all tests.
Fixes #27263
=> 🏗 Run all PR checks during package upgrades

extensions/amp-consent/0.1/amp-consent.js
`this.getConsentRemote_()` can return null, and we're assuming that it always is an object.
Defaults `getConsentRequiredPromise_` to false if this is the case.
=> 🐛 amp-consent getRemoteConsent null

extensions/amp-a4a/0.1/refresh-manager.js, extensions/amp-a4a/0.1/test/test-refresh.js
Read `meta[name="amp-ad-enable-refresh"]` using method supported by
`AmpDocShadow` as well as other `AmpDoc` subtypes.
=> a4a: RefreshManager: Support amp-ad-enable-refresh lookup in AmpDocShadow

extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
Read `meta[name="referrer"]` using method supported by `AmpDocShadow` as well as other `AmpDoc` subtypes.
=> amp-ad-network-doubleclick: Respect meta['referrer'] in AmpDocShadow

build-system/tasks/runtime-test/helpers-unit.js, package.json, yarn.lock
AMP unit tests use the [`find-imports`](https://www.npmjs.com/package/find-imports) package to help determine which tests must be run when a given source file has been touched. The current version of the module (v1.1.0) has a bug, where it prints an error message while searching through some files, most likely because they use `import * as ...` style imports.
It turns out the bug has been fixed in the latest version of the package (v1.3.2), but it has been forked to a different npm package name called [`find-imports-forked`](https://www.npmjs.com/package/find-imports-forked) (even though the code repo is the same).
This PR updates the version of the package used in our tests.
=> 🏗🐛 Upgrade module `find-imports` to 1.3.2

tools/experiments/README.md
Fix the experiment documentation to link to the correct file.
=> 🐛Fix the documentation link to the experiment list

extensions/amp-analytics/0.1/amp-analytics.js
Avoid expanding template for most selectors
before:
after:
=> Avoid expanding selector

babel.config.js, package.json, yarn.lock
A recent change to correctly transpile classes for Stories accidentally added class transpilation to the Module build.
This PR fixes this accidental change and moves the ESM build to a more clearly defined set of different rules.
=> 🚀Ensure Classes are not Transpiled for Module Build

extensions/amp-story-education/0.1/amp-story-education.js
Restrict amp-story-education to the mobile UI, as the tap/swipe education screens are not adapted to desktop UIs.
#27097
=> Restrict amp-story-education to the mobile UI.

build-system/tasks/serve.js
- Using `const ... of` for simplicity
- `require.cache[serverFile]` is undefined, since the cache map uses absolute paths as keys, so this resolves them.
=> 🐛 Properly invalidate `serve` require cache when watching

3p/environment.js
https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-setinterval
https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timer-initialisation-steps
Per the spec, timers must return a value greater than 0.  Currently, the first setInterval call will return 0 as the interval ID.  This can cause some code to inadvertently fail, since 0 is falsey.
=> 🐛 Values returned by setInterval must be greater than 0.

extensions/amp-carousel/0.1/amp-carousel.css, test/integration/test-amp-carousel.js
Fixes bug introduced by #25714: because AMP email overrides the behavior of the `controls` attribute without the attribute being present, neither CSS selector that shows carousel buttons actually catches it.
=> 🐛 Make amp-carousel.css use .i-amphtml-carousel-has-controls instead of [controls]

css/ampdoc.css, extensions/amp-iframe/0.1/test/test-amp-iframe.js, extensions/amp-sidebar/0.1/test/integration/test-amp-sidebar.js, extensions/amp-sidebar/0.2/test/integration/test-amp-sidebar.js, src/service/viewport/viewport-binding-natural.js, test/unit/test-viewport-binding.js
Reverts ampproject/amphtml#27319
Reason for rollback: it breaks sticky CSS.
=> Revert "Disable x-scrolling on iOS when iframed"

extensions/amp-story-education/0.1/amp-story-education.css, extensions/amp-story-education/0.1/amp-story-education.js
Adding CSS scoping for inherited styles to the `amp-story-education` UI.
Fixes https://github.com/ampproject/amphtml/issues/27418
=> Story education shadow reset.

extensions/amp-animation/0.1/test/test-web-animations.js, extensions/amp-animation/0.1/web-animation-types.js, extensions/amp-animation/0.1/web-animations.js
Clip path can be animated safely and with good performance. Some masked shapes that will be used in stories use clip-path a lot. Another good example are local "reveal" animations.
=> Allow clip-path for animations

build-system/test-configs/dep-check-config.js, extensions/amp-ad-network-smartads-impl/0.1/amp-ad-network-smartads-impl.js, extensions/amp-ad-network-smartads-impl/0.1/smartads-a4a-config.js, extensions/amp-ad-network-smartads-impl/0.1/test/test-amp-ad-network-smartads-impl.js, extensions/amp-ad-network-smartads-impl/OWNERS, extensions/amp-ad-network-smartads-impl/amp-ad-network-smartads-impl.md
=> Initial smatr-ads-net

ads/revcontent.js
Some of Revcontents older AMP ad implementations reference a wrapper attribute, but this attribute is not listed as an required or optional attribute for a Revcontent ad tag. This results in an "unknown attribute for revcontent: wrapper" error in the console:
This PR adds this attribute to the list of optional attributes we support and resolves this console error.
=> ✨ Add support for wrapper attribute

extensions/amp-date-display/0.2/test/test-amp-date-display.js
Instead of manually calling `build()` on the element.
=> Wait for amp-date-display to build in unit tests

build-system/compile/compile.js, build-system/compile/pre-closure-babel.js, build-system/compile/single-pass.js, build-system/compile/sources.js, build-system/tasks/check-types.js, build-system/tasks/dist.js, build-system/tasks/helpers.js
- AMP's minified build (`gulp dist`) and type checker (`gulp check-types`) run a set of `babel` transforms on source files before invoking closure compiler. 
- Today, transforms are run on **_all_** source files at once, after which the results are written to disk in a temp directory. Following this, closure compiler is invoked on the temp directory.
- This is particularly inefficient for flags like `--core_runtime_only` and `--noextensions`, which only compile a small subset of source files.
**This PR does the following:**
- Refactors pre-closure babel transforms to run directly on the `gulp.src` stream
- Moves all transform code to `build-system/compile/pre-closure-babel.js`
- Implements a caching mechanism so every source file is transformed at most once
- Deletes …
=> 🏗🚀 Speed up pre-closure `babel` transforms

extensions/amp-access/0.1/access-expr.js, extensions/amp-access/0.1/amp-access.js, extensions/amp-access/0.1/test/test-access-expr.js
**summary**
This PR modifies `amp-access` so that it caches the result of expression evaluation. For sites with the same expression repeated many times on the page, this yields a significant improvement.
Access expressions are evaluated with two parameters, the expression and auxiliary data. The expression is used as the cache key, and the whole cache is invalidated any time the data is referentially changed (should only happen on reauth flows)
All testing was done on a Nokia 2.3. The `applyAuthorizationToRoot_` function went from taking 260ms to 42ms.  The remaining big chunk of work within this long task is actually `DOMPurify` instantiations, which is being optimized in https://github.com/ampproject/amphtml/pull/27260
**before**
**after**
=> access-expr: cache evaluations

build-system/tasks/performance/print-report.js, build-system/tasks/performance/stats.js
Taking performance measurements requires 100 runs at the moment, because the browser can act up in ways that bloat a performance metric. This PR fixes it by removing outliers before taking the average. It identifies outliers using the [Tukey method with inner and outer fences](https://en.wikipedia.org/wiki/Outlier#Tukey's_fences). 
For example, here's a sample run for the visible metric. 
So for control, we'll ignore everything outside the orange fence lines. Same fences are drawn for experiment. Out of bounds!
Hopefully we can use this lower the # of runs required to get reliable metrics, speeding up this task.
//related to https://github.com/ampproject/amphtml/issues/12128
=> 🏗 Remove outliers when testing performance

extensions/amp-app-banner/0.1/amp-app-banner.js
Query meta[name="apple-itunes-app"] using method supported by
AmpDocShadow as well as other AmpDoc subtypes.
=> amp-app-banner: Support apple-itunes-app lookup in AmpDocShadow

extensions/amp-bind/amp-bind.md
The debugging section of the amp-bind documentation lacked a reference to the development mode, which is mandatory.
=> 📖 [amp-bind] Improve documentation on how to debug amp-state

extensions/amp-bind/amp-bind.md
As of https://github.com/ampproject/amphtml/issues/21633#issuecomment-478464327 `data-vars-` attributes are currently not bindable. This is why I adjusted the `amp-bind` documentation.
Edit: As @samouri pointed out, only a few `data-` attributes are bindable. I changed the purpose of this PR to reflect that.
=> 📖 [amp-bind] Fix documentation on binding data- attributes

extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/test/test-amp-story-page.js
Fixing auto advance from audio on story cover page.
The page advancement class was listening for progress/ended events on the original `audio` element, not the one replaced by the pool. Waiting until the elements are registered (and swapped) fixes the race condition.
Partial for #27291
=> Auto advance from audio on story cover page.

extensions/amp-a4a/0.1/callout-vendors.js
Media.net is one of the listed rtc vendors for doubleclick AMP ad.
We need to pass the CONSENT_STATE and CONSENT_STRING macro values in our rtc callout url, to be compliant with international laws.
=> ✨ Add consent macros support in media.net rtc callout url

extensions/amp-access/0.1/access-expr.js, extensions/amp-access/0.1/test/test-access-expr.js
is it preferable to test for a proxy of an implementation detail, or to directly spy on the implementation detail?
cc @ampproject/wg-runtime
=> amp-access: avoid spying on private func.

extensions/amp-script/0.1/test/unit/test-amp-script.js
small cleanup. most of the changes were standard (adding `expectAsyncConsoleError`), but fixing the development tests had a surprise. They were throwing warnings based a service that `buildCallback` needs missing. So for those I installed the service.
=> amp-script: remove all console errors from tests

build-system/global-configs/caches.json
Bing AMP cache hosts are only reachable with `www` prepended.
=> caches: Fix bing cache hosts

AMP_MODULE_BUILD.md
In preparation to ramp up the module build, we should externally explain at a high level what it is and its details.
=> add a module build explainer

build-system/externs/amp.extern.js, src/custom-element.js, src/service/custom-element-registry.js, test/unit/test-base-element.js, test/unit/test-custom-element.js, test/unit/test-dom.js, test/unit/test-intersection-observer.js, testing/describes.js
It's equivalent to the Element's `localName` in every case we care about. Also eliminates a bit of constructor cruft from the CEv0 days.
=> 🚮 Eliminate elementName method

build-system/compile/compile.js, build-system/tasks/build.js, build-system/tasks/check-types.js, build-system/tasks/dist.js
Due to #23238 and https://github.com/google/closure-compiler-npm/issues/9, we lowered the concurrency of closure compiler to 1 for local development.
This PR adds a flag called `--closure_concurrency` to `gulp`, `gulp check-types`, and `gulp dist` that lets you override the concurrency during local development.
Related to #23238
=> 🏗 Add an override for closure compiler concurrency

.travis.yml
Required for the upcoming `nightly` workflow that will eventually replace the `canary` branch workflow
=> 🏗✨ Trigger Travis push builds for the `nightly` branch

build-system/tasks/extension-generator/extension-doc.template.md, extensions/amp-accordion/amp-accordion.md, extensions/amp-next-page/amp-next-page.md
=> fixed some heading errors

src/service/viewer-impl.js
This PR is a follow-up to https://github.com/ampproject/amphtml/pull/27247
That PR attempted to mark the timeout error as expected by checking that the error message raised by `timeoutPromise` was the `opt_message` provided. What I missed at the time was that `getChannelError` prepends text to the error message, so the equality check failed and didn't actually mark the error as expected.
This PR updates the check to instead verify that the error reason matches the `opt_message` provided to `timeoutPromise`
=> 🐛 Mark initMessagingChannel timeout as expected error

extensions/amp-next-page/1.0/service.js
Closes #27493 
- Fixes logic issue that prevented `deep-parsing` from getting disabled if `amp-next-page` doesn't have an `src`
=> 🐛 nit: fix logic for `deep-parsing` on `amp-next-page`

extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/test-amp-list-load-more.js
amp-list[load-more] already did not support layout=container. This change explicitly guards the layout=container feature from going down the infinite list code path.
/cc @rcebulko
=> [amp-list]: make layout=container and load-more mutually exclusive

build-system/server/lazy-build.js, build-system/tasks/build.js, build-system/tasks/default-task.js, build-system/tasks/dist.js, build-system/tasks/presubmit-checks.js, gulpfile.js
- During `gulp dist`, we copy CSS and parsers from `build/` to `dist/`
- During `gulp dist`, we build the core runtime by calling this function:
https://github.com/ampproject/amphtml/blob/c71405018130c691f8be3528e4248dff589cfae3/build-system/tasks/helpers.js#L173-L188
- Make `gulp --compiled` use the same compilation options as `gulp dist` for the core runtime
- Refactor default `gulp` task into `build-system/tasks/default-task.js` and add missing steps for `gulp --compiled`
**Comparison:**
- **`gulp dist --core_runtime_only`:**
- **`gulp --compiled`:**
Follow up to #27471
=> 🏗🐛 Assorted fixes for `gulp --compiled`

validator/testdata/transformed_feature_tests/server_side_rendering.html, validator/testdata/transformed_feature_tests/server_side_rendering.out, validator/validator-main.protoascii
This also fixes hard coded image dimensions.
Fixes #27528
=> 🐛 Validator: support decimals for intrisic sizer dimensions

extensions/amp-story/1.0/amp-story.css, extensions/amp-story/1.0/amp-story.js, test/visual-diff/visual-tests
Fix unsupported browser dynamic font sizing, and reenable tests.
Sorry, I know this is super low priority, but I wanted to look into it as I was worried about a bug in the dynamic font sizing code. Fortunately, this was very specific to the unsupported browser page, that set a `display: none;` on all story pages.
This PR pauses the story, instead of hiding the pages. That makes more sense, as we can expect most people to click the "continue anyway" button.
Fixes #27185
=> Fix unsupported browser font sizing, and reenable tests.

src/custom-element.js, src/layout.js, src/service/mutator-impl.js, src/service/mutator-interface.js
**summary**
Before this PR, every single call to `mutator.mutateElement` would automatically result in a remeasure. The `toggleLoading` flow calls mutate twice, and therefore may result in two extra measurements. It turns out, that our loading indicator will never affect the bounding box of its parent (it has `position: absolute`), therefore measurement is completely unnecessary.
This PR adds an `opt_skipMeasure` parameter to `mutateElement` and takes advantage of it for the loading toggler as well as its cleanup.
**performance delta**
Unlike my prior two PRs where the numbers were relatively stable, I've found that measuring the measurement system (ha!) is difficult. Results are highly variable between refreshes. Our resources system is fairly nondeterministic and highly dependent on …
=> 🚀 Optimize toggleLoading by letting the mutator skip measuring in specific cases.

babel.config.js, build-system/tasks/build.js, build-system/tasks/default-task.js, build-system/tasks/dist.js, build-system/tasks/serve.js, gulpfile.js
- Refactors prerequisite steps for `gulp build` into `runPreBuildSteps()`
- Refactors prerequisite steps for `gulp dist` into `runPreDistSteps()`
- Reuses both functions during unminified / minified lazy build
- Removes all unnecessary copy-pasted steps
- Documents flags for default `gulp` task
- Fixes 3p frame compilation flags during lazy build
- Fixes config returned by `babel.config.js` during minified lazy build
With this PR, the two commands listed below generated identical `v0.js` files:
```sh
gulp dist --core_runtime_only
gulp --compiled
```
Follow up to #27471 and #27515
=> 🏗♻️ More fixes for `gulp --compiled`

extensions/amp-story/1.0/amp-story-draggable-drawer-header.css, extensions/amp-story/1.0/amp-story-draggable-drawer.css, extensions/amp-story/1.0/amp-story-draggable-drawer.js, extensions/amp-story/1.0/amp-story-page-attachment.css, extensions/amp-story/1.0/amp-story-page-attachment.js, extensions/amp-story/1.0/amp-story.css
Open remote page attachments:
- Implement a draggable drawer containing the URL + an opening animation
- Implement a `dragCap` option for the abstract draggable drawer (max amount of px you can drag)
- Implement an `openThreshold` option for the abstract draggable drawer (max amount of px you can drag before it automatically opens the drawer)
- For Safari, listen for `pageshow` events to revert the animation when the page is resumed from the cache (and not reloaded)
- Extract all page-attachment CSS to its own file (it's all a copy/paste, except for all the selectors starting with `.i-amphtml-story-page-attachment-remote`)
- Stops hiding/showing the inline attachment content on close/open as it's handled by the `setOwner` and following methods (legacy)
- Adds `touch-action: none;` to the …
=> Open remote story page attachments.

validator/java/src/main/bin/fetchAMPResources.sh, validator/java/src/test/java/dev/amp/validator/parser/AMPHtmlParserTest.java
- added a cat to roll in css.protoascii from validator/ level
- removed a test, due to changes in style's blacklist (no more fail on !important attribute)
=> 🐛resolve build errors in testing due to new css.protoascii

extensions/amp-story-education/0.1/amp-story-education.js, extensions/amp-story-education/0.1/test/test-amp-story-education.js
Story education API update:
- If `cap=swipe` is NOT present, send a "on tap" message to only show the tap education screen
- If `cap=swipe` is present, send a "on tap and swipe" message to display both tap and swipe education screens
#27097
=> Split 'on tap' and 'on tap and swipe' education messages.

extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side.js
Skips this test:
```
1) amp-consent
chrome
Standalone environment 
should respect server side decision and persist it:
AssertionError: expected 'http://localhost:8000/amp4test/request-bank/e2e/deposit/tracking?consentState=insufficient' to have been sent
```
=> Skip amp-consent flaky e2e test

extensions/amp-story/1.0/media-performance-metrics-service.js, extensions/amp-story/1.0/test/test-media-performance-metrics-service.js
Track whether media are served from the cache, when opted in through the `csi` capability.
Context and details at https://github.com/ampproject/amphtml/issues/27560
Fixes https://github.com/ampproject/amphtml/issues/27560
=> Track whether media are served from the cache.

extensions/amp-story/1.0/page-advancement.js, extensions/amp-story/1.0/test/test-page-advancement.js
Validates auto-advance-after element. Fallbacks to manual advancement if the element is not one of:
- `amp-story[background-audio]`
- `amp-story-page[background-audio]`
- `amp-video`
- `amp-audio`
I was surprised to see that we support auto advancing on an `amp-story` or `amp-story-page` background-audio but apparently we do:
https://github.com/ampproject/amphtml/blob/303f48924029522c36f1b25dd7319d82d67b75ba/extensions/amp-story/1.0/page-advancement.js#L910-L914
I couldn't really test `amp-story` or `amp-story-page` it as background-audio seems to be broken, cf https://github.com/ampproject/amphtml/issues/27573
=> Validate auto-advance-after element.

.eslintrc, examples/amp-story/player.html, src/amp-story-player-impl.js, src/amp-story-player-manager.js, src/amp-story-player.js, test/unit/test-amp-story-player.js
Changing the player to use `CustomElements`. This will help us open up an API for the player.
* Also now listens to the `load` event listener in the window to initialize the player, instead of overriding the `onload` function.
Tracker #26308
To be merged after #27324
=> ✨[amp-story-player] Upgrading amp-story-player to CE

src/custom-element.js, src/loader.js, test/unit/test-custom-element.js
**summary**
The `custom-elements.getLayoutBox` function always triggers a toggleLoading for in-viewport elements. Why do we do this? Can it be removed? We already call `this.toggleLoading(true)` within viewportCallback.
We can also simplify some of the conditions considering that `prepareLoading` will also noop if either `this.loadingContainer_` exists or if `this.isLoadingEnabled` returns false.
/to @ampproject/wg-runtime
=> custom-element.updateLayoutBox: remove automatic toggleLoading

build-system/externs/amp.extern.js, src/config.js, src/error.js
This PR:
- moves the new error reporting endpoint to a `betaErrorReporting` config field
- moves logic for picking reporting endpoint URL to a helper function
- diverts all nightly traffic to the new endpoint (otherwise traffic % times the 0.05 throttling factor on legacy error reporting will suppress almost all errors from Nightly)
In coming weeks, the new endpoint will become the standard `errorReporting` URL, while the `betaErrorReporting` will eventually become `https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta`. When this happens, all traffic will be going through the migrated error reporting, and the exceptions for ESM and Nightly can be removed.
Part of https://github.com/ampproject/error-tracker/issues/112
=> 🏗 Clean up error reporting Beta diversions & divert all Nightly

extensions/amp-story/1.0/amp-story.css
The white icon would not show on the selected answer if the quiz had chip-corner="sharp" since it was overriding the color to transparent.
Before:
After:
=> 🐛Fixed quiz icon not showing on sharp chip

extensions/amp-ad-custom/validator-amp-ad-custom.protoascii
https://github.com/ampproject/amphtml/issues/27614
This requirement should be mandatory but is missing from validator spec. We do not expect to see a large audience encounting problems with it since it would never work.
=> 🐛Require src attribute in amp-ad-custom

.github/ISSUE_TEMPLATE/error-report.md
The AMP release on-duty monitors AMP Error Reporting and files issues for errors that appear. Usually, the on-duty copy-pastes the message/stacktrace and maybe some extra info. This PR introduces a template for error reports, with clear fields for the on-duty to populate. It also adds the **Type: Error Report** label.
An example issue built from this template can be seen [here](https://github.com/rcebulko/amphtml/issues/6)
=> 🏗 Add new issue template for error reports

build-system/tasks/default-task.js
The build system's default task [already supports](https://github.com/ampproject/amphtml/blob/bddcddb6169abfb16abca483823a8fd26c52ee34/build-system/tasks/serve.js#L103) specifying a host to serve on.
But this option is not part of the supported flags that were added in a recent refactor. This PR adds this flag back.
=> 🏗 Added --host option to gulp's default task

build-system/babel-plugins/babel-plugin-const-transformer/index.js, build-system/compile/build.conf.js
Enable the const => let transform in post closure babel pass for module builds.
=> 🚀 Add const-let transform to post closure transforms

extensions/amp-geo/0.1/amp-geo-presets.js, extensions/amp-geo/0.1/amp-geo.js, extensions/amp-geo/0.1/test/test-amp-geo.js
Closes #26637
Add preset-us-ca set before we have generic ISO subdivision support. 
The new `{{AMP_ISO_COUNTRY_HOTPATCH}}` replaced format will be  
`"us                           "` or  `"us us-ca                     "` (string length stays the same)
=> Add preset-us-ca set to amp-geo

examples/amp-next-page.amp.html, extensions/amp-iframe/0.1/amp-iframe.js, src/service/ampdoc-impl.js, test/manual/amp-next-page/1.0/articles/article-short.html, test/manual/amp-next-page/1.0/articles/article-with-fixed.html
AMP enforces restriction to the tracking iframe (with width/height less than 10px) count. It's more reasonable to allow one tracking iframe for each ampdoc instead of each window.
=> Allow one tracking iframe in each amp doc

babel.config.js, build-system/pr-check/build-targets.js
#27576 refactored all babel configs into one place, but neglected to account for the babel plugin tests.
This PR adds a new empty config type called `babel-jest` for `gulp babel-plugin-tests` and makes sure the plugin tests are run when babel configs are changed.
Follow up to #27576
=> 🏗🐛 Fix babel plugin tests and run them for babel config changes

src/service/performance-impl.js
The calls to `getSize` show up in testing, taking up as much as 60ms:
Note that this doesn't eliminate the recalc, since it will still be done at least once. It just doesn't need to happen so soon (before Resources has even loaded).
=> 🚀 Defer viewport getSize in performance-impl

src/service/mutator-impl.js, src/service/resources-impl.js, src/service/viewport/viewport-binding-natural.js, test/unit/test-resources.js
Related to #25428.
Minor bug fix: we always need to schedule a pass after building a resource because it won't be laid out in the same pass (`Resource.build` is async). Surveyed the remaining "skip pass in intersection mode" cases and they look good.
Also realized we're no longer using `scheduleWhenBuilt` parameter at all, so removed it. For some context on "why do we even have that button", the I think the last usage was removed in #12311.
=> intersect-resources: Always schedule pass after build

extensions/amp-story/1.0/amp-story.js
Validation would fail if the `amp-story-consent` doesn't have the right parent, but it cannot catch the case where `amp-consent` does not have an `amp-story-consent` child.
It fails nicely, but the error triggered should be `user()` instead of `dev()`.
Fixes https://github.com/ampproject/amphtml/issues/27669
=> Trigger user rather than dev errors for amp-story-consent misconfiguration.

src/config.js, src/error.js
This PR:
- sets the default error reporting endpoint to the new Cloud Functions deployment
- sets the beta error reporting endpoint to the beta Cloud Functions deployment
- lowers the beta diversion from 20% to 10%
- removes special handling for ESM and Nightly, since now all errors will go to a non-legacy endpoint
Part of https://github.com/ampproject/error-tracker/issues/112
=> 🏗 Ramp new error reporting endpoint to 100%

.travis.yml, build-system/pr-check/module-build-tests.js, build-system/pr-check/module-build.js
Ensure ESM builds run successfully like other runtimes.
=> 🏗 Build ESM output on travis

build-system/compile/internal-version.js
Version must be 13 digits. Combined with a 2-digit config code, this
implies RTVs must be 15 digits.
Fixes #27579
=> build-system: Restrict allowed version_override

extensions/amp-form/0.1/amp-form.js, extensions/amp-form/0.1/test/test-amp-form.js, extensions/amp-form/amp-form.md
Fixes: https://github.com/ampproject/amphtml/issues/7607
- Added support for the enctype attribute on amp-form
- enctype will now support `application/x-www-form-urlencoded` in addition to the previously supported `multipart/form-data`
- Documentation and unit tests updates included
=> ✨ [amp-form] Allow user to specify enctype=application/x-www-form-urlencoded for form submission

build-system/tasks/default-task.js
The build system's default task [already supports](https://github.com/ampproject/amphtml/blob/3207eea93ff8acb30d5cdc3d5026c3bb0196ac95/build-system/tasks/serve.js#L104) specifying a port to serve on.
But this option is not part of the supported flags that were added in a recent refactor. This PR adds this flag back.
=> 🏗 Added --port option to gulp's default task

examples/visual-tests/amp-story/amp-story-bot-rendering.html, extensions/amp-story/1.0/amp-story-page-attachment.js, extensions/amp-story/1.0/amp-story-share-menu.css, extensions/amp-story/1.0/amp-story-vertical.css, test/visual-diff/visual-tests
...which are really just links.
Also:
- Changes vertical rendering to not specify a height for attachments such that they simply flow as high as their content.
- Fixes menu overlaying all vertically rendered content making it non-interactive.
=> Use a real anchor for remote page attachments

contributing/DEVELOPING.md, contributing/contributing-code.md, contributing/release-schedule.md
* Move opt-in instructions from release-schedule.md to DEVELOPING.md
* Add details about the nightly release channel to release-schedule.md
* Move description of beta/experimental channels into the weekly section of release-schedule.md and remove the opt-in instructions (links to DEVELOPING.md instead)
* Minor fixes (e.g., fixing broken links to PR labels)
=> 📖 Development, Nightly, and Release schedule documentation updates

build-system/compile/debug-compilation-lifecycle.js, build-system/compile/post-closure-babel.js, build-system/compile/pre-closure-babel.js, build-system/tasks/dist.js
Introduces a new debugger for `gulp dist` with our evolving compilation pipeline.
This file is updated with each compilation lifecycle event.
As a result, when debugging the pipeline you can see per event the operation, filename, and current status of the contents (written to temp).
This allows you to disect problems with the pipeline by looking at individual operations.
=> 🏗 Debug Compilation Lifecycles via gulp dist --debug
