contributing/release-schedule.md
Closes #27267 
// cc: @ampproject/wg-caching @ampproject/wg-infra @ampproject/wg-outreach
=> 📖 Document the `?optin=<channel>` feature

extensions/amp-social-share/0.1/amp-social-share.js, extensions/amp-social-share/0.1/test/test-amp-social-share.js, extensions/amp-social-share/0.2/social-share.js
=> 🐛 Catch on navigator.share

extensions/amp-access-scroll/0.1/amp-access-scroll.css, extensions/amp-access-scroll/0.1/scroll-bar.js, extensions/amp-access-scroll/0.1/scroll-component.js, extensions/amp-access-scroll/0.1/scroll-impl.js, extensions/amp-access-scroll/0.1/scroll-protocol.js, extensions/amp-access-scroll/0.1/scroll-sheet.js
This cleans up some transition scaffolding that is no longer needed.
=> 🚮 amp-access-scroll: remove holdback

build-system/compile/build.conf.js, src/service/navigation.js, src/service/platform-impl.js
Remove IE specific workaround called out in the module output.
=> 🚀 Remove IE specific references for ESM path

extensions/amp-geo/amp-geo.md
Show amp-geo as usable in stories on amp.dev.
=> Show amp-geo as usable in stories on amp.dev.

build-system/pr-check/module-build.js
=> 🏗 ESM Build exclude language fix

extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
Errors on master:
https://travis-ci.org/github/ampproject/amphtml/jobs/673481233#L2311
https://travis-ci.org/github/ampproject/amphtml/jobs/673480640#L2310
=> ❄️ Skip amp-base-carousel flaky e2e test

extensions/amp-story/1.0/amp-story.js
=> Add period at end of a comment.

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.101
=> ✨ SwG Release 0.1.22.101

examples/amp-story/player.html, src/amp-story-player-impl.js, src/amp-story-player-manager.js, src/amp-story-player.js, test/unit/test-amp-story-player.js
closes #27732
Reverts ampproject/amphtml#27320
=> Revert "✨[amp-story-player] Upgrading amp-story-player to CE"

extensions/amp-geo/0.1/amp-geo.js
In case a server inserts an improperly cased, but still valid, country/subdivision.
Also cleans up the regex matches.
=> 🐛 Always lowercase amp-geo hotpatch matches

build-system/server/app-index/api/api.js
Fuse.js changed its API. Broke on #27537
=> 🐛 Local dev listing: fix search

validator/validator-main.protoascii
This should not have security implications.
https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-enterkeyhint-attribute
=> Drive by PR: Allow new enterkeyhint attribute on input

test/integration/test-amp-img.js
Re: https://github.com/ampproject/amphtml/pull/27783#issuecomment-614228216
=> ✅ Enable simple integration test in IE11

OWNERS
=> 🏗 Make wg-caching a required reviewer for validator changes

extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
✨ Implemented the feature requested in https://github.com/ampproject/amphtml/issues/27712.
=> Disable AdSense ad size optimization for users with wide viewport

extensions/amp-story/1.0/amp-story-page-attachment.css
Remote attachment dark mode support, using the same colors as the inline attachment.
=> Remote attachment dark mode support.

extensions/amp-social-share/0.1/amp-social-share.js, extensions/amp-social-share/0.1/test/test-amp-social-share.js
This reverts commit b3a9501ff61a1f790f3a46229bdbd09d82aa41b7 #27533.
Closes #27826
=> Revert "[amp-social-share]: Allow component to prerender (#27533)"

extensions/amp-story/1.0/sources.js, extensions/amp-story/1.0/test/test-media-pool.js, extensions/amp-story/1.0/test/test-media-tasks.js
=> Make media pool assert HTTPs-ness of URLs to align with amp-video

extensions/amp-loader/0.1/test/test-amp-loader.js, src/loader.js, test/unit/test-loader.js
**summary**
These files had no tests. This PR adds a couple. I've never made a test file from scratch before though, so feel free to be super critical/nitty!
=> ✅ Bootstrap unit tests for both loader.js and amp-loader.js

build-system/tasks/storybook/amp-env/decorator.js, build-system/tasks/storybook/package.json, build-system/tasks/storybook/yarn.lock, extensions/amp-image-slider/0.1/storybook/Basic.amp.js
- Added support for global and local styling of components inside Storybook through `styled-jsx`
- Added an example for using CSS in Storybook by customizing the hints on the `amp-image-slider` component
/cc @krdwan @dvoytenko @jridgewell
=> ✨ CSS support in Storybook and `amp-image-slider` example

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
- Uploaded SwG buttons for country launches 
- Update dependency karma to v5.0.2 
- Update dependency karma-mocha to v2 
- 🐛 Fixes imports for export-to-amp task
=> SwG Release 0.1.22.102

extensions/amp-story-auto-ads/0.1/story-ad-config.js, extensions/amp-story-auto-ads/0.1/test/test-story-ad-config.js
=> 🚀allowlist adsense type for story ads

ads/inabox/inabox-messaging-host.js
Reverts ampproject/amphtml#27912
=> Revert "Do not override inabox host handler"

extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
Closes https://github.com/ampproject/amphtml/issues/27936
=> 🐛 Mark contentWindow unavailable as expected error

extensions/amp-story/1.0/sources.js, extensions/amp-story/1.0/test/test-media-pool.js, extensions/amp-story/1.0/test/test-media-tasks.js
Reverts ampproject/amphtml#27875
=> Revert "Make media pool assert HTTPs-ness of URLs to align with amp-video"

extensions/amp-gfycat/amp-gfycat.md
Stories don't allow amp-gfycat anymore: https://github.com/ampproject/amphtml/pull/25847
https://github.com/ampproject/amphtml/issues/27986
=> Remove stories format from amp-gfycat.

examples/amp-story/player.html, package.json, src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js, yarn.lock
=> ✨[amp-story-player] Add support to load documents from the cache

extensions/amp-geo/OWNERS
=> amp-geo: Fix typo on zhouyx's handle in OWNERS

spec/amp-var-substitutions.md
=> 📖 Update platform variable docs

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
Version: 0.1.22.103
Previous release: 0.1.22.102
Update dependency mocha to v7.1.2 (#1069)
=> SwG Release 0.1.22.103

build-system/global-configs/experiments-const.json, build-system/test-configs/dep-check-config.js, examples/analytics-visibility.amp.html, extensions/amp-intersection-observer-polyfill/0.1/amp-intersection-observer-polyfill.js, extensions/amp-intersection-observer-polyfill/0.1/cross-origin-observer.js, extensions/amp-intersection-observer-polyfill/0.1/test/test-cross-origin-observer.js, package.json, src/friendly-iframe-embed.js, src/polyfills.js, src/runtime.js, src/utils/intersection-observer-polyfill.js, src/window-interface.js, yarn.lock
=> Universal IntersectionObserver polyfill for cross-origin iframes

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/analytics-group.js, extensions/amp-analytics/0.1/cookie-writer.js
To start experiment with AMP docs first. I'll run the experiment in inabox later. 
cc @nainar @jeffkaufman
=> Skip analytics-chunks experiment in inabox

extensions/amp-story/1.0/animation.js
=> 🐛 Ensure animation is initialized when pausing

.prettierignore
Addresses https://github.com/ampproject/amphtml/pull/28083#pullrequestreview-402143786
=> 🏗 Don't format `package.json` with `prettier`

extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
There's no one test here that's failing consistently, but the odds of one of these flaking on any given run is high
=> ❄️ Skip amp-slider tests around interactions

extensions/amp-social-share/0.1/amp-social-share.js, extensions/amp-social-share/0.1/test/test-amp-social-share.js
- Reintroduce changes in #27533 after revert from #27837 due to added safety from #28082 and fix from #27832. **Do not merge this PR before #27832 is merged.**
- Unskip test
=> [amp-social-share]: Allow prerender

extensions/amp-3q-player/amp-3q-player.md
Updated format to match [reference documentation template](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/extension-generator/extension-doc.template.md)
=> amp-rdu round 1 documentation update for amp-3q-player

build-system/compile/bundles.config.js, build-system/compile/compile.js, build-system/compile/sanatize.js, build-system/compile/sanitize.js, build-system/tasks/dist.js
This is to help with diffing the output of dists across build changes.
=> Add sanitize_vars_for_diff option to diff

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js, extensions/amp-consent/0.1/consent-policy-manager.js
Integration with IAB TCF v2 spec for GDPR compliance: pass gdprApplies to amp-ad-network-*.
According to guidelines discussed offline, the `&gdpr=` value should be 1 when `gdprApplies` is true, 0 when false (not falsey like null), and missing if undefined/null.
=> ✨TCF integration: pass gdprApplies to amp-ad-network-*

.gitignore, .travis.yml, build-system/tasks/clean.js, build-system/tasks/karma.conf.js, build-system/tasks/runtime-test/runtime-test-base.js, package.json, yarn.lock
OMG TESTS CAN BE SOOOO MUCH FASTER
=> 🏗✅ Add persistent browserify caching

spec/amp-errors.md, src/error.js
Source code change is only a comment.
=> 📖 Update spec/amp-errors.md with new reporting URL

src/error.js
Part of https://github.com/ampproject/error-tracker/issues/129
~Must not reach stable before the accompanying change in the error-tracker repo.~
=> Pre-throttle error reports from Stable client

build-system/global-configs/canary-config.json
=> Set aside 10% of canary traffic for fie-init-chunking experiment

build-system/compile/compile.js, extensions/amp-analytics/0.1/events.js, src/log.js
Matches `devAssert`'s change in #24047.
=> Fix userAssert's type annotation

css/ampshared.css
Re: https://github.com/ampproject/amphtml/pull/28115#pullrequestreview-405458081
=> Add implicit layout comments

build-system/global-configs/experiments-config.json
Turns off experiment in https://github.com/ampproject/amphtml/pull/27499 until I can debug failing sidebar test when experiment is turned on
=> ⏪ Remove experiment for FixedLayer due to failing sidebar test

build-system/global-configs/prod-config.json
=> Ramp up no center css experiment to 5% prod

extensions/amp-subscriptions/amp-subscriptions.md
=> 📖 Fixes a typo

extensions/amp-story/1.0/amp-story.js
This seems like an oversight; we do actually use CSS variables, but never check for support.
=> Check for CSS variable support

extensions/amp-ad-exit/0.1/amp-ad-exit.js, extensions/amp-analytics/0.1/config.js, extensions/amp-analytics/0.1/default-config.js, extensions/amp-analytics/0.1/transport.js
Change const names and file names.
=> ♻️Change ANALYTICS_CONFIG to DEFAULT_CONFIG to better reflect its usage

validator/nodejs/index.js
=> Validator rollup 465@1045

examples/amp-consent/cmp-vendors.amp.html, extensions/amp-consent/0.1/cmps.js, extensions/amp-consent/amp-consent.md, extensions/amp-consent/cmps/usercentrics.md
This Pull Request will add Usercentrics CMP to amp-consent
Related I2I: https://github.com/ampproject/amphtml/issues/27823
/cc @ampproject/wg-monetization
=> ✨amp-consent: Add Usercentrics CMP

extensions/amp-a4a/0.1/callout-vendors.js, extensions/amp-a4a/rtc-documentation.md
The Galaxie Media alliance brings together the best French sites dedicated to high-tech and innovation topics.
We're setting up our own RTC configuration.
=> ✨ Galaxie Media RTC adapter added

examples/analytics-vendors.amp.html, extensions/amp-analytics/0.1/test/vendor-requests.json, extensions/amp-analytics/0.1/vendors/blueconic.json
Changed the analytics-vendors.amp.html file by adding BlueConic and added the needed json for to use BlueConic as an analytics vendor. [
Fixes #27930](https://github.com/ampproject/amphtml/issues/27930)
=> ✨Add analytics vendor BlueConic

ads/_config.js
=> Oblivki config

extensions/amp-ad-network-adsense-impl/OWNERS, extensions/amp-ad-network-doubleclick-impl/OWNERS
=> Add jeffkaufman to Adsense/Doubleclick OWNERS

build-system/compile/check-for-unknown-deps.js, build-system/compile/sources.js, src/amp-story-player/amp-story-player-impl.js
=> [amp-story-player] Fix import error

test/unit/test-runtime.js
https://github.com/ampproject/amphtml/pull/28367 seems to have added a new script that is auto-inserted. A small test refactor to make it more resilient to new auto-inserted polyfills.
=> ✅ Fix failing test

extensions/amp-analytics/analytics-vendors-list.md
One time effort to add missing vendors to the doc. Follow up to #28321
=> Add missing analytics vendors to the doc

extensions/amp-auto-ads/0.1/placement.js, extensions/amp-auto-ads/0.1/test/test-placement.js
Code changes for this [issue](https://github.com/ampproject/amphtml/issues/28279)
=>  🐛 Bug fix: Limit the Full-Width Responsive upgrade in Auto Ads to mobile users only.

extensions/amp-story/1.0/amp-story-page.js
=> 🐛 Only wait for audio to build when using layout="nodisplay"

build-system/tasks/extension-generator/index.js
This expects a `layout` attribute, like [on the codelab](https://codelabs.developers.google.com/codelabs/creating-your-first-amp-component/#3).
=> 🏗 Fix default extension generator test

.renovaterc.json
Automerge won't work yet since `renovate` doesn't have write permissions, but this group of ampproject dependencies would be safe to auto-merge as long as Travis passes.
=> 🏗 Add auto-merging group for ampproject dependencies

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
=> ✨ SwG Release 0.1.22.105

spec/amp-actions-and-events.md, spec/amp-email-actions-and-events.md
Adds documentation for #27094, fixes #27699
=> added documentation on email actions

extensions/amp-story/1.0/animation.js
Following up to https://github.com/ampproject/amphtml/pull/28423, and will be cherry-picked to prod and beta/exp (https://github.com/ampproject/amphtml/issues/28433).
=> Add missing parenthesis crashing the production build.

src/amp-story-player/amp-story-player-impl.js
=> [amp-story-player] Allow top-navigation for remote attachments

build-system/global-configs/experiments-config.json
I thought there was just an issue with the test config, but there is actually an issue with the interaction between FixedLayer and the sidebar that I will need to address before the experiment can be turned on.
=> 🐛 Turn off FixedLayer experiment config

extensions/amp-animation/amp-animation.md
updated structure and some wording
=> amp-animation documentation update

.renovaterc.json, package.json
Fixes errors introduced in previous config changes. Also enables creation of a [master issue](https://docs.renovatebot.com/configuration-options/#masterissue) which will list all planned and pending renovate PRs, useful for tracking and debugging.
Related to https://github.com/ampproject/amphtml/issues/28473
=> 🏗 Fix renovate config file

.renovaterc.json
=> 🏗 Group patch+pin and separate patch from minor

ads/rakutenunifiedads.md
Update document of  rakutenunifiedads for responsive design
=> Update document for responsive design

.travis.yml, build-system/pr-check/validator-tests.js, build-system/tasks/pr-check.js
Band-aid for https://github.com/ampproject/amphtml/issues/28497
Eventually Java Validator will be split into a separate repo, and all testing logic will be removed entirely
=> 🐛 Skip Java validator tests

.eslintrc
https://github.com/ampproject/amphtml/pull/28452#discussion_r426949473
=> Add globalThis to eslintrc

src/amp-story-player/amp-story-player-impl.js
Renaming per https://github.com/ampproject/amphtml/pull/28426/files#r426108847
=> [amp-story-player] s/whitelist/minlist

src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
=> [amp-story-player] Use window.origin rather than url origin

.renovaterc.json
Related docs: https://docs.renovatebot.com/configuration-options/#prbodycolumns
Sample of Renovate PR with the packages column: https://github.com/amp-rcebulko-test-org/test-repo/pull/7
=> 🏗 Add package file path to renovate PR table

extensions/amp-story/amp-story.md
https://developers.google.com/search/docs/guides/enable-web-stories
=> Reference new structured data doc

build-system/global-configs/prod-config.json
The canary numbers are looking fine (all neutral). We should push this to prod.
=> Run FIE init chunking experiment on prod

extensions/amp-analytics/0.1/amp-analytics.js, extensions/amp-analytics/0.1/test/test-amp-analytics.js
=> Allow empty analytics config switch from error to warning

contributing/contributing-code.md, contributing/release-schedule.md
* Update the release schedule doc to include correct nightly information
* Clarify requirements for escalating an issue to P0
* Clarify cherry-picking instructions for when a P0 issue is present in a nightly build that is bound to be promoted to experimental/beta (Related to #28480)
=> 📖 Release documentation updates

extensions/amp-selector/0.1/amp-selector.css
fixes #28308
Added required css code to fix the bug. (Kept the cursor outline same as in 1.0)
=> 🐛 Added css property for amp selector[multiple] to display cursor:pointer 

.travis.yml
=> Remove apt source from Java Validator tests

extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/test/test-amp-story-page.js
Solves #28511 by adding the source back to the `<audio>` element after registering it in the media pool
=> 🐛 Fixes background audio bug

src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
=> [amp-story-player] initial isReady event for interacting with player API

ads/readmo.js, ads/readmo.md
This PR changes the `data-url` parameter from required to optional on ReadMo units.
=> ♻️readmo: change data-url from required to optional

ads/nativery.js
Added observeIntersection to check if widget is in viewport
=> ✨Nativery Ad Network Added observeIntersection

src/service/resources-impl.js, src/service/task-queue.js
=> Remove an unusedCache

build-system/pr-check/build-targets.js, build-system/pr-check/checks.js, build-system/tasks/check-owners.js, build-system/tasks/check-renovate-config.js, build-system/tasks/pr-check.js, gulpfile.js, package.json, yarn.lock
Closes https://github.com/ampproject/amphtml/issues/28473
Example output for a) A config with invalid JSON b) a config with illegal configuration values/keys c) a valid config
=> 🏗 Validate renovate config when changed

examples/doubleclick-targeting-macro.html, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Closes #25190
Experiment cleanup tracked in #28555
=> ✨Allow CLIENT_ID expansion in doubleclick json targeting 

examples/analytics-vendors.amp.html, extensions/amp-analytics/0.1/test/vendor-requests.json, extensions/amp-analytics/0.1/vendors/ibeatanalytics.json, extensions/amp-analytics/analytics-vendors-list.md
=> Ibeat analytics domain change

extensions/amp-story/amp-story.md
=> 📖 Update cover image size recommendation in amp-story.md

extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
Implementations for issue: https://github.com/ampproject/amphtml/issues/28403. Convert the full-width responsive to container-width responsive for desktop users.
PTAL. @charliereams, @calebcordry, @jridgewell
=> ✨Convert the full-width responsive to container-width responsive for desktop users.

builtins/amp-img.md
See https://github.com/ampproject/amphtml/issues/21912#issuecomment-617995565
=> Don't use webp as a fallback example

ads/ssp.js, test/unit/ads/test-ssp.js
Add new features to SSP amp ads.
✨ Resize ads by their real size
✨ Load ads one by one
✨ Make inside Ad centered vertically and horizontally in bigger wrapper
✅ Tests
=> feat: Resize ampad when SSP ad arive #SSP-2731

ads/24smi.js, ads/24smi.md, examples/ads.amp.html
- `data-blockid` support will remove unnecessary request in our new widgets
- Old code which uses `src` attribute still be working
/cc @ampproject/wg-ads
=> ✨ Add data-blockid to amp-embed type="24smi"

build-system/tasks/unit.js
Follow up to https://github.com/ampproject/amphtml/pull/26055#discussion_r359623254
=> 🏗 Always build vendor configs when running unit tests

ads/google/a4a/utils.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, src/service/resources-impl.js
I ported @choumx 's fix on https://github.com/ampproject/amphtml/pull/28458/files and added the experiment logic to experiment the effect of this fix.
=> 🐛Fix idle render issue while getLastDequeueTime() == 0

extensions/amp-connatix-player/0.1/amp-connatix-player.js, extensions/amp-connatix-player/0.1/test/test-amp-connatix-player.js
Update iframe domain and path for our existing amp-connatix-player.js component
=> 🔥  amp-connatix-player: Update iframe domain and path for our existing amp-connatix-player.js

ads/_config.js, ads/teads.js
Update of Teads ads CDN entry point and prefetch config to reflect infrastructure migration
=> ✨ Update Teads ads CDN entry point and prefetch config

build-system/tasks/extension-generator/index.js
=> 🐛async in generated extension test

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, builtins/amp-img.js, extensions/amp-video/0.1/amp-video.js, extensions/amp-video/0.1/test/test-amp-video.js, test/unit/test-amp-img.js, tools/experiments/experiments-config.js
Closes https://github.com/ampproject/amphtml/issues/17107
=> Cleanup blurry-placeholder experiment

src/service/resources-impl.js
Add two new experiments for reducing the amount of time spend doing `buildCallback` in each resources pass:
1. `build-in-chunks`: Limits the number of elements that may be built in a single pass
- Current chunk size is 10 elements
- Elements visible in viewport are excluded, and will be built regardless
2. `build-close-to-viewport`: Skips building elements unless they are within layout distance of viewport
=> 🚀 Defer/chunk buildCallback

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
=> SwG release 0.1.22.107

examples/amp-story/helloworld.html, extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/test/test-amp-story-page.js
=> 🐛Only start the page auto advancement when assets have loaded.

extensions/amp-next-page/1.0/service.js, extensions/amp-next-page/1.0/test/test-amp-next-page.js
=> 🐛 Delay amp-next-page init until first scroll

extensions/amp-recaptcha-input/amp-recaptcha-input.md
=> Explain a caveat on reCaptcha sitekey registration

3p/README.md, 3p/ampcontext.js, 3p/embedly.js, 3p/integration.js, ads/_a4a-config.js, ads/alp/handler.js, ads/google/utils.js, ads/inabox/inabox-messaging-host.js, examples/ads.amp.esm.html, examples/ads.amp.html, extensions/amp-a4a/0.1/a4a-variable-source.js, extensions/amp-a4a/0.1/real-time-config-manager.js, extensions/amp-a4a/0.1/test/test-real-time-config-manager.js, extensions/amp-a4a/amp-a4a-format.md, extensions/amp-a4a/rtc-documentation.md, extensions/amp-ad-custom/amp-ad-custom.md, extensions/amp-ad-exit/0.1/amp-ad-exit.js, extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js, test/unit/test-3p.js, test/unit/test-integration.js
=> Remove references to whitelist in ads

extensions/amp-story/1.0/amp-story-embedded-component.js, extensions/amp-story/1.0/amp-story-tooltip.css
#24972
Pending validation & docs
=> ✨ Add dark theme tooltip

extensions/amp-analytics/0.1/test/test-variables.js, extensions/amp-analytics/0.1/variables.js
=> Round SCROLL_TOP/SCROLL_LEFT to integer 

extensions/amp-ad-network-doubleclick-impl/0.1/safeframe-host.js
=> Make fluid resizing robust for iframe removal race conditions.

ads/google/a4a/utils.js, build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, tools/experiments/experiments-config.js
=> Launch no center css for ad container

extensions/amp-byside-content/amp-byside-content.md
Small amp-byside-content documentation update.
=> 📖 Update byside content md documentation

extensions/amp-video-iframe/amp-video-iframe.md
- Fixed how JW Player was written in documentation of this component (previous: JwPlayer)
=> 📖Correct capitalization of JW Player in amp-video-iframe.md

README.md
This adds a banner to README to let the community know about the OpenJS World & Collab Summit.
=> Adds a banner for OpenJS World & Collab Summit

extensions/amp-ad-network-doubleclick-impl/doubleclick-rtc.md
=> 📖 Add referrer to doubleclick RTC macro documentation

ads/google/csa.md
Closes #19207
This has been commented out for almost 2 years, I don't think anyone is missing it.
=> 🗑 Remove deprecated demo site

extensions/amp-form/amp-form.md, extensions/amp-list/amp-list.md
=> 📖  Document nested template approach in amp-list, amp-form

ads/google/csa.md
Update csa.md to include styleId since AFS Native is now the default for all CSA partners.
=> Update csa.md to include styleId

extensions/amp-story/1.0/amp-story-page-attachment.css
=> 🖍 Increase target size of swipe up

spec/amp-var-substitutions.md
=> 📖 Document all analytics advanced variable syntax

ads/google/a4a/utils.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-sticky-ad/1.0/amp-sticky-ad.css, extensions/amp-sticky-ad/1.0/amp-sticky-ad.js, tools/experiments/experiments-config.js
https://github.com/ampproject/amphtml/issues/22251
=> Add padding to amp-sticky-ad on all-screen iPhone

extensions/amp-video-docking/0.1/test/validator-amp-video-docking-amp-brid-player.html, extensions/amp-video-docking/0.1/test/validator-amp-video-docking-amp-brid-player.out, extensions/amp-video-docking/amp-video-docking.md
=> Adding docs/tests for brid-player dock

extensions/amp-list/amp-list.md
=> 📖  Formatting for useInitialPageSize blurb

src/service/ie-intrinsic-bug.js
https://github.com/ampproject/amphtml/pull/28806#discussion_r440383529
=> Fix copyright year in intrinsic bugfix

extensions/amp-autocomplete/amp-autocomplete.md
To describe the set of features available for websites and for emails.
/cc @bill97819
=> 📖 Add format filters for amp-autocomplete

extensions/amp-story/1.0/amp-story-system-layer.css, extensions/amp-story/1.0/amp-story-system-layer.js
=> 🚫 Hide story icons when ad is showing

src/service/video-manager-impl.js, src/video-interface.js
=> Pause other videos when a video gets played

extensions/amp-story/amp-story-analytics.md
Adds documentation regarding recently added features that we hadn't documented yet.
Closes #26693
=> [amp-story] Complete docs regarding analytics

ads/springAds.md, examples/ads.amp.html
=> 📖 springAds: update md file

build-system/global-configs/prod-config.json, tools/experiments/experiments-config.js
=> 🧪 Enable json targeting CLIENT_ID expansion at 1%

examples/visual-tests/amp-story/amp-story-bot-rendering.html
=> ✅ Visual tests with amp-video are now working.

build-system/global-configs/prod-config.json
=> Launch fie-init-chunking to 0.5 traffic in prod

build-system/tasks/karma.conf.js, build-system/tasks/runtime-test/runtime-test-base.js, package.json, yarn.lock
The introduced code generates JSON files with test results when a Travis build runs. A PR after this will have Travis POST those results to an application that will store them in a database.
=> 🏗 Generate test reports on Travis build runs.

extensions/amp-lightbox-gallery/0.1/test-e2e/test-open-close.js
=> ❄️ Disable flaky e2e test `AMP Lightbox Gallery Open/Close` > `should open/close lightbox`

extensions/amp-video-docking/0.1/amp-video-docking.js
=> 🐛Support non-single-doc AMP docs for video docking

third_party/zuho/README.amp, third_party/zuho/zuho.js
Modified original zuho.js file to integrate into ampproject:
- Removed all event handling, CSS, menu UI and unused projection mappings
- Refactored into module, exporting Renderer and Matrix classes 
This will be used in the new amp-story-360 extension (separate PR to come).
=> 🏗 Refactor zuho library to prepare for inclusion in upcoming extension

ads/rakutenunifiedads.md
Update document about ad code for rakutenunifiedads
=> Update document about ad code for rakutenunifiedads

extensions/amp-brightcove/0.1/test/test-amp-brightcove.js
=> 🗑 Remove unnecessary test

build-system/global-configs/OWNERS, build-system/global-configs/README.md, build-system/global-configs/experiments-config.json, build-system/pr-check/experiment-tests.js
Will change the build script to reflect this change
=> 🏗🧪 Remove `command` field from experiments-config.json

extensions/amp-story/1.0/page-advancement.js
Context: https://github.com/ampproject/amphtml/issues/28913
Fixes #28913
=> Removes Story loop attribute if media is used to auto advance.

build-system/test-configs/conformance-config.textproto, build-system/test-configs/dep-check-config.js, src/polyfills.js, src/polyfills/weakmap-set.js
WeakSet is unfortunately not supported in IE11.
=> Allow WeakMap

examples/visual-tests/amphtml-ads/helpers.js
Fixes https://github.com/ampproject/amphtml/issues/28975
=> ❄️ Make sure amphtml-ad visual test waits till loaded

ads/_config.js
=> Add prefetch to config

build-system/tasks/karma.conf.js, build-system/tasks/runtime-test/runtime-test-base.js, package.json, yarn.lock
Closes ampproject/amp-github-apps#885.
EDIT: The Travis build passed! See (https://travis-ci.org/github/ampproject/amphtml/builds/700200481).
This PR introduces code that only runs when the branch is pulled, so the above link is the only evidence that it doesn't break the build.
=> 🏗 Generate test reports on Travis builds.

build-system/global-configs/OWNERS
=> 🏗 Fix misconfigured OWNERS file

build-system/global-configs/experiments-config.json
=> Restore IntersectionObserverPolyfillInabox experiment

extensions/amp-next-page/1.0/service.js
=> 🐛 Missing condition fix for amp-next-page with JSON config

css/amp-story-player-iframe.css, src/amp-story-player/amp-story-player-iframe-pool.js, src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
Partial for #28416
Pending for follow-up:
Implements "Change the current story being displayed by the player" API for the player.
=> [amp-story-player ] Implement show() callback

3p/integration.js, ads/_config.js, ads/recreativ.js, ads/recreativ.md, examples/ads.amp.html, extensions/amp-ad/amp-ad.md
add support to amp-ad for recreativ type.
=> ✨ Add "Recreativ" ad network support to amp-ad

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, src/friendly-iframe-embed.js, test/unit/test-friendly-iframe-embed.js, tools/experiments/experiments-config.js
It has been launched on prod traffic for weeks and have behaved stably. The goal is to ship it with fewest behavioral changes on this PR, and then refactor it to provide for an easy to use API interface (moving the logics to chunk.js, for example).
=> 🚀 Launch FIE more chunking

validator/validator-main.protoascii
Pending discussion in #29016.
Closes #29016.
=> Validator: Allow referrerpolicy on amp-img

extensions/amp-story/1.0/amp-story-page.js
=> Fix video performance tracking on first story page.

build-system/global-configs/prod-config.json
The fix is here https://github.com/ampproject/amphtml/pull/28656
=> 🐛 Ramp up render-on-idle-fix

src/dom.js, src/shadow-embed.js, test/unit/test-shadow-embed.js
Fixes https://github.com/ampproject/amphtml/issues/29029
=> 🐛 Allow shadow-embed body to be redeclared

extensions/amp-story/1.0/amp-story-interactive-binary-poll.css
[Demo](https://binary-polls-debugging.web.app/examples/amp-story/interactives.html)
Context / Fixes #29085
=> 🐛 Binary polls overflow bug fix for ios safari.

ads/_config.js, ads/yandex.js
Updating the URL to Yandex ads script
=> Update Yandex ads script URL

extensions/amp-font/amp-font.md
Resolves [issue #27214](https://github.com/ampproject/amphtml/issues/27214)
=> added blurb about font-display and cleaned up language format

extensions/amp-consent/amp-consent.md
Add a section on the IAB TCF support
=> 📖 Document amp-consent TCF support

builtins/amp-img.md
Removes a duplicated phrase from the `amp-img` documentation.
=> 📖 Fix typo in amp-img documentation

src/service/resources-impl.js
=> Fix 'render on idle fix' experiment logic

src/amp-story-player/amp-story-player-impl.js
=> [amp-story-player] Set title to iframe for a11y

extensions/amp-social-share/1.0/social-share.css.js, extensions/amp-social-share/1.0/social-share.js
Removed default background color for a non-configured button (was previously gray)
=> ✨  [amp-social-share][bento] Update default background color

examples/social-share.amp.html, extensions/amp-social-share/1.0/amp-social-share.js
Social Share tracking issue: #28283
Update the experiment version from:
`amp-social-share-v2`
to:
`amp-social-share-bento`
Also update example file to point to latest version of Bento Component
=> ✨ [amp-social-share][bento] Update experiment version

examples/amp-story/player-local-stories.html
Adding a sample for the player using local stories since I use it often and others can find it useful as well.
=> Add player sample with local stories

extensions/amp-story/1.0/animation.js, extensions/amp-story/1.0/test/test-animation.js, extensions/amp-story/1.0/test/test-utils.js, extensions/amp-story/1.0/utils.js
=> 🐛 Fallback on invalid story animation attributes

extensions/amp-story/1.0/amp-story.js
Only play/pause background audio on visibilitystate change if story is unmuted.
Broken by #29178
=> Only play/pause background audio on visibilitystate change if story is unmuted.

extensions/amp-consent/0.1/consent-ui.js, extensions/amp-consent/amp-consent.md, test/manual/amp-consent/amp-consent-inline-postPromptUI.html
I ended up putting everything into the same PR : P
Let me know if you strongly prefer two PRs.
=> 🐛📖 Update postPromptUI bug fix & doc update

contributing/running-server-side-experiment.md
=> fix typo in `running-server-side-experiment.md`

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
Upgrades to the latest version of SwG.
=> SwG release 0.1.22.110

extensions/amp-subscriptions-google/amp-subscriptions-google.md
Fix bad quotes in amp-subscriptions-google.md
=> 📖  Fix bad quotes in amp-subscriptions-google.md

extensions/amp-analytics/0.1/test/vendor-requests.json, extensions/amp-analytics/0.1/vendors/deepbi.json
=> ✨ Add linker to deepbi

build-system/global-configs/canary-config.json, src/service/resources-impl.js
I'd love to simplify resources service. This PR attempts to simplify the task scheduling by removing the `calcTaskTimeout` function and seeing if it negatively affects performance.
The purpose of `calcTaskTimeout` is to ensure that lower priority (usually out of viewport) elements do not have CPU/network contention with higher priority tasks. My hypothesis is that a similar goal is already addressed via `calcTaskScore`.
I conducted measurements with this experiment on and off for 3 websites: article.html, images.html, and a pinterest puppy url. I refreshed the page 10 times, had 6x CPU slowdown, and recorded some basic stats via:
`copy(JSON.stringify(performance.getEntriesByType("mark").map(e => [e.name, e.startTime]).flat()))`.
All the results are in the appendix.
**question for the …
=> Resources: remove task timeouts under an experiment

extensions/amp-story/1.0/amp-story-interactive-quiz.css
To unify our UI motion this will use our duration and easing variables.
=> 🐛 Make duration and easing consistent for percent bar animation.

test/unit/test-amp-story-player.js
Some tests were not running correctly/being flaky.
=> 🐛 [amp-story-player] Fix player tests

examples/autocomplete.amp.html, extensions/amp-autocomplete/0.1/amp-autocomplete.js, extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
=> 🐛  amp-autocomplete `query` should respect [src] mutations

src/service/history-impl.js, src/service/standard-actions-impl.js, test/unit/test-history.js, test/unit/test-standard-actions.js
Implements https://github.com/ampproject/amphtml/issues/5225
=> ✨ Amp Actions: AMP.goBack action should call history.back

extensions/amp-story/1.0/amp-story-store-service.js
Does what it says on the tin. Fixes jank issues with amp-story-360 page transitions on desktop player.
=> 🐛 [amp-story-store-service] add state propery comparison for pageSize

extensions/amp-story/1.0/amp-story-interactive-binary-poll.css
Removes leftover styling from a previous transition method.
=> 🚮  Binary Polls: Removes dead flex styling.

src/amp-story-player/amp-story-player.js
=> [amp-story-player] Use onDocumentReady instead of window.onload

build-system/global-configs/prod-config.json
Related to #25428. Trying again now that #29226 is in.
=> Ramp "intersect-resources" to 100% (second try)

extensions/amp-access-laterpay/amp-access-laterpay.md
This unbreaks amp.dev's build.
/cc @robinvanopstal @sebastianbenz
=> 📖 Fix corrupt tip in amp-access-laterpay

src/service/resource.js
Now that I've collected enough data to debug, we no longer need to report this error.
Re: https://github.com/ampproject/amphtml/issues/29078
=> Remove error report for startLayout flow

extensions/amp-mowplayer/amp-mowplayer.md
=> Updated documentation to explain component

extensions/amp-consent/0.1/consent-config.js
=> 📖 Document `promptIfUnknownForGeoGroup` as legacy

.renovaterc.json
=> 🏗 Move breaking changes instructions to all Renovate PRs

3p/integration.js, ads/_config.js, ads/yektanet.js, ads/yektanet.md, examples/ads.amp.html, extensions/amp-ad/amp-ad.md
Support for Yektanet ad platform is added to amp-ad.
=> ✨  Add Yektanet ad platform support to amp-ad.

src/service/viewer-impl.js
=> 🐛 Mark user action in non-visible doc as expected error

extensions/amp-experiment/1.0/amp-experiment.js, extensions/amp-experiment/1.0/test/test-amp-experiment.js
=> 🐛amp-experiment: Do not throw dev error when experiment is not turned on

examples/analytics-vendors.amp.html, extensions/amp-analytics/0.1/test/vendor-requests.json, extensions/amp-analytics/0.1/vendors/ibeatanalytics.json
=> added new parameters for ibeat analytics

extensions/amp-story/1.0/pagination-buttons.css
This code was not providing any functional value.
=> 🚮 Removes unnecessary pseudo element on pagination buttons.

css/ampshared.css, examples/auto-ads.amp.html, extensions/amp-auto-ads/0.1/amp-auto-ads.js, extensions/amp-auto-ads/0.1/anchor-ad-strategy.js, tools/experiments/experiments-config.js
Tests to be fixed.
Closes #27068
=> Move ads placement into layoutCallback of amp-auto-ads

src/amp-story-player/amp-story-player-impl.js
=> [amp-story-player] Don't drag when only one story is present

validator/validator-main.protoascii
Part 2 of: https://github.com/ampproject/amphtml/pull/29445 since I forgot about amp-form 😬  
context: b/146428532
=> amp-form: allow xssi-prefix in email

extensions/amp-bind/amp-bind.md
We should concat something to the array.
=> 📖 Update concat code snippet

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js, extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js, third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
- Update dependency rollup to v2.23.0 (#1183)
- Update dependency regenerator-runtime to v0.13.7 (#1182)
- Update dependency rollup to v2.22.2 (#1180)
- Update dependency codecov to v3.7.2 (#1179)
- Update dependency regenerator-runtime to v0.13.6 (#1178)
=> SwG release 0.1.22.113

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
send the experiment ids for the module/nomodule runtime experiment and its control ids for doubleclick and adsense implementations
=> Add modulenomodule eid

build-system/tasks/storybook/amp-env/webpack.config.js, build-system/tasks/storybook/preact-env/webpack.config.js
Fixes an issue where webpack doesn't understand the `??` operator.
=> 🏗 Transpile latest JS features for storybook

extensions/amp-analytics/amp-analytics.md
@zhouyx Anything else you think I should add here?
=> 📖 TimerSpec documentation clarification

build-system/global-configs/prod-config.json
Rasta looks good starting 7/21 (when our client side exp fixes went to prod)
https://rasta.corp.google.com/#/metrics?label=_:rNn4Fj2PMYB5olg3ujouGX3v_s8
=> 🧪Ramp up json targeting exp

extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story-page.js, extensions/amp-story/1.0/test/test-amp-story.js
Context at https://github.com/ampproject/amphtml/issues/29371
Fixes https://github.com/ampproject/amphtml/issues/29371
=> Fix unmuting through setDocumentState.

3p/ampcontext.js, extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js, test/unit/test-amp-context.js
Do this so we know how much these interfaces are being used by advertisers.
=> ✨Add metrics for onResizeSuccess/onResizeDenied usage

extensions/amp-autocomplete/amp-autocomplete.md
=> 📖 amp-autocomplete: Add note about authenticating requests

extensions/amp-script/amp-script.md
I'm updating the documentation for amp-script. This is the first part of that effort!
@CrystalOnScript , I've never done this sort of overhaul before. This is just the beginning. As I go, I'll work to pull the formatting closer to [your new standard](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/extension-generator/extension-doc.template.md). Let me know though if I'm doing this right!
=> Updating amp-script documentation, part 1

extensions/amp-list/amp-list.md
/cc @sebastianbenz @patrickkettner @CrystalOnScript @robinvanopstal
=> 📖 amp-list: fix amp.dev docs syntax errors

extensions/amp-story/1.0/test/test-amp-story-page.js
=> [amp-story] Add amp-audio unit test

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/head-validation.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-a4a/0.1/test/test-head-validation.js, src/utils/stream-response.js, test/unit/utils/test-stream-response.js
Hopefully last big PR :) 
Part of #27189
=> ✨Introduce fallback logic for remove signing

src/service/viewer-impl.js, test/unit/test-viewer.js
=> 🐛 Fix: AmpDocShadow shouldn't become visible on user interaction

3p/ampcontext.js, build-system/test-configs/dep-check-config.js, extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js, test/unit/test-amp-context.js
Changing the requestResize API to return promise. This depends on https://github.com/ampproject/amphtml/pull/29532 to function properly on older browsers.
=> ✨ Change requestResize interface to return promise

test/unit/test-amp-story-player.js
not sure how this bypassed checks in https://github.com/ampproject/amphtml/pull/29411
=> remove unused function

ads/yahoofedads.md
Move section id from mandatory field to optional.
=> 📖 Ajust options in document of yahoofedads.

extensions/amp-story/1.0/amp-story-interactive.css
=> 🐛 [Story Interactive] Default pointer in post-select state for interactive options.

extensions/amp-analytics/0.1/amp-analytics.js, src/service/resource.js
=> Reduce number of AMP_TOP errors on iframe unloading

extensions/amp-inputmask/0.1/mask-impl.js, extensions/amp-inputmask/0.1/test/test-mask-impl.js
Fixes https://github.com/ampproject/amphtml/issues/29499
Causes a bug due to: https://github.com/google/closure-compiler/issues/2397
=> 🐛  inputmask: remove static from fn using `this`

extensions/amp-story/1.0/history.js
=> [amp-story] Disable local storage when provided via fragment parameter

extensions/amp-kaltura-player/0.1/amp-kaltura-player.js, extensions/amp-kaltura-player/0.1/test/test-amp-kaltura-player.js, extensions/amp-kaltura-player/0.1/test/validator-amp-kaltura-player.html, extensions/amp-kaltura-player/0.1/test/validator-amp-kaltura-player.out, extensions/amp-kaltura-player/OWNERS, extensions/amp-kaltura-player/amp-kaltura-player.md, extensions/amp-kaltura-player/validator-amp-kaltura-player.protoascii
Implement serviceUrl http://player.kaltura.com/docs/api#kWidget.apiOptions
This is needed to use amp-kaltura with kaltura comunity edition, also this is a must have for TCF v2 https://iabeurope.eu/tcf-2-0/ .
Otherwise if you implement kaltura ce over iframe you can't consent your users.
=> ✨ kaltura: add serviceUrl

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Launch the experiment to 50% users. The metrics appears good.
=> 🧪 Launch render-on-idle-fix

validator/nodejs/README.md, validator/nodejs/package.json
Released amphtml-validator@1.0.32
=> Update validator nodejs details

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
The experiment results appear neutral.
=> ✨ Launch sticky-ad-padding-bottom

build-system/global-configs/prod-config.json
ramp up the experiment to 5% to gather more data
=> Ramp up ampdoc-fie experiment to 10% (5% exp, 5% control) in prod.

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, src/service/resources-impl.js, tools/experiments/experiments-config.js
Fixes https://github.com/ampproject/amphtml/issues/25203
=> 🚮 Cleanup layoutbox-invalidate-on-scroll experiment

extensions/amp-story/1.0/test/validator-amp-story.html, extensions/amp-story/1.0/test/validator-amp-story.out, extensions/amp-story/amp-story.md, extensions/amp-story/validator-amp-story.protoascii
Context: https://github.com/ampproject/amphtml/issues/28992
Fixes https://github.com/ampproject/amphtml/issues/28992
=> Adds entity metadata support.

src/friendly-iframe-embed.js
=> Reduce unloading errors for FIE

3p/integration.js, ads/_config.js, ads/glomex.js, ads/glomex.md, examples/ads.amp.html, extensions/amp-ad/amp-ad.md
Integrate glomex video player to `amp-ad`
Regarding CLA:
I've signed a personal one for a different PR but we (glomex) are also in the process of signing one as a company.
cc @ampproject/wg-ads-reviewers
=> ✨  Add amp-ad support for glomex

build-system/server/routes/a4a-envelopes.js, build-system/server/server-a4a-template.html, build-system/tasks/e2e/amp-driver.js, build-system/tasks/e2e/describes-e2e.js
Introduce new "no signing experiment" env and run all e2e ads test in this environment.
#27189
=> 🧪Enable E2E Tests for no signing exp.

test/integration/test-amphtml-ads.js
Still unreliable on linux GH actions :(
=> 🐛 Remove flaky no signing integration test

build-system/compile/post-closure-babel.js, package.json, yarn.lock
The new major of Terser returns `Promise<MinifyOutput>` from `minify(...)`.
=> 📦 Upgrade to Terser 5

extensions/amp-bind/amp-bind.md, spec/amp-email-actions-and-events.md
It's banned in AMP in Email spec.
/to @caroqliu
=> 📖  Remove pushState documentation for AMP for Email

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Experiment added in #29248, launching with 5% holdback
=> AdSense/Doubleclick Launch Adx/Ady Rounding

3p/integration.js, ads/_config.js, ads/firstimpression.js, ads/firstimpression.md, extensions/amp-auto-ads/0.1/ad-network-config.js, extensions/amp-auto-ads/0.1/firstimpression.io-network-config.js, extensions/amp-auto-ads/amp-auto-ads.md
Integrate FirstImpression.io to amp-auto-ads and amp-ad
/cc @tlong2
=> ✨ Add FirstImpression.io to amp-ad and amp-auto-ads

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Dial up the Adsense ad size optimization experiment to 5%.
PTAL: @rsimha, @lannka, @calebcordry
=> 🧪 Experimental code: Dial up the Adsense ad size optimization experiment to 5%.

extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story.js
Rewind last story page on visibilitystate inactive, ie: when document is swiped away.
Fixes #28927 
Fixes #28650
=> Rewind last story page on visibilitystate inactive.

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, src/service/fixed-layer.js, test/unit/test-fixed-layer.js, tools/experiments/experiments-config.js
Closes https://github.com/ampproject/amphtml/issues/18897
=> Cleanup hidden-mutation-observer experiment

extensions/amp-story/1.0/media-performance-metrics-service.js
Noticed this TODO comment from @gmajoulet to use a WeakMap for this service, so I implemented the small change.
=> ♻️ Fix todo by using a WeakMap

test/integration/test-amp-carousel.js
=> ❄️ Skip flaky amp-carousel test

examples/amphtml-ads/visibility-ad.a4a.html, extensions/amp-analytics/0.1/requests.js, extensions/amp-analytics/0.1/visibility-manager.js, extensions/amp-analytics/0.1/visibility-model.js
As we agreed, collect element size and viewport size at maximum intersect ratio, if we find the active view has element size 0 or viewport size 0.
=> Collect additional visible info for debugging

examples/amp-story/interactives.html, extensions/amp-story-interactive/1.0/amp-story-interactive-poll.css, extensions/amp-story-interactive/1.0/amp-story-interactive-quiz.css, extensions/amp-story-interactive/1.0/amp-story-interactive-results.css, extensions/amp-story-interactive/1.0/amp-story-interactive.css, extensions/amp-story/1.0/amp-story.css
Adding a `chip-style="transparent"` style that can be combined with a dark or light theme to hide the options chip.
Works in polls, quizzes and results
=> ✨Added interactive transparent styles

extensions/amp-social-share/1.0/social-share-config.js, extensions/amp-social-share/1.0/social-share.js, extensions/amp-social-share/1.0/social-share.type.js
- Added prop types
- Updated type definitions throughout
- Used `obj.key` operator instead of `obj['key']` when possible
=> ♻️ [bento][amp-social-share] Add prop types and update type definitions for Social Share and basic cleanup

validator/build.py, validator/js/nodejs/README.md, validator/js/nodejs/index_test.js
=> Fixing indents to match cl

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
=> Ramp json targeting expansion experiment to 100%

spec/amp-actions-and-events.md
=> Docs: Add caveat about AMP.navigateTo

extensions/amp-story-interactive/README.md
The readme will be the main entrypoint to the documentation
Press "display rich diff" icon on diffs to view the rendered version
=> 📖 Added readme to interactive components

extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
Fixes #29759
the bug was introduced by #28929
=> Fix 3p ad viewportCallback

extensions/amp-story/1.0/animation-presets.js
Fixes a comment spelling typo.
=> 🐛 Fix typo

extensions/amp-script/amp-script.md
Otherwise it gets interpreted as HTML!
/cc @samouri
=> Surround <amp-list> with backticks

extensions/amp-script/0.1/amp-script.js
Fixes https://github.com/ampproject/amphtml/issues/29860
=> amp-script: dont assign onerror if failed to init

extensions/amp-bind/amp-bind.md
This paragraph should be edited for clarity too... I just fixed the grammar.
=> Small grammar fixes

test/fixtures/3p-ad.html, test/integration/test-amp-ad-3p.js
=> Improve 3p ad IntersectionObserver API integration test

ads/README.md
To reflect the change on the use of promise as response
=> Update document for amp context requestResize API

src/service/viewer-impl.js
Fixes https://github.com/ampproject/amphtml/pull/29906#discussion_r475832030
=> 🐛 Fix viewer queueing for responders that don't return promises

validator/js/nodejs/README.md, validator/js/nodejs/package.json
update README and version for nodejs
fixes #29941
=> update nodejs location

validator/js/gulpjs/README.md, validator/js/gulpjs/package.json
updates repository and README for validator/js/gulpjs/
=> update gulpjs location

build-system/babel-config/post-closure-config.js, build-system/babel-config/pre-closure-config.js, build-system/compile/bundles.config.js, build-system/compile/compile.js, build-system/compile/post-closure-babel.js, build-system/tasks/dist.js, build-system/tasks/extension-helpers.js
This PR tries to correct the fact that the SxG build is larger than the ESM build.
=> 🚀 SxG binary size reduction.

examples/amp-story/player-amp.html, extensions/amp-story-player/0.1/amp-story-player.md
Closes #29312
Pretty much what is already said in https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md , but cutting off any unsupported/unreleased features for the AMP version
=> 📖  Docs for AMP version of the amp-story-player

src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
* emits an event when a `CURRENT_PAGE_ID` message is received
* includes progress of the story
Part of #29394
=> ✨  [amp-story-player] React to CURRENT_PAGE_ID updates

3p/integration.js, ads/_config.js, ads/playstream.js, ads/playstream.md, examples/ads.amp.html
Implemented Ad Integration for PlayStream Ad Network
=> ✨Enabled PlayStream Integration for Ads

extensions/amp-story/1.0/test/validator-amp-story.html, extensions/amp-story/1.0/test/validator-amp-story.out, extensions/amp-story/amp-story.md, extensions/amp-story/validator-amp-story.protoascii
Context at https://github.com/ampproject/amphtml/issues/29991
Fixes https://github.com/ampproject/amphtml/issues/29991
=> Story generator meta tag validation.

extensions/amp-auto-ads/0.1/denakop-network-config.js, extensions/amp-auto-ads/0.1/test/test-denakop-network-config.js
We are migrating our customers to a new, more robust platform and for that it will be necessary to add a new endpoint url
=> ✨ amp-auto-ads extension: New Denakop enpoint URL

extensions/amp-youtube/amp-youtube.md
minor typos that are currently blocking the build
=> fix some typos in amp-youtube docs

css/ampshared.css
Tested using https://output.jsbin.com/wiqobez/1/quiet
Fixes https://github.com/ampproject/amphtml/issues/29479
=> Make SSR'd img inside unbuilt amp-img visible

examples/amp-story/advance-after-background-audio.html, examples/amp-story/amp-audio.html, extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/test/test-amp-story-page.js
Closes #29623
temp demos
https://story-player-demo.web.app/examples/amp-story/advance-after-background-audio.html
https://story-player-demo.web.app/examples/amp-story/amp-audio.html
=> 🐛  Fix background audio race conditions

extensions/amp-story-education/0.1/amp-story-education.css
Appears to be from values marked `!important` overriding updates in `@keyframes`.
Context / Fixes #30025
=> 🐛 Remove values overriding keyframes. Remove comma typo

extensions/amp-story/1.0/amp-story.css
CSS targeting was incorrect for RTL screen reader back button.
=> 🐛 Fix RTL display of mobile screen reader back button 

ads/google/a4a/test/test-utils.js, ads/google/a4a/utils.js, build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
=> Cleanup AdSense/Doubleclick round adx/ady

examples/visual-tests/amp-story/amp-story-tooltip.html, examples/visual-tests/amp-story/amp-story-tooltip.js, extensions/amp-story/1.0/amp-story-embedded-component.js, extensions/amp-story/1.0/amp-story-page.js
=> 🖍  [amp-story] Fix vertical margins for tweets

src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
=> ✨ [amp-story-player] adds `noNextStory` event

src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
=> ✨ [amp-story-player] adds `noPreviousStory` event

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js, extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
=> ♻️ amp-subscriptions-google: Renames glaa_ params to gaa_

contributing/DESIGN_PRINCIPLES.md, contributing/contributing-code.md, contributing/getting-started-e2e.md
Add pointers to accessibility in some of the most appropriate sections of the initial documentation.
Includes addition of a new design principle around inclusivity/accessibility.
=> ♿ TetraLogical: Accessibility notes for the documentation

extensions/amp-story-interactive/README.md
Improved the README on how publishers can size the components, read changes for more info
=> 📖 Improved readme for sizing interactive components

README.md
Remove survey as end of Quarter
=> Remove survey

extensions/amp-story/1.0/_locales/default.js, extensions/amp-story/1.0/_locales/en.js
=> ♿ Edit tip wordage

src/amp-story-player/amp-story-player-impl.js
=> [amp-story-player] Add allow=autoplay to iframes 

extensions/amp-story/1.0/amp-story-system-layer.css
=> 🐛 Let buttons flow RTL naturally

ads/google/a4a/utils.js, build-system/global-configs/prod-config.json, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, src/service/resources-impl.js
Wait till https://github.com/ampproject/amphtml/pull/29660 rolls out and removes this experiment code for render-on-idle-fix.
=> 🚮  Remove RENDLE_ON_IDLE experiment logic

extensions/amp-timeago/1.0/amp-timeago.js, extensions/amp-timeago/1.0/storybook/Basic.amp.js, extensions/amp-timeago/1.0/storybook/Basic.js, extensions/amp-timeago/1.0/test/test-amp-timeago.js, extensions/amp-timeago/1.0/timeago.js, extensions/amp-timeago/1.0/timeago.type.js, src/preact/base-element.js
=> Timeago: fix placeholder and wrapper

build-system/global-configs/canary-config.json
=> 🧪 Turn off no signing in canary

.github/ISSUE_TEMPLATE/page-experience.md
Add template for Pixi to file issues on Perf WG
This is just the template - we will need to add the placeholders fo where the values go next
=> Add page-experience.md

extensions/amp-ad-network-nws-impl/OWNERS
This is a newly added fast fetch extension.
cc/ @danielstockton
=> ✨Add new owners file for NWS fast fetch

extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Part of #25190 
Closes #28555
https://experiments.corp.google.com/#/portal/experiments/analysis?label=_:2DdGB2glg3f7ZOQmsZEyBTwQ0Go
=> 🧪Fully launch json targeting expansion experiment.

extensions/amp-date-countdown/1.0/storybook/Basic.js
First draft of preact storybook for amp-date-countdown
=> 📖  [bento][amp-date-countdown] Preact storybook for amp-date-countdown

css/amp-story-player-iframe.css
Closes #30236
Closes https://github.com/ampproject/amphtml/issues/30213
=> 🐛[amp-story-player] Fix CSS bug

extensions/amp-a4a/0.1/callout-vendors.js, extensions/amp-a4a/rtc-documentation.md, extensions/amp-a4a/rtc-publisher-implementation-guide.md
Purch has been acquired by Future Plc 2 years ago. We plan to slightly move from our legacy "purch" vendor to a new one "future".
=> ✨ amp-a4a: declare Future Plc as a new vendor

extensions/amp-iframe/0.1/amp-iframe.js, extensions/amp-iframe/0.1/test/test-amp-iframe.js
=> amp-iframe: Hide overflow element on resize

extensions/amp-analytics/0.1/test/test-amp-analytics.js, extensions/amp-analytics/0.1/test/test-visibility-manager.js, extensions/amp-analytics/0.1/visibility-manager.js
Reverts ampproject/amphtml#30105
=> Revert "🐛 Report zero visibility for zero size element"

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Dial up the Adsense ad size optimization experiment to 10%.
PTAL: @lannka, @kristoferbaxter, @calebcordry, @charliereams
=> 🧪 Experimental code: Dial up the Adsense ad size optimization experiment to 10%.

src/preact/base-element.js, test/unit/preact/test-base-element.js
This is useful when DOM nodes aren't drawn so they're used only for render definition on a Preact component, e.g.
```html
<amp-video>
<source src="...">
</amp-video>
```
With component config:
```js
AmpVideo['children'] = {
'sources': {
name: 'children',
selector: 'source',
single: false,
clone: true,
},
};
```
Would then receive as part of `props`:
```js
{children: [<source src="...">]}
```
This is a shallow copy, which is enough for `amp-video`.
For other use cases, it should be considered that:
- indirect descendants are not cloned
- mutations done on children are not observed (but the AMP element's `childList` is, so nodes can be swapped.)
=> ✨ Clone children as VNodes into component call

extensions/amp-ad/0.1/amp-ad-3p-impl.js
Tests forthcoming on separate PR. Need to reorganize it a bit.
=> Wait for scrolling before loading sticky ad

extensions/amp-a4a/0.1/callout-vendors.js, extensions/amp-a4a/rtc-documentation.md, extensions/amp-a4a/rtc-publisher-implementation-guide.md
Adding Adpushup to RTC callout vendors list
=> Added Adpushup callout_vendors.js

.github/ISSUE_TEMPLATE/page-experience.md
=> Remove cache and origin separation

extensions/amp-social-share/1.0/amp-social-share.js, extensions/amp-social-share/1.0/social-share.js
=> Social Share: update wrapper and propagate size from the AMP element

build-system/tasks/storybook/package.json
=> Upgrade @ampproject/storybook-addon to 1.1.2

3p/integration.js, ads/_config.js, ads/_fakedelayed_.js, ads/_fakedelayed_.md, examples/amp-ad/sticky-creative.html, examples/amp-ad/sticky.html, examples/amp-ad/sticky.js
In order to make it easier to test sticky ads on delayed fetched ad vendors.
=> ✨ Add a delay fetched fake vendor for test purposes

examples/amp-consent/cmp-vendors.amp.html, extensions/amp-consent/0.1/cmps.js, extensions/amp-consent/amp-consent.md, extensions/amp-consent/cmps/onetrust.md
- To add Onetrust to the CMP list.
- Added documentation:
- Instructions
- Example
-  Example on cmp-vendors page.
@zhouyx
=> Add OneTrust CMP

extensions/amp-story/1.0/amp-story-embedded-component.js
=> 🐛[amp-story] Only close expanded element when appropriate

extensions/amp-analytics/0.1/vendors/deepbi.json
=> 🔥 Disable linker by default

test/integration/test-css.js
This is the only (enabled) IE11 test that appears to be a genuine failure. Merits looking at in the future, but in the interim, this PR configures the `describes` to skip IE for now.
It looks like this test was disabled for IE originally (which `.configure().run()` does by default, if I understand correctly) but was re-enabled in #29038 when the `.configure()` call was dropped as part of the Sauce Labs cleanup.
Failing test:
=> ✅ Configure CSS integration tests to skip IE11

test/integration/test-extensions-loading.js
Whenever this code was added (quite a long time ago), the function `createFixtureIframe` was called without the second parameter specifying the desired iframe height, leading to downstream code calling `iframe.height = initialIframHeight` where `initialIframeHeight` was `undefined`. It appears that in most browsers, doing so results is some reasonable fallback. In IE11 (or at least the version of the code output by Browserify) the result of this is an error, which was failing five of the tests under IE11.
Part of broad effort under https://github.com/ampproject/amphtml/issues/28152 to enable IE11 integration tests as blocking 
Example log output of test failures:
=> ✅  Fix 5 failing IE11 tests because of missing argument

build-system/pr-check/cross-browser-tests.js, testing/iframe.js
This PR will allow failing IE11 integration tests to block a PR. This is the endcap on the series of PRs listed below, forming a collective effort under #28152
DO NOT SUBMIT this PR until the following test fixes are submitted:
> Note: Since this makes IE11 integration tests blocking, it should be impossible to submit this until it's merged/rebased on top of the above fixes.
=> 🏗 Allow IE integration tests to block the build

src/preact/base-element.js, test/unit/preact/test-base-element-mapping.js
=> ✨ PreactBaseElement['staticProps']

extensions/amp-date-display/1.0/date-display.type.js, extensions/amp-fit-text/1.0/fit-text.type.js, extensions/amp-selector/1.0/selector.type.js, extensions/amp-timeago/1.0/timeago.type.js, src/preact/context.type.js
=> Fix default props

src/error.js
Small changes to enable error reporting for SXG build, based on the ESM build.
=> 🏗 Enable Error Reporting for SXG.

extensions/amp-video/1.0/video-wrapper.js, src/preact/utils.js
=> Remove useMountEffect

examples/amp-consent/diy-consent.html, extensions/amp-consent/0.1/consent-ui.js, extensions/amp-consent/0.1/test/test-consent-ui.js
=> Consent: Allow promptUISrc iframe to run in the background for 1 second after close

extensions/amp-story/1.0/pagination-buttons.css
=> 🔥Remove pointer events on back button when bookend is open.

.gitignore, build-system/tasks/e2e/describes-e2e.js, build-system/tasks/e2e/index.js, build-system/tasks/serve.js
When running `gulp e2e --coverage`, after each test completes, coverage data will be reported to the endpoint provided by `istanbul-middleware` which aggregates the coverage across all tests. Before the test server shuts down, it then downloads the aggregated coverage report and opens the coverage explorer UI.
Builds on #30004 and #30111. Won't work properly until #30099 is also merged, but won't break anything either (both because nothing is using the `--coverage` flag and because the test workflow is not dependent on the server endpoint), so it is safe to review and submit independently. PR #30128 contains the merged version of these two sets of changes, so you can check out the branch on that PR if you'd like to test/experiment locally.
Because some of this PR involved reorganizing …
=> 🏗 Enable coverage reports on e2e testing

extensions/amp-story-360/0.1/amp-story-360.js
=> ✨Pause animation on long press.

build-system/tasks/e2e/index.js
Removes a reference to `doBrowse` added by e2e coverage PR, since that helper was removed while it was in review. Upcoming PR will migrate `opn` to `open`
Fixes build error that occurred once merged: https://travis-ci.org/github/ampproject/amphtml/jobs/731701398
=> 🏗 Replace removed `doBrowse` with `opn`

extensions/amp-base-carousel/1.0/amp-base-carousel.js, extensions/amp-date-display/1.0/amp-date-display.js, extensions/amp-fit-text/1.0/amp-fit-text.js, extensions/amp-timeago/1.0/amp-timeago.js, src/preact/base-element.js
Not a "problem solved" yet. But I think this is a step forward in clarifying things. Also, I think, @alanorozco, you wanted to do this anyway?
=> Clarify layoutSizeDefined and provide default isLayoutSupported

extensions/amp-mustache/amp-mustache.md
Issue mentioned is now [closed.](https://go.amp.dev/issue/8395)
=> 📖 No longer an open proposal

extensions/amp-consent/amp-consent.md
=> 📖 Document metatag consent blocking

examples/amp-story-360.amp.html, extensions/amp-story-360/0.1/amp-story-360.css, extensions/amp-story-360/0.1/amp-story-360.js
=> 🐛 Activate button above content.

extensions/amp-consent/0.1/amp-consent.js
Closes https://github.com/ampproject/error-reporting/issues/11
=> 🐛  Catch rejected promise in getConsentRemote

extensions/BUILD, extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out.cpponly, extensions/amp-geo/0.1/test/validator-amp-geo.cpponly, extensions/amp-geo/0.1/test/validator-amp-geo.out.cpponly, extensions/amp-mustache/0.1/test/validator-amp-mustache.out.cpponly, extensions/amp-mustache/0.2/test/validator-amp-mustache.out.cpponly, extensions/amp-mustache/0.2/test/validator-json-not-in-template.out.cpponly, validator/BUILD, validator/cpp/engine/BUILD, validator/cpp/engine/WORKSPACE, validator/cpp/engine/scripts/BUILD, validator/cpp/engine/scripts/validator_example.cc, validator/cpp/engine/testing-utils.cc
2-3 tests are still broken. Will fix in follow up change as they are not related to file path issues.
=> Fix validator_test partially

testing/describes.js
Alternative to https://github.com/ampproject/amphtml/pull/30488
=> Remove dependency on the global window for impression tracking

extensions/amp-story-player/validator-amp-story-player.protoascii
=> [amp-story-player] Update validation

3p/ampcontext-lib.js, 3p/iframe-transport-client-lib.js, 3p/integration.js, 3p/recaptcha.js, ads/google/imaVideo.js, ads/speakol.js, ads/uas.js, extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, test/unit/ads/test-aduptech.js
=> Remove a few eslint disable rules as unnecessary

build-system/compile/bundles.config.js, extensions/amp-accordion/1.0/accordion.js, extensions/amp-accordion/1.0/accordion.type.js, extensions/amp-accordion/1.0/amp-accordion.css, extensions/amp-accordion/1.0/amp-accordion.js, extensions/amp-accordion/1.0/storybook/Basic.amp.js, extensions/amp-accordion/1.0/storybook/Basic.js, extensions/amp-accordion/1.0/test/test-accordion.js, extensions/amp-accordion/1.0/test/test-amp-accordion.js, src/preact/base-element.js, src/utils/id-generator.js, src/utils/object.js, test/unit/test-object.js
=> Accordion bento component outline

.travis.yml
This is a stopgap fix until #30518 is implemented.
=> 🏗 Use `yarn` v1.22.5 on Travis

extensions/amp-base-carousel/0.1/test/test-carousel.js
=> ❄️ Skip Flaky Carousel Tests

extensions/amp-bind/0.1/bind-impl.js, extensions/amp-gwd-animation/0.1/amp-gwd-animation-impl.js, src/dom.js, src/service/hidden-observer-impl.js, src/service/navigation.js, src/service/standard-actions-impl.js, src/service/url-impl.js, src/shadow-embed.js, test/unit/test-shadow-embed.js
=> ✂️  ampdoc-fie cleanup: remove unused constructor args for doc/fie services

build-system/common/travis.js, build-system/pr-check/utils.js
=> 📖 Add @function JSDoc annotation to wrapped helpers

validator/README.md
=> 📖 Update instructions to install openjdk on macOS

src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
Closes #29368
Prework for https://github.com/ampproject/amphtml/issues/29864
This should be a no-op.
=> ♻️ [amp-story-player] Migrate this.stories_ to new StoryDef 

test/integration/test-actions.js, test/integration/test-amp-img.js, test/integration/test-toggle-display.js, testing/describes.js, testing/test-helper.js
Part of https://github.com/ampproject/amphtml/issues/24144
Started out just migrating a couple integration test suites from deprecated top-level `describe` to `describes.integration`. In the process, ended up doing a lot of general code cleanup/modernization, including migrating some old Promise logic to async/await and allowing integration tests to opt into IE11 (previously only deprecated `describe` blocks could)
=> ✅  Modernize test-actions, test-toggle-display, and integration test infra

extensions/amp-connatix-player/0.1/amp-connatix-player.js
Handle amp-consent for our existing amp-connatix-player.js
=> 🔥 amp-connatix-player: Handle amp-consent for our existing amp-connatix-player.js

extensions/amp-story/1.0/amp-story-system-layer.js, extensions/amp-story/1.0/amp-story.css, extensions/amp-story/1.0/amp-story.js
Closes #29933 
When the embedMode hides the audio UI, hide the video-eq as well
=> ✨ Hide video eq when no-audio embedMode

validator/OWNERS
Require validator owners to approve changes.
=> Update validator owners

build-system/tasks/presubmit-checks.js
The wrapper utility uses vendor prefixes, which we don't need now due to browser support.
=> 🏗 Remove fullscreenEnter wrapper check from denylist

css/amp-story-player-iframe.css, src/amp-story-player/amp-story-player-impl.js
1/n partial for #30031
Consumes JSON configuration from player when setting up messaging with the iframe.
Starts adding TODOs to delete code for the `exit-control` API which will be replaced by this new API.
=> ✨ [amp-story-player] Consume JSON configuration from the player

build-system/test-configs/dep-check-config.js, extensions/amp-story-auto-ads/0.1/story-ad-page.js, extensions/amp-story-auto-ads/0.1/story-ad-ui.js, extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js, extensions/amp-story-auto-ads/0.1/test/test-story-ad-ui.js, extensions/amp-story-auto-ads/0.1/utils.js
Changing UI logic for story ads so that it is able to be shared between inabox and amp case.
Part of #27851
=> Refactor button rendering for story ads (pt 1) 

build-system/tasks/codecov-upload.js
Note: Currently e2e coverage is not collected during Travis runs, but this change ensures that if/when that happens, it's automatically picked up.
=> 🏗 Upload e2e coverage reports to codecov if present

test/integration/test-amp-carousel.js
=> Remove TODO for closed issue

extensions/amp-story-360/0.1/amp-story-360.js, extensions/amp-story/1.0/amp-story-page.js
Call 360 playback methods privately based on store service.
Context / Fixes #30457
=> ♻️ onPageNavigation_ method in 360 component

src/OWNERS
Add wg-components as owners of storage-impl.js
=> Change storage impl OWNERS to wg-components

extensions/amp-story-auto-ads/0.1/story-ad-page.js, extensions/amp-story-auto-ads/0.1/story-ad-ui.js, extensions/amp-story-auto-ads/0.1/test/test-story-ad-ui.js
Changing UI logic for story ads so that it is able to be shared between inabox and amp case.
Part of #27851
=> Refactor button rendering for story ads (pt 2)

src/amp-story-player/amp-story-player-impl.js
#29864
Fetches more stories from a given endpoint.
Points to discuss: 
* Is 2 stories away a good amount? We can also allow the publisher to specify this via the config.
* Since for the non-AMP version we don't need to deal with cache, I made a simple fetch with the minimum headers. We will have to use the actual xhr-impl service in the AMP version for it to work with pages served from the cache.
* ~~This is a simple version without pagination until we resolve the pagination API in #29864~~
=> [amp-story-player] Fetch more stories from endpoint

build-system/server/typescript-compile.js
the error has the useful info, so do not show the stack.
https://github.com/ampproject/amphtml/pull/30292#discussion_r504922866
=> revert the `showStack` change

extensions/amp-story/1.0/amp-story.js
Adding comment to practice github workflow.
=> 📖 raksha's first commit

examples/amp-list-protocol-adapters.html, extensions/amp-script/0.1/amp-script.js
Addresses https://github.com/ampproject/amphtml/issues/30623#issuecomment-707362725
=> amp-script: emit warning when using layout with nodom

extensions/amp-a4a/0.1/callout-vendors.js
✨ Freestar Callout Vendors GDPR Consent Update
=> ✨ Freestar Callout Vendors GDPR Consent Update

examples/amp-story/player-local-stories.html, examples/amp-story/player.html
=> [amp-story-player] Add doctype to local samples

extensions/amp-a4a/0.1/callout-vendors.js, extensions/amp-a4a/rtc-documentation.md
The purpose of this PR is to add nexx360 as RTC vendor.
=> ✨ Nexx360 added as RTC vendor

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/secure-frame.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js
=> 🐛 A4A: allow-scripts for Safari in no-signing exp

extensions/amp-list/0.1/amp-list.js, extensions/amp-list/0.1/test/test-amp-list-load-more.js, extensions/amp-list/0.1/test/test-amp-list.js
=> amp-list: Remove unnecessary keyboard focus stops

ads/springAds.js
because computeInMasterFrame is not working as expected and renderAd never get's invoked right now
=> ♻️ springAds: refactoring computeInMasterFrame

build-system/eslint-rules/query-selector.js, package-lock.json, package.json, src/service/ie-intrinsic-bug.js
Fixes https://github.com/ampproject/amphtml/issues/30822
=> Fix broken query selector

extensions/amp-list/amp-list.md
=> 📖 recommend place amp-list infinite scroll to bottom of page

extensions/amp-story/1.0/amp-story.js
=> 🚮 Deleting comment

build-system/tasks/storybook/index.js, extensions/amp-iframe/0.1/amp-iframe.js, extensions/amp-iframe/0.1/storybook/Basic.amp.js, extensions/amp-iframe/0.1/storybook/SameOrigin.amp.js, extensions/amp-iframe/0.1/storybook/iframe.html, extensions/amp-iframe/0.1/test/test-amp-iframe.js, spec/amp-iframe-origin-policy.md, tools/experiments/experiments-config.js
=> Support disallowDocumentAccess and allow-same-origin

src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
Uses new API to enable circular wrapping.
Gets rid of old API (using DOM attribute) since no one was using it and it's not documented anywhere.
Closes #29289
=> [amp-story-player] Update circular wrapping API

src/service/loading-indicator.js
Fixes https://github.com/ampproject/error-reporting/issues/20
=> Fix intersection observer margin to absolute for non-document-root supporting platforms

extensions/amp-timeago/1.0/test/test-timeago.js
=> Timeago: Preact unit tests

src/viewport-observer.js, test/unit/test-viewport-observer.js
**summary**
match fix in https://github.com/ampproject/amphtml/pull/30871
=> viewport-observer: match fix made for loading-indicator

extensions/amp-story/1.0/amp-story-store-service.js, extensions/amp-story/1.0/amp-story-system-layer.js, extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js, src/amp-story-player/amp-story-player-impl.js
4/n partial for #30031
* Adds click listeners that sends message back to player for those buttons that are appropiate.
* Listens to messages from player side and perform corresponding action (skip next story in desktop, dispatch custom event, etc..)
=> [amp-story-player] [custom UI] Add messaging for clicks in system layer controls

extensions/amp-base-carousel/0.1/amp-base-carousel.js, extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js, extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js, test/manual/amp-base-carousel/basic.amp.html, test/manual/amp-base-carousel/zero-index-slide.amp.html
=> 🐛 Fix amp base carousel index issue

extensions/amp-base-carousel/1.0/amp-base-carousel.js, extensions/amp-base-carousel/1.0/storybook/Basic.amp.js, src/preact/base-element.js, src/preact/media-query-props.js, test/unit/preact/test-base-element-mapping.js, test/unit/preact/test-media-query-props.js
Support for media attributes such as:
```
<amp-base-carousel visibile-count="(min-width: 500px) 1.2, 1">
```
Partial for https://github.com/ampproject/amphtml/issues/28284
=> Bento: media attribute/prop values

extensions/amp-story-auto-ads/0.1/story-ad-config.js
This will be in prod, but NWS is controlling rollout on their side. Will not be fully launched until the no-signing work is complete.
=> ✨Add NWS as supported vendor for story ads

extensions/amp-story/1.0/amp-story-system-layer.js, src/amp-story-player/amp-story-player-impl.js
#30031
Gets rid of allowlist, allowing custom controls to be added to the story via the player.
=> ✨ [amp-story-player] Allow custom controls

.renovaterc.json
For context see https://github.com/ampproject/amphtml/pull/30874#issuecomment-718864410
=> 🏗 Update renovate to use lts_latest node

test/unit/test-url-replacements.js
✅ ❄️ ♻️
It seems `([a-zA-Z0-9_-]+){10,}` matches 10 or more groups of 1 or more of either letters, numbers, underscore and dashes.
What this should test against is 10 or more of either letters, numbers, underscore and dashes: `([a-zA-Z0-9_-]{10,})`
This also fixes the grouping if further analysis of the regex is needed.
https://regex101.com/r/T8E0p8/1/
=> Test Regex: simplify matching and grouping

extensions/amp-timeago/1.0/timeago.js, src/base-element.js, src/context/index.js, src/custom-element.js, src/preact/base-element.js, test/unit/preact/test-base-element-runtime.js, test/unit/test-custom-element.js
=> Bento: unmount/remount component on DOM disconnect/reconnect

extensions/amp-fit-text/1.0/fit-text.js
=> amp-fit-text: Use local window for ResizeObserver

src/amp-story-player/README.md
Click on the "display the rich diff" for an easier review.
=> 📖  [amp-story-player] November update docs

extensions/amp-ad/0.1/amp-ad-3p-impl.js
Partial for https://github.com/ampproject/amphtml/issues/30620.
Due to all the indentation changes, I recommend viewing this diff [without whitespace changes](https://github.com/ampproject/amphtml/pull/30995/files?w=1)
=> amp-ad 3p: remove viewportCallback

test/unit/inabox/test-inabox-viewport.js, test/unit/test-iframe-helper.js, test/unit/test-sanitizer.js, test/unit/test-vsync.js, test/unit/test-xhr.js
Exactly what it says on the box
=> ✅ Unskip 9 passing unit tests

extensions/amp-o2-player/OWNERS
Because yevheniiminin has been left company, needs to add new owners.
=> amp-o2-player changed owners

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Code with 1% experiment added in #30764, ramping to 5% per branch in advance of launch
=> Ramp AdSense/Google Ad Manager ptt experiment to 5%

extensions/amp-story-360/0.1/test/validator-amp-story-360.html, extensions/amp-story-360/0.1/test/validator-amp-story-360.out
cl/340902703 Remove trailing whitespace in js validator test.
=> validator rollup 521@1115

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.131
=> ✨ SwG Release 0.1.22.131

extensions/amp-selector/1.0/selector.js, extensions/amp-selector/1.0/test/test-selector.js
=> Bento Selector: Preact unit tests

examples/amp-story-360.amp.html, extensions/amp-story-360/0.1/amp-story-360.js, third_party/zuho/README.amp, third_party/zuho/zuho.js
Use `WEBGL_lose_context` API to activate or deactivate WebGL context if distance from active page is less than `MIN_WEBGL_DISTANCE`
[Stress test demo](https://discovery-ec239.web.app/examples/amp-story-360.amp.html)
Context / Fixes #29512
=> ✨ Use WEBGL_lose_context API to deallocate WebGL based on distance

extensions/amp-story/1.0/test-e2e/test-amp-story-bookend.js
Part of: https://github.com/ampproject/amphtml/issues/31069
(More info about the flaky tests in the above link)
=> ❄️ [amp-story] Skip flaky e2e test

extensions/amp-story-360/validator-amp-story-360.protoascii, extensions/amp-video/validator-amp-video.protoascii, validator/validator-main.protoascii
cl/341468485 Revision bump for #28349
cl/341513008 noscript-img tagspec clean up
cl/341647629 Revision bump for #31028
cl/341660267 Remove trailing whitespace in js validator test.
=> Validator rollup 521@1119

examples/amp-story-360.amp.html, extensions/amp-story-360/0.1/amp-story-360.js
=> 🐛 Update frame of prev and next page's 360 components

extensions/amp-subscriptions/amp-subscriptions.md
Adding a remark on setting cookies correctly via same site flag if being used, as discussed offline.
=> 📖  Update amp-subscriptions.md to relfect samesite settings on cookies

extensions/amp-date-picker/0.1/test/integration/test-integration-maximum-nights.js, extensions/amp-story/1.0/test-e2e/test-amp-story-share-menu.js
Related to: https://github.com/ampproject/amphtml/issues/31105
More info in link
=> ❄️ [amp-story] Skip flaky e2e test on story-share-menu

extensions/amp-selector/1.0/amp-selector.js, extensions/amp-selector/1.0/selector.js, extensions/amp-selector/1.0/selector.type.js, extensions/amp-selector/1.0/storybook/Basic.amp.js, extensions/amp-selector/1.0/storybook/Basic.js, extensions/amp-selector/1.0/test/test-selector.js
Move `toggle` and `clear` to the Preact layer.
Partial for #28282
=> Bento Selector: Imperative API

build-system/global-configs/prod-config.json
Follow up to #30861.
Haven't seen any issues in Canary :)
To be merged after Wednesday (when the release freeze ends).
=> Turn on visibility-trigger-improvements experiment in prod 

extensions/amp-date-picker/0.1/test/integration/test-integration-maximum-nights.js
Part of: https://github.com/ampproject/amphtml/issues/31103
More info for flaky tests here
=> ❄️ [amp-date-picker] Skip flaky integration test

test/integration/test-amp-carousel.js
Addresses https://github.com/ampproject/amphtml/issues/30661#event-3967871527
=> amp-carousel: unskip another one

build-system/tasks/visual-diff/index.js, build-system/tasks/visual-diff/snippets/iframe-wrapper.js
This should always be a string. Not sure why tests didn't fail with #31124 :o
=> 🐛 I messed this up merging #31124

extensions/amp-story-360/0.1/test/test-amp-story-360.js
Add a few tests to prevent regression on #31121. The last test in particular fails if #31123 is reverted.
=> ✅  [amp-story-360] Add play/pause tests

extensions/amp-base-carousel/amp-base-carousel.md
=> 📖 amp-base-carousel looping based on `visible-count` 

build-system/tasks/storybook/package-lock.json, build-system/tasks/storybook/package.json
=> 🏗 Bump version for @ampproject/storybook-addon

build-system/global-configs/experiments-config.json, src/inabox/amp-inabox.js
Experiment was neutral, https://experiments.corp.google.com/#/portal/study/contentads::569234/analysis?label=_:ss2Mz-GvHEf04mjRqztP5bWLVns
Closes #30781
=> 🚀 Launch inabox story ads.

build-system/tasks/bundle-size/APPROVERS.json
now that we report mjs files we also need to add it to the approvers list
=> add mjs binaries and approvers to list

ads/yahoofedads.js
Pass width and height into underline js so we can resize it better once get responsive AD from AD server.
=> 🐛 [yahoofedads]Pass heigth/width into downstream js.

extensions/amp-story/1.0/amp-story.js, src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
Follows https://github.com/ampproject/amphtml/pull/30927
Closes https://github.com/ampproject/amphtml/issues/31047
Programmatically sends the player to the page specified by the ID passed to the method `goToPageId`
=> [Story Player] Expose goToPageId functionality

ads/springAds.js
For an update on the background tasks an referrence update on AMP is needed
=> 🚀  reference update for background performance improvement

extensions/amp-story/OWNERS
Add Matias and Philip to Story owners.
=> Add Matias and Philip to Story owners.

tools/experiments/experiments-config.js
Cleanup disable-amp-story-default-media experiment.
Fixes https://github.com/ampproject/amphtml/issues/14535
=> Cleanup disable-amp-story-default-media experiment.

src/service/resources-impl.js
**summary**
Still too many amp4email bugs. Will need to fix them all before relaunching.
=> disable intersect-resources for amp4email

ads/_config.js, ads/vlyby.js
♻️Just swapped old vlyby cdn with new one.
=> ♻️ replaced vlyby cdn

extensions/amp-story-360/0.1/amp-story-360.js
context / fixes #31215
[Demo](https://stories-360.web.app/examples/amp-story-360.amp.html)
[Demo of old version for comparison](https://discovery-ec239.web.app/examples/amp-story-360.amp.html)
Holding my phone while tensing my hand.
left is smoothed, right is not.
=> ✨ amp-story-360 gyroscope sensor smoothing

ads/admanmedia.js, ads/admanmedia.md
- Change the adman ssp subdomain name.
- Remove unnecessary id setting code.
- Change sample test id.
=> Change admanmedia ssp endpoint url

extensions/amp-ad-network-nws-impl/0.1/test/test-nws-a4a-config.js
Contributor was having trouble with auto sort.
cc/ @danielstockton
=> Sort imports for NWS test

examples/visual-tests/amphtml-ads/static.js, test/visual-diff/visual-tests
I am not 100% sure if this is the root cause of the flakiness, but I think this fix will help.
https://github.com/ampproject/amphtml/issues/31199
=> ❄️Fix visual diff test flakiness issue on amphtml-ads

src/service/resource.js
Removes unused function `Resources.hasLoadedOnce`
=> resource: remove unused fn

spec/amp-story-player.md, src/amp-story-player/README.md
Closes #31221
Also removes "beta" from the README of features that are in the stable release.
=> 📖  Updating player docs

src/viewport-observer.js, test/unit/test-loading-indicator.js, test/unit/test-viewport-observer.js
Addresses https://github.com/ampproject/amphtml/issues/30794.
=> viewport observer: remove rootMargin

extensions/amp-iframe/amp-iframe.md
=> 📖  [amp-iframe]: Update doc to prevent overflow div moved outside of parent <p>

examples/amp-story/invalid-link-tests.html
Using % for CSS elements in test story so that the test pages appear uniformly on on desktop & mobile.
=> ✅  Using % for CSS elements in test story so that the test pages appear uniformly on on desktop & mobile.

ads/_config.js, ads/purch.js
Purch has been acquired by Future PLC a couple years ago.
We're about to decommission the purch.com, and so we need to replace it by servebom.com, another domain we currently own.
=> ✨ purch.com decommissioning

3p/integration.js, ads/_config.js, ads/pulse.js, ads/pulse.md, examples/ads.amp.html, extensions/amp-ad/amp-ad.md
Provides support for amp-ad type=pulse
Closes #30686
=> ✨ Add Pulse widget ads extension

ads/_config.js, ads/purch.js
This reverts commit 7601993eff6c4399745ae0f6dd46653c7ceaa84e.
I just talk to my managers and they are not really comfortable about rolling out this change just few weeks before Christmas and prefer either to reschedule it to January or to declare a new "future" vendor to then be able to switch our sites one by one and finally remove the "purch" vendor once all our sites will use the new vendor.
My sincere apologies for this change immediately rollbacked :( 
I'll probably make a new merge request in a couple of days to declare a new vendor.
=> ✨ Revert "purch.com decommissionning (#31350)"

extensions/amp-ad/0.1/amp-ad.js
This reverts commit b950dfa82d8f72ece43535249bc1a7b645dfb0a1. This was added in #30992 to get stats about ad network traffic, but was left in long enough to reach Stable. As a result, the error traffic volume (~100k/minute) is taking down parts of error reporting.
=> ⏪ Revert "get statistics about ad network traffic (#30992)"

css/amp-story-player-iframe.css
Closes #31360
Some styles from the parent page were bleeding into the shadow DOM of the player, causing undesired behavior. This PR resets inherited styles on the shadow DOM.
See attached bug for example.
=> 🖍 🐛 [amp-story-player] Resets shadow DOM styles

extensions/amp-consent/amp-consent.md, extensions/amp-recaptcha-input/amp-recaptcha-input.md, extensions/amp-viewer-integration/integrating-viewer-with-amp-doc-guide.md
Fixes https://github.com/ampproject/amp.dev/issues/4999
=> Don't use curly quotes in documentation code blocks

css/amp-story-player-iframe.css
Follow up on #31363, using `!imporant` was overriding our own styles. Using `all: initial` is enough to clear inherited styles while not overriding our own.
=> 🖍  Fix player CSS

extensions/amp-selector/1.0/selector.js, extensions/amp-selector/1.0/test/test-amp-selector.js
=> ✅ amp-selector:1.0 Add AMP-layer unit tests 

build-system/externs/amp.extern.js, build-system/test-configs/dep-check-config.js, extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, src/service/real-time-config/real-time-config-impl.js, src/services.js
https://github.com/ampproject/amphtml/issues/20259
=> ♻️Change real time config to a service

build-system/tasks/presubmit-checks.js, examples/img.amp.html, extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-analytics/0.1/test/test-analytics-root.js, src/experiments/fie-resources-exp.js, src/friendly-iframe-embed.js, src/inabox/inabox-resources.js, src/service/core-services.js, test/unit/inabox/test-inabox-resources.js, test/unit/test-friendly-iframe-embed.js, tools/experiments/experiments-config.js
=> A dedicated resource manager for FIE

extensions/amp-subscriptions-google/0.1/test-e2e/test-amp-subscriptions-google.js
=> ❄️Skip flaky amp-subscriptions-google e2e test

extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, src/experiments/fie-resources-exp.js, src/friendly-iframe-embed.js, src/service/core-services.js
=> Setup fie-resources experiment

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
=> Launch fie-experiments on Canary and unlaunch intersect-resources

examples/visual-tests/amp-story/amp-story-360-image.html
Remove animation to ensure consistent Percy test.
Fixes #31441
=> 🐛 Fix flaky 360 Percy test

spec/amp-story-player.md, src/amp-story-player/README.md
=> 📖 Fix docs

examples/analytics-vendors.amp.html, extensions/amp-analytics/0.1/test/vendor-requests.json, extensions/amp-analytics/0.1/vendors/blackcrowai.json, extensions/amp-analytics/analytics-vendors-list.md
Add Black Crow AI Analytics integration for our partners to easily integrate.
@ampproject/wg-components
Link to issue: https://github.com/ampproject/amphtml/issues/31449
=> added vendor Black Crow AI analytics (#31449)

src/dom.js
All `module` browsers support `MutationObserver`.
https://caniuse.com/?search=MutationObserver
IE 11 also supports it, so `nomodule` builds should be fine too. We may then remove the fallback altogether, but some strictly unsupported outliers (like Opera Mini) would be left out:
```diff
-  if (IS_ESM || win.MutationObserver) {
/** @const {MutationObserver} */
const observer = new win.MutationObserver(() => {
if (checkFunc(parent)) {
observer.disconnect();
callback();
}
});
observer.observe(parent, {childList: true});
-  } else {
-     /** @const {number} */
-    const interval = win.setInterval(() => {
-      if (checkFunc(parent)) {
-        win.clearInterval(interval);
-        callback();
-      }
-    }, /* milliseconds */ 5);
-  }
```
=> 🚀 Remove unnecessary MutationObserver fallback

extensions/amp-story-player/validator-amp-story-player.protoascii
=> [amp-story-player] Add intrinsic to supported layouts

extensions/amp-story/1.0/amp-story-render-service.js
Mitigate `AmpStoryRenderService` error.
Issues mentioning `Render timeout waiting for service amp-story-render`
#29585
#29584
#31333
#30783
#31440
#22774
=> Mitigate AmpStoryRenderService error

extensions/amp-onetap-google/0.1/amp-onetap-google.js, extensions/amp-onetap-google/0.1/test/test-amp-onetap-google.js
Substitute variables in iframe URL.
https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md
```html
<amp-onetap-google
layout="nodisplay"
data-src="https://example.com/onetap?page-view-id=PAGE_VIEW_ID"
></amp-onetap-google>
```
=> ✨ Replace variables in <amp-onetap-google> URL

build-system/tasks/e2e/index.js, src/friendly-iframe-embed.js, src/inabox/inabox-resources.js, test/unit/inabox/test-inabox-resources.js, test/unit/test-friendly-iframe-embed.js
=> Use the right resource manager to pick up the ini-load elements

extensions/amp-story-360/0.1/amp-story-360.js
Use implicit returns in `whenUpgradedToCustomElement` in renderer setup.
=> 🚮 [amp-story-360] Implicit returns on renderer setup

.github/workflows/sweep-experiments.yml
Creates starter pull requests with `gulp sweep-experiments` to be followed up manually.
Task takes about 4.5 mins on Github Actions for a set of 13 experiments. Will likely take less time in the future as more experiments are swept.
=> 🏗 Sweep experiments on a schedule

build-system/tasks/storybook/preact-env/webpack.config.js
Otherwise [borked](https://storage.googleapis.com/amp-test-website-1/amp_dist_84439/examples/storybook/preact/index.html?path=/story/videoiframe--using-video-iframe):
We maybe should run the common babel pipeline on the Storybook build.
=> 🐛 Replace IS_ESM in Storybook Preact build

extensions/amp-animation/0.1/amp-animation.js
=> Cleanup ampdoc-fie in animations

ads/README.md, ads/openx.md, extensions/amp-a4a/0.1/head-validation.js, extensions/amp-ad/amp-ad.md, extensions/amp-bind/amp-bind.md, spec/amp-cache-debugging.md, spec/amp-html-format.md, spec/amp-var-substitutions.md, src/service/url-expander/expander.js, src/service/url-replacements-impl.js, src/service/variable-source.js, validator/validator.pb.go, validator/validator.proto
[per](https://github.com/ampproject/amphtml/blob/32e092f81897a2a0cfaac485cd6951ba89336cbc/build-system/tasks/presubmit-checks.js#L51)
=> use allowlist rather than white list

extensions/amp-list/amp-list.md
=> amp4email doc updates

extensions/amp-lightbox/1.0/test-e2e/test-amp-lightbox.js, test/fixtures/e2e/amp-lightbox/1.0/amp-lightbox.html
=> ✅ Bento Lightbox: Add e2e tests

extensions/amp-access/0.1/amp-access.js, extensions/amp-access/0.1/test/test-amp-access.js
Addresses https://github.com/ampproject/amphtml/issues/31566
=> Access expression errors should be user errors.

ads/yahoonativeads.js, ads/yahoonativeads.md, examples/ads.amp.html
This PR includes changes to support additional configuration options for Yahoo Native Ad tags.
These changes were introduced primarily for enabling ad feedback support `data-enable-ad-feedback`, and future-proofing potential interface changes with `json` attribute. This also includes 📖 documentation updates.
Yahoo ad placements are required to run Ad Feedback, which is currently not possible due to the interface limitations.
=> 🐛 🔥 [yahoonativeads] update configs and documentation

extensions/amp-lightbox/1.0/amp-lightbox.css, extensions/amp-lightbox/1.0/lightbox.js, extensions/amp-lightbox/1.0/lightbox.jss.js, extensions/amp-lightbox/1.0/storybook/Basic.amp.js, extensions/amp-lightbox/1.0/storybook/Basic.js, src/preact/base-element.js
=> 🖍  Bento Lightbox: Customizable styles

extensions/amp-accordion/1.0/amp-accordion.js, extensions/amp-accordion/1.0/test/test-amp-accordion.js
=> Accordion: pick up new child sections

build-system/compile/compile.js
Closure has changed its error / warning behavior over the years. Moreover, in our use case, warnings are silenced unless there are accompanying errors.
- Cleans up all the error / warning / off levels in `compile.js`
- Eliminates the use of `jscomp_warning`, and moves all custom settings to either `jscomp_error` or `jscomp_off`
- Attempts to pick an appropriate set of options to detect the error in #31555
Attempted fix for #31555
=> 🏗 Clean up closure error levels, remove ineffective `jscomp_warning`

build-system/compile/bundles.config.js, extensions/amp-sidebar/0.1/storybook/Basic.amp.js, extensions/amp-sidebar/1.0/amp-sidebar.css, extensions/amp-sidebar/1.0/amp-sidebar.js, extensions/amp-sidebar/1.0/storybook/Basic.amp.js, extensions/amp-sidebar/1.0/test/test-amp-sidebar.js
Partial: https://github.com/ampproject/amphtml/issues/31366
Initial AMP Component of amp-sidebar
Todo: tests
=> ✨ [bento][amp-sidebar] Initial AMP Component

src/service/resources-impl.js
**todo**
-  [x] writeup postmortem (https://github.com/ampproject/amphtml/issues/31232#issuecomment-739086372)
=> intersect-resources: relaunch for amp4email

build-system/babel-config/dep-check-config.js, package-lock.json, package.json
Follow up for #31619
Running `gulp dep-check` was still failing for #31615 ([link](https://travis-ci.com/github/ampproject/amphtml/jobs/461379883#L762))
This adds `@babel/plugin-syntax-import-assertions` to the `dep-check-config`
=> 🏗 I Update dep check config with babel import assertions plugin

extensions/amp-story/1.0/amp-story-tooltip.css
=> 🐛 Add border radius to tooltip icon

ads/_config.js, ads/yektanet.js, ads/yektanet.md, examples/ads.amp.html
Support banners in Yektanet amp ad script
cc ampproject/wg-monetization
=> ✨ Add banners to Yektanet amp ad

extensions/amp-story/amp-story.md
=> fix amp-story frontmatter

build-system/externs/amp.extern.js, build-system/test-configs/dep-check-config.js, extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, src/service/real-time-config/real-time-config-impl.js, src/services.js
Reverts ampproject/amphtml#31101
Since this seems to increase the impression on a certain pub for unknown reasons. Whether this is WAI or bug is tbd.
=> Revert "♻️Change real time config to a service"

extensions/amp-stream-gallery/amp-stream-gallery.md
This is the only component that doesn't have an .md file corresponding to its 0.1. Partial for #28284.
=> 📖 Bento Stream Gallery documentation

extensions/amp-consent/0.1/amp-consent.css, extensions/amp-consent/0.1/consent-ui.js, extensions/amp-consent/0.1/test/test-consent-ui.js
This reverts commit 8de56f3a4658b15fd8df02200dd38ca9d4a9d8d6.
Reverting this commit in favor of a safer fix.
=> ⏪ Revert "[amp-consent] Change `transform` rule to a CSS variable #31660"

src/service/viewport/viewport-impl.js
=> Call fake scroll API on iOS to unstuck the clicks

build-system/tasks/presubmit-checks.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-a4a/0.1/test/test-name-frame-renderer.js, extensions/amp-a4a/0.1/test/test-template-renderer.js, extensions/amp-ad-custom/0.1/test/test-amp-ad-custom.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-safeframe.js, src/base-element.js, src/custom-element.js, src/service/resource.js, test/unit/test-base-element.js, test/unit/test-resource.js
=> ✂️  Remove getPageLayoutBox API

extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-logs.css, extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-logs.js, extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.css
Added status icon on the tab selector to quickly preview if the story passes or fails the validation tests.
=> ✨[Story devtools] Added logs status icon on tab selector

build-system/tasks/presubmit-checks.js
I had a PR Travis [job](https://travis-ci.com/github/ampproject/amphtml/jobs/469003388) fail because it contained a new file annotated as 2021. 🥂
Now allowing 2021..9
=> 🏗  Allow "Copyright 2021"

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Original code change introduced in #30764 wrapped in experiment flag.  Launching change.
=> Launch tag type parameter for AdSense & GAM

extensions/amp-video-iframe/0.1/amp-video-iframe.js, extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js, extensions/amp-video-iframe/amp-video-iframe.md, src/video-iframe-integration.js
=> ✨ amp-video-iframe: pass host's title and lang to iframe

extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
TODO: fix the test (or component behavior)
=> Skip flaky carousel test

validator/js/nodejs/README.md, validator/js/nodejs/package.json
=> update amphtml-validator to v.1.0.34

src/utils/dom-tranform-stream.js, test/unit/utils/test-dom-transform-stream.js
For performance improvements, but still allow callers to supply their own rate limiting function.
Don't love the name I came up with, open to better naming suggestions :)
Partial for #27189
=> 🚀 Remove vsync from dom transform stream

examples/visual-tests/amp-story/amp-story-page-attachment.html, examples/visual-tests/amp-story/amp-story-page-attachment.js, extensions/amp-story/1.0/amp-story-page-attachment.css
The swipe up has an underline because of #31816, but shouldn't
=> 🖍 Remove underline from story swipe up

extensions/amp-script/0.1/user-activation-tracker.js
Addresses https://github.com/ampproject/amphtml/issues/25625
=> activation-tracker: keydown as activation event

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.140
=> Updates SwG to version 0.1.22.140

src/inabox/inabox-resources.js, test/unit/inabox/test-inabox-resources.js, tools/experiments/experiments-config.js
Should improve latency in the streaming case.
Related to #27189
=> 🚀 Build amphtml ads elements before document ready

extensions/amp-a4a/0.1/amp-a4a.js
closes ampproject/error-reporting#37
=> 🐛Fix FIE renderCompleted error

build-system/global-configs/prod-config.json
=> Launch fie-resources to 100%

build-system/global-configs/experiments-config.json, src/inabox/inabox-resources.js, test/unit/inabox/test-inabox-resources.js
=> 🧪Prepare RTV experiment for eager ads building

build-system/tasks/test-report-upload.js
Report the current github repository when reporting test results. This will allow the backend to reject reports from forks running tests on Travis.
=> 🏗 Report github repository with test results

validator/js/chromeextension/content_script.js, validator/js/chromeextension/manifest.json
- restrict rel=amphtml lookup to http/https
- update to v.1.1.8
=> Update to Validator Chrome Extension

extensions/amp-fit-text/0.1/amp-fit-text.md, extensions/amp-fit-text/amp-fit-text.md
- Copy existing `amp-fit-text/amp-fit-text.md` to `amp-fit-text/0.1/amp-fit-text.md`
- Modify `amp-fit-text/amp-fit-text.md` to be about `1.0` instead.
Related to #28281
=> Add documentation for amp-fit-text:1.0

extensions/amp-base-carousel/0.1/amp-base-carousel.md, extensions/amp-base-carousel/amp-base-carousel.md
- Copy existing `amp-base-carousel/amp-base-carousel.md` to `amp-base-carousel/0.1/amp-base-carousel.md`
- Modify `amp-base-carousel/amp-base-carousel.md` to be about `1.0` instead.
Related to #28284
=> Add documentation for amp-base-carousel:1.0 

extensions/amp-image-viewer/0.1/amp-image-viewer.js, extensions/amp-pan-zoom/0.1/amp-pan-zoom.js, extensions/amp-script/0.1/amp-script.js, extensions/amp-script/0.1/test/unit/test-amp-script.js, extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.js, src/base-element.js, src/custom-element.js, src/utils/size-observer.js, test/unit/test-custom-element.js, test/unit/utils/test-size-observer.js
=> Refactor onMeasureChanged API to use ResizeObserver

src/url.js
Related to #31594. If the browser `IS_ESM`, it supports `URL`.
This should DCE `resolveRelativeUrlFallback_` from module scripts.
Notable: `dist/v0.mjs`: Δ `-0.10KB`
=> 🚀 Shortcircuit URL support check in resolveRelativeUrl

extensions/amp-analytics/0.1/requests.js, extensions/amp-analytics/0.1/test/test-requests.js
After #31594, URLs are parsed using native `URL()`.
Previously, invalid URLs parsed with `<a>` would have been parsed without error, but incorrectly, for example:
```js
parseUrlWithA('https://?foo'); // 'https:/?foo'
new URL('https://?foo'); // throws error
```
In this case, #31883 is triggered by `expandUrlAsync` failing with a certain vendor config:
https://github.com/ampproject/amphtml/blob/b445001b99f6ccddc86a6f6e3812a774d4c9ec5a/extensions/amp-analytics/0.1/vendors/mpulse.json#L2-L4
When `beacon_url` fails to resolve, we get the above case:
```js
new URL('https://?h.d=...'); // throws error
```
This can be triggered by any vendor request whose required interpolation values are missing or create an invalid URL, so it's appropriate to redirect them as user errors.
=> 🐛 Malformed resolved analytics URL will trigger user error

build-system/tasks/storybook/OWNERS
Replaced `@wassgha` with myself.
=> 🏗 Update storybook/OWNERS

src/multidoc-manager.js
=> 🐛 [amp-next-page] Fix "unallowed inline javascript" console error in multidoc-manager

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
- Update dependency autoprefixer to v10.2.1 (#1432)
- Update dependency postcss to v8.2.4 (#1433)
- Don't show meter toast if 'showToast' is false (#1441)
- Update API (#1440)
- Add remaining BasicSubscriptions API for adding callbacks for entitle… (#1439)
- Create URL utilities (#1437)
- Change size of loading iframe for meter toast. (#1436)
- Create some URL helpers (#1435)
=> SwG release 0.1.22.141

src/service/real-time-config/real-time-config-impl.js, test/unit/test-real-time-config.js
=> ✨Allow CLIENT_ID to be used in RTC callouts

build-system/pr-check/unminified-tests.js, build-system/tasks/test-report-upload.js
Fixes the `repository` property reported to the API, which uses it to validate the source of the report.
=> 🏗 Use ci-agnostic helper in test reporting and display error message on failure

build-system/tasks/storybook/index.js
The original Storybook implementation was returning a `Promise.all` with the results of the build / launch `child_process`es. While this works well to signal the end of the process, it doesn't propagate errors correctly.
This PR throws an error when build / launch fails, which is correctly caught and handled by the `gulp` process.
Addresses https://github.com/ampproject/amphtml/pull/31959#issuecomment-760381050
Follow up to #31952
=> 🏗 Propagate errors while building / launching storybook

build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/__component_name_hyphenated__.js, build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/__component_name_hyphenated__.jss.js, build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/__component_name_hyphenated__.type.js, build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/amp-__component_name_hyphenated__.css, build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/amp-__component_name_hyphenated__.js, build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.amp.js, build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.js, build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/test/test-amp-__component_name_hyphenated__.js, build-system/tasks/extension-generator/bento/index.js, build-system/tasks/extension-generator/index.js, build-system/tasks/extension-generator/insert-extension-bundles-config.js
As discussed offline
Closes #31887
=> 🏗 Add CSS to legacy generator and import .css from bento component

.renovaterc.json
renovate updates patches and minor versions multiple times a day... resulting in me getting spammed. Set this to major releases only.
https://www.npmjs.com/package/renovate?activeTab=versions
https://github.com/ampproject/amphtml/pull/31672
=> 🏗  Update renovate weekly and ignore patches

extensions/amp-story-interactive/0.1/amp-story-interactive-abstract.js, extensions/amp-story/1.0/amp-story-consent.js, extensions/amp-story/1.0/test/test-amp-story-consent.js
Move the Services fetch to buildCallback from the constructor on `amp-story-interactive` and `amp-story-consent`.
=> 🐛 [Story interactive] Moved services to buildCallback

extensions/amp-connatix-player/0.1/amp-connatix-player.js, extensions/amp-connatix-player/0.1/test/test-amp-connatix-player.js
- added url to iframe query params because there was no way of accessing the full page url from the player
=> ✨ amp-connatix-player: Add URL to iframe query params

build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.js
I fixed the original mistake with a different mistake :sweat_smile:
=> 🐛 Fix bento storybook tag name (again)

extensions/amp-analytics/analytics-vendors-list.md
=> [amp-analytics] Fix dead links in `analytics-vendors-list.md`

extensions/amp-accordion/0.1/amp-accordion.md, extensions/amp-accordion/amp-accordion.md, extensions/amp-date-countdown/0.1/amp-date-countdown.md, extensions/amp-date-countdown/amp-date-countdown.md, extensions/amp-social-share/0.1/amp-social-share.md, extensions/amp-social-share/amp-social-share.md
Bento documentation for social-share, date-countdown, accordion
=> 📖 [bento] Add documentation for social-share, date-countdown, accordion: 1.0

.circleci/config.yml, build-system/common/check-package-manager.js, build-system/common/ci.js, build-system/compile/compile.js, build-system/pr-check/bundle-size.js, build-system/tasks/report-test-status.js, build-system/test-configs/config.js
This PR adds an initial CircleCI config for `amphtml`. It replicates the existing Travis build matrix in `.travis.yml`. For now, this will apply a non-blocking status to every AMP PR, and also run for every commit to `master` or `amp-release-*`.
Build history can be found at https://app.circleci.com/pipelines/github/ampproject/amphtml
**Next steps:** Iterate on the config, optimize running time, make the check blocking, and stop running Travis builds.
=> 🏗 Configure CircleCI

build-system/tasks/serve.js
This updates our local server to listen on `0.0.0.0`, which means listening on all available network interfaces. Currently, we're only binding on `127.0.0.1`, which means only the local machine can connect to the server.
By changing to `0.0.0.0`, any device on the local network will be able to connect. This is really benefitial for testing on our phones.
It also prints all of the IPv4 addresses, so that you don't have to go dig that info up.
=> ✨ Local Server: Listen on all local network addresses

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
🧪 Ramp up the adsense-ad-size-optimization experiment to 100%.
PTAL. @calebcordry, @powerivq, @charliereams,
=> 🧪 Ramp up the adsense-ad-size-optimization experiment to 100%.

build-system/tasks/storybook/.renovaterc.json, build-system/tasks/storybook/package-lock.json, build-system/tasks/storybook/package.json, build-system/tasks/storybook/renovate.json5
Our config doesn't work with v6, we need to ensure that manually. This unblocks the bento dev environment.
Reverts to `@storybook` package versions @ 383321c11b68c38199e9b6c3eaad2dbaf26783f5
(I'll manually upgrade to 6 and separately).
=> 🐛 Revert Storybook package versions

build-system/tasks/helpers.js, package-lock.json, package.json
Follow up to https://github.com/ampproject/amphtml/pull/31988, this should both make us more robust to changes in the output and makes our concatenation sourcemap aware.
=> 🐛 Concat files post-closure with sourcemap awareness

extensions/amp-base-carousel/0.1/test-e2e/test-advance.js, extensions/amp-base-carousel/1.0/test-e2e/test-advance.js
This test has been failing quite frequently on CI.
/cc @ampproject/build-cop
=> ❄️ Skip flaky carousel E2E test

build-system/tasks/extension-generator/index.js
For 0.1 extensions.
1. Adds missing `CSS` import.
2. Formats written files with `prettier`.
3. Since formatting now requires a list of written files, refactors write list format and simplifies:
3.1 all content values are `await`ed
3.2 all holding directories are created if necessary
=> 🐛 Import generated extension CSS, format written files

test/unit/test-iframe-helper.js
Related to #32103
/cc @ampproject/wg-components
/cc @ampproject/build-cop
=> ❄️ Skip flaky iframe test

extensions/amp-viewer-integration/0.1/messaging/messaging.js, extensions/amp-viewer-integration/0.1/messaging/package.json
Partial #31838
Handles case where document redirects, resulting in a different origin in the cache URL than what would normally be computed.
Also need to bump up the messaging library version 
https://github.com/ampproject/amphtml/blob/43df70c521b59eec17e62868f7c22fd685ac731e/package.json#L19
=> [amp-viewer-integration] Handle redirects case

extensions/amp-story/1.0/test/validator-amp-story-grid-layer-presets.html, extensions/amp-story/1.0/test/validator-amp-story-grid-layer-presets.out, extensions/amp-story/validator-amp-story.protoascii
Created validation rules and tests for presets and anchoring. scaling-factor is not valid.
Closes #31284
=> ✨[Story layout] Added validation to presets

examples/visual-tests/amp-user-notification/amp-user-notification.amp.html
Deflake the visual diff test for `amp-user-notification`. Fixes #30868. 
Replaces the amp-ad in the test with a static placeholder.
=> ❄️ Deflake `amp-user-notification` visual diff test

extensions/amp-inline-gallery/amp-inline-gallery.md
=> 📖 amp-inline-gallery documentation missing quotation

.circleci/config.yml, .circleci/fetch_merge_commit.sh, .circleci/setup-storage.sh, build-system/test-configs/hosts
- Clean up `.circleci/config.yml`
- Move cloud storage setup steps to `.circleci/setup-storage.sh`
- Move host config for integration tests to `build-system/test-configs/hosts`
- Add a check to `.circleci/fetch_merge_commit.sh` to prevent builds for PRs on other forks (e.g. [this build](https://app.circleci.com/pipelines/github/ampproject/amphtml/363/workflows/2f209061-1a67-438b-8e70-b43fb462982f/jobs/2961))
Addresses https://github.com/ampproject/amphtml/pull/32051#discussion_r561138741
=> 🏗 Clean up CircleCI config, move some setup steps into separate files

validator/cpp/engine/validator-internal.cc
=> Internal cleanup of map types

extensions/amp-base-carousel/1.0/base-carousel.js, extensions/amp-base-carousel/1.0/base-carousel.jss.js, test/manual/amp-base-carousel/1.0/vertical.amp.html
This PR adds `touch-action` and `overscroll-behavior` to carousel. Related to #28284, stemming from #32049
=> 🖍 Bento Carousel: Touch and scroll properties

extensions/amp-instagram/amp-instagram.md, extensions/amp-timeago/amp-timeago.md
=> 📖 Standalone documentation for amp-timeago and amp-instagram

extensions/amp-video/amp-video.md, extensions/amp-youtube/amp-youtube.md
=> 📖 Document standalone use and API for Bento amp-youtube, amp-video

extensions/amp-date-display/amp-date-display.md, extensions/amp-fit-text/amp-fit-text.md
Partial for #28281.
Partial for #30189.
=> Bento docs for amp-fit-text and amp-date-display

extensions/amp-social-share/amp-social-share.md
Update documentation to match bento template for `amp-social-share`
=> 📖 [bento][amp-social-share] Update bento documentation to match template

extensions/amp-accordion/amp-accordion.md
Update bento docs to match template.
Referenced template PR: https://github.com/ampproject/amphtml/pull/31944
=> 📖 [bento][amp-accordion] Update bento documentation to match template

src/service/navigation.js, test/unit/test-navigation.js
Addresses https://github.com/ampproject/error-reporting/issues/46
=> fix shadow doc navigation interception

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.143
=> SwG Release 0.1.22.143

extensions/amp-story/1.0/amp-story-consent.js, extensions/amp-story/1.0/amp-story-info-dialog.js
Support linker behavior on amp-story-consent and info-dialog.
Follows #32181
=> 🐛 [Story fixit] Added linker to consent and info-dialog

extensions/amp-story-panning-media/0.1/amp-story-panning-media.css, extensions/amp-story-panning-media/0.1/amp-story-panning-media.js, extensions/amp-story-panning-media/0.1/test/test-amp-story-panning-media.js
=> ✨ [Panning media] Use translate3d for transition

build-system/tasks/extension-generator/bento/amp-__component_name_hyphenated__/amp-__component_name_hyphenated__.md, extensions/amp-accordion/amp-accordion.md, extensions/amp-base-carousel/amp-base-carousel.md, extensions/amp-date-countdown/amp-date-countdown.md, extensions/amp-date-display/amp-date-display.md, extensions/amp-fit-text/amp-fit-text.md, extensions/amp-inline-gallery/amp-inline-gallery.md, extensions/amp-instagram/amp-instagram.md, extensions/amp-lightbox/amp-lightbox.md, extensions/amp-selector/amp-selector.md, extensions/amp-stream-gallery/amp-stream-gallery.md, extensions/amp-timeago/amp-timeago.md, extensions/amp-video/amp-video.md, extensions/amp-youtube/amp-youtube.md
=> Remove backticks for bento guide link

extensions/amp-story-360/0.1/amp-story-360.js, extensions/amp-story-360/0.1/test/test-amp-story-360.js, extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/test/test-amp-story-page.js
Details https://github.com/ampproject/amphtml/pull/32252#issuecomment-769250590
Stories use the role="button" to know not to navigate to the next page on click in some cases.
=> [amp-story] 🐛  Add role=button back to components that need it

package-lock.json, package.json
Follow up for #32076 #32109
Closes  #31838
=> [amp-viewer-integration] Bump up viewer-messaging version

css/ampshared.css, test/unit/test-layout.js, validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.html, validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.out, validator/testdata/transformed_feature_tests/server_side_rendering.html, validator/testdata/transformed_feature_tests/server_side_rendering.out, validator/validator-css.protoascii, validator/validator-main.protoascii
=> Add validation rules for aspect-ratio support via SSR

.circleci/config.yml, .circleci/fetch_merge_commit.sh, .circleci/install_dependencies.sh, .circleci/setup_storage.sh
- Move all cloud storage setup into `.circleci/setup_storage.sh`
- Move all node / dependency installation into `.circleci/install_dependencies.sh`
- Log coloring for readability
=> 🏗  Consolidate CircleCI VM setup steps into separate scripts

extensions/amp-story-auto-analytics/0.1/test/validator-amp-story-auto-analytics.html, extensions/amp-story-auto-analytics/0.1/test/validator-amp-story-auto-analytics.out, extensions/amp-story-auto-analytics/validator-amp-story-auto-analytics.protoascii, extensions/amp-story/1.0/test/validator-amp-story-amp-experiment-error.out, extensions/amp-story/1.0/test/validator-amp-story-amp-twitter-error.out, extensions/amp-story/1.0/test/validator-amp-story-cta-layer-error.out, extensions/amp-story/validator-amp-story.protoascii
Added validation for amp-story-auto-analytics
=> ✨  [Story auto-analytics] Added validation and tests

extensions/amp-anim/amp-anim.md
=> 📖  Fix missing space and mention `https` for amp-anim in emails

contributing/TESTING.md
Structure was changed on #30910.
btw:
```
npx markdown-toc --bullets="-" --no-firsth1 contributing/TESTING.md
```
=> 📖 Update TOC on TESTING.md

extensions/amp-story/1.0/amp-story-page.js
* Add maybeSetStoryNextUp_() to set default auto-advance-after value.
* Set `auto-advance-after` attribute to the value of `storyNextUp` param if (a) the current page is the last page, (b) the current page has no `auto-advance-after` set by the publisher AND (c) `storyNextUp` is set.
* Add isLastPage().
=> ✨ Add support for storyNextUp, to allow default auto-advance on last page.

validator/js/nodejs/README.md
=> Update node.js readme with htmlFormat parameter

extensions/amp-base-carousel/1.0/amp-base-carousel.css, extensions/amp-fit-text/1.0/amp-fit-text.css, extensions/amp-inline-gallery/1.0/amp-inline-gallery.css, extensions/amp-instagram/1.0/amp-instagram.css, extensions/amp-social-share/1.0/amp-social-share.css, extensions/amp-stream-gallery/1.0/amp-stream-gallery.css, extensions/amp-video/1.0/amp-video.css, extensions/amp-youtube/1.0/amp-youtube.css, src/service/loading-indicator.js, test/unit/test-loading-indicator.js
=> Ensure loader is marked up as a service element so that it doesn't get blocked by shadow

extensions/amp-a4a/0.1/test/test-amp-a4a.js, src/base-element.js, src/custom-element.js, test/unit/test-custom-element.js
=> Quick Fix: cleanup BaseElement internal state update from the CustomElement

.eslintrc.js
=> 🏗 Allow for...of on tests

src/service/resource.js, src/service/resources-impl.js, test/unit/test-resources.js
Shot in the dark at fixing: https://github.com/ampproject/error-reporting/issues/51
@dvoytenko / @jridgewell:  WDYT?
=> resources: unschedule removed resources

3p/bodymovinanimation.js
I missed this when merging #32315. This prevents the compiler from garbling property names on minification (in a possible future, this should work fine at the moment.)
=> 🐛  bodymovinanimation.js: safe bracket access

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg.js
=> swg release 0.1.22.144

build-system/common/ci.js
Fixes these typos:
https://github.com/ampproject/amphtml/pull/32421/files#diff-0eaf73b139ce456dfcc9e1edb747f8f714ae6bd8de9f7d171eba32d9fd6b7e5fR96
https://github.com/ampproject/amphtml/pull/32421/files#diff-0eaf73b139ce456dfcc9e1edb747f8f714ae6bd8de9f7d171eba32d9fd6b7e5fR110
Follow up to #32421
=> 🏗 Use correct env var to check for PR / push

extensions/amp-brid-player/0.1/amp-brid-player.js
Small change to pass isAutoplay value to player
=> Pass isAutoplay to player

src/inabox/inabox-resources.js, test/unit/inabox/test-inabox-resources.js, tools/experiments/experiments-config.js
Closes #31776
https://experiments.corp.google.com/#/portal/study/contentads::920739/analysis?label=_:AvRSei7THBjY_v9bltXVzHJhqYE
=> 🚀 Launch eager building of amp elements in inabox/fie resources

extensions/amp-a4a/rtc-documentation.md, extensions/amp-a4a/rtc-publisher-implementation-guide.md, src/service/real-time-config/callout-vendors.js
* add prebidopenx as a vendor to RTC config
* add vendor to documentation pages
=> ✨ Add prebidopenx as a vendor to RTC config

spec/amp-story-player.md, src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
Closes #32101
Related #31392
Adds support for an autoplay API which publishers can use to override the default autoplay behavior on the player. 
By default the player will play the first story when the player becomes visible, but this is not the desired behavior for some users. They want to be able to control when the player starts playing the first story.
With this API, publishers can opt-out of autoplay like this:
```html
<amp-story-player style="width: 360px; height: 600px;">
<script type="application/json">
{
"behavior": {
"autoplay": false
}
}
</script>
... // stories
</amp-story-player>
```
=> [amp-story-player] ✨ Add autoplay API

build-system/global-configs/prod-config.json
=> Launch layout-aspect-ratio-css to 10%

extensions/amp-form/amp-form.md
This paragraph lacked a section header, so it seemed part of the `Polyfills > Validation` section. Move up into its own section.
=> 📖 Move autoexpand paragraph into correct section

extensions/amp-iframe/0.1/amp-iframe.js, extensions/amp-iframe/0.1/test/test-amp-iframe.js
Part 2 of https://github.com/ampproject/amphtml/pull/32459
Fixing https://github.com/ampproject/amphtml/issues/32449
=> amp-iframe: unlayoutOnPause

build-system/externs/amp.extern.js, build-system/test-configs/dep-check-config.js, extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, src/service/real-time-config/real-time-config-impl.js, src/services.js
https://github.com/ampproject/amphtml/pull/31101
It moves the rtc related code into a service.
=> ♻️ Move RTC to a service

ads/google/a4a/sticky-ad-transition-exp.js
The existing one expired. Need to update to a newly starting experiment ID.
=> Update amp-ad sticky experiment number

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
This experiment adjusts some css for amp-ad. To verify there is no functional difference.
=> 🧪 Ramp up sticky-ad-transition experiment to 0.01

spec/amp-actions-and-events.md, spec/amp-email-actions-and-events.md
Some events are incorrectly located in the actions section and vice
versa.
/to @caroqliu
=> 📖  Fix amp-list event and action documentation

build-system/pr-check/cross-browser-tests.js
=> 🏗 Fix message in `cross-browser-tests.js`

extensions/amp-playbuzz/0.1/utils.js, extensions/amp-user-notification/0.1/amp-user-notification.js, package-lock.json, package.json, src/impression.js, src/polyfills/fetch.js, src/polyfillstub/intersection-observer-stub.js, src/polyfillstub/resize-observer-stub.js, src/runtime.js, src/service/resource.js, src/service/resources-interface.js, src/service/viewer-interface.js, src/style.js, third_party/subscriptions-project/swg.js
Renovate seems to be down temporarily, so I'm manually bumping closure to Feb's version.
https://app.renovatebot.com/dashboard#github/ampproject/amphtml/
=> 🏗 Update closure compiler to February's version

examples/image-slider.amp.html, extensions/amp-image-slider/0.1/test/integration/test-amp-image-slider.js
=> Fix very slow tests due to unsplash response times

test/integration/test-amphtml-ads.js
Example failure link: https://app.circleci.com/pipelines/github/ampproject/amphtml/1549/workflows/cdbc541d-1fdb-467a-9a28-6612a08f542f/jobs/14788/parallel-runs/0/steps/0-108
Related to #24421
=> ❄️ Skip flaky ads tests

extensions/amp-base-carousel/1.0/test-e2e/test-carousel.js
Example failure link: https://app.circleci.com/pipelines/github/ampproject/amphtml/1549/workflows/cdbc541d-1fdb-467a-9a28-6612a08f542f/jobs/14794/parallel-runs/0/steps/0-108
Related to #24195
=> ❄️ Skip flaky carousel test

extensions/amp-sidebar/0.1/amp-sidebar.js, extensions/amp-sidebar/0.2/amp-sidebar.js
=> Remove onLayoutMeasure and getLayoutSize from sidebars

build-system/compile/sources.js
=> amp-fit-text: Add cross-version dependencies to source files

test/integration/test-extensions-loading.js
The tests skipped in this PR are [failing consistently in master.](https://app.circleci.com/pipelines/github/ampproject/amphtml/1632/workflows/b015c46e-7d72-44d2-b858-03d61ce0d6a0/jobs/15686) Investigating now but wanted to unblock master first.
cc build hall monitors @kristoferbaxter @estherkim
=> Skip failing tests in Experiment C branch

extensions/amp-story/amp-story-analytics.md
Adds the tag names for the components that are trackable by the `story-open/close` triggers. Also adds an example.
=> [amp-story] 📖 Specify tagNames for trackable components

src/service/real-time-config/callout-vendors.js
We want to add the GDPR consent string to our callout url.
=> ✨ Add Gdpr Consent String to Yieldlab callout vendor

extensions/amp-story/amp-story.md
Pointed out by WP support rep Lucky.
=> amp-story.md: Fix minor typo

ads/vendors/feedad.js
This PR removes the adConfig dependency.
=> Unbundle feedad ad impl from adConfig

examples/visual-tests/amp-video-docking/amp-video-docking.js, test/visual-diff/visual-tests
=> ❄️ Disable flaky visual diff tests

extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Launch Adsense ad size optimization experiment.
PTAL. @calebcordry, @powerivq, @charliereams,
=> 🚮  Launch Adsense ad size optimization experiment.

build-system/tasks/bundle-size/filesize.json
Related to https://github.com/ampproject/amp-github-apps/issues/1224
=> 🏗 Track bundle size of 3p integrations

extensions/amp-video/amp-video.md
Stories determine whether they display a mute button based on the `noaudio` attribute:
https://github.com/ampproject/amphtml/blob/d8e92a3b6027b5c8f4b0adcb08840d69004dd6f2/extensions/amp-story/1.0/amp-story.js#L2584-L2592
=> 📖 Clarify effects of `noaudio` inside <amp-story>

build-system/babel-config/unminified-config.js
Right now, esbuild is treating the transformed Babel output as the real "source" code, because it doesn't see a sourcemap to trace through. By having Babel output an inline sourcemap, esbuild will trace through our transformed code back into the real source files.
- [Before](https://justin.ridgewell.name/source-map-visualization/#base64,dmFyIF9fZGVmUHJvcCA9IE9iamVjdC5kZWZpbmVQcm9wZXJ0eTsKdmFyIF9fbWFya0FzTW9kdWxlID0gZnVuY3Rpb24odGFyZ2V0KSB7CiAgcmV0dXJuIF9fZGVmUHJvcCh0YXJnZXQsICJfX2VzTW9kdWxlIiwge3ZhbHVlOiB0cnVlfSk7Cn07CnZhciBfX2V4cG9ydCA9IGZ1bmN0aW9uKHRhcmdldCwgYWxsKSB7CiAgZm9yICh2YXIgbmFtZSBpbiBhbGwpCiAgICBfX2RlZlByb3AodGFyZ2V0LCBuYW1lLCB7Z2V0OiBhbGxbbmFtZV0sIGVudW1lcmFibGU6IHRydWV9KTsKfTsKCi8vIHNyYy9wdXJlLWFzc2VydC5qcwpfX21hcmtBc01vZHVsZShleHBvcnRzKTsKX19leHBvcnQoZXhwb3J0cywgewogIFVTRVJfR …
=> 🏗️  Output inline sourcemaps during esbuild

test/unit/test-url-replacements.js
Related to https://github.com/ampproject/amphtml/pull/32530
Related to https://github.com/ampproject/amphtml/issues/32710
=> Tests for AUTHDATA selection when both amp-access and amp-subscriptions available

build-system/global-configs/prod-config.json, test/unit/test-layout.js
=> Launch layout-aspect-ratio-css to 100%

build-system/externs/amp.extern.js, build-system/test-configs/dep-check-config.js, extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, src/service/real-time-config/real-time-config-impl.js, src/services.js
Reverts ampproject/amphtml#32386
Reason https://github.com/ampproject/amphtml/issues/32713
=> Revert "♻️ Move RTC to a service"

extensions/amp-analytics/0.1/test/vendor-requests.json, extensions/amp-analytics/0.1/vendors/clicky.json
* Add referer to initial pageview request
* Prevent interval request from firing immediately
=> Small changes for Clicky Web Analytics vendor

build-system/tasks/bundle-size/APPROVERS.json, build-system/tasks/bundle-size/README.md
Closes https://github.com/ampproject/amp-github-apps/issues/1224
=> Update APPROVERS.json to use globext syntax and add `dist.3p/current-min/vendor/*.js`

build-system/tasks/extension-generator/index.js
=> 🏗 Add license to HTML file generated for new extension

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
=> Cleanup fie-resources flags

src/service/resources-impl.js
**summary**
potentially fixes `b/178971515`
=> resources: disable intersect-resources for email

spec/amp-story-player.md, src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
Closes #32580
* Adds a configuration option to disable page scrolling.
Example for opting out of page scrolling:
```html
<amp-story-player style="width: 320px; height: 538px">
<script type="application/json">
{
"behavior": {
"pageScroll": false
}
}
</script>
...
</amp-story-player>
```
* Propagates touch events as DOM events, `touchmove` includes a `isNavigationalSwipe` so that developers trying to use the swipe for other things can ignore it.
a usage example:
```js
player.addEventListener("touchmove", (event) => {
if (
event.detail.isNavigationalSwipe ||
event.detail.isNavigationalSwipe === null
) {
// Ignore when swiping to next story.
return;
}
// Start closing the player.
});
```
=> [amp-story-player] Propagate touch events and disable scroll

src/polyfills/intersection-observer.js, test/unit/polyfills/test-intersection-observer.js
Fixes https://github.com/ampproject/error-reporting/issues/55
TODO:
=> Force polyfill in the FIE iframes if the document root feature is not supported

build-system/tasks/build.js, build-system/tasks/dist.js
For build time performance concerns.
=> 🏗 Disable building 3p integration vendor

examples/visual-tests/amp-video-docking/amp-video-docking.js, test/visual-diff/visual-tests
=> ✅ Ensure that amp-video-docking visual tests lack a scrollbar

build-system/compile/bundles.config.js, build-system/compile/compile.js, build-system/tasks/3p-vendor-helpers.js, build-system/tasks/dist.js, build-system/tasks/extension-helpers.js, package-lock.json, package.json
The ESM output is identical with and without it.
=> 🏗 Remove esmPassCompilation from build-system

extensions/amp-mathml/0.1/test/test-amp-mathml.js
Fixes #32841
Unit test coverage: 79.17% (using `gulp unit --coverage`)
=> ✅  [amp-mathml] add unit tests

build-system/tasks/check-video-interface-list.js, spec/amp-video-interface.md
=> 🏗 amp-video-interface can use links from amp.dev

contributing/release-schedule.md, contributing/validator-release-schedule.md
=> validator release schedule

build-system/compile/bundles.config.extensions.json, extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-cta-button.css, extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-inabox.css, extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-shared.css, extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css, extensions/amp-story-auto-ads/0.1/story-ad-page.js, extensions/amp-story-auto-ads/0.1/story-ad-ui.js, extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js, src/inabox/inabox-story-ad.js
Isolates pub styles from runtime styles to protect the CTA button.
Closes #28865
=> ✨Move Story Ads CTA to shadow

extensions/amp-accordion/0.1/amp-accordion.js, extensions/amp-accordion/0.1/test/test-amp-accordion.js
=> ♿ amp-accordion: Respect pre-existing role attribute

validator/validator-main.protoascii
See https://github.com/ampproject/amphtml/pull/32851
Part of https://github.com/ampproject/amphtml/issues/27590
=> ✨ Validator: Enable the i-amphtml-binding attribute for faster amp-bind

test/integration/test-amp-img.js
See flake history: http://amp-test-cases.appspot.com/test-results/history/644ca2f72a281d7990cdf21dd2c5a9ed
=> ❄️ Skip flaky amp-img integration test

test/integration/test-amp-img.js
Revert and fix for https://github.com/ampproject/amphtml/pull/32929
=> Fix a flake on media change

extensions/amp-sidebar/0.1/test-e2e/test-amp-sidebar.js, extensions/amp-sidebar/1.0/test-e2e/test-amp-sidebar.js, test/fixtures/e2e/amp-sidebar/amp-sidebar.html
Add e2e tests for amp-sidebar `1.0`
=> ✅ [bento][amp-sidebar][fixit] Port sidebar e2e tests to from 0.1 to 1.0

extensions/amp-social-share/1.0/test-e2e/test-amp-social-share.js, test/fixtures/e2e/amp-social-share/amp-social-share.html
Add e2e tests for amp-social-share
Related to: https://github.com/ampproject/amphtml/issues/25284
=> ✅ [bento][amp-social-share][fixit] Add e2e tests for social-share

extensions/amp-accordion/1.0/amp-accordion.js, src/service/action-impl.js
First step in unifying event triggering logic (https://github.com/ampproject/amphtml/issues/32756). This PR introduces `ActionInvocation#triggerWithDispatch` temporarily, so files can be updated asynchronously/across multiple PRs avoiding merge issues. Once all uses are migrated, it can be renamed to `trigger` across codebase with find-replace.
=> ♻️ Fixit: dispatchCustomEvent in ActionInvocation#trigger

src/amp-story-player/amp-story-player-impl.js
Currently if you want to add a property inside a `StoryDef` you have to remember to add it both in `initializeStories_` and `add()`. This consolidates that logic into `initializeAndAddStory_()`
* Renames build_(story) to more accurate name buildIframeFor_(story).
* Renames initializeStories_() to more accurate name initializeAnchorElStories_().
* Consolidates logic that previously needed to be added in both add() and initializeStories_() into new initializeAndAddStory_(story).
=> [amp-story-player] ♻️  Mini refactoring

extensions/amp-story/1.0/amp-story.js, src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
Closes #31424
Adds `player.rewind(storyUrl)` API to replay a given story inside of the player.
=> [amp-story-player] ✨♻️  Rewind API

extensions/amp-a4a/0.1/secure-frame.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, src/friendly-iframe-embed.js
Follow up to #32820.
Closes #32832
=> ✨Allow AMP polyfills in no-signing

build-system/tasks/storybook/OWNERS
@ampproject/wg-components use Storybook too so they should be stakeholders of this directory's health.
=> 📖 Add wg-components to storybook OWNERS

build-system/common/utils.js, build-system/tasks/prettify.js
Otherwise could check files generated by a task running on CI.
=> Check only tracked files

validator/js/webui/serve-standalone.go
=> 🐛 Fix a bug that validator webui incorrectly serves custom validator.js

ads/vendors/fusion.js, extensions/amp-ad-exit/0.1/amp-ad-exit.js, extensions/amp-analytics/0.1/transport-serializer.js, extensions/amp-apester-media/0.1/utils.js, extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js, extensions/amp-base-carousel/0.1/responsive-attributes.js, extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js, extensions/amp-story/1.0/amp-story-access.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/animation.js, extensions/amp-stream-gallery/1.0/test/test-amp-stream-gallery.js, src/utils/media-query-props.js
Use a builtin instead of wrapping in function.
=> ♻️ Use filter(Boolean)

build-system/common/utils.js
https://app.circleci.com/pipelines/github/ampproject/amphtml/3283/workflows/d22cd99d-ad74-4326-873e-6b77fcc82e34/jobs/39542/parallel-runs/0/steps/0-107
=> Revert "Check only tracked files"

extensions/amp-a4a/rtc-documentation.md, extensions/amp-a4a/rtc-publisher-implementation-guide.md, src/service/real-time-config/callout-vendors.js
Hi @lannka!
Could you please review this PR and let me know if anything else is needed? It's just another vendor RTC endpoint.
Thanks!
=> ✨ Local Media Consortium: Add RTC endpoint to callout-vendors.js

extensions/amp-accordion/1.0/amp-accordion.js, src/service/action-impl.js
Reverts ampproject/amphtml#32884
Context thread: https://github.com/ampproject/amphtml/issues/32756#issuecomment-788082430
=> Revert "♻️ Fixit: dispatchCustomEvent in ActionInvocation#trigger"

build-system/tasks/ava.js
1. Pass `--watch` for `ava --watch`.
2. Use `npx ava`.
=> 🏗 gulp ava --watch

extensions/amp-delight-player/0.1/test/test-amp-delight-player.js
Fixes #32949 
This change increases code coverage in `amp-delight-player` from 47.67% to 66.28%
(Measured using the `--coverage` flag with `gulp-unit`)
=> ✅ [`amp-delight-player`] Add more unit tests to improve coverage.

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Partial for #30952.
The experiment is implemented in #33000.
=> Fully launch disable-a4a-non-sd

build-system/global-configs/prod-config.json
=> Unlaunch layout-aspect-ratio-css

build-system/common/git.js
Fix bug in counting cherry picks; accounting for an empty string.
=> 🐛 Get number of cherry picks bug

src/custom-element.js, test/unit/test-custom-element-registry.js, test/unit/test-custom-element.js
=> Explicitly specify the version of automatic legacy extensions

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/friendly-frame-util.js, extensions/amp-a4a/0.1/head-validation.js, extensions/amp-a4a/0.1/template-validator.js, extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js, src/friendly-iframe-embed.js, test/unit/test-friendly-iframe-embed.js, testing/describes.js
=> Multi-version: support and requirements for ads

extensions/amp-accordion/1.0/test-e2e/test-amp-accordion.js, extensions/amp-accordion/1.0/test-e2e/test-single-expand.js, test/fixtures/e2e/amp-accordion/amp-accordion.html, test/fixtures/e2e/amp-accordion/single-expand.html
Add e2e tests for amp-accordion bento
Tracker: https://github.com/ampproject/amphtml/issues/30445
=> ✅  [bento][amp-accordion][fixit] Bento accordion e2e tests

ads/_a4a-config.js, build-system/compile/bundles.config.extensions.json, build-system/test-configs/dep-check-config.js, examples/valueimpression.amp.html, extensions/amp-ad-network-valueimpression-impl/0.1/amp-ad-network-valueimpression-impl.js, extensions/amp-ad-network-valueimpression-impl/0.1/flexible-ad-slot-utils.js, extensions/amp-ad-network-valueimpression-impl/0.1/test/test-amp-ad-network-valueimpression-impl.js, extensions/amp-ad-network-valueimpression-impl/0.1/test/test-flexible-ad-slot-utils.js, extensions/amp-ad-network-valueimpression-impl/OWNERS, extensions/amp-ad-network-valueimpression-impl/amp-ad-network-valueimpression-impl-internal.md
This commit contains a fast fetch implementation for Valueimpression ad network.
This is my first time participating in the AMP Project, looking forward to helping.
=> ✨ Fast fetch implementation for Valueimpression network

extensions/amp-onetap-google/0.1/amp-onetap-google.js, extensions/amp-onetap-google/0.1/test/test-amp-onetap-google.js, extensions/amp-onetap-google/amp-onetap-google.md
Update `amp-subscriptions` entitlements after completing signup using `<amp-onetap-google>`.
=> ✨ amp-onetap-google refreshes amp-subscriptions

validator/js/nodejs/index.js
The next version of javascript validator will include an async initializer.
This PR lets the nodejs tool call the initializer if it exists.
=> 🐛 Check validator initialization in nodejs tool

extensions/amp-story/1.0/page-advancement.js
Reverts ampproject/amphtml#32518
Closes #33080
=> Revert "[amp-story] Prevent clicks on top 80%"

validator/js/webui/@polymer/webui-mainpage/webui-mainpage.html
The next version of javascript validator will include an async initializer.
This PR lets the WebUI tool call the initializer if it exists.
=> 🐛 Check validator initialization in webui tool 

src/service/extensions-impl.js
=> ✂️  Minor: extensions remove unused method

build-system/externs/amp.extern.js
Partial for #33001.
Follow up on #33024
=> Additional externs for module version and latest flags
