- src/service/performance-impl.js
- test/unit/test-performance.js
**summary**
- timeOrigin should be ticked as an absolute value as opposed to as a delta.
- resolves `b/137215986`
> 🐛performance-impl: timeOrigin should be a value instead of delta

- build-system/compile/compile.js
- build-system/tasks/dist.js
Support `--sourcemap_url` flag in `gulp dist` to customize the base URL
used in sourcemap links. The value passed to this flag should include a
placeholder `{version}` that will be replaced with the actual version.
For example:
```
gulp dist --sourcemap_url "https://example.com/{version}/root/" --version_override "12345"
```
would set the `amp.js` sourcemap URL to
```
https://example.com/12345/root/src/amp.js
```
This feature improves support for self-hosting the AMP runtime. It will be documented in the "Hosting the AMP framework" guide.
> build-system: Support alternate sourcemap URLs

- .travis.yml
- build-system/pr-check/dist-bundle-size.js
- build-system/pr-check/module-dist-bundle-size.js
- build-system/pr-check/utils.js
- build-system/tasks/presubmit-checks.js
#27685 made it so that ESM code was compiled during Travis CI. Given that the intent is to run a whole host of tests against ESM code, we want to stick with the model followed by multi-pass `gulp dist` (compile code in the `build` stage, upload to GCP, download and run tests in the `test` stage).
- Migrates the module job to `'Module Dist, Bundle Size'`, which is based on the current `'Dist, Bundle Size'` job
- Adds`yarn` checks before esm compilation (to prevent conflicts due to Travis merge commits)
- Adds a step to upload esm artifacts to GCP
- Adds placeholders for bundle size checks
- Adds the `--fortesting` flag so that integration tests can be run using a `localhost` server
**Successful upload:**
**Build time comparisons:**
`gulp dist --fortesting`: [5m …
> 🏗Lay groundwork for testing ESM code during CI

- build-system/pr-check/build-targets.js
- build-system/pr-check/validator-tests.js
- validator/java/.bazelrc
- validator/java/BUILD
- validator/java/build.sh
- validator/java/build_and_test.sh
- validator/java/install_bazel.sh
- validator/java/src/main/bin/copyValidatorJavaSource.sh
- validator/java/src/main/bin/fetchAMPResources.sh
#27271 added tests for the Java validator to our Travis CI workflow. A few follow up items remain.
- Add MacOS support to `validator/java/install_bazel.sh`
- Instead of a hard-coded SHA, download the correct `.sha256` for the installer
- Download with `curl -L`, which supports URL redirects (Linux and MacOS)
- Use latest version [3.0.0](https://github.com/bazelbuild/bazel/releases/tag/3.0.0) of `bazel`
- Perform a SHA check before installation on Linux and MacOS
- Substantially reduce logging verbosity on Travis in the passing case
- Make scripts return a failing exit status soon as a command fails
- Add a `.bazelrc` file for more streamlined output
- Refactor build target detection for `VALIDATOR` and `VALIDATOR_JAVA`
- Run `VALIDATOR_JAVA` tests when a `.protoascii` …
> 🏗 Validator Java test updates

- examples/visual-tests/amp-story/amp-story-bot-rendering.html
- extensions/amp-story/1.0/amp-story-page-attachment.css
- extensions/amp-story/1.0/amp-story-page-attachment.js
- extensions/amp-story/1.0/amp-story-vertical.css
- extensions/amp-story/1.0/amp-story.js
- Render remote attachments inline with their page to retain the correct ordering relationship.
- Support a title for the remote attachment anchor
- Don't overflow that title (render is completely)
> Small fixes for vertical rendering

- src/service/resource.js
- src/service/resources-impl.js
- test/unit/test-resources.js
Related to #25428.
More closely mimic the classical behavior of "explicit measure before layout" by checking if there's an unprocessed, "premeasured rect" from a more recent intersection callback. 
Noticed this potential issue in examples/everything.amp.html in an `amp-ad > amp-analytics` element that starts with size 1x1 and then gets hidden.
> intersect-resources: Fix incorrect pre-layout assumption

- extensions/amp-story/1.0/animation-presets.js
- extensions/amp-story/1.0/animation-types.js
- extensions/amp-story/1.0/animation.js
- extensions/amp-story/1.0/test/test-animation.js
- extensions/amp-story/1.0/test/test-full-bleed-animations.js
1. Presets are now a `{name: preset}` map, rather than a constructor function. Their `keyframes()` functions now take the element-defined options, rather than having a top-level constructor function. 
2. Test everything.
> ♻️✅ amp-story animations: test, refactor presets

- src/service/standard-actions-impl.js
**summary**
Recently, I've added support to `mutator-impl.mutateElement` to skip the remeasurement of an element in cases we know that it is unnecessary. I believe I've found another (albeit less significant) case.
The `hide()` action calls `mutateElement`, but I believe it then performs its own measurements within `collapseElement` (e.g. sets it all to 0, since `display:none`). It then sets relayoutTop and schedules a new pass.
> 🚀 amp-actions hide() can skipRemeasure

- examples/amp-story/attachment.html
- extensions/amp-story/1.0/amp-story-page-attachment.css
- extensions/amp-story/1.0/test/validator-amp-story-page-attachment-error.html
- extensions/amp-story/1.0/test/validator-amp-story-page-attachment-error.out
- extensions/amp-story/1.0/test/validator-amp-story-page-attachment.html
- extensions/amp-story/1.0/test/validator-amp-story-page-attachment.out
- extensions/amp-story/amp-story-page-attachment.md
- extensions/amp-story/validator-amp-story.protoascii
- Adds docs
- Adds validator rules
- Adds example
- Fixes robustness of drawer stylesheet (Ideally the UI would move into shadow DOM)
> Ship remote page attachments

- examples/amp-story/show-tooltip.html
- extensions/amp-story/1.0/page-advancement.js
Changing the name of the introduced `has-tooltip` #27549. Context in #27647
> Change name to show-tooltip

- build-system/global-configs/canary-config.json
- src/service/resource.js
- src/service/resources-impl.js
Related to #25428.
Also add a handy log for detecting forced remeasures e.g. due to `changeSize()`.
> intersect-resources: Fix bad devAssert

- build-system/tasks/css.js
- build-system/tasks/dist.js
- build-system/tasks/extension-helpers.js
- build-system/tasks/helpers.js
- build-system/tasks/lint.js
- build-system/tasks/presubmit-checks.js
- build-system/tasks/serve.js
- build-system/tasks/vendor-configs.js
- package.json
- yarn.lock
Several tasks in AMP's `gulp` toolchain provide `watch` functionality to enable rebuild-on-edit behavior. However, if a file is saved more than once in a short interval (e.g. hitting Ctrl+S twice in succession), the watcher function is kicked off more than once, which can lead to [races in file writes](https://github.com/ampproject/amphtml/issues/27722#issue-599001542).
- Uses [`debounce`](https://www.npmjs.com/package/debounce) for instances of `watchify` and `gulp-watch` that use a simple watcher function
- Uses [`gulp-debounce`](https://www.npmjs.com/package/gulp-debounce) for the one instance of `gulp-watch` that operates on the `gulp` stream
- Drive-by minor cleanup of `helpers.js`, `dist.js` and `lint.js`
**Tasks fixed by this PR:**
```sh
gulp
gulp …
```
> 🏗 Debounce all `watch` operations in the AMP dev toolchain 

- build-system/compile/debug-compilation-lifecycle.js
- build-system/compile/helpers.js
- build-system/compile/post-closure-babel.js
- build-system/compile/pre-closure-babel.js
Also adds sourcemaps debugging at each stage in the compilation process.
> 🏗 Do not write sourcesContent in sourcemaps unless requested

- build-system/tasks/presubmit-checks.js
- src/amp-story-player-impl.js
- src/amp-story-player-manager.js
Fixes  #27538
When calling `applySandbox()`, `devAssert()` was being called since one of the flags in the sandbox of the iframe isn't allowed in firefox. And since `devAssert()` hasn't been initialized, it was throwing an error. Calling `initLogConstructor()` initializes it.
> [amp-story-player] 🐛 Fixes firefox bug

- extensions/amp-story/1.0/amp-story.js
Added a comma to clarify a nonrestrictive clause in a comment as a trivial tweak
/cc @newmuis @gmajoulet
> Added comma to a comment as a trivial tweak

- extensions/amp-animation/0.1/web-animations-polyfill.js
Native Web Animations on WebKit do not respect easing for individual keyframes and break overall timing.
Fixes #27762 as a workaround for https://bugs.webkit.org/show_bug.cgi?id=210526
This was the only technique I could find that forces the polyfill across multiple checks. Alternatives tried:
1. Setting a global boolean to short-circuit a particular condition.
2. `delete win.Element.prototype.animate`
3. `delete win.document.documentElement.animate`
> 🐛 Force Web Animations polyfill on Safari

- babel.config.js
#27576 added a check to make sure none of AMP's `gulp` commands would inadvertently use the wrong babel config. However, this works badly with dev dependencies that use babel under the covers. For example, see the comment thread starting at https://github.com/ampproject/amphtml/issues/27718#issuecomment-613611374
This PR does two things:
- Makes caller extraction resilient to the case where there's no caller at all
- Prints a warning instead of throwing an error when an unrecognized / empty caller is encountered
Partially fixes #27718
> 🏗Don't throw an error when an unrecognized `babel` caller is encountered

- src/polyfills/custom-elements.js
This is a continuation of #25245. All of our Custom Elements extend from a common `CustomAmpElement` class, which itself extends from `HTMLElementPolyfill`. In #27470, I removed the `constructor` from `CustomAmpElement` class. But, because it's a subclass and must have a `constructor` that calls `super()`, Closure replaced it with a `constructor() { superClass.apply(this, arguments); }` when transpiling.
But, due to the same faulty inheritance chain described in #25245, `HTMLElementPolyfill` doesn't inherit an `apply` method! So doing `superClass.apply()` throws an error. 😭
This PR installs all important Function methods onto our polyfill, to be resilient to any future changes in the instance creation.
Fixes #27660
Fixes #27775
> 🐛 Fix Custom Element instance creation in IE11, redo

- extensions/amp-video/0.1/amp-video.js
- extensions/amp-video/0.1/test/test-amp-video.js
- src/preconnect.js
Under this scenario a video might not fall back to the origin on pre-render.
Possible fix for #27109
Reproduces by navigating (locally) to [page with a video on page one in prerender mode](http://localhost:8000/proxy/s/stories.nonblocking.io/waffles/?usqp=mq331AQFKAGwASA%3D&amp_js_v=0.1#referrer=https%3A%2F%2Fwww.google.com&visibilityState=prerender&cap=swipe&ampshare=https%3A%2F%2Funumbox.com%2Fwebsite-development-trends-2020-amp-story%2F),
waiting for the prerender load to fail, and then executing `AMP.viewer.receiveMessage('visibilitychange', {'state': 'visible'})` in the console.
If this if not a fix for #27109, then it might be the same race, but elsewhere. The problem is that you cannot wait for `loadPromise` on a video element that has failed a source and has just had a new source …
> Fix nasty race condition in AMP video

- build-system/pr-check/build-targets.js
- build-system/pr-check/build.js
- build-system/pr-check/checks.js
- build-system/pr-check/dist-bundle-size.js
- build-system/pr-check/e2e-tests.js
- build-system/pr-check/experiment-tests.js
- build-system/pr-check/local-tests.js
- build-system/pr-check/module-dist-bundle-size.js
- build-system/pr-check/single-pass-tests.js
- build-system/pr-check/validator-tests.js
- build-system/pr-check/visual-diff-tests.js
- build-system/tasks/pr-check.js
From #27786, it turns out that there is no guarantee that the Java validator is always in sync with amphtml code. Therefore, we cannot run these tests in blocking mode all the time.
**PR changes:**
- Exclude validator-related runtime changes from the `VALIDATOR_JAVA` build target
- For PR builds, run `gulp validator-java` in blocking mode for the `VALIDATOR_JAVA` target
- For PR builds, run `gulp validator-java` in non-blocking mode for the `RUNTIME` target (in the absence of the `VALIDATOR_JAVA` target)
- For Push builds, run `gulp validator-java` in non-blocking mode
- For local PR checks, run `gulp validator-java` in blocking mode for the `VALIDATOR_JAVA` target
Partial fix for #27786
> 🏗Java Validator testing changes

- css/ampshared.css
- test/fixtures/overflow.html
- test/integration/test-css.js
Related to #25428.
`[overflow]` elements currently increase size of parents that use sizers (responsive/intrinsic) after `buildCallback`. For example:
```html
<amp-iframe layout=responsive width=100 height=100>
<div overflow style="height: 20px>Overflow</div>
</amp-iframe>
```
This is due to the following CSS rule:
https://github.com/ampproject/amphtml/blob/876ef78fbbb2ccc281a3766b911b8e8c645ad633/css/ampshared.css#L234-L238
This PR makes the pre-build sizing behavior consistent by overriding `display: none` with `display: initial`. The overflow is not displayed already due to `visibility: hidden`.
Re: `intersect-resources` experiment, this bug can result in incorrect cached layout boxes for affected elements. More generally, any unsanctioned change in size (not through the `changeSize()` …
> 🐛 Avoid [overflow] layout shift after buildCallback

- validator/README.md
Tapping `caskroom/cask` returns an error. 
This updates the command for installing Homebrew Cask.
> Updates Homebrew Cask install command.

- build-system/babel-config/post-closure-config.js
Services break module patterns, and the current transform is not designed to handle this issue when running post closure compilation.
> 🏗 Temporarily disable function transform due to Services implementation

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/test/test-amp-story-page.js
https://github.com/ampproject/amphtml/pull/27366 has an optimization to run the `registerAllMedia_()` only once. But the `background-audio` is built and added to the DOM on `layoutCallback`, which happens after the first call to `registerAllMedia_()` for pages with distance > 2.
Fixes https://github.com/ampproject/amphtml/issues/27573, https://github.com/ampproject/amphtml/issues/27779
> Register story page level background-audio.

- src/service/standard-actions-impl.js
- test/unit/test-standard-actions.js
**summary**
When showing a hidden element, we must remeasure that element as well as everything below it (via `relayoutTop`). I just found an edge case where we miss the remeasurement, which would cause all the elements below the shown one to have stale (and incorrect) measurements.
The bug only strikes if all three conditions are met:
- On an iOS device
- Calling `.show()` with a target that is not an amp element (e.g. a div)
- Element we are showing requires `autofocus`
> 🐛 .show() for iOS and autofocus must always remeasure

- build-system/babel-config/replace-plugin.js
- build-system/tasks/build.js
- build-system/tasks/default-task.js
- build-system/tasks/dist.js
> Add --define_experiment_constant as valid flag

- .renovaterc.json
When renovate was originally installed to keep `amphtml` dependencies up to date, only the root `package.json` was opted in.
Since then, various developers have added a bunch of new `package.json` / `pom.xml` files without opting them in to automatic updates. This frequently results in security vulnerabilities due to outdated dependencies.
This PR removes the `includePaths` section of `.renovaterc.json` and enables automatic updates for the following files:
I'll merge this after checking with the respective owners on whether automatic updates are desirable, and if not, we can add specific files to `ignorePaths`.
With this, security vulnerability reports for AMP should become less frequent.
> 🏗📦 Switch renovate updates for `amphtml` from opt-in to opt-out

- extensions/amp-analytics/0.1/amp-analytics.js
- extensions/amp-analytics/0.1/linker-manager.js
I don't see any need to return a promise for the LinkerManager.init()
The initialization is asynchronous but not blocking any service.
> Remove linker initialization promise

- extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
- extensions/amp-consent/0.1/test-e2e/test-amp-consent-client-side.js
- extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side.js
I can't reproduce the test failure locally. Tried the fix a few times on travis, seemed to work. 
Confirmed with @estherkim `await expect(url).to.have.been.sent` only check the urls till the check is invoked. 
I added a timeout before verifying the outgoing request to minimize the flakiness.  An ideal fix would be to have something like `await expect(url).to.have.eventually.been.sent`. 
Closes #27634
> Unskip amp-consent e2e test

- build-system/pr-check/build-targets.js
Based on #27786, it isn't guaranteed that the validator java tests will always pass on `master`. Therefore, they shouldn't be run as blocking checks for any code other than the java validator code in and of itself.
This PR removes `VALIDATOR_JAVA` as a blocking check for `amphtml` package updates, which would earlier run _**all**_ test targets.
Follow up to #27788
> 🏗Don't run `VALIDATOR_JAVA` tests for `amphtml` package updates

- .github/ISSUE_TEMPLATE/release-tracking-issue.md
* Switch explanation to using pre-existing Nightly releases instead of cutting a `canary` branch
* Consistent capitalization of release channels
> 📖 Updates to the release issue template

- extensions/amp-animation/0.1/web-animations-polyfill.js
> 🐛 Different method to bail out of native Animation on Safari

- src/service/mutator-impl.js
**summary**
No point in calling `calcRelayoutTop` if we aren't going to remeasure anyway.
> mutator: skip an extra measure

- .codecov.yml
We've had code coverage reports for `amphtml` for a while via https://codecov.io/gh/ampproject/amphtml. However, our [config file](https://github.com/ampproject/amphtml/commits/master/.codecov.yml) has bit-rotted, and GitHub PR integration with codecov.io appears to have been shut off a while ago.
This PR updates the config in `.codecov.yml` based on the latest documentation here:
- https://docs.codecov.io/docs/codecovyml-reference
- https://docs.codecov.io/docs/pull-request-comments
- https://docs.codecov.io/docs/commit-status
**Next steps:**
> 🏗Update code coverage status configuration for `amphtml`

- extensions/amp-story/1.0/amp-story-draggable-drawer.js
- extensions/amp-story/1.0/amp-story-page-attachment.js
- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/amp-story-share-menu.js
- extensions/amp-story/1.0/amp-story-system-layer.css
- extensions/amp-story/1.0/amp-story-system-layer.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/pagination-buttons.css
- extensions/amp-story/1.0/pagination-buttons.js
- extensions/amp-story/1.0/progress-bar.js
- extensions/amp-story/1.0/semantic-render.js
- Turn mute/unmute into a real button.
- Restore focus outline for the pagination buttons.
- Use video `aria-label` in vertical rendering.
- Use `aria-hidden` to only expose current page.
- Mark pages as `role="region"`
- Mark the story itself as a live region.
- Hide share menu and bookend via `aria-hidden` when hidden.
- Hide progress bar from screen reader.
- Label the pagination buttons.
> A11Y changes for Stories

- examples/analytics-vendors.amp.html
- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors/moengage.js
- extensions/amp-analytics/0.1/vendors/moengage.json
- I2I reference: https://github.com/ampproject/amphtml/issues/27221
- Implemented amp-analytics for the vendor MoEngage.
- Docs for the client to use this plugin: https://docs.moengage.com/docs/amp-event-analytics
> ✨ New feature: Adding our platform MoEngage as an amp-analytics plugin.

- build-system/tasks/bundle-size/index.js
- package.json
- yarn.lock
Filesize 4.0.1 was released with improved concurrency, the ability to filter types of compression, and an updated API.
These changes have been applied in this PR.
|             | Local  | Travis |
|---        |---       |---       |
| Before | 4.23s  | 16s     |
| After    | **2.55s**  | **7.74s**  |
> 🏗 Update `@ampproject/filesize` to 4.0.1 with new API

- ads/inabox/inabox-messaging-host.js
Closes #27899 
I put a `dev().warn()` because long term we should remove the double event register. 
Another fix would be for the inabox iframeClient to not register listener twice.
> Do not override inabox host handler

- extensions/amp-sidebar/0.1/storybook/Basic.amp.js
Added two stories in storybook for amp-list
> 📖 Added basic storybook stories for amp-list

- extensions/amp-video/0.1/amp-video.js
> 🐛 amp-video NodeList to Array

- extensions/amp-consent/amp-consent.md
- extensions/amp-consent/customizing-extension-behaviors-on-consent.md
add @jawadst as reviewer as well. Open to suggestions. 
I am seeing this doc as the vendor facing one. 
amp-consent.md will be the publisher facing doc,
and integrating-consent.md will be the CMP facing doc. 
Thank you
> Improve vendor facing doc to collect consent related information. 

- extensions/amp-social-share/0.2/social-share.js
- extensions/amp-social-share/0.2/storybook/Basic.js
Add basic storybook story for amp-social-share component
Includes a change to preact amp-social-share file to include aria-label attribute.  (This is used for accessibility, and without the label an accessibility error is triggered in storybook.)
aria-label is used for screenreaders
---
My understanding of bento is limited so please feel free to recommend changes
> 📖 [amp-social-share] Add basic bento storybook story for amp-social-share component

- extensions/amp-social-share/0.1/storybook/Basic.amp.js
- extensions/amp-social-share/0.2/storybook/Basic.amp.js
Add storybook stories for v1 and v2 of amp-social-share component
- v1 is an amp component
- v2 is a bento component, story for v2 is for the amp version of component
- add documentation around use data-params for reference in v2 bento re-design (reproduced below)
```
* Key Configuration Parameters -
* type - This is a required attribute.  It configures a pre-configured set of parameters needed to share with a particular social-media.  Most notably, the share-endpoint is set by the type.  Configuration details can be found in amp-social-share-config.js.  The user may also select 'custom' with this knob to manually specify the required parameters.  Setting any of the other attributes below overwrites the pre-configured parameters defined by the type.
* data-share-endpoint - This is the api …
```
> 📖 [amp-social-share] Add storybook stories for amp version of component (v1 and v2)

- extensions/amp-next-page/1.0/service.js
- extensions/amp-next-page/1.0/test/test-amp-next-page.js
Fixes an issue that caused the recommendation box to override itself when using templates
> 🐛 Quick fix: amp-next-page templated recommendation box

- extensions/amp-consent/0.1/amp-consent.js
- extensions/amp-consent/0.1/consent-ui.js
- extensions/amp-consent/0.1/test/test-consent-ui.js
Keep track of `isActionPromptTrigger` when showing consentUI. 
`isActionPromptTrigger` was only used as part of clientInfo to be sent to iframe. 
Now it's also used to relax the restriction on `enter-fullscreen` signal sent from iframe. 
Closes #27819
> amp-consent allow full screen after promptTrigger: action

- build-system/tasks/babel-plugin-tests.js
- package.json
- yarn.lock
The latest version of `jest` (v25) introduces a [breaking change](https://travis-ci.org/github/ampproject/amphtml/jobs/678451955#L425-L447) in the CLI that makes it incompatible with `gulp-jest`. See https://github.com/ampproject/amphtml/pull/27973#issuecomment-618594375.
This PR does a minor refactor of AMP babel plugin tests and eliminates the use of `gulp-jest` in favor of directly using the `jest` CLI, which is now shipped as part of `@jest/core`.
- https://github.com/facebook/jest/issues/9512
- https://github.com/facebook/jest/pull/8874#discussion_r317470364
- https://jestjs.io/docs/en/configuration#options
Addresses https://github.com/ampproject/amphtml/pull/27973#issuecomment-618594375.
Closes #27973
> 🏗Make babel plugin tests work with `jest` v25

- ads/google/a4a/utils.js
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
- extensions/amp-ad/0.1/amp-ad.css
- tools/experiments/experiments-config.js
https://github.com/ampproject/amphtml/issues/27095
Create an experiment to try removing the CSS. It only affects the fast fetch. I don't feel we really need to test 3p mode, SG? @glevitzky
> 🖍Experiment to remove adsense/doubleclick centering css

- extensions/amp-story/1.0/amp-story.js
Remove the title only if the platform is not bot.
Used for crawling only, but remove otherwise.
Fixes #27997
> 🐛Remove title if not bot

- .codecov.yml
One of the AMP team's long-term goals is to improve release quality via automated testing. A few of the bugs we've found recently could have easily been caught by tests that were either missing or had been skipped.
Today, the AMP runtime code ([not counting](https://github.com/ampproject/amphtml/blob/90f1f7fcff01c68d703140e1cb6f6da2ebbabbef/build-system/babel-config/test-config.js#L30-L37) ads, infrastructure, third party, and test code) has a little more than 80% code coverage from unit tests as reported on [this dashboard](https://codecov.io/gh/ampproject/amphtml/tree/master) (click through for subdirectory-level numbers).
[![image](https://user-images.githubusercontent.com/26553114/80176366-57b94580-85c6-11ea-9650-daff77e406dc.png)](https://codecov.io/gh/ampproject/ampht …
> 🏗✨ Enforce a minimum of 80% code coverage for AMP source code

- build-system/common/git.js
- build-system/compile/internal-version.js
- build-system/tasks/build.js
- build-system/tasks/default-task.js
- build-system/tasks/dist.js
> Set the last three digit of the AMP version to be the number of cherry-picks in the branch

- extensions/amp-video/0.1/amp-video.js
- extensions/amp-video/0.1/test/test-amp-video.js
Decode errors do not fallback to the next available source. This code manually handles that fallback.
Fixes #27982
> Handle decode errors in amp-video

- build-system/global-configs/canary-config.json
This PR turns on the no css for canary.
> 🖍 Enable amp-ad-no-center-css CSS for canary

- build-system/babel-config/dep-check-config.js
- build-system/babel-config/pre-closure-config.js
- build-system/babel-config/test-config.js
- build-system/babel-config/unminified-config.js
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/index.js
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/fixtures/transform/argument/input.js
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/fixtures/transform/argument/options.json
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/fixtures/transform/argument/output.mjs
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/fixtures/transform/not-promise-resolve/input.js
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/fixtures/transform/not-promise-resolve/options.json
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/fixtures/transform/not-promise-resolve/output.mjs
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/fixtures/transform/promise-resolve/input.js
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/fixtures/transform/promise-resolve/options.json
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/fixtures/transform/promise-resolve/output.mjs
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/fixtures/transform/relative-importing/input.js
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/fixtures/transform/relative-importing/options.json
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/fixtures/transform/relative-importing/output.mjs
- build-system/babel-plugins/babel-plugin-transform-promise-resolve/test/index.js
- build-system/test-configs/dep-check-config.js
- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-next-page/1.0/service.js
- extensions/amp-story/0.1/amp-story-info-dialog.js
- extensions/amp-story/0.1/media-pool.js
- extensions/amp-story/1.0/amp-story-info-dialog.js
- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/media-pool.js
- package.json
- src/resolved-promise.js
- yarn.lock
Re: https://github.com/ampproject/amphtml/pull/27901
> Add shared Promise.resolve() babel transform

- .travis.yml
- validator/java/pom.xml
- Apply [pending updates](https://github.com/ampproject/amphtml/pulls?q=is%3Apr+is%3Aopen+%22validator%2Fjava%2Fpom.xml%22+sort%3Aupdated-desc) for `validator/java/pom.xml`
- Cache downloaded maven artifacts on Travis (https://github.com/travis-ci/travis-ci/issues/1441)
Partial fix for #27939
> 🏗Java Validator updates

- css/ampdoc.css
- css/ampshared.css
- examples/visual-tests/amp-list/amp-list.amp.html
- test/visual-diff/visual-tests
Partial for #26872.
"Initial content" is an alternative way of displaying placeholder content that supports DOM diffing. 
Currently, an amp-list's "initial content" is hidden before `buildCallback` due to existing AMP CSS rules. This PR adds a line of CSS to make it match the behavior of `[placeholder]`.
> amp-list[diffable]: Make initial content visible pre-build

- extensions/amp-story/1.0/amp-story-page-attachment.js
Close the remote attachment drawer when navigation deeplinked to another app.
Fixes https://github.com/ampproject/amphtml/issues/27981
> Close the attachment drawer when navigation deeplinked to another app.

- validator/validator_gen.py
- validator/validator_gen_js.py
- validator/webui/build.py
Changes are compatible with both Python 2.7 and Python 3.
- Remove 2.7 from shebang in `webui/build.py`
- Update `print` usage in `webui/build.py`
- Explicitly cast variables or fix types where necessary
Fixes: #26279
> validator: Python3 compatibility fixes

- extensions/amp-story/1.0/animation-types.js
- extensions/amp-story/1.0/animation.js
- extensions/amp-story/1.0/test/test-animation.js
Partial for #27758
1. Restructure `StoryAnimationConfigDef` so that it contains a `WebAnimationDef` without duplicate props.
2. Wrap `<amp-story-animation>` specs in a `StoryAnimationConfigDef`.
3. `<amp-story-animation>` passes the id of a `source` it will wait for. It can also define its own sequencing id.
> ✨ Sequence <amp-story-animation>

- third_party/nailgun/README.amp
- third_party/nailgun/nailgun-runner
Cherry-pick python3 compatibility fixes into nailgun client:
- [\[python3\] Fix memoryview to work with python3](https://github.com/facebook/nailgun/commit/90167a65969d90094d7997e0308d9ddb1124d4b6)
- [\[python3\] Ensure UTF8 strings are sent properly](https://github.com/facebook/nailgun/commit/f923d52beff7963f508b808f846f9970f97be0f6)
- [\[python3\] Remove bytes -> str conversion](https://github.com/facebook/nailgun/commit/878f95db2ec6cb3f69144ec456a4b3fa3f1eb2f9)
Changes are compatible with both Python 2.7 and Python 3.5+.
Fixes #26425
> third-party: Nailgun python3 compatibility improvements

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/test/test-amp-story-page.js
Every media element has to be registered into the mediapool before being loaded or played. This register() method is also where the sources are extracted. We wait for the amp-video we want to register to complete its layoutCallback (CommonSignals.LOAD_END), so all the sources, including the origin fallbacks, are in the DOM by the time they're extracted by the mediapool.
Note: I'm keeping preloading as a followup, cf https://github.com/ampproject/amphtml/issues/27983
Fixes https://github.com/ampproject/amphtml/issues/27109
> Wait for media layout before registering them into the mediapool.

- build-system/common/check-package-manager.js
Python 2.7 is EOL but still supported
Python 3.5+ are still supported (TODO: deprecate 3.5 on 2020-09-13)
https://devguide.python.org/#status-of-python-branches
Depends on #28037 and #28036
> build-system: Support python 3.5+

- css/ampshared.css
In #27083 the `disable-inline-width` attribute was introduced to allow “specifying the `sizes` on elements without getting the sizing behavior of sizes in AMP (which adds a width based on which media query matches).” This addressed #21736. 
In the WordPress AMP plugin we wrestled a lot with AMP's `sizes` behavior (#17053), leading us ultimately to remove the `sizes` attribute altogether to avoid it (https://github.com/ampproject/amp-wp/pull/2036). This was not ideal because even though WordPress generates images with `sizes` and `srcset`, for the sake of AMP we had to strip the `sizes` out. 
When [updating the validator spec](https://github.com/ampproject/amp-wp/pull/4548) in the plugin, I discovered the new `disable-inline-width` attribute and …
> 🐛 Restrict display:block/position:relative styles to implicit responsive layout

- src/service/resources-impl.js
- test/unit/test-resources.js
**summary**
Context `b/154603596`
This PR tells the resources service to send a `documentHeight` message after all amp elements have all laid themselves out. This message should correct previously sent messages which all occurred before amp finished applying styles.
Repro steps:
1. Go to the AMP4Email playground: https://amp.gmail.dev/playground/
2. Click on the Carousel template. Notice how it doesn't render properly
Testing done:
1. I used Charles Proxy on GMail and the Playground. I mapped both `v0.js` and the entire `v0/` folder to the local files after running `gulp dist` on this branch.
2. I then ensured that the carousel loads properly
**next steps**
- Add integration tests that we send out the correct `documentHeight`
cc @choumx
> Resources: send a documentHeight message after ampInitialized if height has changed.

- build-system/externs/amp.extern.js
- examples/bind/list.amp.html
- extensions/amp-bind/0.1/bind-impl.js
- extensions/amp-bind/0.1/test/integration/test-bind-impl.js
- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
- extensions/amp-list/validator-amp-list.protoascii
Another amp-list/amp-bind interaction option that straddles `refresh` and `always`.
Like `refresh`, don't wait for children to have their bindings evaluated/applied on initial render. However, asynchronously evaluate the expressions in those bindings and cache their results. 
The outcome is that in subsequent `setState()` calls, elements whose expression values don't change will be skipped. This is similar to `always` (modulo mutating DOM on initial render), and is desirable for some use cases related to binding on form inputs.
Meta: I'm not in love with this API and I'm considering alternatives. E.g. support `this` keyword for getting the current value in `[text]` bindings. 
`b/140023700#comment8`
> amp-list[binding=refresh-evaluate]

- .travis.yml
Now that the AMP toolchain is fully compatible with python3 (see #28037, #28036, and #28038, all courtesy @mdmower), it is time to set python v3 as the default for Travis jobs.
- Removes top-level [`python`](https://docs.travis-ci.com/user/languages/python/) version from `.travis.yml` ([doesn't work](https://travis-ci.community/t/please-activate-python-3-by-default-for-non-python-build/3899) for `language: node_js`)
- Makes known-good versions of python v2 and v3 globally available (using [`pyenv global`](https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-global-advanced))
- Makes all invocations of `python` default to v3 (first arg to `pyenv global` [gets precedence](https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-global-advanced)) 
**Install …
> 🏗 Use Python v3 on Travis

- src/custom-element.js
- src/service/resource.js
- test/unit/test-resource.js
In `intersect-resources`, it's more likely for elements to be measured before build (known case). But, `measure() > updateLayoutBox()` only calls `onLayoutMeasure`/`onMeasureChanged` if the element is built (oops).
Somewhat happily though, this fix means `intersect-resources` shouldn't be affected by #26866.
This affects all elements that rely on `onLayoutMeasure`, but especially `amp-ad` which face-plants if an element receives `layoutCallback` (render) before `onLayoutMeasure` (query).
> intersect-resources: Fix bug that skips onLayoutMeasure

- validator/testdata/feature_tests/regexps.html
- validator/testdata/feature_tests/regexps.out
- validator/validator-main.protoascii
Adds support for the new CSS API v2 so `https://fonts.googleapis.com/css2` URLs aren't flagged as being invalid AMP.
Fixes #27881.
> 🐛 Update validator regex to support Google Fonts CSS API v2

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/audio.js
Removes the `loop` attribute on the `audio` tag when a page is configured to auto-advance after its background-audio. Otherwise the page keeps looping rather than auto advancing.
eg: `<amp-story-page id="foo" background-audio="bar.mp3" auto-advance-after="foo">...</>`
Found while working on https://github.com/ampproject/amphtml/issues/28010
> Do not loop background audio when used to auto-advance.

- build-system/tasks/bundle-size/filesize.json
- build-system/tasks/bundle-size/index.js
- package.json
The `gulp bundle-size` check uses `@ampproject/filesize` to determine `brotli` sizes for minified JS files.
Storing the `filesize` config in `package.json` [breaks compatibility](https://travis-ci.org/github/ampproject/amphtml/jobs/678816324#L406-L411) between `yarn add` and `prettier`, causing them to go back and forth on formatting. See https://github.com/ampproject/filesize/issues/83#issue-605945124.
This PR moves the config from `package.json` to `build-system/tasks/bundle-size/filesize.json`. (`@ampproject/filesize` has already been updated in #28079.)
> 🏗 Move `filesize` config into its own file

- validator/webui/app.yaml
Go1.9 is deprecated on AppEngine, for the mean time use `runtime: googlelegacy`.
> WebUI app.yaml update to runtime

- extensions/amp-story/1.0/amp-story-share-menu.js
- extensions/amp-story/1.0/test/test-amp-story-share-menu.js
Closes #27826
Having attribute `hidden` was preventing the element from calling layoutCallback
> Fixes share button bug

- css/ampshared.css
The blurry image placeholder uses a transition to slowly fade the blur into the real image. When it's done, the blurry image is "hidden" via `opacity: 0` styles. Unfortunately, users can still interact with this blurry image, and because it overlays the entire image, can't interact with the real image.
Adding `pointer-events: none` seems to be the easiest fix. Other possibilities include adding a `transitionend` event to toggle `display: none` (requires JS, and slow), or converting to a CSS animation (unsure of browser support and smoothness).
Fixes b/153094647
Any chance this can fix b/149038942?
> 🐛 Prevent interaction with blurry-image placeholder

- src/polyfills/custom-elements.js
- test/unit/test-polyfill-custom-elements.js
- testing/describes.js
Old Safari has an interesting definition for `Element.p.innerHTML`: the descriptor is non-configurable and the `set` setter is undefined. In the old code, trying to patch this setter throws an error.
This leaves the document in a broken state. The first CE to be defined will not properly upgrade the elements that existed were already parsed on the page. Additionally, `innerHTML` will not properly sync-upgrade CEs that are parsed from the string, but they will async-upgrade via the `MutationObserver`.
Skipping this `innerHTML` patch shouldn't hurt, since we'll still get the async-upgrade. Safari 9 is sooo old, all we really need here is a best-effort "it kinda works".
- - -
This also adds a potential fix for Yandex browser not having an `innerHTML` descriptor. Based on the stack trace, the …
> 🐛 CEv1: Fix innerHTML patch in Safari <= 9 and maybe Yandex

- .eslintrc
- build-system/babel-config/pre-closure-config.js
- build-system/eslint-rules/get-mode-usage.js
- build-system/eslint-rules/no-import-rename.js
- build-system/tasks/presubmit-checks.js
- src/log.js
- src/mode-object.js
- src/mode.js
- test/unit/test-log.js
- test/unit/test-mode.js
Right now in production, we still include all of the code guarded by `getMode().test`. That's because it's a configuration value and not a compile time constant.
Now, test will be stripped out when running `gulp dist` if you do not include `--fortesting`. And other related `getMode` cleanups.
> Redefine getMode().test to only be true in local development

- build-system/compile/compile.js
We're seeing increasing instances of stalled `gulp dist` invocations on Travis.
The root cause of these stalls appears to be concurrency problems with our custom closure compiler `runner.jar`. Actually solving this problem needs us to eliminate `AmpPass.java` (#24047), which is currently blocked by #23960.
Meanwhile, this PR reduces closure concurrency on Travis from 4 to 2, to match the [number of cores](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system) in the default Xenial VMs.
Addresses https://github.com/ampproject/amphtml/issues/24487#issuecomment-621471530
> 🏗 Reduce closure concurrency on Travis from 4 to 2

- build-system/compile/bundles.config.js
- build-system/server/lazy-build.js
- build-system/tasks/helpers.js
During the default `gulp` task, we kick off a pre-build step for the core runtime and optionally some extensions, and start off the server. Meanwhile, if the developer loads an example page that tries to kick off a lazy-build for the same files, the lazy-builder uses the following mechanism to prevent a duplicate build, and waits for the pending build instead:
https://github.com/ampproject/amphtml/blob/67815dc7b6c1f434a09fcd52227a01f7b0b2c728/build-system/server/lazy-build.js#L51-L75
It turns out that the core runtime does not use this mechanism because of the special options it uses. Meanwhile, pre-built extensions do benefit from  duplicate-build detection.
This PR un-special-cases the core runtime as follows:
- Moves extra options for `amp.js` to …
> 🏗 De-dupe pre-build and lazy-build of `amp.js` during default `gulp`

- 3p/beopinion.js
- ads/_config.js
- extensions/amp-beopinion/0.1/amp-beopinion.js
- extensions/amp-beopinion/amp-beopinion.md
We changed domains and recently stopped using our old one. This PR fixes the `preconnect` links and scripts URLs.
> 🐛Update beop URLs after domain change

- extensions/amp-analytics/0.1/amp-analytics.js
This breaks selectors that looks like `:not(*)${gtm_css_1_0}`
I was wrong about the usage, looks like it is used a lot via gtm. 
Revert the proposed optimization
> Revert #27276

- build-system/babel-plugins/babel-plugin-transform-amp-asserts/index.js
- build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-boolean-non/output.js
- build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-number-non/output.js
- build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-dev-assert-string-not-string-non/output.js
- build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-devAssert-empty-string/output.js
- build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-devAssert-false/output.js
- build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-devAssert-null/output.js
- build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-devAssert-zero/output.js
- build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-devAssert/output.js
- build-system/babel-plugins/babel-plugin-transform-amp-asserts/test/fixtures/transform-assertions/transform-user-fine/output.js
- src/layout.js
This updates amp-asserts babel transform to match the code that AmpPass (which is being removed) generates.
Necessary for #24047
Fixes #23960.
> Update amp-asserts transform to match AmpPass's transformations

- README.md
This removes the Q2 devx survey link from README.
> Remove the Q2 devx survey link from README

- src/font-stylesheet-timeout.js
- test/unit/test-font-stylesheet-timeout.js
Make it so that the timeout
- Is as late as possible (reduces swaps)
- But still in time to enable a good LCP time (2500ms)
Related to #27776
> Change the LCP/CLS trade-off in font timeouts

- src/service/performance-impl.js
- test/unit/test-performance.js
Fixes regression blocking 4/7 inabox release. There are likely other perf improvements we could make for inabox in the `performance-impl` since the viewer will never exist, but those would be much larger changes.
> 🛑Disable all perf observers in inabox.

- build-system/common/utils.js
- build-system/tasks/e2e/index.js
- build-system/tasks/lint.js
- build-system/tasks/runtime-test/runtime-test-base.js
I tried passing `'**/test/**/*.js, **/test-e2e/**/*.js'` to the linter, but the space after the comma caused the second glob to not match anything.
> 🏗 Allow spaces between commas in files globs

- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- src/friendly-iframe-embed.js
- test/unit/test-friendly-iframe-embed.js
- tools/experiments/experiments-config.js
https://github.com/ampproject/amphtml/issues/27584
Chunking the FIE initialization steps. My local profiling shows that with the experiment on, the js execution block seems a bit smaller (210ms->160ms).
@calebcordry can you help validate that on your device?
Chrome profiling flame charts attached:
[Control group](https://github.com/ampproject/amphtml/files/4482935/Profile-Control.txt)
[Experiment group](https://github.com/ampproject/amphtml/files/4482936/Profile-Experiment.txt)
[Before this PR](https://github.com/ampproject/amphtml/files/4482933/Profile-Before.txt)
I have ran tests 25 times each on a low-end device for friendly iframe rendering of https://github.com/ampproject/amphtml/blob/master/test/fixtures/e2e/amphtml-ads/image.html
Ad rendering is delayed by 1697.08ms (use chunk API) …
> 🚀 Introduce more chunking in FIE init

- .github/ISSUE_TEMPLATE/cherry_pick_template.md
- .github/ISSUE_TEMPLATE/error-report.md
- .github/ISSUE_TEMPLATE/release-tracking-issue.md
Adds `/cc @ampproject/release-on-duty` to issue templates for releases, cherry-picks, and error reports, now that https://github.com/ampproject/amp-github-apps/issues/778 has added them.
> 🏗 Tag release on-duty team in issue templates

- build-system/test-configs/config.js
Addresses https://github.com/ampproject/amphtml/pull/28157#issuecomment-622561868
> 🏗 Ignore `.karma-cache` during lint / prettier checks

- build-system/tasks/runtime-test/helpers-unit.js
In #28131, the detection logic for affected files was fixed, resulting in PRs running more tests during `gulp unit --local_changes`. While this is good for local development (e.g. testing CSS changes is easier), it can lead to inefficiencies on Travis (e.g. A logging file is touched and ~4000 tests are affected, causing all those tests to be run twice).
This PR skips the `--local_changes` run on Travis when more than 20 test files are affected by a PR.
> 🏗 Skip `gulp unit --local_changes` on Travis if too many tests were affected

- .eslintrc
- build-system/eslint-rules/always-call-chai-methods.js
- build-system/eslint-rules/prefer-spread-props.js
- extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
- extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
- extensions/amp-form/0.1/test/test-amp-form.js
- extensions/amp-form/0.1/test/test-form-submit-service.js
- extensions/amp-fx-flying-carpet/0.1/test/test-amp-fx-flying-carpet.js
- extensions/amp-skimlinks/0.1/test/test-tracking.js
- extensions/amp-story/1.0/test/integration/test-amp-story-affiliate-link.js
- extensions/amp-story/1.0/test/test-animation.js
- extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
- extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
- extensions/amp-user-notification/0.1/test/test-amp-user-notification.js
- test/integration/test-video-manager.js
- test/unit/test-ampdoc.js
- test/unit/test-cid.js
- test/unit/test-document-submit.js
- test/unit/test-dom.js
- test/unit/test-json.js
- test/unit/test-object.js
- test/unit/test-polyfill-object-values.js
- test/unit/test-service.js
- test/unit/test-url.js
- test/unit/test-video-iframe-integration.js
Several assertions in chai are not automatically invoked during the getter (the `.ok` in `expect().to.be.ok`). Assertion methods, like `throw`, must be called for the assertion to run.
> ✅🏗 Ensure we always call Chai method assertions

- extensions/amp-analytics/0.1/config.js
- extensions/amp-analytics/0.1/test/test-config-new.js
I believe this is a bug. let me know if there's a reason not to expand analytic variables.
> Expand analytics variables in remote config url

- css/ampshared.css
- Adds unresolved layout for `intrinsic` styles
- Fixes specificity for unresolved `fixed-height` styles
- Adds unresolved implicit layout `responsive` styles
> 🖍 Cleanup several unresolved amp-layout CSS states

- build-system/tasks/e2e/index.js
- build-system/tasks/runtime-test/runtime-test-base.js
- build-system/tasks/visual-diff/index.js
`stopServer()` in `build-system/tasks/serve.js` was converted to an `async` function in [#27471](https://github.com/ampproject/amphtml/pull/27471/files#diff-68eb307bd570cd1da4673aa2f01e235c), but not all call sites were updated. Luckily, this hasn't broken things (yet) because they don't all trigger the asynchronous behavior.
This PR updates all call sites with `await`.
Addresses https://github.com/ampproject/amphtml/pull/28148#discussion_r419758970
> 🏗 Add missing `await` to `stopServer()` invocations

- validator/build.py
- validator/nodejs/cli.js
- validator/nodejs/index.js
- validator/nodejs/index_test.js
- validator/nodejs/package.json
The hashbang #!/usr/bin/env at the top of the node validator implementation causes problems when importing the file via require in Node >12. To address this, this commit moves the cli script into a separate file.
Fixes #28158
> Fix Node API on Node >12

- extensions/amp-script/0.1/amp-script.js
As part of https://github.com/ampproject/amphtml/issues/24266, error messages with substitutions aren't logged properly. Some parts of amp-script use `user().error()` to log locally, then `throw new Error()`, resulting in AMP Error Reporting getting a smattering of bare `Error: Error` reports, which add to error reporting noise and are difficult for a release on-duty to assess/debug
This PR updates those bare `throw`s to instead throw a user error with a useful message.
Closes https://github.com/ampproject/amphtml/issues/28184
> 🐛 Add error messages to thrown bare Error()s in `amp-script`

- examples/amp-script/amp-script-demo.js
- extensions/amp-script/0.1/amp-script.js
**summary**
Fixes https://github.com/ampproject/amphtml/issues/28198.
Adds an `onerror` handler to the worker script so that we can rethrow all errors as user errors instead of bubbling into a dev one. This should help clear some noise from the error tracker.
Here's a screenshot of the new error format:
cc @rcebulko @ampproject/wg-runtime
> amp-script: catch user errors in worker scripts

- .codecov.yml
- build-system/pr-check/local-tests.js
- There appears to be a problem with our `codecov` check, where it reports incorrect coverage levels for PRs from old branches: https://github.com/ampproject/amphtml/issues/28212#issuecomment-624286549
- In addition, there doesn't seem to be a straightforward way to override the baseline for comparisons: https://github.com/ampproject/amphtml/issues/28212#issuecomment-624326511 and https://github.com/codecov/codecov-bash/issues/83#issuecomment-606674059
- Meanwhile, it appears that the total project-level coverage was reduced from 80.5% to ~76-77% by https://github.com/ampproject/amphtml/commit/f26a825a35711b834d01165666f59e1d11f1b879. (It's currently unknown why this was so.)
This PR makes a few changes to temporarily work around the issues described …
> 🏗 Reduce coverage threshold for `codecov` check

- extensions/amp-list/amp-list.md
This is not supported in the AMP for Email spec.
/to @caroqliu 
/cc @samouri
> 📖 Exclude `amp-state:` documentation for email

- build-system/compile/compile.js
- build-system/compile/single-pass.js
I'd like to be able to use [nullish coalescing](https://v8.dev/features/nullish-coalescing).
Fails with current configuration:
```
ERROR - [JSC_LANGUAGE_FEATURE] This language feature is only supported for ECMASCRIPT_2020 mode or better: Nullish coalescing.
: rect[field] ?? 0;
```
> 🏗 Configure Closure Compile to use ECMASCRIPT_2020

- extensions/amp-3d-gltf/amp-3d-gltf.md
Updated amp-3d-gltf format to match [reference template](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/extension-generator/extension-doc.template.md)
> amp-rdu round 1 documentation update for amp-3d-gltf 

- extensions/amp-accordion/0.1/amp-accordion.js
- extensions/amp-base-carousel/0.1/amp-base-carousel.js
- extensions/amp-carousel/0.2/amp-carousel.js
- extensions/amp-inline-gallery/0.1/amp-inline-gallery-pagination.js
- extensions/amp-inline-gallery/0.1/amp-inline-gallery-thumbnails.js
- extensions/amp-inline-gallery/0.1/amp-inline-gallery.js
- extensions/amp-mega-menu/0.1/amp-mega-menu.js
- extensions/amp-nested-menu/0.1/amp-nested-menu.js
- extensions/amp-selector/0.1/amp-selector.js
- extensions/amp-sidebar/0.2/amp-sidebar.js
- extensions/amp-stream-gallery/0.1/amp-stream-gallery.js
- amp-accordion
- amp-base-carousel
- amp-carousel 0.2
- amp-inline-gallery
- amp-stream-gallery
- amp-mega-menu
- amp-nested-menu
- amp-selector
- amp-sidebar
- amp-stream-gallery
Some of these likely were just oversight. Others were not opted in because they don't have a `layoutCallback` but nowadays `buildCallback` is also guarded by `prerenderAllowed`.
> 🚀 Allow prerendering of more elements

- test/manual/amp-analytics/performanceTestPages/visible-multiple.html
Ads are currently not handled in the performance task. Will take a look at them after we stop the `performance experiment` from [failing](https://travis-ci.org/github/ampproject/amphtml/jobs/683920395).
> Temporarily remove ads from performance test pages

- src/multidoc-manager.js
- src/service/extensions-impl.js
- test/unit/test-extensions.js
- test/unit/test-runtime.js
Fixes the only two (that I've found) issues with module/nomodule script pairs:
1. When extensions are reloaded, we didn't mark all current scripts as "replaced".
2. When Multidoc inserts scripts into the new ampdoc, it couldn't correctly parse `v0.mjs`.
Everywhere else won't care about script pairs. The extension service collates all `custom-element` attributes into a set. Multidoc will try to insert the pairs twice (once for each script), but only the first will actually insert since it'll be registered. And reloading/inserting will always insert the correct `.js` or `.mjs` based on whether the runtime is currently using `getMode().esm`.
> Add support for module/nomodule script pairs

- build-system/common/utils.js
- build-system/tasks/e2e/index.js
**summary**
Currently, running e2e tests automatically launches a `dist` build of the runtime + extensions.  This PR adds the ability for the `gulp e2e` command to accept both the `--extensions` and `--core_runtime_only` flags which `dist` already accepts. This can significantly speed up the change/test loop.
> e2e tests: support building specific extensions instead of everything.

- extensions/amp-social-share/0.1/amp-social-share.js
> amp-social-share should not layout without a share endpoint

- build-system/test-configs/dep-check-config.js
- extensions/amp-analytics/0.1/linker-manager.js
- extensions/amp-iframe/0.1/amp-iframe.js
- src/enums.js
- src/service/ampdoc-impl.js
To fix #28220. 
TBH I still don't know what's causing the error. But the purpose of the check is to only initiate the linker manager once for each ampdoc. No need to check for `ShadowRoot`, the attribute can be applied to the document.body.
> 🐛 Register `LINKER_CREATED` on ampdoc instead of attribute

- extensions/amp-story/1.0/amp-story-page.js
Auto-playing videos might have already started pllaying by the time we attach the playing event listener. Since there isn't a direct attribute to tell whether a video is playing, this checks whether the `currentTime` is 0.
Fixes #28275
> Fix race condition that fails to hide video loading indicator

- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
- src/base-element.js
- src/custom-element.js
- src/service/resource.js
- src/service/resources-impl.js
- test/unit/test-resource.js
- test/unit/test-resources.js
Reverts ampproject/amphtml#28043.
This appears to be causing impression loss in 2005050322000 RC.
> Revert "🚮 Remove idleRenderOutsideViewport"

- examples/amp-story/amp-story-animation.html
- extensions/amp-story/1.0/animation.js
- extensions/amp-story/1.0/test/test-animation.js
This disambiguates effect specs that trigger with page entrance versus those that are triggered by other specs (subanimations).
Note that subanimations are not currently supported, but this change prevents issues when introducing the feature.
> ♻️ Require trigger="visibility" to run an <amp-story-animation> effect

- 3p/twitter.js
- build-system/tasks/presubmit-checks.js
This PR fixes a failure that snuck in with #28243.
It turns out we were missing a few runtime checks for package upgrades. Fix sent out in #28317.
> 🐛Fix `check-types` failure due to new closure version

- src/service/localization.js
- test/unit/test-localization.js
Closes #27023
Original description:
In platform contexts, it makes sense for document-rendered system-level user interfaces to be consistent across documents. This PR allows an AMP viewer or story player to specify a fragment parameter to indicate the language to be used, falling back to the document's language if unspecified.
Follows up on #27990 #27053
> 🌐 Allow language override from viewer context

- build-system/pr-check/build-targets.js
For package upgrades, we add all build targets to the set of targets to be tested / checked. However, `RUNTIME`, which is a special case target, was left out.
This PR adds an explicit build target for `RUNTIME` (that includes all files in the `src/` directory). Note that other files that do not explicitly match a target will still fall through to the `RUNTIME` target, and get tested.
It turns out this was the root cause of #28316 and the resulting failures on `master`.
Follow up to #27297.
> 🏗🐛 Fix build target logic by adding an explicit `RUNTIME` target

- build-system/common/utils.js
- build-system/pr-check/e2e-tests.js
- build-system/pr-check/experiment-tests.js
- build-system/tasks/e2e/index.js
- build-system/tasks/visual-diff/index.js
**summary**
Makes `gulp e2e` default to a faster unminified build and adds a `--compiled` flag as an option. This [brings it in line](https://github.com/ampproject/amphtml/pull/28305#discussion_r423225133) with other gulp tasks.
> 🚀 e2e tests: support fast (unminified) mode.

- build-system/global-configs/prod-config.json
analytics-chunks experiment = Break the analytics initialization to chunks (doesn't apply in inabox). 
While it's uncertain if the experiment helped with FID, it didn't lead to new errors. (errors from #28264 and #28200 were surfaced, not caused by the experiment). Should be safe to turn on in prod.
> Turn on analytics-chunks in prod

- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors/comscore.json
Warnings previously sent because of our requests to b instead of p. This will return a pixel to prevent the error.
> 🐛 [TAG-6201] use p in the amp request to avoid errors with response sizes

- src/error.js
The initial change was wrong; runtime is `1p`, `3p`, `inabox`, etc. Binary type is `rc`, `production`, `canary`, etc.
> 🐛 Use binaryType instead of runtime for pre-throttling

- src/preact/slot.js
`dev().assertElement()` was [recently introduced](https://github.com/ampproject/amphtml/pull/24047/files#diff-f5e4baf202eba6455d4b3142d8809a4bR48) but should be removed.
> Slot: `ref` should not be an element

- extensions/amp-analytics/analytics-vendors-list.md
- extensions/amp-analytics/integrating-analytics.md
As discussed here https://github.com/ampproject/amp.dev/issues/3926
We will keep a list of all the supported analytics vendors under the ampproject/amphtml repo. Then export the list to amp.dev to always keep the list updated. 
To not block the work on the amp.dev side, I'll update the list to include all missing vendor names in a following PR.
cc @matthiasrohmer
> 📖 Doc all supported analytics vendors

- build-system/compile/check-for-unknown-deps.js
Fixing regex checking for unknown dependencies. Apparently Closure changed the import identifier format
> Fix check for unknown deps regex

- .travis.yml
Sauce labs runs are currently unreliable due to disconnection errors. See https://github.com/ampproject/amphtml/issues/28343#issuecomment-628063934. This PR makes Sauce runs [non-blocking on Travis](https://docs.travis-ci.com/user/customizing-the-build#jobs-that-are-allowed-to-fail) until a fix is identified.
Temporary mitigation for #28343
/cc @ampproject/build-cop
> 🏗Make Sauce Labs runs non-blocking on Travis

- extensions/amp-base-carousel/0.1/auto-advance.js
- extensions/amp-base-carousel/0.1/test/test-carousel.js
Related to #28248: `prerenderAllowed` was enabled for `amp-base-carousel` and `amp-carousel` in #28203, but the pre-existing `pauseCallback` does not suffice to prevent carousel from auto-advancing when the document is in the prerender visibility state. This change explicitly checks for the visibility state as part of `shouldAutoAdvance_`, a tool that is used by both `amp-base-carousel` and `amp-carousel:0.2`.
Try this out by running `gulp` with the following local targets, modifying (and refreshing) between `#visibilityState=visible` and `#visibilityState=prerender`:
- [amp-carousel:0.2](http://localhost:8000/proxy/s/output.jsbin.com/zuvexej/quiet#visibilityState=visible)
- [amp-base-carousel](http://localhost:8000/proxy/s/output.jsbin.com/berayedowe/quiet#visibilityState=visible)
cc …
> [amp-carousel:0.2] Do not autoplay when document is not visible

- build-system/tasks/helpers.js
This PR updates `MINIFIED_TARGETS` and `UNMINIFIED_TARGETS` in `helpers.js` so they no longer have hard-coded extensions.
This allows `MINIFIED_TARGETS` to be reused by `gulp dist`, `gulp dist --esm`, and the upcoming `gulp release`. There is no longer the need to modify via `maybeToEsmName()` during `esm` builds.
Addresses https://github.com/ampproject/amphtml/pull/28344#discussion_r423951195
> 🏗 Make `AMP_CONFIG` target names easily reusable across `build-system/`

- .renovaterc.json
First step of https://github.com/ampproject/amphtml/issues/28322 , grouping PATCH and MINOR updates (separately) to once-a-day PRs weekday mornings.
> 🏗 Group minor and patch upgrades in once-a-day PRs

- extensions/amp-story/1.0/amp-story-system-layer.css
Prevent TalkBack from selecting and reading hidden text by adding `visibility: hidden` to elements.
This fixes text content in the page notification and sound display containers.
Consistently order css declarations in the modified blocks.
Contributes to #28293 and #28294
[Screen recording before](https://drive.google.com/file/d/118P7sxG4p6rlQPI_5lSYNQsqzVCa9GFO/view?usp=sharing)
[Screen recording after](https://drive.google.com/file/d/1DfjnmUfG4S2f8b_5gkajvFckG9Qjnt1b/view?usp=sharing)
> Prevent TalkBack from selecting hidden text.

- spec/amp-boilerplate.md
Resolves https://github.com/ampproject/amp.dev/issues/3940.
The boilerplate generator while being a useful tool gets little recognition. Adding this hint to the boilerplate spec which surfaces at amp.dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate/ might help.
> Add hint about amp.dev's boilerplate generator to boilerplate spec

- build-system/tasks/runtime-test/helpers.js
We used to print messages during Sauce Labs runs for the `browser_start` and `browser_complete` [Karma events](http://karma-runner.github.io/4.0/dev/public-api.html). This was done in order to help debug stalled builds. With recent work, it turns out that these messages are unnecessary, and in fact, can make the logs confusing to read.
- Prints the list of the browsers being tested at the start of each batch
- Eliminates inline logging for `browser_start`
- Eliminates non-error inline logging for `browser_complete`
| Before  | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/26553114/81971422-0d3c4f00-95ef-11ea-9284-f3dd95712c60.png) | ![image](https://user-images.githubusercontent.com/26553114/81971469-21804 …
> 🏗 Improve Sauce Labs logging

- extensions/amp-story/1.0/animation.js
`start()` was previously a workaround for `pause()` calls failing in case the animation is `finish()`ed and internal players are orphaned:
https://github.com/ampproject/amphtml/blob/b6313e372fdd1298928e2417dcc616b03288e051/extensions/amp-animation/0.1/runners/native-web-animation-runner.js#L204-L205
(Players are _not_ orphaned when the animation is finished naturally, only when calling `finish()`)
However, `start`ing a finished animation will restart it, instead of keeping it in its finished state. This is problematic when trying to tap elements that get paused on `touchstart`.
> 🐛 try/catch when pausing animations

- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/test/test-amp-story.js
Adds `<amp-story muted>` attribute when story is muted, and tests to check functionality.
Can be used in CSS to change styles using `amp-story[muted]` or `amp-story:not([muted])`
Resolves #28395
> Added muted attribute to amp-story

- extensions/amp-story-education/0.1/amp-story-education.js
Story navigation was completely blocked after prerendering the education screens, because somehow the `pointer-events: none;` was not respected and the `amp-story-education` element was acting as a click shield. Hiding it entirely works though, and does not change the animations.
I've also seen race conditions where we try to access the ampdoc too early through the `getLocalizationService` method.
To verify the fix:
1. Open the link in mobile emulation
2. In the console, copy/paste `AMP.viewer.receiveMessage('visibilitychange', {'state': 'visible'})`
3. Try to navigate to the next page
[This story has the fix](https://stamp-storytime-le.firebaseapp.com/examples/s20/body-painting/index.html?amp_js_v=0.1#origin=https://www.google.com&prerenderSize=1&visibilityState=prerender&paddingTop=0&p2r …
> Unblock Story navigation after prerendering the education screens.

- build-system/tasks/e2e/describes-e2e.js
- examples/viewer.html
- src/service/resources-impl.js
- test/e2e/test-document-height.js
- test/fixtures/e2e/amp-carousel/0.1/document-height.html
- test/unit/test-resources.js
**do not merge until may 5th**
Better long term fix for https://github.com/ampproject/amphtml/pull/28065.
We decided to initially opt for #28065 because it is less risky and we'd like to unblock gmail, and then switch to this solution for future cuts. It was less risky because it preserves behavior.
Old behavior during init for a `display:none` iframe was as follows:
1. documentHeight: 0
2. documentHeight: 20 (incorrect and sent before amp finishes initializing)
3. documentHeight: correct number
New behavior with this PR will be:
1. documentHeight: 0
2. documentHeight: correct number
This should result in fewer flickers for consumers of the `documentHeight` message.
cc @ampproject/wg-runtime 
TODO:
> Resources: wait until amp init before sending documentHeight

- extensions/amp-analytics/0.1/config.js
- test/manual/analytics-batching.amp.html
Fix a regression caused by #28261.
`AnalyticsConfig.vendorConfig_` is always a json object. Check for `type` attribute instead. 
Change in behavior: Now we also throw error for invalid vendor type. I'm ok with this change.
> 🐛 Analytics config: Do not check inline transport setting without vendor specified

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
- extensions/amp-analytics/0.1/amp-analytics.js
- extensions/amp-analytics/0.1/analytics-group.js
- extensions/amp-analytics/0.1/cookie-writer.js
- tools/experiments/experiments-config.js
Since there's no objection from the ads team, I'll start with experimenting the feature in AMPHTML ads. 
Introduced a separate experiment because `analytics-chunks` has been turned on to AMP docs.
> Introduce 'analytics-chunks-inabox' experiment

- extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
- extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
- extensions/amp-ad-network-adsense-impl/OWNERS
Fix the logic for saving the enableAutoAdSize flag in local storage:
1. The flag saving flow should not be controlled by the experiment.
2. The data will be returned in the form of string and need an extra step for JSON parsing.
> 🐛 Bug fix: Fix the logic for saving the enableAutoAdSize flag in local storage.

- extensions/amp-ad-exit/0.1/amp-ad-exit.js
- extensions/amp-link-rewriter/0.1/link-rewriter.js
- src/service/navigation.js
- src/service/url-replacements-impl.js
- test/unit/test-url-replacements.js
I wanted to clean up the urlReplacement Service and refactor the Expander class a bit. 
First thing I noticed is that `expandUrlSync` and `expandStringSync` takes in unused variable `opt_collectVars`. 
There's no need to collect vars synchronously. 
I removed the unused variables. This also fix a bug in RTC where we failed to handle the allowed macro list. 
https://github.com/ampproject/amphtml/blob/49f075c0f4c2ee02d7dee9eb92c02fb3609b6475/extensions/amp-a4a/0.1/real-time-config-manager.js#L143
> 🐛♻️ Remove unused 'opt_collectVars' from expandUrlSync 

- .renovaterc.json
Iterations on renovate config.
> 🏗 Fix PR titles and remove reviewer teams

- build-system/test-configs/conformance-config.textproto
- extensions/amp-story/1.0/amp-story-affiliate-link.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/test/test-amp-story.js
toggleAttribute is not widely supported so it fails on multiple platforms (iOS <=11, various Android)
Switched to using setAttribute and RemoveAttribute.
Resolves #28463
> 🐛Change toggleAttribute to set/removeAttribute

- .renovaterc.json
- package.json
Attempting to separate major updates in different directories by hijacking the branch name
> 🏗 Tweak renovate grouping and re-disable PR creation

- 3p/integration.js
- ads/_config.js
- ads/yahoofedads.js
- ads/yahoofedads.md
- examples/ads.amp.html
- extensions/amp-ad/amp-ad.md
Adds support to render Yahoo Native-Display Ad Federation units using the amp-embed tag.
Sample Rendering
Test page on localhost:
http://localhost:8000/examples/ads.amp.html?type=yahoofedads
> ✨support for amp-embed type=yahoofedads

- src/service/resources-impl.js
Partial for #25428.
I originally thought that elements outside of the rootMargin need special handling (explicit measures), but I forgot that the initial observer callback includes all observed elements which will provide a measurement to all elements on the page.
So just removing the early-out might do the trick. 😅
> intersect-resources: Enable idle render

- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
- src/service/resources-impl.js
Current amp-ad type=doubleclick will send all requests ASAP independent of location relative to viewport (ensuring the creative is ready to render as soon as possible) but will delay render based on data-loading-strategy value. However, publishers may instead prefer to delay the ad request based on viewport location (and thus render). This PR allows publishers to do so on a per slot basis via data-lazy-fetch=true attribute. When set, fetch will be delayed until the slot is within the viewport margin specified via data-loading-strategy: absent/invalid uses 3, can set an explicit numeric value for viewports, or prefer-viewability-over-views which uses 1.25. Note the following:
lazy requesting and SRA cannot both be enabled, lazy requesting usage on ANY slot will disable SRA for ALL slots …
> Doubleclick lazy fetch

- extensions/amp-image-lightbox/0.1/amp-image-lightbox.js
- extensions/amp-image-lightbox/0.1/test/test-amp-image-lightbox.js
Moves the `addToWhitelist` from `buildLightbox_` to `buildCallback`. Fixes #28504
> Allow amp-image-lightbox to "open" in AMP4Email

- build-system/global-configs/experiments-config.json
- src/inabox/inabox-viewport.js
- src/service/viewport/viewport-impl.js
- src/service/viewport/viewport-interface.js
Enables Move FixedLayer experiment and resolves issues with experiment. Tests were failing due to missing `fixedLayer_` property on viewport, used by `amp-sidebar` via publicly accessible APIs. 
Verified tests failing [here](https://travis-ci.org/github/ampproject/amphtml/jobs/687565149) are resolved via running commands from `experiment-tests.js` gulp task.
> 🚀 Fix & enable Move FixedLayer experiment

- .travis.yml
Unblocks https://github.com/ampproject/amphtml/pull/28538 by allowing `renovate` to be installed.
> 🏗 Install the latest version of Yarn for Travis builds

- build-system/tasks/e2e/amp-driver.js
- build-system/tasks/e2e/describes-e2e.js
- examples/viewer.html
- test/e2e/test-document-height.js
- test/fixtures/e2e/amp-viewer-integration/viewer.html
**Summary**
The current e2e viewer fixture is a mishmash of code for manual and automated testing. This yields a slightly more confusing test harness than necessary, and very likely slower e2e tests because for every 1 test page we load 9 unrelated ones (not that e2e tests are a bottleneck in our dev process). This PR separates out the two.
I followed these steps:
1. `cp examples/viewer.html test/fixtures/e2e/amp-viewer-integration/viewer.html`
2. Deleted everything that seemed related to only manual testing from the new file.
3. Deleted everything related to e2e testing from `examples/viewer.html`
Addresses https://github.com/ampproject/amphtml/issues/28200.
> E2e viewer fixture

- ads/nativery.js
convert NodeList to array before using forEach
> fix to conformance error

- build-system/global-configs/prod-config.json
Expanding the experiment from 2.5% to 50%. This PR removes the amp-ad's centering CSS rule.
> Enable 50% on prod for amp-ad-no-center-css

- build-system/tasks/integration.js
- build-system/tasks/karma.conf.js
I'm not sure if this is useful or not, but it has allowed me to add "debugger" statements while fixing/creating integration tests. is there an alternative to this or a process that i dont know while doing integration?
> Add "debug" flag to `gulp integration`

- extensions/amp-story/1.0/amp-story.css
Fixes #28199
Enforces `position: absolute` on video elements in stories.
cc @ampproject/wg-stories
> 🖍 Lock video position inside Story

- build-system/tasks/dist.js
This PR logs the experiment being enabled when `--define_experiment_constant` is used with `gulp dist`.
We should have done this a long time ago. Hopefully, it will help debug build problems with experiments.
> 🏗 Print experiment info as part of help text in `gulp dist`

- extensions/amp-consent/0.1/amp-consent.js
Don't throw user error if no metadata is included
> 🐛 Add metadata user error restriction

- extensions/amp-a4a/0.1/amp-a4a.js
Wraps part of a4a request/response in its own method to prep for removal of signing. Should be no significant logic change. `?w=1` is helpful for cleaner github diff.
> ♻️ Extract signing flow into own method

- validator/validator-main.protoascii
In reported in a [support topic](https://wordpress.org/support/topic/src-in-tag-img-i-amphtml-intrinsic-sizer-is-set-to-the-invalid/) for the the AMP plugin, validation errors were being reported for transformed `amp-img` that contained an intrinsic sizer image as follows:
```html
```
Note the space appearing before the `<svg>` element in the `data:` URL. This space is getting added by a WordPress page caching plugin which is mutating the HTML to inject this space as part of its processing. This is very similar to another issue (https://github.com/ampproject/amp-wp/issues/4491) where caching plugins may try to optimize the HTML by removing the trailing slash of the `svg` element. Note that both of these issues would be avoided if the sizer SVG image was base64-encoded: …
> 🐛 Allow whitespace to precede intrinsic sizer SVG element in data: URL

- extensions/amp-story/1.0/amp-story-reaction-quiz.css
Two main CSS fixes:
1) Quizzes would keep the accent color around the letter of the selected option, but it should remove the outline instead. Pictures below.
Why change the color instead of remove the border? Because the layout would shift by 4px if the border was removed. This way the circle stays centered and there are no layout shifts. Also the circle occupies the same area as before.
2) The option backgrounds would "peek" from the left when the percentage was 0% and have minor weird behaviors because of unnecessary 1px and 2px measurements. Not all glitches were caught on first image, but it shows up slightly on the unselected options at the very left (with the wider border which shows part of the background).
Before:
After:
Resolves #26617
> 🖍 Changed circle color

- extensions/amp-story/1.0/media-pool.js
Fixes #28625
In Firefox, `cloneNode()` does not properly copy the `muted` audio/video DOM property that was set in the seed node. This seems like a Firefox bug, because this does not happen in Chrome.
To repro, try this in Chrome / Firefox:
```
videoEl.muted = true;
const clonedEl = videoEl.cloneNode(true /** deep */ )
```
Firefox:
```
clonedEl.muted 
> false
videoEl.muted
> true
```
Chrome
```
clonedEl.muted
> true
videoEl.muted
> true
```
> 🐛 Fix unmuted audio bug in FF

- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- tools/experiments/experiments-config.js
Adds diversion point, experiment will not be launched until logic is complete.
Part of #27189
> 🧪Introduce a4a-no-signing experiment diversion

- build-system/babel-config/pre-closure-config.js
this is currently breaking the prod version of esm build. turn it off temporarily
> turn off function decl transformer temporarily in pre closure

- build-system/tasks/presubmit-checks.js
In Presubmit Checks and other locations, the term `whitelist` is used when `allowlist` is preferred.
This PR moves Presubmit Checks over to `allowlist`.
> 🏗 Use allowlist instead of whitelist

- examples/runtime/animals.json
- examples/runtime/list-always.html
**summary**
https://github.com/ampproject/amphtml/pull/28503 introduced a few issues. This addresses one of them. Namely that `file://` paths can't be used as the src for an `amp-list`.
- page still looks the same when accessed through `gulp` default server.
> runtime perf pages: amp-list should use state

- validator/testdata/transformed_feature_tests/server_side_rendering.html
- validator/testdata/transformed_feature_tests/server_side_rendering.out
- validator/validator-main.protoascii
This makes the intrisic sizer more robust against html minification and
saves 21 bytes:
```
data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9Ijc1IiB3aWR0aD0iNzUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIi8+
data:image/svg+xml;charset=utf-8,<svg height=&quot;75&quot; width=&quot;75&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; version=&quot;1.1&quot;/>
```
See https://github.com/ampproject/amp-wp/issues/4491
> ✨Validator: base64 encoding for SSR'd intrinsic sizer

- src/error.js
Fixes #28649
However, we still need to investigate why there is an "expected error" on every story page load.
> 🐛 Don't attempt to unhide the body for expected errors.

- build-system/tasks/performance/load-config.js
- build-system/tasks/performance/measure-documents.js
pupeteer treats an `undefined` value for a key as `true`. this pr explicitly sets it to false.
**to test**
- confirm that `gulp performance` runs in headless mode
- confirm that `gulp performance` on this branch does not run headless.
> gulp performance: force headless/devtools to bool

- extensions/amp-story/1.0/amp-story-embedded-component.js
- I think the role should be preferred over a custom label.
- Adding focus fixes keyboard navigation of links.
Fixes #25729
> ♿ Assign correct aria-role to tooltips and give them focus.

- build-system/compile/log-messages.js
since module builds and nomodule builds are built in different runs it is unlikely that they are able to share the same extracted messages table. the module build and nomodule build each need to have theyre own json file with theyre unique tables.
> add an mjs or js suffix to output json file

- extensions/amp-fit-text/0.1/amp-fit-text.js
I'm slightly puzzled how exactly this is happening, but this makes `amp-fit-text` robust for the case where content div isn't the same size as the element itself.
Fixes #28330
> 🐛 Fix amp-fit-text with content div that is smaller than the container.

- builtins/amp-img.js
- test/unit/test-amp-img.js
When we [start SSR rendering](https://github.com/ampproject/amphtml/issues/28672) the internal `<img>` tag, we need to be a bit careful with the order with the intrinsic `i-amphtml-sizer`. This is because the intrinsic sizer itself includes an `<img>` tag. So we need to limit the SSR'd `<img>` to being a direct child only.
> 🐛 Fix any issues with SSR rendered intrinsic amp-img

- examples/pinterest.amp.html
- extensions/amp-pinterest/0.1/test/test-amp-pinterest.js
- extensions/amp-pinterest/0.1/util.js
Credit to @jridgewell for doing the original debugging.
Fixes #13881
> 🦟 Pinterest data comes HTML encoded, not URL encoded.

- extensions/amp-fit-text/0.1/amp-fit-text.js
- extensions/amp-fit-text/0.1/test/test-amp-fit-text.js
Doesn't support changing HTML children, which would be much more complicated without Shadow DOM.
Fixes #17895
> ✨ Add support for writing and reading textContent on amp-fit-text.

- .travis.yml
* `canary` - no longer exists
* `nightly` - always an unneccesary rerun on an already green commit
* `release` - no longer exists
> 🏗 Remove branches from Travis push builds

- build-system/babel-config/pre-closure-config.js
The fallback sets a `src` attribute if there is not one and the browser doesn't understand `srcset`. It's just for IE.
> Strip srcset fallback for ESM builds

- extensions/amp-analytics/0.1/resource-timing.js
- extensions/amp-analytics/0.1/test/test-resource-timing.js
Part of https://github.com/ampproject/amphtml/issues/16226
The use here was unnecessary because `entry.name` is of type `URL` which already has accessors for host, etc.
> ♻️ Remove use of parseUrlDeprecated from amp-analytics

- extensions/amp-story/amp-story.md
This removes amps-story's component reference documentation from the "websites" filter in the component reference docs.
Pro: This is technically fixes things, as you can not use the <amp-story> element on an AMP website.
Con: Comes at the expense of slight decrease of discoverability, as devs have to switch to stories format first to get all the story documentation.
/cc @sebastianbenz @CrystalOnScript
> 📖 Remove <amp-story> element documentation from "websites"

- extensions/amp-video/0.1/amp-video.js
This is how real posters behave. Only needed if the poster size isn't the same as the video size.
Manually validated that this makes poster positioning perfect.
Fixes #28586
> 🐛  Center emulated video posters.

- build-system/global-configs/prod-config.json
Partial for #25428.
CSI graphs look good and ad metrics are neutral. Did some manual testing on Chrome desktop on Safari iOS on the Top Stories/Visual Stories carousels and amp.dev.
> Enable 'intersect-resources' on 10% of prod

- 3p/polyfills.js
- build-system/babel-config/pre-closure-config.js
- builtins/amp-img.js
- src/css.js
- src/polyfills.js
- src/service/resources-impl.js
This will still allow the code to DCE, and is less brittle than using the import's path and local binding. See https://github.com/ampproject/amphtml/pull/28817/files#r438452603.
Also skips `installGetBoundingClientRect`, which is only needed for old IE.
> ♻️ Use IS_ESM to skip polyfills/fixes

- extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md
- extensions/amp-ad-network-doubleclick-impl/lazy-fetch.md
Documentation on how publishers can delay ad request until the slot is near the viewport.   Feature implemented in #28552
> Add documentation for amp ad type Doubleclick lazy fetch

- extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
- extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
AMP could reject ad size optimization's attempt to resize the element in the viewport. This fix add a check to avoid the unnecessary alignment with viewport if the resize failed.
@calebcordry PTAL.
> 🐛 Bug fix: Avoid aligning to the viewport if the full-width resize failed before.

- 3p/mathml.js
Fixes: https://github.com/ampproject/amphtml/issues/26082
Update the config object for the `mathjax` library to remove math formulas from tabIndex (user will no longer be able to access the math formula by tabbing to it, (this is desired))
> 🐛 [amp-mathml] Update config to remove math formulas from tabIndex

- build-system/server/new-server/router.js
add a try catch when using postHTML. this allows us to print the html that might have issues processing
Fixes #28800
> catch any errors while `transform` is called

- extensions/amp-ima-video/amp-ima-video.md
The old link to ImaSdkSettings went 404. This updates the link to the new location.
> 📖 Update link to ImaSdkSettings

- extensions/amp-story/1.0/amp-story.js
This prevents TalkBack from reading/announcing information and labels that are not currently visible on the page.
This prevents TalkBack from reading story page content automatically, making the experience more consistent with TalkBack's default behavior.
This makes #28780 obsolete.
This fixes #28408 and #28294.
> ♿  Remove aria-live attribute on amp-story.

- build-system/tasks/presubmit-checks.js
- extensions/amp-consent/0.1/amp-consent.js
- extensions/amp-consent/0.1/cmps.js
- extensions/amp-consent/0.1/consent-config.js
- extensions/amp-consent/0.1/consent-state-manager.js
- extensions/amp-consent/0.1/consent-ui.js
- extensions/amp-consent/0.1/test/test-amp-consent.js
- extensions/amp-consent/0.1/test/test-consent-config.js
- extensions/amp-consent/0.1/test/test-consent-state-manager.js
- extensions/amp-consent/0.1/test/test-consent-ui.js
- src/services.js
> Support variable expansion in amp-consent

- extensions/amp-story/1.0/story-analytics.js
Always prefix auto advance advancement modes with `autoAdvance`, so viewers can easily write a future proof `isAutoAdvance()` helper to use with the `selectDocument` message.
> Always prefix auto advance advancement modes with autoAdvance.

- src/amp-story-player/amp-story-player-impl.js
Closes #28777
Only add additional sandbox flag when iframe was sandboxed previously. Otherwise it causes some unexpected behavior in different browsers.
> 🐛 Only add additionaly sandbox flag when iframe was sandboxed previously

- extensions/amp-access/0.1/amp-access-source.js
- extensions/amp-access/0.1/amp-access.js
- extensions/amp-analytics/0.1/events.js
- extensions/amp-analytics/0.1/instrumentation.js
- extensions/amp-analytics/0.1/test/test-events.js
- extensions/amp-next-page/1.0/service.js
- extensions/amp-subscriptions/0.1/analytics.js
- src/analytics.js
- src/error.js
- src/extension-analytics.js
- test/manual/amp-analytics/default-data-vars.html
Closes #28636 
As we agreed all attributes starts with `data-vars` from the target element will be passed as analytics variables. Extension defined variables will override the publisher set data-vars.
> Include data-vars value to all analytics events by default

- .travis.yml
- build-system/pr-check/remote-tests.js
- build-system/pr-check/utils.js
- build-system/tasks/report-test-status.js
- build-system/test-configs/config.js
The credentials have already been set as secure env vars on Travis (available during push builds).
Partial mitigation for #28343.
Related to #28790.
> 🏗 Run integration tests and only some unit tests on Sauce Labs, only during push builds

- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
Fixes: https://github.com/ampproject/amphtml/issues/21680
Issue: 
- When a component is used within amp-list, and amp-list re-renders its list contents, the previous elements do not have their `unlayoutCallback()` (amp lifecycle callback) called.
- In the issue linked above, `amp-bind` with a new `src` triggers the re-render
- `Amp-date-countdown` uses `setInterval()` to periodically update its date.  It then does `clearInterval` in it's `unlayoutCallback()` when it is no longer used
- Since the `unlayoutCallback()` is not called when `amp-date-countdown` is used within `amp-list`, after `amp-list` re-renders, the intervals is still set and continues to run it's callback
- In this situation, the callback tries to access the root node of the element (which is no longer the DOM's root) and …
> 🐛 [amp-list] Call scheduleUnlayout when amp-list container is updated

- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
If a story has less than 7 pages left when an ad is viewed we do not fetch another ad. There is an edge case where a user can still see 7 un-viewed pages after this by moving backwards through the story, or if there are 6 pages left in the story + the ad page itself. In the case we incorrectly try to place the same ad twice causing user to get stuck in a loop.
Closes #28840
cc/ @mszylkowski
> 🐛 Fix infinite loop in story ads

- src/service/viewer-impl.js
- test/unit/test-viewer.js
This will declare a doc to be visible if it isn't but gets a user action.
In Google Search this should never happen, because the doc isn't actually shown until the viewer handshake happened.
But other viewers do show documents right away, and we've seen cases where docs where presented to the user, but not interactive, because they never got the respective message.
Fixes #28227
> ✨ Add a defense-in-depth to the viewer in case communication fails

- extensions/amp-subscriptions/0.1/crypto-handler.js
- third_party/subscriptions-project/aes_gcm.js
- Refactor decryptAesGcm function to remove decoding from function and accept decoded IV
- Calls subtle.importkey once for all decryption sections instead of once per section.
> ♻️  Refactor AES-GCM decryption function.

- build-system/global-configs/prod-config.json
We usually see canary traffic too small to make a meaningful comparison, so we wanted to do a smaller portion of prod instead.
> Enable sticky-ad-padding-bottom on prod

- builtins/amp-img.js
- test/unit/test-amp-img.js
Blurry image placeholders are also `<img>` tags inserted as a direct child of the `<amp-img>` element. This will cause conflicts with the `<amp-img>`'s SSR rendering.
We want to ignore the blurry image placeholder when finding the real `<img>` child to reuse.
Re: https://github.com/ampproject/amphtml/pull/28758
> 🐛 Fix amp-img SSR with blurry-image placeholder

- README.md
This adds a link to AMP's OpenJS Collab Summit schedule & Slack channel.
> Adds a link to AMP's OpenJS Collab Summit schedule & Slack channel

- spec/amp-html-format.md
Seen at https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/custom_fonts/#1.-using-%3Clink%3E
> 📖  Added missing allow-listed host for font-awesome

- extensions/amp-autocomplete/0.1/amp-autocomplete.js
This PR makes the `max-entries` attribute available when delegating rendering to the server. This is so the server can truncate the results it sends to the `max-entries` size.
/cc @bill97819
> Pass `maxEntries` to SSR template

- extensions/amp-autocomplete/0.1/amp-autocomplete.js
Resolves #28926
Previously the `role=combobox` attribute was misplaced on the `amp-autocomplete > input` element whereas it should be on the `amp-autocomplete` element itself. This also supplies `role=combobox`-required associated `aria-*` attributes.
This change also makes `role=combobox` exclusive to child `<input>` tags, thereby excluding child `<textarea>` tags from this a11y treatment. This is because `role=combobox` is only allowed in the spec to apply to single-line input fields. Both of these are fully accessible usages of `amp-autocomplete` after the runtime applies appropriate fields:
```html
<amp-autocomplete filter="substring">
<label>
combobox 
<textarea autoexpand></textarea>
</label>
<script type="application/json">
{
"items": ["apple", "orange", "banana"]
}
</script> …
```
> ♿  amp-autocomplete: Comply with `role=combobox`

- build-system/test-configs/conformance-config.textproto
- build-system/test-configs/dep-check-config.js
- src/polyfills.js
- src/polyfills/array-includes.js
- src/polyfills/map-set.js
- src/polyfills/set-add.js
Allows `Map` and `Set`, since they're well supported even in IE11.
We had previously banned these because we couldn't prevent the automatic import of the entire iteration polyfill. That doesn't seem to be a problem anymore.
/cc @caroqliu
> Add Map and Set support

- extensions/amp-subscriptions/amp-subscriptions.md
This error breaks amp.dev's build as RegEx targeting code fences overlap.
> 📖  Fix syntax error in amp-subscriptions doc

- extensions/amp-analytics/0.1/amp-analytics.js
Noticed an error when I ran the analytics multi selector example page. 
str.replace is not a function.
This should fix the error.
> 🐛 Do not expand selector when it is an array

- build-system/tasks/karma.conf.js
- build-system/tasks/runtime-test/runtime-test-base.js
- package.json
- yarn.lock
Unbreak the build: https://travis-ci.org/github/ampproject/amphtml/jobs/699880037
There was a typo in https://github.com/ampproject/amphtml/pull/28951/commits/fe3bf7b7107a75f086f59144fb449e0d00bba17b#diff-0ee67c46629bb85f060f8bfe6bb6def4L175 -- I set `config.jsonReporter` instead of `config.jsonResultReporter`. The error was not detected before pull-requesting because `isTravisPushBuild()` was false during the pull request, meaning that the offending code didn't run.
I'll remove the `isTravisPushBuild()`check, see if fixing the typo fixes the issue, then add the check again.
> ⏪ Revert "🏗 Generate test reports on Travis build runs. (#28943)"

- examples/visual-tests/amp-story/amp-story-consent.html
- examples/visual-tests/amp-story/amp-story-consent.rtl.html
Fixes flaky Story consent visual diff tests. I assume it's because Percy fixed their amp-video within amp-story integration, and this video had no source.
Eg: https://percy.io/ampproject/amphtml/builds/5761486
> Fixes flaky Story consent visual diff tests.

- examples/amp-list-layout-container.amp.html
- src/custom-element.js
- src/layout.js
- test/unit/test-custom-element.js
#27911 allowed `amp-list` to have `layout=container` on the condition that it contains a size-defined `placeholder` element to display while items are being fetched and rendered. Default loaders do not currently apply to any `layout=container` AMP elements because, by virtue of not being size-defined, the element size could shift due to insertion of the loader.
A few important notes:
- amp-list has `position:relative` styling as a consequence of being `layout=container`
- The loading indicator is desirable to overlay across the whole amp-list, as this is consistent with other layout types of amp-list
- We still want to see content behind the loader because this may include the placeholder or initial contents
- `load-more` is not impacted here since `layout=container` and `load-more` are …
> Allow amp-list[layout=container] to opt into default loaders

- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.html
- extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out
- extensions/amp-autocomplete/amp-autocomplete.md
- extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
- validator/testdata/amp4email_feature_tests/amp-autocomplete.html
- validator/testdata/amp4email_feature_tests/amp-autocomplete.out
This change is to create a more consistent API surface between amp-autocomplete and amp-list, which after this change will both share `items` and `max-items` attributes along with expected sourcedata shapes. cc @bill97819
> amp-autocomplete: Replace "max-entries" with "max-items"

- extensions/amp-brightcove/0.1/amp-brightcove.js
- extensions/amp-brightcove/0.1/test/test-amp-brightcove.js
1. Component gets unlaid out.
2. `layoutCallback` is executed correctly, but it awaits a promise that is only resolved by `buildCallback`, which isn't called again.
Resolving this promise when a ready event is sent from the frame fixes this. 
Fixes #28745
> 🐛 Resolve amp-brightcove loading promise after every layout

- build-system/tasks/check-sourcemaps.js
This PR adds a help message to `gulp check-sourcemaps` to help handle intentional mapping changes, and makes cases like https://travis-ci.org/github/ampproject/amphtml/jobs/699511094#L478 (#28929) easier to address.
Related to #28929
> 🏗 Add a help message for intentional sourcemap changes

- validator/webui/.gcloudignore
- validator/webui/app.yaml
- validator/webui/main/serve.go
Update the webui validator code to use go1.13 and replace appengine with google cloud APIs.
> Update the webui validator code to use go1.13.

- spec/email/amp-email-css.md
In the last WG meeting, we agreed to add support for `-webkit-appearance`, `-webkit-tap-highlight-color` and `appearance`.
> Update email CSS spec

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
- tools/experiments/experiments-config.js
Remove the obsoleted Adsense format experiment to avoid the confusion and make the flow cleaner.
See manual testing & verification details [here](https://docs.google.com/document/d/1QXyfQTpHkDp2oxbHwEjYKX0IhKf_4GHng63CZ-4aECE/edit).
PTAL when you have time. Thanks.
@keithwrightbos, @glevitzky
> 🚮 Deleting code: Remove obsoleted Adsense format experiment.

- extensions/amp-analytics/amp-video-analytics.md
- extensions/amp-video/0.1/amp-video.js
- extensions/amp-video/0.1/test/test-amp-video.js
- src/service/video-manager-impl.js
- src/video-interface.js
For backward compat, because not all video players emit a play event, this change continues to emit the analytics play upon the video playing event if no video play event has been seen.
The existing integration tests should cover this as there isn't a change in behavior for simple cases (where playback isn't interrupted by network issues).
Fixes #23509
> 🐛 Switch analytics video play event to video play event.

- package.json
- yarn.lock
Partial for #27807.
Fixes #28994.
This version mainly fixes the case where the polyfill is loaded directly in a same-origin iframe.
> Upgrade IntersectionObserver polyfill to 0.11.0

- .github/ISSUE_TEMPLATE/release-tracking-issue.md
This instructs on-duty to add a link for new commits of a baby release compared to stable.
> 🏗  Update release issue template to add link for new commits

- src/inabox/inabox-resources.js
- src/service/resource.js
- test/unit/test-resource.js
I think there's a race condition where:
1. The element is schedule for layout
2. The page becomes hidden (swipe to next page, or change tabs)
3. The element's scheduled layout finally starts
I think the `state` is being reset to `NOT_LAID_OUT` or `READY_FOR_LAYOUT`, and somehow the `startLayout` method is being called. Either state is acceptable for `startLayout` for some reason. Really, we should only be accepting the resource when it's `LAYOUT_SCHEDULED`, which happens when the (async) layout flow is started. If anything happens between the start of that flow and the time the `startLayout` method is called, we're in a broken flow.
Re: https://github.com/ampproject/amphtml/issues/21116
> 🐛 Prevent layoutCallback if resource state changes after scheduling layout

- .travis.yml
Our Sauce Labs account has been shut down and `master` is red as a result. This PR merely stops running the "Remote Tests (Sauce Labs)" job on Travis. A full cleanup is out for review in #29038.
> 🏗 Stop running "Remote Tests (Sauce Labs)" on Travis

- package.json
- yarn.lock
WorkerDOM was transpiled using `loose` mode for AMP which specifically broke `classList` support.
> 🔥 Upgrade WorkerDOM to fix ES5 transpilation issue

- build-system/common/git.js
- build-system/compile/internal-version.js
Sometimes a commit that we verifies was cherry-picked from master is marked incorrectly as a new commit, which messes up with version numbers. This PR fixes this issue.
> 🏗 Verify whether a commit is a cherry-pick that was miscategorized to fix rare issue with version numbers

- src/service/resource.js
- src/service/resources-impl.js
- test/integration/test-visibility-states.js
Partial for #25428.
Fixes a bug I discovered when trying to enable `intersect-resources` in 100% prod. A test case in `test-visibility-state.js` caught this, yay coverage.
I also surveyed the other cases where resources are set to `NOT_LAID_OUT` state and this appears to be the only problematic one.
> intersect-resources: Fix elements relayout when doc inactive->active

- src/service/extensions-impl.js
- test/unit/test-extensions.js
Fixes #28582 and `b/158855528`.
> Allow reloadExtension() to soft fail

- build-system/compile/bundles.config.js
- build-system/tasks/css.js
- build-system/tasks/helpers.js
- build-system/tasks/presubmit-checks.js
- css/amp-story-entry-point.css
- src/amp-story-player/amp-story-component-manager.js
- src/amp-story-player/amp-story-entry-point/amp-story-entry-point-impl.js
- src/amp-story-player/amp-story-entry-point/amp-story-entry-point.js
- src/amp-story-player/amp-story-player-manager.js
- src/amp-story-player/amp-story-player.js
- test/unit/test-amp-story-player.js
Related to #26308
Adds `<amp-story-entry-point>` skeleton files and generates bundle. I thought it would be a good idea to leverage our existing "runtime" (`AmpStoryPlayerManager`) to handle the lifecycle of the entry points as well, but that's open for discussion.
> [amp-story-player] Entry point skeleton code and bundle

- build-system/compile/bundles.config.js
- examples/amp-story/interactives.html
- extensions/amp-story/1.0/amp-story-interactive-binary-poll.css
- extensions/amp-story/1.0/amp-story-interactive-binary-poll.js
- extensions/amp-story/1.0/amp-story.css
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/test/test-amp-story-interactive-binary-poll.js
To create regular poll, the current "binary polls" need to be renamed into its own component.
Since the concrete interactive classes are mostly layout implementations, the binary poll has a unique layout that shouldn't be in the same component as the regular poll.
Renamed all the interactive-poll into interactive-binary-poll.
> ♻️ Renamed binary polls

- extensions/amp-analytics/0.1/variables.js
- src/enums.js
- src/service/performance-impl.js
- src/utils/signals.js
- test/manual/amp-analytics/core-web-vitals.html
- test/unit/test-performance.js
- test/unit/utils/test-signals.js
Closes #29015
LargestContentfulPaintVisible:
Calculate the end_time by adding `this.timeOrigin_ + entry.renderTime`
Also fix the issue where delta 0 is treated as `undefined`. 
FirstInputDelay:
The first input should always happen after the document is visible, and the measuring start time is not `this.timeOrigin_`. Removed `FirstInputDelayVisible` since it doesn't tell anything.
> 🐛 Fix LargestContentfulPaintVisible and remove FirstInputDelayVisible

- extensions/amp-story/1.0/amp-story-page.js
Don't send `PAGE_PROGRESS` event from an inactive page. There's a code path where this could happen because of the polling mechanism in page-advancement, and it'd set the progress bar back to a previous segment.
> Don't send PAGE_PROGRESS event from an inactive page.

- build-system/global-configs/README.md
- contributing/running-server-side-experiment.md
The doc should help whoever wants to create an experiment.  The inabox part will be documented separately and internally.
> 📖 Add instructions to start a RTV Experiment

- build-system/global-configs/prod-config.json
- examples/accordion.amp.html
- extensions/amp-accordion/0.1/amp-accordion.css
- extensions/amp-accordion/0.1/amp-accordion.js
- extensions/amp-accordion/0.1/test/test-amp-accordion.js
This change modifies the existing `amp-accordion-display-locking` experiment with the `content-visibility` CSS property implementation. [[Demo](https://accordion-display-locking.firebaseapp.com/)] FYI @dvoytenko 
**Status update as of 2020-06-25**
This change is ready to go, pending the following:
- Bug fix to coordinate asynchronous section expansion with synchronous scrolling and manual testing upon resolution
- Experimental availability of `content: hidden-matchable` and the `beforematch` event on the Chrome side. 
cc @vmpstr
> [amp-accordion] Implement Display Locking via CSS property

- src/service/performance-impl.js
- test/unit/test-performance.js
**summary**
In an effort to pipe custom metrics through to the `gulp perfomance` task, this teeny PR makes it so that `performance-impl` emits a custom metric on every tick.
Initially I was planning on having this PR in the same one as the changes to the performance task, but it was difficult to compare `master` vs. `this branch` because master wasn't emitting events (and `gulp performance` only emits metrics that are in both).
In the next PR, I believe it should be possible to delete most of the custom metric collection code in `tasks/performance/measure-documents` 🎉 .
> performance-impl: emit custom events for each csi metric

- extensions/amp-story/1.0/amp-story-page.js
Restarts video event listeners when a new video becomes visible, which happens in many cases but mostly on the first page of a story.
Followup to #29032 
Fixes #28997
> Fix video loading indicator on first story page.

- src/service/resource.js
The error report isn't giving enough information for me to properly debug this. So, I'm now logging the current state, and attaching the associated element the element so the tagname is also reported.
> Log current state and element with error report during broken layout flow

- examples/amp-story/consent-geo.html
- examples/amp-story/consent.html
- examples/visual-tests/amp-story/amp-story-consent.html
- examples/visual-tests/amp-story/amp-story-consent.rtl.html
- extensions/amp-consent/amp-consent.md
- extensions/amp-story/1.0/amp-story-consent.js
- extensions/amp-story/1.0/test/test-amp-story-consent.js
Closes #27469
Take the `consentConfig_` and merge the legacy fields in the the top level fields: 
```
{
"consents": {
"ABC": {
"checkConsentHref": "http://localhost:8000/get-consent-v1",
"promptUI": "ui0"
}
}
}
```
to
```
{
"consentInstanceId": "ABC",
"checkConsentHref": "http://localhost:8000/get-consent-v1",
"promptUI": "ui0"
}
```
The merging is not expensive (`amp-story-consent.js`), but it is duplicated work, since amp-consent basically does the same config transformation to support new and legacy config formats.  
Updated the documentation in `amp-consent.md`, examples, and visual diff tests.
> Allow amp-story-consent to work with new amp-consent config

- build-system/externs/amp.extern.js
related thought for future prevention: could add a lint check against `/* type {`, since that would almost always be a mistake.
> Add asterisk to comments that were meant to be jsdocs in amp.extern

- build-system/tasks/release/index.js
This flag will enable running different flavors (`base`/`experimentN`) in parallel VMs
> 🏗 Add a `--flavor` flag to `gulp release`

- build-system/pr-check/cross-browser-tests.js
- test/integration/test-amp-recaptcha-input.js
- test/integration/test-amphtml-ads.js
- test/integration/test-user-error-reporting.js
This PR skips a few known failures on Firefox / Safari, that started failing when we enabled testing on GH actions. Follow up to #29012
> ❄️ Skip tests that are known to fail on GH Actions

- builtins/amp-img.js
- test/unit/test-amp-img.js
- validator/validator-main.protoascii
The `img` tag needs to have a `crossorigin` attribute in order to be used in a canvas context, cf https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
We're using an `amp-img` tag to build a new `amp-story-360` extension that will use this image in a canvas in https://github.com/ampproject/amphtml/pull/29023
> Propagate amp-img crossorigin attribute.

- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js
The "filter" attribute is banned in the email format because it describes the client-side filter method to follow. Prior to this change, the default value `none` (indicating no client-side filter) was set only for SSR-enabled documents. 
This change sets the default filter value as `none` whenever the attribute `filter` is unset, as it always is for valid email documents and never is for valid web documents.
> 🐛  amp-autocomplete: Set default filter to "none"

- package.json
- yarn.lock
Caches some input file JSON.stringify output to reduce the repetition in stringifying the same content.
> 🏗 Reduce JSON.stringify cost during Closure Compilation

- README.md
This removes the Collab Summit banner from README.md, and adds the Q3 survey link.
> Removes Collab Summit banner from README, adds Q3 survey link

- spec/amp-html-format.md
Fixes #28515.
The overflow scroll CSS property is allowed according to the amp validator, but disallowed according to the docs. This fixes that inconsistency (Please let me know if I'm wrong).
> 📖 Remove documentation for overflow

- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
- extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
- src/ampdoc-fie.js
We are running a few client side experiments where the `experimentInfoMap` is formatted incorrectly. Specifically our branch ids are arrays `['123']` when they should be strings `'123'`. This causes checks like https://github.com/ampproject/amphtml/blob/242e092ff440aa70334a4fdf9b06362c4a69ac56/extensions/amp-sticky-ad/1.0/amp-sticky-ad.js#L81-L82 to never be true 😬.
Unfortunately the logic that formats the url flattens these out using `Number(['123'])` resulting in `123` or we would have probably caught this earlier. https://github.com/ampproject/amphtml/blob/242e092ff440aa70334a4fdf9b06362c4a69ac56/ads/google/a4a/utils.js#L724 This means that it appears we are running client side diversions and see an equal split on rasta even though client side the logic is not actually diverted.
We …
> 🐛 Fix broken ads client side experiments

- src/web-worker/amp-worker.js
- test/unit/web-worker/test-amp-worker.js
Fixes #29101
Replaces `sourceMappingURL` with the absolute URL. Please see [issue description](https://github.com/ampproject/amphtml/issues/29101) for more details.
The unit tests pass, but I haven't been able to test the fix. Any help here will be appreciated!
> 🐛 Replace sourceMappingURL URL with absolute URL

- extensions/amp-story/1.0/amp-story.js
Pause/play Story level background audio on viewer/tab visibility change.
Story level background audio is not bound to the PAUSED state like other page media, as it's meant to play throughout the story without any interruption. But we forgot to play/pause it when the tab becomes inactive, or when the viewer marks the document as inactive.
Repro case: https://jumprope.com/g/amp/fajitas-on-the-double-burner-griddle/inxwgkXJ
> Pause/play Story level background audio on viewer/tab visibility change.

- src/context/index.js
- src/context/node.js
- src/context/scan.js
- src/context/scheduler.js
- src/utils/array.js
- test/unit/context/test-node-discover.js
The initial API for the context node API.
See the [design doc](https://docs.google.com/document/d/1oRj1X-1zg70y9pgOZjkJHTUOD7hgoiYQO45glYxro8s/edit#).
Next step: property propagation API.
In addition to the context node API, this PR also will try a slightly different source tree org.
> ContextNode: types and discovery phase

- extensions/amp-a4a/0.1/amp-a4a.js
User warning indicates only `position: fixed` is disallowed, but this line indicates `position: sticky` is also disallowed: https://github.com/ampproject/amphtml/blob/master/src/ad-helper.js#L44. While `sticky` is similar to `fixed`, it's a separate css value, and should be specified, given the phrasing of the warning. This might resolve some confusions.
> 📖 clarify isAdPositionAllowed

- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- src/service/action-impl.js
The `change` event was introduced in #26273 but did not bubble by default -- this PR changes the event init options to do just that.
Coincidentally, because this is a DOM `change` event on an `input` field, this also fires an AMP `change` event automatically from the action service: 
https://github.com/ampproject/amphtml/blob/984f380f9e6f9f2c9fed07956fc69c34bf15a8e2/src/service/action-impl.js#L358-L363
Therefore this PR also does the following:
- catches errors thrown when modifying `readonly` `detail` from programmatic events
- removes the explicit AMP `change` event fired in the amp-autocomplete (otherwise it will get fired twice)
> amp-autocomplete: Selection `change` event should bubble

- extensions/amp-story/1.0/amp-story-store-service.js
- extensions/amp-story/1.0/amp-story-system-layer.css
- extensions/amp-story/1.0/amp-story-system-layer.js
- extensions/amp-story/1.0/embed-mode.js
Story players are increasingly trying to use native sharing and audio controls. This PR introduces a new embed mode that hides the system layer icons, without all the side effects from `embedMode=1` (unmuted, no ads, ...).
This will eventually be used by several 1p players.
> New Story embed mode to hide system layer icons.

- build-system/test-configs/config.js
node_modules and cache for performance task were throwing lots of forbidden string errors. 
Closes #29206
> 🐛 Fix `gulp presubmit`

- build-system/common/git.js
The logic that determines the runtime version is [broken](https://github.com/ampproject/amphtml/pull/29115/checks?check_run_id=846716418#step:6:22) on Windows because it doesn't recognize Posix style environment variables.
This PR fixes versioning on Windows.
> 🏗🐛 Fix AMP version logic on Windows

- build-system/babel-plugins/babel-plugin-transform-function-declarations/index.js
- build-system/babel-plugins/babel-plugin-transform-function-declarations/test/fixtures/transform-assertions/argument-function/input.js
- build-system/babel-plugins/babel-plugin-transform-function-declarations/test/fixtures/transform-assertions/argument-function/output.js
This PR attempts to address the issue that was raised in #28698, which was occurring because the bailout conditions did not consider that the exemption regex must also be tested against property identifiers.
> 🐛 #28698: Fix for bug that was incorrectly transforming anonymous function to arrow function.

- src/service/resources-impl.js
Partial for #25428.
`rootMargin` was missing this: https://github.com/ampproject/amphtml/blob/c2fef917e518c739358d751090a6c2e16d78bc8b/src/service/resources-impl.js#L1388-L1393
Now, according to the comment, it sounds like that code was added back when `loadRect == viewportSize`. But it's live now and anything that deviates causes ads regressions. :)
> intersect-resources: Add missing 25% loadRect expansion to rootMargin

- build-system/global-configs/prod-config.json
Reverts ampproject/amphtml#29049.
Likely culprit of a ~1% query/impression regression, probably because forgot to include [this 25% loading rect expansion](https://github.com/ampproject/amphtml/blob/c2fef917e518c739358d751090a6c2e16d78bc8b/src/service/resources-impl.js#L1388-L1393) in the `IntersectionObserver.rootMargin`. 
Will cherry-pick to RC and try again later.
> Revert "Enable 'intersect-resources' in 100% of prod"

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/amp-story.js
This prevents screen readers from announcing the `src` value of an image if an `alt` is not specified.
This fix assumes that if publishers do not specify an `alt` their images are [decorative](https://www.w3.org/WAI/tutorials/images/decorative/).
context / fixes #28410
> 🐛 Prevent screen reader from announcing img src if alt tag is not specified.

- ads/google/a4a/experiment-utils.js
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
- extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
- src/ampdoc-fie.js
- src/experiments.js
- src/service/resources-impl.js
- test/unit/test-experiments.js
There are no strong reasons to use an object/map when defining experiments. This PR changes them to use arrays to prevent possible key name type mismatch problems. It won't by itself solve Closure's problem of not checking the element within object/array.
> Change experiment setting to arrays

- build-system/tasks/presubmit-checks.js
- build-system/test-configs/dep-check-config.js
- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-a4a/0.1/head-validation.js
- extensions/amp-a4a/0.1/test/test-head-validation.js
- extensions/amp-a4a/0.1/validate-head.js
> ✨A4A: introduce head validation

- examples/fake-ad.amp.html
- extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
- extensions/amp-ad-network-fake-impl/0.1/test/test-amp-ad-network-fake-impl.js
- extensions/amp-ad-network-fake-impl/amp-ad-network-fake-impl-internal.md
This allows the creative text to be inlined using the `srcdoc` attribute of an amp ad using the fake impl e.g. 
```html
<amp-ad width="300" height="400"
id="i-amphtml-demo-id-2"
type="fake"
a4a-conversion="true"
srcdoc="<p>Hello World</p>"
></amp-ad>
```
This is a request from partner ad networks, as it allows them to maintain a html template for things like previewing, and write the creative string into the template.
> ✨Introduce `srcdoc` feature to fake ad network

- extensions/amp-story/amp-story.md
Fixed Link anchors don't jump to the right heading Issue ampproject/amp.dev#4167 by replacing #live-story to #live-story-optional  in additional  tr tag 
📖 Documentation
🐛 Bug fix
> Fixed Link anchor don't jump to the right heading ampproject/amp.dev#4167

- examples/visual-tests/amp-story/basic.html
- examples/visual-tests/amp-story/basic.rtl.html
- examples/visual-tests/amp-story/embed-mode-1.html
- examples/visual-tests/amp-story/embed-mode-2.html
- examples/visual-tests/amp-story/info-dialog.rtl.html
- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/page-advancement.js
- extensions/amp-story/1.0/test/test-amp-story-page.js
- extensions/amp-story/1.0/test/test-full-bleed-animations.js
- extensions/amp-story/1.0/utils.js
- extensions/amp-video/0.1/amp-video.js
Note: we will very likely ask for this PR to be cherry-picked on beta/experimental.
1. Fixes a `distance` issue that introduces race conditions for single page stories by marking the active page as `distance 1`
2. Removes the video visibility updates listener. I don't think anyone uses it, and it's made the code very complicated for no good reason. Given all the video bugs we had I think making the video code easier, and removing all the different code paths we have is very desirable. It's also required for change 3.
3. When registering elements to the media pool we query audio and video elements. In some cases with no cache (super easy to repro with a carousel of 3p iframes), amp-audio and amp-video are not built yet so our querySelector doesn't register them. Now, we wait for …
> Fix and improve Story first page videos.

- build-system/tasks/clean.js
- Refactors `gulp clean` to use `async/await`
- Adds logging for files that were actually deleted
- Adds a `--dry_run` flag to indicate what will be deleted
- Adds a `--include_subpackages` flag to include inner `node_modules` directories that aren't easy to delete manually. (The root `node_modules` directory cannot be deleted because `gulp clean` uses a bunch of those directories.)
Fixes #28537
> 🏗 Refactor `gulp clean` and add logging

- ads/google/a4a/test/test-utils.js
- ads/google/a4a/utils.js
- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
amp-ad type=adsense or doubleclick, setup experiment that rounds position pixel parameters given expectation of integer values.
🐛 Bug fix
🧪 Experimental code
> AdSense/Doubleclick Ad - Round Positions Experiment

- build-system/tasks/clean.js
`expandDirectories` wasn't set prior to the refactor; which defaults to false. By setting it to true, maybe it's deleting more than it should. This explicitly sets it to false.
> 🐛  Fix gulp clean refactor bug

- extensions/amp-story/1.0/amp-story-interactive-binary-poll.css
They were using old variable names.
> 🐛 Use correct css variables on binary poll percent bars.

- .eslintrc.js
- extensions/amp-fit-text/1.0/fit-text.js
- extensions/amp-fit-text/1.0/fit-text.type.js
The goal: remove quotes when accessing props fields in components.
The proposal: use closure externs for props types. This is an alternative to a babel plugin that would allow unquoted prop access.
Key points:
1. This requires us to have a separate file like `fit-text.type.js` marked as `@externs` and containing types. This is not a very big burden however, and is similar to the `d.ts` files used elsewhere.
2. `...rest` ends up being an untyped object. But this is usually ok since it's only used to pass it through.
3. For type declarations, we can use either `@interface` or `@typedef`. The reason I went with `@typedef` here is because `@interface` doesn't allow us to access `props['aria-label']`.
4. I tried `@interface` as well. One benefit: it allows `@extends`. However, I think the need …
> POC: using externs for component props

- src/utils/dom-tranform-stream.js
- test/unit/utils/test-dom-transform-stream.js
There is a race where the response may finish (`onEnd` is called) before the target body is ready (`transferBody` has not been called). In this case we should wait for the target body before trying to transfer elements.
Related to #27189
> 🐛 Transforming stream race condition

- src/amp-story-player/amp-story-player-impl.js
Closes #28235
Once a story was finished and the next story is shown in the player, keyboard events of the *previous* story would continue to trigger. We should change the focus of the iframe to the current story once we navigate stories
> 🐛  [amp-story-player] Fixes keyboard navigation

- build-system/tasks/get-zindex/index.js
- build-system/tasks/get-zindex/test.js
- css/Z_INDEX.md
Changes how [`Z_INDEX.md`](https://github.com/ampproject/amphtml/blob/master/css/Z_INDEX.md) is generated.
1. Word values weren't treated especially, so you'd get `auto`/`initial` skipped across number values. Now they're sorted before numeric values.
2. Numeric values are now in descending length order, which I think makes more sense for `z-index` reference (assumption that you'd most likely want to know which layers are higher in the hierarchy.)
3. Explain how to generate from the file itself.
4. Format with `prettier` for lint compliance.
> 🏗 Sort z-index table differently, add instructions

- extensions/amp-base-carousel/1.0/arrow.js
- extensions/amp-base-carousel/1.0/base-carousel.css.js
- extensions/amp-base-carousel/1.0/base-carousel.js
- extensions/amp-base-carousel/1.0/scroller.js
- extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
- extensions/amp-base-carousel/1.0/storybook/Basic.js
- extensions/amp-base-carousel/1.0/test/test-base-carousel.js
- src/preact/index.js
- src/preact/utils.js
This PR makes the following changes:
I would recommend the following item to be split up into subsequent PRs by logical chunks.
- `mixed-length`, `visible-count`, `advance-count`, `auto-advance`, `auto-advance-count`, `auto-advance-interval`, `auto-advance-loops`, `snap`, `snap-align`, `snap-by`, `slide`, `horizontal`
> [Carousel]: Initial Preact Component

- css/amp-story-player-iframe.css
- examples/amp-story/player-with-button.html
- src/amp-story-player/amp-story-player-impl.js
- test/unit/test-amp-story-player.js
- Implement back and close button functionality, specify which by setting the button attribute of the amp-story-player tag to be "close" or "back" and the button, when clicked, will fire the appropriate event. (Visual diff tests are in a separate PR)
Partial for: #28416
/cc @Enriqe @newmuis
> 🖍✅✨  [amp-story-player] Implement back and close buttons

- extensions/amp-social-share/1.0/amp-social-share.js
- extensions/amp-social-share/1.0/social-share.js
Added additional check for userAgent in Preact component (execute during click)
Does a regex against window.navigator.userAgent which is the same way its checked in AMP
Did not remove check on AMP side (in case only AMP has access to userAgent)
AMP implementation: https://github.com/ampproject/amphtml/blob/master/src/service/platform-impl.js#L47
> ✨ [amp-social-share][bento] Duplicate target logic from amp component to bento

- ads/yahoofedads.js
Change the path of load script from a mock js file to a real js file rendered and maintained by a CICD pipeline for ads/yahoofedads type.
> ✨  yahoofedads: Change the mock js to real js lib.

- extensions/amp-video/0.1/amp-video.js
- extensions/amp-video/0.1/test/test-amp-video.js
If we don't do this, we try all cached sources first. None of them are likely to work if the first fails, so we want to sort uncached with cached.
Part of #29254
> Copy data-bitrate attribute to origin sources

- build-system/babel-config/helpers.js
Small change that will introduce `IS_SXG`, which will become a boolean value depending on input `argv.sxg`.
> 🏗 Introducing `IS_SXG` in Babel transformers.

- ads/yahoofedads.js
- ads/yahoofedads.md
Use correct path for Yahoo Federation AD library
The previous path is rendered by a config error.
> 🐛  Use correct path for Yahoo Federation AD library

- extensions/amp-animation/0.1/amp-animation.js
- extensions/amp-animation/0.1/test/test-amp-animation.js
- extensions/amp-animation/amp-animation.md
This is part of series to remove dependencies on FIE API to unblock the ampdoc-fie launch.
Partial for https://github.com/ampproject/amphtml/issues/22734.
> Reimplement amp-animation visibility trigger via IntersectionObserver

- .renovaterc.json
- package.json
- yarn.lock
The `renovate` package was updated in https://github.com/ampproject/amphtml/pull/29065, which required updating the config file as well. The actual bot itself, however, appears to be on an older version, and so it broke renovate bot because it can't process the updated config. This PR reverts the renovate package, reverts the config, and also adds some extra text to renovate PR bodies
> 🐛 Fix renovate bot

- build-system/externs/preact.extern.js
- extensions/amp-date-display/1.0/date-display.type.js
- extensions/amp-date-display/1.0/render-dom-tree.js
- extensions/amp-selector/1.0/amp-selector.js
- extensions/amp-selector/1.0/selector.js
- extensions/amp-selector/1.0/selector.type.js
- src/preact/index.js
The most consequential change is in the `build-system/externs/preact.extern.js`. I'm using `?` for the `FunctionalComponent`'s declaration. I couldn't find any other way that worked. I tried `Object` and `*` - they all failed in different places for reasons that are not clear to me.
> PropTypes: update Preact externs and use in more components

- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-a4a/0.1/friendly-frame-util.js
- extensions/amp-a4a/0.1/test/test-amp-a4a.js
- extensions/amp-animation/0.1/test/test-amp-animation.js
- src/friendly-iframe-embed.js
- test/unit/test-friendly-iframe-embed.js
> Remove ambiguous FIE.isVisible() API

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
- tools/experiments/experiments-config.js
Removes the experiment from https://github.com/ampproject/amphtml/issues/26473 now that the feature has been launched for months.
> 🚮  [amp-list] cleanup experiment 'amp-list-init-from-state'

- extensions/amp-social-share/1.0/amp-social-share.js
@dvoytenko 
I was wondering your opinion on this change.  The social-share component has an error check to see if a custom endpoint is provided when the `type` is not one of the pre-configured types.  I am thinking that we can remove this check from the amp side, since most of the error checking is done on the Preact side (this way don't do a duplicate check on both amp and preact).
Link to Preact side error check: https://github.com/ampproject/amphtml/blob/master/extensions/amp-social-share/1.0/social-share.js#L106
One side effect I noticed was that the Preact side will actually throw the error twice.  Once on the initial render, and a second time when the amp side passes asynchronous props and triggers a second render.  I think this is okay for now, but just wanted to bring it up.
> [amp-social-share][bento] Remove endpoint check from amp component

- extensions/amp-story/1.0/amp-story-page-attachment.js
- extensions/amp-story/1.0/amp-story-store-service.js
- extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js
- extensions/amp-story/1.0/test/test-amp-story-viewer-messaging-handler.js
@connielei noticed there's no way for us to subscribe for changes in the page attachment, since it's only stored in history. 
This PR adds attachmentPageId to the store so we can listen to the state changes at the player level.
Partial for #29219
> [amp-story] Add attachmentPageId to the store

- extensions/amp-consent/0.1/amp-consent.css
The `alertDialog` class is meant to style an 'invisible' element, that the screen reader will pick up always. 
Due to the the `alertDialog` class having `left: -10000px`, pages with `dir="rtl"` fail to show the amp-consent 3p iframe.
[Original reasoning](https://github.com/ampproject/amphtml/pull/26456#discussion_r375034203) for large negative `left` value was to essentially hide the element. Using `left: auto` will let the browser determine where the left edge is. This keeps the existing behavior and fixes the `dir=rtl` problem.
Another solution could be to create 2 alert dialog classes based upon direction:
```
amp-consent[dir="rtl"] .i-amphtml-consent-alertdialog{ right: -10000px; }
amp-consent[dir="ltr"] .i-amphtml-consent-alertdialog{ left: -10000px; }
```
> 🐛🌐 amp-consent: fix rtl support caused by alertDialog

- build-system/tasks/presubmit-checks.js
- build-system/test-configs/dep-check-config.js
- examples/analytics-visibility.amp.html
- src/friendly-iframe-embed-legacy.js
- src/friendly-iframe-embed.js
- src/service/extensions-impl.js
- test/unit/test-friendly-iframe-embed.js
1. The non ampdoc-fie code is moved to a separate `friendly-iframe-embed-legacy.js` to (1) easier to prohibit dependencies, and (2) ease of experiment cleanup.
2. The move from `friendly-iframe-embed.js` to `friendly-iframe-embed-legacy.js` is a trivial move.
> FIE: ensure that custom-element-registry is only used via extensions service

- build-system/tasks/dist.js
Remade PR due to CLA check, as well as no longer using the `.sxg.js` approach discussed earlier with Infra.
> 🏗 Addition of `--sxg` flag in `dist`.

- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-a4a/0.1/secure-frame.js
- extensions/amp-a4a/0.1/test/test-amp-a4a.js
- src/friendly-iframe-embed.js
I know it says 3000 lines, but it's really not so bad if you use the `?w=1` whitespace trick :)
I will start working on enabling the integration test tomorrow, but I didn't want to lose the momentum on this. Happy to wait to merge until we get integration test going. I haven't looked at integration yet, but 3p fallback is not yet fully supported so may have to wait for that. 
Part of #27189
> ✨Introduce rendering for unsigned creatives

- src/service/resource.js
- test/unit/test-resource.js
#29078 is happening way too frequently. Tracking it down, it's caused by elements that use `isRelayoutNeeded`. This means every time the element is measured (which happens every resource pass for these elements), they're setting their resource state to `READY_FOR_LAYOUT`. Normally, that's not an issue. But, we also happens to trigger this measurement directly before calling `startLayout`, which means every single element that uses `isRelayoutNeeded` would always fire this bug every single time.
This fixes the bug, by only setting to `READY_FOR_LAYOUT` if the element is in `LAYOUT_COMPLETE` state (or `FAILED`). And that prevents the bug because we'd no longer transition away from `LAYOUT_SCHEDULED` just before calling `startLayout`.
This re-enables the logging disabled in …
> Resources: Don't become ready for layout if already scheduled

- src/preact/base-element.js
Add 'passthroughNonEmpty' mode for handling children in bento.
Handling children with passthroughNonEmpty mode is the same as passthrough mode except that when there are no children elements, the returned prop['children'] will be null instead of the unnamed `<slot>`.  This allows the Preact environment to have conditional behavior depending on whether or not there are children.
Note: The framework will treat whitespace as a child text node.  
This will be considered to have a child text node with a return and some spaces.
This will not be considered to have any children.
Edit:  7/21/2020
Added logic to check if all children are whitespace only text nodes and if so, consider there to be no children and return `props['children'] = null`.
> ✨ [bento] Add passthroughNonEmpty mode for handling children in Bento

- extensions/amp-analytics/0.1/test/vendor-requests.json
- extensions/amp-analytics/0.1/vendors/blueconic.json
- Changed ${ampGeo} to ${ampGeo(ISOCountry) in the blueconic.json;
- Changed this for vendor-requests.json for the test as well;
- Transport added to the blueconic.json, we only support the image mechanisme;
> 🐛 Geo location was not set to the blueconic-analytics-vendor

- extensions/amp-a4a/0.1/secure-frame.js
- extensions/amp-a4a/0.1/test/test-amp-a4a.js
`connect-src *` for analytics to be able to send pings, and `allow popups` so that clicks are allowed to open landing pages in new window. Found in incoming PR to enable integration tests.
Part of #27189
> 🐛A4A: add more functionality to secure frame

- src/service/performance-impl.js
- src/utils/signals.js
- test/unit/test-performance.js
Per discussion this is expected and should not throw an error
> 🐛 Don't throw errors for unsupported metrics APIs in amp-analytics

- extensions/amp-a4a/0.1/head-validation.js
- extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
- test/integration/test-amphtml-ads.js
Introduces an element level attribute to opt into experiment branch for fake ad impl, and turns on a couple integration tests. 
Related to #27189
> 🧪Enable A4A integration test for no-signing exp

- build-system/compile/bundles.config.js
- examples/amp-story/interactive_results.html
- examples/amp-story/interactives.html
- extensions/amp-story/1.0/amp-story-interactive-binary-poll.css
- extensions/amp-story/1.0/amp-story-interactive-poll.css
- extensions/amp-story/1.0/amp-story-interactive-quiz.css
- extensions/amp-story/1.0/amp-story-interactive-results.css
- extensions/amp-story/1.0/amp-story-interactive-results.js
- extensions/amp-story/1.0/amp-story-interactive.css
- extensions/amp-story/1.0/amp-story-interactive.js
- extensions/amp-story/1.0/amp-story.css
- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/story-analytics.js
- extensions/amp-story/1.0/test/test-amp-story-interactive-results.js
This PR creates the results page for categorical results.
The amp-story-interactive-results will receive the state update when an interactive is completed, and calculate the category to fetch the attributes for it and populate the component.
The interactive-results-category component can be configured as follows:
```html
<amp-story-interactive-results
style="--interactive-accent-color: red" theme="dark"
prompt-text="You are a"
option-1-results-category="Dog" option-1-text="You are a fun intelligent creature" option-1-image="dog.png"
option-2-results-category="Cat" option-1-text="You are a calm humble creature" option-2-image="cat.png">
</amp-story-interactive-results>
```
Likewise, poll components that want to specify the category per-option can do it as follows:
```html …
```
> ✨Creating an interactive-results-category component

- extensions/amp-social-share/1.0/amp-social-share.js
- src/preact/base-element.js
Add mutation observer to bento's base-element (parent class for bento components).  Mutation observer should be used in combination with `passthroughNonEmpty` mode for handling children.  The mutation observer allows the Preact component to re-render when child nodes or characterData of the current element are updated as this may change whether or not the unnamed slot should be included in the Preact rendered nodes in amp mode.
> ✨  [bento] Add mutation observer to 'passthroughNonEmpty' children mode in base-element

- extensions/amp-a4a/0.1/callout-vendors.js
Add Hubvisor to the list of RTC callout-vendors in order to be able to add Hubvisor in the rtc-config attribute of amp-ad tags.
> ✨ Add Hubvisor to RTC callout-vendors for amp-ad

- extensions/amp-list/validator-amp-list.protoascii
> amp-list: email should support xssi-prefix

- extensions/amp-a4a/0.1/head-validation.js
- extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
- test/integration/test-amphtml-ads.js
Reverts ampproject/amphtml#29393
Breaking integration tests on Linux GH Actions.
> Revert "🧪Enable A4A integration test for no-signing exp"

- src/focus-history.js
When calling `tryFocus()` on the change of iframe in the player, an error would be thrown `Element expected:  null`. This checks if there's an `activeElement` before calling `this.pushFocus_` on it.
> [amp-story-player] Suppress expected element errors in iframe focus

- src/friendly-iframe-embed.js
- test/unit/test-friendly-iframe-embed.js
This was happening a lot in stories, but probably exists in all google ads cases. The iframe is originally set to have 0 height and width, then later resized using `setStyle` in adsense/doubleclick impl. This creates a race where the elements inside the iframe can be measured before the iframe has size, and because the runtime thinks they have no size, it never lays them out.
The fix attaches a listener to the frame to force remeasure when resized.
cc/ @ampproject/wg-ads
> 🐛 Fix case where ads iframe is measured before resize

- build-system/global-configs/prod-config.json
Reverts ampproject/amphtml#29354. 
~1% regression in ads queries still present -- appears to be primarily Android. Needs more investigation.
> Revert "Ramp "intersect-resources" to 100% (second try)"

- extensions/amp-bind/0.1/bind-impl.js
**summary**
- `state` has already been removed as a possible attribute. It already fails validation so it is safe to remove from bind
- The `is-layout-container` attribute is already in the validator test, so we can remove the comment.
> ♻️ bind-impl: remove outdated amp-list attr

- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
**Overview**
In a previous experiment cleanup [submit](https://github.com/ampproject/amphtml/pull/28957/files), the [code changes](https://screenshot.googleplex.com/fsSHfQm2RYq) introduced a bug during refactoring. This CL tried to undo the changes to the ad size logic but keep the outdated experiment deleted.
**Issues:**
Based on the current logic, if the AMP ad elements happen to have odd attribute values like width=0, the right values from getIntersectionElementLayoutBox could be overwritten.
An example from @nbeloglazov:  https://kban.me/article/9045?amp=1&display=b&amp_event-read-body 
The ad request will look like
`GET /pagead/ads?adsid=*&client=ca-pub-7593099783759275&format=0x320&w=0&h=320&iu=6222457915&adk=2108771703&output=html&bc=7&pv=1&wgl=1&asnt=0-2321678494345226860&dff=Gudea …
> 🐛 Bug fix: Undo the changes for adsense ad size overwrite logic.

- tools/experiments/experiments.html
This PR fixes the mismatched closing [`details` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) for the "Advanced" section in `experiments.html`.
Speculative fix for #29439.
> 🏗🐛 Fix mismatched HTML5 tag in `experiments.html`

- build-system/eslint-rules/dict-string-keys.js
- build-system/eslint-rules/prefer-destructuring.js
`...rest` properties when destructuring was causing an error to be thrown by the `prefer-destructuring` lint rule.
> 🏗 Fix prefer-destructuring to support rest properties

- .gitignore
- build-system/pr-check/local-tests.js
/cc @rcebulko @estherkim 
Closes https://github.com/ampproject/amp-github-apps/issues/922
EDIT: Normally, we can't tell whether or not these changes break the build (since they only run on push builds). However, manually enabling the flags for the PR build didn't break the build, as shown in the following link: https://travis-ci.org/github/ampproject/amphtml/builds/711576997
> 🏗 [test-case-reporting] Run gulp tasks & add flags when pushing

- extensions/amp-fit-text/1.0/amp-fit-text.js
- extensions/amp-fit-text/1.0/fit-text.js
- extensions/amp-timeago/1.0/amp-timeago.js
- extensions/amp-timeago/1.0/timeago.js
- extensions/amp-timeago/1.0/timeago.type.js
- src/preact/base-element.js
- src/preact/component/component.type.js
- src/preact/component/contain.js
- src/preact/component/index.js
After some research, it looks like most of our embedding scenarios can now be neatly expressed in terms of [CSS contain](https://developer.mozilla.org/en-US/docs/Web/CSS/contain) (which is not very surprising). The implementation is mostly factored out of `fit-text.js` and re-expressed in terms of `contain: ?`.
The main nuance in how `contain: strict` is implemented. It's done with via a wrapper with the following markup/styles:
```
<div (wrapper) style="contain: strict; ...{user styles}" class={user classes}>
<div (content) style="position: relative; width: 100%; height: 100%"></div>
</div>
```
This gives us a good compromise:
1. If a dev does not give the right sizing to component it's essentially has 0 size and very broken. It makes it clear that the sizing must be provided for correct …
> Bento: contain wrapper for most typical embedding scenarios

- examples/amp-list-protocol-adapters.html
- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
- extensions/amp-list/validator-amp-list.protoascii
- extensions/amp-script/0.1/amp-script.js
- extensions/amp-script/0.1/test/unit/test-amp-script.js
- src/services.js
- tools/experiments/experiments-config.js
**summary**
Implements Protocol adapters: #25719.
Introduces the concept of the `amp-script` src for amp-list components.
I picked this to be more in line with how initializing from `amp-state` works, but if anyone feels strongly I'd be 
ok with switching back to the more terse `fn:`.
Note that amp-bind is not required for this to work.
**future work**
- introduce the "lite" parameter for a domless amp-script.
- documentation
- allow all bind expressions to reference amp-script functions (as requested https://github.com/ampproject/amphtml/issues/25684)
cc @morsssss
> Implement protocol adapters

- extensions/amp-list/validator-amp-list.protoascii
only out of order attr in <amp-list> is `xssi-prefix`, added by me 8 months ago https://github.com/ampproject/amphtml/pull/25946.
> amp-list: alphabetize attributes

- extensions/amp-mega-menu/validator-amp-mega-menu.protoascii
- extensions/amp-nested-menu/validator-amp-nested-menu.protoascii
> 🐛  Allow `select` and `use` as descendants of mega-menu and nested-menu

- ads/_config.js
- ads/ads.extern.js
- ads/aduptech.js
- ads/aduptech.md
- examples/ads-legacy.amp.html
- examples/ads.amp.esm.html
- examples/ads.amp.html
- extensions/amp-ad/amp-ad.md
- test/unit/ads/test-aduptech.js
- validator/testdata/feature_tests/ads.html
- validator/testdata/feature_tests/ads.out
-  Add GDPR support for `aduptech` amp-ad tag
- Add new optional `gdpr` and `gdpr_consent` data-attributes
- Prefer consent string from `global.context.consentSharedData`
-  Add new optional `pageurl` data-attribute
- Using `global.context.sourceUrl` or `global.context.location.href` as fallback
-  Refactored/Optimized code
-  Added tests 
-  Fixed documentation
-  Fixed company naming in several files from "Ad Up" to  "AdUp"
> ✨ Add basic GDPR support for AdUp Technology amp-ad tag

- extensions/amp-accordion/0.1/amp-accordion.js
- extensions/amp-accordion/0.1/test/test-amp-accordion.js
- spec/amp-actions-and-events.md
- spec/amp-email-actions-and-events.md
- Allows amp-accordion `toggle`, `collapse`, and `expand` actions in AMP4Email.
- Adds amp-accordion to the AMP actions and events documentation.
Double checked [email components](https://amp.dev/documentation/components/?format=email) and accordion should be the only one that was not originally included. b/162131613
> 🐛  Allowlist amp-accordion actions in AMP4Email

- build-system/tasks/cherry-pick.js
gulp no longer supports synchronous tasks, so return a promise to avoid 
```
The following tasks did not complete: cherry-pick
Did you forget to signal async completion?
```
> 🏗  Return a promise in gulp cherry-pick

- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete.js
- extensions/amp-form/0.1/amp-form.js
- extensions/amp-mustache/0.1/amp-mustache.js
- extensions/amp-mustache/0.1/test/test-amp-mustache.js
- extensions/amp-mustache/0.2/amp-mustache.js
- extensions/amp-mustache/0.2/test/test-amp-mustache.js
- src/service/template-impl.js
- src/ssr-template-helper.js
- test/unit/test-template.js
`amp-mustache` `setHtml` wraps an HTML string of multiple elements with an outer div, silently turning
```
"<div>A</div><div>B</div><div>C</div>"
```
into
```html
<div>
<div>A</div>
<div>B</div>
<div>C</div>
</div>
```
This PR allows `setHtml` to return many elements as an array instead of adding an outer `<div>`, which is not well documented behavior. In the above example it will now return:
```html
[ <div>A</div>,  <div>B</div>,  <div>C</div> ]
```
Notes:
- The result of passing singular elements to `setHtml` (`<div>A</div>`) remains the same (`<div>A</div>`).
- Setting non-element HTML (`"abc"`) results in `<div>abc</div>` prior to and after this change.
- Setting an HTML string that consists of both elements and text nodes will wrap text nodes in `<div>` elements prior to the return. …
> 🐛 Respect template HTML for strings of many elements

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
Ramp experiment to 10% that corrects amp-ad type AdSense/Doubleclick position parameters to be valid integers, See #29248
🐛 Bug fix
> Ramp AdSense/Doubleclick correct position param experiment

- SUPPORT.md
📖  I figured we should include the Slack channel on [our Support page](https://amp.dev/support)!
If you think we shouldn't, please comment here....
> Include Slack channel in Support page

- extensions/amp-script/amp-script.md
* normalize headings
* fix broken raw tag
* mention toolbox csp lib instead of suggesting implementing on your own
* remove experimental flag
> 📖 Fix amp-script doc

- extensions/amp-accordion/amp-accordion.md
Inline examples were accidentally removed during structure update. Added them back in. Whoops!
> fixed code samples to inline executable

- src/service/resources-impl.js
- test/unit/test-resources.js
Partial for #25428. 
Reduce time-to-first-measure for ads (only) by manually measuring instead of waiting for the client rect from the `IntersectionObserver` callback.
Also allow measure requests from owned elements (probably an oversight).
> intersect-resources: Force immediate first measure for ads

- extensions/amp-live-list/0.1/live-list-manager.js
- extensions/amp-live-list/0.1/test/test-live-list-manager.js
`amp-live-list` should only restart the poller when the document becomes visible _**if**_ the component is enabled.
Fixes #29488
> 🐛 amp-live-list: Respect `disabled` when on visible

- extensions/amp-access-scroll/0.1/scroll-bar.js
- extensions/amp-access-scroll/0.1/scroll-impl.js
- extensions/amp-access-scroll/0.1/scroll-url.js
When user has Scroll app but is not signed in, and when ampdoc is not being served from proxy, redirect to app login flow.
- refactor constructing urls to buildUrl method in scroll-url.js
- refactor ScrollContentBlocker to separate logic for detecting vs handling
- add redirect case
cc @dvoytenko @kushal @dbow 
closes #20997
> ✨ Amp-access-scroll: Implement "activate" redirect when not on proxy

- extensions/amp-autocomplete/amp-autocomplete.md
- extensions/amp-list/amp-list.md
amp-mustache will unwrap multiple top-level elements with an outer `div`. This PR updates `amp-autocomplete` and `amp-list` to note this.
> 📖  Update component documentation with templating detail

- extensions/amp-story/1.0/utils.js
For each media-based advancement, there is a warning log: `[AMP-STORY] Invalid time string audio1`. This is probably very confusing for developers.
The root of the problem is we check first if the advancement is time-based, and then if it's media-based. So we are always checking for a valid time-based format, even though it's not what the intention is.
> Supress false warnings

- OWNERS
This change (I think) makes it so that any member of reviewers-amphtml can be an OWNER for .md file changes.
(I'm currently often the bottleneck for PRs that involve a change to an .md file when I probably don't need to be. :))
@rcebulko, will this do what I expect?
> Make any amphtml-reviewer an owner of md file changes

- build-system/externs/amp.extern.js
- extensions/amp-base-carousel/1.0/amp-base-carousel.js
- extensions/amp-base-carousel/1.0/scroller.js
- extensions/amp-base-carousel/1.0/storybook/Basic.js
- src/preact/base-element.js
- src/shadow-embed.js
- test/unit/test-shadow-embed.js
Partial for https://github.com/ampproject/wg-bento/issues/7
Design doc: https://docs.google.com/document/d/14gMbnzsTG3F1gxfbLck4kr7At62UYWa-DyrI3nDMJJw/edit#
This is the first and very preliminary step. The goal of this step is to place the shadow stylesheet into an adopted constructed stylesheet. This is a significantly faster option than `<style>` tag. However, there's no yet React-specific solution and this is why Storybook part is for now "hacked together".
In the follow-up steps we will construct a toolchain that will remove duplication and manual steps.
> Preliminary boilerplate and poc for shadow stylesheets

- extensions/amp-autocomplete/0.1/autocomplete-binding-single.js
- extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-bindings.js
As described in the [attribute documentation](https://amp.dev/documentation/components/amp-autocomplete/#suggest-first)
> amp-autocomplete: Silently disregard `suggest-first`

- build-system/tasks/extension-helpers.js
- extensions/amp-list/0.1/test-e2e/test-function-src.js
- extensions/amp-script/0.1/amp-script.css
- extensions/amp-script/0.1/amp-script.js
- extensions/amp-script/0.1/test/unit/test-amp-script.js
- package.json
- test/fixtures/e2e/amp-list/amp-list-function-src.html
- yarn.lock
**summary**
- Bumps worker-dom to 0.25.2 which has `nodom` build support.
- Introduce nodom attribute for `<amp-script>`, yielding a tiny worker bundle size and 0 size requirement.
- Creates basic e2e test for the happy path
**next step**
- Documentation!
> protocol adapters: e2e test, nodom binary, and bump worker-dom.

- ads/_config.js
codeBase upgrade removed adlib_seq from repository so prefetching it is no longer useful
> 🚀 springAds: removing revised and no longer used prefetch

- examples/amp-consent/cmp-vendors.amp.html
- extensions/amp-consent/0.1/cmps.js
- extensions/amp-consent/amp-consent.md
- extensions/amp-consent/cmps/iubenda.md
This PR introduces the integration of the iubenda Cookie Solution configuration in the amp-consent component.
https://www.iubenda.com
iubenda makes sites & apps legally compliant across multiple languages and legislations (including the GDPR) with lawyer-crafted, self-updating solutions and it's used by thousand of websites. Part of them have requested to support AMP pages.
Clarifications:
1. promptUI has not been specified in the configuration cause it's different for each customer. We ask our customers to host their promptUI on their own website, so this property must be set by customers.
2. There was no way to test the added configuration locally (cmps.js) since there are no instructions on how to build and use AMP locally, in addition the example page is using the AMP version in …
> ✨ Integration of iubenda in amp-consent

- extensions/amp-social-share/1.0/social-share.js
Social Share Tracking Issue: https://github.com/ampproject/amphtml/issues/28283
Currently throws an error if params are not defined when type is `email`.  Check if params exist first so no error is thrown.  (If params do not exist, return empty string in the line of code that is changed)
> ✨ [bento][amp-social-share] Do not throw error when no params are provided for email type

- extensions/amp-accordion/validator-amp-accordion.protoascii
- extensions/amp-fit-text/validator-amp-fit-text.protoascii
- extensions/amp-form/validator-amp-form.protoascii
- validator/testdata/amp4email_feature_tests/no_latest_extensions.out
In #24854 the validation for the AMP Email format script tags was separated from other AMP formats. This allowed for the removing support of version: latest and explicitly required a numerical version.
As a result of this separation from other HTML formats, it is not necessary to include requires_usage: EXEMPT or deprecated_allow_duplicates: true as part of the AMP Email format. Those were included to support the AMP format.
Fix #25249
> Remove unnecessary requires_usage and deprecated_allow_duplicates 

- extensions/amp-inputmask/0.1/amp-inputmask.js
- extensions/amp-inputmask/0.1/inputmask-custom-alias.js
Fixes https://github.com/ampproject/amphtml/issues/29100, https://github.com/ampproject/amphtml/issues/28062. The issue is due to trying to mask elements that may have the `mask` attribute but aren't `<input>`s.
From checking example documents with this error, it often occurs in SVGs
**for the reviewer**: are there any situation in which the input mask can be called on a non `<input>` element? If so then we'll need a different fix.
> 🐛  amp-inputmask: query is too zealous

- src/context/component-hooks.js
- src/context/component-install.js
- src/context/component-meta.js
- src/context/component.js
- src/context/index.js
- src/context/node.js
- src/context/scheduler.js
- test/unit/context/test-node-components.js
Follow up on #28665 and #29197.
Key points:
- `ContextNode` only now contains as set of components and two methods to add/remove. But it doesn't depend on `Component` class itself. The caller must provide it. This accomplishes: a more versatile types of components, and a smaller binary footprint of the `ContextNode` itself. Otherwise the component code inside `ContextNode` follows the `Values` .
- `Component` object is a placeholder for the component's dependencies and states. It subscribes to dependent values using `Values` APIs. It also has a persistent state for a component, that's used by hooks.
- Additionally `Component` trackers cleanup functions that can be registered by hooks.
- Component, component factories, and hooks are all designed to optimize for dead code elimination - that …
> ContextNode: components, subscribers, and hooks

- validator/webui/@polymer/webui-mainpage/webui-mainpage.html
- validator/webui/@polymer/webui-urlform/webui-urlform.html
- validator/webui/README.md
AMP format Actions is no longer currently being developed and can be removed from the Validator WebUI.
> Remove AMP Actions from Validator WebUI

- extensions/amp-analytics/0.1/default-config.js
- extensions/amp-analytics/0.1/test/test-variables.js
- extensions/amp-analytics/0.1/variables.js
- src/experiments.js
- test/unit/test-experiments.js
`EXPERIMENT_BRANCHES` || `${experimentBranches}`. Can be used to slice analytics reports by control/experiment.
> ✨Introduce new macro for experiment branches.

- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-a4a/0.1/head-validation.js
- extensions/amp-a4a/0.1/secure-frame.js
- extensions/amp-a4a/0.1/test/test-amp-a4a.js
- extensions/amp-a4a/0.1/test/test-head-validation.js
FIE installs a `<base>` element that I overlooked. Also copy over amp4ads boilerplate style.
#27189
> 🐛 No Signing: add missing elements to secure frame.

- extensions/amp-a4a/0.1/head-validation.js
- extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
- test/integration/test-amphtml-ads.js
This is actually the same PR as before that was breaking linux only GH actions. I have ran this PR on GH actions ~15 times and it passes every time. 🤷‍♂️ It's possible something has changed with linux config, or the a4a code, but not sure what would have this effect. 
Should we merge and try again? I can keep a close eye on it and revert (again) if it starts acting up.
> Enable integration tests for no-signing (2nd try)

- build-system/tasks/coverage-map/index.js
Based on feedback received in #29519, some small changes are made to the `coverage-map` task to expand on the usability for this gulp task. Updates include:
- Customize port number for AMP server
- Designate the input file (of all JS files via `*.js`) for `source-map-explorer`
- Skipping `dist` build process
>  🏗 Additional updates for gulp task `coverage-map`

- build-system/tasks/css.js
- build-system/tasks/extension-helpers.js
- build-system/tasks/helpers.js
- build-system/tasks/serve.js
- build-system/tasks/vendor-configs.js
This PR implements the solution outlined in https://github.com/ampproject/amphtml/issues/29214#issuecomment-668803993, and switches almost all the `watch` functionality in `build-system` from the third-party [`gulp-watch`](https://www.npmjs.com/package/gulp-watch) (last updated 2 years ago) to the built-in [`gulp.watch()`](https://gulpjs.com/docs/en/api/watch/) present in `gulp` v4.
The only remaining usage of the old `gulp-watch` is in [`lint.js`](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/lint.js), whose watcher reuses the main `gulp` stream, which can't be done with `gulp.watch()` as written. Migrating requires a refactor and is out of scope for this PR.
With this, we should hopefully see fewer of the missed file changes described in #29214.
Tested by …
> 🏗 Switch usage of `gulp-watch` to `gulp.watch`

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/test/test-amp-story-page.js
Wait until after `preloadAllMedia_()` for the actual `video` element to be available and start tracking media performance. #29233 made amp-video/audio.layoutCallback() resolve instantly, and media pool swap in/out are now synchronous, so register and preload operations are synchronous and thus very fast.
In addition to #29233, this fixes https://github.com/ampproject/amphtml/issues/29105
> Fix media performance tracking on first story page.

- build-system/compile/sources.js
- extensions/amp-base-carousel/1.0/base-carousel.js
- extensions/amp-base-carousel/1.0/scroller.js
- src/preact/compat.js
- src/preact/index.js
Use `forwardRef` to [dedup refs](https://github.com/ampproject/amphtml/pull/28704#discussion_r454696809) referenced between `Scroller` and `BaseCarousel`. Partial for #28284
> ♻️ Carousel: Use forwardRef

- build-system/tasks/default-task.js
Allow the `--https` flag when starting the dev server.
The `amp-story-360` component will use `DeviceOrientationEvent` which requires https. [WIP PR #29626](https://github.com/ampproject/amphtml/pull/29626).
Adding this flag will allow developers to work on this feature locally.
Current error when running with the flags:
> ✨ Add https to default task flags.

- build-system/compile/compile.js
Not all iOS versions that support module build (esm) has Intersection Observer. (11.1 to 12.1)
we need to install IntersectionObserver polyfill even in module build
as a follow up, we need to get rid of this closure and writefile transform to a babel transform to get rid of this hacky shadow polyfill removal code in compile (cc @rsimha)
> include intersection observer polyfill back into ESM

- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
Fixes a regression in #25964 which causes `amp-list[layout=container]` to have zero height during render (with SSR). 
This is caused by `firstLayoutCompleted() -> togglePlaceholder(false)` before render of real children finishes, which causes the `layout=container` amp-list to lose its height (defined by its placeholder) have its `height` style locked to 0.
> amp-list: Fix layoutCallback promise chain in SSR path

- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-adsense-impl/0.1/responsive-state.js
- extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-adsense-impl/0.1/test/test-responsive-state.js
Separate the convertToContainerWidth flow from maybeUpgradeToResponsive method, and trigger the flow from one level higher. The changes should not impact business logic.
Verifications in local mode:
mobile full width: https://screenshot.googleplex.com/dAYL7va7t6T
desktop container width: https://screenshot.googleplex.com/Cjcraf6STzV
PTAL: @kristoferbaxter, @calebcordry
> ♻️ Refactoring: Separate the convertToContainerWidth flow from maybeUpgradeToResponsive method

- src/amp.js
- src/service/viewport/viewport-impl.js
@dvoytenko pointed out that these two modules would probably not be needed in SxG build, so these can be excluded from it. These two changes remove 1KB from `v0.js`.
> 🧪Removal of `pull-to-refresh` and `viewport-binding-ios-embed` for SxG build.

- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
Just avoids the `userAssert` in `isLayoutSupported`. The rest is renaming "initial content" to "diffable placeholder".
> amp-list: Allow layout=container and diffable together

- extensions/amp-animation/0.1/install-polyfill.js
Per comment from @dvoytenko, FIE instances are created and destroyed often. Using a `WeakMap` instead of a `Map` allows for the VM to clean up these instances instead of retaining them for the sake of the polyfill map.
> ♻️ Switch Lazy Loading Animation Polyfill to WeakMap

- src/context/values.js
- test/unit/context/test-node-values.js
A recursive value with dependencies cannot simply use the parent value when no input is specified. It has to take into the account the dependencies as well.
For instance, a `CanPlay` prop can be defined as `CanPlay = CanRender && CanPlay.input && CanPlay.parent`. If `CanRender == false`, then the resulting `CanPlay` would also be `false` regardless of whether there's an input set for `CanPlay` itself.
> ContextNode: fix recursive computations with dependencies

- .eslintrc.js
- build-system/eslint-rules/no-static-this.js
- testing/test-helper.js
Closure Compiler doesn't support static this. It doesn't explode either, it just behaves strangely at runtime.
This lint rule should help up catch it early.
Most of the credit goes to Justin for writing the meat of the rule.
cc @kristoferbaxter 
Blocked by https://github.com/ampproject/amphtml/pull/29695
> new lint rule: no static this

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.116
Version: SwG Release 0.1.22.115
Previous release: 0.1.22.113
Update dependency @babel/core to v7.11.1 (#1202)
Update dependency mocha to v8.1.1 (#1201)
Create a hashing utility (#1200)
Create getCanonicalUrl Helper (#1198)
Update dependency browserify to v16.5.2 (#1199)
Expose event manager to publishers (#1181)
Update dependency eslint to v7.6.0 (#1194)
Add java 8 config flag to our build (#1192)
Bump elliptic from 6.5.0 to 6.5.3 (#1191)
Update babel monorepo to v7.11.0 (#1190)
Update dependency autoprefixer to v9.8.6 (#1188)
Update dependency mocha to v8.1.0 (#1189)
Update dependency karma to v5.1.1 (#1187)
Update dependency karma-coverage to v2.0.3 (#1185)
Update dependency chromedriver to v84.0.1 (#1184)
> 🏗 SwG Release 0.1.22.116, Aug 8, 2020

- extensions/amp-analytics/0.1/requests.js
- extensions/amp-analytics/0.1/test/test-requests.js
closes #29580
`extraUrlParams` can be an object with variables that need to be expanded. 
```
"extraUrlParams": {
"body": {
"data": {
"product": "${product}",
}
}
}
```
Currently, we send a shallow copy of `extraUrlParams` to `requests#expandExtraUrlParams()` which expands the variables and modifies `extraUrlParams`'s nested objects for subsequent requests, instead of expanding them per each request.
> 🐛 Use deep copy of extraUrlParams for sending requests

- build-system/global-configs/canary-config.json
Client side diverted experiment so this should affect 0.25% of traffic.
> 🧪Enable no-signing exp in experimental.

- src/utils/intersection-observer-polyfill.js
The `target` property points to a DOM element, which is not structured clonable (a requirement for `postMessage`). We used to `delete entry.target`, to get around this.
But when using native `IntersectionObserver`, the `IntersectionObserverEntry`s has no own properties. Instead, the properties are getters that exist on the prototype. `delete` doesn't work for prototype-inherited properties, so this workaround stopped working. Now, we'll just create a new object with the properties we care about, which is honestly cleaner (you shouldn't mutate objects you don't own).
Fixes https://github.com/ampproject/amphtml/issues/29747
> 🐛 Clone IntersectionObserverEntry for cross-origin postMessages

- build-system/compile/post-closure-babel.js
A followup to https://github.com/ampproject/amphtml/pull/29705.
Now that we're using async/await for Terser, we should propagate errors via the `next` callback.
There are no tests for this or other build-system code, so I added errors and manually verified.
> 🏗 Catch Minify Errors

- extensions/amp-subscriptions/0.1/amp-subscriptions.js
- extensions/amp-subscriptions/0.1/local-subscription-platform-base.js
- extensions/amp-subscriptions/0.1/subscription-platform.js
- extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
Removes special case of only pinging back local platform.  Sends pingback in platform preferred format to each platform that requests it.
Tides up some type issues
Make test of waiting for viewer more robust.
> ✨ extend support for pingback on to platforms.

- build-system/tasks/cherry-pick.js
This is to avoid an out-of-sync local when pushing a cherry pick branch to remote:
```
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
> 🏗  Always pull latest in gulp cherry-pick

- extensions/amp-auto-ads/0.1/firstimpression.io-network-config.js
By the results of discussion in PR #29712 with @calebcordry , in network config of `amp-auto-ads`, reverted to using `window.location` directly, rather then `ampdoc_.win.location`, because after minifying the `ampdoc_` variable name is not consistent across different JS files.
> 🐛 FirstImpression.io integration: reverted to using window.location

- extensions/amp-story/1.0/amp-story.css
context, fixes #29802
Button highlights when using TalkBack or VoiceOver.
[Demo](https://stamp-a11y.web.app/examples/amp-story/ampconf.html)
> 🐛 Hide border if user is not using keyboard input.

- extensions/amp-story/1.0/amp-story.css
Follow up to #29803
Prevents the button from intercepting pointer events.
Button is still clickable with TalkBack.
> 🐛 Talkback button, no pointer events

- extensions/amp-ad-network-fake-impl/0.1/amp-ad-network-fake-impl.js
- extensions/amp-ad-network-fake-impl/0.1/test/test-amp-ad-network-fake-impl.js
Not all chars were getting correctly encoded eg `#`. Switched to `encodeURIComponent`.
> 🐛 Fix srcdoc in fake ad

- extensions/amp-story-interactive/1.0/amp-story-interactive.css
- extensions/amp-story/1.0/amp-story.css
Closes #29792 
On local tests:
- Clicking on the prompt or anywhere not in the options takes you to the next page
- Clicking on the options on pre-select, does not change the page but selects the option
- Clicking on the options on post-select takes you to the next page
Also: width cannot be currently overriden by the creators, but it should. Removed !important from width so that they can specify `width:320px`. Currently they can set a max width if they enclose it in a div and set the width of that div, but it's not desired if they can just set it with a CSS attribute
> ✨Added pointer events caching only on selectable items

- extensions/amp-ad/0.1/test/validator-amp-ad.html
- extensions/amp-ad/0.1/test/validator-amp-ad.out
- extensions/amp-ad/validator-amp-ad.protoascii
We plan to use this attribute to opt in to rich sticky ads (e.g Kargo sidekick) in amp-ad tag.
> ✨ Add sticky to allowable amp-ad attributes

- extensions/amp-list/amp-list.md
- extensions/amp-script/amp-script.md
Followup to https://github.com/ampproject/amphtml/pull/29541
I plan on holding off on merging this until the experiment is turned on.
> 📖  protocol adapters: adds documentation

- src/service/navigation.js
- src/service/url-impl.js
- src/url.js
- test/unit/test-navigation.js
Fixes #26248 and patches #22376.
- `getSourceUrl('/path/to/page.html')` causes a userAssert on cache since `*.cdn.ampproject.org/path/` is not a valid CDN prefix
> Fix AMP.navigateTo with relative URLs on cache

- ads/google/a4a/test/test-utils.js
- ads/google/a4a/utils.js
As agreed in cr/325220403
The the response now also support `btrUrl` as an optional array.
The begin to render config looks like
```
{
on: ini-load,
selector: amp-ad,
selectionMethod: closest
}
```
> Add begin to render requests to a4a ad

- extensions/amp-social-share/1.0/social-share-config.js
- extensions/amp-social-share/1.0/social-share.js
- extensions/amp-social-share/1.0/social-share.type.js
Follow Up to: https://github.com/ampproject/amphtml/pull/29658
Bento Tracking Issue: https://github.com/ampproject/amphtml/issues/28283
Changes include:
1. Remove Config typedef from externs file - Externs should serve as API for the entire module.  Config type should be used internally and does not need to be exposed.  Also, externs items are not minified, but since config is essentially private, it should be minified.
2. Move {...rest} to be first item within Components returned JSX - Otherwise, user could accidentally overwrite existing attributes on the div.  We do not want to let them accidentally do this.
> ♻️ [bento][amp-social-share] Minor cleanup of typedefs PR

- test/unit/test-amp-story-player.js
We were using a `Sinon` `mock`, when we should be actually be using a `spy`. Otherwise, we would have to mark _all_ the calls to the mock as expected when calling the mock from a test. This would pollute them with many `mock.expects(...)`.
> ✅♻️   [amp-story-player] Clean up tests

- 3p/ampcontext.js
- extensions/amp-ad/0.1/amp-ad-3p-impl.js
- extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
- src/3p-frame-messaging.js
This PR allows amp-ad to render a sticky ad if it has a `sticky` attribute in it. It also adds an interface in the ampcontext API so that the ad can tell the runtime whenever it is ready to be interacted.
> ✨ Allow sticky ads be shown on amp-ad

- src/context/component-hooks.js
- src/context/component-install.js
- src/context/component.js
- src/context/index.js
- src/context/node.js
- src/types.js
- test/unit/context/test-node-components.js
- test/unit/test-types.js
This pull request completes the APIs described in the [design doc](https://docs.google.com/document/d/1mEk_myi5-Q51RffLuoWU5o8UcacEBaKhiwfm32ghIdo/edit#bookmark=id.c4uh12mrsjv3).
These APIs extend `setProp`, `setComponent`, and `subscribe` APIs and intended to be used as hooks inside a component. These actually main APIs and their primary goal is to implement auto-cleanup when any related node disappears from the DOM. This avoids excessive and error-prone cleanup code.
> ContextNode: child props and components with auto-cleanup

- build-system/compile/closure-compile.js
- package.json
- yarn.lock
Now that our closure source repo has moved organizations, it's time to switch the reference in our compilation code.
> 🏗 Switch closure dependency source from `@kristoferbaxter` to `@ampproject`

- .github/workflows/continuous-integration-workflow.yml
- Consolidate duplication in GH actions workflow file
- Add yarn caching to speed up installs
**Reference:** https://github.com/actions/cache/blob/releases/v2/examples.md#node---yarn
**Before (average case):**
**Before (worst case):**
**After (TBD):**
> 🏗 Consolidate GH actions workflow file and add `yarn` caching

- ads/advertserve.js
- ads/advertserve.md
Added support and documentation for custom fields to the AdvertServe AMP ad tag that allow users to pass anywhere from 1-10 category/keyword fields for ad targeting purposes.
> AdvertServe Custom Field Support

- build-system/babel-plugins/babel-plugin-transform-dev-methods/index.js
We use `.error()` and `.expectedError()` to send error reports to amp-error-reporting server.
Undoes part of https://github.com/ampproject/amphtml/pull/29913.
> Keep error and expectedError in ESM builds

- extensions/amp-script/0.1/amp-script.js
- extensions/amp-script/0.1/test/unit/test-amp-script.js
- src/service/resources-impl.js
Fixes https://github.com/ampproject/amphtml/issues/29614
For the reviewer: adding a `.catch` to `WorkerDOM.upgrade` was hacky. If an error occurs within the worker-dom code, we'd probably want an uncaught exception to throw, whereas if it is caused by the code to retrieve authorScript, then we don't want that.
The cleanest way of having the same effect would be to have the entire upgrade path within a `.then()` callback of the scripts, although that would then delay the start of the upgrade until after they've resolved (not that I think worker-dom actually does much work before they do, but it is what caused my hesitation).
> amp-script: improved error messages

- build-system/tasks/visual-diff/helpers.js
- build-system/tasks/visual-diff/index.js
AMP has modified the way it displays loading indicators a while back, this PR updates the visual diff task to catch up and, hopefully, deal with any recent flakiness
> 🏗 Update the class names that visual-diff uses to verify loading is complete

- .renovaterc.json
Babel updates often require accompanying code changes. This PR splits them off into a dedicated PR so that other updates are not blocked.
> 🏗 Split off renovate updates for babel packages into a separate PR

- extensions/amp-story-360/0.1/amp-story-360.js
This is a follow up to #29882
Use `naturalWidth` and `naturalHeight` from `imgEl` instead of `width` and `height`.
Otherwise if the user specifies smaller image dimensions the code will fail.
Such as in this example:
`imgEl.width` would equal `10` and the code will fail.
We need to use `imgEl.naturalWidth` to get the source image dimension which is `7168`
> 🐛 Get natural dimensions of image in checkImageReSize_

- extensions/amp-analytics/0.1/amp-analytics.js
Follow up to #29779 
This is to fix the beginToRender request which waits for the `ini-load` signal. 
Tested with the fake ad type. We can make the fake ad  support the `extractAmpAnalyticsConfig()` feature that insert analytics component based on `x-analytics` is response header or a meta tag.
> Allow ini-load & render-start trigger in sandboxed analytics component

- build-system/babel-plugins/babel-plugin-transform-dev-methods/index.js
- build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/imported-both-usage/input.js
- build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/imported-both-usage/output.mjs
- build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/imported-user-usage/input.js
- build-system/babel-plugins/babel-plugin-transform-dev-methods/test/fixtures/transform-assertions/imported-user-usage/output.mjs
- build-system/tasks/babel-plugin-tests.js
Fixes https://github.com/ampproject/amphtml/issues/29988, as well as updates the tests for `babel-plugin-transform-dev-methods` which recently became out of sync.
Surprisingly, the `Promise` returned from `jest.runCLI` doesn't return a rejected promise in the case of test failure, we need to check for `results.success`. After this PR the task should fail ci as appropriate:
> gulp babel-plugin-test failure should fail ci

- extensions/amp-script/0.1/test/validator-amp-script.html
- extensions/amp-script/0.1/test/validator-amp-script.out
- extensions/amp-script/validator-amp-script.protoascii
Fixes https://github.com/ampproject/amphtml/issues/30017.
While here I also alphabetized the attributes.
> amp-script: "nodom" attribute should pass validation

- extensions/amp-script/validator-amp-script.protoascii
`nodom` and `nodom=nodom` are valid, any other value is invalid
> Attribute nodom contains no value

- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/sra-utils.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
The existing SRA logic was creating a pseudo response that would cause the no-signing exp to fail due to the non-existence of response.body & response.text
This PR makes these pseudo responses actual responses in the no signing exp. Response constructor is polyfilled by `fetch.js` for unsupported browsers.
Part of #27189
> 🐛Fix SRA in no signing exp

- test/_init_tests.js
- test/integration/test-amp-ad-3p.js
Implements the plan in https://github.com/ampproject/amphtml/issues/29930#issuecomment-682988055 by cleaning up iframes between tests on Safari. With this, tests that rely on absolute position should no longer fail due to the presence of multiple iframes.
I can see that `test/integration/test-amp-ad-3p.js` passes locally when run with other tests. Will confirm with a full run on GH actions.
Fixes #29930
> 🏗🐛 Clean up iframes between tests on Safari

- extensions/amp-base-carousel/1.0/amp-base-carousel.js
- extensions/amp-base-carousel/1.0/base-carousel.js
- extensions/amp-base-carousel/1.0/base-carousel.type.js
- extensions/amp-base-carousel/1.0/scroller.js
- extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
- extensions/amp-inline-gallery/1.0/inline-gallery.type.js
- src/preact/base-element.js
- src/preact/compat.js
- src/preact/index.js
This pull request uses Preact's `useImperativeHandle` to export the component's imperative API to the AMP layer. The most common use for this is support of AMP actions. This pull request implements `next`, `prev`, and `goToSlide` actions. The imperative API itself is declared and described in the `type.js` file.
> Export imperative API from carousel

- validator/js/engine/validator_test.js
- validator/validator-main.protoascii
- cl/329019993 Revision bump for #30036
- cl/329000722 Update AMP4Email format document size limit to 200k.
- cl/328995853 Revision bump for #30003
- cl/328993182 Revision bump for #30026
> Validator rollup 2020-08-31

- extensions/amp-base-carousel/1.0/base-carousel.js
The broken  dependency is `clamp -> getMode -> IS_ESM`.
> Remove use of clamp due to dependency on getMode

- extensions/amp-story/1.0/amp-story.js
- src/amp-story-player/amp-story-player-impl.js
- test/unit/test-amp-story-player.js
Fixes #29320
Loading 2 iframes initially involved a lot of changes (because of how other methods like `show()` expect there to be 3 iframes) so I'm sending those in a follow up. (Tracked  #29706)
As seen on the first table, having a story specific event that delays the subsequent stories from being loaded makes the initial load time of the current story shorter.
|          | current | `storyLoaded`      | `documentLoaded`  |
|----------|---------|------------------|-----------------|
| normal   | 1.88s   | 1.37s (Δ -27.13%) | 1.74s (Δ -7.45%) |
| fast 3G  | ~72s    | ~30s (Δ -58.33%)  | ~34s (Δ -52.78%) |
There is a downside though, loading subsequent stories take longer to finish pre-rendering. 
|          | current | new             |
|----------|---------|-----------------|
| normal …
> 🚀  [amp-story-player] Wait for first story to load before loading next ones

- src/amp-story-player/amp-story-player-impl.js
- test/unit/test-amp-story-player.js
Part of #29443 originally noted by @proyectoramirez in https://github.com/ampproject/amphtml/pull/29443#discussion_r464706111
Fixes bug where fragment params were being appended before the query param.
> 🐛 [amp-story-player] Fix fragment param issue

- build-system/babel-plugins/babel-plugin-transform-jss/index.js
- build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-jss-var/output.mjs
- build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-literal/input.js
- build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-literal/output.mjs
- build-system/babel-plugins/babel-plugin-transform-jss/test/index.js
- extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
**summary**
- Introduces a new key for classname output: key-filehash.  This means you'll get a stable key independent of order in which files are transformed, but there is a very small possibility of collisions.
- Introduces a check to fail-fast in case there is a classname collision between files.
>  jss: make classname deterministic

- build-system/tasks/browse.js
- gulpfile.js
`gulp browse --url <URL>` uses the platforms default browser (or, in the case of Windows, Chrome) to open a specified page. To be used for upcoming changes, including automatically opening a coverage UI after running e2e tests with the `--coverage` and `--browse` flags. Can also add `gulp serve --browse` for the same effect.
> 🏗Add `gulp browse` task to open browser to URL

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
- The demo now validates Google Article Access (GAA) URL params (#1247)
- Updates a test that was using the deprecated `getEntitlements` string param (#1245)
- Entitlements Manager: Improves test coverage (#1244)
- Update dependency karma to v5.2.1 (#1243)
- Update dependency eslint to v7.8.1 (#1242)
- Fixes Travis config (#1241)
- Improves comments (#1239)
- Improves test coverage of EntitlementsManager (#1236)
- Update dependency rollup to v2.26.9 (#1237)
- Metering demo: "gaa_at" URL param triggers "metering" flow (#1234)
- Update dependency eslint to v7.8.0 (#1235)
- Update babel monorepo to v7.11.5 (#1233)
- Update dependency rollup to v2.26.8 (#1231)
- Update dependency karma to v5.2.0 (#1232)
- Remove Pay Client Lazyload experiment (#1230)
- Update dependency mocha to v8.1.3 …
> SwG Release 0.1.22.120

- extensions/amp-analytics/0.1/test/test-amp-analytics.js
- extensions/amp-analytics/0.1/test/test-visibility-manager.js
- extensions/amp-analytics/0.1/visibility-manager.js
> 🐛 Report zero visibility for zero size element

- extensions/amp-consent/0.1/amp-consent.js
Closes #29655 by catching errors that occur while trying to parse the JSON response.
> Add error message for unparseable checkConsentHref response

- extensions/amp-ad/0.1/amp-ad-ui.js
For sticky ad type only, reject the requestResize if the requirement is not met.
> ✨  Restrict amp-ad sticky ad size to 20% viewport size and 50% height

- build-system/babel-plugins/babel-plugin-transform-jss/create-hash.js
- build-system/babel-plugins/babel-plugin-transform-jss/index.js
- build-system/babel-plugins/babel-plugin-transform-jss/test/index.js
**summary**
The recently introduced jss transform bans duplicate classnames from appearing.
As written, it breaks `watch` mode since when the same file is compiled twice it of course generates the same classnames.
This PR fixes it by allowing for dupes within the same file.
> 🐛 jss transform: support watch mode by allowing dupes if same file

- examples/amp-story/interactive_polls.html
- extensions/amp-story-interactive/0.1/amp-story-interactive-poll.css
- extensions/amp-story-interactive/0.1/amp-story-interactive-poll.js
- extensions/amp-story-interactive/0.1/test/test-amp-story-interactive-poll.js
Polls can have two lines by decreasing the size of the options (changing the font-sizes). Changing the size is necessary if we want to allow 2 lines so that we can fit the text in the chip.
<table>
<tr>
<td>Original size w 2 lines</td>
<td>New size w 2 lines</td>
<td>Ellipsis with 3+ lines</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/22420856/92521283-fb5c6880-f1ea-11ea-98fb-ed0479fa80c6.png"></td>
<td><img src="https://user-images.githubusercontent.com/22420856/92521311-0616fd80-f1eb-11ea-89d3-8b63fb383cbb.png"></td>
<td><img src="https://user-images.githubusercontent.com/22420856/92521305-02837680-f1eb-11ea-9c87-4cb52d12b36e.png"></td>
</tr>
</table>
Closes #30120
> ✨ Interactive poll can have options with two lines

- build-system/global-configs/prod-config.json
Reverting the removal from #28196, to merge when ready.
> Enable `amp-accordion-display-locking` experiment on 1% traffic

- .vscode/settings.json
- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test-e2e/test-function-src.js
- extensions/amp-list/0.1/test/test-amp-list.js
- test/fixtures/e2e/amp-list/amp-list-function-load-more.html
**summary**
Fixes https://github.com/ampproject/amphtml/issues/30095
The load-more option was broken when attempting to use it with `amp-script` as a data source. This is because it has a separate fetch flow that didn't consider `amp-script:` or `amp-state:` URIs.
This PR combines the two fetch flows, as well as adds a new e2e test for this interaction. In a future PR we should add documentation for how these two features interact.
> amp-list: support amp-state and amp-script for load-more

- build-system/compile/sources.js
- build-system/tasks/extension-helpers.js
- extensions/amp-script/0.1/amp-script.js
- extensions/amp-script/0.1/test/unit/test-amp-script.js
- package.json
- yarn.lock
- remove the copying of "mjs" files into "max.js" files (turning modules into nomodules is a big no no)
- copy the "js" files to "mjs" files to fix the missing "mjs" files for when the module version of amp is loaded (this is OK for now as a temp fix)
- if /dist/amp-production exists in worker-dom then the new directory structure implemented has https://github.com/ampproject/worker-dom/pull/929 is merged and we should copy from the new directories
- make sure to copy source map files as well
- upgrade worker-dom version
- fix import paths to main.mjs
> copy worker-dom files from the new amp-production directory when it exists

- extensions/amp-base-carousel/0.1/amp-base-carousel.js
This is a fix for the amp-base-carousel that do not behave properly in hiding the next arrow when reaching the end of the slides.
In particular, the hiding code was not working when there are more than one slide visible in the page (visible-count attribute set greater than 1).
> 🐛 [amp-base-carousel] fix for next arrow not hidden properly when visible-count > 1

- extensions/amp-timeago/1.0/test/test-amp-timeago.js
Timeago tracking issue: https://github.com/ampproject/amphtml/issues/29246
Skipping flaky tests in amp-timeago.  Appears to be a timeout on this line:  https://github.com/ampproject/amphtml/blob/master/extensions/amp-timeago/1.0/test/test-amp-timeago.js#L43
Causes travis to timeout with the error shown in the screenshot below.
Does not reproduce when running locally unless using `--watch` mode and manually stepping through the test.
To do: research and unskip.  Tracked in: https://github.com/ampproject/amphtml/issues/29246
> ❄️  [bento][amp-time-ago] Skip flaky tests in amp-timeago for now

- extensions/amp-social-share/1.0/test/test-amp-social-share.js
- extensions/amp-social-share/1.0/test/test-social-share.js
Social Share Tracking Issue: https://github.com/ampproject/amphtml/issues/28283
Unit tests for Amp Social Share
1. Error checking is handled in the Preact side test as errors are primarily thrown here and errors are thrown synchronously in Preact (asynchronously in Amp, since we are waiting for asynchronous render).  Was not able to find an easy way to check for errors asynchronously from Amp side.
2. General use cases are handled on the Amp side test so we can test both Amp and Preact in a single test.
> ✅ [bento][amp-social-share] First draft test amp-social-share

- src/service/resource.js
**summary**
Fixes an issue with `intersect-resources` experiment where it can use an out-of-date rect. Specifically we were seeing a regression in `amp-ad` where a carousel 1.0 slides were not being laid out at all. This is due to a mismatch in `isDisplayed` between the premeasure rect and the more-recent measure within owners.
The sequence of events that causes this bug were:
1. io callback premeasure occurs with zero height/width (this is valid / can happen for various reasons)
2. explicit measure happens via the owners system, and a layout is scheduled
3. an attempt at layout begins but the task is skipped due to checking `isDisplayed` with the premeasuredRect - see below for the snippet that does the skipping.
4. io callback premeasure occurs again with positive width/height, but its …
> intersection-observer: don't use premeasure if there is a more recent measure

- extensions/amp-date-display/1.0/test/test-amp-date-display.js
- extensions/amp-date-display/1.0/test/test-date-display.js
- extensions/amp-social-share/1.0/test/test-social-share.js
- extensions/amp-timeago/1.0/test/test-amp-timeago.js
This pull request reverts #30181.
Preact schedules handler only once for a queue, when [`queue.length === 1`](https://github.com/preactjs/preact/blob/84a16f2108da9f23fbd017e703500fd2f7d31e02/hooks/src/index.js#L325). We had a situation where the fake test clock was used to schedule the update for `queue.length === 1`, but then it was discarded. All followup queue pushes were not scheduled because `queue.length > 1`. But the fake timer was never executed, so the queue was stuck - more items were added to it, but handler was never called. I was actually surprised by this a bit - I though `clock.uninstall` would run all pending timers, but apparently not.
Not yet clear how to defend from this in depth. Debugging this problem is extremely difficult - there's no way to determine a "hanged" …
> Unblock Preact tests that are executed against fake clock

- extensions/amp-delight-player/0.1/amp-delight-player.js
Since publishers that use the amp-delight-player rely on the correct handling of tcf2 consent strings in the video player it is necessary for the amp-delight-player element to retrieve consent data and send that data via post message to the underlying video player iframe.
> ✨Consent: Pass consent string and metadata to amp-delight-player

- ads/kargo.js
- Replaces `this` reference in loadScript call with local `window`
> 🐛 Fixing window reference for amp-ad type kargo

- ads/_ping_.js
- examples/ac-creative.js
- examples/ampcontext-creative-json.html
- examples/ampcontext-creative.html
- test/integration/test-amp-ad-3p.js
We have moved from onRequestSuccess to promise. These are the references needing to be changed.
> ♻️ Move tests and reference implementation to use promise on context.requestResize API

- build-system/global-configs/experiments-config.json
- build-system/tasks/e2e/amp-driver.js
- build-system/tasks/e2e/describes-e2e.js
- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-a4a/0.1/test/test-amp-a4a.js
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Move branch level No Signing experiment to ExperimentA slot to stop polluting canary logs.
link without whitespace in diff :) https://github.com/ampproject/amphtml/pull/30201/files?w=1
> Move no-signing to RTV exp

- ads/google/a4a/utils.js
- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-sticky-ad/1.0/amp-sticky-ad.css
- extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
- tools/experiments/experiments-config.js
The experiment has been running for a while. We have looked at the outcome when we fully launched it on experiments-config.
Other changes come from autoformatting the CSS.
> 🧪 Remove and launch sticky ad safety area css experiment

- extensions/amp-social-share/0.1/storybook/Basic.amp.js
- extensions/amp-social-share/1.0/storybook/Basic.amp.js
- extensions/amp-social-share/1.0/storybook/Basic.js
Update storybooks for amp-social-share
Updated storybook labels (i.e. amp-social-share-0_1)
1. amp-social-share-0_1 (pre-bento)
- Add `undefined` type
- Add `width` and `height` knobs
2. amp-social-share-1_0
- Add `undefined` type
- Add `width` and `height` knobs
- Add `layout` knob, user can input `responsive`, removed `responsive` storybook example
3. SocialShare
- Add knobs for `foreground` and `background` colors
- Add knob for `children`
> 📖 [bento][amp-social-share] Clean up storybooks for social share

- extensions/amp-story-auto-ads/0.1/story-ad-page.js
- extensions/amp-story-auto-ads/0.1/utils.js
In the normal case the cta url & cta type are extracted from the metadata obj and added as data-var attrs to the <amp-ad> element. In the no-signing case the metadata obj does not exist. This PR extends what we query for in the ad doc to find the `<meta name=amp-cta-*>` elements.
Should fix broken experimentA on master builds.
> 🐛 Fix story ads in no signing exp

- build-system/common/utils.js
**summary**
Globby does not [support windows paths](https://github.com/sindresorhus/globby/issues/127).
This fix worked for `--flags`, but we may want to look into switching to a lib that explicitly cares about Windows support.
> --files flag windows support

- extensions/amp-story/1.0/animation-presets.js
Uses keyframes based off of peak physics values.
Alternates easing for realistic velocity change.
Context / Fixes #30219
new:
old:
> Drop keyframes based on physics

- ads/yieldpro.js
After https://github.com/ampproject/amphtml/pull/29929, it is no longer supported to use implicit this. Therefore the reference to *this* needs to be changed to *global*.
@tsanders42 FYI. Regrettably it might have broken your ad since last week and we are working on a fix.
> Fix yield pro use of implicit this

- build-system/tasks/presubmit-checks.js
- extensions/amp-date-display/1.0/amp-date-display.js
- extensions/amp-date-display/1.0/date-display.js
- extensions/amp-date-display/1.0/date-display.type.js
- extensions/amp-date-display/1.0/storybook/Basic.js
- extensions/amp-date-display/1.0/test/test-amp-date-display.js
- extensions/amp-date-display/1.0/test/test-date-display.js
- extensions/amp-timeago/1.0/amp-timeago.js
- extensions/amp-timeago/1.0/storybook/Basic.js
- extensions/amp-timeago/1.0/test/test-amp-timeago.js
- extensions/amp-timeago/1.0/timeago.js
- extensions/amp-timeago/1.0/timeago.type.js
- src/preact/base-element.js
- src/preact/component/contain.js
- src/preact/component/wrapper.js
- src/utils/date.js
- test/unit/preact/test-base-element.js
- test/unit/utils/test-date.js
Partial for #30189, #30052, #29246.
This PR allows a more complicated logic for a prop mapping: many attributes -> a prop. On AMP side we have to support excessive input formats because we are not tied to any particular type system. On Preact's side, we are tied to JavaScript system and thus the typing is less ambiguous. It's easier to supply a single `Date|number` type for a datetime prop than numerous props that do the same thing. The conversion code in this case is simpler than the additional documentation code.
Some key points:
1. A bunch of date attrs (`datetime`, `timestamp-ms`, etc) map into a single `datetime` prop of a stricter type. E.g. strings no longer allowed and a component has almost no conversions/computations when handling this prop.
2. The mapping looks like this: …
> Multi-attribute prop bindings for date components

- build-system/babel-plugins/babel-plugin-transform-jss/index.js
- build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-jss-var/output.mjs
- build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-literal/input.js
- build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-literal/output.mjs
- build-system/tasks/create-golden-css/index.js
- build-system/tasks/jsify-css.js
**summary**
Transform the extracted css via our custom `postcss` function.
This is pretty gnarly. `postcss` runs async but babel can only run sync. I get around this by using `spawnSync`, but it is needlessly expensive.  When we start transforming more files it may pay to invest in starting up an external server and communicate over ports to amortize the cost as they do in [babel-plugin-transform-css](https://github.com/wbyoung/babel-plugin-transform-postcss).
The more obvious and better solution is to use jss plugins. this seems harebrained
> jss transform: transform via postcss

- extensions/amp-a4a/0.1/callout-vendors.js
- extensions/amp-a4a/rtc-documentation.md
- extensions/amp-a4a/rtc-publisher-implementation-guide.md
Similar to https://github.com/ampproject/amphtml/pull/13355, we'd like to submit a new endpoint to the RTC config.  This endpoint will respond in the same manner as the original `prebidappnexus` endpoint, though it will be hosted from a different location.
I'm not sure if anything else needs to be updated (eg documentation-wise), so please let me know if there is.  Thanks.
> ✨ Add prebidappnexuspsp as a vendor to RTC config

- ads/ads.extern.js
- ads/google/imaVideo.js
- extensions/amp-ima-video/0.1/test/test-amp-ima-video.js
See #30155.
Data from IMA SDK gives incorrect values required for interpolated label with currently used APIs, but a different one is equivalent.
Before:
> 🐛 Fix ad index value in IMA video

- extensions/amp-viewer-integration/0.1/test/integration/test-messaging-handshake.js
Closes #30217
I didn't quite understand, but changing the order helped when I run the test locally.
The test only fails when I run all four unit tests within this file in headless chrome. I wonder if it because we fail to clean up and reset the testing environment.
> ❄️ Attempt to deflake messaging-handshake test

- build-system/tasks/cherry-pick.js
This is to match `gulp release` logic.
> 🏗  Increment cherry pick branch version by number of commits

- extensions/amp-story/1.0/amp-story-system-layer.css
- extensions/amp-story/1.0/amp-story-system-layer.js
- extensions/amp-story/1.0/amp-story.css
[Demo](https://stamp-ui.web.app/examples/amp-story/ampconf.html)
- UI icons graphics and spacing updates
- EQ icon bug fix
Context / Fixes #30274  
Fixes #30289 
cc @hongcatlover
> 🖍 System UI updates

- extensions/amp-access-scroll/0.1/scroll-impl.js
Previously, Scroll was only interested in whether the file was blocked in order to determine next steps for the viewer. Now we also check if a particular value is in the response.
> 🐛 Also look at the content of the response when detecting Scroll

- package.json
- yarn.lock
include partial support for innerHTML entity decoding.
> dependencies: bump worker-dom

- build-system/tasks/storybook/amp-env/main.js
- builtins/storybook/amp-layout-with-aspect-ratio-css.amp.js
- builtins/storybook/amp-layout.amp.js
- css/ampshared.css
- src/layout.js
- test/unit/test-layout.js
- tools/experiments/experiments-config.js
Partial for #30291
This pull request implements two features:
1. When `aspect-ratio` is supported, the `layout=responsive` is implemented via this property and the private `sizer` element is not added.
2. The optimized AMP page can supply both `sizer` and `aspect-ratio` and AMP Runtime will hide the `sizer` if the browser supports the `aspect-ratio` CSS.
Additionally added few storybooks for the responsive layouts, with and without aspect-ratio support.
> Support aspect-ratio CSS for layout=responsive

- .eslintrc.js
- build-system/eslint-rules/jss-animation-name.js
Will error:
```diff
const JSS = {
foo: {
+ // The animation name in property animationName should start with $ (e.g. $foo).
+ // This scopes it to a keyframes rule present in this module.
animationName: 'bar',
+ // ----------------^
},
};
```
```diff
const JSS = {
foo: {
+ // The animation name in property animation should start with $.
+ // This scopes it to a keyframes rule present in this module.
animation: 'bar linear 0.5s',
+ // ------------^
},
};
```
> 🏗  Lint for $ in animation-name

- extensions/amp-auto-ads/0.1/firstimpression.io-network-config.js
Fixed a minor typo in network config code
> 🐛 amp-auto-ads: Fix a typo in firstimpression.io network config

- ads/_config.js
- ads/broadstreetads.js
This PR implements the render-start requested by the AMP team on https://github.com/ampproject/amphtml/pull/12475
> amp-ad type broadstreetads: Support renderStart()

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test-e2e/test-function-src.js
- extensions/amp-list/0.1/test/test-amp-list.js
- tools/experiments/experiments-config.js
Cleanup for [protocol adapters](https://github.com/ampproject/amphtml/issues/26474)
> 🚮  amp-list: remove experiment 'protocol-adapters'

- src/friendly-iframe-embed.js
This caused a major bug while we were experimenting with ads.
this would **silently** (because it is pre closure) remove the call for [installStylesForDoc](https://github.com/ampproject/amphtml/blob/master/src/friendly-iframe-embed.js#L696) in src/friendly-iframe-embed.js which would then break ads because no styles are installed in the friendly iframe.
this was only triggered in the esm build because the ["filter-imports" plugin](https://github.com/ampproject/amphtml/blob/master/build-system/babel-config/pre-closure-config.js#L32-L41) was only turned on in the esm build.
> when in ESM mode, copy the the parent runtime CSS into the friendly iframe

- extensions/amp-animation/0.1/install-polyfill.js
We need only polyfill when the major version of Safari is less than 14.
Example of Safari not polyfilled and working as expected.
Example inside Web Story.
> 🚀 Safari 14 Fixed the Web Animations API implementation

- extensions/amp-analytics/0.1/test/test-amp-analytics.js
- extensions/amp-analytics/0.1/test/test-visibility-manager.js
- extensions/amp-analytics/0.1/visibility-manager.js
#30105 added check element size
The visibility tracking relies on the IntersectionObserverEntry, this means if the element resizes itself within the viewport, and its intersectionRatio doesn't change,  a new IntersectionObserverEntry won't be fired. 
With the current implementation, the analytics service won't be able to pick up visibility change due to element resize within the viewport. Fortunately this won't be an issue within AMP because it doesn't allow element resizing within the viewport. One exception is if it's an inabox ad served in a non AMP page. 
The fix is to add an event listener to listen to window resize event when it is inabox mode.   
cc @jeffkaufman
> 🐛 Inabox visibility reporting: listen to window resize event

- build-system/global-configs/canary-config.json
Enables experiment from https://github.com/ampproject/amphtml/pull/28553 to limit number of elements that can be built in a single pass. This issue is affecting amp.dev and causing a long task .
> 🧪 Enable build-in-chunks experiment in canary-config.json

- extensions/amp-animation/0.1/storybook/Basic.amp.js
- extensions/amp-animation/0.1/storybook/Random.amp.js
- extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
- extensions/amp-date-display/1.0/storybook/Basic.amp.js
- extensions/amp-fit-text/1.0/storybook/Basic.amp.js
- extensions/amp-image-slider/0.1/storybook/Basic.amp.js
- extensions/amp-inline-gallery/1.0/storybook/Basic.amp.js
- extensions/amp-selector/1.0/storybook/Basic.amp.js
- extensions/amp-sidebar/0.1/storybook/Basic.amp.js
- extensions/amp-social-share/0.1/storybook/Basic.amp.js
- extensions/amp-social-share/1.0/storybook/Basic.amp.js
- extensions/amp-timeago/1.0/storybook/Basic.amp.js
- extensions/amp-youtube/0.1/storybook/Basic.amp.js
From [Storybook's docs](https://github.com/storybookjs/storybook/blob/next/lib/core/docs/storiesOf.md):
> In Storybook 5.2 we introduced a simpler and more portable [Component Story Format](https://storybook.js.org/docs/react/api/csf), and all future tools and infrastructure will be oriented towards CSF. Therefore, we recommend migrating your stories out of `storiesOf` API, and even provide [automated tools to do this](https://github.com/storybookjs/storybook/blob/next/lib/core/docs/storiesOf.md#component-story-format-migration).
AMP samples were using `storiesOf()`, but Preact samples already used Component Story Format.
Used migration tool mentioned.
> ♻️ Storybook in Component Story Format

- src/context/node.js
- test/unit/context/test-node-discover.js
> ContextNode: automatically re-discover changes in the shadow DOM on slotchange event

- extensions/amp-video/1.0/autoplay.jss.js
**Adding `content`**
This slipped me before, and without it `:before/:after` pseudoelements are not displayed.
**Removing `transform`**
Default translate values were used for a workaround where instead of setting `animation-play-state, we'd remove the entire animation`:
https://github.com/ampproject/amphtml/blob/c4a663d0ba13d0488c6fe73c55dc8c971ac6ec0d/src/service/video/autoplay.js#L73-L76
The bug this worked around is no longer [present](https://glitch.com/edit/#!/animation-play-state-transform) in iOS, so we can remove it. If we remove the default transform value, we can also remove the dual selector in `:before, :after {}`.
> 🖍 Cleanup autoplay JSS/fix :before, :after

- src/context/index.js
- src/context/node.js
- test/unit/context/test-node-discover.js
This API allows to group children of the same node into a sub-node. This makes it easier to to set properties on a whole group rather than doing it 1-by-1. For instance, this allows us to express something like this: "all unslotted children of a node have to be paused".
> ContextNode: groups API

- extensions/amp-social-share/1.0/social-share.js
- extensions/amp-social-share/1.0/social-share.type.js
- extensions/amp-social-share/1.0/test/test-social-share.js
Tracking Issue: https://github.com/ampproject/amphtml/issues/28283
Updated Preact component and automated tests for Social Share.
Preact component should not throw an error.
> 🐛 [bento][amp-social-share] Preact component should not throw error

- src/chunk.js
- test/unit/test-chunk.js
`isInputPending` is launching soon. This API is a better replacement for our current mechanism tracking the time spent in a current macrotask during chunking.
https://groups.google.com/a/chromium.org/g/blink-dev/c/8Vt2atMrNNs/m/1DGx9DKsBwAJ
This is a draft PR, and I'll continue iterating on it on Monday.
> 🚀 FID improvement use isInputPending if available for chunk.

- css/amp-story-player-iframe.css
- css/amp-story-player.css
- src/amp-story-player/amp-story-player-impl.js
Closes #27358
Adds a fallback for older Edge browsers that don't support `attachShadow` by using the player element as container instead of a shadow root.
It also resets the width/height of the `<a>`, so that it doesn't push the stories below when using the player element as a container.
> [amp-story-player] Add ShadowDOM fallback for edge

- build-system/tasks/extension-helpers.js
This PR cleans up the duplicate logging introduced by #30141.
Addresses https://github.com/ampproject/amphtml/pull/30141#discussion_r485963577
> 🏗 Clean up duplicate logging in `gulp dist` during `worker-dom` resource copying

- src/amp-story-player/amp-story-player-iframe-pool.js
- src/amp-story-player/amp-story-player-impl.js
- test/unit/test-amp-story-player.js
Closes #28987
Simplifies logic by:
* Checking if navigated story using `show(story)` has iframe
* if it does, just reposition the iframe
* if it doesn't, detach iframe and allocate to new current story.
It also leverages new loading strategy introduced in #29703 to prioritize loading the current story over the adjacent ones.
> 🚀 🐛  [amp-story-player] show() improvements

- examples/amp-ad/sticky.html
- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-ad/0.1/amp-ad-3p-impl.js
- extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
- extensions/amp-ad/0.1/amp-ad.css
- extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
- extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js
The button will render when the ad is rendered the first time.
It also adds tests to cover https://github.com/ampproject/amphtml/pull/30306
> ✨Add a close button to amp-ad stick type

- build-system/babel-plugins/babel-plugin-transform-jss/index.js
- build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-jss-var/output.mjs
- build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-literal/output.mjs
- css/ampshared.css
- extensions/amp-base-carousel/1.0/amp-base-carousel.js
- extensions/amp-inline-gallery/1.0/amp-inline-gallery-pagination.js
**summary**
This PR makes two modifications to the jss transformer: 
1. Uses the `@enum` closure type instead of untyped JSON for the `classes` object.
2. Uses a separate export for `CSS` instead of sidecar-ing it with the return of `useStyles`
> jss transform: use @enum instead of json.parse

- css/Z_INDEX.md
- extensions/amp-story-360/0.1/amp-story-360.css
Sets z-index on `i-amphtml-story-360-activate-button` to be same as `i-amphtml-story-system-layer`.
This ensures it will always be above content.
Updates Z_INDEX.md
cc @ampproject/wg-stories @t0mg
> 🐛 "activate 360" button always above content

- test/integration/test-amp-ad-3p.js
`window.location` in a srcdoc iframe is `"about:srcdoc"` in sane browsers and a special magic string in Edge and IE. The special-case handling was in place already for Edge, but not for IE, causing the IE11 integration test to fail. This PR adds the IE11 check to the special-case check.
> ✅ Fix amp-ad-3p sourceUrl assertion for IE11

- testing/test-helper.js
The `animation-play-state` property in IE11 is apparently known to be a bit funky, and returns an empty string for `document.body.style.animationPlayState` when the property remains unset through the CSS shorthand syntax. Since empty string isn't part of the allowed set defined for the assertion, the `isAnimationNone` fails for tests in IE11.
This PR adds the empty string to the accepted values for `animation-play-state`
Fixes failure:
> ✅  Fix failing isAnimationNone assertion in IE11

- test/integration/test-amp-ad-3p.js
Creating and dispatching custom events in IE11 requires a workaround rather than using the `Event` constructor directly. This PR replaces calls to `new Error()` with calls to the existing `createCustomEvent` helper. Fixes remaining failures in this test on IE11.
Fixed error (revealed by #30389, fixing a failure earlier in the test):
> ✅ Fix amp-ad-3p Event constructor calls

- build-system/babel-plugins/babel-plugin-transform-jss/index.js
- build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-jss-var/output.mjs
- build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-literal/output.mjs
**summary**
Unsure how necessary this is. I'm currently pretty confused by Closure Compiler's sometimes inconsistent mangling. Seeing this issue in online closure tools, but not in dist builds.
[Broken compilation examle](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT5_STRICT%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%250Aconst%2520a%2520%253D%2520%257B%2520%2522cx1%2522%253A%2520'hello'%252C%2520%2522cx2%2522%253A%2520'world'%257D%253B%250Aconst%2520getA%2520%253D%2520()%2520%253D%253E …
> jss: fix potential issue with quotes

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
- Change minified name for GSI JS. (#1282)
- Update dependency rollup to v2.28.2 (#1281)
- Adds handling of subscribe button on metering toast iframe (#1280)
- Update dependency postcss to v8.0.9 (#1279)
- Update dependency postcss to v8.0.8 (#1278)
- Update dependency postcss to v8.0.7 (#1276)
- GSI: Renders GSI iframe (#1273)
- Update dependency postcss to v8.0.6 (#1274)
- Update dependency rollup to v2.28.1 (#1275)
- Sends list of allowed origins in example iframe. (#1272)
- Create Example Google Sign-in iframe (#1238)
- Update dependency rollup to v2.27.1 (#1271)
- Update dependency postcss to v8.0.5 (#1270)
- Update dependency postcss to v8.0.4 (#1269)
- Update dependency rollup to v2.27.0 (#1268)
- Update dependency prettier to v2.1.2 (#1267)
- Update dependency postcss to v8.0.3 …
> SwG Release 0.1.22.121

- build-system/common/exec.js
- build-system/tasks/serve.js
- build-system/tasks/storybook/index.js
Previously, you'd have to run `gulp` at the same time as `storybook-amp` to serve binaries from `localhost:8000`.
> 🏗 Run default task in parallel with storybook-amp

- test/integration/test-actions.js
After lots of digging, I can't track down the source of this issue. The error message is cryptic:
When enabling logging and digging deeper, the root seems to come from a `SyntaxError` within an unhandled promise rejection, but it's been impossible to determine the source of the `SyntaxError` itself. Further digging might yield useful information, but for know this test should just be skipped until a fix is indentified. (See https://github.com/ampproject/amphtml/pull/30372 for the long, painful slog attempting to log something of use to squash this issue)
> ✅ Skip borked on= tests for IE11

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
- src/runtime.js
- test/unit/test-runtime.js
- tools/experiments/experiments-config.js
I'm the last one still disabling version locking, and it's easier to just override the local versions or manually opt-out in my local builds.
> 🚮 Remove version-locking in prod builds

- examples/visual-tests/amphtml-ads/resource/amp-ads-fallback.html
Without this slash, the URL is interpreted as a domain name. Travis somehow just blocks rather than fails fast, causing it to timeout and the loading indicator present. This PR changes the domain name to a path that returns 404.
> ❄️ Fix amphtml-ad visual diff test flakiness

- extensions/amp-youtube/amp-youtube.md
Fixing this: 
Markdown isn't able to show code within `<ul>` so this is a workaround.
> 📖 Quick fix to amp-youtube markdown code error

- build-system/server/new-server/transforms/sxg/sxg-transform.ts
- build-system/server/new-server/transforms/sxg/test/sxg-env-compiled/input.html
- build-system/server/new-server/transforms/sxg/test/sxg-env-compiled/options.json
- build-system/server/new-server/transforms/sxg/test/sxg-env-compiled/output.html
- build-system/server/new-server/transforms/sxg/test/sxg-env/input.html
- build-system/server/new-server/transforms/sxg/test/sxg-env/options.json
- build-system/server/new-server/transforms/sxg/test/sxg-env/output.html
- build-system/server/new-server/transforms/sxg/test/sxg-query-param/input.html
- build-system/server/new-server/transforms/sxg/test/sxg-query-param/options.json
- build-system/server/new-server/transforms/sxg/test/sxg-query-param/output.html
- build-system/server/new-server/transforms/transform.ts
- build-system/server/new-server/transforms/utilities/script.ts
pulling this in instead of https://github.com/ampproject/amphtml/pull/30401 since Derek has finished his internship and i will take over his PRs.
this modifies the script src to either use ".sxg.js" as the suffix to the path when in `--compiled` mode, otherwise it just appends the `f=sxg` query param
> create a postHTML transformer that modifies script src url for sxg mode

- extensions/BUILD
- extensions/WORKSPACE
- validator/BUILD
protoascii in extensions are needed by validator project workspace.
> Create build rules for extensions protoascii 

- src/custom-element.js
In ampdoc-fie the existing check would not correctly detect FIE case.
cc/ @lannka
> 🐛 Fix A4A check in custom element

- build-system/common/check-package-manager.js
There is an issue with the current release of `yarn`, this PR temporarily pins us to 1.22.4 until we can resolve.
> 🏗 Pin yarn to 1.22.5 temporarily

- css/amp-story-player-iframe.css
- css/amp-story-player.css
- src/amp-story-player/amp-story-player-impl.js
Closes #30423
I tested different layouts in AMP (responsive, fixed...) and they seemed to work fine.
Also tested without shadow DOM in case it's not supported.
Note that since there's no way of calling `this.applyFillContent(element)` from the `amp-story-player-impl.js` class directly (since it does not inherit from base element), I had to apply the CSS class `i-amphtml-fill-content` manually.
> 🐛  [amp-story-player] Adds intermediate element and removes default size

- extensions/amp-accordion/0.1/amp-accordion.js
This is a workaround for https://bugs.chromium.org/p/chromium/issues/detail?id=1134237
> amp-accordion: Enable display locking based on `beforematch`

- src/custom-element.js
**summary**
These were for CustomElements v0, but we are fully on v1 now. (correct me if I'm wrong)
> custom-element: remove attached/detached callbacks

- builtins/amp-img.js
- extensions/amp-a4a/0.1/test/test-amp-a4a.js
- extensions/amp-analytics/0.1/test/test-amp-analytics.js
- extensions/amp-analytics/0.1/test/test-vendors.js
- extensions/amp-iframe/0.1/amp-iframe.js
- extensions/amp-story/1.0/amp-story-grid-layer.js
- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-truncate-text/0.1/amp-truncate-text.js
- extensions/amp-video/0.1/amp-video.js
- src/base-element.js
- src/custom-element.js
- test/unit/test-amp-img.js
- test/unit/test-custom-element.js
- testing/describes.js
Addresses https://github.com/ampproject/amphtml/issues/30487
Changes:
- 0 instances found of an overrided BaseElement `createdCallback`, so I just removed it.
- 4 instances of overriden `firstAttachedCallback`. There were only two kinds:
1. Calculation and caching of `prerenderAllowed`. Depending on if the calculation seemed expensive, I either inlined or made the caching lazy. Note that this is the primary valid-ish use-case, although I'd argue (and implement here) that a lazy calc of the value within the prerenderAllowed() method is better. 
2. Code that could have been in `buildCallback`, so I moved it.
> ♻️ Remove firstAttachedCallback and createdCallback

- build-system/pr-check/dist-tests.js
- build-system/pr-check/e2e-tests.js
- build-system/tasks/test-report-upload.js
Currently, dist and e2e tests try to report test results on master push builds, but fail because the commands are not called with the `--report` flag, so the file read fails. This throws an error in the test-report-upload task, which fails the build.
This PR 1) adds the necessary `--report` flags to ensure the result report itself is created and 2) adds error handling to the test-report-upload task so failures don't cause the task to fail. An alternative to 2 would be letting the task fail, and using `timedExec` instead of `timedExecOrDie` for the test-report-upload task, so failures don't fail the build. I can make that change if desired.
Note that these errors make the master build red, but do not occur locally or on PR builds, so they should not block other progress (this is also what …
> 🏗Fix test-report-upload in push builds

- build-system/babel-plugins/babel-plugin-transform-jss/test/index.js
- build-system/server/app-index/boilerplate.js
- build-system/server/app-index/file-list.js
- build-system/server/app-index/settings.js
- build-system/server/app-index/template.js
- build-system/server/shadow-viewer.js
- build-system/tasks/e2e/describes-e2e.js
- build-system/tasks/helpers.js
- build-system/tasks/storybook/amp-env/main.js
- build-system/tasks/storybook/preact-env/main.js
- extensions/amp-addthis/0.1/addthis-utils/classify.js
- extensions/amp-animation/0.1/web-animations.js
- extensions/amp-apester-media/0.1/monetization/companion/video.js
- extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
- extensions/amp-geo/0.1/test/test-amp-geo.js
- extensions/amp-script/0.1/test/integration/test-amp-script.js
- extensions/amp-story/1.0/_locales/km.js
- extensions/amp-subscriptions/0.1/test/test-crypto-handler.js
- src/amp-shadow.js
- src/amp.js
- src/iframe-helper.js
- src/service/origin-experiments-impl.js
- src/service/position-observer/position-observer-impl.js
- src/service/video-manager-impl.js
- src/service/viewport/viewport-binding-ios-embed-wrapper.js
- src/service/viewport/viewport-binding-natural.js
- test/integration/test-amp-bind.js
- test/integration/test-amp-recaptcha-input.js
- test/unit/test-origin-experiments.js
- testing/yield.js
These eslint-disables are showing up on check-types as unnecessary. Removing them will make the logs easier to view.
> 🚮 Remove unused eslint-disable

- build-system/server/app.js
- build-system/tasks/serve.js
By appending an `onunload` event handler when this flag is set, this will report the code coverage each time the browser exits a page, hits back, closes the tab, etc. With this in place, it should be possible to manually test pages under `examples/` and see exactly what lines of code have been manually tested.
Node this only works with code compiled using `gulp (build|dist) --coverage`, which takes longer than a non-instrumented build.
---
```bash
git checkout -b rcebulko-unload master
git pull https://github.com/rcebulko/amphtml.git rcebulko/unload
gulp build --fortesting --coverage
gulp serve --coverage=live
```
4. Visit one or more `examples/` pages served by the AMP Dev Server (a tab should open automatically), play with components, etc.
5. Close each tab, or use the **Back** button …
> 🏗 Add `gulp serve --coverage=live` to auto-report coverage while browsing

- extensions/amp-video/OWNERS
I have been authoring (eg: https://github.com/ampproject/amphtml/pull/21972, https://github.com/ampproject/amphtml/pull/23360, https://github.com/ampproject/amphtml/pull/25456, https://github.com/ampproject/amphtml/pull/29233) and reviewing (eg: https://github.com/ampproject/amphtml/pull/28005, https://github.com/ampproject/amphtml/pull/29182, https://github.com/ampproject/amphtml/pull/29308) many PRs related to `amp-video` and its `loadPromise` helper over the past 2+ years. @ampproject/wg-stories  has many video related fixes or improvements and having someone from the working group part of `amp-video` OWNERS would help with smaller scope fixes such as https://github.com/ampproject/amphtml/pull/30481 and more to come.
cc @ampproject/wg-ui-and-a11y
> Add gmajoulet to amp-video OWNERS.

- extensions/amp-story/1.0/amp-story.js
- extensions/amp-story/1.0/pagination-buttons.css
While working on #30031 I noticed pagination buttons weren't being built for documents that were initially prerendered. This is because the `layoutCallback()` was being short circuited here for prerendered documents:
https://github.com/ampproject/amphtml/blob/056f82bf5ec3a9aac06a3747b37bea0b8e42e842/extensions/amp-story/1.0/amp-story.js#L1012-L1019
Which is right before the pagination buttons are built.
> 🐛  [amp-story] Build pagination buttons for pre-rendered stories

- src/service/performance-impl.js
we are seeing a higher rate of this error in module build and this affects the startup chunk process. Wrap the observe call in a try/catch, this seems to be a bug in chrome 73
Fixes https://github.com/ampproject/amphtml/issues/29399
> add a try catch for navigation performanceobserver

- build-system/compile/bundles.config.js
- extensions/amp-date-countdown/1.0/amp-date-countdown.js
- extensions/amp-date-countdown/1.0/date-countdown.js
- extensions/amp-date-countdown/1.0/date-countdown.type.js
- extensions/amp-date-countdown/1.0/test/test-amp-date-countdown.js
- extensions/amp-date-countdown/1.0/test/test-date-countdown.js
Date-countdown items: https://github.com/ampproject/amphtml/issues/30052
Bento version of AMP component for `amp-date-countdown`
Added the amp component
Updated the preact component.  Some nuanced notes on the design below:
1. `useRenderer` sets state of the `value` / `rendered` variable
2. this triggers a re-render of the preact component (this variable is controlled by `useState`)
3. on this re-render, the `data` object passed into `useRenderer` should NOT be changed (properties can change, but actual object should be the same instance).  If it is changed, `useRenderer` will attempt to set state of `value` / `rendered` again, causing an infinite loop
4. the `data` object is therefore stored in `dataRef` (`useRef` hook).  On the renders (and re-renders) the `data` object is NOT changed …
> ✨ [bento][amp-date-countdown] Bento version of AMP component

- src/service/performance-impl.js
- test/unit/test-performance.js
This collects the SSR experiments enabled in the `<meta name=amp-usqp>` for CSI metrics.
See the related cl/335090010 for injecting the new meta tag.
> CSI: Report SSR experiments via the USQP meta

- build-system/common/travis.js
- build-system/tasks/test-report-upload.js
Oddly enough, there is no way to link to a Travis job/build log with just the repo and job/build number.
> 🏗 Report Travis job/build URLs to test case reporting

- build-system/common/check-package-manager.js
- build-system/common/exec.js
- build-system/common/process.js
- build-system/pr-check/dist-tests.js
- build-system/pr-check/e2e-tests.js
- build-system/pr-check/local-tests.js
- build-system/pr-check/utils.js
- build-system/tasks/cherry-pick.js
When introducing the helper `execOrThrow`, I built on `execWithError`, which uses stderr to detect a failure. This fails when nothing is written  to stderr, but the process status code is non-zero. This PR switches the logic to mirror `execOrDie` instead.
> 🏗 Use status instead of stderr to detect failure in execOrThrow

- extensions/amp-date-countdown/1.0/storybook/Basic.amp.js
- extensions/amp-date-countdown/1.0/storybook/Basic.js
Date Countdown Tracking Issue: https://github.com/ampproject/amphtml/issues/30052
Add storybook for AMP component
Update storybook for Preact component
AMP Component determines time from one of four attributes:
-`end-date`
-`timeleft-ms`
-`timestamp-ms`
-`timestamp-seconds`
If `end-date` is available, it will use `end-date`.  If not, it will use `timeleft-ms`, then `timestamp-ms`, etc.
Since the `end-date` knob is a `date` type knob, it cannot be configured to be a null value.  So `end-date` will always be included and the other 3 values will not have a chance to be used.
To get around this, I added an additional knob on the AMP storybook `Select a "date-attribute"`.  This allows the user to toggle one of the four date attributes `end-date`, `timeleft-ms`, `timestamp-ms`, and …
> 📖 [bento][amp-date-countdown] Add and update existing storybook for amp-date-countdown

- validator/README.md
Updates both Linux and OSX instructions to Python 3, and changes OSX to use pip-provided protobuf library instead of brew, since the latter seems to be too old to work with our current build.py.
> 📖 Update validator install instructions

- third_party/zuho/zuho.js
`scene-heading` value needs to be reversed in `euler_` so api behavior is symmetric with `heading-start` and `heading-end`.
Noticed while working on #30002
> 🐛 Correct scene-heading value in euler_ method

- 3p/ampcontext.js
- ads/google/csa.js
- build-system/tasks/presubmit-checks.js
- test/unit/ads/test-adplugg.js
- test/unit/ads/test-aduptech.js
- test/unit/ads/test-csa.js
It should not change the behavior. 
3p iframe is now polyfilled, so we can get rid of promise use restriction.
> Refactor onResizeSuccess/onResizeFailure to requestResize

- extensions/amp-story-interactive/0.1/amp-story-interactive.css
Fixes #30531 
Screenshot of working state in issue linked.
> 🐛 Fix interactive prompt not centering when CSS variable is center

- src/amp-story-player/amp-story-player-impl.js
- test/unit/test-amp-story-player.js
According to https://github.com/ampproject/amphtml/blob/master/extensions/amp-viewer-integration/integrating-viewer-with-amp-doc-guide.md#google-amp-cache, we should only need to add this query param when using the cache URL of the story.
> 🐛 [amp-story-player] Only add amp_js_v when amp cache

- extensions/amp-access-scroll/0.1/amp-access-scroll.css
Overly broadly-scoped CSS styles affecting margin or padding for the .amp-access-scroll-bar div result in the Scrollbar looking cut off and unusable. 
This PR ensures we specify a 0 reset for padding and margin so the Scrollbar appears correctly and is more resilient to other CSS styles of the page using amp-access-scroll.
cc @kushal 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ampproject/amphtml/30498)
> 🐛 amp-access-scroll: Reset iframe container padding and margin

- 3p/beopinion.js
It is not a great idea to keep DoSing requestResize API, but for sake of refactoring, I am keeping its behavior the same.
> ♻️ Move beopinion to use requestResize promise

- build-system/compile/compile.js
This includes `AbortController` in the approved ESM polyfills.
For some reason, ESM polyfills are still stripped in the build-system code _and_ in source code (via `IS_ESM` guards), so when I added `AbortController` with only the source code it was still stripped by the build system.
> 🔥 Include AbortController in ESM polyfills

- extensions/amp-story/1.0/amp-story-page.js
- extensions/amp-story/1.0/test/test-amp-story-grid-layer.js
- extensions/amp-story/1.0/test/test-amp-story-page.js
Fixes https://github.com/ampproject/error-reporting/issues/13
GetImpl is being called without waiting for the custom element to load so sometimes the getImpl doesn't exist for the story.
> 🐛 Fix .getImpl race condition on Android

- extensions/amp-story-interactive/0.1/amp-story-interactive-abstract.js
Fixes #30584 
Tested locally, with this patch the effects only show when the user selects an option for the first time, but don't show when you reload an interactive that was already selected
> 🐛 Interactives only should show confetti on user selection

- build-system/compile/bundles.config.js
- build-system/compile/compile.js
All polyfills are already guarded by `IS_ESM` and `IS_SXG` checks already, so an additional build-time removal is not necessary anymore.
> 🏗 Remove includeOnlyESMLevelPolyfills

- src/service/performance-impl.js
- test/unit/test-performance.js
the performance tracking instance is initialized very early in the amp initialization lifecycle. A throw to a call to `observe` can occur and break the initialization of the whole runtime. Make it more resilient to this case by wrapping all calls to observe in a try catch block
> add try/catch to calls to PerformanceObserver.prototype.observe and add tests

- build-system/tasks/e2e/describes-e2e.js
Hooks into the `istanbul-middleware/lib/core` module to directly merge coverage objects extracted from the page after each test, and reports them all at once at the end of the e2e test suite.
> ✅ Aggregate coverage during testing and report after

- builtins/amp-img.js
- extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js
- src/base-element.js
- test/unit/test-amp-img.js
- test/unit/test-base-element.js
Fixes https://github.com/ampproject/amphtml/issues/30547
While here, I noticed that `propagateDataset` is used exclusively by `amp-img` and so does not belong in `base-element` IMO
> amp-img: do not propagate data-amp-bind*

- .github/ISSUE_TEMPLATE/cherry_pick_template.md
- .github/ISSUE_TEMPLATE/page-experience.md
- .github/ISSUE_TEMPLATE/release-tracking-issue.md
This PR adds a new section to the CP template to enable AMP's QA expert to verify changes after they are cherry-picked.
> 📖 Update Cherry-pick template with QA section

- .travis.yml
- build-system/common/check-package-manager.js
AMP uses `yarn` v1 for package management. The latest two stable versions 1.22.10 and 1.22.5 appear to have intermittent [GPG signature problems](https://travis-ci.org/github/ampproject/amphtml/jobs/735788977#L326) during installation. This PR does two things:
- Pins the local dev version of `yarn` to 1.22.4
- Removes the extra installation step for Travis' Xenial machines, which now come with 1.22.4 preinstalled
The long term fix is to pursue a replacement of our package management solution via #30518.
> 🏗 Pin `yarn` stable version to v1.22.4

- src/amp-story-player/amp-story-player-impl.js
Follow up for #30500
When sending a `customDocumentUI ` message, passes a new object with the "controls" key for future-proofing.
> [amp-story-player] Pass object with controls key

- extensions/amp-animation/0.1/test/test-amp-animation.js
- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
- extensions/amp-twitter/0.1/amp-twitter.js
- src/base-element.js
- src/custom-element.js
- src/service.js
- src/service/core-services.js
- src/service/loader-element.js
- src/service/loading-indicator.js
- src/services.js
- test/unit/test-amp-inabox.js
- test/unit/test-custom-element.js
- test/unit/test-loader.js
- test/unit/test-loading-indicator.js
Partial #30620.
TODO:
Key points:
1. Most refactoring is straightforward code move from `custom-element.js` to `loading-indicator.js`.
2. However, one critical change: the `inViewport` callback is no longer used and instead `IntersectionObserver` is used. Thus, the main API that custom element calls is: `track` (start tracking the element in case loading indicator needs to be shown) and `untrack` (stop tracking and cleanup).
3. The `isLoadingReused` is removed because it's not a property of an element but rather the property of a loader - whether or not the loader is shown for layout or for any other reason.
4. The `LoadingIndicator` service tracks the element's state in a weak map.
5. The `LoadingIndicator` service is installed _only_ in the environments where it's used. E.g. it's …
> Reimplement loading indicator via IntersectionObserver

- extensions/amp-story-interactive/0.1/amp-story-interactive-binary-poll.css
Binary polls with more than two lines on the title would not clamp the text appropriately.
This PR adds a max-width equal to 2 line-heights for the title container, and moves back the percentage to occupy the space it already did when the height of the title is at one line.
This is what the error looked like:
This is how it looks like now:
Fixes #30657
> 🐛Fix binary poll not clamping more than two lines

- extensions/amp-analytics/analytics-vendors-list.md
The links that are wrapped in `` 403 but actually work when visiting manually.
> 📖 Fix dead links in analytics vendors

- extensions/amp-base-carousel/1.0/amp-base-carousel.js
- extensions/amp-base-carousel/1.0/arrow.js
- extensions/amp-base-carousel/1.0/base-carousel.js
- extensions/amp-base-carousel/1.0/base-carousel.jss.js
- extensions/amp-base-carousel/1.0/base-carousel.type.js
- extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
- extensions/amp-base-carousel/1.0/storybook/Basic.js
- extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
- extensions/amp-base-carousel/1.0/test/test-base-carousel.js
This PR adds the `outsetArrows` prop to `amp-base-carousel` with unit tests. 
`outsetArrows` = `Boolean`
- Whether to display next and prev arrows beside the carousel (`true`) or on top of it (`false`). Defaults to `false`. 
- When `true`, there are the following additional side effects: 
- The width of the slides is `100px` less than the width of the full carousel to account for the arrows (`50px` each). 
- `controls` attribute is ignored and defaults to value `"always"`
- `true`:
- `false`:
Note this prop was originally exclusive to `amp-stream-gallery` but is being moved to `amp-base-carousel` instead. Partial for #28284
> Bento Carousel: `outsetArrows` prop

- extensions/amp-story-360/0.1/amp-story-360.css
Align `activate 360` button with header UI for system UI consistency.
cc @ampproject/wg-stories @hongcatlover
> 🐛 Align 'activate 360' button with header UI

- extensions/amp-a4a/0.1/callout-vendors.js
- extensions/amp-analytics/analytics-vendors-list.md
Also updated the Lotame vendor link.
> ✨ Lotame: Change to allow limiting the maximum number of audiences. 

- examples/amp-story-360.amp.html
- extensions/amp-story-360/0.1/amp-story-360.js
Sets default heading orientation when in gyroscope mode.
[Demo](https://stories-360.web.app/examples/amp-story-360.amp.html) 
This is called on the active page on:
- page navigation
- gyroscope enabled
- layout callback
Context / Fixes #30002
> ✨ Set default orientation in gyroscope mode

- src/service/performance-impl.js
- test/unit/test-performance.js
Send document `canonicalUrl` with `sendCsi` viewer events.
FYI @ampproject/wg-stories
> Send document canonicalUrl with sendCsi viewer events.

- build-system/server/new-server/transforms/tsconfig.json
- build-system/server/new-server/transforms/utilities/script.ts
Two small fixes in this PR:
1. Explicitly adds a dependency [on the `dom` library](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29733#issuecomment-430077183). (The implicit dependency is causing errors in an [unrelated PR](https://github.com/ampproject/amphtml/pull/29967).)
2. Silences a message so that Travis and local testing logs are less noisy.
> 🏗 Fix errors in new server transforms and make logs less noisy

- extensions/amp-accordion/1.0/accordion.js
- extensions/amp-accordion/1.0/amp-accordion.js
- extensions/amp-accordion/1.0/test/test-accordion.js
- extensions/amp-accordion/1.0/test/test-amp-accordion.js
- src/utils/id-generator.js
Tracking Issue for amp-accordion: https://github.com/ampproject/amphtml/issues/30445
This PR adds the following a11y attributes to amp-accordion.
**Adding the following attributes to `header`:**
role="button"
aria-controls={contentId}
tabIndex="0"
**Adding to `content`:**
id={contentId}
**Outstanding question (answered below):**
1. In amp-mode we may overwrite an existing `id`.  Not sure how to check for existing id and pass it to header.
2. Should we remove things like `role` and `aria-controls` on callback of `headershim's` `layoutEffect`?  Currently am only checking for `tabIndex` since I am checking whether or not `tabIndex` already exists prior to overwriting.
**Answers**
1. This is marked as todo in Tracking Issue: https://github.com/ampproject/amphtml/issues/30445 (handle protect …
> ✨ [bento][amp-accordion] Adding a11y to bento accordion

- src/service/resource.js
- test/unit/test-resource.js
Fixes https://github.com/ampproject/amphtml/issues/30379.
Affected components: 
- amp-addthis
- amp-analytics
- amp-bind-macro
- amp-state
- amp-sticky-ad
- amp-user-notifications
Root cause is related to `intersect-resources` experiment. Since measurement can (and often will) occur before the extension loads, measurement is then done while still a stub. At that moment, `isAlwaysFixed` is always false.
Therefore layoutBox computations were not adjusted for `position:fixed` and components would not be laid out. Band-aid fix in this PR is to recompute measurements once the extension loads using the same computed rect as earlier (but now taking the fixed position into account).
Future work: instead of relying upon some notion like `isAlwaysFixed`, we should have a simpler flag for …
> resources-impl: fix alwayFixed

- extensions/amp-consent/0.1/amp-consent.js
- extensions/amp-consent/0.1/test/test-amp-consent.js
From this discussion: https://github.com/ampproject/amphtml/issues/28634#issuecomment-690605633
Remove the restriction on `consentMetadata` to only be updated in conjunction with `consentString`.
For the purposes of updating from `checkConsentHref`, `consentStateValue` will have to be defined, and `consentRequired` will have to be true as well.
> Remove consent string restriction on metadata

- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-a4a/0.1/test/test-amp-a4a.js
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Cleanup 'frc' parameter for amp-ad type=doubleclick ad requests used to determine how often request was triggered from resumeCallback.
> Amp-ad Doubleclick: Remove frc parameter

- src/OWNERS
- src/service/OWNERS
Fix for #30684 (changes src/OWNERS instead of src/service/OWNERS)
> Owners fix to storage-impl

- .prettierrc
- build-system/tasks/lint.js
- contributing/TESTING.md
- yarn.lock
Yarn can sometimes incorrectly resolve [caret semver versions](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) in its lockfile (typically during upgrades). E.g. `prettier` version `^2.0.0` is resolved to `2.0.1` instead of `2.1.2` in [`yarn.lock`](https://raw.githubusercontent.com/ampproject/amphtml/d3202baae0d7959edd375a0f672e2970a4ec041b/yarn.lock) (search for `"prettier@^2.0.0:"`). NPM correctly resolves caret versions, and doesn't have this bug.
This PR contains a couple of pre-emptive fixes that will prevent a bunch of new Prettier errors from appearing when we switch from Yarn to NPM:
1. Updates the default globs used by `gulp lint` to explicitly ignore files in `.gitignore`
2. Uses the exact same `prettier` version for `gulp lint` and `gulp prettify`
With this PR, the …
> 🏗 Pre-emptive lint fixes + clean up

- extensions/amp-consent/amp-consent.md
Better documentation for when the meta tag is required in amp-consent [type].
Closes #30553
> 📖 amp-consent meta tag documentation

- extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
This fixes a new regression introduced by #30426.
In it, I changed `amp-analytics` to call `collapse` instead of `toggle`. This causes the analytics element's owner to be notified via `collapsedCallback`. `amp-sticky-ad` receives that notification, and then [collapses itself](https://github.com/ampproject/amphtml/blob/master/extensions/amp-sticky-ad/1.0/amp-sticky-ad.js#L128-L136). What should happen is the sticky ad should only collapse if the _ad_ its wrapping collapses, and we can just ignore everything else.
> 🔥 Only collapse sticky-ad when ad collapses

- contributing/DEVELOPING.md
- contributing/component-validator-rules.md
- contributing/contributing-code.md
- contributing/getting-started-e2e.md
Our dev docs point to the codelab at https://codelabs.developers.google.com/codelabs/creating-your-first-amp-component/index.html as a good starting point for writing a new AMP component.
The codelab has disappeared and the link 404s, so this PR replaces it with [this guide](https://github.com/ampproject/amphtml/blob/master/contributing/building-an-amp-extension.md) wherever applicable.
> 📖 Fix dead link in AMP dev docs

- extensions/amp-access/0.1/iframe-api/OWNERS
- src/purifier/OWNERS
- third_party/amp-toolbox-cache-url/OWNERS
This PR adds the infra and performance WGs as silent owners of `package.json` files in `amphtml` subdirectories. The original owners of these packages will continue to be notified of changes, while making infrastructure maintenance and upgrades easier.
> 🏗 Add `OWNERS` files to simplify package updates in `amphtml` subdirs

- extensions/amp-social-share/0.1/amp-social-share.js
- extensions/amp-social-share/0.1/storybook/Basic.amp.js
- extensions/amp-social-share/0.1/test/test-amp-social-share.js
- extensions/amp-social-share/amp-social-share.md
Add a default value for `aria-label` on social share.
Fixes: https://github.com/ampproject/amphtml/issues/29563
> ♿ [a11y-fixit][amp-social-share] Add social share aria-label

- validator/js/gulpjs/index.js
Fixes #30527
By [default](https://github.com/ampproject/amphtml/blob/64c46649d55d5fb56e548455981de742af56a3a4/validator/js/gulpjs/index.js#L22) the gulp implementation of the validator uses [fancy-log](https://www.npmjs.com/package/fancy-log) for logging. However it calls the non-existing method `.log` to report results. Instead use `.info`.
Verified now working as intended.
> use fancy-log.info()

- validator/js/gulpjs/README.md
- validator/js/gulpjs/package.json
This PR includes updating the readme and version in package.json.
Already released as [1.0.6](https://www.npmjs.com/package/gulp-amphtml-validator/v/1.0.6).
Includes PR #30744
> Release gulp-amphtml-validator @1.0.6

- extensions/amp-onetap-google/validator-amp-onetap-google.protoascii
- validator/testdata/transformed_feature_tests/amp-img.html
- validator/testdata/transformed_feature_tests/amp-img.out
- validator/validator-main.protoascii
Changes:
- cl/336924217 Revision bump for #30418
- cl/336906679 Fix trailing tabs on validator-amp-onetap-google
- cl/336771722 Revision bump for #30576
- cl/336216200 Fix typo Obsolute -> Obsolete.
- cl/336204310 Validator: allow loading=lazy on SSR'd amp-img > img
> Validator rollup for 20201020

- extensions/amp-accordion/0.1/amp-accordion.js
- extensions/amp-accordion/0.1/test/test-amp-accordion.js
- extensions/amp-accordion/amp-accordion.md
Add the `role` and `aria-labelledby` attributes to the `content` element of each `accordion` section.
Fixes: https://github.com/ampproject/amphtml/issues/30727
> ♿ [a11y-fixit][amp-accordion] Add various a11y attributes to amp-accordion

- extensions/amp-story/1.0/amp-story-tooltip.css
The parent `.i-amphtml-story-tooltip` has a `max-width`.
We can use `flex-shrink: 0` on the children we don't want to shrink.
Then `i-amphtml-tooltip-text` will grow or shrink based on the space it needs.
Context / Fixes #30777
> 🐛 🖍  Prevent tooltip graphics from cropping

- src/service/resources-impl.js
- test/_init_tests.js
Addresses https://github.com/ampproject/amphtml/issues/30522
- resources-impl fix: with intersect-resources, components that are unlaid are moved back to `READY_FOR_LAYOUT` instead of `NOT_YET_BUILT` since they in general don't need explicit measurements. Therefore the cleanup() function was missing them.
cc @jridgewell to review the resources change
> unit tests: align with prod-config

- extensions/amp-carousel/0.1/base-carousel.js
- extensions/amp-carousel/0.1/base-slides.js
- extensions/amp-carousel/0.1/scrollable-carousel.js
- extensions/amp-carousel/0.1/slidescroll.js
- extensions/amp-carousel/0.1/test/test-base-slide.js
**summary**
While working on removing `viewportCallback` (https://github.com/ampproject/amphtml/issues/30620), I noticed this extraneous lifecycle hook within amp-carousel 0.1 components. It was basically manual inheritance and may as well take advantage of actual inheritance instead.
**testing**
> carousel: remove onViewportCallback

- build-system/global-configs/canary-config.json
- build-system/global-configs/prod-config.json
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
For amp-ad type=adsense or doubleclick, 1% experiment that sends new ptt parameter on ad request with fixed value.
> 1% experiment - AdSense/GAM ad request ptt parameter

- css/amp-story-player-iframe.css
- css/amp-story-player.css
The `.i-amphtml-story-player-shadow-root-intermediary` class was in the Shadow CSS file, where it should've been in the light DOM. This caused the intermediary element (the element between the `amp-story-player` and the shadow DOM) to not have any height. Breaking the `height` CSS property chain.
We didn't catch this in QA because our docs were not using `<!DOCTYPE html>`: https://stackoverflow.com/questions/1966300/height-100-is-not-working-in-html-when-using-doctype
Closes #30783
> 🔥  Fix height bug

- extensions/amp-accordion/1.0/accordion.js
- extensions/amp-accordion/1.0/amp-accordion.js
- extensions/amp-accordion/1.0/test/test-accordion.js
- extensions/amp-accordion/1.0/test/test-amp-accordion.js
Accordion Tracker Issue: https://github.com/ampproject/amphtml/issues/30445
Move the `aria-expanded` attribute from the `section` to its first child element `header` to match `0.1`.
> ✨ [bento][amp-accordion] Move aria-expanded from section to header

- extensions/amp-list/0.1/amp-list.js
amp-list fix to #29611 
>We recommend completely removing the aria-live="polite" that is generated by default for <amp-list> To convey that a list has changed, use announcements such as "list updated", "item added", or similar. Don't fire these announcements on page load when the list if first rendered, but reserve these for subsequent changes after the initial render.
- Why not adding the announcements as suggested. 
`<amp-list>` either load more item via the "Load more" manually, or via `load-more=auto`
When load more manually, there's the load more button, we don't need the `list updated` announcements because the load more action is triggered by user.
When load more automatically, we are aiming to provide the infinite scroll behavior. Where one never reach the end of the list. In this …
> ♿  remove aria-live=polite from amp-list

- extensions/amp-social-share/0.1/amp-social-share.css
- extensions/amp-social-share/0.1/test/test-amp-social-share.js
- extensions/amp-social-share/amp-social-share.md
a11y fixit week issue: https://github.com/ampproject/amphtml/issues/29561
Add a custom CSS (blue outline)(see Twitter in screenshot below) when an `amp-social-share` element is focused.  Chose not to use polyfill required CSS selector mentioned in issue as feature works great for all users not just keyboard users.  Choice of color is based on other focus items used in amp, see `main.css` (see this example: https://github.com/ampproject/amphtml/blob/master/build-system/server/app-index/main.css#L208)
> ♿ [a11y-fixit][amp-social-share] Add custom CSS when focussed for amp-social-share

- spec/amp-actions-and-events.md
> 📖 Update doc to pair focus with scrollTo as an a11y best practice (#24555)

- extensions/amp-story-360/0.1/test/validator-amp-story-360.html
- extensions/amp-story-360/0.1/test/validator-amp-story-360.out
- extensions/amp-story-360/validator-amp-story-360.protoascii
> 🐛 Add "controls" to amp-story-360 validator

- src/viewport-observer.js
- test/unit/test-viewport-observer.js
**summary**
Adds `viewport-observer` file with three exported functions.
1. `getViewportObserver`: its a helper for creating a viewport-tracking IntersectionObserver. Attempts to add 25% rootMargin as a nice-to-have, but if impossible proceeds without it.
2. `observe`: a method for registering a callback for when an element enters/exits viewport. essentially an on-demand viewportCallback that ~10 components will use (as opposed to all). This allows them to share the same InOb, one per window. While theoretically a shared InOb for all use cases could cause conflicts if multiple actors try to observe/unobserve the same set of elements, this shouldn't happen when each component is only responsible for managing themselves.
3. `unobserve`: cleanup function for observe.
Notes: 
- Only one …
> utility: add viewport-observer

- build-system/compile/bundles.config.js
- build-system/global-configs/experiments-config.json
- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-inabox.css
- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-shared.css
- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
- extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
- extensions/amp-story-auto-ads/0.1/story-ad-page.js
- extensions/amp-story-auto-ads/0.1/story-ad-ui.js
- src/inabox/amp-inabox.js
- src/inabox/inabox-story-ad.js
Introduces new logic to inabox that detects for story ad metadata, and if it exists, renders as a story ad. 
Part of #27851
> 🧪 Add story ad rendering to inabox.

- extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
- extensions/amp-base-carousel/1.0/storybook/Basic.js
Unfortunately, we're still blocked from using `button` knobs until we Storybook 6.1 is released.
> Carousel: imperative API in storybooks

- extensions/amp-carousel/0.1/base-carousel.js
- extensions/amp-carousel/0.2/amp-carousel.js
> ♿ 🐛 Show Carousel control button when mouse is detected

- extensions/amp-auto-ads/0.1/alright-network-config.js
- extensions/amp-auto-ads/0.1/attributes.js
- extensions/amp-auto-ads/0.1/test/test-alright-network-config.js
- extensions/amp-auto-ads/0.1/test/test-attributes.js
changed the 'layout' attribute value to 'fluid'.
added 'height' attribute.
> 🐛  Ads was missing 'height' attribute

- extensions/amp-list/0.1/amp-list.js
- extensions/amp-list/0.1/test/test-amp-list.js
The infinitely scroll behavior try to load more content when the bottom of the list is 3 viewport height away. if one scroll pass the list we should stop loading more content to save resources. 
Test is unrelated to the change. But it's a fix.
> 🚀 Improve amp-list loadMore behavior

- extensions/amp-consent/0.1/consent-ui.js
- extensions/amp-consent/0.1/test/test-consent-ui.js
Closes #30736
With the introduction of the modal UI for amp-consent, we should focus on it once loads. Additionally we do not have to show the SR button in this case, that would allow the user to focus on the dialog.
> ♿ Focus on consent modal immediately (and don't show SR button)

- build-system/compile/sources.js
Could not compile without changes to `sources.js`
> 🐛 Fix broken Exp B (story ad inabox)

- contributing/contributing-code.md
Updates the CLA documentation to point to the OpenJSF CLA instead of the Google CLA (following up on https://github.com/ampproject/meta/issues/60).
/cc @tobie
> Update CLA documentation

- extensions/amp-list/0.1/amp-list.js
**summary**
Addresses: https://github.com/ampproject/amphtml/issues/30261#issuecomment-696982168.
Adds a warning when single-item is used in conjunction with an Array Response. Ideally the developer should remove the `single-item` attribute. I'm unsure how wordy to make the warning. Should I also include instructions to remove the attribute?
> amp-list: single-item a11y warning.

- 3p/ampcontext.js
- ads/README.md
- ads/_ping_.js
- extensions/amp-ad/0.1/amp-ad-3p-impl.js
- extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
Closes #30786
Expose consentMetadata collected from amp-consent to 3p ad iframes through `window.context` as we already expose `consentString`, `consentState`, and `sharedData` in this way.
> Expose consentMetadata to 3p ad iframes

- extensions/amp-3q-player/0.1/amp-3q-player.js
- extensions/amp-brightcove/0.1/amp-brightcove.js
- extensions/amp-dailymotion/0.1/amp-dailymotion.js
- extensions/amp-ima-video/0.1/amp-ima-video.js
- extensions/amp-mowplayer/0.1/amp-mowplayer.js
- extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js
- extensions/amp-ooyala-player/0.1/amp-ooyala-player.js
- extensions/amp-ooyala-player/0.1/test/test-amp-ooyala.js
- extensions/amp-powr-player/0.1/amp-powr-player.js
- extensions/amp-video/0.1/amp-video.js
- extensions/amp-wistia-player/0.1/amp-wistia-player.js
- extensions/amp-youtube/0.1/amp-youtube.js
- extensions/amp-youtube/0.1/test/test-amp-youtube.js
- src/service/video-manager-impl.js
- src/viewport-observer.js
- test/integration/test-video-manager.js
- test/integration/test-video-players-helper.js
- testing/fake-dom.js
**summary**
Supersedes https://github.com/ampproject/amphtml/pull/30619. A more aggressive take on the same idea.
Partial for: https://github.com/ampproject/amphtml/issues/30620.
Fixes https://github.com/ampproject/amphtml/issues/30818
~Blocked by https://github.com/ampproject/amphtml/pull/30761~
TODO:
> AMP Video Players: use IntersectionObserver instead of viewportCallback + scroll detection.

- extensions/amp-3d-gltf/0.1/amp-3d-gltf.js
- extensions/amp-ad/0.1/amp-ad-3p-impl.js
- extensions/amp-beopinion/0.1/amp-beopinion.js
- extensions/amp-bodymovin-animation/0.1/amp-bodymovin-animation.js
- extensions/amp-embedly-card/0.1/amp-embedly-card-impl.js
- extensions/amp-facebook-comments/0.1/amp-facebook-comments.js
- extensions/amp-facebook-like/0.1/amp-facebook-like.js
- extensions/amp-facebook-page/0.1/amp-facebook-page.js
- extensions/amp-facebook/0.1/amp-facebook.js
- extensions/amp-gist/0.1/amp-gist.js
- extensions/amp-ima-video/0.1/amp-ima-video.js
- extensions/amp-mathml/0.1/amp-mathml.js
- extensions/amp-reddit/0.1/amp-reddit.js
- extensions/amp-twitter/0.1/amp-twitter.js
- extensions/amp-viqeo-player/0.1/amp-viqeo-player.js
- extensions/amp-yotpo/0.1/amp-yotpo.js
- extensions/amp-youtube/0.1/amp-youtube.js
Added basic titles to internal iframes of AMP components. Fixing: https://github.com/ampproject/amphtml/issues/29874
One side-note: I wanted to know if these titles should be more detailed/specific to the component they're representing (like should the `amp-youtube` iframe `title` have a video-id in it for differentiation?). I shied away from this because I'm thinking this would create an ugly experience for screen readers, so a basic descriptive title is better.
> ♿ Added titles to internal iframes of AMP components

- src/preact/base-element.js
Made some small performance improvements to Preact base-element attribute prefixes. Noted by Justin here: https://github.com/ampproject/amphtml/pull/30639
> 🚀 Small performance improvements to Preact base-element attribute prefixes

- src/base-element.js
- src/custom-element.js
- src/inabox/inabox-mutator.js
- src/service/mutator-impl.js
**summary**
Removes `expandedCallback()`. Doesn't look like its used anywhere.
> BaseElement: remove expandedCallback

- extensions/amp-base-carousel/1.0/amp-base-carousel.js
- extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
- src/dom.js
- src/preact/base-element.js
- test/unit/preact/test-base-element-mapping.js
- test/unit/test-dom.js
This is somewhat controversial decision, but it also appears to be the best compromise among all other options. See full discussion [here](https://docs.google.com/document/d/1G_WMXyyKGoHHta6iyXr0dF2B-kLGm_cAoArdVcn0VNg/edit#heading=h.t1nypbr9lvgm).
The boolean rules are now as following:
- `<amp-element custom>` -> `true`
- `<amp-element custom="true">` -> `true`
- `<amp-element custom="false">` -> `false`
- `<amp-element custom="(min-width: 360px) true, false">` -> `matchMedia('(min-width:360px)').matches`
- `<amp-element>` -> default value, most commonly `false`.
> Bento: enable boolean-string values

- extensions/amp-accordion/1.0/accordion.js
- extensions/amp-accordion/1.0/accordion.type.js
- extensions/amp-accordion/1.0/amp-accordion.js
- extensions/amp-accordion/1.0/storybook/Basic.amp.js
- extensions/amp-accordion/1.0/storybook/Basic.js
- extensions/amp-accordion/1.0/test/test-accordion.js
- extensions/amp-accordion/1.0/test/test-amp-accordion.js
- src/preact/base-element.js
API Update 10/27
`toggle()` and `expand()` API methods called with no arguments for an accordion that has the attribute `expand-single-section` are special cases and are handled uniquely.  These two actions will not change the behavior of the accordion at all by definition.  These functions do not have a clearly defined behavior for accordions of more than 1 section.  To stay consistent, they will also not have an impact on accordions with 1 section.
****
Initial Description Below (10/20)
There are three API functions for Accordion in Preact mode
1. `toggle(id)` - if called with an `id`, the accordion will check for an Accordion section that has the same `id` and toggle it.  If called without an `id` it will toggle all sections.  Behavior is undefined for toggle all sections when …
> ✨ [bento][amp-accordion] Add Imperative API for amp-accordion with Tests and Storybook

- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js
- extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
- extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
**summary**
Removes `BaseElement.viewportCallback` from a4a, its subclass doubleclick, and Flying Carpet.
Blocked on https://github.com/ampproject/amphtml/pull/30802 & https://github.com/ampproject/amphtml/pull/30647
Partial for https://github.com/ampproject/amphtml/issues/30620
> Remove BaseElement.viewportCallback from ads.

- extensions/amp-3d-gltf/0.1/amp-3d-gltf.js
- extensions/amp-anim/0.1/amp-anim.js
- extensions/amp-apester-media/0.1/amp-apester-media.js
- extensions/amp-carousel/0.1/base-carousel.js
- extensions/amp-carousel/0.1/base-slides.js
- extensions/amp-carousel/0.1/scrollable-carousel.js
- extensions/amp-carousel/0.1/slidescroll.js
- extensions/amp-carousel/0.1/test/test-base-slide.js
- extensions/amp-carousel/0.1/test/test-slidescroll.js
- extensions/amp-delight-player/0.1/amp-delight-player.js
- extensions/amp-image-slider/0.1/amp-image-slider.js
- extensions/amp-playbuzz/0.1/amp-playbuzz.js
- extensions/amp-timeago/0.1/amp-timeago.js
- extensions/amp-timeago/0.1/test/test-amp-timeago.js
- testing/fake-dom.js
**summary**
Partial for #30620
Included components:
1. 3d-gltf
1. amp-anim
1. apester-media
1. base-carousel 0.1: base-carousel, base-slides, slidescroll, scrollable-carousel.
1. delight-player
1. img-slider 
1. playbuzz
1. timeago
Notes:
- For apester-media, I removed all custom placeholder logic. I couldn't figure out why it existed.
> Remove viewportCallback from the rest of non-ads related components.

- extensions/amp-3d-gltf/amp-3d-gltf.md
- extensions/amp-ad/amp-ad.md
- extensions/amp-beopinion/amp-beopinion.md
- extensions/amp-bodymovin-animation/amp-bodymovin-animation.md
- extensions/amp-embedly-card/amp-embedly-card.md
- extensions/amp-facebook-comments/amp-facebook-comments.md
- extensions/amp-facebook-like/amp-facebook-like.md
- extensions/amp-facebook-page/amp-facebook-page.md
- extensions/amp-facebook/amp-facebook.md
- extensions/amp-gist/amp-gist.md
- extensions/amp-ima-video/amp-ima-video.md
- extensions/amp-mathml/amp-mathml.md
- extensions/amp-reddit/amp-reddit.md
- extensions/amp-twitter/amp-twitter.md
- extensions/amp-viqeo-player/amp-viqeo-player.md
- extensions/amp-yotpo/amp-yotpo.md
- extensions/amp-youtube/0.1/amp-youtube.js
- extensions/amp-youtube/amp-youtube.md
This is the documentation addition to https://github.com/ampproject/amphtml/pull/30834.
It also contains a small fix to `amp-youtube`'s titling, as previously the title propagation was missed for it.
> 📖 Added title attribute to documentation pages + small amp-youtube fix

- test/integration/test-amp-carousel.js
Addresses https://github.com/ampproject/amphtml/issues/29783
@krdwan: I gave this a go. Noticed that the code was currently only waiting for `buildCallback` instead of `layoutCallback`, which could be a cause for flakes.
> amp-carousel integ test: wait for layout instead of build

- examples/amp-consent/cmp-vendors.amp.html
- extensions/amp-consent/0.1/cmps.js
- extensions/amp-consent/amp-consent.md
- extensions/amp-consent/cmps/quantcast.md
Adding Quantcast to the list of registered CMPs.
Added:
- Quantcast CMP config
- Example on cmp-vendors page
- Example documentation.
[Quantcast Choice](https://www.quantcast.com/gdpr/consent-management-solution/) is a consent management provider (CMP) solution built on and registered with the IAB Europe Transparency and Consent framework. 
Additional context
We would like to register Quantcast Choice as a Supported Consent Management Platform for visibility and ease of implementation. 
Context: https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/integrating-consent.md
cc @ampproject/wg-monetization
> ✨  Add Quantcast type for amp-consent

- .gitignore
- build-system/pr-check/dist-bundle-size.js
- build-system/tasks/storybook/amp-env/main.js
- build-system/tasks/storybook/index.js
- build-system/tasks/storybook/preact-env/main.js
- extensions/amp-video/1.0/video-wrapper.js
Publish a [static Storybook](https://storybook.js.org/docs/react/workflows/publish-storybook) alongside public directories consumed by the PR deploy bot. This allows reviewers to live-test Bento/Preact components as we go along.
1) Provides `gulp storybook --build`.
(This only works for `preact` mode for now.)
2) Runs Storybook build task as part of CI.
By putting the generated files inside `examples/`, the deploy bot already [picks them up.](https://storage.googleapis.com/amp-test-website-1/amp_dist_82967/examples/storybook/preact/index.html)
(This takes [about one minute on Travis.](https://travis-ci.com/github/ampproject/amphtml/jobs/422916229#L850))
3) Add support for `amp` mode by referencing the same binaries as created with `gulp dist`.
`@ampproject/storybook-addon` needs to take a …
> 🏗 Build static Storybook on PR deploy

- src/service/resource.js
- src/service/resources-impl.js
- src/web-worker/amp-worker.js
- test/unit/test-resources.js
**summary**
Context: `b/170538870`, `b/169596105`, and maybe but unlikely this one as well `b/150231440`.
If the viewport size changes after an InOb premeasurement, then we need to invalidate the premeasurement as a viewport size change is likely to change the size of elements. This is especially true for elements that expand to the space given (e.g. fixed in only one dimension, or layout=container).
---
_bigger picture_: I didn't do an exhaustive check of whether there are more events which should invalidate a premeasure. two ways we could design the architecture to be more resilient are:
1. don't have a delay between when measurement is taken and applied. this is done today so that the diff between experiement on and off is reduced. after removing the experiment we can work to remove …
> resources: relayoutAll should invalidate premeasurements

- extensions/amp-analytics/0.1/default-config.js
🐛 Bug fix
`${pageViewId64}` should be a default variable for `PAGE_VIEW_ID_64`, as per the docs:
https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#page-view-id-64
In November 2019, adding this to the default variables was mentioned by @lannka: https://github.com/ampproject/amphtml/issues/25794#issuecomment-559280932
> Match docs for pageViewId64

- build-system/compile/bundles.config.js
This was omitted in the original PR.
cc/ @danielstockton @ampproject/wg-monetization
> 🏗 Add nws ad extension to build

- extensions/amp-base-carousel/0.1/carousel.js
- extensions/amp-base-carousel/0.1/test-e2e/test-advance.js
- extensions/amp-base-carousel/0.1/test/test-carousel.js
- test/manual/amp-base-carousel/advance.amp.html
Closes #30905
When the viewport is barely bigger than the carousel (on the scrolling axis), the scroll listener will not receive the final event that would set `currentElementOffset_` and `currentIndex_` to `0` and `n+1` (instead it would be set at something like `-0.998`, `n`). 
Then, when `resetScrollReferencePoint_()` is finally called, it will update `currentIndex_` to the correct value, but leave `currentElementOffset_` to be referencing the old index value.
https://github.com/ampproject/amphtml/blob/f479ea6d8e7ce704ac59aca8b08bd25e978fcc7f/extensions/amp-base-carousel/0.1/carousel.js#L1182-L1187
Then finally, when `restoreScrollStart_()` is called, `deltaOffset` will not be 0, due to `actualOffset` and `currentElementOffset_` referencing 2 different elements (causing another shift …
> 🐛 amp-base-carousel: Update offset and index together

- extensions/amp-story/1.0/amp-story.js
> The code tries to access the ampdoc before it's available and everything fails. This is caused by the service getters in amp-story.constructor() that use this.element as a parameter. The ones using this.win are fine.
These service getters need to be moved to amp-story.buildCallback().
https://github.com/ampproject/amphtml/issues/30798#issuecomment-721332274
context / fixes #30798
> 🐛 Move ampDoc references into amp-story buildCallback

- contributing/building-an-amp-extension.md
Two options:
1. delete
2. change to indicate folks may consider adding examples to amp.dev
Sound off in the comments below.
> docs: 📖 remove amp by example, since it deprecated/dead.

- extensions/amp-o2-player/0.1/amp-o2-player.js
- extensions/amp-o2-player/0.1/test/test-amp-o2-player.js
- extensions/amp-o2-player/amp-o2-player.md
this is a copy of pr #30858, travis is stuck in that pr.
It is impact on business a lot.
@estherkim  HI! this is a copy.
> ✨amp-o2-player add handling consent data

- build-system/tasks/pr-deploy-bot-utils.js
- build-system/tasks/storybook/index.js
- build-system/tasks/storybook/package-lock.json
- build-system/tasks/storybook/package.json
Enables [`examples/storybook/amp`](https://storage.googleapis.com/amp-test-website-1/amp_dist_83181/examples/storybook/amp/index.html?path=/story/amp-video-1-0--default) on PR build deploys.
Slightly awkward that the binary source for the PR's build has to be picked manually. The Storybook addon could default to the custom URL instead.
> 🏗 Enable AMP Storybook on PR deploys

- extensions/amp-story/1.0/test/test-amp-story-viewer-messaging-handler.js
- extensions/amp-story/1.0/test/test-variable-service.js
- extensions/amp-story/1.0/variable-service.js
Resolving open issue: #30821
`storyProgress` is currently calculated with `currentPageIndex / totalPages`, but in order for completed stories to correctly record a value of 1, `storyProgress` should be calculated with `currentPageIndex / (totalPages - 1)`.
> 🐛 Fixing storyProgress calculation so that values are [0,1]

- css/video-autoplay.css
- src/service/video/autoplay.js
1. The iOS issue no longer applies to our support matrix.
2. Even if it did, after the `IntersectionObserver` change, videos playing while visible to 0% so we rarely see this state.
> 🚮 Remove iOS specific unpausable workaround

- extensions/amp-autocomplete/0.1/amp-autocomplete.js
- extensions/amp-lightbox/0.1/test-e2e/test-amp-lightbox.js
- test/fixtures/e2e/amp-lightbox/amp-lightbox.html
Reverts ampproject/amphtml#30901
This fails on an experiment branch when merged into master.
Logs here: https://travis-ci.com/github/ampproject/amphtml/builds/198282104
@dmanek  - Can you please take a look?
cc: @estherkim
> Revert "🐛[amp-autocomplete] Move event listeners to buildCallback from layoutCallback"

- extensions/amp-video/validator-amp-video.protoascii
When adding a portrait video to a [blog post](https://blog.amp.dev/2020/05/12/infinite-recommendations-with-a-new-and-improved-amp-next-page/) on the AMP blog, it ended up rendering poorly as it showed up exceedingly large in relation to the text:
> ![image](https://user-images.githubusercontent.com/134745/81733658-3b7f2a80-9447-11ea-8f68-55d07270b5cc.png)
This is because WordPress is adding the `amp-video` with the `layout=responsive`. This was undesirable. What was actually wanted was the video to have an `intrinsic` layout so it will show with its natural dimensions but then shrink to fit its container on smaller viewports:
> ![image](https://user-images.githubusercontent.com/134745/81733759-5d78ad00-9447-11ea-96d4-6924c1be6a7d.png)
Nevertheless, the intrinsic layout is not valid AMP. …
> ✨ amp-video: Add intrinsic to supported_layouts

- extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.css
On iOS the quiz options would overshoot the border-radius property beyond 1/2 of the height of the actual option div, which glitches the shadow renderer and doesn't show the borders on the corners. Does not happen consistently across devices, but is consistent on a single device and story. With this change, the border-radius will be slightly smaller than the height and will not overshoot, therefore fixing the bug.
Tested on iOS with web inspector and was able to fix bug with this change.
Height of options div is 3.3em, so half of it is 1.65ems. Had to set border-radius to 1.649 to get rid of this error.
Example of overshooted borders not rendering properly the inset box-shadow:
Fixes #30788
> 🐛 Overshooting the borders in interactive-quiz made them disappear on iOS

- examples/amp-consent/amp-consent-geo.html
- examples/amp-consent/diy-consent.html
- extensions/amp-analytics/0.1/default-config.js
- extensions/amp-analytics/0.1/test/test-variables.js
- extensions/amp-analytics/0.1/test/test-vendors.js
- extensions/amp-analytics/0.1/variables.js
- extensions/amp-consent/customizing-extension-behaviors-on-consent.md
- src/consent.js
Closes #30979
- Added CONSENT_STRING macro (also accessible via ${consentString}) as a variable substitution within amp-analytics
- A little clean up on `examples/amp-consent/amp-consent-geo.html` and `examples/amp-consent/diy-consent.html` (for manual testing)
- Tests and documentation
- policyId will be set to default just like in CONSENT_STATE macro
> ✨ CONSENT_STRING macro available through in amp-analytics

- extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.css
Numbers and percentages could get split into separate lines if the option text has 2 lines on a quiz.
Uses `flex-shring` to enforce the percentage will take as much space as needed.
> 🐛 [Story Interactive] Two lines on quizzes sometimes make percentages wrap

- extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js
**summary**
We'd like to remove current `isInViewport` knowledge from Runtime. One of the last holdouts is lightbox-gallery and this check for whether or not an elem is worth animating out.
How important is this optimization. Is it okay to just drop it?
Partial for: https://github.com/ampproject/amphtml/issues/30620
> lightbox-gallery: remove viewport check

- extensions/amp-ad/0.1/amp-ad.js
@rcebulko We want to do this to see ad network's actual traffic share. It is a one-time thing so we can prioritize on amp-ad revamp. We will remove after use. Do you have concerns from infra standpoint?
> Get statistics about ad network traffic

- extensions/amp-story/1.0/test/test-variable-service.js
- extensions/amp-story/1.0/variable-service.js
Due to recent change, `pageIndex / (numberOfPages - 1)` ( #30821) could have had a divide by 0 error when a story has 1 page. Adding a check for that specific edge case.
> 🐛  fixing storyProgress for case when a story only has 1 page

- extensions/amp-a4a/0.1/amp-a4a.js
- extensions/amp-a4a/0.1/test/test-amp-a4a.js
- src/service/real-time-config/real-time-config-impl.js
- test/unit/test-real-time-config.js
In order for real time config to be shared between A4A and ima-video, we must stop letting it depend on `AmpA4A` element. This PR removes A4A completely from real time config manager.
https://github.com/ampproject/amphtml/issues/20259
> ♻️ Refactor: remove a4a dependency from real time config manager

- extensions/amp-a4a/0.1/secure-frame.js
Tests didn't catch this because they are protected by RTV exp. 🤦‍♂️
> 🐛 Fix allow-script in no signing

- build-system/tasks/presubmit-checks.js
- extensions/amp-accordion/1.0/accordion.js
- extensions/amp-accordion/1.0/accordion.type.js
- extensions/amp-accordion/1.0/amp-accordion.js
- extensions/amp-accordion/1.0/storybook/Basic.amp.js
- extensions/amp-accordion/1.0/storybook/Basic.js
- extensions/amp-accordion/1.0/test/test-accordion.js
- extensions/amp-accordion/1.0/test/test-amp-accordion.js
2nd POC of triggering events in bento accordion
`amp-accordion` will fire an `expand` and `collapse` event on each of these respective actions.
The `preact` version of the component is expanded to take in props for `onExpandStateChange` so the user can specify and specific type of action to be used here.
> ✨ [bento][amp-accordion] Fire events on amp-accordion expand and collapse (2nd version)

- build-system/compile/typescript.js
- build-system/tasks/helpers.js
There's a circular dependency bug in `build-system` where `helpers.js` and `typescript.js` depend on each other for `endBuildStep()` and `transpileTs()`. This is currently benign because we don't actually invoke `transpileTs()` during builds. With node v14, there's a new warning for circular dependencies:
This PR eliminates the bug by moving the call to `endBuildStep()` from `transpileTs()` in `typescript.js` to `compileTs()` in `helpers.js`.
> 🏗 Remove circular dependency between `helpers.js` and `typescript.js`

- extensions/amp-accordion/0.1/amp-accordion.js
- extensions/amp-accordion/0.1/test/test-amp-accordion.js
This PR removes `getMode().test` as away to enable display locking in amp-accordion.
More context: 
The amp-accordion visual tests [fail on Percy](https://percy.io/ampproject/amphtml/builds/7653685?utm_campaign=ampproject&utm_content=amphtml&utm_source=github_status_public) when the `i-amphtml-display-locking` class is attached. This is attached 10% of the time because the experiment is currently at 10%.
The test fails when the class is attached because the experiment is gated on _either_ the availability of `onbeforematch` _or_ the AMP mode being in a testing environment. Given visual tests are run in the testing environment (`gulp dist --fortesting`), the `i-amphtml-display-locking` class is attached in all cases where the experiment is on. In actuality we want our visual diff tests to …
> Deflake amp-accordion visual tests

- build-system/global-configs/canary-config.json
Turn on `amp-backup-cid` experiment (#30375) in canary.
To be merged after Wednesday, after the release freeze ends.
Turn on in prod the following week.
> Turn on amp-backup-cid experiment in canary

- extensions/amp-video/1.0/autoplay.jss.js
After switching to `<button>` on #31008, the autoplay mask on videos (Bento) wasn't clickable (per lack of `.i-amphtml-fill-content`)
> 🐛 Allow mask to cover video (Bento)

- build-system/pr-check/module-build.js
- test/integration/test-amp-carousel.js
module-build must build and upload the `dist` build for module if integration tests are modified
The condition list found in `pr-check/module-build.js` must eventually match the same buildTargets check ound in pr-check/nomodule-build.js as we turn on the systems that run against the module build. (ex. visual diffs, e2e, etc.).
unblocks #31029
> build and upload module build if integration tests are modified

- extensions/amp-base-carousel/0.1/carousel.js
- extensions/amp-carousel/0.2/test/test-type-slides.js
Closes #28921
`amp-carousel-0.2` wraps its slides with wrapper `<div>s`, so that it can style/label the wrapper and not the actual content.  
The problem occurs when we loop and create "spacer" slides to help with looping (and autoplay). The spacers and the wrappers are always styled with `scroll-snap-align: this.alignment_`, but the actual content children of the wrappers do not get this style.
B/c the wrapper essentially isn't anything, this messes with `scroll-snap-align` causing the animation to break when you drag.
The fix is to actually apply the `scroll-snap-align`  style to the child content and not the wrapper (if it exists, and it only exists in amp-carousel-0.2).
> amp-carousel-0.2 Fix scroll-snap-align for wrapper slides

- extensions/amp-accordion/1.0/accordion.js
- extensions/amp-accordion/1.0/accordion.type.js
- extensions/amp-accordion/1.0/amp-accordion.js
- extensions/amp-accordion/1.0/storybook/Basic.js
- extensions/amp-accordion/1.0/test/test-accordion.js
**First pass rough draft** - will flesh out after initial review, and more changes incoming after merging https://github.com/ampproject/amphtml/pull/30976
Restructuring to approach 3 in this doc (titled: `Special-purpose subcomponents for header and content.`): 
https://docs.google.com/document/d/1L5jG0Z81BX-ESs003qvFFVYSEWFZYIgKYrxfKrvXB8U/edit#
Updated one storybook example to show how the things would change on Preact side from user's perspective (no changes on amp-side): https://github.com/ampproject/amphtml/pull/31083/files#diff-ee23fff81349bbe0e67b47387d4bf79e1fbdd4f7f3fa66c8eeb52a800b683462R86
Essentially something like this:
```
<Accordion>
<AccordionSection>
<AccordionSectionHeader>Header 1</AccordionSectionHeader>
<AccordionSectionContent>Content in section …
```
> ✨ [bento][amp-accordion] Restructure section, header, and content components

- extensions/amp-story-360/0.1/amp-story-360.js
Check active page before play or pause.
fixes #31121
This might fix or contribute to #31062 since that is related to animating inactive pages.
> 🐛 Check active page before pausing or playing 360 element

- build-system/tasks/visual-diff/index.js
- build-system/tasks/visual-diff/snippets/iframe-wrapper.js
Visual diffs tend to flake from loader animation being captured at slightly different points:
These diffs are meaningless, so we disable the loader animation.
This change changes every visual diff that includes a loader, as intended.
> ✅ Disable loader animation on visual tests

- src/service/real-time-config/callout-vendors.js
We want to try using an IAB CMP for GDPR consent, which means we need to pass GDPR consent to our AdServer.
> ✨ Add GDPR consent string to Future PLC vendor

- extensions/amp-auto-ads/0.1/firstimpression.io-network-config.js
A few additional parameters that can be passed as both hash parameters or query parameters to debug FirstImpresion.io setup of `amp-auto-ads`
> amp-auto-ads: FirstImpression.io additional debug parameters

- src/amp-story-player/amp-story-player-impl.js
With the new Story Player methods to programmatically add Stories, or fetch them from a backend on initial load, we don't need to throw an error if no Stories were configured.
> [Story Player] Allow no initial stories

- extensions/amp-date-countdown/0.1/amp-date-countdown.js
- extensions/amp-date-countdown/0.1/test/test-amp-date-countdown.js
- extensions/amp-date-countdown/0.1/test/validator-amp-date-countdown.html
- extensions/amp-date-countdown/0.1/test/validator-amp-date-countdown.out
- extensions/amp-date-countdown/amp-date-countdown.md
- extensions/amp-date-countdown/validator-amp-date-countdown.protoascii
Address this feature request: https://github.com/ampproject/amphtml/issues/30197
Add a new feature that allows the user to specify an attribute `count-up` which makes it so that the `amp-date-countdown` component counts upward instead.  This is useful when the user wants to display how much time has elapsed since the target time.  This is a feature request from a user.
> ✨ [amp-date-countdown] Add count-up feature in amp-date-countdown component

- extensions/amp-base-carousel/0.1/carousel.js
- extensions/amp-base-carousel/0.1/test/test-carousel.js
Closes: #31054
Unskips: #30563 (related to larger #30661)
Root cause is that [scrollLeft](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft) accounts for RTL; it is negative when scrolling left in RTL and positive when scrolling right in LTR.
Made appropriate changes to our `isScrollAtRightEdge ` and `isScrollAtLeftEdge ` methods.
Edit: This fix only applies to `amp-carousel-0.2` since `amp-carousel-0.1` does not support `dir=rtl` (confirmed with @nainar).
> 🐛 amp-carousel: Fix edge calculations for RTL

- build-system/tasks/update-packages.js
- package-lock.json
- package.json
Update to release [2.6.6](https://github.com/jakubroztocil/rrule/releases/tag/v2.6.6) which contains our luxon fix.
Note: I don't expect this to solve https://github.com/ampproject/amphtml/pull/31072
> rrule: update to latest + remove hack

- build-system/compile/sources.js
- build-system/tasks/update-packages.js
- extensions/amp-date-picker/0.1/dates-list.js
- extensions/amp-date-picker/0.1/test/test-dates-list.js
Our current usage of the `RRule` library in `amp-date-picker` is via the ES5 minified module. This usage breaks our ESM build with the latest version of Closure compiler, which introduces a new warning about  block-scoped function declarations. See https://github.com/ampproject/amphtml/pull/31072#issuecomment-725014116 for full details.
This PR does two things:
1. Switches to the unminified version of the self-contained RRule library (`node_modules/rrule/dist/es5/rrule.js`) as listed at https://www.npmjs.com/package/rrule#client-side. As a result, we minify the code using Closure instead of relying on a previously minified library.
2. Deletes `node_modules/rrule/dist/es5/rrule.js.map` during compilation as a workaround until https://github.com/google/closure-compiler/issues/3720 is fixed. …
> 🏗  Fix RRule usage so it works with module build

- extensions/amp-jwplayer/0.1/test/validator-amp-jwplayer.html
- extensions/amp-jwplayer/0.1/test/validator-amp-jwplayer.out
- extensions/amp-jwplayer/amp-jwplayer.md
- extensions/amp-jwplayer/validator-amp-jwplayer.protoascii
This PR updates the spec file for `amp-jwplayer` to allow `outstream` as a valid data-media-id in addition to the existing regex rule.
> Update amp-jwplayer validator

- extensions/amp-ad/0.1/amp-ad.js
In unit tests, it causes a few `unexpected console error` errors. Since this is a temporary log, fixing it this way is preferable to fixing the tests, in which we have to revert after this logging finishes.
> Do not emit ad log console errors for test

- extensions/amp-story-auto-ads/0.1/story-ad-ui.js
- extensions/amp-story-auto-ads/0.1/test/test-story-ad-ui.js
- src/inabox/inabox-story-ad.js
We should not throw an error in normal inabox rendering. This does not affect the ad, but pollutes logs.
cc/ @jeffkaufman
> 🐛 Remove story error pollution from inabox.

- extensions/amp-accordion/1.0/accordion.js
- extensions/amp-accordion/1.0/accordion.type.js
- extensions/amp-accordion/1.0/amp-accordion.js
- extensions/amp-accordion/1.0/test/test-accordion.js
- extensions/amp-accordion/1.0/test/test-amp-accordion.js
Bento Accordion Tracker: https://github.com/ampproject/amphtml/issues/30445
This PR does the following
1. Adds functionality so that an `id` on an existing `header` or `content` section (in either `bento` or `amp`) will not be overwritten by the components internal logic for assigning `ids`
2. Ensures `id` on header is matched with `aria-labelledby` on `content` which fixes https://github.com/ampproject/amphtml/issues/31137
3. Ensures `role` and `aria-labelledby` attributes are on the `content` and `id` is on the `header`
4. Default element tag for `header` updated from `header` to `div`.  This addresses an a11y issue in `storybook` which does not allow for `role="button"` on the `header` tag.
> ✨ [bento][amp-accordion] Prevent overwrite of existing ids on content and header and add a11y attributes

- extensions/amp-base-carousel/1.0/amp-base-carousel.js
- extensions/amp-base-carousel/1.0/base-carousel.js
- extensions/amp-base-carousel/1.0/base-carousel.type.js
- extensions/amp-base-carousel/1.0/scroller.js
- extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
- extensions/amp-base-carousel/1.0/storybook/Basic.js
- extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
- extensions/amp-base-carousel/1.0/test/test-base-carousel.js
Partial for #28282. This PR introduces `snap-by` to `amp-base-carousel` and `snapBy` to `BaseCarousel`.
- `snap-by`: A number, defaults to `1`. This determines the granularity of snapping and is useful when using `visible-count`.
> ✨  Bento Carousel: `snapBy` feature

- src/service/resource.js
- src/service/resources-impl.js
- test/unit/test-resources.js
**summary**
context: `b/173209780`
Followup to https://github.com/ampproject/amphtml/pull/30937.
I believe there was an accidental usage of `this.relayoutAll_` instead of `relayoutAll`. Especially considering the ivar will always be false. This essentially means that even though _everything_ was supposed to be remeasured, many things ended up ignored.
Note: I also added a `requestMeasure()` to invalidatePremeasurement as a safeguard. At the moment it won't change behavior. But if we were to start calling invalidatePremeasurement in a new location instead of just during a relayoutAll, then this could cause bugs if we don't also force remeasurement.
> resources: incorrect var name

- extensions/amp-story-interactive/validator-amp-story-interactive.protoascii
While importing the validator spec into the AMP-WP plugin (https://github.com/ampproject/amp-wp/pull/5608), I noticed a but with the regex for the `option-*-results-threshold` attributes on the `amp-story-interactive-results` component. Namely, if you provide a decimal value, ten it is flagged as a validation error:
```html
<amp-story-interactive-results
prompt-text="Your level is"
option-1-results-category="Beginner" option-1-image="beginner.png"
option-1-results-threshold="0.5"
option-2-results-category="Expert" option-2-image="expert.png"
option-2-results-threshold="80.5">
</amp-story-interactive-results>
```
If I supply `80.` instead of `80.5` then it passes. Clearly a capture group was intended rather than a character class.
> 🐛 Fix value_regex for decimal option-*-results-threshold attr values

- extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
```
Error: a.h.onResizeSuccess is not a function. (In 'a.h.onResizeSuccess()', 'a.h.onResizeSuccess' is undefined)
at (https://raw.githubusercontent.com/ampproject/amphtml/2010302236002/extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js:461)
```
In some cases, where the baseInstance is an AmpA4A element, they would not have onResizeSuccess function available. Currently, AmpA4A integrations do not support sticky ad type. We are fixing this first and then address the unavailability of sticky ad on AmpA4A next.
> 🐛 Fix onResizeSuccess is undefined issue on ads

- extensions/amp-ad-network-nws-impl/0.1/amp-ad-network-nws-impl.js
- extensions/amp-ad-network-nws-impl/0.1/test/test-nws-a4a-config.js
We need to be able to dynamically insert tracking URLs for analytics.
This PR allows us to do that, by returning the necessary config encoded as json in an X-NWS header in the ad response.
> ✨ Dynamically insert amp-analytics based on ad response headers

- contributing/release-schedule.md
This suggests fixes for small typos in the documentation:
- the change be live &rarr; the change **to** be live
- In the event that &rarr; **If**
- experimantal &rarr; experim**e**ntal
- cache busting &rarr; cache-busting
- users <del>of AMP</del> who opted into the AMP Experimental Channel &rarr; users who opted into the AMP Experimental Channel
- when stability of the codebase &rarr; when **the** stability of the codebase
- _Other missing commas_
cc. @cramforce, @dvoytenko, @jridgewell.
> 📖 Fix release schedule typos

- extensions/amp-selector/1.0/amp-selector.js
- extensions/amp-selector/1.0/selector.js
- extensions/amp-selector/1.0/selector.type.js
- extensions/amp-selector/1.0/storybook/Basic.amp.js
- extensions/amp-selector/1.0/storybook/Basic.js
- extensions/amp-selector/1.0/test/test-selector.js
Partial for #28282. This PR introduces the following changes:
- `keyboard-select-mode` attribute on `amp-selector` with the following possible configurations:
- `none`: `Enter` and `Space` selects an `Option` (Default)
- `focus`: `Enter` and `Space` selects an `Option`, Arrow keys `Left`, `Right`, `Down`, and `Up` navigate focus in DOM order between options, including looping:
- `select`: Arrow keys `Left`, `Right`, `Down`, and `Up` navigate selected state on the target element in DOM order between options, including looping.
- `Enter` and `Space` selects an `Option` in Preact mode, but no `keyboardSelectMode` prop is used as this requires a defined order of option children. Omitting `keyboardSelectMode` should be fine in this layer, as it is primarily a prop for enhanced configuration of …
> ✨ Bento Selector: keyboard-select-mode feature

- examples/amp-story/amp-story-animation.html
- extensions/amp-story/1.0/amp-story-draggable-drawer.js
- src/amp-story-player/amp-story-player-impl.js
- src/amp-story-player/page-scroller.js
Closes #28009
Forwards vertical touch events from the iframe into scroll events for the parent window in order to allow scrolling. 
~Works well except that inertia scrolling doesn't really work since we are setting the scrolling coordinates via JS.~
> [amp-story-player] Forward scrolling touch events to parent window

- build-system/test-configs/dep-check-config.js
- extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
- extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
- src/experiments/intersect-resources-exp.js
- src/service/resources-impl.js
To determine impact of known issue.
cc/ @jeffkaufman
> 🧪Introduce ads experiment for intersect-resources

- contributing/building-an-amp-extension.md
- spec/amp-3p-naming.md
Some of these guidelines have been followed by convention, but never been written down. Hopefully this clears up some confusion.
> 📖 Guidelines for naming third-party components

- extensions/amp-base-carousel/1.0/amp-base-carousel.js
- extensions/amp-base-carousel/1.0/base-carousel.js
- extensions/amp-base-carousel/1.0/base-carousel.type.js
- extensions/amp-base-carousel/1.0/dimensions.js
- extensions/amp-base-carousel/1.0/scroller.js
- extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
- extensions/amp-base-carousel/1.0/storybook/Basic.js
- extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js
- extensions/amp-inline-gallery/1.0/thumbnails.js
- extensions/amp-stream-gallery/1.0/stream-gallery.js
Partial for #28284. This PR introduces the following `snapAlign` feature in various forms to different carousels:
- `snap-align` to `amp-base-carousel` and `snapAlign` to `BaseCarousel`
- Use `snapSlign` in `Thumbnails` (`amp-inline-gallery-thumbnails`)
- `slide-align` to `amp-stream-gallery` and `slideAlign` to `StreamGallery`: Note this is consistent with 0.1 but can be renamed since `StreamGallery` is not yet launched.
`snap-align`: Either `"start"` or `"center"`. When `"start"` aligning, the start of a slide (e.g. the left edge, when horizontal aligning) is aligned with the start of a carousel. When `"center"` aligning, the center of a slide is aligned with the center of a carousel. 
- `"start"` on first render of a looping 8-slide carousel:
- `"center"` on first render of a looping …
> ✨ Bento Carousel: snap-align feature

- extensions/amp-inline-gallery/1.0/amp-inline-gallery-pagination.js
- extensions/amp-inline-gallery/1.0/amp-inline-gallery-thumbnails.js
- extensions/amp-stream-gallery/1.0/amp-stream-gallery.js
Allows `amp-inline-gallery-pagination`, `amp-inline-gallery-thumbnails`, and `amp-stream-gallery` attributes to be responsive.
> Bento: Turn on media attributes for other carousel components

- extensions/amp-story/1.0/page-advancement.js
Fixing bug where `getLayoutBox` was still used in one call for `isInStoryPageSideEdge`. Wrote new function `getStoryPageRect_` that can be used every time this value needs to be calculated.
Fixes #30825
> 🐛 Fixing bug where getLayoutBox was erroneously used in a call for isInStoryPageSideEdge

- extensions/amp-delight-player/0.1/test/test-amp-delight-player.js
I've been seeing [this flake](https://travis-ci.com/github/ampproject/amphtml/jobs/447001971#L2165) a lot lately:
```
DESCRIBE => amp-delight-player
DESCRIBE =>  
IT => renders
✗ Error: Timeout of 4000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
●●
IT => should forward events
✗ Error: Timeout of 4000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
The tests work fine with a locally served blank page, which would prevent this timeout due to lack of response from the external server.
> ✅ Unflake test-amp-delight-player by embedding a blank page

- src/amp-story-player/amp-story-player-impl.js
We should also unregister touch events when recycling iframes, otherwise this causes a weird bug when having more than 3 stories in the player and scrolling vertically on the page (introduced in #31051). 
The bug would duplicate the touch events, causing the scrolling to glitch and (sometimes) get stuck when scrolling on the player.
> 🐛 [amp-story-player] Unregister touch events

- third_party/subscriptions-project/config.js
- third_party/subscriptions-project/swg.js
- Makes init method unblock APIs that don't need a configured runtime (#1366)
- Update dependency rollup to v2.33.3 (#1365)
- Update dependency chromedriver to v87 (#1364)
- Update dependency gzip-size to v6 (#1363)
- Update dependency rollup to v2.33.2 (#1362)
- Regwall: i18n (#1361)
- Adds drop shadow to meter toast iframe on mobile (#1360)
- Updates dependency versions
- Allows for Scroll to close Meter Toast iframe (#1355)
- Update dependency gulp-sourcemaps to v3 (#1359)
- CI: Cleans up references to Travis (#1358)
- CI: Adds CodeCov action (#1357)
- CI: Run on PR events (#1356)
- Update dependency postcss to v8.1.7 (#1353)
- Migrates CI to GitHub Actions (#1354)
- Update dependency autoprefixer to v10.0.2 (#1352)
> 🏗 SwG Release Nov. 19, 2020 (0.1.22.133)

- extensions/amp-carousel/0.2/amp-carousel.css
- extensions/amp-carousel/0.2/test-e2e/helpers.js
- extensions/amp-carousel/0.2/test-e2e/test-responsive-carousel.js
- test/fixtures/e2e/amp-carousel/0.2/responsive.carousel.amp.html
Closes  #31304
Without a set width on the slide element (for `type=carousel`), the spacer (that gets created by runtime for responsive elements) inside the <amp-img> slide will have a height and width set to 0x0. 
When the carousel lays out its children, runtime stops `<amp-img>` layoutCallback() from being called because it has 0 height and width (because spacer is not correctly inflating the element).
The fix is to add `width: 100%` to the slide child. 
Additionally, it doesn't make sense for the carousel to get styled as `position: static`, since the spacer for the carousel (when set to `layout=responsive type=carousel`) will take up the space that the carousel should occupy.
> 🐛 amp-carousel-0.2 Fix width for responsive children and position for responsive carousel

- extensions/amp-accordion/0.1/test/validator-amp-accordion.html
- extensions/amp-accordion/0.1/test/validator-amp-accordion.out
- extensions/amp-accordion/validator-amp-accordion.protoascii
Fixes: https://github.com/ampproject/amphtml/issues/25807
Support feature request in above link.  Allows `access-hide` attribute in `amp-accordion` section so that `amp-access` can be used within an `amp-accordion`.
> ✨ [amp-accordion][amp-access] Allow access-hide attribute in accordion section

- extensions/amp-story/1.0/page-advancement.js
Fixes #31107: tap safety zone should be 12% of page width, with a minimum of 48px.
> 🐛  Tap safety zone should be 12% of page width, with a minimum of 48px.

- src/viewport-observer.js
- test/unit/test-viewport-observer.js
Should fix https://github.com/ampproject/error-reporting/issues/27
> viewportObserver: Fix case of quick observe and unobserve that both occur before the io callback

- examples/amp-list.amp.html
- examples/list.example.json
- extensions/amp-mustache/0.2/test/test-amp-mustache.js
- extensions/amp-mustache/amp-mustache.md
- src/purifier/sanitation.js
- test/unit/test-purifier.js
♻️ Allowlist `<amp-img>`, `<h1>`, `<h2>`, and `<h3>` as unescaped HTML with `{{{` amp-mustache.
- Add tags to sanitization.js within `TRIPLE_MUSTACHE_ALLOWLISTED_TAGS`.
- Create an example within `amp-list.amp.html` containing a string of unescaped HTML.
- Add test case expecting tags to be present in rendered template.
Resolves #27344
> ♻️ Allowlist <amp-img>, <h1>, <h2>, and <h3> as unescaped HTML within amp-mustache

- ads/ads.extern.js
- ads/google/imaVideo.js
- extensions/amp-ima-video/0.1/test/test-amp-ima-video.js
Closes #31125
Currently it seems that the ad clicks are handled by the actual IMA video SDK, i.e. when the video ad is clicked, the SDK handles opening the new window with the click-through link. 
In the original issue, the large play button (with a circle outline) is not created by AMP's `imaVideo.js` ad integration, but rather the SDK. The problem was the the SDK was pausing and showing the large play button but we weren't listening for the [`AdEvent.PAUSED`](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdEvent) signal (and adjusting the smaller play/pause button). 
Fix is to listen for these signals and then adjust the play-pause button accordingly.
> Listen for PAUSED and RESUMES Ad Event signals in imaVideo integration
