extensions/amp-accordion/1.0/accordion.js
extensions/amp-accordion/1.0/accordion.jss.js
extensions/amp-accordion/1.0/accordion.type.js
extensions/amp-accordion/1.0/amp-accordion.css
extensions/amp-accordion/1.0/amp-accordion.js
extensions/amp-accordion/1.0/animations.js
extensions/amp-accordion/1.0/storybook/Basic.amp.js
extensions/amp-accordion/1.0/storybook/Basic.js
extensions/amp-accordion/1.0/storybook/Bind.amp.js
extensions/amp-accordion/1.0/storybook/DisplayLocking.amp.js
extensions/amp-accordion/1.0/test/test-accordion.js
extensions/amp-accordion/1.0/test/test-amp-accordion.js

Add new display locking feature to [bento][accordion].  This supports `ctrl + f` finding of content that is in a collapsed accordion section.  If the content is found, the accordion section will expand.
This only works for new Chromium Canary browser.  To check if the browser supports this, type this in the console: `CSS.supports("content-visibility","hidden-matchable")` (must return true)
API -
AMP - The experiment `amp-accordion-display-locking` must be set to `true`
Preact - The top-level Accordion component must have prop `experimentDisplayLocking` set to `true`
(additionally in both cases, the above CSS property must be supported by the browser)
Implemented by including the following CSS properties on a collapsed content section.
```
content-visibility: hidden-matchable !important; …
```

✨ [bento][amp-accordion] Add display-locking feature to bento accordion

---

src/service/resources-impl.js
test/unit/test-resources.js

**summary**
Context: `b/170491750`, `b/173271514`
There is no guarantee as to when an iframes `resize` event occurs. It can (and sometimes does) happen much later than the causally related IntersectionObserver events. This led to a mismatch between the viewport service's size and InOb. Here is an example sequence of events that occurs in the sample document (given an initial iframe height of 1px):
1. Load begins. iframe height=1
2. `documentHeight` message sent to the Viewer which resizes the iframe. height=104.
3. InOb fires its callbacks/measures since the resource now intersects with the viewport.
4. Resource is determined not to be within viewport since viewport service's size hasn't updated yet.
5. `window.resize` event finally fires and updates the viewport service. no pass is …

resources-impl: fix resize event race condition.

---

extensions/amp-subscriptions-google/0.1/test-e2e/test-amp-subscriptions-google.js

This reverts commit b2a2e361c55a003eaa36ca4006ceb67a10f7fae0.
Test was skipped due to flakiness, but the error resurfaced in a completely unrelated test (see #31409 ), indicating the test itself was not the source of flakiness. This PR restores/unskips that test.(

⏪ Revert "Skip amp-subscriptions-google e2e test (#31399)"

---

build-system/tasks/visual-diff/helpers.js
build-system/tasks/visual-diff/index.js
examples/visual-tests/amphtml-ads/static.js
package-lock.json
package.json

**summary**
We have a dependency on [sleep-promise](https://www.npmjs.com/package/sleep-promise). The package provides a very useful utility, but it is also easy to replicate in a single line. There is a cost involved with each dependency we have in our package.json file (repeated downloads, updates, security via malicious uploads to npm, etc.). For a utility this small, I think its better to write it ourself. Also, see [leftpad](https://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm).
```js
// Before
const sleep = require('sleep-promise');
// After
const sleep = (ms) => new Promise((res) => setTimeout(res, ms));
```

dependencies: remove sleep-promise

---

.renovaterc.json
build-system/common/check-package-manager.js
build-system/common/ci.js
build-system/common/ctrlcHandler.js
build-system/common/utils.js
build-system/compile/compile.js
build-system/pr-check/build-targets.js
build-system/tasks/babel-plugin-tests.js
build-system/tasks/check-exact-versions.js
build-system/tasks/check-links.js
build-system/tasks/check-owners.js
build-system/tasks/dep-check.js
build-system/tasks/dev-dashboard-tests.js
build-system/tasks/e2e/describes-e2e.js
build-system/tasks/e2e/index.js
build-system/tasks/e2e/mocha-dots-reporter.js
build-system/tasks/extension-helpers.js
build-system/tasks/helpers.js
build-system/tasks/karma.conf.js
build-system/tasks/lint.js
build-system/tasks/performance/measure-documents.js
build-system/tasks/pr-check.js
build-system/tasks/prettify.js
build-system/tasks/runtime-test/helpers-unit.js
build-system/tasks/runtime-test/helpers.js
build-system/tasks/runtime-test/runtime-test-base.js
build-system/tasks/server-tests.js
build-system/tasks/update-packages.js
validator/build.py
validator/js/webui/build.py

This PR updates all spots where the question "is this a Travis build" can be reasonably replaced by "is this a CI build". It does so by adding a new function called `isCiBuild()` to replace `isTravisBuild()`.
As written, this should be a no-op for our CI builds. Other changes to follow in subsequent PRs.
- https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
- https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables
- https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
Partial fix for #31416

🏗♻️ Replace Travis-specific check with a generic CI build check

---

.codecov.yml

We were applying two statuses from Codecov.io for all PRs: project-level and patch-level coverage. The former was meant to be a barometer of overall coverage, but has proved to be noisy and not so useful.
This PR reduces codecov statuses to just patch-level coverage.
Fixes #28212

🏗 Remove project-level code coverage status

---

examples/amp-story/player-local-stories.html
extensions/amp-story/1.0/pagination-buttons.js

On the last page of a desktop mode story, the navigation button should show "next" instead of "rewind", and navigate to the next story.
Fixes #31207

🐛 Desktop navigation button should show "next" on the last page of a story

---

extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js
extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
extensions/amp-ad/0.1/amp-ad-3p-impl.js
extensions/amp-ad/0.1/amp-ad-ui.js
extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
extensions/amp-ad/0.1/amp-ad.css
extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
extensions/amp-ad/0.1/test/test-amp-ad-ui.js
extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js

Refactor: Move sticky ad related features to `amp-ad-ui.js`
This also has the effect of make sticky ad features available on amp-a4a.

♻️ Make sticky ad available on a4a

---

extensions/amp-loader/0.1/amp-loader.css

Today, before sticky ad layouts, the amp-ad loader inside still gets displayed, overlaying on top of content. The reason is because of the following css
```
all: initial;
```
overrides the visibility property. Therefore this PR adds a visibility property to force inherits the visibility property. The rest of the PR is just autoformatting, no real changes.

🖍 Do not show ad loader from not layouted sticky ad

---

extensions/amp-vimeo/0.1/amp-vimeo.js
extensions/amp-vimeo/0.1/test/test-amp-vimeo.js
extensions/amp-vimeo/amp-vimeo.md

Adding an optional 'do-not-track' attribute to AmpVimeo component that causes the dnt=1
attribute to be appended to the vimeo player iframe src url.
This will "prevent the player from tracking session data, including cookies"
for details see: https://developer.vimeo.com/api/oembed/videos
Issue:  #31384

✨ Support enabling Vimeo players do-not-track attribute when using AmpVimeo component 

---

build-system/global-configs/canary-config.json
build-system/global-configs/experiments-config.json
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
tools/experiments/experiments-config.js

Start an experiment to measure the impact of ads renderOnIdle feature.

---

build-system/common/ci.js
build-system/common/circleci.js
build-system/common/github-actions.js
build-system/common/travis.js
build-system/pr-check/bundle-size.js
build-system/pr-check/checks.js
build-system/pr-check/e2e-tests.js
build-system/pr-check/esm-tests.js
build-system/pr-check/local-tests.js
build-system/pr-check/module-build.js
build-system/pr-check/nomodule-build.js
build-system/pr-check/unminified-build.js
build-system/pr-check/validator-tests.js
build-system/pr-check/visual-diff-tests.js

This PR updates all spots where the question "is this a Travis PR / push build" can be reasonably replaced by "is this a PR / push build". It does so by adding new service-agnostic functions to `ci.js` along with a service-to-function mapping to determine which service-specific function to call.
This should be a no-op for existing CI builds.
Partial fix for #31416

🏗♻️  Refactor most checks for PR and push builds

---

build-system/tasks/presubmit-checks.js
examples/carousel.amp.html
extensions/amp-carousel/0.1/scrollable-carousel.js
extensions/amp-carousel/0.1/slidescroll.js
extensions/amp-carousel/0.1/test/test-slidescroll.js
extensions/amp-image-slider/0.1/amp-image-slider.js
extensions/amp-viz-vega/0.1/amp-viz-vega.js

Mostly replaced `getLayoutBox/getLayoutWidth` with a direct measurement where the old code is doing additional measurements anyway.

Low-hanging fruit replacements for getLayoutWidth/Box uses and deprecate some measurement APIs

---

src/web-worker/web-worker-polyfills.js

Fixes https://github.com/ampproject/amphtml/issues/31466
TODO

amp-bind: polyfill String.prototype.startsWith for ie11 support.

---

extensions/amp-carousel/0.2/amp-carousel.js
extensions/amp-carousel/0.2/test/test-type-slides.js

Porting the feature from v0.1
Fixes #27082

✨  [amp-carousel] Expose actionTrust property in amp-carousel v2 `slideChange` event

---

build-system/tasks/sweep-experiments/index.js

Missed this earlier when merging #31458.
When an experiment launch is removed from config, it should also be removed from the opt-in lists:
```diff
{
-  "allow-doc-opt-in": ["foo", "removed"],
-  "allow-url-opt-in": ["removed"],
+  "allow-doc-opt-in": ["foo"],
+  "allow-url-opt-in": [],
"foo": 1,
-  "removed": 1,
}
```

🏗 Delete swept experiment from opt-in config

---

build-system/common/ci.js
build-system/common/circleci.js
build-system/common/git.js
build-system/common/github-actions.js
build-system/common/travis.js
build-system/pr-check/utils.js
build-system/tasks/bundle-size/index.js
build-system/tasks/visual-diff/index.js

- Replaces Travis-specific code-paths in `git.js` with service-agnostic equivalents
- Updates call-sites (mostly internal to `git.js`)
- Cleans up unnecessary boilerplate checks in `travis.js` and makes code more readable
Partial fix for #31416

🏗♻️ Make all utilities in `build-system/common/git.js` CI-service-agnostic

---

build-system/tasks/visual-diff/index.js
build-system/tasks/visual-diff/snippets/snapshot-error.html

This PR makes `gulp visual-diff` agnostic of the CI service it's running on. This is currently a no-op and doesn't change where the tests are run (coming up in a future PR).
Partial fix for #31416

🏗♻️ Make visual diff code CI service agnostic

---

examples/amp-story/interactives.html
extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.js
extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.js

Make all the story players sync when you navigate on one of them.
Also: removed duplicate import of extension on demo story, set tabs to container because AMP complains if they don't have a layout type.
Closes #31442

✨  [Story devtools] Sync players on navigation

---

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js

The current logic does not grant access correctly because of the following two issues:
1. `gaa_at` is set to `la` not `laa`
2. The [protocol](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/protocol) of referrer has a trailing `:` which is not currently accounted for.
This change fixes both checks.

🐛 amp-subscriptions-google: Correct LAA logic

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

- Update dependency postcss to v8.2.1 (#1398)
- Update dependency autoprefixer to v10.1.0 (#1396)
- Update dependency postcss to v8.2.0 (#1397)
- Update dependency eslint to v7.15.0 (#1393)
- Update dependency rollup to v2.34.2 (#1394)
- Update dependency chromedriver to v87.0.2 (#1392)
- Update dependency postcss to v8.1.14 (#1391)
- Regwall: Only render if URL has fresh GAA URL params (#1390)
- Update dependency chromedriver to v87.0.1 (#1385)
- Update dependency postcss to v8.1.13 (#1387)
- Update dependency rollup to v2.34.1 (#1388)
- Update dependency eslint-plugin-prettier to v3.2.0 (#1389)

SwG  Release 0.1.22.138

---

src/web-worker/web-worker-polyfills.js

**summary**
Context: https://github.com/ampproject/amphtml/pull/31492#pullrequestreview-547388939
All of these are already excluded from v0, so we should probably do the same for ww.
https://github.com/ampproject/amphtml/blob/0006e2f21f93fdb03a4108b2ccc7a61cc18d173c/src/polyfills.js#L36-L47
**size difference**
```
- dist/ww.js:  Δ -0.01KB
- dist/ww.mjs: Δ -0.32KB
```

Remove polyfills from webworker for esm builds.

---

extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-a4a/0.1/friendly-frame-util.js
src/friendly-iframe-embed.js
src/service.js
src/service/timer-impl.js
src/service/url-replacements-impl.js
src/services.js
test/unit/test-amp-pixel.js
test/unit/test-element-service.js
test/unit/test-friendly-iframe-embed.js
test/unit/test-service.js

Use an embed override for timer service

---

extensions/amp-lightbox/1.0/amp-lightbox.css
extensions/amp-lightbox/1.0/amp-lightbox.js
extensions/amp-lightbox/1.0/lightbox.js
extensions/amp-lightbox/1.0/storybook/Basic.amp.js
extensions/amp-lightbox/1.0/storybook/Basic.js
extensions/amp-lightbox/1.0/test/test-amp-lightbox.js
extensions/amp-lightbox/1.0/test/test-lightbox.js

This PR makes the following changes to `amp-lightbox` and `Lightbox`: 
- remove `initialOpen` from both layers, as a lightbox that is open on page load is an intrusive interstitial
- register `open` as the default AMP action (so users may write `on="tap:my-lightbox"` to mean the equivalent of `on="tap:my-lightbox.open()`)
- make `open` a mutable attribute after component registration
- fix Preact unit tests which were trivially passing and add AMP unit tests
- update storybooks
Subsequent PRs will handle:
- CSS customizability in both layers
- porting e2e tests from 0.1

Bento Lightbox: Various fixes and unit tests

---

extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-animation/0.1/amp-animation.js
src/friendly-iframe-embed.js
test/unit/test-friendly-iframe-embed.js

Tell FIE ampdoc that it is complete only after all elements have been transferred. Tested manually and if I am in no-signing + fie-resources this will solve the malformed json errors. This will probably cost us a bit of speed, but will iterate on fie-resource building logic in follow up. 
Partial #27189

🐛 Properly indicate when FIE is done for no-signing

---

.github/workflows/cross-browser-tests.yml
build-system/common/git.js
build-system/pr-check/cross-browser-tests.js
build-system/tasks/karma.conf.js
build-system/tasks/presubmit-checks.js
build-system/tasks/runtime-test/runtime-test-base.js

- For PR builds, runs tests based on build-targets (e.g. docs changes will no longer compile code / run tests)
- For push builds, continues to run all platform-specific unit / integration tests
- Adds missing `npm` checks and commit log messages
- Updates `fetch-depth` config for repo checkout so `git` operations can be performed (fetch running time is still ~20s)
- Uses `origin/master` instead of `master` in `gitBranchCreationPoint()` so it works across CI services
- Restores `super-dots` reporter on GH actions (used to be broken, fixed by [this](https://github.blog/2020-09-23-a-better-logs-experience-with-github-actions/) update)
- Modifies `runtime-test-base.js` logic to be flag-based instead of CI-based (addresses …

🏗 Optimize cross-browser test runs on GH actions

---

extensions/amp-social-share/1.0/amp-social-share.js
extensions/amp-social-share/1.0/test/test-amp-social-share.js
src/preact/base-element.js

Update amp-social-share to respond to attribute changes for the following attributes:
1. type
2. data-target
3. data-share-endpoint
4. data-param-*
Updates the URL if any of these are changed after initial render (in amp-mode).  If type is changed, updates the CSS class to update the icon colors and also updates the icon image.  If type is changed to something not supported, hide the element.
-------
Added tests for `amp-social-share` (component)

[bento][bug-bash][amp-social-share] Update social share to respond on attribute changes

---

extensions/amp-sidebar/1.0/sidebar.js
extensions/amp-sidebar/1.0/sidebar.jss.js
extensions/amp-sidebar/1.0/sidebar.type.js
extensions/amp-sidebar/1.0/storybook/Basic.js
extensions/amp-sidebar/1.0/test/test-sidebar.js

First draft of Preact amp-sidebar component for initial review
12/11 - Update
1. Added unit tests - 
- imperative API
- click to open, close, toggle
- click mask to close 
- left and right sides
- animations
2. Updated storybook
- removed background content
- add buttons to open, close, toggle to within sidebar
3. Added type definition file

✨ [bento] Preact version of amp-sidebar

---

build-system/tasks/e2e/amp-driver.js
build-system/tasks/e2e/describes-e2e.js
test/e2e/test-amp-email.js
test/fixtures/e2e/amp-viewer-integration/viewer.html
test/fixtures/e2e/amp4email/element-size-race.html
test/fixtures/e2e/amp4email/viewport-size-race.html

There's been a recent [uptick in bugs](https://github.com/ampproject/amphtml/issues/31232#issuecomment-739086372) affecting `amp4email`. This PR introduces two new e2e tests meant to increase our confidence in the stability of our viewer support.
- New e2e test environment named `email-demo`. It simulates gmail viewers by beginning with 0 height and 0 width, and then resizing the iframe based on `documentHeight` events.
- Cleaned up the `viewer.html` fixture by removing unnecessary elements. This is solely meant for automatically running e2e tests, so all the visual aspects were noise.
In general, both added tests help with sanity checking. We don't have great e2e testing for the entire flow involving documentHeight -- and these tests should at least check the basics. On top of that, each …

Create e2e tests for viewers that depend on documentHeight (gmail)

---

extensions/amp-analytics/integrating-analytics.md

Based on 7f6863f394e24031aa60594e480ca13771b6870b, it seems like this was removed. So I removed the lingering references to it elsewhere in the file

remove references to the batch plugin for amp-analytics

---

src/preact/base-element.js
test/unit/preact/test-base-element-mapping.js

A typical symptom:
> Prepending a slide doesn't work. The new and old slides are slotted into the first slide. (#28284)

Fix children ID auto-assignment to avoid duplicates

---

extensions/amp-animation/0.1/amp-animation.js
extensions/amp-animation/0.1/test/test-amp-animation.js

For some components 1-pixel intersections are very common, such as the next slide in the carousel. Thus the minimum threshold is needed to allow animation to play.
The symptom is:
> animations do not pause. note: a different reason than video pausing.

Require a minimal threshold for an animation to play

---

build-system/compile/post-closure-babel.js
build-system/tasks/check-sourcemaps.js
build-system/tasks/extension-helpers.js

In regular builds, the v0.js file starts with:
```js
var global=self;self.AMP=self.AMP||[];try{(function(_){
```
That's it. It's an effectively "empty" line, and we can freely prepend code to this line without effecting our sourcemaps. As long as the prepended code never includes a newline, the sourcemap will fix itself on the next line.
However in ESM builds, we run terser. Terser will concat lines together, making the first line:
```js
var global=self;self.AMP=self.AMP||[];try{(function(t){var e=class{constructor(){this.Ff=new i}abort(){this.Ff.df=!0}get signal(){return this.Ff}};…snip 11kb…
```
When we prepended our config onto this line, we affected the sourcemap for all of the later code on the line! A simple fix is to just force terser to prepend a newline before any code, so we're …

🐛 Fix ESM sourcemaps

---

package-lock.json
package.json
src/polyfills/intersection-observer.js
src/polyfillstub/intersection-observer-stub.js
src/service/resources-impl.js
test/unit/polyfills/test-intersection-observer.js

Modifies the `IntersectionObserverStub` and polyfill installer in order to select the best possible IntersectionObserver on a per-instance basis.
- If `win.IntersectionObserver` is undefined --> immediately install the stub, later upgrade to polyfill.
- If IntersectionObserver is present, but it doesn't support document root --> use a dispatcher that returns a stub/polyfill or native InOb depending on the constructor args
- If IntersectionObserver is present and supports all features: just use native.
**also updates polyfill version + resources-impl integration**

IntersectionObserver Polyfill: per-instance impl selection

---

extensions/amp-story-player/0.1/amp-story-player.js
src/amp-story-player/amp-story-component-manager.js
src/amp-story-player/amp-story-player-impl.js
src/amp-story-player/amp-story-player-viewport-observer.js
test/unit/test-amp-story-player-viewport-observer.js
test/unit/test-amp-story-player.js

Closes #31225
Closes #29798
Closes #31118
New logic:
I. When player is outside of viewport, only prerender first story.
II. Once player is visible, switch first story to visible and start prerendering neighboring stories (if any).
III. Increase distance in IntersectionObserver to 2 viewports away (before 1) so we start prerendering stories earlier.
Open questions / discussion points:
1. Is minimum 2 viewports away far enough for prerendering?
2. ~~Is 30% of player visibility in the viewport enough to set the story as visible?~~
Changed it to make it visible as soon as it hits the viewport, to stick with AMP standards.
3. Alternative strategy ([in first commit](https://github.com/ampproject/amphtml/pull/31305/commits/5483e735ee9099c59cf1cbe6975cf0323047911a)), which I later discarded for …

🚀 Improve player loading strategy

---

extensions/amp-sidebar/0.1/amp-sidebar.js
extensions/amp-sidebar/0.1/amp-sidebar.md
extensions/amp-sidebar/0.1/test/test-amp-sidebar.js

Fixes: https://github.com/ampproject/amphtml/issues/28902
Fixes: https://github.com/ampproject/amphtml/issues/31326
This PR updates Gestures behavior in amp-sidebar with three main changes to address the two bugs above:
1. **Bug Fix** (https://github.com/ampproject/amphtml/issues/28902) - Passive event listeners do not allow prevent.default().  So we have to remove the prevent.default() or have a bunch of console errors when we get the `touchmove` event (from swiping).  This optimization improves performance for `touchmove` events [more info](https://medium.com/@Esakkimuthu/passive-event-listeners-5dbb1b011fb1#:~:text=Passive%20event%20listeners%20are%20an%20emerging%20web%20standard%2C%20new%20feature,touch%20and%20wheel%20event%20listeners.) by improving the default scroll behavior of …

✨ 🐛 [amp-sidebar] Fix gestures in amp-sidebar

---

extensions/amp-social-share/0.1/amp-social-share.js

Chrome appears to use stuff from the Object prototype, which isn't present in the JsonObject returned from `parseQueryString_`. 
Context / Fixes #30302

🐛 Spread data object in navigator.share

---

extensions/amp-story/1.0/amp-story-desktop-panels.css

Scales pixel offset by scale factor.
Context / Fixes #31027
before, after screenshot:

🐛 Align panels desktop pagination panels

---

build-system/tasks/extension-helpers.js

The main intention was to not build the default extensions when using `--core_runtime_only`, but I accidentally prevented you from specifying `--extensions=foo`.
Fixes https://github.com/ampproject/amphtml/pull/31602/files/748f5a1b406a6d0723a09355d8868fc6f4735327#r544582134

🏗🐛 Fix core_runtime_only with extensions build

---

extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.js

Set the answer choices on quizzes to not translate since we want to translate them on our localizedStrings if anything.
Fixes #31610

🐛 [Story interactive] Prevent translations on the ABCD on quizzes

---

src/error.js

Dev expected errors are, well, errors we expect to happen. We use them to track overall metrics of errors (to make sure there's no an unexpected spike, meaning something's gone very wrong). But displaying the errors to publishers isn't helpful, and can lead them to believe they have a bug on their pages.

Hide dev expected errors from console

---

extensions/amp-a4a/0.1/secure-frame.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js

<iframe> sandbox without `allow-scripts` keeps breaking in unpredictable ways. The latest version is that references to functions on iframe window (eg `this.win.setTimeout` or `this.win.clearInterval`) will throw errors. This moves all browsers to use the same setup as safari, relying on csp rather than sandbox.

🐛 Fix script errors in no signing

---

build-system/common/ci.js
build-system/pr-check/cross-browser-tests.js
build-system/tasks/report-test-status.js

- Enables test status reporting across all CI services
- Renames the `travisJobUrl` field to `ciJobUrl` (now that https://github.com/ampproject/amp-github-apps/pull/1139 has been deployed)
- Adds missing subtypes for cross-browser tests
- Replaces the `local` subtype with `minified` or `unminified` (unless a more specific subtype is applicable)
- Simplifies implementation of `inferTestType()`
- Separates `reportAllExpectedTests()` for each CI service
- Extracts `pull_request.head.sha` in `ciPullRequestSha()` for GH Actions
Related to https://github.com/ampproject/amp-github-apps/issues/1111

🏗 Make test status reporting work across CI services

---

build-system/babel-plugins/babel-plugin-transform-json-import/index.js

**summary**
Followup to https://github.com/ampproject/amphtml/pull/31595
Unblocks: https://github.com/ampproject/amphtml/pull/31615/checks?check_run_id=1573479334
The transform was making paths valid only on posix. By changing from `../` --> `..`, and using regular `path` instead of `path.posix`, I was able to make the tests pass on Windows.
Ideally the babel plugin tests would also run on Windows so we'd catch the issue one PR earlier.
cc @rsimha

babel json transform: Windows support.

---

extensions/amp-consent/0.1/amp-consent.css
extensions/amp-consent/0.1/consent-ui.js
extensions/amp-consent/0.1/test/test-consent-ui.js
tools/experiments/experiments-config.js

For #31580 
When served in a google viewer, the viewer has a top bar. When a user scrolls, the bar shows/hides. For elements tracked by the fixed layer (i.e. amp-consent element), when the bar is shown and hidden, the `transform` style applied to the element's style is eliminated. 
Therefore, when a user scrolls on a doc served in a viewer before the consent iframe loads, the transform style will be removed and no transformation will be applied. 
Since fixed layer only removes `transform` style, we can add it to another class (just need to worry about CSS rule precedence).
/cc @jridgewell

[amp-consent] Change `transform` rule to a CSS variable

---

extensions/amp-bind/0.1/bind-impl.js

Follow-up to #26137. Also tracked in `b/159464750#comment12`:
> The fix linked to that issue was necessary but missed an interesting edge case.
> 
> 1. Form valid/invalid events toggle the disabled state of the "Reply" button (via amp-bind)
> 2. With `diffable`, the `<form>` is no longer destroyed and re-rendered so its validation state must be manually reset to avoid staleness problems
> 3. On reply, the form clears the comment `<textarea>` (also via amp-bind) but doesn't reset its validation state
> 4. Bug: the stale validation state causes the "Reply" button to get stuck in the disabled state
> 
> **Original fix:** resolve (3) by adding behavior to make sure we check form validity when the comment `<textarea>` is cleared
> 
> **Edge case:** form validity unexpectedly returns `true`, …

🐛 amp-bind: Dispatch FORM_VALUE_CHANGE on [disabled] changes

---

extensions/amp-base-carousel/1.0/base-carousel.js
extensions/amp-base-carousel/1.0/dimensions.js
extensions/amp-base-carousel/1.0/scroller.js
extensions/amp-inline-gallery/1.0/storybook/Basic.js
extensions/amp-inline-gallery/1.0/test/test-inline-gallery.js
extensions/amp-inline-gallery/1.0/thumbnails.js

Partial for #28284. This PR fixes the following bugs:
- `Thumbnails` component can control a deviant internal state from its primary `BaseCarousel` sibling with the following rules:
- Internal state is overridden by most recent slide change state on the primary `BaseCarousel` (referenced as the "global state"), including actions via scrolling, its arrows, or `Pagination` interaction
- Internal state can deviate from the primary `BaseCarousel` if user scrolls directly on the `Thumbnails` component or navigates it using its own rendered arrows.
- `Thumbnails` will default to omit the `src` prop (set to `false` instead of `''`) if `thumbnailSrc` is `undefined` on the cloned slide element.
- `Thumbnails` component will align slides to `"center"` if `loop` and `"start"` otherwise, as the …

Bento Carousel: Various fixes for Thumbnails component

---

extensions/amp-truncate-text/0.1/amp-truncate-text.css

From what I see, the acceptable `slot` values are `expanded`/`collapsed`/`persistent`, but the CSS rule here looks for `slot="expand"` (unless I'm missing something). I'm guessing this rule was minor enough that the typo may have had minimal effect.

🐛Fix typo in slot value for amp-truncate-text

---

extensions/amp-consent/0.1/amp-consent.css
extensions/amp-consent/0.1/consent-ui.js
extensions/amp-consent/0.1/test/test-consent-ui.js

For #31580 (a safer version of #31660)
When served in a google viewer, the viewer has a top bar. When a user scrolls, the bar shows/hides. When the bar is shown and hidden, the viewer sends this event to AMP. For elements tracked by the fixed layer (i.e. amp-consent element),  this event will trigger the removal of the `transform` style. 
https://github.com/ampproject/amphtml/blob/4e79d3b517641f580d2aeef305d7b7589d1befa8/src/service/fixed-layer.js#L314-L322
Therefore, when a user scrolls on a doc served in a viewer before the consent iframe loads, the transform style will be removed and no transformation will be applied. 
Since fixed layer only removes `transform` style, we can add it to another class (just need to worry about CSS rule precedence).
/cc @jridgewell

🐛 [amp-consent] Move transform style to class

---

extensions/amp-stream-gallery/1.0/amp-stream-gallery.js
extensions/amp-stream-gallery/1.0/storybook/Basic.amp.js
extensions/amp-stream-gallery/1.0/storybook/Basic.js
extensions/amp-stream-gallery/1.0/stream-gallery.js
extensions/amp-stream-gallery/1.0/test/test-amp-stream-gallery.js

- Adds `next`, `prev`, and `goToSlide` actions to `StreamGallery` and `amp-stream-gallery`
- Exposes `slideChange` event on `amp-stream-gallery`
- Removes passthrough props from `StreamGallery` which are covered via `...rest`
- Unit tests

Bento Carousel: StreamGallery imperative API

---

extensions/amp-base-carousel/amp-base-carousel.md
extensions/amp-stream-gallery/amp-stream-gallery.md

📖 amp-base-carousel: Add `controls` attribute to component documentation

---

examples/amp-story/interactives.html
extensions/amp-story/1.0/amp-story-grid-layer.js
extensions/amp-story/1.0/amp-story-page.js
extensions/amp-story/1.0/amp-story.js

When you specify `#visibilityState=prerender&page=page-id` (example [here](https://www.gstatic.com/amphtml/stamp/qa/branching.html#page=page-2&visibilityState=prerender)) the second page is not loaded / shown, but the first one is. Fixes #29351
Demo: https://stories-demos-matias.web.app/examples/amp-story/interactives.html#visibilityState=prerender&page=quiz-intl
The fix involves 3 things:
- Set the hashParam'ed page as active instead of the first page by default when you pass a page in the hashString.
- Allow prerendering of the hashParam'ed **page** before the visibility changes. This marks the page as built so it updates the classes `i-amphtml-built` (for instance so that the text is not set to transparent) and it also triggers the `buildCallback` of the hashParam'ed page.
- Allow …

🐛  [Story preload] Fix preloading and specifying page in hashParam

---

examples/amp-story/video-one-page.html
examples/amp-story/video-one-page2.html
test/e2e/test-amp-story-player-navigation.js
test/e2e/test-amp-story-player-prerender.js
test/e2e/test-amp-story-player.js
test/fixtures/e2e/amp-story-player/basic.html
test/fixtures/e2e/amp-story-player/navigation.html
test/fixtures/e2e/amp-story-player/pre-rendering.html

#31276
Adds e2e tests for the player.

[amp-story-player] ✅  Add e2e tests

---

build-system/tasks/presubmit-checks.js
extensions/amp-video-docking/0.1/amp-video-docking.js
extensions/amp-video-docking/0.1/math.js
extensions/amp-video-docking/0.1/test/test-amp-video-docking.js

A more holistic rewrite could eliminate significant amount of measures. However, in my analysis:
1. Most of the measurements (and most performance sensitive ones) happen as the result of `PositionObserver` callback. However, that callback, conveniently, provides the `ClientRect` structure, which I used when possible to eliminate most of the measurements.
2. The code as it stands is fairly efficient. E.g. it starts monitoring of positions only when the element is in a right corridor.

Remove getPageLayoutBox, getLayoutBox, and getIntersectionChangeEntry APIs from docking

---

examples/ac-creative.js
examples/ampcontext-creative.html
extensions/amp-ad/0.1/legacy-ad-intersection-observer-host.js
extensions/amp-ad/0.1/test/test-legacy-ad-intersection-observer-host.js
test/integration/test-amp-ad-3p.js

**summary**
Replaces the usage of `custom-element.getChangeIntersectionEntry` with an actual IntersectionObserver. For the `fire()` call, uses an unobserve/observe pair. 
Note: I think we could remove batching since InOb will handle that automatically (a series of many observe/unobserve) pairs in rapid succession will only emit a single event)
Partial for https://github.com/ampproject/amphtml/issues/31540

Remove getChangeIntersectionEntry from LegacyAdIntersectionObserverHost

---

extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.css
extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.js

The maximum amount of phones that can be added to the screen is 4, but tablets and desktops will take 2 spaces.
Defined a property `deviceSpaces` on all devices that determines how many spaces a device takes. If the sum of the current device spaces and the device we want to add is larger than 4, then the chip button should be disabled.
The `data-spaces` attribute on chips store how many spaces are required to display a device, and when the AddDeviceDialog is created, it will only set to enabled the devices that have space to be added, or the devices that are added (which are removed when you click on those chips).
If there are 4 spaces occupied already, disable adding any new devices:
If there are 3 spaces occupied, only enable the devices that would occupy 1 space (so desktop is …

✨[Story devtools] Added functionality to block adding devices if no space

---

ads/forkmedia.js
ads/forkmedia.md

/cc @zhouyx
/cc @lannka
@zhouyx
@lannka 
Added New Formats Support on AMP via Fork Media Ad Server ContextAds

forkmedia amp changes

---

examples/amp-consent/cmp-vendors.amp.html
extensions/amp-consent/0.1/cmps.js
extensions/amp-consent/amp-consent.md
extensions/amp-consent/cmps/uniconsent.md

Add UniConsent CMP for amp-consent:
* UniConsent CMP config
* Example on cmp-vendors page
* Documentation page
[UniConsent](https://www.uniconsent.com/) is a consent management platform (CMP) registered with the IAB Europe Transparency and Consent framework (GDPR) and supports The U.S. Privacy Signal (CCPA).
Context: https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/integrating-consent.md
cc @ampproject/wg-monetization
cc @ampproject/wg-ads-reviewers

✨ Add UniConsent CMP for amp-consent

---

build-system/common/utils.js

The following command trips up:
gulp unit --watch --nobuild --files=test/unit/{test-ads-config.js,test-integration.js}
In argv.files, that's already an Array, not a string to be split.

Handles argv.files better for runtime tests.

---

extensions/amp-video/validator-amp-video.protoascii

Addresses accidental removal in #31373. See https://github.com/ampproject/amphtml/pull/31373#discussion_r544645139
@westonruter

amp-video: Add intrinsic to supported_layouts

---

extensions/amp-mowplayer/0.1/amp-mowplayer.js
extensions/amp-mowplayer/0.1/test/test-amp-mowplayer.js
extensions/amp-nexxtv-player/0.1/test/test-amp-nexxtv-player.js

Tracking for all players on #31785
Fixing these two initially since [they seem to be flaking a significant amount](http://amp-test-cases.appspot.com/test-cases/stats/fail):

✅ Deflake: Use local iframe URL on (two) 3p video player tests

---

validator/js/nodejs/package-lock.json
validator/js/nodejs/package.json

`colors` 1.2.5 is three years old. Its inclusion is causing the warnings below in my project. This was fixed in 1.3.1 (https://github.com/Marak/colors.js/issues/233)
>(!) Circular dependencies
../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/colors.js -> ../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/maps/america.js -> ../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/colors.js
../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/colors.js -> ../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/maps/america.js -> /home/bmccann/src/kit/node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/colors.js?commonjs-proxy -> ../../node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/colors.js …

📦 Upgrade colors dependency in NodeJS validator

---

build-system/tasks/firebase.js

As of node v14.0.0, [`fs.copyFile`](https://nodejs.org/api/fs.html#fs_fs_copyfile_src_dest_mode_callback) enforced stricter type validation on the third parameter (formerly `flags`, now `mode`), causing the `gulp firebase` task to throw the following:
```
[11:04:52] 'firebase' errored after 3.12 s
[11:04:52] TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
at Object.copyFile (fs.js:1972:10)
at /Users/carolineliu/amp/amphtml/node_modules/universalify/index.js:8:12
at new Promise (<anonymous>)
at Object.copyFile (/Users/carolineliu/amp/amphtml/node_modules/universalify/index.js:7:14)
at firebase (/Users/carolineliu/amp/amphtml/build-system/tasks/firebase.js:79:8)
```
This PR removes passing the third argument entirely in the firebase …

🏗  Remove file overwrite option in firebase task

---

extensions/amp-analytics/0.1/requests.js
extensions/amp-analytics/0.1/visibility-manager.js
extensions/amp-analytics/0.1/visibility-model.js

We have fixed the issue by checking the element size through `IntersectionObserver.boundingClientRect` in addition to `IntersectionObserver.intersectionRatio`. (fixed by #30267)
We no longer see `'Debugging: Activeview request with zero viewport size` error in logs. 
There's still `Debugging: Activeview request with zero element size` error in logs, however with an extremely low frequency. (5/day => 5 / 10% (throttle via code) / 10% (error log throttle) / 10% (expected error throttle) = 5000/day) 
An example error log looks like
```
Activeview request with zero element size 414 0. {"layoutBoxAtMaxRatio":{"left":0,"top":1569,"width":414,"height":0,"bottom":1569,"right":414,"x":0,"y":1569},"boundingClientRectAtMaxRatio":{"left":57,"top":461,"width":300,"height":250,"bottom":711,"right":357," …
```

🚮 Clean up additional error info added in #29629

---

examples/amp-story/attachment.html
extensions/amp-story/1.0/amp-story-page-attachment.css
extensions/amp-story/1.0/amp-story-page.js
extensions/amp-story/1.0/amp-story.js

Closes #27941
When hovering on desktop, the page attachment "swipe up" button will behave like an `<a href>` by showing on the bottom left the destination.
When hovering on mobile, it will work with the long press functionality to show the context menu.
Solution: convert page-attachment ui to `a[href]` and only `e.preventDefault` on `addEventListener(contextmenu)` on `amp-story.js` when the item should not show a context menu (for now we just enable context menus on the page-attachment "swipe up" button).
On iOS it's also necessary to add `-webkit-touch-callout: default` so the tag is long pressable (because `amp-story` sets it to `none`). More info [here](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout)
Working screenshot:

✨ Page attachment shows link on hover and long press

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json
build-system/tasks/runtime-test/helpers-unit.js
examples/sticky.ads.amp.html
extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
extensions/amp-ad/0.1/amp-ad-ui.js
extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
extensions/amp-ad/0.1/amp-ad.css
extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
extensions/amp-ad/0.1/test/test-amp-ad-ui.js
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css
package-lock.json
src/experiments/sticky-ad-transition-exp.js

Add a white background and shadow css, so that the amp-ad sticky ad looks much more like amp-sticky-ad. Ensure resizing works on both amp-ad scenarios.

✨ Implement sticky ad bottom type ad on amp-ad

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json
extensions/amp-analytics/0.1/amp-analytics.js
extensions/amp-analytics/0.1/analytics-group.js
extensions/amp-analytics/0.1/cookie-writer.js
tools/experiments/experiments-config.js

The experiment leads to inabox ad activeview regression. We think it is because of the delay in the initialization. 
The decision here is to only land the improvement to AMP docs.

🚮cleanup analytics-chunks-inabox experiment

---

src/utils/intersection.js
src/viewport-observer.js
test/unit/utils/test-intersection.js

**summary**
- Split out from https://github.com/ampproject/amphtml/pull/31753 to enable merging the helper before it passes review from ads folks.
- Creates new fn with signature: `measureIntersection(!Element) => !Promise<!IntersectionObserverEntry>`

Introduce `measureIntersection` helper for async measures.

---

build-system/eslint-rules/no-array-destructuring.js
src/base-element.js
src/custom-element.js
src/preact/base-element.js
src/preact/index.js
test/unit/preact/test-base-element-runtime.js

Implements `whenUpgraded` for Bento Imperative APIs, which exposes the API object from `Preact`'s `useImperativeHandle`. The API is wrapped an API wrapper, so that the object can be shared across rerenders (get the API once, instead of calling `whenUpgraded` multiple times).

Bento: expose Imperative API object

---

builtins/amp-img.js

Now the `sizes` are generated only once per layout.

Remove regenration of sizes for amp-img

---

extensions/amp-sidebar/1.0/amp-sidebar.css
extensions/amp-sidebar/1.0/sidebar.js
extensions/amp-sidebar/1.0/sidebar.jss.js
extensions/amp-sidebar/1.0/sidebar.type.js
extensions/amp-sidebar/1.0/storybook/Basic.amp.js
extensions/amp-sidebar/1.0/storybook/Basic.js
extensions/amp-sidebar/1.0/test/test-amp-sidebar.js
extensions/amp-sidebar/1.0/test/test-sidebar.js

1/15
- Added updates to tests
Overview of PR:
1. Have included multiple configurable CSS properties for sidebar listed below:
- color
- background-color
- height
- --story-page-vh
- top
- max-height
- max-width
- min-width
- outline
- z-index
- width
- padding
- border
2. In amp mode these can be directly controlled by user supplied CSS
```
amp-sidebar {
color: ${foregroundColor};
background-color: ${backgroundColor};
}
amp-sidebar::part(backdrop) {
background-color: ${maskBackgroundColor};
}
```
3. In preact mode pass in a style object as the `style` and `backdropStyle` props.  To have the style included inline in the rendered element.
```
<Sidebar 
style={{color: foregroundColor, backgroundColor: someColor}}
backdropStyle={{backgroundColor: someColor}}
/>
```
*******
12/18
- Added …

🖍 [bento][amp-sidebar] Allow various CSS properties to be configurable on amp-sidebar

---

validator/js/chromeextension/content_script.js

Fixes typo introduced in #31867 via 2f605e2.
I noticed via a console error today:

🐛 Fix typo s/GetAttribute/getAttribute/

---

extensions/amp-inline-gallery/1.0/amp-inline-gallery-pagination.js
extensions/amp-inline-gallery/1.0/amp-inline-gallery-thumbnails.js
extensions/amp-stream-gallery/1.0/amp-stream-gallery.js
extensions/amp-video/1.0/base-element.js
src/preact/base-element.js
test/unit/preact/test-base-element-mapping.js

This is a controversial step, but I'd like to try it under our "bento" experiment. The new design of Bento components ensures that for a `layoutSizeDefined` component the user can do either:
1. Specify classic `layout=fixed|responsive|etc` with `width`, `height`, and other static layout attributes.
2. Not specify any layout (which defaults to "container") and our `contain:strict` will guarantee 0-size for the element. AMP will not try to load this element. And it will look like an obvious error with the expectation that a user would naturally fix by providing the size via CSS. All CSS tools are available in that case, including flex/grid/aspect-ratio/fixed CSS layouts.
The main reason for this is to avoid changing the user DOM by adding internal sizer elements, etc.

Relax layout restrictions for Bento components

---

build-system/tasks/sweep-experiments/index.js
build-system/tasks/sweep-experiments/jscodeshift/parser-config.json
build-system/tasks/sweep-experiments/jscodeshift/remove-experiment-config.js
build-system/tasks/sweep-experiments/jscodeshift/remove-experiment-runtime.js

Allows `jsx` and `importAssertions` like:
https://github.com/ampproject/amphtml/blob/3514120627396355c4c5974f30ee023f6f51a21f/extensions/amp-story/1.0/amp-story.js#L117
Handier to keep track of manual steps:
```diff
- - `file.js`
+ - [ ] `file.js`
```
This was previously untested, fixed:
```
gulp sweep-experiments --experiments=my-experiment
```
Adds a section:
```markdown
Close these once they've been addressed and this PR has been merged:
- `foo`: #1111
- `bar`: #2222
```

🏗 Experiment sweep tool improvements

---

extensions/amp-lightbox/1.0/amp-lightbox.js
extensions/amp-lightbox/1.0/lightbox.js
extensions/amp-lightbox/1.0/storybook/Basic.amp.js
extensions/amp-lightbox/1.0/storybook/Basic.js
extensions/amp-lightbox/1.0/test/test-amp-lightbox.js

- Remove `data-close-button-aria-label` and hardcode the default. #31052 tracks the separate effort to replace this with `slot="close-button"` support.
- Rename `animate-in`/`animateIn` as `animation`.
- Remove `enable-animation`/`enableAnimation` - This is not present in 0.1, and if feedback is received that this is desired, it should be better as an `animation` option.
Partial for #31052

♻️ Refactor Bento Lightbox animation features

---

extensions/amp-sidebar/1.0/amp-sidebar.js
extensions/amp-sidebar/1.0/test/test-amp-sidebar.js

When sidebar is not a direct child of body, throw a warning to the user.
todo: add tests

✨ [bento][amp-sidebar] Add warning when sidebar not child of body (amp mode only)

---

extensions/amp-story/1.0/amp-story-page.js
extensions/amp-story/1.0/test/test-amp-story-page.js

Context / Fixes #31911
To consistently keep audio unmuted after auto-play, play needs to be called before unmuting the media on iOS 14.2 and 14.3.
This PR calls `unmuteAllMedia_` after `playAllMedia_` resolves in `amp-story-page`.
[demo](https://stamp-autoplay.web.app/examples/amp-story/ampconf.html)

Unmute media after playAllMedia resolves.

---

extensions/amp-video-iframe/0.1/amp-video-iframe.js
extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js

Partial for https://github.com/ampproject/amphtml/issues/31540
Note: this is [a similar strategy](https://github.com/ampproject/amphtml/pull/31055#discussion_r520958803) being used by the new version of amp-video

amp-video-iframe: use InOb instead of ce.getIntersectionChangeEntry.

---

build-system/tasks/e2e/index.js
build-system/tasks/e2e/mocha-dots-reporter.js
build-system/tasks/karma.conf.js
build-system/tasks/presubmit-checks.js

During the migration to CircleCI, I discovered two problems:
- CircleCI doesn't wrap its logs, resulting in ~10k dots on one line during unit tests for example.
- New versions of Mocha have changed the reporter API, causing E2E test logging to break on CircleCI and [stall the job](https://app.circleci.com/pipelines/github/rsimha/amphtml/141/workflows/554d9f08-3e5a-4841-95b6-d29ca47561fc/jobs/539).
**This PR does two things:**
- Wraps all test logging to 150 dots per line
- Modernizes the custom reporter for e2e tests based on the latest mocha dev docs
**Passing result:** 
Also tested on CircleCI [here](https://app.circleci.com/pipelines/github/rsimha/amphtml/149/workflows/ae42212b-07e7-4c91-b7fa-f5fbaf7fb6b3/jobs/548/parallel-runs/0/steps/0-107)
**Reference:** …

🏗 Modernize / fix test logging during CI builds

---

extensions/amp-access-poool/0.1/poool-impl.js
extensions/amp-access-poool/amp-access-poool.md

This PR addresses 2 minor issues for `amp-access-poool`:
- Some users are stuck with the default locale (aka fr) when there's an error trying to show the paywall
- We introduced a "contextual" level over journeys inside Poool, which is missing here and a blocking issue for some users

🐛  amp-access-poool: add missing locale & context config values

---

build-system/tasks/visual-diff/index.js

This PR wraps most of the visual diff runner code in separate try/catch blocks, to increase the verbosity of logging info in case of errors, and to also upload the "error page" snapshot to Percy in more cases

🏗✅ Add fine-grained logging and error reporting to visual diff tests

---

build-system/tasks/clean.js
build-system/tasks/validator.js
validator/build.py
validator/package-lock.json
validator/package.json

This PR contains a few Validator fixes in anticipation of the migration of our CI from Travis to CircleCI.
- Explicitly invoke `python3` in `gulp validator[-webui]` (because CircleCI Ubuntu 20.04 VMs have `pip3` but not `pip`)
- Use [`jasmine-console-reporter`](https://www.npmjs.com/package/jasmine-console-reporter) for logging (because CircleCI logs do not wrap, and print ~12K dots on one line)
- Clean up `validator/dist/` during `gulp clean`
**Before:** ([link](https://app.circleci.com/pipelines/github/rsimha/amphtml/161/workflows/8239d6ab-cb21-41f6-8b5b-95c68cf150b2/jobs/561/parallel-runs/0/steps/0-108))
**After:** ([link](https://app.circleci.com/pipelines/github/rsimha/amphtml/164/workflows/47c2351b-56a1-4402-9c12-7d2c69a92407/jobs/577/parallel-runs/0/steps/0-108))
/cc …

🏗 Assorted Validator fixes

---

examples/amp-consent/cmp-vendors.amp.html
extensions/amp-consent/0.1/cmps.js
extensions/amp-consent/amp-consent.md
extensions/amp-consent/cmps/pubtech.md

Adding Pubtech to the list of registered CMPs.
Added:
- Pubtech CMP config
- Example on cmp-vendors page
- Example documentation.
Pubtech CMP is a consent management provider (CMP) solution built on and registered with the IAB Europe Transparency and Consent framework.
Context: https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/integrating-consent.md
cc @ampproject/wg-monetization

✨  Add Pubtech type for amp-consent

---

extensions/amp-base-carousel/1.0/base-carousel.js

The experimental logic to only show a subset of slides depending on their distance from the `currentSlide` should account for when the carousel is looping. For instance, if you have slides `[0][1][2][3][4][5][6][7][8]`, rearranged as `[5][6][7][8][0][1][2][3][4]`(centered around `0`), we currently render `[0][1][2][3]`. This PR adds logic so also render `[6][7][8]` in that case.
This is particularly important when we have `snap-align="center"` and `visible-count > 1`, as prior to this change we would see nothing rendered in that partial spot where the last slide should be visible.
We could alternatively measure slides and render those that are within a certain threshold of the carousel viewport, as that would generically support all cases (looping, non-looping, mixed-length) and be a bit …

🐛 Bento Carousel: Conditionally render wraparound slides when looping

---

.gitignore
build-system/server/lazy-build.js
build-system/tasks/clean.js
build-system/tasks/extension-helpers.js
build-system/tasks/storybook/amp-env/webpack.config.js
build-system/tasks/storybook/index.js
build-system/tasks/storybook/package-lock.json
build-system/tasks/storybook/package.json
build-system/tasks/storybook/preact-env/webpack.config.js

This is what the storybook build [currently looks like](https://app.circleci.com/pipelines/github/rsimha/amphtml/168/workflows/c48a4c90-6006-479e-b8e2-0cd247d547c0/jobs/586/parallel-runs/0/steps/0-107) during CI:
**A few fixes:** (in anticipation of the move to CircleCI)
- Makes `build-storybook` synchronous so that build steps and the gulp task do not early exit before completion
- Leaves `start-storybook` as asynchronous, but updates task invocation code and cleans up flags
- Removes the explicit `--ci` flag for `start-storybook` and auto-detects CI runs
- Adds an implicit `--loglevel` flag to `build-storybook` to silence verbose logging during CI
- Modernizes webpack configs to eliminate deprecation warnings
- Includes `examples/storybook` in `gulp clean`
- Fixes a bug in the default …

🏗 Assorted storybook fixes

---

extensions/amp-sidebar/1.0/sidebar.js
extensions/amp-sidebar/1.0/test/test-amp-sidebar.js
extensions/amp-sidebar/1.0/test/test-sidebar.js

If `side` attribute / prop is not provided to the `sidebar` component.  The component first checks if the document is an RTL document and if so assigns default side to `right`, otherwise defaults to `left`.
todo: add tests

✨ [bento][amp-sidebar] Add check for RTL docs for default side

---

.travis.yml
build-system/pr-check/utils.js

A few updates to VM setup in anticipation of the move to CircleCI:
- Move Travis specific steps from `build-system/pr-check/utils.js` to `.travis.yml`
- Remove Java setup steps (no longer needed because we use native closure compiler)
- Make `gsutil` upload / download less verbose with `-q` (the ASCII spinner doesn't work on non-TTY consoles)
This paves the way to setup CircleCI VMs using a different (more streamlined) set of steps, and use a different storage bucket if desired.

🏗 Updates to VM setup during CI

---

build-system/babel-config/pre-closure-config.js
build-system/compile/compile.js
package-lock.json
package.json
src/friendly-iframe-embed.js
src/inabox/amp-inabox.js
src/runtime.js

This fixes several issues:
1. AMP Shadow (amp-next-page) uses `AMP.combinedCss`, which is the combined `ampdoc.css` + `ampshared.css`.
- In ESM mode, this property was `undefined` because we stripped the imports. It's now the `textContent` of `<style amp-runtime>`.
2. Re-adds `ampshared.css` to inabox
- The import was removed, so it became just the string `'html.i-amphtml-inabox{width:100%!important;height:100%!important}'`
- It's unclear whether inabox can run without it.
3. Fixes FIE to only inject `ampshared.css`
- This was changed in #22418, and we essentially undid it.
- `<style amp-runtime>` is the **combined** css, not just shared css
And it removes `filter-imports` babel plugin. [Have I mentioned how much I disliked it before](https://github.com/ampproject/amphtml/pull/28825)?

🔥 Fix runtime styles in ESM mode

---

extensions/amp-story/1.0/amp-story-grid-layer.js
extensions/amp-story/1.0/test/test-amp-story-grid-layer.js

Added the `preset` attribute to grid-layers with 2 presets:
- **`2021-foreground`**: aspect-ratio of 69:116
- **`2021-background`**: aspect-ratio of 69:116 and scaling-factor of 1.142
Wrote test to ensure presets are applied and aspect-ratio is used.
Attribute does not pass validation yet.
Closes #31283

✨[Story layouts] Responsiveness presets for grid-layers

---

build-system/common/ci.js
build-system/pr-check/utils.js
build-system/tasks/pr-deploy-bot-utils.js
build-system/tasks/test-report-upload.js

With the impending move from Travis to CircleCI, build and job identifiers are not guaranteed to be numeric values. This PR updates `buildNumber` and `jobNumber` to `buildId` and `jobId` respectively.

🏗 Update CI build / job identifiers

---

css/amp-story-player.css

Closes #31419
Hides `<a>` elements under the player by applying `display: none` to them once the player is loaded.

🐛  [amp-story-player] Apply display:none to <a> tags under the player once loaded

---

validator/validator-css.protoascii

Fixes #32004.
Tests may also need to be updated.

Increase Transformed AMP CSS limit to 112500 bytes

---

build-system/tasks/ava.js
build-system/tasks/get-zindex/test-2.css

- Fixes bug due to transitive dependency (gulp 3 -> 4) of the gulp-ava plugin (the task should no longer be `async`)
- Exposes and fixes a test failure introduced by #29275

🏗 Expose and fix silent failure in ava tests

---

validator/validator-css.protoascii

This is in continuation of #32004
The intention is to provide a buffer for Transformed AMP. In addition to the buffer of overall CSS we're adding a buffer for inline style. Related is #31512.

Increase inline style to 1500 bytes for Transformed AMP

---

src/service/resources-impl.js
test/unit/test-mutator.js
test/unit/test-resources.js

Run Resources tests via realWin

---

extensions/amp-form/amp-form.md

file and password input types are banned in the email spec.
Fixes #32037
/to @CrystalOnScript @caroqliu 
/cc @bill97819

📖  Fix amp-form doc for email on banned input types

---

extensions/amp-story/1.0/amp-story.js

Context: #32067
The previous code was a bit confusing because it sounded like it was hiding the story until the content loads or timeout fires, when it's actually the `amp-story-renderer-service` doing this. So I renamed a few things for clarity.
Fixes #32067

Increase initial content loaded timeout.

---

build-system/pr-check/bundle-size.js
build-system/pr-check/checks.js
build-system/pr-check/cross-browser-tests.js
build-system/pr-check/module-build.js
build-system/pr-check/nomodule-build.js
build-system/pr-check/nomodule-tests.js
build-system/pr-check/unminified-build.js
build-system/pr-check/unminified-tests.js
build-system/pr-check/utils.js
build-system/pr-check/validator-tests.js
build-system/tasks/pr-deploy-bot-utils.js

Follow up to #32041 and #32044. 
- Rename `stopTimedJob()` to the more appropriate `abortTimedJob()` for early exit on failure
- Rename `signalDistUpload()` to `signalPrDeployUpload()`
- Consolidate calls to `signalPrDeployUpload()` in one place (`nomodule-build.js`)
- Fix bug in `{nomodule|unminified}-build.js` (there's no need to build runtime for unit tests)
- Simplify `if` block in `nomodule-tests.js`

🏗  Fixes to PR-check logic

---

build-system/tasks/pr-deploy-bot-utils.js

- Update nomodule binary name from `amp_dist_<ID>.zip` to `amp_nomodule_<ID>.zip`
- Update signal-upload url from `/travisbuilds/` to `/cibuilds/`
Companion to https://github.com/ampproject/amp-github-apps/pull/1141 and https://github.com/ampproject/amp-github-apps/pull/1196
Follow up to #31940

🏗 Update PR deploy URLs

---

build-system/pr-check/bundle-size.js

Turns out that download / comparison of sizes works on CircleCI, but saving of sizes does not.

🏗 Fix bundle-size check for Travis builds

---

.prettierignore
build-system/tasks/prettify.js
build-system/test-configs/config.js

- Import `logOnSameLine` from correct place
- Exempt `package.json` and `package-lock.json` from prettier checks

🏗  Minor bugfixes for `gulp prettify`

---

.circleci/config.yml
.circleci/fetch_merge_commit.sh

Other CI services test the result of merging a PR branch on to `master`, and include recent upstream commits while running tests. CircleCI does not exhibit this behavior by default.
This PR adds a post-checkout step that switches to the well-known Github merge ref `refs/pull/$CIRCLE_PR_NUMBER/merge`.
**Before:**
**After:**
**Reference:** https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662

🏗 Test the merge commit with `master` during CircleCI builds

---

.circleci/config.yml
.travis.yml
build-system/pr-check/unit-tests.js
build-system/tasks/unit.js

**Current state:**
- Unit tests are run with the unminified integration tests
- They used to need the entire unminified runtime, but no longer do
- They add 7-10 mins of running time to the job
**Changes in this PR:**
- Move unit tests to their own CI job
- Coverage and test case reporting data are uploaded separately
- On CircleCI, run when the job starts (provides an early signal when tests fail)
- On Travis, run in parallel with integration tests (shortens overall CI running time)
- Remove defunct `--nobuild` from `gulp unit` (remaining pre-steps CSS / vendor configs / jison take <1s to run)
**New running times:**

🏗 Split off unit tests into a separate CI job

---

build-system/global-configs/canary-config.json
extensions/amp-ad/0.1/legacy-ad-intersection-observer-host.js
src/iframe-attributes.js
src/utils/intersection.js
test/unit/utils/test-intersection.js

**summary**
This PR applies two solutions to a newly introduced bug in `LegacyAdIntersectionObserverHost` and the `measureIntersection` helper:
1. Sometimes IntersectionObserverEntry will have null rootBounds. This is especially true when within a crossorigin iframe (e.g. a Viewer). The current [intersectionEntryToJson](https://github.com/ampproject/amphtml/blob/00c6263009a751884aba82fd8abc614c7988eea1/src/utils/intersection.js#L86-L94) function breaks in this case. 
2. A potentially null `rootBounds` (following correct spec) is a breaking change for current 3p consumers of amp-provided intersections (amp-ads). This PR adds in the old behavior of `getViewport.getRect()` for situations with missing rootBounds by setting `root=document` instead.
3. Completely turns off …

Fix null rootBounds for LegacyAdIntersectionObserverHost

---

.circleci/config.yml

Performance tests take ~30 mins and regularly fail during CI.
With this PR, CI round trip time should reduce to ~20 mins. 
Tracking issue: #12128

🏗 Stop running performance tests until they are optimized / fixed

---

.circleci/OWNERS

This is a new directory, and (intentionally) isn't captured by the dotfile glob in the root `OWNERS` file.

🏗 Add an owners file for `.circleci/`

---

.circleci/config.yml

Right now, CircleCI is building all branches on `ampproject/amphtml` in addition to PR branches. This PR restricts push builds to just `master` and `amp-release-*` branches. PR branches will continue to be built.

🏗  Add branch filtering for CircleCI builds

---

build-system/test-configs/dep-check-config.js
src/friendly-iframe-embed.js
src/polyfills/abort-controller.js
src/service/resource.js
test/unit/polyfills/test-abort-controller.js
test/unit/test-resource.js

Ensure that aborting layout via unload cancels the layout promise

---

package-lock.json
package.json
src/purifier/package-lock.json
src/purifier/package.json

The runtime uses `dompurify` 2.0.7, which appears to have a security vulnerability. This PR upgrades to the latest version 2.2.6.

🏗 Upgrade to `dompurify` 2.2.6

---

test/visual-diff/visual-tests

This test has been failing repeatedly of late. See https://github.com/ampproject/amphtml/issues/28975#issuecomment-764908430.
/cc @ampproject/build-cop

❄️ Mark visual test `amphtml-ads: friendly iframe static` as flaky

---

extensions/amp-base-carousel/0.1/test-e2e/test-advance.js
extensions/amp-base-carousel/0.1/test-e2e/test-arrows-non-looping.js
extensions/amp-base-carousel/0.1/test-e2e/test-arrows.js
extensions/amp-base-carousel/0.1/test-e2e/test-autoadvance.js
extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
extensions/amp-base-carousel/0.1/test-e2e/test-default-attributes.js
extensions/amp-base-carousel/0.1/test-e2e/test-grouping.js
extensions/amp-base-carousel/0.1/test-e2e/test-hidden-controls.js
extensions/amp-base-carousel/0.1/test-e2e/test-initial-slide.js
extensions/amp-base-carousel/0.1/test-e2e/test-mixed-lengths-no-snap.js
extensions/amp-base-carousel/0.1/test-e2e/test-mixed-lengths.js
extensions/amp-base-carousel/0.1/test-e2e/test-multi-visible-single-advance.js
extensions/amp-base-carousel/0.1/test-e2e/test-non-looping.js
extensions/amp-base-carousel/0.1/test-e2e/test-responsive.js
extensions/amp-base-carousel/0.1/test-e2e/test-rtl.js
extensions/amp-base-carousel/0.1/test-e2e/test-snap-property.js
extensions/amp-base-carousel/0.1/test-e2e/test-vertical.js
extensions/amp-base-carousel/1.0/test-e2e/test-advance.js
extensions/amp-base-carousel/1.0/test-e2e/test-arrows-non-looping.js
extensions/amp-base-carousel/1.0/test-e2e/test-arrows.js
extensions/amp-base-carousel/1.0/test-e2e/test-autoadvance.js
extensions/amp-base-carousel/1.0/test-e2e/test-carousel.js
extensions/amp-base-carousel/1.0/test-e2e/test-grouping.js
extensions/amp-base-carousel/1.0/test-e2e/test-mixed-lengths-no-snap.js
extensions/amp-base-carousel/1.0/test-e2e/test-mixed-lengths.js
extensions/amp-base-carousel/1.0/test-e2e/test-non-looping.js
extensions/amp-base-carousel/1.0/test-e2e/test-responsive.js
extensions/amp-base-carousel/1.0/test-e2e/test-rtl.js
extensions/amp-base-carousel/1.0/test-e2e/test-vertical.js
extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js

Related to #24195 
- Rename e2e test files to include the version number for easier debugging
- Increase the test timeouts for some 1.0 files to see if this gets us anywhere with CircleCI. Another PR should follow up to skip these tomorrow if we find that this is not the case.

❄️  amp-base-carousel e2e test modifications

---

build-system/pr-check/utils.js
build-system/tasks/pr-deploy-bot-utils.js

On CircleCI, restarting a failed job results in a new workflow ID. This breaks binary download because the filename suffix is the old workflow ID. The only way out is to restart the entire workflow. See [this example](https://app.circleci.com/pipelines/github/ampproject/amphtml?branch=pull%2F32073).
- Change filename suffix to `ciPullRequestSha()` (consistent across restarts)
- Update PR Deploy utils with this change
- Execute `signalPrDeployUpload()` only when binaries are built on Travis (until transition is complete)
- Remove build / workflow ID from the reporting URL
Updates to the PR deploy app internals are contained in https://github.com/ampproject/amp-github-apps/pull/1201

🏗 Switch build artifact unique identifier from build ID to commit SHA

---

build-system/common/ci.js
build-system/pr-check/utils.js
build-system/tasks/codecov-upload.js
build-system/tasks/pr-deploy-bot-utils.js

This PR fixes a bug in #32083, where the commit SHA wasn't being fetched correctly during push builds. (The SHA is used to name the zip file containing build artifacts passed between the build and test stages of CI).

🏗 Fix commit SHA retrieval for push and PR builds on all CI services

---

build-system/compile/compile.js
build-system/tasks/dist.js

This should help tweak compilation speed during local development and CI builds.
**Results:**
Travis Linux:
GH Actions Linux:
GH Actions macOS:
GH Actions Windows:
CircleCI Linux (xlarge):

🏗 Print closure concurrency during `gulp dist`

---

extensions/amp-date-countdown/0.1/amp-date-countdown.md
extensions/amp-date-countdown/1.0/amp-date-countdown.js
extensions/amp-date-countdown/1.0/date-countdown.js
extensions/amp-date-countdown/1.0/date-countdown.type.js
extensions/amp-date-countdown/1.0/storybook/Basic.amp.js
extensions/amp-date-countdown/1.0/storybook/Basic.js
extensions/amp-date-countdown/1.0/test/test-date-countdown.js
extensions/amp-date-countdown/amp-date-countdown.md

Update the `1.0` bento component to match the `0.1` component which currently includes the `countUp` feature.
The countUp feature allows the date-countdown component to count upwards instead.  (Time elapsed since a particular date/time).
Related bug: https://github.com/ampproject/amphtml/issues/30197
todo:
- validator and amp side - added 1/21
- storybooks - added 1/21
- tests - added 1/21
- documentation - added 1/21

✨ [bento][amp-date-countdown] countUp feature for date-countdown component

---

extensions/amp-base-carousel/1.0/test-e2e/helpers.js
extensions/amp-base-carousel/1.0/test-e2e/test-arrows-non-looping.js
extensions/amp-base-carousel/1.0/test-e2e/test-mixed-lengths.js
extensions/amp-base-carousel/1.0/test-e2e/test-vertical.js

Since #32113, tests [still appear to be flaking](https://app.circleci.com/pipelines/github/ampproject/amphtml/236/workflows/6bb80f36-96d2-4986-923f-b0c147e08933/jobs/1588) for `amp-base-carousel`.
EDIT: This PR skips existing flaky tests, often those which call `getScrollingElement`, `getPrevArrow`, and `getNextArrow` - we should continue monitoring if others which use these helper functions (whose timeouts I also increased) begin flaking as well.
The timeout message in the above sample test run `Wait timed out after 5063ms` suggests we should not be increasing the full timeouts for the blocks but the default timeouts given to the `controller.findElement` method. Since this and other ([1](https://app.circleci.com/pipelines/github/ampproject/amphtml/223/workflows/a3f401ef-791b-47aa-b1ed-554 …

❄️ Skip flaky amp-base-carousel e2e tests

---

src/service/video-manager-impl.js
src/utils/intersection.js
test/unit/test-video-rotate-to-fullscreen.js

**summary**
Partial for https://github.com/ampproject/amphtml/issues/31540
Note: besides for the ads initialIntersection experiment, this is the last usage of `getIntersectionChangeEntry`

video-manager-impl: remove usage of getIntersectionChangeEntry

---

.circleci/config.yml

CircleCI builds currently use an `ampproject` organization-level [context](https://circleci.com/docs/2.0/contexts/). The downside is that other projects within the org will inherit the same context when builds are enabled for them.
This PR switches the config to implicitly use project-level environment variables (already set) that are locked down to just the [`amphtml`](https://app.circleci.com/pipelines/github/ampproject/amphtml) CircleCI project.

🏗  Replace org-level context with project-level env vars on CircleCI

---

extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-logs.css
extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.css
extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.js
extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.js

Added changes from @hongcatlover comments:
- Made scrollbar from logs match dark colors
- Moved logs tab to 2nd place (because it's more important than page-experience)
- Centered devices better by improving sizing of devices container
- Increased border radius of dialogs

✨ [Story devtools] Finalize UI details: dark scrollbar, center devices, change tab order

---

build-system/pr-check/bundle-size.js
build-system/pr-check/checks.js
build-system/pr-check/ci-job.js
build-system/pr-check/cross-browser-tests.js
build-system/pr-check/e2e-tests.js
build-system/pr-check/experiment-tests.js
build-system/pr-check/module-build.js
build-system/pr-check/module-tests.js
build-system/pr-check/nomodule-build.js
build-system/pr-check/nomodule-tests.js
build-system/pr-check/performance-tests.js
build-system/pr-check/unit-tests.js
build-system/pr-check/unminified-build.js
build-system/pr-check/unminified-tests.js
build-system/pr-check/validator-tests.js
build-system/pr-check/visual-diff-tests.js

As the number of parallel CI jobs has increased, we've accumulated heaps of boilerplate code.
**PR highlights;**
- Standardizes the structure of a CI job script via `runCiJob()` in `ci-job.js`
- Simplifies all CI job scripts using the above function
For easy reviewing, use [this link](https://github.com/ampproject/amphtml/pull/32140/files?w=1) that hides all the whitespace-only changes.

🏗♻️ Refactor and simplify all CI job executor scripts

---

.codecov.yml
.prettierrc
.vscode/settings.json
METRICS.md
README.md
build-system/server/app-index/header-links.js
build-system/tasks/pr-deploy-bot-utils.js
build-system/tasks/presubmit-checks.js
build-system/test-configs/config.js
contributing/DEVELOPING.md
contributing/TESTING.md
contributing/buildcop.md
contributing/getting-started-e2e.md
contributing/release-schedule.md
extensions/amp-3d-gltf/0.1/test/test-amp-3d-gltf.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js
extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
extensions/amp-iframe/0.1/amp-iframe.js
test/integration/test-amphtml-ads.js
test/unit/test-mutator.js

This PR makes it possible to fully stop Travis builds, but does not actually do so.
- Enable auto-formatting for CircleCI's config file
- Clean up unused configs pertaining to Travis
- Report PR deploy success from CircleCI builds so it no longer relies on Travis
- Remove Travis badges on AMP's readme and metrics pages
- Update CI link on AMP's dev server to CircleCI
- Update AMP dev docs with CircleCI-specific links and text
- Clean up mentions of Travis in test file comments
**Coming up next week:**

🏗 Prepare to move AMP's CI off Travis

---

extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.js

Closes #32124
Moved creating the devices to the layoutCallback so they are loaded when in the preview tab. This makes the stories load properly.
Also, the unloadedCallback was removing the resizing so also fixed that.

🐛  [Story devtools] Make players on layoutCallback so they load

---

build-system/pr-check/build-targets.js
build-system/pr-check/bundle-size.js
build-system/pr-check/checks.js
build-system/pr-check/ci-job.js
build-system/pr-check/cross-browser-tests.js
build-system/pr-check/e2e-tests.js
build-system/pr-check/module-build.js
build-system/pr-check/module-tests.js
build-system/pr-check/nomodule-build.js
build-system/pr-check/nomodule-tests.js
build-system/pr-check/unit-tests.js
build-system/pr-check/unminified-build.js
build-system/pr-check/unminified-tests.js
build-system/pr-check/validator-tests.js
build-system/pr-check/visual-diff-tests.js
build-system/tasks/pr-check.js
build-system/tasks/report-test-status.js

- Add the `Targets` enum to `build-targets.js`
- Add `buildTargetsInclude()` to check if a PR's build targets include the given target(s)
- Cache the set of build targets once they have initially been determined
- Eliminate the hundreds of spots where build targets are referenced by name
- Modify `reportAllExpectedTests()` to use the previously computed build targets
- Fix bug where a nonexistent target was still being checked (`VALIDATOR_JAVA` no longer exists)

🏗 Refactor and simplify build target logic during CI builds

---

build-system/pr-check/utils.js
gulpfile.js

The `gulp` CLI [disables log coloring](https://github.com/gulpjs/gulp-cli/blob/726c6ed1395a382712fa1f67691ac955a53970b8/lib/shared/ansi.js#L30-L41) by default on most CI services due to [these lines](https://github.com/isaacs/color-support/blob/v1.1.3/index.js#L93-L97) in the [`color-support`](https://www.npmjs.com/package/color-support) library.
This PR enables log coloring by adding the `--color` flag to all `gulp` commands invoked during PR jobs.
**Before:**
**After:**

🏗 Enable `gulp` log coloring during CI

---

build-system/pr-check/bundle-size.js
build-system/tasks/pr-deploy-bot-utils.js

All experimentation with CircleCI is now complete. We will fully switch from Travis later this week. Until then, let's do all signaling of bundle-size / PR-deploy from Travis, since that's the blocking check.

🏗 Report bundle-size / PR-deploy from Travis until the switch to CircleCI actually happens

---

.circleci/config.yml

We currently use `xlarge` CircleCI VMs, which give us a build round trip time of under 20 mins. E.g. [this build](https://app.circleci.com/pipelines/github/ampproject/amphtml/386/workflows/3e1e4878-35f1-4bff-a26a-c11d4a6a8564).
From the [pricing chart](https://circleci.com/pricing/), `xlarge` VMs cost 5x as much per minute as `large` VMs.
This PR optimizes the price / performance of CircleCI builds by using `xlarge` VMs for jobs that build the AMP runtime (highly parallelized), and `large` VMs for all other jobs that run tests (mostly done serially).

Optimize CircleCI builds with a mix of `xlarge` and `large` VMs

---

build-system/tasks/report-test-status.js

The experimentation we were doing with CircleCI builds is now complete. This PR moves expected-test-status-reporting back to Travis until it is time to fully move off it later this month.

🏗 Report test statuses from Travis until it is turned off

---

build-system/compile/bundles.config.extensions.json
examples/bento.amp.html
extensions/amp-accordion/1.0/amp-accordion.css
extensions/amp-base-carousel/1.0/amp-base-carousel.css
extensions/amp-base-carousel/1.0/amp-base-carousel.js
extensions/amp-base-carousel/1.0/test-e2e/test-autoadvance.js
extensions/amp-base-carousel/1.0/test-e2e/test-carousel.js
extensions/amp-fit-text/1.0/amp-fit-text.css
extensions/amp-fit-text/1.0/amp-fit-text.js
extensions/amp-inline-gallery/1.0/amp-inline-gallery.css
extensions/amp-instagram/1.0/amp-instagram.css
extensions/amp-instagram/1.0/amp-instagram.js
extensions/amp-lightbox/1.0/amp-lightbox.css
extensions/amp-sidebar/1.0/amp-sidebar.css
extensions/amp-social-share/1.0/amp-social-share.css
extensions/amp-stream-gallery/1.0/amp-stream-gallery.css
extensions/amp-stream-gallery/1.0/amp-stream-gallery.js
extensions/amp-video/1.0/amp-video.css
extensions/amp-video/1.0/amp-video.js
extensions/amp-youtube/1.0/amp-youtube.css
extensions/amp-youtube/1.0/amp-youtube.js

Partial for #32155.
This is an alternative to the #32157. Unlike the #32157, this pull request places the pre-upgrade CSS in the each element's stylesheet. Thus the use of an element will look like this:
```
<head>
<link rel="stylesheet" type="text/css" href="https://cdn.ampproject.org/v0/amp-base-carousel-1.0.css">
<script async custom-element="amp-base-carousel" src="https://cdn.ampproject.org/v0/amp-base-carousel-1.0.js"></script>
</head>
```
One inconvenience - a developer would have to ensure manually that stylesheets are included before any custom styles since order-based specificity is important for something like this.
This solution is pretty economical, you'd notice that the only real "annoying" duplicative piece here is this fragment:
```
amp-foo:not(.i-amphtml-built) > …
```

Pre-upgrade CSS for Bento as part of per-element stylesheets

---

extensions/amp-social-share/0.1/amp-social-share.md
extensions/amp-social-share/1.0/amp-social-share.css
extensions/amp-social-share/1.0/amp-social-share.js
extensions/amp-social-share/1.0/social-share.js
extensions/amp-social-share/1.0/social-share.jss.js
extensions/amp-social-share/1.0/test/test-amp-social-share.js
extensions/amp-social-share/1.0/test/test-social-share.js
extensions/amp-social-share/amp-social-share.md
src/preact/base-element.js
test/unit/preact/test-base-element-mapping.js

POC - Get Bento version (`1.0`) up to date with (`0.1`) on focus highlighting per: #29561
When the user focuses on the Social Share element, highlight with a blue outline that is highly visible
Can overwrite in amp mode by including the following in the amp-page,
```
amp-social-share:focus-within {
desired styling...
}
```
Differs slightly from `0.1` which would use an `amp-social-share:focus selector`.  This is because the actual element that gets focus is within the shadow DOM of the `amp-social-share` element (and is not this actual element).  Also considered making the host element the element that receives focus, but then on `keydown` events, the actual button element within the shadow DOM does not receive the event.
Open Question:
1. Not sure how would we overwrite in preact mode? …

♿ [bento][social-share] Enable focus highlighting on bento version of component

---

extensions/amp-accordion/1.0/amp-accordion.js
extensions/amp-accordion/1.0/test/test-amp-accordion.js

Fix a bug in amp-accordion.  amp-accordion was dispatching events with the incorrect name causing a bug when attempting to listen for events in bento mode.

🐛 [bento][amp-accordion] Update accordion to dispatch event with correct name

---

extensions/amp-base-carousel/0.1/amp-base-carousel.js
extensions/amp-base-carousel/0.1/test-e2e/test-mixed-length-arrows.js
test/manual/amp-base-carousel/no-arrows.amp.html

Closes #32120
For mixed length carousels, we ignore visible count: https://amp.dev/documentation/components/amp-base-carousel/?format=websites#mixed-length
Therefore, we should not only use `visibleCount` in our arrow disabled calculations. We could eliminate `visibleCount` from our disabled calculations completely, but I think it's safer to keep in, seeing as it's a trivial calculation.

🐛 [amp-base-carousel 0.1] Mixed length carousel disabled arrow calculations

---

extensions/amp-lightbox/1.0/amp-lightbox.css
extensions/amp-lightbox/1.0/lightbox.js
extensions/amp-lightbox/1.0/lightbox.jss.js
extensions/amp-lightbox/1.0/lightbox.type.js
extensions/amp-lightbox/1.0/storybook/Basic.amp.js
extensions/amp-lightbox/1.0/storybook/Basic.js
extensions/amp-lightbox/1.0/test/test-lightbox.js

This PR implements the `scrollable` feature for `Lightbox`/`amp-lightbox`. Related to #31052.
Scrolling is allowed within the `Lightbox` with application of `overflow: scroll` as opposed to `overflow: hidden`. It also prevents scrolling beyond the `Lightbox` in the outer document with application of `overscroll-behavior: none` and `overflow: scroll`. It appears that `overflow: hidden` in combination with `overscroll-behavior: none` does not yield scroll containment due to over-scrolling not being possible given the lack of overflow.
Unfortunately, `overscroll-behavior` is only [partially supported](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior#browser_compatibility), so we may need to have more robust approaches such as adding an event listener to the element's root …

✨ Bento Lightbox: `scrollable` feature

---

extensions/amp-base-carousel/validator-amp-base-carousel.protoascii

Missing "controls" attribute, which is can take a [media query](https://amp.dev/documentation/components/amp-base-carousel/?format=websites#media-queries) to resolve to its value as one of `"auto"|"always"|"never"`.
https://amp.dev/documentation/components/amp-base-carousel/?format=websites#controls
Example valid value in media query format:
`(min-width: 1000px) always, (min-width: 600px) never, always`
Resolves #31872

🐛Update validator-amp-base-carousel.protoascii with 'controls' attribute. Resolves 31872

---

src/service/video-manager-impl.js
test/integration/test-video-manager.js

Fixes #32173
1. When closing a container lightbox, the `<amp-youtube>` element is unlaid out. 
2. When opening the lightbox a second time, the `<amp-youtube>` element is laid out again.
The `VideoManager` then incorrectly stores two entries. When playing for a second time it will `pauseOtherVideos()`, incorrectly pausing itself—so the video never plays.
The reused `VideoEntry` maintains its listeners at the e.g. `<amp-video>` level, so they continue to work.

🐛 Fix video pausing itself after second layout

---

src/polyfillstub/intersection-observer-stub.js
src/service.js
test/unit/polyfills/test-intersection-observer.js

**summary**
Due to a InOb WebKit bug (https://bugs.webkit.org/show_bug.cgi?id=219495), we should force the InOb polyfill for all WebKit-based browsers. The polyfill already will choose a Native InOb when available + non-document root is requested on a per-instance basis, which works well for this case.
Note: I've never written UA engine detection code before, so I'm still researching now to ensure `WebKit` is safe as a regex test.

InOb: Force polyfill for WebKit document=root

---

css/ampdoc.css
test/unit/test-viewport-binding.js

Partial for #31364.
This is an undo of https://github.com/ampproject/amphtml/pull/27319. The reasoning: this is a very heavy-handed fix and possible too risky.

Disable overflow-x:hidden for WebView mode

---

extensions/amp-date-countdown/1.0/amp-date-countdown.js
extensions/amp-date-countdown/1.0/storybook/Basic.amp.js
extensions/amp-date-countdown/amp-date-countdown.md

Change the `data-count-up` attribute to be named `count-up.`
This matches the rest of the attributes and unlikely to have collision with native attributes since there is a dash in `count-up.`
Related to: https://github.com/ampproject/amphtml/pull/32047
https://github.com/ampproject/amphtml/pull/32047#discussion_r562828744

✨ [bento][amp-date-countdown] Change attribute name of count-up

---

extensions/amp-base-carousel/amp-base-carousel.md

Related to #28284, incorporating format changes from #31944

📖  Bento: Adopt new formatting for `amp-base-carousel` documentation

---

examples/amp-story/analytics.html
extensions/amp-story/1.0/amp-story-embedded-component.js
extensions/amp-story/1.0/utils.js

Linker cannot access anchor tag from tooltip since it's inside the shadow dom, so we create an anchor outside the shadow root and click it when the tooltip is clicked. Creating the tag and clicking it is considered a trusted user interaction since it's called inside the original click event listener
Demo at https://stories-demos-matias.web.app/examples/amp-story/analytics.html#page=p3. Clicking on the bottom and top links adds the cid to the url
Closes #32060

🐛  Use anchor tags outside tooltip for linking

---

extensions/amp-inline-gallery/amp-inline-gallery.md
extensions/amp-lightbox/amp-lightbox.md
extensions/amp-selector/amp-selector.md
extensions/amp-stream-gallery/amp-stream-gallery.md

Incorporate format changes from #31944 to the following Bento components which expose an API:
- `amp-selector`
- `amp-lightbox`
- `amp-inline-gallery`
- `amp-stream-gallery`

📖  Add imperative API code samples to Bento component documentation

---

src/utils/media-query-props.js
test/unit/utils/test-media-query-props.js

Partial for #30719.
This PR restores the parser from https://github.com/ampproject/amphtml/pull/31948/files#diff-9eb1c00413eabb4d404cf58e8a43343e7602e54fcf2a67fab82073da72fb00b5L43 and transfers relevant tests.
Fixes https://github.com/ampproject/amphtml/issues/32246

Restore SizeList media query parser

---

extensions/amp-viewer-integration/0.1/messaging/messaging.js
extensions/amp-viewer-integration/0.1/messaging/package.json
src/amp-story-player/amp-story-player-impl.js

Follow up for #32076
We were importing `urls` from AMP, which isn't available when doing npm install. This PR sends the regex as a parameter.
~~Question for @jridgewell : is calling `const env = self.AMP_CONFIG || {};` in the npm package safe?~~

[amp-viewer-integration] Don't import from AMP, use regex as constant

---

extensions/amp-accordion/1.0/amp-accordion.css

Partial for #32155.
A bit of a hack, but it works. The goal is to disallow `:where()` selector to be combined with other selectors, which breaks some older browsers. A better solution would have been to use `@supports selector`, but it's not yet supported by PostCSS. See https://github.com/postcss/postcss/issues/1520

Prevent :where selector from being optimized with other selectors

---

build-system/pr-check/build-targets.js
build-system/tasks/check-exact-versions.js
third_party/amp-toolbox-cache-url/package.json
validator/js/webui/package-lock.json
validator/js/webui/package.json

We currently check select `package.json` files in the repo for exact versions in order to streamline version upgrades and make test results predictable.
This PR extends that check to all `package.json` files in the `amphtml` repo and fixes a couple of files with non-exact versions.

🏗 Run the exact version check on all `package.json` files in the repo

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Partial for #30291.
Aspect Ratio CSS has launched in Chrome 88.

Launch layout-aspect-ratio-css to 1%

---

ads/google/a4a/sticky-ad-transition-exp.js
extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
extensions/amp-ad/0.1/amp-ad-ui.js
extensions/amp-ad/0.1/amp-ad.css
extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
extensions/amp-ad/0.1/test/test-amp-ad-ui.js
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css

Restart https://github.com/ampproject/amphtml/pull/31491
Added back a few applyFillContent to fix responsive ad issue. The rest of the changes are experiment covered.

Implement sticky ad, experiment for css changes

---

extensions/amp-date-countdown/amp-date-countdown.md

Add Bento documentation for amp-date-countdown

Add Bento documentation for amp-date-countdown

---

extensions/amp-list/0.1/amp-list.js
extensions/amp-list/0.1/test/test-amp-list.js

The current error message isn't super helpful to developers.
XHR/template proxying is an implementation detail that developers
shouldn't care.
The new messages follow similar error messages in the non-proxying path.
/to @caroqliu 
/cc @bill97819

Improve amp-list error messages for proxied XHRs

---

build-system/pr-check/build-targets.js
build-system/pr-check/bundle-size.js
build-system/pr-check/checks.js
build-system/pr-check/cross-browser-tests.js
build-system/pr-check/e2e-tests.js
build-system/pr-check/module-build.js
build-system/pr-check/module-tests.js
build-system/pr-check/nomodule-build.js
build-system/pr-check/nomodule-tests.js
build-system/pr-check/unminified-build.js
build-system/pr-check/unminified-tests.js
build-system/pr-check/visual-diff-tests.js
build-system/tasks/pr-check.js
build-system/tasks/report-test-status.js

- Add new targets `PRESUBMIT`, `LINT`, and `PRETTIFY` so these checks are run only if necessary
- Remove the obsolete `FLAG_CONFIG` target and roll it into `RUNTIME` (flag config changes will run all runtime tests)
- Add `nonRuntimeTargets` to ensure that the runtime is tested for all files that may affect it (logic is now more transparent)
- Optimize order of checks so that faster running ones run first (fail-fast)
- Add logging to explain that all tests will be run during CI when packages are upgraded
- Fix an old function rename bug in `pr-check.js` (`stopTimedJob` -> `abortTimedJob`)
With these changes, CI will run significantly faster for smaller PRs (e.g. only docs files)

🏗 Optimize the running of various checks during local dev and CI builds

---

build-system/tasks/analytics-vendor-configs.js
build-system/tasks/extension-helpers.js
build-system/tasks/unit.js
extensions/amp-analytics/0.1/test/test-vendors.js
gulpfile.js

We are adding a vendor config building step for ads, therefore it seems proper to rename the analytics build task to one with analytics name in it.

Rename vendor-configs target to analytics-vendor-configs

---

.circleci/config.yml
.circleci/fetch_merge_commit.sh

- **Fix CircleCI workflow name:** Not all workflows are PR builds (some are push builds), so remove the suffix from the name. This also saves space on the GH commit status message.
- **Fix branch filtering for PR builds:** Not all branches are of the form `pull/12345`. Some are of the form `foo-patch-1`, etc. Instead of an include list, simply ignore the `nightly` branch and build all other branches. (`nightly` always reuses existing `master` commits, so we don't want a new build when it's updated.)
- **Fix merge commit fetching logic:** For PRs originating from branches on the main repo (e.g. `foo-patch-1`), extract the PR number from an env var before fetching the merge commit.
Follow up to #32095

🏗  CircleCI config fixes

---

css/ampshared.css

#28535 causes layout shift in `[placeholder]` elements. This PR resets these styles much like we did for `[overflow]` elements.

Reset line-height:0 for placeholder elements

---

ads/vendors/ssp.js
test/unit/ads/test-ssp.js

Fixes inside 3P ssp.js module includes:
multiple XHR request fix (canceling / failing when one of ad units call noContentAvailable())
better behaviour for layout="responsive" (sizing / positioning)
minor refactoring

🐛♻️ ADS: XHRs race condtion and responsivnes fix

---

build-system/test-configs/dep-check-config.js
extensions/amp-video-docking/0.1/amp-video-docking.css
extensions/amp-video-docking/0.1/amp-video-docking.js
extensions/amp-video-docking/0.1/def.js
extensions/amp-video-docking/0.1/math.js
extensions/amp-video-docking/0.1/test/test-amp-video-docking.js

- 🖍   Previously the video element would lag behind when using `position: fixed` at undock. `position: absolute` follows the video as it scrolls, eliminating the lag.  (This was backported from Bento version.)
- 🚀  Use existing `clientRect` where possible to prevent `getBoundingClientRect()` calls.
- 🚀  Migrates to `IntersectionObserver`.
---
**Before / after** (at 0.75 speed)
https://user-images.githubusercontent.com/254946/106031359-0756a300-6084-11eb-8bab-7cbe1f769313.mp4
(Tip: right click > `Loop`)

🖍🚀 Alternate `position: fixed/absolute` when docking/undocking

---

.circleci/config.yml

AMP's Karma tests persist their babel transforms in `.karma-cache`. We lost the ability to cache the directory on Travis due to https://github.com/ampproject/amphtml/pull/28834#discussion_r438964074. This PR reintroduces caching for the directory on CircleCI.
Results are great. We shave off ~30 secs from integration test runs, and ~5 mins from unit test runs. 
**[Cold cache:](https://app.circleci.com/pipelines/github/ampproject/amphtml/780/workflows/6b19ea42-a351-4109-8179-70b1349757f8)**
**[Warm cache:](https://app.circleci.com/pipelines/github/ampproject/amphtml/780/workflows/fe50f44f-7da5-4aa9-8b58-a3a9760c584c)**
**Coming up:** Caching for babel transforms in end-to-end tests.

🏗 Cache Karma's babel transforms during CircleCI builds

---

extensions/amp-form/0.1/amp-form-textarea.js

Fixes https://github.com/ampproject/amphtml/issues/32291 and `b/150231440`
Related: https://bugs.chromium.org/p/chromium/issues/detail?id=1171989

Fix <textarea> scrollHeight calculation

---

build-system/common/browserify-cache.js
build-system/common/logging.js
build-system/tasks/e2e/mocha-dots-reporter.js
build-system/tasks/runtime-test/runtime-test-base.js
build-system/test-configs/karma.conf.js

Browserify caching was introduced in https://github.com/ampproject/amphtml/pull/28157#issue-412022994. It had to be disabled on Travis in https://github.com/ampproject/amphtml/pull/28834#discussion_r438964074, but was reintroduced on CircleCI in https://github.com/ampproject/amphtml/pull/32295#issue-563733319.
This PR cleans up the caching code and moves it into its own file. It also moves `karma.conf.js` to `build-system/test-configs/`.

🏗 Reorganize browserify caching code

---

build-system/pr-check/build-targets.js

Our build-system contains an [optimization](https://github.com/ampproject/amphtml/pull/32257/files#diff-19e974deb1e4e50db022e0a4c6b920052ff4bb12bf4382375fa2387aa012104cR309) to prevent CI builds from running the whole slew of runtime tests against PRs that are known not to affect the runtime. E.g. Docs-only changes.
There's a bug in the optimization due to the use of `element in array` instead of `array.includes(element)`:
```js
// Correct
['foo', 'bar', 'baz'].includes('foo') // true
// Incorrect
'foo' in ['foo', 'bar', 'baz'] // false
```
With this fix, CI will run much faster for PRs like #32304.

🏗  Fix bug in build target discovery logic

---

.circleci/config.yml

Experiment but worth considering.

🏗 Remove Browser Installation from CI tasks and use smaller instances when possible

---

.circleci/fetch_merge_commit.sh
.circleci/setup_storage.sh
.github/workflows/cross-browser-tests.yml
.github/workflows/install_dependencies.sh

- GH actions environment setup and dependency installation now lives in `workflows/install_dependencies.sh`
- Remove `node-version` from GH Actions config (it's disregarded and LTS is used anyway)
- Shorten GH actions commit status name (so there's more space for details)
- Clean up comments in script files
- https://docs.npmjs.com/cli/v6/commands/npm-config
- https://docs.npmjs.com/cli/v6/commands/npm-prefix
- https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path

🏗 Clean up CI config files

---

extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.js

Closes #32106:
If you navigate fast on a player on the dev-tools, a second navigation on user input might get reported before a first navigation on the other players due to the programmatic navigation, so the programmatic advancement can trigger an endless loop of players updating each other between those two pages.
**Fix:** Skip the navigation events that are expected from when an API call was made. Each player will have a list of the navigation calls done that were not surfaced yet, adding a pageId to the list when calling `.show` and removing the pageId when receiving the `storyNavigation` event. If an event is not in the list, it must be a user interaction, so we propagate it to the other players.
Edge cases: If an unloaded player receives a `.show` event but is not ready to pass to …

🐛 [Story devtools] Fix player loop with timestamp

---

src/amp-story-player/amp-story-player-impl.js
test/e2e/test-amp-story-player-prerender.js
test/unit/test-amp-story-player.js

Introduces `render()` method which consolidates a lot of the logic from different methods, effectively reducing the amount codepaths.
Follow up for #32115
Closes #31212
Closes #31010
Related:
#31925
#31445
#31738

[amp-story-player] Introduce render() method ♻️

---

.github/workflows/cross-browser-tests.yml
build-system/pr-check/cross-browser-tests.js
build-system/tasks/report-test-status.js

**Three things that need to be fixed in our GH Actions jobs:**
- Installing dependencies can be slow (e.g. it took >5 mins during [this Windows job](https://github.com/ampproject/amphtml/pull/32176/checks?check_run_id=1809656940))
- We build the runtime, then run integration tests, and only then unit tests (simple test failures are slow to surface)
- CircleCI jobs aren't pre-reporting expected test statuses, which is currently gated on `isTravisBuild()` 
- Add a caching step for dependency installation
- Reorder steps to first run unit tests, then build the runtime, then run integration tests (fail-fast)
- Gate pre-reporting of test statuses on `!isCircleciBuild()` so it works on GH actions and Travis
**Results:** Seeing some decent gains in installation time. For …

🏗 Optimize GitHub Actions jobs

---

extensions/amp-accordion/amp-accordion.md

The current validator rules don't allow new AMP extension versions for
the email format by default.
/to @caroqliu @krdwan

📖  Remove email as supported format of accordion 1.0

---

.circleci/config.yml

This PR prevents AMP's CircleCI workflow from running unless the repo URL is `https://github.com/ampproject/amphtml`.
Until CircleCI fixes their bug and stops responding to duplicate webhooks from forks of `ampproject/amphtml`, this should block bogus builds [like this](https://app.circleci.com/pipelines/github/ampproject/amphtml/931/workflows/7b75d63b-bd10-4e1c-8f94-1e07410637c9) from being created (even if they are triggered by webhooks).
- https://circleci.com/docs/2.0/pipeline-variables
- https://circleci.com/docs/2.0/pipeline-variables/#conditional-workflows
- https://circleci.com/docs/2.0/configuration-reference/#logic-statements

🏗 Trigger CircleCI builds only for `ampproject/amphtml`

---

build-system/tasks/bundle-size/index.js

This should help shed light on cases when there's an unexpected size increase. (E.g. Maybe new commits have landed on `master`, causing the merge commit of a PR to affect sizes? Maybe there's a way to further fine-tune baseline selection?)

🏗 Log commit info during bundle-size checks

---

extensions/amp-video/0.1/amp-video.js

Context #32323
In a story with more than 8 videos, the next videos won't play. 
This bug was introduced in #31976, where `amp-video` introduces a `detachedCallback()` which calls `this.updateIsPlaying_(false)`;
In stories the media pool recycles videos (detaches and re-attaches same video elements in the DOM), which means that whenever a video is detached from the DOM it will call `this.updateIsPlaying_(false)` and `unobserveDisplay()`. This last one is causing videos to not play.

🔥 [amp-video] Don't update isPlaying if managed by stories

---

extensions/amp-base-carousel/validator-amp-base-carousel.protoascii
validator/testdata/feature_tests/doctype_lang.html
validator/testdata/feature_tests/doctype_lang.out
validator/testdata/feature_tests/doctype_lang.out.cpponly
validator/testdata/feature_tests/newline_attributes.html
validator/testdata/feature_tests/newline_attributes.out
validator/validator-main.protoascii

covers 354149380 to 355170607
- cl/355043682 n/a
- cl/354600080 Revision bump for #32288
- revert duplicate controls
- cl/354593816 Revision bump for #32262
- cl/354558578 Deprecate `lang` attribute on `doctype`.
- cl/354149380 Revision bump for #31873

Validator rollup 20210202

---

.github/workflows/cross-browser-tests.yml

AMP's GitHub actions workflow is designed to run on PRs and pushes _to_ `ampproject/amphtml`. However, it isn't designed to run for PRs _from_ `ampproject/amphtml` to other forks. Doing so can mess with our custom apps. Example: [this build](https://github.com/ConnectionMaster/amphtml/runs/1816726939?check_suite_focus=true#step:5:1010) on some other fork.
This PR adds a rule so the workflow only runs for PRs and pushes to our repo.
- https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
- https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

🏗  Run GH actions workflow only for `ampproject/amphtml` PRs and pushes

---

extensions/amp-date-countdown/amp-date-countdown.md
extensions/amp-fit-text/amp-fit-text.md
extensions/amp-inline-gallery/amp-inline-gallery.md
extensions/amp-instagram/amp-instagram.md
extensions/amp-lightbox/amp-lightbox.md
extensions/amp-selector/amp-selector.md
extensions/amp-stream-gallery/amp-stream-gallery.md
extensions/amp-timeago/amp-timeago.md
extensions/amp-video/amp-video.md
extensions/amp-youtube/amp-youtube.md

In addition to helping code snippets be more readable in their language, I assume this change will help that some of the code snippets are not correctly escaping, like this `[/example]` here: https://amp.dev/documentation/components/amp-inline-gallery-v1.0/?format=websites#example
This assumption is based off of #32285 fixing the above problem for `amp-base-carousel`.

📖 Add syntax highlighting in Bento documentation code snippets

---

.circleci/config.yml

Reverts ampproject/amphtml#32346
Reason for revert: https://github.com/ampproject/amphtml/pull/32346#issuecomment-771849006

Revert "🏗 Trigger CircleCI builds only for `ampproject/amphtml`"

---

build-system/test-configs/karma.conf.js
package-lock.json
package.json

We use [`karma-simple-reporter`](https://www.npmjs.com/package/karma-simple-reporter) to print inline error messages in real-time during tests. It [depends on an ancient version](https://github.com/guyius/karma-simple-reporter/blob/f0d83a06f5485d9d826da5e7d28717b800110520/package.json#L8) of `karma`, whose transitive dependencies print numerous warnings during package installation on Windows. See [these logs](https://github.com/ampproject/amphtml/runs/1818483413?check_suite_focus=true#step:4:44):
`karma-simple-reporter` was originally forked from [`karma-spec-reporter`](https://www.npmjs.com/package/karma-spec-reporter), a plugin that [uses the current version](https://github.com/mlex/karma-spec-reporter/blob/f78dd34f668bc45c8152aa1669b7f8a79fc6cb09/package.json#L24-L26) of `karma`, and …

🏗 Replace `karma-simple-reporter` with `karma-spec-reporter`

---

validator/testdata/feature_tests/svg-filter-primitive-elements.html
validator/testdata/feature_tests/svg-filter-primitive-elements.out
validator/validator-main.protoascii
validator/validator-svg.protoascii

Fixes #32329.
Allow more SVG filter primitive elements
```
<feBlend>
<feComponentTransfer>
<feConvolveMatrix>
<feDiffuseLighting>
<feDisplacementMap>
<feDistantLight>
<feDropShadow>
<feFuncA>
<feFuncB>
<feFuncG>
<feFuncR>
<feMorphology>
<fePointLight>
<feSpecularLighting>
<feSpotLight>
<feTile>
<feTurbulence>
```

Allow more SVG filter primitive elements

---

extensions/amp-story-panning-media/0.1/amp-story-panning-media.js

Prevents animation from running when:
-  previous value has not been set
- `prefers-reduced-motion` is enabled on the OS
[Demo](https://panning-media.web.app/examples/amp-story/amp-story-panning-media.html)
[About reduced motion / how to enable it](https://web.dev/prefers-reduced-motion/)
context / Fixes #32320
context / Fixes #32282

✨ [Panning media] Early return to not animate

---

build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/ignore-unrelated-exports/input.js
build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/ignore-unrelated-exports/options.json
build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/ignore-unrelated-exports/output.mjs

**summary**
Lines unrelated to `createUseStyles` and the JSS calculation should be unaffected by the transform
Verify / addresses a concern from https://github.com/ampproject/amphtml/pull/32365/files#r569678476

jss transform test: unrelated lines unaffected

---

src/amp-story-player/amp-story-component-manager.js
src/amp-story-player/amp-story-player-viewport-observer.js
test/e2e/test-amp-story-player-prerender.js
test/e2e/test-amp-story-player.js
test/unit/test-amp-story-player-viewport-observer.js

If Player is not visible in the first viewport, do not load the first story nor prerender it at first so it does NOT impact the LCP.
On first user scroll, prerender the Story, and switch it to visible when it becomes visible in the current viewport

[amp-story-player] Prerender first story on scroll

---

extensions/amp-fit-text/1.0/base-element.js
extensions/amp-fit-text/1.0/component.js
extensions/amp-fit-text/1.0/component.jss.js

We moved to JSS after this component was implemented, so this PR brings the style-setting process up to date for this component. Partial for #28281

🖍 Bento: Move amp-fit-text to shadowCss

---

.circleci/check_config.sh
.circleci/config.yml

During CircleCI PR builds, we [fetch the merge commit](https://github.com/ampproject/amphtml/blob/master/.circleci/fetch_merge_commit.sh) of the PR branch with `master` so that code is tested against all recent changes.
However, since the CircleCI config is loaded before the merge commit is fetched, the PR could be using an outdated version of the config file. The risk of allowing the build to proceed is that if a new testing step were added to the config file in an upstream change, it won't be applied to the PR.
Other CI services use the `master` merge commit for PR builds, so they don't have this problem.
- Add a check to make sure that a PR branch contains the latest changes to the CircleCI config file
- If not, print a message asking for the PR …

🏗 Check if PR branches contain the latest CircleCI config file

---

.circleci/fetch_merge_commit.sh
build-system/common/ci.js

**Description edited by `rsimha`:**
CircleCI's PR builds have the `CIRCLE_PULL_REQUEST` and `CIRCLE_PR_NUMBER` env vars set, while push builds are supposed to have neither.
AMP's push builds are incorrectly getting the `CIRCLE_PULL_REQUEST` env var set due to a bug in CircleCI's use of APIs.
This PR switches our PR build detection code to using `CIRCLE_PR_NUMBER`, which isn't being erroneously set. With this, our `master` commits should actually build fully while CircleCI fixes the API bug on their side. The builds could still be linked to a PR on an external fork if it references the commit (something that CircleCI is working on fixing).

Attempt to fix Circle push builds

---

.circleci/check_config.sh
.circleci/fetch_merge_commit.sh
build-system/common/ci.js

CircleCI PR builds for PRs originating from forks have the `CIRCLE_PR_NUMBER` environment variable. However, a PR originating from an upstream branch (directly created on `ampproject/amphtml`) does not. Yet, we want to run a PR build on the branch because it is neither `master` nor `amp-release-*`. We also want to fetch the merge commit for the branch if available.
- Rewrite the push build detection logic in `ci.js` and `fetch_merge_commit.sh` to check for `master` or `amp-release-*`
- Attempt to fetch the merge commit if the upstream branch is linked to a PR (will accurately test older branches)
- If the branch is not yet linked to a PR, test the branch as-is (since it was most likely just created)
**Main use cases:**
**[Upstream PR branch, PR not yet …

🏗 Refine PR / push build detection logic for upstream branches

---

build-system/pr-check/bundle-size.js
build-system/tasks/pr-deploy-bot-utils.js
build-system/tasks/report-test-status.js

Signals for bundle-size, test-status, and pr-deploy are sent from Travis but not CircleCI in order to prevent duplication.
This PR switches the signaling to CircleCI. Once we merge and observe for several builds, we can make CircleCI a blocking check.

🏗 Switch signaling for bundle-size, test-status, and pr-deploy to CircleCI

---

extensions/amp-analytics/amp-analytics.md

Closes #30940 
Document that variables are fulfilled async--which could affect collection of CWV.

📖 [amp-analytics] Document async var resolutions (in relation to CWV)

---

build-system/externs/amp.multipass.extern.js
extensions/amp-facebook/0.1/test/test-amp-facebook.js
extensions/amp-image-lightbox/0.1/test/test-amp-image-lightbox.js
extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
extensions/amp-video/0.1/test/test-amp-video.js
src/common-signals.js
src/custom-element.js
src/element-stub.js
src/service/custom-element-registry.js
test/unit/test-custom-element-registry.js
test/unit/test-custom-element.js
test/unit/test-friendly-iframe-embed.js

This is a fragment of the #32002 refactoring. The `ElementStub` is no longer created until upgraded class is available.

Avoid creation of ElementStub until the upgrade class is available

---

spec/amp-story-player.md
src/amp-story-player/amp-story-player-impl.js
test/unit/test-amp-story-player.js

There will be some cases where publishers will create the player element dynamically and it will start not appended to the DOM. In these cases, when the iframe is not appended to the DOM, it will not have a `iframeEl.contentWindow`, which the messaging library uses to establish the communication.
With this PR, we will throw an error when trying to call `load()` before the player is appended to the DOM.

[amp-story-player] Throw error when trying to call load() on player that isn't attached to the DOM

---

build-system/tasks/e2e/describes-e2e.js

When attempting to run the e2e tests using safari the driver was never being constructed so the tests would not run.
Unfortunately safari does not support arguments like firefox and chrome, but the tests do run and pass now.
`gulp e2e --browsers=safari`
Fixes #24009

 🏗   ✅  🐛  Add safari web driver builder

---

.github/workflows/cross-browser-tests.yml

In #32429 and #32439, we tried caching `~/.npm` and `node_modules/` respectively in order to speed up package installation during CI builds. Neither approach really worked (see PRs for details).
As things stand today, running `npm ci` will rewrite `node_modules/` from scratch for each build. This PR removes the unnecessary caching step on GH Actions.
As a follow up, I'll read up some more on whether there's a more effective way of achieving caching without breaking packages (e.g. [this `@babel` error](https://github.com/ampproject/amphtml/pull/32439#issuecomment-773653012)).

🏗 Remove `node_modules` caching on GH Actions

---

.renovaterc.json
package-lock.json
package.json

Reverts ampproject/amphtml#32318
Reason for revert: This may have affected incoming renovate PRs. Will revert this and try https://github.com/ampproject/amphtml/pull/32384.

Revert "📦 Update dependency renovate to v24.34.2"

---

build-system/pr-check/cross-browser-tests.js
build-system/tasks/report-test-status.js

This PR runs E2E tests on Safari and Firefox on GH Actions. Trying out the suggestion in https://github.com/ampproject/amphtml/issues/24009#issuecomment-772030645.
We appear to have all-green E2E runs that finish in under a minute, but the really fast running times make me wonder if the tests are actually being executed. **Edit:** They are. The fast tests are all unit tests for the E2E framework.
**Safari:** [169 tests in 50s](https://github.com/ampproject/amphtml/runs/1834887271?check_suite_focus=true#step:5:305)
**Firefox:** [165 tests in 30s](https://github.com/ampproject/amphtml/runs/1834887236?check_suite_focus=true#step:5:314)
Don't know if we actually want to merge this, but I figured it's worth reviewing. **Edit:** Given the fast runs and the fact that we're already building the …

🏗  Run E2E tests on Safari and Firefox

---

extensions/amp-iframe/0.1/amp-iframe.js
extensions/amp-iframe/0.1/test/test-amp-iframe.js

**summary**
Should not call unlayout if has owner element has owner.
Fixes: https://github.com/ampproject/amphtml/issues/32449, caused by https://github.com/ampproject/amphtml/pull/31976

fix overly eager iframe unload() call

---

build-system/test-configs/dep-check-config.js
extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js
extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js

Introduces a new method `skipClientSideValidation(headers)` that ad networks can override with whatever header they choose to fall back to x-domain without trying to validate.
Changes doubleclick and adsense impls to only try validation if `AMP-Fast-Fetch-Signature` header exists.

✨[no-signing] Allow creatives to opt out of client side validation

---

extensions/amp-smartlinks/0.1/amp-smartlinks.js
extensions/amp-smartlinks/0.1/linkmate.js
extensions/amp-smartlinks/0.1/test/test-amp-smartlinks.js
extensions/amp-smartlinks/0.1/test/test-linkmate.js

@ampproject/wg-components fixes #32188
'window.location.href' allows you get the url of the current article url, regardless of whether your current article doc is a shadow doc or a single doc. Similarly, 'document.getElementsByTagName("title")[0].text' will grab the title of the current article, regardless of whether your current article doc is a shadow doc or a single doc.
These changes are needed to correctly populate the payloads for the Linkmate API call and the page impression API call that indicates a page load event has happened.
/cc @dvoytenko

🐛 getUrl fix enabling shadow docs to have access to the article url and name #32188

---

.eslintrc.js
OWNERS
package-scripts.js

This PR introduces a way to run `npm` scripts without adding them to `package.json`. Scripts are defined in `package-scripts.js` and run using [`nps`](https://www.npmjs.com/package/nps) (short for `npm-package-scripts`).
This will prevent us from going back to a situation like this:
https://github.com/ampproject/amphtml/blob/ee2dea74e954ceaf5c284bfbfb2f81416858fa9a/package.json#L17-L26
**Usage:**
```sh
npm i -g nps
nps filesize
```
**Example:**
Addresses https://github.com/ampproject/amphtml/pull/32476#discussion_r571330400

🏗 Add a way to run NPM scripts that live outside `package.json` (via `nps`)

---

ads/google/adsense.md

The [CSA AMP ad type] link in the documentation had not been updated, so I fixed it.
I looked to check if there were any others, but this was the only one.
That's when the path changed: https://github.com/ampproject/amphtml/commit/71ed0fc161cc9f256932ec24cfaf46fabb7b772c#diff-4620745fb7a4065006a431a9475478f212dbe5867f07639fbac1e9f3f1f07986

📖 Fix link to csa in document

---

build-system/common/check-package-manager.js

If `which` is supported, this uses a similar check as `npm list --global --depth 0`.
This saves (maybe just me) 10s each invocation.

🏗 Removes gulp warning non-global installations via npm

---

build-system/babel-plugins/babel-plugin-transform-jss/index.js
build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/ignore-unrelated-exports/output.mjs
build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-jss-var/output.mjs
build-system/babel-plugins/babel-plugin-transform-jss/test/fixtures/transform-assertions/should-transform-literal/output.mjs
build-system/tasks/babel-plugin-tests.js
build-system/tasks/css/index.js
build-system/tasks/css/init-sync.js
build-system/tasks/css/jsify-css-sync.js
build-system/tasks/css/jsify-css.js
build-system/tasks/extension-helpers.js
package-lock.json
package.json

#30206 added a `babel` plugin for JSS transforms via `postcss`. Since `babel` is sync but `postcss` plugins are async, the PR used a `child_process` hack. See https://github.com/ampproject/amphtml/pull/30206#discussion_r487310574 for the gory details. Under a profiler, each transform takes 2-3s to execute.
This PR adds a [`sync-rpc`](https://www.npmjs.com/package/sync-rpc) wrapper to the transform function. It too uses a `child_process`, but the overhead is paid for just the first call. Every subsequent transform executes in < 50ms. Gains will be higher as the number of JSS transforms increases.
**Time spent by `gulp dist` on transforms:**
**Before:** 8%.
**After:** 1%.
Addresses https://github.com/ampproject/amphtml/pull/30206#issue-485410038

🏗🚀 Provide a way to synchronously transform CSS in Babel

---

src/utils/display-observer.js
test/unit/utils/test-display-observer.js

Closes #32487.
These rules come from the [Resources class](https://github.com/ampproject/amphtml/blob/8f5f944ca3ed12c919397b0dc6a93edacf26ce61/src/service/resources-impl.js#L1871-L1895). Notice that only "paused" and "inactive" cause transitions to `pause()`.

Display-observer: a hidden tab should still be displayable for playback

---

build-system/tasks/bundle-size/index.js
package-lock.json
package.json

This PR replaces the custom logging in `gulp bundle-size` with the built-in output from `filesize`. With this, we standardize bundle-size output as follows:
**Local development:**
**CI builds:**
Companion PR to https://github.com/ampproject/filesize/pull/127
Addresses https://github.com/ampproject/amphtml/pull/32476#discussion_r571330400

🏗 Replace logging in `gulp bundle-size` with output from `filesize`

---

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
extensions/amp-subscriptions/0.1/amp-subscriptions.js
extensions/amp-subscriptions/0.1/analytics.js
extensions/amp-subscriptions/0.1/crypto-handler.js
extensions/amp-subscriptions/0.1/local-subscription-platform-base.js
extensions/amp-subscriptions/0.1/platform-store.js
extensions/amp-subscriptions/0.1/service-adapter.js
extensions/amp-subscriptions/0.1/subscription-platform.js
extensions/amp-subscriptions/0.1/test/test-amp-subscriptions.js
extensions/amp-subscriptions/0.1/test/test-analytics.js
extensions/amp-subscriptions/0.1/test/test-local-subscription-rendering.js
extensions/amp-subscriptions/0.1/test/test-local-subscriptions.js
extensions/amp-subscriptions/0.1/test/test-platform-store.js
extensions/amp-subscriptions/0.1/test/test-service-adapter.js
extensions/amp-subscriptions/0.1/test/test-viewer-platform.js
extensions/amp-subscriptions/0.1/viewer-subscription-platform.js

This PR updates the `amp-subscriptions` and `amp-subscriptions-google` extensions to consistently refer to subscription platforms as "platforms" internally. After the this PR, subscription platforms would only be called "services" externally in configuration JSON, templates, etc
Context: I found the interchangeable use of "platform" and "service" in the code was pretty confusing. Between the two terms, "platform" seems much more descriptive, in my opinion

♻️ amp-subscriptions*: Consistently refers to subscription platforms as "platforms" internally

---

src/service/url-replacements-impl.js

Right now, a site using both amp-access and amp-subscriptions cannot access AUTHDATA from amp-subscriptions because amp-access wins.
This change allows amp-access and amp-subscriptions to coexist for the purpose of URL substitution by first checking subscriptions and then access. Users of amp-access can use namespaces to reduce the risk of conflict.

🐛 Make AUTHDATA fall back from subscriptions to access

---

build-system/tasks/presubmit-checks.js
src/custom-element.js
src/service/owners-impl.js
src/service/resources-interface.js
test/unit/test-custom-element.js
test/unit/test-owners.js

The code moved mostly verbatim from the Owners class to the CustomElement. This accomplishes a few objectives:
1. It reduces dependencies on `Owners` service and makes a `CustomElement` more isolated.
2. This makes it `Owners` service more defunct on its way to complete elimination.
3. The `CustomElement` will be able to support separate modes for  `ensureLoaded()` (current and deferred-build).
Alternative considered:
```
class CustomElement {
set loading(value) {...}
}
customElement.loading = 'eager';
```
That would seem like more in-line with the img's `loading` property. However, at this time it's easier to continue refactoring with the promisable function.

Move ensureLoaded to CustomElement from owners

---

build-system/pr-check/cross-browser-tests.js

Another follow up to #32443 that I should've done there. Hopefully third time lucky!

🏗 Fix skip logic for E2E tests on FF / Safari

---

build-system/global-configs/experiments-config.json
build-system/global-configs/experiments-const.json
src/ini-load.js
test/unit/test-ini-load.js

A version of whenContentLoaded without measurements

---

extensions/amp-subscriptions/0.1/platform-store.js
extensions/amp-subscriptions/0.1/test/test-platform-store.js

The Platform Store was potentially deleting too many entries in its `failedPlatforms_` list, whenever a previously failing platform resolved

🐛✅ amp-subscriptions: Fixes a `splice` bug in Platform Store

---

build-system/tasks/e2e/describes-e2e.js
build-system/tasks/e2e/index.js

**Two changes:**
- Conditionally load `istanbul-middleware` (its circular dependency warning can be avoided during non-coverage builds)
- Add a Ctrl+C handler (so E2E tests can be canceled if needed during local dev)

🏗 E2E test improvements

---

build-system/tasks/lint.js
src/ini-load.js

This PR enables the detection of `eslint` directives that have become unnecessary, and cleans up the one such instance in our code.
**Reference:** https://eslint.org/docs/developer-guide/nodejs-api#cliengine
Addresses https://github.com/ampproject/amphtml/pull/32397/files#r572619849

🏗 Remove and prevent unused eslint directives

---

build-system/pr-check/visual-diff-tests.js

They're already being run on CircleCI, and we're shutting off Travis soon.

🏗 Stop running visual diff tests on Travis

---

build-system/common/utils.js
build-system/tasks/visual-diff/index.js

This is the same (or close enough) version as the one used on Percy. Pinning this version of Chromium used on our CI to the same as the one used on Percy would help us avoid subtle visual bugs caused by lack of support for newer versions on either end
Related to #32461

🏗 Pin the Chromium version used by visual diff to 78.0.3904.0

---

test/integration/test-extensions-loading.js

The tests touched in this PR are [failing consistently in master](https://app.circleci.com/pipelines/github/ampproject/amphtml/1632/workflows/b015c46e-7d72-44d2-b858-03d61ce0d6a0/jobs/15686), due to `.i-amphtml-fit-text-content` not existing in the Bento version path. 
Note: If this PR is merged first we will not need #32581

Fix extensions loading integration tests in Experiment C

---

.circleci/check_config.sh
.circleci/config.yml
.circleci/fail_fast.sh
.circleci/fetch_merge_commit.sh
.circleci/install_dependencies.sh
.circleci/setup_storage.sh
.github/workflows/install_dependencies.sh
build-system/common/enable-git-pre-push.sh

This PR adds a step that early-exits the entire CircleCI workflow if a single job fails.
E.g. if an early step in the `Checks` job were to fail, we no longer spend several minutes building and testing the runtime in parallel jobs.
**Pros:**
- Workflow view makes it clear which job failed
- Logs from the failing job will show the error that caused the job to fail
- Unrelated parallel / subsequent jobs will be terminated early (significant savings of CPU minutes)
**Cons:**
- After fail-fast, the top-level workflow status is "canceled", not "failed" (by design, according to [this](https://support.circleci.com/hc/en-us/articles/360052058811-Exit-build-early-if-any-test-fails))
- Fail-fast behavior requires the use of an API token (set as a secure project-level environment variable) …

🏗 Add fail-fast behavior to CircleCI builds

---

extensions/amp-story/1.0/page-advancement.js

Closes #32258
There are still ways to circumvent the bottom 20% restriction for the amp-story-cta-layer. e.g. using `transform: translateY(-80%);`. 
This PR fixes this by checking if the click was in the bottom of the screen.  
Note that `amp-story-cta` adds `role="link / button"` to links & buttons respectively. So on `page-navigation.js` we currently consider this a "protected target" when checking `isProtectedTarget_()`, which returns early and prevents navigation.

[amp-story] Prevent clicks on top 80%

---

src/service/video-manager-impl.js
src/utils/intersection.js
src/viewport-observer.js
test/fixtures/3p-ad.html
test/integration/test-amp-ad-3p.js
test/unit/test-viewport-observer.js

**summary**
- When iframed we should likely always use `root:document` for InObs. Otherwise rootBounds=null.
- question: should default for `needsRootBounds` be true or false?
I recommend viewing the diff [without whitespace](https://github.com/ampproject/amphtml/pull/32402/files?w=1) changes

measureIntersection: use root=document

---

.circleci/check_config.sh
.circleci/config.yml
.circleci/fail_fast.sh
.circleci/fetch_merge_commit.sh
.circleci/install_dependencies.sh
.circleci/setup_storage.sh
.github/workflows/install_dependencies.sh
build-system/common/enable-git-pre-push.sh

In #32575, we added fail-fast behavior to CircleCI builds. See https://github.com/ampproject/amphtml/pull/32575#issue-570790371 for why this is a good idea.
The change was reverted in #32589 because failing fast during push builds could cancel steps that establish baselines for `master` commits (e.g. bundle-size, visual diff).
This PR reinstates #32575, but only for PR builds.
**Sample logs:**
- For PR builds, [fail-fast if a job fails](https://app.circleci.com/pipelines/github/ampproject/amphtml/1707/workflows/4df806e2-b6cf-4467-9275-aa6e9f031ec1/jobs/16429)
- For push builds, [don't fail-fast even if a job fails](https://app.circleci.com/pipelines/github/ampproject/amphtml/1708/workflows/b752c2d2-9ede-4064-b4bc-5bf50c7b4b5b/jobs/16431)

🏗 Add fail-fast behavior to CircleCI PR builds

---

test/integration/test-amphtml-ads.js

The ads tests in `test/integration/test-amphtml-ads.js` have been particularly flaky in the recent past. There is a long-standing issue to track this at #24421.
**Example failure logs:** https://app.circleci.com/pipelines/github/ampproject/amphtml/1726/workflows/1fb8f966-0e94-4f36-94b0-85a64339adc2/jobs/16647
This PR skips another of its tests because the flakiness is hampering development.
@ampproject/wg-monetization Could we prioritize fixing these tests during the upcoming fix-it week?

❄️ Skip flaky ads test

---

build-system/global-configs/canary-config.json
extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-a4a/0.1/name-frame-renderer.js
extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
extensions/amp-ad/0.1/amp-ad-3p-impl.js
src/experiments/ads-initial-intersection-exp.js
test/integration/test-amp-ad-3p.js

Followup to: https://github.com/ampproject/amphtml/pull/31753
cc @calebcordry.
Note for the reviewer: I've never written experiment diversion code before, so please review carefully
**blocked by**: https://github.com/ampproject/amphtml/pull/32402

Remove sync measurement from ad iframes: experiment

---

.circleci/config.yml
build-system/pr-check/experiment-tests.js
build-system/tasks/e2e/index.js
build-system/tasks/integration.js
build-system/tasks/report-test-status.js
extensions/amp-fit-text/0.1/test-e2e/test-amp-fit-text.js

This should help identify Experiment test failures before they hit `master`. Initially, we will probably see more PR job failures, but over time, our experiment code will be more solidly tested.
Addresses https://github.com/ampproject/amphtml/pull/32581#issuecomment-776813037

🏗 Run experiment tests during PR builds

---

.github/workflows/install_dependencies.sh
build-system/compile/log-messages.js

In #32539, we replaced `ansi-colors` with `kleur/colors`. 2 changes here:
- Clean up one stray use of `colors`
- Enable log coloring on GH actions (supported even though it's not TTY)
Follow up to #32539.
**Reference:** https://github.com/lukeed/kleur#conditional-support

🏗 Clean up log coloring, enable on GH Actions

---

.circleci/config.yml
.travis.yml
build-system/pr-check/experiment-build.js
build-system/pr-check/utils.js

In #32574, we added experiment tests to the PR build workflow so that AMP code could be more solidly tested before merge.
This PR splits the building and testing of experiments into two separate jobs. There are a few advantages:
- Tests (which run serially anyway) now use a lower power VM (5x cheaper), so saves $$
- Rerunning tests will not need a full rebuild, saving time and $$
- We can now deploy experiment code via PR deploy if we want to
It also removes the now inaccurate and no longer used `experiment` stage from Travis (we're shutting it down soon)
**Results:** [link](https://app.circleci.com/pipelines/github/ampproject/amphtml/1804/workflows/832075ee-60cf-49c8-8173-4173157b4b3c)
**Future work:** Speed up E2E tests #32616
Follow up to #32574

🏗 Split experiment builds and tests into separate jobs

---

builtins/amp-img.js
test/unit/test-amp-img.js

This is the first step in fixing #32629.
In Safari setting a `src` before a `srcset` on an image (even in the same microtask) will cause the browser to start requesting the contents of the `src` attribute.
This PR ensures the last attribute propagated from `amp-img` to `img` is the `src`.

🚀 Ensure src is the last propagated attribute for amp-img

---

extensions/amp-form/0.1/amp-form.js
extensions/amp-form/0.1/test/test-amp-form.js

**summary**
Fixes: https://github.com/ampproject/amphtml/issues/32577
Changelog:
- Surround call to analytics with try/catch s.t. an error with analytics won't get in the way of updating `<form>` state
- Analytics call to use cached ampdoc s.t. if the `<form>` is detached from DOM, it'll still function 
- Swap order of error flow so that form state is updated prior to analytics event
- Add unit test that fakes an analytics failure

amp-form: enable detached analytics & fix error flow

---

build-system/pr-check/build-targets.js
build-system/tasks/prettify.js
package-lock.json
package.json

This is another in a series of PRs that modernize our development tasks.
- Directly use the `prettier` [nodejs API](https://prettier.io/docs/en/api.html)
- Eliminate file streaming via `gulp.src`
- Remove the dependency `gulp-prettier`
- Update the `PRETTIFY` build target to include the check itself
Partial fix for #32585

🏗 Rewrite `gulp prettify` using the `nodejs` API of `prettier`

---

extensions/amp-analytics/0.1/instrumentation.js
extensions/amp-analytics/0.1/test/test-instrumentation.js

**summary**
Followup to https://github.com/ampproject/amphtml/pull/32578.
When a node is detached, we can't perform our standard analytics flow for it (which includes finding its window + ampdoc).
While I'm sure each individual instance where this could occur needs its own handling, we can at least throw a more specific error so that we can identify the issue correctly (as well as not spiral into other unrelated errors due to unexpected throws - like missing AMP_TOP etc.).
Example error:

analytics: bail out for detached targets

---

extensions/amp-list/amp-list.md

**summary**
Addresses https://github.com/ampproject/amphtml/pull/32601
Note: I've never heard of this rule `The bottom is within 15% of the height of the entire page and within 1000px of the end of the page.`

📖 amp-list docs: increase clarity of overflow section

---

build-system/common/utils.js
build-system/tasks/visual-diff/index.js

+ revert no-longer useful change to `installPackages` that was introduced in #32554
Proof that this works now: https://percy.io/ampproject/amphtml/builds/8835566/changed/501352751 ^_^

🏗 Fix incorrect Chrome version pinning for visual diff tests

---

validator/validator-main.protoascii

The absence of this layout in the spec allowlist seems like an
oversight because the email spec already allows intrinsic layout for
amp-carousel. The SVGs used for sizing intrinsic layout elements are
hardcoded by the AMP runtime, so there's no privacy or security
concerns.
This is discussed with the AMP for Email WG with mail.ru, Yahoo!
Mail and Gmail and the consensus is to allow this.
/to @honeybadgerdontcare 
/cc @ampproject/wg-amp4email 
WG meeting notes: https://docs.google.com/document/d/1lsG9svgClzfknEwWD8mMc7kf91N8RJhGrssNPc0lO9E/edit#bookmark=id.amayc9wwynok
This addresses the concern at https://github.com/ampproject/amp.dev/issues/4027#issuecomment-727250406.

✨ Allow <amp-img layout=intrinsic> for email spec

---

3p/frame.max.html
extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
src/3p-frame.js
test/unit/3p/test-3p-frame.js

This PR gets rid of the hard coded `integration.js`/`f.js`, and replace it with a URL that is assigned by AMP runtime. In addition, it moves script calls from HTML to the Javascript.
The risk here is that some 3p script might depend on `draw3p()` being ran within the container div or a specific script tag, but I see no sign any 3p integration actually does that. Tested several ads and 3p (facebook and twitter extensions) and all worked fine.
Pulling in @dvoytenko  do you see this being a problems with this?

♻️ Allow dynamically setting 3p bootstrap script

---

build-system/tasks/caches-json.js
build-system/tasks/get-zindex/get-zindex.test.js
build-system/tasks/get-zindex/index.js
build-system/tasks/performance-urls.js
build-system/tasks/presubmit-checks.js
build-system/tasks/server-tests.js

This is another in a series of PRs that modernize our development tasks.
- Remove `gulp` file streaming from `server-tests`, `presubmit`, `caches-json`, `performance-urls`, and `get-zindex`
- Opportunistic bugfixes:
- Make file I/O async where possible
- Add `bing` to the list of expected caches in `caches.json`
- Fail task on parsing errors in `caches-json` and `performance-urls`
- Minor logging cleanup
For easy reviewing (without whitespace-only changes), use this link: https://github.com/ampproject/amphtml/pull/32623/files?w=1
Partial fix for #32585

🏗  Remove `gulp` streaming from a few developer tasks

---

builtins/amp-img.js
test/unit/test-amp-img.js

🚀 Dont autogenerate sizes if the ssr image contains sizes already, or is ssr'd using a transformer

---

extensions/amp-lightbox/1.0/lightbox.js

useValueRef hook moved into shared utils at
`src/preact/component` (from: https://github.com/ampproject/amphtml/pull/32584)
Updating instance of `useValueRef` in lightbox

♻️ [bento] Update imports of useValueRef

---

build-system/babel-config/unminified-config.js
build-system/tasks/helpers.js
extensions/amp-bind/0.1/bind-expression.js
package-lock.json
package.json

This is another in a series of PRs that modernize our development tasks.
- Rewrite `gulp build` without file streaming
- Replace `browserify ` with `esbuild` and `@babel/core` for a considerable increase in speed
- Remove `gulp-regexp-sourcemaps`, `gulp-rename`, `gulp-sourcemaps`, `vinyl-source-stream`, and `watchify` 
**Results:** This brings down the time taken for a [full unminified build](https://app.circleci.com/pipelines/github/ampproject/amphtml/2058/workflows/cf6015b6-a8cf-48f3-8277-4ee497ef5567/jobs/21181/parallel-runs/0/steps/0-107) of AMP from ~5m to ~1m.
- https://esbuild.github.io/api/
- https://babeljs.io/docs/en/babel-core
Partial fix for #32585

🏗🚀 Rewrite and speed up `gulp build` using `esbuild` and `@babel/core`

---

build-system/babel-config/unminified-config.js
build-system/tasks/helpers.js

Two follow up changes to #32663:
- Remove the `if (transform)` code path from the custom `babel` plugin for `esbuild` (https://github.com/ampproject/amphtml/pull/32663#discussion_r577171120)
- Remove `babel-plugin-transform-remove-directives` for unminified builds (https://github.com/ampproject/amphtml/pull/32663#discussion_r577168201)

🏗 Follow up changes to `gulp build` rewrite

---

extensions/amp-sidebar/1.0/sidebar.js
extensions/amp-sidebar/1.0/sidebar.jss.js
extensions/amp-sidebar/1.0/storybook/Basic.amp.js
extensions/amp-sidebar/1.0/storybook/Basic.js
extensions/amp-sidebar/1.0/test/test-amp-sidebar.js

Sidebar tracker: https://github.com/ampproject/amphtml/issues/31366
Important Note: This PR represents a workaround to ensure overscroll-behavior works properly.  The workaround includes adding a large element as the child of the backdrop to force the scroll behavior on backdrop.  A bug has been filed with the chrome team here: https://bugs.chromium.org/p/chromium/issues/detail?id=1176733
Once the bug has been fixed in ALL MAJOR BROWSERS, the following fix should be implemented:
1. Set `overscroll-behavior` to `none` and `overflow` to `scroll` on both backdrop and sidebar elements.  Expected behavior is that the background does not scroll when scrolling on the sidebar or backdrop elements.
2. See if the bug fix has other requirements and implement as needed!
******
When inside of the …

✨ [bento][amp-sidebar] Prevent scrolling in background of sidebar

---

extensions/amp-story/1.0/media-tasks.js

When recycling a media pool element, its sources are removed and the LoadTask runs to reset it (buffered data, readyState, etc). It needs to run synchronously so the media element can't be used in a new context but with old data.

Run LoadTask synchronously.

---

css/ampshared.css
test/integration/test-css.js
test/unit/test-layout.js

This is remedies a situation allowed by the #27736. The overflow element should not distort size-defined elements, such as `layout=responsive`. It's a semi-breaking change, but realistically this shouldn't be an issue because the overflow is always recommended to be styled with `position:absolute` for these cases.

The overflow element must not distort size-defined layouts

---

build-system/babel-config/unminified-config.js
build-system/tasks/helpers.js

This moves the ESM->CJS conversion from Babel into esbuild, which should aid esbuild's tree-shaking (it can now analyze static import/export, instead of imperative require/exports.foo).

🏗️  Allow esbuild to handle esm->output format conversion

---

extensions/amp-iframe/0.1/amp-iframe.js
extensions/amp-iframe/0.1/test/test-amp-iframe.js

A partial revert of #31976.
Will be rolled forward by #32541 when other fixes are complete.

Revert display observer for amp-iframe until lightbox/offscreen is supported

---

3p/ampcontext-integration.js

There are currently no ad vendors using it, however it causes the entire https://github.com/ampproject/amphtml/blob/master/ads/_config.js file to be compiled into integration.js, contributing to  ~20KB.
For the per-vendor-built integration.js, it will approximately reduces the size by a half (50KB to 25KB)

♻️ Remove masterFrameAccessibleType in 3p integration

---

extensions/amp-sidebar/1.0/sidebar.js
extensions/amp-sidebar/1.0/test/test-amp-sidebar.js
extensions/amp-sidebar/1.0/test/test-sidebar.js

Sidebar tracker: https://github.com/ampproject/amphtml/issues/31366
******
Update 2/10
This is dependent on: https://github.com/ampproject/amphtml/pull/32584
On hold until dependency is completed!
******
When sidebar opens, attach an eventListener to check for the 'esc' key being pressed and close the sidebar if it is pressed.
How does this work?
1. `eventListener` gets attached once sidebar element is rendered (done via `useEffect` (async))
2. If it is clicked mid-animation, the `close` api will handle reversing the animation

✨ [bento][amp-sidebar] Allow esc key to close sidebar

---

extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js

Currently it just tags "TAG", making the error message hard to be traced.

doubleclick tag the namespace for error message

---

ads/_config.js
extensions/amp-ad/0.1/amp-ad-3p-impl.js
extensions/amp-ad/0.1/amp-ad.js
extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
extensions/amp-ad/0.1/test/test-amp-ad.js
src/3p-frame.js
test/unit/3p/test-3p-frame.js

With RTC support, custom remote.html is not really useful any more. No ad vendors are currently setting this attribute.

Remove remoteHTMLDisabled attributes from adConfig

---

examples/amp-story/player-amp.html
examples/amp-story/player-local-stories.html
examples/amp-story/player-with-button.html
examples/amp-story/player.html
extensions/amp-story-player/0.1/amp-story-player.md
extensions/amp-story-player/0.1/test/validator-amp-story-player-error.html
extensions/amp-story-player/0.1/test/validator-amp-story-player-error.out
extensions/amp-story-player/0.1/test/validator-amp-story-player-img.html
extensions/amp-story-player/0.1/test/validator-amp-story-player-img.out
extensions/amp-story-player/0.1/test/validator-amp-story-player.html
extensions/amp-story-player/0.1/test/validator-amp-story-player.out
extensions/amp-story-player/validator-amp-story-player.protoascii
spec/amp-story-player.md
validator/validator-main.protoascii

Context #30512
Replaces usages of the CSS variable with an `<img loading="lazy" amp-story-player-poster-img>` tag.
In preparation for dev preview of the player, we should clean up all the samples / docs before wide spread comms.
I'm holding off on updating the docs / samples of the AMP version until we address https://github.com/ampproject/amphtml/issues/30512#issuecomment-704511825

[amp-story-player] Replace poster img CSS variable with img el

---

extensions/amp-a4a/0.1/amp-a4a.js

Activeview is reported by an amp-analytics element created from the `x-ampanalytics` header. In #32446 I introduced a new feature that would optionally early exit for non-amp creatives, but if this happens before `a4a.extractSize` is called the analytics config never gets parsed, or created later.

🐛 [No signing] fix broken analytics

---

examples/amp-lightbox.amp.html
extensions/amp-lightbox/0.1/amp-lightbox.js
src/utils/display-observer.js
test/unit/utils/test-display-observer.js

See explainer [here](https://docs.google.com/document/d/15KpYsY0bXzPXxPDy2SyGc6VmOJ2rvvUB7-EWTTv4Xcc/edit#).

Support display observer in the lightbox

---

extensions/amp-selector/1.0/base-element.js

🐛 Bento Selector: Correctly deregister events in OptionShim

---

build-system/externs/amp.extern.js
build-system/test-configs/dep-check-config.js
extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js
src/service/real-time-config/real-time-config-impl.js
src/services.js
test/unit/test-real-time-config.js

Redo https://github.com/ampproject/amphtml/pull/32386
https://github.com/ampproject/amphtml/issues/32713 Ran into this issue, and this PR has it fixed. The root cause is that different amp-ad elements are incorrectly sharing the same service instance.

♻️ Move RTC manager to a service

---

build-system/tasks/visual-diff/index.js

Visual tests have been flaky of late because the Percy backend was using Chrome v78. We therefore pinned our CI to that version while running visual tests. Now, Percy has moved to v87.
This PR pins our CI to the current stable channel version v88. This will be the way to go until Percy agrees to regularly update to Chrome stable channel.

🏗 Sync Chrome version used by Visual tests with Percy backend

---

extensions/amp-base-carousel/amp-base-carousel.md

typo in the docs, fixes ampproject/amp.dev#4270

remove stray "That"

---

extensions/amp-vimeo/0.1/test/test-amp-vimeo.js

Fixes #32813
Code coverage increase from 47.12% to 58.65% (using `--coverage` flag with `gulp unit` on `test-amp-vimeo.js`).

✅  [amp-vimeo] add unit tests

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg.js

- i18n: Add es_AR translations (#1497)
- Removes extra console.log (#1496)
- Update dependency eslint to v7.20.0 (#1492)
- Showcase Regwall: Removes scroll disabling (#1494)
- i18n: Updates comments relating to compilation (#1493)
- Update babel monorepo to v7.12.16 (#1488)
- Update dependency rollup to v2.39.0 (#1490)
- Compile SwG Basic as part of compile.js. (#1486)
- Showcase Regwall: Renames strings (#1489)
- Update dependency mocha to v8.3.0 (#1487)
- Catches cancel errors in Meter Toast (#1485)
- Fixes referrer check in Showcase demo (#1482)
- Fix checktype errors in SwG basic code. (#1481)
- Remove @export to avoid closure error JSC_MISSING_EXPORT_SYMBOL_DEFINITION in AMP (#1484)
- Update dependency postcss to v8.2.6 (#1483)
- Adds new languages for Showcase Regwall, for reals
- …

SwG Release 0.1.22.149

---

css/ampshared.css

This change allows us to immediately display SSR images when they load, even if this occurs before JS load (or JS fails to load). Before, these images would be stuck behind the blurry image placeholder due to the z-index stacking.
Fixes https://github.com/ampproject/amphtml/issues/32387

Fix displaying hero images over blurry image placeholder

---

extensions/amp-list/0.1/amp-list.js
extensions/amp-list/0.1/test/test-amp-list.js

Currently the full URL is too long for Gmail since the URL includes
`__amp_source_origin`, which is the full data URL for the AMP document
itself. The long URL spams the JS console with unreadable log messages.
This follows the eliding pattern for the non-SSR path in xhr-impl:
https://github.com/ampproject/amphtml/blob/a0f71dfb0381e236d6c6be287549748838731467/src/service/xhr-impl.js#L111
/to @caroqliu

✨  Shorten URL in error messages

---

validator/js/webui/@polymer/webui-mainpage/webui-mainpage.html

Set htmlFormat and editor content individually.
Fixes #23088, allowing `htmlFormat=xxx` to be used with `url=xxx`.

✨Allow htmlFormat to be used with other hash params

---

build-system/common/diff.js
build-system/pr-check/checks.js
build-system/tasks/get-zindex/index.js
css/Z_INDEX.md

Successful `--fix` run: (truncated)
```diff
gulp get-zindex --fix
[10:10:23] Using gulpfile ~/git/amphtml/gulpfile.js
[10:10:23] Starting 'get-zindex'...
diff --git a/css/Z_INDEX.md b/css/Z_INDEX.md
index 437b768da..a1c673789 100644
--- a/css/Z_INDEX.md
+++ b/css/Z_INDEX.md
@@ -1,7 +1,9 @@
-Run `gulp get-zindex` to generate this file.
+Run `gulp get-zindex --fix` to generate this file.
| selector                                     | z-index    | file                                      |
-| -------------------------------------------- | ---------- | --------------------------------------- |
+| -------------------------------------------- | ---------- | ----------------------------------------- |
| .i-amphtml-expanded-mode amp-story-grid-lay  | auto       | …
```

🏗 Ensure that z-index table is up to date

---

.gitignore
build-system/babel-config/dep-check-config.js
build-system/tasks/clean.js
build-system/tasks/dep-check.js
package-lock.json
package.json

This is another in a series of PRs that modernize our development tasks.
- Rewrite `dep-check` with `esbuild` and `babel`
- Rewrite `getSrcs()`, which was only writing one file (and rename it to `getEntryPointModule()`)
- Rewrite `getGraph()` to use `esbuild` and `babel` (and rename it to `getModuleGraph()`)
- Clean up `flattenGraph()`
- Eliminate the use of `browserify`, `babelify`, `gulp.dest`, and `vinyl-source-stream`
- Delete `vinyl-source-stream` from `package.json` (others need more work)
**Reference:** https://esbuild.github.io/api/#metafile
Partial fix for #32585

🏗 Rewrite `dep-check` with `esbuild` and `babel`

---

extensions/amp-selector/1.0/amp-selector.css

This PR:
- Allows disabled, selected options to show an outline
- Allows selected options of disabled amp-selectors to show an outline
- Shows disabled options with 0.4 opacity so they are visually knowable as disabled (already non-clickable)
Partial for #28282
Prior to this change:
(Note: The second img looks selectable but is disabled, and "Option 3" is selected and disabled but does not look this way.)
After this change:
All disabled/selected/hybrid states are knowable visually

Bento Selector: Support hybrid selected/disabled state

---

examples/amp-story/interactives.html
extensions/amp-story/1.0/amp-story-page.js

Disable in-page CTAs from tabbing when they are not on an active page. When they are on an active page, they should have their original tabindex. We can store the original tabindex on `data-orig-tabindex` when a page is initialized, and update `tabindex` when it becomes active or inactive.
Adding `tabindex="-1"` to the pages directly does not prevent the children from being tabbed, so the direct `a` tags need to be affected

♿  [Story a11y] Make CTAs not tabbable when not on active page

---

build-system/tasks/bundle-size/index.js

The bundle-size GCP app is down, and this is preventing CI from working reliably.
This PR makes reporting non-blocking for CI. The status will still be missing, but an override approval can address that.
I'm thinking this PR should be permanent, since it decouples failures in one system (GCP) from another (CI).

🏗 Make bundle-size reporting failures non-blocking

---

build-system/server/lazy-build.js
build-system/tasks/helpers.js

**summary**
In watch mode, we should rebuild `v0.js` each time any of its dependents change. Similarly to extensions, the science here is inexact, and I'm watching the `src` folder as a heuristic for a dependency change.
In a followup PR, I plan on using the machinery in the bundlers to tell us exactly which files need to be watched.

watch src dir for v0.js

---

examples/visual-tests/amp-story/amp-story-tooltip.js
extensions/amp-story/1.0/amp-story-embedded-component.js
extensions/amp-story/1.0/amp-story-share-menu.css
extensions/amp-story/1.0/amp-story-share-menu.js
extensions/amp-story/1.0/amp-story.css

Contributes to #32493
Applies same pattern for close button in share menu and Twitter overlay.
- Uses `button` element
- Uses localized "close" string for `aria-label`
- Uses close button element reference in click event delegation

[ampproject/amphtml] ♿ [Story a11y] Accessible close button in share menu and Twitter overlay

---

build-system/tasks/integration.js

`buildRuntime` (which is run unless you specify `--nobuild` flag) does a full build system cleaning, which also wipes out the built `test-bin` directory. We need to compile the HTML fixtures _after_ it, so they're not immediately cleaned.
Fixes #32091

🐛🏗 Fix building HTML fixtures during integration tests

---

extensions/amp-onetap-google/0.1/amp-onetap-google.js

Closure fails to detect this, but `getRootNode()` returns `{!Document|!ShadowRoot}`. `ShadowRoot`s do not have a `createElement` method.
Fixes https://github.com/ampproject/error-reporting/issues/57.

Do not use getRootNode to create element

---

extensions/amp-inputmask/amp-inputmask.md

The sentence that explains the behavior of `mask-output="alphanumeric"` incorrectly describes this as the behavior for `mask-output="raw"`. Fixes #31079

📖  Fix amp-inputmask documentation of `mask-output`

---

extensions/amp-story/1.0/amp-story-page.js

Contributes to #32493
Sets completely empty `alt` tag on images by default.

[ampproject/amphtml] ♿ [Story a11y] Empty img alt tags

---

src/assert.js
test/unit/test-assert.js

Mirrors existing functionality in standalone assertion helpers

♻️ Attach firstElement and messageArray to assert errors

---

extensions/amp-analytics/0.1/instrumentation.js
extensions/amp-analytics/0.1/test/test-instrumentation.js

Reverts ampproject/amphtml#32637
Potential "fix" to https://github.com/ampproject/error-reporting/issues/54.
Setting this up in case we want to eventually merge, we'll have the CI predone.

Revert "analytics: bail out for detached targets"

---

.circleci/config.yml
build-system/pr-check/module-tests.js
build-system/pr-check/nomodule-tests.js
build-system/tasks/prepend-global/index.js
build-system/tasks/report-test-status.js

Fixes #25720:
* splits the `integration/module` and `integration/nomodule` tests on CircleCI to `integration/module-prod`, `integration/module-canary`, `integration/nomodule-prod`, `integration/nomodule-canary`
* Runs `Math.round()` on all experiment percentage ratios to remove any randomness from the tests
See the CircleCI build for this PR to see the results

🏗 Execute integration tests on both prod and canary config, with experiments derandomized

---

extensions/amp-story/1.0/pagination-buttons.css

Bring back `pointer-events: none` on mobile pagination buttons.
A patch to #32861

[ampproject/amphtml] ♿ [Story a11y] Pagination buttons mobile pointer-events patch

---

validator/js/engine/validator.js
validator/testdata/feature_tests/amp_layouts.html
validator/testdata/feature_tests/amp_layouts.out

Fixes #25320
Fixes the bug that the layout `fixed_height` and `FIXED-HEIGHT` were (incorrectly) parsed as the `fixed-height`.
Now the javascript validator is case-sensitive, and only accepts the exact layout value (such as `fixed-height`).

🐛Fix the bug that parseLayout ignores case and underscore

---

extensions/amp-redbull-player/0.1/test/test-amp-redbull.js

Fixes #32902 
This change increases code coverage in `amp-redbull-player` from 41.67% to 63.33%. 
(Measured using the `--coverage` flag with `gulp unit`)

✅ [`amp-redbull-player`] Add unit tests to increase coverage.

---

build-system/babel-config/unminified-config.js
build-system/tasks/build.js

**summary**
Allow `gulp build` to process `--esm` mode. This aligns it with dist build's definition of esm mode (less transpilation, and fewer polyfills).
Note: esbuild still outputs an IIFE and not `esm`. this is intentional and controlled via the [format](https://esbuild.github.io/api/#format) option.

gulp build: support esm

---

build-system/compile/bundles.config.extensions.json
build-system/compile/sources.js
build-system/tasks/helpers.js
build-system/tasks/update-packages.js
extensions/amp-a4a/0.1/test/test-friendly-frame-renderer.js
extensions/amp-a4a/0.1/test/test-friendly-frame-util.js
extensions/amp-shadow-dom-polyfill/0.1/amp-shadow-dom-polyfill.js
package-lock.json
package.json
src/base-element.js
src/friendly-iframe-embed.js
src/polyfills/custom-elements.js
src/preact/base-element.js
src/service/custom-element-registry.js
src/service/extensions-impl.js
test/fixtures/shadow-dom-element-polyfill.html
test/fixtures/shadow-dom-element.html
test/integration/test-shadow-dom-element.js
test/unit/preact/test-base-element-mapping.js
test/unit/test-custom-element-registry.js
test/unit/test-extensions.js
test/unit/test-friendly-iframe-embed.js
test/unit/test-polyfill-custom-elements.js
third_party/resize-observer-polyfill/ResizeObserver.install.js
third_party/resize-observer-polyfill/ResizeObserver.js

Partial for #30952.
1. The SD polyfill is not quite an AMP extension - it has a side-effect and has to be imported into the using window directly. I didn't find any other way to use it.
2. To accommodate - I added `importUnwrapped` in extensions service to allow direct window import instead of a usual AMP service.
3. The polyfill is loaded and installed before the first element that needs it is upgraded.
4. In order to be able to import the polyfill into the FIE's window, I had to expand the FIE's CSP rules. /cc @calebcordry 
5. Some lints are complaining about `this` in the static method, but I believe this particular use is correct.
TODO:

Shadow DOM polyfill for elements that need it

---

extensions/amp-accordion/1.0/base-element.js
extensions/amp-accordion/1.0/test/test-accordion.js
extensions/amp-accordion/1.0/test/test-amp-accordion.js

Accordion Tracker: https://github.com/ampproject/amphtml/issues/30445
Bug / Issue Link: https://github.com/ampproject/amphtml/issues/32549
Before defaulting the role attribute on the Header and Content sections to `button` and `region` respectively.  First check if an existing role attribute exists and use that value instead.
Works in both bento and amp / bento modes.  Includes tests.
How it works:
1. Check for `role` attribute on AMP side
2. Pass in the `role` attribute OR `undefined` if it does not exist to the Preact side to populate
3. If `undefined` Preact side will use default value.

✨ [bento][amp-accordion][fixit] Check for pre-existing role attribute before using default value

---

examples/visual-tests/amphtml-ads/amp-fie-static.html
test/visual-diff/visual-tests

Fallback within AMPHTML ad rendered in amp-ad is the source of the flakiness. Given that it is rarely used, it seems fine not being included.
https://github.com/ampproject/amphtml/issues/28975

❄️ Fix amphtml fie static visual diff

---

build-system/tasks/presubmit-checks.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js

- Moves all code inside a `describes` block.
- Removes any references to `window`.
Should help with weird flakes due to persistent state across runs. Closes #29517

Isolate state in test-amp-a4a.js

---

.circleci/config.yml

This PR does DRY
> Description from previous version of this PR that included splitting integration and e2e tests into separate jobs:
> > Reduces total running time of CircleCI for PRs from ~20.5 minutes ([example](https://app.circleci.com/pipelines/github/ampproject/amphtml/2927/workflows/ad7c3033-1789-45a8-b415-9b439c72562f)) to ~18.5 minutes ([example](https://app.circleci.com/pipelines/github/ampproject/amphtml/2944/workflows/10a74732-ff86-4af6-893e-aedbf8bab502)), at the cost of about an extra ~8.5 minutes of total VM time. Not sure if it's worth it, wdyt?

🏗 Matrixify Experiment Build/Tests on CircleCI

---

build-system/pr-check/module-tests.js
build-system/pr-check/nomodule-tests.js
build-system/tasks/prepend-global/index.js

Other changes:
* Remove unused legacy code that uses allows setting --target via an environment variable
* Get config file directly from the requested branch without checking it out into the filesystem
* Remove unexpected behaviour where a missing config file in the requested branch defaults to using the local branch's copy of the file
* Do not export functions that aren't used anywhere else
* Ensure only one of `--prod` or` --canary` can be passed
* Fix Promise return types

🏗  Add support for multiple (comma-separated) --target files for `gulp prepend-global`

---

.circleci/config.yml
build-system/pr-check/module-tests.js
build-system/pr-check/nomodule-tests.js
build-system/tasks/report-test-status.js

As discussed in https://github.com/ampproject/amphtml/pull/32865#discussion_r583063328

🏗 Pass CircleCI matrix parameters to (module|nomodule)-tests.js as a command line flag

---

src/inabox/inabox-resources.js
test/unit/inabox/test-inabox-resources.js

This is a complete symmetry with the main `Resources` manager. See #32568 for more details.

Ignore V1 elements in the inabox resource manager

---

extensions/amp-access/0.1/test/test-login-dialog.js
src/service.js
src/service/core-services.js
test/unit/test-action.js
test/unit/test-activity.js
test/unit/test-friendly-iframe-embed.js
test/unit/test-history.js
test/unit/test-preconnect.js
test/unit/test-runtime.js
test/unit/test-service.js
test/unit/test-shadow-embed.js
test/unit/test-url-replacements.js

There are several methods of sharing services with FIE, but the 2 main ones are:
1. FIE installs its own factory
2. FIE copies the parent's factory **instance**
https://github.com/ampproject/error-reporting/issues/58 is caused because the FIE is using its own factory instance (which means it has its own `Templates` class code, with private names mangled, in each binary that installs the FIE). But each FIE then uses code shared with v0.js to install a amp-mustache instance. This means we have code compiled in v0.js trying to directly interact with a class that's provided by, eg, amp-ad-custom (a separate binary!). This is never good.
What's really needed here is a 3rd way to share services with FIE:
3. FIE copies the parent's **factory**
FIE can then instantiate its own instance of that …

Allow Service Factories to be adopted by FIE

---

src/custom-element.js
test/unit/test-custom-element.js

Closes #32978
The problem is due to the race condition when a `Resource` correctly updates its state vs when an element knows reliably it has been built. This will be a non-issue for V1/Bento, but for classical elements this duality is still the case.
Note! This is a PR against release-2102130314000 branch.

Fix ensureLoaded-vs-build race condition in stable

---

src/custom-element.js
test/unit/test-custom-element.js

Closes #32978
This is the #32980 for the current HEAD

Fix ensureLoaded-vs-build race condition in HEAD

---

src/core/assert.js
src/core/error-message-helpers.js
src/log.js
test/unit/test-assert.js

Part of broader effort to bring `src/core/assert.js` to feature parity with `src/log.js` and untie fully from runtime deps

♻️ Support stringifying element args in asserts + split helpers

---

examples/doubleclick-rtc.amp.html
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
extensions/amp-ad-network-doubleclick-impl/doubleclick-rtc.md

data-json attribute does not exist, so it will simply error out. There are publishers misled by this template. `TGT` macro which uses the `json` attribute appears to be the correct one.

Fix doubleclick rtc example page, allowlist json in RTC macro

---

build-system/server/app.js
build-system/tasks/helpers.js
build-system/tasks/runtime-test/helpers.js
build-system/tasks/runtime-test/runtime-test-base.js
build-system/test-configs/karma.conf.js

In #32891, we switched Karma's transformer from `browserify` to `esbuild`. Notably, we combined all JS test files into a single file for `esbuild` to transform with `babel`. This PR fixes watch mode while running tests.
- Disable `babel` transform caching in watch mode (so the unified file is re-transformed when a test file is edited)
- Fix logging for start of transforms and start of tests (Karma's trigger events vary between watch and non-watch modes)
- Clean up references to obsolete `argv.w` and `argv.v`
- Bonus fix: Clean up test script response logic so that `test-3p.js` can be run repeatedly in watch mode
With this PR, the watcher is triggered when an edit is made to either a test file or a runtime file consumed by it.
**Screenshot:**
**Note:** Babel caching …

🏗 Fix Karma's watch mode for `esbuild` transforms

---

build-system/global-configs/canary-config.json
src/service/resources-impl.js

Removes:
- `remove-task-timeout`
- `build-in-chunks`
- `build-close-to-viewport`
Diff best viewed [without whitespace changes](https://github.com/ampproject/amphtml/pull/33032/files?w=1).

resources: remove inactive experiments

---

build-system/global-configs/experiments-const.json
examples/a4a.amp.html
extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js

Partial for #30952.
Based on the https://github.com/ampproject/amphtml/pull/32943

Experiment: disallow a4a on platforms w/o native shadow DOM support

---

build-system/tasks/3p-vendor-helpers.js
build-system/tasks/analytics-vendor-configs.js
build-system/tasks/extension-helpers.js
build-system/tasks/helpers.js

**summary**
Followup to https://github.com/ampproject/amphtml/pull/32663#issuecomment-781736550
> The watcher knows each file that is modified. The babel cache is on a file by file basis. When the watcher detects that a file has been modified, we can remove it from the cache.
While technically faster, its a bit more fragile. Not tied to it.
---
While working on this, I noticed there is nothing set to retrigger builds of core runtime `src/` folder is modified.

build-system: invalidate babel cache via watcher

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

- Update dependency @babel/preset-env to v7.13.9 (#1519)
- Update dependency chai to v4.3.1 (#1521)
- Improve fetch error messaging (#1520)
- CI: Adds comments regarding Java 8 and Ubuntu 20.04 LTS (#1518)
- Update dependency rollup to v2.40.0 (#1514)
- Update dependency karma to v6 (#1498)
- Update babel monorepo to v7.13.8 (#1515)
- Send metering pingback only on metering requests (#1479)
- CI: Uses Java 8 (#1517)
- Update dependency eslint to v7.21.0 (#1516)
- Update babel monorepo (#1500)
- Showcase Regwall: Handle GSI failures (#1513)
- Use msg for GSI button content (#1512)
- Add client config and auto prompt managers (#1505)
- Describe entitlements object (thanks andrehash@!) (#1510)

SwG release 0.1.22.151

---

build-system/compile/compile-wrappers.js
build-system/tasks/extension-helpers.js

Partial for #33001.
For multi-version support we need to know what version the extension is being registered and whether or not it's the "latest" version.

Multi-versioned extensions: propagate version info in the binaries

---

build-system/tasks/sweep-experiments/index.js
build-system/tasks/sweep-experiments/jscodeshift/remove-experiment-config.js
build-system/tasks/sweep-experiments/jscodeshift/remove-experiment-runtime.js

1. `--no-babel` prevents transformer plugin files from being transpiled by Babel. This speeds up transformer startup.
2. Use `api.report()` to pass parser results through `stdout` instead of writing to temp file.

🏗🚀 Improve jscodeshift execution on sweep-experiments

---

extensions/amp-accordion/1.0/test-e2e/test-amp-accordion.js

Appears to be flaky in [master](https://app.circleci.com/pipelines/github/ampproject/amphtml/3624/workflows/a9c3b54b-7a9c-4dee-a089-241d6c8c3d14/jobs/45085) due to async expect of the incorrect value (which is sometimes met during size transition).

✅  Fix e2e test for collapsed amp-accordion

---

babel.config.js
build-system/babel-config/empty-config.js
build-system/tasks/presubmit-checks.js

**Two changes:**
- When a `babel` caller loads `babel.config.js`, lazy-require and return only the config requested.
- Remove `build-system/` deps from `babel.config.js` to eliminate side-effects when an empty config is returned.

🏗 Lazy-require babel configs

---

examples/amp-story/amp-story-auto-ads.html
extensions/amp-story-auto-ads/0.1/story-ad-analytics.js
extensions/amp-story-auto-ads/0.1/story-ad-page.js
extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js

Allows amp-analytics to listen for this trigger which is fired when an ad page is horizontally swiped.

✨Introduce new `story-ad-swipe` event.

---

src/core/assert.js
src/core/minified-mode.js

Allows DCE to remove devAssert calls 
TODO:

🐛Add minified check to assert

---

src/multidoc-manager.js

Partial for #33001.
For some reason, the multidoc is installing extensions twice. In reality they only install once since the extension service checks whether or not an extension has been installed. But there's no reason to do it twice. More importantly, the first call is more precise because it includes the correct version.
The first call is inside the `mergeHead_`: 
https://github.com/ampproject/amphtml/blob/472974b65e64cc5c354cb576f122f31d15d865a3/src/multidoc-manager.js#L442-L446
The second call is done right after the `mergeHead_`:
https://github.com/ampproject/amphtml/blob/472974b65e64cc5c354cb576f122f31d15d865a3/src/multidoc-manager.js#L242

Do not install extensions twice in multidoc

---

src/amp-story-player/amp-story-player-impl.js

Closes #30512
Now that https://github.com/ampproject/amphtml/pull/30753 has been merged, we can start supporting using an `<img>` tag to declare a poster image for the player.

[amp-story-player] Support poster img from anchor el

---

.circleci/check_config.sh

This PR adds clear instructions for what to do when a PR branch is outdated and the CircleCI config has changed. The easiest fix involves clicking a button on GitHub, and can be done by internal and external contributors with no trouble.
**Example:** See [these](https://app.circleci.com/pipelines/github/ampproject/amphtml/3792/workflows/34a32c83-7b80-406e-a941-687c41100927/jobs/47915/parallel-runs/0/steps/0-103) logs.

🏗 Expand instructions for dealing with stale PR branches

---

extensions/amp-story-360/0.1/amp-story-360.md
extensions/amp-story-interactive/amp-story-interactive.md
extensions/amp-story/amp-story-grid-layer.md
extensions/amp-story/amp-story.md
extensions/amp-video/0.1/amp-video.md
extensions/amp-video/amp-video.md

Suggested changes and additions based on the TetraLogical accessibility review commissioned by @nainar / @caroqliu
Main changes:
* where appropriate, add extra prose about importance of providing captions
* accessibility consideration notes for 360 and interactive components (that lack keyboard accessibility, and the latter lacks screenreader support altogether)
* note about judicious use of animations
* typo "subsect" > "subset"
* expand alt text of documentation images to actually convey information
* where appropriate, add `alt="..."` placeholder attribute to reinforce the idea for developers that they should provide text alternatives
* note about content order still matching source order for AT users, even if using named areas in template to provide a different apparent content order …

♿ TetraLogical: AMP Stories accessibility review / documentation

---

extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/test/test-amp-story.js

Reported as bug where stories with > 2 video ads and no organic videos would often show broken ads after the second video ad. 
When mediapool goes to evict an element, it will try to locate the element with the largest distance from the current page. It does this by starting at the element and walking up the tree until it finds an amp story page. When the element is inside an iframe it will always stop at the iframe boundary and never find the correct page nor distance. This leads to cases where the video element on the page that is about to show with be chosen to be evicted, swapped, and re-sourced all in a race condition with undesirable results. 
This may also be responsible for hard to reproduce "black screen" bugs reported in past.
This fix is to always return the right distance even …

🐛Fix mediapool location logic for elements inside iframe.

---

extensions/amp-lightbox/1.0/amp-lightbox.js
extensions/amp-lightbox/1.0/base-element.js
extensions/amp-lightbox/1.0/component.js
extensions/amp-lightbox/1.0/component.type.js
extensions/amp-lightbox/1.0/storybook/Basic.amp.js
extensions/amp-lightbox/1.0/storybook/Basic.js
extensions/amp-lightbox/1.0/test-e2e/test-custom-close-button.js
extensions/amp-lightbox/1.0/test/test-component.js
test/fixtures/e2e/amp-lightbox/custom-close-button.amp.html

If one is not provided, the 2x2 screen reader-only close button will be provided with a generic label "Close the modal". Customizing the label itself is recommended to be done by providing a custom close button.
Related to #31052 cc @dvoytenko

Bento Lightbox: Support providing custom close button

---

build-system/test-configs/dep-check-config.js
extensions/amp-ad/0.1/test/test-amp-ad.js
extensions/amp-form/0.1/test/integration/test-integration-form.js
extensions/amp-live-list/0.1/live-list-manager.js
extensions/amp-live-list/0.1/test/test-live-list-manager.js
src/element-service.js
src/runtime.js
src/service/ampdoc-impl.js
src/service/custom-element-registry.js
src/service/extension-script.js
src/service/extensions-impl.js
test/fixtures/overflow.html
test/unit/test-ampdoc.js
test/unit/test-custom-element-registry.js
test/unit/test-custom-element-v1.js
test/unit/test-custom-element.js
test/unit/test-extensions.js
test/unit/test-friendly-iframe-embed.js
test/unit/test-runtime.js
testing/describes.js

Partial for #33001.
The main change is `AmpDoc.declareExtension(extensionId, version)`. Starting from this PR an ampdoc will not only track which extensions are installed for this doc, but also which version exactly. All other changes, essentially, are only there to propagate version as far as needed.

Multiversion: declare extensions with version

---

extensions/amp-story/amp-story-cta-layer.md

Update [amp-story-cta-layer docs page](https://amp.dev/documentation/components/amp-story-cta-layer/) to specify that `<amp-story-cta-layer>` may not be used on the first story page.
/cc @gmajoulet 
Resolves #24978

📖 Document that amp-story-cta-layer may not appear on the first story page

---

extensions/amp-form/0.1/test/integration/test-integration-form.js
src/document-submit.js
src/friendly-iframe-embed.js
src/multidoc-manager.js
src/service/ampdoc-impl.js
src/service/custom-element-registry.js
test/unit/test-custom-element-registry.js
test/unit/test-document-submit.js
test/unit/test-friendly-iframe-embed.js
test/unit/test-runtime.js
testing/describes.js

Partial for #33020.
The document will get a signal when extensions are known. This will remove the need from polling and/or rescanning scripts in the `<head>` to know whether an extension and its version are in a document. See `src/document-submit.js` for an example of how this is used.
TODO:

Multi-version: signal when extensions are known

---

extensions/amp-video/0.1/flexible-bitrate.js
extensions/amp-video/0.1/test/test-flexible-bitrate.js

When a cached video loads, it has a chance of sending a `waiting` event before loading and a `playing` event when it starts playing. If these events take more than 100ms, it would trigger a downgrade on the videos even though the video is not loaded yet, and the `nonTrivialWait` is not a buffering problem

🐛  [Story video] Fix video downgrading on load

---

extensions/amp-brightcove/0.1/amp-brightcove.js
extensions/amp-brightcove/0.1/test/test-amp-brightcove.js

`<amp-brightcove>` is autoplaying without `autoplay`. This means that the video can also dock without user interaction, which it should not. See #32706
Brightcove should update their player document so that it can't autoplay without the attribute. Otherwise, it cannot dock.
cc @mister-ben

🐛 Disable `dock` on amp-brightcove

---

babel.config.js
build-system/babel-config/minified-config.js
build-system/tasks/3p-vendor-helpers.js
build-system/tasks/build.js
build-system/tasks/dist.js
build-system/tasks/helpers.js

To improve the performance during circleci testing and dist.
Added 8s build time for all 274 vendors.

🏗 Move 3p iframe vendor builds to use esbuild

---

examples/amp-story/interactives.html
extensions/amp-story-interactive/0.1/amp-story-interactive-poll.css
extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.css

Fixes #33206
We recently changed the options to use <button> tags for accessibility, and buttons by default have text centered instead of the initial alignment. This causes quizzes or polls options that have 2 lines to have text-align: center.
Tested fix locally on ltr and rtl stories
Eg (before/after):

🐛  [Story interactives] Fixed text align of buttons

---

src/custom-element.js
src/service/custom-element-registry.js
test/unit/test-custom-element.js

Currently, the first `stubElementsForDoc` can be called after the first element is upgraded. This could create race conditions where an element would request its implementation before it knows whether the implementation has already been requested.

Ensure that pre-stubbing always happens before the first element is upgraded

---

build-system/pr-check/checks.js
build-system/pr-check/ci-job.js
build-system/pr-check/cross-browser-tests.js
build-system/pr-check/e2e-tests.js
build-system/pr-check/experiment-build.js
build-system/pr-check/module-build.js
build-system/pr-check/module-tests.js
build-system/pr-check/nomodule-build.js
build-system/pr-check/nomodule-tests.js
build-system/pr-check/npm-checks.js
build-system/pr-check/performance-tests.js
build-system/pr-check/unit-tests.js
build-system/pr-check/unminified-build.js
build-system/pr-check/unminified-tests.js
build-system/pr-check/visual-diff-tests.js

**Two changes:**
- Add a check to `pr-check/npm-checks.js` to ensure `package-lock.json` was properly updated
- Instead of having every CI job independently update packages, make it a step in `pr-check/ci-job.js`
**[Example failure:](https://app.circleci.com/pipelines/github/ampproject/amphtml/4306/workflows/34f185d4-c949-4502-82df-cc6876bb73c4/jobs/55915/parallel-runs/0/steps/0-108)**

🏗 Ensure up-to-date and clean `package-lock.json` before running any CI job

---

.circleci/compute_merge_commit.sh
.circleci/config.yml
.circleci/fetch_merge_commit.sh
.circleci/get_pr_number.sh
.gitignore
build-system/common/ci.js
build-system/tasks/bundle-size/index.js

**Assorted cleanup after #33165:**
- Split off pieces of `fetch_merge_commit.sh` into `compute_merge_commit.sh` and `get_pr_number.sh` (https://github.com/ampproject/amphtml/pull/33165#discussion_r590923237)
- Update `amphtml-docker-small-executor` to use a small docker instance with an updated spec (#33195)
- Properly persist `mergeSha` so it can be used (and logged) by bundle-size (simply `export`ing it is insufficient)

 🏗 Clean up CircleCI merge SHA logic

---

.circleci/compute_merge_commit.sh
.circleci/fetch_merge_commit.sh

Follow up to #33215 to make it work on push builds

🏗 Guard access to `BASH_ENV` during CircleCI push builds

---

extensions/amp-video/0.1/amp-video.js
extensions/amp-video/0.1/test/test-amp-video.js

Fixes https://github.com/ampproject/amphtml/issues/33225

Fix amp-video amp_video_quality parameter name for cached sources.

---

extensions/amp-instagram/1.0/base-element.js
extensions/amp-instagram/1.0/component.js
extensions/amp-instagram/1.0/component.type.js
extensions/amp-instagram/1.0/storybook/Basic.amp.js
extensions/amp-instagram/1.0/storybook/Basic.js
extensions/amp-instagram/1.0/test/test-component.js
extensions/amp-video/1.0/storybook/Basic.amp.js
extensions/amp-video/1.0/storybook/VideoIframe.js
extensions/amp-video/1.0/test/test-video-iframe.js
extensions/amp-video/1.0/test/test-video-wrapper.js
extensions/amp-video/1.0/video-iframe.js
extensions/amp-video/1.0/video-iframe.type.js
extensions/amp-video/1.0/video-wrapper.js
extensions/amp-video/1.0/video-wrapper.type.js
extensions/amp-youtube/1.0/component.js
extensions/amp-youtube/1.0/storybook/Basic.amp.js
src/custom-element.js
src/preact/base-element.js
src/preact/context.js
src/preact/storybook/Context.js
src/service/resources-impl.js
test/unit/preact/test-base-element-mapping.js
test/unit/preact/test-base-element-runtime.js
test/unit/preact/test-context.js
test/unit/test-custom-element-v1.js
testing/resize-observer-stub.js

Partial for #30283.
The main general changes are in the `src/preact/base-element.js` and they are simple:
1. `layoutCallback` is gone.
2. `ensureLoaded` is added. Works via `loading=eager`
3. Loading is started immediately when the Preact component is rendered the first time.
4. The ready state is propagated from the Preact component to AMP element using `Ref<Api>` and `onReadyState` event.
Other changes include:
1. `unloadOnPause` is changed to allow reloading.
2. `VideoWrapper` and `Instagram` components have been updated to V1 protocol.

Migrate Bento components to V1

---

build-system/test-configs/dep-check-config.js
extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-a4a/0.1/amp-ad-utils.js
extensions/amp-a4a/0.1/friendly-frame-util.js
extensions/amp-a4a/0.1/template-validator.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js
extensions/amp-a4a/0.1/test/test-amp-ad-utils.js
extensions/amp-a4a/0.1/test/test-template-validator.js
extensions/amp-story/1.0/test/test-amp-story-page.js
src/friendly-iframe-embed.js
test/unit/test-friendly-iframe-embed.js

- Extracts extension version from ad where previously unavailable.
- Passes extension version info (as `extensions`) from A4A legacy code, no signing, and templates ads. 
- Removes `preloadFriendlyIframeEmbedExtensionIdsDeprecated` from all call sites outside of `friendly-iframe-embed.js`.
Partial #33020

✨ Send extension versions from AMPHTML ads to FIE 

---

.circleci/fetch_merge_commit.sh

This PR prevents a race that occurs as follows:
- A file is directly changed on `ampproject/amphtml` and a branch is created
- CI build starts on that branch
- A PR is created after the first stage of CI has begun, but before the second stage
- Second stage tries to read the merge commit file
Now, we don't read the merge commit file if it doesn't exist.
**[Example race:](https://app.circleci.com/pipelines/github/ampproject/amphtml/4503/workflows/3886a337-e39e-45a2-96e6-c3a73510b082)**
**First stage:**
**Second stage:**

🏗 Read merge commit only if file was created

---

extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
extensions/amp-base-carousel/1.0/test-e2e/test-autoadvance.js
extensions/amp-base-carousel/1.0/test-e2e/test-carousel.js
extensions/amp-base-carousel/1.0/test-e2e/test-mixed-lengths.js
extensions/amp-base-carousel/1.0/test-e2e/test-non-looping.js
extensions/amp-base-carousel/1.0/test-e2e/test-rtl.js
extensions/amp-base-carousel/1.0/test-e2e/test-vertical.js

Related to #24195
Skips all offenders below:
cc @samouri

Skip flaky amp-base-carousel 1.0 tests

---

build-system/compile/sources.js
build-system/global-configs/experiments-config.json
build-system/global-configs/experiments-const.json
build-system/test-configs/dep-check-config.js
extensions/amp-fit-text/0.1/amp-fit-text.js
extensions/amp-fit-text/0.1/test-e2e/test-amp-fit-text.js
test/integration/test-extensions-loading.js

This removes the experiment which upgraded `amp-fit-text` version `0.1` to `1.0` in Experiment C channel. Closes #32523
cc @dvoytenko

🚮  Clean up amp-fit-text server-side experiment

---

src/service/extensions-impl.js
test/unit/test-extensions.js

Partial for #33020.
This is a subtle change, but it's important for consistency. I couldn't find any good argument why we need to wait until the extension is loaded before declaring it. All other codepaths declare an extension before it's loaded.

Multi-version: declare the installed extension as soon as possible

---

.circleci/config.yml

I just think it makes the graph look better 😅
------ | ------
Before | After

🏗 Remove `Compute Merge Commit` as a direct CircleCI job dependency where it's already a transitive dependency

---

src/element-service.js
src/service/ampdoc-impl.js
src/service/extensions-impl.js
src/services.js
test/unit/test-element-service.js
test/unit/test-extensions.js
test/unit/test-runtime.js
test/unit/test-url-replacements.js

Partial for #33020.
With ampdoc services the version is declared on the document itself. With global services the version has to be provided explicitly.
TODO:

Multi-version: always specify version when waiting for an extension

---

build-system/compile/compile.js
build-system/compile/pre-closure-babel.js
build-system/tasks/extension-helpers.js
build-system/tasks/helpers.js

Now that our closure compilation code has been refactored, it's time to make sure incremental minified watch builds work.
- Add `removeFromBabelCache()` to delete files / dirs from the local pre-closure babel cache directory
- Call it wherever minified watch builds are triggered so babel transforms are re-run on modified files
- Add missing `continueOnError: true` to `watchFunc()` in `compileCoreRuntime()`
- If transformation / compilation fails during a watch build, early-exit from `compile()`
- Bonus cleanup: Rename extension directory variable in `extension-helpers.js` from `path` to `extDir`
**Usage:**
1. Run `gulp --compiled`
2. Go to `http://localhost:8000` and load a test page
3. When a JS file / extension is edited, old results are removed from the babel cache …

🏗 Add support for minified lazy build + watch

---

package-lock.json
package.json

This PR removes the dependency on `0x`. It was inadvertently re-added by #33111.
See `package-lock.json` changes for all the transitive dependencies that we no longer need to install.
Addresses https://github.com/ampproject/amphtml/pull/33111#discussion_r591649903

🏗 Remove root `package.json` dependency on `0x`

---

build-system/server/typescript-compile.js
build-system/tasks/check-types.js
build-system/tasks/coverage-map/index.js
build-system/tasks/serve.js
build-system/tasks/server-tests.js

**summary**
- Use esbuild instead of tsc for compilation. 
- Task duration goes from **~1.3s --> ~30ms**.
It is important to note that **esbuild does not perform typeschecking**. Therefore we still need to use `tsc`, but I've moved this usage to the `gulp check-types` command.

build-system: use esbuild for compiling AMP Server (new server).

---

src/service/performance-impl.js
test/unit/test-performance.js

**summary**
- All CLS-related events are emitted within the same `flush()`, at the time when CLS would normally be emitted.
- `cls-fcp` and `cls-ofv` now use the corresponding entryTime for knowing which layout-shifts to include, as opposed to assuming they were invoked synchronously after the corresponding event.
- In order to accomplish both items above, we now collect all the layout shift events into an array instead of summing as we go. I've added a limit of 1000 entries so that it can't have unbounded growth.

performance-impl: use fcp and ofv entryTime when summing for cls-fcp and cls-ofv

---

extensions/amp-story-panning-media/0.1/amp-story-panning-media.js

- Subscribes to `UI_STATE` to set `maxDistanceToAnimate_ `
- Renames `distance_ ` to `pageDistance_ `
Context / Fixes #32215

✨ [amp-story-panning-media] Animate active page on desktop panels

---

extensions/amp-a4a/0.1/amp-ad-template-helper.js
extensions/amp-a4a/0.1/test/test-amp-ad-template-helper.js
extensions/amp-a4a/0.1/test/test-template-renderer.js
extensions/amp-ad-custom/0.1/test/test-amp-ad-custom.js
extensions/amp-ad-network-adzerk-impl/0.1/test/test-amp-ad-network-adzerk-impl.js
testing/describes.js

amp-ad-custom: resolve the template in the right context

---

extensions/amp-a4a/0.1/amp-ad-template-helper.js
extensions/amp-a4a/0.1/test/test-amp-ad-template-helper.js
extensions/amp-a4a/0.1/test/test-template-renderer.js
extensions/amp-ad-custom/0.1/test/test-amp-ad-custom.js
extensions/amp-ad-network-adzerk-impl/0.1/test/test-amp-ad-network-adzerk-impl.js
testing/describes.js

Copy of https://github.com/ampproject/amphtml/pull/33324 for `amp-release-2103060631003-cp-base` branch.
Fixes #33317.

amp-ad-custom: resolve the template in the right context for amp-release-2103060631003-cp-base

---

src/utils/dom-tranform-stream.js
test/unit/utils/test-dom-transform-stream.js

Transfer any attributes that may exist on `<body>` in the in-memory dom to live DOM.
Closes #33274

🐛[no-signing] Transfer attributes on body element

---

build-system/babel-config/minified-config.js
build-system/tasks/helpers.js

3p vendors' compilation process uses `compileJsWithEsbuild` without a target attribute, which causes esbuild to output some arrow functions after babel transpiler. This PR specifies target to es5 on esbuild to prevent that. For ESM builds, the babel transpiler will transform them back to ESM.
This PR only affects 3p vendor compilation, not anything else (e.g. runtime or extensions).

🐛 Change ESbuild 3p vendor target to ES5

---

build-system/common/esbuild-babel.js
build-system/tasks/clean.js
build-system/tasks/helpers.js

**summary**
Partial for https://github.com/ampproject/amphtml/issues/33011
Use the filesystem for the babel cache in addition to the in-memory `Map`.
- Cold compilation of `amp.js` drops from ~5s --> ~500ms. 
- Total startup time is down from ~9s --> 4.5s.

🚀 🚀 🚀  build-system: use fs for babel-cache 🚀 🚀 🚀 

---

build-system/tasks/presubmit-checks.js
builtins/amp-img.js
extensions/amp-iframe/0.1/test/test-amp-iframe.js
src/base-element.js
src/common-signals.js
src/custom-element.js
src/preact/base-element.js
src/ready-state.js
src/service/resource.js
src/service/scheduler.js
test/integration/test-visibility-states.js
test/unit/inabox/test-inabox-resources.js
test/unit/preact/test-base-element-runtime.js
test/unit/test-amp-img-v1.js
test/unit/test-custom-element-v1.js
test/unit/test-custom-element.js
test/unit/test-mutator.js
test/unit/test-owners.js
test/unit/test-resource.js
test/unit/test-resources.js
test/unit/test-scheduler.js
testing/element-v1.js

Key changes:
* The `mount/unmount` callbacks are added to a V1 element API. They are called automatically on first build, attach/detach from DOM, manual unmount, etc. They are similar to `layout/unlayout` callbacks, but meant to be executed with build and more "like build, but reversible".
* Builder now calls `mountInternal()` on an element. Consequently it's renamed to `Scheduler`.
* `BaseElement.load()` is added to make build->load states a little less fragile.
* The `layoutCallback`, `unlayoutCallback`, `pauseCallback`, and `resumeCallback` in the `CustomElement` have been deprecated.
TODO:

V1: mount/unmount concept and automatic scheduling

---

extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js

https://github.com/ampproject/amphtml/pull/32135 This experiment is coming back negative. This PR attempts to fix it by only not calling `applyFillContent` when it is a sticky ad. In theory, it should not affect non-sticky ad any more.

Maybe fix amp-ad css experiment issue

---

extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
package-lock.json
package.json
third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-button.css
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

- Plumb paySwgVersion through to pay-flow. (#1557)
- Let getEntitlements API take swgUserToken (#1556)
- Gulp: Install dependencies before anything else (#1555)
- Allows older Yarn versions (#1554)
- Make offer iframes non-closable for pages marked as paygated. (#1553)
- Simplifies setup (#1552)
- Update button UX to split on revenue model. Only applies to swg-basic for now. (#1551)
- Update dependency rollup to v2.41.4 (#1550)
- Base64Url: Trims `=` padding characters when encoding, and leaves them when decoding (#1543)
- Showcase: Improves ld+json check with optional chaining (#1544)
- Updates Closure Compiler, then fixes errors and warnings (#1545)
- Update dependency eslint to v7.22.0 (#1549)
- Update dependency rollup to v2.41.2 (#1547)
- Update dependency chai to v4.3.4 (#1548)
- …

🏗  SwG Release 0.1.22.152

---

src/service/resources-impl.js

This is a preparation for the `intersect-resources` experiment cleanup.

Remove intersect-resources from bento experiment

---

amp.js
build-system/tasks/amp-task-runner.js
build-system/tasks/build.js
build-system/tasks/check-links.js
build-system/tasks/check-types.js
build-system/tasks/css/index.js
build-system/tasks/default-task.js
build-system/tasks/dist.js
build-system/tasks/lint.js
build-system/tasks/prettify.js
build-system/tasks/update-packages.js

- Automates `npm` package updates during `amp` tasks by doing it as part of task initialization
- Prevents the case where a task loads a dependency that then gets updated during execution
**Updates necessary:**
**Updates not necessary:**
Fixes #33364
Partial fix for #33141

🏗 Automatically update `npm` packages if needed before any task is run

---

build-system/compile/closure-compile.js
build-system/compile/typescript.js
build-system/tasks/bundle-size/index.js
build-system/tasks/css/jsify-css.js
build-system/tasks/performance/copy-images.js
build-system/tasks/performance/rewrite-analytics-tags.js
build-system/tasks/performance/rewrite-script-tags.js

When an individual `amp` task is run, only the code for that task is loaded, resulting in near instant startup most of the time. However, when `amp --help` is run, we must load the code for all tasks in order to extract descriptions and flag info.
- Profiled task loading to identify particularly slow loading modules
- Lazy-required those modules so they are only loaded while running task(s) that use them
- Bonus fix: Run `cli-highlight` before formatting and coloring closure errors so text isn't mangled
**Results:**
The load time for all tasks was computed by running `0x amp --help`. In the flame charts, blue areas are infrastructure code, wider purple areas are slow loading modules, and narrow purple areas are quick loading modules.
**Before:**  ~6.3 …

🏗🚀 Speed up `amp` task loading by lazy-requiring large dependencies

---

build-system/test-configs/dep-check-config.js
extensions/amp-a4a/0.1/amp-ad-utils.js
extensions/amp-a4a/0.1/template-validator.js
extensions/amp-a4a/0.1/test/test-amp-ad-utils.js
extensions/amp-a4a/0.1/test/test-template-validator.js
extensions/amp-ad-network-adzerk-impl/0.1/amp-ad-network-adzerk-impl.js
extensions/amp-ad-network-adzerk-impl/0.1/test/test-amp-ad-network-adzerk-impl.js

Fixes template ads case where the server sends `customElementExtensions` in metadata, but `extensions` is always an empty array by merging the two sources.
Partial #33020

🐛 Use customElementExtensions where extensions may not be populated

---

spec/amp-story-player.md
src/amp-story-player/amp-story-component-manager.js
src/amp-story-player/amp-story-player-impl.js

Closes #32826
Fixes duplicate player loading scenario by 
1. Throwing an error when trying to instantiate a player on a DOM element that already has one.
2. Calling `new AmpStoryPlayer(...)` should return the player DOM element instead of the class instance, so we have consistency between doing `querySelector('amp-story-player')` on a Player that was in the initial HTML, and calling `new AmpStoryPlayer(...)`
3. Revise our documentation examples to show that
There's no breaking change to these updates.

[amp-story-player] Fix duplicate player loading scenario

---

extensions/amp-story/1.0/amp-story-store-service.js
extensions/amp-story/1.0/amp-story-system-layer.css
extensions/amp-story/1.0/amp-story-system-layer.js
extensions/amp-story/1.0/amp-story.js

Closes #32508
Makes pause/play buttons in the system layer focusable via keyboard.
It uses the `amp-mode-keyboard-active` AMP CSS class to display the button when the keyboard is active.
Outdated comments before 87fed97f4c594e63ccaf0281a238eb02d82fae63:
* Buttons cannot be focused if they are `display: none` or `visibility: hidden`, so we have to render them and hide them another way.
* The other two options to hide the buttons is using `opacity` or `width`. I tried using `opacity: 0` initially, but it would create an empty space between the other buttons in the system layer.
* Modifying the `width` is usually frowned upon since it causes CLS and negatively impacts performance. Alternative would be to use a `transform: scaleX(0)`, but it would still create the space between the other …

[amp-story] ♿ Make pause/play buttons keyboard focusable

---

build-system/pr-check/experiment-tests.js

Forgot to pass in `--report` in #33389.

🏗 Pass in `--report` for experiment tests on push builds

---

src/core/assert.js

In #32407, when splitting user/dev assertions into `src/core/assert`, I mistakenly dropped the `isMinified` check and user/dev asserts stopped being DCE'd out of builds. Justin identified this after some time (we do not have testing for this) and I created #33087, which re-introduced the minified check, but in the shared `assertion` method rather than exclusively in `devAssert`, leading to both `userAssert` and `devAssert` being stripped in minified builds.
This PR moves the minified check into `devAssert` only

🐛 Move minified check to devAsserts only

---

extensions/amp-3q-player/0.1/amp-3q-player.js
extensions/amp-video/0.1/amp-video.js
src/utils/pause-helper.js
test/unit/utils/test-pause-helper.js

I think a simple helper would simplify the support for us. Instead of having several state vars we'd just encapsulate them inside a single helper.

Async pause: simplify adoption with a helper

---

extensions/amp-3d-gltf/0.1/amp-3d-gltf.js
extensions/amp-ad/0.1/amp-ad-3p-impl.js
extensions/amp-beopinion/0.1/amp-beopinion.js
extensions/amp-bodymovin-animation/0.1/amp-bodymovin-animation.js
extensions/amp-facebook-comments/0.1/amp-facebook-comments.js
extensions/amp-facebook-like/0.1/amp-facebook-like.js
extensions/amp-facebook-page/0.1/amp-facebook-page.js
extensions/amp-facebook/0.1/amp-facebook.js
extensions/amp-ima-video/0.1/amp-ima-video.js
extensions/amp-reddit/0.1/amp-reddit.js
extensions/amp-twitter/0.1/amp-twitter.js
src/3p-frame.js
test/integration/test-amp-ad-3p.js
test/unit/3p/test-3p-frame.js

Use the vendor specific integration js rather than `f.js` that contains all the vendors.

Experiment turning on splitted vendor integration JS

---

build-system/tasks/e2e/mocha-custom-json-reporter.js

Enabling test case reporting for experiment tests exposed a bug in `writeOutput()`, which assumes that the `result-reports/` directory doesn't exist. This is no longer true because integration and E2E tests are run on the same job.

🏗 Fix folder creation for test reports

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

https://github.com/ampproject/amphtml/pull/32763
Experiment is defined herein.

Ramp up 3p-vendor-split experiment

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json
src/inabox/inabox-resources.js
src/service/mutator-impl.js
src/service/resource.js
src/service/resources-impl.js
src/service/resources-interface.js
src/service/viewport/viewport-binding-def.js
src/service/viewport/viewport-binding-ios-embed-wrapper.js
src/service/viewport/viewport-binding-natural.js
src/service/viewport/viewport-impl.js
src/service/viewport/viewport-interface.js
test/integration/test-visibility-states.js
test/unit/test-resource.js
test/unit/test-resources.js
tools/experiments/experiments-config.js

**summary**
Remove `intersect-resources` now that we are moving to "V1" instead (https://github.com/ampproject/amphtml/issues/31915).
Having three resources systems would be 2 too many.
Best viewed [without whitespace changes](https://github.com/ampproject/amphtml/pull/33262/files?w=1).

resources: remove intersect-resources experiment

---

extensions/amp-iframe/0.1/amp-iframe.js
extensions/amp-iframe/0.1/test/test-amp-iframe.js
src/custom-element.js
test/unit/test-custom-element.js

A small change: use `PauseHelper` for `amp-iframe` and make sure the resources pass is scheduled after unlayout.

amp-iframe: add async pause

---

ads/google/a4a/docs/RTBExchangeGuide.md
extensions/amp-access/0.1/amp-login-done.html
tools/experiments/experiments.html
validator/js/webui/index.html

A few of our UI elements use the old name of "Accelerated Mobile Pages". They should be "AMP", stylized in all caps.

🖍 Fix visible UI that mentions "Accelerated Mobile Pages"

---

build-system/server/new-server/transforms/scripts/scripts-transform.ts
build-system/server/new-server/transforms/scripts/test/convert-to-max-names/input.html
build-system/server/new-server/transforms/scripts/test/convert-to-max-names/output.html
build-system/server/new-server/transforms/scripts/test/invalid-src-loose/output.html
build-system/server/new-server/transforms/scripts/test/multiple/output.html
build-system/server/new-server/transforms/scripts/test/port-transform-loose/output.html
build-system/server/new-server/transforms/scripts/test/port-transform-strict/output.html
build-system/server/new-server/transforms/scripts/test/retain-extension/output.html
build-system/server/new-server/transforms/scripts/test/runtime/input.html
build-system/server/new-server/transforms/scripts/test/runtime/output.html
build-system/server/new-server/transforms/transform.ts
build-system/server/new-server/transforms/utilities/cdn.ts
build-system/server/new-server/transforms/utilities/script.ts

currently when a port and host override is passed in from `gulp serve` the transformer does not currently apply the values to the transformed document. this breaks some port forwarding scenarios as well as being able to override the host and port values manually.

fix server transformer not respecting host and port overrides

---

build-system/global.d.ts
build-system/server/app-utils.js
build-system/tasks/check-exact-versions.js
build-system/tasks/check-sourcemaps.js
build-system/tasks/cherry-pick.js
build-system/tasks/helpers.js
build-system/tasks/pr-check.js
build-system/tasks/server-tests.js
build-system/tasks/storybook/index.js

The old `gulp` task runner used by AMP had a boolean [`showStack`](https://github.com/gulpjs/plugin-error/blob/1d51476e4d7da44c1daea246531ae822617e4565/index.d.ts#L85-L88) field in its Error interface to decide on whether to show the (mostly-useless) nodejs callstack. With the new `amp` task runner, the way to go is to simply throw an error when a task hits a fatal error.
This PR cleans up all old code that used `showStack`.

🏗 Clean up all `gulp` style error throwing in build-system

---

build-system/server/lazy-build.js
build-system/tasks/3p-vendor-helpers.js
build-system/tasks/serve.js

Currently, 3p integrations cannot be lazily built. This PR fixes the lazy building so that `gulp` can defer building 3p integration JS files till needed.

🏗 Lazy building 3p integrations

---

amp.js
build-system/common/update-packages.js
build-system/common/utils.js
build-system/pr-check/ci-job.js
build-system/tasks/amp-task-runner.js
build-system/tasks/coverage-map/index.js
build-system/tasks/e2e/index.js
build-system/tasks/performance/index.js
build-system/tasks/release/index.js
build-system/tasks/storybook/index.js
build-system/tasks/visual-diff/index.js

- Add a step to the `amp` task runner that auto-installs task-specific subpackages if necessary
- Consolidate `updatePackages` and `updateSubpackages` in `common/update-packages.js`
- Remove `amp update-packages` now that packages are automatically updated before every other task
- Change dir to repo-root and update root packages only when a task is actually being run (skip for `--help`)
- Delete `initializeRunner()` now that there's nothing left to do in it
**First run during local dev:**
**Subsequent run during local dev:**
**Clean run during CI:**
Fixes #33141

🏗 Optimize root-level and task-level package installation while running `amp` tasks

---

build-system/test-configs/dep-check-config.js
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js

And delete a bunch of state keeping logic from `amp-story-auto-ads` that has moved to these new classes. 
Partial #33147
~~Do not merge before #33387 so we can do clean revert if necessary.~~ Merged.

♻️ [story-ads]: Hook up StoryAdPageManager and StoryAdAlgorithm

---

contributing/DEVELOPING.md
contributing/build-on-duty.md

This is something we've been meaning to do for a while.
**Companion PR:** https://github.com/ampproject/amp-github-apps/pull/1250
**Next steps:**

🏗 Replace all mentions of `build cop` with `build on-duty`

---

build-system/test-configs/dep-check-config.js

Broken in #33377. Was not caught due to tests running before call site PR was merged.

🐛 Fix broken dep check

---

.eslintignore
.prettierignore
build-system/common/utils.js
build-system/tasks/prettify.js
build-system/test-configs/config.js
package.json

Also ensure prettier respects its `.prettierignore` file, which for some reason it ignores when using the API vs the CLI.

🏗️  Ignore .babel-cache directory

---

extensions/amp-lightbox/0.1/amp-lightbox.js
extensions/amp-lightbox/0.1/test/test-amp-lightbox.js
src/base-element.js
src/custom-element.js
src/dom.js
src/service/scheduler.js
src/utils/display-observer.js
test/unit/test-custom-element-v1.js
test/unit/test-dom.js
test/unit/test-scheduler.js
testing/intersection-observer-stub.js

Key changes:
* A container element, such as `amp-lightbox` can contribute its own intersection observer to the scheduler.
* `unmountAll` is used from the new `resources-container-helper.js`.
TODO:

V1: allow lightbox to add its own intersection observer to the scheduler

---

src/base-element.js
src/custom-element.js
src/service/scheduler.js
test/unit/test-scheduler.js

**summary**
Renames `deferredBuild` --> `deferredMount`.
In V1 there is only `mount`, no such thing as `build`.

V1 Resources: deferredBuild --> deferredMount

---

build-system/compile/closure-compile.js
build-system/compile/compile.js
build-system/tasks/check-types.js

As requested in https://github.com/ampproject/error-reporting/issues/73#issuecomment-806217750, this PR lets you set different warning levels while type checking different parts of the AMP codebase.
Once this is merged, it should be possible to change the `warningLevel` option for the calls to `closureCompile()` in `check-types.js` one by one and fix resulting errors / warnings via separate PRs. This should make it more feasible to split up #32875.
**Bonus fixes:**
- Correctly destructure the `highlight` package that is used to print closure error messages
- Modernize `check-types.js` to use arrow functions and `async` / `await` (no functional changes)
**Note:** For easy reviewing, use [this link](https://github.com/ampproject/amphtml/pull/33469/files?w=1) to hide whitespace-only changes.

🏗 Make warning levels for `check-types` more granular

---

extensions/amp-lightbox/0.1/test/test-amp-lightbox.js

This PR:
1. Fixes local failure for `should allow default actions in email documents` case by waiting for the element to build before invoking any actions.
2. Fixes console warning `ERROR: '[History] failed to execute a task: Error: No messaging channel: undefined'` for the above by stubbing history impl
3. Makes all other test cases wait for build because the test is configured with `runtimeOn: true` and was showing errors despite passing anyway, i.e:
- `ERROR: '[Resource] Error: layoutComplete race'`
- `INFO: '[Resources] task failed:', 'amp-lightbox#1#L', 'amp-lightbox#1', Error: CANCELLED`
- `ERROR: 'Error: CANCELLED'`
- Note that waiting for build (via `getImpl(true)`) eliminated these messages.
Open question: 
- Why was (1) not caught in CI? 🦇 🚨 @ampproject/wg-infra any ideas? One …

✅ Unit tests for amp-lightbox:0.1 should always build component

---

build-system/common/utils.js
build-system/tasks/lint.js
build-system/tasks/prettify.js

This PR implements the idea that I did a terrible job of describing in https://github.com/ampproject/amphtml/pull/33449#discussion_r600064303 and https://github.com/ampproject/amphtml/pull/33462#discussion_r600777934. Now that there is a way to explicitly ignore patterns from an ignore file like `.prettierignore` or `.eslintignore`, we can get rid of a bunch of unnecessary code in `lint.js`.
Bonus cleanup: The logic in `eslintRulesChanged()` to force-lint the entire repo if even a single rule changed was more trouble than it was worth during local development, so I've removed it. (We already lint all files during CI, there's no reason to annoy developers when they're running `amp lint --local_changes`.)

🏗 Consolidate arg processing and file globbing / ignoring across `amp` tasks

---

build-system/eslint-rules/no-forbidden-terms.js

- Remove newline
- Add period to message only if needed

🏗 Format forbidden term report message

---

extensions/amp-lightbox/0.1/amp-lightbox.js
extensions/amp-lightbox/1.0/base-element.js
extensions/amp-lightbox/1.0/component.js
extensions/amp-lightbox/1.0/component.type.js
extensions/amp-lightbox/1.0/test/test-amp-lightbox.js
extensions/amp-lightbox/1.0/test/test-component.js
extensions/amp-video/1.0/video-wrapper.js
src/preact/base-element.js
src/preact/slot.js
src/service/scheduler.js
test/unit/preact/test-base-element-mapping.js
test/unit/preact/test-slot.js

Follow up on https://github.com/ampproject/amphtml/pull/33281 for 1.0 version.

Bento: add container to the lightbox 1.0

---

build-system/eslint-rules/forbidden-terms-config.js
build-system/test-configs/.eslintrc.js
build-system/test-configs/forbidden-terms.js

Adds a lint rule `local/forbidden-terms-config` that's used on one file:
- Term keys should be string literals.
- Allowlist items should be string literals.
- Allowed files should contain the term.
- `allowlist` property should be removed if empty.

🏗 Ensure that forbidden term allowlists are updated

---

.eslintrc.js
build-system/eslint-rules/no-forbidden-terms.js
build-system/tasks/presubmit-checks.js
build-system/test-configs/forbidden-terms.js

Replaces hardcoded filename logic with globs on `.estlintrc.js`.

🏗 Move term list fileset to eslint config

---

src/preact/base-element.js
test/unit/preact/test-base-element-runtime.js

This is a hacky (only need in local dev) workaround for https://github.com/preactjs/preact/issues/3084.

Stop Preact from exposing VNode as ref

---

build-system/server/app.js
build-system/tasks/serve.js

**summary**
Fixes https://github.com/ampproject/amphtml/pull/33426#discussion_r601037983.
Requests for `ww.js` and `amp-auto-lightbox` fail in Storybook because of CORs.
See: <img width="1353" alt="Screen Shot 2021-03-25 at 3 23 17 PM" src="https://user-images.githubusercontent.com/4656974/112531575-1dc86480-8d7e-11eb-9df6-5ac0827b9cb4.png">
This PR adds the access control headers s.t. crossorigin requests (i.e. from storybook) can `fetch` js binaries.
Open to any and all suggestions of alternative solutions.

Dev Server: Allow crossorigin fetch of JS binaries.

---

extensions/amp-story/1.0/amp-story-page.js

Closes https://github.com/ampproject/error-reporting/issues/73
`NodeList` does not have a `forEach` method in all browsers, wrapping it in a `toArray()`.

🐛 [amp-story] Use toArray on NodeList

---

build-system/tasks/visual-diff/index.js

Renames `installDependencies_()` to `loadBrowserFetcher_()` to better indicate what's left to be done during setup.
Addresses https://github.com/ampproject/amphtml/pull/33452#discussion_r600671280

🏗 Clean up visual-diff install code

---

extensions/amp-sidebar/1.0/base-element.js
extensions/amp-sidebar/1.0/component.js
extensions/amp-sidebar/1.0/component.type.js
extensions/amp-sidebar/1.0/sidebar-animations-hook.js
extensions/amp-sidebar/1.0/test/test-amp-sidebar.js

Follow up on #33503 for 1.0 version.

Bento: add container to the amp-sidebar 1.0

---

extensions/amp-base-carousel/0.1/carousel.js
extensions/amp-base-carousel/0.1/test-e2e/test-initial-slide.js
extensions/amp-base-carousel/0.1/test/test-carousel.js
extensions/amp-carousel/0.2/amp-carousel.js

This PR:
- Fixes the normalized `initialSlide` value for non-looping carousels introduced in #32914. It's an off-by-one bug - we want to clamp so that the maximum value is the last index, not the length
- Applies the fix to the `slide` attribute behavior for the following scenarios:
- on first render and any changes with `amp-bind` 
- on both `amp-base-carousel:0.1` and `amp-carousel:0.2` (Note that `amp-carousel` does not support responsive attribute values.)
- Unskips the e2e test which tests for this attribute
- Updates unit tests accordingly
Resolve #33512 because the class does not assume the given initial index is valid, but normalized the value incorrectly:
https://github.com/ampproject/amphtml/blob/4f2b7f0081a3be32b2886ddb815cbb069058016f/extensions/amp-base-carousel/0.1/carousel.j …

🐛  amp-carousel:0.2 off-by-one bug for initialSlide when non-looping

---

extensions/amp-story-auto-ads/0.1/test/test-algorithm-predetermined.js

Skipped in #33529.
When introducing experimental ad density in #33471 I did not update the tests to pass this new param causing non-deterministic ad density and placement results.

🐛 [story ads] Fix flaky placement algo tests.

---

.eslintignore
.gitignore
.prettierignore
build-system/common/esbuild-babel.js
build-system/common/transform-cache.js
build-system/tasks/clean.js
build-system/tasks/css/init-sync.js
build-system/tasks/css/jsify-css.js

**summary**
Final step for [#33011](https://github.com/ampproject/amphtml/issues/33011)
The slowest part of AMP's dev server startup is transforming CSS via `postcss`. This PR takes the infrastructure we built for [caching babel transforms](https://github.com/ampproject/amphtml/pull/33314) which was surprisingly generic, and reuses it for caching our css transforms.
_results_:
- warm cache css build reduced from 2.7s --> 100ms.
- total lazy server startup time for a warm cache is now 1s.
- extension building should be sped up as well, although these were already pretty fast so much less interesting.
**implementation notes**
- Renamed `BabelTransformCache` to `TransformCache`, and moved it from  `esbuild-babel.js` to its own file.
- Specified cache location as `.css-cache` (corollary to …

build-system: Introduce CSS Cache 🚀

---

build-system/compile/bundles.config.extensions.json
build-system/tasks/extension-helpers.js

This is a follow up PR to https://github.com/ampproject/amphtml/pull/32742, which abstracts the generation of preact and react npm binaries.

Bento: Make generating preact/react npm binary easier

---

extensions/amp-sidebar/validator-amp-sidebar.protoascii
extensions/amp-story/1.0/test/validator-amp-story-sidebar.out

Contributes to I2R: #33293
It adds a warning on `amp-sidebar` when it's in an `amp-story`, and suggests to use anchor tags or amp-story-player controls.

🚮  [Story sidebar] Added warning to deprecate amp-sidebar in stories

---

extensions/amp-story/1.0/amp-story-user-overridable.css

Closes #32678
Removes the `overflow: hidden` on preset layers since the layers shouldn't cut off items that are partially outside the layer

🖍  [Story responsiveness] Show overflow on preset layers

---

extensions/amp-story-player/0.1/amp-story-player.js
src/amp-story-player/amp-story-component-manager.js
src/amp-story-player/amp-story-player-impl.js
src/amp-story-player/amp-story-player-viewport-observer.js

Closes #33546
Attaching our own custom `layoutCallback` in the `amp-story-player-impl.js` class to the `<amp-story-player>` element was confusing the AMP runtime, which would call our custom `layoutCallback()` instead of the `custom-element.js`'s `layoutCallback()`. This would cause the loader to get stuck since it's waiting for `AMP.BaseElement.layoutCallback()` to finish.

[amp-story-player] Change name of build/layout callbacks

---

build-system/common/ci.js
build-system/common/git.js
build-system/common/main-branch.js
build-system/common/utils.js
build-system/compile/internal-version.js
build-system/pr-check/build-targets.js
build-system/pr-check/npm-checks.js
build-system/pr-check/utils.js
build-system/pr-check/visual-diff-tests.js
build-system/tasks/bundle-size/index.js
build-system/tasks/check-exact-versions.js
build-system/tasks/check-links.js
build-system/tasks/cherry-pick.js
build-system/tasks/prepend-global/index.js
build-system/tasks/runtime-test/helpers-unit.js
build-system/tasks/visual-diff/index.js

- Remove all hard-coded references to `master` in the `build-system/` implementation
- Add a single source of truth in `common/main-branch.js` (will be changed to `main` later)
**Notes:**
- As written, this PR should be a no-op. 
- Documentation / comment URLs in our codebase will be changed in a follow up PR.
Partial fix for #32195

Make `build-system` code main-branch-agnostic

---

extensions/amp-script/amp-script.md

`utf8` fixes the following TS error:

📖  amp-script: Recommend "utf8" for Utf8AsciiLatin1Encoding

---

extensions/amp-iframe/0.1/amp-iframe.js
extensions/amp-iframe/0.1/test/test-amp-iframe.js

Partial revert of https://github.com/ampproject/amphtml/pull/33382
In some circumstances the `ResizeObserver` produces incomplete measurement results. Research is ongoing still why and when. But due to the incorrect results, the iframe believes it has been unloaded.
Test is available here: https://forest-spark-school.glitch.me/original.html

Revert async pause for an iframe due to zero-size iframes

---

build-system/global-configs/experiments-config.json
build-system/global-configs/experiments-const.json

The stats confirm no negative effect from this launch.

Launch INI_LOAD_INOB experiment

---

extensions/amp-dailymotion/0.1/amp-dailymotion.js
extensions/amp-dailymotion/0.1/test/test-amp-dailymotion.js

Provide unlayout callback for amp-dailymotion

---

extensions/amp-izlesene/0.1/amp-izlesene.js
extensions/amp-izlesene/0.1/test/test-amp-izlesene.js

Provide unlayoutCallback for amp-izlesene

---

extensions/amp-kaltura-player/0.1/amp-kaltura-player.js
extensions/amp-kaltura-player/0.1/test/test-amp-kaltura-player.js

Provide unlayoutCallback for amp-kaltura-player

---

extensions/amp-reach-player/0.1/amp-reach-player.js
extensions/amp-reach-player/0.1/test/test-amp-reach-player.js

Provide unlayoutCallback for amp-reach-player

---

extensions/amp-soundcloud/0.1/amp-soundcloud.js
extensions/amp-soundcloud/0.1/test/test-amp-soundcloud.js

Provide unlayoutCallback for amp-soundcloud

---

extensions/amp-springboard-player/0.1/amp-springboard-player.js
extensions/amp-springboard-player/0.1/test/test-amp-springboard-player.js

Provide unlayoutCallback for amp-springboard-player

---

extensions/amp-vine/0.1/amp-vine.js
extensions/amp-vine/0.1/test/test-amp-vine.js

Provide unlayoutCallback for amp-vine

---

extensions/amp-o2-player/0.1/amp-o2-player.js
extensions/amp-o2-player/0.1/test/test-amp-o2-player.js

Provide unlayoutCallback for amp-o2-player

---

build-system/tasks/storybook/package-lock.json
build-system/tasks/storybook/package.json
extensions/amp-render/1.0/storybook/Basic.amp.js

Upgrades to version 1.1.9. 1.1.8 was skipped due to bugfix.
With this upgrade we're now generating `amp-script` hashes. A previous story included a hardcoded hash, so we remove it.

🏗 Bump @ampproject/storybook-addon

---

extensions/amp-base-carousel/1.0/base-carousel.js
extensions/amp-base-carousel/1.0/scroller.js

Depending on the props given, looping instances of the carousel may inflate the size of its container to enable scroll navigation when advancing. When there is not enough room to scroll to later slides when advancing, the carousel instead re-renders to the slides in place. 
This feature is expected to impact a small number of cases overall. Specifically, it impacts carousels with `loop=true` that are given slides such that the `advanceCount` or (`autoAdvanceCount` when `autoAdvance=true`) is >=25% of the total slides. For instance, advancing by `2` for carousels with `8` slides are transitioned with new renders, as opposed to slide lengths of `9` which transition via scrolling. 
When we double the slides, we roughly double the proportion necessary to meet this threshold, making it easier …

Bento Carousel: Remove doubly rendered JSX

---

extensions/amp-bind/amp-bind.md

fixes ampproject/amp.dev#5440
Technically not invalid currently, but since the playground is calling the debugger to get information, it is flagging the example with a scary warning.

set technically correct defaults for amp-bind example

---

validator/README.md

Looks like `openjdk-7-jre` [has been removed since Ubuntu 16.04](https://unix.stackexchange.com/a/475657).  Using the `default-jdk` package seems to have worked for me; not sure if there's complete compatibility or not (and my understanding is that it's intended to continually change in the future, so I'm not sure if there's a better approach).

📖  Use `default-jdk` for `amp validator --update_tests` instead of `openjdk-7-jre`

---

extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js
extensions/amp-ad/0.1/amp-ad-3p-impl.js

**summary**
Partial for https://github.com/ampproject/amphtml/issues/31540
I had recently (ish) [run an experiment](https://github.com/ampproject/amphtml/pull/32437) to see if moving from sync measures to async would cause a hit to ads metrics.
It had a minor one (-0.2% in a few areas). In order to mitigate this, we can move the async measures to `buildCallback` instead of within the layout flow, so that by the time the measure is needed it is ready.

ads experiment: move initialIntersection to buildCallback

---

amp.js
build-system/tasks/check-asserts.js
src/core/assert.js
src/log.js

Asserts the expected presence/absence of devAsserts and userAsserts be checking sentinel strings against `amp.js` and `v0.js` (not yet included in the actual CI, this PR is just the task/check itself)

✅ Add amp task to validate assertion DCE-ing

---

.circleci/config.yml
build-system/pr-check/bundle-size.js

With this, we should no longer have any size fluctuations due to code that would have normally been DCE'd in production builds.
**Notes:**
- The `Bundle Size` job now does its own builds (using an XLarge VM), and doesn't wait for test binaries to be built
- Total CI round trip time remains unchanged (because there are other longer-running jobs)
- The bundle-size [check run](https://github.com/ampproject/amphtml/pull/33659/checks?check_run_id=2281134449) shows a small decrease (because we're no longer counting DCE-able code)
Fixes #33657
Fixes #33658

🏗 Run the `bundle-size` check on pure production code

---

.circleci/config.yml
build-system/common/ci.js
build-system/pr-check/bundle-size.js
build-system/pr-check/cross-browser-tests.js
build-system/pr-check/e2e-tests.js
build-system/pr-check/experiment-build.js
build-system/pr-check/experiment-tests.js
build-system/pr-check/module-build.js
build-system/pr-check/module-tests.js
build-system/pr-check/nomodule-build.js
build-system/pr-check/nomodule-tests.js
build-system/pr-check/unit-tests.js
build-system/pr-check/unminified-build.js
build-system/pr-check/unminified-tests.js
build-system/pr-check/utils.js
build-system/pr-check/validator-tests.js
build-system/pr-check/visual-diff-tests.js

This PR uses [CircleCI's workspaces](https://circleci.com/blog/persisting-data-in-workflows-when-to-use-caching-artifacts-and-workspaces/) to indicate to downstream jobs that they should not be executed; this happens before checking out the code, so a job that is going to be skipped completes within ~15-20 seconds instead of ~2-3 minutes

Gracefully halt downstream jobs on CircleCI when parent jobs are skipped

---

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-shared.css
extensions/amp-story-auto-ads/0.1/story-ad-ui.js
extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js

This regression was introduced when I moved the button into shadow DOM. When a listener is fired in the parent dom, the `event.target` will be the shadow host, not the actual element. This causes amp-story to swallow the click, as it thinks it should be a page navigation.
Setting the `role="button"` on the shadow host tells the amp-story to let the click flow through. Also resizes the host so that actual navigation clicks will navigate.

🐛 Fix "story-ad-click" trigger.

---

extensions/amp-timeago/1.0/test/validator-amp-timeago-mutation-error.html
extensions/amp-timeago/1.0/test/validator-amp-timeago-mutation-error.out
extensions/amp-timeago/1.0/test/validator-amp-timeago-mutation.html
extensions/amp-timeago/1.0/test/validator-amp-timeago-mutation.out
extensions/amp-timeago/1.0/test/validator-amp-timeago.html
extensions/amp-timeago/1.0/test/validator-amp-timeago.out
extensions/amp-timeago/validator-amp-timeago.protoascii

Note: `bento-timeago` experiment is still active, so this PR does not "launch" the component, only widens the pool for experimental usage and feedback to include valid AMP documents on the web.
Partial for #29246

Add validation rules for amp-timeago:1.0

---

extensions/amp-date-display/1.0/test/validator-amp-date-display.html
extensions/amp-date-display/1.0/test/validator-amp-date-display.out
extensions/amp-date-display/validator-amp-date-display.protoascii

Note: `bento-date-display` experiment is still active, so this PR does not "launch" the component, only widens the pool for experimental usage and feedback to include valid AMP documents on the web.
Partial for #30189.

Add validation rules for amp-date-display:1.0 on websites

---

build-system/server/app-utils.js
build-system/server/app.js
build-system/tasks/pr-deploy-bot-utils.js
test/manual/video-caching.amp.html

The local server contains logic to replace references to `amp-story-0.1.js` to `-1.0.js`. This removes that logic since `0.1` is no longer shipped.
I've confirmed that this repository no longer references `amp-story-0.1.js` and that it does not use the `story_v` query parameter referenced in a changed server route.

🚮 Remove server logic for amp-story 0.1

---

extensions/amp-accordion/1.0/storybook/Bind.amp.js

Apparently the accordion does not like having the `expanded` attribute when `amp-bind` is used
This issue seems to be isolated to Storybook.  Tried it out on a test page and the issue does not occur
Issue for tracking storybook: https://github.com/ampproject/amphtml/issues/33679

[bento][amp-accordion] Accordion storybook issue

---

extensions/amp-script/0.1/user-activation-tracker.js

**summary**
Fixes https://github.com/ampproject/amp.dev/issues/4879, https://github.com/ampproject/amphtml/issues/30548
The activity tracker relies on careful ordering of `longTask` events. We need it to be a sequence of START --> END --> START --> END.
The `.catch` call ended up delaying the `LONG_TASK_END` event by an extra microtask, which was just enough to make it occur after a 2nd start event.
**before**
**after**
**note**: a more robust but larger fix would either be: (a) start/end counter (so order doesn't matter), or (b) the `longTask` fn gets called with a "type" for start/end (avoids promises)

amp-script: fix long task start/end order for within the same macrotask

---

build-system/pr-check/nomodule-build.js

Without this, the check cannot be skipped. See https://app.circleci.com/pipelines/github/ampproject/amphtml/6229/workflows/0d129b3f-f949-42df-bb67-e2ec2dbdbc69/jobs/88512/parallel-runs/0/steps/0-111
Addresses https://github.com/ampproject/amphtml/pull/33620#discussion_r608918755

🏗 Extract `PERCY_TOKEN` before skipping the check

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

- Create publisher facing showcase ineligible event (#1595)
- Start listening to GA Events in ConfiguredBasicRuntime (#1593)
- Route to the new contributionoffersiframe in ContributionsFlow if use UpdatedOfferFlows in the ClientConfig is true. (#1592)
- Initial Implementation of Google Analytics Event Listener (#1589)
- Update dependency postcss-import to v14.0.1 (#1590)
- Remove margin-bottom for SwG UX iframes (#1588)
- Compile swg-mini-promp CSS (#1587)

SwG Release 0.1.22.155

---

.circleci/config.yml
build-system/common/ci.js
build-system/pr-check/utils.js

This prevents a conflict when more than one parallel job signals a graceful halt. For example, [here](https://app.circleci.com/pipelines/github/ampproject/amphtml/6244/workflows/5ddec186-f3d0-47da-9f0f-0decdadd4443/jobs/88781/parallel-runs/0/steps/0-101).

🏗 Use unique filenames to signal graceful halt of CircleCI Jobs

---

extensions/amp-analytics/0.1/amp-analytics.js
extensions/amp-analytics/0.1/test/test-transport.js
extensions/amp-analytics/0.1/transport.js
extensions/amp-script/0.1/amp-script.js
extensions/amp-script/0.1/test/unit/test-amp-script.js
test/manual/analytics-script-target.html

**summary**
Fixes: https://github.com/ampproject/amphtml/issues/33580
Enables the usage of the `amp-script: ` protocol as an amp-analytics request endpoint.

Teach amp-analytics how to forward events to amp-script

---

build-system/compile/compile.js
build-system/tasks/check-types.js

This should further assist in splitting up #32875
Follow up to #33469

🏗 Make `check-types` more granular by splitting `src/` and `extensions/`

---

.circleci/check_config.sh
.circleci/compute_merge_commit.sh
.circleci/config.yml
.circleci/fail_fast.sh
.circleci/fetch_merge_commit.sh
.circleci/get_pr_number.sh
.github/workflows/create-design-review-issue.yml
.github/workflows/cross-browser-tests.yml
.renovaterc.json
build-system/common/main-branch.js
build-system/server/app-index/header-links.js

This PR will need to be force-merged immediately after the branch is renamed. (Until then, CI is expected to fail.)
In anticipation of this change, all CI code in `build-system/` was refactored in #33535. This PR modifies exactly one source of truth in that directory (see code below). Once the dust settles, we can delete `main-branch.js`.
https://github.com/ampproject/amphtml/blob/702f2798967f7e01ecd06145c6f438695a38d638/build-system/common/main-branch.js#L21
**Next steps:**
- Once the branch is renamed, all visitors to the `amphtml` repo will see a notification like this:
- For those who use `upstream` to refer to `ampproject/amphtml` and `origin` to refer to their fork, here are distilled instructions that will work (to be run after the rename is done):
```sh
git checkout master
git …
```

🏗 Update AMP's CI config to work on the `main` branch

---

.circleci/check_config.sh
.circleci/compute_merge_commit.sh
.circleci/config.yml
.circleci/fail_fast.sh
.circleci/fetch_merge_commit.sh
.circleci/get_pr_number.sh
.github/workflows/create-design-review-issue.yml
.github/workflows/cross-browser-tests.yml
.renovaterc.json
build-system/common/main-branch.js
build-system/server/app-index/header-links.js

Repeat of https://github.com/ampproject/amphtml/pull/33698 for good measure because it doesn't appear in the [commit history of `main`](https://github.com/ampproject/amphtml/commits/main), but does appear in the [commit history of `master`](https://github.com/ampproject/amphtml/commits/master). (Likely a GitHub skew.)

🏗 Update AMP's CI config to work on the `main` branch (#33698)

---

build-system/test-configs/config.js
build-system/test-configs/forbidden-terms.js
contributing/building-an-amp-extension.md

- Adds `.md` files to the presubmit check glob.
- Replaces `checkComments` flag with `checkProse`, which causes a term to be matched in source, comments and Markdown documentation.

🏗 Check forbidden terms in Markdown files

---

build-system/pr-check/build-targets.js

This will ensure that any changes made to implementation or rules are tested during CI. E.g. #33710

🏗 Run `lint` and `presubmit` when the checks' implementation or rules are changed

---

build-system/test-configs/conformance-config.textproto

Closure compiler [recently added](https://github.com/google/closure-compiler/commit/95499c4c0bb395ea54cd254c435cab0868cb76a0) support for [`allowlist`](https://github.com/google/closure-compiler/blob/1ccfd438b8fdd7cf15f6b7026ec23c0f1ef16fb4/src/com/google/javascript/jscomp/CheckConformance.java#L107-L117), so we can use it instead of `whitelist`.
Addresses https://github.com/ampproject/amphtml/issues/33694#issuecomment-815332256
Related to #32875

🏗 Use the `allowlist` option in the closure conformance config

---

build-system/tasks/amp-task-runner.js

The `gulp` task runner begins by printing the full path of `gulpfile.js` relative to the OS home dir. During the switch to the `amp` task runner, we initially set out to replicate this behavior, but ended up logging a hard-coded `amphtml/amp.js` instead. (See https://github.com/ampproject/amphtml/pull/33315#discussion_r596238113)
However, as pointed out by @antiphoton, this can be very confusing to developers who maintain multiple local copies of the `amphtml` repo in different directories. As a result, this PR goes back to explicitly logging the path of the task file relative to the OS home dir. With this, variations in the task file path are properly captured.
**Before:**
**After (main local repo):**
**After (duplicate local repo - type 1):**
**After (duplicate local repo - type 2):**

🏗 Print relative path of task file while running `amp` tasks

---

extensions/amp-a4a/0.1/refresh-manager.js
extensions/amp-a4a/0.1/test/test-refresh.js

This should bring into alignment refresh on/off behavior as specified in [the docs](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/refresh.md ).
(This is a duplicate of PR#33646. That PR was broken due to pulling in a bunch of unrelated changes. Not sure what happened, but likely due to my AMP environment rusting over from not using it in a while.)

Ensure no error is displayed when publishers correctly disable slot for refresh with data attribute.

---

amp.js
build-system/task-runner/amp-task-runner.js
build-system/task-runner/cli-runner.js
build-system/task-runner/install-task-runner.js
build-system/test-configs/forbidden-terms.js
gulp-deprecated.js
package.json

- The `amp` / `gulp` commands are hard-coded symlinks to `amp.js` / `gulp-deprecated.js` in the local `amphtml` repo.
- While this works for a single local repo, it breaks down when there are two repo copies in different directories.
- Running a task in the second directory redirects to the first due to the hard-coded symlink, as reported by @antiphoton.
- Replaces hard-coded symlinks with global wrapper scripts that load the correct repo-local task runner.
- Ensures that the scripts gracefully error out when invoked from outside a `git` directory.
- Seamlessly updates any previously installed symlinks during `npm install`.
- Continues to detect and respect globally installed `gulp-cli` / `gulp` (prints a warning and exits).
- Consolidates all task …

🏗 Make `amp` and `gulp` execute the correct repo-local task runner

---

build-system/compile/compile.js
build-system/tasks/check-types.js

Reverts ampproject/amphtml#33696

Revert "🏗 Make `check-types` more granular by splitting `src/` and `extensions/`"

---

build-system/global-configs/experiments-config.json
build-system/global-configs/experiments-const.json

Let's run the integration tests again next week before actually shipping.
Edit: Reverting due to #33727 breaking google ads integration tests. I would like to have them re-enabled and passing against nightly before shipping.

🐛[no-signing] unlaunch pt 2

---

extensions/amp-a4a/0.1/head-validation.js
extensions/amp-a4a/0.1/test/test-head-validation.js

The regex was excluding anything with a `rtv/1234` in the path.

🐛 [no-signing] handle versioned extensions correctly

---

build-system/tasks/dist.js

With this PR, we no longer build ~300 ad vendors when only a subset of extensions / runtime binaries are built. This only takes effect during local development and doesn't affect CI or releases.

🏗  Optimize `dist` when only a subset of binaries need to be built

---

ads/README.md

There is a typo in [README](https://github.com/ampproject/amphtml/blob/main/ads/README.md#ad-markup)

Fix a typo in README

---

build-system/compile/bundles.config.extensions.json
extensions/amp-base-carousel/1.0/test/validator-amp-base-carousel.html
extensions/amp-base-carousel/1.0/test/validator-amp-base-carousel.out
extensions/amp-base-carousel/validator-amp-base-carousel.protoascii
extensions/amp-inline-gallery/1.0/test/validator-amp-inline-gallery-pagination.html
extensions/amp-inline-gallery/1.0/test/validator-amp-inline-gallery-pagination.out
extensions/amp-inline-gallery/1.0/test/validator-amp-inline-gallery-thumbnails.html
extensions/amp-inline-gallery/1.0/test/validator-amp-inline-gallery-thumbnails.out
extensions/amp-inline-gallery/validator-amp-inline-gallery.protoascii
extensions/amp-stream-gallery/1.0/test/validator-amp-stream-gallery.html
extensions/amp-stream-gallery/1.0/test/validator-amp-stream-gallery.out
extensions/amp-stream-gallery/validator-amp-stream-gallery.protoascii

This PR adds validation rules for:
- `amp-base-carousel:1.0` - `latest` still goes to `0.1.`
- `amp-inline-gallery:1.0` and usage of `amp-inline-gallery-pagination` and `amp-inline-gallery-thumbnails`  - `latest` still goes to `0.1.`
- `amp-stream-gallery:1.0` and `amp-stream-gallery-latest`
- `amp-stream-gallery:0.1` and `latest` were never valid AMP, so `1.0` can use `latest` without affecting any valid AMP users. On a related note, this PR also updates the bundle `latestVersion` for `amp-stream-gallery` to point to `1.0` as no valid AMP documents should be able to use `amp-stream-gallery-latest.js` now anyhow.
Note: `bento-carousel`, `bento-inline-gallery`, and `bento-stream-gallery` experiments are still active, so this PR does not "launch" these components, only widens the pool for …

Add validations for Bento carousels on websites

---

src/core/assert.js
src/error.js
src/log.js
src/service/resource.js
test/unit/test-assert.js
test/unit/test-log.js

Currently core assertion code picks out the first element in the message array and assigns it to `error.associatedElement`. This is only used in two places and only by AMP code. This PR hoists that logic up into `prepareError` in `src/log`
Part of https://github.com/ampproject/amphtml/issues/33631

♻️ Hoist associatedElement extraction out of core

---

build-system/global-configs/experiments-config.json
build-system/global-configs/experiments-const.json

Third time is the charm :)
Once this is merged we can re-enable and re-run all the integration tests against the new nightly.

[no-signing] launch experiment

---

build-system/task-runner/install-amp-task-runner.js

The local var `runnerBinary` is now an exact duplicate of `ampBinary` on line 37, so we should remove it. Forgot to do this in #33787.

🏗 Remove duplicate local var in task runner installer

---

extensions/amp-brightcove/0.1/amp-brightcove.js
extensions/amp-brightcove/0.1/test/test-amp-brightcove.js

Disables the autoplay setting if configured on the Brightcove Player in `<amp-brightcove>`.
Restores dock functionality on `<amp-brightcove>`, which was disabled in #33137
cc @alanorozco

🐛 Restore `dock` on amp-brightcove

---

build-system/common/esbuild-babel.js
build-system/common/transform-cache.js
build-system/tasks/css/jsify-css.js

This is a pending item that was discussed in https://github.com/ampproject/amphtml/pull/33313#discussion_r603598002. In addition to moving directory management into `TransformCache`, this PR lazily instantiates the cache on first use. Doing it at the global scope during module load will slow down all `amp` tasks, even unrelated ones.

🏗 Move directory management into `TransformCache`

---

.gitignore
build-system/tsconfig.json

This shows up as a local diff when you run `amp check-build-system`.
Bonus fix: Update comment with number of remaining errors in `build-system/tasks/e2e/`

🏗 Ignore `build-system/dist`

---

examples/visual-tests/amp-story-player/story-attribution.html
test/visual-diff/visual-tests

Part of https://github.com/ampproject/amphtml/issues/33353

[amp-story-player] ✅  Add story attribution visual test

---

build-system/server/lazy-build.js
build-system/tasks/extension-helpers.js
build-system/tasks/helpers.js

**summary**
Fixes: https://github.com/ampproject/amphtml/issues/33664
- Uses `esbuild` metafiles for perfectly determining JS dependencies of an extension (or runtime).
- Utilizes this function for all JS. Even the less used runtime have watch modes that now work as expected.
- Creates a new esbuild plugin for stripping import assertions
**testing**
For both `amp` and `amp --compiled`:
- Modify `amp.js` --> v0 should be rebuilt
- Modify `install-alp.js`+ one other alp dependency --> alp should be rebuild.
- Modify amp-story-player-entrypoint --> amp-story-player should be rebuild.
- Load an amp-bind example, modify a ww.js dep --> ww.js should be rebuilt, only once.
- Load an amp-bind example, modify a `jison` file --> jison should be recompiled (as well as ww.js)
- Load an amp network …

build-system: use metafile for smarter watching

---

src/service/performance-impl.js
test/unit/test-performance.js

**summary**
Use `AmpDoc#onVisibilityChange` for both `inactive` and `hidden` states, instead of a mix of visibilitychange API and ampdoc.
- Removes the need for a `fakeWin` in tests.
- I removed the test "For chromium 77", although I couldn't understand why it existed in the first place. Should I put it back? It seemed like a regular CLS test (of which we have others)
---
Note: this is relatively low priority. When reading through the code again I was just confused as to why we are doing this.

performance-impl: exclusively use ampdoc visibility state

---

extensions/amp-accordion/0.1/amp-accordion.js
extensions/amp-accordion/0.1/test/test-amp-accordion.js

`0.1 amp-accordion` should not support `amp-bind` on the `expanded` attribute.
This is related to: https://github.com/ampproject/amphtml/pull/33493
Validator is currently unable to distinguish between `0.1` and `1.0` for attributes using `amp-bind` so we must throw an error to protect against improper usage.

✨ [amp-accordion] Error when amp-accordion 0.1 is used with amp-bind on the expanded attribute

---

build-system/common/check-package-manager.js

Python 3.5 reached EOL a few months ago: https://devguide.python.org/#status-of-python-branches
This PR changes AMP's list of supported versions to 2.7 (legacy support still works) and 3.6+. Developers with other versions of python on their machines will see a warning during `npm install`, but devtools will all continue to work normally.
**Obligatory xkcd:** ([link](https://xkcd.com/1987/))

🏗 Drop support for python 3.5 now that it has reached EOL

---

3p/amp-script-proxy-iframe.js
build-system/compile/bundles.config.js
build-system/tasks/dist.js
build-system/tasks/extension-helpers.js
examples/amp-script/example.sandboxed.amp.html
extensions/amp-script/0.1/amp-script.js
extensions/amp-script/0.1/test/integration/test-amp-script.js
extensions/amp-script/validator-amp-script.protoascii

**summary**
Fixes: https://github.com/ampproject/amphtml/issues/30193. The relevant `worker-dom` changes are here: https://github.com/ampproject/worker-dom/pull/1042.
- Creates a new binary in `dist.3p` called `amp-script-proxy-iframe.js`
- Creates the `sandboxed` attribute for `<amp-script>` and allows it in the validator. When present, csp is ignored.
- 🍝  integration test

✨ amp-script: allow 3p scripts without csp hash if sandboxed

---

.eslintignore
.gitignore
.prettierignore
build-system/common/esbuild-babel.js
build-system/common/transform-cache.js
build-system/compile/closure-compile.js
build-system/compile/helpers.js
build-system/compile/pre-closure-babel.js
build-system/tasks/clean.js
build-system/tasks/css/jsify-css.js
build-system/tasks/helpers.js

- Builds on the excellent work done by @samouri to create `TransformCache` in #33314 and #33313
- Introduces a persistent on-disk cache `.pre-closure-cache` for pre-closure babel transforms
- Rewrites `preClosureBabel()` to use `TransformCache` to cache (and invalidate) babel output
- Repurposes the non-persistent `cacheDir` to `outputDir` (closure requires the original src tree structure)
- Updates `amp clean` to wipe out the cache directory
- Fixes assorted bugs that snuck in over time
- Makes sure that `fs.outputFile()` completes in the `then()` block of `TransformCache.set()`
- Removes unused `modifiedFile` param from `compileJs()`
- Adds missing `continueOnError: true` while setting up `watch` in `compileJs()`
**Results:**
- First time compilation of `v0.js` gets a …

🚀🏗 Speed up minified compilation by caching pre-closure transforms

---

extensions/amp-auto-ads/0.1/placement.js

Doing this as a temporary stopgap fix.

Do not allow amp-auto-ads from inserting to above the viewport

---

build-system/tasks/helpers.js

#33840 introduced a way to extract the dependencies of JS entry points so that the watcher could intelligently react to code changes. This broke in situations when an extension contained JSX, because `getDependencies()` wasn't using all the plugins required to parse and transform the source code.
This PR makes `getDependencies()` use the exact set of plugins that would've been used by `esbuild` during normal compilation. With this, watching extensions containing JSX code is fixed, and future changes to the set of babel plugins used during compilation will automatically get picked up by `getDependencies()`.
Addresses https://github.com/ampproject/amphtml/pull/33873#issuecomment-821327849
Implements https://github.com/ampproject/amphtml/pull/33873#issuecomment-821334930

🏗 Fix dependency extraction while watching JS entry points

---

.circleci/config.yml

There seems to have been a temporary blip with the old image. For example, [these logs](https://app.circleci.com/pipelines/github/ampproject/amphtml/6957/workflows/1db0388e-0be1-4411-abc1-534ab9bff66e/jobs/100978).
This PR switches to the new [April 2021 image](https://circleci.com/developer/images/image/cimg/base).

🏗 Update CircleCI base docker image from 12/2020 to 4/2021

---

extensions/amp-base-carousel/1.0/amp-base-carousel.js
extensions/amp-base-carousel/1.0/arrow.js
extensions/amp-base-carousel/1.0/base-carousel.js
extensions/amp-base-carousel/1.0/storybook/Basic.amp.js
extensions/amp-base-carousel/1.0/storybook/Basic.js
extensions/amp-base-carousel/1.0/test/test-base-carousel.js
extensions/amp-stream-gallery/1.0/amp-stream-gallery.js
extensions/amp-stream-gallery/1.0/storybook/Basic.amp.js
extensions/amp-stream-gallery/1.0/stream-gallery.js
extensions/amp-stream-gallery/1.0/test/test-stream-gallery.js

This PR changes the `arrowPrev` and `arrowNext` props to be `arrowPrevAs` and `arrowNextAs`, such that a custom navigational button is given as `() => <button></button>` as opposed to plain `<button></button>`. This is inline with the Lightbox custom close button introduced in #33105.
Note that all AMP elements that integrate with these `as` props have an intermediary layer where the prop is defined via `updatePropsForRendering`. This can be removed once we have a generic soln in PreactBaseElement, which will be introduced in a follow up PR.

Bento Carousel: Support passing in custom arrows with `as`

---

extensions/amp-instagram/1.0/test/validator-amp-instagram.html
extensions/amp-instagram/1.0/test/validator-amp-instagram.out
extensions/amp-instagram/validator-amp-instagram.protoascii

Note: `bento-instagram` experiment is still active, so this PR does not "launch" the component, only widens the pool for experimental usage and feedback to include valid AMP documents on the web.
Partial for #30172

Add validation rules for amp-instagram:1.0

---

extensions/amp-lightbox/1.0/test/validator-amp-lightbox.html
extensions/amp-lightbox/1.0/test/validator-amp-lightbox.out
extensions/amp-lightbox/1.0/test/validator-amp4ads-lightbox.html
extensions/amp-lightbox/1.0/test/validator-amp4ads-lightbox.out
extensions/amp-lightbox/validator-amp-lightbox.protoascii

Notes: 
- `bento-lightbox` experiment is still active, so this PR does not "launch" the component, only widens the pool for experimental usage and feedback to include valid AMP documents on the web.
- This PR preserves `controls` and `from` attr from 0.1 but there is currently no indication their purpose, so there is reason to assume they are unsupported in 1.0.
Partial for #31052

Add validation rules for amp-lightbox:1.0

---

extensions/amp-accordion/amp-accordion.md

Small update to documentation to clarify bind behavior in `1.0` migration notes.

✨ [bento][amp-accordion] Small update to documentation

---

builtins/amp-img.js
test/unit/test-amp-img-intrinsic.js
test/unit/test-amp-img-v1.js
test/unit/test-amp-img.js

Avoid late LCP for attaching the same node again during hydration.

🚀 Early exit for SSR AMP Image 

---

extensions/amp-analytics/0.1/test/test-transport.js
extensions/amp-analytics/0.1/transport.js
extensions/amp-list/0.1/amp-list.js
extensions/amp-list/0.1/test/test-amp-list.js
extensions/amp-render/1.0/amp-render.js
extensions/amp-script/0.1/amp-script.js
src/services.js
src/url.js

**summary**
Partial for https://github.com/ampproject/amphtml/issues/33581
Now that `amp-script.callFunction` is used in 4 places (a4a rtc, analytics, amp-list, amp-render), it is worth extracting the common logic at callsites into `AmpScriptService`.
Notes
- I corrected the jsdoc for var args functions `callFunction` and `fetch`
- Centralized logic the call logic into `amp-script.js.AmpScriptService`
TIL: do not export things from files that call `AMP.extension`.
**size diff**
```
dist/v0/amp-list-0.1.mjs: Δ -0.07KB
dist/v0/amp-list-0.1.js: Δ -0.10KB
dist/v0/amp-render-1.0.mjs: Δ -0.18KB
dist/v0/amp-render-1.0.js: Δ -0.14KB
dist/v0/amp-script-0.1.mjs: Δ +0.15KB
dist/v0/amp-script-0.1.js: Δ +0.16KB
dist/v0/amp-analytics-0.1.mjs: Δ -0.08KB
dist/v0/amp-analytics-0.1.js: Δ -0.01KB
```

♻️ Extract AmpScriptService.fetch into its own fn.

---

examples/amp-story/analytics.html
extensions/amp-story/1.0/amp-story-page-attachment.js

Closes #33860
Outlinks are clicked inside a shadow dom, so the linker doesn't get triggered.
Fix: Replace the `.click()` with `triggerClickFromLightDom`, a utility function that clones the anchor tag and adds it into the light dom, so that the linker can catch the navigation event and append the `linker` queryParam.
Tested on swipe up and click, both work with the linker.

🐛 [Story outlink] Use linker on swipe up

---

extensions/amp-accordion/1.0/test/test-amp-accordion.js
src/.eslintrc.js
src/context/contextprops.js
src/preact/base-element.js
src/preact/slot.js
test/unit/context/test-contextprops.js
test/unit/preact/test-base-element-runtime.js
test/unit/preact/test-slot.js

This seems to be directly tied into `src/context`, so this move seemed to make sense to me. It also untangles one cross-dependency from `src/core/contextprops` into `src/context`
Somewhat related to #33631

♻️ Move contextprops from src/core to src/context

---

examples/amp-story/show-tooltip.html
extensions/amp-story/1.0/amp-story-page.js

Closes #31747
Relates to #32498
Twitter component can be focused with tabbing when outside the page. Adding the iframe to the tabindex logic will set `tabindex="-1"` on the iframe when the component is being initialized.
Does this work? Yes, the iframe is picked up by `toggleTabbableElements_` and sets `tabindex="-1"` on the iframe if it's on an active story. Since amp-twitter doesn't support a custom `tabindex` set by the creator, we don't need to worry about the iframe not being loaded when the `initializeTabbableElements` function is ran.

♿  [Story a11y] Make amp-twitter not tabbable if not on current page

---

extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js

Fixes https://github.com/ampproject/error-reporting/issues/79.

Minor fix: auto-lightbox: check image's loading state after async measurement

---

3p/amp-script-proxy-iframe.js
examples/amp-list-protocol-adapters.html
package-lock.json
package.json

**summary**
Fixes a bug in `<amp-script>` sandboxed mode where the upgrade completes before the underlying iframe/worker is actually ready to receive messages.
- Bumps `worker-dom` verison.
- Updates the iframe to send the new `worker-ready` message
- Modified the `amp-list` "protocol adapters" example to use a sandboxed amp-script, demonstrating the fix (would not have worked before PR)
~Blocked on https://github.com/ampproject/worker-dom/pull/1047~

Bump worker-dom, update iframe-worker-proxy

---

extensions/amp-script/0.1/amp-script.js
extensions/amp-script/amp-script.md
test/fixtures/e2e/amp-script/basic.amp.html

Related to https://github.com/ampproject/amphtml/issues/33402
Publishers wanting to use multiple inline amp-scripts in a page require multiple source SHAs. The current parsing logic expects them to be a space-delimited list in a single meta tag, but this is undocumented and non-obvious. This PR:

📖 Support newlines for amp-script meta hashes

---

.circleci/maybe_gracefully_halt.sh
build-system/tasks/check-invalid-whitespaces.js

**Before:**
**After:**
**Reference:** https://github.com/mrmlnc/fast-glob#dot
Follow up to #33926

🏗 Check dot files and directories for invalid whitespaces

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

It has been two weeks since we notified the vendors. With some manual testing, we could ramp it up a bit here.

Ramp up 3p-vendor-split to 10%

---

build-system/tasks/check-invalid-whitespaces.js

Forgot to do this in #33926 and #33927

🏗 Omit files / dirs in `.gitignore` during invalid whitespace checks

---

examples/amp-ad/doubleclick-rtc.amp.html
extensions/amp-script/0.1/amp-script.js
src/service/real-time-config/real-time-config-impl.js
test/unit/test-real-time-config.js

**summary** 
Fixes https://github.com/ampproject/amphtml/issues/33581.
- Adds support for RTC for fetching JSON from `amp-script`. 
- Unit test + manual example both included
- ~Blocked on https://github.com/ampproject/amphtml/pull/33900~

✨  Ads RTC: support amp-script fetching

---

extensions/amp-story/1.0/amp-story-open-page-attachment.css
extensions/amp-story/1.0/amp-story-open-page-attachment.js

Context / Fixes #33913
Add contrast protection for inline attachments.
[demo](https://philipbell-stamp-ui.web.app/examples/amp-story/attachment.html)
The theming for "no image pre-tap dark theme" will be added in #32767

✨ [Amp story] [Page attachments] [inline] Add contrast protection

---

build-system/server/new-server/router.js

We are getting CORS failures on a4a envelope since ads are served from a different domain intentionally (ads.localhost vs localhost).

Fix amp-ad a4a example server

---

examples/amp-story/auto-analytics.html
extensions/amp-story-auto-analytics/0.1/auto-analytics-configs.js
extensions/amp-story-auto-analytics/0.1/test/test-amp-story-auto-analytics.js

Closes #33463
Having `'groups': 'default'` overrides the `linker` configuration (if provided) and does not decorate URLs. 
The only way I was able to get the URLs decorated is by removing the `groups` property and specifying `destinationDomains`. which we would need to open an API for at the `<amp-story-auto-analytics>` component level.

[amp-story-auto-analytics] Add default linker

---

extensions/amp-story/1.0/amp-story-page.js

* Remove `isLastPage_()` and `isLastStoryPage_`
* Add `getFirstVideo_()`
* Update `maybeSetStoryNextUp_()` to apply to all pages
* Update `maybeSetStoryNextUp_()` to prefer using the first video when possible
* Add a comment explaining that "storyNextUp" is a param used for testing that may be changed or removed without notice

✨Update storyNextUp to auto-advance on all pages.

---

build-system/test-configs/forbidden-terms.js

One term is fine:
Start references for multiple terms are overridden:
**This change fixes it:**

🐛🏗 Fix start references for multiple forbidden terms

---

extensions/amp-story/1.0/amp-story-draggable-drawer.js
extensions/amp-story/1.0/amp-story-open-page-attachment.js
extensions/amp-story/1.0/amp-story-page-attachment-ui-v2.js
extensions/amp-story/1.0/amp-story-page-attachment.js
extensions/amp-story/1.0/amp-story.js

**summary**
Fixes https://github.com/ampproject/amphtml/issues/33993
Removes circular dependency from test-amp-story-bookend.

amp-story-bookend: fix circular dependency

---

extensions/amp-story/1.0/amp-story-page.js
extensions/amp-vimeo/0.1/amp-vimeo.js
src/mode-object.js
src/mode.js
src/service/video-manager-impl.js
src/utils/video.js
test/integration/test-video-manager.js
test/integration/test-video-players-helper.js
test/unit/test-mode.js

We would previously allow viewers to opt-in to a "lite" document by setting the query parameter `amp_lite`.
In practice, this signal was used sparingly—only to disable video autoplay.
Since viewers almost never ask for a lite document, we remove this notion.

🚮 Remove notion of a lite viewer

---

build-system/tasks/report-test-status.js
build-system/tasks/runtime-test/helpers.js
build-system/tasks/runtime-test/runtime-test-base.js

- Throws from `teardown()` immediately after a fatal error is detected (to ensure the task doesn't stall)
- Adds a check for a non-existent `results` object in `reportTestRunComplete()` (some fatal errors don't yield results)
With this, errors like the one in https://github.com/ampproject/amphtml/issues/30907#issue-732459832 will cleanly exit with an error message
Fixes #30907

🏗 Prevent Karma from hanging when a transformation error is encountered

---

build-system/tasks/validate-html-fixtures.js

This PR adds a way to validate HTML fixtures that are currently skipped from checks due to existing errors.
**Usage:**
```sh
amp validate-html-fixtures # Passes because fixtures with errors are skipped
amp validate-html-fixtures --include_skipped # Fails with a huge number of errors
amp validate-html-fixtures --include_skipped --local_changes # Shows if the file just edited is indeed fixed
```
With this, it will become significantly easier for us to fix the [_huge_](https://gist.github.com/rsimha/eda744513ea77c82fc45a56ad8df15e5) list of validation errors in our test fixtures.
Follow up to #33997
Partial fix for #25149

 🏗 Add a way to validate all HTML test fixtures, even skipped ones

---

build-system/global-configs/canary-config.json
extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/story-ad-page.js
extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js
src/experiments/story-ad-auto-advance.js
tools/experiments/experiments-config.js

Auto advancing story ads at 3 time intervals (6, 8, 10s) in order to determine monetization impact.
Partial #33969

🧪[story ads] Start auto advance exp

---

build-system/tasks/make-extension/bento/amp-__component_name_hyphenated__/__component_version__/test/test-amp-__component_name_hyphenated__.js

Most of the Bento tests already use `htmlFor`, which is a lot nicer than using DOM APIs to define trees.

🏗 Bento extension generator: use `htmlFor`  in test

---

extensions/amp-analytics/0.1/vendors/taboola.json

@micajuine-ho I think I messed up with the merging. I created a new branch anyway which is probably the right thing to do. This pull request is to fix the bug in #32803. Found an issue where our trk.js was not getting loaded and after debugging found out it is because of missing "iframePing":true. Can you please take a look at the change to fix that. We need this to be resolved, since we have customers waiting for this fix. Thanks

🐛 added support for iframePing to load trk.js

---

ads/_config.js
ads/vendors/myfinance.js
ads/vendors/myfinance.md

- Configures the clientIdScope for the myfinance Ad Network, which was inadvertently left off initially  
- Fixes attribute typo in the myfinance.md

🐛 AmpAd: Add clientIdScope to myfinance ad network

---

build-system/tasks/check-types.js

🏗 Add catch-all type-check target and src dirs

---

.renovaterc.json

This PR enables automatic merging of renovate PRs that update `devDependencies` and have passed all other CI checks.
**Other required steps before this will kick in:**
**Reference:** https://docs.renovatebot.com/automerge-configuration/

🏗 Enable `automerge` for renovate updates to `devDependencies`

---

.renovaterc.json

This will serve two purposes:
- Enable `esbuild` (and `karma-esbuild`) upgrades to be tested in isolation
- Prevent other upgrades from being held back because of a breaking change in `esbuild` (e.g. #33443)

 🏗 Perform `esbuild` package upgrades via a separate PR

---

build-system/global-configs/prod-config.json
extensions/amp-auto-ads/0.1/placement.js

In order to see the revenue impact of doing so.
The change is necessary to prevent CLS on pages using amp-auto-ads. This experiment will only emit eid if the ad is created using amp-auto-ads, not through any other means.

✨ Holdback experiment for disallowing amp-auto-ad from inserting ads above the viewport

---

extensions/amp-story/1.0/amp-story-open-page-attachment.js
extensions/amp-story/1.0/test/test-amp-story-page.js

Closes #34024
#33656 introduced a change in outlink navigation for swipe up. By not using the `navigator` anymore, we essentially changed from `target="_top"` to  `target="self"`. This PR adds `target="_top"` to the `<a>` of the `page-attachment`.
Tested on iOS Safari (test navigating, hitting back, navigating again). iOS 14.4.2

[amp-story] 🐛 Add target="_top" to page attachment

---

src/validator-integration.js
test/unit/test-validator-integration.js

After merging #33941, the integration of `validator_wasm.js` has been tested.
This PR (#33980) puts all validator traffic to `validator_wasm.js`.

✨Use WASM Validator for browser integration

---

build-system/tasks/runtime-test/helpers.js
build-system/test-configs/config.js

Back in the days of `karma-browserify`, a result with zero tests was an occasional transitional condition and wasn't flagged as a fatal error. See #16851 and #24957.
Now, with `karma-esbuild`, transformation errors can result in zero tests, and it must be flagged as a fatal error. This PR surfaces silent failures like the one in https://github.com/ampproject/amphtml/pull/33418#issuecomment-827846534.
A more correct fix would be to get `karma-esbuild` to throw an error when it encounters errors like the ones in https://github.com/ampproject/amphtml/pull/34020#issuecomment-827923414.

🏗 Flag an error and exit when Karma runs zero tests

---

build-system/tasks/helpers.js

This PR improves logging during `amp dist` and `amp build`.
**Before:**
**After:**

🏗 Log extension name while building npm binaries

---

build-system/tasks/make-extension/index.js
build-system/tasks/make-extension/template/shared/extensions/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.amp.js

Share the `storybook/Basic.amp.js` template so that Classic extensions generate one as well.

🏗 `make-extension` always creates Storybook file

---

build-system/common/utils.js

This PR adds a useful message if `amp [unit|integration|e2e] --files` is called with non-existent test files.
**Before:**
**After:**

🏗 Flag an error if `--files` matches zero test files

---

build-system/tasks/make-extension/index.js

**A few fixes:**
- Don't use `--report` (it's only meant to be used by flaky-test reporting during `main` branch CI runs)
- No longer read the report file to check if tests actually passed (#34060 makes this unnecessary)
- Don't use `--nohelp` (doesn't affect success / failure output, and simplifies the command used)
- Clean up JSDoc

🏗 Clean up extension generator tests

---

.renovaterc.json

- **[existing]** Test all `major` in isolation via independent PRs
- **[new]** Consolidate configuration for `major` updates in one place (simplifies currently separate config)
- **[new]** Group `minor`, `patch`, `pin`, and `digest` updates in the same category (separating them proved to be too noisy)
- **[existing]** Further group updates to `devDependencies` into `subpackage`, `build-system`, `validator`, `core`, `linting`, `babel`, `esbuild`, and `ampproject`
- **[existing]** Also group updates to `dependencies` into `ampproject` (published by `@ampproject`) and `core` (all others)
- **[new]** Enable renovate updates for `core` (not published by `@ampproject`) `dependencies` …

🏗 Refine renovate configuration

---

src/core/assert.js
src/error-reporting.js
src/log.js
test/unit/test-log.js

Moves detection of `error.associatedElement` from `log#prepareError_` to `error-reporting` where it is used. Simplifies `log#assert` method in preparation for adding type assertion helpres to core.

♻️ Simplify log/assert code and use core assert

---

.renovaterc.json
build-system/tasks/coverage-map/package-lock.json
build-system/tasks/coverage-map/package.json

This PR is a follow up to #34064, and addresses the two remaining issues mentioned in https://github.com/ampproject/amphtml/pull/34064#issuecomment-828879960. It also undoes the top-level grouping of `major` updates because that has the undesired side-effect of applying incorrect labels for `major` updates to subpackage dependencies (e.g. `validator/package.json`).
**Reference:** https://docs.renovatebot.com/configuration-options

🏗 Further refine renovate configuration

---

extensions/amp-story-panning-media/0.1/amp-story-panning-media.js
extensions/amp-story/1.0/amp-story-page.js
extensions/amp-story/1.0/animation.js
extensions/amp-story/1.0/test/test-amp-story-page.js
src/utils/media-query-props.js

Native animations will not run with `prefers-reduced-motion`. Disable the `AnimationManager` altogether so that pre-animation styling is not applied, and elements correctly remain in their end-state.
Fixes #34062

🐛 Stories: Disable animations when user `prefers-reduced-motion`

---

build-system/test-configs/dep-check-config.js
extensions/amp-video/1.0/storybook/VideoIframe.js
extensions/amp-video/1.0/test/test-video-iframe.js
extensions/amp-video/1.0/video-iframe.js
extensions/amp-vimeo/1.0/component.js
extensions/amp-youtube/1.0/component.js

Makes internal implementations simpler, while allowing `<amp-video-iframe>` to use a `VideoIframe` directly.
```diff
- <VideoWrapper
-   component={VideoIframe}
+ <VideoIframe
...
/>
```

♻️ Use Bento VideoIframe directly

---

build-system/common/logging.js

🏗 Use terminal width for test log wrapping if possible

---

.renovaterc.json

- In #34064, we enabled updates for `dependencies` (which had been ignored thus far and had bit-rotted)
- In #34082, we refined the grouping of `dependencies` to apply to just the sub-groups
These had a combined effect of unnecessarily splitting off subpackage-level `dependencies` (e.g. ones in `validator/`). The subgroups like `core`, `babel`, `linting`, `esbuild`, etc. should only apply to the root `package.json` file. This PR adds a `matchFiles` specification to the groups.
This should reduce the noise being seen by @ampproject/wg-caching while preventing their old `dependencies` from bit-rotting. (Sorry about that! I'll go in and make sure your existing set of many PRs is consolidated.) …

🏗 Restrict all root-level upgrade groups to the root `package.json`

---

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-progress-bar.css
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js

Stop the progress bar animation if the user pauses the video with a long press.
Partial #33969

🐛[story-ads] Pause the progress bar when paused.

---

.renovaterc.json

This PR tries a new approach to grouping package updates as far as possible, while not auto-merging `major` updates. The expectation is that this will further reduce PR noise over time (now that we're also updating our `dependencies`).
**Reference:** https://docs.renovatebot.com/configuration-options

🏗 Further group package updates to reduce noise

---

OWNERS
extensions/amp-access/0.1/iframe-api/OWNERS
third_party/amp-toolbox-cache-url/OWNERS
validator/OWNERS

We're in the process of automating most package updates using an auto-review and auto-merge workflow for low-risk non-dependency PRs that pass all CI checks.
This PR separates out package upgrades and prevents owners-bot from automatically adding reviewers. Shortly, we're going to add an auto-approval bot to do this work. Working groups will still remain owners, and can manually merge PRs if they'd like.
This should reduce the noise being seen by working groups while preventing their npm packages from bit-rotting.

🏗 Make package update review requests less noisy

---

extensions/amp-accordion/validator-amp-accordion.protoascii
extensions/amp-date-countdown/validator-amp-date-countdown.protoascii
extensions/amp-lightbox/validator-amp-lightbox.protoascii

Disable attributes in amp4email that are only used in `1.0` version of the component since amp4email does not currently use `1.0` and validator is unable to specify attributes specific to a version.
This impacts the following components:
- `amp-accordion`
- `amp-lightbox`

[bento] Disable 1.0 only attributes for amp4email

---

extensions/amp-story/amp-story-grid-layer.md

Added more documentation to explain how the grid-layer presets work.
There is some confusion on:
- What is being maximized
- What devices are fully covered by the preset background (mobile devices -> mobile phones)
- How the foreground layer works
Closes #34011

📖  Improved documentation on modern presets

---

build-system/tasks/make-extension/index.js
build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/base-element.js
contributing/building-a-bento-amp-extension.md

Since they require CSS on the AMP layer, but not JSS on the component, I'd like to specify on a guide that Bento video players can be started with:
```console
amp make-extension --bento --nojss
```

🏗 Optionally exclude JSS with `make-extension --nojss`

---

OWNERS

This PR is necessary due to the reasons outlined in https://github.com/ampproject/amphtml/pull/34148#issuecomment-831308299.
The supplementary fix to owners bot can be found in https://github.com/ampproject/amp-github-apps/pull/1284. This PR will need to merged in conjunction with the owners bot change.
Partial fix for https://github.com/ampproject/amp-github-apps/issues/1283

🏗 Switch top-level reviewer list from `reviewerTeam` to `reviewerPool`

---

extensions/amp-story/1.0/amp-story-open-page-attachment.css
extensions/amp-story/1.0/amp-story-page.js

Context / Fixes #33954
This follows the natural flow of page layout and allows the images to preload in the new attachment UI.
- Renders page attachments in `layoutCallback`.
- Always styles `amp-story-page-attachment-ui-v2` in natural position (`display: none` prevents images from loading).

✨ [Amp story] [Page attachments] Render page attachment in layoutCallback

---

OWNERS

This PR is a follow up to #34176 and #34148. Looks like Owners bot uses the name of the approving bot while running its check (and not the underlying github ID used by the bot).
This PR changes the owner to `renovate-approve` to see if owners checks like the one in https://github.com/ampproject/amphtml/pull/34180/checks?check_run_id=2495249187 will be satisfied.
**Screenshot for posterity:** (see #34180)

🏗 Use bot name of `renovate-approve` for owner approval of upgrade PRs

---

OWNERS

Reverts ampproject/amphtml#34182
Reason for revert: https://github.com/ampproject/amphtml/pull/34182#issuecomment-831545515
Related to #33959

Revert "🏗 Use bot name of `renovate-approve` for owner approval of upgrade PRs"

---

.renovaterc.json

The validator webui implementation uses an older version of Polymer that works just fine. Since there are no plans to upgrade to the latest version of Polymer, this PR disables package updates for `validator/js/webui/package.json`.
With this, PRs like #34157 and #34184 will no longer be auto-generated when there are pending upgrades.
Addresses https://github.com/ampproject/amphtml/pull/34157#issuecomment-831570050
Addresses https://github.com/ampproject/amphtml/pull/34186#discussion_r625412393
Closes #34186

🏗 Disable updates for validator webui

---

OWNERS

We use the `renovate-approve` app to auto-approve low-risk package upgrade PRs that have otherwise passed all other CI checks. In order to allow this, owners bot needs to be satisfied that the bot account is listed in `reviewerPool`.
From looking at the [review payload](https://api.github.com/repos/ampproject/amphtml/pulls/34180/reviews) on GitHub, the `renovate-approve` account shows up with a `[bot]` suffix. This PR adds that suffix to the entry in `reviewerPool` so owners bot recognizes it.

🏗 Use correct suffix for `renovate-approve` bot

---

validator/OWNERS

Right now, all validator package updates require a manual review from someone in @ampproject/wg-caching. With this PR, low-risk updates to validator `devDependecies` like the ones in #34205 will be auto-merged if / when all PR checks go green.

🏗 Allow auto-merge for low-risk validator upgrades

---

contributing/building-a-bento-amp-extension.md
contributing/building-a-bento-video-player.md

📖 Guide to Building a Bento Video Player

---

extensions/amp-video-iframe/1.0/amp-video-iframe.js
extensions/amp-video-iframe/1.0/base-element.js
extensions/amp-video-iframe/1.0/storybook/Basic.amp.js

- `canplay` is not part of `BUBBLE_EVENTS` since `0.1` dispatches `load` instead. Dispatch from Bento as it's required.
- `controls` has to be passed from AMP layer.
- remove `withA11y` from Storybook

🐛 Bento <amp-video-iframe>: assorted fixes

---

ads/vendors/feedad.js
build-system/compile/closure-compile.js
build-system/tasks/check-types.js
extensions/amp-a4a/0.1/amp-ad-utils.js
extensions/amp-accordion/1.0/component.type.js
extensions/amp-addthis/0.1/amp-addthis.js
extensions/amp-addthis/0.1/config-manager.js
extensions/amp-bind/0.1/bind-impl.js
extensions/amp-brightcove/0.1/amp-brightcove.js
extensions/amp-lightbox-gallery/1.0/component.type.js
extensions/amp-lightbox/1.0/component.type.js
extensions/amp-render/1.0/component.type.js
extensions/amp-selector/1.0/component.type.js
extensions/amp-sidebar/1.0/component.type.js
extensions/amp-sidebar/1.0/sidebar-animations-hook.js
extensions/amp-story-auto-ads/0.1/story-ad-page-manager.js
extensions/amp-story-auto-ads/0.1/story-ad-ui.js
extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.js
extensions/amp-subscriptions/0.1/entitlement.js
extensions/amp-video/1.0/video-iframe.js
src/amp-story-player/amp-story-player-viewport-observer.js
src/context/node.js
src/custom-element.js
src/preact/component/3p-frame.js
src/preact/component/component.type.js
src/preact/slot.js

**summary**
- Fixes all `JSC_BAD_JSDOC_ANNOTATION`, `JSC_INVALID_PARAM`, and `JSC_TYPE_PARSE_ERROR` errors within `src` and `extensions` directories.
- Creates a new function that is run on each `amp check-types` that ensures these errors don't occur again in new code.
**sample failure when introducing a new malformed type**

Types: fix all type parse errors and ensure no new ones crop up

---

build-system/externs/amp.extern.js
build-system/global-configs/experiments-config.json
build-system/global-configs/experiments-const.json
builtins/amp-img.js
src/base-element.js
src/custom-element.js
src/inabox/inabox-resources.js
src/preact/base-element.js
src/service/resource.js
src/service/resources-impl.js
test/integration/test-visibility-states.js
test/unit/inabox/test-inabox-resources.js
test/unit/preact/test-base-element-mapping.js
test/unit/test-amp-img-v1.js
test/unit/test-custom-element-v1.js
test/unit/test-resources.js
testing/element-v1.js

**summary**
See go/what-amp.
In order to clear up ambiguity around all the different things being called "V1" these days (bento components, bento runtime, etc.), we've decided to rename the new resources system from "V1" to "R1".
- Classic Resources --> R0
- New Resources --> R1

resources: rename V1 to R1, to clear up ambiguity

---

extensions/amp-story/validator-amp-story.protoascii

This is a follow up to #33142, allowing for the http protocol and relative urls. This is a result of cl/362183596 being in prod now.

allow http and relative for amp-story-page-attachment

---

build-system/tasks/check-types.js
src/.eslintrc.js
src/polyfills/abort-controller.js
src/polyfills/custom-elements.extern.js
src/polyfills/custom-elements.js
src/polyfills/document-contains.js
src/polyfills/get-bounding-client-rect.js
src/polyfills/promise.extern.js
src/polyfills/promise.js
src/polyfills/shame.extern.js
src/polyfills/stubs/intersection-observer-stub.js
src/polyfills/stubs/resize-observer-stub.js

It passes now. Part of https://github.com/ampproject/amphtml/issues/34096

♻️ Enable type-checking src/polyfills in CI

---

extensions/amp-brightcove/0.1/amp-brightcove.js
extensions/amp-brightcove/0.1/test/test-amp-brightcove.js

Following an update to the Brightcove Player's AMP support plugin, this update makes sure autoplay is handled correctly in all cases.
- Removes any autoplay query param, including the interim autoplay=false
- Distinguishes play messages sent through postmessage which are autoplay requests
cc @alanorozco

🐛 amp-brightcove: improve autoplay handling

---

ads/google/imaVideo.js
extensions/amp-ima-video/0.1/amp-ima-video.js

Rename `postMessage` method names so that they're uniform with `VideoIframe`'s. This simplifies the upcoming Bento implementation.

♻️ Name amp-ima-video methods uniformly for Bento

---

extensions/amp-script/0.1/amp-script.js

`amp-script` development can be frustrating, as every change triggers the invalid hash error. Wanted to highlight the `data-ampdevmode` [we mention in the documentation](https://amp.dev/documentation/components/amp-script/#script-hash) to improve DX

update amp-script console error to mention data-ampdevmode

---

build-system/tasks/check-types.js

A change in https://github.com/ampproject/amphtml/pull/34105 accidentally made all type-checks use a custom logger that swallowed output, when we only needed to take a copy of the log output. This patches that issue, unmasking typecheck errors.

🐛 Log output when onError set

---

.eslintrc.js
extensions/amp-video/1.0/storybook/_helpers.js

Disable `require-jsdoc` since it auto-fixes, and we don't need JSDoc in these locations.
We preserve the following rules since they ensure correctness, like type-check already does.
```
jsdoc/check-param-names
jsdoc/check-tag-names
jsdoc/check-types
jsdoc/require-param
jsdoc/require-param-name
jsdoc/require-param-type
jsdoc/require-returns
jsdoc/require-returns-type
```

🏗 Disable JSDoc requirement on Storybook files

---

extensions/amp-sidebar/1.0/component.js
extensions/amp-sidebar/1.0/test/test-component.js

Updating the Preact component to an SSR compatible design.  See `Design Proposal: Media Query Based Approach` on page 3 of [AMP Sidebar Design Doc](https://docs.google.com/document/d/1YPQ1ObQc0qpLm01TgsXACnwVwYppwZI_8ETBfK0wyOA/edit#heading=h.4zli8r3l75p6)
This PR updates the Preact side only.  Design works by duplicating `Toolbar` into the `Toolbar Target Element` and appending a style element that controls visibility of the duplicated `Toolbar` using a media query in CSS.
One optimization over the previous iteration is that duplicating of nodes is done with `Node.cloneNode()` instead of relying on portals.  This matches the 0.1 design AND solves the `ref` issue encountered in the previous design.  (The issue was inconsistent ref behavior between Preact vs React).  Now a `ref` to the …

[bento][amp-sidebar] SSR compatible design for Sidebar Toolbar

---

extensions/amp-story/1.0/test/test-page-advancement.js

These tests compare millisecond values when the test is running, and there's no guarantee that there's an exact match. See https://github.com/ampproject/amphtml/pull/34153#pullrequestreview-656192589.
**Links:**
- https://app.circleci.com/pipelines/github/ampproject/amphtml/8866/workflows/2ea8df92-b56c-434a-98e3-f03f5b8d556f/jobs/134483/parallel-runs/0/steps/0-112
- https://app.circleci.com/pipelines/github/ampproject/amphtml/8873/workflows/8940beff-c45a-4835-9188-5997da23b5da/jobs/134598/parallel-runs/0/steps/0-112
**Logs:**
```
AssertionError: expected 1999 to equal 2000
at Context.<anonymous> (home/circleci/project/extensions/amp-story/1.0/test/test-page-advancement.js:155:53)
```
```
AssertionError: expected 1998 to equal 2000
at Context.<anonymous> …
```

❄️ Skip flaky stories tests

---

css/amp-story-player-iframe.css
examples/amp-story/player.html
spec/amp-story-player.md
src/amp-story-player/amp-story-player-impl.js
test/unit/test-amp-story-player.js

Closes #30889
Allows scripts to specify options on `go` and `show` like so: `go(..., {animate: false});` to disable the animations when navigating to another story.

✨ Add parameter to configure amp-story-player animation

---

extensions/amp-facebook-comments/1.0/storybook/Basic.amp.js
src/preact/base-element.js
test/unit/preact/test-base-element-mapping.js

This PR will allow components which are built using Shadow DOM to display their placeholder and fallback elements, which otherwise are hidden once the shadow root gets attached. cc @dmanek

Bento: Assign placeholder and fallback elements to service slot

---

extensions/amp-story/1.0/amp-story-page-attachment.js
extensions/amp-story/1.0/amp-story-page.js

Adds codepath for `openRemoteV2_`.
Add selector for `amp-story-page-outlink` in `attachmentEl`.
Context / Fixes #34323

🐛 [Amp story] [Page attachments] [Outlink] Split outlink codepaths for open attachment

---

build-system/test-configs/forbidden-terms.js
extensions/amp-web-push/0.1/amp-web-push-helper-frame.js

It seems we forgot that web-push has a helper iframe, which acts as an entry point into our JS. It doesn't include `v0.js`, so it needs to initialize the log constructor for logging to work.
Fixes https://github.com/ampproject/amphtml/issues/34318.

🐛 Initialize Logs in web-push's helper frame endpoint

---

src/preact/base-element.js
test/unit/preact/test-base-element-mapping.js

Identifying existing element by `tagName` alone can cause collisions with other elements i.e. placeholder, fallback, overflow. cc @dmanek

Bento: Find rendered `lightDomTag` elements by attribute instead of `tagName`

---

extensions/amp-facebook-comments/0.1/test/test-amp-facebook-comments.js
extensions/amp-facebook-comments/1.0/test/test-amp-facebook-comments.js

Add unit tests for amp-facebook-comments:0.1

---

build-system/compile/bundles.config.extensions.json
extensions/amp-twitter/1.0/package.json

NPM Publishing Tracker Issue https://github.com/ampproject/amphtml/issues/34137
NPM Publishing Status: [Doc](https://docs.google.com/spreadsheets/d/1JnCfYzgEojX_vPVy6h0fOnOLIHOcfPl4FCOZUDpclfE/edit#gid=0)
Get `amp-twitter` ready for NPM publishing.
1. Add `npm` definition.
2. Add `package.json` file.

🏗 [bento][npm][amp-twitter] Update npm definition and package file for publishing

---

css/ampdoc.css
examples/amp-script/example.sandboxed.amp.html
examples/amp-script/export-functions.js
extensions/amp-ima-video/0.1/test/test-ima-video-internal.js
extensions/amp-script/0.1/amp-script.js
extensions/amp-script/0.1/test/integration/test-amp-script.js

**summary**
There are complications that could arise when trying to use `sandboxed` amp-script without nodom.
- Any exported functions used would hang until the amp-script was close enough to viewport to be laid out.
- Potential unpleasant ramifications for allowing 3p scripts to have control over part of the DOM.
This PR skirts the whole issue for now by forcing `nodom` for any amp-script using sandboxed mode, and we can revisit this later. It is easier to loosen restrictions than to lock them down.

amp-script: sandboxed implies nodom

---

.eslintrc.js
build-system/eslint-rules/no-private-props.js
build-system/eslint-rules/private-prop-names.js
src/base-element.js

This fixes a cross binary issue with private properties being mangled to, ie., `lc` inside `BaseElement` base class. The issue is that a subclass extending it in another binary (eg, `amp-a4a`) can reuse that mangled name for something entirely different, because Closure isn't aware of what the base class is at that point.
Why not just revert https://github.com/ampproject/amphtml/pull/33963 to fix the issue? Because that requires keeping two files in sync, and we'd still need an ESLint rule to ensure they were. It's easier to just forbid the privates entirely. Doing it this way also fixes helps Terser, whenever we can finally enable property mangling there.
Fixes https://github.com/ampproject/error-reporting/issues/83

🐛 Forbid private properties inside BaseElement

---

extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-button.css
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

- Update babel monorepo to v7.14.2 (#1686)
- Dark button interactive states (#1685)
- Showcase: Warn about invalid metering state IDs (#1684)
- Add call to getSubscriptionFlow in GA event listener (#1683)
- Showcase: Bail if `gaa_at` = 'na' (#1677)
- Add 'supportsEventManager' to contributions flow iframe (#1682)
- Update prettier and lint fix (#1681)
- Update dependency postcss to v8.2.15 (#1680)
- Update dependency postcss-import to v14.0.2 (#1678)
- Open a toast "signed in as abc@gmail.com" after verifying entitlement… (#1679)
- Bump hosted-git-info from 2.8.8 to 2.8.9 (#1675)
- Update dependency eslint to v7.26.0 (#1674)
- Showcase: Add additional languages (#1672)
- Showcase: Styles reset metering demo button. (#1673)
- Dismiss SwG UI (#1671)
- Send an empty EntitlementsResponse …

SwG release 0.1.22.165

---

extensions/amp-analytics/analytics-vendors-list.md

📖 Disable deadlink checking for Infoline

---

build-system/tasks/e2e/package-lock.json
build-system/tasks/e2e/package.json
validator/package-lock.json
validator/package.json

These resolutions were added a long time ago to address security vulnerabilities. They are now obsolete and can be deleted.

🚮 Clean up obsolete npm resolutions

---

build-system/tasks/OWNERS

We're frequently adding/tweaking the lists of files that are passing type-checking. This adds wg-performance to the OWNERS for the `check-types` task. Will still request review from infra on any substantive changes to the task.

🏗 Allow Performance WG to manage check-types

---

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js

If the viewer is auto advancing the story ad page, we need the visual treatment. This is likely temporary until we have proper experiment sharing.
Partial #33969
cc/ @zaparent

🐛 [story-ads] Show progress bar when viewer auto-advance enabled

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

This is a follow up to #34398, improving the bug report template in three ways:
* `s/Wordpress/WordPress/` per [`capital_P_dangit()`](https://developer.wordpress.org/reference/functions/capital_p_dangit/)
* Fixes WordPress AMP plugin link to point to the correct plugin.
* Adds a link to the support forum to encourage checking there before opening an issue on GitHub.

📖 Improve references to the AMP plugin for WordPress in bug report template

---

build-system/tasks/check-types.js
src/context/contextprops.js
src/context/index.js
src/context/node.js
src/context/prop.js
src/context/prop.type.js
src/context/scan.js
src/context/scheduler.js
src/context/shame.extern.js
src/context/subscriber.js
src/context/values.js

♻️ Enable passing type-checking on src/context

---

extensions/amp-story/1.0/amp-story.js
src/mode.js

On the minified JS build, `getMode().development` gets replaced with `false` so the Web Story DevTools don't get triggered.
Exposing a function `isModeDevelopment` can be used by `amp-story.js` to check whether to trigger the tools without relying on `getMode()`
Closes #34364

🐛  [Story devtools] Toggle devtools on mjs build

---

src/custom-element.js

See https://output.jsbin.com/yuwojok/29/quiet for a working demo of the bug. When we construct a CustomElement in one document, then insert it into another document (as we do with A4A ads), Firefox incorrectly resets the prototype of our CE instance to `HTMLElement.prototype`.
Luckily, we can fix this by listening for the `adoptedCallback`, which fires just after Firefox resets the prototype. If we detect a broken prototype chain, we can correct it before any other code can notice. See https://output.jsbin.com/datajos/5/quiet for a demo of the fix.

🐛  Add adoptedCallback to work around Firefox Native CE bug

---

extensions/amp-apester-media/0.1/amp-apester-media.js
extensions/amp-brid-player/0.1/amp-brid-player.js
extensions/amp-brid-player/0.1/test/test-amp-brid-player.js
extensions/amp-delight-player/0.1/amp-delight-player.css
extensions/amp-delight-player/0.1/amp-delight-player.js
extensions/amp-gfycat/0.1/amp-gfycat.js
extensions/amp-gfycat/0.1/test/test-amp-gfycat.js
extensions/amp-iframely/0.1/amp-iframely.js
extensions/amp-iframely/0.1/test/test-amp-iframely.js
extensions/amp-jwplayer/0.1/amp-jwplayer.js
extensions/amp-jwplayer/0.1/test/test-amp-jwplayer.js
extensions/amp-kaltura-player/0.1/amp-kaltura-player.js
extensions/amp-kaltura-player/0.1/test/test-amp-kaltura-player.js
extensions/amp-springboard-player/0.1/amp-springboard-player.js
extensions/amp-springboard-player/0.1/test/test-amp-springboard-player.js
extensions/amp-video-iframe/0.1/amp-video-iframe.js
extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
extensions/amp-viqeo-player/0.1/amp-viqeo-player.js
extensions/amp-viqeo-player/0.1/test/test-amp-viqeo-player.js

Where extensions would previously create `<amp-img>` placeholders, now create a plain `<img>` element with `loading="lazy"`

♻️ Create plain `<img>` placeholders

---

extensions/amp-list/0.1/amp-list.js
extensions/amp-list/0.1/test/test-amp-list.js

Two fixes for `diffable`:
1. In #32650, we defer binding scan until render. But [this conditional](https://github.com/ampproject/amphtml/blob/master/extensions/amp-list/0.1/amp-list.js#L1106) is not the same as [this one](https://github.com/ampproject/amphtml/blob/df83808bc81014fc23fe9efb58f04bc91e1ff702/extensions/amp-list/0.1/amp-list.js#L1163). Make them the same.
2. With `single-item`, we shouldn't expect the diffable placeholder to have `[role=list]`.
`b/182456351`

amp-list: Support diffable with single-item

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/cherry-pick-request.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/intent-to-deprecate.yml
.github/ISSUE_TEMPLATE/intent-to-implement.yml
.github/ISSUE_TEMPLATE/intent-to-remove.yml
.github/ISSUE_TEMPLATE/intent-to-ship.yml
.github/ISSUE_TEMPLATE/release-tracker.yml
.prettierignore
.prettierrc
.vscode/settings.json
build-system/test-configs/config.js

This is a follow up to #34400, which migrated all issue templates to yaml forms.
- Enable prettier-auto formatting for all `.yml` files (`.gitignore` contents are still ignored)
- Enable VSCode auto-formatting for `.yml` files
- Remove superfluous per-file associations in `.prettierrc` and `.vscode/settings.json`
- Include `.yml` files in the `amp prettify` CI check (`--fix` will work during local dev)
- Apply auto-fixes to all files in `.github/ISSUE_TEMPLATE/` (separate commit)

🏗 Enable VSCode auto-formatting and prettier checks for `.yml` files

---

extensions/amp-story/1.0/amp-story-open-page-attachment.css
extensions/amp-story/1.0/amp-story-page-attachment.css
extensions/amp-story/1.0/amp-story-page-attachment.js

Reduces post-tap progress bar animation time.
Edits motion curve of progress bar to lead into the opening attachment experience.
Removes the open attachment page overlay.
All edits are hidden behind the `amp-story-page-attachment-ui-v2` experiment.
The experiment is forced on in the [demo](https://philipbell-stamp-ui.web.app/examples/amp-story/attachment.html#page=outlink-dark-theme)
Fixes #34470
Edits discussed with and approved by @hongcatlover

[Amp story] [Page attachments] [Outlink] Remove open attachment delay and animation

---

extensions/amp-animation/amp-animation.md

📖 amp-animation: Clarify prefers-reduced-motion

---

css/ampshared.css
validator/validator-main.protoascii

Fixes #34402. As suggested by @jridgewell in https://github.com/ampproject/amphtml/issues/34402#issuecomment-843521657.
This will facilitate incorporating native `img` elements onto AMP pages (#30442).
This also allows `width` and `height` attributes on SSR'ed `amp-img > img` elements which can be supplied by an optimization layer, like Mod_Pagespeed (https://github.com/apache/incubator-pagespeed-mod/issues/2067).
Using test case: https://ampshared-img-styling-issues.glitch.me/
Before | After
-------|------

🖍 Prevent native `img` elements from being styled by `ampshared.css`

---

build-system/global-configs/prod-config.json
extensions/amp-auto-ads/0.1/placement.js

It is showing that the ads inserted above the viewport are rarely viewed. Therefore it makes sense to keep preventing ads from being inserted above to avoid the unnecessary CLS.

Unlaunch auto-ads-no-insertion-above holdback experiment

---

build-system/pr-check/build-targets.js

- Consolidates all glob expansion in `build-targets.js` into one helper function
- Uses the `{dot: true}` option so that dotfiles are matched if necessary (e.g. PR template changes will match `DOCS`)

🏗 Consolidate glob expansion while determining build targets

---

src/validator-integration.js
test/unit/test-validator-integration.js

Fixes #34501
#34372 introduce `isModeDevelopment` so that development can be determined in module runtime (v0.mjs). Use this for validator integration instead of `getMode().development`.

Use isModeDevelopment for validator integration

---

.github/ISSUE_TEMPLATE/bug-report.yml

This PR adds two new fields to the bug report template.

📖 Add bug report fields for OSs and Devices

---

.github/ISSUE_TEMPLATE/bug-report.yml

This addresses the good point raised by @honeybadgerdontcare in https://github.com/ampproject/amphtml/pull/34522#issuecomment-848003059

📖 Use `n/a` instead of `/all` in the OS and device fields

---

build-system/tasks/check-links.js

We've already configured the link checker `amp check-links` to make sure the following files don't contain broken URLs:
https://github.com/ampproject/amphtml/blob/53ec150159954af9290d9af12d8ec2d547e34a97/build-system/test-configs/config.js#L171-L179
Now that some of the files we want to check live in `.github/`, we need to set `dotfile: true` while expanding globs in the link checker task.

🏗 Include dotfiles while expanding globs during the CI check for valid URLs

---

extensions/amp-accordion/1.0/package.json
extensions/amp-accordion/1.0/react.js
extensions/amp-base-carousel/1.0/package.json
extensions/amp-base-carousel/1.0/react.js
extensions/amp-date-countdown/1.0/package.json
extensions/amp-date-countdown/1.0/react.js
extensions/amp-date-display/1.0/package.json
extensions/amp-date-display/1.0/react.js
extensions/amp-fit-text/1.0/package.json
extensions/amp-fit-text/1.0/react.js
extensions/amp-inline-gallery/1.0/package.json
extensions/amp-inline-gallery/1.0/react.js
extensions/amp-instagram/1.0/package.json
extensions/amp-instagram/1.0/react.js
extensions/amp-lightbox/1.0/package.json
extensions/amp-lightbox/1.0/react.js
extensions/amp-selector/1.0/package.json
extensions/amp-selector/1.0/react.js
extensions/amp-stream-gallery/1.0/package.json
extensions/amp-stream-gallery/1.0/react.js
extensions/amp-timeago/1.0/package.json
extensions/amp-timeago/1.0/react.js
extensions/amp-twitter/1.0/package.json
extensions/amp-twitter/1.0/react.js
extensions/amp-youtube/1.0/package.json
extensions/amp-youtube/1.0/react.js

Partial for: https://github.com/ampproject/amphtml/issues/34137
Update package.json files for existing bento components ready for NPM publishing.
Includes additional `react.js` file which is needed for react apps.

✨ [bento][npm] Support react modules in NPM Bento components

---

.github/workflows/publish-npm-packages.yml
build-system/npm-publish/build-npm-binaries.js
build-system/npm-publish/get-extensions.js
build-system/npm-publish/write-package-jsons.js

Creates a GH Action to publish bento packages on npm under ampprojectbot https://www.npmjs.com/~ampprojectbot
`NPM_TOKEN` was added to the repo last week, but won't be usable until merged into main for security reasons
I also moved node scripts from `.github/workflows/publish` to `build-system/npm-publish` because GitHub doesn't pick up workflow files from a subdir in `.github/workflows/`

🏗  Automate bento publishing with a GitHub Action

---

extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js

Related to #24195
Note: [This test appears to be failing consistently on Circle CI ](https://app.circleci.com/pipelines/github/ampproject/amphtml/9854/workflows/e0bd0a95-2391-49cf-b7ce-2ad4e236b4af/jobs/152844)but I could not get it to fail on local runs.

Skip failing amp-base-carousel:0.1 e2e test

---

build-system/server/typescript-compile.js
build-system/tasks/coverage-map/index.js

With this, `amp check-build-system` will return zero type errors even when the server transforms have been built locally.

🏗 Don't type-check server transform output

---

.github/ISSUE_TEMPLATE/bug-report.yml

We use AMP's default [bug report template](https://github.com/ampproject/amphtml/issues/new?assignees=&labels=Type%3A+Bug&template=bug-report.yml) for two broad purposes:
1. To receive bug reports about the AMP runtime + components from internal and external contributors
2. To receive bug reports / track tasks related to the non-runtime internals of AMP (e.g. infrastructure)
- For case 1, it's valuable to have info like browser, OS, device, and AMP version.
- For case 2, this info is mostly irrelevant.
**Options to address this:**
- Make the fields optional, with the expectation that they will still be filled out for case 1.
- Let the fields remain mandatory, and add a different "infrastructure bug report" template for case 2.
This PR implements the first option. …

📖 Make a few bug report fields optional

---

.eslintignore
build-system/server/app-index/test/helpers.js
build-system/server/app-index/test/test-amphtml-helpers.js
build-system/server/app-index/test/test-file-list.js
build-system/server/app-index/test/test-html.js
build-system/server/app-index/test/test-self.js
build-system/server/app-index/test/test-template.js
build-system/server/app-index/test/test.js

These tests were added in #18796, but weren't auto-formatted or linted at the time. While investigating https://github.com/ampproject/amphtml/pull/34451#issuecomment-848221679, I found it useful to have auto-formatting and inline lint checks.

🏗 Auto-format dev dashboard tests

---

build-system/common/update-packages.js
build-system/tasks/check-build-system.js

#34525 made it so that all build-system subpackages are installed before type-checking the directory. 
This PR skips running NPM checks for those subpackages during type-checking because this is already done while running the individual tasks. Doing so should shave off several seconds of running time.

🏗 Skip NPM checks while type-checking build-system

---

extensions/amp-story/1.0/amp-story.js
extensions/amp-video/0.1/flexible-bitrate.js
extensions/amp-video/0.1/test/test-amp-video.js

Send the `flexible-bitrate` with the enabled experiments so it can be used to filter the CSI dashboards.

Track flexible-bitrate experiment through CSI pipeline.

---

build-system/tasks/extension-helpers.js
build-system/tasks/helpers.js

Update naming of generated files for NPM publishing.
Instead of using `.mjs`, we will go with `.module.js` since `create-react-app` does not support `.mjs` format.

✨ [bento][npm] Update file naming from mjs to module

---

.eslintignore
build-system/pr-check/build-targets.js
build-system/pr-check/checks.js
build-system/tasks/lint.js
build-system/tasks/pr-check.js

During PR checks, we run `amp lint` against the entire repo. This is a long and time-consuming process primarily due to `prettier`, as can be seen by running `TIMING=1 amp lint`.
```
Rule                              |  Time (ms) | Relative
:---------------------------------|-----------:|--------:
prettier/prettier                 | 105048.078 |    78.9%
jsdoc/check-types                 |   7343.111 |     5.5%
jsdoc/check-tag-names             |   6639.867 |     5.0%
local/no-forbidden-terms          |   1453.448 |     1.1%
jsdoc/require-param               |    953.783 |     0.7%
local/closure-type-primitives     |    903.859 |     0.7%
google-camelcase/google-camelcase |    780.167 |     0.6%
jsdoc/check-param-names           |    767.958 |     0.6% …
```

🏗 Optimize linting during PR builds

---

extensions/amp-story/1.0/amp-story-page.js

Do not wait for a fallback media to load before sending the load events.
Fixes https://github.com/ampproject/amphtml/issues/34581

Don't block Story render on a fallback media load.

---

.github/ISSUE_TEMPLATE/release-tracker.yml

This PR adds explanatory text to the LTS and cherry-pick sections of the release tracker so that their purpose is clear.
Addresses https://github.com/ampproject/amphtml/pull/34440#issuecomment-849035772.

📖 Add explanatory text to the LTS and cherry-pick sections of the release tracker

---

.eslintignore
.gitignore
.prettierignore
build-system/tasks/clean.js
build-system/tasks/release/index.js

Fixes #34542
Root cause of the issue is that the `compileDistFlavors_` function called `amp clean` between different flavors (base, experimentA, ...) which caused a followup function in the process (`populateOrgCdn_`) to fail, as it was expecting files that were cleaner by `amp clean`
The PR fixes this by looping through all the `distFlavors` and calling all the functions use each individual `distFlavor`, instead of calling those functions with `distFlavors` (plural) and looping through it inside those functions.
This PR also makes the typedefs more explicit and fixes some weird Promise-related type issues.

Run through all actions for each distFlavor in `amp release` before the next

---

build-system/tasks/check-types.js

Currently, type-check targets added as part of #34096 require providing an object with `srcGlobs` and `externGlobs`. Since `externGlobs` almost always follows directly from `srcGlobs`, this PR makes it easier to add/enable typecheck targets by specifying just the source globs.

🏗 Make new typecheck targets simpler

---

extensions/amp-video/0.1/test/test-video-cache.js
extensions/amp-video/0.1/video-cache.js

Enable the video cache for `amp-video[src]` configurations.

Video cache for amp-video[src].

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-button.css
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.167

SwG Release 0.1.22.167

---

.github/workflows/publish-npm-packages.yml
build-system/npm-publish/write-package-files.js

Get remaining changes from #34528 that added `react.js` to each dir
cc/ @caroqliu @jridgewell

🏗  Automatically write react.js files for bento components when publishing

---

build-system/test-configs/dep-check-config.js
extensions/amp-video/0.1/amp-video.js
extensions/amp-video/0.1/test/test-video-cache.js
extensions/amp-video/0.1/test/validator-amp-video-cache.html
extensions/amp-video/0.1/test/validator-amp-video-cache.out
extensions/amp-video/0.1/video-cache.js
extensions/amp-video/validator-amp-video.protoascii

`amp-cache-url` will eventually become unnecessary. We will stop asking publishers to provide it, and will lazy load it until it's no longer required sometimes in Q3.
cc @ampproject/wg-stories FYI

[Video cache] Lazy load amp-cache-url and make it optional.

---

extensions/amp-story/1.0/page-advancement.js

Stories with a very short `auto-advance-after` break Story navigation, as they instantly advance to the next/prev page. In the case of a back navigation you're stuck on the current page.

Minimum duration for auto-advance-after.

---

extensions/amp-accordion/OWNERS
extensions/amp-anim/OWNERS
extensions/amp-autocomplete/OWNERS
extensions/amp-bind/OWNERS
extensions/amp-carousel/OWNERS
extensions/amp-fit-text/OWNERS
extensions/amp-form/OWNERS
extensions/amp-image-lightbox/OWNERS
extensions/amp-lightbox/OWNERS
extensions/amp-list/OWNERS
extensions/amp-mustache/OWNERS
extensions/amp-selector/OWNERS
extensions/amp-sidebar/OWNERS
extensions/amp-timeago/OWNERS

This change applies to all components that are valid in the email format which live in `extensions/`. Note: `amp-img` and `amp-layout` are maintained in the general spec. cc/ @ampproject/wg-amp4email

Notify wg-amp4email as OWNERS for extension spec changes

---

build-system/babel-config/post-closure-config.js

For ESM builds, the `transform-minified-comments` is run during the pre- and post- closure compilation passes, resulting in duplicate copyright comments in all binaries.
**For example:**
This PR removes the plugin from the post-closure pass. With this, there's only one copy of the copyright comments.
**Question:** Is there any valid reason to run this plugin twice? If so, is there merit in the suggestion in https://github.com/ampproject/amphtml/pull/26779#discussion_r398302869?

🏗 Don't duplicate copyright comments in ESM output

---

build-system/babel-config/eslint-config.js
build-system/common/check-package-manager.js
build-system/common/exec.js
build-system/global.d.ts
build-system/task-runner/amp-cli-runner.js
build-system/task-runner/amp-task-runner.js
build-system/tasks/dep-check.js
build-system/tasks/e2e/driver/query-xpath.js
build-system/tasks/make-extension/index.js
build-system/tasks/storybook/amp-env/register.js
build-system/tsconfig.json

- Add a `files` section to `tsconfig.json` and reference `global.d.ts` (it wasn't being consumed earlier)
- Replace the `include` section of `tsconfig.json` with `./**/*.js` (so all JS files are checked by default)
- Trim the `exclude` section of `tsconfig.json` to only those directories that still need work
- Fix several type-check errors

🏗 Fix several suppressed type-check errors in `build-system`

---

validator/validator-css.protoascii

In the past few days the WordPress AMP plugin has been getting topics about Search Console reporting a warning for a CSS syntax error:
https://wordpress.org/support/topic/amp-css-syntax-error-in-tag-style-amp-custom-2/
https://wordpress.org/support/topic/css-syntax-error-in-tag-style-amp-custom-11/
https://wordpress.org/support/topic/css-syntax-error-in-tag-style-amp-custom-12/
For example:
The offending CSS code looks like this:
```css
@media only screen and (-webkit-min-device-pixel-ratio: 1.5),
only screen and (min--moz-device-pixel-ratio: 1.5), 
only screen and (min-resolution: 240dpi) 
{
div.googleplay a.apptitle {
background: url(../img/googleplay-small.png);
}
}
```
Both the JS and C++ validators are reporting:
> CSS syntax error in tag 'style amp-custom' - disallowed media feature …

🖍 Add `min--moz-device-pixel-ratio` and `max--moz-device-pixel-ratio` media features to CSS validator spec

---

build-system/babel-config/post-closure-config.js
build-system/babel-plugins/babel-plugin-transform-minified-comments/index.js
build-system/babel-plugins/babel-plugin-transform-minified-comments/test/fixtures/transform/licenses-tabs/input.js
build-system/babel-plugins/babel-plugin-transform-minified-comments/test/fixtures/transform/licenses-tabs/output.js
build-system/babel-plugins/babel-plugin-transform-minified-comments/test/fixtures/transform/licenses/input.js
build-system/babel-plugins/babel-plugin-transform-minified-comments/test/fixtures/transform/licenses/output.js
build-system/compile/post-closure-babel.js
third_party/webcomponentsjs/ShadowCSS.js

- Updates `transform-minified-comments` to remove newline characters and multi-whitespaces from comments
- Fixes bug that was resulting in duplicate comments
- Runs the plugin after closure compilation in esm and non-esm modes (running it before closure has no effect)
- Updates logic used to trigger `post-closure` transforms
- Updates expected output in `amp babel-plugin-tests`
**Before:**
**After:**
Addresses https://github.com/ampproject/amphtml/pull/34628#issuecomment-852158829

🏗 Shorten copyright comments in esm and non-esm minified output

---

test/unit/core/math/test-layout-rect.js

At one point, each `describe` block was its own `describes.sandboxed`. They were converted to `describe` under a single root `describes.sandboxed`, but the extra `{}` was never removed.
Fixes https://github.com/ampproject/amphtml/issues/34580
Fixes https://github.com/ampproject/amphtml/issues/34642

🐛 Fix namespace bug in tests

---

ads/_config.js
ads/vendors/opinary.md
examples/amp-ad/ads.amp.html

Opinary AMP integration only supported the "automatic matching", where the Opinary algorithm decided what polls to show - sometimes it decided to do not to show any poll 
Regarding information in the documentation:
_If no ad is available for the slot, AMP attempts to collapse the amp-ad element (that is, set to display: none). AMP determines that this operation can be performed without affecting the user's scroll position. If the ad is in the current viewport, the ad will not be collapsed because it affects the user's scroll position; however, if the ad is outside of the current viewport, it will be collapsed._
Sometimes it keeps reserved space even any poll is displayed and is it problematic for publishers, in that case, we decided to reverse logic and we could reserve 1px height and in …

♻️ Opinary Ads: fix whitespace issue for AMS integration

---

build-system/common/update-packages.js
build-system/task-runner/amp-task-runner.js
build-system/tasks/check-build-system.js

In #33452, we introduced automatic subpackage installation for `amp` tasks (see #33141). It turns out we're still loading task code before installation can happen. This can break during first run if a task does not lazy-require its packages. See [example failure logs](https://app.circleci.com/pipelines/github/ampproject/amphtml/10381/workflows/5567fe9e-9c11-4d42-b51e-77f694c8510d/jobs/162101).
- Perform subpackage installation in `amp-task-runner.js` before task code can be loaded
- Fix incorrect assumption that `updateSubpackages()` is async (it uses the synchronous `spawnSync()` under the covers)
- Update call-sites where `await` is no longer needed
With this, there's no need for tasks to lazy-require their packages (unless it's for performance …

🏗 Update task-level subpackages before task code can be loaded

---

.eslintignore
build-system/tasks/visual-diff/helpers.js
build-system/tasks/visual-diff/index.js
build-system/tasks/visual-diff/package-lock.json
build-system/tasks/visual-diff/package.json
build-system/tasks/visual-diff/snippets/freeze-canvas-image.js
build-system/tasks/visual-diff/snippets/freeze-form-values.js
build-system/tasks/visual-diff/snippets/iframe-wrapper.js
build-system/tasks/visual-diff/snippets/remove-amp-scripts.js
build-system/tsconfig.json

- Enable type-checking for `build-system/tasks/visual-diff/`
- Convert lazy requires to regular requires (okay because subpackage deps are now auto-installed)
- Enable linting / auto-formatting for `build-system/tasks/visual-diff/snippets/`
- Add a few typedefs, fix a few type errors

🏗 Enable type-checking for `build-system/tasks/visual-diff`

---

OWNERS

In order to get auto-submit working for low-risk package upgrades, we're switching from the `forking-renovate` app (creates PRs from a fork) to the `renovate` app (creates PRs on the main repo).
Since the new app uses a slightly different committer ID, we need an owners config change.
**Example:**
**PR:** https://github.com/ampproject/amphtml/pull/34673
**Owners check run:** https://github.com/ampproject/amphtml/pull/34673/checks?check_run_id=2737953772
**Commit info:** https://github.com/ampproject/amphtml/pull/34673/commits

🏗 Switch name of renovate bot for owners check

---

.renovaterc.json

We just switched from the `forking-renovate` app (creates PRs from a fork) to the `renovate` app (creates PRs on the main repo).
This PR updates the instructions for resolving breaking changes. We no longer need the `renovate-bot-` prefix for the branch name, and PR branches are now created on `ampproject/amphtml`. I've verified that the new instructions work.

🏗 Update instructions to resolve breaking changes during package upgrades

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json
tools/experiments/experiments-config.js

Sweep experiments last flipped globally up to 2020-11-29:
- (2020-08-14, 77ced1de0) `expand-json-targeting`: 1

🚮 Sweep experiments older than 2020-11-29

---

build-system/test-configs/jscodeshift/parser-config.json

Required for parsing files that import JSON. I thought this was already present, but memory may be failing me.

🏗 Add `importAssertions` to jscodeshift parser config

---

build-system/tasks/sweep-experiments/README.md
build-system/tasks/sweep-experiments/index.js

Decreases age of flipped experiment config from 365 days to 180.

🏗 Reduce experiment cleanup cutoff date to 180 days

---

validator/build.py
validator/package-lock.json
validator/package.json

**Two advantages:**
- Validator tests will always use the same version of closure compiler that AMP does
- You will no longer have to rubber-stamp a separate closure upgrade for `validator/` each month (e.g. #34691)
Closes #34691

🏗 Use AMP's closure compiler while running validator checks

---

.github/workflows/publish-npm-packages.yml

This overwrites the Node scripts with latest, so that we don't have to wait for PRs with those changes to make a release cut.

Use latest scripts when publishing Bento components

---

extensions/amp-sidebar/1.0/base-element.js
extensions/amp-sidebar/1.0/component.js
extensions/amp-sidebar/1.0/component.type.js
extensions/amp-sidebar/1.0/sidebar-toolbar-hook.js
extensions/amp-sidebar/1.0/storybook/Basic.amp.js
extensions/amp-sidebar/1.0/test/test-amp-sidebar.js

Sidebar Tracker: https://github.com/ampproject/amphtml/issues/31366
Toolbar design amp side for amp-sidebar
How does this work?
1. The preact Toolbar will be leveraged in both cases.  It has been refactored into `ToolbarHelper` with a wrapper preact component to be used each in `amp` and `preact` modes.
2. Each of the wrapper components pass down context to indicate whether we are in `amp` or `preact` mode.  When in `amp` mode, there is also an actual `Toolbar` `domElement` which is passed via context.
3. When in `preact` mode, the behavior is relatively unchanged.
4. When in `amp` mode, the `base-element` updates the `children` prop to be passed into preact by appending `amp` version of the `Toolbar` (the amp wrapper from 1 above).  This amp version of the toolbar takes in the actual …

✨ [bento][amp-sidebar] Toolbar design for AMP side for amp-sidebar

---

.renovaterc.json

- Add a link to all PRs pointing to the [dev dashboard](https://github.com/ampproject/amphtml/issues/34671)
- Enable auto-merge for all devDependency upgrades ([worked well](https://github.com/ampproject/amp-github-apps/pulls?q=is%3Apr+author%3Aapp%2Frenovate+sort%3Aupdated-desc+is%3Aclosed) for the `amp-github-apps` repo)
**Notes:**
- With this, we will see less noise from version upgrades
- Major version updates will still be tested in a separate group (default renovate behavior)
- Runtime dependencies will still need manual review / merge.

🏗 Enable auto-merge for all devDependency upgrades that pass CI

---

src/inabox/utils.js
src/ini-load.js
test/unit/inabox/test-utils.js

Inabox runtime wants to keep using the legacy ini load measurement mechanism since the new one is causing some regressions there.

Force inabox to use legacy ini load measurement

---

examples/amp-ad-exit-conversion.html
extensions/amp-a4a/0.1/secure-frame.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js
extensions/amp-ad-exit/0.1/amp-ad-exit.js
extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js

Opts in browsers where 
```js
// Should be chrome 92+ only.
document.featurePolicy.features().includes('attribution-reporting') == true
```
Manually verified that `the window.open()` call results in a new "Active Source" using `chrome://conversion-internals/`
Steps to repro:
1. Use chrome version >= 92
2. Enable `#experimental-web-platform-features` at `chrome://flags`
3. Click on `examples/amp-ad-exit-conversion`
4. See new entry at `chrome://conversion-internals/`
cc/ @jshamble

✨Support conversion tracking in amp-ad-exit

---

build-system/tasks/visual-diff/index.js

Puppeteer is frequently stalling / complaining about a browser disconnection during visual tests.
**Example builds:** [1](https://app.circleci.com/pipelines/github/ampproject/amphtml/10653/workflows/88ff5e62-c953-43f4-92b9-0c559f57b9e4/jobs/166860), [2](https://app.circleci.com/pipelines/github/ampproject/amphtml/10619/workflows/e7469b42-a362-42cf-8290-550ad1c0aef7/jobs/166269), [3](https://app.circleci.com/pipelines/github/ampproject/amphtml/10635/workflows/8a6991c2-8e7b-4dec-9420-df8e768f2475/jobs/166619)
The root cause is as yet unknown, but might be due to recent changes to puppeteer.
This PR is a speculative fix. Instead of using a global variable for the puppeteer instance, we directly `await` and return the result of `puppeteer.launch()`, as recommended by the "Usage" section of …

🏗 Speculative fix for puppeteer disconnections

---

extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js

Removed export for methods that are not used outside the current module in `amp-auto-lightbox`.

♻️ amp-auto-lightbox exported methods unused outside

---

docs/contributing-code.md

This PR is a copy of #30137:
> Based on a conversation with @nainar on email, pointing out that there are already mechanisms in place to make sure accessibility is considered as part of any code/submission review (and indeed, seeing that `wg-ui-and-a11y` is set as owner in most of the OWNER files), it may be worth explicitly mentioning this for further visibility/clarity.
Note that because `wg-components` no longer contains `a11y` in the name, I also added a clause about the group being a relevant resource for web accessibility considerations in the documentation.
/to @rcebulko who approved the original PR
/cc @TetraLogicalHelpdesk

📖 Add explicit mention of working groups as owners

---

build-system/pr-check/build-targets.js
build-system/server/test/app-utils.test.js
build-system/tasks/ava.js

`replaceUrls` is used throughout the build system and could do with a cleanup. Adding tests for current state before refactoring.

🏗✅ Test `replaceUrls`

---

extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js

**summary**
Fixes https://github.com/ampproject/amphtml/issues/34556
During the `showCarousel` flow, the gallery directly calls `unlayoutCallback` on its child carousel:
https://github.com/ampproject/amphtml/blob/b14fb62461438176936f8bd51e1e19271b88c7c1/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js#L353-L368
This is a problem, because `unlayoutCallback` is _not_ meant to be directly called, just like layoutCalback isn't either. It must be called by either Resources or Owners or else those systems develop undefined behavior.   In this case, it was leading to the carousel never being scheduled for layout again.
---
Note: there are still further issues here. For example, when any thumbnail but the first is clicked, an error is logged:
AFAICT, this is due to an inefficiency …

amp-lightbox-gallery: fix incorrect unlayout

---

build-system/server/app-index/amphtml-helpers.js
build-system/server/server-a4a-template.html
build-system/tasks/make-extension/template/classic/examples/amp-__component_name_hyphenated__.html
build-system/tasks/make-extension/template/shared/extensions/amp-__component_name_hyphenated__/__component_version__/test/__validator__-amp-__component_name_hyphenated__.html

This PR is a partial copy of #31208, which adds `lang="en"` to relevant code snippets in this codebase. Instead of copying the PR file-for-file, I decided to break this change up into a few root directories for ease of review and less likelihood of falling behind to merge conflicts.
Original PR description:
> Suggested changes and additions based on the TetraLogical accessibility review commissioned by @nainar / @caroqliu
>
> x-ref ampproject/amp.dev#4972
/cc @TetraLogicalHelpdesk

♿  Add lang="en" to relevant snippets in `build-system/`

---

.github/workflows/publish-npm-packages.yml
build-system/npm-publish/get-extensions.js
build-system/npm-publish/write-package-files.js

There's a bug where GHA attempts to publish latest package for stable releases, but npm says it can't since it was already published as nightly. Fixes bug by tagging instead of publishing for stable.
Tag-along: removes hard-coded extension versions i.e `1.0` and `2.0`. Use matrix instead by getting `version` values from bundle config

Tag stable version as latest on npm

---

.github/workflows/update-design-review-issues.yml
build-system/common/update-design-review-issues.js

Sessions for region `Asia/Oceania` should actually occur on Thursdays 01:00 UTC, as opposed to Wednesdays like the other regions.
After this change, issues should also close at the correct time. See https://github.com/ampproject/amphtml/issues/34439#issuecomment-857303300

🏗🐛 Allow Design Review rotation item to specify own day-of-week

---

build-system/tasks/check-types.js

**summary**
Removes the PRIDE target, as it is not compatible with the rest of our strategy involving an interim period with many separate passing targets with duplication in their externs.

typechecking: remove pride as not compatible with rest of strategy

---

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/story-ad-page.js
extensions/amp-story/1.0/amp-story-system-layer.css
extensions/amp-story/1.0/progress-bar.js
extensions/amp-story/1.0/test/test-amp-story-progress-bar.js

Follow up to #34662  that moves almost all logic to `progress-bar.js`.
Auto progresses ad and bar shows 8 second animation. Will be ran as an experiment to determine UX improvements.
Partial #33969

✨[story-ads] Introduce new yellow segment progress bar v2

---

build-system/compile/bundles.config.extensions.json

This PR establishes `build-system/compile/bundles.config.extensions.json` as the file to be utilized as the ground truth for all components which have a Bento version and what that version is, while configuring all current Bento components with `options: { "wrapper": "bento" }`. This change does not impact the bundling/build process.
Notes:
- `options: {wrapper: "bento"}` is a temporary state that is being introduced immediately for ease of reference by publishers wanting to use Bento components and easily identify which these are. It is preferred to `bento: true` or `bentoVersion: "1.0"` because the `wrapper` piece will be utilized by the auto-envelope effort (see below).
- The final state is expected to be `options: {wrapper: wrappers.bento}` once ~#30275~ #34820 is finalized.
- The …

🏗 Add `"wrapper": "bento"` option to Bento components

---

build-system/tasks/validate-html-fixtures.js

Makes the grouping process of `amp validate-html-fixtures` about **`45x` faster**. This represents a `~24%` speedup of the overall task.
- Uses `posthtml` instead of `JSDOM` to parse the tree when necessary. 
- Filters out files that lack a suffix like `4email`.
| method   | filters | time (ms) |          |
| -------- | ------- | --------: | -------- |
| JSDOM    |         |      2095 | (before) |
| JSDOM    | yes     |       241 |          |
| posthtml |         |       116 |          |
| posthtml | yes     |        47 | (after)  |

🏗🚀 Speed up validated example grouping ~45x

---

build-system/compile/bundles.config.extensions.json
build-system/compile/compile-wrappers.js
build-system/tasks/extension-helpers.js
extensions/amp-shadow-dom-polyfill/0.1/amp-shadow-dom-polyfill.js

In preparation for a larger Bento change, allow extension bundles to specify their own compile wrapper.
Bento bundles already set `"wrapper": "bento"`. By specifying this wrapper to be the same as `wrappers.extension`, this has no effect on actual output.

🏗 Allow extension bundles to specify their own wrapper

---

extensions/amp-story/1.0/amp-story.css

Context / Fixes #34830
Positions `distance="2"` page below viewport when `amp-story-desktop-one-panel` is active.
`100vh` will ensure the panel will always be off of the viewport.

✨ `amp-story-desktop-one-panel` Position distance="2" page below viewport

---

.renovaterc.json

**Two changes:**
- Set `rebaseWhen` to `never` (prevents ~hourly auto-rebasing and avoids unnecessary wastage of CI resources)
- Remove the unnecessary `assignAutomerge` setting (it's used only when `reviewers` or `assignees` is set)
- https://docs.renovatebot.com/configuration-options/#rebasewhen
- https://docs.renovatebot.com/configuration-options/#assignautomerge

🏗 Refinements to renovate config

---

ads/google/ima/ima-video.js
css/amp-ima-video-iframe.css
extensions/amp-ima-video/0.1/test/test-ima-video-internal.js

Fixes #34831
In addition, hides progress slider on livestreams since it's not usable.

🐛 amp-ima-video: Fix duration label on livestreams

---

extensions/amp-date-countdown/1.0/amp-date-countdown.css
extensions/amp-date-display/1.0/amp-date-display.css
extensions/amp-facebook-comments/1.0/amp-facebook-comments.css
extensions/amp-timeago/1.0/amp-timeago.css
extensions/amp-twitter/1.0/amp-twitter.css

- For components whose `0.1` do not need a CSS file, the `1.0` serves the purpose of providing pre-upgrade styles for layout stability, to be included as `<link>` tag on non-AMP pages.
- Excludes `amp-render` which to my knowledge will not be usable on non-AMP documents.
- Does not update `hasCss` for these new components which only have "pre-upgrade" styles -- bundling them with AMP components for use on AMP pages would be redundant to the pre-upgrade document stability styles provided by AMP's boilerplate. (In fact, a separate PR should remove `hasCss: true` from applicable Bento components that currently have it enabled.)
- Fixes https://github.com/ampproject/amp.dev/issues/5901

Bento: Ensure all Bento components have a CSS file

---

builtins/amp-layout/amp-layout.js
docs/building-an-amp-extension.md
extensions/amp-accordion/0.1/amp-accordion.js
extensions/amp-audio/0.1/amp-audio.js
extensions/amp-call-tracking/0.1/test/test-amp-call-tracking.js
extensions/amp-carousel/0.1/scrollable-carousel.js
extensions/amp-carousel/0.1/slidescroll.js
extensions/amp-carousel/0.2/amp-carousel.js
extensions/amp-consent/0.1/amp-consent.js
extensions/amp-fit-text/0.1/amp-fit-text.js
extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
extensions/amp-image-slider/0.1/amp-image-slider.js
extensions/amp-image-viewer/0.1/amp-image-viewer.js
extensions/amp-lightbox/0.1/amp-lightbox.js
extensions/amp-pan-zoom/0.1/amp-pan-zoom.js
extensions/amp-script/0.1/amp-script.js
extensions/amp-sidebar/0.1/amp-sidebar.js
extensions/amp-sidebar/0.2/amp-sidebar.js
extensions/amp-sidebar/1.0/base-element.js
extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
extensions/amp-truncate-text/0.1/amp-truncate-text.js
src/base-element.js
src/core/dom/layout.js
src/core/dom/query.js
src/custom-element.js
src/preact/base-element.js
test/unit/core/dom/test-dom.js
test/unit/core/dom/test-query.js
test/unit/test-custom-element.js

**summary**
In order to remove Runtime dependencies from `amp-layout`'s `buildCallback`, I've extracted getRealChildNodes and getRealChildren to core from CE and BE.
The primary diff in most files looks like this:
```diff
-const children = this.getRealChildren();
+const children = getRealChildren(this.element);
```
---
Note: I've noticed that in the transition from classic to bento, we are making lots of small tradeoffs that reduce our reliance on runtime code (v0.js) and will end up duplicated in all of the extensions. It is definitely a worthwhile tradeoff, but at some point far in the future may be worth mitigating.

Refactor: move getRealChildNodes and getRealChildren to core

---

extensions/amp-story/1.0/page-advancement.js

Context / Fixes #34815
Get page dimension when in `DESKTOP_ONE_PANEL` instead of story dimensions to decide left or right navigation intention.
[Demo](https://philipbell-stamp-ui.web.app/examples/amp-story/amp-story-desktop-one-panel.html)

✨ `amp-story-desktop-one-panel` Check UI type to get page dimension on tap

---

examples/amp-story/amp-story-desktop-one-panel.html
examples/visual-tests/amp-story/amp-story-desktop-one-panel.html

Add demo with animations and page attachment to test usecases.
[demo](https://philipbell-stamp-ui.web.app/examples/amp-story/amp-story-desktop-one-panel.html)

`amp-story-desktop-one-panel` Update demo with usecases

---

3p/yotpo.js
examples/amp-yotpo.amp.html
extensions/amp-yotpo/0.1/test/test-amp-yotpo.js

It looks like we intend to support it: 
https://github.com/ampproject/amphtml/blob/1f2308befa3015c84f0c8839357884dff36880d2/3p/yotpo.js#L282
But ultimately do not due to removing the part of the 3p script which inserts the Reviews Tab element:
https://github.com/ampproject/amphtml/blob/1f2308befa3015c84f0c8839357884dff36880d2/3p/yotpo.js#L28
Fixes #34859

Support `amp-yotpo` `data-widget-type="ReviewsTab"`
