src/preact/base-element.js

The helper has the wrong name! This PR fixes it.

Rename IS_NONEMPTY_TEXT to IS_EMPTY_TEXT_NODE

---

build-system/tasks/storybook/package-lock.json

The changes in this PR are applied each time `gulp storybook` is run, so the goal in merging these is for the expected dependencies and the needed dependencies for this task to become aligned.

Apply `gulp storybook` package-lock.json updates

---

extensions/amp-lightbox/0.1/amp-lightbox.js
extensions/amp-video/0.1/amp-video.js
extensions/amp-video/0.1/test/test-amp-video.js

The video is simply paused when it's resized to 0.

Video: async pause control via ResizeObserver

---

extensions/amp-fit-text/1.0/component.js
extensions/amp-fit-text/1.0/test/test-component.js

✅  FitText: Add Preact unit tests

---

spec/amp-actions-and-events.md

https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/

📖 Keep Video Element list constant

---

extensions/amp-accordion/1.0/amp-accordion.css

Switch to supports selector format for :where CSS

---

build-system/compile/compile.js

See https://github.com/ampproject/amp-closure-compiler/pull/57

🏗 Include AMP_MODE when closure compiling

---

src/runtime.js
src/service/extension-script.js
src/service/extensions-impl.js
test/unit/test-extension-script.js
test/unit/test-extensions.js
test/unit/test-runtime.js

Multiversion: get stricter with propagating and filtering extension versions

---

ads/vendors/ssp.js

ADS: fix SSP responsive rendering

---

extensions/amp-story-player/0.1/test/test-e2e/test-amp-story-player-navigation.js
extensions/amp-story-player/0.1/test/test-e2e/test-amp-story-player-prerender.js
extensions/amp-story-player/0.1/test/test-e2e/test-amp-story-player.js
test/fixtures/e2e/amp-story-player/basic.amp.html
test/fixtures/e2e/amp-story-player/navigation.amp.html
test/fixtures/e2e/amp-story-player/pre-rendering.amp.html

Adds e2e tests for AMP version of the player.

[amp-story-player] ✅  Add e2e for AMP version

---

spec/amp-story-player.md

[amp-story-player] 📖  Fix headers

---

ads/_config.js
ads/vendors/fluct.js
ads/vendors/fluct.md
examples/amp-ad/ads.amp.html

We support new type of ad deliver tag and would like to add `amp-ad`.
This is non breaking changes.
Previous tag
```
<amp-ad width="300" height="250"
type="fluct"
data-g="1000067784"
data-u="1000101409">
</amp-ad>
```
New tag
To use new ad tag,  `data-tagtype` have to be set `api`.
```
<amp-ad width="300" height="250"
type="fluct"
data-g="1000128429"
data-u="1000220560"
data-tagtype="api">
</amp-ad>
```
And also it had changed hostname of fluct, We would like to merge changes of the PR below.
refs. https://github.com/ampproject/amphtml/pull/26035

Support new tag type for fluct SSP

---

extensions/amp-story/1.0/amp-story-page.js

♿ [amp-story] [Page attachments] Click listener on shadow root container

---

3p/vendors/adpushup.js
3p/vendors/finative.js
3p/vendors/ketshwa.js

Add 3 vendors to seperate 3p builds

---

extensions/amp-story-auto-ads/0.1/algorithm-count-pages.js
extensions/amp-story-auto-ads/0.1/algorithm-interface.js
extensions/amp-story-auto-ads/0.1/algorithm-utils.js
extensions/amp-story-auto-ads/0.1/story-ad-page-manager.js

Implementation to follow.
Partial #33147

♻️ Introduce skeleton for story ads page manager & algorithm interface

---

extensions/amp-story/1.0/amp-story.js
src/amp-story-player/amp-story-player-impl.js
test/unit/test-amp-story-player.js

Closes #32941
To be merged after #32931

[amp-story-player] Rewind stories in the background

---

validator/cpp/engine/WORKSPACE

🐛 Fix missing dependencies in bazel

---

validator/BUILD

🐛Fix missing svg rules in BUILD file

---

extensions/amp-story-auto-ads/0.1/story-ad-page-manager.js
extensions/amp-story-auto-ads/0.1/test/test-story-ad-page-manager.js

♻️ Add logic for story ad page manager.

---

build-system/global-configs/experiments-config.json
build-system/global-configs/experiments-const.json
extensions/amp-a4a/0.1/test/test-a4a-integration.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js

✨Launch no-signing

---

extensions/amp-autocomplete/0.1/test/validator-amp-autocomplete.out.cpponly

The output file is outdated in github. See b/182193178#comment2 and b/182193178#comment3.

🐛 Sync amp-autocomplete test output file

---

build-system/common/utils.js
build-system/pr-check/experiment-build.js
build-system/pr-check/experiment-tests.js
build-system/pr-check/utils.js
build-system/tasks/report-test-status.js

Thanks @calebcordry for reporting this issue!

🏗 report test status of experimentN as "skipped" when no such experiment exists

---

extensions/amp-font/amp-font.md

Resolves [issue 5504](https://github.com/ampproject/amp.dev/issues/5504)

small amp-font fixes for issue 5504

---

build-system/global-configs/experiments-const.json

Breaks partner ad networks #33274

🐛Unlaunch no signing

---

build-system/global-configs/OWNERS

I no longer need to follow these updates in real time

Remove danielrozenberg from build-system/global-configs/OWNERS

---

extensions/amp-story-auto-ads/0.1/algorithm-count-pages.js
extensions/amp-story-auto-ads/0.1/test/test-algorithm-count-pages.js

♻️ [Story Ads] Move existing placement logic to algo impl

---

src/preact/compat.js

Add portals to preact/compat for use in Bento components

🏗 [bento] Add portals to preact compat

---

contributing/design-reviews.md

Should not be syntax highlighted:

📖 License code block not be ```js

---

examples/3q-player.amp.html
extensions/amp-3q-player/0.1/amp-3q-player.js
extensions/amp-3q-player/0.1/test/test-amp-3q-player.js

This will serve as a template for all similar elements.

3q-player: implement async pause

---

build-system/compile/pre-closure-babel.js
build-system/tasks/extension-helpers.js
build-system/tasks/helpers.js

**summary**
Can be reproduced on current master by:
1. `gulp`
2. go to http://localhost:8000/dist/v0/amp-bind-0.1.max.js
3. modify`bind-impl.js` and see explosions.

build-system: fix unminified watch mode.

---

extensions/amp-a4a/rtc-documentation.md
extensions/amp-a4a/rtc-publisher-implementation-guide.md
src/service/real-time-config/callout-vendors.js

✨ Local Media Consortium: Endpoint rename to NewsPassID

---

build-system/common/esbuild-babel.js

Alternative to https://github.com/ampproject/amphtml/pull/33365#event-4478137702

esbuild cache invalidation: add argv to optionsHash

---

build-system/common/esbuild-babel.js

Avoid JSON stringifying unless absolutely necessary.

Optimize babel hashing

---

validator/js/webui/serve-standalone.go

The Validator Web UI will use the experimental WebAssembly code when the URL is like `https://validator.amp.dev/?experimental_wasm=1`.

✨ Add a query param to enable wasm validator in webui

---

build-system/common/ci.js
build-system/pr-check/experiment-tests.js

- Adds test case reporting for experiment builds
- Fixes job ID extraction (turns out that `CIRCLE_NODE_INDEX` is always zero, so use `CIRCLE_JOB` instead)
**Reference:** https://circleci.com/docs/2.0/env-vars/

🏗 Report results for experiment tests

---

extensions/amp-lightbox/1.0/test-e2e/test-custom-close-button.js

This test has been a common source of flakiness in CI
http://amp-test-cases.appspot.com/test-results/history/71865af50987cd6ec686cf54939edcc0
#32442

skip flaky lightbox test

---

build-system/global-configs/experiments-config.json

🧪 [no-signing] re-enable in exp A 

---

examples/visual-tests/amp-story/amp-story-bot-rendering.html

Adding `amp-video-0.1.js` script and fixing validation issues in hopes of fixing flakiness.

[amp-story] ❄️ Fix visual diff flake

---

extensions/amp-lightbox/test-e2e/test-amp-lightbox.js

Flake PR: https://github.com/ampproject/amphtml/issues/33413

❄️Skip flaky amp-lightbox e2e test

---

extensions/amp-story/amp-story-bookend.md

retrying #33378
see ampproject/amp.dev#3957
cc @newmuis

mark amp-story-bookend as deprecated

---

extensions/amp-story-auto-ads/0.1/algorithm-utils.js

Doing this in a separate PR to merge before #33343 so that we can have a clean revert of #33343 if something goes horribly wrong :)

✨[story-ads] Send win to algo choice function

---

extensions/amp-animation/0.1/test-e2e/test-amp-animation.js
extensions/amp-base-carousel/1.0/test-e2e/test-non-looping.js
extensions/amp-onetap-google/0.1/test/test-amp-onetap-google.js

Skip-test PR for https://github.com/ampproject/amphtml/issues/33438, https://github.com/ampproject/amphtml/issues/33437, and https://github.com/ampproject/amphtml/issues/24195#issuecomment-805025326

❄️Skip flaky tests in amp-carousel:1.0, amp-animation, amp-onetap-google

---

extensions/amp-onetap-google/0.1/amp-onetap-google.js
extensions/amp-onetap-google/0.1/test/test-amp-onetap-google.js

❄ Deflake amp-onetap-google

---

.github/workflows/create-design-review-issue.js

Apologies to those who had workflow run notifications on their personal forks.

🐛Don't run new desrev issue workflow on forks

---

validator/js/webui/app.yaml
validator/js/webui/build.py

Build `index_wasm.html` which uses WebAssembly AMP Validator.
The WebAssembly Web UI will be at https://validator.amp.dev/index_wasm.html.

✨ Add WebAssembly page to Validator Web UI

---

extensions/amp-story-auto-ads/0.1/algorithm-predetermined.js
extensions/amp-story-auto-ads/0.1/algorithm-utils.js
extensions/amp-story-auto-ads/0.1/test/test-algorithm-predetermined.js

Determines number of pages and insertion points upon page load. Monetizes shorter stories (>4 pages).
Partial #33147

✨[story-ads] Introduce new placement algorithm

---

src/custom-element.js
src/preact/base-element.js
test/unit/preact/test-base-element-runtime.js
test/unit/test-custom-element-v1.js

Bento: adopt mount/unmount

---

examples/amp-story/video-one-page.html
examples/amp-story/video-one-page2.html
extensions/amp-story-player/0.1/test/test-e2e/test-amp-story-player-navigation.js
test/e2e/test-amp-story-player-navigation.js

Closes  #33482
* Increases timeouts to decrease flakiness .
* Imports extension scripts manually in tests.
When running `amp --compiled` and navigating to the test page (e.g. `http://localhost:8000/test/fixtures/e2e/amp-story-player/navigation.amp.html`) the local server fails to fetch dynamically installed extensions (see error logs below).
e.g. in `amp-story.js` we install the `amp-viewer-integration-0.1.js` here when it's not found in the doc:
https://github.com/ampproject/amphtml/blob/6616e578b8c257d82ab91fd99aa720fcdc4022b1/extensions/amp-story/1.0/amp-story.js#L1363
We didn't have to manually add these extensions to the test files, I believe this is a regression in the local server @ampproject/wg-infra 
Error logs when running `amp --compiled` and navigating to the test page (e.g. …

❄️ [amp-story-player] Fix flakiness in e2e test

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json
extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
extensions/amp-story-auto-ads/0.1/algorithm-predetermined.js
extensions/amp-story-auto-ads/0.1/algorithm-utils.js
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
src/experiments/story-ad-placements.js
tools/experiments/experiments-config.js

🧪[story-ads] Start new placement algo exp

---

extensions/amp-sidebar/0.1/amp-sidebar.js
extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
extensions/amp-sidebar/0.2/amp-sidebar.js
extensions/amp-sidebar/0.2/test/test-amp-sidebar.js

Follow up on https://github.com/ampproject/amphtml/pull/33281

Legacy sidebar to set container for Bento mounting

---

.eslintrc.js
build-system/test-configs/forbidden-terms.js

Terms can now specify whether they should be checked in comments.

🏗 Check some forbidden terms in comments

---

extensions/amp-story-auto-analytics/amp-story-auto-analytics.md

📖  [Story autoanalytics] Improved documentation

---

extensions/amp-story-auto-ads/0.1/test/test-algorithm-predetermined.js

Failing frequently on master. 
to/ @ampproject/build-on-duty

🐛 Skip flaky story ad tests

---

builtins/amp-img.js

Prepare amp-img for V1 experiment

---

extensions/amp-subscriptions/amp-subscriptions.md

- Adding more guidance on how to migrate from amp-access to amp-subscriptions
- Change image rendering so it loads on amp.dev

📖  More detail on difference between amp-subscriptions and amp-access

---

build-system/tasks/release/index.js

This will allow us to parallelize building the module and nomodule binaries in separate VMs

🏗 Add --esm flag to `amp release`

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

- Update dependency postcss to v8.2.9 (#1586)
- Bind PayClient.handleResponse_ in ctor (#1577)
- Update dependency karma to v6.3.2 (#1585)
- Update dependency rollup to v2.44.0 (#1582)
- Update dependency @babel/core to v7.13.14 (#1580)
- Update dependency karma to v6.3.1 (#1579)
- Update dependency eslint to v7.23.0 (#1581)

🏗  SwG Release March 31, 2021

---

examples/visual-tests/amp-story-player/player-amp-version.html
examples/visual-tests/amp-story-player/player-amp-version.js
examples/visual-tests/amp-story-player/story-loaded-amp-version.js
test/visual-diff/visual-tests

Closes https://github.com/ampproject/amphtml/issues/33562

[amp-story-player] Add visual test for AMP version

---

examples/auto-ads.amp.html
extensions/amp-auto-ads/0.1/premiumads-network-config.js

https://github.com/ampproject/amphtml/issues/33459

✨ New feature (allowing add data-attributes when premiumads type for amp-auto-ads)

---

extensions/amp-iframe/0.1/amp-iframe.js
extensions/amp-iframe/0.1/test/test-amp-iframe.js

Roll forward amp-iframe async pause

---

extensions/amp-story/1.0/amp-story-system-layer.css
extensions/amp-story/1.0/amp-story-system-layer.js

Partial for https://github.com/ampproject/amphtml/issues/33355 #33353
Adds skeleton layout + CSS which will contain story attribution (publisher's logo + name).
Follows the next considerations:
- `<img>` tag contains `alt` since its only a decorative logo that will be accompanied by text (publisher or entity name) [w3 functional images](https://www.w3.org/WAI/tutorials/images/functional/#logo-image-within-link-text)
- tested in RTL in landscape, 3 panels
- hides the attribution when an ad is shown to avoid mis-attribution as well as overlap between the "Ad" badge and the attribution.

✨ [amp-story] [story-attribution]Add markup and CSS

---

build-system/global-configs/experiments-config.json
build-system/global-configs/experiments-const.json

Second try after animation fix. 
Partial #27189

🚀 Launch no-signing experiment

---

build-system/global-configs/experiments-config.json
test/integration/test-visibility-states.js

Launch deferred mount for amp-img for 1%

---

validator/js/webui/app.yaml

✨ Set Validator WebUI to use WebAssembly by default

---

.circleci/config.yml
build-system/pr-check/utils.js

Follow up to #33686
I've [confirmed](https://app.circleci.com/pipelines/github/ampproject/amphtml/6265/workflows/8b9da3bc-f8c9-47c5-8a2e-aceedb68d5bd) this works. Pay attention to the job times in the right-side column.

🏗 Another fix for the graceful halt optimization during CI

---

package-lock.json
package.json

Fixes: https://github.com/ampproject/amphtml/issues/32984, as well as creates `sandboxed` worker support. Blocks https://github.com/ampproject/amphtml/pull/33643

dependencies: bump worker dom

---

src/core/assert.js
src/log.js
test/integration/test-errors.js
test/unit/test-assert.js
test/unit/test-error.js
test/unit/test-log.js

Companion to https://github.com/ampproject/amphtml/pull/33434
Use core assertion logic within otherwise-convoluted log.js logic.

♻️Use core/assert within log assert

---

src/config.js

Types: fix src/config.js urls type

---

build-system/pr-check/ci-job.js

We already catch and report unhandled errors from within `amp` tasks. However, failures during other portions of a CI Job can [slip through](https://app.circleci.com/pipelines/github/ampproject/amphtml/6337/workflows/b4ac4686-9c95-48dc-a4d9-d385b8fd534c/jobs/90309/parallel-runs/0/steps/0-111).
This PR updates the CI wrapper script to catch and report any unhandled errors that may occur during the PR or push build workflows, and ensures that the process exits with a failing `exitCode`.

🏗 Catch and report errors thrown during CI Jobs

---

validator/js/webui/app.yaml
validator/js/webui/build.py
validator/js/webui/index.html

🐛Rename JS version Validator WebUI as `legacy.html`

---

build-system/externs/amp.extern.js
build-system/test-configs/forbidden-terms.js
src/core/assert.js
src/service/url-replacements-impl.js
src/service/video-manager-impl.js
src/service/video/autoplay.js
src/service/viewer-impl.js
src/service/viewport/viewport-binding-def.js
src/service/viewport/viewport-binding-ios-embed-wrapper.js
src/service/viewport/viewport-binding-natural.js
src/service/viewport/viewport-impl.js
src/service/xhr-impl.js
src/services.js
src/shadow-embed.js
src/style.js
src/url.js
src/utils/dom-tranform-stream.js
src/utils/intersection-no-root.js
src/utils/intersection.js
src/utils/resource-container-helper.js
src/utils/xhr-utils.js
src/video-interface.js

Types: viewport and video-manager modules

---

extensions/amp-date-display/1.0/test/validator-amp-date-display.html
extensions/amp-date-display/1.0/test/validator-amp-date-display.out

🐛 Fix a typo in test file

---

test/visual-diff/visual-tests

❄️ Disable two flaky visual diff tests

---

build-system/test-configs/forbidden-terms.js
src/service/video-manager-impl.js

Async measure: remove getLayoutSize from video-manager-impl

---

build-system/externs/amp.extern.js
src/service/scheduler.js
src/service/standard-actions-impl.js
src/service/template-impl.js
src/service/url-expander/expander.js
test/unit/test-standard-actions.js

Types: url-expander and standard-actions

---

extensions/amp-selector/0.1/amp-selector.js

This was tagged as safe to remove in Q1 2020. It's been one year.
[Related thread on Slack.](https://amphtml.slack.com/archives/C9HPA6HGB/p1618255480137700)

🚮 Remove old warning about change in behavior

---

extensions/amp-mustache/OWNERS

Update amp-mustache OWNERS

---

.github/workflows/sweep-experiments.yml

🏗 Don't run sweep-experiments workflow on forks

---

.github/PULL_REQUEST_TEMPLATE.md
contributing/getting-started-e2e.md
contributing/getting-started-quick.md

These instructions should help first-time contributors ensure that all PR checks are correctly triggered. For example, https://github.com/ampproject/amphtml/pull/33795#issuecomment-819516701.

📖 Add sign-in instructions for PR check services to dev docs and PR template

---

build-system/compile/bundles.config.extensions.json
build-system/tasks/bundle-size/filesize.json

🏗 Generate npm bundles+bundle-sizes for extension with component.js

---

examples/visual-tests/amp-story-player/player-amp-version.html
examples/visual-tests/amp-story-player/player-amp-version.js
test/visual-diff/visual-tests

Partial #33758
Removes scrollbar to fix flaky test.

[amp-story-player] Fix flaky test

---

spec/amp-story-player.md

Forgot to add docs for the rewind API.
Part of #31424

[amp-story-player] Add docs for rewind API

---

extensions/amp-brid-player/0.1/amp-brid-player.js
extensions/amp-brightcove/0.1/amp-brightcove.js
extensions/amp-connatix-player/0.1/amp-connatix-player.js
extensions/amp-dailymotion/0.1/amp-dailymotion.js
extensions/amp-delight-player/0.1/amp-delight-player.js
extensions/amp-gfycat/0.1/amp-gfycat.js
extensions/amp-ima-video/0.1/amp-ima-video.js
extensions/amp-izlesene/0.1/amp-izlesene.js
extensions/amp-jwplayer/0.1/amp-jwplayer.js
extensions/amp-kaltura-player/0.1/amp-kaltura-player.js
extensions/amp-megaphone/0.1/amp-megaphone.js
extensions/amp-mowplayer/0.1/amp-mowplayer.js
extensions/amp-nexxtv-player/0.1/amp-nexxtv-player.js
extensions/amp-o2-player/0.1/amp-o2-player.js
extensions/amp-ooyala-player/0.1/amp-ooyala-player.js
extensions/amp-powr-player/0.1/amp-powr-player.js
extensions/amp-reach-player/0.1/amp-reach-player.js
extensions/amp-soundcloud/0.1/amp-soundcloud.js
extensions/amp-springboard-player/0.1/amp-springboard-player.js
extensions/amp-video-iframe/0.1/amp-video-iframe.js
extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
extensions/amp-vimeo/0.1/amp-vimeo.js
extensions/amp-vine/0.1/amp-vine.js
extensions/amp-youtube/0.1/amp-youtube.js
extensions/amp-youtube/0.1/test/test-amp-youtube.js

Blocked on:
This will serve as a template for all similar elements.
* amp-brid-player
* amp-brightcove
* amp-connatix-player
* amp-dailymotion
* amp-delight-player
* amp-gfycat
* amp-ima-video
* amp-izlesene
* amp-jwplayer
* amp-kaltura-player
* amp-megaphone
* amp-mowplayer
* amp-nexxtv-player
* amp-o2-player
* amp-ooyala-player
* amp-powr-player
* amp-reach-player
* amp-soundcloud
* amp-springboard-player
* amp-video-iframe
* amp-vimeo
* amp-vine
* amp-youtube

Async pause for video players

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Ramp up sticky-ad-transition to 50%

---

spec/amp-story-player.md
src/amp-story-player/amp-story-player-impl.js
test/unit/test-amp-story-player.js

Exposes an event that is dispatched whenever the story is muted/unmuted.
A quirk with this is that if `player.mute()/unmute()` is called, this event will be dispatched (same issue we have when getting page updates). Some additional work is needed to mark these events as coming from the player so that they can be ignored/used depending on the use case.

[amp-story-player] Expose amp-story-muted-state event

---

extensions/amp-story-auto-ads/0.1/algorithm-predetermined.js
extensions/amp-story-auto-ads/0.1/algorithm-utils.js
src/experiments/story-ad-placements.js

12 is revenue negative and 8 is a bit aggressive. We would like to see how 10 performs.

🧪[story ads] add ten branch to placement exp

---

extensions/amp-render/1.0/test/test-amp-render.js

See https://github.com/ampproject/amphtml/pull/33859#issuecomment-821627949 for context
TL;DR - Large refactor involved moving some files. New test file referenced old location, but wasn't present in branch during main refactor

🐛 Fix import (merge?) error in test file

---

.circleci/fail_fast.sh
build-system/pr-check/checks.js

🏗 Configure CircleCI to email build/release-on-duty on main/release branch failures, respectively

---

extensions/amp-analytics/analytics-vendors-list.md

Updated docs to fix product name and link
@ampproject/wg-analytics

Updated docs to fix product name and link to docs

---

build-system/tasks/validator.js

**Before:** ([logs](https://app.circleci.com/pipelines/github/ampproject/amphtml/7224/workflows/41cf7899-7d0f-403a-be8c-6cf1bbea51dd/jobs/105611/parallel-runs/0/steps/0-112))
**After:** ([logs](https://app.circleci.com/pipelines/github/ampproject/amphtml/7249/workflows/7d9e86fc-5753-49a7-992a-96b09033ac05/jobs/106035/parallel-runs/0/steps/0-112))
- https://docs.bazel.build/versions/master/command-line-reference.html#flag--show_progress
- https://docs.bazel.build/versions/master/command-line-reference.html#flag--show_loading_progress
- https://docs.bazel.build/versions/master/command-line-reference.html#flag--test_output
- https://docs.bazel.build/versions/master/command-line-reference.html#flag--test_summary
- https://docs.bazel.build/versions/master/command-line-reference. …

🏗 Clean up validator C++ logs and surface errors

---

.circleci/setup_storage.sh
build-system/tasks/pr-deploy-bot-utils.js

.config.yml file change will come later, for now this PR will remove the step without disrupting builds

🏗 Disable gcloud storage support in CircleCI

---

extensions/amp-story/1.0/amp-story-open-page-attachment.css

Fix CSS targeting and cascade position.
Context / Fixes #32716

🐛 [Amp story] [Page attachments] [Outlink] Fix theming

---

extensions/amp-live-list/0.1/test/test-live-list-manager.js
src/friendly-iframe-embed.js
src/service/extensions-impl.js
test/unit/test-extensions.js
test/unit/test-friendly-iframe-embed.js
test/unit/test-runtime.js
testing/describes.js

Turn on multi-version extensions

---

src/validator-integration.js
test/unit/test-validator-integration.js

For example, when using `https://amp.dev/#development=1&validate=wasm`, the WebAssembly version of AMP Validator will be used to validate the page.

✨Add a hash parameter to integrate WebAssembly Validator

---

validator/build.py

The message is missing two spaces.

Fix validator message space

---

examples/amp-story/attachment.html
extensions/amp-story/1.0/amp-story-open-page-attachment.css
extensions/amp-story/1.0/amp-story-open-page-attachment.js

Context / Fixes #32767
- Adds dark theme support for inline default pre-tap.
- Updates template.
- Removes animation (animation will be added in follow up #33261)
[demo](https://philipbell-stamp-ui.web.app/examples/amp-story/attachment.html)

✨ [Amp story] [Page attachments] [Inline] Theme pre-tap without images

---

extensions/amp-animation/amp-animation.md
extensions/amp-story/amp-story.md

Closes #30680
Adds documentation for the `<amp-story-animation>` component.

[amp-story] 📖 Add amp-story-animation docs

---

build-system/pr-check/utils.js

🏗 Remove legacy gcloud storage code-path

---

spec/amp-video-interface.md

Removes list item that I accidentally submitted when testing `amp check-video-interface-list`.

📖 Remove placeholder list item

---

build-system/compile/OWNERS

Update owners for bundles.config.*

---

extensions/amp-video/0.1/test-e2e/test-amp-video-analytics.js
test/fixtures/e2e/amp-video/analytics-triggers.html

The CircleCI insights dashboard has flagged `amp-video with video analytics chrome Standalone environment control buttons should manipulate video box behavior` as one of the slowest e2e tests.
[Insights - ampproject_amphtml_workflows_CircleCI.pdf](https://github.com/ampproject/amphtml/files/6361644/Insights.-.ampproject_amphtml_workflows_CircleCI.pdf)
This seems to be due to the two synchronous 5000ms awaits. To address this I have changed the player to use a shorter video to ensure a smaller period of time is equivalent to a similar play percentage and decreased the await times.

✅  🚀  speed up test-amp-video-analytics test

---

build-system/compile/bundles.config.extensions.json
css/Z_INDEX.md
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-progress-bar.css
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js

To be enabled when ads are auto advancing. Should help user confusion.

✨[story ads] Introduce new progress bar 

---

src/experiments/OWNERS

Folder used for shared experiments across extensions. Mostly used by ads.

🏗 Add OWNERS for src/experiments/

---

extensions/amp-story/1.0/story-analytics.js
extensions/amp-story/1.0/test/test-story-analytics.js

🐛 [amp-story] don't send story-page-visible for ad pages

---

extensions/amp-video/1.0/test/validator-amp-video.html
extensions/amp-video/1.0/test/validator-amp-video.out
extensions/amp-video/validator-amp-video.protoascii

Add validation rules for amp-video 1.0

---

ads/vendors/opinary.js
ads/vendors/opinary.md

Opinary has developed a software solution for online polls.
So far the AMP integration only supported the "automatic matching", where the Opinary algorithm decided what polls to show.
This pull request allows publishers to embed a specific poll to a specific article.
The publisher is also able to subscribe to the poll data using postmessage events.

✨ Ads: Resolves support for Opinary Embed integration

---

test/visual-diff/visual-tests

See #34033 for details and logs

❄️ Mark `amp-story-dev-tools` visual tests as flaky

---

spec/amp-story-player.md

[amp-story-player] 📖 Fix typos in docs

---

test/fixtures/e2e/amp-carousel/0.1/slidescroll-autoplay.html

According to the test insights provided by CircleCI `AMP carousel 0.1 slideChange on type="slide" with autoplay chrome Standalone environment should re low trust event for autoplay advance` is among the slowest tests.
[Insights - ampproject_amphtml_workflows_CircleCI.pdf](https://github.com/ampproject/amphtml/files/6360614/Insights.-.ampproject_amphtml_workflows_CircleCI.pdf)
This seems to be because the test is waiting for the slides autoplay to trigger a `slideChange` event. According to the docs the autoplay attribute does not actually accept a value and the delay attribute should be used instead.
https://amp.dev/documentation/examples/components/amp-carousel/#autoplay

✅  🚀  ♻️  Reduce delay for amp-carousel autoplay e2e tests

---

test/unit/polyfills/test-array-includes.js
test/unit/polyfills/test-custom-elements.js
test/unit/polyfills/test-document-contains.js
test/unit/polyfills/test-domtokenlist-toggle.js
test/unit/polyfills/test-math-sign.js
test/unit/polyfills/test-object-assign.js
test/unit/polyfills/test-object-values.js

This PR fixes the paths in some polyfill unit tests. See https://github.com/ampproject/amphtml/pull/34020#issuecomment-827923414.
To prevent this in future, I've sent out #34040.

✅ Fix broken unit tests

---

build-system/pr-check/checks.js
build-system/tasks/make-extension/index.js

Per https://github.com/ampproject/amphtml/pull/34021#issuecomment-827915882

🏗 Add `make-extension --test` to `pushBuildWorkflow`

---

extensions/amp-story/1.0/pagination-buttons.css

context / Fixes #32504
[demo](https://philipbell-stamp-a11y.web.app/examples/amp-story/ampconf.html)

✨ ♿ [amp story] Visible pagination button when navigating with keyboard on small screen.

---

src/core/OWNERS

🏗 Notify (not require) Justin on core changes

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-button.css
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

- Handle AlreadySubscribedResponse in swg-basic.js. It will open check … (#1621)
- Initialize Pay Client in ctor upon redirect. (#1620)
- Populate event info for PAYMENT_COMPLETE event in GA function calls. (#1616)
- Update dependency @babel/core to v7.13.16 (#1619)
- Let offers flow process EntitlementsResponse if users already a subsc… (#1618)
- Update dependency chromedriver to v90 (#1617)
- Remove extra deps (#1615)
- Add swgUserToken field to EntitlementsResponse api message. (#1614)
- Update dependency eslint-plugin-prettier to v3.4.0 (#1613)
- Mini prompt and button UX tweaks (#1612)
- Add subscription_flow string to EventParams. (#1611)

✨ swg release 0.1.22.158

---

src/service/extensions-impl.js
test/unit/test-extensions.js

Addresses https://github.com/ampproject/amphtml/issues/25415

runtime: remove extension loading timeout

---

build-system/compile/sources.js

🚮 Remove nonexistent directory from `sources.js`

---

extensions/amp-story/OWNERS

✨ Add raxsha to amp-story owners.

---

extensions/amp-iframely/amp-iframely.md

Their names are very close, but one goes through a 3rd-party vendor. 
This component nor its documentation have made it live.

📖 Clarify that <amp-iframely> is not <amp-iframe>

---

contributing/OWNERS

Remove user who's no longer a member from `OWNERS`.

📖 Remove user who's no longer a member from `OWNERS`

---

extensions/amp-youtube/validator-amp-youtube.protoascii

✅ Validator should satify `amp-youtube`, not `amp-video`

---

extensions/amp-iframely/0.1/test/validator-amp-iframely.html
extensions/amp-iframely/0.1/test/validator-amp-iframely.out
extensions/amp-iframely/validator-amp-iframely.protoascii

add also_requires_attr to data-url for data-key

amp-iframely validation update

---

validator/js/nodejs/index.js

After #34069 upgraded `commander` to v7, the cli args need to be visited by `opts.validator_js` rather than `program.validator_js`.

🐛 Fix a bug that validator failed to get cli opts

---

extensions/amp-youtube/1.0/component.js

🐛 amp-youtube 1.0: forward mute method

---

extensions/amp-story-panning-media/amp-story-panning-media.md

Fixes a broken link and adjusts size of images.
@ampproject/wg-stories

📖 🐛 Update amp-story-panning-media docs image link and size

---

extensions/amp-video/1.0/storybook/_helpers.js

Fix type recently merged as it may be blocking CI.

🐛 Fix bad type

---

src/error-reporting.js
test/unit/test-error-reporting.js

Trim down the size of runtime (curious how much though).

🚀 Remove Error classification

---

extensions/amp-subscriptions-google/OWNERS
extensions/amp-subscriptions/OWNERS

Update owners to reflect current active team members

🏗  amp-subscriptions* owners update

---

build-system/compile/bundles.config.extensions.json
build-system/tasks/extension-helpers.js

The configuration always has to be the same, so if `true` is specified it will assume the default structure.
/cc @krdwan @ampproject/wg-bento

🏗️ Simplify enabling npm bundle for components

---

extensions/amp-story/1.0/amp-story-open-page-attachment.css
extensions/amp-story/1.0/amp-story-open-page-attachment.js

Outlink
- Add drop shadow
- Fix jagged edges on arrow SVG
- Prevent label text descenders from clipping
INLINE
- Gradient adjustment
- Fix jagged edges on arrow SVG
@ampproject/wg-stories

🖍 [Amp story] [Page attachments] Style adjustments

---

extensions/amp-story/1.0/amp-story-page.js
extensions/amp-story/1.0/page-advancement.js
extensions/amp-story/1.0/test/test-amp-story-page.js
extensions/amp-story/1.0/test/test-page-advancement.js

- When setting a default value for auto-advance-after, always use `storyNextUp` value first
- Add `updateTimeDelay()` method which allows a TimeBasedConfig to update the delay it uses, and derivative values
- Listen once for when the amp-video metadata is available and maybe update the time delay to the video duration
- Add tests for `updateTimeDelay()`
- Add tests to make sure `storyNextUp` is only used if there's no `auto-advance-after` value already set.

Check video duration when setting AutoAdvance default

---

extensions/amp-render/1.0/amp-render.js
extensions/amp-render/1.0/test/test-amp-render.js

♿  [amp-render] add aria-live attribute if not specified

---

.github/workflows/publish/build-npm-binaries.js
.github/workflows/publish/write-package-jsons.js
build-system/pr-check/write-package-jsons.js

Creates package json files for given bento components and amp versions

Let GitHub Actions write package jsons for bento

---

src/preact/OWNERS

Folder used for Preact layer of Bento component architecture.

🏗 Add OWNERS for `src/preact`

---

extensions/amp-story/1.0/test/test-amp-story-page.js

Closes #34260
Adds additional language around using `_top` in swipe up links (opening the link in the parent window for viewers).
(Follow up for #34030)

Add additional wording to page attachment tests for target=_top

---

src/core/types/array.js

With this fix, the following type-checks fine:

🐛Solve dumb CC type inference bug

---

extensions/amp-twitter/1.0/amp-twitter.js
src/amp-story-player/amp-story-player-impl.js
src/context/node.js
src/context/prop.js
src/context/values.js
src/core/assert/dev.js
src/core/assert/index.js
src/core/assert/user.js
src/core/constants/action-constants.js
src/core/dom/css.js
src/inabox/inabox-viewport.js
src/polyfills/fetch.js
src/preact/base-element.js
src/preact/slot.js
src/purifier/purifier.js
src/utils/bytes.js
src/utils/date.js
src/utils/detached-dom-stream.js
src/utils/dom-ancestor-visitor.js
src/utils/dom-tranform-stream.js
src/utils/dom-writer.js
src/utils/math.js
src/utils/xhr-utils.js
src/web-worker/amp-worker.js
test/unit/core/test-assert.js

Related to https://github.com/ampproject/amphtml/issues/33631 and https://github.com/ampproject/amphtml/issues/32693

♻️ Start updating assertions to use core/assert instead of src/log

---

extensions/amp-fx-collection/0.1/amp-fx-collection.js
src/context/scheduler.js
src/context/subscriber.js
src/core/error.js
src/polyfills/custom-elements.js
src/utils/resource-container-helper.js
src/utils/size-observer.js

♻️ Provide core `tryCallback` helper

---

extensions/amp-ima-video/0.1/test/test-ima-video-internal.js

Fixes red main branch
https://github.com/ampproject/amphtml/pull/34248#issuecomment-840684625

🐛Fix lint error in test-ima-video-internal.js

---

extensions/amp-facebook-like/0.1/test/test-amp-facebook-like.js

✅ Add unit tests for amp-facebook-like

---

src/amp-story-player/amp-story-player-impl.js

Another bug found while creating my own lightbox player:
If the player is not visible in the first viewport (behind a lightbox), and then you call `player.play()` from an entry point (e.g. carousel). An error[1] will be thrown and the player won't display.
This is caused by the loading strategy that the player uses to lay out the component:
1) When the player is visible in the viewport, or
2) On first scroll
Because the carousel implementation doesn't fulfill any of these two rules**, the player will never be laid out. We should add a 3rd rule:
3) when `play()` is called and `this.element_.isLaidOut_ === false`
*The error thrown is:
```
amp-story-player-impl.js:1234 Uncaught TypeError: Cannot read property 'then' of undefined
at X (amp-story-player-impl.js:1234)
at Db.l.play …
```

[amp-story-player] Fix layout bug

---

extensions/amp-facebook-page/0.1/test/test-amp-facebook-page.js
extensions/amp-facebook/0.1/test/test-amp-facebook.js

✅ Add unit tests for amp-facebook-page

---

build-system/pr-check/visual-diff-tests.js

Change effects effects e2e tests but do not effect the runtime lead to visual diff tests being run without the modules being built. [here is an example build](https://app.circleci.com/pipelines/github/ampproject/amphtml/9063/workflows/40e756f5-fa66-4ffa-9f60-5ffeb96f121e). To resolve this we will simply create an empty passing check for percy in the event that visual-diff tests are run without being needed.

❄️  🏗  🐛  Add empty passing check to visual-diff tests when they are not needed

---

.eslintrc.js
build-system/eslint-rules/no-private-props.js
src/.eslintrc.js
src/base-element.js

Fixes several post merge nits were added in #34376

Fix nits in #34376

---

.github/ISSUE_TEMPLATE/bug-report.yml

Addresses https://github.com/ampproject/amphtml/pull/34393#discussion_r632754118
**New Screenshot:**

📖 Expand AMP issue template intro text

---

ads/google/a4a/traffic-experiments.js
build-system/tasks/check-types.js
build-system/test-configs/conformance-config.textproto
build-system/test-configs/dep-check-config.js
build-system/test-configs/forbidden-terms.js
extensions/amp-analytics/0.1/test/test-analytics-group.js
src/.eslintrc.js
src/examiner/examiner.js
src/experiments/experiments.extern.js
src/experiments/experiments.type.js
src/experiments/index.js
src/experiments/shame.extern.js
src/experiments/story-ad-auto-advance.js
src/experiments/story-ad-placements.js
test/unit/test-experiments.js

♻️ Enable passing type-checking on src/experiments and src/examiner

---

src/service/real-time-config/callout-vendors.js

✨ New feature: PubMatic OpenWrap to pass consent strings

PubMatic OpenWrap to pass consent strings

---

src/amp-story-player/amp-story-player-impl.js

While building my own player carousel experience I bumped into an issue:
If you configure the player to start on pause with `autoplay: false`, the next stories (after the current) won't play. This is because `play()` only plays the current story. Which means you'd need to call `player.play()` for each story on navigation for the player to continue playing the stories. This is a lot of work expected for publishers for a simple action.
Codewise, this is caused by this check on the `render_` promise, which blocks any story from becoming visible unless `this.autoplay_` is true. But `this.autoplay_` only has an initial value, which is only set at the time we read the configuration. 
https://github.com/ampproject/amphtml/blob/514973222be683b9c8c210ac4a2a711b1986c60e/src/amp-story-player/amp-stor …

[amp-story-player] Persist playing state on play()/pause()

---

src/mode.js

Invisible merge conflict between #34372 and #34399

🐛 Fix invisible merge conflict

---

validator/js/nodejs/index.js
validator/js/nodejs/index_test.js

✨ Change default validator to WebAssembly in Node.js Package

---

src/service/resources-impl.js

Check if documentHeight has changed after all elements initially built

---

validator/js/nodejs/README.md
validator/js/nodejs/package.json

✨ Update npm amphtml-validator to v1.0.35

---

extensions/amp-render/1.0/amp-render.js
extensions/amp-render/1.0/component.js
src/layout.js

✨ [amp-render] support loading indicator and `no-loading` attribute

---

build-system/common/esbuild-babel.js
build-system/compile/closure-compile.js
build-system/compile/compile.js
build-system/compile/debug-compilation-lifecycle.js
build-system/compile/post-closure-babel.js
build-system/global.d.ts
build-system/server/app.js
build-system/server/new-server/router.js
build-system/tasks/babel-plugin-tests.js
build-system/tasks/check-asserts.js
build-system/tasks/coverage-map/index.js
build-system/tasks/e2e/amp-driver.js
build-system/tasks/e2e/describes-e2e.js
build-system/tasks/e2e/e2e-types.js
build-system/tasks/e2e/expect.js
build-system/tasks/e2e/index.js
build-system/tasks/e2e/mocha-ci-reporter.js
build-system/tasks/e2e/mocha-custom-json-reporter.js
build-system/tasks/e2e/selenium-webdriver-controller.js
build-system/tasks/extension-helpers.js
build-system/tasks/helpers.js
build-system/tasks/release/index.js
build-system/tasks/server-tests.js
build-system/tsconfig.json
package-lock.json
package.json

Prior to this change there were 99 type errors, assuming no more are introduce prior to this being merged there will only be one after. The remaining issue is quite complicated and I plan to fix it as a separate PR.
#28387

🏗  ♻️  Fix ALMOST all type issues in /build-system

---

build-system/tasks/check-build-system.js

🏗  Update build-system subpackages before checking types

---

extensions/amp-story/1.0/amp-story-open-page-attachment.js
extensions/amp-story/1.0/amp-story-page-attachment.js

Fixes attachment link regression.

🐛 [Amp story] [Page attachments] [Outlink] Open remote from light dom

---

build-system/global-configs/prod-config.json

We have been running at 10% for a few weeks and it is looking fine.

Ramp up 3p vendor splitting to 50%

---

extensions/amp-render/1.0/test/validator-amp-render.html
extensions/amp-render/1.0/test/validator-amp-render.out
extensions/amp-render/validator-amp-render.protoascii

✨  [amp-render] validator changes

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Launch `flexible-bitrate` experiment to 10%.

Launch flexible-bitrate experiment to 10%.

---

build-system/pr-check/build-targets.js
build-system/pr-check/checks.js
build-system/tasks/e2e/expect.js
build-system/tasks/e2e/selenium-webdriver-controller.js
build-system/tasks/pr-check.js
build-system/tsconfig.json

Now that we have gotten the number of type errors in `build-system` down to **0** it is time to prevent new type errors from being added by running the task to `pr-checks`
When introducing a type error you should be presented with a message like this:

🏗  Add check-build-system to pr-checks

---

extensions/amp-fit-text/1.0/test/test-amp-fit-text.js

There are existing unit tests for the Preact layer; this PR introduces unit tests for the AMP layer. Related to #28281

✅ Unit tests for amp-fit-text:1.0

---

build-system/npm-publish/write-package-jsons.js

Get changes from #34528
Next step when verified is to delete individual package.jsons

🏗  Update bento package.json template

---

extensions/amp-story/1.0/amp-story-page.js
extensions/amp-story/1.0/page-advancement.js
extensions/amp-story/1.0/test/test-page-advancement.js

Re-introducing code from https://github.com/ampproject/amphtml/pull/34354 and adding unit tests.
Fixes https://github.com/ampproject/amphtml/issues/34597

Fix time based auto-advance-after.

---

build-system/compile/bundles.config.extensions.json

Add missing bundles entry for amp-iframely

---

validator/js/engine/htmlparser-interface.js

[Validator Rollup] cl/376003218 Fix a bug in identifying amp cache domain

---

extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js

Per conversation with @calebcordry.

❄️ Skipping failing test on main

---

validator/validator-main.protoascii

cl/376942095 Update spec_file_revision comment.

Validator Rollup: cl/376942095 Update spec_file_revision comment.

---

extensions/amp-render/1.0/test/validator-amp-render.html
extensions/amp-render/1.0/test/validator-amp-render.out
extensions/amp-render/validator-amp-render.protoascii

validation changes for binding="never"

---

examples/sticky.ads.amp.html
extensions/amp-ad/0.1/amp-ad-ui.js
extensions/amp-ad/0.1/amp-ad.css
extensions/amp-ad/0.1/test/test-amp-ad-ui.js

This permits `<amp-ad sticky=top` to work properly. No experiment gating is necessary since we did not officially allow this on the validator yet.

Top sticky ad implementation

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.168

---

build-system/tasks/e2e/e2e-types.js
build-system/tasks/e2e/selenium-webdriver-controller.js
extensions/amp-form/0.1/test-e2e/test-custom-validation-reporting.js
test/fixtures/e2e/amp-form/custom-validation-reporting.html

Adds test case related to #34641, which should fail with a rollforward.
_(Redo of #34679 since I messed up my previous branch.)_

✅ Add e2e test for `form[custom-validation-reporting="as-you-go"]`

---

OWNERS

Context: https://github.com/ampproject/amphtml/pull/34676#issuecomment-854039159
This now passes the schema check.

🏗 Fix bot account name for owners check

---

extensions/amp-access/0.1/test/test-amp-access-server-jwt.js
extensions/amp-story/1.0/test/test-animation.js

These tests are frequently failing during CI:

❄️ Skip a few flaky tests

---

build-system/compile/bundles.config.extensions.json
build-system/tasks/make-extension/index.js
build-system/tasks/make-extension/test/test.js

🏗 Extension generator inserts in order: `name`, `version`, `latestVersion`

---

extensions/amp-analytics/0.1/test/vendor-requests.json
extensions/amp-analytics/0.1/vendors/top100.json

♻️ [amp-analytics] We want to add url param to our config and change ruid on tid

Change top100 config for amp-analytics

---

build-system/global-configs/canary-config.json
build-system/global-configs/prod-config.json

Launch `flexible-bitrate` experiment to 90%.

Launch flexible_bitrate experiment to 50%.

---

build-system/server/app-utils.js

Cached pages use `.mjs`. Matching it locally allows us to use the **Load by URL Proxy**.

🏗♻️ Allow rewriting `.mjs` CDN files on local mode

---

.github/ISSUE_TEMPLATE/bento-component-tracker.yml

📖 Create a yaml issue template for a Bento component tracker

---

extensions/amp-smartlinks/amp-smartlinks.md

Failed in Circle CI run for #34766: https://app.circleci.com/pipelines/github/ampproject/amphtml/10861/workflows/99440ff1-e11a-4f58-9c67-a3c75a19032d/jobs/170706
Please advise if a different link would be better here.

📖 Update dead link for amp-smartlink

---

build-system/externs/amp.extern.js
build-system/tasks/check-types.js
build-system/test-configs/forbidden-terms.js
src/experiments/experiments.extern.js
src/experiments/index.js
src/experiments/shame.extern.js
test/unit/test-experiments.js

✨🧪 Use injected AMP_EXP to toggle experiments

---

build-system/server/app-utils.js
build-system/server/app.js
build-system/server/new-server/transforms/utilities/cdn.ts
build-system/server/test/app-utils.test.js
build-system/server/typescript-compile.js
build-system/tasks/pr-deploy-bot-utils.js
examples/viewer-iframe-poll.html
examples/viewer-webview.html
examples/viewer.html
test/fixtures/e2e/amp-viewer-integration/viewer.html
test/manual/accessibility/aria-propagation.amp.html
test/manual/amp-install-serviceworker.amp.html

Removes duplicate implementation. Also now supports some renamed binaries which were not mapped on the removed implementation.

🏗♻️ Use new server's URL replacement scheme on old server

---

build-system/externs/amp.extern.js
build-system/tasks/check-types.js
build-system/test-configs/forbidden-terms.js
src/experiments/experiments.extern.js
src/experiments/shame.extern.js

Moves new externs for experiments into `src/experiments/experiments.extern.js` and removes typecheck dependency on `build-system/externs/amp.extern.js`

🏗 Don't pull all externs into experiments

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.169

---

extensions/amp-render/amp-render.md

📖 [amp-render] minor doc updates and fix broken links

---

build-system/babel-config/import-resolver.js
build-system/tasks/storybook/amp-env/webpack.config.js
build-system/tasks/storybook/preact-env/webpack.config.js
builtins/storybook/amp-layout-with-aspect-ratio-css.amp.js
builtins/storybook/amp-layout.amp.js

🏗 Add alias support to storybook webpack configs

---

build-system/tasks/make-extension/index.js

`amp make-extension --bento` now adds property to bundle config like in #34838

🏗 Set `wrapper: "bento"` in generated extension bundle

---

build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/amp-__component_name_hyphenated__.js
build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/base-element.js
build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/component.js
build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.js
build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/test/test-amp-__component_name_hyphenated__.js
build-system/tasks/make-extension/template/classic/extensions/amp-__component_name_hyphenated__/__component_version__/test/test-amp-__component_name_hyphenated__.js
build-system/tasks/make-extension/template/shared/extensions/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.amp.js

🏗 Use aliased paths in generated extensions

---

src/.eslintrc.js

Its layout and dom helpers have been core-ified:

🏗 Remove cleaned up file from allowlist

---

build-system/server/app-index/main.css
build-system/server/app-index/template.js

- Updated the shade of AMP blue. It was too bright on the file list specifically, so we're using it only as hover color there.
- Made some size adjustments as well.

🖍 AMP blue in app-index

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.170

---

tsconfig.json

🏗 Exclude node_modules in tsconfig.json

---

test/visual-diff/visual-tests

More descriptive name for visual test and new test for small square screen.

✅ `amp-story-desktop-one-panel` Rename visual test and new test for small square screen

---

.github/workflows/update-session-issues.yml
build-system/common/update-session-issues/index.js
build-system/common/update-session-issues/template/design-review.js
build-system/common/update-session-issues/types.js
build-system/test-configs/forbidden-terms.js

Extracts Design Review template so that the tool can create multiple types of session. This is in preparation of automated Office Hours issues.

🏗♻️ Refactor issue scheduling to use templates

---

validator/testdata/feature_tests/lts_extension_without_lts_runtime.html
validator/testdata/feature_tests/lts_extension_without_lts_runtime.out
validator/testdata/feature_tests/lts_runtime_and_extensions.html
validator/testdata/feature_tests/lts_runtime_and_extensions.out

minor clean up of unnecessary comments.

validator test, update comments

---

src/core/mode/local-dev.js
src/core/mode/test.js

♻️ Allow mode.isLocalDev(win) param to be optional

---

extensions/amp-story/1.0/amp-story-desktop-one-panel.css
extensions/amp-story/1.0/pagination-buttons.css

Context / fixes #34762
Adds pagination buttons with RTL support.
[Demo](https://stamp-ui.web.app/examples/amp-story/amp-story-desktop-one-panel.html)

✨ `amp-story-desktop-one-panel` Position pagination buttons

---

build-system/test-configs/conformance-config.textproto
extensions/amp-list/0.1/amp-list.js
validator/cpp/engine/parse-layout.cc
validator/cpp/engine/parse-layout.h
validator/validator.pb.go
validator/validator.proto

📖 Update outdated comments referencing moved file

---

build-system/global-configs/prod-config.json

It has stayed in 50% for a few weeks and has been complaint-free.

🧪 Launch 3p-vendor-split experiment

---

ads/vendors/ssp.js

Fixes inside 3P ssp.js module includes:
- forced reflow for some dsp banners (otherwise is banner sometimes invisible)

🐛♻️ external dsp visibility fix (pubmatic2)

---

docs/building-a-bento-video-player.md

📖 Building a Bento Video Player docs: Update import paths

---

extensions/amp-render/1.0/test/validator-amp-render.html
extensions/amp-render/1.0/test/validator-amp-render.out
extensions/amp-render/validator-amp-render.protoascii
validator/js/nodejs/package-lock.json

✨ [amp-render] validation changes for layout="container"

---

build-system/compile/OWNERS

Add @ampproject/wg-stories to `build-system/` OWNERS.

Add wg-stories to build-system/ OWNERS.

---

validator/cpp/htmlparser/BUILD
validator/cpp/htmlparser/node.cc
validator/cpp/htmlparser/node.h
validator/cpp/htmlparser/parser.cc
validator/cpp/htmlparser/parser.h
validator/cpp/htmlparser/parser_test.cc
validator/cpp/htmlparser/strings.cc
validator/cpp/htmlparser/strings.h
validator/cpp/htmlparser/strings_test.cc
validator/cpp/htmlparser/token.h
validator/cpp/htmlparser/tokenizer.cc
validator/cpp/htmlparser/tokenizer.h
validator/cpp/htmlparser/tokenizer_test.cc

Reverts ampproject/amphtml#34999

Revert "Sync for validator/cpp/htmlparser"

---

extensions/amp-render/1.0/test/validator-amp-render.html
extensions/amp-render/1.0/test/validator-amp-render.out
extensions/amp-render/validator-amp-render.protoascii

🐛 [amp-render] add missing validation rule for `template` attribute

---

extensions/amp-fx-collection/0.1/test/integration/test-amp-fx-fade-in-scroll.js

CircleCI's Test Insights dashboard is working again and has provided us with more information on slow running tests.
[test_insights_6-18-21.pdf](https://github.com/ampproject/amphtml/files/6679391/test_insights_6-18-21.pdf)
Before:
After:

🚀 ✅ Speed up amp-fx-collection tests

---

build-system/global-configs/OWNERS
build-system/global-configs/README.md
build-system/global-configs/client-side-experiments-config.json

🧪 Add client-side experiments config file

---

build-system/pr-check/checks.js
build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/component.js
build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/test/test-amp-__component_name_hyphenated__.js
build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/test/test-component.js
build-system/tasks/make-extension/template/classic/extensions/amp-__component_name_hyphenated__/__component_version__/test/test-amp-__component_name_hyphenated__.js

- Use aliased import for test helper
- Add `test-component.js` template for Preact layer

Bento: Update test template in `amp make-extension`

---

validator/cpp/htmlparser/node.h
validator/cpp/htmlparser/parser.cc
validator/cpp/htmlparser/parser.h
validator/cpp/htmlparser/parser_test.cc
validator/cpp/htmlparser/strings.cc
validator/cpp/htmlparser/strings.h
validator/cpp/htmlparser/strings_test.cc
validator/cpp/htmlparser/token.h
validator/cpp/htmlparser/tokenizer.cc
validator/cpp/htmlparser/tokenizer.h

Sync for validator/cpp/htmlparser

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.172

---

src/core/mode/test.js
src/mode.js
test/unit/test-mode.js

🐛 Fix getMode().rtvVersion in testing

---

extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js

When this was moved to branch level experiment the test was not updated correctly and can fail if the control branch is randomly selected.

🐛[story-ads] Fix flaky system layer tests

---

src/url.js

♻️ Clean up `url.js` in preparation for core migration

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.173

---

extensions/amp-apester-media/0.1/amp-apester-media.js
extensions/amp-apester-media/0.1/monetization/companion/bottomAd.js
extensions/amp-apester-media/0.1/monetization/companion/video.js

🐛 Bug fixes for amp-apester-media: fix for height of video ad block; fix for loader logo position; fix for css style conflict

amp-apester-media fixes

---

extensions/amp-lightbox-gallery/1.0/amp-lightbox-gallery.js
extensions/amp-lightbox/1.0/amp-lightbox.js
extensions/amp-sidebar/1.0/amp-sidebar.js

Follow up to [this thread](https://github.com/ampproject/amphtml/pull/35102#discussion_r663082219) because #35102 was set to auto merge 😅

Bento: Call overridden method in `amp-lightbox-gallery`, `amp-lightbox`, `amp-sidebar`

---

extensions/amp-tiktok/0.1/test/test-amp-tiktok.js

This PR fixes the currently skipped amp-tiktok tests by short circuiting waits in the code.

✅ [`amp-tiktok`] Fix skipped amp-tiktok tests. 

---

extensions/amp-story/1.0/background-blur.js

Context / Fixes #35131
- Includes `amp-video` in selector
- Checks if video is loaded
- if loaded, draws pixels from first frame
- if not loaded, draws from poster image url
[demo](https://discovery-ec239.web.app/examples/amp-story/ampconf.html)

✨ `amp-story-desktop-one-panel` `background-blur` Use video or video poster in blur.

---

extensions/amp-video/0.1/test/test-video-cache.js
extensions/amp-video/0.1/video-cache.js

Track `video-cache` experiment through CSI.

Track video-cache experiment through CSI.

---

examples/amp-ad/sticky.html

We are updating to use sticky=bottom

Fix the sticky ad amp-ad example

---

examples/amp-ad/sticky.ads.amp.html

Add amp-ad sticky ads example page

---

extensions/amp-iframe/0.1/test/test-amp-iframe.js

This is causing the `main` build [to fail](https://app.circleci.com/pipelines/github/ampproject/amphtml/13129/workflows/e28d6e95-6c29-4f46-8aad-61d917db82dd/jobs/210622).
```
extensions/amp-iframe/0.1/test/test-amp-iframe.js
31:26  error  Unexpected use of file extension "js" for "../../../../testing/test-helper.js"  import/extensions
31:26  error  Do not use relative path for aliased modules                                    module-resolver/use-alias
```
Unsure why the original CI run for the PR did not catch this.

🐛 Use correct import path

---

extensions/amp-story-interactive/0.1/test/helpers.js
extensions/amp-story-interactive/0.1/test/test-amp-story-interactive-binary-poll.js
extensions/amp-story-interactive/0.1/test/test-amp-story-interactive-img-poll.js
extensions/amp-story-interactive/0.1/test/test-amp-story-interactive-img-quiz.js
extensions/amp-story-interactive/0.1/test/test-amp-story-interactive-poll.js
extensions/amp-story-interactive/0.1/test/test-amp-story-interactive-quiz.js
extensions/amp-story-interactive/0.1/test/test-amp-story-interactive-results.js
extensions/amp-story-interactive/0.1/test/test-amp-story-interactive.js

✅ Split test-amp-story-interactive-* test files to not recursively include the base test-amp-story-interactive tests in them

---

test/unit/test-3p.js

See https://app.circleci.com/pipelines/github/ampproject/amphtml/13248/workflows/8e8ebe83-d950-45c1-b2df-bc91c76be6da/jobs/212866

❄️ Disable flaky test 3p > loadScript > should handle onSuccess callback

---

extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js
extensions/amp-script/0.1/amp-script.js
src/3p-frame.js
src/error-reporting.js
src/log.js
src/mode-object.js
src/mode.js
src/runtime.js
test/unit/3p/test-3p-frame.js
test/unit/test-fixed-layer.js

**summary**
Removes the `minified` key from the Mode object.

♻️  getMode(): remove .minified

---

src/amp.js

Small change to improve readability and match our coding style.

♻️ Convert ESM output to early return

---

extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js

No longer needed to experiment, for being running long enough.

🧪 Clean up module/nomodule experiment

---

ads/_config.js

✨Enable renderStart API for Ezoic

---

examples/standard-actions.amp.html

📖 Add missing `</body>` closing tag

---

extensions/amp-list/0.1/test/test-amp-list.js

e.g., https://app.circleci.com/pipelines/github/ampproject/amphtml/13438/workflows/ec604a2b-dc97-4f75-a23c-4a827514d8bc/jobs/218126

❄️ Skip flaky amp-list tests

---

3p/remote.html

Missing `vendor/` in the path.

Fix the URL in remote.html example

---

extensions/amp-ad/0.1/amp-ad.css

🖍 Enforce top/bottom sticky ad size limit

---

extensions/amp-a4a/0.1/amp-a4a.js
extensions/amp-a4a/0.1/secure-frame.js
extensions/amp-a4a/0.1/test/test-amp-a4a.js

Should cover 
- nameframe
- safeframe
- iframe get
Partial https://github.com/ampproject/amphtml/issues/35347

✨[a4a] Set `attribution-reporting` feature policy in 3p fallback

---

ads/google/a4a/test/test-utils.js
ads/google/a4a/utils.js
build-system/externs/amp.extern.js
build-system/test-configs/dep-check-config.js
extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js

✨[google ads] insert origin trial token when extension is used

---

src/service/performance-impl.js

Record google-font experiment

---

extensions/amp-consent/amp-consent.md

1. Update snippet to valid JSON
2. Update some wording
3. Unrelated: Fixes `AppConsent` website URL in order to pass `check-links` with this change.

📖  Update`<amp-consent>` `policy` configuration snippet

---

build-system/compile/bundles.config.extensions.json
extensions/amp-story-interactive/0.1/amp-story-interactive-results-detailed.css
extensions/amp-story-interactive/0.1/amp-story-interactive-results-detailed.js
extensions/amp-story-interactive/0.1/amp-story-interactive.js

Updated `bundles.config.extensions`; set up and registered empty component
New component is named `amp-story-interactive-results-detailed` temporarily but will likely be changed in the future
/cc @mszylkowski 
/cc @processprocess

✨ [Story interactive] Scaffolding for New Results Component

---

.circleci/restore_build_output.sh
build-system/pr-check/utils.js

Required before merging #35295

🏗 Store compiled Bento components between CircleCI jobs

---

examples/amp-story/interactive_img_polls.html
examples/amp-story/interactive_img_quizzes.html

Add pages with results components to the example stories for image quizzes and polls to test that the results component correctly summarizes image quizzes and polls
Demos (see last page):
https://interactive-img.web.app/results/quiz.html
https://interactive-img.web.app/results/poll.html
/cc @mszylkowski 
/cc @processprocess

✅ [Story interactive] Test Results Integration for Image Quizzes and Polls

---

extensions/amp-iframe/0.1/amp-iframe.js

`clickToPlay` is misleading as it involves no clicking.

♻️  [amp-iframe] rename `clickToPlay` to `hasPlaceholder`

---

extensions/amp-story/1.0/amp-story.js

Add a missing period to a comment in amp-story.js.

📖 Add missing period to comment

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-button.css
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.177

---

extensions/amp-lightbox-gallery/1.0/test/validator-amp-lightbox-gallery.html
extensions/amp-lightbox-gallery/1.0/test/validator-amp-lightbox-gallery.out
extensions/amp-lightbox-gallery/validator-amp-lightbox-gallery.protoascii

Add validations for amp-lightbox-gallery:1.0

---

ads/google/a4a/utils.js

https://github.com/ampproject/amphtml/pull/35368#discussion_r675910948

🏎 [a4a] Scope origin trial querySelector to head

---

docs/spec/amp-actions-and-events.md

Add documentation for the new `navigate` param. Last step before closing https://github.com/ampproject/amphtml/issues/5225

AMP.goBack: update documentation

---

validator/js/nodejs/index.js

When building my project with Rollup, I get the warning:
> default imported from external module 'url' but never used
> default imported from external module 'querystring' but never used

♻️ Remove unused imports

---

build-system/global-configs/client-side-experiments-config.json

https://github.com/ampproject/amphtml/issues/30659

Ramp up amp-sticky-ad-to-amp-ad to 5%

---

test/manual/amp-consent/amp-consent-granular-consent.html

I should have done this as part of #35508
Also formatted file, and removed unused extension script.

🚮 Remove unnecessary experiment toggle

---

build-system/global-configs/client-side-experiments-config.json

Reverts ampproject/amphtml#35510
We have got one day of data, and it is enough to diagnose the problem.

Revert "Ramp up amp-sticky-ad-to-amp-ad to 5%"

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.178

---

extensions/amp-anim/amp-anim.md

📖 Update `amp-anim` styling documentation

---

examples/dailymotion.amp.html

Currently the amp-dailymotion autoplay example is disabled pending an update to the validator. This PR reenables it.

📖 [`amp-dailymotion`] Update examples to include autoplay example.

---

build-system/global-configs/canary-config.json
build-system/global-configs/client-side-experiments-config.json
build-system/global-configs/prod-config.json

🚀 [Story performance] Added load outside viewport to experiments

---

build-system/babel-plugins/babel-plugin-amp-mode-transformer/index.js
build-system/babel-plugins/babel-plugin-const-transformer/index.js
build-system/babel-plugins/babel-plugin-imported-helpers/index.js
build-system/babel-plugins/babel-plugin-transform-amp-asserts/index.js
build-system/babel-plugins/babel-plugin-transform-amp-extension-call/index.js
build-system/babel-plugins/babel-plugin-transform-annotation-to-extern/index.js
build-system/babel-plugins/babel-plugin-transform-default-assignment/index.js
build-system/babel-plugins/babel-plugin-transform-dev-methods/index.js
build-system/babel-plugins/babel-plugin-transform-fix-leading-comments/index.js
build-system/babel-plugins/babel-plugin-transform-function-declarations/index.js
build-system/babel-plugins/babel-plugin-transform-html-template/index.js
build-system/babel-plugins/babel-plugin-transform-inline-isenumvalue/index.js
build-system/babel-plugins/babel-plugin-transform-json-configuration/index.js
build-system/babel-plugins/babel-plugin-transform-json-import/index.js
build-system/babel-plugins/babel-plugin-transform-jss/index.js
build-system/babel-plugins/babel-plugin-transform-log-methods/index.js
build-system/babel-plugins/babel-plugin-transform-minified-comments/index.js
build-system/babel-plugins/babel-plugin-transform-parenthesize-expression/index.js
build-system/babel-plugins/babel-plugin-transform-promise-resolve/index.js
build-system/babel-plugins/babel-plugin-transform-prune-namespace/index.js
build-system/babel-plugins/babel-plugin-transform-remove-directives/index.js
build-system/babel-plugins/babel-plugin-transform-simple-array-destructure/index.js
build-system/babel-plugins/babel-plugin-transform-stringish-literals/index.js
build-system/babel-plugins/log-module-metadata.js
build-system/babel-plugins/static-template-metadata.js
build-system/tsconfig.json

First step towards https://github.com/ampproject/amphtml/issues/35573

enable typechecking for the babel-plugin directory

---

build-system/babel-plugins/babel-plugin-transform-simple-array-destructure/index.js

Partial for https://github.com/ampproject/amphtml/issues/35573
~~Blocked by https://github.com/ampproject/amphtml/pull/35574~~

typecheck babel plugin: simple array destructure

---

build-system/test-configs/dep-check-config.js

Related to https://github.com/ampproject/amphtml/issues/32693

🏗 Allow #core imports in dep-check-config

---

.github/workflows/status-page.yml
build-system/status-page/comment.js
build-system/status-page/incident.js

Move `issue.body` and `comment.body` input fields to env vars

🏗  Use more env vars for status page GitHub Action

---

build-system/babel-plugins/babel-plugin-transform-remove-directives/index.js

Partial for https://github.com/ampproject/amphtml/issues/35573

typecheck babel plugin: remove directive

---

build-system/babel-plugins/babel-plugin-transform-promise-resolve/index.js

**summary**
Partial for https://github.com/ampproject/amphtml/issues/35573

typecheck babel plugins: promise-resolve

---

testing/async-errors.js
testing/console-logging-setup.js

Re: https://github.com/ampproject/amphtml/pull/35563

🏗️  Integrate expectAsyncConsoleError with rethrowAsync

---

examples/analytics-vendors.amp.html
extensions/amp-analytics/0.1/test/vendor-requests.json
extensions/amp-analytics/0.1/vendors/OWNERS
extensions/amp-analytics/0.1/vendors/appsflyer.json
extensions/amp-analytics/analytics-vendors-list.md

We would like to propose an analytics solution for our customers which supports AMP pages.
We would like to be added to the analytics vendors list.
Closes #35218
I2I #35218
Added an OWNERS file as suggested by this issue #35200

add AppsFlyer as amp-analytics vendor

---

build-system/babel-plugins/babel-plugin-const-transformer/index.js
build-system/babel-plugins/babel-plugin-imported-helpers/index.js
build-system/babel-plugins/babel-plugin-transform-annotation-to-extern/index.js
build-system/babel-plugins/babel-plugin-transform-default-assignment/index.js
build-system/babel-plugins/babel-plugin-transform-dev-methods/index.js
build-system/babel-plugins/babel-plugin-transform-fix-leading-comments/index.js
build-system/babel-plugins/babel-plugin-transform-json-import/index.js
build-system/babel-plugins/babel-plugin-transform-minified-comments/index.js
build-system/babel-plugins/babel-plugin-transform-parenthesize-expression/index.js
build-system/global.d.ts

partial for https://github.com/ampproject/amphtml/issues/35573

typecheck the easy babel plugins

---

src/core/error/error.extern.js
src/core/error/index.js
src/log.js
test/unit/core/test-error.js
testing/async-errors.js

Part of #32693
Does not yet update call-sites outside of `log.js`

♻️ #core: error helpers

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.179

---

build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/nomodule/input.js
build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/nomodule/output.mjs
build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/transform/input.js
build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/transform/output.mjs
extensions/amp-script/0.1/amp-script.js
src/mode-object.js
src/mode.js
test/unit/3p/test-3p-frame.js

♻️  Remove `version` from legacy mode object

---

extensions/amp-a4a/0.1/amp-a4a.js
src/core/types/string/url.js
src/log.js
src/mode-object.js
src/mode.js
src/service/url-replacements-impl.js
src/validator-integration.js
test/unit/core/types/string/test-url.js
test/unit/test-log.js

It's only used in `log.js`, so we move the parsing etc. there.

♻️ Define helper for hash params and drop barely-used `getMode().log`

---

extensions/amp-geo/0.1/amp-geo.js
extensions/amp-geo/0.1/test/test-amp-geo.js
src/mode.js

Moves it to `amp-geo`, its only usage.

♻️ Remove geoOverride from mode

---

build-system/babel-plugins/babel-plugin-transform-stringish-literals/index.js

babel-plugin stringish literal: attack of the automerge

---

extensions/amp-story/1.0/amp-story-store-service.js
extensions/amp-story/1.0/amp-story-system-layer.js
extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/embed-mode.js
extensions/amp-story/1.0/test/test-utils.js
extensions/amp-story/1.0/utils.js

Hide Story URL info for embedMode=4.

Embed mode url info

---

build-system/global-configs/client-side-experiments-config.json

Launch amp-story-first-page-max-bitrate to 30%.

Launch amp-story-first-page-max-bitrate exp to 30%.

---

docs/spec/amp-var-substitutions.md
extensions/amp-analytics/0.1/default-config.js
src/service/url-replacements-impl.js
test/unit/test-url-replacements.js

Proposal https://github.com/ampproject/amphtml/issues/35626

Add user agent client hint parameters for url-replacement and amp-analytics

---

extensions/amp-ad-network-valueimpression-impl/0.1/amp-ad-network-valueimpression-impl.js
extensions/amp-ad-network-valueimpression-impl/0.1/flexible-ad-slot-utils.js
extensions/amp-ad-network-valueimpression-impl/0.1/test/test-amp-ad-network-valueimpression-impl.js
extensions/amp-ad-network-valueimpression-impl/0.1/test/test-flexible-ad-slot-utils.js
extensions/import-order-excluded.json

Group sorting amp-ad-network-valueimpression

---

build-system/release-tagger/create-release.js
build-system/release-tagger/test/create-release.test.js
build-system/release-tagger/utils.js

Example cherry pick header:
<h2>🌸 Cherry-picked release 🌸  </h2>
<a href="https://github.com/ampproject/amphtml/releases/tag/2107302322000">2107302322000</a> was patched and published as <b>2107302322001</b>. Refer to the <a href="https://amp-release-calendar.appspot.com/">release calendar</a> for additional channel information.

🏗  Create cherry-pick release notes for the release tagger

---

build-system/server/typescript-compile.js
build-system/tasks/analytics-vendor-configs.js
build-system/tasks/bundle-size/index.js
build-system/tasks/check-exact-versions.js
build-system/tasks/compile-jison.js
build-system/tasks/css/index.js
build-system/tasks/dist.js
build-system/tasks/get-zindex/index.js
build-system/tasks/markdown-toc/index.js
build-system/tasks/markdown-toc/test/test.js
build-system/tasks/presubmit.js
build-system/tasks/server-tests.js

Addresses https://github.com/ampproject/amphtml/pull/35713#discussion_r691417366

🏗 Use asynchronous `globby` API wherever possible

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-button.css
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.180

---

extensions/amp-link-rewriter/amp-link-rewriter.md

Documentation for new feature supporting AMP Geo information in URL rewriting.

📖 AMP Geo for URL Rewriting

---

extensions/amp-consent/0.1/test/test-consent-config.js

A PR was merged without passing "Checks". We need to investigate how this was not caught but it appears to be something about the PRs head.
#35582

❄️  Fix check failure

---

extensions/amp-stream-gallery/validator-amp-stream-gallery.protoascii
extensions/amp-wordpress-embed/validator-amp-wordpress-embed.protoascii

Covers
- amp-stream-gallery
- amp-wordpress-embed

Add latest to bento_supported_version

---

build-system/global-configs/canary-config.json
build-system/global-configs/client-side-experiments-config.json
build-system/global-configs/prod-config.json

Setting experiment to 50% to client side experiments and canary/prod

🚀 [Story performance] Set "load first page only" experiment to 50%

---

build-system/compile/bundles.config.extensions.json

Bento component `options` should specify `wrapper` not `wrappers`

---

extensions/amp-story/amp-story-page-attachment.md
extensions/amp-story/amp-story-page-outlink.md

🐛[Amp story] page-attachment and page-outlink docs links fix

---

docs/developing.md

📖 Remove IE11 support from supported browsers

---

extensions/amp-analytics/0.1/test/test-iframe-transport-client.js
extensions/amp-pan-zoom/0.1/test/test-amp-pan-zoom.js
extensions/amp-viewer-integration/0.1/test/test-highlight-handler.js
test/unit/test-amp-context.js

Partial for https://github.com/ampproject/amphtml/issues/35898

Skip new test failures after Chrome93 release

---

build-system/compile/sources.js
build-system/test-configs/dep-check-config.js
extensions/amp-date-display/0.1/amp-date-display.js
extensions/amp-date-display/0.1/amp-date-display.md
extensions/amp-date-display/0.1/test/test-amp-date-display.js
extensions/amp-date-display/1.0/component.js
extensions/amp-date-display/1.0/test/test-amp-date-display.js
extensions/amp-date-display/1.0/test/test-component.js
extensions/amp-date-display/amp-date-display.md
extensions/amp-date-display/format.js

This reverts commit 017c5a84a0df37610c4cad6c2c4c0a717b7134f2.

Revert "⏮ Rollback `timeZoneName` changes (#35895)"

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.182

---

build-system/test-configs/forbidden-terms.js
src/core/context/node.js
src/core/dom/layout/viewport-observer.js
src/core/mode/index.js
src/core/mode/local-dev.js
src/core/mode/test.js
src/mode.js
src/preact/base-element.js
src/service/extension-script.js
src/video-iframe-integration.js
test/unit/core/window/test-history.js
test/unit/test-runtime.js
test/unit/test-viewport.js

Reverts ampproject/amphtml#35823

Revert "mode: collapse definitions of localDev and test"

---

validator/js/engine/parse-css.js
validator/js/engine/parse-css_test.js
validator/testdata/feature_tests/media_expression_calc.html
validator/testdata/feature_tests/media_expression_calc.out

- cl/394490119 Fix a bug where the CSS parser was not correctly accounting for the possibility of calc() in the media expression.

cl/394490119 Fix a bug where the CSS parser was not correctly accounting for the possibility of calc() in the media expression.

---

extensions/amp-base-carousel/1.0/arrow.js
extensions/amp-base-carousel/1.0/base-element.js
extensions/amp-base-carousel/1.0/carousel-context.js
extensions/amp-base-carousel/1.0/component.js
extensions/amp-base-carousel/1.0/component.type.js
extensions/amp-base-carousel/1.0/storybook/Basic.js
extensions/amp-base-carousel/1.0/test/test-component.js
extensions/amp-inline-gallery/1.0/test/test-component.js
extensions/amp-inline-gallery/1.0/thumbnails.js
extensions/amp-lightbox-gallery/1.0/provider.js
extensions/amp-lightbox-gallery/1.0/test/test-component.js
extensions/amp-stream-gallery/1.0/component.js
extensions/amp-stream-gallery/1.0/test/test-component.js

Documentation covered in #35645.

Rename `BaseCarousel` as `BentoBaseCarousel`

---

extensions/amp-twitter/1.0/base-element.js
extensions/amp-twitter/1.0/component.js
extensions/amp-twitter/1.0/component.type.js
extensions/amp-twitter/1.0/storybook/Basic.js
extensions/amp-twitter/1.0/test/test-component.js

Documentation for `bento-twitter` is completed in #35847.

Rename `Twitter` to `BentoTwitter`

---

.github/workflows/release-tagger.yml

Remove condition because it exists in the caller and receiver

🏗 Update release-tagger.yml

---

ads/vendors/ssp.js
ads/vendors/ssp.md
test/unit/ads/test-ssp.js

3P ssp.js module now supports `data-said` param in <amp-ad /> tag

✨ Ssp params extended

---

extensions/amp-inline-gallery/1.0/storybook/Basic.js
extensions/amp-lightbox-gallery/1.0/storybook/Basic.js

PR #35935 missed two `BaseCarousel`→`BentoBaseCarousel` renames, which are causing the `Checks` job on `main` branch CircleCI to fail: https://app.circleci.com/pipelines/github/ampproject/amphtml/15953/workflows/b28786ee-04d3-494d-b839-ec91cda39fd4/jobs/281461

🐛 Followup fix from BaseCarousel → BentoBaseCarousel rename

---

extensions/amp-timeago/1.0/base-element.js
extensions/amp-timeago/1.0/component.js
extensions/amp-timeago/1.0/component.type.js
extensions/amp-timeago/1.0/storybook/Basic.js
extensions/amp-timeago/1.0/test/test-component.js

Documentation completed in #32244

Rename `Timeago` to `BentoTimeago`

---

build-system/release-tagger/make-release.js
build-system/release-tagger/test/make-release.test.js
build-system/release-tagger/utils.js

🏗  Fix `make release` bug for release tagger

---

build-system/global-configs/canary-config.json
build-system/global-configs/client-side-experiments-config.json
build-system/global-configs/prod-config.json

🚀 [Story performance] Set `load first page only` experiment to 1

---

validator/build.py
validator/js/nodejs/index.js
validator/js/nodejs/index_test.js

Clean up some small linter issues with validator files.

---

extensions/amp-instagram/1.0/base-element.js
extensions/amp-instagram/1.0/component.js
extensions/amp-instagram/1.0/component.type.js
extensions/amp-instagram/1.0/storybook/Basic.js
extensions/amp-instagram/1.0/test/test-component.js

Documentation completed in #32244

Rename `Instagram` to `BentoInstagram`

---

extensions/amp-embedly-card/1.0/base-element.js
extensions/amp-embedly-card/1.0/component.js
extensions/amp-embedly-card/1.0/component.type.js
extensions/amp-embedly-card/1.0/embedly-context.js
extensions/amp-embedly-card/1.0/storybook/Basic.js

Rename `EmbedlyCard` as `BentoEmbedlyCard`

---

extensions/amp-brightcove/1.0/base-element.js
extensions/amp-brightcove/1.0/component.js
extensions/amp-brightcove/1.0/storybook/Basic.js
extensions/amp-brightcove/1.0/test/test-component.js

♻️ Rename `Brightcove` to `BentoBrightcove`

---

extensions/amp-video/1.0/base-element.js
extensions/amp-video/1.0/component.js
extensions/amp-video/1.0/storybook/Basic.js

♻️ Provide BentoVideo

---

extensions/amp-vimeo/1.0/base-element.js
extensions/amp-vimeo/1.0/component.js
extensions/amp-vimeo/1.0/storybook/Basic.js

♻️ Rename `Vimeo` to `BentoVimeo`

---

extensions/amp-youtube/1.0/base-element.js
extensions/amp-youtube/1.0/component.js
extensions/amp-youtube/1.0/storybook/Basic.js
extensions/amp-youtube/1.0/test/test-component.js

♻️ Rename `Youtube` to `BentoYoutube`

---

validator/README.md

📖 Add instructions to reproduce validator tests

---

extensions/amp-inline-gallery/1.0/README.md

docs(amp-inline-gallery): add README for bento component

---

extensions/amp-video-iframe/1.0/base-element.js
extensions/amp-video-iframe/1.0/component.js

♻️ Rename `VideoIframe` to `BentoVideoIframe`

---

ads/google/a4a/utils.js

I was using the OT token for the wrong domain :(

🐛 Update attribution-reporting token value

---

extensions/amp-wordpress-embed/1.0/base-element.js
extensions/amp-wordpress-embed/1.0/component.js
extensions/amp-wordpress-embed/1.0/component.type.js
extensions/amp-wordpress-embed/1.0/storybook/Basic.js

Rename `WordPressEmbed` to `BentoWordPressEmbed`

---

extensions/amp-base-carousel/1.0/README.md

Updating existing docs following #35935

Documentation: `BaseCarousel` should be `BentoBaseCarousel`

---

extensions/amp-accordion/1.0/README.md
extensions/amp-inline-gallery/1.0/README.md
extensions/amp-stream-gallery/1.0/README.md

Adds readme for bento component

📖 docs(amp-stream-gallery): add README for bento component

---

ads/vendors/trafficstars.js

Fix ads vendor TrafficStars integration script

🐛 Fix TrafficStars integration

---

extensions/amp-accordion/1.0/README.md
extensions/amp-date-countdown/1.0/README.md
extensions/amp-date-display/1.0/README.md
extensions/amp-inline-gallery/1.0/README.md
extensions/amp-stream-gallery/1.0/README.md

adds readme for bento component 
continues: https://github.com/ampproject/amphtml/pull/35875 and #35874

📖 docs(amp-date-display): add README for bento component

---

extensions/amp-lightbox-gallery/1.0/provider.js
extensions/amp-lightbox/1.0/base-element.js
extensions/amp-lightbox/1.0/component.js
extensions/amp-lightbox/1.0/component.type.js
extensions/amp-lightbox/1.0/storybook/Basic.js
extensions/amp-lightbox/1.0/test/test-component.js

Rename `Lightbox` to `BentoLightbox`

---

extensions/amp-iframe/1.0/component.js
extensions/amp-timeago/1.0/component.js
src/preact/storybook/Hooks.js
src/preact/utils.js

Carrying over from https://github.com/ampproject/amphtml/pull/35835#discussion_r705732157

`useMergeRefs` custom hook

---

build-system/release-workflows/cut-nightly.js

🏗 Remove DRY_RUN flag from nightly branch cut job

---

ads/README.md

Vendor splitting document update

---

validator/js/webui/@polymer/webui-mainpage/webui-mainpage.html
validator/testdata/amp4ads_feature_tests/min_valid_amp4ads.html
validator/testdata/amp4ads_feature_tests/min_valid_amp4ads.out
validator/testdata/amp4ads_feature_tests/min_valid_multiline_amp4ads.html
validator/testdata/amp4ads_feature_tests/min_valid_multiline_amp4ads.out
validator/testdata/amp4email_feature_tests/min_valid_amp4email.html
validator/testdata/amp4email_feature_tests/min_valid_amp4email.out
validator/testdata/feature_tests/minimum_valid_amp.html
validator/testdata/feature_tests/minimum_valid_amp.out
validator/testdata/transformed_feature_tests/minimum_valid_amp.html
validator/testdata/transformed_feature_tests/minimum_valid_amp.out

Update text to minimum valid JavaScript AMP

---

build-system/global-configs/client-side-experiments-config.json

We modified the experiment since the last time and hopefully this can give a better comparision.

🧪 amp-sticky-ad-to-amp-ad-v2 ramp up to 5%

---

examples/amp-script/export-functions.js
package-lock.json
package.json

Fixes  https://github.com/ampproject/amphtml/issues/35902

🐛 Bump worker dom, fixes storage access in sandbox

---

extensions/amp-viewer-integration/0.1/test/test-highlight-handler.js

fix test failures for Chrome 93

---

src/utils/xhr-utils.js

The new behavior was introduced in #27644.
/to @samouri @krdwan

📖 Add a blurb about how `init.body` can be a string

---

extensions/amp-story-interactive/amp-story-interactive.md

Adding the documentation for the info dialog so that backend owners can add the domains to the lookup file

📖 [Story interactives] Added docs for info dialog

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.185

---

build-system/global-configs/client-side-experiments-config.json
build-system/global-configs/prod-config.json

Created prod experiment to accompany the CTA migration page outlink layer
Part of #36035

🧪 Added story ad page outlink prod experiment at 2%

---

extensions/amp-sidebar/1.0/test/validator-amp-sidebar.html
extensions/amp-sidebar/1.0/test/validator-amp-sidebar.out
extensions/amp-sidebar/validator-amp-sidebar.protoascii

This is the last task of #31366 /to @ampproject/wg-caching

Add validator rules for 1.0 amp-sidebar

---

build-system/compile/bundles.config.extensions.json
extensions/amp-mathml/0.1/amp-mathml.md
extensions/amp-mathml/1.0/README.md
extensions/amp-mathml/1.0/amp-mathml.css
extensions/amp-mathml/1.0/amp-mathml.js
extensions/amp-mathml/1.0/base-element.js
extensions/amp-mathml/1.0/component.js
extensions/amp-mathml/1.0/component.jss.js
extensions/amp-mathml/1.0/component.type.js
extensions/amp-mathml/1.0/storybook/Basic.amp.js
extensions/amp-mathml/1.0/storybook/Basic.js
extensions/amp-mathml/1.0/test/test-amp-mathml.js
extensions/amp-mathml/1.0/test/test-component.js
extensions/amp-mathml/1.0/test/utils.js
extensions/amp-mathml/1.0/test/validator-amp-mathml.html
extensions/amp-mathml/1.0/test/validator-amp-mathml.out
extensions/amp-mathml/1.0/utils.js
extensions/amp-mathml/validator-amp-mathml.protoascii
test/unit/test-real-time-config.js

✨ Initial Bento mathml implementation

---

src/preact/component/intersection-observer.js

**summary**
Addresses small nit: https://github.com/ampproject/amphtml/pull/36106#discussion_r716964669

♻️  preact inob: small cleanup

---

ads/_config.js
ads/vendors/adfox.js
ads/vendors/yandex.js

Yandex updated ads codes:
- https://yandex.ru/adv/news/zagruzka-reklamy-na-sayte-stala-bystree-s-novymi-kodami-vstavki-blokov-rsya-i-adfox
- https://yandex.ru/support/adfox-sites/codes/change-code.html
- https://yandex.ru/support/partner2/web/products-rtb/partner-code.html#partner-code__new-code

🚀 [Ads] Update Yandex & ADFOX insert codes

---

extensions/amp-iframe/1.0/test/validator-amp-iframe.html
extensions/amp-iframe/1.0/test/validator-amp-iframe.out
extensions/amp-iframe/validator-amp-iframe.protoascii

✨  [bento][amp-iframe] Add validator rules for 1.0

---

package-lock.json
package.json

**summary**
Bumps bento-compiler version number, which includes mem-leak fixes and perf improvements.

deps: bump bento-compiler

---

src/builtins/amp-img/amp-img.js
test/unit/builtins/test-amp-img.js

Propagate importance for `amp-img` => `img`.

🚀 Propagate importance

---

extensions/amp-ad-network-dianomi-impl/OWNERS

✨Add OWNERS for Dianomi fast fetch impl

---

extensions/amp-call-tracking/amp-call-tracking.md

The current teaser text for amp-call-tracking specifies that it displays gltf 3d models. I have used the first sentence from the usage section.

📖 Updated wrong teaser text for amp-call-tracking extension

---

extensions/amp-video/0.1/test-e2e/test-amp-video-analytics.js

This test has been flaking recently and is currently our #1 and #2 flakiest test according to [CircleCI Insights](https://app.circleci.com/insights/github/ampproject/amphtml/workflows/CircleCI/tests?branch=main&reporting-window=last-30-days).
I'm hoping that increasing the wait time by 250ms smoothes this out.

❄️  ✅  Increase timeout for test-amp-video-analytics test

---

extensions/amp-facebook/1.0/README.md

📖 Remove unnecessary frontmatter from the bento facebook README.md

---

build-system/global-configs/client-side-experiments-config.json

We have obtained enough data for this experiment, ramping down.

🧪 Demote amp-sticky-ad-to-amp-ad-v3 experiment

---

src/service/real-time-config/callout-vendors.js

🖍 Sorting ad RTC vendor list

---

extensions/amp-video/0.1/amp-video.js

🐛 Only create poster element when attribute is provided

---

build-system/compile/bundles.config.extensions.json
extensions/amp-jwplayer/1.0/README.md
extensions/amp-jwplayer/1.0/amp-jwplayer.css
extensions/amp-jwplayer/1.0/amp-jwplayer.js
extensions/amp-jwplayer/1.0/base-element.js
extensions/amp-jwplayer/1.0/component.js
extensions/amp-jwplayer/1.0/component.type.js
extensions/amp-jwplayer/1.0/jwplayer-api.js
extensions/amp-jwplayer/1.0/storybook/Basic.amp.js
extensions/amp-jwplayer/1.0/storybook/Basic.js
extensions/amp-jwplayer/1.0/test/test-amp-jwplayer.js
extensions/amp-jwplayer/1.0/test/test-component.js
extensions/amp-video/1.0/video-iframe.js

✨ initial implementation of `bento-jwplayer`

---

test/e2e/test-bento.js

♻️ (bento): refactor test to use existing shadow root utilities

---

build-system/npm-publish/write-package-files.js
package-lock.json
package.json

Fixes #36655. This gets us some very good defaults:
---
> The Bento Accordion component allows you to display collapsible and expandable content sections.
> The Bento Carousel component is a generic carousel for displaying multiple similar pieces of content along a horizontal or vertical axis.
> Bento brightcove Component
> The Bento Date Countdown component displays a countdown sequence to a specified date.
> The Bento Date Display component displays time data that you can render in your page.
> The Bento Embedly Card component provides you with responsive and shareable embeds to drive the reach of your websites, blog posts, and articles from any URL using Embedly cards.
> The Bento Facebook component allows you to embed a Facebook post, a Facebook video, or a comment on a Facebook post. …

🏗 Populate Bento package description from README

---

extensions/amp-video-iframe/1.0/test-e2e/test-bento-video-iframe.js
test/fixtures/e2e/bento/video-iframe.html

✅ [bento-video-iframe] add e2e test

---

extensions/amp-soundcloud/1.0/test-e2e/test-bento-soundcloud.js
test/fixtures/e2e/bento/soundcloud.html

✅ [bento-soundcloud] add e2e test

---

extensions/amp-vimeo/1.0/test-e2e/test-bento-vimeo.js
test/fixtures/e2e/bento/vimeo.html

✅ [bento-vimeo] add e2e test

---

.vscode/settings.json
build-system/global-configs/README.md
build-system/global-configs/versioning.json
build-system/json-schemas/versioning.json

🏗 Add versioning.json file

---

.github/workflows/sync-versioning-to-cdn.yml

Followup on #36714
Part of #36152

🏗 Sync versioning.json to CDN

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.192

---

extensions/amp-social-share/1.0/base-element.js
extensions/amp-social-share/1.0/component.js
extensions/amp-social-share/1.0/test-e2e/test-bento-social-share.js
extensions/amp-social-share/1.0/test/test-component.js
test/fixtures/e2e/amp-social-share/amp-social-share.html
test/fixtures/e2e/bento/social-share.html

🐛✅ [social-share] fix title and canonical url being passed to share link

---

extensions/amp-auto-lightbox/0.1/amp-auto-lightbox.js
extensions/amp-auto-lightbox/0.1/test/test-amp-auto-lightbox.js
extensions/amp-lightbox-gallery/0.1/service/lightbox-manager-impl.js
src/auto-lightbox.js

Use static enum linting with AutoLightboxEvents

---

extensions/amp-accordion/1.0/base-element.js
extensions/amp-selector/1.0/base-element.js

use correct logger in bento standalone components

---

extensions/amp-video-iframe/0.1/amp-video-iframe.js
extensions/amp-video-iframe/0.1/test/test-amp-video-iframe.js
extensions/amp-video-iframe/amp-video-iframe.md

✨ Pass in JSON-LD data as part of `amp-video-iframe` metadata

---

build-system/release-tagger/index.js
build-system/release-tagger/test/update-issue-tracker.test.js
build-system/release-tagger/update-issue-tracker.js
build-system/release-tagger/utils.js
build-system/test-configs/forbidden-terms.js

🏗 Decode url params for release tagger

---

extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.js
extensions/amp-story-interactive/0.1/amp-story-interactive-abstract.js

Refactor `loadFonts_` to reduce variables and utilize es6.
(Saw an opportunity while researching `FontFace` and understanding this function)

♻️ 🚮 [amp story interactives] [amp story dev tools] Refactor loadFonts_

---

build-system/global-configs/client-side-experiments-config.json

The fixes are now in. Start another round now.

Ramp up amp-sticky-ad-to-amp-ad-v4 experiment to 5%

---

extensions/amp-facebook/1.0/test-e2e/test-bento-facebook.js
test/fixtures/e2e/bento/facebook.html

✅[bento-facebook] add e2e test

---

src/compiler/compile.js
src/compiler/types.d.ts
test/unit/compiler/test-compile.js

compiler.js: s/versions/component_versions

---

extensions/amp-embedly-card/1.0/amp-embedly-key.js
extensions/amp-embedly-card/1.0/base-element.js
extensions/amp-embedly-card/1.0/bento-embedly-card.js
extensions/amp-embedly-card/1.0/key-base-element.js
extensions/amp-embedly-card/1.0/web-component.js
extensions/amp-facebook/1.0/amp-facebook.js
extensions/amp-facebook/1.0/base-element.js
extensions/amp-facebook/1.0/bento-facebook.js
extensions/amp-facebook/1.0/web-component.js
extensions/amp-inline-gallery/1.0/web-component.js

Bento export many comps

---

extensions/amp-accordion/1.0/README.md
extensions/amp-base-carousel/1.0/README.md
extensions/amp-embedly-card/1.0/README.md
extensions/amp-facebook/1.0/README.md
extensions/amp-fit-text/1.0/README.md
extensions/amp-iframe/1.0/README.md
extensions/amp-inline-gallery/1.0/README.md
extensions/amp-instagram/1.0/README.md
extensions/amp-jwplayer/1.0/README.md
extensions/amp-lightbox-gallery/1.0/README.md
extensions/amp-lightbox/1.0/README.md
extensions/amp-mathml/1.0/README.md
extensions/amp-selector/1.0/README.md
extensions/amp-sidebar/1.0/README.md
extensions/amp-social-share/1.0/README.md
extensions/amp-soundcloud/1.0/README.md
extensions/amp-stream-gallery/1.0/README.md
extensions/amp-timeago/1.0/README.md
extensions/amp-twitter/1.0/README.md
extensions/amp-wordpress-embed/1.0/README.md
src/bento.js

♻️ Use native CustomElements in `bento.mjs`

---

extensions/amp-accordion/1.0/example/index.html

📖 Add standalone bento-accordion example

---

build-system/tasks/visual-diff/browser.js
build-system/tasks/visual-diff/index.js

Fixes #36750
Turns out that we were only supporting Linux until now 😅
Shoutout to @erwinmombay for pointers!

🏗 Add `amp visual-diff` support for Mac and Windows

---

build-system/tasks/extension-helpers.js
test/fixtures/e2e/bento/social-share.html
test/fixtures/e2e/bento/timeago.html

removes css from being included in the autogenerated npm/cdn packages

remove styles npm/cdn bento packages

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.193

---

extensions/amp-accordion/1.0/README.md
extensions/amp-base-carousel/1.0/README.md
extensions/amp-date-countdown/1.0/README.md
extensions/amp-date-display/1.0/README.md
extensions/amp-embedly-card/1.0/README.md
extensions/amp-facebook/1.0/README.md
extensions/amp-fit-text/1.0/README.md
extensions/amp-iframe/1.0/README.md
extensions/amp-lightbox-gallery/1.0/README.md
extensions/amp-lightbox/1.0/README.md
extensions/amp-selector/1.0/README.md
extensions/amp-stream-gallery/1.0/README.md
extensions/amp-twitter/1.0/README.md

📖 Remove newlines inside paragraphs in Bento docs

---

extensions/amp-fit-text/1.0/README.md
extensions/amp-fit-text/1.0/example/index.html
extensions/amp-iframe/1.0/example/index.html
extensions/amp-inline-gallery/1.0/example/index.html
extensions/amp-lightbox-gallery/1.0/example/index.html
extensions/amp-lightbox/1.0/example/index.html
extensions/amp-mathml/1.0/example/index.html
extensions/amp-selector/1.0/README.md
extensions/amp-selector/1.0/example/index.html
extensions/amp-sidebar/1.0/README.md
extensions/amp-sidebar/1.0/example/index.html
extensions/amp-social-share/1.0/example/index.html
extensions/amp-stream-gallery/1.0/example/index.html
extensions/amp-timeago/1.0/README.md
extensions/amp-timeago/1.0/example/index.html

These are just starting points, not the complete examples.

📖 Populate Bento hero examples from READMEs

---

docs/building-an-amp-extension.md
src/core/dom/layout/index.js
test/unit/test-custom-element.js

Refactor LOADING_ELEMENTS into a Set

---

build-system/eslint-rules/camelcase.js
src/compiler/compile.js

implements https://github.com/ampproject/amphtml/pull/36859#discussion_r745882034
cc @rcebulko / @jridgewell

lint local/camelcase: allow destructure

---

test/unit/test-crypto.js
test/unit/test-custom-element.js

[Another](https://github.com/ampproject/amphtml/pull/36923) test fix for #36273, which I'm not sure how it was merged with failing tests.

Fix test from #36273

---

extensions/amp-fit-text/1.0/example/index.html

(also fix readme formatting error)

📕 Add bento-fit-text example

---

build-system/global-configs/client-side-experiments-config.json

We have got enough data for investigation purposes. Ramping down.

Ramp down amp-sticky-ad-to-amp-ad experiment

---

extensions/amp-base-carousel/1.0/README.md
extensions/amp-embedly-card/1.0/README.md
extensions/amp-facebook/1.0/README.md
extensions/amp-lightbox-gallery/1.0/README.md
extensions/amp-social-share/1.0/README.md
extensions/amp-soundcloud/1.0/README.md
extensions/amp-twitter/1.0/README.md
extensions/amp-wordpress-embed/1.0/README.md

📖 Bento: list `<link rel=stylesheet ...`

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

✨  UI specifications of Sign in with Google button
✨  Issue in which gaaUser is not present in message
🖍  Showcase: Underline link
🖍  Keep translateY fixed to 50% when resizing centered dialogs (#1995)
✨  Focus the dialog contents after its opened (#1993)

SwG Release 0.1.22.194

---

extensions/amp-base-carousel/1.0/component.js
extensions/amp-lightbox-gallery/1.0/consumer.js
extensions/amp-selector/1.0/storybook/Basic.js
extensions/amp-stream-gallery/1.0/component.js
src/preact/compat.js
src/preact/index.js

Take 2:
* remove createPortal
* replace toChildArray with the fn from preact
* copy/paste forwardRef implementation
I'm not copy/pasting from the shim [here](https://gist.github.com/developit/974b5e4e582df8e954c5a7981603cd37) anymore because it seems wrong (for our purposes). Conceptually, it seems fine, but the official `forwardRef` seems to have extra logic (adding properties to the forwarded component, exporting extra symbols, etc.), without which many of our components seem to break.
Instead, I am copy/pasting from the actual [preact/compat/dist/compat.js](https://unpkg.com/browse/preact@10.5.15/compat/dist/compat.js) distributable the actual pieces of minified code that seem relevant to the `forwardRef`. I am effectively copying the minified version of forwardRef file …

refactor preact/compat to reduce bundlesize

---

src/preact/compat.js
src/preact/index.js

Re: https://github.com/ampproject/amphtml/pull/36976

Cleanup forwardRef implementation

---

build-system/common/update-packages.js

The replaced code is no longer present on the installed version of `web-animations-js`

🏗 Remove specific workarounds from `patchWebAnimations`

---

test/unit/test-document-info.js

Fix DocInfo tests

---

.circleci/config.yml

Re: https://github.com/ampproject/amphtml/pull/37043#issuecomment-977986229

Rename Build Prod CircleCI jobs

---

test/fixtures/e2e/bento/brightcove.html
test/fixtures/e2e/bento/lightbox.html

Adding more fixtures because it's been helpful for me to test <bento-*> components
tests to follow

More e2e fixtures

---

build-system/tasks/helpers.js

**summary**
Context: https://github.com/ampproject/amphtml/issues/35264.

🚀   Use esbuild for all production builds

---

build-system/release-tagger/index.js

🐛 Fix undefined time param for release tagger

---

extensions/amp-mustache/amp-mustache.md

It's currently out of sync with the code (#32081 didn't update this documentation). It also incorrectly states
that amp-list is allowed (it's not), which is probably a typo from #31300.
https://github.com/ampproject/amphtml/blob/c91e704e4d09d8fbac1068653e0dd71a078d8912/src/purifier/sanitation.js#L104-L159
/to @dvoytenko 
/cc @nickFalcone 
/cc @dmanek 
/cc @alanorozco

📖 Update the documented triple Mustache tag allowlist

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.195

---

validator/validator-main.protoascii

fix comment for dvh polyfill spec

---

ads/vendors/trafficstars.js
ads/vendors/trafficstars.md

Add data attributes(subid) support for analytics reasons
/cc @ishaba

🐛 Add subid support to TrafficStars Ad

---

build-system/pr-check/visual-diff-tests.js

forgot to add --esm and --minified to push builds

add --esm and --minified to push build workflow

---

ads/vendors/smartclip.md

The example code misses important information/recommendation in the age of transparency and consent. The new parameter data-block-on-consent="_till_responded" is necessary to not request ads prematurely.

📖  [smartclip] Extends code sample with `data-block-on-consent`

---

extensions/amp-youtube/1.0/README.md

📖 Bento Youtube

---

build-system/npm-publish/write-package-files.js

🐛 fix typo for dir

---

build-system/npm-publish/write-package-files.js

check if file exist before copying

---

build-system/common/update-session-issues/template/design-review.js

🏗 Update Design Review issue template

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.196

---

src/service/real-time-config/callout-vendors.js

Extract the GDPR applies flag from macro and transmit it within the Criteo URL.

✨ Add gdpr applies flag to Criteo URL

---

extensions/amp-story/1.0/amp-story.js

We also need to detect if we're ssr'ing the link element

detect link server side rendering for amp-story-1.0.css

---

extensions/amp-story/1.0/amp-story-store-service.js
extensions/amp-story/1.0/amp-story-system-layer.js
extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/test/test-amp-story-store-service.js

🚮 [Story system-layer] Removing unused `storyHasAudio` state property

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.197

---

build-system/global-configs/experiments-config.json
build-system/global-configs/experiments-const.json

Cleanup for https://github.com/ampproject/amphtml/issues/35264

Cleanup esbuild exp_c flag

---

extensions/amp-subscriptions-google/OWNERS
extensions/amp-subscriptions/OWNERS

🏗 Update OWNERS

---

OWNERS

🏗 Make @ samouri own all build-dom files

---

OWNERS

🏗 [OWNERS] Let Infra & Perf WGs own all .d.ts files

---

test/unit/test-viewer.js

Test has been failing for a few days.
cc @jridgewell @alanorozco

❄️  Skipping failing test for viewer

---

3p/vendors/dex.js
ads/_config.js
ads/vendors/dex.js
ads/vendors/dex.md
examples/amp-ad/ads.amp.html
extensions/amp-ad/amp-ad.md

Hi there,
We'd like to integrate our client Ad-Server with AMP. We've contributed to AMP as per documentation. Please check & approve.
Thanks in advance!
Tijl Verbert

Dex integration

---

OWNERS

Fix OWNERS typo

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.199

---

extensions/amp-mathml/1.0/storybook/Basic.amp.js

mathml storybook: supply missing component definition.

---

extensions/amp-story/1.0/amp-story.css

Reverts ampproject/amphtml#37329

Revert "🚀 [Story performance] Show story with CSS only on transformed docs"

---

build-system/compile/bundles.config.extensions.json

**summary**
Addresses https://github.com/ampproject/amphtml/issues/37356.
Each version should line up what what is encoded in [bundles.legacy-latest-versions.jsonc](https://github.com/ampproject/amphtml/blob/main/build-system/compile/bundles.legacy-latest-versions.jsonc)
**steps taken**
1. Git revert 4df29d5cb8c054a42fafc8cfe0e07259c678754d
2. Undo all the files other than build-system/compile/bundles.config.extensions.json

🐛 extension bundles json: revert latestVersions change

---

build-system/release-workflows/cut-nightly.js

To be merged after https://github.com/ampproject/cdn-configuration/pull/29

🏗 Trigger the nightly promote workflow after cutting a new nightly

---

examples/amp-access-fewcents.html
extensions/amp-access-fewcents/0.1/amp-access-fewcents.css
extensions/amp-access-fewcents/0.1/amp-access-fewcents.js
extensions/amp-access-fewcents/0.1/fewcents-constants.js
extensions/amp-access-fewcents/0.1/fewcents-impl.js
extensions/amp-access-fewcents/0.1/test/test-amp-access-fewcents.js
extensions/amp-access-fewcents/0.1/test/validator-amp-access-fewcents.html
extensions/amp-access-fewcents/0.1/test/validator-amp-access-fewcents.out
extensions/amp-access-fewcents/amp-access-fewcents.md

Ref to I2I: #[31854](https://github.com/ampproject/amphtml/issues/31854)
**Description:**
This PR is second cut for the amp-access-fewcents component, you can find the first PR [here](https://github.com/ampproject/amphtml/pull/37096), and this PR includes:
- Authorize API call completion
- Handled the authorize response
- Completing the paywall
- Added design
- Added amp-analytics using segment.
We have been following amp-access-laterpay and amp-access-poool for our reference.
- [amp-access](https://github.com/ampproject/amphtml/tree/main/extensions/amp-access)
- AMP code contribution docs: https://github.com/ampproject/amphtml/blob/main/docs/contributing-code.md
- First time setup: https://github.com/ampproject/amphtml/blob/main/docs/getting-started-e2e.md
- Building an …

✨ Second cut for new component: [amp-access-fewcents] paywall support by Fewcents

---

src/compiler/builders.js

Bug found and will address in https://github.com/ampproject/amphtml/pull/37358

bug found!: remove carousel from builder map

---

validator/README.md

Add instructions of building wasm validator

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-button.css
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.200

---

extensions/amp-next-page/1.0/service.js
extensions/amp-next-page/1.0/test/test-amp-next-page.js

🐛 Return viewer message response in multi-doc shadow

---

examples/compiler-hydration.html

**summary**
Adds manual test to compare csr and ssr of carousel 0.1s two types: scrollable/slides.
A future PR will add serialized event handlers.
**screenshot**

examples: add carousel-0.1 to compiler-hydration.html

---

extensions/amp-carousel/0.1/tsconfig.json
src/compiler/builders.ts
src/compiler/compile.ts
src/compiler/global.d.ts
src/compiler/index.ts
src/compiler/polyfills.ts
src/compiler/tsconfig.json

**summary**
Use `.ts` for src/compiler.

compiler: use .ts files

---

.circleci/config.yml
build-system/release-workflows/trigger-promote.js

Currently triggers the nightly promote job.

🏗  Trigger promote workflow after uploading release

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.201

---

src/preact/OWNERS

Caroline is still listed as an owner here, so this removes her. Replaced her with myself for now but happy to remove or replace with wg-bento

replace caroline as an owner of src/preact

---

src/compiler/builders.ts

revert of https://github.com/ampproject/amphtml/pull/37366.
cc @rcebulko

Compiler: Add amp-carousel-0.1 to the builder map (take2)

---

.circleci/config.yml

CircleCI has a new executor type available for macOS builds that is supposed to be much faster.

🏗  Update circleci config to use new macos executor

---

src/preact/amp-base-element.js

change fn name

---

build-system/release-workflows/trigger-promote.js

Also adds workflow to trigger based on branch name

Fix trigger promote job

---

src/preact/amp-base-element.js

fix comment

---

extensions/amp-base-carousel/validator-amp-base-carousel.protoascii
extensions/amp-carousel/validator-amp-carousel.protoascii
extensions/amp-live-list/0.1/test/validator-amp-live-list.out
extensions/amp-live-list/validator-amp-live-list.protoascii
extensions/amp-next-page/validator-amp-next-page.protoascii
extensions/amp-selector/validator-amp-selector.protoascii
extensions/amp-story/validator-amp-story.protoascii

Add descriptive names to all validator reference points.

---

build-system/eslint-rules/no-import-rename.js

These paths have been moved/aliased.

🏗 Update paths in `no-import-rename`

---

extensions/amp-story/amp-story.md

Add required `autoplay` attribute in amp-story.md

---

docs/writing-css.md

fixed some typos

---

OWNERS
third_party/OWNERS

Now that @kristoferbaxter is leaving he has requested to be removed from all OWNERS files

♻️ 🚮 Remove kristoferbaxter from OWNERS files

---

examples/amp-story/amp-story-shopping.html
examples/amp-story/shopping/remote.json
examples/visual-tests/amp-story/amp-story-shopping-lang-de.html
examples/visual-tests/amp-story/amp-story-shopping.html
extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js
extensions/amp-story-shopping/0.1/amp-story-shopping-config.js
extensions/amp-story-shopping/0.1/amp-story-shopping-tag.js
extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-attachment.js
extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-config.js
extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-tag.js
extensions/amp-story/1.0/amp-story-store-service.js

Makes semantics be more symmetric by using `data-product-id` instead of `data-tag-id`. 
This helps put emphasis on the product instead of the tag since the product is what's being identified, and not the tag itself.

♻️ [amp story shopping] Rename tag-id to product-id

---

src/bento/OWNERS

The components team should own the new `src/bento` directory. While components are being moved to the new directory, infra should also have ownership to reduce strain during the move.

🏗 Add OWNERS file to `src/bento`

---

extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

Reverts ampproject/amphtml#37492
Version "0.1.22.203" introduced a regression

Revert "✨ SwG Release 0.1.22.203"

---

extensions/amp-ad/amp-ad.md

fix readme link

---

extensions/amp-inline-gallery/1.0/amp-inline-gallery.css

import subcomponent styles so they're exposed in extension stylesheet

---

.github/workflows/sweep-experiments.yml
build-system/tasks/sweep-experiments/cleanup-branches.js

After a new `sweep-experiments` PR is created, cleanup unaddressed PRs:
1. Close pull request.
2. Delete associated branch.

🏗 Cleanup experiment removal branches

---

3p/iframe-messaging-client.js
ads/vendors/ssp.js

We longer use CC, the comments are no longer elevant.

rm: @suppress checkTypes

---

test/e2e/test-amp-bind-iframe.js

Band-aid for: https://github.com/ampproject/amphtml/issues/37532

❄️ Skip amp-bind 'should support binding to src' e2e test

---

.github/workflows/update-session-issues.yml
build-system/common/update-session-issues/template/design-review.js

Addresses https://github.com/ampproject/amphtml/issues/36888

Remove Asia/Oceania from design review rotation.

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.205

---

build-system/tasks/extension-helpers.js

🐛 build and copy if built css doesn't exist

---

extensions/amp-story/1.0/test/validator-amp-story-form-error.out
validator/testdata/feature_tests/forms.html
validator/testdata/feature_tests/forms.out
validator/testdata/feature_tests/leaks.out
validator/testdata/feature_tests/leaks.out.cpponly
validator/validator-main.protoascii

Allow input[type=image].

---

package-lock.json
package.json

bump worker-dom and bento-compiler

---

build-system/compile/bento-remap.js

Error:
```
/Users/alanorozco/git/amphtml/build-system/compile/bento-remap.js:112
Object.entries(isMinified).map(([source, cdn]) => [
^
TypeError: Cannot convert undefined or null to object
```

🏗🐛 Fix non-`dist` build of Bento extensions

---

test/visual-diff/visual-tests.jsonc

🐛 Disable flaky visual test

---

ads/vendors/broadstreetads.js

This PR allows the customization of the URL to our initialization script, which will allow our dev team to test local changes.

✨ [amp-ad broadstreetads] Add the ability to customize the init url

---

build-system/tasks/storybook/index.js

🐛 Fix Proxy Frames in Storybook

---

build-system/tasks/storybook/env/amp/package-lock.json
build-system/tasks/storybook/env/amp/package.json

🏗 Fix AMP Storybook 6.4 dependency

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.206

---

build-system/tasks/runtime-test/helpers-unit.js

The recently introduced alias imports appears to have broken local change detection mode in the unit tests (`amp unit --local_changes`). This PR makes two fixes to the existing logic:
- Resolves all import aliases in test files before checking if a dependent file was modified
- No longer assumes that imported files are js (so that ts and js files are checked)
If after this fix, the local change logic seems too clunky, an alternative would be to eliminate `--local_changes` altogether, and simply rely on `amp unit` (all tests). Thoughts?

🏗  Fix local change detection in unit tests

---

build-system/eslint-rules/forbidden-terms-config.js

Otherwise errors opaquely:
```
TypeError: Cannot read properties of undefined (reading 'range')
Occurred while linting /Users/alanorozco/git/amphtml/build-system/test-configs/forbidden-terms.js:723
at removeFromArray (/Users/alanorozco/git/amphtml/build-system/eslint-rules/forbidden-terms-config.js:54:46)
```

🏗🐛Fix forbidden terms check when file lacks term

---

extensions/amp-access-fewcents/amp-access-fewcents.md

Ref to I2I: https://github.com/ampproject/amphtml/issues/31854
**Description**:
This PR fixes 3 typos we had in the readme and adds teaser text for SEO optimisation. 
References:
1. [amp-access](https://github.com/ampproject/amphtml/tree/main/extensions/amp-access)
2. [AMP code contribution docs](https://github.com/ampproject/amphtml/blob/main/docs/contributing-code.md)
3. [First time setup](https://github.com/ampproject/amphtml/blob/main/docs/getting-started-e2e.md)
4. [Building an extension](https://github.com/ampproject/amphtml/blob/main/docs/building-an-amp-extension.md)

📖Updates Readme for component: [amp-access-fewcents] paywall support by Fewcents

---

build-system/test-configs/OWNERS

Fix test-configs/OWNERS

---

extensions/amp-script/0.1/amp-script.js
extensions/amp-script/0.1/test/unit/test-amp-script.js

Addresses https://github.com/ampproject/amphtml/issues/33566

amp-script: warn with zero width or height

---

build-system/tasks/build-bento.js
build-system/tasks/extension-helpers.js
build-system/tasks/helpers.js

Cleaning up some inconsistencies in how the `dist` and `build/css` directories were being created during the build process.

🏗  ♻️ Refactor creation of build artifact directories

---

extensions/amp-geo/amp-geo.md

follow up to https://github.com/ampproject/amphtml/pull/37755/files to update docs

add ISOSubdivision support to docs

---

build-system/npm-publish/write-package-files.js
build-system/release-tagger/make-release.js
build-system/release-tagger/test/make-release.test.js

When attempting to fix Bento component publishing in #37735 I introduced another issue. [See logs](https://github.com/ampproject/amphtml/runs/5301120632?check_suite_focus=true).
In addition to fixing the issues created in #37735 and to prevent these sort of issues from occurring in the future I am updating and adding tests.
#37737

🐛  🏗 ✅  Fix bug in npm publish flow

---

src/bento/bento.js

move bento-ce.js into Bento Runtime/Core

---

ads/vendors/adocean.js

Pass consent string and gdprApplies if available and tcf2 compliant to AdOcean.

✨ [ads] AdOcean vendor - pass consent string and gdprApplies if tcf2 compliant

---

build-system/tasks/extension-helpers.js

Blocked by https://github.com/ampproject/amphtml/pull/37734
fixes: https://github.com/ampproject/amphtml/issues/37674

Utilize bento/core in (p)react extensions

---

examples/amp-story/fake-ad.html

This example needs to be updated to reflect the new prefix name.

📖 Meta tag meta prefix fix

---

.github/workflows/publish-npm-packages.yml
build-system/npm-publish/get-package-dir.js
build-system/npm-publish/utils.js
build-system/npm-publish/write-package-files.js

The Bento publish flow has been failing for about 2 weeks for 2 different reasons...
[Core publishing issue logs](https://github.com/ampproject/amphtml/runs/5431875974?check_suite_focus=true)
[Bento components directory issue logs](https://github.com/ampproject/amphtml/runs/5301120632?check_suite_focus=true)
Core is not being published because the directory is changed prior to the script determining the version being called.
Components are not being published because the publish script assumes all packages are under the `extensions` directory.
#37737

🏗 🐛 Fix bento publish flow

---

extensions/amp-form/amp-form.md

Email format doesn't allow template for the submitting div. See
https://github.com/ampproject/amphtml/blob/92155aab898ad949209dc4e0bc72bddfe02febba/validator/validator-main.protoascii#L2705-L2707.

Update email doc re: <div submitting>

---

extensions/amp-twitter/1.0/test-e2e/test-bento-twitter.js
test/fixtures/e2e/bento/twitter.html

add twitter fixture

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.209

---

src/service/real-time-config/callout-vendors.js

Updating T13 endpoint to support 'consent_string' and 'CONSENT_METADATA'

🚀 callout vendors update for t13

---

extensions/amp-story-shopping/amp-story-shopping.md

Documentation for the amp-story-shopping experience.
The analytics section will be added once the actions are defined.
Fixes #37894

📖 [amp story shopping] documentation

---

build-system/eslint-rules/service-getters.js
src/service/.eslintrc.js
src/service/index.js

♻️🐛 Remove non-arrow-function Service getter

---

build-system/tasks/e2e/selenium-webdriver-controller.js
extensions/amp-base-carousel/1.0/storybook/Basic.js
extensions/amp-base-carousel/1.0/test-e2e/e2e-fixture.js
extensions/amp-base-carousel/1.0/test-e2e/helpers.js
extensions/amp-base-carousel/1.0/test-e2e/test-bento-base-carousel.js
extensions/amp-base-carousel/1.0/test-e2e/test-preact-react.js
extensions/amp-base-carousel/1.0/test/standalone/test-bento-base-carousel.js

✅ Add tests for base-carousel Resolves #37891

---

extensions/amp-date-countdown/1.0/README.md
extensions/amp-date-display/1.0/README.md

Update web component section in both readme since we now support mustache template for them.

📖  Update readme for `bento-date-display` and `bento-date-countdown`

---

build-system/tasks/default-task.js
build-system/tasks/dist.js
docs/testing.md

🏗 Remove unused CLI arguments related to Closure Compiler

---

src/core/dom/query.js

https://caniesm.vercel.app/?search=matches
https://caniesm.vercel.app/?search=closest

♻️ Dead-code-eliminate implementations of `matches` and `closest` on ESM

---

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
extensions/amp-story/1.0/amp-story-store-service.js
extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/progress-bar.js
extensions/amp-story/1.0/test/test-amp-story-viewer-messaging-handler.js
extensions/amp-story/1.0/test/test-amp-story.js
extensions/amp-story/1.0/test/test-variable-service.js
extensions/amp-story/1.0/variable-service.js

This is so that we can put ads into the progress bar more eloquently.

♻️ Story: refactor to treat story ad pages as story pages

---

extensions/amp-story/1.0/amp-story.js

Just a typo in the comment. Nothing important.

amp-story comment typo fix

---

extensions/amp-timeago/1.0/storybook/Basic.js
extensions/amp-timeago/1.0/test-e2e/e2e-fixture.js
extensions/amp-timeago/1.0/test-e2e/test-preact-react.js

Add e2e preact/react test for timeago.

✅ add bento-timeago preact/react e2e test. resolves #37923

---

.github/create_issue_on_error.md
.github/workflows/create-issue-on-error.yml
.github/workflows/cut-nightly.yml
.github/workflows/publish-npm-packages.yml
.github/workflows/release-tagger.yml
.github/workflows/status-page.yml
.github/workflows/sweep-experiments.yml
build-system/test-configs/config.js

Not sure whether all of these make sense, most specifically I'm unfamiliar with how/when/whom triggers publish-npm-packages.yml

🏗 Create a GitHub issue when automated GH Actions workflow fail

---

build-system/compile/bento-remap.js

🏗 Fix Windows path resolution for Bento remap

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

🏗 SwG Release 0.1.22.212

---

src/service/real-time-config/callout-vendors.js

A new parameter _curl_ is added in PubMatic Openwrap RTC config.

✨[PubMatic Openwrap] Added curl rtc config in PubMatic openwrap vendor

---

extensions/amp-story/1.0/amp-story-page.js
extensions/amp-story/1.0/amp-story-system-layer.css
extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/progress-bar.js
extensions/amp-story/1.0/test/test-amp-story-progress-bar.js

It is gated under the story-ad-auto-progression experiment. Can you do a first round of review? Tests to be added.

✨ Yellow story ads progress bar for ads

---

.github/workflows/cross-platform-builds.yml
.github/workflows/cut-nightly.yml
.github/workflows/publish-npm-packages.yml
.github/workflows/release-tagger.yml
.github/workflows/status-page.yml
.github/workflows/sweep-experiments.yml

🏗 Replace token for create-issue-on-error from GITHUB_TOKEN to AMPPROJECTBOT

---

extensions/amp-script/0.1/amp-script.js
extensions/amp-script/0.1/test/unit/test-amp-script.js

Fixes https://github.com/ampproject/error-reporting/issues/155

amp-script: callFunction should handle when workerDom failed to init

---

src/inabox/inabox-resources.js
test/unit/inabox/test-inabox-resources.js

Fixes https://github.com/ampproject/error-reporting/issues/157

inabox-resources: Resource.build may return undefined by spec.

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.213

---

src/shadow-embed.js
third_party/webcomponentsjs/README.amp
third_party/webcomponentsjs/ShadowCSS.js

♻️🚀 Dead-code-eliminate `ShadowCSS.js`

---

extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
extensions/amp-story-auto-ads/0.1/story-ad-page.js
extensions/amp-story-auto-ads/0.1/story-ad-ui.js
extensions/amp-story-auto-ads/0.1/test/test-story-ad-ui.js
extensions/amp-story-page-attachment/0.1/amp-story-open-page-attachment.css
extensions/amp-story-page-attachment/0.1/amp-story-open-page-attachment.js
extensions/amp-story/1.0/amp-story-page.js
extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/progress-bar.js
extensions/amp-story/1.0/test/test-amp-story-progress-bar.js
src/experiments/story-ad-progress-segment.js

Experiments:
1. Control
2. Auto advance + old CTA
3. Auto advance + new CTA w/ animation
4. Auto advance + new CTA w/o animation
Experiment IDs need to be updated before merging.

🧪 Experiment: story auto advance and new cta button

---

build-system/test-configs/dep-check-config.js
extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js
extensions/amp-story-shopping/0.1/amp-story-shopping-tag.js
extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-attachment.js
extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-tag.js
extensions/amp-story/1.0/amp-story.js
extensions/amp-story/1.0/history.js

A follow up PR to #37503 after config validation was added.
Closes #38034 and https://github.com/ampproject/amphtml/issues/38040

🐛 amp-story-shopping does not display CTA if all tags are invalid and Fixes remote shopping data loading on refresh with page attachment open 

---

test/integration/test-amp-ad-type-custom.js

This test has been flaking and is blocking CI
#38126

✅  ❄️  skip flaky amp-ads test

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.214

---

ads/vendors/4wmarketplace.js

Fix parameters on 4wmarketplace amp library

🐛fix parameters

---

third_party/subscriptions-project/OWNERS

🏗  Update subscriptions owners 

---

.circleci/OWNERS
.circleci/install_microsoft_edge.sh
.vscode/OWNERS
OWNERS
build-system/common/OWNERS
build-system/common/ci.js
build-system/common/update-packages.js
build-system/pr-check/OWNERS
build-system/server/OWNERS
build-system/task-runner/OWNERS
build-system/tasks/runtime-test/custom-launchers.js
testing/console-logging-setup.js
third_party/OWNERS

🚮 Remove `rsimha` from all owners files and comments

---

extensions/amp-story-subscriptions/0.1/amp-story-subscriptions.css
extensions/amp-story-subscriptions/0.1/amp-story-subscriptions.js
extensions/amp-story/1.0/amp-story.css

✨ [AMP Story Paywall] Make buttons and anchor element focusable/tabbable

---

examples/amp-ad/ads.amp.html
extensions/amp-a4a/rtc-documentation.md
extensions/amp-a4a/rtc-publisher-implementation-guide.md
src/service/real-time-config/callout-vendors.js

This PR adds the PubWise RTC Endpoints.

✨Addition of RTC Endpoint for PubWise

---

3p/vendors/adenza.js
ads/_config.js
ads/vendors/adenza.js
ads/vendors/adenza.md
examples/amp-ad/ads.amp.html

Create this to fix an issue adenzanetwork  is facing.
https://github.com/ampproject/amphtml/pull/38150

Adenza: new ad vendor

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.216

---

extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js

Adding more data to the messaging API to allow more feature for story integration.

Added the possibility to get page count to the story messaging api

---

examples/amp-story/amp-story-subscriptions.html
examples/visual-tests/amp-story/amp-story-subscriptions.html
extensions/amp-story-subscriptions/0.1/amp-story-subscriptions.css
extensions/amp-story-subscriptions/0.1/amp-story-subscriptions.js

See the internal API documentation draft here: [go/amp-story-subscriptions-documentation](https://goto.google.com/amp-story-subscriptions-documentation)

Change amp-story-subscriptions attribute names to reflect their flexibility

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.217

---

ads/vendors/dable.js
ads/vendors/dable.md

Add new optional parameter "channel" to meet our customer's needs.

✨ Dable: add new optional parameter "channel"

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.218

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

- setOnEntitlementsResponse() should be available to publishers 
- Added AnalyticsEvent to track GIS button click

SwG Release 0.1.22.219

---

3p/vendors/vox.js
ads/_config.js
ads/vendors/vox.js
ads/vendors/vox.md
examples/amp-ad/ads.amp.html
extensions/amp-ad/amp-ad.md

Vox ad integration

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.220

---

validator/validator-main.protoascii

Add xssi-prefix to form method=POST for AMP & Ads

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.221

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.222

---

build-system/common/esbuild-babel.js
extensions/amp-analytics/0.1/test/vendor-requests.json
extensions/amp-analytics/0.1/vendors/gfksensic.json

amp-analytics Gfksensic: removed p param from request

---

ads/vendors/vox.js

Vox date intregration fix

---

build-system/compile/bundles.config.extensions.json

prefer dashes to underscore for file naming consistency

prefer dashes to underscore for file naming consistency for ssr css filenames

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

🏗 Update SwG to latest version.

 SwG Release 0.1.22.227

---

.circleci/config.yml
extensions/amp-script/0.1/test-e2e/test-amp-script.js

Supported Xcode versions https://circleci.com/docs/using-macos#supported-xcode-versions

Update CircleCI macOS Xcode version

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.229

---

third_party/subscriptions-project/OWNERS

Adding myself as an owner to help approve code reviews for subscriptions

Adding hartmannr76 as subscriptions-project owner

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.230

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.231

---

extensions/amp-subscriptions-google/OWNERS
extensions/amp-subscriptions/OWNERS
third_party/subscriptions-project/OWNERS

Update SwG owners

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.233

---

build-system/tasks/e2e/index.js

Hoping this will reduce `main` flakiness

🏗❄️ Make e2e test flakes more lenient in CI

---

examples/visual-tests/amp-story/amp-story-page-attachment.js

e.g., https://app.circleci.com/pipelines/github/ampproject/amphtml/26276/workflows/442a2a3e-153b-441c-a20a-a204c3cfd2fc/jobs/547151

❄️ Disable a flaky visual diff test

---

3p/vendors/r9x.js
ads/_config.js
ads/ads.extern.js
ads/vendors/r9x.js
ads/vendors/r9x.md
examples/amp-ad/ads.amp.html
extensions/amp-ad/amp-ad.md

R9x ad vendor

---

ads/google/a4a/utils.js
extensions/amp-a4a/0.1/secure-frame.js
extensions/amp-ad-exit/0.1/amp-ad-exit.js
extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js

Our code had gone out of sync with the latest proposal from chrome folks. See https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#registering-attribution-sources
cc/ @zombifier

🧪 Update attribution tracking api to match latest spec

---

src/service/real-time-config/callout-vendors.js

Add `targeting` param to pubmatic openwrap callout URL

✨ [PubMatic Openwrap] Add targeting to PubMatic Openwrap callout URL

---

OWNERS

adding myself as root owner so i can approve PR's

add erwin as root owner

---

3p/vendors/pubfuture.js
ads/_config.js
ads/vendors/pubfuture.js
ads/vendors/pubfuture.md
examples/amp-ad/ads.amp.html
extensions/amp-ad/amp-ad.md

✨ Add Pubfuture to vendor list

---

extensions/amp-subscriptions-google/OWNERS
extensions/amp-subscriptions/OWNERS
third_party/subscriptions-project/OWNERS

Chris has rejoined the team, adding him back to owners.

🏗  Add ChrisAntaki to owners for amp-subscriptions-* and subscriptions-project

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-button.css
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.240

---

ads/google/a4a/utils.js
extensions/amp-a4a/0.1/secure-frame.js

🧪 Update origin trial token

---

extensions/amp-a4a/rtc-documentation.md
extensions/amp-a4a/rtc-publisher-implementation-guide.md
src/service/real-time-config/callout-vendors.js

Add improvedigital to RTC callout vendors

---

ads/vendors/relap.js
ads/vendors/relap.md
examples/amp-ad/ads.amp.esm.html
examples/amp-ad/ads.amp.html
validator/testdata/feature_tests/ads.html
validator/testdata/feature_tests/ads.out

🐛 Fixes #38474
Also fixed widget examples

🐛 Optimize Relap widget loading

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 0.1.22.243

---

.github/workflows/cross-platform-builds.yml
.github/workflows/cut-nightly.yml
.github/workflows/publish-npm-packages.yml
.github/workflows/release-tagger.yml
.github/workflows/status-page.yml
.github/workflows/sweep-experiments.yml
.github/workflows/update-session-issues.yml

- use node lts
- upgrade actions/checkout to v3
- upgrade actions/setup-node to v3

Update GitHub actions 

---

.github/workflows/publish-npm-packages.yml
.github/workflows/sweep-experiments.yml

set-output will be deprecated in May 2023 - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Replace gha set-output with env vars

---

build-system/release-workflows/upload-release.js
package-lock.json
package.json

No longer required since https://github.com/ampproject/cdn-worker/pull/199
Post-merge actions:

🏗🚮 Remove GCS uploads for releases

---

extensions/amp-ad-network-adsense-impl/OWNERS
extensions/amp-ad-network-doubleclick-impl/OWNERS

A couple of folks who are no longer working on ads at google.

♻️ Clean up google ads OWNERS

---

.github/workflows/release-tagger.yml
build-system/release-tagger/index.js
build-system/release-tagger/label-pull-requests.js
build-system/release-tagger/make-release.js
build-system/release-tagger/test/label-pull-requests.test.js
build-system/release-tagger/test/make-release.test.js
build-system/release-tagger/test/update-release.test.js
build-system/release-tagger/update-release.js
build-system/release-tagger/utils.js
build-system/tasks/ava.js
package-lock.json
package.json

Reverts ampproject/amphtml#38649

Revert "Delete release tagger"

---

build-system/externs/amp.extern.js
src/runtime.js

add placeholder for consent API's

add global and granular consent listener API placeholders

---

ads/vendors/revcontent.js
ads/vendors/revcontent.md
examples/amp-ad/ads.amp.html

Revcontent is working on updating our ad code and part of this effort is to provide a better AMP experience for our publishers. As such, I'm proposing changes to our AMP logic when these new tags are used.
Refactoring was done to support the existing functionality while adding new functionality for newer tag implementations. Functionally, this adapter will work the same way it currently does but the values for things like required/optional attributes have been moved into an options object where the appropriate values are used depending on how the AMP tag is configured. 
Notably for our newer uses cases, the optional behavior changes to support dynamic attributes that can be used. Our reasoning behind this is that it is possible that we may implement a new feature or behavior for our ad …

♻️ Refactor revcontent logic for new adcode support

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

SwG Release 216488bf

---

.circleci/install_validator_dependencies.sh
build-system/pr-check/validator-tests.js

Reverts ampproject/amphtml#38688

Revert "Resume validator tests by using bazel 5"

---

ads/_config.js
ads/vendors/seedtag.js

♻️ Refactor
We are changing the URL of our javascript loader

Seedtag ads - update loader url

---

ads/google/a4a/utils.js
extensions/amp-a4a/0.1/secure-frame.js

https://github.com/ampproject/amphtml/issues/35347

Update attribution reporting tokens

---

extensions/amp-a4a/0.1/secure-frame.js

Update attribution reporting [second try]

---

.github/workflows/scorecard.yml

From https://github.com/ossf/scorecard-action/#installation

🏗 Add OSSF Scorecard GitHub Action

---

extensions/amp-story-captions/0.1/amp-story-captions-presets.css
extensions/amp-story-captions/0.1/amp-story-captions.md

Updates `amp-story-captions` docs for official launch.
Corrects comment in css file.

📖 [amp story captions] Update docs

---

.circleci/config.yml
extensions/amp-story-audio-sticker/0.1/test/test-amp-story-audio-sticker.js

Use a `Deferred` object to finalize the test

🐛 Fix flaky test in `amp-story-audio-sticker` as a result of using `setTimeout`

---

package-lock.json
package.json

This reverts commit 5d410d089d3b382c25c64c3380a614726ad776a0.

Revert "📦 Update ampproject dependencies (#38853)"

---

ads/google/a4a/utils.js
extensions/amp-a4a/0.1/secure-frame.js

Contains some auto linting, but primarily is still to update the origin trial token.

Update privacy sandbox origin trial tokens

---

build-system/tasks/e2e/package-lock.json
build-system/tasks/e2e/package.json

Continuing to bump ChromeDriver! (follow-up on #38965)
* 103: no failures
* 104: [16 non-trivial failures](https://app.circleci.com/pipelines/github/ampproject/amphtml/27672/workflows/6bef27aa-8e18-42a2-b9e1-461fea46a82f/jobs/583337)

🏗 Bump chromedriver to 103

---

ads/vendors/dable.js
ads/vendors/dable.md

Add new optional parameters "articleSection", "articleSection2", "articleSection3" for categories to meet our customer's needs.

✨ Dable: add new optional params for categories

---

3p/vendors/skoiy.js
ads/_config.js
ads/vendors/skoiy.js
ads/vendors/skoiy.md
examples/amp-ad/ads.amp.html
extensions/amp-ad/amp-ad.md

Skoiy is an integrated suite of platforms that simplify and centralize the management, distribution, and monetization of digital media across a suite of independent platforms that fit the needs of each project.
We want to make our technology available and compatible on AMP pages to our clients. We are IAB members & TCF compliant.

✨ [Skoiy ad network] Added Skoiy to ad network list for amp-ads

---

3p/vendors/pubscale.js
ads/_config.js
ads/vendors/pubscale.js
ads/vendors/pubscale.md
examples/amp-ad/ads.amp.html
extensions/amp-ad/amp-ad.md

[PubScale](https://pubscale.com) is an all-in-one platform enabling fast monetization and user acquisition for apps, websites, and games while retaining positive user experiences. With PubScale, you can uplift revenue and analyze business growth all in a single place.
This PR integrates the PubScale ad network, using the <amp-ad> tag.

✨ PubScale ad network registration

---

build-system/tasks/OWNERS

rcebulko is no longer working on AMP.

Remove rcebulko from check-types.js owner required=true

---

extensions/amp-analytics/0.1/vendors/neodata.json

File added in #39064, not sure why this wasn't caught in CI!

Fix JSON formatting in `extensions/amp-analytics/0.1/vendors/neodata.json`

---

ads/vendors/dable.js

This PR enhances 'sendLog' with optional category1, category2, category3 parameters if applicable. This improves event tracking with detailed category information.

✨ Dable: Enhance 'sendLog' by Adding Category Parameters

---

OWNERS

add new root owners

---

OWNERS

Refactor root owners

---

package-lock.json
package.json

0.34 contained an off by 1 bug which is fixed in 0.35
we need to make sure the bug is fixed. previously the bug was not detected by any of our integration or e2e tests so we will need some additional coverage.

bump worker dom to 0.35

---

.github/ISSUE_TEMPLATE/ga4-bug-report.yml

add an issue template that reporters can use to report ga4 and AMP specific bugs

add ga4 bug report template

---

build-system/tasks/check-links.js
extensions/amp-analytics/amp-analytics.md
extensions/amp-story-auto-analytics/amp-story-auto-analytics.md

add links for more detailed instructions on how to use GA4 with AMP

add links for Google Analytics 4 instructions

---

build-system/server/new-server/transforms/css/css-transform.ts
build-system/server/new-server/transforms/tsconfig.json
build-system/server/new-server/transforms/utilities/lazy.ts

had to remove `get` from `Lazy` type and fix tests to remove the target option

Remove target again

---

validator/js/webui/@polymer/webui-mainpage/webui-mainpage.html
validator/js/webui/@polymer/webui-urlform/webui-urlform.html

remove fetch url feature from validator webui

---

extensions/amp-apester-media/0.1/amp-apester-media.js

🚮 Remove 'full-size' button from media

---

extensions/amp-social-share/1.0/test-e2e/test-amp-social-share.js

e.g. failed case: https://app.circleci.com/pipelines/github/ampproject/amphtml/28341/workflows/adb02dbf-a65c-4c55-a7ca-32390edb3ed0/jobs/601390/parallel-runs/0?filterBy=ALL

❄️ Fix flaky `amp-social-share` test due to changes in twitter.com

---

build-system/release-tagger/utils.js

Fixes #39200
Tested manually (https://github.com/ampproject/amphtml/actions/runs/5425812733/jobs/9867078100) (I had to allow this PR's branch in the protection rules, but I've removed it since)

🏗 Reduce batch size in release tagger to avoid timeouts

---

.renovaterc.json
build-system/pr-check/checks.js
build-system/tasks/pr-check.js

🏗 Revert #39229 and disable check `amp check-renovate-config`

---

.renovaterc.json
build-system/pr-check/checks.js
build-system/tasks/pr-check.js

Fixed #39231
This reverts commit a3793d8
Looks like we've been upgraded to v36, letsgo!

🏗 Un-revert #39229 and restore check `amp check-renovate-config`

---

extensions/amp-a4a/rtc-documentation.md
src/service/real-time-config/callout-vendors.js

Order alphabetically and add missing vendors into documentation

📖 Reorder RTC vendors and fix documentation

---

extensions/amp-analytics/0.1/vendors/googleanalytics.json

Maybe there is a better link to link to?

Add deprecation notice for universal analytics

---

extensions/amp-auto-ads/0.1/premiumads-network-config.js
extensions/amp-auto-ads/0.1/test/test-premiumads-network-config.js

https://github.com/ampproject/amphtml/issues/39250

New feature (I2I: Allowing add data-json when premiumads type for amp-auto-ads #39250)

---

extensions/amp-geo/0.1/amp-geo-presets.js

add Sark to European Economic Area list

---

.circleci/install_microsoft_edge.sh
build-system/tasks/runtime-test/custom-launchers.js

🏗 Use Edge Stable instead of Beta

---

validator/js/chromeextension/manifest.json

So that we can release under 1.3.0
This is a manifest-only upgrade w/o functional diff. So I am update minor version only.

Bump chrome extension version

---

extensions/amp-social-share/0.1/amp-social-share.css
extensions/amp-social-share/1.0/amp-social-share.css
extensions/amp-story/1.0/amp-story-tooltip.css
third_party/optimized-svg-icons/amp-social-share-svgs.css

https://github.com/ampproject/amphtml/issues/39375
and for social share.
Check out the Percy link for how the social share looks.

Change twitter logo to X

---

extensions/amp-geo/amp-geo.md

Update the list of supported states + Washington DC
Fixes https://github.com/ampproject/amphtml/issues/39041

Update documentation on US Subdivision detection support

---

build-system/server/app.js
examples/csp.amp.html
validator/testdata/feature_tests/regexps.html
validator/testdata/feature_tests/regexps.out.cpponly
validator/validator-main.protoascii

Fixes https://github.com/ampproject/amphtml/issues/38726
Also need to add this to our backend CSP

add https://cdnjs.cloudflare.com/ajax/libs/font-awesome/ to allowed font provider

---

build-system/global-configs/canary-config.json

🧪 Enable INP metrics on canary at 10%

---

ads/ads.extern.js
ads/vendors/adsviu.md
ads/vendors/seedtag.js
ads/vendors/seedtag.md
examples/amp-ad/ads.amp.html

♻️ Refactor
We are changing our endpoint to init the AMP config.
Now our AMP adapter only need the `adunitId` to initialize and reach our js endpoint.
Old integrations sill compatible

Seedtag - new js endpoint

---

build-system/tasks/e2e/controller-promise.js
build-system/tasks/e2e/describes-e2e.js
build-system/tasks/e2e/network-logger.js
build-system/tasks/e2e/package-lock.json
build-system/tasks/e2e/package.json
build-system/tasks/e2e/selenium-webdriver-controller.js

It bothered me, and makes it harder to debug some stuff later on 😅

🏗 Add typing information to selenium-webdriver in e2e task and make some required changes

---

extensions/amp-story/OWNERS

Stop notifying gmajoulet@, and remove people who left the overall team.

Update OWNERS for amp-story.

---

examples/amp-story/shopping/product.schema.json

📖  [amp-story-shopping]: Fix typo in product schema

---

third_party/subscriptions-project/config.js
third_party/subscriptions-project/swg-gaa.js
third_party/subscriptions-project/swg.js

Cherrypick https://github.com/subscriptions-project/swg-js/pull/3204 into swg project to fix payment issue caused by migration

SwG Release 3579668c - Fix a payment issue caused by O2 migration on mWeb and web

---

OWNERS

add danielrozenberg as root owner

---

extensions/amp-ad-custom/0.1/amp-ad-custom.js

First step of https://github.com/ampproject/amphtml/issues/39443

Add deprecation notice for amp-ad-custom

---

ads/vendors/adman.js
examples/adman.amp.html

Adding some new configuration for the Adman advertising.

✨ add new configuration for grx 

---

validator/js/chromeextension/manifest.json

Only to update the wasm validator.

minor version update for chrome extension

---

ads/_a4a-config.js
build-system/server/app-index/template.js
build-system/test-configs/forbidden-terms.js
extensions/amp-access/0.1/amp-access-server-jwt.js
extensions/amp-iframe/0.1/amp-iframe.js
src/3p-frame.js
src/amp-story-player/amp-story-player-impl.js
src/cookies.js

Remove all src/* and extension/* paths from the cdn.ampproject.org string presubmit check.
Explicitly skip individual lines so we can clearly see where we have anything hardcoded in regards to CDN URL's
Fixes https://github.com/ampproject/amphtml/issues/39328

add additional forbidden term for ampproject.org

---

extensions/amp-mowplayer/0.1/test/test-amp-mowplayer.js

e.g., https://app.circleci.com/pipelines/github/ampproject/amphtml/30226/workflows/18d308f7-f3ad-4157-919b-af19c2cfecce/jobs/649119

❄️ Skip flaky tests

---

.circleci/config.yml

🏗 Unpin Node version in CircleCI

---

.circleci/config.yml

🏗 Add emoji to all CircleCI steps

---

test/fixtures/served/shadow.html

placekitten doesn't always work, which breaks tests :'(
We shouldn't be relying on external pages in our tests anyways

❄️ Fix flaky test `AMP shadow v0 » should layout amp-img component in shadow AMP document`

---

.circleci/config.yml

Possible fix for the problem described in https://github.com/evanw/esbuild/issues/3636#issuecomment-1990936837

🏗 Increase Docker container size for `All Unit Tests` and `End-to-End Tests` jobs on CircleCI

---

extensions/amp-subscriptions-google/0.1/test-e2e/test-amp-subscriptions-google.js

https://github.com/ampproject/amphtml/issues/39914
This is now blocking a few PRs from being merged.

❄️ Skip flaky e2e test amp-subscriptions-google

---

validator/js/nodejs/package-lock.json
validator/js/nodejs/package.json

Updating dependencies and version number. It has not been deployed for 3yrs.
Fixes https://github.com/ampproject/amphtml/issues/39934

Amphtml validator nodejs renovate

---

extensions/amp-consent/amp-consent.md

These seems to be the only references to US Privacy strings. Adding GPPs here.

📖 Add GPP into amp-consent document

---

3p/vendors/momagic.js
ads/_config.js
ads/ads.extern.js
ads/vendors/momagic.js
ads/vendors/momagic.md
examples/amp-ad/ads.amp.html
extensions/amp-ad/amp-ad.md

Opening on behalf of @mmprebid https://github.com/ampproject/amphtml/pull/39956
They are having difficulty creating a workable PR.

MoMAGIC Ad Network - Vendor Registration

---

test/visual-diff/visual-tests.jsonc

Recent flakes:
- https://app.circleci.com/pipelines/github/ampproject/amphtml/30897/workflows/f282d8cb-5906-400d-93e6-add6ae10f59b/jobs/669174
- https://app.circleci.com/pipelines/github/ampproject/amphtml/30880/workflows/2c924d5b-3c4c-4227-9926-1a967f0055ae/jobs/668601
- https://app.circleci.com/pipelines/github/ampproject/amphtml/30640/workflows/4b17688c-3317-41f9-a822-9c6860bb8f17/jobs/661193

❄️ Disable flaky visual diff test

---

extensions/amp-analytics/0.1/test/vendor-requests.json
extensions/amp-analytics/0.1/vendors/colanalytics.json

* add new attributes for user id

♻️ Refactor [Colombia Analytics] - Added new parameters

---

test/integration/test-video-players.js

Build is currently failing frequently for daily motion. Disable now.

Skip amp-dailymotion for video player tests

---

extensions/amp-lightbox/0.1/test/test-amp-lightbox.js
extensions/amp-skimlinks/0.1/test/test-affiliate-link-resolver.js

this was fixed in https://github.com/ampproject/amphtml/pull/40218
see #40214 for more details

unskip some more tests

---

extensions/amp-base-carousel/0.1/test-e2e/test-arrows-non-looping.js
extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js

unskip carousel test thats passing

---

.circleci/config.yml

Fixes https://github.com/ampproject/amphtml/issues/40246

Update browser tools to 1.5.1 to fix firefox installation failure

---

extensions/amp-carousel/0.1/test/test-slidescroll.js
extensions/amp-carousel/0.2/test/test-type-slides.js
extensions/amp-lightbox/0.1/test/test-amp-lightbox.js
extensions/amp-social-share/0.1/test/test-amp-social-share.js

Skip flakey tests, most likely related to selenium webdriver issues.
Added #40258 to track and fix and unskip tests

Fix Flakey Tests

---

extensions/amp-social-share/1.0/test-e2e/test-amp-social-share.js

Tests are consistently failing.

❄️ Disable amp-social-share e2e flaky test

---

ads/google/a4a/cookie-utils.js
ads/google/a4a/test/test-cookie-utils.js
extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js

Fixes issue in GFP header processing logic.

Fix GFP cookie header processing iteration logic.

---

package-lock.json
package.json

Goal is to get rid of 3rd party user errors. Since there are other dependency changes, this might cause some bugs not readily identifiable. We should monitor metrics very closely during the release process.

Upgrade to worker-dom 0.36

---

examples/slikeplayer.amp.html
extensions/amp-slikeplayer/0.1/amp-slikeplayer.js
extensions/amp-slikeplayer/0.1/test/test-amp-slikeplayer.js

- Introduced a new example HTML page for the Slike Player demonstrating its features and viewport behavior.
- Updated amp-slikeplayer.js to support automatic play/pause based on viewport visibility with configurable thresholds.
- Improved iframe source URL for better integration with the player service.

Add Slike Player example page and enhance amp-slikeplayer functionality
