extensions/amp-story/1.0/amp-story.js
Uses an aspect ratio threshold based on the largest one-panel ratio.
The aspect ratio media query has [good browser coverage](https://caniuse.com/mdn-css_at-rules_media_aspect-ratio).
[Demo](https://stamp-ui.web.app/examples/amp-story/amp-story-desktop-one-panel.html) (includes panel positioning code from #34824)
Context / Fixes #34829
=> ✨ `amp-story-desktop-one-panel` Aspect ratio breakpoint

build-system/tasks/OWNERS
Context: https://github.com/ampproject/amphtml/pull/34736 added a global list of externs to one of the typecheck targets. One goal of the type-check effort is to split those externs closer to where they are required. Since this was a broader PR, it was reviewed by another member of the performance WG with less visibility into the type-checking effort. New code added to typechecked directories should pass typechecking, and accidentally pulling in new files/externs can be difficult to revert if the checked-in code doesn't pass. There are almost no circumstances where type-check targets should be altered at this stage, with the exception of PRs that are enabling new ones.
=> 🏗 Require rcebulko for check-types.js

build-system/common/utils.js, build-system/pr-check/build-targets.js
#34887 demonstrated that the `forbidden-terms` file always needs to be checked by removing forbidden terms from files on the allowlist. Because the we run `amp lint --local_changes` in CI now the checks passed but then started failing on main.
Checks run from bad PR
https://app.circleci.com/pipelines/github/ampproject/amphtml/11572/workflows/fa5345cd-0ebe-4663-b8a1-f5905a1b63da/jobs/183106
Future checks run on main
https://app.circleci.com/pipelines/github/ampproject/amphtml/11572/workflows/fa5345cd-0ebe-4663-b8a1-f5905a1b63da/jobs/183106
=> 🏗  🐛  ❄️  always check forbidden terms

extensions/amp-ad/0.1/test/validator-amp-ad.html, extensions/amp-ad/0.1/test/validator-amp-ad.out, extensions/amp-ad/validator-amp-ad.protoascii
Closes https://github.com/ampproject/amphtml/issues/31513
This change allows the top/bottom sticky ads to pass AMP validator.
=> Enable amp-ad sticky type top/bottom

build-system/babel-plugins/babel-plugin-is_minified-constant-transformer/index.js, build-system/test-configs/forbidden-terms.js, src/core/amp-config.extern.js, src/core/assert/dev.js, src/core/mode/for-testing.js, src/core/mode/index.js, src/core/mode/local-dev.js, src/core/mode/minified.js, src/core/mode/test.js, src/core/window/window.extern.js, src/mode.js
Make `#core/mode` direct DCE-able helpers for key properties. Unblocks core migration of a lot of other files which otherwise have only `#core` dependencies
=> ♻️ Moved mode logic into #core/mode

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-ad-badge.css, extensions/amp-story-auto-ads/0.1/amp-story-auto-ads-progress-bar.css, extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
Context / fixes #34785
Positions badge and progress bar based on story panel in new `amp-story-desktop-one-panel` UI.
Progress bar and badge:
=> ✨ `amp-story-desktop-one-panel` Position of ad badge and progress bar in new one-panel UI

extensions/amp-render/amp-render.md
After discussion with @dmanek , I'd like to suggest this extra bit of clarification for what to do if you want to use the `key` attribute with data fetched via `amp-script`.
=> 📖 Clarify amp-render documentation on "key" attribute

build-system/eslint-rules/no-duplicate-import.js
We have a custom rule that merges import declarations from the same location. It deletes the duplicate import statement, but leaves a blank line in its place, segmenting the imports into unrelated groups which are sorted separately. 
Example:
This fix removes the newline after the removed import.
=> 🐛 Fix local/no-duplicate-import autofix bug

tsconfig.json
According to https://www.typescriptlang.org/tsconfig, `exclude` is a top-level option and should not go under `compilerOptions`. Noticed this because VSCode shows red squiggly lines in the editor when you open `tsconfig.json`.
Follow up to #34901
=> 🏗 Move `exclude` out of `compilerOptions` in `tsconfig.json`

extensions/amp-base-carousel/1.0/component.js, extensions/amp-lightbox-gallery/1.0/component.jss.js, extensions/amp-lightbox-gallery/1.0/consumer.js, extensions/amp-lightbox-gallery/1.0/provider.js, extensions/amp-lightbox-gallery/1.0/test/test-component.js
This PR adds the following user interface features:
- Display lightboxed elements in a grid in the open gallery
- Allow toggling between grid and carousel views in the open gallery
- Display SVGs for the toggle-to-grid and toggle-to-carousel button, swapping them in place depending on the current state
- Unit tests
It also adds a change to `BaseCarousel` to propagate its `onClick` prop to the `Scroller` as opposed to the `ContainWrapper`, so as to exclude arrows (which already have a click-behavior) from triggering it.
Partial for #32759
=> ✨ Bento: LightboxGallery grid view 

build-system/common/utils.js, build-system/tasks/lint.js
Some time ago CI was updated to run lint with the `local_changes` flag to speed up the process. However, the issues related to usage of "forbidden terms" are only displayed when the `forbidden-terms` file is linted. This meant that any change that involved "forbidden terms" would pass initially, then fail when a full lint was run on main.
I solved this issue in #34897 by updating the `getFilesToCheck` helper function to ensure that the `forbidden-terms` file is always checked. What I did not know was that the function is also used by the `check-owners` task which now fails when it is called with the `local_changes` flag (if an OWNERS file has actually been changed).
Before:
After:
#34986
=> update forbidden-terms check to only run during lint

src/preact/base-element.js, src/preact/parse-props.js
**summary**
Mapping element attributes to Preact props is a key aspect of being able to server-render Bento components. In order to accomplish this, we need the mapping to be able to occur independent of a an AMP environment. As a first step to accomplish this, I've extracted `collectProps` to its own file. There should be no actual code changes.
=> ♻️  PreactBaseElement: extract collectProps

extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/test/test-amp-story-page.js
`999999ms` is a special value passed from the viewer as the `storyNextUp` param that indicates we are in the control group of the auto advance experiment.
#33969
=> 🐛 [amp-story] Don't set auto-advance when in control

extensions/amp-story/1.0/amp-story-open-page-attachment.js, extensions/amp-story/1.0/test/test-amp-story-page.js
Build AMP Cache URLs for inline attachment CTA when served from AMP Cache.
Early return on publisher's origin, or if an AMP Cache URL is already provided.
=> Build AMP Cache URLs for inline attachment CTA when served from AMP Cache.

extensions/amp-tiktok/validator-amp-tiktok.protoascii
Google3 version of this file was fixed to have the correct regex "\\d" vs. "\d". Making this change here to make sure the files match.
=> 🐛 Update regex to match google3 version.

extensions/amp-story/1.0/amp-story-page-attachment.js
Moves the building of the outlink preview to layoutCallback.
This element for reference:
=> Move building outlink attachment to layoutcallback.

validator/cpp/engine/parse-layout.cc, validator/cpp/engine/parse-layout.h, validator/cpp/engine/validator-internal.cc, validator/cpp/htmlparser/node.cc, validator/cpp/htmlparser/node.h, validator/cpp/htmlparser/parser.cc, validator/cpp/htmlparser/parser_test.cc, validator/cpp/htmlparser/token.h, validator/cpp/htmlparser/tokenizer.cc, validator/cpp/htmlparser/tokenizer.h, validator/cpp/htmlparser/tokenizer_test.cc
Sync for validator/cpp/htmlparser
Sync for validator/cpp/engine
This PR syncs cl/378533243 for the two folders in one time, because neither can pass circle ci test by itself.
=> Sync for validator/cpp/{engine,htmlparser}

tsconfig.json
The built-in VSCode typescript extension is showing what looks like a bogus error in `tsconfig.json` that mentions a random source file each time it appears.
Since this is an error from the extension and we don't actually generate any TS -> JS output for `amphtml` source, this PR updates the settings in `tsconfig.json` to avoid emitting any output, and if necessary, use the `dist` directory instead of overwriting source files. These two changes appear to have silenced the error above.
- https://www.typescriptlang.org/tsconfig
- https://github.com/Microsoft/TypeScript/issues/14538
- https://stackoverflow.com/questions/42609768/typescript-error-cannot-write-file-because-it-would-overwrite-input-file
=> 🏗 Fix errors emitted by the VSCode typescript plugin

validator/cpp/engine/validator-internal.cc, validator/js/engine/htmlparser-interface.js, validator/js/engine/validator.js, validator/testdata/feature_tests/regexps.out
- cl/380257173 Adds error for invalid AMP cache domain.
This PR syncs cl/380257173 for the two folders in one time, because neither can pass circle ci test by itself.
=> Sync for validator/cpp/engine and Validator rollup

extensions/amp-ad/0.1/amp-ad-ui.js
We need to add this messaging to ensure that sites using <amp-ad sticky> will need to change to <amp-ad sticky=bottom>. Currently, only sites coordinated with Kargo know this since the api is not documented yet, so this should not become a big surprise.
=> Deprecate notice for amp-ad sticky with empty attribute value

build-system/test-configs/dep-check-config.js, extensions/amp-story-360/0.1/amp-story-360.js, extensions/amp-story-auto-ads/0.1/story-ad-localization.js, extensions/amp-story-auto-ads/0.1/test/test-story-ad-localization-strings.js, extensions/amp-story-education/0.1/amp-story-education.js, extensions/amp-story-interactive/0.1/amp-story-interactive-quiz.js, extensions/amp-story-interactive/0.1/interactive-disclaimer.js, extensions/amp-story/1.0/amp-story-consent.js, extensions/amp-story/1.0/amp-story-draggable-drawer.js, extensions/amp-story/1.0/amp-story-embedded-component.js, extensions/amp-story/1.0/amp-story-hint.js, extensions/amp-story/1.0/amp-story-info-dialog.js, extensions/amp-story/1.0/amp-story-open-page-attachment.js, extensions/amp-story/1.0/amp-story-page-attachment.js, extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/amp-story-share-menu.js, extensions/amp-story/1.0/amp-story-share.js, extensions/amp-story/1.0/amp-story-system-layer.js, extensions/amp-story/1.0/amp-story-unsupported-browser-layer.js, extensions/amp-story/1.0/amp-story-viewport-warning-layer.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/pagination-buttons.js, extensions/amp-story/1.0/simple-template.js, extensions/amp-story/1.0/test/test-amp-story-localization-strings.js, src/OWNERS, src/service/localization/OWNERS, src/service/localization/index.js, src/service/localization/strings.js, test/unit/test-localization.js
amp-story & pals are the only consumers of the localization service, and that service is the only consumer of `localization-strings.js`. This PR moves those strings + the service into the `#service/localization` submodule as part of a broader effort to clean up the flat files in `src/` directory (related to #32693)
=> ♻️ Move localization-strings under localization service

builtins/amp-layout/amp-layout.js
**summary**
Extracts `buildDOM` from `buildCallback` so that it can be called separate from the rest of init (for server render).
=> amp-layout: extract buildDOM #compiler

extensions/amp-analytics/0.1/events.js
We're now polyfilling `new Set(iterable)` (#35019), so the IE-specific workaround for passthrough is no longer needed.
=> 🚮 Remove IE-specific workaround for `new Set(iterable)`

extensions/amp-video/0.1/test/test-video-cache.js, extensions/amp-video/0.1/video-cache.js
Video caching: rewrite `/i/` URLs to `/mbv/`.
If a video source is an image extension, e.g. `.gif`, the Cache URL service would return an URL containing `/i/` instead of the expected `/c/`.
cc @Gregable FYI
=> Video caching: rewrite /i/ URLs to /mbv/.

build-system/test-configs/dep-check-config.js, extensions/amp-base-carousel/1.0/component.js, extensions/amp-base-carousel/1.0/scroller.js, extensions/amp-lightbox-gallery/1.0/amp-lightbox-gallery.js, extensions/amp-lightbox-gallery/1.0/base-element.js, extensions/amp-lightbox-gallery/1.0/consumer.js, extensions/amp-lightbox-gallery/1.0/provider.js, extensions/amp-lightbox-gallery/1.0/storybook/Basic.amp.js, extensions/amp-lightbox-gallery/1.0/storybook/Basic.js, extensions/amp-lightbox-gallery/1.0/test/test-amp-lightbox-gallery.js, extensions/amp-lightbox-gallery/1.0/test/test-component.js
This PR supports grouping functionality in `amp-lightbox-gallery` and `LightboxGallery` as part of #32759. It behaves as follows:
- Any `img` or `amp-img` with the `lightbox` attribute get grouped in a single group by default, called `"default"`.
- All `img` or `amp-img` inside `amp-base-carousel` or `amp-stream-gallery` with the `lightbox` attribute get grouped in their own encapsulated lightbox group. You can think of this as one distinct group per lightboxed carousel. These are named `carousel0`, `carousel1`, etc. by default.
- Groups can be named with a non-default value by giving the `lightbox` attribute a value. This doesn't appear to be documented currently but is a behavior of 0.1. One perk of doing this for standalone `img` and `amp-img` elements is that they can be subdivided …
=> Bento `amp-lightbox-gallery` grouping behavior

validator/cpp/engine/WORKSPACE, validator/cpp/htmlparser/WORKSPACE
`re2` updated from `master` to `main` causing a breakage. use `main` instead for `http_archive` of `re2`
see `re2` [commit here](https://github.com/google/re2/commit/ccdbd348259434cca6c66c66a35c5ef71ff3ee1a)
=> update re2 master to main

extensions/amp-video/1.0/base-element.js
Fixes the video element not resizing to the outer box size.
This component exports styles from two different files. Ensure that a concatenated string for both is used.
=> 🐛 Add missing `shadowCss` for video

extensions/amp-fit-text/0.1/amp-fit-text.js
**summary**
This PR hides `amp-fit-text` until font size calculation is complete. 
For our example doc at `examples/amp-fit-text.amp.html`:
- before: 0.055 CLS
- after: 0.000 CLS
=> amp-fit-text: fix cls by hiding until font size calculation

extensions/amp-lightbox-gallery/1.0/amp-lightbox-gallery.js, extensions/amp-lightbox-gallery/1.0/base-element.js, extensions/amp-lightbox/1.0/amp-lightbox.js, extensions/amp-lightbox/1.0/base-element.js, extensions/amp-sidebar/1.0/amp-sidebar.js, extensions/amp-sidebar/1.0/base-element.js
Moves calls to `setAsContainer` and `removeAsContainer` to the AMP layer in the components that call them (`amp-lightbox`, `amp-lightbox-gallery`, `amp-sidebar`). Also makes these calls optional due to #34820. 
Note that tests already exist to ensure these are called at the precise time.
=> Use `setAsContainer` and `removeAsContainer` in AMP mode only

package-lock.json, package.json
**summary**
- Bumps the version number to the latest worker-dom.
- This includes `localStorage` support in nodom mode.
=> bump worker-dom to 0.30.1

.github/ISSUE_TEMPLATE/cherry-pick-request.yml
Step 1 of https://github.com/ampproject/amphtml/issues/35065
- Adds `formats` dropdown that is required by https://status.amp.dev
- Removes progress to be later added as a comment for stable/lts cherry-picks
=> 🏗  Update cherry-pick request template for status page automation

builtins/amp-layout/amp-layout.js
**summary**
Reverts the meaningful changes from https://github.com/ampproject/amphtml/pull/34770.
The root cause of the issue was that `parseLayout` _is not_ equivalent to `this.getLayout()`.
- parseLayout just ensures the input layout type is valid and returns a `Layout`
- `this.getLayout` would use the "effective layout" calculated by calling `applyStaticLayout`.
=> Revert: "amp-layout: extract buildDOM #compiler (#34770)"

docs/release-schedule.md
**Two main changes:**
- Fixed doc to indicate that we do release to beta / experimental channels during freeze weeks.
- Changed a few instances of the word "build" to "release" for consistency.
=> 🏗 Update release (freeze) documentation

test/unit/test-amp-layout.js
**summary**
Adds two basic unit tests for `<amp-layout>`. 
The second test in particular would have caught https://github.com/ampproject/amphtml/issues/35154
=> Add unit tests for amp-layout

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-ad/0.1/amp-ad-3p-impl.js, extensions/amp-ad/0.1/amp-ad-ui.js, extensions/amp-ad/0.1/test/test-amp-ad-ui.js, extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
Send a client error when loading the second (and after) sticky ads.
=> ✨ Prevent multiple sticky ads from being loaded on one page

build-system/status-page/comment.js, build-system/status-page/common.js, build-system/status-page/incident.js
Step 2 of https://github.com/ampproject/amphtml/issues/35065
- `comment.js` will be called when a cherry-pick request is created for stable and/or lts
- `incident.js` will be called when the progress comment is edited
=> 🏗  Add node scripts for status page automation

.github/workflows/status-page.yml
Step 4 of https://github.com/ampproject/amphtml/issues/35065
- Adds a `🌸 Cherry-Pick Progress 🌸` comment when cherry-pick request issues are open for stable/lts. 
- Creates, updates, and resolves incidents on status.amp.dev when on-duty edits the comment.
=> 🏗  Add GitHub Action to sync cherry-picks with status page

extensions/amp-story/1.0/animation.js
Closes https://github.com/ampproject/error-reporting/issues/94
When the story animations are not initialized (eg: because the story page is not visible yet, due to prerender mode), calling `pause` will throw an error because `this.players_ == null`.
There was a try/catch that was catching this error that was removed in #34466 that is needed.
https://github.com/ampproject/amphtml/pull/34466/files#diff-c5a86c80a77ae2a9abb4ac5ff1e9ef10f58c0e9262baa64273be1b4424d7161bL383-L388
We can re-introduce this try-catch and prevent these errors from surfacing, which is ok since the story is not initialized when the pause method is called. Changing the comment to more clearly explain why the method call can fail
An alternative is to change the behavior of pause by doing `if (!this.players_) {return;}` …
=> 🐛  [Story animation] Fix error thrown when user pauses before animation runs.

build-system/compile/bundles.config.js, build-system/tasks/check-types.js, build-system/tasks/helpers.js, build-system/test-configs/dep-check-config.js, src/compiler/index.js
**summary**
Creates a new binary for the Bento Compiler project.
The first iteration acts as an identity function.
The purpose of this PR is to get bikeshedding out of the way re. the file location, name etc.
**binary contents**
```js
;
(function(){"use strict";function compileHtml(a){return a}function compileAst(a){return a}globalThis.compileHtml=compileHtml;globalThis.compileAst=compileAst})();//# sourceMappingURL=compiler.js.map
```
=> 💅  / 🏗 Create new binary for compiler #compiler

extensions/amp-story/1.0/amp-story-page-attachment.js
Users could swipe up and then click the anchor. We disable this to not trigger side effects like:
- native environments that intercept navigation events and open two webviews/CCTs
- potential different analytics triggering in web environment
=> Prevent double navigation from page-outlink.

extensions/amp-story/1.0/background-blur.js
- Pre draws image to an off-screen canvas, then fades in the composed image.
- Adjusts animation to match system layer progress bar.
- Separates draw logic into functions.
This creates a smooth transition:
https://user-images.githubusercontent.com/3860311/125135823-a2de4c00-e0d7-11eb-9130-0af69e84c219.mp4
Without this the image will flash as it's faded in:
https://user-images.githubusercontent.com/3860311/125135854-b12c6800-e0d7-11eb-8852-cae568d03dac.mp4
=> ✨ `amp-story-desktop-one-panel` `background-blur` Pre draw image to fade in

extensions/amp-fit-text/0.1/amp-fit-text.js
**summary**
Using the clone API is both faster and more worker-dom friendly than using `innerHTML`
=> amp-fit-text: avoid innerHTML serialize/parse

build-system/global-configs/canary-config.json, build-system/global-configs/client-side-experiments-config.json, build-system/global-configs/prod-config.json, examples/amp-story/performance/lcp-compressed.html, examples/amp-story/performance/lcp.html, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story.js
Launches the `story-load-first-page-only` experiment to 10%.
Also, since experiments don't start with `amp-` (everything is amp), removed the prefix `amp-` from the experiment name
=> 🚀 [Story performance] Launch first page load experiment to 10%

extensions/amp-video/0.1/amp-video.js, extensions/amp-video/0.1/test/test-amp-video.js
Use remote video cache over AMP Cache video cache.
Given the following configuration:
```
<amp-video
cache="google"
src="example-com.cdn.ampproject.org.com/foo.mp4"
amp-orig-src="example.com/foo.mp4"
```
The `cdn.ampproject.org` will NO LONGER take precedence, and the `cache="google"` will be used.
=> Use remote video cache over AMP Cache video cache.

.github/workflows/publish-npm-packages.yml
Fix bug where stable releases were expected to already exist on npm when they were published as nightly. This is not always true in the case of cherry-picks.
(Below you'll see me trying to test on this branch. The environment protection rules where you can only run a GitHub action on `main` worked. I was able to test this on my own repo)
=> 🏗  Publish stable releases that have cherrypicks

validator/testdata/feature_tests/forms.html, validator/testdata/feature_tests/forms.out, validator/validator-main.protoascii
Fixes #35177
Allows `<input capture type=file>`.
=> add capture for inpute[type=file] on AMP format only

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js, extensions/amp-facebook-comments/1.0/amp-facebook-comments.js, extensions/amp-facebook-like/1.0/amp-facebook-like.js, extensions/amp-facebook-page/1.0/amp-facebook-page.js, extensions/amp-facebook/1.0/amp-facebook.js, extensions/amp-twitter/1.0/amp-twitter.js, src/3p-frame.js, src/preact/component/3p-frame.js, test/unit/3p/test-3p-frame.js
Remove as no longer needed. The experiment was launched to 100%.
=> 🧪 Remove 3p-vendor-split experiment code path

build-system/tasks/storybook/amp-env/main.js, build-system/tasks/storybook/amp-env/webpack.config.js, build-system/tasks/storybook/env-utils.js, build-system/tasks/storybook/preact-env/main.js, build-system/tasks/storybook/preact-env/webpack.config.js
https://github.com/ampproject/amphtml/issues/30954#issuecomment-868679665
```diff
examples/storybook/preact:
...
- runtime~main.6bbc6c672e356009e233.manager.bundle.js
- runtime~main.b0af52cf.iframe.bundle.js
- vendors~main.3e7ae188.iframe.bundle.js
- vendors~main.3e7ae188.iframe.bundle.js.LICENSE.txt
- vendors~main.3e7ae188.iframe.bundle.js.map
- vendors~main.fb93791576556ba81a2a.manager.bundle.js
- vendors~main.fb93791576556ba81a2a.manager.bundle.js.LICENSE.txt
+ runtime-main.6bbc6c672e356009e233.manager.bundle.js
+ runtime-main.b0af52cf.iframe.bundle.js
+ vendors-main.3e7ae188.iframe.bundle.js
+ vendors-main.3e7ae188.iframe.bundle.js.LICENSE.txt
+ vendors-main.3e7ae188.iframe.bundle.js.map
+ vendors-main.fb93791576556ba81a2a.manager.bundle.js
+ …
```
=> 🏗 Omit tilde (`~`) in Storybook output filenames

src/amp.js
This PR adds a message only visible when loading an AMP document in Internet Explorer to inform of deprecation.
=> ✨ Message announcing IE Deprecation

build-system/tasks/get-zindex/index.js
This should help avoid synchronization issues when running this inside Docker containers (#35176)
=> 🏗🐛 Change get-zindex to await on child process to close, not the child process's stdout stream

extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Server side google ads are using this param value to serve the correct size ads. Before this change doubleclick would send the <amp-ad> element size, but adsense would send the viewport size. This changes adsense to also send element size.
=> 🐛 [story-ads] Use ad slot size in spsa param

extensions/amp-ad/0.1/amp-ad-ui.js
The previous version would cause a hard error and the ad is no longer loaded. This PR changes to a soft error message. I do not think it is currently being used by kargo on a campaign though.
=> Change deprecation to soft failure

build-system/common/esbuild-babel.js, build-system/tasks/runtime-test/helpers.js
We're seeing occasional errors during integration tests because the step that cleans old build artifacts can clash with the (too eager) instantiation of the babel cache. See https://github.com/ampproject/amphtml/issues/35257#issuecomment-881592688.
- Delay instantiation of the babel cache to just before its first use. (Artifact cleanup is guaranteed to be done by then.)
- **Bonus fix:** Cosmetic fix to the logging statement that says what kind of build is being tested against.
Fixes #35257
=> 🏗 Fix bug in instantiation of babel cache

extensions/amp-iframe/0.1/test/test-amp-iframe.js
Tests 'is sent' and 'is sent with empty fields when consent service not
available' used one or two calls of `await macroTask()` before checking
whether the `MessageType.SEND_CONSENT_DATA` listener triggered
`sendConsentDataToIframe_` successfully. These tests were failing due to
a race condition:
consent-data message
✗ is sent
AssertionError: expected stub to have been called exactly once, but
it was called 0 times
✗ is sent with empty fields when consent service not available
AssertionError: expected stub to have been called exactly once, but
it was called 0 times
Wait for `sendConsentDataToIframe_` to be called at least once, then allow
another event queue to flush before verifying listener handled message
exactly once.
=> ❄️ test-amp-iframe: Fix consent message races

extensions/amp-experiment/0.1/test/test-amp-experiment.js, extensions/amp-experiment/1.0/test/test-amp-experiment.js, extensions/amp-facebook/0.1/test/test-amp-facebook.js
`expectAsyncConsoleError` requires at least one argument, the message string or regex to expect. The incorrect usage causes tests to silently fail due to known issue https://github.com/mochajs/mocha/issues/94
=> ❄️ Fix incorrect usage of expectAsyncConsoleError(...) in tests

src/amp.js
Removes experiment enabling for `no-boilerplate`.
=> 🧪 Remove enabled experiment based on boilerplate

extensions/amp-autocomplete/amp-autocomplete.md
=> `amp-autocomplete`: Fix email-specific code samples

build-system/compile/build-constants.js
**summary**
Fixes https://github.com/ampproject/amphtml/issues/35325
I created a bug in local development when merging https://github.com/ampproject/amphtml/pull/34327.
I had assumed `isForTesting` corresponded to when the flag `--fortesting` was passed, but really the value should always be true unless `amp dist` is used _without_ the fortesting flag.
cc @calebcordry
=> 🐛  fix build-constant isForTesting

extensions/amp-lightbox-gallery/1.0/base-element.js
`amp-lightbox-gallery` allows `lightbox`-ing a few AMP components. Given #34820 allows some Bento components to have either `amp-` or `bento-` prefix depending on its mode of usage, `amp-lightbox-gallery` should support both varieties of these components.
Note that while `amp-lightbox-gallery` supports `amp-img`, this PR does not add `bento-img` tag to its img tag list because the Bento version of `amp-img` is `img`.
=> `amp-lightbox-gallery`: Support bento- prefixed selectors

test/unit/test-3p.js
It fails because test-3p.js uses modules and is not loadable to the browser. It changes to use a browser side JS.
Close https://github.com/ampproject/amphtml/issues/35315
=> ✅ Fix failing 3p unit test

.eslintrc.js, build-system/babel-config/pre-closure-config.js, build-system/compile/build-constants.js, build-system/compile/compile.js, build-system/test-configs/forbidden-terms.js, src/core/mode/for-distribution.js, src/core/mode/index.js, src/core/mode/local-dev.js, src/core/mode/prod.js, src/core/mode/test.js
**summary**
The `IS_FORTESTING` variable is set to false _only_ when `amp dist` is called without `--fortesting`.
It doesn't directly have anything to do with "testing" (i.e. `amp unit`, `amp integration` etc).
This PR flips the variable name to `IS_PROD`, which IMO ends up clearer.
Alternative/supplementary fix for https://github.com/ampproject/amphtml/issues/35325
=> build-constants/mode: rename from isForTesting --> isProd

extensions/amp-video/0.1/video-cache.js
Only serve evergreen non cached video sources to crawlers.
=> Only serve evergreen non cached video sources to crawlers.

test/unit/test-friendly-iframe-embed.js
The browser somehow triggers a resize event after iframe is being created, therefore causes a mutateElement call (https://github.com/ampproject/amphtml/blob/main/src/friendly-iframe-embed.js#L412). The event emits probabilistically.
Moving spy to after iframe being created will prevent browser resize event from affecting the test.
=> ✅ Fix FIE unit test failure

build-system/tasks/e2e/describes-e2e.js, extensions/amp-base-carousel/0.1/test-e2e/test-autoadvance.js, extensions/amp-base-carousel/0.1/test-e2e/test-multi-visible-single-advance.js, extensions/amp-carousel/0.1/test-e2e/test-slidescroll-autoplay.js, extensions/amp-consent/0.1/test-e2e/test-amp-consent-client-side.js, extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side-expire-cache.js, extensions/amp-consent/0.1/test-e2e/test-amp-consent-server-side.js, extensions/amp-consent/0.1/test-e2e/test-cmp-ui-interaction.js, extensions/amp-date-picker/0.1/test-e2e/test-blocked-dates.js, extensions/amp-script/0.1/test-e2e/test-amp-script.js, extensions/amp-story-auto-ads/0.1/test-e2e/test-amp-story-auto-ads.js, extensions/amp-story-player/0.1/test/test-e2e/test-amp-story-player-prerender.js, test/e2e/test-amp-story-player-prerender.js
Reducing the maximum test timeout (and overriding it in the tests that currently exceeded it) is the first step in preventing new long running tests from being introduced. In the future I would like to disallow usage of `this.timeout` to control newly added slow running tests.
=> ✅  ♻️  Reduce default e2e test timeout

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, build-system/test-configs/forbidden-terms.js, extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js, extensions/amp-ad/0.1/amp-ad-ui.js, extensions/amp-ad/0.1/amp-ad.css, extensions/amp-ad/0.1/test/test-amp-ad-ui.js, extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
Create an experiment to turn amp-sticky-ad element into an amp-ad element. In theory they should act the same. Set the experiment group info for Adsense/Doubleclick.
=> Create an experiment to turn amp-sticky-ad to amp-ad sticky implementation

extensions/amp-twitter/1.0/storybook/Basic.js
We are trying to deprecate f.js (https://github.com/ampproject/amphtml/issues/35349), in favor of vendor-specific js for better performance. PTAL
=> Replace f.js with twitter.js for 3p iframe

3p/integration.js, 3p/remote.html
As the first step of https://github.com/ampproject/amphtml/issues/35349, we send out deprecation notice to those using f.js
=> Add deprecation notice to 3p iframe f.js

extensions/amp-lightbox-gallery/1.0/amp-lightbox-gallery.js, extensions/amp-lightbox-gallery/1.0/base-element.js, extensions/amp-lightbox-gallery/1.0/component.type.js, extensions/amp-lightbox-gallery/1.0/provider.js, extensions/amp-lightbox-gallery/1.0/test/test-amp-lightbox-gallery.js
Partial for #32759, this PR supports the following pre-existing analytics events on `amp-lightbox-gallery`:
- `lightboxOpened`
- `thumbnailsViewToggled`
- `descriptionOverflowToggled`
=> Bento `amp-lightbox-gallery`: Support analytics events

3p/integration.js
The logger is not initialized until `init` call, so we need to warn afterwards.
=> Fix 3p integration deprecation warning

examples/amp-ad-exit-conversion.html, extensions/amp-ad-exit/0.1/amp-ad-exit.js, extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js
This allows ad networks to monitor the status of the new `attribution-reporting` API rollout.
Partial #35347
=> ✨Introduce new ATTRIBUTION_REPORTING_STATUS macro for amp-ad-exit

build-system/babel-config/minified-config.js, build-system/babel-config/pre-closure-config.js, build-system/babel-plugins/babel-plugin-amp-mode-transformer/index.js, build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/no-transform/options.json, build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/nomodule/input.js, build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/nomodule/options.json, build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/nomodule/output.mjs, build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/transform/input.js, build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/transform/options.json, build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/transform/output.mjs, build-system/compile/build-constants.js, build-system/test-configs/forbidden-terms.js
**summary**
- amp-mode-transformer now runs for both .mjs and .js output
- `.version` and `.isEsm` are now transformed
- the babel plugin receives `BUILD_CONSTANTS` as an argument
- updates tests
**results**
Double digit changes copy/pasted below:
```
dist/v0/amp-install-serviceworker-0.1.js: Δ -0.35KB
dist/v0/amp-access-poool-0.1.js: Δ -0.32KB
dist/v0/amp-access-laterpay-0.1.js: Δ -0.33KB
dist/v0/amp-access-laterpay-0.2.js
dist/v0/amp-access-scroll-0.1.js: Δ -0.20KB
dist/v0/amp-next-page-0.1.js: Δ -0.19KB
dist/shadow-v0.js: Δ -0.12KB
dist/v0.js: Δ -0.15KB
dist/v0/amp-story-0.1.js: Δ -0.79KB
dist/v0/amp-story-1.0.js: Δ -0.79KB
```
@ampproject/wg-performance
=> amp-mode-transformer: transform two more keys

extensions/amp-fit-text/0.1/amp-fit-text.js, src/builtins/amp-layout/amp-layout.js, src/compiler/types.js
**summary**
- Creates docs for `buildDom`. Could not get a `@see` or `@{link}` working...no matter what I tried. If anyone knows how to make a link actually work in VS Code...I'm all ears. 
- Simplifies the function signature from `(Document, Element) => *` to `Element => *`
=> buildDom: simplify interface, improve docs

css/amp-story-player-shadow.css, extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js, src/amp-story-player/amp-story-player-impl.js, test/unit/test-amp-story-player.js
Uses story viewer messaging service to listen to ui state update events.
Toggles visibility of the prev and next story buttons on the component based on UI state. 
Hides code behind experiment.
Removes old comment.
https://user-images.githubusercontent.com/3860311/127017462-9d1ce22f-b8e8-487c-86d6-8c4cdd942017.mp4
=> ✨ [Amp story player] [Desktop panels player] Hide buttons if full-bleed story.

.circleci/config.yml
As described in https://circleci.com/docs/2.0/caching/?section=pipelines#source-caching
Credits used and workflow duration are barely affected, but the upsides are:
* quicker restarts for flaky jobs (~10-15 seconds shorter due to having the git repository pre-cached)
* no longer need to `curl` the maybe_gracefully_halt.sh file
* being better citizens of the net by reducing the number of times we fetch the entire repo from GitHub 😃
Raw data: https://docs.google.com/spreadsheets/d/1R_rihHtAbf56eAj1dUvABjakyrDFy29Y6Vce2_dWG-A/edit
=> 🏗 Cache .git directory in CircleCI builds

.circleci/config.yml, .circleci/restore_build_output.sh, build-system/pr-check/bundle-size-module-build.js, build-system/pr-check/bundle-size-nomodule-build.js, build-system/pr-check/utils.js
The bundle-size job is now the longest running single job, and takes longer than the rest of the job layers combined. This PR splits the production-ready build steps into to separate jobs, and moves the actual bundle-size calculation to its own separate sub-job (running on a medium docker container instead of xlarge)
Runtime improves significantly (from ~13:58 to ~11:47 on average, 19% faster) with a marginal decrease in credit use (2,241 to 2,235, should be dismissed as the measurements' margin of error)
Raw data: https://docs.google.com/spreadsheets/d/1X_ge9s172IH7ilBQUWhak7Srk4KICv05SmdkYp5RbbY/edit
=> 🏗 Parallelize bundle-size build jobs on CircleCI

examples/amp-story/interactive_img_polls.html, examples/amp-story/interactive_img_quizzes.html, extensions/amp-story-interactive/0.1/amp-story-interactive-img.css, extensions/amp-story/1.0/amp-story.css
Puts a background color in place of a missing image for image quizzes and image polls; the background color is a grey-ish color that depends on the theme of the component
Demos (see second-to-last and third-to-last pages):
https://interactive-img.web.app/missing-img/quiz.html
https://interactive-img.web.app/missing-img/poll.html
/cc @mszylkowski 
/cc @processprocess
=> 🖍 [Story interactive] Styling for Image Quizzes and Polls with Missing Images

extensions/amp-lightbox-gallery/1.0/amp-lightbox-gallery.js, extensions/amp-lightbox-gallery/1.0/test/test-amp-lightbox-gallery.js, extensions/amp-lightbox/1.0/amp-lightbox.js, extensions/amp-lightbox/1.0/test/test-amp-lightbox.js
Final feature for Bento `amp-lightbox` #31052 and partial for Bento `amp-lightbox-gallery` #32759, for feature conformance with 0.1 counterparts.
=> Use history service in `amp-lightbox:1.0` and `amp-lightbox-gallery:1.0` in AMP layer

extensions/amp-video-iframe/amp-video-iframe.md
On the the [amp.dev component page for `amp-video-iframe`](https://amp.dev/documentation/components/amp-video-iframe/), the AMP page is invalid due to "Invalid URL protocol 'hhttps:' for attribute 'href' in tag 'a'.". This change fixes the broken URL.
https://amp.dev/documentation/components/amp-video-iframe/
=> 🐛 Fix broken link & invalid AMP page on amp.dev amp-video-iframe component documentation

src/preact/index.js
While `preact.Fragment` is a function, `react.Fragment` is not. This PR nests with `preact.createElement` to account for remapping `preact` -> `react`. Fixes #35412.
=> Wrap preact.Fragment with preact.createElement

build-system/compile/bundles.config.extensions.json
Without this, this will 404: 
- https://cdn.ampproject.org/v0/amp-timeago-1.0.css
- https://cdn.ampproject.org/v0/amp-video-1.0.css
=> Release existing CSS files for Bento components

extensions/amp-consent/0.1/consent-config.js, extensions/amp-consent/0.1/test/test-consent-config.js
This is fine to do since the `SOURCE_URL` can be extracted from the referrer anyway, and this resolves it according to origin.
=> ✨ Allow expanding `SOURCE_URL` in `amp-consent` URLs

extensions/amp-story/1.0/amp-story.js
Prefer [`screen.orientation.lock`](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock) to [`screen.lockOrientation`](https://developer.mozilla.org/en-US/docs/Web/API/Screen/lockOrientation).
=> Improve screen orientation locking for stories

build-system/tasks/helpers.js
**summary**
The first in a series of small cleanups to our build helpers. The improvements are extractions from a much larger https://github.com/ampproject/amphtml/pull/35201
This PR
- Updates `esbuild` to write only to memory instead of `fs`
- Removes esbuild minification as it doesn't add much in conjunction with terser. It also makes enabling private prop mangling impossible (which we aren't doing yet....but stay tuned).
- Terser updates
- Strip comments
- Operate in module mode depending on `argv.esm`
- Operate in-mem instead of reading/writing to fs.
- Use builtin sourcemap conversion instead of deferring to `remapping`
- Adds a preamble of `;`, like we do with closure.
Next up improvements:
- Combining `compileWithEsbuild` and `compileUnminifiedJs`
- `finishBundle` should also …
=> build-system: improve terser/esbuild integration

build-system/pr-check/bundle-size-module-build.js, build-system/pr-check/bundle-size-nomodule-build.js, build-system/pr-check/utils.js
This is required for PRs that _do not_ change the RUNTIME target, because we still need to call `amp bundle-size --on_skipped_build`
/cc @samouri
=> 🏗 Allow the bundle-size job to run even if the builds were skipped

extensions/amp-story-auto-ads/amp-story-auto-ads.md
📖 Documentation
Fixes #35425 by adding in an example of who to use the remote config for the amp story auto ads component.
=> Updated document with use cases of remote config

extensions/amp-fit-text/0.1/amp-fit-text.js, extensions/amp-fit-text/0.1/test/test-amp-fit-text.js, src/builtins/amp-layout/amp-layout.js, test/unit/builtins/test-amp-layout.js
**summary**
Adds basic unit tests for `buildDom` in both `amp-fit-text` and `amp-layout`. The tests assert that the outerHTML result of calling `buildCallback` and `buildDom` should be the same for a given component.
=> ✅ buildDom: add tests for amp-fit-text and amp-layout

extensions/amp-story-interactive/amp-story-interactive.md, extensions/amp-story/amp-story-grid-layer.md
Use ```amp-layout``` instead of ```div``` to fix invalidation issues on https://amp.dev/documentation/components/amp-story-grid-layer/.
/cc @sebastianbenz @matthiasrohmer
=> 🐛 amp-story-grid-layer: Fix AMP invalidation error in documentation

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, extensions/amp-consent/0.1/amp-consent.js, extensions/amp-consent/0.1/consent-ui.js, extensions/amp-consent/0.1/test/test-amp-consent.js, extensions/amp-consent/0.1/test/test-consent-ui.js, src/custom-element.js, test/unit/test-custom-element.js, tools/experiments/experiments-config.js
=> 🚮 Remove experiment `amp-consent-granular-consent`

build-system/babel-plugins/babel-plugin-amp-mode-transformer/index.js, build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/no-transform/input.js, build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/no-transform/output.js, build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/transform/input.js, build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/transform/output.mjs
**summary**
Blocks https://github.com/ampproject/amphtml/pull/35298
Teaches amp mode transformer how to inline `mode.version()`.
=> babel: teach amp mode transformer about #core/mode

3p/vendors/jixie.js
**summary**
Generated via `amp lint --fix`
**timeline**
- Jixie PR is created and makes modifications (https://github.com/ampproject/amphtml/pull/35128)
- `eslint`  rules update PR is created (https://github.com/ampproject/amphtml/pull/35454)
- Jixie PR merges (https://github.com/ampproject/amphtml/commit/2d970c1c465c9529c583d470865d71fef10df774)
- `eslint` PR merges...but new rules weren't checked against recent changes (https://github.com/ampproject/amphtml/commit/2d970c1c465c9529c583d470865d71fef10df774).
Fix after created a new lint rule.
=> build: run amp lint --fix to address import order of jixie

extensions/amp-subscriptions/amp-subscriptions.md
* Removes unsupported ```layout="responsive"``` from ```img```-tag
* Adds mandatory ```width``` and ```height``` to ```amp-img```-tag
/cc @sebastianbenz @matthiasrohmer
=> 🐛 amp-subscriptions: Fix img attributes in documentation

3p/integration-lib.js, ads/google/a4a/utils.js, build-system/test-configs/dep-check-config.js, build-system/test-configs/forbidden-terms.js, extensions/amp-ad-network-valueimpression-impl/0.1/amp-ad-network-valueimpression-impl.js, extensions/amp-addthis/0.1/amp-addthis.js, extensions/amp-analytics/0.1/iframe-transport.js, extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js, src/3p-frame.js, src/amp-shadow.js, src/amp.js, src/core/mode/index.js, src/core/mode/version.js, src/iframe-attributes.js, src/inabox/amp-inabox.js, src/log.js, src/mode.js, src/runtime.js, src/service/url-replacements-impl.js
**summary**
Adds `.version` to `#core/mode`. Removes it from `src/internal-version.js`.
=> core mode: add version()

build-system/test-configs/forbidden-terms.js, extensions/amp-youtube/0.1/test/test-amp-youtube.js, extensions/amp-youtube/1.0/test/test-component.js
1. Update some non-inclusive terms to match spellings that were missed.
1. Update `checkProse` so that it implies `checkInTestFolder`, since prose can occur anywhere.
1. Update files to remove non-inclusive terms.
=> 🏗 Update forbidden terms for matching and check in test folders

build-system/tasks/dep-check.js
Currently, depCheck does not take into account 3p vendor entrypoints. This PR adds them so that these entrypoints are gone through by the depCheck.
=> 🏗 Add 3p iframe vendor files to depCheck targets

extensions/amp-ad/amp-ad.md
Update documentation to reflect `<amp-ad sticky=bottom>` usage.
=> 📖 Update amp-ad sticky ad documentation

src/service/performance-impl.js, test/unit/test-performance.js
Fixes https://github.com/ampproject/amphtml/issues/34383.
As reported by @diasflack,
> Maybe, the solution will be to design slightly different logic for not Embedded pages.
=> 🐛  performance-impl: origin should use value directly from PO

build-system/tasks/storybook/preact-env/webpack.config.js, extensions/amp-twitter/1.0/storybook/Basic.js
Otherwise we get `IS_PROD is not defined` and similar - [example](https://storage.googleapis.com/amp-test-website-1/amp_nomodule_e51a76dd6761004d76c6f440a0cd39047e7caeff/examples/storybook/preact/index.html?path=/story/twitter--moments).
=> 🍱  Bento Storybook: Define all `BUILD_CONSTANTS`

docs/spec/amp-actions-and-events.md
This PR updates the AMP.navigateTo documentation to note that it does not support standard URL substitutions.
This change mirrors the change made in #3865, in the ampproject/amphtml repository. 
Resolves issue #35538.
=> 📖  Update AMP.navigateTo documentation re: URL subsitutions.

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, examples/amp-consent/amp-consent-3p-postmessage.html, extensions/amp-consent/0.1/amp-consent.js, extensions/amp-consent/0.1/test/test-amp-consent.js, tools/experiments/experiments-config.js
Launched ~5 months ago, getting ahead of the automated removal at the beginning of next month.
=> 🚮 Remove `tcf-post-message-proxy-api` experiment

build-system/test-configs/forbidden-terms.js, src/core/error/message-helpers.js, src/error-reporting.js, src/log.js, src/mode.js, src/service/viewer-impl.js, test/unit/test-log.js
- move `setReportError` to `error-reporting`
- move user embed error message helpers to `#core/error/message-helpers`
- general reduction in complexity and verbosity of some `Log` methods/constructor helpers
- deleting methods that aren't used anywhere
=> ♻️ Another pass at reducing complexity around `Log`

.circleci/config.yml, .github/workflows/cross-browser-tests.yml, build-system/pr-check/safari-tests.js
With all the recent work done to speed up CI, the coast is clear to start moving our cross browser tests from GH Actions to CircleCI.
- Move all macOS testing to CircleCI
- Reuse build output from the previous stage
- **Bonus:**
- Clean up / standardize executor names
- Consolidate some setup steps
- Surround the main step of each job with ⭐ to make it easy to spot
There's no need for parallelization since only a subset of tests are run on macOS.
- https://support.circleci.com/hc/en-us/articles/360047639331-Node-version-on-macOS-images
- https://support.circleci.com/hc/en-us/articles/360056920051--Error-untarring-cache-when-running-a-macOS-job
- https://support.circleci.com/hc/en-us/articles/360056461992-Enabling-safaridriver-support-on-macOS
=> 🏗 Move macOS testing from GH Actions to CircleCI

.circleci/config.yml, build-system/pr-check/nomodule-build.js, build-system/pr-check/pr-deploy.js, build-system/pr-check/utils.js, build-system/tasks/visual-diff/index.js
Most of AMP's testing jobs depend on the nomodule (test) build during CI, and cannot start until that job completes.
- Move the PR deploy steps out of the critical path, allowing tests to begin a couple mins sooner
- Create a separate `PR Deploy` job to carry out those steps only during PR builds
- **Bonus:** Move `PERCY_TOKEN` extraction into the visual testing task (co-locate with related code and reduce repetition)
Addresses https://github.com/ampproject/amphtml/pull/35455#discussion_r685362997
=> 🏗 Move deployment of PR output (minified + storybook) to a separate CI job

examples/amp-story/ads/remote.json, examples/amp-story/story-ad-remote-config.html, src/utils/dom-ancestor-visitor.js
🐛 Bug fix
Updated ad example for remote auto ads config to use a working ad that will always show up,
regardless of user preferences or settings. This was due to the ad not showing up in the safari browser.
Tested and works now with chrome and safari.
=> Update ad example for remote auto ads config

.circleci/config.yml, .github/workflows/cross-browser-tests.yml, build-system/pr-check/firefox-tests.js
Picking up from where #35455 left off.
- Move all Firefox testing to CircleCI
- Reuse build output from the previous stage
- Clean up internally and externally visible job names (easier to reference in the workflow)
- Standardize cross-browser job names so they're alphabetized
Addresses https://github.com/ampproject/amphtml/pull/35455#discussion_r685373170
=> 🏗 Move Firefox testing from GH Actions to CircleCI

.circleci/config.yml
Restoring/saving Git cache on MacOS ends up being slower than a cold `git clone`
Also disables the call to `check_config.sh` because it now [breaks the job](https://app.circleci.com/pipelines/github/ampproject/amphtml/14475/workflows/b1731fe2-ad13-4cd4-ac1c-d923ef6222d3/jobs/243293)
Before | After
--------- | ------
=> 🏗 Disable .git caching for MacOS jobs on CircleCI

extensions/amp-apester-media/0.1/amp-apester-media.js
Makes #35457 a user error.
Also, there were a lot of nested promises. This PR turns them into chained promises. Took a stab at it, feel free to take over the PR.
=> 🐛 Make amp-apester-media use user error

extensions/amp-story/1.0/amp-story.js
On iPads, `orientation` is not defined. 
An error is being thrown when trying to access the `screen.orientation.lock` property.
This PR checks if `orientation` exists before accessing `lock`.
Related to the work in #35478
=> 🐛 [Amp story] Null check on screen.orientation

.circleci/config.yml, .circleci/initialize_repo.sh
**Background:** With the introduction of `.git` caching on CircleCI, the repo initialization job often ends up with an outdated view of the `main` branch that is restored from the cache. This can cause our check for config freshness to incorrectly pass when it should fail. (The risk is that PRs will run an incomplete set of tests and go on to break `main` once merged.)
- Fix `initialize_repo.sh` to actually update `main`. (It was doing a fetch, but wasn't updating the local `main` branch.)
- Move the check to the `Initialize Repository` job so failures are detected at the very start, and logs are less confusing.
**Screenshots:** [link](https://app.circleci.com/pipelines/github/ampproject/amphtml/14704/workflows/e58b1336-9a74-4abb-89ab-e4eab438ac69)
=> 🏗 Fix CircleCI config check so it works with `.git` caching

ads/vendors/springAds.md
That text funnels to https://amp.dev/support/faq/platform-and-vendor-partners/ and makes it look weird
=> Remove extra wording from springAds readme doc

test/e2e/test-amp-bind-brightcove.js
This appears to be causing the test case to return control early and continue running in the background, resulting in concatenated test suite names during `amp e2e`... and maybe bogus test failures?
=> ✅ Remove a couple unnecessary `async`s from `amp-bind` e2e test

build-system/babel-plugins/babel-plugin-transform-stringish-literals/index.js, build-system/babel-plugins/log-module-metadata.js, build-system/babel-plugins/static-template-metadata.js
=> babel-plugins typecheck: stringish-literals

build-system/tasks/3p-vendor-helpers.js, build-system/tasks/extension-helpers.js, build-system/tasks/helpers.js
**summary**
- Rename `compileJsWithEsbuild` --> `esbuildCompile` (similar to closureCompile).
- Use `esbuildCompile` for unminified builds
=> 🚀  ♻️  build-system: merge unminified and vendor codepath

extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js, src/3p-frame.js, test/unit/3p/test-3p-frame.js
This change enables 3p iframe Bento components to reference the mode without having to be on an AMP document.
=> `3p-frame`: Prefer `#core/mode` to `getMode`

validator/testdata/transformed_feature_tests/amp-img.html, validator/testdata/transformed_feature_tests/amp-img.out, validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.html, validator/testdata/transformed_feature_tests/i_amphtml_sizer_child.out, validator/validator-main.protoascii
This PR is the first step for resolving #35485, after which we will update cache and optimizer transforms to apply `slot="i-amphtml-svc"` to `i-amphtml-sizer` elements to be consistent with https://github.com/ampproject/amphtml/blob/07771ad684334ee96894f70a8ea7f839c738a8a3/src/static-layout.js#L163
=> Allow `i-amphtml-sizer[slot="i-amphtml-svc"]` on transformed documents.

extensions/amp-fit-text/1.0/base-element.js, extensions/amp-fit-text/1.0/component.js, extensions/amp-fit-text/1.0/component.type.js, extensions/amp-fit-text/1.0/storybook/Basic.js, extensions/amp-fit-text/1.0/test/test-component.js
This change updates the name of the released Preact/React components on npm from `FitText` to `BentoFitText`.
=> Rename `FitText` Component as `BentoFitText`

build-system/babel-config/import-resolver.js, build-system/eslint-rules/no-deep-destructuring.js, build-system/release-tagger/create-release.js, build-system/tasks/release/index.js, src/preact/component/3p-frame.js
**summary** 
Partial for https://github.com/ampproject/amphtml/issues/35694
Explicitly bans these kinds of patterns:
```js
const [[x], y] = arr;
```
```js
const [{x}] = arr
```
=> eslint rule: no-deep-destructuring should handle ArrayPattern

extensions/amp-base-carousel/1.0/component.js, extensions/amp-base-carousel/1.0/scroller.js, extensions/amp-base-carousel/1.0/test/test-component.js
This PR modifies `rtl` to return a string, and `group` to be `undefined` when irrelevant (as opposed to `false`). This fixes the following issues described in #35553:
```
* Warning: Received `false` for a non-boolean attribute `rtl`. If you want to write it to the DOM, pass a string instead: `rtl="false"` or `rtl={value.toString()}`. If you used to conditionally omit it with `rtl={condition && value}`, pass `rtl={condition ? value : undefined}` instead.
* Warning: Received `false` for a non-boolean attribute `group`. If you want to write it to the DOM, pass a string instead: `group="false"` or `group={value.toString()}`. If you used to conditionally omit it with `group={condition && value}`, pass `group={condition ? value : undefined}` instead.
```
=> 🐛 Bento Carousel: Fix unrecognized attributes

build-system/common/utils.js, build-system/tasks/build.js, build-system/tasks/dist.js, build-system/tasks/firebase.js, build-system/tasks/performance/compile-scripts.js
Previously, we used to pre-build the AMP runtime (minified or unminified) via an in-process function call to the entry point function of `amp dist` or `amp build`. This broke recently, most likely due to the interaction between nodejs module load, cache instantiation, and actual building of code.
This PR switches the pre-building step to invoke `amp dist|build` in a separate process instead of calling `doDist()|doBuild()`. This fixes the bugs around in-process building, and lets us simplify / consolidate all calls from testing tasks to the pre-build function `buildRuntime()`.
As a follow up, we could consider renaming the `--compiled` flag to something like `--minified` for better usability.
=> 🏗 Use a different process to pre-build AMP while running tests

build-system/babel-plugins/babel-plugin-amp-mode-transformer/index.js, build-system/babel-plugins/babel-plugin-amp-mode-transformer/test/fixtures/transform-assertions/nomodule/output.mjs
Fixes https://github.com/ampproject/amphtml/issues/35655
`getMode().development` should correspond to whether or not the page has development params in the URL. I mistakenly disabled this for all builds in a previous PR (https://github.com/ampproject/amphtml/pull/35294).  It should only be disabled for `.mjs` builds for smaller bundle size.
=> 🐛 amp-mode-transformer: Only resolve development mode for esm builds

ads/google/a4a/test/test-utils.js, ads/google/a4a/utils.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
If the google ads is rendered within `<amp-ad sticky=bottom`, we still want it to carry sticky ads attributes. This google parameters function does not have a test right now, so I am deferring that.
@zombifier
=> ✨ Add act=lb for amp-ad sticky ads

extensions/amp-analytics/0.1/analytics-root.js
`AnalyticsRoot.getViewer()` was introduced in #8805 and used as a helper in a method that has since been removed:
https://github.com/zhouyx/amphtml/blob/33a0d3c643947b9f9a9820b23b4bc62db0de962f/extensions/amp-analytics/0.1/events.js#L423-L441
The only comparable piece of code similar to the above is `createReportReadyPromiseForDocumentHidden_`, which now uses the ampdoc instead:
https://github.com/ampproject/amphtml/blob/38d96dac71275e901683097053ffe07690f40a3a/extensions/amp-analytics/0.1/events.js#L1674-L1694
=> amp-analytics: Remove unused `getViewer` method

build-system/tasks/compile-jison.js, build-system/tasks/extension-helpers.js
- Fix `amp build` on Windows (the path being passed to `compileJison()` was incorrectly formatted on Windows)
- **Bonus:** Speed up `compileJison()` by eliminating ~200 parallel + synchronous + unnecessary `mkdirSync` operations
**Passing logs:** [here](https://github.com/ampproject/amphtml/runs/3355857514?check_suite_focus=true)
Addresses https://github.com/ampproject/amphtml/pull/35630#issuecomment-899945493
=> 🏗 Fix unminified build on Windows

build-system/release-tagger/label-pull-requests.js, build-system/release-tagger/test/label-pull-requests.test.js, build-system/release-tagger/utils.js
Removes labels from PRs in the case of rollbacks.
=> 🏗  Remove label from PRs for release tagger

validator/js/engine/validator_test.js, validator/testdata/feature_tests/a_private_click_measurement.html, validator/testdata/feature_tests/a_private_click_measurement.out, validator/validator-main.protoascii
Fixes #35067 by allowing the following attributes on `a` tags for AMP Websites and AMP Ads only:
```
attributiondestination
attributionexpiry
attributionreportto
attributionsourceeventid
attributionsourceid
conversiondestination
impressiondata
impressionexpiry
reportingorigin
```
=> Allow private click measurement attributes

.github/workflows/cross-platform-builds.yml, build-system/pr-check/cross-platform-builds.js
This should speed up our post-merge cross-platform build verification workflow a little and make errors (e.g. https://github.com/ampproject/amphtml/pull/35630#issuecomment-899945493) easier to spot. Does not affect PR checks in any way.
**Example:** https://github.com/ampproject/amphtml/actions/runs/1144580544
**Screenshot:**
Follow up to #35713
=> 🏗 Matrixify `amp build | dist` checks on GH actions

extensions/amp-tiktok/amp-tiktok.md
Removed excess space in ```width```-attribute, that caused https://amp.dev/documentation/components/amp-tiktok/ to be invalid.
/cc @sebastianbenz @matthiasrohmer
=> 🐛 amp-tiktok: remove excess space from document

.circleci/fetch_merge_commit.sh, .circleci/initialize_repo.sh
This PR solves the corner case where if a PR originates directly from a branch on the main `ampproject/amphtml` repo, and if that branch gradually goes out of date, we still do a full refresh of the current view of `main`, `origin/main`, and other repo branches _before_ running CI checks.
Note that on git repos, we need to fetch the `main` and `origin/main` branches in a separate step because it also needs to update the _local_ `main` branch on the VM. (Hence the two step `git fetch`.)
With these precautions, we should no longer see PRs that edit only a few files, but are [tested as if](https://app.circleci.com/pipelines/github/ampproject/amphtml/15096/workflows/9abab3f1-0458-492b-8dec-00a1fdcca93c/jobs/259490?invite=true#step-113-10) they edit a whole lot more files. …
=> 🏗 Refresh git branches before potentially early-exiting during repo setup

.circleci/fetch_merge_commit.sh, .circleci/initialize_repo.sh
Turns out we can't refresh the `main` branch during push builds because it's already refreshed and checked out.
This PR does the refresh step only for non-main branches.
Follow up to #35742.
=> 🏗 Refresh git cache only for non-main branches

examples/ad-lightbox.amp.html, examples/amp-date-countdown.amp.html, examples/amp-next-page.amp.html, examples/amp-smartlinks.html, examples/amp-story/interactive_quizzes.html, examples/amp-story/interactive_size.html, examples/viqeo.amp.html, test/fixtures/e2e/amp-base-carousel/captions.amp.html, test/fixtures/served/ampdoc-with-messaging.html, test/manual/amp-analytics/analytics-shadow.html, test/manual/amp-flying-carpet-media.amp.html, test/manual/amp-lightbox-gallery.amp.html, test/manual/amp-list/infinite-scroll-2.amp.html, test/manual/amp-sidebar-focus.amp.html, test/manual/autofocus-on-show.html, test/manual/video-caching.amp.html
We're doing away with the AMP copyright in our source files. See https://github.com/ampproject/amphtml/pull/35717#issue-715220675.
This PR cleans up all non-validator HTML files (there are only a handful remaining). It also removes blank lines left behind from a previous cleanup.
=> 📖 Remove AMP Copyright notice from non-validator HTML files

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/name-frame-renderer.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad/0.1/amp-ad-3p-impl.js, src/experiments/ads-initial-intersection-exp.js, test/integration/test-amp-ad-3p.js
**summary**
Reviving a very old effort. I had tried to move measurements of ad iframe `initialIntersection` param to async, but the experiments showed a negative enough impact to ad performance that I didn't feel comfortable pushing through. Instead now opting to move this codepath to ads-specific code. First step is removing the experiment.
Partial for https://github.com/ampproject/amphtml/pull/34133
=>  ♻️  ads-initialIntersection: clean up failed experiment

OWNERS
Add wg-caching as owners for `validator-*.out.cpponly`files.
Example where just these files aren't owned by wg-caching:
https://github.com/ampproject/amphtml/pull/35748/checks?check_run_id=3376047276
=> Add wg-caching as owners of validator-*.out.cpponly

extensions/amp-story/1.0/amp-story-embedded-component.js
Hides the tooltip overlay arrows when a tweet is focused on desktop one panel UI mode.
=> 🐛 [Amp story] Toggle desktop attribute on tooltip overlay

build-system/tasks/extension-helpers.js
The `wrapper` for bento components is defined for use with custom element builds, not preact/react builds. For npm binaries, the `"wrapper": "bento"` designation was being split up via this helper and written as a `bent` to the start of all npm build binaries:
https://github.com/ampproject/amphtml/blob/c43ba128ad9d11794a77ce79a7414b3feaf8d45e/build-system/tasks/helpers.js#L426-L439
Another option could be to guard for an invalid wrapper, which also fixes the issue (but may have more consequences given more code paths may be affected):
```diff
diff --git a/build-system/tasks/helpers.js b/build-system/tasks/helpers.js
index a92748b0ee..3cc029ab2a 100644
--- a/build-system/tasks/helpers.js
+++ b/build-system/tasks/helpers.js
@@ -428,9 +428,13 @@ async function esbuildCompile(srcDir, …
```
=> npm builds should not use `options.wrapper`

build-system/compile/helpers.js
Addresses https://github.com/ampproject/amphtml/pull/35675#discussion_r693232730. Likely not causing any issues since `sourcesContent` isn't included in the first place unless `--full_sourcemaps` is present. A less defensive version of this PR would be to remove the logic entirely.
https://github.com/ampproject/amphtml/blob/c43ba128ad9d11794a77ce79a7414b3feaf8d45e/build-system/compile/compile.js#L260
=> Update sourcemap helper according to @jridgewell feedback.

extensions/amp-story/1.0/amp-story-system-layer.css
Displays the pause/play controls when in desktop panel mode.
Fixes #35640
=> 🐛 [Amp story] Desktop one panel play button

src/custom-element.js, src/service/extension-script.js, test/unit/test-custom-element-v1.js
This fixes a bug caused by easylist's hiding of any element with a `.amp-unresolved` class.
Since the initial releases of AMP, we've added an `.amp-unresolved` class to our custom elements to allow publishers to style elements while the element's JS file is downloading. As soon as it was downloaded, we immediately upgraded the element and removed the `.amp-unresolved` class. Essentially "downloaded" and "upgraded" meant the same thing.
Now, easylist blocks certain JS files from being downloaded. This left large empty blocks on the page, because the element can never be upgraded to actually run. They took advantage of the `.amp-unresolved` class to hide the element from the page. Now the blocked elements are hidden from page when the JS is blocked.
This actually has a nasty side-effect …
=> Remove amp-unresolved when extension downloads in R1

babel.config.js, build-system/babel-config/import-resolver.js, build-system/babel-plugins/babel-plugin-transform-inline-isenumvalue/index.js
I'm tired of seeing `Unrecognized Babel caller` in my logs.
=> 🏗 Ensure every babel invocation has a name

build-system/test-configs/forbidden-terms.js, extensions/amp-iframe/0.1/amp-iframe.js, extensions/amp-iframe/0.1/test/test-amp-iframe.js
**summary**
`getIntersectionElementLayoutBox` is used in two places:
1. As part of `Ads` code (amp-a4a, amp-ad-3p-impl, amp-ad-network-adsense, amp-ad-network-doubleclick)
2. In the implementation of `base-element.getIntersectionChangeEntry`. This in turn is only called by the same Ads files as (1), but with the addition of `name-frame-renderer.js` which is also part of a4a.
Unless there is a codepath where Ads utilizes `<amp-iframe>` under the hood, it should be safe to remove this measurement API.
**note**: I did find a suspicious codepath around checking to see if the iframe is `adLike` or a tracking pixel, but it did not seem to use the measured iframe value. They both depend on `CE.getLayoutSize` (which depends on resources system size)
=> 🚮 Remove getIntersectionElementLayoutBox from amp-iframe

extensions/amp-twitter/0.1/amp-twitter.md, extensions/amp-twitter/1.0/README.md, extensions/amp-twitter/amp-twitter.md
=> 📖 `bento-twitter` documentation

examples/amp-story/attachment.html, extensions/amp-story/1.0/amp-story-page-attachment.js
Adds `title` attribute to the draggable-drawer header if defined.
Will default to `data-title` if `title` is not defined.
This is communicated in our [docs](https://amp.dev/documentation/components/amp-story-page-attachment/#title-%28optional%29) and needs to be reflected in our code.
=> 🐛 [Amp story page attachment] Propagate title attribute to draggable drawer header

extensions/amp-fit-text/0.1/amp-fit-text.js, extensions/amp-fit-text/0.1/build-dom.js, extensions/amp-fit-text/0.1/test/test-amp-fit-text.js, src/builtins/amp-layout/amp-layout.js, src/builtins/amp-layout/build-dom.js, src/compiler/builders.js, src/compiler/index.js, src/compiler/polyfills.js, src/compiler/shame.extern.js, test/unit/builtins/test-amp-layout.js
**summary**
Make compiler.js bundle runnable
- Extracts buildDoms to their own file to reduce import-based side-effects.
- Creates a `self` polyfill
If the code is still not runnable in V8 directly, this will at least get us partway.
1. `npx amp dist --noextensions`
2. Enter the node repl via `node`
3. `require('./dist/compiler.js')` should not throw
=> Make `compiler.js` runnable within a node.js environment

extensions/amp-date-display/format.js
- Fixes compatibility in very old browsers that don't support `.find()`
- Fixes https://github.com/ampproject/error-reporting/issues/103
=> ♻️ Remove use of `.find`

build-system/tasks/storybook/amp-env/main.js
Preact environment had been updated to this syntax, but the AMP environment had not.
=> 🐛 Use `/register` for Storybook addons

extensions/amp-ad-network-doubleclick-impl/0.1/sra-utils.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-sra.js
Some networks use a comma in a network code part to denote a child identifier. This comma however was kept when serialized, causing it to be treated as a separate network code. This change fixes it by converting it to a colon.
=> 🐛 Fix child identifiers in amp-ad network=doubleclick SRA IUs.

build-system/tasks/extension-helpers.js, examples/bento/api.html, examples/bento/no-v0.html, extensions/amp-base-carousel/1.0/README.md, test/fixtures/e2e/bento/minimal.html
`amp-*.js` binaries for Bento-compatible extensions provide an `<amp-*>` element that can be used **with** `v0.js`, and a `<bento-*>` element that can be used **without** `v0.js`.
We'd like that Bento elements are used from `bento-*.js` in Bento mode.
Eventually, this binary will only provide the Bento element, while `amp-*.js` provides only an AMP element. In the meantime, we alias the multiple-compatibility binary so that `bento-*.js` can be used as soon as possible. This unblocks release since we'll be able to include the scripts in Bento mode using the correct URL.
=> 🏗 Alias `amp-*.js` binaries as `bento-*.js`

.circleci/config.yml, .github/workflows/cut-nightly.yml
This allows us to better control the permissions model wrt GitHub API tokens (replaces #35878)
=> 🏗 Move nightly branch cut job from CircleCI to GitHub Actions

extensions/amp-story/1.0/amp-story-open-page-attachment.js
Prevents display issues if `cta-accent-color` is not defined.
Throws a warning to notify user to define the `cta-accent-color` attribute.
Fixes #34983
=> 🐛 [Amp story page outlink] Default outlink color and warning

extensions/amp-story/1.0/amp-story.css
Context / Fixes #35381
iOS 15 expands images on long press. This breaks our long-press to pause UX. 
This PR prevents the image from being selectable by globally removing pointer events from images .
With this fix TalkBack is still able to select and read the `alt` text of images.
We have [this code](https://github.com/ampproject/amphtml/blob/11a2daaca49c45df1159ee0ea0c4187af30f22ab/extensions/amp-story/1.0/amp-story.js#L791-L799) to prevent `contextmenu` events. 
It does not help in this case since `contextmenu` does not fire. 
Events logged from `monitorEvents(window)`:
=> 🐛 [Amp story] Prevent pointer events on images

extensions/amp-accordion/1.0/amp-accordion.js, extensions/amp-accordion/1.0/base-element.js, extensions/amp-accordion/1.0/component.js, extensions/amp-accordion/1.0/component.type.js, extensions/amp-accordion/1.0/storybook/Basic.js, extensions/amp-accordion/1.0/test/test-component.js, extensions/amp-instagram/1.0/storybook/Basic.js, extensions/amp-video/1.0/storybook/Basic.js, extensions/amp-video/1.0/storybook/VideoIframe.js, extensions/amp-youtube/1.0/storybook/Basic.js
Changes name of all Accordion-related Preact component to prefix with `Bento`
=> ♻️ Docs/bento accordion

build-system/compile/bundles.config.extensions.json, extensions/amp-date-display/1.0/base-element.js, extensions/amp-date-display/1.0/component.js, extensions/amp-date-display/1.0/component.type.js, extensions/amp-date-display/1.0/storybook/Basic.js, extensions/amp-date-display/1.0/test/test-component.js
Rename all date-display-related Preact components to prefix with `Bento` 
ensures that css is published
Readme.md updated in separate PR
=> ♻️ Docs/bento date display

extensions/amp-fit-text/1.0/storybook/Basic.js
Last week's Bento meeting, we decided the Storybook titles should not be `Bento` prefixed so that they can be more easily delineated in the sidebar where samples are displayed.
=> Update `BentoFitText` Storybook title to 'FitText'

build-system/tasks/dist.js
This is a small optimization, shaving ~1.5 minutes of wall time for developers and ~1 minute of VM time with no noticeable side effects. I reran the CircleCI workflow on this PR and on the `main` commit it's based on 3 times each, raw data:
Attempt | Nomodule (Prod) | Nomodule (Test) | Module (Prod) | Module (Test) | VM time | Wall time
------- | ------- | ------- | ------- | ------- | ------- | -------
main (1) | 8:19 | 8:43 | 8:24 | 8:22 | 33:48 | 15:08
main (2) | 8:45 | 8:04 | 8:39 | 8:27 | 33:55 | 13:14
main (3) | 7:52 | 8:15 | 7:41 | 8:23 | 31:11 | 13:51
main (avg) | | | | | **32:58** | **14:43**
PR (1) | 8:10 | 7:47 | 7:34 | 8:54 | 33:25 | 14:16
PR (2) | 7:18 | 7:18 | 8:15 | 8:32 | 31:23 | 12:44
PR (3) | 7:35 | 6:59 | 7:51 | 7:37 | 30:02 | 12:21
PR (avg) | | | | | **31:37** | …
=> 🏗 Parallelize `dist` steps

extensions/amp-base-carousel/1.0/README.md
=> 📖 BentoBaseCarousel README code fixes

extensions/amp-inline-gallery/1.0/amp-inline-gallery-pagination.js, extensions/amp-inline-gallery/1.0/amp-inline-gallery-thumbnails.js, extensions/amp-inline-gallery/1.0/base-element.js, extensions/amp-inline-gallery/1.0/component.js, extensions/amp-inline-gallery/1.0/component.type.js, extensions/amp-inline-gallery/1.0/pagination.js, extensions/amp-inline-gallery/1.0/storybook/Basic.js, extensions/amp-inline-gallery/1.0/test/test-component.js, extensions/amp-inline-gallery/1.0/thumbnails.js
Rename inline-gallery-related Preact components to prefix `Bento`
Update Readme.md in a separate PR
=> ♻️ Docs/bento inline gallery

build-system/compile/bundles.config.extensions.json, extensions/amp-date-countdown/1.0/base-element.js, extensions/amp-date-countdown/1.0/component.js, extensions/amp-date-countdown/1.0/component.type.js, extensions/amp-date-countdown/1.0/storybook/Basic.js, extensions/amp-date-countdown/1.0/test/test-component.js
Renames date-countdown-related Preact components to prefix with `Bento`
Adding Readme.md in separate PR
=> ♻️ Docs/bento-date-countdown

extensions/amp-stream-gallery/1.0/base-element.js, extensions/amp-stream-gallery/1.0/component.js, extensions/amp-stream-gallery/1.0/component.type.js, extensions/amp-stream-gallery/1.0/storybook/Basic.js, extensions/amp-stream-gallery/1.0/test/test-component.js
Rename all stream-gallery-related Preact components to prefix `Bento`
update Readme.md in a separate PR
=> ♻️ docs/bento-stream-gallery

build-system/tasks/make-extension/index.js, build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/base-element.js, build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/component.js, build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/component.type.js, build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.js, build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/test/test-component.js
Replaces `__component_name_pascalcase__` with `Bento__component_name_pascalcase__` in all cases except:
- `class Amp__component_name_pascalcase__ extends BaseElement`
- Storybook `title: '__component_name_pascalcase__'`
=> Update Storybook template to differentiate between `Foo` and `BentoFoo`

src/ssr-template-helper.js, test/unit/test-ssr-template-helper.js
This can happen whenever the XHR proxy server returns an error and
doesn't include the HTML to render the submit-failure template (e.g.,
AMP CORS failure, unreachable proxy). Sever-side rendering of template
is an implementation detail of AMP for Email that developers shouldn't
care about so it makes sense to change this to one that would make more
sense for developers.
/to @caroqliu
=> Make amp-form failure message developer-friendlier

extensions/amp-consent/0.1/consent-ui.js
Because of the rendering cycle, a `promptUI` that contains an `amp-iframe` may cause content flashing.
`promptUISrc` can be used instead and prevent that issue.
=> 📖 Warn when using a consent promptUI that contains an iframe

extensions/amp-accordion/1.0/storybook/Basic.js, extensions/amp-accordion/1.0/storybook/Bind.amp.js, extensions/amp-animation/0.1/storybook/Basic.amp.js, extensions/amp-animation/0.1/storybook/Random.amp.js, extensions/amp-base-carousel/1.0/storybook/Basic.amp.js, extensions/amp-base-carousel/1.0/storybook/Basic.js, extensions/amp-brightcove/1.0/storybook/Basic.amp.js, extensions/amp-brightcove/1.0/storybook/Basic.js, extensions/amp-date-countdown/1.0/storybook/Basic.amp.js, extensions/amp-date-countdown/1.0/storybook/Basic.js, extensions/amp-embedly-card/1.0/storybook/Basic.js, extensions/amp-facebook/1.0/storybook/Basic.js, extensions/amp-fit-text/1.0/storybook/Basic.amp.js, extensions/amp-fit-text/1.0/storybook/Basic.js
=> ♻️ Use Storybook `args` (second round)

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg-gaa.js, third_party/subscriptions-project/swg.js
=> SwG Release 0.1.22.183

.circleci/config.yml
This is to prevent new stable releases of Chrome from causing test failures. Eg, the Chrome 93 release caused several tests failures that made `main` red until the tests were skipped. This delayed a cherry-pick we're working on, since the new release (on on top of old code) also picked up Chrome 93.
This should be updated regularly, hopefully with a chance to test Chrome releases during the Beta period so we can proactively fix issues.
=> 🏗 Pin CircleCI's Chrome version

extensions/amp-story/1.0/animation.js
When state is prerender ([example story](https://www.herzindagi.com/amp-stories/hindi/diary/pani-puri-recipe-article-655#visibilityState=prerender)) long pressing on the story will throw an error because it will try to pause and resume the animations on the page. This makes it so that long pressing breaks the system layer, since the long press logic is interrupted by the error and doesn't execute until the end.
Adding a `try/catch` just like the `pause` method could work, but when releasing the long press, the system layer is shown but the animations don't play (you need to come back to the page for them to start playing).
We can use the `start` method instead of `resume` so that the animations will be initiated if they are not, and then resumed (the implementation of `start` is `if …
=> 🐛 [Story animations] Fix prerender resume animation

docs/spec/amp-html-responsive-attributes.md, docs/spec/bento-common-props.md, extensions/amp-accordion/1.0/README.md, extensions/amp-accordion/1.0/storybook/Basic.amp.js
Adds documentation 1.0 amp-accordion
=> 📖 docs(amp-accordion): add readme docs for 1.0 amp-accordion

extensions/amp-video/0.1/test-e2e/test-amp-video-flexible-bitrate.js
To unblock `main` builds
e.g., https://app.circleci.com/pipelines/github/ampproject/amphtml/16009/workflows/c8ef54fd-ca20-4d21-9825-d48fe76c5891/jobs/282926/tests
=> ❄️ Disable flaky test in `extensions/amp-video/0.1/test-e2e/test-amp-video-flexible-bitrate.js`

extensions/amp-fit-text/0.1/amp-fit-text.md, extensions/amp-fit-text/1.0/README.md, extensions/amp-fit-text/amp-fit-text.md
The new `README.md` is meant for npm publishing and is distinct from `amp-fit-text.md`, which is specific to AMP documents.
=> Add documentation for `bento-fit-text` and `BentoFitText`

build-system/tasks/helpers.js
**summary**
1. Removes the check that minification results in an empty bundle as this is expected in a single case (`amp-shadow-polyfill`)
2. Updates `terserOptions` during mangling according to recently discovered bugs.
3. Creates a new `combinedWithCompiledFile` codepath for esbuild flow. It is much simpler albeit less efficient since it forces us to disable mangling. Note that the final combined binaries are still smaller than what Closure was outputting (w/ one exception)
=> esbuild for dist: fix 3 discovered issues

build-system/compile/bundles.config.extensions.json, extensions/amp-wordpress-embed/1.0/README.md, extensions/amp-wordpress-embed/1.0/amp-wordpress-embed.css, extensions/amp-wordpress-embed/amp-wordpress-embed.md
Documentation is needed for publishing on npm, and CSS is needed for providing layout stabilizing CSS (pre-upgrade)
=> Add documentation and CSS for `bento-wordpress-embed` and `BentoWordPressEmbed`

build-system/compile/build-compiler.js, build-system/compile/bundles.config.js, build-system/tasks/dist.js, build-system/tasks/helpers.js, build-system/test-configs/forbidden-terms.js, package-lock.json, package.json, src/compiler/index.js, src/compiler/polyfills.js, src/compiler/types.js
**summary**
Myriad fixes to compiler.js as we iterate at both ends:
- Creates completely separate build path for `compiler.js` as its constraints are fairly different from the rest of our bundles. It does not need to be minified or transpiled. The new build step takes ~50ms. 
- Modified the parameter to `compilerAst` to match the latest proto def as well as created temporary defaults.
- Renames compileAst --> compile
- Adds a new polyfill for `Node`
=> ✨ compiler.js: myriad fixes

extensions/amp-story-auto-ads/0.1/story-ad-page-manager.js
Deprecated in https://github.com/ampproject/amphtml/pull/35932 but missed a file.
cc/ @jshamble this should get rid of the console error around an undefined state property.
=> 🗑[story-ads] Remove more 3 panel logic

docs/building-a-bento-amp-extension.md, extensions/amp-base-carousel/1.0/amp-base-carousel.css, extensions/amp-brightcove/1.0/amp-brightcove.css, extensions/amp-date-countdown/1.0/amp-date-countdown.css, extensions/amp-date-display/1.0/amp-date-display.css, extensions/amp-facebook/1.0/amp-facebook.css, extensions/amp-fit-text/1.0/amp-fit-text.css, extensions/amp-inline-gallery/1.0/amp-inline-gallery.css, extensions/amp-instagram/1.0/amp-instagram.css, extensions/amp-social-share/1.0/amp-social-share.css, extensions/amp-stream-gallery/1.0/amp-stream-gallery.css, extensions/amp-timeago/1.0/amp-timeago.css, extensions/amp-twitter/1.0/amp-twitter.css, extensions/amp-video-iframe/1.0/amp-video-iframe.css, extensions/amp-video/1.0/amp-video.css, extensions/amp-vimeo/1.0/amp-vimeo.css, extensions/amp-wordpress-embed/1.0/amp-wordpress-embed.css, extensions/amp-youtube/1.0/amp-youtube.css
Fixes #35805
The previously excluded classname `.i-amphtml-svc` is **never** added by the runtime. The original CSS pre-upgrade selector that has been carried over across extensions meant to target `[slot='i-amphtml-svc']` instead, which refers to sizer elements used for e.g. `layout=intrinsic`.
=> 🐛 Fix pre-upgrade Bento styles for sizer element

build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/base-element.js, build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/component.js, build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/component.type.js, build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/storybook/Basic.js, build-system/tasks/make-extension/template/bento/extensions/amp-__component_name_hyphenated__/__component_version__/test/test-component.js
Rename reference to use actual key:
https://github.com/ampproject/amphtml/blob/07da65927c96b26ab6dcea937793cab15126b350/build-system/tasks/make-extension/index.js#L228
=> 🐛 Fix extension template reference

.github/workflows/cut-nightly.yml, build-system/release-workflows/cut-nightly.js
* Adds the `release_tagger` environment (we should probably create a new environment just for releases, but for now this would do!)
* Explicitly pass the environment's GITHUB_TOKEN as an env variable
* Use `octokit.rest.checks.listForRef` instead of `octokit.rest.repos.getCombinedStatusForRef` because the former returns *all* statuses, while the latter misses some (such as, critically, CircleCI!)
* Better logging
=> 🏗 Fix nightly cut job to use the correct API endpoint for status checks and GitHub access token

build-system/tasks/helpers.js
**summary**
- Since we are running a performance experiment, may as well start with the safer version first and see if it already good enough.
- We can iterate and ensure mangling is 100% safe by applying a simple babel transform to add a suffix to all of our private vars. (i.e. `AMP_PRIVATE_`), that way our regex would not collide with any imported 3p libraries.
=> esbuild: disable prop mangling

ads/google/a4a/utils.js, extensions/amp-a4a/0.1/secure-frame.js, extensions/amp-ad-exit/0.1/amp-ad-exit.js
Includes the token in FIE rendering as this is needed even if iframe is friendly. Also updates the enablement check because `document.featurePolicy.features().includes('attribution-reporting')` will always return `true` if token is present, but `document.featurePolicy.allowsFeature('attribution-reporting')` will only return true if OT token present && `allow=attribution-reporting` is correctly set on the frame.
Partial #35347
=> 🐛 Fix attribution reporting OT token in FIE

build-system/release-tagger/test/update-issue-tracker.test.js, build-system/release-tagger/update-issue-tracker.js, build-system/release-tagger/utils.js
When we promote to stable, make sure to close the old stable's issue tracker.
=> 🏗 close old release tracker issues

build-system/global-configs/client-side-experiments-config.json
We are still getting similar regressions here, and it proves that there might be some visibility issues rather than performance issues. Reverting it for now as we investigate.
=> Stopping amp-sticky-ad-to-amp-ad-v2 experiment

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg-gaa.js, third_party/subscriptions-project/swg.js
- Demos: Load correct JS for qual autoprompt demo (#1900)
- Demos: Add qual pages (#1899)
- Analytics: Logs special event when unlocking for crawlers (#1898)
- Update dependency chromedriver to v93 (#1891)
- Analytics: Avoid logging subscription unlock events for crawlers (#1897)
- Update dependency @babel/preset-env to v7.15.6 (#1896)
- Update dependency prettier to v2.4.0 (#1895)
- Allow Dialog to be contained in a given element and iframe CSS class (#1894)
=> SwG Release 0.1.22.184

.github/workflows/release-tagger.yml, build-system/release-tagger/index.js, build-system/release-tagger/label-pull-requests.js, build-system/release-tagger/make-release.js, build-system/release-tagger/test/label-pull-requests.test.js, build-system/release-tagger/test/make-release.test.js
This is because we now need the distinction of `beta-opt-in` and `beta-percent` for updating the release issue trackers.
=> 🏗  Rename beta to beta-percent for release tagger

.github/ISSUE_TEMPLATE/release-tracker.yml, .github/workflows/release-tagger.yml, build-system/release-tagger/index.js, build-system/release-tagger/test/update-issue-tracker.test.js, build-system/release-tagger/update-issue-tracker.js, build-system/release-tagger/utils.js
To submit at the end of the week, avoiding active on-duty stuff.
=> 🏗  Trigger issue tracker management with release-tagger action 

build-system/compile/compile.js, build-system/compile/post-closure-babel.js, build-system/pr-check/module-tests.js, build-system/pr-check/nomodule-tests.js, build-system/server/lazy-build.js, build-system/tasks/build.js, build-system/tasks/helpers.js, build-system/tasks/prepend-global/index.js, build-system/tasks/prepend-global/prepend-global.test.js, build-system/tasks/release/index.js, build-system/test-configs/forbidden-terms.js
**summary**
See Attempt 1 for full PR description: https://github.com/ampproject/amphtml/pull/35773
In the prior attempt, the `npx amp` command was not setting `localDev: true` for the `amp build` and `amp` default task  commands. This caused all extension loading to default to `cdn` instead of localhost. This should be fixed via 3d1d2fe05b5258d6ceba41306e0170998808e3de. Note: this PR is also important for migrating to a different bundler, so that we can separate out the notion of bundler being directly tied to mode. Before this PR, closure-->(localDev=false), esbuild-->(localDev=true). After the PR they are tied to the build command instead (build, dist etc)
- All CI passes
- Verified that `npx amp`, `npx amp build`,  and `npx amp dist` all have identical AMP_CONFIG's to …
=> Revert "Revert "Improve AMP_CONFIG handling during build (#35773)" (#35819)"

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
The ad element currently is not being rebuilt after amp-sticky-ad is converted into an amp-ad. This is causing issues sometimes (especially doubleclick) where the state of the ads impl could be messed up. This PR will change to rebuild the ad once converted.
On my machine, it appears to be causing daily mail ads to drop 50% and works after patching this. It should be the culprit of the metrics drop.
=> 🐛 Fix doubleclick rendering issues when converted from amp-sticky-ad

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/friendly-frame-util.js, extensions/amp-a4a/0.1/secure-frame.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-a4a/0.1/test/test-friendly-frame-util.js
Add the following attributes when creating ad iframes: aria-label, tabindex, and role.
=> ♿ Add Accessibility attributes to iframes

build-system/common/git.js, build-system/compile/internal-version.js, build-system/release-workflows/cut-nightly.js
Reorganizes nightly script into separate functions.
Open to thoughts on using octokit instead of git to generate AMP version.
=> 🏗  Create tag as part of nightly cut

.github/workflows/cut-nightly.yml, build-system/release-workflows/cut-nightly.js
`actions/checkout@v2` defaults to fetching 1 commit; set it to 100.
tagalong - use `Octokit` instead of `any` in typedef.
=> 🏗 Fetch more than 1 commit for nightly job

build-system/compile/post-closure-babel.js, build-system/tasks/check-exact-versions.js, package-lock.json, package.json
Type annotations fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55845
=> 🏗 Update @types/fs-extra to 9.0.13 and standardize readJson calls to pass string encoding instead of options object

extensions/amp-accordion/1.0/README.md, extensions/amp-base-carousel/1.0/README.md, extensions/amp-date-countdown/1.0/README.md, extensions/amp-date-display/1.0/README.md, extensions/amp-embedly-card/1.0/README.md, extensions/amp-fit-text/1.0/README.md, extensions/amp-inline-gallery/1.0/README.md, extensions/amp-soundcloud/1.0/README.md, extensions/amp-stream-gallery/1.0/README.md, extensions/amp-twitter/1.0/README.md, extensions/amp-wordpress-embed/1.0/README.md
The frontmatter annotation is specific to amp.dev, which will not be surfacing these files. Instead, they will be published on npm where these annotations currently look very bad. :)
=> Remove frontmatter from Bento component `README` files

build-system/release-tagger/index.js
Forgot to include beta-opt-in as a supported channel
=> 🏗  Add supported channels for release tagger

extensions/amp-next-page/1.0/service.js, extensions/amp-next-page/1.0/test/test-amp-next-page.js, src/inabox/inabox-viewer.js, src/multidoc-manager.js, src/service/viewer-impl.js, src/service/viewer-interface.js
Fixes #35488
Messages meant for the Viewer are lost on documents loaded by `<amp-next-page>`.
This fix reuses the existing `messageDeliverer` from the host document's `Viewer` instance as the deliverer for the second document's `Viewer`. This way, messages are
received the same way.
=> 🐛 `<amp-next-page>`: Propagate host's message deliverer

extensions/amp-ad/0.1/amp-ad-ui.js, extensions/amp-ad/0.1/amp-ad.css, extensions/amp-ad/0.1/test/test-amp-ad-ui.js
Following UI discussion, we are comfortable allowing desktop (defined as wider than 1024px viewport) using left/right sticky ads, with a hard width limit of 100px. No behavior changes. Publishers will be responsible for ensuring no content overlaps because it might not be occupying full height.
https://github.com/ampproject/amphtml/issues/18123
=> ✨ Allow left/right sticky ads, strengthen unit tests

extensions/amp-sidebar/1.0/README.md, extensions/amp-sidebar/amp-sidebar.md
Documentation for AMP mode lives in `extensions/amp-sidebar/amp-sidebar.md` and Bento and Preact modes in `extensions/amp-sidebar/1.0/README.md`.
=> Add documentation for `amp-sidebar`, `bento-sidebar`, and `BentoSidebar`

build-system/global-configs/experiments-config.json, build-system/tasks/check-sourcemaps.js, build-system/tasks/helpers.js, build-system/tasks/prepend-global/index.js, build-system/tasks/visual-diff/index.js
**summary**
See https://github.com/ampproject/amphtml/pull/35816 for a PR that forces `esbuild` to be true and has all of CI green. Adds in one important fix for EXP_C, and then two fixes that only matter when it is the primary bundler:
1. ~(important): accept either unminified or minified name for `getAmpConfigForFile`. The distinction wasn't useful and forced us to pass in the minified name for minified builds (`srcFilename` is more ergonomic)~. Instead I pass `destFilename`
2. visual-diff:`test:true` check should also allow `!0` since that is the minified version of `true`
3. check-sourcemaps: esbuild has first line of the output on the first line instead of the second.
**confidence checks**
- prop mangling has been disabled for now. this is the riskiest optimization we could do, and …
=> Reenable EsbuildCompilation on EXP_C

extensions/amp-story/1.0/amp-story-draggable-drawer.js
The sticky positioning of the page attachment header does not work on iOS because of a known Safari issue where `position: sticky` fails if a parent element has `overflow: auto` set (see [caniuse](https://caniuse.com/?search=sticky)). I attempted to replicate sticky positioning via JS by setting the header's `position: fixed` whenever the sticky header was expected to be seen, but this also resulted in the header's layout being incorrectly altered.
The current behavior on iOS page attachments is such that the header transitions to its sticky layout whenever the attachment reaches full height, only for the header to be scrolled out of view. We have decided that we will prevent the sticky header layout from being shown on iOS at all, until a working solution for sticky positioning has been …
=> 🖍 Restrict page attachment sticky header to non-iOS, non-Safari surfaces

extensions/amp-stream-gallery/1.0/component.js
Use `toChildArray` to get the `children.length`, partial for #35678
=> `BentoStreamGallery`: Use `toChildArray` to get the `length`

build-system/tasks/helpers.js
**summary**
Silly code, but technically equivalent to what already exists in `compileMinified` (closure) path.
Hopefully can move to the solution outlined in https://github.com/ampproject/amphtml/pull/36162 in the future.
cc @danielrozenberg
=> esbuild compile: also write version.txt

extensions/amp-a4a/0.1/test/test-template-renderer.js, src/amp.js, src/custom-element.js, src/service/custom-element-registry.js, src/service/extension-script.js, src/service/performance-impl.js, test/unit/test-custom-element-registry.js, test/unit/test-custom-element.js
This permanently fixes the CLS caused by adblockers by delaying adding `.amp-unresovled` until we know the extension has been blocked. There's a race condition on when the element registry can register the `onerror` and when the script can actually load, so we listen for when the document is complete (which means all subresources have finished loading or failed to load) and mark any stragglers.
=> 🚀 Delay marking unresolved AMP Elements until extension fails

build-system/tasks/dist.js
This PR partially reverts commit 1e2c80849657030c90aaae5b8568611148227797.
The parallelization of these steps are causing a rare (3-6%) crash on CircleCI builds. For now it's probably worth to revert it. See #36164 for more info.
We allow parallelization only for the smaller tasks, before the main esbuild run. See [results](https://app.circleci.com/pipelines/github/ampproject/amphtml/17030/workflows/f78b6748-55a2-43da-a885-e27eb3d439a0/jobs/308263) of attempting this change on 100 VMs
=> Partially revert "🏗 Parallelize `dist` steps (#35943)"

extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js, extensions/amp-lightbox-gallery/0.1/test-e2e/test-open-close.js, test/fixtures/e2e/amp-lightbox/amp-lightbox-gallery-launch.amp.html
Issue #35920 requests to have the clicked on amp-image be the selected slide.
It appears this was an unintentional side effect of performing an unlayout on the carousel after waiting for the image transition to finish. I removed the unlayout call and added a e2e test to ensure we don't accidently break this functionality in the future.
=> 🐛(amp-lightbox-gallery): opens to selected image, resolve #35920

build-system/tasks/dist.js, build-system/tasks/helpers.js
**summary**
We currently write `version.txt` hundreds of times during an `amp dist`, usually to the same exact file (`dist/v0/version.txt`), but sometimes elsewhere. My instinct is that most of these writes were accidental, but I'm not going to fry that 🐟 here.
This PR extracts the logic to only happen once per dir.
Full set before:
```
[
'./dist.tools/experiments/',
'./dist/v0/',
'./dist/v0',
'./dist',
'./dist.3p/2109241350001',
'./dist/v0/examples',
'./dist.3p/2109241350001/vendor/',
'extensions/amp-accordion/1.0/dist',
'extensions/amp-base-carousel/1.0/dist',
'extensions/amp-date-countdown/1.0/dist',
'extensions/amp-date-display/1.0/dist',
'extensions/amp-facebook/1.0/dist',
'extensions/amp-embedly-card/1.0/dist',
'extensions/amp-fit-text/1.0/dist', …
```
=> build-system: only write version.txt once per dir

extensions/amp-bind/0.1/bind-impl.js
**summary**
Addresses https://github.com/ampproject/error-reporting/issues/105#issuecomment-919406318
If a pub specifies an `<amp-state>` as a data source for `amp-list`, then it is not a framework error if that element does not exist. We should mark it as such for correct error reporting.
=> 🐛  bind-impl: missing <amp-state> specified as an amp-list data source is a user error

ads/google/a4a/utils.js
Previous token expired. This one is good until 10/12/21 which really isn't long enough for prod release, but should be ok for local testing.
=> 🧪Update OT token for `attribution-reporting`

build-system/npm-publish/write-package-files.js
This addresses #35870 by adding a new export directive for stylesheets to the generated `package.json` files. For each existing stylesheet, an export as follows is added:
```json
{
"./<path_to_file>.css": "./dist/<path_to_file>.css",
}
```
Example:
```json
{
"./styles.css": "./dist/styles.css",
}
```
This allows using imports as follows in modern bundlers like webpack v5:
```js
import '@ampproject/amp-base-carousel/styles.css';
```
No export directive is added if there are no stylesheets.
**See also:**
* [Node.js documentation about package entry points](https://nodejs.org/api/packages.html#packages_package_entry_points)
Fixes #35870
=> 🏗  Add `exports` for stylesheets to `package.json`

src/service/performance-impl.js, test/unit/test-performance.js
Fixes https://github.com/ampproject/error-reporting/issues/106.
**question for @jridgewell**: can you explain what the intended tick times are? 1s after the last received shift?
=> performance-impl: cant check ampdoc vis hidden while null

extensions/amp-a4a/0.1/amp-a4a.js
The crypto signature is never used in the newish no-signing path, but requests are still being made to the `amp-ad-verifying-keyset.json` file. Once this change is in prod we can confirm that nothing has broken and requests for this file have stopped. At that point we should be able to deprecate the file.
cc/ @zombifier
=> ♻️Don't fetch crypto signature verifier in no-signing

extensions/amp-consent/0.1/consent-ui.js, extensions/amp-consent/0.1/test/test-consent-ui.js
Fixes #36063
`amp-consent` explicitly adds itself to the `FixedLayer`, transferring itself before the iframe is loaded.
On a later pass, `FixedLayer` decides that `amp-consent` is not transferrable, so it returns it to the original `<body>` element.
Enabling `forceTransfer` causes the return reparenting to not occur, thus preventing the iframe from loading a second time.
=> 🐛 Force transfer of `amp-consent` element to the `FixedLayer`

extensions/amp-iframe/1.0/component.js
**summary**
First order superficial fix for https://github.com/ampproject/amphtml/issues/36239 in order to unblock https://github.com/ampproject/amphtml/pull/36143.
We still need to address the root cause of useEffect hooks running during the wrong tests.
**to test**
Run the iframe and render tests together before and after this commit:
```
npx amp unit --headless --files=extensions/amp-iframe/1.0/test/test-amp-iframe.js,extensions/amp-render/1.0/test/test-amp-render.js
```
=> bento amp-iframe: guard effect from running without a win

build-system/babel-config/minified-config.js, build-system/babel-plugins/babel-plugin-transform-rename-privates/index.js, build-system/babel-plugins/babel-plugin-transform-rename-privates/test/fixtures/transform/rename-amp-privates/input.js, build-system/babel-plugins/babel-plugin-transform-rename-privates/test/fixtures/transform/rename-amp-privates/options.json, build-system/babel-plugins/babel-plugin-transform-rename-privates/test/fixtures/transform/rename-amp-privates/output.mjs, build-system/babel-plugins/babel-plugin-transform-rename-privates/test/fixtures/transform/skip-nonamp-privates/input.js, build-system/babel-plugins/babel-plugin-transform-rename-privates/test/fixtures/transform/skip-nonamp-privates/options.json, build-system/babel-plugins/babel-plugin-transform-rename-privates/test/fixtures/transform/skip-nonamp-privates/output.mjs, build-system/babel-plugins/babel-plugin-transform-rename-privates/test/index.js, build-system/common/esbuild-babel.js, build-system/tasks/helpers.js, extensions/amp-iframe/1.0/component.js
This PR renames all of AMP's private vars so that we can safely enable terser prop mangle during minification.
|                                 | v0.js brotli | v0.js  | v0.mjs brotli | v0.mjs |
|---------------------------------|--------------|--------|---------------|--------|
| closure compiler                | 69.33        | 269.42 | 60.93         | 213.00 |
| esbuild/terser with prop mangle | 71.38        | 281.43 | 63.40         | 233.13 |
| esbuild/terser                  | 74.50        | 314.80 | 66.42         | 266.23 |
**explanation**
Normally enabling prop mangling requires [significant attention to detail](https://terser.org/docs/cli-usage#cli-mangling-property-names-mangle-props) to perform safely. Creating a babel transform that marks all AMP private properties with a …
=> 🚀 babel/terser: rename all amp privates with sentinel suffix

.eslintignore, .gitignore, .prettierignore, build-system/tasks/clean.js
Identify user configuration files under build-system/global-configs as
distinct from generated output. This will help avoid accidentally
including them in the cleanup script in the future.
=> ♻️ configs: Separate user configs from output files

build-system/global-configs/canary-config.json, build-system/global-configs/client-side-experiments-config.json, build-system/global-configs/prod-config.json
We already have the results of the experiment, so we're disabling it to allow animations to play again on stories
=> 🧪 Set animations experiment to 0

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-doubleclick-fluid.js, extensions/amp-carousel/0.1/base-carousel.js, extensions/amp-carousel/0.1/scrollable-carousel.js, extensions/amp-carousel/0.1/slidescroll.js, extensions/amp-carousel/0.1/test/test-slidescroll-slides.js
**summary**
Renames `viewportCallbackTemp` --> `viewportCallback` now that there is no collision with BaseElement.viewportCallback.
Followup to https://github.com/ampproject/amphtml/pull/30859 and https://github.com/ampproject/amphtml/pull/30802
=> Rename viewportCallbackTemp --> viewportCallback

ads/vendors/broadbandy.md
Hi, our amp integration was successful but the name in documentation is wrong
this will fix the Company name mb file
=> set correct ad network name

src/service/performance-impl.js, test/unit/test-performance.js
The LCP's target is an element, but I had assumed it would be a `#text` node if the LCP was textual. When we retrieve the outermost element, it'll be something like a `<p>`/`<h1>` tag. The `tagName` isn't `null`, so we incorrectly labeled them as `other` type instead of `text` type.
=> 🐛 Correctly detect P tags as text element types

extensions/amp-subscriptions-google/0.1/test-e2e/test-amp-subscriptions-google.js
**summary**
Sometime over the past 24 hours, sxg e2e has started failing 100% of the time ([example](https://app.circleci.com/pipelines/github/ampproject/amphtml/17462/workflows/85513875-8ce8-49b3-9f22-695909a11513/jobs/319157)).
**root cause**
The content which the iframe points to has changed. 
To fix, I modified the test to check for the updated content.
**follow ups**
- Why did sxg iframe change? Was this unintentional?
- Are there any other consumers of sxg iframe that are potentially breaking as well?
- How can we prevent this from happening again?
@jpettitt
=> sxg e2e test: fix outdated check

.circleci/config.yml, build-system/pr-check/e2e-tests.js, build-system/pr-check/experiment-e2e-tests.js, build-system/pr-check/unit-tests.js, build-system/pr-check/utils.js
- Persist the test sharding filelist used during E2E and unit tests as a CircleCI artifact
- Rename the value of the `--filelist` argument from `TEST_FILES_LIST_FILE_NAME` to `FILELIST_PATH` for simplicity
[**Results:**](https://app.circleci.com/pipelines/github/ampproject/amphtml/17490/workflows/6a133921-3d69-47b4-bf3b-96f289eef645/jobs/319800/artifacts)
Implements https://github.com/ampproject/amphtml/issues/35580#issuecomment-895587167
=> 🏗 Persist test sharding filelist as an artifact on CircleCI

build-system/test-configs/forbidden-terms.js, docs/building-an-amp-extension.md, src/base-element.js, src/service/ampdoc-impl.js
Cleanup `getWin`, which has been deprecated since 2016: https://github.com/ampproject/amphtml/pull/4115
=> BaseElement: remove .getWin()

build-system/tasks/release/index.js
- Fix a TODO item to remove the undefined case for the `--esm` flag
- Add a `--dedup_v0` flag to remove duplicates v0/ files from some RTVs
=> 🏗 `amp release` changes

.github/workflows/sync-client-side-experiments-config-to-cdn.yml, .github/workflows/wrangler.toml
Example of this running: https://github.com/ampproject/amphtml/pull/36308/checks?check_run_id=3842831917
(I removed the trigger on `pull_request` in 695215e)
=> 🏗 Sync client-side-experiments-config.json to the CDN

.circleci/config.yml, .circleci/get_pinned_chrome_version.sh, .renovaterc.json
This PR pins the Chrome version used during CI so that a new browser release cannot inadvertently break tests.
- Extract major version of the [`chromedriver`](https://www.npmjs.com/package/chromedriver) npm package used by the E2E tests
- Determine the latest Chrome release matching that version from versionhistory.googleapis.com
- Configure Renovate to auto-update it whenever a new version of Chrome is released
With this PR, when Chrome 95 is released and the `chromedriver` npm package is updated, a new renovate PR will be generated to test our CI systems with the new version. Until then, existing CI builds will continue to use Chrome 94.
**Pinned to v93:** [logs](https://app.circleci.com/pipelines/github/ampproject/amphtml/17698/workflows/805964e7-a6d3-49 …
=> 🏗 Pin Chrome version used during CI

extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js, third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg-gaa.js, third_party/subscriptions-project/swg.js
https://github.com/subscriptions-project/swg-js/releases/tag/0.1.22.188
- Base change in creating GIS sign in button; currently almost identical to existing GSI button (#1942)
- Force lang in subscriptions iframe when forceLangInIframes is set (#1940)
- Remove unused eslint-disable lines in basic-runtime.js (#1941)
- Add support for prefixedHostPath option to handle pending server change (#1928)
- Add forceLangInIframes to ClientOptions and set it to true in basic-runtime.js (#1938)
- Destructure ClientConfig params (#1934)
- chore: Adds a newline to the end of .map files to confirm to build rules (#1935)
- E2E: Verify popup URL has a Google domain (#1936)
- gaa: Add 3p sign in button (#1919)
- Pass swgUserToken and orderId via web activities (#1933)
- Bump nth-check from 2.0.0 to 2.0.1 …
=> SwG Release 0.1.22.188

extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js
This is the reason why 3p sticky ads are not clickable. This is intended to prevent misclicks from sidekick ads while motion is still ongoing. Will explore some better ways of doing it for regular sticky ads (maybe block clicks right after requestResize).
=> Do not disable clicking for 3p sticky ads

build-system/compile/bundles.config.extensions.json, build-system/compile/compile-wrappers.js, build-system/tasks/clean.js, build-system/tasks/extension-helpers.js, build-system/tasks/make-extension/index.js
Before this change, output `bento-*.js` files are identical as `amp-*.js`, and not as they should be:
1. They should only work on Bento standalone mode, not AMP mode
2. They should not attempt to use AMP runtime features.
Bento components directories include both `amp-*.js` and `base-element.js`. The former exports an AMP extension, while the latter exports a component-specific `BaseElement` that does not attempt to use AMP runtime features. 
This change generates a `bento-*.js` source file that uses the `BaseElement` implementation without AMP usage.
=> 🏗 Output distinct `bento-*.js`

extensions/amp-story/1.0/amp-story-system-layer.css
The height of the progress chip is `3px` instead of `2px` in supports landscape mode. Switch to `100%` so that the CSS handles both correctly.
Closes https://github.com/ampproject/amphtml/issues/36336
=> 🐛 [story-ads] Fix yellow chip in `supports-landscape` mode.

src/service/performance-impl.js
The new CLS metric uses a different path, and I forgot to check the Fonts experiment when it was calculated. We're probably missing all kinds of reports…. Gah.
=> 🐛 Record the google fonts exp when flushing CLS score

build-system/pr-check/build-targets.js, build-system/tasks/ava.js
Derive directories that should trigger `amp ava` tests based on the test files location.
This prevents us from accidentally submitting new test files without a matching target directory (like I had to fix on 596fe2d6c).
Directories are the same as the test file, or its parent if the directory is named `test`. This matches the same of file set as before.
=> 🏗 Derive `ava` target paths

extensions/amp-ad/0.1/amp-ad-ui.js, extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js, extensions/amp-ad/0.1/amp-ad.css, extensions/amp-ad/0.1/test/test-amp-ad-ui.js, extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js
On fast fetch networks, onResizeSuccess will not run and the logic will not be triggered correctly.
In addition, it fixes the off-by-one-pixel that offsets the ads by 4 pixels.
=> 🐛 Fix top sticky ad auto hiding on fast fetch networks and bottom sticky css

package-lock.json, package.json, src/compiler/compile.js, src/compiler/index.js, src/compiler/types.d.ts, test/unit/compiler/test-compile.js, test/unit/compiler/test-index.js
**summary**
- Teaches `compiler.js` how to compile a list of nodes instead of only complete documents.
- Bumps version of bento-compiler (0.11 introduced the compileNodes fn)
- ~Adds tests for the compiler entrypoint~
- Extracts `compile()` function to its own file to make it testable. The global side effects created from the entrypoint unfortunately break our testing infra.
=> compiler: accept partials

extensions/amp-story-auto-ads/0.1/story-ad-ui.js, extensions/amp-story-auto-ads/0.1/test/test-story-ad-ui.js
Webkit does not count swipes as a trusted interaction, therefore causing the landing page not to open if `target=_blank`.
=> 🐛[story-ads] use `target=_top`

build-system/release-tagger/index.js, build-system/release-tagger/make-release.js, build-system/release-tagger/test/update-issue-tracker.test.js, build-system/release-tagger/update-issue-tracker.js, build-system/release-tagger/utils.js
1. Fix CP logic: 
Release tagger assumed that any version not ending with `000` was a new CP, so it would try to update the issue tracker with new tasks.  When actually, versions not ending in `000` can be a previously CP'ed version.
2. Handle 404s:
Add an octokit hook that returns undefined instead of throwing error when a github resource is not found. This lets the release tagger do a quick null check instead of try/catch clauses everywhere.
=> 🏗 Add release tagger hook to handle 404s and fix CP logic

.eslintrc.js, build-system/eslint-rules/preact.js, extensions/amp-story/1.0/amp-story-access.js, src/core/dom/jsx.js, test/unit/core/dom/test-jsx.js
Related to #36459
Provides a replacement for existing rendering methods that's more powerful and convenient:
|                  | JSX | imperative DOM | `htmlFor` | `simple-template` (Stories) |
| ---------------- | --- | -------------- | --------- | --------------------------- |
| like HTML        | ✅  | 🚫             | ✅        | 🚫                          |
| dynamic attrs    | ✅  | ✅             | 🚫        | ✅                          |
| dynamic children | ✅  | 🚫             | 🚫        | sort-of                     |
| event handlers   | ✅  | 🚫             | 🚫        | 🚫                          |
| nesting          | ✅  | 🚫             | 🚫        | 🚫                          |
A minimal implementation of JSX is included as `#core/dom/jsx`.
This library adds ~0.22K of size to any …
=> 🏗 Allow rendering plain DOM using JSX

build-system/npm-publish/write-package-files.js
current configuration breaks with apps bundled by exports, because the redirecting-logic seems not to work. switching this configuration to explicitly reference the web-component files does work.
=> fix npm exports declaration so it works with webpack

build-system/pr-check/visual-diff-tests.js, build-system/tasks/visual-diff/index.js, docs/testing.md
It's more trouble than it's worth, a forgotten flag shouldn't cost me 10 minutes 😅
=> 🏗 Remove the --nobuild flag from visual diff tests

extensions/amp-story/1.0/amp-story-consent.js, extensions/amp-story/1.0/amp-story-draggable-drawer.js, extensions/amp-story/1.0/amp-story-embedded-component.js, extensions/amp-story/1.0/amp-story-form.js, extensions/amp-story/1.0/amp-story-hint.js, extensions/amp-story/1.0/amp-story-info-dialog.js, extensions/amp-story/1.0/amp-story-localization-service.js, extensions/amp-story/1.0/amp-story-open-page-attachment.js, extensions/amp-story/1.0/amp-story-page-attachment.js, extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/amp-story-share-menu.js, extensions/amp-story/1.0/amp-story-share.js, extensions/amp-story/1.0/amp-story-system-layer.js, extensions/amp-story/1.0/amp-story-unsupported-browser-layer.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/pagination-buttons.js, extensions/amp-story/1.0/simple-template.js, extensions/amp-story/1.0/test/test-simple-template.js
All callsites now use `localize(element, key)`. This attempts zero changes in functionality.
This function compresses better than the alternatives, which we're able remove as well:
- `getLocalizationService(...).getLocalizedString(...)`. Some callsites check for existence of the service even though it's always present, and sometimes they'd store it in a private. `localize()` is briefer.
- On `simple-template`, we remove awkward fields: `unlocalizedString` and `localizedStringId` use `children`, and `localizedLabelId` is moved to an `aria-label` in `attrs`. This allows us to simplify the `simple-template` implementation, and reformats templates so that they'll be more easily converted to JSX in the future.
Together, these changes reduce the module build by ~0.3k compressed:
|        | …
=> 🚀♻️ Normalize how locale strings are rendered in `amp-story`

extensions/amp-script/0.1/amp-script.js, extensions/amp-script/0.1/test/unit/test-amp-script.js
**summary**
Likely since switching to bundling with esbuild for tests (particularly since the esbuild change which _forces_ all .mjs files to be module type), the `amp-script` tests have started emitting errors.
Turns out our stubbing of `WorkerDOM` module was broken as it relies on assigning to an esm namespace.
This PR removes the errors + fixes the stubbing.
As a bonus fix, I also moved service registration / clearing to toplevel, which should help out https://github.com/ampproject/amphtml/pull/36618 💅 
**example error**
cc @zshnr
=> test-amp-script: fix stubbing of WorkerDOM

build-system/babel-config/minified-config.js, build-system/babel-config/pre-closure-config.js, build-system/babel-config/test-config.js, build-system/babel-config/unminified-config.js, package-lock.json, package.json
This transform breaks `#core/dom/jsx`. It does not provide much benefit in our case when using `#preact` either, so we disable it.
=> 🏗 Remove `@babel/plugin-transform-react-constant-elements`

build-system/tasks/visual-diff/index.js, build-system/tasks/visual-diff/package-lock.json, build-system/tasks/visual-diff/package.json
Attempt at fixing the issue found by @alanorozco: https://app.circleci.com/pipelines/github/ampproject/amphtml/18737/workflows/5c398bd7-f6e6-448c-a10c-8ebe0548cc9c/jobs/349250?invite=true#step-113-90
=> 🏗 Force `amp visual-diff` to wait for the Percy agent to be reachable

extensions/amp-script/0.1/amp-script.js, extensions/amp-script/0.1/test/unit/test-amp-script.js
**Summary**
Skips the CSP hash check for a cross-origin source passed to `amp-script` since this is one of the features of `sandboxed` mode introduced in PR #33643.
Fixes #36614
=> 🐛 [amp-script] skip sha384 check for cross-origin scripts in sandboxed mode

extensions/amp-story/1.0/page-advancement.js
This simplifies the handle event check when a click is inside a draggable drawer.
This checks if the element is a draggable drawer rather than checking the tag name of elements that extend the draggable drawer.
This will be helpful in the future - when other elements extend draggable drawer (such as `amp-story-shopping-attachment`), we will not need to add another tag to this list.
=> ♻️[amp story page advancement] handle clicks on drawer

extensions/amp-story/1.0/amp-story-page.js
Fixes #36711
Reverts removing the JS units calculation from #36033
Before / After (URLs match the [original story](https://stories.nws.ai/1288496525/new-omnichannel-customer-experiences/) and the [demo story with change](https://stories-demos-matias.web.app/examples/amp-story/nws.html))
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Also tested, and the styles for the desktop one-panel are not affected by the bug, and are also not affected by this fix (those styles are overriden). Also, the desktop one-panel is not shown on mobile UIs.
=> 🐛 Added back JS for vh

build-system/tasks/visual-diff/browser.js, build-system/tasks/visual-diff/consts.js, build-system/tasks/visual-diff/dev-mode.js, build-system/tasks/visual-diff/helpers.js, build-system/tasks/visual-diff/index.js, build-system/tasks/visual-diff/log.js, build-system/tasks/visual-diff/package-lock.json, build-system/tasks/visual-diff/package.json, build-system/tasks/visual-diff/types.js, build-system/tasks/visual-diff/verifiers.js, docs/testing.md, docs/writing-visual-diff-tests.md, examples/visual-tests/amp-accordion/amp-accordion.js, examples/visual-tests/amp-autocomplete/amp-autocomplete.js, examples/visual-tests/amp-date-picker/amp-date-picker.js, examples/visual-tests/amp-form/amp-form.js, examples/visual-tests/amp-list/amp-list.amp.js, examples/visual-tests/amp-mega-menu/amp-mega-menu.js, examples/visual-tests/amp-selector.js, examples/visual-tests/amp-sidebar/amp-sidebar-toolbar.js, examples/visual-tests/amp-sidebar/amp-sidebar.js, examples/visual-tests/amp-story/amp-story-ad.js, examples/visual-tests/amp-story/amp-story-page-attachment.js, examples/visual-tests/amp-story/amp-story-pagination-buttons.js, examples/visual-tests/amp-story/amp-story-tooltip-desktop.js, examples/visual-tests/amp-story/amp-story-tooltip.js, examples/visual-tests/amp-video-docking/amp-video-docking.js
This PR adds a "development mode" for `amp visual-diff` to help iterate on new visual diff tests faster. It's triggered by calling `amp visual-diff --dev` (preferably with `--grep <test-name>` to make it easier):
Then the user selects the test file and an interactive test if they exist:
And the task opens a browser window with the test, runs any interactivity code embedded in it, and then prompts the user for actions:
The actions are to immediately test whether a CSS selector is visible/invisible on the page or to reload the page.
Reloading the page by pressing enter on an empty prompt will reload any new changes to the HTML and interactive JS files
=> 🏗 Add dev-mode for `amp visual-diff` and split code into modules

validator/validator-main.protoascii
In reviewing the [New WebKit Features in Safari 15](https://webkit.org/blog/11989/new-webkit-features-in-safari-15/), I noticed:
> In the HTML meta tag, developers can specify separate colors for Dark Mode and light appearance with the `media` attribute.
> ```html
> <meta name="theme-color" 
>       content="#ecd96f" 
>       media="(prefers-color-scheme: light)">
> <meta name="theme-color" 
>       content="#0b3e05" 
>       media="(prefers-color-scheme: dark)">
> ```
I thought this was a Safari-specific thing, but turns out it isn't. It's [documented on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color):
<!--
> You can provide a media type or query inside the `media` attribute; the color will then only be set if the media condition is true. For …
=> ✨ Allow `media` attribute on `meta` tag in validator spec

.github/workflows/publish-npm-packages.yml
Tagalong - improve readability
=> 🏗 Print amp version and npm tag 

.github/workflows/cross-platform-builds.yml, .github/workflows/cut-nightly.yml, .github/workflows/publish-npm-packages.yml, .github/workflows/release-tagger.yml, .github/workflows/status-page.yml, .github/workflows/sweep-experiments.yml
@twifkak noticed that our "cross-platform builds" workflow has been [failing](https://github.com/ampproject/amphtml/actions/runs/1418014332) for a while. Turns out GH actions [still defaults](https://github.com/ampproject/amphtml/runs/4096255028?check_suite_focus=true#step:3:12) to node 14.
- Explicitly use Node LTS for all workflows that also do a full install of `amphtml` packages. (Workflows that don't do so have been left alone.)
- Also remove any hardcoded references to node 16 (resolves [this](https://github.com/ampproject/amphtml/pull/36646#pullrequestreview-792057870) comment).
=> 🏗 Explicitly use node LTS for GH actions workflows

examples/amp-story/amp-story-shopping.html, examples/visual-tests/amp-story/amp-story-shopping.html, examples/visual-tests/amp-story/amp-story-shopping.js, extensions/amp-story/1.0/amp-story-page.js, test/visual-diff/visual-tests.jsonc
Adds `amp-story-shopping-attachment` to list of elements that need a CTA button rendered.
Adds visual test for default and dark theme.
Adds example for dark theme.
Fixes #36697
=> ✨ Render page level CTA when amp-story-shopping-attachment exists

build-system/tasks/css/jsify-css.js, package-lock.json, package.json
This PR enables the `amp` dev server's watcher to fully rebuild extensions when a nested CSS file is modified.
**User flow:**
1. Launch dev server
```
amp
```
2. Load an `amp-story` [test page](http://127.0.0.1:8000/examples/amp-story/amp-story-desktop-one-panel.html) in a browser
3. Modify a nested CSS file. E.g. Change `background` from `none` to `yellow` in `pagination-buttons.css`
https://github.com/ampproject/amphtml/blob/b829088d4a7e7ca9be0892b585b16e253c93fc9e/extensions/amp-story/1.0/pagination-buttons.css#L17
4. Refresh the browser after the dev server rebuilds `amp-story`
Fixes #33826
=> 🏗✨ Add lazy-build support for nested CSS imports

build-system/tasks/helpers.js
Addresses part of https://github.com/ampproject/amphtml/issues/36476#issuecomment-952373926 by enabling the `toplevel` flag.
This significantly shrinks our .js bento builds.
```
extensions/amp-jwplayer/1.0/dist/web-component.js: Δ -5.02KB
extensions/amp-timeago/1.0/dist/web-component.js: Δ -2.68KB
extensions/amp-base-carousel/1.0/dist/web-component.js: Δ -4.04KB
extensions/amp-stream-gallery/1.0/dist/web-component.js: Δ -4.13KB
extensions/amp-lightbox-gallery/1.0/dist/web-component.js: Δ -4.07KB
```
=> terser: enable toplevel, less hacky fix for nameCache local vars

build-system/babel-config/minified-config.js, build-system/babel-config/pre-closure-config.js, build-system/babel-config/test-config.js, build-system/babel-config/unminified-config.js, build-system/babel-plugins/babel-plugin-dom-jsx-svg-namespace/index.js, build-system/babel-plugins/babel-plugin-dom-jsx-svg-namespace/test/fixtures/transform/ignored/input.mjs, build-system/babel-plugins/babel-plugin-dom-jsx-svg-namespace/test/fixtures/transform/ignored/options.json, build-system/babel-plugins/babel-plugin-dom-jsx-svg-namespace/test/fixtures/transform/ignored/output.mjs, build-system/babel-plugins/babel-plugin-dom-jsx-svg-namespace/test/fixtures/transform/sets-prop/input.mjs, build-system/babel-plugins/babel-plugin-dom-jsx-svg-namespace/test/fixtures/transform/sets-prop/options.json, build-system/babel-plugins/babel-plugin-dom-jsx-svg-namespace/test/fixtures/transform/sets-prop/output.mjs, build-system/babel-plugins/babel-plugin-dom-jsx-svg-namespace/test/index.js, src/core/dom/jsx.js, test/unit/core/dom/test-jsx.js
SVG Elements must be especially created with `createElementNS`.
This transforms SVG-related JSX elements in order to always include an `xmlns` prop that's used to create the DOM nodes correctly.
This prop is consumed by `core/dom/jsx`. We ignore files that do not import this module.
Fixes #36713
=> 🏗🐛 Annotate JSX SVG namespace during build-time

build-system/eslint-rules/preact.js
This prevents an issue with `<Div />`, where `Div` value comes from a user-provided data source. Only regular nodes (lowercase `<div />`), and Components that we can prove come from a local function definition or import are allowable.
It also prevents spread attributes, to prevent them from overriding an assumed-safe static attribute. Eg, `<script type="text/json" {…userData} />` can override the `type` with `userData.type` accidentally.
=> Lint for dynamic JSX nodes

extensions/amp-story/1.0/amp-story-page-attachment.js
=> 🖍 [Attachment Forms] Remove the 'www.' prefix from the displayed publisher domain in the page attachment header

.github/workflows/cross-platform-builds.yml, .github/workflows/cut-nightly.yml, .github/workflows/publish-npm-packages.yml, .github/workflows/release-tagger.yml, .github/workflows/status-page.yml, .github/workflows/sweep-experiments.yml
While installing node on GH actions, it turns out that `check-latest: true` and `node-version: lts/*` [don't guarantee](https://github.com/ampproject/amphtml/pull/36746#discussion_r742258250) that the latest active LTS version is installed. Probably related to https://github.com/actions/setup-node/issues/26 or https://github.com/actions/setup-node/issues/355.
This PR restores the hard-coded `node-version: 16` and removes `check-latest`. We can revisit this next year when the next active LTS is released.
Addresses https://github.com/ampproject/amphtml/pull/36746#discussion_r742258250
=> 🏗 Restore hard-coded node version in GH actions setup

build-system/tasks/visual-diff/index.js
Turns out Percy won't snapshot a page with the url `about:blank`, so `--empty` builds fail because of the change I made in #36673
=> 🏗🐛 Restore blank.html for visual diff tests

build-system/tasks/storybook/index.js, build-system/tasks/storybook/package-lock.json, build-system/tasks/storybook/package.json
`@ampproject/storybook-addon` has outdated peer dependencies that conflict with the main install. Disable the AMP environment for now so that the Preact environment can run.
We'll update the addon soon: https://github.com/ampproject/storybook-addon-amp/issues/57
Additionally, we were relying on `@storybook/client-api` as a transitive dependency from the addon. Install it so that Storybook can run.
=> 🏗 Temporarily disable Storybook AMP environment

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
The response from `sendMessageAwaitResponse` is already parsed (not JSON) so we don't need to parse again.
Also add some tests.
=> 🐛[story-ads] fix shared exp parsing

.eslintrc.js, build-system/.eslintrc.js, build-system/eslint-rules/enums.js, src/amp-story-player/amp-story-player-impl.js
This adds an optional enum linter that ensures that an enum is only used in a statically DCE-able way. Enums opt-into this behavior by using the `_Enum` suffix in their name.
Depends on #36755
Partial for #36754
=> Add optional static enum lint

extensions/amp-story/1.0/_locales/en.json, extensions/amp-story/1.0/amp-story-open-page-attachment.js, src/service/localization/strings.js
As discussed in #36724, we are updating the default CTA for page attachments from "Swipe up" to "Read more". This PR adds this new "Read more" string in the appropriate places to be translated.
=> 🖍 [Page Attachments] Add the 'Read more' string for translation

build-system/tasks/visual-diff/index.js
=> 🏗 Also fix blank page snapshot with `amp visual-diff --main`

build-system/global-configs/versioning.json, build-system/json-schemas/versioning.json
Unlike other channels, these two have a different promote day for opt-in and for traffic
=> 🏗 split the {beta,experimental} channels in `versioning.json` into {-opt-in,-traffic} channels

build-system/tasks/get-zindex/index.js, package-lock.json, package.json
It's redundant since it's used on a script that `prettier`-formats the output, with the same results.
=> 🏗🚮 Remove `text-table`

extensions/amp-story/amp-story.md
**summary**
amp-story.md cleanup
- Removes outdated references to `0.1`
- Removes the extra "Example" text
---
=> amp-story: remove reference to 0.1

build-system/tasks/validate-html-fixtures.js, build-system/test-configs/config.js, examples/compiler-hydration.html
**summary**
Creates a new amp document in the `examples/` directory for showcasing component hydration.
=> Examples: create document for component hydration

build-system/compile/bundles.config.extensions.json, build-system/tasks/css/index.js, build-system/tasks/extension-helpers.js
This is a more flexible model since changing the built CSS binaries does not require OWNERS approval on the `extensions.json` file. 
Even though we might be building some files unnecessarily if they're `@import`ed, in practice the task takes just as long to complete.
=> 🏗 Build all CSS in an extension's dir, and remove `cssBinaries`

extensions/amp-carousel/0.1/scrollable-carousel.js, extensions/amp-carousel/0.1/slidescroll.js
**summary**
Turns out gallery depends on the public API of carousel:
https://github.com/ampproject/amphtml/blob/abfe09e34b17a53fc676f9f2ae98ad8065fd5d77/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js#L509-L515
I changed that public API in https://github.com/ampproject/amphtml/commit/a3b02b44afff558c5dded72dd3659761bf98083a. Resulting in this new error:
- `npx amp`
- Open up http://0.0.0.0:8000/examples/lightbox-gallery.amp.html, click an img, ensure arrow buttons proceed to next/prev image
=> gallery/carousel fix: restore public function

extensions/amp-accordion/1.0/README.md, extensions/amp-base-carousel/1.0/README.md, extensions/amp-embedly-card/1.0/README.md, extensions/amp-facebook/1.0/README.md, extensions/amp-fit-text/1.0/README.md, extensions/amp-iframe/1.0/README.md, extensions/amp-inline-gallery/1.0/README.md, extensions/amp-instagram/1.0/README.md, extensions/amp-jwplayer/1.0/README.md, extensions/amp-lightbox-gallery/1.0/README.md, extensions/amp-lightbox/1.0/README.md, extensions/amp-mathml/1.0/README.md, extensions/amp-selector/1.0/README.md, extensions/amp-sidebar/1.0/README.md, extensions/amp-social-share/1.0/README.md, extensions/amp-soundcloud/1.0/README.md, extensions/amp-stream-gallery/1.0/README.md, extensions/amp-timeago/1.0/README.md, extensions/amp-twitter/1.0/README.md, extensions/amp-wordpress-embed/1.0/README.md
- Some snippets were incorrectly formatted because they did not include `<body>` or `<html>`. Fixed.
- Adds `<%-- example --%>` as an annotation for the docs website.
=> 📖 Bento docs: Full snippets have `<html>` and `<%-- example --%>`

extensions/amp-base-carousel/0.1/amp-base-carousel.js, extensions/amp-carousel/0.1/scrollable-carousel.js, extensions/amp-carousel/0.1/slidescroll.js, extensions/amp-lightbox-gallery/0.1/test/test-amp-lightbox-gallery.js
**summary**
Context: https://github.com/ampproject/amphtml/issues/36871
- Adds super basic test for confirming that the carousels `amp-gallery-lightbox` depends on have the expected functions on their prototype
- Adds `goCallback` back to the SlidableCarousel and ScrollableCarousel classes
- [preexisting bug]: Renames `goToSlide_` to `goToSlide` for scrollable carousel
- [preexisting bug] Adds `goCallback` to amp-base-carousel
=> adds basic tests to amp-gallery-lightbox, reintroduce goCallback to amp-carousel 0.1

examples/amp-story/amp-story-1.0.css, src/style-installer.js, test/unit/test-style-installer.js
Some amp optimizers will in the future add a link[rel=stylesheet] for an
extension to improve their performance. We need to be able to detect and
not overwrite the installed styles by the external stylesheet.
=> Detect if a link[rel=stylesheet] has been SSR'd/installed for an extension

extensions/amp-mathml/1.0/README.md, extensions/amp-mathml/1.0/amp-mathml.js, extensions/amp-mathml/1.0/component.js, extensions/amp-mathml/1.0/storybook/Basic.amp.js, extensions/amp-mathml/1.0/storybook/Basic.js, extensions/amp-mathml/1.0/test/test-amp-mathml.js, test/fixtures/e2e/bento/mathml.html
Removes all the intersection observer logic - now it depends on the consumer to set the dimensions of the mathml formula explicitly (through height/width, aspect-ratio, etc.). Displays nothing if no dimensions are set.
=> refactor mathml to require consumer to set dimensions

.circleci/config.yml
The Git cache on CircleCI is platform-dependent, so the Safari test job was cloning from scratch every time - for some reason, it can take multiple minutes to finish the clone step:
This PR saves the Git cache specifically for this single MacOS job, which can be reused later:
=> 🏗 Save Git cache in MacOS jobs on CircleCI

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js
This is a bit racy until we are able to block properly on a viewer capability check. Until then we should send the message and await the response as early as possible.
=> 🧪[story-ads] move exp check earlier in lifecycle

extensions/amp-story/1.0/_locales/README.md
The `.js` references are incorrect
=> 📖 Update instances of ".js" to ".json" in localization instructions

validator/validator-main.protoascii
Fixes https://github.com/ampproject/amphtml/issues/36843
=> amp-form: allow xssi-prefix for amphtml and amp4ads

build-system/babel-plugins/babel-plugin-react-style-props/index.js, build-system/babel-plugins/babel-plugin-react-style-props/test/fixtures/transform/function/input.js, build-system/babel-plugins/babel-plugin-react-style-props/test/fixtures/transform/function/options.json, build-system/babel-plugins/babel-plugin-react-style-props/test/fixtures/transform/function/output.js, build-system/eslint-rules/preact-preferred-props.js, extensions/amp-accordion/1.0/component.js, extensions/amp-base-carousel/1.0/arrow.js, extensions/amp-inline-gallery/1.0/thumbnails.js, extensions/amp-selector/1.0/base-element.js, extensions/amp-selector/1.0/component.js, extensions/amp-social-share/1.0/component.js, extensions/amp-stream-gallery/1.0/component.js, extensions/amp-video/1.0/component.js, src/preact/component/contain.js, src/preact/component/wrapper.js, src/preact/utils.js
Partial for #35678
For safety of prop name replacement, and consistent with either Preact or React style, replace e.g. `propName('class')` when destructuring props.
- Added passthrough function `propName()`.
- Updated Babel plugin to replace function uses.
- Updated eslint rule so that it generates `[propName('class')]: className`, and verifies uses of `propName()`.
=> 🏗♻️ Annotate use of Preact-style prop names

build-system/babel-config/minified-config.js, build-system/babel-config/pre-closure-config.js, build-system/babel-config/unminified-config.js, build-system/babel-plugins/babel-plugin-jsx-style-object/index.js, build-system/babel-plugins/babel-plugin-jsx-style-object/test/fixtures/transform/dimensional/input.mjs, build-system/babel-plugins/babel-plugin-jsx-style-object/test/fixtures/transform/dimensional/options.json, build-system/babel-plugins/babel-plugin-jsx-style-object/test/fixtures/transform/dimensional/output.mjs, build-system/babel-plugins/babel-plugin-jsx-style-object/test/fixtures/transform/ignored/input.mjs, build-system/babel-plugins/babel-plugin-jsx-style-object/test/fixtures/transform/ignored/options.json, build-system/babel-plugins/babel-plugin-jsx-style-object/test/fixtures/transform/ignored/output.mjs, build-system/babel-plugins/babel-plugin-jsx-style-object/test/fixtures/transform/nested/input.mjs, build-system/babel-plugins/babel-plugin-jsx-style-object/test/fixtures/transform/nested/options.json, build-system/babel-plugins/babel-plugin-jsx-style-object/test/fixtures/transform/nested/output.mjs, build-system/babel-plugins/babel-plugin-jsx-style-object/test/fixtures/transform/transformed/input.mjs, build-system/babel-plugins/babel-plugin-jsx-style-object/test/fixtures/transform/transformed/options.json, build-system/babel-plugins/babel-plugin-jsx-style-object/test/fixtures/transform/transformed/output.mjs, build-system/babel-plugins/babel-plugin-jsx-style-object/test/index.js, extensions/amp-story/1.0/amp-story-consent.js, src/core/dom/jsx-style-property-string.js, test/unit/core/dom/test-jsx-style-property-string.js
Converts Object Expression syntax in `style={{foo: 'bar'}}` to a concatenated string expression.
This only transforms a file if it imports the `core/dom/jsx` module, which lacks runtime support for converting the Object into a string. This transform takes that responsibility instead.
=> 🏗 Transform `style` objects into string expressions

.eslintrc.js, build-system/eslint-rules/core-dom-jsx.js, build-system/eslint-rules/preact.js, extensions/amp-story/1.0/amp-story-hint.js, extensions/amp-story/1.0/amp-story-system-layer.js, extensions/amp-story/1.0/toast.js, src/core/dom/jsx.js, test/unit/core/dom/test-jsx.js
Closes #36679
This handles all caveats mentioned except mapped attribute names, which are handled by `local/preact-preferred-props`
Also transfers relevant rules from `local/preact` into `local/core-dom-jsx`.
=> 🏗 Lint uses of `core/dom/jsx`

extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.css, extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js
Something has recently changed in browsers, where they forgot to paint the contents of our flying carpet when it comes into view. Luckily, we can force them to redraw as we enter the viewport and they'll correctly display.
See this working at https://output.jsbin.com/jibufud/quiet.
Fixes https://github.com/ampproject/amp.dev/issues/6219
Re: https://bugs.chromium.org/p/chromium/issues/detail?id=1269529
=> Fix flying carpet rendering

validator/README.md
Update the Validator Instruction to use docker image `cimg/openjdk:17.0-node`, which is the same as [CircleCI config](https://github.com/ampproject/amphtml/blob/504411bcf4e86bb92df1482ce985d9ad458a2a7d/.circleci/config.yml#L63).
The difference is that `cimg/openjdk:17.0-node` uses `g++ 9.3.0` while `node:lts-buster` uses `g++ 8.3.0`.
=> Update Validator Instruction about Docker image

ads/google/a4a/utils.js, extensions/amp-a4a/0.1/secure-frame.js
Previous experiment expired. New tokens are able to be extended through 1/25/22
=> 🧪 [amp-ads] update OT token for `conversion-measurement` exp

extensions/amp-access/0.1/test/test-login-dialog.js, extensions/amp-experiment/0.1/test/test-variant.js, extensions/amp-experiment/1.0/test/test-variant.js, src/service/ampdoc-impl.js, src/service/performance-impl.js, test/unit/core/window/test-history.js, test/unit/test-action.js, test/unit/test-activity.js, test/unit/test-ampdoc.js, test/unit/test-cid.js, test/unit/test-custom-element-registry.js, test/unit/test-fixed-layer.js, test/unit/test-storage.js, test/unit/test-viewer.js, test/unit/test-viewport.js, testing/fake-dom.js
When comparing the LCP and LCPV scores for viewer-embedded pages that are immediately visible, I noticed the LCPV scores were considerably lower. This seems wrong, if the page is immediately visible, the LCP and LCPV should be equivalent. 
I think this is because the `ampdoc` keeps track of the time the page is first visible, but that's initialized in JS when the `ampdoc` is first created. That means we don't notice the parse+exec time that it takes to reach that point, and the LCPV is better than reality.
=> 🐛 Use timeOrigin for getFirstVisibleTime when page starts visible

test/unit/test-viewer.js
**summary**
- Removes an it.only that made it into the codebase via https://github.com/ampproject/amphtml/pull/36273/files
TODO: how was this able to be merged given `checks` should have failed
=> Fix the build.

build-system/pr-check/bundle-size-module-build.js, build-system/pr-check/bundle-size-nomodule-build.js, build-system/tasks/helpers.js
I'm getting annoyed with all the `±0.01kb` changes in our bundle-size outputs, which aren't actually cased by any change in the file. It's just Terser detecting the relative frequency of chars in the files it outputs, which it uses to prioritize certain chars over others.
=> Generate stable test outputs for better bundle-size comparisions

extensions/amp-jwplayer/1.0/amp-jwplayer.js, extensions/amp-jwplayer/1.0/base-element.js, test/fixtures/e2e/bento/jwplayer.html
Moves consent retrieval to amp layer since it depends on amp service and consent in bento is still being tbd (?)
Creates minimal fixture for jwplayer.html
=> 🐛 fix jwplayer consent & add fixture

extensions/amp-base-carousel/1.0/component.js, extensions/amp-lightbox-gallery/1.0/consumer.js, extensions/amp-stream-gallery/1.0/component.js, src/preact/compat.js, src/preact/index.js
- Removes createPortal because it's not used
- Moves `toChildArray` to use implementation from `preact`
- Replace `forwardRef` from `preact/compat` with copy/pasted implementation: Preact has a bug that causes (a lot) of unnecessary extra code to be added to the bundle due to its side-effects. This PR manually implements `forwardRef` by copy/pasting the impl from the preact source so we don't take the extra cruft. We should change this use the exported `forwardRef` at whichever time preact fixes this bug. See issue for more information https://github.com/preactjs/preact/issues/3295
Reduces `bento.js` size from 18.038kb to 16.270kb (-1.768kb)
=> Remove extraneous preact/compat code in bento.js bundle

extensions/amp-base-carousel/1.0/component.js, extensions/amp-lightbox-gallery/1.0/consumer.js, extensions/amp-stream-gallery/1.0/component.js, src/preact/compat.js, src/preact/index.js
Reverts ampproject/amphtml#36901
Auto-merge strikes again.
Culprit: https://discuss.circleci.com/t/workflow-checking-showing-as-neutral-on-github-checks/41911/8
Action items:
=> Revert "Remove extraneous preact/compat code in bento.js bundle"

extensions/amp-brightcove/1.0/base-element.js, extensions/amp-date-display/1.0/base-element.js, extensions/amp-jwplayer/1.0/base-element.js, extensions/amp-twitter/1.0/base-element.js, extensions/amp-youtube/1.0/base-element.js, src/preact/base-element.js, src/preact/parse-props.js, test/fixtures/e2e/amp-fit-text/1.0/amp-fit-text.html, test/unit/preact/test-base-element-mapping.js
Partial for #36899
Refactor `{attrPrefix}` and `{type: 'date'}` so that they resolve to a `{parseAttrs}` config instead.
This allows extension bundles to include these parsing mechanisms independently, rather than sharing it as part of `PreactBaseElement`.
All Bento extensions are 0.03 kb to 0.25 kb smaller as a result. The `bento.js` binary should see similar savings once it includes shared dependencies.
=> 🏗  Extract `{attrPrefix}` and `{type: 'date'}` from `parseProps()`

extensions/amp-carousel/0.1/amp-carousel.js, extensions/amp-carousel/0.1/build-dom.js, extensions/amp-carousel/0.1/carousel-controls.js, extensions/amp-carousel/0.1/scrollable-carousel.js, extensions/amp-carousel/0.1/shame.d.ts, extensions/amp-carousel/0.1/slidescroll.js, extensions/amp-carousel/0.1/test/test-scrollable-carousel.js, extensions/amp-carousel/0.1/test/test-slidescroll-slides.js, extensions/amp-carousel/0.1/test/test-slidescroll.js, test/integration/test-amp-carousel.js
**summary**
Final piece for server-rendering amp-carouse-0.1 (https://github.com/ampproject/amphtml/issues/36299).
Implements both `buildDom` and hydration within the `build-dom.js` file.
- The primary `buildDom` has been split into 3 sub-builders. `buildCarouselControls`, `buildSlideScrollCarousel`, `buildScrollableCarousel`. Each of these sub-builders has an associated `queryXYZ` function for implementing hydration.
- All side effects for each of these files have moved to a `setupBehavior` function. 
- All properties were converted to attributes.
**testing**
=> compiler: create buildDom for amp-carousel 0.1

extensions/amp-carousel/0.1/scrollable-carousel.js, extensions/amp-carousel/0.1/slidescroll.js
**summary**
I just merged in a pretty stale branch without realizing that I've also made a different change in the meantime which conflicts. Should have rebased. 
This is now caught by type checking!
Yay for type checking.
- Stale branch: https://github.com/ampproject/amphtml/pull/36602
- Conflict: https://github.com/ampproject/amphtml/pull/36869
=> amp-carousel-0.1: fast-followup fix for outdated merge

extensions/amp-sidebar/1.0/test-e2e/test-bento-sidebar.js
The bento-sidebar e2e test is rather flaky. I believe this may have something to do with animations. Seeing how the amp-sidebar e2e test is technically doing the same thing, but is not flaky. I will check the location of the sidebar to make sure the animation is done before doing anything else.
=> ✅ [bento-sidebar] refactor e2e test to hopefully be less flaky

build-system/common/esbuild-babel.js, build-system/common/transform-cache.js, build-system/compile/pre-closure-babel.js
In the old code, `batchedRead` performed a file read, and hashed the contents with an input `optionsHash`. But `batchedRead` is designed to allow multiple callers to share the same file, and they may provide different `optionsHash`es. When this happened, only the first caller's read+`optionsHash` would be used, and the 2nd+ caller would receive the first caller's hashes!
This simple fix is to move this out of `batchedRead` and let that _just_ read and hash the file contents. If you want to rehash with options, do that afterwards.
=> 🏗️ 🔥  Fix batchedReads being shared by different callers

build-system/tasks/helpers.js
Part two of #36937, because apparently Terser doesn't share the mangler for both variables and properties.
=> Use stable identifier mangling for properties

.github/workflows/publish-npm-packages.yml
In attempt to fix `npm publish` 404 errors.
=> 🏗  Rename npm publish env vars

.renovaterc.json
**summary**
Updates Renovate Configuration to immediately create PRs for updates to `@ampproject`.
Does that by setting schedule to null, which equates to default settings, which equates to "at all times" ([docs](https://docs.renovatebot.com/configuration-options/#schedule))
**to test**
```
npm install -g renovate
renovate-config-validator .renovaterc.json
```
=> renovate: immediately bump deps from @amppproject

extensions/amp-bind/0.1/bind-expression.js, extensions/amp-bind/amp-bind.md
**summary**
`<amp-bind>` expression limits were last rebalanced on May 2018 https://github.com/ampproject/amphtml/pull/15517.
It has always been a relatively conservative, and median CPUs have also improved in the past 3 years. It makes sense to bump the number.
New AST size limit is 250.
**testing notes**
On my much-faster-than-median-phone 2018 MBP, with only a single run (this is nowhere near statistically valid):
```
200 nodes  eval took: 3ms
600 nodes  eval took: 3ms
1000 nodes eval took: 5ms
5000 nodes eval took: 9ms
```
=> bind-expression: bump max expression size.

src/friendly-iframe-embed.js, src/polyfills/index.js
The only ESM browser that doesn't support CEv1 is Firefox 60-63, which we've now decided is not worth supporting.
Re: https://github.com/ampproject/amphtml/issues/36908
Fixes https://github.com/ampproject/amphtml/issues/36908
=> Remove CEv1 polyfill from ESM binaries

extensions/amp-story/1.0/amp-story-store-service.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/animation.js, extensions/amp-story/1.0/embed-mode.js
Allows viewers setting this param to disable animation. Referred to as `EmbedMode.PREVIEW` in the codebase.
=> ✨[amp-story] Disable first page animations when `#embedMode=3`

src/service/performance-impl.js, test/unit/test-performance.js
LCP isn't a cumulative metric (later entries don't change the value of the first), so it makes no sense to wait for more metrics to come in. This may be the final reason our CSI metrics don't align with UKM data. LCP pass rate appears low, but it's just because we're not receiving the metric at all even though the LCP already fired.
=> Flush LCP metric once it's received

extensions/amp-geo/0.1/amp-geo.js, extensions/amp-geo/0.1/test/test-amp-geo.js
The design of the amp-geo server side rendering of amp-geo related classes prioritizes the number of bytes that we can cache. This forces us to add the "prerender" hinting classes on the `html` element as the `body` element can be very far from the byte start of the document. (imagine for example a document with a fully used `style[amp-custom]` which has an allowed 75kb worth of data as of writing).
- render the amp-geo related classes (geolocation/groups) to the `html` element as well as the `body` element.
- prioritize `html` as the element to scan for `prerender` hinting classes
- fix off by 1 error in `clearPreRender`
I didn't make the change to us-ca as i wanted to do it in a separate PR for further discussion if there are any implications in doing so such as, would a publisher be …
=> allow amp-geo server side rendering on cache

src/bento.js
Without this, the wrapper function will be held in memory, with all the source code needed to create new instances of everything inside.
=> 🚀  Ensure we free waiting BENTO wrapper functions

extensions/amp-story/1.0/amp-story-store-service.js, extensions/amp-story/1.0/amp-story-unsupported-browser-layer.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story-store-service.js, extensions/amp-story/1.0/test/test-amp-story.js, extensions/amp-story/1.0/utils.js
Refactors Unsupported Browser Layer to minimize bundle size and complexity.
These are compressed size deltas:
Browsers that run the `module` build support all detected features, so the unsupported browser layer is unnecessary. We strip it out completely.
We remove some complexity by encapsulating the layer so that it's cleanly stripped out from the `module` build. As a result, the size of the `nomodule` build also reduces.
=> ♻️🚀 amp-story: Refactor unsupported browser layer for size

build-system/tasks/make-extension/template/shared/extensions/amp-__component_name_hyphenated__/amp-__component_name_hyphenated__.md, extensions/amp-accordion/1.0/README.md, extensions/amp-base-carousel/1.0/README.md, extensions/amp-embedly-card/1.0/README.md, extensions/amp-fit-text/1.0/README.md, extensions/amp-instagram/1.0/README.md, extensions/amp-jwplayer/1.0/README.md, extensions/amp-lightbox-gallery/1.0/README.md, extensions/amp-lightbox/1.0/README.md, extensions/amp-sidebar/1.0/README.md, extensions/amp-social-share/1.0/README.md, extensions/amp-soundcloud/1.0/README.md, extensions/amp-stream-gallery/1.0/README.md, extensions/amp-timeago/1.0/README.md, extensions/amp-twitter/1.0/README.md, extensions/amp-video/amp-video.md, extensions/amp-wordpress-embed/1.0/README.md, extensions/amp-youtube/amp-youtube.md
This is to keep the first example simple.
=> 📔 Bento: split code samples into static and dynamic version

build-system/pr-check/bundle-size-module-build.js, build-system/pr-check/bundle-size-nomodule-build.js, build-system/tasks/dist.js, build-system/tasks/helpers.js
The mangle cache is necessary when generating multiple binaries which need to interact. However, our bundle size workflow doesn't actually run the code, it just needs to estimate the size impact a PR causes.
Hopefully fixes #37014.
=> Stable bundle size by disabling mangle cache

build-system/tasks/helpers.js, build-system/tasks/runtime-test/runtime-test-base.js
**summary**
Partial for https://github.com/ampproject/amphtml/issues/36453
By default esbuild will utilize browser, module, main in that order ([docs]()). This PR swaps the priorities of module/browser for better tree shaking of our dependencies. In particular, this allows for the elision of the [cache-url](https://github.com/ampproject/amp-toolbox/tree/main/packages/cache-url) package.
**size diff**
```diff
- ✔ dist/v0/amp-story-0.1.mjs               73.40 kb   –          353.52 kb  
- ✔ dist/v0/amp-story-1.0.mjs               73.40 kb   –          353.52 kb 
+ ✔ dist/v0/amp-story-0.1.mjs               71.09 kb   –          347.51 kb  
+ ✔ dist/v0/amp-story-1.0.mjs               71.09 kb   –          347.51 kb  
```
=> esbuild: prioritize "module" over "browser"

extensions/amp-carousel/0.2/amp-carousel.js, extensions/amp-carousel/0.2/test/test-type-slides.js
The test code was copied from 0.1 tests:
https://github.com/ampproject/amphtml/blob/5df91d394d6e41a03dba8d3ceb950ed2ba4fe1ea/extensions/amp-carousel/0.1/test/test-slidescroll.js#L1543
/to @samouri
=> 🐛 Allowlist amp-carousel 0.2 goToSlide for email

build-system/tasks/css/jsify-css.js, extensions/amp-video-docking/0.1/amp-video-docking.css
This should save some bytes on SVGs that appear inside our CSS as `data:image/svg+xml`.
=> Do not encode CSS SVGs

src/video-interface.js
`esbuild` lacks the `@interface` concept from Closure. As a result, it believes that `VideoInterface.prototype.element;` could have side effects, and preserves the empty class. Bundles that import utilities from `src/video-interface.js` include this useless class.
We avoid this issue by defining dynamic getters instead.
=> ♻️ Prevent `VideoInterface` class from being bundled

extensions/amp-story/1.0/amp-story-system-layer.js, src/amp-story-player/amp-story-player-impl.js, src/amp-story-player/event.js
By importing `AMP_STORY_PLAYER_EVENT` (whose value equals its name), we're accidentally bundling all of `@ampproject/toolbox-cache-url`. It's equivalent to `2.30 kb` compressed (!!!)
Closure knew how to remove this code, but esbuild does not. We move the string to a standalone file.
=> ♻️🚀 Remove side-effect bloat from `amp-story` bundle

build-system/tasks/helpers.js
This is a test to see what the bundle size impact is. Now that https://github.com/ampproject/amphtml/issues/37014 is fixed, this isn't strictly necessary anymore.
=> Remove stable terser id mangling

extensions/amp-story/1.0/amp-story-embedded-component.js, extensions/amp-story/1.0/logging.js, extensions/amp-story/1.0/page-advancement.js
Some parts of the code used to have extra spaces due to splitting strings into multiple newlines, making the indentation part of the bundle size.
=> 🚀 [Story performance] Removed spaces in strings

extensions/amp-story/1.0/amp-story-page.js
Before this change we were ignoring the actual selector passed to `getMediaBySelector_` and always selecting video and audio elements if the page was an ad. 
This change respects the selector but removes the `amp-story-grid-layer` ancestor as these do not exists inside the FIE.
=> 🐛 [amp-story] fix FIE media selector

build-system/tasks/extension-helpers.js, build-system/tasks/helpers.js
In #36976, we changed our implementation of `forwardRef` from being a simple wrapper around `preact/compat` to a custom-written implementation. There a bunch of side-effects in `preact/compat` that we don't want in addition to the `forwardRef` side-effect that we do want. This means that the side-effect now lives in `src/preact/comapt.js`.
When building React binaries, we do a simple dependency remapping that swaps literal `import ... from 'preact/compat'` into `import ... from 'react'`. This worked perfectly when we were wrapping `preact/compat`, because the side-effect import would be remapped directly to `react`. But now that we moved our side-effect into `src/preact/compat.js`, we need to update our remapping logic to handle this. Now, when a component imports from …
=> Fix forwardRef in react builds

extensions/amp-lightbox/1.0/README.md, extensions/amp-lightbox/1.0/example/index.html, extensions/amp-sidebar/1.0/README.md, extensions/amp-sidebar/1.0/example/index.html, test/fixtures/e2e/bento/lightbox.html
See https://github.com/ampproject/bento.dev/pull/131:
<blockquote cite="https://github.com/ampproject/bento.dev/pull/131">
Since `bento-lightbox` and `bento-sidebar` have these [style](https://github.com/ampproject/amphtml/blob/b78e8781ff3976b3bff1ba881cf66dd2609b5c07/extensions/amp-sidebar/1.0/amp-sidebar.css#L3-L6) [rules](https://github.com/ampproject/amphtml/blob/b78e8781ff3976b3bff1ba881cf66dd2609b5c07/extensions/amp-lightbox/1.0/amp-lightbox.css#L3-L6):
```css
/* Pre-upgrade: not displayed */
amp-sidebar[hidden] {
display: none !important;
}
```
```css
/* Pre-upgrade: not displayed */
amp-lightbox[hidden] {
display: none !important;
}
```
If the `amp-sidebar` or `amp-lightbox` does not initially have the `hidden` attribute, then there is a flash of unstyled content (FOUC): …
=> 🐛 Add `hidden` attribute to `bento-lightbox` and `bento-sidebar` to prevent FOUC

src/core/dom/element.nonce.extern.js, src/core/dom/index.js, src/service/extension-script.js, src/validator-integration.js, test/unit/test-validator-integration.js
**summary**
Related: `b/160931736`
Recently, browsers have updated their handling of the `nonce` s.t. it is only accessible via property access and not via attribute. This PR updates our handling to support the new recommendations. Notably, it seems that presence check still works via CSS Selector, just value retrieval fails (empty string is returned)
I verified that the nonce detection still works in Chrome/FF/Safari. 
- Both Chrome and FF follow new spec and automatically hide the nonce attribute value for scripts added to head.
- Safari hasn't implemented this yet.
=> Update nonce propagation to retrieve value via property

extensions/amp-base-carousel/1.0/component.js, extensions/amp-lightbox-gallery/1.0/consumer.js, extensions/amp-stream-gallery/1.0/component.js, src/preact/compat.js, src/preact/index.js
Because `import {Children} from '#preact/compat'` is automatically remapped to `import {Children} from 'react'`, we need to use the official interface for interacting with renderable children.
Fixes https://github.com/ampproject/amphtml/issues/37111#issuecomment-987078671
=> Implement Children interface in Preact

ads/_config.js, extensions/amp-auto-ads/0.1/test/test-wunderkind-network-config.js, extensions/amp-auto-ads/0.1/wunderkind-network-config.js
This PR updates the Wunderkind `amp-ad` and `amp-auto-ads` to support full-width ads.
It also updates spacing and ad count settings per our customers' requests.
Fixes #37068
=> 🐛 Add support for Wunderkind full width ads

build-system/npm-publish/write-package-files.js
Copies the (p)react styles from an extension's package's `dist` folder to the root to support importing (p)react styles from the root of the package (e.g `import '@bentoproject/foo/styles.css'`).  
I could have also modified the `buildNpmCss` function in `extension-helpers.js` but that would generate a bunch of extensions/**/styles.css files that would need to be added to the gitignore and amp clean list. 
Couple questions I wanted to confirm:
* is `extension` always only 1 extension or can it be a comma-separated list of multiple extensions. From the `publish-npm-package.yml` looks like it should only be called with 1 extension at a time?
* is the version always 1.0? Looks like that should be the case, but please confirm
=> 🐛 copy react styles to root of each package before deploying

build-system/server/new-server/transforms/css/css-transform.ts, build-system/server/new-server/transforms/utilities/lazy.ts
This fixes the crash that happens when calling `amp visual-diff --empty` without building the runtime first: https://app.circleci.com/pipelines/github/ampproject/amphtml/20371/workflows/a8e75693-6c6b-4870-8433-38280f5e1b04/jobs/391367?invite=true#step-113-45
=> 🏗🐛 Lazy-load built files in the built-in server's CSS transformer

src/service/ampdoc-impl.js, test/unit/test-ampdoc.js
In #36273, I switched from `Date.now()` to `performance.now()`, thinking it was a higher resolution timestamp time since the unix epoch. But, `performance.now` is relative to _page load time_ (or `performance.timeOrigin`), not the epoch.
This matters because our "since visible" metrics use the epoch as their base time, meaning the timestamps are roughly 1.6 trillion milliseconds. But `performance.now` is tiny, in the range of a few million for a page that was loaded an hour ago. When we calculated the "since visible", we received values that were still in the trillions when we expect millions.
By adding `performance.now()` and `performance.timeOrigin`, we get a timestamp relative to the epoch. Now when we calculate the "since visible", we get the correct values.
Fixes #37072.
=> Fix first visible timestamp and LCPV

extensions/amp-story/1.0/amp-story-info-dialog.css, extensions/amp-story/1.0/amp-story-system-layer.css
Part of #37044
The share menu CSS gets bundled 3 times in the CSS file, making the uncompressed `amp-story.js` much larger than needed. In practice 2 of these are not necessary, and the compressed bundle is good at optimizing them, but we want to get rid of them for when we extract the share menu.
=> 🚀 [Story performance] Remove extra share CSS styles duplicated

extensions/amp-auto-ads/0.1/anchor-ad-strategy.js
Rather than controlling this from the server side, we think it might be easier to do a client side change to filter out sticky attribute if the old amp-sticky-ad is being placed by amp-auto-ads. Once the switchover happens, we only need to do a client-side refactor.
=> Fix the bottom sticky issue: amp-sticky-ad element contains amp-ad sticky

docs/component-validator-rules.md
Remove `version: "latest"` as a suggestion for new components.
=> Remove 'version: "latest"'.

extensions/amp-carousel/0.1/carousel-controls.js, extensions/amp-carousel/0.2/amp-carousel.js, extensions/amp-carousel/0.2/test/test-type-slides.js
**summary**
Fixes https://github.com/ampproject/amphtml/issues/26396.
Navigating the 0.2 carousel via keyboard events seems to have never been setup properly. Fix was as simple as copying the handler code from 0.1. I also added a unit test for ensuring keyboard events work for navigation.
=> amp-carousel-0.2: fix keyboard navigation.

src/core/dom/static-template.js
**summary**
Fixes old bug in our `svgFor` codepath.
Found while adding `noImplicitAny` to our tsconfig.
=> 🐛 static-template: Fix FIE check for SVGs

src/core/window/interface.js
**summary**
Noticed a little case where we explicitly have support for IE. Removing as we've since turned that down, no need to waste bytes.
=> core/window/interface: small ie support removal

build-system/tasks/check-types.js
**summary**
Partial #35264
We no longer type check any directories with closure. So 🔪  it.
=> check-types: remove closure

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js
Story ads will ask embedded viewers for active player experiments. This is protected by an `isEmbedded()` check, but sometimes the story will be embedded in a player that does not support this message and throw an error. In that case we should catch the error and mark it as expected.
This does not have any effect on users.
=> 🐛[story-ads] Catch unsupported `playerExperiments` message

extensions/amp-carousel/0.1/build-dom.js, extensions/amp-fit-text/0.1/build-dom.js, src/builtins/amp-layout/build-dom.js
**summary**
In closure typed code, everything was assumed to be nullable unless it had an exclamation point. In TypeScript items are never considered nullable unless they have a `?`, i.e. `SomeType?`.
This PR just removes exclamation points now that they are noops.
=> tsc: Remove some exclaimation points, since not nullable by default.

src/core/types/function/date-global.d.ts, src/core/types/function/index.js
**summary**
Fixes a small bug that should only affect tests introduced in https://github.com/ampproject/amphtml/pull/37141.
**TODO**
Why didn't CI fail for the problem PR
=> src/core/function: grab Date off win

tsconfig.json
**summary**
An accidental side effect of https://github.com/ampproject/amphtml/pull/37215 was to enable `checkJs` for the root tsconfig.
This causes VS Code to get very angry as all of `src` becomes subject to red squigglies / IDE-driven type errors.
Thanks for spotting it @alanorozco!
**screenshot**
=> root tsconfig: disable typecheck to save VS Code

extensions/amp-mustache/0.1/amp-mustache.js, extensions/amp-mustache/amp-mustache.md, src/purifier/index.js, src/purifier/sanitation.js, src/sanitizer.js, test/unit/test-purifier.js, test/unit/test-sanitizer.js
This allowlist of triple Mustache tags was shared with the email
format. triple-mustache is a pretty security sensitive feature in
the email format, and adding non-formatting tags like amp-img to
the allowlist requires a security review.
For some email clients (like Gmail) the Mustache is actually rendered
on the server side, and the server uses a different triple-mustache
allowlist. However, for consistency with email clients who don't
server-side render the template we should keep the client-side
sanitization consistent.
Using a separate list for email so we don't accidentally modify the
email format when there are requests to add new tags for the website
format (e.g., #32039). We can still add to the email allowlist on a
case-by-case basis.
/to @samouri
=> Use a separate triple Mustache allowlist for email

extensions/amp-wordpress-embed/1.0/amp-wordpress-embed.js
The `amp-wordpress-embed` component was created (in #34948) without any non-Bento version, so the Bento experiment is currently blocking it from being usable on valid AMP pages. This removes the experiment.
=> ✨ Remove Bento experiments from `amp-wordpress-embed`

examples/visual-tests/amp-story/amp-story-shopping.html, extensions/amp-story-shopping/0.1/amp-story-shopping-tag.css
Prevents tag dot and image from shrinking when there is text. In the tag.
Related to #37112
Text formatting will be added in #37039
=> 🖍 [amp story shopping] Prevent shopping tag dot and image from shrinking

validator/validator-main.protoascii
In the documentation for [`amp-mega-menu`](https://amp.dev/documentation/components/amp-mega-menu/#styling), the example advises the use of the [`aria-modal` attribute](https://w3c.github.io/aria/#aria-modal):
```html
<li>
<button aria-expanded aria-controls="unique_id" aria-haspopup="dialog">
...
</button>
<div role="dialog" aria-modal id="unique_id">
...
</div>
</li>
```
Nevertheless, `aria-modal` is not in the validator spec so this is invalid. It's true that `amp-meta-menu` is still experimental, but it seems this attribute should still be allowed regardless.
This PR adds the missing attribute.
=> ✨ Add missing `aria-modal` to global attributes in validator spec

extensions/amp-render/validator-amp-render.protoascii
Since `amp-render` is not Bento per https://github.com/ampproject/amphtml/pull/36601, the `bento_supported_version` flag should be removed from the validator spec.
=> ⏪ Remove `bento_supported_version` from `amp-render` validator spec

extensions/amp-lightbox/0.1/amp-lightbox.js, extensions/amp-lightbox/0.1/test/test-amp-lightbox.js, src/utils/close-watcher-impl.js, src/utils/close-watcher.extern.js, test/unit/utils/test-close-watcher-impl.js
Use [CloseWatcher API](https://wicg.github.io/close-watcher/) for amp-lightbox 0.1. It's supposed to be launched in Chrome 98. Some key benefits of this new API:
1. Reduces reliance on a global `window.history`.
2. Provides cleaner per-platform behavior. For instance, if platform has its own "close" gesture, then it's channeled via this API.
TODO:
=> Use CloseWatcher API in amp-lightbox 0.1

extensions/amp-story-page-attachment/0.1/amp-story-page-attachment.css
This prevents a potential line-break in remote attachments.
Fixes #37250
=> 🐛 [Amp story page attachment] Prevent "Opening" text from shrinking 

build-system/compile/compile.js, build-system/tasks/check-sourcemaps.js, build-system/tasks/dist.js, build-system/tasks/helpers.js, package-lock.json, package.json
The coast is clear to delete all the closure compilation code paths used during minification. The guts of the actual compilation still remain because they're used during type checking. They can be cleaned up after type checking moves to TS.
Related to #35264
=> 🏗🚮 Clean up closure compiler code paths no longer used by `amp dist`

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js
We were passing `skipAccountCreation` in config and it should be in `clientOptions`
=> 🐛 pass swg skipAccountCreation param in the right spot

build-system/babel-config/minified-config.js, build-system/babel-config/unminified-config.js, build-system/babel-plugins/babel-plugin-transform-rename-privates/index.js, build-system/common/esbuild-babel.js, build-system/common/transform-cache.js, build-system/tasks/css/jsify-css.js, build-system/tasks/extension-helpers.js, build-system/tasks/helpers.js, build-system/tasks/runtime-test/runtime-test-base.js
For some reason, Terser is using the already changed property names instead of the original names (which exist inside the babel sourcemap). Instead of letting Terser do the remapping, we'll use our `remapping` library to remap our minified output maps into real source code.
=> Use remapping to remap minified sourcemap into source code

build-system/tasks/helpers.js
There's a clash between sourcemap's files (which are always interpreted using POSIX `/foo/bar`) and Windows' files (which use `D:\foo\bar` paths). By not including the absolute `process.cwd()` in the `sourceRoot`, we can avoid joining POSIX and Windows filepaths during the sourcemap remapping load phase.
=> Fix remapping esbuild output on Windows

extensions/amp-carousel/0.1/build-dom.js, src/compiler/builders.js
**summary**
A necessary step for ssring `amp-carousel` is adding it to the builder map.
=> Compiler: Add amp-carousel-0.1 to the builder map

extensions/amp-story/1.0/pagination-buttons.js
Once the replay class was added, it was not being removed. Both classes were present resulting in always displaying the replay button 
Due to async between mutation and setting state the classList was not being updated properly.
This sets the state synchronously within the mutation.  
Fixes a regression from #37098
=> 🐛 [amp story] Replay/next page button bug fix

ads/google/a4a/utils.js, src/inabox/amp-inabox.js
Inserts the origin trial token for inabox so that it is possible for partner ad networks to use this feature.
=> Enable `attribution-reporting` API for inabox

src/compiler/README.md
It's currently empty because it's outputting a real `<amp-layout>` custom element, which can't render on GitHub.
=> Fix compiler link text

extensions/amp-carousel/0.1/carousel-controls.js, extensions/amp-carousel/0.1/scrollable-carousel.js, extensions/amp-carousel/0.1/slidescroll.js, extensions/amp-carousel/0.1/test-e2e/test-hidden-controls.js, extensions/amp-carousel/0.1/test-e2e/test-slidescroll-autoplay.js, extensions/amp-carousel/0.1/test/test-slidescroll.js, extensions/amp-fit-text/0.1/amp-fit-text.js, extensions/amp-fit-text/0.1/build-dom.js, extensions/amp-fit-text/1.0/component.js, src/core/context/node.js, src/core/context/scheduler.js, src/preact/base-element.js, src/preact/bento-ce.js, src/preact/compat.js, src/preact/component/3p-frame.js, src/preact/component/component.type.js, src/preact/component/contain.js, src/preact/component/iframe.js, src/preact/component/renderer.js, src/preact/component/wrapper.js, src/preact/context.js, src/preact/contextprops.js, src/preact/parse-props.js, src/preact/slot.js, src/preact/utils.js
**summary**
In closure, most types are nullable by default and required `!` to mark them as NonNullable.
This is no longer necessary in TS. This PR applies @rcebulko 🧙 magic🧙   SublimeText regex to a couple of directories to remove the needless noise from future PRs. 
**regex**:
- Find `((?:^ *|\/\*)\* @\w+ (?:[^*\n]|\*(?!\/))*)!(.*?(?:\*\/|$))`
- Replace: `$1$2`
**directories**
- extensions/amp-carousel/0.1
- src/preact
- src/core
=> small type cleanup: remove exclamation points

src/compiler/polyfills.js, tsconfig.base.json
**summary**
We should enable this feature to ensure we don't begin using features which require multi-file transpilation (would break compat with esbuild, babel, swc, etc).
See https://www.typescriptlang.org/tsconfig#isolatedModules
=> tsconfig: enable isolatedModules

package-lock.json, package.json, validator/build.py, validator/package-lock.json, validator/package.json
**summary**
Since `validator` is the only piece still needing closure compiler, moves the dep to its folder.
=> small build cleanup: move closure devDep to validator folder

.circleci/check_config.sh, .circleci/get_pr_number.sh
e.g., this line shouldn't happen: https://app.circleci.com/pipelines/github/ampproject/amphtml/21409/workflows/eebc003a-45ab-4f88-8b28-0d7182dcafcc/jobs/417934?invite=true#step-104-114
=> 🏗 Mark nightly branch as a push build in CircleCI shell jobs

.circleci/config.yml, .circleci/maybe_gracefully_halt.sh
Looks like Release jobs on CircleCI have been checking the existence of `experimentexperimentA` instead of `experimentA`... This PR fixes it and simplifies the code overall by consolidating two env variables together
=> 🏗 Fix incorrect flavor check on CircleCI release jobs

build-system/release-workflows/upload-release.js
Persisted file should be found in downstream jobs in the file `/tmp/restored-workspace/AMP_VERSION`
=> 🏗 Persist AMP version number between jobs in CircleCI release pipeline

OWNERS, src/compiler/OWNERS
**summary**
Marks `wg-performance` as owners of `src/compiler` and `**/tsconfig.json` as we are the authors/maintainers of both.
=> Update OWNERS for tsconfig and compiler

build-system/release-workflows/cut-nightly.js
Promoting immediately after the cut can (≈ will) cause a race condition, since the version hasn't finished building before we attempt to promote it. @estherkim has a PR out (#37408) to trigger the promote job directly from the build job
=> 🏗 Remove nightly promotion trigger from cut-nightly.yml workflow (undo #37328)

build-system/eslint-rules/forbidden-terms-config.js
ESLint API changed so that `node.start/node.end` do not exist anymore. 
This makes the lint rule fail opaquely:
```
[13:02:52] AssertionError [ERR_ASSERTION]: Fix has invalid range: {
"range": [
null,
null
],
"text": ""
}
```
These values are now an array `node.range`. Correct errors after fix:
```
build-system/test-configs/forbidden-terms.js
737:7  error  File does not exist  local/forbidden-terms-config
```
=> 🏗🐛 Fix range in `forbidden-terms-config`

build-system/test-configs/forbidden-terms.js, extensions/amp-story-dev-tools/0.1/amp-story-dev-tools-tab-preview.js, extensions/amp-story-dev-tools/0.1/amp-story-dev-tools.js, extensions/amp-story-page-attachment/0.1/amp-story-draggable-drawer.js, extensions/amp-story/1.0/amp-story-embedded-component.js, extensions/amp-story/1.0/pagination-buttons.js, src/amp-story-player/amp-story-player-impl.js
toggleAttribute is [not widely supported](https://caniuse.com/?search=toggleAttribute) so it fails on multiple platforms.
This PR uses the toggleAttribute utility function instead.
Fixes [#120](https://github.com/ampproject/error-reporting/issues/120), [#93](https://github.com/ampproject/error-reporting/issues/93)
=> 🐛 [amp story] Change toggleAttribute to set/removeAttribute

src/service/real-time-config/callout-vendors.js
Denakop (https://denakop.com/) has developed its own Prebid Server solution with AMP support to deliver Ads on AMP pages. With this Vendor's URL, any publisher will have the possibility of monetizing Ads on his site.
- Add Denakop as a vendor to RTC config
=> ✨ Add Denakop to RTC callout vendors

build-system/server/typescript-compile.js, build-system/tasks/check-types.js
**summary**
We've always had a command `amp check-types`. Historically we'd call `tsc` to typecheck the new-server and then closure compiler to check binary code.
Now that we use `tsc` for both, might as well merge the logic.
=> typecheck: merge new-server check with the rest.

build-system/babel-config/react-config.js, build-system/tasks/storybook/env/react/webpack.config.js
Run the same React-specific transforms on Storybook files as we do on component bundles.
In effect, this maps Preact-style prop names to React-style. This prevents issues like ``Invalid DOM property `class`. Did you mean `className`?``
Note that we still get an error for using `tabindex` instead of `tabIndex`. This is because our prop mapping is erroneously flipped. See #37459
=> 🏗 Apply Babel config to React Storybook

extensions/amp-bind/amp-bind.md
Add an example showing that it can be initialized to a constant, not just an object. (This is something I was never sure about when I first started using AMP.)
Note - I wasn't able to get the import to work on my local machine, so I tested this with an outdated version of the docs. It might be worth verifying this on a fully working build!
=> 📖 Mention that amp-state can contain a constant

build-system/common/preact-prop-names.js, build-system/eslint-rules/no-import-rename.js, build-system/eslint-rules/preact-preferred-props.js, extensions/amp-accordion/1.0/component.js, extensions/amp-accordion/1.0/component.type.js, extensions/amp-base-carousel/1.0/component.js, extensions/amp-base-carousel/1.0/scroller.js, extensions/amp-inline-gallery/1.0/thumbnails.js, extensions/amp-lightbox-gallery/1.0/provider.js, extensions/amp-lightbox/1.0/component.js, extensions/amp-selector/1.0/base-element.js, extensions/amp-selector/1.0/component.js, extensions/amp-sidebar/1.0/component.js, extensions/amp-social-share/1.0/base-element.js, extensions/amp-social-share/1.0/component.js, extensions/amp-social-share/1.0/component.type.js, extensions/amp-video/1.0/component.js, src/preact/utils.js
We've been incorrectly mapping `tabIndex` as the Preact-style prop name and `tabindex` as the React-style prop name. This should be reversed.
=> ♿ Flip `tabindex` prop mapping

build-system/eslint-rules/forbidden-terms-config.js, build-system/eslint-rules/html-template.js, build-system/eslint-rules/no-private-props.js, build-system/eslint-rules/preact-preferred-props.js
eslint changed the node API so that `.start/end` is no longer available, instead providing `.range`. 
This is the same change as #37422, but for the rest of the rules.
=> 🏗🐛 Fix uses of eslint `node.start/end` vs. `node.range`

tsconfig.json
**summary**
There is a bug in in that the root `tsconfig.json` includes `shame.d.ts` files. The module definitions end up overriding the correct files in the "Go To Definition" feature, even outside of the files that the shame file is relevant.
cc @calebcordry who alerted me to the issue :)
=> Fix GoToDefinition in IDEs

build-system/compile/helpers.js, build-system/tasks/helpers.js
Currently sourcemaps are being directed to a `raw.githubusercontent.com/ampproject/amphtml/${internalRuntimeVersion}` url which does not exist for the fake dev rtv, so it 404s.
=> 🐛 Fix sourcemaps in local dev server

extensions/amp-story-page-attachment/0.1/amp-story-open-page-attachment.js
Building the attachment was refactored as part of #37278 to be a separate component and introduced a regression which was not caught since Percy diffs were broken at the time of submitting the PR. `this.element` is now a reference to `amp-story-page-outlink` or `amp-story-page-attachment` and never `amp-story-shopping-attachment`.
This PR checks the parent element to see if it's an `amp-story-shopping-attachment` to create the appropriate label.
=> 🐛 [amp story shopping] shopping CTA label fix

build-system/compile/bundles.config.bento.json, src/bento/components/jwplayer/1.0/bento-jwplayer.css
When creating #36639 I didn't realize that `amp-jwplayer.css` was being used by the Bento code as well. As a result I did not move it with the rest of the code. This resulted in `bento-jwplayer-1.0.css.js` not being generated during build. Unfortunately this file is not imported during any of the tests and thus the build showed as green. The fastest fix for this is to copy the file over (and also clean up some naming). 
Before moving more components over I will do the following:
1) Come up with a test to detect this sort of issue.
2) Explore reversing the logic used to replace `amp` in the css files with `bento` and import the Bento css file from the AMP component. To reduce duplicate code.
=> 🐛  🏗 Copy jwplayer css to `src/bento`

test/integration/test-visibility-states.js
As part of https://github.com/ampproject/amphtml/issues/37129, I'm going to be adding tests to this file. It's bit-rotted a bit, with a few different conventions for doing the same thing. This migrates the file to use async-await in most places (instead of just a few) and generally standardizes the format/vertical spacing of the tests themselves.
=> ♻️ Async-ify and clean up test-visibility-states.js

extensions/amp-story-auto-ads/0.1/story-ad-page.js
So that they are not visible to screen readers until the ad itself is visible.
This works as expected with talkback, chromeOS & iOS. Voiceover appears to have a bug for mac only where it will read aloud the frame element even when `aria-hidden=true` is set on the parent `<amp-story-page>` element.
=> ♿ [story-ads] Add aria-hidden for ad pages

examples/amp-story/fake-ad.html, extensions/amp-story-auto-ads/0.1/story-ad-page.js, extensions/amp-story-auto-ads/0.1/story-ad-ui.js, extensions/amp-story-auto-ads/0.1/test/test-story-ad-ui.js, src/inabox/inabox-story-ad.js
Solves https://github.com/ampproject/amphtml/issues/37423
It pulls the meta tags from body once and filters them accordingly.
=> Add meta tag to variable list in story ads

extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-ad/0.1/amp-ad-3p-impl.js, extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js
Performance enhancement for sticky ads:
1. Force layout to address scenarios where the size is 0x0 and layout is not triggered.
2. Setup scroll callback earlier to catch more scrolls.
=> Force amp sticky ad layout and move scroll listener to earlier stage

build-system/tasks/helpers.js, build-system/tasks/sourcemaps.js
**summary**
Moves `massageSourcemaps` and `getSourcemapRoot` to its own file, `sourcemap.js`. 
Thats it
=> build-system: reorganize sourcemap logic

extensions/amp-story-page-attachment/0.1/amp-story-open-page-attachment.js, extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js, extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-attachment.js
This PR encapsulates shopping attachment logic by setting the `cta-text` attribute on the inner page-attachment element and includes a unit test.
=> ♻️ ✅ [amp story shopping] Move i18n CTA label logic into shopping-attachment component

build-system/tasks/storybook/env/amp/webpack.config.js, build-system/tasks/storybook/env/preact/webpack.config.js, build-system/tasks/storybook/env/react/webpack.config.js, src/preact/context.tsx
**summary**
1. Updates our three `webpack.config.js` (storybook) files to support TypeScript. There is ample opportunity to remove duplication among these configurations in future PRs.
2. Converts a single file within `src/preact` to typescript!
Note: there is no change to our binaries with this PR
=> 🎉  src/preact: convert first file to tsx

OWNERS
With the departure of @kristoferbaxter, we discussed adding an additional root-level owner of `amphtml` in https://github.com/ampproject/amphtml/pull/37504#pullrequestreview-865249169 so that @jridgewell isn't the only active contributor available to provide owners approval for root-level changes (e.g. base infra changes, large refactors, etc.).
This PR adds @rsimha (me) as an additional owner. Note that targeted changes affecting inner directories will continue to require reviews from their current owners, and this change only affects large scale changes that could use a single owners approval.
=> 🏗 Add `rsimha` as a root-level owner of `amphtml`

extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js, extensions/amp-story-shopping/0.1/amp-story-shopping-config.js, extensions/amp-story-shopping/0.1/amp-story-shopping.js, extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-config.js
Custom elements are heavy. `<amp-story-shopping-config>` does not render, or hold any state, so it does not need to be a component.
Instead of registering a custom element, use a parser function instead. 
(Note that this retains API and all other behavior).
=> 🚀♻️  amp-story-shopping-config: no custom element

.eslintrc.js, build-system/server/new-server/transforms/utilities/lazy.ts, build-system/tasks/performance/print-report.js
**summary**
Some inspo from https://www.executeprogram.com/blog/typescript-features-to-avoid.
The tldlr: is that we'd like to restrict ourselves to just "JS with types". This makes TS --> JS conversion significantly simpler and less error prone.
=> tslint: ban non-standard ecmascript features

build-system/tasks/extension-helpers.js, build-system/tasks/helpers.js
No longer necessary since the wholesale move to esbuild
=> build-system: cleanup esbuild options

src/preact/component/3p-frame.js
**summary**
We should not use the deprecated path in new code.
This breaks IE11 compat.
**bundle size diff**
```
extensions/amp-mathml/1.0/dist/component-react.js: Δ -0.41KB
dist/v0/bento-mathml-1.0.js: Δ -0.40KB
extensions/amp-embedly-card/1.0/dist/component-react.js: Δ -0.41KB
dist/v0/bento-embedly-card-1.0.js: Δ -0.40KB
extensions/amp-embedly-card/1.0/dist/component-preact.js: Δ -0.42KB
extensions/amp-twitter/1.0/dist/component-preact.js: Δ -0.40KB
extensions/amp-facebook/1.0/dist/component-react.js: Δ -0.42KB
extensions/amp-facebook/1.0/dist/component-preact.js: Δ -0.43KB
extensions/amp-mathml/1.0/dist/web-component.js: Δ -0.39KB
extensions/amp-embedly-card/1.0/dist/web-component.js: Δ -0.39KB
extensions/amp-twitter/1.0/dist/web-component.js: Δ -0.41KB
dist/v0/amp-twitter-1.0.mjs: Δ …
```
=> src/preact: use URL instead of parseUrlDeprecated

extensions/amp-story-page-attachment/0.1/amp-story-draggable-drawer-header.css
A thin drop shadow was intended to be added to the header as part of the header UI updates.
It was just noticed in the shopping UI design files and confirmed to be in the original UI update design file.
This PR 
- Adds the drop shadow.
- Renames the color variable so it makes sense used in additional places.
=> 🖍️ [amp story page attachment] Box shadow on header

build-system/pr-check/checks.js, build-system/pr-check/validator-tests.js, build-system/tasks/validate-html-fixtures.js, build-system/test-configs/config.js
Adding new validation rules while also adding new AMP code could result in a mismatch with the existing rules in the `amphtml-validator` npm pacakge, and lead to developer friction similar to https://github.com/ampproject/amphtml/pull/37414#discussion_r791078244.
This PR updates the `amp validate-html-fixtures` task to attempt to use the locally built wasm / js validator, failing which it will default to the wasm validator from the CDN.
Right now, this will result in CI checks using the locally built js validator. When the wasm validator is added to our CI workflow in future, the task will start using it.
Fixes #37467
=> 🏗 Use locally built validator during `amp validate-html-fixtures`

build-system/server/lazy-build.js, build-system/tasks/build-bento.js, build-system/tasks/extension-helpers.js
Components moved to `src/bento` bundle common dependencies instead of sharing with `bento.js`. They lack these options that enable module loading:
```js
{
wrapper: 'bento',
babelCaller: options.minify
? 'bento-element-minified'
: 'bento-element-unminified',
}
```
To fix this, they should use `buildBentoExtensionJs()`
---
See bundle size after change:
```
dist/v0/bento-accordion-1.0.mjs: Δ -12.25KB
dist/v0/bento-jwplayer-1.0.mjs: Δ -11.31KB
```
=> 🐛 Use `buildBentoExtensionJs` under `src/bento/components`

build-system/compile/bundles.config.js, build-system/tasks/dist.js, build-system/tasks/extension-helpers.js
It hasn't been used anywhere since we migrated to `esbuild`.
=> 🏗 Remove `extraGlobs` option

build-system/babel-config/test-config.js, extensions/amp-story-page-attachment/0.1/amp-story-open-page-attachment.js, extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js, src/core/dom/jsx/index.ts, test/unit/core/dom/test-jsx.js
Allows verifying the output of JSX elements whose style is set using an object.
=> 🏗♻️ Enable `babel-plugin-jsx-style-object` in tests

build-system/tasks/storybook/env/react/main.js
React Storybook references `extensions/` only. It should have an equivalent glob pattern under `src/bento/components`
=> 🏗🐛 Add `src/bento/components` to Storybook React paths

package-lock.json, package.json, test/unit/compiler/test-compile.js
Incorporates important fixes for boolean attributes: https://github.com/ampproject/bento-compiler/pull/40
/to @rcebulko 
Unsure why renovate didn't jump on this.
CP Incoming right afterwards.
=> dependencies: bump bento-compiler

build-system/tasks/build-bento.js
When writing the build-bento script I had originally planned to support a separate set of flags for building components. Upon reviewing the completed system I thought it was too complicated and removed what I thought to be all references. It seems like I missed this one.
=> 🏗  🐛 build-bento should respect no extensions

extensions/amp-facebook/0.1/amp-facebook.js, extensions/amp-facebook/1.0/base-element.js, extensions/amp-facebook/1.0/test/test-amp-facebook.js
Facebook recently deprecated its Embedded comments feature, and as such we added specific error/warn statements to alert authors to this change. However, `bento-facebook` never actually allowed `embedAs` to equal `comment` and this specific message is unnecessary. 
This PR also fixes the incorrect labeling of the `amp-facebook` warning as `bento-lightbox`.
=> 🐛[bento-facebook] Invert error conditions to make sure both errors are thrown appropriately. 

examples/amp-story/doubleclick.html, extensions/amp-story/1.0/amp-story-system-layer.css
~~Introduces new css that makes the pause button invisible to users, but accessible to screen readers. It then removes these properties if the button is visual shown (desktop, keyboard active mode)~~
Introduces CSS selector that will make pause button intractable when screen readers are used.
- On both one-panel and supports-landscape the pause button is always visible
- When keyboard becomes active the pause button will show on mobile
- When the screen reader focuses on the pause button it becomes visible on iOS but not android. This is because talkback does not appear to set the `:focus` pseudo class as expected. 
Partial #37393
=> ♿ [amp-story] Allow screen reader users to pause auto-advancing stories

build-system/tasks/helpers.js
This is fun. When babel performs internal remapping (when there is an input sourcemap), it just fails to output a valid sourcemap if the output has multiple source files (I actually recently fixed this...). When esbuild generates a sourcemap, it'll link to the map file with a `sourceMappingUrl` comment. Babel will try see that comment, and interpret the sourcemap as an input. And we hit the bug if the output has multiple sources.
This works fine on the initial build, because the map file hasn't been written to disk yet. But on a re-dist, the map file will exist, and babel will read it. This will cause a bug in our `@ampproject/remapping`, because we see a transformation that outputs an invalid map (and we throw an error).
=> 🏗️  Fix a bug with remapping when dist is run a second time

src/custom-element.js, test/unit/test-custom-element-v1.js
**summary**
Schedules an element to be laid out if it is the target of an amp-bind mutation.
Fixes https://github.com/ampproject/amphtml/issues/37400
=> R1: schedule amp-bind targets

build-system/babel-config/minified-config.js, build-system/babel-config/unminified-config.js, build-system/common/esbuild-babel.js, build-system/tasks/check-sourcemaps.js, build-system/tasks/helpers.js, build-system/tasks/release/index.js, build-system/tasks/sourcemaps.js, package-lock.json, package.json
Our sourcemaps got borked again by prepending code **without** updating the sourcemaps. To make this easy for both `AMP_CONFIG` and `AMP_EXP`, we're putting the `;\n` back at the beginning of every file. Basically a revert of https://github.com/ampproject/amphtml/pull/36008. revert revert revert revert…
=> 🐛 Insert empty newline as first line of minified outputs

build-system/pr-check/module-build.js
#37115 made the visual tests use the module build, but did not express a dependency so that the build is performed when a visual test is modified.
https://github.com/ampproject/amphtml/blob/49445839c2a35af58984299c0a77a924e23e45fd/build-system/pr-check/module-build.js#L28-L41
This PR adds the dependency.
=> 🏗 Make visual tests depend on module build

ads/_config.js
No need to preconnect to a domain that is being prefetched. Fixes https://app.circleci.com/pipelines/github/ampproject/amphtml/22850/workflows/27e01357-051d-45b4-a77d-2d57da0cf6ed/jobs/455841
Follow up to #37672
@github-vincent-mathon Let me know if you have any concern.
=> 🐛 Teads Ads: remove prefetch domain from preconnect

build-system/tasks/helpers.js
Fix a bug when bundling not being able to find, very specifically `src/preact/compat.js` when remapping dependencies for react.
But this fix should also cover any remap key that is missing the js or ts extension.
=> 🐛added optional extention matching for dependency remap when bundling

examples/compiler-hydration.html, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-carousel/0.1/test/test-scrollable-carousel.js, extensions/amp-carousel/0.1/test/test-slidescroll.js, extensions/amp-fit-text/0.1/test/test-amp-fit-text.js, src/core/dom/style.js, test/integration/test-video-manager.js, test/unit/builtins/test-amp-layout.js, test/unit/compiler/test-builders.js, test/unit/test-fixed-layer.js, testing/helpers/index.js
**summary**
While testing server-side transforms, I noticed [a bug in `worker-dom`](https://github.com/ampproject/worker-dom/issues/1134). Specifically, setting keys of the `style` prop on a node does not reflect in attributes properly. Instead [style.setProperty](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty) has to be used to trigger the  "PropertyBackedAttribute" flow.
Separately, if we actually need JS in `setStyles` to dynamically figure out vendor-specific prop names, that of course won't work either.
This PR does a few things:
1. Swaps applications of a few known style props (`width`, `height`, `order`) to be set with `setProperty`. I scanned the relevant components we plan on server-rendering and I believe this covers it.
2. Creates a new test …
=> 🐛  compiler.js buildDoms: ensure behavior matches browser

extensions/amp-story-interactive/0.1/amp-story-interactive-abstract.js, extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js, extensions/amp-story-shopping/0.1/amp-story-shopping-tag.js
Lazy load fonts by moving them to layoutCallback.
Removes a duplicate font load.
Note: this causes CLS if component is on the first page of a story.
Fixes #37684
=> 🚀 [amp story shopping] [amp story interactive] Load fonts in layoutCallback

testing/helpers/index.js
**why did CI not catch this in the PR that introduced the error?** (https://github.com/ampproject/amphtml/pull/37694).
Even after merging, need to investigate. Is `check-build-system` only run on push?
cc @rileyajones
=> build fix: build-system types

build-system/eslint-rules/forbidden-terms-config.js, build-system/tasks/storybook/env/amp/main.js, build-system/tasks/storybook/env/amp/register.js, build-system/tasks/storybook/env/disabled-stories.js, build-system/tasks/storybook/env/preact/main.js, build-system/tasks/storybook/env/react/main.js, build-system/tasks/storybook/package-lock.json, build-system/tasks/storybook/package.json, build-system/test-configs/forbidden-terms.js, extensions/amp-animation/0.1/storybook/Basic.amp.js, extensions/amp-animation/0.1/storybook/Random.amp.js, extensions/amp-animation/0.1/storybook/template.js
Related to #35923
`@storybook/addon-knobs` has been deprecated, and it's officially obsolete. This prevents us from upgrading the Storybook version due to a peer dependency conflict. 
This change:
- Removes `@storybook/addon-knobs`
- Disables Storybook files that require Knobs. We use the forbidden term allowlist to find disabled files. 
- Since `amp-animation` tests do not match the allowlist schema for disabling, we migrate those to Controls instead.
=> 🏗♻️🚮 Disable `@storybook/addon-knobs`

build-system/common/esbuild-babel.js
Windows uses `\` chars instead of `/`, so the allowance for `/node_modules/` paths didn't match.
=> Fix build for windows

css/ampdoc.css, examples/compiler-hydration.html, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-carousel/0.1/build-dom.js, extensions/amp-carousel/0.1/slidescroll.js, extensions/amp-fit-text/0.1/test/test-amp-fit-text.js, src/compiler/builders.ts, src/core/dom/style.js, test/unit/core/dom/test-style.js, test/unit/test-fixed-layer.js, test/unit/test-friendly-iframe-embed.js, testing/helpers/index.js
**summary**
Server-rendering AMP Components should allow us to have UI visible without blocking on JS executaion.
Via disabling JS locally, I was surprised to see that this wasn't the case yet.
We still have two issues stopping `<amp-carousel>` from rendering without JS:
1. Loading extension CSS is still bundled with JS execution. We need to add a `<style>` link to the CSS to the `<head>`.
2. The application of class names which unhide the amp-carousel take place in `layoutCallback` instead of `buildDom`.  In this case it is the addition of `i-amphtml-element` and `i-amphtml-slide-item-show`.
I solve (2) in this PR, and am working on (1) separately.
🚀 🚀 🚀  **results** 🚀 🚀 🚀 
For webpages with their LCP Element in the amp-carouse, we can expect a ~40% improvement to LCP. …
=> 🚀 🚀 🚀  amp-carousel ssr: allow render without JS 🚀 🚀 🚀 

build-system/release-workflows/upload-release.js
Partial for https://github.com/ampproject/cdn-worker/pull/91
Tested running this script on my machine and the compression phase pass. I don't have a gcloud upload key locally (nor should I) so the script failed when attempting to actually upload the files, but it looks like the compression part is complete and the upload part hasn't changed
=> Pre-compress release files in Brotli before uploading

build-system/release-workflows/cut-nightly.js
The API by default returns the first 30 results. Since now each Bento component has its own publish action, there are many more than 30 results, causing us to miss the self-check in the API (and worst, we could miss actual failures) - instead of setting a `per_page` value I prefer to use [`.paginate`](https://octokit.github.io/rest.js/v18#pagination) here to guarantee we get all results
// cc: @samouri
=> Paginate check runs in cut-nightly workflow

extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js
Original `attachmentEl_` is discarded in the same element callback. Don't create it.
=> ♻️ `amp-story-shopping-attachment`: Remove duplicate `-page-attachment`

extensions/amp-ad/0.1/amp-ad-ui.js, extensions/amp-ad/0.1/amp-ad.css
The viewer debug tool actually behaves differently than a real viewer in that the fixed layer automatically adjusts by viewer's paddingTop. This PR:
1. Set `top` css to 0 and attaches the sticky ad to the fixed layer so that its top automatically gets adjusted.
2. Hide the top sticky ads when scrolled to top and show it upon scrolling down again.
=> 🐛 Fix viewer banner/top sticky ads conflicts

examples/amp-story/amp-story-shopping.html, examples/visual-tests/amp-story/amp-story-shopping-lang-de.html, examples/visual-tests/amp-story/amp-story-shopping-rtl.html, examples/visual-tests/amp-story/amp-story-shopping.html
Rearranges examples and images for the amp-story-shopping component.
Static images are added in the visual tests to avoid test flakiness.
=> 🐛 amp-story-shopping Get examples and visual diff tests ready for dev preview

examples/amp-story/amp-story-shopping.html, examples/visual-tests/amp-story/amp-story-shopping-lang-de.html, examples/visual-tests/amp-story/amp-story-shopping-rtl.html, examples/visual-tests/amp-story/amp-story-shopping.html, extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.css, extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js, extensions/amp-story/1.0/_locales/en.json, src/service/localization/strings.js
Adds a plaintext expandable/collapsable details section to the PDP template.
Adds i18n string.
[Demo](https://philipbell-shopping.web.app/examples/amp-story/amp-story-shopping.html)
Fixes #36740
=> ✨ [amp story shopping attachment] Add details module to PDP template

examples/amp-story/amp-story-shopping.html
Bringing back images to the example template that is not a visual diff test. Follow up to #37733
=> [amp story shopping] bring back images to example

extensions/amp-story-shopping/0.1/amp-story-shopping-tag.js
There is a race condition where the tag will sometimes not get the `active` attribute.
This happens when the layoutCallback runs after the `CURRENT_PAGE_ID` state is set on load.
callToInitialize is also added to RTL state in this PR since this may also happen in that case.
=> 🐛 [amp story shopping tag] Call To Initialize listeners

extensions/amp-story-share-menu/0.1/amp-story-share-menu.js, extensions/amp-story-share-menu/0.1/test/test-amp-story-share-menu.js, extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js, extensions/amp-story-shopping/0.1/amp-story-shopping-config.js, extensions/amp-story-shopping/0.1/amp-story-shopping-tag.js, extensions/amp-story-shopping/0.1/amp-story-shopping.js, extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-config.js, extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-tag.js, extensions/amp-story/1.0/test/test-utils.js, extensions/amp-story/1.0/utils.js
Element implementations are able to use the synchronous Story service getters by wrapping their class in `dependsOnStoryServices`. This simplifies the initialization flow.
This reduces the compressed size of each extension by ~0.5 kb, by stripping out the base definition of asynchronous getters entirely.
=> 🚀♻️ Use sync services in `amp-story-shopping` and `amp-story-share-menu`

build-system/npm-publish/get-extensions.js, build-system/npm-publish/utils.js, build-system/npm-publish/write-package-files.js, build-system/release-tagger/make-release.js, build-system/release-tagger/test/make-release.test.js, build-system/tasks/build-bento.js
Components in the `src/bento/components` directory have not been getting picked up by the `publish-npm-packages` workflow. My fix is to ensure the workflow reads the `bundles.config.bento.json` file as well as the `bundles.config.extensions.json` file and adds the adds knowledge of the new `src/bento/components` directory to the build flow.
#37737
=> 🏗 🐛 Release-tagger should respect the bundles.config.bento.json file

.github/workflows/publish-npm-packages.yml
Tagalong changes:
- change `ampversion` to `amp-version` to be consistent with promote workflows
- enforce dropdown on tag input when running manually (not allowed on workflow_call event)
=> Let cdn-configuration trigger npm publishing

extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/media-pool.js, extensions/amp-story/1.0/test/validator-amp-story-video-error.html, extensions/amp-story/1.0/test/validator-amp-story-video-error.out, extensions/amp-video/0.1/amp-video.md, extensions/amp-video/validator-amp-video.protoascii
This PR fixes #37372 and enables a few things:
- it allows the volume attribute on an amp-video in stories to be set to 0
- it removes the unmute button when the volume is set to 0
- it sets media with noaudio to a volume of 0
=> ✨ [amp-story] Enables volume=0 and sets noaudio to be an alias for volume=0

extensions/amp-auto-ads/0.1/ad-network-config.js, extensions/amp-auto-ads/0.1/adsense-network-config.js, extensions/amp-auto-ads/0.1/alright-network-config.js, extensions/amp-auto-ads/0.1/amp-auto-ads.js, extensions/amp-auto-ads/0.1/denakop-network-config.js, extensions/amp-auto-ads/0.1/doubleclick-network-config.js, extensions/amp-auto-ads/0.1/firstimpression.io-network-config.js, extensions/amp-auto-ads/0.1/ping-network-config.js, extensions/amp-auto-ads/0.1/premiumads-network-config.js, extensions/amp-auto-ads/0.1/test/test-adsense-network-config.js, extensions/amp-auto-ads/0.1/wunderkind-network-config.js
We have found that in some pages, where both amp-auto-ads and adsbygoogle tags are present, both could load anchor ads and conflict with each other. This PR aims at fixing that.
=> Adsense to disable anchor ads if detected non-amp adsbygoogle tag

examples/visual-tests/amp-story/amp-story-shopping-landscape.html, extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.css, test/visual-diff/visual-tests.jsonc
The responsive UI for the shopping experience breaks in desktop full-bleed since it's displayed in a modal with a static width.
This PR sets a static size for the UI in desktop supports-landscape.
[Demo](https://discovery-ec239.web.app/examples/amp-story/amp-story-shopping.html)
Before:
After:
We may want to re-visit the full-bleed attachment experience to be more consistent with mobile but this will allow the shopping experience to be functional in desktop full-bleed for the time being.
=> ✨ 🖍 [amp story shopping] Display in desktop supports-landscape

extensions/amp-story/1.0/amp-story-system-layer.css
Regression introduced in #37582 When adding our "visible to screen reader only logic" I failed to notice new padding that was introduced when videos are playing in a story page.
Bad:
Good:
TODO: see if we can write a visual test that would have caught this regression.
=> 🐛 [story] fix spacing when pause button is hidden

build-system/compile/bento-remap.js, build-system/tasks/extension-helpers.js
Bento components in the `src/bento/components` try to remap dependencies on themselves. Thank you @alanorozco for the help on this.
=> 🏗  🐛 Fix issue with bento dependency remapping for peers

examples/amp-story/amp-story-shopping.html, extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js
Allow the template to render if `aggregateRating` is not defined. 
Ensure spacing is maintained between "title" and "buy now".
=> ✨ [amp story shopping] Optionally render rating

extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.css
This PR adds CSS targeting for border radius around a single image in RTL.
Before:
After:
=> 🌐 🖍 [Amp story shopping] Border radius on single image in RTL

extensions/amp-story-shopping/0.1/amp-story-shopping-tag.js
Closes #37749
There is an issue with the shopping data: the shopping tags subscribe to changes to the shopping data in the store service. However, it may not always be the case that the correct data will be loaded for the tag as sometimes the promises are unresolved, such as the case with remote data.
To fix this problem,  we have added an additional conditional check for making sure that the data is loaded first before rendering. We have also refactored it so it only adds the shopping tag listeners after a valid shopping tag is created, not in the layout callback.
=> Fixes amp-story-shopping shopping tag not showing up on refresh when using remote data

build-system/npm-publish/write-package-files.js, build-system/tasks/extension-helpers.js
* adds `@bentoproject/core` as a (pinned) dependency of every extension
* enables extension npm standalone binaries to use core package for common code
Partial https://github.com/ampproject/amphtml/issues/37546
Blocked by: https://github.com/ampproject/amphtml/pull/37645
=> 🏗 Enable @bentoproject/core dependency for npm bento standalone extensions

build-system/common/esbuild-babel.js, build-system/compile/bento-remap.js
When attempting to fix Bento component peer remapping, I introduced a bug where the remapped paths do not work on Windows.
#37797
=> 🏗 🐛 Fix bento peer dependency remapping on Windows

build-system/release-workflows/build-release.js
See example release build: https://app.circleci.com/pipelines/github/ampproject/amphtml/23608/workflows/387e9047-ccf0-41ec-acaa-73c2d98a7528/jobs/476041/artifacts
=> Add a custom-config.json to the automated releases that uses ampjs.org as the default runtime CDN

ads/vendors/broadstreetads.js
This PR updates the URL to our initialization script to a more recent/widely used version for the default value.
=> ✨ [amp-ad broadstreetads] Replaced default value for initUrl

src/service/real-time-config/callout-vendors.js
We discussed the change of the AMP parameter 'gdpr_consent' in today's Prebid Server committee meeting. Want to change it to the more generic 'consent_string'. Both have been supported by PBS-Go and PBS-Java for a long time. Also noticed that old PR https://github.com/ampproject/amphtml/pull/30712 was never merged. Combined the changes here -- will close the old one.
Fixes https://github.com/prebid/prebid-server/issues/1167
(FWIW - there's no emoji for "config change", so picked the bug.)
Adding @syntaxnode to confirm the appnexus string changes, which we discussed in the meeting today. I'm authoritative for the rubicon changes.
=> 🐛 callout-vendors updates for rubicon and appnexus

.github/workflows/publish-npm-packages.yml, build-system/npm-publish/write-package-files.js
=> Get corePkgVersion from github workflow job output instead of package.json

extensions/amp-story-shopping/0.1/amp-story-shopping-tag.css, extensions/amp-story-shopping/0.1/amp-story-shopping-tag.js, extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-tag.js
#closes https://github.com/ampproject/amphtml/issues/37808
Some animation CSS keyframes were not calculating the border-radius properly, this PR fixes them.
=> 🐛 amp-story-shopping removes support for different multi-line border radii

build-system/babel-config/import-resolver.js, build-system/babel-config/minified-config.js, build-system/babel-config/react-config.js, build-system/babel-config/unminified-config.js, build-system/tasks/storybook/env/preact/webpack.config.js, build-system/tasks/storybook/env/react/webpack.config.js, src/react/dom.js, src/react/index.js
This work is also incorporated in #37385, but this is just the module replacement that allows Bento components to use external libraries that rely on React. 
The original problem: `react-day-picker` (the library that is used for the date picker under the hood) relies on React. Without any module replacement, rendering the day picker component in Bento mode doesn't render the calendar and fails silently. Aliasing `react` to `preact/compat` also results in some weird compatibility issues between `preact/compat` and `src/preact`. 
While the compiled bento code `bento.js` or `bento.max.js` also exports all the necessary React functions from `src/preact`, it is incompatible with synthetic default import syntax (`import React from 'react'`) used by many libraries.
Doing this module replacement …
=> Add react remapping to import resolver plugin

build-system/tasks/extension-helpers.js, build-system/tasks/helpers.js, build-system/tasks/remap-dependencies-plugin/remap-dependencies.js, build-system/tasks/remap-dependencies-plugin/test-remap-dependencies.js
needed because resolvePath() only handles local modules
We would run into this anytime we would try to remap to non-external node module. But we don't actually run into this bug yet because whenever we remap to a node module (`react`), we're also setting it as an external, so it never calls resolvePath(). 
The tests already assume this, so they don't need to change
=> handle remapping to a node module that is bundled

build-system/compile/json-schema/index.js
Fixes the following `esbuild` error:
```
error: Transforming default arguments to the configured target environment ("es5") is not supported yet
```
This would occur due to this part of the transform:
```diff
function validate(
data,
-   {
-     instancePath = '',
-     foo: 'bar',
-   }
+   instancePath = ''
) {}
```
When replacing the `ObjectPattern` with `instancePath = ''`, we were previously inserting the `ObjectProperty` rather than its child `AssignmentPattern`.
This would create a tree that _looked_ right when generated, but which Babel did not how to transpile into ES5. Tests aren't updated with this change because the string output is exactly the same.
=> 🏗🐛 Fix compiling JSON Schema in ES5

extensions/amp-story-page-attachment/amp-story-page-attachment.md, extensions/amp-story-page-attachment/amp-story-page-outlink.md
Adds missing metadata to outlink and attachment docs.
This example was taken from [amp-story-360 docs](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-360/0.1/amp-story-360.md?plain=1#L22) and may fix the docs [linking problem](https://amp.dev/documentation/components/amp-story-page-attachment/?format=stories).
=> 📖🐛 [amp story page attachment][amp story page outlink] add path metadata docs

extensions/amp-analytics/0.1/test/vendor-requests.json, extensions/amp-analytics/0.1/vendors/lotame.json, src/service/real-time-config/callout-vendors.js
This adds the TCF consent string and boolean for whether GDPR applies to Lotame amp-ad and amp-analytics requests.
=> ✨ Lotame - adding TCF consent to amp-analytics and amp-ad requests

build-system/common/fs.js, build-system/compile/bento-remap.js, build-system/compile/bundles.config.bento.json, build-system/tasks/build-bento.js, build-system/tasks/extension-helpers.js
Generic:
- Pass `npm` through from `bundles.config.bento.json`
- Remove self from dependency remapping.
Special:
- NPM builds should remap its dependency to `mustache` instead of `@bentoproject/mustache`.
=> 🏗 Allow `bento-mustache` build

extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story.js
We want to lock the versioning of the json with the runtime version
=> add rtv path when fetching story languages json

extensions/amp-story/1.0/media-pool.js
All these references are arrow functions, so they don't need a bound `this`.
=> ♻️ Remove unnecessary `.bind/.call(this)`

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/story-ad-page.js, extensions/amp-story-auto-ads/0.1/test/test-amp-story-auto-ads.js, extensions/amp-story-auto-ads/0.1/test/test-story-ad-page.js, extensions/amp-story-education/0.1/amp-story-education.js, extensions/amp-story-page-attachment/0.1/amp-story-draggable-drawer.js, extensions/amp-story-page-attachment/0.1/amp-story-page-attachment.js, extensions/amp-story-page-attachment/0.1/test/test-amp-story-page-attachment.js, extensions/amp-story-share-menu/0.1/amp-story-share-menu.js, extensions/amp-story/1.0/amp-story-embedded-component.js, extensions/amp-story/1.0/amp-story-hint.js, extensions/amp-story/1.0/amp-story-page.js, extensions/amp-story/1.0/amp-story-store-service.js, extensions/amp-story/1.0/amp-story-system-layer.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/media-pool.js, extensions/amp-story/1.0/page-advancement.js, extensions/amp-story/1.0/pagination-buttons.js, extensions/amp-story/1.0/progress-bar.js, extensions/amp-story/1.0/test/test-amp-story-grid-layer.js, extensions/amp-story/1.0/test/test-amp-story-page.js, extensions/amp-story/1.0/test/test-amp-story.js, extensions/amp-story/1.0/test/test-media-pool.js
Updates some `enums` in `amp-story` so that their values are inlined, removing their keys. This reduces compressed size by ~0.20kb.
=> ♻️ Refactor unoptimizable uses of `@enum` in `amp-story`

build-system/server/app-utils.js, build-system/server/app.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story.js, src/service/extension-script.js, test/unit/test-extension-script.js
- Move the json url calculation logic to extension-script.js
- Handle amp-story json rtv path requests on the local server
=> move json file url calculation to extension-script.js

extensions/amp-ad-network-smartadserver-impl/0.1/amp-ad-network-smartadserver-impl.js, extensions/amp-ad-network-smartadserver-impl/0.1/test/test-amp-ad-network-smartadserver-impl.js
The change blocks XHR calls that duplicate iframe source requests. Currently, the extension sends two similar calls but the XHR one is useless.
=> 🐛[amp-ad smartadserver] Removes duplicate calls

extensions/amp-story-auto-ads/0.1/test/test-algorithm-count-pages.js, extensions/amp-story-auto-ads/0.1/test/test-algorithm-predetermined.js, extensions/amp-story-interactive/0.1/amp-story-interactive-abstract.js, extensions/amp-story-page-attachment/0.1/amp-story-page-attachment.js, extensions/amp-story/1.0/amp-story-consent.js, extensions/amp-story/1.0/amp-story-embedded-component.js, extensions/amp-story/1.0/amp-story-info-dialog.js, extensions/amp-story/1.0/amp-story-system-layer.js, extensions/amp-story/1.0/request-utils.js, extensions/amp-story/1.0/utils.js
Since the service is provided by the runtime, using it prevents us from including duplicate util implementations in the `amp-story` bundle. 
This reduces the size of `amp-story-1.0` by `0.41kB` in ESM and `0.82kB` (!!!) in nomodule.
=> ♻️🚀 `amp-story`: Use `Services.urlForDoc` instead of util functions

.github/workflows/cross-platform-builds.yml, .github/workflows/cut-nightly.yml, .github/workflows/publish-npm-packages.yml, .github/workflows/release-tagger.yml, .github/workflows/status-page.yml, .github/workflows/sweep-experiments.yml, .github/workflows/update-session-issues.yml
GitHub asks users to define workflow permissions, see https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ and https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token for securing GitHub workflows against supply-chain attacks.
The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) also treats not setting token permissions as a high-risk issue. 
This PR adds minimum token permissions for the GITHUB_TOKEN using https://github.com/step-security/secure-workflows. 
This project is part of the top 100 critical projects as per OpenSSF (https://github.com/ossf/wg-securing-critical-projects), so fixing the token permissions to improve security.
=> 🏗ci: Add GitHub token permissions for workflows

.circleci/get_pinned_chrome_version.sh
Looks like we're stumbling on `429 Resource Exhausted` HTTP errors on occasion; this PR should mitigate that for now
e.g. before this PR (broken): https://app.circleci.com/pipelines/github/ampproject/amphtml/24690/workflows/ac9e9719-1277-4650-a6a7-ccdbde7729ec/jobs/506132?invite=true#step-113-10
with this PR (fixed): https://app.circleci.com/pipelines/github/ampproject/amphtml/24696/workflows/356fd8f7-8bc4-4a29-9678-6ba8f7a34020/jobs/506258/parallel-runs/1?filterBy=ALL&invite=true#step-113-10
=> 🏗 Attempt to fetch pinned chrome version up to 3 times per CI job

extensions/amp-story/1.0/progress-bar.js
Bug: when PAGE_IDS update, it does not force a `render_` which sets the proper overflow CSS. This PR would fix that.
This is exacerbated by https://github.com/ampproject/amphtml/pull/37940 because it forces updating of PAGE_IDS more often.
=> 🔥 Fix progress bar overflow mode bug

build-system/babel-config/minified-config.js, build-system/babel-config/unminified-config.js, build-system/tasks/helpers.js
`for...of` has been [available](https://caniuse.com/mdn-javascript_statements_for_of) in all our supported browsers since 2015. By disabling the babel plugin, we're able to remove a runtime helper from the bundle.
=> 🏗🚀 Disable `@babel/plugin-transform-for-of`

build-system/babel-plugins/babel-plugin-transform-json-import/index.js, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-complex/output.mjs, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-currency-code/output.mjs, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-format-date/output.mjs, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-format/output.mjs, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-name-collision/input.js, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-name-collision/name-collision.schema.json, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-name-collision/output.mjs, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-object-enum/input.js, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-object-enum/object-enum.schema.json, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-object-enum/options.json, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-object-enum/output.mjs, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-one-of/output.mjs, build-system/babel-plugins/babel-plugin-transform-json-import/test/fixtures/transform-assertions/schema-refs/output.mjs, build-system/compile/json-schema/index.js
ajv's output may sometimes reference a part of the schema object, in which case the entire schema is included in the bundl.
This change follows the references made to each schema object, in order to only preserve the portions required. This is a big culprit of compiled size, since the schema varies in length and may include a lot of unnecessary information.
=> 🏗 Tree-shake included JSON Schema in compiled output

.github/workflows/cross-platform-builds.yml, .github/workflows/cut-nightly.yml, build-system/release-workflows/cut-nightly.js
- don't fail fast in cross plat compile jobs
- increase check runs fetch from 30 (default) to 100
- explicitly say which check runs we care about
- add manual trigger to cut_nightly job
=> Skip windows build check when cutting nightly

build-system/release-workflows/cut-nightly.js
=> 🏗 Unskip Windows builds in cut-nightly.yml

build-system/compile/bento-remap.js
There's currently a bug that produces bundles with malformed imports - they import npm modules with a `./` prefix (ie. `import {..} from "./@bentoproject/core"`)
this fixes that
=> 🐛 stop formatting npm imports as local modules

extensions/amp-story-shopping/amp-story-shopping.md
Addresses some of the concerns that documentation pointing to the schema is not hosted publicly as brought up [here](https://github.com/GoogleForCreators/web-stories-wp/issues/11210)
=> 📖 amp-story-shopping Added product json schema documentation

extensions/amp-form/amp-form.md
`<template>` is not allowed there in the email format. #37698 didn't
update this doc properly, hence this follow-up fix.
/to @samouri
=> 📖 Remove template under <div submitting> for email

extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js, extensions/amp-story-shopping/amp-story-shopping.md, extensions/amp-story/1.0/_locales/en-GB.json, extensions/amp-story/1.0/_locales/en.json
Change casing pattern to match other CTA text such as "Swipe up" for attachments.
Fixes #38082
=> 🌐 amp story shopping "Shop now" CTA casing

extensions/amp-story-shopping/amp-story-shopping.md
Make CTA casing in docs consistent with the code.
"Shop Now" => "Shop now"
"Buy Now" => "Buy now"
Removes "draft" from docs metadata.
Follow up from #38096
=> 📖 [amp story shopping] CTA casing in docs. Remove "draft" from doc metadata.

extensions/amp-story-360/0.1/amp-story-360.js
This PR removes the context handling code from the 360 component. 
Removing this code is not a final solution but will allow 360 to work in most use cases until the root of the bug is resolved.
Additional context: 
GL context handling was implemented to lose and restore web gl context based on distance from the active page. Browsers limit contexts to 8-16. Web Stories that feature 360 such as [this one](https://www.google.com/search/static/gs/museum/m0d3c49.html) use less than the maximum. 
This context handling broke within the past several months. Context is not restored and a blank screen is displayed. In some cases context is created but then lost right after.
The [codepen example](https://codepen.io/philipbell/pen/RwRQGmo) still works which leads me to believe it's a race condition …
=> 🚮 🐛 [amp story 360] Remove GL context handling

extensions/amp-story-shopping/0.1/amp-story-shopping.md
Fixes images that had incorrect sizes.
Closes image tags.
Makes header casing consistent.
=> 📖 🐛 [amp story shopping] Fix images in docs

extensions/amp-analytics/0.1/test/test-variables.js, extensions/amp-analytics/0.1/variables.js, src/core/types/string/index.js, test/unit/core/types/string/test-string.js
If the input string contains many `${` which do not have a closing `}`, the `expandTemplate`'s replace will iterate the entire string at every beginning mark.
Fixes #36108.
=> 🐛 Prevent expandTemplate from ReDOSing

examples/amp-story/shopping/product.schema.json
Closes #38174
Note: We are using minItems and NOT minContains as 
as ajv uses an earlier draft for performance reasons, see
https://ajv.js.org/json-schema.html#draft-07
=> 🐛 added minItems to amp-story-shopping productImages JSON Schema

extensions/amp-script/0.1/amp-script.js, extensions/amp-script/amp-script.md
Fixes: #38173
Creates a separate size limit for scripts running in `sandboxed` mode. Includes updating the `sizeLimitExceeded` function to correctly accumulate and calculate size limit based on whether the script being checked is running in `sandboxed` mode or not.
Also updates the documentation to reflect this change.
=> ✨ amp-script: implement new size limits for sandboxed scripts

build-system/release-workflows/cut-nightly.js
* Immediately bail if the newly selected SHA from `main` is already the tip of the `nightly` branch, without failing the job
* Better error handling
* Better logs
=> 🏗 Fixes for cut-nightly.js job

src/amp-story-player/amp-story-player-impl.js
Disables player swipeX events when the page attachment is open.
This allows swipeable media within the attachment like carousels.
Fixes #38193
=> 🐛 [amp story player] Prevent vertical swipe when page-attachment is open

ads/google/ima/ima-video.js, extensions/amp-ima-video/0.1/amp-ima-video.js, extensions/amp-ima-video/0.1/test/test-amp-ima-video.js, extensions/amp-ima-video/0.1/test/test-ima-video-internal.js
Implemented according to: https://support.google.com/admanager/answer/9805023?hl=en
=> ✨ Pass `gdpr_consent` and `addtl_consent` to IMA URL

.circleci/config.yml, .circleci/install_validator_dependencies.sh, package-lock.json
Super temp workaround to avoid running `npm ci` on circleci that fails...
Also pin protobuf to v3.19.4 until `amp validator` can be fixed with new version
```
validator-tests.js Running amp validator...
[17:10:01] Using task file project/amp.js
[17:10:01] Starting 'validator'...
Traceback (most recent call last):
File "build.py", line 620, in <module>
Main(parser.parse_args())
File "build.py", line 597, in Main
GenValidatorProtoGeneratedJs(out_dir='dist')
File "build.py", line 195, in GenValidatorProtoGeneratedJs
from dist import validator_pb2
File "/home/circleci/project/validator/dist/validator_pb2.py", line 33, in <module>
_descriptor.EnumValueDescriptor(
File "/home/circleci/.local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 755, in __new__ …
```
=> Install npm packages with `--legacy-peer-deps` on ci

examples/visual-tests/amp-story/amp-story-shopping-landscape.html, examples/visual-tests/amp-story/amp-story-shopping-lang-de.html, examples/visual-tests/amp-story/amp-story-shopping-rtl.html, examples/visual-tests/amp-story/amp-story-shopping.html
Removes animations on `amp-story-shopping` visual diff tests to prevent flakes such as [this one](https://percy.io/ampproject/amphtml/builds/18680083/changed/1047950639?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=320&widths=320).
This should be able to target elements in shadow dom since Percy runs in [test mode](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/utils.js#L91-L93).
Percy may be disabling CSS animations by going to the last keyframe by default. This element has two animations so it may not be targeting [both animations](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-shopping/0.1/amp-story-shopping-tag.css#L171-L173).
=> ❄️ 🐛 [amp-story-shopping] Remove animations on visual tests

.circleci/config.yml, package-lock.json, package.json
`react-dates` is used by `amp-date-picker-0.1` but does not support `react>=17`, which is what the rest of amphtml uses. This means that `npm install` fails.
Turns out we install `react-dates` in `third_party/` so that means we can probably remove `react-dates` from `package.json`
=> Remove react-dates from package.json

extensions/amp-story-subscriptions/0.1/amp-story-subscriptions.css, extensions/amp-story/1.0/amp-story-desktop-one-panel.css, extensions/amp-story/1.0/amp-story.js, src/amp-story-player/amp-story-player-impl.js
- Part of #37129
---
This PR increases the aspect ratio threshold beyond which the desktop UI is displayed, from 3/4 to 31/40. Story previews are shown on the mobile SERP in a viewer with a 3/4 aspect ratio, so a 31/40 min-aspect-ratio here ensures that the mobile UI is displayed instead of the desktop UI.
=> 🖍 [Story Preview] Prevent story previews from displaying with the desktop UI in the mobile SERP

extensions/amp-story-shopping/0.1/test/test-amp-story-shopping-attachment.js, extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story.js
Remove all localization strings to rely on the JS.
This removes the experiment flag because opting-out of this experiment cannot be done (the localizations strings are removed completely from the bundle).
=> 🚀 [Story localization] Removed localization strings from js

build-system/tasks/visual-diff/index.js, build-system/tasks/visual-diff/package-lock.json, build-system/tasks/visual-diff/package.json
Note that the `@percy/core` package changed from cjs to mjs, so we have to `import()` instead of `require()` it, which results in a `Promise<Module>`. Those are the changes in `index.js`
=> 🏗 Update deps for visual-diff task

src/service/real-time-config/callout-vendors.js
Get attributes width and height for vendor mediasquare, in addition to `data-multi-size` for compatibility with publishers not using  `data-multi-size`
=> 🐛 Callout vendor update mediasquare - check width and height

src/service/standard-actions-impl.js, test/unit/test-standard-actions.js
@zhangsu reported that `toggleChecked()` fails when `force` is null.
@jridgewell fixed it in https://github.com/ampproject/amphtml/issues/38312#issuecomment-1168095157
=> 🐛 Fix #38312 toggleChecked

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json, extensions/amp-story/1.0/amp-story.js, tools/experiments/experiments-config.js
This will be pushed only when all the final approvals from all stakeholders are granted.
=> ✨ Add amp-story-subscriptions experiment and turn it to 100%

extensions/amp-story-auto-ads/0.1/test/validator-amp-story-auto-ads-remote.html, extensions/amp-story-auto-ads/0.1/test/validator-amp-story-auto-ads-remote.out, extensions/amp-story-auto-ads/validator-amp-story-auto-ads.protoascii
Allow optional `src` attr on `<amp-story-auto-ads>` to specify remote config https://amp.dev/documentation/components/amp-story-auto-ads/?format=stories#remote-ad-config
This functionality was added very long ago, but the validator was never updated. This should be an optional `src` attribute that points to a publishers JSON endpoint.
=> 🐛 [story-ads] Allow optional `src` attr

extensions/amp-consent/0.1/consent-config.js, extensions/amp-consent/0.1/test/test-consent-config.js
Allows passing the `CANONICAL_URL` variable into the `amp-consent` component, as proposed by @alanorozco in #38183.
Changing the parameters passed to the test suite changed the indentation of the whole file, unfortunately. I just touched the test `support expansion in allowed list`.
=> ✨ Add CANONICAL_URL to allowed list of consent iframe replacement variables

src/service/extension-script.js, test/unit/test-extension-script.js
This caused a bug with the `ssr-css` experiment where extensions that were dependent on amp-story to load first and initialize its services, to break on some occasions. This is because `waitWhenReady` for extensions breaks as it uses `parseExtensionUrl` to detect if an extension even exists on the page to wait on.
This was detected on manual testing prior to turning on the experiment so this issue does not exist on production. I might need to ask for a cherry pick for this
=> allow ssr-css query param for parseExtensionUrl

src/service/history-impl.js
Fixes #38386.
This catches errors thrown when using the History API in a context where it is not supported (e.g. when in a document rendered inside `iframe[srcdoc]`.
The following screencrabs are taken from https://wave-cookie-error.glitch.me/container-iframe-srcdoc.html
Tapping to the next page fails:
https://user-images.githubusercontent.com/134745/183138274-2d144fcc-0e1c-4d84-b474-ead4f7b68060.mov
Tapping to the next page succeeds, and reloads even restore the current page.
Changes applied via the Local AMP extension with changes in this PR. (Note some of the console errors reflect issues with the local server.)
https://user-images.githubusercontent.com/134745/183138327-7ec7b309-2d58-411c-9655-1c79b809f728.mov
=> 🐛 [History] Wrap `pushState`/`replaceState` calls in `try`/`catch` blocks

test/visual-diff/visual-tests.jsonc
This may be due to an ordering race condition with this selector.
https://github.com/processprocess/amphtml/blob/main/examples/visual-tests/amp-story/amp-story-shopping.js#L92
As a follow up, an explicit selector may fix this. 
https://percy.io/ampproject/amphtml/builds/20456391/changed/1146414036?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=320&widths=320%2C400
=> [amp-story-shopping] Mark flaky test in shopping rtl visual test

.circleci/get_pinned_chrome_version.sh
Fixes bug where `CHROME_MAJOR_VERSION=95` was returning `105.0.5195.102` where it should return `95.0.4638.69`
=> Fix grep pattern when getting major chrome version for CI

third_party/subscriptions-project/config.js, third_party/subscriptions-project/swg-gaa.js, third_party/subscriptions-project/swg.js
- Add experiment which disables miniprompt button for wide desktop screen. (#2382)
- Opt in failure translations (#2387)
- Update dependency selenium-webdriver to v4.4.0 (#2390)
- Update dependency rollup to v2.79.0 (#2389)
- Update dependency postcss to v8.4.16 (#2388)
- Update dependency gulp-load-plugins to v2.0.8 (#2386)
- Update dependency cssnano to v5.1.13 (#2385)
- Update dependency @babel/core to v7.18.13 (#2384)
- Add ppid as a query param for swg-basic and swg-classic (#2381)
- add clientOption for allowScroll (#2378)
- Logging 3P button click with new analytics event (#2380)
=> SwG Release 0.1.22.232

extensions/amp-story-page-attachment/0.1/amp-story-draggable-drawer.js, extensions/amp-story/1.0/amp-story-system-layer.js, extensions/amp-story/1.0/utils.js, test/visual-diff/visual-tests.jsonc
This allows for a screen reader experience that matches the intended UX by not allowing the content behind the draggable drawer to be readable.
Fixes #38433
Screen capture with TalkBack:
https://user-images.githubusercontent.com/3860311/188980971-1d8df100-3874-4eea-b9da-8e3d211ecafc.mp4
A note that `aria-modal=true` should hide content underneath the dialog however in [this example](https://codepen.io/philipbell/live/jOxbjOV) The "Add Delivery Address" button is still selectable when the modal is open.
https://www.w3.org/WAI/ARIA/apg/example-index/dialog-modal/dialog
Other examples [work with tabbing](https://codepen.io/anqa/full/EEdOQY) but not with screen readers.
For this reason I used `aria-hidden` and `tab-index`.
=> ♿ 🐛 [Story a11y] When drawer is open hide content outside of drawer

.github/stale.yml
#27253 introduced the stale bot with plans to reduce to 1y if things go well.
This PR reduces the timespan to 1y; I think we could potentially reduce it further depending on usage.
=> Change stale bot duration to 1 year

extensions/amp-subscriptions-google/0.1/amp-subscriptions-google.js, extensions/amp-subscriptions-google/0.1/test/test-amp-subscriptions-google.js
Checks the `location.hash` or the gaa params before falling back to `location.search`
=>  🐛 check swg hash fragment for gaa params

extensions/amp-vimeo/validator-amp-vimeo.protoascii
Fixes #38494 &  Fixes #37865
🐛 Bug fix
the `do-not-track` attribute is  [supported on the tag](https://amp.dev/documentation/components/amp-vimeo/) , but validators fail because this isn't added.
This pr adds the attribute.
=> 🐛 Updates to add the missing do-not-track attribute to <amp-vimeo> validator-amp-vimeo.protoascii

extensions/amp-a4a/0.1/amp-a4a.js
A fix for https://github.com/ampproject/amphtml/issues/38499
There is a race condition when two layoutCallback are triggered simultaneously, two calls to render ads are executed together, thereby creating two iframes. This fix will remove the older iframe when creating a new one therefore fixing the race.
=> Bugfix: Remove the ad iframe before creating a new one

src/core/dom/static-template.js
This change updates AMP's `createNode` function to be [Trusted Types](https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API) compatible, partial fix to #37297. This was the most widely used [TT sink](https://www.w3.org/TR/2022/WD-trusted-types-20220927/#injection-sinks) in AMP. Since the value assigned to `innerHTML` was already using template tags and assigning the constant value, we've added an inline policy to make the values `TrustedHTML`s instead of plain strings. This will let the browser know the assignment is safe, so when Trusted Types is enforced, this call will not cause a violation and therefore won't be blocked. The Trusted Types policy creation and `TrustedHTML` generation happens in an anonymous function to minimize the risk of the Trusted Types policy leaking …
=> ♻️🐛 [Trusted Types] Make createNode Trusted Types compatible

examples/amp-ad-exit-conversion.html, extensions/amp-ad-exit/0.1/amp-ad-exit.js, extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js
We moved this macro from `finalUrl` to the `browserAdConfig.attributionsrc` in the most recent update but we were not running the variable substitution pattern on that value. 
Partial https://github.com/ampproject/amphtml/issues/35347
=> Resolve `ATTRIBUTION_REPORTING_STATUS` in `attributionsrc`

build-system/release-workflows/upload-release.js, package-lock.json, package.json
For now we upload to both GCS and R2. Once we have enough data in R2 I can start switching cdn-worker to use it as a backend instead of GCS, and we can sunset GCS then
=> 🏗 Upload built releases to Cloudflare R2

extensions/amp-story/1.0/media-pool.js
Fixes https://github.com/ampproject/amphtml/issues/38531
Given two story pages with videos on each one, when amp-story transitions from page 1 to page 2 we start playing the video on page 2 as early as possible on the next animation frame (let's call this rAF1), and then amp-story rewinds the video on page 1 after rAF1 has executed in another rAF (lets call this rAF2). When the `seeking` event is triggered during the current tick of the event loop in rAF2 which is the [step 2 of the switchTo_ operation](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/amp-story.js#L1460-L1503) this glitch can occur. A quick fix is to push the `seeking` event to the next tick of the event loop.
Another fix for this might possibly be moving `oldPage.setState(PageState.NOT_ACTIVE);` …
=> Add a 10ms delay when rewinding a media pool video

extensions/amp-story/1.0/media-pool.js
Some devices, specifically iphone 12 and up are still having the video glitching issue with the 10ms delay. Bumping it up to 100ms seems to fix the issue.
=> increase the rewind delay to 100ms

extensions/amp-story-auto-ads/0.1/amp-story-auto-ads.css, extensions/amp-story/1.0/amp-story.css
Need to make `amp-ad` clickable after https://github.com/ampproject/amphtml/pull/38377 by adding `pointer-events: auto`. Also, glass-pane on top of the ad should be clickable so that it catches unwanted clicks on the top of the page.
Closes https://github.com/ampproject/amphtml/issues/38552
=> 🐛 Fix xdomain ad not clickable

.circleci/config.yml
To fix validator tests that are using a bad cache. Also upgrade node orb to latest.
=> Disable node pkg caching on circleci

extensions/amp-story-page-attachment/0.1/amp-story-open-page-attachment.css
Need to increase the line-height for IOS devices.  20px seems to be enough (tested in iOS simulator)
=> theres clipping specifically on iOS devices so we need to increase the line height

build-system/pr-check/validator-tests.js
`amp validator-cpp` started failing on 12/20. The previous build on 12/8 succeeded. My guess is that our tests aren't compatible with the latest bazel version that was released on 12/19 https://github.com/bazelbuild/bazel/releases/tag/6.0.0
Skipping tests for now to fix failing builds on main.
=> Skip validator-cpp tests for now

extensions/amp-geo/0.1/test/test-amp-geo.js, extensions/amp-geo/amp-geo.md
We're adding US Virginia (`us-va`) detection support. This should work out of the box once backend changes are completed.
=> Add documentation for us-va support

build-system/test-configs/dep-check-config.js, extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/privacy-sandbox-utils.js, extensions/amp-a4a/0.1/secure-frame.js, extensions/amp-a4a/0.1/test/test-amp-a4a.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, src/experiments/attribution-reporting.js, tools/experiments/experiments-config.js
Allows us to send requests opting into new api in ad response.
partial #35347
=> 🧪 Introduce structure for `attribution-reporting` client side experiment

extensions/amp-story/1.0/semantic-render.js
This is a partial fix to #37297.
This change refactors the loose HTML parsing by assigning to a div that's never attached to the DOM, by replacing the use of `<div>` with a `<template>` node. This reduces XSS risk, as an `innerHTML` assignment on a `<div>` that's never attached can still lead to code execution (eg. `<img src=x onerror=alert()>`). This change also adds an inline policy to create a `TrustedHTML`  when assigning to `innerHTML` to avoid the Trusted Types violation.
=> ♻️ Make innerHTML assignment in semantic-render Trusted Types compatible

validator/testdata/amp4ads_feature_tests/anchor_attribution_reporting.html, validator/testdata/amp4ads_feature_tests/anchor_attribution_reporting.out, validator/validator-main.protoascii
Partial https://github.com/ampproject/amphtml/issues/35347
See https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#api-overview for more details around the chrome API.
=> Allow `attributionsrc` on `<a />`

extensions/amp-a4a/rtc-publisher-implementation-guide.md
CircleCI is currently failing rtc-related changes because of highfivve.com failing the link check. Since we have no way of enforcing external links and, in case it happens, we cannot easily find the owner organization. I propose we disable these checks.
=> ❄️ Remove rtc publisher link from link checker

build-system/task-runner/install-amp-task-runner.js
npm version 9 dropped support for `npm bin`. The only place this command is used is in `install-amp-task-runner` to install the `amp` binary in the global node modules bin/ directory. Switch to `npm prefix` which is still supported and modify the target path to specify `bin` manually.
Fixes #38662
=> 🐛 build: npm@9 compatibility fix for amp task runner

src/experiments/attribution-reporting.js
Original ids could not be shared between server side exp and client side, so we needed new ids.
Part of https://github.com/ampproject/amphtml/issues/35347
=> 🧪 Update ids in `attribution-reporting` experiment

extensions/amp-a4a/rtc-documentation.md, extensions/amp-a4a/rtc-publisher-implementation-guide.md, extensions/amp-ad-network-smartadserver-impl/0.1/test/test-amp-ad-network-smartadserver-impl.js, src/service/real-time-config/callout-vendors.js
Hi. I'm from Xandr/AppNexus.
The `prebidappnexus` RTC vendor is deprecated in favor of `prebidappnexuspsp`. Cleaning up our integration now that that publishers have migrated to our new vendor code.
=> 🚮 Remove prebidappnexus RTC Vendor

extensions/amp-ad-exit/0.1/amp-ad-exit.js, src/pixel.js
#38619 used the shared `isAttributionReportingAllowed` helper but passes `win` in a couple places that should be `document`.  `win.featurePolicy?.allowedFeatures().includes('attribution-reporting');` will always return `undefined`.
=> Fix `attribution-reporting` browser support detection

.circleci/install_validator_dependencies.sh, build-system/pr-check/validator-tests.js
=> Resume validator tests by using bazel 5

build-system/release-tagger/utils.js
Handle undefined responses when fetching with octokit/rest api
=> Handle undefined responses with release tagger

extensions/amp-consent/0.1/cmps.js
Updated consentmanager domain to delivery.consentmanager.net. consensu.org domain will soon be deprecated by the IAB and all CMPs must switch to new domains.
---
This is a branch of the original PR https://github.com/ampproject/amphtml/pull/38371 to check if we need a rebase
=> Update cmps.js for new consentmanager domain

extensions/amp-consent/0.1/cmps.js
Change sddan.mgr.consensu.org to choices.consentframework.com as consensu.org hosts will be removed by IAB.
--
This is a fork of the original PR https://github.com/ampproject/amphtml/pull/36661 to check if it needs to be rebased
=> Update of CMP Sirdata configuration for <amp-consent>

src/validator-integration.js, test/unit/test-validator-integration.js
Adding an inline Trusted Types policy to validate the URL and generate a TrustedScriptURL object to avoid Trusted Types violations due to the `script.src` call. Also updated the test example to match the trusted URL pattern to simplify validation.
=> ♻️Make loadScript function in validator-integration Trusted Types compatible 

.circleci/config.yml, build-system/tasks/validator.js, validator/.bazelrc, validator/README.md, validator/cpp/engine/wasm/BUILD
* Test whether `validator_wasm.js` can be built successfully
* Use `2xlarge` container to run validator tests.
* Add a few blaze args to speed up building speed.
=> Add build test for wasm validator

.circleci/get_pinned_chrome_version.sh, build-system/tasks/e2e/package-lock.json, build-system/tasks/e2e/package.json
Google removed v95 from the download site, so we have to bump to the next available version. #38762 attempts to bump this to the latest version (currently v112) but that breaks a lot of tests. For now let's merge this PR and then work on fixing the broken tests so we can merge #38762 later
=> 🏗 Bump chromedriver to 96 (smallest increment) and remove workaround from get_pinned_chrome_version.sh

.github/workflows/codeql.yml
Currently these files generate a lot of false-positives, e.g.: https://github.com/ampproject/amphtml/security/code-scanning/148
=> 🏗 Ignore extension test files in CodeQL

build-system/tasks/visual-diff/browser.js, build-system/tasks/visual-diff/dev-mode.js, build-system/tasks/visual-diff/package-lock.json, build-system/tasks/visual-diff/package.json
This PR:
* Updates `puppeteer` to v19~
* Updates the Percy-compatible version of Chrome (unlike before, this is now a single version for all platforms)
* Updates the instructions on how to perform this update, since a few things changed
* Updates `inquirer` to v9~
* Minor code changes now that `inquirer` is an ES module
=> 🏗 Update Puppeteer and other deps for visual diffs and fix code to reflect

extensions/amp-consent/0.1/consent-ui.js, extensions/amp-consent/0.1/test/test-consent-ui.js, extensions/amp-consent/integrating-consent.md
In #38183 @alanorozco and I discussed options how to allow amp-consent's consent-ui iframe to trigger navigation events in the top window. This pull request allows specifying additional sandbox attributes similar to how users can specify them for `amp-iframe` (see [amp-iframe v0.1](https://github.com/ampproject/amphtml/blob/main/extensions/amp-iframe/1.0/README.md#sandbox-optional-) and [amp-iframe v1.0](https://github.com/ampproject/amphtml/blob/main/extensions/amp-iframe/0.1/amp-iframe.md#sandbox-)).
Context: it is possible to load the consent ui in `amp-consent` from an external URL. The URL provided via `promptUISrc` is loaded inside an iFrame. The code inside that iFrame can communicate with the parent page via `postMessage` calls to e.g. signal ready or fullscreen events. The iFrame …
=> ✨ Allow custom iframe sandbox attributes in amp-consent

extensions/amp-ad-exit/0.1/amp-ad-exit.js, extensions/amp-ad-exit/0.1/test/test-amp-ad-exit.js
We have seen a few previous issues that when the attribution reporting feature policy is not enabled on the client side when we attempt to fire background ping via `attributionsrc` url, the click ping is eventually lost.
Our new behavior should not depend solely on the existence of the attributionsrc url. We should send trackingUrls for all traffic and either send the tracking ping to attributionsrc or trackingUrls depending on whether the feature policy is enabled on the browser.
Successor of https://github.com/ampproject/amphtml/issues/35347
=> Gate attributionsrc and trackingUrls on attribution reporting enabled ✨

build-system/tasks/e2e/package-lock.json, build-system/tasks/e2e/package.json, extensions/amp-base-carousel/1.0/test-e2e/test-bento-base-carousel.js, extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js, extensions/amp-date-display/0.1/test/test-amp-date-display.js, extensions/amp-date-display/1.0/test/test-amp-date-display.js, extensions/amp-date-display/1.0/test/test-component.js, extensions/amp-powr-player/0.1/test/test-amp-powr-player.js, test/unit/test-iframe-stub.js, testing/iframe.js
#38762 (bump chromedriver to 112) is failing on multiple tests. Using this PR to bisect the highest version we can bump to with the least amount of other modifications
I was able to bump up to 102:
* Chrome 97 - breaks test/unit/test-iframe-stub.js, _trivial fix_
* Chrome 98 - breaks multiple amp-date-display tests, _trivial fix_ (pending localization review)
* Chrome 99-100 - no new test breakages
* Chrome 101 - breaks all `amp-powr-player` tests. It looks like all these tests rely on a real network endpoint that no longer exists, so I _disabled_ them
* Chrome 102:
* breaks test `should execute next and prev actions` in extensions/amp-base-carousel/1.0/test/test-amp-base-carousel.js, _disabled_
* breaks all tests in extensions/amp-base-carousel/1.0/test-e2e/test-bento-base-carousel.js, …
=> 🏗 Bump chromedriver to 102

build-system/tasks/visual-diff/browser.js, build-system/tasks/visual-diff/dev-mode.js, build-system/tasks/visual-diff/index.js, build-system/tasks/visual-diff/log.js, build-system/tasks/visual-diff/package-lock.json, build-system/tasks/visual-diff/package.json, build-system/tasks/visual-diff/types.js, build-system/tasks/visual-diff/verifiers.js
* [Replace `puppeteer` with `puppeteer-core`](https://www.educative.io/answers/puppeteer-vs-puppeteer-core)
* Use `@puppeteer/browsers` to download and cache browsers instead of the now-removed `createBrowserFetcher`
* Remove use of `puppeteer-extra` which makes things complicated for a minor dev-ex gain
* Remove most type-import hacks
=> 🏗 Update visual-diff dependencies and code

build-system/server/app.js, build-system/server/routes/a4a-envelopes.js, build-system/status-page/comment.js, build-system/status-page/incident.js, build-system/tasks/bundle-size/index.js, build-system/tasks/check-owners.js, build-system/tasks/e2e/describes-e2e.js, build-system/tasks/performance/helpers.js, build-system/tasks/release/index.js, build-system/tasks/sweep-experiments/cleanup-branches.js, build-system/tasks/test-report-upload.js, package-lock.json, package.json
`fetch` is built in to Node since v18, which we now require as a minimum.
`node-fetch` is currently preventing submitting #38981
Tag-along
* A few minor fixes to differences in API
* Added @types/tar as a devDep because I needed it to debug stuff while I was fixing some API differences :D
=> 🏗 Remove `node-fetch` as a dependency

build-system/common/ctrlcHandler.js, package-lock.json, package.json
Our current `@types/node` is long outdated
Tag-along:
* Fix `createCtrlcHandler` to work with minor changes in types
=> 🏗 Bump `@types/node` to v18

extensions/amp-geo/0.1/test/test-amp-geo.js, extensions/amp-geo/amp-geo.md
add documentation that we support Colorado and Connecticut geo detection for amp-geo
=> add us-co (Colorado) and us-ct (Connecticut) docs and test for geo detection support

build-system/task-runner/amp-task-runner.js
Hopefully this will get around the problem where occasionally a job hangs on CircleCI after it finishes
=> 🏗 Add `process.exit(0)` to task runner when tasks finish

extensions/amp-analytics/0.1/vendors/gtag.json
✨  Add support for sending session timestamp, session count and the current timestamp to gtag config rewriter to enable session tracking support.
=> Add support for additional variables to gtag vendor

build-system/task-runner/amp-task-runner.js
In lieu of #39071 (which was reverted in #39090)
=> 🏗 Temporary fix for e2e tests getting stuck on CircleCI

.circleci/config.yml
Saving/restoring git cache on MacOS takes much longer (~3 minutes) than just checking out the repo!
=> 🏗🚀 Disable Git cache on CircleCI when using Mac OS

.circleci/config.yml, build-system/tasks/e2e/package-lock.json, build-system/tasks/e2e/package.json, extensions/amp-audio/1.0/component.js, extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js, extensions/amp-base-carousel/0.1/test/test-child-layout-manager.js, extensions/amp-date-display/1.0/test/test-component.js, extensions/amp-next-page/0.1/test/test-amp-next-page.js, extensions/amp-pan-zoom/1.0/test/test-amp-pan-zoom.js, extensions/amp-story-interactive/0.1/test/test-amp-story-interactive-binary-poll.js, test/unit/inabox/test-inabox-resources.js, test/unit/preact/test-base-element-mapping.js
Needed to run `apt update` before installing Chrome due to some Docker images we use having an outdated packages list, which prevents installing `google-chrome-stable` deps
Tests skipped:
* `PreactBaseElement> shadow container rendering > SSR > *` in test/unit/preact/test-base-element-mapping.js
Tests fixed:
* `amp-autocomplete init > should error with invalid JSON script` in extensions/amp-autocomplete/0.1/test/test-amp-autocomplete-init.js (built-in error output changed, replaced assertion with a more lenient regex)
* Multiple tests in extensions/amp-base-carousel/0.1/test/test-child-layout-manager.js (effects are no longer immediate after requesting animation frame, added `await macroTask();` to fix)
* `DateDisplay 1.0 preact component > provides variables in Czech when "cs" locale is …
=> 🏗 Bump chromedriver to v113

build-system/task-runner/amp-task-runner.js
`process.exitCode` is set explicitly in build-system/tasks/e2e/index.js:171, so the workaround introduced in #39102 incorrectly always exits with `0` instead of the explicitly set value.
Tested this in 700a73a, forcing a test to fail (`expect(1).to.equal(0);`): https://app.circleci.com/pipelines/github/ampproject/amphtml/28032/workflows/631dd486-297d-45fa-bbe6-21d2a1e1ad89/jobs/593162/parallel-runs/2?filterBy=ALL
=> 🏗 Fix temporary workaround for e2e tests in CircleCI

build-system/pr-check/module-build.js, build-system/pr-check/nomodule-build.js
Not sure how we missed this edge case for so long.
I created #39123 which only marks a single e2e test as flaky. The resulting build targets for CI were `E2E_TEST` and `LINT`, which means the Visual Diff task was skipped. This skip is triggered in the [`Module Build (Test)`](https://github.com/ampproject/amphtml/blob/2d2e54cd316d1aebf961f32901126a7e0aba9421/build-system/pr-check/module-build.js#L30-L42) job. However, the `Nomodule Build (Test)` is responsible for creating an empty visual diff check on Percy/GitHub, and that one wasn't skipped due to the [`E2E_TEST`](https://github.com/ampproject/amphtml/blob/13a6dbe2e20b55c716bd843a4b5c3491e065282f/build-system/pr-check/nomodule-build.js#L40) target
This PR moves the responsibility for an empty build to the former build job
=> 🏗 Create an empty Visual Diff job from skipped "Module" builds, not "Nomodule"

.circleci/config.yml
Tag-along:
* Update xcode version to latest
* Add `git gc --auto` before caching (so the Git cache won't grow forever. `--auto` makes it run only sporadically)
=> 🏗 Initialize a Mac OS job early, to cache the Git repository before the Safari test job

package-lock.json, package.json
0.34 contains critical bugs that renders amp-script non operational
This reverts commit 1c0436f0dce63c927b7d6588914d639ee50a47cd.
=> Revert "📦 Update dependency @ampproject/worker-dom to v0.34.0 (#39050)"

build-system/server/new-server/transforms/tsconfig.json
New versions of esbuild ignore this field and fire off a warning ([example](https://app.circleci.com/pipelines/github/ampproject/amphtml/28191/workflows/e95db7e4-a51b-47f8-9490-c943d83c2036/jobs/597764?invite=true#step-114-37)). This PR removes the deprecation warning
=> 🏗 Remove the `target` field from the server's tsconfig.json

extensions/amp-analytics/0.1/vendors/metrika.json
The update adds custom client ID generation and ensures the ID is compatible with the one created by regular metrika script: https://github.com/yandex/metrica-tag/blob/main/src/utils/uid/uid.ts#L51
Otherwise the reports provided by the vendor might not be accurate.
=> 🐛 Add uid generation to metrika analytics template

build-system/server/new-server/transforms/tsconfig.json
Reverts ampproject/amphtml#39164
It causes failures 
```
build-system/server/new-server/transforms/utilities/lazy.ts:9:14 - error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
9   public get value(): T {
~~~~~
Found 1 error.
```
=> Revert "🏗 Remove the `target` field from the server's tsconfig.json"

build-system/tasks/remap-dependencies-plugin/remap-dependencies.js
And make it infinitesimally more efficient :D
This should fix security advisories:
* https://github.com/ampproject/amphtml/security/code-scanning/56
* https://github.com/ampproject/amphtml/security/code-scanning/57
* https://github.com/ampproject/amphtml/security/code-scanning/58
* https://github.com/ampproject/amphtml/security/code-scanning/59
=> 🐛 Fix incorrect regex in `remapDependenciesPlugin`

ads/vendors/adskeeper.js, ads/vendors/idealmedia.js, ads/vendors/lentainform.js, ads/vendors/mgid.js, extensions/amp-ad-network-mgid-impl/0.1/test/test-amp-ad-network-mgid-impl.js
Should fix security advisories:
* https://github.com/ampproject/amphtml/security/code-scanning/52
* https://github.com/ampproject/amphtml/security/code-scanning/53
* https://github.com/ampproject/amphtml/security/code-scanning/54
* https://github.com/ampproject/amphtml/security/code-scanning/55
=> 🐛 Fix overly permissive regex in ads vendors' code

.github/codeql/config.yml, .github/workflows/codeql.yml
=> 🏗️ Fix CodeQL config

src/service/real-time-config/real-time-config-impl.js, test/unit/test-real-time-config.js
Implements the changes proposed in #38627 by adding the TITLE and SOURCE_URL global macros to the allowlist for real-time-config
=> ✨ [RTC-Config]: add source_url and title to real-time-config global macros allowlist

build-system/test-configs/dep-check-config.js, examples/amp-story/player-cross-origin-copy-link.html, extensions/amp-story-share-menu/0.1/amp-story-share-menu.js, extensions/amp-story-share-menu/0.1/test/test-amp-story-share-menu.js, extensions/amp-story/1.0/amp-story-viewer-messaging-handler.js, src/amp-story-player/amp-story-player-impl.js, src/amp-story-player/event.js
Context:
Currently in `<amp-story-player>`, if the embedded Story has a different origin than the hosting page's origin, the clicking on `Get Link` button would fail to copy URL to the clipboard. This is because `Get Link` button tries to write the URL of embedded story to the hosting page's clipboard, which is one kind of cross-origin referencing and not allowed.
Solution:
Use viewer's messaging object, e.g. `AmpStoryViewerMessagingHandler`, to pass URL from the embedded Story to the hosting page and copy it there.
Reported bug: #38936
=> 🐛 Enable cross-origin copy url in <amp-story-player>

src/amp-story-player/amp-story-player-impl.js
Newest iframe API for triggering the native share menu: https://developer.chrome.com/blog/web-share-api-in-third-party-iframes/
#39181
=> 🐛  Fix native share by matching the newest iframe API

3p/facebook.js
SDK version was deprecated. This PR will fix https://github.com/ampproject/amphtml/issues/38368
=> 🐛 amp-facebook broken: fix sdk version

build-system/common/ci.js, build-system/tasks/test-report-upload.js
Removes an old TODO. Renames the function to circleciJobUrl to emphasize that it's only relevant in CircleCI
=> 🏗 Remove unused branch from `ciJobUrl` function

extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
Currently, because `0` is treated the same as `null` the latter will take precedence because of the ordering of logic.
For AdSense, switch to `??`, while DoubleClick uses a more explicit logic because there are multiple possible sources for tfcd/tfua values.
=> 🐛 amp-ad doubleclick & adsense: allow tfcd/tfua=0

build-system/global-configs/experiments-config.json
This experiment is +2 years out of date. It's not being tested on CI, but our build platform still builds it (even though we don't use it). Might as well remove it!
=> 🧪 Remove outdated `experimentB` from `experiments-config.json`

extensions/amp-date-picker/1.0/test/test-component.js
These tests are flaky (and probably can be removed given that we don't build Bento components anymore) and prevent renovatebot's PR #37042 from passing CI
=> ❄️ Disable flaky tests `BentoDatePicker preact`

extensions/amp-story/1.0/amp-story.js, extensions/amp-story/1.0/test/test-amp-story.js
There are 2 known cases where the race condition happen:
1. The visibility of the story becomes inactive before the active page is set(~20k / day):
2. By tapping, keying down, or clicking on the navigational button, the navigation happens before the active page is set(~40k / day): 
This PR adds the async handler to finish the operation once the active page is set, instead of failing the entire story directly.
Context: #38979
=> 🐛 Fix active page race condition in Web Story

examples/amp-story/amp-story-shopping.html, examples/amp-story/attachment.html, extensions/amp-story-page-attachment/0.1/amp-story-open-page-attachment.js, extensions/amp-story-page-attachment/0.1/test/test-amp-story-open-page-attachment.js
Also manually add page-attachment script to the template htmls, which is to avoid the script installation errors that only happen in local dev environment.
Context: #39299
=> 🐛 Disallow empty CTA string in page attachment

build-system/release-workflows/upload-release.js, package-lock.json, package.json
We're getting [repeated failures](https://app.circleci.com/pipelines/github/ampproject/amphtml?branch=nightly) for the job that uploads nightly builds to Cloudflare's R2. This PR updates the S3 client library we use and increases the number of attempts from (the default) 3 to 7 attempts, because I don't have better ideas.
Tag-along change: change how we print progress, because CircleCI doesn't display background colours
This PR won't affect the currently failing nightly, but hopefully it'll work tomorrow!
=> 🏗 Attempt to execute the upload command to R2 up to seven times

test/integration/test-boilerplates.js, testing/helpers/service.js
Per https://developer.mozilla.org/en-US/docs/Web/CSS/animation-duration "For time-based animations, auto is equivalent to a value of 0s".
I added an option to add "auto" as one of the initial value states for `animation-duration`. It seems this is implemented differently across browsers which is why there is a helper function for this check.
Fixes https://github.com/ampproject/amphtml/issues/39152
---
Revert "Disable broken test `should show the body in boilerplate test` (#39151)"
This reverts commit 927c884cb6b5634e556668652c37805af740c7cc.
=> Turn back on the "amp boilerplate animation test" for Microsoft Edge

src/web-worker/amp-worker.js
This causes a "Cannot access 'policy' before initialization bug in modern JS syntax. This does not break with `var` because of function scoping.
=> Fix variable decalaration bug

src/service/extension-script.js, src/web-worker/amp-worker.js
Found this issue while debugging https://github.com/ampproject/amphtml/issues/36253
In local dev configuration, amp-worker won't even work because the regex is stringent.
=> Allowlist localhost for amp-worker and extensions in localDev

build-system/release-workflows/cut-nightly.js
This blocks renovatebot's PR #36642 from being submitted. Instead of putting this workaround in that branch (which stops it from automatically updating itself) I'm splitting it into this separate PR
=> 🏗 Workaround for typing issues in cut-nightly.js

extensions/amp-carousel/0.1/slidescroll.js
Fixes  https://github.com/ampproject/amphtml/issues/36253
Root cause is that touch events are HIGH trust, and scroll-caused transitions are LOW trust. This would change them to HIGH trust so that it is able to trigger amp-state update.
=> 🐛 Set slide events to high trust so that it can trigger amp-state update

ads/vendors/dable.js, ads/vendors/dable.md
Add new option for special case
Add backup options to deliver accurate data
The original PR won't trigger the build on Circle. https://github.com/ampproject/amphtml/pull/39433
=> ✨ ENHANCE: expand widgetOpts/logOpts

.circleci/config.yml
Node v18.18.0 broke the build, while we investigate a fix this PR pins Node.JS to the last version that this repo works with
* [Last passing build on main](https://app.circleci.com/pipelines/github/ampproject/amphtml/29172/workflows/77e14143-a503-4bdb-baec-5876506ad33f), when `nvm install --lts` installed v18.17.1
* [First failing build on main](https://app.circleci.com/pipelines/github/ampproject/amphtml/29178/workflows/9a7a34c2-c4d1-407a-89a5-d023c52263e2), when `nvm install --lts` installed v18.18.0
=> ⏪ Temporarily pin Node to v18.17.1

ads/google/a4a/test/test-utils.js, ads/google/a4a/utils.js, extensions/amp-a4a/0.1/secure-frame.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, src/inabox/amp-inabox.js
Chrome has removed the origin trial token requirement for enabling privacy sandbox, therefore it won't be necessary to send these token any more.
=> Remove privacy sandbox origin trial

build-system/tasks/unit.js, package-lock.json, package.json
We often see unit tests failing on CircleCI on `main` with a silent timeout (recent examples: [[1]](https://app.circleci.com/pipelines/github/ampproject/amphtml/29231/workflows/19e044c0-d243-42c6-a3cb-4cb5d39ede9c/jobs/624647) [[2]](https://app.circleci.com/pipelines/github/ampproject/amphtml/29221/workflows/f2a3b97d-04d1-4ea1-a318-e17d0f3b8539/jobs/624397) [[3]](https://app.circleci.com/pipelines/github/ampproject/amphtml/29206/workflows/ab2a730f-fe82-4b88-a053-866c903f3aff/jobs/623971)), _after_ they pass on the related PR. I can't seem to be able to reproduce these failures directly on the PR, so I want to add this debugging statement that will automatically fail the PR if the unit test is running for longer than 7 minutes (these usually resolve within 4 minutes, so I think it's a safe …
=> ✅ Temporary debugging output for unit tests running on CircleCI

build-system/tasks/visual-diff/index.js
Percy recently introduced changes that make it so that missing snapshots now trigger an error. When we create a build on Percy we either just generate a build with a single, blank page (e.g., for docs-only changes), or we generate a build with all the visual tests _except_ the blank page - this means that now every PR fails on Percy (blank page PRs are missing 146 snapshots, and regular PRs are missing 1 snapshot)
This PR makes two changes:
1. It sets `PERCY_PARTIAL_BUILD` (introduced [a while ago](https://docs.percy.io/docs/partial-builds), but wasn't required until recently) on blank page-only PRs
2. Generates the blank page snapshot on full PRs too
=> 🏗 Fix for Percy changes on handling missing snapshots

extensions/amp-consent/0.1/amp-consent.js, extensions/amp-consent/0.1/consent-info.js, extensions/amp-consent/0.1/consent-policy-manager.js, extensions/amp-consent/0.1/consent-state-manager.js, extensions/amp-consent/0.1/consent-ui.js, extensions/amp-consent/0.1/tcf-api-command-manager.js, extensions/amp-consent/0.1/test/test-amp-consent.js, extensions/amp-consent/0.1/test/test-consent-info.js, extensions/amp-consent/0.1/test/test-consent-policy-manager.js, extensions/amp-consent/0.1/test/test-consent-state-manager.js, extensions/amp-consent/0.1/test/test-tcf-api-command-manager.js, extensions/amp-consent/amp-consent.md, extensions/amp-consent/integrating-consent.md
The proposal is for the CMP to declare the tcf policy version (related to the GVL they are using).
to preserve the current behavior and as a fallback the tcf policy version will be 2. (As it's used in tcf v2.0). This will guarantee a free deploy of that thing in amp. And CMP can progressively update this without breaking changes.
closes #39410
=> ✨ I2I: <amp-consent> Allow receiving TCF 2.2 consent string via TCF postmessage API (new TCF policy version support)

build-system/tasks/e2e/describes-e2e.js
e2e tests use Selenium to control the testing browser, whereas unit/integration tests use Karma. Karma overrides which Chrome binary to use for tests when the `CHROME_BIN` env variable is set, so this PR brings e2e tests on par, which would make it easier for us to test breakages on browser version changes
e.g., I can now run `CHROME_BIN=$HOME/Downloads/chrome-stable-114/opt/google/chrome/google-chrome amp e2e --nobuild --headless --minified` when debugging e2e tests that break between Chrome 113 and 114
=> 🏗 Override Chrome binary in e2e tests with `CHROME_BIN` env variable

extensions/amp-analytics/0.1/test/test-transport.js, extensions/amp-analytics/0.1/transport.js, src/builtins/amp-pixel/amp-pixel.js, src/pixel.js, test/unit/builtins/test-amp-pixel.js
Fixes https://github.com/ampproject/amphtml/issues/39284, using the extension element for retrieving the proper service instead of forcing window.document. Same approach followed by most of other extensions.
=> 🐛 amp-analytics failing in some cases when using amp shadow

extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js
`scrollLeft` doesn't do what the original test authors think it does - they use it as a way to tell how far an element is inside its scrolling container, but it's really only relevant to the container itself - scrollLeft tells us how many pixels the container's view itself has been scrolled. Since we perform the slide transitions using CSS animation tricks (at least, that's been my understanding), these test don't actually work
I'm not sure why they passed until Chrome 113, but they've been failing starting with 114 (blocking #39081) - this change in how we perform the tests fixes these incorrect assumptions, and make these tests pass on versions 114 and up.
=> ❄️ Fix amp-carousel e2e tests to use the slides' bounding rect instead of scrollLeft

3p/frame.max.html
In order to remove the possibility of generating arbitrary HTML code using the URL argument.
=> 🐛 frame.html: generate the script tag securely

.circleci/config.yml
This shouldn't have any positive or negative effect on CI performance, but [on occasion a network hiccup causes a build to fail](https://app.circleci.com/pipelines/github/ampproject/amphtml/29413/workflows/4e17dd84-5c01-4be9-906c-ae5946c3c382/jobs/629561#:~:text=0s-,Install%20Node.js%20lts,-Explain%20this%20error) when downloading Node with nvm. This PR caches the nvm cache inside CircleCI so we can reuse it between builds.
Since the LTS version of Node changes once every few weeks, this is a pretty stable cache key!
=> 🏗 Save nvm cache in CircleCI's cache

.circleci/config.yml
Because of #39510 
I've reworked the way we save/restore the nvm cache and determine which version to install: previously CircleCI would simply restore the latest cached version, which is not necessarily what we want, because that means the cache key that includes v18.18.2 was overtaken by v20.9.0, even once this PR is merged. With this PR, the major version we fix to becomes part of the cache key. Once we switch to back to 'lts' it'll simply continue to increment the cache key every time a new version comes out, but if we have to revert back to a fixed number again (like here) we can change the value of the `node-version` parameter and the cache will work out of the box
I also noticed that by default nvm tries to install Node twice - first immediately after nvm is unpacked it installs a …
=> 🏗 Temporarily pin Node to v18.* and fix nvm cache

build-system/test-configs/dep-check-config.js, examples/connatix-player.amp.html, extensions/amp-connatix-player/0.1/amp-connatix-player.js, extensions/amp-connatix-player/0.1/test/validator-amp-connatix-player.html, extensions/amp-connatix-player/0.1/test/validator-amp-connatix-player.out, extensions/amp-connatix-player/amp-connatix-player.md, extensions/amp-connatix-player/validator-amp-connatix-player.protoascii
The purpose of this PR is to add support for the VideoInterface API, as a means to enable the `dock` attribute to be used in conjunction with the Connatix Player AMP component.
=> ✨ Add VideoInterface support to Connatix Player component

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Does not appear to be breaking anything. INP is also not appearing in Google-specific dashboards. Therefore we should be able to safely launch it to 100%.
=> Launch INP metrics on amp-analytics

docs/spec/amp-errors.md, src/error-reporting.js, test/unit/test-error-reporting.js
To support error reporting for different CDNs
=> 🏗 Add `cdn` to error reporting function, and update amp-errors.md

extensions/amp-social-share/1.0/test-e2e/test-amp-social-share.js
This test often fails due to taking longer than the default timeout. Increasing the timeout to 5,000ms should hopefully fix it
=> ❄️ Increase timeout for e2e test `amp-social-share > clicking > opens a new window on click`

SECURITY.md
Resolves https://github.com/ampproject/amphtml/issues/39712
This PR adds a suggestion of a Security Policy for the repository.
Please mind that the link suggested for reporting vulnerabilities uses GitHub's Security Advisories [report vulnerability](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability) feature. You would need to enable the feature for it to work.
Let me know if this security policy makes sense for the repository or how can we work it better to reflect how team would like to handle vulnerability reports.
=> ✨ Add a Security Policy

src/service/real-time-config/callout-vendors.js
Hello, 
We are improving our inventory management and will rely on uid and pid query parameters in the future. But we are still needing the old query parameters during the transition. 
Please could you review this ?
Thanks !
=> ✨ Criteo: Add uid and pid macro to amp endpoint

build-system/release-tagger/index.js, build-system/release-tagger/make-release.js, build-system/release-tagger/utils.js, build-system/task-runner/amp-task-runner.js, build-system/tasks/unit.js, package-lock.json, package.json, src/preact/component/types.d.ts
This PR updates code devDependencies that require non-trivial changes to the codebase:
* `dedent` - explicitly requires that we import its `default`
* `commander` - requires that we import `Program` instead of the default export
* `typescript` - requires a minor type definition change in `src/preact/component/types.d.ts`
This PR also removes the `why-is-node-running` package and the debugging code that used it, which should fix the broken `amp --help` command
=> 🏗 Partial updates for core devDependencies

extensions/amp-connatix-player/0.1/amp-connatix-player.js
The current PR fixes two issues:
1. Player could not be muted/unmuted through docking UI controls if user hadn't interacted with the player while it was embedded. This was solved by using the `addUnsafeAllowAutoplay` method.
2. Desyncing between the player volume and the docking UI mute/unmute button icon. This was solved by only updating mute/unmute status after the volumeChanged command has been received.
=> 🐛 [Connatix Player] - Fix player not unmuting while docking

.circleci/config.yml
I've noticed that a lot of times jobs fail because of the `Install NPM packages` step due to random network hiccups. We run this step on each CircleCI job (so a total of ~30 times per PR!) - this isn't really necessary because we can just run `npm ci` once during the init job, cache the resulting `node_modules/` directory, and restore that cache at the start of every subsequent job. For PRs that don't change package-lock.json (which is most of the human-written PRs), we can skip the installation step entirely and just restore the cache.
This means that any PR that changes package-lock.json will take about 50 seconds longer to go through the initializing step, but then all PRs (whether they change package-lock.json or not) shortens every other job by about 40 seconds! That shortens the the …
=> 🏗 Cache node_modules/ in between CircleCI jobs

examples/amp-story/attachment.html, extensions/amp-list/0.1/amp-list.js
For amp-list embedded in the amp-story-page-attachment, because the attachment is initially in nodisplay mode, the layoutCallback of all amp-img elements are not called at all, even after the attachment is opened and amp-list fetches results and inserted built amp-img(from templates) into DOM. Force call layoutCallback to render images.
Fix #39707 and #33241.
=> Enable amp-img to be rendered inside amp-list in story page attachment

examples/amp-story/player.html, src/amp-story-player/amp-story-player-impl.js
Context:
In Firefox, when player.show() is called, the transition animation of iframes(that host stories) cause the final position to be wrong. More specifically, it only happens when you show the 2nd story(not any other stories), where after the animation the story with index 1 is at the position 0, and all stories with index n is at the position n-1. Basically, the entire array of stories shift left by one.
This bug only happens in Firefox. I agree with Corey that focus() and transition animation running at the same time somehow cause the bug. This PR fixes it by first waiting for the transition animation to end, and then call focus() to focus on the current story's iframe element.
#38634
=> Don't focus on the current story until the animation ends

.circleci/config.yml, build-system/tasks/e2e/.npmrc, build-system/tasks/visual-diff/.npmrc, build-system/tasks/visual-diff/browser.js, build-system/tasks/visual-diff/index.js, test/integration/test-video-players.js
- Update the `circleci/browser-tools` Orb to v1.4.8
- Add an .npmrc file to e2e tasks with `chromedriver_skip_download=true`, since we're installing it with the Orb (and it currently fails for the same reason that the Orb's previous version failed - the download URL changed)
- Use the Chrome version installed by CircleCI in `amp visual-diff`
- Disabled a flaky test
=> 🏗 Fix for recent changes to Chromedriver installation on CircleCI

.circleci/config.yml
I'm thinking that it doesn't make sense to cache the `.git` directory for PRs, since they constantly change but only by a small amount compared to their branch-off point out of `main`
This PR makes it so that the `Save .git Cache` will only execute in the initializing jobs (1 for Linux, 1 for MacOS) on push builds and only on the `main` branch. A quick overview of the data shows that **this saves between 15-30s of init time** on CI jobs for PR!
=> 🏗 🚀 Only cache the .git directory in CircleCI for push jobs on the `main` branch

build-system/tasks/runtime-test/runtime-test-base.js
This PR reduces the full name of tests to only be the text in the `it('...')` spec, and adds delimiters to different `describes` texts for the `classname`. Also removes empty strings in the middle (which happens as a side-effect of how we implemented some of the test runners)
| Before | After |
| --- | --- |
| ![image](https://github.com/ampproject/amphtml/assets/1839738/3a76f1e1-71c7-4c77-9b6a-6171c1ea230a) | ![image](https://github.com/ampproject/amphtml/assets/1839738/47cae073-3c28-4a88-afb8-d26468afe323) |
| ![image](https://github.com/ampproject/amphtml/assets/1839738/fa10b225-d0fb-4902-9b32-ae27ccef3597) | ![image](https://github.com/ampproject/amphtml/assets/1839738/8ead6fc9-5577-4006-a33c-2648c21f235d) |
=> 🏗 Nicer format for test names when reporting to CircleCI

.circleci/config.yml
Example of where this fails as of now: https://app.circleci.com/pipelines/github/ampproject/amphtml/30407/workflows/7b9680ee-501d-4f56-a871-7682b9781fd3/jobs/653480
Example of how this PR fixes this: https://app.circleci.com/pipelines/github/ampproject/amphtml/30408/workflows/7b455776-e6aa-4cd4-af41-dc13937836f0/jobs/653511
=> 🏗🐛 Install Chrome in CircleCI `Module 3p Build (Test)` job, for empty visual-diff edge-case

extensions/amp-analytics/0.1/test/test-events.js, extensions/amp-base-carousel/0.1/test-e2e/test-carousel.js, extensions/amp-consent/0.1/test/test-amp-consent.js
- Attempt at deflaking amp-consent tests
- Disabled flaky amp-analytics test
- Disabled flaky amp-base-carousel test
=> ❄️ Flaky tests

src/video-iframe-integration.js, test/unit/test-video-iframe-integration.js
Fixes https://github.com/ampproject/amphtml/issues/39676
For unknown reason, iOS refuses to send `canplay` event when the video player is in ready state.
https://html.spec.whatwg.org/multipage/media.html#mediaevents This appears to be contrary to the spec, which state that it should do so when `readyState` becomes >=3, which was AMP's implementation.
Therefore, we have to apply this nasty patch to make it work. Since `platform service` is not available here, I do user agent check directly instead of using `isIos()` function.
=> 🐛 Fix videojs amp-video-iframe intergration on ios

build-system/tasks/check-links.js, extensions/amp-analytics/analytics-vendors-list.md, package-lock.json, package.json
Efforts have been taken to find the best replacement URLs. Had to merge this since it blocks https://github.com/ampproject/amphtml/pull/39907 from merging.
Furthermore, I added the user agent to make some servers happy. I updated the version of markdown-link-check to fix some weird errors.
=> Fix deadlinks in the analytics-vendors-list, and add user agent

src/service/real-time-config/callout-vendors.js
Related to https://github.com/ampproject/amphtml/issues/38628
Adding the Global Privacy Protocol Section ID (GPP_SID) to the prebidrubicon RTC callout query string. It would make most sense to merge this along with or after support for CONSENT_METADATA(gppSectionId)
thanks
=> ✨ callout-vendors: add gpp_sid to rubicon

extensions/amp-youtube/0.1/amp-youtube.js
I just analyzed the resources which are loaded in a YouTube embed and they include:
* `fonts.gstatic.com` (for the fonts used in the title)
* `yt3.ggpht.com` (for the channel logo)
* `i.ytimg.com` (for the poster image)
* `www.youtube.com` (for JS and CSS assets)
* `www.gstatic.com` (for more JS assets)
Notably, `s.ytimg.com` is _not_ among the domains that resources are loaded from, although it is still being preconnected to:
https://github.com/ampproject/amphtml/blob/dccbba6692d322f9843c856bd21d9dcc693291a1/extensions/amp-youtube/0.1/amp-youtube.js#L117-L121
I suggest removing this preconnect and instead replace it with a preconnect to `fonts.gstatic.com` since it is used to render the title text which is the actual LCP element (since the poster background image is excluded based on the …
=> 🐛 Update preconnects in amp-youtube component

.vscode/settings.json
A few people are having issues since VSCode does not automatically insert a newline at EOF. This change intends to set it for project.
=> VS code config: Insert EOF newline

extensions/amp-consent/0.1/amp-consent.js
Added basic title to internal iframe of the AMP consent component. Following same logic applied in https://github.com/ampproject/amphtml/pull/30834.
=> fix: add missing title in amp-consent iframe element

extensions/amp-ad-network-smartadserver-impl/0.1/amp-ad-network-smartadserver-impl.js, extensions/amp-ad-network-smartadserver-impl/0.1/test/test-amp-ad-network-smartadserver-impl.js
=> ✨[amp-ad smartadserver] Include consent data in iframe name

src/error-reporting.js, test/unit/test-error-reporting.js
* Reduce error reporting threshold
* Fix incorrect comparison for non-AMP JS threshold (See https://github.com/ampproject/amphtml/pull/39975/files#diff-4c1872815c54699a5124f8d6e482c787991ead59f538c696845d18654ce5ef1fR337)
* ~~Asyncify various functions in the error-reporting.js file~~ _(dropped this change; it causes a big spike in bundle sizes for some reason)_
* Replace magic numbers with consts
=> 🏗 Simplify error reporting thresholds

build-system/tasks/visual-diff/browser.js
`headless: !!argv.dev` means that visual diffs run in headless mode when we pass `--dev`, and with full UI when there's no `--dev` in the args list. This is the exact opposite of what we want 😅
=> 🏗🐛 Fix incorrect condition for `headless` mode in visual-diff task

.circleci/config.yml
Per https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718
Also updates `xcode` to 15.3.0 (Safari 17), replaces our custom `Enable Safari Automation` step with the recommended `macos` Orb's step, and installs Rosetta to enable compatibility with the new CPU.
The existing resource class we're using (`macos.x86.medium.gen2`) is being deprecated in June.
=> 🏗 Replace CircleCI's MacOS resource class to `macos.m1.medium.gen1`

validator/js/gulpjs/package-lock.json, validator/js/gulpjs/package.json
It is used by amp.dev and we want the latest change on the validator.
Also fixes an issue where `kleur` is used on index.js but not declared, and it is causing downstream issues.
=> Update gulp-amphtml-validator to use latest validator

ads/vendors/adskeeper.js, ads/vendors/adskeeper.md, examples/amp-ad/ads.amp.html
We adding new attribute "website" to adskeeper ad component. It could be used instead legacy attributes "publisher" and "container" (they are still supported, but are not encouraged to use)
=> ✨ Adskeeper website attribute

ads/_a4a-config.js, ads/vendors/idealmedia.js, ads/vendors/idealmedia.md, ads/vendors/mgid.js, ads/vendors/mgid.md, examples/amp-ad/ads.amp.esm.html, examples/amp-ad/ads.amp.html
We adding new attribute "website" to mgid and idealmedia ad components. It could be used instead legacy attributes "publisher" and "container" (they are still supported, but are not encouraged to use)
=> ✨ Add new attribute to mgid and idealmedia ad components

extensions/amp-analytics/analytics-vendors-list.md
It is needed because the build is blocked by the deadlink check otherwise.
=> Fix analytics doc deadlink

ads/vendors/yektanet.js
Yektant company wants to make changes in its main script that these changes should not be applied in the Amp script, that's why the content of the Amp script was made available to the Amphtml project through a new address.
=> ✨Update yektanet banner script address

examples/brid-player.amp.html, extensions/amp-brid-player/0.1/amp-brid-player.js, extensions/amp-brid-player/0.1/test/test-amp-brid-player.js, extensions/amp-brid-player/validator-amp-brid-player.protoascii
Closes #40130
Talked to team and decided to go other way around then the issue suggests.
=> ✨ Add TargetVideo Alias To Brid AMP Player

test/integration/test-video-players-helper.js, test/integration/test-video-players.js
Turns out it's because amp-youtube integration tests are failing on circle only. It works fine locally. Suspect it is some network issue on circle or Youtube actively blocking access from a cloud machine. https://github.com/ampproject/amphtml/issues/40181
This PR reenables relevant tests, but disables amp-youtube
Fixes #39857
=> Reenable flaky video test

extensions/amp-social-share/1.0/test-e2e/test-amp-social-share.js
Looks like a change in tumblr is breaking our tests on main. This is a quick fix that should be more forward-compatible: https://app.circleci.com/pipelines/github/ampproject/amphtml/31723/workflows/62b2cc4d-c419-4caf-950a-5831b6bbc9e4/jobs/695279
=> ❄️ Fix flaky test `[v1.0] amp-social-share > chrome > Viewer environment > clicking tabs between multiple social-shares and opens on "enter" keypress`

extensions/amp-ad-network-mgid-impl/0.1/amp-ad-network-mgid-impl.js
We no longer need to call amp-pixel with https://c.mgid.com/pv/, so it should be removed.
=> 🚮 Stop loading pv endpoint from MGID AMP stories

extensions/amp-skimlinks/0.1/test/test-affiliate-link-resolver.js, extensions/amp-story-player/0.1/test/test-e2e/test-amp-story-player.js, extensions/amp-video/0.1/test/test-flexible-bitrate.js, testing/fake-dom.js
This resolves some of the url issues we've been dealing with on the chromdriver 131 upgrade
there seems to have been a change between chrome 119 to chrome 131 on how the baseURI is inherited. We can force the baseURI of the FakeWindow by appending a `base` element on construction in fake-dom.js
See #40214
=> append a `base` element to force the baseURI of the FakeWindow

extensions/amp-ad-exit/0.1/test-e2e/test-amp-ad-exit.js
The reason it fails is that we use performance events to find out requests being made, and that it fails when being within a cross domain iframe (but works within a friendly iframe). No ideas why it worked before though. This PR changes to verify that the request is sent using request bank directly.
=> Fix chrome 131 amp-ad-exit test

test/unit/builtins/test-amp-pixel.js
```
export function isAttributionReportingAllowed(doc) {
return doc.featurePolicy?.allowedFeatures().includes('attribution-reporting');
}
```
Because isAttributionReportingAllowed is defined by whether the browser supports the attribution reporting api, with the new Chrome it flips to true. This PR fixes the test by no longer assuming it is off by default and forcing this test to test as if it is not supported. The supported case already exists.
=> ✅ Fix amp-pixel attribution reporting test failure

3p/environment.js
As a fix to the timeout/interval space conflict problem: https://github.com/ampproject/amphtml/issues/40235
This does not guarantee that there is no conflict, but at least it will become highly unlikely. Because the way we implement setInterval, we are not able to use the js engine's namespace. The only way to resolve this is to we also generate the ids for timeouts, which is a bit more involved.
=> Quick fix to the interval/timeout namespace conflict

extensions/amp-bind/amp-bind.md
The `src` attribute is banned in the email spec.
/to @powerivq 
/cc @missingtrailingcomma
=> 📖 Filter out mention of amp-state `src` for email

ads/google/a4a/cookie-utils.js, ads/google/a4a/test/test-cookie-utils.js, build-system/test-configs/dep-check-config.js, extensions/amp-a4a/0.1/amp-a4a.js, extensions/amp-a4a/0.1/test/test-amp-a4a-cookies.js, extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js, src/cookies.js, test/unit/test-cookies.js
Addresses #40248.
Implements both cookie writing and reading components described in the linked I2I. In particular, we will set the specified cookies on the ad response HTTP header, and add those cookies to ad requests when available. We also add here some ads utility functions for verifying user consent for cookies, and some global cookie utility functions for checking whether setting cookies is allowed.
This change on its own is mostly a no-op, as serving is not yet setup to send to the new HTTP cookie header.
=> ✨ Google Ad Manager Publisher first-party IDs

3p/ampcontext.js, test/unit/test-amp-context.js
The `setupMetadata_`  is currently passed in a context object that comes from ads safeframe code. The current code assumes that the context object is nested inside the passed in parameter which causes a parsing error that is silently caught by the wrapping top level try/catch in https://github.com/ampproject/amphtml/blob/6a610ba7734d8bfced751644876e9f72e9108725/3p/ampcontext-lib.js#L19-L27
=> Bugfix: Fix AMP_CONTEXT_DATA parsing

extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
Fixes an oversight in https://github.com/ampproject/amphtml/pull/40249.
=> Fix issue where GFP cookie is not being attached to AdSense ad requests.

extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js, extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
Fixes an issue wherein `this.iframe` may be destroyed by the time we attempt to process a postMessage from it resulting in a null access error.
=> 🐛 Add defensive check around ad iframe existence before checking contentWindow.

ads/google/a4a/cookie-utils.js
Current behavior will attempt to set a cookie value indiscriminately, which may throw an error on some domains. This fix adds a `canSetCookie` check, which will ensure setting cookie is safe and will not result in a thrown error, before attempting to set cookies.
=> 🐛 Add canSetCookie check before attempting to set cookies

build-system/global-configs/canary-config.json, build-system/global-configs/prod-config.json
Related to: https://github.com/ampproject/amphtml/issues/40183
This PR will allow opting into the experiment `story-ad-allow-fullbleed` (https://github.com/ampproject/amphtml/pull/40264) via the `<meta>` tag:
`<meta name="amp-experiments-opt-in" content="story-ad-allow-fullbleed">`
=> 🧪 Allow doc opt in for `story-ad-allow-fullbleed`

extensions/amp-bind/amp-bind.md
https://amp.dev/documentation/components/email/amp-bind
deep-merges links to a bad link. This PR fixes that.
=> Fix setstate link for amp-bind

.github/create_validator_rollup_issue.md, .github/workflows/request-validator-rollup.yml
This PR adds a GitHub Action that will notify @ampproject/wg-caching when a validator change has been merged to `main`, and create an issue to roll it up on the AMP cache
Example of these can be found on my fork: https://github.com/danielrozenberg/amphtml/actions/workflows/request-validator-rollup.yml
=> 🏗 Automatically create an issue to request a validator rollup

extensions/amp-slikeplayer/0.1/amp-slikeplayer.js
- Renamed SlEvent to CleoEvent and added new ad-related events.
- Implemented viewportCallback to play/pause based on visibility.
- Updated redispatch logic to handle new events appropriately.
=> Refactor event handling in amp-slikeplayer

test/integration/test-amp-bind.js
Replacing the fake remote image URLs with inlined `data:` URLs seems to do the trick here.
Tag-along changes:
- Reduced the timeout for these tests significantly; they pass now without the need for an extended timeout
- Rewrote all the tests to be async and to pass/fail via awaiting Promises, instead of using generator functions which are not widely used in our codebase
=> ❄️ Fix flaky async integration tests for `amp-bind`
